### ISSUE TITLE
[Bug]: i get this error when i add plugin to my backend app

### ISSUE THREAD

**Issue by trinhcongduc** [medusajs/medusa#10038]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "medusa-plugin-contentful": "^1.2.12",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v21.7.3

### Database and its version

17.0

### Operating system name and version

MacOS

### What happended?

I always get type of this issue when i trying to add plugin on my application . 
<img width="1384" alt="image" src="https://github.com/user-attachments/assets/b1916828-151d-4ca6-bfe7-fc769d419703">

Even i do same config on the guideline document 
<img width="1063" alt="image" src="https://github.com/user-attachments/assets/9fe9faae-597b-4f67-83f8-e8dda72760d6">

### Expected behavior

Run well application 

### Actual behavior

App crash and stop because of adding plugin error

### Link to reproduction repo

https://github.com/trinhcongduc/medusajs-demo

**Comment by trinhcongduc** [comment]
i just realized a non official way to pass the error, it seems crazy  : 
<img width="731" alt="image" src="https://github.com/user-attachments/assets/da8f0f3f-4d1d-47ee-83db-f24179e5296a">

**Comment by olivermrbl** [comment]
@trinhcongduc, `plugins` are not officially supported in Medusa v2.0.0 yet, so the experience around registering and using them is likely to have errors. We expect to officially support plugins sometime early next year. I'll close this for now, as we are tracking this internally already.
