### ISSUE TITLE
[Feature]: Google Authorization - Register method.

### ISSUE THREAD

**Issue by Furman1331** [medusajs/medusa#10035]
### Package.json file

```JSON
{
  "name": "pritty-prints-medusa",
  "version": "0.0.1",
  "description": "Pritty Prints Store CMS build with Medusa",
  "author": "Michał Furmańczak (michalfurmanczak@gmail.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "^2.0.3",
    "@medusajs/cli": "^2.0.3",
    "@medusajs/framework": "^2.0.3",
    "@medusajs/medusa": "^2.0.3",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v20.5.1

### Database and its version

Postgres

### Operating system name and version

MacOS

### Browser name

Brave

### What happended?

Google Authorization Provider does not support method "register", right now to create an account throught Google Provider we send callback method to check is user exist in database. If does not we need to create user by "api/store/customers". But before that we need to collect e-mail address from user by form.

![image](https://github.com/user-attachments/assets/39875ff5-0175-4e85-a864-3357816cc185)

To stay convenient I suggest to add support for register method, which right now is empty.

I'm curious why it was not done from the beginning, are there any contraindications?

Just want to make sure that I can a upload PR for that feature without wasting time.

### Expected behavior

Register method does create user in database and authorize. Make it convenient

### Actual behavior

Google Provider register method does not support.

### Link to reproduction repo

...

**Comment by Furman1331** [comment]
@sradevski, I ping you because, saw that you've done this provider.

**Comment by sradevski** [comment]
@Furman1331 both registration and authentication happens through the `authenticate` method for Oauth providers, `register` is only for auth methods such as email/password. Here are the docs: https://docs.medusajs.com/resources/commerce-modules/auth/auth-providers/google#main

**Comment by Furman1331** [comment]
Yeah, I read the docs and checking the code, but it's non sense to make user fill form with e-mail when we've got it from google provider. We can use register method to make it more smooth and convenient, like i said above.

In Google OAuth we can get the data from google more then once, so in register method we can get email and register customer / user in database without filling the form, and automate this process.

This is, after all, why we are implementing, such solutions.

**Comment by sradevski** [comment]
I think the only missing piece is not storing the email in the user metadata here: https://github.com/medusajs/medusa/blob/9e40f34ba8ffb70c25fdc8a485afaa2f215eae96/packages/modules/providers/auth-google/src/services/google.ts#L146C11-L146C23

You can then use the user metadata to pre-populate whatever you need from the auth provider.

**Comment by Furman1331** [comment]
Yeah but what we can do with this e-mail stored in provider-identity? To create new customer we need to pass e-mail address in request, if we add such an email to the metadata, it will do us no good unless we return it to the frontend, which in turn may cause a security vulnerability

Right now example decoded token from response is:
`
actor_id: ""
actor_type: "customer"
app_metadata: {}
auth_identity_id: "authid_00000000"
exp: 1731505363
iat: 1731418963
`

Look on image bellow, how it could look. 
![image](https://github.com/user-attachments/assets/b94c468f-6c47-481b-9db8-4f38c874dfdd)

**Comment by sradevski** [comment]
The user_metadata on the provider identity doesn't carry anything sensitive, so it can be returned to the FE if needed.

If you were to eg. create a customer in the `register` method, then you are mixing two separate concerns - authentication vs. application roles, and there can be many, depending on the application.

If you need the provider identities, you can create an endpoint to get them in your app so you can prepopulate some email field you have

**Comment by SalahAdDin** [comment]
> Yeah but what we can do with this e-mail stored in provider-identity? To create new customer we need to pass e-mail address in request, if we add such an email to the metadata, it will do us no good unless we return it to the frontend, which in turn may cause a security vulnerability
> 
> Right now example decoded token from response is: `actor_id: "" actor_type: "customer" app_metadata: {} auth_identity_id: "authid_00000000" exp: 1731505363 iat: 1731418963`
> 
> Look on image bellow, how it could look. ![image](https://private-user-images.githubusercontent.com/72356359/385311633-b94c468f-6c47-481b-9db8-4f38c874dfdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NDQ1ODQsIm5iZiI6MTczMTQ0NDI4NCwicGF0aCI6Ii83MjM1NjM1OS8zODUzMTE2MzMtYjk0YzQ2OGYtNmM0Ny00ODFiLTlkYjgtNGYzOGM4NzRkZmRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDIwNDQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhNDU2MTQ1NjRlMGM0ODY0YjRmYjhmNzg4ZmY5OGU4ZWExNTU4MDE0NjIzYWM4MzQzNWUyZjM5ZDIxZTM5ZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.y-6BgrXOc_P7i-nxa5BPvY6QkzxSpMFoxVVgtWNUmCY)

how did you create such image? looks awesome!

**Comment by Furman1331** [comment]
> > Yeah but what we can do with this e-mail stored in provider-identity? To create new customer we need to pass e-mail address in request, if we add such an email to the metadata, it will do us no good unless we return it to the frontend, which in turn may cause a security vulnerability
> > Right now example decoded token from response is: `actor_id: "" actor_type: "customer" app_metadata: {} auth_identity_id: "authid_00000000" exp: 1731505363 iat: 1731418963`
> > Look on image bellow, how it could look. ![image](https://private-user-images.githubusercontent.com/72356359/385311633-b94c468f-6c47-481b-9db8-4f38c874dfdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NDQ1ODQsIm5iZiI6MTczMTQ0NDI4NCwicGF0aCI6Ii83MjM1NjM1OS8zODUzMTE2MzMtYjk0YzQ2OGYtNmM0Ny00ODFiLTlkYjgtNGYzOGM4NzRkZmRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDIwNDQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhNDU2MTQ1NjRlMGM0ODY0YjRmYjhmNzg4ZmY5OGU4ZWExNTU4MDE0NjIzYWM4MzQzNWUyZjM5ZDIxZTM5ZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.y-6BgrXOc_P7i-nxa5BPvY6QkzxSpMFoxVVgtWNUmCY)
> 
> how did you create such image? looks awesome!

You mean the screenshot, I have just add some text?

**Comment by Furman1331** [comment]
So @sradevski, am I understand it correctly that after approving this change, the easiest way to create customer with google email is to, collect provider-identity from the database into the frontend, accordint to the ID we received in the response. And send an email with that address to create the customer, right?

If this is true, we need to update the documentation.

**Comment by sradevski** [comment]
@Furman1331 Yes exactly, the provider identities can be listed based on `req.auth_context.auth_identity_id`, and then you can use whatever data you have there to populate the "create customer" form.

Please open a new Issue/PR for the docs update, as it's easier for us to triage it.

**Comment by Furman1331** [comment]
I'll do it soon, we can close this issue.

**Comment by Furman1331** [comment]
I've tested this today to see if i can get provider-identity and i cannot find method in AuthService to find provider-identity by auth_identity_id, second problem is auth_identity_id has no flag in postgres that it should be assign only to one provider-identity. 

Also while google create provider-identity, there is also created auth-identity without any content, also there is something wrong with #10049 which connects to this task.

**Comment by jha-r** [comment]
@Furman1331 did you find how to get the email from google after authentication to create that user? appreciate any help on this. Thanks

**Comment by SalahAdDin** [comment]
> I've tested this today to see if i can get provider-identity and i cannot find method in AuthService to find provider-identity by auth_identity_id, second problem is auth_identity_id has no flag in postgres that it should be assign only to one provider-identity.
> 
> Also while google create provider-identity, there is also created auth-identity without any content, also there is something wrong with #10049 which connects to this task.

How is it going on?

**Comment by Furman1331** [comment]
I didn't found a solution for that situation expect asking user for e-mail so I gave up after some time, because it should be convenient for user.

**Comment by SalahAdDin** [comment]
> I didn't found a solution for that situation expect asking user for e-mail so I gave up after some time, because it should be convenient for user.

This issue should be opened again then!

**Comment by Furman1331** [comment]
I test it again and right now, you get back auth-identity model so you can collect data about user from there. 

I'm closing.

**Comment by cellthium-dev** [comment]
i read the documentation for the third-party authentication in the storefront [here](https://docs.medusajs.com/resources/storefront-development/customers/third-party-login) which is referring to Auth Flow with routes from the docs [here](https://docs.medusajs.com/resources/commerce-modules/auth/authentication-route#2-third-party-service-authenticate-flow) and also following the comments here trying to understand them, but i still can't understand. 

The decoded token from the `/auth/{actor_type}/{provider}/callback?code?{code}&state={state}` does not provide me information about the user email address, which is needed to register a new customer. Example of the decoded response: 

```typescript
{
  actor_id: '',
  actor_type: 'customer',
  auth_identity_id: 'authid_xxx,
  app_metadata: {},
  iat: xxx,
  exp: xxx
}
```

Could you please elaborate more on that? @sradevski 
what i am trying to do here is to register the user when they are not yet registered. 

If what you guys meant above was to load the information from the `auth_identity` joined with `customer` table. The app_metadata column is empty if the user does not exist. 

![Image](https://github.com/user-attachments/assets/68e08031-99c1-4037-a238-384e72c3e6d4)

**Comment by Furman1331** [comment]
> So, am I understand it correctly that after approving this change, the easiest way to create customer with google email is to, collect provider-identity from the database into the frontend, accordint to the ID we received in the response. And send an email with that address to create the customer, right?
> 
> If this is true, we need to update the documentation.

We've describe it here, you just need to connect created auth_identity with this google, you can collect the information from request: /auth/customer/provider/${id}

If you can't find the metadata in the database you probably don't have the latest version of medusa

**Comment by cellthium-dev** [comment]
thank you for your reply. i updated the package to the latest version. 
![Image](https://github.com/user-attachments/assets/8e4a96b4-6b03-411f-be6a-1f86cdf3be80)

But the problem still exists. I get Unauthorized error. @Furman1331 

![Image](https://github.com/user-attachments/assets/87c0d4c0-d359-4e33-b75d-9c9f96accf10)

**Comment by cellthium-dev** [comment]
to verify, i just deleted and re-instantiated the backend project and the database also. For information: i'm using postgres database from supabase.

**Comment by cellthium-dev** [comment]
May be i'm just missing a little bit of the puzzle. So, do i understand it correctly that from the [validation callback endpoint](https://docs.medusajs.com/api/admin#auth_postactor_typeauth_providercallback) we get JWT-Token back as a string. From the documentation, i could see that the JWT token could be used for registration or authentication. How could i register a customer only with the JWT token?

**Comment by cellthium-dev** [comment]
The question remains: how could i get the email address without asking the customer to fill out a form as written in the docs? The endpoint `/auth/customer/google/${id}` does not seem to exist.

**Comment by cellthium-dev** [comment]
i could get the user information in the user_metadata property like name, email, picture, given_name and family_name by creating a custom endpoint on the backend. I did execute the autoModuleService.validateCallback() method with the `code` and `state` from the authentication endpoint as query parameter. I did not understand why if i did it using the js-sdk, i just got no information from the decoded token. For me it seems like the `@medusajs/medusa/auth` hides this information when creating the jwt token.

**Comment by apiscerena** [comment]
I'm stuck with the same problem. await sdk.auth.callback("customer", "google", queryParams) only returns the token, without email and other information. How could you resolve this? @cellthium-dev

**Comment by unlux** [comment]
i have been banging my head on this for 5 days straight for 14 hours a day. 
i have skimmed through half of the internet for this problem.
i have sucked every AI model to get this to work _the Medusa Way_
i have only just found this issue now.
i want to hurt myself.
i want to know of a way around using google for auth
or maybe using auth0.

**Comment by apiscerena** [comment]
I believe i solved this problem, according to some posts in discord.

you have to setup a route.ts to manually retrieve email info from database and pass email to create your account.

like this

```
import {
  MedusaRequest,
  MedusaResponse,
} from "@medusajs/framework";
import { IAuthModuleService } from "@medusajs/framework/types";
import { Modules } from "@medusajs/framework/utils";
import { jwtDecode } from "jwt-decode";

type TokenPayload = {
  actor_id?: string;
  actor_type?: string;
  auth_identity_id?: string;
  app_metadata?: any;
  iat?: number;
  exp?: number;
}

export const GET = async (
  req: MedusaRequest,
  res: MedusaResponse
) => {
  try {
    const authHeader = req.get("Authorization");
    const token = authHeader?.replace("Bearer ", "").trim();
    
    if (!token) {
      return res.status(401).json({
        message: "Authorization token is required",
        code: "UNAUTHORIZED",
      });
    }

    let decoded: TokenPayload;
    try {
      decoded = jwtDecode(token) as TokenPayload;
      console.log('Decoded token:', decoded);
    } catch (error) {
      return res.status(401).json({
        message: "Invalid token format",
        code: "INVALID_TOKEN",
      });
    }

    const authIdentityId = decoded.auth_identity_id;
    if (!authIdentityId) {
      return res.status(400).json({
        message: "Token does not contain auth_identity_id",
        code: "INVALID_TOKEN_DATA",
      });
    }

    const authModuleService = req.scope.resolve<IAuthModuleService>(
      Modules.AUTH
    );

    const providerIdentities = await authModuleService.listProviderIdentities({
      auth_identity_id: authIdentityId
    });

    if (!providerIdentities || providerIdentities.length === 0) {
      return res.status(404).json({
        message: "No provider identities found for this auth identity",
        code: "NOT_FOUND",
      });
    }

    const providerIdentity = providerIdentities.find(
      (pi) => pi.provider !== "emailpass"
    ) || providerIdentities[0];

    let email: string | null = null;
    let name: string | null = null;
    let provider: string | null = null;

    if (providerIdentity) {
      provider = providerIdentity.provider;
      
      if (providerIdentity.user_metadata) {
        const userMetadata = providerIdentity.user_metadata as any;
        
        if (userMetadata.email) {
          email = userMetadata.email;
        }
        
        if (userMetadata.name) {
          name = userMetadata.name;
        } else if (userMetadata.given_name && userMetadata.family_name) {
          name = `${userMetadata.given_name} ${userMetadata.family_name}`;
        } else if (userMetadata.given_name) {
          name = userMetadata.given_name;
        }
      }

      if (!email) {
        if (providerIdentity.provider_metadata) {
          const metadata = providerIdentity.provider_metadata as any;
          if (metadata.email) {
            email = metadata.email;
          }
        }
        
        if (!email && providerIdentity.entity_id && providerIdentity.entity_id.includes('@')) {
          email = providerIdentity.entity_id;
        }
      }

      if (!name && providerIdentity.provider_metadata) {
        const metadata = providerIdentity.provider_metadata as any;
        
        if (metadata.name) {
          name = metadata.name;
        } else if (metadata.given_name && metadata.family_name) {
          name = `${metadata.given_name} ${metadata.family_name}`;
        } else if (metadata.given_name) {
          name = metadata.given_name;
        }
      }
    }

    return res.json({
      auth_identity_id: authIdentityId,
      actor_id: decoded.actor_id,
      actor_type: decoded.actor_type,
      email,
      name,
      provider,
      user_metadata: providerIdentity?.user_metadata,
      provider_metadata: providerIdentity?.provider_metadata,
    });

  } catch (error) {
    console.error("Error retrieving user info from token:", error);
    
    return res.status(500).json({
      message: "Internal server error",
      code: "INTERNAL_ERROR",
    });
  }
};

```

Good Luck!

@unlux

**Comment by unlux** [comment]
thanks for the revert @apiscerena. i have lost all sense of direction in my project. could i maybe see your exact code and fork the auth implementation? would be a great help.

**Comment by apiscerena** [comment]
sorry, i'm working on a private repo. But i believe you could use the code above to finish the google login. It easy, trust me.

**Comment by unlux** [comment]
is just this code enough? and how do i work with it in the callback page? is it possible that you in a (very low effort and quick) way create an empty repo with medusa's started nextjs template and put your patch there and upload it to your repo

**Comment by SalahAdDin** [comment]
> is just this code enough? and how do i work with it in the callback page? is it possible that you in a (very low effort and quick) way create an empty repo with medusa's started nextjs template and put your patch there and upload it to your repo

you can find it on google man.

> i have been banging my head on this for 5 days straight for 14 hours a day.
> i have skimmed through half of the internet for this problem.
> i have sucked every AI model to get this to work the Medusa Way
> i have only just found this issue now.
> i want to hurt myself.
> i want to know of a way around using google for author maybe using auth0.

Take it easy man!

**Comment by unlux** [comment]
i still couldnt find relevant info. or maybe i am too dumb to begin with. would love some proper documentation or templated code.

**Comment by Misfit-Ha** [comment]
> i still couldnt find relevant info. or maybe i am too dumb to begin with. would love some proper documentation or templated code.

Probably best to open another issue but [this person's project](https://github.com/Road-to-Capstone-Project/c.v.o.s-all/tree/main) has a google auth that looks pretty solid from what i can tell
Although I havent tested it out myself, i plan on doing that later

**Comment by skndash96** [comment]
I've successfully added a Login With Google button in which redirects to the Google consent screen.
Then I realized `createCustomer` requires email. So as @apiscerena suggested, I made a separate route to fetch the email and other metadata.
Now I can successfully fetch the email by calling `sdk.client.fetch('/path/to/api-for-getting-auth-metadata')`
But at this point, I'm stuck.
It creates/retrieves the customer info correctly but the session is not established i guess?
What happens next after retrieving customer?

**Comment by unlux** [comment]
I used that repo, searched Google, and copied each file accurately, including the proper .env files. I also added the relevant callback URL to the Google client. It works for me, though it’s pretty slow. Check it out at [test website](https://tjj2.unlux.dev/in/account). backend frontend redis are on same instance. but the env uses 2 diff subdomains because the `code and state` kept going to localhost instead of the prod domain.

 I don’t get why Medusa provides the full path for third-party integrations but doesn’t offer a prebuilt solution for direct use. It’s always like, 'Here’s how you make a wishlist provider.' Now I have to rely on someone else’s work (after all the effort of building it) instead of something straight from Medusa.

**Comment by skndash96** [comment]
The login is pretty fast for me. 
Another thing is,
<img width="1843" height="805" alt="Image" src="https://github.com/user-attachments/assets/f2512ea3-7c2b-4267-8b67-b647cd32ce36" />
This probably belongs to another discussion but this bug's been annoying me in your example as well as my local environment
The subtotal is 50.01/- and shipping cost is 49/-
and yet the total is 50.01 instead of 99.01/-
Like shipping cost is not being added to the total. I don't think it's a frontend logic erorr. It's the cart data received from the backend.

**Comment by SalahAdDin** [comment]
> The login is pretty fast for me. Another thing is, <img alt="Image" width="1843" height="805" src="https://private-user-images.githubusercontent.com/78152517/484114748-f2512ea3-7c2b-4267-8b67-b647cd32ce36.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTY3NzIwMTAsIm5iZiI6MTc1Njc3MTcxMCwicGF0aCI6Ii83ODE1MjUxNy80ODQxMTQ3NDgtZjI1MTJlYTMtN2MyYi00MjY3LThiNjctYjY0N2NkMzJjZTM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTAyVDAwMDgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjZGNlMzJlMzI1YTI1NzczN2U0YWE1ZDIzMTk3M2JjOTJmYzUzYTEwOTgzYjYwZGY1NmI2MGZhM2FmOWZmNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gp6DBB5UwyhgQh-7BRF4UpFKH3tMxB97WZPZKj0WuVo"> This probably belongs to another discussion but this bug's been annoying me in your example as well as my local environment The subtotal is 50.01/- and shipping cost is 49/- and yet the total is 50.01 instead of 99.01/- Like shipping cost is not being added to the total. I don't think it's a frontend logic erorr. It's the cart data received from the backend.

Open a new bug for it.

**Comment by unlux** [comment]
> The login is pretty fast for me. Another thing is, <img alt="Image" width="1843" height="805" src="https://private-user-images.githubusercontent.com/78152517/484114748-f2512ea3-7c2b-4267-8b67-b647cd32ce36.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTY4MDI5NzEsIm5iZiI6MTc1NjgwMjY3MSwicGF0aCI6Ii83ODE1MjUxNy80ODQxMTQ3NDgtZjI1MTJlYTMtN2MyYi00MjY3LThiNjctYjY0N2NkMzJjZTM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTAyVDA4NDQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyYTk5MWUzMzllNWFjZGU0YWNkODBhMTVlNGJlZDg0NzdjNTZiY2VhYWE3NDRjMjAzNDZiYjQyZmNmZWExYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.79Mm5D3mgvmPVVvo5fZNig_uQMYIXGhTpAPFH7aBtnc"> This probably belongs to another discussion but this bug's been annoying me in your example as well as my local environment The subtotal is 50.01/- and shipping cost is 49/- and yet the total is 50.01 instead of 99.01/- Like shipping cost is not being added to the total. I don't think it's a frontend logic erorr. It's the cart data received from the backend.

damn, i just noticed. for me, the total is working fine but the shipping cost is getting added to the subtotal as well. will check soon.

**Comment by SalahAdDin** [comment]
Open an issue for those guys!

**Comment by skndash96** [comment]
Here is the issue #13403

**Comment by yasin7a** [comment]
@apiscerena  thanks man, love u, your solution works
