### ISSUE TITLE
[Bug]: [Deprecation] Custom state pseudo classes have been changed from ":--webkit-search-cancel-button" to ":state(webkit-search-cancel-button)"

### ISSUE THREAD

**Issue by SummerFans** [medusajs/medusa#10055]
### Package.json file

```JSON
{
  "dependencies": {
    "@medusajs/js-sdk": "^2.0.4",
    "@medusajs/types": "^2.0.4",
    "@medusajs/ui": "^4.0.1"
  }
}
```

### Node.js version

v20.11.1

### Database and its version

PostgreSQL 15.8

### Operating system name and version

mac 14.6.1 

### Browser name

Chrome

### browser error messages
![image](https://github.com/user-attachments/assets/b9b36b0c-800e-4a7d-bbde-8238be012883)

### ::-webkit-search-cancel-button has been deprecated
https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-search-cancel-button

### Expected behavior

no errors

### Actual behavior

[Deprecation] Custom state pseudo classes have been changed from ":--webkit-search-cancel-button" to ":state(webkit-search-cancel-button)"

### Link to reproduction repo

https://github.com/medusajs/medusa/blob/9e40f34ba8ffb70c25fdc8a485afaa2f215eae96/packages/design-system/ui/src/components/input/input.tsx#L19

**Comment by fPolic** [comment]
Please see: https://github.com/medusajs/medusa/issues/8294#issuecomment-2258242796
