### ISSUE TITLE
https://docs.medusajs.com/resources/medusa-config 404

### ISSUE THREAD

**Issue by gowy222** [medusajs/medusa#10058]
### What Medusa version and documentation are you using?

None

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I was seeking how to set cookie works in http NOT https,
everytime try to check doc,

open:
https://docs.medusajs.com/learn/installation
```
Configure Medusa Application[#](https://docs.medusajs.com/learn/installation#configure-medusa-application)
By default, your Medusa application is equipped with the basic configuration to start your development.

If you run into issues with configurations, such as CORS configurations, or need to make changes to the default configuration, refer to [this guide on all available configurations](https://docs.medusajs.com/resources/medusa-config).
```

then:
https://docs.medusajs.com/resources/medusa-config

404

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue
- [ ]

**Comment by shahednasser** [comment]
Thanks for opening this issue! The correct URL is https://docs.medusajs.com/resources/references/medusa-config

Will open a PR to fix this error
