### ISSUE TITLE
Medusa Development Resources: Issue in Get Product Variant Prices using Query Docs - Medusa Development Resources

### ISSUE THREAD

**Issue by karanchugh02** [medusajs/medusa#10068]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The sample code provided below retrieves product variants along with their prices:
[Link to this Page](https://docs.medusajs.com/resources/commerce-modules/product/guides/price)
```
const { data: products } = await query.graph({
  entity: "product",
  fields: [
    "*",
    "variants.*",
    "variants.prices.*",
  ],
  filters: {
    id: [
      "prod_123",
    ],
  },
})
```

However, based on the Pricing Module’s Price Data Model reference, while the prices array is part of this data model, there doesn’t appear to be a prices property directly accessible in the model itself. You can find the reference documentation here: [Price Data Model](https://docs.medusajs.com/resources/references/pricing/models/Price). 

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Hello @karanchugh02 , I think there's a misunderstanding here. Basically each item in the `prices` array is a record of the `Price` data model. It's not that the `Price` data model has an array of prices.

Will close this issue as i don't see any problem in it. Feel free to reopen it if you have more information.
