### ISSUE TITLE
[Bug]: No DB prompts in create-medusa-app@latest

### ISSUE THREAD

**Issue by jcedborger** [medusajs/medusa#10067]
### Package.json file

```JSON
No package.json file
```

### Node.js version

v23.1.0

### Database and its version

PostgreSQL 15.8

### Operating system name and version

Mac OS 15.1 (24B83)

### What happended?

When I run `npx create-medusa-app©latest` I am not getting prompted to enter my db credentials, and then I get thrown with the following error.

 npx create-medusa-app@latest
(node:13267) ExperimentalWarning: CommonJS module /opt/homebrew/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /opt/homebrew/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
? What's the name of your project? my-medusa-store
? Would you like to create the Next.js storefront? You can also create it later No
🚀 Starting project setup, this may take a few minutes.
✔ Created project directory
An error occurred while trying to create your database: error: permission denied to create database

### Expected behavior

It should let me input my DB credentials.

### Actual behavior

It doesn't. Also, the link to the discord is invalid.

### Link to reproduction repo

no repo

**Comment by jcedborger** [comment]
Nevermind. I rebooted everything and it worked.

**Comment by jcedborger** [comment]
I solved the permission denied error, but was still not prompted to enter the db credentials at setup

**Comment by shahednasser** [comment]
Hi @jcedborger , the permission issue isn't something to resolve from our side, so glad you could resolve that!

I assume then the rest of the setup was successful?

> but was still not prompted to enter the db credentials at setup

By default, the `create-medusa-app` command uses your `postgres` user with default credentials. If it can't connect to the database with the default credentials, it then asks you for the database credentials. So, it just means that the command connected to your database successfully.

is there a reason you want to be prompted for the database credentials during setup?

**Comment by shahednasser** [comment]
Will close this issue as it's the expected behavior and for lack of response. Feel free to follow-up if you have more questions.
