### ISSUE TITLE
[Bug]: Could not resolve module: Payment

### ISSUE THREAD

**Issue by homosape** [medusajs/medusa#10076]
### Package.json file

```JSON
{
  "name": "qnari-commerce",
  "version": "0.0.1",
  "author": "Nari Solutions",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "^2.0.4",
    "@medusajs/cli": "^2.0.4",
    "@medusajs/framework": "^2.0.4",
    "@medusajs/medusa": "^2.0.4",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0",
    "zod": "^3.22"
  },
  "devDependencies": {
    "@medusajs/test-utils": "^2.0.0",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v20.12.1

### Database and its version

supabase

### Operating system name and version

macOS Sequoia 15.1

### What happended?

I cleared database and trying to run seed to populate it with new products. `yarn seed` command throws error.

### Expected behavior

I expected it to populate database without issues since nothing has changed except I added few more products.

### Actual behavior

Seed command throws error
<img width="1075" alt="Screenshot 2024-11-13 at 17 37 16" src="https://github.com/user-attachments/assets/ca6c64c4-9de8-4945-ba68-0c0b6eb37d11">

### Link to reproduction repo

https://github.com/homosape/medusa-demo/tree/develop

**Comment by sradevski** [comment]
How did you clear the database? It seems there are tables missing.

If you completely removed all tables, you can run `npx medusa db:migrate` to run the migrations, `npx medusa db:sync-links` to relink all modules, and then you can try running the seed command.

As this doesn't seem to be a bug on Medusa's side, I'll close the ticket

**Comment by homosape** [comment]
@sradevski thanks it has worked!

I've dropped all tables and then ran` yarn seed `directly without migrations.

**Comment by mk0y** [comment]
For me it doesn't work at all, fresh Medusa installation development mode:

```
{"level":"error","message":"Could not resolve module: Payment. Error: Class extends value undefined is not a constructor or null\n","timestamp":"2024-11-21 10:42:05"}
```
