### ISSUE TITLE
[Discussion] Remove lock file from the repo

### ISSUE THREAD

**Issue by ymaheshwari1** [medusajs/medusa#1008]

**Comment by chill117** [comment]
Why? Lock files are very important for ensuring that the correct dependencies are used across installations for both development and deployment in production environments. Without a lock file, weird inconsistencies will appear eventually.

**Comment by ymaheshwari1** [comment]
> Why? Lock files are very important for ensuring that the correct dependencies are used across installations for both development and deployment in production environments. Without a lock file, weird inconsistencies will appear eventually.

Hi @chill117 I am also in your favor that we should keep the files, but as medusa uses two package managers, npm and yarn and thus after the discussion on discord I have created this issue, you can read the full conversation [here](https://discord.com/channels/876835651130097704/877195433649258536/933022555781099530).

**Comment by chill117** [comment]
> > Why? Lock files are very important for ensuring that the correct dependencies are used across installations for both development and deployment in production environments. Without a lock file, weird inconsistencies will appear eventually.
> 
> Hi @chill117 I am also in your favor that we should keep the lock files, but as medusa uses two package managers, npm and yarn and thus after the discussion on discord I have created this issue, you can read the full conversation [here](https://discord.com/channels/876835651130097704/877195433649258536/933022555781099530).

That discord link requires a login. For the interest of transparency, might be good to include the relevant quotes from that discussion here.

**Comment by ymaheshwari1** [comment]
> > > Why? Lock files are very important for ensuring that the correct dependencies are used across installations for both development and deployment in production environments. Without a lock file, weird inconsistencies will appear eventually.
> > 
> > 
> > Hi @chill117 I am also in your favor that we should keep the lock files, but as medusa uses two package managers, npm and yarn and thus after the discussion on discord I have created this issue, you can read the full conversation [here](https://discord.com/channels/876835651130097704/877195433649258536/933022555781099530).
> 
> That discord link requires a login. For the interest of transparency, might be good to include the relevant quotes from that discussion here.

Sure
```
Yes, indeed the lock files should not be pushed neither yarn.lock nor package-lock 
you could create an issue and PR if you want
```
```
Me: 
But I have gone through multiple articles around pushing lock files to git or not, and most of them says you should push lock files.
Even node doc says https://nodejs.dev/learn/the-package-lock-json-file
```
```
It's recommended to push one or the other. The warning comes from the fact that we currently have both in our repository 
```
```
but the thing is that you as a consumer can push the lock files into your remote repository 
but the original project should not contains the lock files
```

**Comment by chill117** [comment]
Those comments are contradictory.

In node.js projects, it is a best practice to commit a lock file - either package-lock.json or yarn.lock (if yarn is used) but not both. So this repository is fine, because it has only a yarn.lock file.

**Comment by srindom** [comment]
Was just checking out Gatsby: https://github.com/gatsbyjs/gatsby/tree/54d4721462b9303fed723fdcb15ac5d72e103778/packages/gatsby

They don't commit `yarn.lock`s. My personal thinking is that it does more harm than good to not include them, would be great to understand the best practices here further. Have you come across resources that cover what is best for packages that can be consumed in both NPM and Yarn managed projects?

**Comment by ymaheshwari1** [comment]
Actually, what I have seen on different projects is that they do consider pushing the lock files, and even the same is recommended by node.

**Comment by srindom** [comment]
@graysonhicks would you be able to shed some light on this for us? :)

**Comment by graysonhicks** [comment]
We do commit the `yarn.lock` file at Gatsby.  You don't see it there I think because it is at the root of the monorepo that is managed by Lerna.  I think the principle of commit a lock file, but not two conflicting ones, is correct.

**Comment by srindom** [comment]
@graysonhicks thanks - this makes sense! I'll close this issue.
