### ISSUE TITLE
[Bug]: hooks of LineItem are missing

### ISSUE THREAD

**Issue by dupuisbenjamin** [medusajs/medusa#10086]
### Package.json file

```JSON
{
    [...]
    "scripts": { [...] },
    "dependencies": {
        "@medusajs/admin-sdk": "latest",
        "@medusajs/framework": "latest",
        "@medusajs/medusa": "latest",
        "@medusajs/cli": "latest",
        "@mikro-orm/core": "5.9.7",
        "@mikro-orm/knex": "5.9.7",
        "@mikro-orm/migrations": "5.9.7",
        "@mikro-orm/postgresql": "5.9.7",
        "awilix": "^8.0.1",
        "pg": "^8.13.0",
        [...]
    },
    "devDependencies": {
        "@mikro-orm/cli": "5.9.7",
        "@medusajs/test-utils": "latest",
        [...]
    }
}
```

### Node.js version

v20.17.0

### Database and its version

PostgreSQL v10.4

### Operating system name and version

Windows 11

### What happended?

I'm trying to extend the LineItem on an order. While there is no documentation for extending the Order module, I've found a similar one for the Cart. Here is the [link](https://docs.medusajs.com/resources/commerce-modules/cart/extend)
I'd like to consume the lineItemCreated workflow hook, similarly to step 4. I've checked the https://docs.medusajs.com/learn/advanced-development/workflows/workflow-hooks and the reference https://docs.medusajs.com/resources/medusa-workflows-reference, and couldn't find any hooks that allows you to add additional_data to a line_item.

### Expected behavior

According to the [reference guide](https://docs.medusajs.com/resources/references/medusa-workflows/addOrderLineItemsWorkflow) and to the [github](https://github.com/medusajs/medusa/blob/develop/packages/core/core-flows/src/order/workflows/add-line-items.ts#L66)

I am expecting to be able to do the following
```
addOrderLineItemsWorkflow.hooks.LineItemCreated(
      async ({ lineItem, }, { container }) => {
            // TODO
      })
)
```

### Actual behavior

Error that there is no hook on addOrderLineItemsWorkflow

### Link to reproduction repo

-

**Comment by sradevski** [comment]
Hi there, we are adding hooks as necessary, so we might not have gotten to it just yet.

I cannot say when we'll be able to look into it though, so we'd be more than happy if you can just open a PR adding the hooks. 

Thanks!

**Comment by dupuisbenjamin** [comment]
Hi @sradevski,

I have been working on the workflow `createOrderLineItemsWorkflow` and implementing it in the `createOrdersWorkflow`.

However, after several hours working on it, I noticed that achieving my goal won't be possible at the moment due to the impossibility of supplying the workflow with additional_data like in [`createOrdersWorkflow`](https://github.com/medusajs/medusa/blob/493d242c1259cdc68ecdce5f0f9d7885cbd67094/packages/core/core-flows/src/order/workflows/create-orders.ts#L182). 
The validator doesn't allow the addition of customAdditionalData Validation to the additional_data of an item inside an order, aka LineItem.
I was expecting to be able to do it in Medusa v2 because it was possible to do so in Medusa v1. With the current additional_data structure, this seems impossible. Extending LineItem to add additional_data is crucial for my team, I am quite disappointed in the lack of extendability of important entities.

Looking forward for future fixes about it.

**Comment by sradevski** [comment]
@dupuisbenjamin the way you extend models is different in V2, please check https://docs.medusajs.com/learn/customization/custom-features.
