### ISSUE TITLE
Medusa Development Resources: Issue in Medusa Development Resources - Stripe Integration

### ISSUE THREAD

**Issue by huotarih** [medusajs/medusa#10096]
### What Medusa version and documentation are you using?

None

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The integration guide for stripe is out of date

https://docs.medusajs.com/resources/storefront-development/checkout/payment/stripe is not up to date. 

`import { useCart } from "../../providers/cart"` does not exist, and looks like in the payment component there is already some stripe elements. 

### How can this issue be resolved?

1. Rewrite the dev docs to work with the latest version of medusa & storefront

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for reporting this! Actually the guide is up to date, but it misses a key prerequisite. Apologies for the confusion! You should refer to this guide for the provider:

https://docs.medusajs.com/resources/storefront-development/cart/context

Will open a PR to update the prerequisites

**Comment by huotarih** [comment]
Thanks for the quick response.

I added the providers and followed up on the integration, but I ran into another issue with an Unhandled Runtime Error of `Error: useCart must be used within a CartProvider

`

This happened after I replaced my payment component to the one in this guide https://docs.medusajs.com/resources/storefront-development/checkout/payment

How I understand the current frontend example, is that with adding stripe to the backend and env keys to both, I should be able to already use stripe card payment just by enabling it in the backend. What happens instead is it doesn't show any card element and just skips that and buttons are disabled after. Also cart doesn't update anymore when adding products after being in the checkout. This seems all very complicated now versus a year ago when I set up my first medusa store.

Thanks for addressing this though, hope you have the time to test the integration steps in a new project as well.

Sidenote: The Cart and Region context providers should wrap the headers value to check if the ENV is there to prevent linting errors:

        ```
headers: process.env.NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY
          ? {
              "x-publishable-api-key":
                process.env.NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY,
                contentType: "application/json"
            }
          : undefined,

```

**Comment by shahednasser** [comment]
> Error: useCart must be used within a CartProvider

Did you add the Cart provider in your hierarchy tree as explained [here](https://docs.medusajs.com/resources/storefront-development#use-cartprovider-in-component-tree)? Because the error sounds like you're using `useCart` in a component that isn't a child of `CartProvider`. The `CartProvider` should be somewhere higher in your component tree so that all your other components are children of it.

> Sidenote: The Cart and Region context providers should wrap the headers value to check if the ENV is there to prevent linting errors:

Thanks for the feedback! Will look into this separately.
