### ISSUE TITLE
[Bug]: npx medusa db:setup fails

### ISSUE THREAD

**Issue by amatosc** [medusajs/medusa#10105]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v20.11.1

### Database and its version

PostgreSQL 15.6 on aarch64-unknown-linux-gnu, compiled by gcc (GCC) 13.2.0, 64-bit

### Operating system name and version

MacOs 15.1 (24B83)

### Browser name

Safari

### What happended?

First create a new project skipping the bd creation

```shell
➜  /tmp npx create-medusa-app@latest --skip-db
? What's the name of your project? my-medusa-store
? Would you like to create the Next.js storefront? You can also create it later No
🚀 Starting project setup, this may take a few minutes.
✔ Created project directory
✔ Installed Dependencies
✔ Project Built
✔ Finished Preparation
✔ Project Prepared
```

when trying to initiate the BD, the commands fails. (I added the `DATABASE_URL` to the .env file)

```shell 
➜  my-medusa-store npx medusa db:setup --db "postgres"
info:    Connection established with the database "postgres"
error:   DbHandler exited
error: DbHandler exited
    at /private/tmp/my-medusa-store/node_modules/pg/lib/client.js:535:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async dbExists (/private/tmp/my-medusa-store/node_modules/@medusajs/utils/src/pg/index.ts:48:18)
    at async dbCreate (/private/tmp/my-medusa-store/node_modules/@medusajs/medusa/src/commands/db/create.ts:138:7)
    at async main (/private/tmp/my-medusa-store/node_modules/@medusajs/medusa/src/commands/db/setup.ts:14:21) {
  length: 44,
  severity: 'FATAL',
  code: 'XX000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: undefined,
  line: undefined,
  routine: undefined
}
```

### Expected behavior

Create database

### Actual behavior

Fails

### Link to reproduction repo

not apply

**Comment by trinhcongduc** [comment]
Do you sure you have correct postgresql URL and it's ready to connect ? And show your medusa-config.ts  file

**Comment by amatosc** [comment]
> Do you sure you have correct postgresql URL and it's ready to connect ? And show your medusa-config.ts file

Yes, actually I've tried 

```shell
npx create-medusa-app@latest --db-url "postgresql://postgres.user:password@aws-0-eu-west-3.pooler.supabase.com:PORT/postgres"
```

and it works (the `db-url` is the same that I have in my `.env` file)

### medusa-config.ts
```shell 
➜  my-medusa-store-skipping-db cat medusa-config.ts
import { loadEnv, defineConfig } from '@medusajs/framework/utils'

loadEnv(process.env.NODE_ENV || 'development', process.cwd())

module.exports = defineConfig({
  projectConfig: {
    databaseUrl: process.env.DATABASE_URL,
    http: {
      storeCors: process.env.STORE_CORS!,
      adminCors: process.env.ADMIN_CORS!,
      authCors: process.env.AUTH_CORS!,
      jwtSecret: process.env.JWT_SECRET || "supersecret",
      cookieSecret: process.env.COOKIE_SECRET || "supersecret",
    }
  }
})
```

**Comment by hadicph** [comment]
@amatosc Do you have a DB_NAME variable in your env file ?

**Comment by trinhcongduc** [comment]
Let's try connect DB by command line first: to make sure your postgresql url is correct . 

> ```shell
> psql -h aws-0-eu-west-3.pooler.supabase.com -p YOUR_PORT
> ```

By the way, make sure there is no space on your .env parameter's value

**Comment by amatosc** [comment]
I did verify the connection before :( , what really surprises me is that this one works!

`npx create-medusa-app@latest --db-url "postgresql://postgres.user:password@aws-0-eu-west-3.pooler.supabase.com:PORT/postgres"`

No spaces on the .env file
![Screenshot 2024-11-15 at 15 19 38](https://github.com/user-attachments/assets/5b24fc14-15d5-49f4-a80e-121c37d968c9)


Connection proof
![Screenshot 2024-11-15 at 15 20 08](https://github.com/user-attachments/assets/bb51f048-3cfc-4e83-9902-3046d1c06b98)

**Comment by trinhcongduc** [comment]
It's quite strange!
If your Postgresql password include special characters, it will a bit different define them on your .env file . Take a look 
<img width="861" alt="image" src="https://github.com/user-attachments/assets/fa6dad39-2e07-4774-b23a-4c1813173bc1">

Can you try it ?

**Comment by olivermrbl** [comment]
The error message does indeed suggest an issue with the PG connection. Someone reported a similar scenario with a Supabase connection string [here](https://stackoverflow.com/questions/79057470/receiving-an-unknown-error-message-trying-to-connect-to-postgresql-using-net). This is worth a shot!

**Comment by amatosc** [comment]
> It's quite strange! If your Postgresql password include special characters, it will a bit different define them on your .env file . Take a look <img alt="image" width="861" src="https://private-user-images.githubusercontent.com/38092290/386640734-fa6dad39-2e07-4774-b23a-4c1813173bc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MTkyMjAsIm5iZiI6MTczMTkxODkyMCwicGF0aCI6Ii8zODA5MjI5MC8zODY2NDA3MzQtZmE2ZGFkMzktMmUwNy00Nzc0LWIyM2EtNGMxODEzMTczYmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA4MzUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNGMzMWRiYzUxYzQ4YmY0MTE5YjkwNmJhYWE0ZmZkZmQ0NWM0Y2RlZGNhOGNkZTRmM2U2YmI2M2UyMWI0YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wCGBPiTI6iPp67ehkt71SdVGTlL9EI_cMx4AztpP1O4">
> 
> Can you try it ?

My password doesn’t contain any special characters; it only includes uppercase and lowercase letters as well as numbers. I understand this might be a lot to ask, but if you could test with a Supabase database, you would see the issue for yourself. I’m using the default user and the password generated by Supabase (just create a new project)

**Comment by amatosc** [comment]
> The error message does indeed suggest an issue with the PG connection. Someone reported a similar scenario with a Supabase connection string [here](https://stackoverflow.com/questions/79057470/receiving-an-unknown-error-message-trying-to-connect-to-postgresql-using-net). This is worth a shot!

To be honest, I don’t think the issue is with the connection. As you can see in the first log:

```bash
info:    Connection established with the database "postgres"
```

I also tried the solution mentioned in that post, but it still didn’t work (same error). I found it strange that when running `npx medusa db:setup`, it required the `DATABASE_URL` in the `.env` file but then still asked for the database separately.

**Comment by amatosc** [comment]
Hi @olivermrbl,

Could you please provide a workaround for creating and running database migrations in production?

Thank you!

**Comment by olivermrbl** [comment]
@amatosc, could you provide me with the (exact) steps to reproduce and I'll try to find time this week to give it a spin myself?

**Comment by amatosc** [comment]
Hi  @olivermrbl,

Sure! 

### Prerequisite

Ensure you have a project created in Supabase.

### Steps to Reproduce

1. Create a new Medusa project, skipping the database creation step:

```bash
   npx create-medusa-app@latest --skip-db
```

2.	Add the DATABASE_URL environment variable with the Postgres URI from Supabase to your `.env` file
```yaml
DATABASE_URL=postgres://postgres.user:password@aws-0-eu-central-1.pooler.supabase.com:6543/postgres
```

4.	Initialize the database:

```bash
npx medusa db:setup
```

However, I'm no longer sure if this issue is a bug in Medusa or an issue with Supabase. For comparison, I tried creating a new database in Neon, and the command to initialize the database works as expected.

**Comment by olivermrbl** [comment]
Pretty sure this is just because Supabase doesn't allow you to specify a database other than the one they provide. You probably should not be running `npx medusa db:setup` here, but instead `npx medusa db:migrate`, as the setup command attempts to create a new database before migrating.
