### ISSUE TITLE
[Bug]: When will Plugins official work with v2 ? We are so waiting for this update because it's very important to work with MedusaJS project ?

### ISSUE THREAD

**Issue by trinhcongduc** [medusajs/medusa#10118]
### Package.json file

```JSON
{
  "name": "trustedo-medusas-backend",
  "version": "0.0.1",
  "description": "A TrustedO Medusa source",
  "author": "dukstry.com",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "start": "medusa start",
    "dev": "medusa develop",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "migrate:contentful": "./src/loaders/contentful-migrations/index.ts",
    "import:contentful": "contentful space import --space-id $CONTENTFUL_SPACE_ID --mt $CONTENTFUL_ACCESS_TOKEN --content-file  ./data/contentful-seed.json",

  },
  "dependencies": {
    "@faker-js/faker": "^9.2.0",
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/event-bus-redis": "^2.0.4",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@medusajs/workflow-engine-redis": "^2.0.4",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "medusa-file-minio": "^1.3.2",
    "medusa-payment-manual": "^1.0.25",
    "medusa-payment-stripe": "^6.0.11",
    "medusa-plugin-contentful": "^1.2.12",
    "medusa-plugin-meilisearch": "^2.0.11",
    "pg": "^8.13.0",
    "typeorm": "^0.3.20"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "contentful-migration": "^4.26.1",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v21.7.3

### Database and its version

17.0

### Operating system name and version

MacOS

### What happended?

Plugins do not work with medusajs v2.

### Expected behavior

Plugins work

### Actual behavior

Not work

### Link to reproduction repo

https://github.com/trinhcongduc/medusajs-demo

**Comment by christiananese** [comment]
Hey @trinhcongduc, it looks like you linked a private repo.

Can you elaborate a little bit on your use case and what you are trying to build?

**Comment by trinhcongduc** [comment]
Hi @christiananese , 
It same issue i reported here : https://github.com/medusajs/medusa/issues/10038
I am trying to connect my app with some libraries but it seems not work .
And, i also always get this warning :
<img width="1291" alt="image" src="https://github.com/user-attachments/assets/0366408b-24a2-4ae2-a0c4-8d21a87bf905">

**Comment by olivermrbl** [comment]
As noted in the referenced issue, plugins are not supported in v2 yet, so the experience around registering and using them will likely have some friction. Our recommendation, for now, is to build the features directly in your Medusa project instead of extracting them to a plugin. Is there anything about your use case that is keeping you from doing this?

**Comment by olivermrbl** [comment]
I'll close this issue for now, since this is a known limitation. @trinhcongduc, please feel free to follow up here and we can keep the conversation going. Alternatively, you can create a GitHub Discussion :)

**Comment by olivermrbl** [comment]
@trinhcongduc, other than installing existing packages, such as the Contentful integration, do you need plugins for anything specific?

**Comment by gyurka00** [comment]
Hi @olivermrbl,

When will be done the plugin support?
I want to use the https://github.com/RSC-Labs/medusa-documents plugin to generate invoice but I could not use it with medusa v2.

**Comment by RajnandiniIngale** [comment]
@olivermrbl 

When will be the plugin support available for medusajs v2?

**Comment by jesvijonathan** [comment]
same, even oauth plugins are not working with 2.0 ig

**Comment by SalahAdDin** [comment]
Is it working now?

**Comment by christiananese** [comment]
Yes, plugins support was added to v2 a while ago. <br>You can find the docs [here](https://docs.medusajs.com/learn/fundamentals/plugins) or if you prefer a step by step guide we have one [here](https://docs.medusajs.com/resources/plugins/guides/wishlist).<br><br>There's no plan to support v1 plugins in Medusa 2.x, so using a v1 plugin will most likely not work.

**Comment by spjhon** [comment]
Do you recommend doing all the Medusa.js customizations in a plugin, or is it better to keep them directly in the src directory as of now?

**Comment by gyurka00** [comment]
Plugins are not working in medusa V2 production!
@christiananese please do not misinform people if it has a breaking issue.

It had reported before your answer:
https://github.com/medusajs/medusa/issues/11729

Conversation about it:
https://discord.com/channels/876835651130097704/1343843066737459210

**Comment by nyctonio** [comment]
why this issue is closed the plugins are still not loading the ui

**Comment by SalahAdDin** [comment]
> why is this issue closed? The plugins are still not loading the ui

@olivermrbl 
Could you help us here?

**Comment by christiananese** [comment]
Hi everyone - I just tried to follow the guides I previously shared and can confirm that plugins do work in Medusa v2.

To resolve the problem, please:

Upgrade to the latest version of Medusa, and then follow our official guide to build your own plugin using the Framework: https://docs.medusajs.com/learn/fundamentals/plugins 
[docs.medusajs.com](https://docs.medusajs.com/learn/fundamentals/framework)

Keep in mind that v1 plugins **won’t** be ported to v2, but most of them can be easily migrated. We recommend following the wishlist plugin guide as an example: https://docs.medusajs.com/resources/plugins/guides/wishlist 
[docs.medusajs.com](https://docs.medusajs.com/resources/plugins/guides/wishlist)

If you run into issues while following the guide, feel free to ask on Discord for help. And if you believe you've encountered an actual bug, please open a new issue so we can address it directly.

Hope this helps!
