### ISSUE TITLE
Medusa Development Resources: Issue in Customers in Storefront - Medusa Development Resources

### ISSUE THREAD

**Issue by omesh845** [medusajs/medusa#10127]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

#### Description
I've created a subscriber to trigger when a new customer is created using the `customer.created` event. It works fine when customers are created through the admin dashboard but does **not trigger** when customers are created via the API (Storefront). 

In contrast, another subscriber I implemented for the `order.placed` event works as expected for all scenarios.

#### Code Examples
Here is the code for the `customer.created` subscriber:
```typescript
import type { SubscriberArgs, SubscriberConfig } from "@medusajs/medusa";
import { Modules } from "@medusajs/utils";

export default async function customerCreatedHandler({
  event: { data },
  container,
}: SubscriberArgs<{ id: string }>) {
  const customerModuleService = container.resolve(Modules.CUSTOMER);
  const notificationModuleService = container.resolve(Modules.NOTIFICATION);

  const customer = await customerModuleService.retrieveCustomer(data.id);

  // Your email sending logic here
  console.log(`Customer created: ${customer.email}`);
}

export const config: SubscriberConfig = {
  event: "customer.created",
};
```

#### Expected Behavior
The `customer.created` event should trigger the subscriber when a customer is created via:
1. The admin dashboard.
2. The Storefront API.

#### Actual Behavior
The event only triggers when a customer is created using the admin dashboard. When creating a customer via the Storefront API:
- The customer is created successfully.
- Tokens are returned correctly.
- The event is **not triggered**, and the subscriber does not run.

#### Steps to Reproduce
1. Implement the above `customer.created` subscriber in `subscribers/test-sub.ts`.
2. Create a customer using the admin dashboard → Event triggers correctly.
3. Create a customer via the Storefront API → Event does not trigger.

#### Additional Information
The following subscriber for `order.placed` works as expected in all scenarios:
```typescript
import { Modules } from "@medusajs/utils";
import { INotificationModuleService, IOrderModuleService } from "@medusajs/types";
import { SubscriberArgs, SubscriberConfig } from "@medusajs/medusa";
import { EmailTemplates } from "../modules/email-notifications/templates";

export default async function orderPlacedHandler({
  event: { data },
  container,
}: SubscriberArgs<any>) {
  const notificationModuleService: INotificationModuleService = container.resolve(Modules.NOTIFICATION);
  const orderModuleService: IOrderModuleService = container.resolve(Modules.ORDER);

  const order = await orderModuleService.retrieveOrder(data.id, {
    relations: ["items", "summary", "shipping_address"],
  });
  const shippingAddress = await (orderModuleService as any).orderAddressService_.retrieve(order.shipping_address.id);

  try {
    await notificationModuleService.createNotifications({
      to: order.email,
      channel: "email",
      template: EmailTemplates.ORDER_PLACED,
      data: {
        emailOptions: {
          replyTo: "info@example.com",
          subject: "Your order has been placed",
        },
        order,
        shippingAddress,
        preview: "Thank you for your order!",
      },
    });
  } catch (error) {
    console.error("Error sending order confirmation notification:", error);
  }
}

export const config: SubscriberConfig = {
  event: "order.placed",
};
```

#### Questions
1. Is there a difference in how the `customer.created` event is emitted for the admin dashboard vs. Storefront API?
2. Am I missing any configuration for the subscriber to work with the Storefront API?

#### Environment
- MedusaJS version: v2
- Node.js version: v22.9.0
- Storefront: Expo

### How can this issue be resolved?

1. Ensure the Event is Emitted Correctly for `customer.created` via Stormfront API
2. if I'm Missing Something, please let me know

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by tadinski** [comment]
experiencing same issue

**Comment by tadinski** [comment]
any updates on this issue?

**Comment by gyurka00** [comment]
I have the same issue

**Comment by sradevski** [comment]
The issue has been fixed already and is in the latest release

**Comment by gyurka00** [comment]
Yes,it is working now.
I was with 2.1.0 and it was not working but now with 2.1.2 it is working.
(if you have a payment configured maybe you will get db error with the new version.
I got this `Could not resolve module: Payment. Error: Loaders for module Payment failed: column p0.deleted_at does not exist` this error and the ` npx medusa db:migrate` solved the issue. )

**Comment by gyurka00** [comment]
@omesh845 @tadinski try the latest release (v2.1.2)

**Comment by damienmutt** [comment]
> I got this `Could not resolve module: Payment. Error: Loaders for module Payment failed: column p0.deleted_at does not exist` this error and the ` npx medusa db:migrate` solved the issue.

Updated from 2.0.3 to 2.1.3 and got this error so I tried to run `npx medusa db:migrate` and now it works, BIG thanks!
