### ISSUE TITLE
Medusa Development Resources: Issue in Medusa Development Resources

### ISSUE THREAD

**Issue by Jotadebeese** [medusajs/medusa#10129]
### What Medusa version and documentation are you using?

None

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In Medusa SDK Documentation, under store -> products the methods list and retrieve are repeated twice:

![image](https://github.com/user-attachments/assets/b45f0b45-f615-4835-981d-3f42f8432277)

![image](https://github.com/user-attachments/assets/80c758b2-aff3-4bbb-ba22-07e15b743ed3)

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch! Will fix soon
