### ISSUE TITLE
Docs(Code Issue): import changes in in Module DOCS

### ISSUE THREAD

**Issue by omesh845** [medusajs/medusa#10137]
### What Medusa version and documentation are you using?

v2

Hi, i noticed in the docuemntation:

` import CustomerModule from "@medusajs/medusa/customer"`
 
 but its actually worked in `import CustomerModule from "@medusajs/customer";` 
 
 so, please check for others and update the documentation, 
 Thanks

**Comment by shahednasser** [comment]
Hello, thank you for opening this issue! Is there a reason you're importing from `@medusajs/customer` and not `@medusajs/medusa/customer`? Because the recommended approach is to import from `@medusajs/medusa/customer`

**Comment by omesh845** [comment]
I’m using `@medusajs/customer` simply because trying to import from `@medusajs/medusa/customer` gives the following error:

```
Cannot find module '@medusajs/medusa/customer' or its corresponding type declarations.

```

I found that `@medusajs/customer` works, so I decided to use it.

**Comment by shahednasser** [comment]
Are you using the latest version of Medusa? If not can you update it and try again? Make sure you're using the `latest` tag in `package.json` for the Medusa packages

**Comment by omesh845** [comment]
### `package.json` :
```json
{
  "@medusajs/admin-sdk": "latest",
  "@medusajs/cli": "latest",
  "@medusajs/core-flows": "latest",
  "@medusajs/framework": "latest",
  "@medusajs/medusa": "latest",
  "@medusajs/notification-sendgrid": "latest",
  "@medusajs/payment-stripe": "latest",
  "@medusajs/types": "latest",
  "@medusajs/utils": "latest",
  "@medusajs/workflow-engine-redis": "latest",
  "@mikro-orm/core": "5.9.7",
  "@mikro-orm/knex": "5.9.7",
  "@mikro-orm/migrations": "5.9.7",
  "@mikro-orm/postgresql": "5.9.7",
  "@react-email/components": "^0.0.26"
}
```

### Issue:
When trying to import from `@medusajs/medusa/customer`, I encountered the following error:

```
Cannot find module '@medusajs/medusa/customer' or its corresponding type declarations.
There are types at '<PATH>/node_modules/@medusajs/medusa/dist/modules/customer.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.
```

I attempted to update the dependencies, but the same error persisted.

**Comment by shahednasser** [comment]
Can you update your `package.json` to the following:

```json
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "@sanity/client": "^6.22.4",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

And you `tsconfig.json`:

```jsonc
{
  "compilerOptions": {
    "target": "ES2021",
    "esModuleInterop": true,
    "module": "Node16",
    "moduleResolution": "Node16",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "declaration": false,
    "sourceMap": false,
    "inlineSourceMap": true,
    "outDir": "./.medusa/server",
    "rootDir": "./",
    "baseUrl": ".",
    "jsx": "react-jsx",
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "checkJs": false
  },
  "ts-node": {
    "swc": true
  },
  "include": [
    "**/*",
    ".medusa/types/*"
  ],
  "exclude": [
    "node_modules",
    ".medusa/server",
    ".medusa/admin",
    ".cache"
  ]
}
```

Make sure to also install the dependencies, then try again

**Comment by omesh845** [comment]
Thanks! Deleting the `package-lock.json` file and updating `tsconfig.json` solved the problem. However, another issue has come up during login:  

```
Could not find an auth provider with id: emailpass
```

I’ve decided to migrate from the old setup to a new Medusa instance.  

That said, I have some specific doubts about extending modules in Medusa for the application I’m building. If possible, I’d really appreciate your guidance on these queries. Thank you so much!

**Comment by shahednasser** [comment]
Seems like your setup is a bit outdated, so moving to the new instance should solve your problems. If not, feel free to open another issue.

As for extending modules, it depends on the use case you have in mind. For example, if you want to add a custom field to the `product` data model in the product module, then you should use [Module Links](https://docs.medusajs.com/learn/advanced-development/module-links). The concept of directly extending modules is currently not supported. I recommend following the documentation to better understand Medusa's concepts and how you can use them.
