### ISSUE TITLE
Docs(Code Issue):  Database URL configuration in Medusa Installation 

### ISSUE THREAD

**Issue by yahyanoor123** [medusajs/medusa#10131]
### What Medusa version and documentation are you using?

None

### Preliminary Checks

- [ ] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

npx create-medusa-app@latest --db-url "postgres://user:password@localhost:<YOUR_PORT>/medusa-store"

This command not working.

### How can this issue be resolved?

Use this command for Medusa project installation.

npx create-medusa-app@latest my-medusa-store --db-url "postgres://user:password@localhost:<YOUR_PORT>/medusa-store

This command works in my case

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by yahyanoor123** [comment]
![image](https://github.com/user-attachments/assets/6f1d5d92-eafb-43e7-accd-faa48b9f75d2)


Check this !

**Comment by shahednasser** [comment]
Hey @yahyanoor123 when specifying the port, you shouldn't include `<>`, which you seem to have fixed in the second try in the screenshot. Did the installation work after?

**Comment by yahyanoor000123** [comment]
@shahednasser Thank you. It's working fine as per your suggestion.

**Comment by shahednasser** [comment]
Sounds great! Will close this issue then.
