### ISSUE TITLE
[Admin Dashboard UI Bug]: Functional problem with Product Variant Title when creating a new product

### ISSUE THREAD

**Issue by djidatechs** [medusajs/medusa#10148]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "^2.0.4",
    "@medusajs/cli": "^2.0.4",
    "@medusajs/framework": "^2.0.4",
    "@medusajs/medusa": "^2.0.4",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.1"
  },
  "devDependencies": {
    "@medusajs/test-utils": "^2.0.4",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.37",
    "@types/jest": "^29.5.14",
    "@types/node": "^20.17.6",
    "@types/react": "^18.3.12",
    "@types/react-dom": "^18.3.1",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.3",
    "vite": "^5.4.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v20.15.0

### Database and its version

psql (PostgreSQL) 17.1

### Operating system name and version

Windows 10

### What happended?

When creating a new product using the admin dashboard ui, I **titled** the variants with different titles but after publishing the product, the titles did not appear in product > variant > title , nor inventory > inventory item title.

For now I had to fix the problem with a subscription to product.created

![filling title field](https://github.com/user-attachments/assets/8189660a-3b26-4f3b-b7cd-09d37f01ed7e)

### Expected behavior

the values filled in the columns (marked in the picture) should be the titles of the variants in product>variant>title , and inventory > inventory item title

### Actual behavior

seems like the Values of each variant (ex: 1L, 2L, 3L) are used to fill the title fields instead of the collumns I marked in the image i sent

### Link to reproduction repo

/

**Comment by djidatechs** [comment]
in product variant , it just show the actual options names : 

![AzelP](https://github.com/user-attachments/assets/05eda092-6754-49d5-a5d8-98d3f879f32c)

in inventory  I fixed it with the subscriber sorry for not providing a picture, but same issue

**Comment by riqwan** [comment]
Thanks for surfacing this @djidatechs! Opened a PR to fix this - [https://github.com/medusajs/medusa/pull/10155](https://github.com/medusajs/medusa/pull/10155)
