### ISSUE TITLE
Medusa v2 Documentation: Issue in 1. Introduction - Medusa v2 Documentation - Medusa v2 Documentation

### ISSUE THREAD

**Issue by prakash03yes** [medusajs/medusa#10141]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

https://docs.medusajs.com/learn/installation

Was reading documention, tried to click  "Prerequisites 3" toggle button, page went into error
<img width="643" alt="Screenshot 2024-11-18 at 7 19 18 PM" src="https://github.com/user-attachments/assets/2a8be8f8-47e9-426c-83b8-2566bd7fd84d">
<img width="1100" alt="Screenshot 2024-11-18 at 7 20 05 PM" src="https://github.com/user-attachments/assets/2f9c3036-d5ea-4617-b615-b85bd7da63a9">
<img width="571" alt="Screenshot 2024-11-18 at 7 21 20 PM" src="https://github.com/user-attachments/assets/cb91b034-34b4-4c69-9854-ef9400dc7ab7">

### How can this issue be resolved?

1.
2.
3.
...
Sorry, Will check into this later

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for submitting this issue! Can reproduce this error. Will open a PR for a fix soon.
