### ISSUE TITLE
Medusa Development Resources: Issue in Update Cart in Storefront - Medusa Development Resources

### ISSUE THREAD

**Issue by Fxudel** [medusajs/medusa#10149]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

[wrong fields when updating cart customer](https://docs.medusajs.com/resources/storefront-development/cart/update#update-carts-customer): 
*customer_id* make zod error "error:   Invalid request: Unrecognized fields: 'customer_id'
MedusaError: Invalid request: Unrecognized fields: 'customer_id'
    at zodValidator"

### How can this issue be resolved?

1. Work fine with the fields email instead customer_id, update the documentation with correct field 
or
2. Update the codebase to follow documentation

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch thanks! Will look into fixing it
