### ISSUE TITLE
Docs(Code Issue): Missing import of Heading  Component from @medusajs/ui

### ISSUE THREAD

**Issue by ambigos1** [medusajs/medusa#10163]
### What Medusa version and documentation are you using?

None

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

the path-parameter example has a compilation error since the Heading Component is not imported.
 should be updated and import Heading from @medusajs/ui

Link:
https://docs.medusajs.com/learn/advanced-development/admin/widgets#path-parameters

![image](https://github.com/user-attachments/assets/0a7f9f5c-559e-4d09-98b6-07fe4afbcc54)

### How can this issue be resolved?

1. go to: https://docs.medusajs.com/learn/advanced-development/admin/widgets#path-parameters
2. Check that there is no Import for Heading

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch! Will open a PR to fix this
