### ISSUE TITLE
[Bug]: The request url "/app/node_modules/@medusajs/admin-bundler/dist/entry.tsx" is outside of Vite serving allow list - @medusajs/admin-bundler

### ISSUE THREAD

**Issue by chillpilllike** [medusajs/medusa#10178]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "predeploy": "medusa db:migrate",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

20

### Database and its version

16

### Operating system name and version

22.04

### What happended?

The request url "/app/node_modules/@medusajs/admin-bundler/dist/entry.tsx" is outside of Vite serving allow list.
http:    GET /app/entry.tsx ← https://secretgreen-medusa-backend-serverxxxxxxxxxxx/app (403) - 2.271 ms

I get this error when I visit the /app admin page. I have setup admin with server mode. health test said ok

### Expected behavior

The admin page should open

### Actual behavior

The request url "/app/node_modules/@medusajs/admin-bundler/dist/entry.tsx" is outside of Vite serving allow list.
http:    GET /app/entry.tsx ← https://secretgreen-medusa-backend-serverxxxxxxxxxxx/app (403) - 2.271 ms

### Link to reproduction repo

https://github.com/medusajs/medusa-starter-default.git

**Comment by chillpilllike** [comment]
I have added the server domain to the following in the server-mode backend env file:

MEDUSA_BACKEND_URL=[https://secretgreen-medusa-backend-serverxxxxxxxxxxx](https://secretgreen-medusa-backend-serverxxxxxxxxxxx
ADMIN_CORS=[https://secretgreen-medusa-backend-serverxxxxxxxxxxx](https://secretgreen-medusa-backend-serverxxxxxxxxxxx
AUTH_CORS=[https://secretgreen-medusa-backend-serverxxxxxxxxxxx](https://secretgreen-medusa-backend-serverxxxxxxxxxxx
STORE_CORS=[https://secretgreen-medusa-backend-serverxxxxxxxxxxx](https://secretgreen-medusa-backend-serverxxxxxxxxxxx

any variable tone added to worker-mode backend too? I followed the guide and this is what I understood but it is giving error

**Comment by chillpilllike** [comment]
**_In medusa-worker medusa-config.ts I have set:_**
admin: {
    disable: process.env.DISABLE_MEDUSA_ADMIN === "true", // Added admin.disable
  },
  
  
  ENV:
 COOKIE_SECRET=supersecret # TODO GENERATE SECURE SECRET
JWT_SECRET=supersecret  # TODO GENERATE SECURE SECRET
DISABLE_MEDUSA_ADMIN=true
MEDUSA_WORKER_MODE=worker
PORT=9000
DATABASE_URL # POSTGRES DATABASE URL
REDIS_URL= # REDIS DATABASE URL



**_In server mode:_**

admin: { // Added admin configuration
    backendUrl: process.env.MEDUSA_BACKEND_URL,
  },
  
  ENV

STORE_CORS= # STOREFRONT URL
ADMIN_CORS= server mode URL
AUTH_CORS= server mode URL # STOREFRONT AND ADMIN URLS, SEPARATED BY COMMAS
 MEDUSA_BACKEND_URL= server mode URL
 
 
 am I doing anything wrong, getting confused please help.

**Comment by chillpilllike** [comment]
This is my medusa-config.ts file for server mode:



import { loadEnv, defineConfig } from '@medusajs/framework/utils';
import { Modules } from "@medusajs/framework/utils";

loadEnv(process.env.NODE_ENV || 'development', process.cwd());

module.exports = defineConfig({
  projectConfig: {
    databaseUrl: process.env.DATABASE_URL,
    redisUrl: process.env.REDIS_URL, // Added redisUrl
    workerMode: process.env.MEDUSA_WORKER_MODE as "shared" | "worker" | "server", // Added workerMode
    http: {
      storeCors: process.env.STORE_CORS!,
      adminCors: process.env.ADMIN_CORS!,
      authCors: process.env.AUTH_CORS!,
      jwtSecret: process.env.JWT_SECRET || "supersecret",
      cookieSecret: process.env.COOKIE_SECRET || "supersecret",
    },
  },
  admin: {
    disable: process.env.DISABLE_MEDUSA_ADMIN === "true", // Added admin.disable
    backendUrl: process.env.MEDUSA_BACKEND_URL, // Added admin.backendUrl
  },
  modules: [
    {
      resolve: "@medusajs/medusa/cache-redis",
      options: { 
        redisUrl: process.env.CACHE_REDIS_URL,
      },
    },
    {
      resolve: "@medusajs/medusa/workflow-engine-redis",
      options: {
        redis: {
          url: process.env.WE_REDIS_URL,
        },
      },
    },
    {
      resolve: "@medusajs/medusa/event-bus-redis",
      options: { 
        redisUrl: process.env.EVENTS_REDIS_URL,
      },
    },
    {
      resolve: "@medusajs/medusa/file",
      options: {
        providers: [
          {
            resolve: "@medusajs/medusa/file-s3",
            id: "s3",
            options: {
              file_url: process.env.S3_FILE_URL,
              access_key_id: process.env.S3_ACCESS_KEY_ID,
              secret_access_key: process.env.S3_SECRET_ACCESS_KEY,
              region: process.env.S3_REGION,
              bucket: process.env.S3_BUCKET,
              endpoint: process.env.S3_ENDPOINT,
            },
          },
        ],
      },
    },
    {
      resolve: "@medusajs/medusa/notification",
      options: {
        providers: [
          {
            resolve: "@medusajs/medusa/notification-sendgrid",
            id: "sendgrid",
            options: {
              channels: ["email"],
              api_key: process.env.SENDGRID_API_KEY,
              from: process.env.SENDGRID_FROM,
            },
          },
        ],
      },
    },
    {
      resolve: "@medusajs/medusa/payment",
      options: {
        providers: [
          {
            resolve: "@medusajs/medusa/payment-stripe",
            id: "stripe",
            options: {
              apiKey: process.env.STRIPE_API_KEY,
            },
          },
        ],
      },
    },
  ],
});

**Comment by chillpilllike** [comment]
<img width="1274" alt="Screenshot 2024-11-20 at 7 19 01 pm" src="https://github.com/user-attachments/assets/85e597f7-a278-42b7-8ef3-8f37e92cacb1">


Don't know why docker internal port is visible here in the browser. But not in the worker server.


<img width="786" alt="Screenshot 2024-11-20 at 7 20 53 pm" src="https://github.com/user-attachments/assets/53152aa3-edc0-478b-b580-ec77da7f7ad7">

**Comment by chillpilllike** [comment]
Documentation is tricky for deployment. got it worked

**Comment by pmessan** [comment]
I have the same issue, how did you solve it?

**Comment by chillpilllike** [comment]
by following this:


https://docs.medusajs.com/resources/medusa-cli/commands/build

**Comment by pmessan** [comment]
this worked immediately! Thank you very much.

I am curious why this doc linked is seemingly filling the missing gaps that [this one](https://docs.medusajs.com/learn/deployment/general) has, but they are not linked. And, my setup seems to work without deploying the worker.

What is happening here? I documented my issues in #10378

**Comment by zaamx** [comment]
Can some of you help me with the correct path to deploy? I have the same issue
