### ISSUE TITLE
[Bug]: redisUrl not found. A fake redis instance will be used. - medusa db:migrate

### ISSUE THREAD

**Issue by chillpilllike** [medusajs/medusa#10171]
### Package.json file

```JSON
Unable to deploy says:

#11 12.50 > medusa-starter-default@0.0.1 predeploy
#11 12.50 > medusa db:migrate
#11 12.50 
#11 15.67 redisUrl not found. A fake redis instance will be used.
#11 15.69 error:   connect ECONNREFUSED 127.0.0.1:5432
#11 15.69 Error: connect ECONNREFUSED 127.0.0.1:5432
#11 15.69     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16) {
#11 15.69   errno: -111,
#11 15.69   code: 'ECONNREFUSED',
#11 15.69   syscall: 'connect',
#11 15.69   address: '127.0.0.1',
#11 15.69   port: 5432
#11 15.69 }


but in the env I have mentioned:

REDIS_URL=redis://default:xxxxxxx@xxxxxx:6379

the connection is active
```

### Node.js version

20

### Database and its version

16

### Operating system name and version

22.04

### What happended?

Unable to deploy the server, when command runs medusa db:migrate

redisUrl not found. A fake redis instance will be used. errors shows up and not deployed

### Expected behavior

it should deploy without this error since I have mentioned REDIS_URL in env

### Actual behavior

 > [8/8] RUN cd .medusa/server && yarn install && npm run predeploy:
15.67 redisUrl not found. A fake redis instance will be used.
15.69 error:   connect ECONNREFUSED 127.0.0.1:5432
15.69 Error: connect ECONNREFUSED 127.0.0.1:5432
15.69     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16) {
15.69   errno: -111,
15.69   code: 'ECONNREFUSED',
15.69   syscall: 'connect',
15.69   address: '127.0.0.1',
15.69   port: 5432
15.69 }
------
Dockerfile:28
--------------------
  26 |     
  27 |     # Run migrations and start the Medusa server
  28 | >>> RUN cd .medusa/server && yarn install && npm run predeploy
  29 |     
  30 |     CMD ["sh", "-c", "cd .medusa/server && yarn run start"]
--------------------
ERROR: failed to solve: process "/bin/sh -c cd .medusa/server && yarn install && npm run predeploy" did not complete successfully: exit code: 1
##########################################
### Link to reproduction repo

https://github.com/medusajs/medusa-starter-default.git

**Comment by chillpilllike** [comment]
I used the guid and added:

module.exports = defineConfig({
  projectConfig: {
    // ...
    redisUrl: process.env.REDIS_URL,
  },
})


now another problem arises after this:

$ medusa db:migrate
error:   Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_PG.acquireConnection (/app/medusa-starter-default/node_modules/knex/lib/client.js:332:26)
    at async Runner.ensureConnection (/app/medusa-starter-default/node_modules/knex/lib/execution/runner.js:305:28)
    at async Runner.run (/app/medusa-starter-default/node_modules/knex/lib/execution/runner.js:30:19)
    at async ensureDbExists (/app/medusa-starter-default/node_modules/@medusajs/medusa/src/commands/utils/index.ts:11:5)
    at async migrate (/app/medusa-starter-default/node_modules/@medusajs/medusa/src/commands/db/migrate.ts:33:3)
    at async main (/app/medusa-starter-default/node_modules/@medusajs/medusa/src/commands/db/migrate.ts:77:22) {
  sql: 'SELECT 1 + 1;',
  bindings: undefined
}
error Command failed with exit code 1.

**Comment by thetutlage** [comment]
Hello @chillpilllike 

Your issue is missing the `package.json` and also a reproduction repo will be needed on our end to look into the issue. 

Feel free to share the necessary information here and then we can reopen the issue :)

**Comment by chillpilllike** [comment]
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "predeploy": "medusa db:migrate",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}

**Comment by chillpilllike** [comment]
> medusa-starter-default@0.0.1 predeploy
> medusa db:migrate

error:   Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_PG.acquireConnection (/app/node_modules/knex/lib/client.js:332:26)
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:305:28)
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async ensureDbExists (/app/node_modules/@medusajs/medusa/src/commands/utils/index.ts:11:5)
    at async migrate (/app/node_modules/@medusajs/medusa/src/commands/db/migrate.ts:33:3)
    at async main (/app/node_modules/@medusajs/medusa/src/commands/db/migrate.ts:77:22) {
  sql: 'SELECT 1 + 1;',
  bindings: undefined
}

**Comment by chillpilllike** [comment]
> medusa-starter-default@0.0.1 start
> medusa start

error:   Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_PG.acquireConnection (/app/node_modules/knex/lib/client.js:332:26)
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:305:28)
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async ensureDbExists (/app/node_modules/@medusajs/medusa/src/commands/utils/index.ts:11:5)
    at async migrate (/app/node_modules/@medusajs/medusa/src/commands/db/migrate.ts:33:3)
    at async main (/app/node_modules/@medusajs/medusa/src/commands/db/migrate.ts:77:22) {
  sql: 'SELECT 1 + 1;',
  bindings: undefined
}
info:    Skipping instrumentation registration. No register function found.
info:    No link to load from /app/.medusa/server/src/links. skipped.
warn:    Local Event Bus installed. This is not recommended for production.
info:    Locking module: Using "in-memory" as default.
info:    No workflow to load from /app/.medusa/server/src/workflows. skipped.
(node:114) [DEP0178] DeprecationWarning: dirent.path is deprecated in favor of dirent.parentPath
(Use `node --trace-deprecation ...` to show where the warning was created)
- Creating server
✔ Server is ready on http://localhost:9000 – 20ms
info:    Admin URL → http://localhost:9000/app
http:    GET / ← https://103.xx.x.x/ (404) - 40.111 ms

**Comment by chillpilllike** [comment]
the solution I got after using 

RUN npx medusa build

to build the project. thanks
