### ISSUE TITLE
[Bug]: Backend URL for uploaded images defaults to localhost:9000 instead of the configured value

### ISSUE THREAD

**Issue by orbikular** [medusajs/medusa#10184]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start -p 9001",
    "dev": "medusa develop -p 9001",
    "sync": "medusa exec ./src/scripts/sync-products.ts",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0",
    "xlsx": "^0.18.5"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v20.5.1

### Database and its version

PostgreSQL 17.1

### Operating system name and version

macOS 15.0.1 - BuildVersion: 24A348

### Browser name

Google Chrome

### What happended?

I have set `MEDUSA_BACKEND_URL=http://localhost:9001` in my `.env` file to specify the correct backend URL. I start Medusa with:

```bash
medusa develop -p 9001
```

Additionally, in my medusa-config.ts, I have configured the backend URL for the admin panel like this:

```ts
admin: {
  backendUrl: process.env.MEDUSA_BACKEND_URL || "http://localhost:9001"
}
```

Despite these settings, images that I upload are still being saved with the default URL http://localhost:9000, which results in a 404 error when trying to access them.

### Expected behavior

When I configure MEDUSA_BACKEND_URL in the .env file and backendUrl in medusa-config.ts, I expect uploaded images to use this URL (i.e., http://localhost:9001) to be properly accessible.

### Actual behavior

Images are being saved with the default URL http://localhost:9000 rather than the URL set in MEDUSA_BACKEND_URL or backendUrl in medusa-config.ts. This causes a 404 error when trying to access uploaded images.

### Link to reproduction repo

Got only a private repo

**Comment by fPolic** [comment]
hey @orbikular, are you using the default file provider? You can pass backend URL as option: https://docs.medusajs.com/resources/architectural-modules/file/local#main

**Comment by orbikular** [comment]
@fPolic Thank you for your answer! I actually had the problem last night, but is that the intended solution? Shouldn't it actually work with the backendUrl? 
If this is the actual way, perhaps it should be better explained in the documentation.

**Comment by kasperkristensen** [comment]
Hi @orbikular, yes you are supposed to set the backend_url in the module option as described in the docs Frane linked above.

The `backendUrl` in the admin options is only used within the scope of the admin dashboard, to initialize the JS SDK. The field is only really needed if you host your dashboard independently from your server (from 2.0.4 and up before that it was also needed if you ran your server on another port then 9000).
