### ISSUE TITLE
[Bug]: Admin Backend URL configuration not reflecting on app network

### ISSUE THREAD

**Issue by okechukwu0127** [medusajs/medusa#10190]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "bcrypt": "^5.1.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.14",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-jest": "^29.2.5",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v2.0.4

### Database and its version

PostgreSQL 13.5 (Debian 13.5-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

### Operating system name and version

MacBook Pro , Sonoma 14.5

### Browser name

Chrome

### What happended?

I updated the medusa-config.js file to include the admin configuration as follows:

```admin: 
  {  
      path: "/api/market-place-2/app",   
      backendUrl: "http://localhost:9000/api/market-place-2",
  }
```
 
After loading the admin login page at `http://localhost:9000/api/market-place-2/app/login`, I attempted to log in but its not working as expected.

### Expected behavior

I expected the emailpass URL to include the path specified in the admin.backendUrl configuration, resulting in http://localhost:9000/api/market-place-2/auth/user/emailpass. 
However, upon inspecting the network requests, the URL being used was http://localhost:9000/auth/user/emailpass, which ignores the path setting in the configuration. 

<img width="1369" alt="image" src="https://github.com/user-attachments/assets/0b399292-0e1c-43f3-95e5-422942f98ac7">

### Actual behavior

Medusa 2 on the network resolves to http://localhost:9000/auth/user/emailpass 

while I was expetcting it to resolve to 
http://localhost:9000/api/market-place-2/auth/user/emailpass

### Link to reproduction repo

https://github.com/okechukwu0127/medusa-2.0.4

**Comment by phelian23** [comment]
Also facing same issue. This behavior causes the login flow to break for setups requiring custom paths.

**Comment by kasperkristensen** [comment]
Hi @okechukwu0127,

Can you explain why you want to set the backendUrl to "http://localhost:9000/api/market-place-2"? The issue occurs because our `js-sdk` only uses the `origin` of the baseUrl that it is given, in this case the `backendUrl`, which results in only `http://localhost:9000` being used to construct requests. We can change this behaviour, I am just not sure we should do that, so if you could describe your use case that would be great.

**Comment by okechukwu0127** [comment]
> Hi @okechukwu0127,
> 
> Can you explain why you want to set the backendUrl to "http://localhost:9000/api/market-place-2"? The issue occurs because our `js-sdk` only uses the `origin` of the baseUrl that it is given, in this case the `backendUrl`, which results in only `http://localhost:9000` being used to construct requests. We can change this behaviour, I am just not sure we should do that, so if you could describe your use case that would be great.

Thank you very much for your response. I appreciate.
The use case for setting the backendUrl to http://localhost:9000/api/market-place-2 is rooted in the architecture of our system. We use an API Gateway to route requests to various services within our application infrastructure. The Medusa backend is one of these services, and it operates behind the API Gateway.

**Why is the Custom Path Important?**
The custom path (/api/market-place-2) is essential for the API Gateway to correctly route incoming requests to the appropriate service. Without this custom route:
Ambiguity in Routing: The API Gateway cannot determine which service should handle requests directed to http://localhost:9000/.

**Conflict**: Other services managed by the API Gateway may also use similar endpoints (e.g., /auth/user/emailpass), causing conflicts or incorrect routing.
By specifying a custom path in the backendUrl, the API Gateway can unambiguously forward requests to the Medusa service. 

**For example**:
The API Gateway routes requests to http://localhost:9000/api/market-place-2/auth/user/emailpass to the Medusa backend.
Requests to other services (e.g., /api/another-service/) are routed elsewhere.

NB: In version 1.2, the backendUrl works as expected without ignoring the path set.

**Comment by kasperkristensen** [comment]
@okechukwu0127 thanks for the explanation. I'll open a PR to preserve the path.
