### ISSUE TITLE
Docs Error: POST /store/payment-collections "Unrecognized fields: 'region_id'"

### ISSUE THREAD

**Issue by roberttolton** [medusajs/medusa#10215]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The current sample cURL code for 'Create Payment Collection' is below:

```
curl -X POST '{backend_url}/store/payment-collections' \
-H 'Content-Type: application/json' \ \
-H 'x-publishable-api-key: {your_publishable_api_key}'
--data-raw '{
  "cart_id": "{value}",
  "region_id": "{value}",
  "currency_code": "{value}",
  "amount": 8468325826822144
}'
```

However, if you include a `region_id` field, you get an error:

```
error:   Invalid request: Unrecognized fields: 'region_id'
MedusaError: Invalid request: Unrecognized fields: 'region_id'
    at zodValidator (/redacted/node_modules/@medusajs/framework/src/zod/zod-helpers.ts:126:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async validateBody (/redacted/node_modules/@medusajs/framework/src/http/utils/validate-body.ts:30:27) {
  __isMedusaError: true,
  type: 'invalid_data',
  code: undefined,
  date: 2024-11-22T02:03:28.319Z
}
```

### How can this issue be resolved?

The documentation example should only include fields that are valid for the request.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for reporting this! Will open a PR to fix it
