### ISSUE TITLE
[Bug]: Create Return api not working

### ISSUE THREAD

**Issue by kalpesh-git** [medusajs/medusa#10216]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v22.11.0

### Database and its version

PostgreSQL 14.14

### Operating system name and version

mac m2

### What happended?

postman response : 
=============================
{
    "code": "unknown_error",
    "type": "unknown_error",
    "message": "An unknown error occurred."
}

log error:
=============
error:   Cannot read properties of undefined (reading 'items')
{
  message: "Cannot read properties of undefined (reading 'items')",
  name: 'TypeError',
  stack: "TypeError: Cannot read properties of undefined (reading 'items')\n" +
    '    at Object.<anonymous> (/private/var/www/shopper-backend-v2/my-medusa-store-v2/node_modules/@medusajs/core-flows/src/order/workflows/return/create-complete-return.ts:227:16)\n' +
    '    at Object.invoke (/private/var/www/shopper-backend-v2/my-medusa-store-v2/node_modules/@medusajs/workflows-sdk/src/utils/composer/helpers/create-step-handler.ts:72:67)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async DistributedTransaction.handler (/private/var/www/shopper-backend-v2/my-medusa-store-v2/node_modules/@medusajs/orchestration/src/workflow/workflow-manager.ts:214:16)\n' +
    '    at async stepHandler (/private/var/www/shopper-backend-v2/my-medusa-store-v2/node_modules/@medusajs/orchestration/src/transaction/transaction-orchestrator.ts:806:20)\n' +
    '    at async Promise.allSettled (index 0)\n' +
    '    at async promiseAll (/private/var/www/shopper-backend-v2/my-medusa-store-v2/node_modules/@medusajs/utils/src/common/promise-all.ts:23:18)\n' +
    '    at async TransactionOrchestrator.executeNext (/private/var/www/shopper-backend-v2/my-medusa-store-v2/node_modules/@medusajs/orchestration/src/transaction/transaction-orchestrator.ts:934:7)\n' +
    '    at async executeNext (/private/var/www/shopper-backend-v2/my-medusa-store-v2/node_modules/@medusajs/orchestration/src/transaction/transaction-orchestrator.ts:982:14)\n' +
    '    at async TransactionOrchestrator.resume (/private/var/www/shopper-backend-v2/my-medusa-store-v2/node_modules/@medusajs/orchestration/src/transaction/transaction-orchestrator.ts:997:5)\n' +
    '⮑ sat /private/var/www/shopper-backend-v2/my-medusa-store-v2/node_modules/@medusajs/core-flows/dist/order/workflows/return/create-complete-return.js: [create-complete-return-order -> create-return-order-validation (invoke)]'
}

### Expected behavior

don't know

### Actual behavior

don't know

### Link to reproduction repo

https://github.com/medusajs/medusa

**Comment by sradevski** [comment]
Please provide more information on what you are trying to do, what calls happened, and if you did any customizations. Also it'd be useful if you do some debugging before you open a ticket and provide that info so we can know where to focus.

**Comment by sradevski** [comment]
Closing due to lack of information. Feel free to open a new issue with more information
