### ISSUE TITLE
How to create a product?

### ISSUE THREAD

**Issue by stelasido** [medusajs/medusa#10221]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Im following the example from here to create a product: https://docs.medusajs.com/resources/commerce-modules/product
I see this: 
`
  message: 'Product "Medusa Shirt" has variants with missing options: [Black Shirt]',
  name: 'Error',
  stack: 'Error: Product "Medusa Shirt" has variants with missing options: [Black Shirt]\n' +`
With the example, there aren't options in product, Ive tried with it and changed like: 

```
    const products = await productService.createProducts([
      {
        title: "Medusahhhhhhhhhhhhhhhhhhhhh Shirt",
        options: [
          {
            title: "Color121", 
            values: ["black1111"], // not from docs
          },
        ],
        variants: [
          {
            title: "Blackttttttttttttttt Shirt", 
            options: [
              {
                value: "black1111", 
              },
            ],
          },
        ],
      },
    ]);

still the same.
And like that:
```
    const products = await productService.createProducts([
      {
        title: "Medusahhhhhhhhhhhhhhhhhhhhh Shirt",
        options: [
          {
            
            title: "Color121", // Define the option title for the product
            values: ["black1111"], // Provide the possible values for the option
          },
        ],
        variants: [
          {
            title: "Color121", // Variant title
            option: 'black1111',
            value: 'black1111',
            options: ["black1111"],
          },
        ],
      },
    ]);

```

`error:   Product "Medusahhhhhhhhhhhhhhhhhhhhh Shirt" has variants with missing options: [Color121]`


```

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by sradevski** [comment]
Hey @stelasido the request should look something like this:
```
service.createProducts({
            title: "product 1",
            status: ProductStatus.PUBLISHED,
            options: [
              {
                title: "opt-title",
                values: ["val-1", "val-2"],
              },
            ],
            variants: [
              {
                id: "variant-1",
                title: "variant 1",
                options: { "opt-title": "val-1" },
              },
            ],
          })
```

I'll open a PR to update the docs

**Comment by stelasido** [comment]
> Hey @stelasido the request should look something like this:
> 
> ```
> service.createProducts({
>             title: "product 1",
>             status: ProductStatus.PUBLISHED,
>             options: [
>               {
>                 title: "opt-title",
>                 values: ["val-1", "val-2"],
>               },
>             ],
>             variants: [
>               {
>                 id: "variant-1",
>                 title: "variant 1",
>                 options: { "opt-title": "val-1" },
>               },
>             ],
>           })
> ```
> 
> I'll open a PR to update the docs

There is an error with it:  
select "p0".* from "public"."product_option_value" as "p0" where "p0"."id" in ('optval_01JEZ96WP37EG17RP3FENVBJ6P') - current transaction is aborted, commands ignored until end of transaction block
{
  message: `select "p0".* from "public"."product_option_value" as "p0" where "p0"."id" in ('optval_01JEZ96WP37EG17RP3FENVBJ6P') - current transaction is aborted, commands ignored until end of transaction block`,
