### ISSUE TITLE
"All your dependencies are belong to us"

### ISSUE THREAD

**Issue by IanDarwin** [medusajs/medusa#1024]
There are so many warnings about insecure or unmaintained dependencies that one hesitates to trust this software...

"medusa new xxx -seed" produced these; an equally-impressive lot was generated from npm install medusa-cli.

npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/pinpoint@1.0.2: Moved to 'npm install @sideway/pinpoint'
npm WARN deprecated @hapi/formula@1.2.0: Moved to 'npm install @sideway/formula'
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated cli-ux@5.6.7: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated @hapi/joi@16.1.8: Switch to 'npm install joi'
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

**Comment by vkpdeveloper** [comment]
I think the repo is not maintained well. A lot of bugs and deprecations are in the project.

**Comment by microbuilder** [comment]
I have to agree with this a bit. I'm quite interested in the project, but the number of dependencies, and the quantity of unmaintained ones, is definitely a major concern. A good goal for an upcoming release would be to try to reduce the dependency list, and see is some of these can be replaced with something maintained.

**Comment by drbeanut** [comment]
its just too clunky. this what happen when u rely on so much 3rd party software!!!

**Comment by srindom** [comment]
Hey everyone! Thanks for pointing this out - we are aware of the issue already and have begun a larger migration to Typescript in which we will also be cleaning up dependencies.
