### ISSUE TITLE
Missing page in docs

### ISSUE THREAD

**Issue by flaturtha** [medusajs/medusa#10266]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Link on https://docs.medusajs.com/api/admin#workflows ("… this guide …") points to https://docs.medusajs.com/customization/extend-models/extend-create-product but that shows Page Not Found

### How can this issue be resolved?

1. Find old page or recreate
2. Correct lonk
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch! Will open a PR to fix it

**Comment by flaturtha** [comment]
I'm an experienced editor and writer. If I can help with copy editing, etc., I'm more than happy to contribute. Please reach out if needed.
