### ISSUE TITLE
Missing Documentation in Orders Events

### ISSUE THREAD

**Issue by amatosc** [medusajs/medusa#10272]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Under the Orders Events section, only the `order.placed` event is documented. However, it seems that the `order.canceled` event is also supported and works as expected.

### How can this issue be resolved?

1. Add documentation for this event as well.
2. In version 1, events like order.updated were available but are not mentioned in the current documentation. It would be great to include details on how to use them, or alternatives if they’re no longer available.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for reporting this! Will look into updating the events
