### ISSUE TITLE
page not found

### ISSUE THREAD

**Issue by kimhwanhoon** [medusajs/medusa#10281]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I wanted to read more about this url but got not found error page.

`https://docs.medusajs.com/resources/references/payment/modules/PaymentSession`

# Error situation
url: https://docs.medusajs.com/resources/commerce-modules/payment/payment-session
## What's a Payment Session?
A payment session, represented by the [PaymentSession data model](https://docs.medusajs.com/resources/references/payment/modules/PaymentSession), is a payment amount to be authorized. It’s associated with a payment provider that handles authorizing it.

___

When clicking `PaymentSession data model` it leads to not found page.

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [x] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for reporting this issue! Will open a PR to fix it.
