### ISSUE TITLE
Not able redirect to a different custom page after login.

### ISSUE THREAD

**Issue by haricoddle** [medusajs/medusa#10283]
I am facing an issue with redirecting to another page after successfully logging into the admin panel. I want my application to redirect to another custom page that I have created and I’ve tried troubleshooting but haven’t been able find a solution. Could there be a potential fix for this, or am I missing something critical in the implementation?

**Comment by riqwan** [comment]
Hey @haricoddle,

This is not a feature we currently support. Can you share your use-case a bit more in detail? (the business case)

Where would you like to redirect to? What does this page consist of, what benefits you see from doing this, etc?

**Comment by haricoddle** [comment]
Hi @riqwan 

I had created a separate Product's page apart from the one that was being  provided by the medusa, and I want the page to be redirect to the product page after the login, actually it was the requirement from the other side.

**Comment by riqwan** [comment]
Thanks @haricoddle, unforuntately this isn't something we provide as a customisable option.

**Comment by haricoddle** [comment]
oh ok...anyway thanks for the reply..much appreciated @riqwan .
