### ISSUE TITLE
Password reset event subscriber - actor_type variable incorrect

### ISSUE THREAD

**Issue by subnebula** [medusajs/medusa#10304]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

On this [page](https://docs.medusajs.com/resources/commerce-modules/auth/reset-password#1-create-subscriber) the actor type is defined as `actor_type` both in the description and in the code snippet however the actor type in the [workflow](https://github.com/medusajs/medusa/blob/b024c6c558a4ca8f7826ff9daaf0ed85fedcb6c0/packages/core/core-flows/src/auth/workflows/generate-reset-password-token.ts) is returned as `actorType`.

Given the entity id is returned as `entity_id` it probably makes this less of a documentation issue and just a typo in the code as it would make sense for the actor id to be `actor_id`. 

I'm happy to submit a PR to fix this if needed, just let me know if it's better to fix up the doco or the workflow code!

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by kasperkristensen** [comment]
Hi @subnebula, thanks for the report. You are right it's a typo. I have gone ahead and made a PR that deprecates `actorType`. For the time being we will return both `actorType` and `actor_type`, and then `actorType` will be removed in a future release.
