### ISSUE TITLE
Can't find some pages for the custom plugin docs

### ISSUE THREAD

**Issue by haricoddle** [medusajs/medusa#10334]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

**Can't find the page** : "https://docs.medusajs.com/development/entities/create",
![Screenshot 2024-11-28 at 11 34 04](https://github.com/user-attachments/assets/8a2764ad-d25f-4bc0-9803-60066d142060)

this is one page, there are some other pages also showing "Page Not Found", in the docs for building a custom plugin.

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Hey, all v1 docs are now at https://docs.medusajs.com/v1

Closing this issue, feel free to re-open if you have other info.
