### ISSUE TITLE
[Bug]: API call POST update cart (Store) using Postman

### ISSUE THREAD

**Issue by dooke** [medusajs/medusa#10347]
### Package.json file

```JSON
{
  "name": "nextjs-layout-app-dir",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@medusajs/js-sdk": "^2.0.1",
    "@medusajs/medusa": "^1.20.10",
    "@medusajs/medusa-js": "^6.1.9",
    "@medusajs/types": "^2.0.1",
    "@tanstack/react-query": "^5.59.20",
    "add": "^2.0.6",
    "ag-grid-community": "^32.3.3",
    "ag-grid-react": "^32.3.3",
    "autoprefixer": "10.4.14",
    "bootstrap": "^5.3.3",
    "classnames": "^2.5.1",
    "client-only": "^0.0.1",
    "cookies-next": "^4.3.0",
    "datatables.net": "^2.1.8",
    "datatables.net-bs5": "^2.1.8",
    "datatables.net-dt": "^2.1.8",
    "eslint": "8.40.0",
    "eslint-config-next": "13.4.1",
    "js-cookies": "^1.0.4",
    "lodash": "^4.17.21",
    "medusa-react": "^9.0.18",
    "moment": "^2.30.1",
    "next": "^14.2.15",
    "path": "^0.12.7",
    "react": "18.2.0",
    "react-accessible-treeview": "^2.10.0",
    "react-bootstrap": "^2.10.5",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.53.1",
    "react-hot-toast": "^2.4.1",
    "react-icons": "^5.3.0",
    "reactstrap": "^9.2.3",
    "sass": "^1.79.5",
    "server-only": "^0.0.1",
    "sweetalert2": "^11.14.3"
  },
  "devDependencies": {
    "@babel/core": "^7.25.8",
    "@babel/eslint-parser": "^7.25.8",
    "@typescript-eslint/eslint-plugin": "^8.8.1",
    "@typescript-eslint/parser": "^8.8.1",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-import-resolver-alias": "^1.1.2",
    "eslint-plugin-react": "^7.37.1",
    "eslint-plugin-react-hooks": "^5.0.0"
  }
}
```

### Node.js version

v20.17.0

### Database and its version

PostGresSQL 13

### Operating system name and version

Mac Os

### Browser name

Brave/Chrome

### What happended?

**Bug 1**: According to this endpoint - documentation https://docs.medusajs.com/api/store#carts_postcartsid
In the request body we are able to pass on "Request Body" customer_id parameter

Using Postman calling : POST http://localhost:9000/store/carts/cart_xxxx
With this body: { "customer_id": "cus_yyyy" }
Response Body : {
    "type": "invalid_data",
    "message": "Invalid request: Unrecognized fields: 'customer_id'"
}

**Bug 2**: Endpoint https://docs.medusajs.com/api/store#carts_postcartsidcustomer exists but i assume it's for transferring/setting a cart after user sign in like described.
In documentation the Request Body parameters are missing. I suppose this is the same format as previous endpoint but still get the same error.

Using Postman calling : POST http://localhost:9000/store/carts/cart_xxxx/customer
With this body: { "customer_id": "cus_yyyy" }
Response Body : {
    "type": "invalid_data",
    "message": "Invalid request: Unrecognized fields: 'customer_id'"
}

### Expected behavior

Cart Object

### Actual behavior

Error {
    "type": "invalid_data",
    "message": "Invalid request: Unrecognized fields: 'customer_id'"
}

### Link to reproduction repo

http://localhost:9000

**Comment by fPolic** [comment]
hey @dooke, for assigning a cart to a registered customer you should use the second endpoint as you mentioned. The cart will be assigned to the logged-in customer so `customer_id` param is not needed.

We will update the docs regarding the first issue.
