### ISSUE TITLE
Inventory Module Documentation page is not available

### ISSUE THREAD

**Issue by rameshlamba** [medusajs/medusa#10358]
### What Medusa version and documentation are you using?

None

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Inventory Module Documentation page is not available

### How can this issue be resolved?

1. Add or  Update the Inventory Module Documentation page is link
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Hello! Can you clarify more where you're trying to access it from? It's available [here](https://docs.medusajs.com/resources/commerce-modules/inventory) and you can access it from the sidebar and other overview pages.

**Comment by rameshlamba** [comment]
I am trying to access inventroy module documentation [link](https://docs.medusajs.com/modules/multiwarehouse/inventory-module) from  https://medusajs.com/inventory-module/

**Comment by shahednasser** [comment]
You're right it's incorrect there. Will relay it to the associated team and close this. Thanks!
