### ISSUE TITLE
[Bug]: Price Lists

### ISSUE THREAD

**Issue by v-darko** [medusajs/medusa#10357]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

![Screenshot from 2024-11-28 20-35-35](https://github.com/user-attachments/assets/4bae1675-0d77-496d-92f8-bbdd18908a34)
![Screenshot from 2024-11-28 20-37-56](https://github.com/user-attachments/assets/5ea6b2f2-a903-460a-b567-e01373d0a67b)

### Node.js version

v20.18.1

### Database and its version

PostgreSQL 16.6

### Operating system name and version

Ubuntu 24.04

### Browser name

Chrome

### What happended?

1. I have added a price list for a customer group that contains a 5% discount on a certain item.
2. As a customer in this group, I added the discounted item to my cart.
3. Then I removed this pricelist
4. As a customer I tried to clear the cart and got an error.

I just downloaded Medusa and tested it without any changes in the code.

### Expected behavior

If I remove any discounts such as price lists, customer can delete previously discounted items from the cart.

### Actual behavior

Customer has items with discounts in their cart and can't delete them

### Link to reproduction repo

https://github.com/medusajs/medusa

**Comment by olivermrbl** [comment]
@v-darko, it seems your issue is related to promotions and not price lists. We will look into this issue.

Can I get you to try the price list functionality without a promotion applied on the cart?

So:
- Create price list for customer group
- Sign in as customer
- Add item to cart
- Delete price list
- Delete item from cart

**Comment by v-darko** [comment]
> @v-darko, it seems your issue is related to promotions and not price lists. We will look into this issue.
> 
> Can I get you to try the price list functionality without a promotion applied on the cart?

Oh sorry, yes it is related to promotions. And i'm just testing medusa 2.0 before update.
