### ISSUE TITLE
[Bug]: error code `EADDRINUSE` when deploying in worker mode per deployment instructions

### ISSUE THREAD

**Issue by pmessan** [medusajs/medusa#10378]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "migrations": "medusa migrations run",
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa db:migrate && medusa start",
    "dev": "medusa develop",
    "predeploy": "medusa db:migrate",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v22.11.0

### Database and its version

PostgreSQL 16.4

### Operating system name and version

Ubuntu 24.04.1

### Browser name

Chrome

### What happended?

I am trying to deploy medusa on an Ubuntu server using the guide available [here](https://docs.medusajs.com/learn/deployment/general).  I cannot access the admin page after I deploy medusa (blank page in browser, 403 reported on server).
The building and running in server mode seems to work fine, but the running in worker mode fails with the following error (in the worker logs):

```text
Error: listen EADDRINUSE: address already in use :::9000
    at Server.setupListenHandle [as _listen2] (node:net:1907:16)
    at listenInCluster (node:net:1964:12)
    at Server.listen (node:net:2066:7)
    at internalStart (/home/webadmin/repos/pjfmess.com-worker/node_modules/@medusajs/medusa/src/commands/start.ts:142:15)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async start (/home/webadmin/repos/pjfmess.com-worker/node_modules/@medusajs/medusa/src/commands/start.ts:227:5) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 9000
}
```

I have a copy of the repo in 2 separate directories and am using direnv to load different env variables for each folder before running `npm run build && .medusa/server && npm run start`. 

server .envrc
```shell
export COOKIE_SECRET=supersecret
export JWT_SECRET=supersecret
export STORE_CORS=http://localhost:8000
export ADMIN_CORS=http://localhost:9000
export AUTH_CORS=http://localhost:9000
export DISABLE_MEDUSA_ADMIN=false
export REDIS_URL=redis://localhost:6379
export DB_NAME=medusa-website.com
export DATABASE_URL=postgres://medusa:**********@localhost/$DB_NAME
export MEDUSA_BACKEND_URL=http://localhost:9000
export MEDUSA_WORKER_MODE=server
export PORT=9000
```

worker .envrc
```shell
export COOKIE_SECRET=supersecret
export JWT_SECRET=supersecret
export DISABLE_MEDUSA_ADMIN=true
export REDIS_URL=redis://localhost:6379
export DB_NAME=medusa-website.com
export DATABASE_URL=postgres://medusa:**********@localhost/$DB_NAME
export MEDUSA_WORKER_MODE=worker
export PORT=9000
```

medusa-config.ts is the same for both

```typescript

import { loadEnv, defineConfig } from '@medusajs/framework/utils'

loadEnv(process.env.NODE_ENV || 'development', process.cwd())

module.exports = defineConfig({
  projectConfig: {
    databaseUrl: process.env.DATABASE_URL,
    http: {
      storeCors: process.env.STORE_CORS!,
      adminCors: process.env.ADMIN_CORS!,
      authCors: process.env.AUTH_CORS!,
      jwtSecret: process.env.JWT_SECRET || "supersecret",
      cookieSecret: process.env.COOKIE_SECRET || "supersecret",
    },
    workerMode: process.env.MEDUSA_WORKER_MODE as "shared" | "worker" | "server",
    redisUrl: process.env.REDIS_URL
  },
  admin: {
    disable: process.env.DISABLE_MEDUSA_ADMIN === "true",
    backendUrl: process.env.MEDUSA_BACKEND_URL,
  },
  modules: [
    {
      resolve: "@medusajs/medusa/cache-redis",
      options: {
        redisUrl: process.env.REDIS_URL,
      },
    },
    {
      resolve: "@medusajs/medusa/event-bus-redis",
      options: {
        redisUrl: process.env.REDIS_URL,
      },
    },
    {
      resolve: "@medusajs/medusa/workflow-engine-redis",
      options: {
        redis: {
          url: process.env.REDIS_URL,
        },
      },
    },
  ],
})
```

### Expected behavior

Deployment of medusa succeeds both in server mode and worker mode, enabling me to access the admin page

### Actual behavior

health check reports OK (on the server side 304), but navigating to /app results in a 403 with the following error message server side:

```text
2:34:20 PM [vite] Pre-transform error: Failed to load url /entry.tsx (resolved id: /home/webadmin/repos/pjfmess.com-server/node_modules/@medusajs/admin-bundler/dist/entry.tsx). Does the file exist?
```

I can confirm the file does indeed exist.

### Link to reproduction repo

https://github.com/PJFMess-Enterprise/medusa-debug

**Comment by fPolic** [comment]
hey @pmessan, it seems that you are trying to run 2 Medusa instances on the same port of the server. The guide assumes that you are deploying in 2 different deployments or Docker containers etc.

Since you are running on a single server, you could run a single Medusa instance in the "shared" mode.

**Comment by Deroswent** [comment]
@fPolic Hi and thanks for your reply. Could you please explain how two medusa instances, in server + worker mode “communicate” with each other?

I have deployed two instances in server and worker mode. Everything works, but the worker is always idle.  It literally does nothing, even though I've done load testing, created thousands of products with a single request, filled them via CSV and did a lot of weird things to maximize the load on the server.
It didn't give any result, only the server always works. The instance that is running in worker mode has literally not received a single request and has not started a single workflow.

**Comment by fPolic** [comment]
hey @Deroswent, communication is happening via a message queue - worker instance will run Subscribers that listen for an event or Jobs that run periodically in a separate process.

You can read more about the worker mode [here](https://docs.medusajs.com/resources/references/medusa-config#workermode).

**Comment by yannickschuchmann** [comment]
hey, I am running into the same problem with the port being used already by the server.
Unfortunately the logs are not much verbose. **It would be very helpful to see the mode when a medusa instance starts.** I pass `MEDUSA_WORKER_MODE` as worker and as server. But I don't see if it is picked up correctly.

@fPolic could you shine some light why there is a PORT being used in a worker? For me it looks like it is not picking up the right mode and therefore tries to spin up a server on the same PORT. If the worker would need a port, wouldn't the docs then mention that as well besides talking about how to just set the mode itself?

Trying really not to complain, so rather as a feedback: the medusa developer experience still feels often like guessing, even tho the docs got much better over the last half of a year.

```
workerMode: process.env.MEDUSA_WORKER_MODE as
      | "shared"
      | "worker"
      | "server",
```

```
pm2 start "MEDUSA_WORKER_MODE=worker DISABLE_MEDUSA_ADMIN=true NODE_ENV=production pnpm medusa start" --name medusa-worker
```

I know NODE_ENV now defaults to production for medusa start. That's what I mean with the "guessing". there is this overall feeling to not know if it is also true for the worker mode. Because `medusa db:migrate` does not default to production. And that default is at least afaik not standard in the landscape of frameworks.

Besides my ranting.. sorry for that.. any idea how I can debug / find out why the instance is not going into worker mode? 

---

```sh
3|medusa-worker  | {"activity_id":"01JTBY5CEM60SHA4BA0T7656N0","config":{},"level":"info","message":"Creating server","timestamp":"2025-05-03 20:42:18"}
3|medusa-worker  | Error: listen EADDRINUSE: address already in use :::9000
3|medusa-worker  |     at Server.setupListenHandle [as _listen2] (node:net:1904:16)
3|medusa-worker  |     at listenInCluster (node:net:1961:12)
3|medusa-worker  |     at Server.listen (node:net:2063:7)
3|medusa-worker  |     at internalStart (/home/deployer/lovely-leaves-repo/medusa/node_modules/.pnpm/@medusajs+medusa@2.7.1_12ce7ab1f34b2611407d53648e3562aa/node_modules/@medusajs/medusa/src/commands/start.ts:208:15)
3|medusa-worker  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
3|medusa-worker  |     at async start (/home/deployer/lovely-leaves-repo/medusa/node_modules/.pnpm/@medusajs+medusa@2.7.1_12ce7ab1f34b2611407d53648e3562aa/node_modules/@medusajs/medusa/src/commands/start.ts:290:5) {
3|medusa-worker  |   code: 'EADDRINUSE',
3|medusa-worker  |   errno: -98,
3|medusa-worker  |   syscall: 'listen',
3|medusa-worker  |   address: '::',
3|medusa-worker  |   port: 9000
3|medusa-worker  | }
```

**Comment by siddharthrawal121** [comment]
@yannickschuchmann you figured it out?
