### ISSUE TITLE
[BUG] Mark draft order endpoint wrong in `medusa-js`

### ISSUE THREAD

**Issue by olivermrbl** [medusajs/medusa#1038]
**What**
The endpoint to mark a draft order paid is `/pay`, but in `medusa-js` we currently have `/register-payment`.

**How**
Change [this line](https://github.com/medusajs/medusa/blob/80e86ca08c6d825797bbb783484c21fb92a33a9c/packages/medusa-js/src/resources/admin/draft-orders.ts#L86) to be `/pay`

**Comment by RishiKumarRay** [comment]
const path = `/admin/draft-orders/${id}/pay`
@olivermrbl is this what you are saying ?

**Comment by olivermrbl** [comment]
Yes exactly! @RishiKumarRay

**Comment by RishiKumarRay** [comment]
@olivermrbl can you please review the PR

**Comment by olivermrbl** [comment]
Solved in #1046
