### ISSUE TITLE
fatal: Remote branch v2 not found in upstream origin

### ISSUE THREAD

**Issue by bilofy** [medusajs/medusa#10396]
### What Medusa version and documentation are you using?

None

### Preliminary Checks

- [x] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

```bash
git clone https://github.com/medusajs/nextjs-starter-medusa -b v2 my-medusa-storefront
Cloning into 'my-medusa-storefront'...
fatal: Remote branch v2 not found in upstream origin
```

The V2 branch does not exist. Should be corrected in your documentation.
https://docs.medusajs.com/resources/nextjs-starter#installation

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by fPolic** [comment]
thanks @bilodev7, we will update the docs
