### ISSUE TITLE
Don't understand this discount behaviour

### ISSUE THREAD

**Issue by BorisKamp** [medusajs/medusa#10407]
Using medusa `1.20.10`, im creating a custom endpoint to create a Medusa order out of a shopify order.

I have uploaded the `src/api/admin/orders/shopify/route.ts` file here as zip, as `.ts` files are not allowed.
[route.ts.zip](https://github.com/user-attachments/files/17991441/route.ts.zip)

On line `202` you see I start with the discounts logic. The discount is created, i see it in the medusa admin UI, but the `rendeemed` count stays at `0`. The `cart.discounts` is empty as well, as is the `cart.discount_total`. However, I see each `item.adjustments` has one entry. But this is NOT what I want, I don't need the adjustments, I need the discounts.

When I return the endpoint before line `202`, and I then call `{{medusa-host}}/store/carts/cart_01JE615RCWB32J85WMFKBTE56S` manually with a discount code, I DO have the expected behaviour: discounts are set on the cart.

Why is this?

**Comment by sradevski** [comment]
Hi there, 

Unfortunately we are not working on any improvements or fixes to v1 of Medusa, unless it is a critical or a security bug. Freel free to open a PR and we'll look into it. Closing the issue in the meantime

**Comment by BorisKamp** [comment]
> Hi there,
> 
> Unfortunately we are not working on any improvements or fixes to v1 of Medusa, unless it is a critical or a security bug. Freel free to open a PR and we'll look into it. Closing the issue in the meantime

Well that’s easy😅

i bet 90% or more is on V1 but you drop the support. V2 dont get me wrong, I appreciate the work and Medusa hugely but V2 is not even fully functional for us as Stripe support is missing.

I understand if this choice to not support V1 is made a year or two years from now, but at this moment?

**Comment by sradevski** [comment]
We are a small team, and it's important to prioritize carefully. As I said, we are still open to community contributions, but the core team is too small to fix every single issue and edge case that shows up in v1.

Stripe is supported in v2, not sure why there was the impression that it isn't
