### ISSUE TITLE
[Bug]: New update 2.1.0 - Problem with refresh shipping method price

### ISSUE THREAD

**Issue by Arrowkuu** [medusajs/medusa#10451]
### Package.json file

```JSON
{
  "name": "medusa",
  "version": "1.0.0",
  "description": "Medusa",
  "author": "Medusa",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "migrate": "medusa db:migrate && medusa db:sync-links",
    "medusa-cli": "medusa",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "install:deps": "yarn install --non-interactive"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "2.1.0",
    "@medusajs/cli": "2.1.0",
    "@medusajs/framework": "2.1.0",
    "@medusajs/medusa": "2.1.0",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "@types/jsonwebtoken": "^9.0.7",
    "awilix": "^8.0.1",
    "axios": "^1.7.5",
    "express": "^4.21.0",
    "jsonwebtoken": "^9.0.2",
    "nodemailer": "^6.9.15",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "2.1.0",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/express": "^5.0.0",
    "@types/jest": "^29.5.14",
    "@types/node": "^20.0.0",
    "@types/nodemailer": "^6.4.16",
    "jest": "^29.7.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v22.11.0

### Database and its version

PostgreSQL 16.2

### Operating system name and version

Linux

### What happended?

I am currently testing a new feature i.e. price rules for shipping options, all elements with shipping options works good, pricing of shipping options was changed if the price threshold will be exceeded - but problem is with update a shipping method inside cart. Price is not updated. I think problem is in one workflow step `refreshCartShippingMethodsStep` - it does not accept new content.

If I'm wrong, let me know..

### Expected behavior

Price of shipping method must be updated when cart is loaded.

### Actual behavior

Now price in shipping method is without shipping option price rules.

### Link to reproduction repo

https://github.com/medusajs/medusa/blob/v2.1.0/packages/core/core-flows/src/cart/steps/refresh-cart-shipping-methods.ts

**Comment by Arrowkuu** [comment]
I think you need to add `total` inside a `cartFieldsForRefreshSteps`, total value is missing and the `addShippingMethodToCartWorkflow` does not calculate pricing includes `total` attribute.

Then in `refreshCartShippingMethodsStep` problem is in validation, probably you need to add pricing validation here.

@riqwan

**Comment by paulkolle** [comment]
It works if you update the shipping address at the same time as updating the shipping method

**Comment by riqwan** [comment]
@Arrowkuu, sorry just saw this. This feature wasn't ready to be used yet. I just merged in the last piece, can you try again?

**Comment by Arrowkuu** [comment]
Update is on 2.1.0 release?

**Comment by riqwan** [comment]
No, its still on the develop branch, unreleased. As of the previous release, this feature is not functional yet.

**Comment by riqwan** [comment]
Closing this for now, we will have a new release tomorrow which will have this feature completed. Feel free to reopen if the issue persists after!
