### ISSUE TITLE
Admin Dashboard: Customers Groups list pagination disappeared in case groups amounts more 14 items in the list 

### ISSUE THREAD

**Issue by oz-verum** [medusajs/medusa#10461]
### Describe the bug

Hi devs, we have an issue in case adding more Customers Groups more than 14, the pagination panel hides and end users cannot going to the next page. Please help us to resolve this issue.

### System information

Medusa version 1.20.10 (including plugins):
       "@medusajs/admin": "^7.1.17",
        "@medusajs/cache-inmemory": "^1.8.11",
        "@medusajs/cache-redis": "^1.9.2",
        "@medusajs/event-bus-local": "1.9.9",
        "@medusajs/event-bus-redis": "^1.8.14",
        "@medusajs/icons": "1.2.2",
        "@medusajs/medusa": "^1.20.10",
        "@medusajs/medusa-cli": "latest",
        "@medusajs/ui": "^3.0.1",
        "@medusajs/utils": "1.11.11",

Node.js version: 18.20.4
Database:
Operating system: Ubuntu
Browser (if relevant): Chrome

### Steps to reproduce the behavior

1. Go to 'Customers'
2. Click on 'Groups'
3. Add 15 groups
4. Pagination Panel hides

### Expected behavior

See Group list up to 15 items with ability going to next page in case groups are more than 15.

### Screenshots

![groups14](https://github.com/user-attachments/assets/d61722be-d055-4cee-97d5-867f638ebbbd)
![groups15](https://github.com/user-attachments/assets/da2f4f87-7768-41b7-9b51-97950d140232)
If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by sradevski** [comment]
Hi there, since we are only backporting critical bugs to v1 at this point, you can either open a PR or upgrade to v2. I'll close the issue as we won't be working on it.
