### ISSUE TITLE
404 page -> [this guide](https://docs.medusajs.com/basics/modules) 

### ISSUE THREAD

**Issue by bilofy** [medusajs/medusa#10470]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

found it on this page:
https://docs.medusajs.com/resources/commerce-modules/product/extend#step-1-define-custom-data-model

Also other links on the same page lead to 404:
https://docs.medusajs.com/resources/commerce-modules/product/extend#step-2-define-link-to-product-data-model
https://docs.medusajs.com/resources/commerce-modules/product/extend#step-4-consume-productscreated-workflow-hook

Actually every link with this sentence leads to 404:

```
Tip: Learn more about x in [this guide](link).
```

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for reporting this! opened PR #10472 to fix the links
