### ISSUE TITLE
[Bug]: large dataset error - Maximum call stack size exceeded

### ISSUE THREAD

**Issue by chillpilllike** [medusajs/medusa#10496]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "predeploy": "medusa db:migrate",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/core-flows": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

20

### Database and its version

16

### Operating system name and version

22.04

### Browser name

safari

### What happended?

When I try to open storefront, it gives error 500 and backend give the below error:

[14:58:13.000] ERROR:
    message: "Maximum call stack size exceeded"
    stack: [
      {
        "columnNumber": 16,
        "fileName": "/app/.medusa/server/node_modules/@mikro-orm/core/platforms/ExceptionConverter.js",
        "functionName": "PostgreSqlExceptionConverter.convertException",
        "lineNumber": 8,
        "methodName": "convertException",
        "native": false,
        "typeName": "PostgreSqlExceptionConverter"
      },
      {
        "columnNumber": 22,
        "fileName": "/app/.medusa/server/node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js",
        "functionName": "PostgreSqlExceptionConverter.convertException",
        "lineNumber": 42,
        "methodName": "convertException",
        "native": false,
        "typeName": "PostgreSqlExceptionConverter"
      },
      {
        "columnNumber": 54,
        "fileName": "/app/.medusa/server/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js",
        "functionName": "PostgreSqlDriver.convertException",
        "lineNumber": 201,
        "methodName": "convertException",
        "native": false,
        "typeName": "PostgreSqlDriver"
      },
      {
        "columnNumber": 24,
        "fileName": "/app/.medusa/server/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js",
        "functionName": null,
        "lineNumber": 205,
        "methodName": null,
        "native": false,
        "typeName": null
      },
      {
        "columnNumber": 5,
        "fileName": "node:internal/process/task_queues",
        "functionName": "processTicksAndRejections",
        "lineNumber": 95,
        "methodName": null,
        "native": false,
        "typeName": null
      },
      {
        "columnNumber": 31,
        "fileName": "/app/.medusa/server/node_modules/knex/lib/formatter/wrappingFormatter.js",
        "functionName": "unwrapRaw",
        "lineNumber": 104,
        "methodName": null,
        "native": false,
        "typeName": null
      },
      {
        "columnNumber": 15,
        "fileName": "/app/.medusa/server/node_modules/knex/lib/formatter/wrappingFormatter.js",
        "functionName": "wrap",
        "lineNumber": 80,
        "methodName": null,
        "native": false,
        "typeName": null
      },
      {
        "columnNumber": 11,
        "fileName": "/app/.medusa/server/node_modules/knex/lib/query/querycompiler.js",
        "functionName": "QueryCompiler_PG.get tableName [as tableName]",
        "lineNumber": 1472,
        "methodName": "get tableName [as tableName]",
        "native": false,
        "typeName": "QueryCompiler_PG"
      },
      {
        "columnNumber": 13,
        "fileName": "/app/.medusa/server/node_modules/knex/lib/query/querycompiler.js",
        "functionName": "QueryCompiler_PG.onlyJson",
        "lineNumber": 800,
        "methodName": "onlyJson",
        "native": false,
        "typeName": "QueryCompiler_PG"
      },
      {
        "columnNumber": 25,
        "fileName": "/app/.medusa/server/node_modules/knex/lib/query/querycompiler.js",
        "functionName": "QueryCompiler_PG.columns",
        "lineNumber": 313,
        "methodName": "columns",
        "native": false,
        "typeName": "QueryCompiler_PG"
      },
      {
        "columnNumber": 40,
        "fileName": "/app/.medusa/server/node_modules/knex/lib/query/querycompiler.js",
        "functionName": null,
        "lineNumber": 135,
        "methodName": null,
        "native": false,
        "typeName": null
      },
      {
        "columnNumber": null,
        "fileName": null,
        "functionName": "Array.forEach",
        "lineNumber": null,
        "methodName": "forEach",
        "native": false,
        "typeName": "Array"
      },
      {
        "columnNumber": 16,
        "fileName": "/app/.medusa/server/node_modules/knex/lib/query/querycompiler.js",
        "functionName": "QueryCompiler_PG.select",
        "lineNumber": 134,
        "methodName": "select",
        "native": false,
        "typeName": "QueryCompiler_PG"
      },
      {
        "columnNumber": 29,
        "fileName": "/app/.medusa/server/node_modules/knex/lib/query/querycompiler.js",
        "functionName": "QueryCompiler_PG.toSQL",
        "lineNumber": 75,
        "methodName": "toSQL",
        "native": false,
        "typeName": "QueryCompiler_PG"
      },
      {
        "columnNumber": 41,
        "fileName": "/app/.medusa/server/node_modules/knex/lib/formatter/wrappingFormatter.js",
        "functionName": "unwrapRaw",
        "lineNumber": 102,
        "methodName": null,
        "native": false,
        "typeName": null
      }
    ]
[14:58:13.000] USERLVL:
    message: "172.18.0.1 - - [08/Dec/2024:14:58:13 +0000] \"GET /store/products?limit=1&offset=999999&region_id=reg_01JEE2P8Z6ESDR4XZPEHWNTDEB HTTP/1.1\" 500 86 \"-\" \"undici\""

### Expected behavior

The storefront should open

### Actual behavior

ERROR: message: "Maximum call stack size exceeded"

### Link to reproduction repo

https://github.com/medusajs/medusa-starter-default.git

**Comment by chillpilllike** [comment]
I have 130,000 products and tested it with 3 starters, they all were working fine till 130,000 then afterwards they give this error

**Comment by thetutlage** [comment]
Hello @chillpilllike 

It's impossible to debug this issue with the information you have provided. Please share the dataset size and also try to debug what length of result sets are getting returned in the response. 

Feel free to re-open the issue when you are able to debug it further and once you have enough information at hand that can help us reproduce this issue

**Comment by chillpilllike** [comment]
This is my backend url

https://secretgreen-au-backend-server.g5edov.easypanel.host/


I can not get products list even 10 products, fetching 10 products using offset now gives the error:

curl -X GET "https://secretgreen-au-backend-server.g5edov.easypanel.host/store/products?limit=1&offset=10" \
-H "x-publishable-api-key: pk_1f84a883e7f454772abcc1dd2ae1e3d562d64a5cf6b58f4c5e5e75bc2b1078a8" \
-H "Content-Type: application/json"

**Comment by chillpilllike** [comment]
I have increase the max_stack_depth = 7MB       from 2MB in postgres config file but still the error persists.

**Comment by thetutlage** [comment]
Where have you deployed your app and what is the server configuration?

**Comment by chillpilllike** [comment]
I have a bare metal server with 64 core cpu and 256 gb ram.
 currently on 5% resources are used.

**Comment by chillpilllike** [comment]
the store was working fine upto 100,000 then it started giving errors when it reached 130,000
