### ISSUE TITLE
[Bug]: Prices from price lists are not applicable when adding to cart.

### ISSUE THREAD

**Issue by Deroswent** [medusajs/medusa#10490]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

20.15.0

### Database and its version

PostgreSQL 16.4

### Operating system name and version

Windows 11

### What happended?

Clean  installation of Medusa 2.1 + official storefront, without any changes in the code.

Problem:
The price of an item in the cart = always the full price of the product variand, not including the price list.  

How to reproduce the problem:

1) Register as a customer on the storefront and authorize on the storefront.

2) In medusa backend, create a Customer group and add our customer to it.

3) In medusa backend, create two price lists: Sale type and Override type, make both price lists active by date and apply them to our Customer group.  Assign prices to any product variant: sale = 7 eur, override = 5 eur.

4) On the storefront (being an authorized customer) we look at the prices for our product variant - everything works fine and we see the price of 5 eur.  Add this variant to the cart.

5) Go to the cart and we see that the price of the cart is 10 eur (the full price of the product variant without price lists). This is the bug.

![2024-12-07_21-22](https://github.com/user-attachments/assets/103faf61-54c8-4a2a-9dca-e1c364432e00)

![2024-12-07_21-01](https://github.com/user-attachments/assets/39d384ee-b144-4378-9285-e2026888df2a)

If we check the database, we see that
1)Cart is linked to our user

![2024-12-07_21-23](https://github.com/user-attachments/assets/a141466c-3c8f-4f5a-8170-2818604af05b)

2) The price of line item in the unit_price field is 10 eur and not 5. 

![2024-12-07_21-24](https://github.com/user-attachments/assets/966eacec-bf12-4c51-972a-d5bfdbae42ed)

So this is not a storefront bug, but a bug in the core of Medusa.

### Expected behavior

The price of the item in the shopping cart should match the price on the storefront.

### Actual behavior

The price in the shopping cart is always the full price of the product without any price lists.

### Link to reproduction repo

https://github.com/medusajs/medusa

**Comment by sergiocampama** [comment]
I was looking into this today too. Was able to find that adding a product to a cart uses the `add-to-cart.ts` workflow which does not take into account the pricingContext coming in from the request.

Was trying to develop locally but it hasn't been super easy setting a reproducible development stack.

**Comment by sergiocampama** [comment]
apologies for the notification spam, had the ticket id in the commit and did some pushes
