### ISSUE TITLE
Access token for admin endpoints

### ISSUE THREAD

**Issue by jbesraa** [medusajs/medusa#1050]
Hello

Thanks for the great project.

How can I generate an access token to access the admin endpoint mentioned here https://docs.medusajs.com/api/admin/collection/create-a-product-collection ?

**Comment by labeneator** [comment]
Did you ever find out how to generate the access token? Can't find it anywhere in the docs

**Comment by olivermrbl** [comment]
@labeneator You should be able to follow our authentication guide [here](https://docs.medusajs.com/api/admin/) 👍

**Comment by camfeghali** [comment]
@olivermrbl Can you please explain this ? I have a admin user, but it's `api_token` column is empty. 

How can I generate one ?

**Comment by irab** [comment]
Just to help anyone, here's how to add a token to the admin user:

1. Open Dev Tools in Chrome
2. Find your admin userID by clicking 'Edit Information' and updating one of the name fields
3. Check the XHR POST request and the userID will be in the URL
<img width="681" alt="image" src="https://github.com/medusajs/medusa/assets/1463626/608d130a-2bfe-434b-acd0-3a6810d0b4ed">

4. Also in the request will be a `connect.sid` value in the Cookie.

Use both in the following cURL command to create an API token e.g.:

```bash
curl -L -X POST 'http://localhost:9000/admin/users/usr_01HNBKZ0Y1N2A02GMCWNGS2MV4' \
-H 'Cookie: connect.sid=s%3A0AYLa8FDlo2OdbpozH9etItCYyDyMlmO.ZP5Nlq6bIM7Xq4ZGNoMkKgupTG3keCODIKem6rXbxns' \
-H 'Content-Type: application/json' \
--data-raw '{
    "api_token": "put_whatever_you_want_here_lsdflsfljsldfjsdlfjslkfjs002342"
}'
```

Then you can call the following API to confirm the API token user:

```bash
curl 'http://localhost:9000/admin/auth' \
-H 'x-medusa-access-token: put_whatever_you_want_here_lsdflsfljsldfjsdlfjslkfjs002342'
```

You should see something like the following:
```json
{
  "user": {
    "id": "usr_01HNBKZ0Y1N2A02GMCWNGS2MV4",
    "created_at": "2024-01-29T22:03:16.696Z",
    "updated_at": "2024-01-30T00:01:38.998Z",
    "deleted_at": null,
    "role": "admin",
    "email": "admin@your-domain.com",
    "first_name": "Admin",
    "last_name": "Admin",
    "api_token": "put_whatever_you_want_here_lsdflsfljsldfjsdlfjslkfjs002342",
    "metadata": null
  }
}
```

**Comment by alexandrosk** [comment]
You can easily get the token by selecting checking the user table on postgresql db

**Comment by RajnandiniIngale** [comment]
@olivermrbl Is there a way to refresh access tokens in medusajs?

**Comment by kevin25** [comment]
> Just to help anyone, here's how to add a token to the admin user:
> 
> 1. Open Dev Tools in Chrome
> 2. Find your admin userID by clicking 'Edit Information' and updating one of the name fields
> 3. Check the XHR POST request and the userID will be in the URL
> 
> <img alt="image" width="681" src="https://private-user-images.githubusercontent.com/1463626/300636689-608d130a-2bfe-434b-acd0-3a6810d0b4ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODE4NjgsIm5iZiI6MTcxODc4MTU2OCwicGF0aCI6Ii8xNDYzNjI2LzMwMDYzNjY4OS02MDhkMTMwYS0yYmZlLTQzNGItYWNkMC0zYTY4MTBkMGI0ZWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTlUMDcxOTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGExZWIwZDMwYTQ3NzliN2QyNjVmOGUxMTNkMzNjNTdkYzE4MTY5YTYzMGY5MDI5NDQyODNiOTc5ZjE1NDczMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8ddmQknjC1EovZpV_dYJfFmJl1A363krH7yutWJAAWY">
> 4. Also in the request will be a `connect.sid` value in the Cookie.
> 
> Use both in the following cURL command to create an API token e.g.:
> 
> ```shell
> curl -L -X POST 'http://localhost:9000/admin/users/usr_01HNBKZ0Y1N2A02GMCWNGS2MV4' \
> -H 'Cookie: connect.sid=s%3A0AYLa8FDlo2OdbpozH9etItCYyDyMlmO.ZP5Nlq6bIM7Xq4ZGNoMkKgupTG3keCODIKem6rXbxns' \
> -H 'Content-Type: application/json' \
> --data-raw '{
>     "api_token": "put_whatever_you_want_here_lsdflsfljsldfjsdlfjslkfjs002342"
> }'
> ```
> 
> Then you can call the following API to confirm the API token user:
> 
> ```shell
> curl 'http://localhost:9000/admin/auth' \
> -H 'x-medusa-access-token: put_whatever_you_want_here_lsdflsfljsldfjsdlfjslkfjs002342'
> ```
> 
> You should see something like the following:
> 
> ```json
> {
>   "user": {
>     "id": "usr_01HNBKZ0Y1N2A02GMCWNGS2MV4",
>     "created_at": "2024-01-29T22:03:16.696Z",
>     "updated_at": "2024-01-30T00:01:38.998Z",
>     "deleted_at": null,
>     "role": "admin",
>     "email": "admin@your-domain.com",
>     "first_name": "Admin",
>     "last_name": "Admin",
>     "api_token": "put_whatever_you_want_here_lsdflsfljsldfjsdlfjslkfjs002342",
>     "metadata": null
>   }
> }
> ```

I did but not working for me
