### ISSUE TITLE
[Bug]: Unable to retrieve custom payment provider.

### ISSUE THREAD

**Issue by ldgaetano** [medusajs/medusa#10500]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "predeploy": "medusa db:migrate",
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "@stripe/react-stripe-js": "^2.9.0",
    "@stripe/stripe-js": "^4.10.0",
    "awilix": "^8.0.1",
    "axios": "^1.7.8",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  },
  "packageManager": "yarn@1.22.22+sha512.a6b2f7906b721bba3d67d4aff083df04dad64c399707841b7acf00f6b133b7ac24255f2652fa22ae3534329dc6180534e98d17432037ff6fd140556e2bb3137e"
}
```

### Node.js version

v23.3.0

### Database and its version

Postgres SQL 17.2

### Operating system name and version

Ubuntu 22.04.5 LTS 64-bit

### Browser name

Firefox

### What happended?

I implemented my custom payment provider following the Medusa documentation. I can see that the payment provider id is in the database as an entry in the payment_provider table. I am able to select it as an option for regions in the admin panel. I am able to select it as an option when testing the cart checkout process on the frontend. However, when I click continue (i.e. when a payment session is attempted to be created with the custom provider), I get an error saying that the payment provider is not registered in the container.

### Expected behavior

I expected my custom payment provider to be registered in the Medusa container, I have added it to the medusa-config file properly. A payment session should have been created with the custom payment provider.

### Actual behavior

I get the following error:

```
error:   
      Unable to retrieve the payment provider with id: pp_coinbase-commerce_coinbase
      Please make sure that the provider is registered in the container and it is configured correctly in your project configuration file.
      
{
  message: '\n' +
    '      Unable to retrieve the payment provider with id: pp_coinbase-commerce_coinbase\n' +
    '      Please make sure that the provider is registered in the container and it is configured correctly in your project configuration file.\n' +
    '      ',
  name: 'Error',
  stack: 'Error: \n' +
    '      Unable to retrieve the payment provider with id: pp_coinbase-commerce_coinbase\n' +
    '      Please make sure that the provider is registered in the container and it is configured correctly in your project configuration file.\n' +
    '      \n' +
    '    at PaymentProviderService.retrieveProvider (/home/ldgaetano/development/work/zengate/palmyra-express/node_modules/@medusajs/payment/src/services/payment-provider.ts:51:13)\n' +
    '    at PaymentProviderService.createSession (/home/ldgaetano/development/work/zengate/palmyra-express/node_modules/@medusajs/payment/src/services/payment-provider.ts:59:27)\n' +
    '    at PaymentModuleService.createPaymentSession (/home/ldgaetano/development/work/zengate/palmyra-express/node_modules/@medusajs/payment/src/services/payment-module.ts:313:67)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async Proxy.<anonymous> (/home/ldgaetano/development/work/zengate/palmyra-express/node_modules/@medusajs/orchestration/src/workflow/local-workflow.ts:129:20)\n' +
    '    at async Object.exports.createPaymentSessionStep.async.container.container (/home/ldgaetano/development/work/zengate/palmyra-express/node_modules/@medusajs/core-flows/src/payment-collection/steps/create-payment-session.ts:27:21)\n' +
    '    at async Object.invoke (/home/ldgaetano/development/work/zengate/palmyra-express/node_modules/@medusajs/workflows-sdk/src/utils/composer/helpers/create-step-handler.ts:72:52)\n' +
    '    at async DistributedTransaction.handler (/home/ldgaetano/development/work/zengate/palmyra-express/node_modules/@medusajs/orchestration/src/workflow/workflow-manager.ts:214:16)\n' +
    '    at async stepHandler (/home/ldgaetano/development/work/zengate/palmyra-express/node_modules/@medusajs/orchestration/src/transaction/transaction-orchestrator.ts:827:20)\n' +
    '    at async Promise.allSettled (index 0)\n' +
    '⮑ sat /home/ldgaetano/development/work/zengate/palmyra-express/node_modules/@medusajs/core-flows/dist/payment-collection/workflows/create-payment-session.js: [create-payment-sessions -> create-payment-session (invoke)]'
}
```

### Link to reproduction repo

https://github.com/ldgaetano/medusa-reproduction.git

**Comment by riqwan** [comment]
Hey @ldgaetano, thanks for the well written issue! It helped jump in and debug. 

This is the actual error you're getting:
<img width="1260" alt="Original error" src="https://github.com/user-attachments/assets/212092f6-6bca-482c-b1e2-ad4448095087">

I've opened a PR for it to log this in the server logs. The issue you're having is that the `CoinbaseCommercePaymentProviderService` service constructor accepts a `coinbaseClient`. The arguments here are basically resolving from an awilix container.

<img width="636" alt="Screenshot 2024-12-09 at 14 24 47" src="https://github.com/user-attachments/assets/dda01e11-470e-4af9-94bd-42d287d10bcb">

For this to work in the current form, you need to register `coinbaseClient` in the provider loaders or you could just rewrite the constructor to build a new instance of the client in the constructor.

**Comment by ldgaetano** [comment]
Thanks! Any documentation you can link for the first option? I was initially following similar steps outlined in the Getting Started documentation for integrating a third-party service, where the example was creating a third-party client in the way I did it.

**Comment by riqwan** [comment]
Before I do, would this not be helpful in this case? https://www.npmjs.com/package/coinbase-commerce-node

also, @ldgaetano can you share the link to the doc?

**Comment by ldgaetano** [comment]
Yes, actually, it would 😅. Nowhere is it referenced in the coinbase commerce documentation, so I had no idea this existed. 

The doc I was referring to was from here: https://docs.medusajs.com/learn/customization/integrate-systems/service

However, this documentation has changed since last friday, which is when I last used it. It seems to no longer show the previous example implementation of the BrandClient.

**Comment by riqwan** [comment]
yeah, I had to dig a bit to find it, but knew that I saw it somewhere. 😄 

Closing this for now, feel free to reopen if you come across anything else. 🤞🏻
