### ISSUE TITLE
[Bug]: Requested fields [measurement] are not valid

### ISSUE THREAD

**Issue by imash96** [medusajs/medusa#10519]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v20.18.1

### Database and its version

PostgreSQL 17.2

### Operating system name and version

Windows 11

### What happended?

I have created a module name `measurement` and linked it with `customer` module.

```
import { defineLink } from "@medusajs/framework/utils";
import CustomerModule from "@medusajs/medusa/customer";
import MeasurementModule from "../modules/measurement";

export default defineLink(
    CustomerModule.linkable.customer,
    {
        linkable: MeasurementModule.linkable.measurement,
        isList: true
    }
);
```

When i query customer along with field measurement I'm getting error. 

```
curl 'http://localhost:9000/store/customers/me?fields=+*measurements' \
--header 'Authorization: Bearer {token}'
```

> error:   Requested fields [measurements] are not valid
> MedusaError: Requested fields [measurements] are not valid
>     at prepareListQuery (D:\Project\backend\node_modules\@medusajs\framework\src\http\utils\get-query-config.ts:187:3)
>     at prepareRetrieveQuery (D:\Project\backend\node_modules\@medusajs\framework\src\http\utils\get-query-config.ts:251:21)
>     at validateQuery (D:\Project\backend\node_modules\@medusajs\framework\src\http\utils\validate-query.ts:86:27)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5) {
>   __isMedusaError: true,
>   type: 'invalid_data',
>   code: undefined,
>   date: 2024-12-10T08:25:07.962Z
> }

below are some console log of get-query-config.ts file

```
{
  allowed: [
    'id',           'email',
    'company_name', 'first_name',
    'last_name',    'phone',
    'metadata',     'has_account',
    'deleted_at',   'created_at',
    'updated_at',   'addresses',
    'orders'
  ],
  restricted: [ 'order', 'orders' ],
  notAllowedFields: [ 'measurements' ],
  fieldsToCheck: [
    'id',           'email',
    'company_name', 'first_name',
    'last_name',    'phone',
    'metadata',     'has_account',
    'deleted_at',   'created_at',
    'updated_at',   'addresses',
    'measurement'
  ]
}
```

### Expected behavior

The expect behaviour should be as below

```
[
    {
        "id": "cus_01JEP339TKP8CBNVCFBQNQ6MFN",
        "company_name": "Company Name",
        "first_name": "First Name",
        "last_name": "Last Name",
        "email": "email@gmail.com",
        "phone": "0000000000",
        "has_account": true,
        "metadata": null,
        "created_at": "2024-12-09T16:12:35.539Z",
        "updated_at": "2024-12-09T16:12:35.539Z",
        "deleted_at": null,
        "created_by": null,
        "measurements": [
            {
                "id": "msrmt_01JEQA7A8RDGYMF584WJFDJQCM",
                "type": "Jacket",
                "fit": "Regular",
                "gender": "Male",
                "name": null,
                "height": null,
                "weight": null,
                "info": null,
                "measurements": null,
                "metadata": null,
                "created_at": "2024-12-10T03:36:21.529Z",
                "updated_at": "2024-12-10T03:36:21.529Z",
                "deleted_at": null
            },
            {
                "id": "msrmt_01JEQTCG4SABAWGW791V4A47ZG",
                "type": "Jacket",
                "fit": "Regular",
                "gender": "Male",
                "name": null,
                "height": null,
                "weight": null,
                "info": null,
                "measurements": null,
                "metadata": null,
                "created_at": "2024-12-10T08:18:48.601Z",
                "updated_at": "2024-12-10T08:18:48.601Z",
                "deleted_at": null
            }
        ]
    }
]
```

### Actual behavior

> error:   Requested fields [measurement] are not valid
> MedusaError: Requested fields [measurement] are not valid
>     at prepareListQuery (D:\Project\backend\node_modules\@medusajs\framework\src\http\utils\get-query-config.ts:187:3)
>     at prepareRetrieveQuery (D:\Project\backend\node_modules\@medusajs\framework\src\http\utils\get-query-config.ts:251:21)
>     at validateQuery (D:\Project\backend\node_modules\@medusajs\framework\src\http\utils\validate-query.ts:86:27)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5) {
>   __isMedusaError: true,
>   type: 'invalid_data',
>   code: undefined,
>   date: 2024-12-10T08:25:07.962Z
> }

### Link to reproduction repo

NA

**Comment by imash96** [comment]
@srindom any help

**Comment by imash96** [comment]
@srindom @riqwan @VariableVic @thetutlage @olivermrbl @fPolic any help on this buddy?

**Comment by imash96** [comment]
@srindom  @riqwan  @VariableVic  @thetutlage  @olivermrbl  @fPolic  any help on this buddy?

**Comment by imash96** [comment]
@shahednasser please help

**Comment by imash96** [comment]
@srindom @riqwan @VariableVic @thetutlage @oliverheaps @fPolic @shahednasser any help folks?

**Comment by imash96** [comment]
@srindom @riqwan @VariableVic @thetutlage @oliverheaps @fPolic @shahednasser any help folks?

**Comment by imash96** [comment]
@srindom  @riqwan  @VariableVic  @thetutlage  @oliverheaps  @fPolic  @shahednasser  any help folks?

**Comment by imash96** [comment]
@srindom @riqwan @VariableVic @thetutlage @oliverheaps @fPolic @shahednasser any help folks?

**Comment by kasperkristensen** [comment]
Hi @imash96, the customer endpoints are protected to limit what you can query from a customer, this is done with a static list of allowed fields. The allowed fields are these:

```
[
  "id",
  "email",
  "company_name",
  "first_name",
  "last_name",
  "phone",
  "metadata",
  "has_account",
  "deleted_at",
  "created_at",
  "updated_at",
  "*addresses",
  "orders"
]
```
This is what is preventing you from querying measurements, as the list of allowed fields are static. It's on the roadmap to make this list dynamic to account for custom fields, and its something we expect to start work on next year.

But thanks for pointing this out, as the current guide is misleading, we will update the docs ASAP to reflect this. In the meantime, I would recommend that you create a new separate endpoint to retrieve a customers measurements.

**Comment by Yujink0624** [comment]
@kasperkristensen Hi, I am also facing the same issue, what I found that

I was able to update a customer with `additional_data` with this api endpoint `/admin/customers/:id`
```
{
    "email":"test@gmail.com",
    "company_name": "TEST",
    "first_name": "test66",
    "last_name" : "Test6",
    "phone": "222-1111-2",
    "additional_field" : {
        "gender" : "male"
    }
}
```

However, I couldn't do the same thing with the api endpoint `/store/customers/me`, it throws 400 error, the response is the below : 
```
{
    "type": "invalid_data",
    "message": "Invalid request: Expected type: 'object' for field '', got: 'string'"
}
```

Is there any way to update a customer additional_data?

Please help me, any comments would be much appreciated.
