### ISSUE TITLE
Introduction - 3.2 - Integration methods - Wrong breadcrum and example 

### ISSUE THREAD

**Issue by brunogarba** [medusajs/medusa#10515]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### On intro documentation there's a wrong breadcrumb that misleads and confuses the user reading the documentation.
[Integration methods]( https://docs.medusajs.com/learn/customization/integrate-systems/service#integration-methods) 

Documentation says 
> Add the following methods in the CmsModuleService

Which should be on the recently created "src/modules/cms/service.ts" on the previous step. Yet the breadcrumbs show "src/modules/brand/services/client.ts" which is a file that shouldn't even exist on the user that's following the documentation.

The class name on the example is also wrong, "BrandClient" should be the recently created "CmsModuleService"

### How can this issue be resolved?

1. Make changes on the documentation page

### Are you interested in working on this issue?

- I'm not interested in fixing the issue as I'm not familiar with the documentation site and i'm currently following the medusa introduction project.

**Comment by shahednasser** [comment]
Nice catch! Will open a PR to fix this
