### ISSUE TITLE
Create fulfilment creates partial fulfilment in case there are more than one line item in the order.

### ISSUE THREAD

**Issue by imumesh18** [medusajs/medusa#10541]
### Describe the bug

I am using v1.20.10 of medusajs and ran into this issue where everytime if there is more than two line items into the order the fulfilment code doesn’t add profile_id in the lineItem hence fulfilment gets created but with no line items. The problematic code is this: https://github.com/medusajs/medusa/blob/0a97a10f0c8b48ee836ba9faa23d2c2a6d2f7ce8/packages/medusa/src/services/fulfillment.ts#L131. 

### System information

Medusa version (including plugins):
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Steps to reproduce the behavior

1. Create a fresh v1.20.10 repo
2. Try to create a fulfilment with order which has two line items in it.
3. It will go to partial fulfilment.
### Expected behavior

After creating a fulfilment it should be marked fulfilled.

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

https://github.com/medusajs/medusa/blob/0a97a10f0c8b48ee836ba9faa23d2c2a6d2f7ce8/packages/medusa/src/services/fulfillment.ts#L131. 

validateFulfillmentLineItem method is the culprit here. It's somehow removing profile_id.
### Additional context
I am using manual fulfilment. No changes has been made in lineitem repo. I debugged the code by putting print statements till the above method everything works fine after making changes to it i was able to make it work.

**Comment by sradevski** [comment]
Hi there,
We have shifted our focus to v2, so we won't be able to look into this issue. However, feel free to open a PR with a fix and we'll have it reviewed and merged.

Thanks!
