### ISSUE TITLE
Medusa-Stripe - Paypal not showing in Production Mode

### ISSUE THREAD

**Issue by Leon-LaZer** [medusajs/medusa#10544]
### Describe the bug

We created a custom frontend and backend for Medusa and wanted to use the medusa-payment-stripe Plugin as our payment provider. In the development mode of stripe, everything worked perfectly, we saw credit card and paypal as our Payment options like we wanted. Now we turned the dev mode to production mode and exchanged all the stripe api keys (sk_live, pk_live, webhook_secret) but now the only thing we see is "credit card" as our payment option. Our PayPal Account is linked to our stripe and the stripe support said from their side everything looks correct. Do we need to configure something in our frontend/medusa so that paypal is shown as a payment option? 

Our region is configured for europe with eur as the currency.

Edit: I also added "Revolut" just for testing (as it is the only one without a verification), that was displayed without issues in our frontend.

### System information

Medusa version (including plugins):
    "@medusajs/medusa": "^1.20.3",
    "medusa-payment-manual": "^1.0.24",
    "medusa-payment-stripe": "^6.0.9",
    "medusa-fulfillment-manual": "^1.1.39",
    "@medusajs/utils": "^1.11.6",

Node.js version:
    "@types/node": "20.0.0",

Database: PostgresSQL 16.2

Browser (if relevant): Chrome without Adblock

### Steps to reproduce the behavior

(0.5 Set Stripe to "prod" mode)
1. Add Products to Cart
2. Go to cart and checkout
3. Fill address etc. and see payment options
4. Don't see Paypal

### Expected behavior

See PayPal as a payment option

### Code snippets

Configuration of medusa-payment-stripe in medus-config.js:
```
  {
    resolve: 'medusa-payment-stripe',
    options: {
      api_key: STRIPE_API_KEY,
      webhook_secret: STRIPE_WEBHOOK_SECRET,
      automatic_payment_methods: true,
      capture: true,
    }
  }
```

also tried:
```
  {
    resolve: 'medusa-payment-stripe',
    options: {
      api_key: STRIPE_API_KEY,
      webhook_secret: STRIPE_WEBHOOK_SECRET,
      automatic_payment_methods: false,
      payment_method_types: ["card", "paypal"],
      capture: true,
    }
  }
```

When I add things to a cart, a payment session with the following data is created:
```
provider_id: stripe,
status: authorized,
is_initiated: true,
amount: 1700,
data: {
   "id":"pi_3QT2CBK5uFQePnVc0dogZttF",
   "amount":1700,
   "object":"payment_intent",
   "review":null,
   "source":null,
   "status":"requires_confirmation",
   "created":1733494071,
   "invoice":null,
   "currency":"eur",
   "customer":"cus_RKF5FqKLnjToor",
   "livemode":true,
   "metadata":{
      "resource_id":"cart_01JEE483H5KSSMQBQEQR51F0BV"
   },
   "shipping":null,
   "processing":null,
   "application":null,
   "canceled_at":null,
   "description":null,
   "next_action":null,
   "on_behalf_of":null,
   "client_secret":"pi_3QT2CBK5uFQePnVc0dogZttF_secret_NuzeX91zEW2qpgCZkue4f1Fa5",
   "latest_charge":null,
   "receipt_email":null,
   "transfer_data":null,
   "amount_details":{
      "tip":{
         
      }
   },
   "capture_method":"automatic",
   "payment_method":"pm_1QT2CDK5uFQePnVciGkl06ew",
   "transfer_group":null,
   "amount_received":0,
   "amount_capturable":0,
   "last_payment_error":null,
   "setup_future_usage":null,
   "cancellation_reason":null,
   "confirmation_method":"automatic",
   "payment_method_types":[
      "card",
      "paypal"
   ],
   "statement_descriptor":null,
   "application_fee_amount":null,
   "payment_method_options":{
      "card":{
         "network":null,
         "installments":null,
         "mandate_options":null,
         "request_three_d_secure":"automatic"
      },
      "paypal":{
         "reference":null,
         "preferred_locale":null
      }
   },
   "automatic_payment_methods":{
      "enabled":true,
      "allow_redirects":"always"
   },
   "statement_descriptor_suffix":null,
   "payment_method_configuration_details":{
      "id":"pmc_1PDmYAK5uFQePnVcVPZGofiA",
      "parent":null
   }
}
```

**Comment by sradevski** [comment]
Hi there,

As we've shifted our focus on v2, we are not actively working on non-critical issues of v1. If you find any bugs feel free to open a PR and we'll have it reviewed. Thanks!
