### ISSUE TITLE
Create CustomerGroup datamodel

### ISSUE THREAD

**Issue by pKorsholm** [medusajs/medusa#1054]
Steps: 
1. create `CustomerGroup` table: 
```javascript
customer-group {
	id: string - required
	name: string - required
	metadata?: object
}
```
2. Add `groups` field to customer model: 
```javascript
customer{ 
	...
	customer-group?: CustomerGroup[]
	...
}
```
this requires a many to many relation between the two which should be realised like other many to many relations e.g. giftcards in `models/order.ts` with an appropriate joinTable name.
```javascript
@ManyToMany(() => GiftCard)
  @JoinTable({
    name: "cart_gift_cards",
    joinColumn: {
      name: "cart_id",
      referencedColumnName: "id",
    },
    inverseJoinColumn: {
      name: "gift_card_id",
      referencedColumnName: "id",
    },
  })
  gift_cards: GiftCard[]
```

`Customers` should also be a field on the `CustomerGroup` entity.

**Acceptance criteria:** 

- A `CustomerGroup` model is added to `/models`
- A `CustomerGroupRepository` is added to `/repositories`
- An “empty” `CustomerGroupService` is added to `/services` , meaning
- a migration with customer group entity and customer field is added to the codebase

**Comment by olivermrbl** [comment]
Closed #1074
