### ISSUE TITLE
[Bug]: Incorrect Language Code Format for Brazilian Portuguese in Admin Dashboard

### ISSUE THREAD

**Issue by rafaelnep** [medusajs/medusa#10554]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v20.14.0

### Database and its version

PostgreSQL 16

### Operating system name and version

macOS Sonoma 14.6.1

### Browser name

Edge

### What happended?

When changing the language of the Medusa Admin dashboard to Portuguese, the interface becomes blank, and multiple errors are logged in the browser’s console. This prevents the dashboard from rendering properly.

Suspected Cause:

It appears that the issue might be related to the language code format. The current setup seems to use ptBR, while the internationalization (i18n) system likely expects the language code in the standard format pt-BR, as per [IETF BCP 47](https://tools.ietf.org/html/bcp47). This discrepancy might result in the system failing to locate or process the translation files, causing the interface to break.

### Expected behavior

The dashboard should display all interface elements in Brazilian Portuguese after changing the language setting, without any rendering issues.

### Actual behavior

When changing the language of the Medusa Admin dashboard to Brazilian Portuguese, the interface fails to render correctly, resulting in a completely blank screen (or black screen if the dark theme is enabled). Additionally, the browser console logs multiple errors related to the loading or processing of the required translation files.

### Link to reproduction repo

This issue can be reproduced using a fresh, clean installation of Medusa.

**Comment by christiananese** [comment]
Hey @rafaelnep,
what version of Medusa are you running? (see relevant issue [10417](https://github.com/medusajs/medusa/issues/10417))
Can you upgrade to the latest version and see if the problem still persists? We shipped a fix for this last week 😊
