### ISSUE TITLE
Create CustomerGroup endpoint: Create

### ISSUE THREAD

**Issue by pKorsholm** [medusajs/medusa#1056]
`POST /admin/customer-groups`

Endpoint should use the `CustomerGroupService` to implement a `create` method for CustomerGroups

**Blocked by #1054** 

**acceptance criteria:**

- creates a customer group with a name and metadata
- Uses `CustomerGroupService` as a middle layer between api and repository with an appropriate method corresponding to the api action
- Uses `CustomerGroupRepository` to handle database entries using the corresponding typeorm repository method from the repository api
- Integration tests which ensures the implementation works as intended for the given endpoint

**Comment by olivermrbl** [comment]
Closed #1074
