### ISSUE TITLE
Explain how to install the Stripe provider

### ISSUE THREAD

**Issue by adevinwild** [medusajs/medusa#10574]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

It would be interesting to highlight which package must be installed to be able to take advantage of the Stripe provider on Medusa 2.0 🙌🏼

### How can this issue be resolved?

We can add a new section before the [Register the Stripe Module Provider](https://docs.medusajs.com/resources/commerce-modules/payment/payment-provider/stripe#register-the-stripe-module-provider), that will show an install block with a package manager
...

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Hey! The stripe module provider is actually already available for use so you don't need to install it. I'll create a PR to highlight this in the document.

**Comment by adevinwild** [comment]
> Hey! The stripe module provider is actually already available for use so you don't need to install it. I'll create a PR to highlight this in the document.

Oh thanks you @shahednasser I always thought we needed to install it, but indeed in the codebase it's included
