### ISSUE TITLE
[Bug]: Type hints for CRUD methods are incorrect when the object ends with 'o'

### ISSUE THREAD

**Issue by damianr13** [medusajs/medusa#10580]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "2.1.1",
    "@medusajs/cli": "2.1.1",
    "@medusajs/framework": "2.1.1",
    "@medusajs/medusa": "2.1.1",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "2.1.1",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v22.11.0

### Database and its version

PostgreSQL 16.2

### Operating system name and version

MacOS Sonoma 14.6.1

### Browser name

N/A

### What happended?

I have a model named `VendorLegalInfo`. I want to perform CRUD operations on this model using its module service. 

The type hints suggest that the correct way to create a new object of this type is by calling the method `createVendorLegalInfoes`: 
![image](https://github.com/user-attachments/assets/ed53f86e-706c-473b-afae-fcbc73763ebf)

Calling this method crashes with: 
```
marketplace.createVendorLegalInfoes is not a function
```

When I step into the execution with the debugger, I can see that the correct name of the function is `createVendorLegalInfos`: 
![image](https://github.com/user-attachments/assets/e23523f7-a0df-42b3-b222-48635bc6da30)

But this is detected as an incorrect call in the IDE: 
![image](https://github.com/user-attachments/assets/86e433be-99c9-4621-b254-80cba096786a)

### Expected behavior

The actual method and the linting (IDE checking) should point to the same function name. 

In this particular case `info` is an abbreviation so grammatically speaking the correct plural form is still "info", but I think a grammatically incorrect plural in this special case is fine as long as it's consistent.

### Actual behavior

There is an inconsistency between the actual method name and the method that the IDE (through linting?!) knows about.  

### Link to reproduction repo

N/A

**Comment by riqwan** [comment]
Hey @damianr13, thanks for the issue, a PR for this has been merged! https://github.com/medusajs/medusa/pull/10599#event-15646977670

You can use the `preview` tag to test this or wait until the next release. Feel free to ask any questions. 🤞🏻
