### ISSUE TITLE
[Bug]: Can't access server after deployed to Coolify.

### ISSUE THREAD

**Issue by HeinKoZin** [medusajs/medusa#10595]
### Package.json file

```JSON
{
	"name": "medusa-starter-default",
	"version": "0.0.1",
	"description": "A starter for Medusa projects.",
	"author": "Medusa (https://medusajs.com)",
	"license": "MIT",
	"keywords": [
		"sqlite",
		"postgres",
		"typescript",
		"ecommerce",
		"headless",
		"medusa"
	],
	"scripts": {
		"build": "medusa build",
		"seed": "medusa exec ./src/scripts/seed.ts",
		"start": "medusa db:migrate && medusa start",
		"dev": "medusa develop",
		"predeploy": "medusa db:migrate",
		"build:admin": "medusa build --admin-only",
		"test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
		"test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
		"test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
	},
	"dependencies": {
		"@medusajs/admin-sdk": "2.1.1",
		"@medusajs/cli": "2.1.1",
		"@medusajs/framework": "2.1.1",
		"@medusajs/medusa": "2.1.1",
		"@medusajs/ui": "^4.0.2",
		"@mikro-orm/core": "5.9.7",
		"@mikro-orm/knex": "5.9.7",
		"@mikro-orm/migrations": "5.9.7",
		"@mikro-orm/postgresql": "5.9.7",
		"awilix": "^8.0.1",
		"pg": "^8.13.0"
	},
	"devDependencies": {
		"@medusajs/test-utils": "2.1.1",
		"@mikro-orm/cli": "5.9.7",
		"@swc/core": "1.5.7",
		"@swc/jest": "^0.2.36",
		"@types/jest": "^29.5.13",
		"@types/node": "^20.0.0",
		"@types/react": "^18.3.2",
		"@types/react-dom": "^18.2.25",
		"jest": "^29.7.0",
		"prop-types": "^15.8.1",
		"react": "^18.2.0",
		"react-dom": "^18.2.0",
		"ts-node": "^10.9.2",
		"typescript": "^5.6.2",
		"vite": "^5.2.11"
	},
	"engines": {
		"node": ">=20"
	}
}
```

### Node.js version

v22.3.0

### Database and its version

Postgres 17

### Operating system name and version

Ubuntu 22.04

### What happended?

After running medusa in Coolify. It logged 

> 2024-12-12T22:02:32.399456859Z 
2024-12-12T22:02:32.399508035Z info:    Migrations completed
2024-12-12T22:02:32.399513956Z 
2024-12-12T22:02:33.866642801Z info:    Syncing links...
2024-12-12T22:02:40.753985503Z info:    Database already up-to-date
2024-12-12T22:02:44.453342708Z info:    Skipping instrumentation registration. No register function found.
2024-12-12T22:02:44.591495507Z warn:    Local Event Bus installed. This is not recommended for production.
2024-12-12T22:02:45.710302904Z info:    Locking module: Using "in-memory" as default.
2024-12-12T22:02:52.540700792Z info:    No job to load from /app/node_modules/.pnpm/@medusajs+medusa@2.1.1_@babel+runtime@7.26.0_@medusajs+framework@2.1.1_@mikro-orm+core@5.9.7__j76clbup63btlkjelzyd2xm56q/node_modules/@medusajs/medusa/dist/jobs. skipped.
2024-12-12T22:02:52.739974681Z - Creating server
2024-12-12T22:02:52.976788894Z ✔ Server is ready on http://0.0.0.0:9000 – 229ms
2024-12-12T22:02:52.998989319Z info:    Admin URL → http://0.0.0.0:9000/app

But I can't access to server.

### Expected behavior

It should show product list when I call to /store/products

### Actual behavior

Error like this whenever I call to api 

![Capture-2024-12-13-102856 AM](https://github.com/user-attachments/assets/99a26dc6-24a0-4b0e-8786-793079dbbc0f)

### Link to reproduction repo

https://github.com/HeinKoZin/mr-medusa

**Comment by sgirones** [comment]
hi @HeinKoZin. Do you see any attempt of request in the Medusa logs? If not, it must be something misconfigured in your infrastructure. Maybe you have a balancer in front that is not routing the requests properly? I suggest you check the balancer logs if so.

Do you have a public URL we can check?

Unfortunately, it seems the issue may be outside the realm of the Medusa service, so we can't help you with that. But if you verify requests are being mishandled by Medusa, please let us know.

**Comment by HeinKoZin** [comment]
It was deployed on http://e4k84wc0gksw4s484okgogo0.62.146.234.39.sslip.io/
