### ISSUE TITLE
Create CustomerGroup endpoint: List

### ISSUE THREAD

**Issue by pKorsholm** [medusajs/medusa#1060]
`GET /admin/customer-groups`

This endpoint should support basic pagination(limit, offset) query parameters as well as an `expand` parameter. See `list-orders.ts` for inspiration.

As `list-orders`, `list-customer-groups` should receive a queryparameter "q" for searching customer groups in plain text

Implementation should use a "listAndCount" method in the `CustomerGroupService` and the api response should extend the pagination response and thus contain: 
- `limit`
- `offset`
- `count` - total count of customer groups, not `.length` of result
- `customerGroups`

**Blocked by #1054** 

**Acceptance criteria** 
- list: lists customer group with pagination parameters as well as “q”
- Uses `CustomerGroupService` as a middle layer between api and repository with an appropriate method corresponding to the api action
- Uses `CustomerGroupRepository` to handle database entries using the corresponding typeorm repository method from the repository api
- Integration tests which ensures the implementation works as intended for the given endpoint

**Comment by olivermrbl** [comment]
Solved #1099
