### ISSUE TITLE
Extend customer module not working as expected

### ISSUE THREAD

**Issue by imash96** [medusajs/medusa#10615]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I followed exactly same guide as mention in [https://docs.medusajs.com/resources/commerce-modules/customer/extend](url).

But when I tried to retrive customer uisng below method I am getting error

> curl 'localhost:9000/admin/customers/{customer_id}?fields=+custom.*' \
> -H 'Authorization: Bearer {token}'

![image](https://github.com/user-attachments/assets/5fca42db-1262-43f5-bce7-6c41d433b29b)

I have also open a new issue [https://github.com/medusajs/medusa/issues/10519](url)

### How can this issue be resolved?

1. Query failed beacuse the allowed fields make the custom field to notAllowedFields
```
{
  allowed: [
    'id',           'email',
    'company_name', 'first_name',
    'last_name',    'phone',
    'metadata',     'has_account',
    'deleted_at',   'created_at',
    'updated_at',   'addresses',
    'orders'
  ],
  restricted: [ 'order', 'orders' ],
  notAllowedFields: [ 'custom' ],
  fieldsToCheck: [
    'id',           'email',
    'company_name', 'first_name',
    'last_name',    'phone',
    'metadata',     'has_account',
    'deleted_at',   'created_at',
    'updated_at',   'addresses',
    'custom'
  ]
} 
```
2. Allow user to extend allowed fileds

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by kasperkristensen** [comment]
Hi @imash96, see my comment in #10519 as the same principle applies.
