### ISSUE TITLE
[Bug]: order.completed event is never emitted

### ISSUE THREAD

**Issue by markusj1394** [medusajs/medusa#10611]
### Package.json file

```JSON
{
  "name": "-",
  "version": "0.0.1",
  "description": "-",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "lint": "eslint ./src --ext .ts --fix",
    "prettier": "prettier --check \"src/**/*.{ts,graphql,js,json}\"",
    "format": "yarn lint && prettier --write \"src/**/*.{ts,graphql,js,json}\"",
    "start": "medusa start",
    "dev": "NODE_TLS_REJECT_UNAUTHORIZED=0 medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "@sgftech/payment-razorpay": "^2.1.11",
    "awilix": "^8.0.1",
    "medusa-plugin-category-images": "^1.0.18",
    "nodemailer": "^6.9.16",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v21.0.0

### Database and its version

PostgreSQL 16.2

### Operating system name and version

Ubuntu 22

### What happended?

I am trying to subscribe to order completion events, but looks like they are never emitted. However, I can confirm that order.placed events are emitted properly.

### Expected behavior

As per the docs (https://docs.medusajs.com/resources/events-reference) order.completed events should be emitted (when the order is marked as delivered from admin panel).

### Actual behavior

Currently order.completed events are not emitted after marking order as delivered. I am not totally sure that marking order as delivered is same as order being completely though.

### Link to reproduction repo

-

**Comment by kasperkristensen** [comment]
Hi @markusj1394, the completed event is triggered, when an order is completed, which is not the same as marking the order as shipped. Medusa doesn't set the order as completed for you, you will need to set it as completed yourself, as we don't have an opinion on when an order is deemed complete. 

You might want to set the order as completed once an order has been shipped, somebody else might want to set an order as completed once the return policy for that order has expired, etc.

To complete an order you can use the `POST /admin/orders/:id/complete` endpoint, or use the `completeOrderWorkflow` in a subscriber, to set up order completion to fit your use case.

Closing the issue as the event is fired when marking an order as completed.
