### ISSUE TITLE
[Bug]: Many missing events

### ISSUE THREAD

**Issue by fxmb** [medusajs/medusa#10635]
### Package.json file

```JSON
no package needed
```

### Node.js version

v2.1.2

### Database and its version

16.2

### Operating system name and version

Linux

### What happended?

There are many (!) events missing that prevent us from going to prod at some point. E:g. `customer.created` is not triggered.

This has been flagged countless times on discord by a lot of users and it is extremely frustrating unfortunately.

Can the medusa team prioritise a proper assessment and add all missing events?

### Expected behavior

Events triggered

### Actual behavior

Many events are missing

### Link to reproduction repo

no repo

**Comment by sradevski** [comment]
We are open to contributions, feel free to open PRs for the events that are missing.

**Comment by sradevski** [comment]
Closing as it is too generic. We are more than happy to accept contributions for the events that people need before we have the time to add them.
