### ISSUE TITLE
[Bug]: 401 error when requesting /customer/me after user login

### ISSUE THREAD

**Issue by UKFox** [medusajs/medusa#10638]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/js-sdk": "^2.1.0",
    "@medusajs/medusa": "latest",
    "@medusajs/types": "^2.1.0",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "@react-email/components": "0.0.31",
    "@rokmohar/medusa-plugin-meilisearch": "^0.1.1",
    "awilix": "^8.0.1",
    "medusa-plugin-meilisearch": "^2.0.11",
    "pg": "^8.13.0",
    "resend": "^4.0.1"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v22.12.0

### Database and its version

PostgreSQL 14.15

### Operating system name and version

Windows 11

### What happended?

Medusa V2 created with the `create-medusa-app` command

I got 401 error when trying to login with a customer account when storefront + admin are running in localhost (storefront : localhost:8000 & admin : localhost:9000)

I have the following error after customer login form submission (correct login/password) in the storefront logs : 
```
Performing request to:
 URL: http://localhost:9000/store/customers/me?fields=%2Aorders
 Headers: {
  "accept": "application/json",
  "authorization": "<REDACTED>",
  "content-type": "application/json",
  "x-publishable-api-key": "pk_[...]"
}


Received response with status 401
```

Using postman, I can get the user token : 
```
POST /localhost:9000/auth/customer/emailpass
{
    "email": "user@email.com",
    "password": "user-password"
}
```
but I still got the 401 error when trying to call the 'customers/me' endpoint : 
```
GET /localhost:9000/store/customers/me
x-publishable-api-key=pk_[...]
Authorization=Bearer {{token}}
```
I still have this 401 error in, response : 
```
{
    "message": "Unauthorized"
}
```

My .env file : 
```
MEDUSA_ADMIN_ONBOARDING_TYPE=nextjs
#STORE_CORS=http://localhost:8000,https://docs.medusajs.com
STORE_CORS=/http:\/\/*/
#ADMIN_CORS=http://localhost:5173,http://localhost:9000,https://docs.medusajs.com
ADMIN_CORS=/http:\/\/*/
#AUTH_CORS=http://localhost:5173,http://localhost:9000,https://docs.medusajs.com
AUTH_CORS=/http:\/\/*/
REDIS_URL=redis://localhost:6379
JWT_SECRET=supersecret
COOKIE_SECRET=supersecret
DATABASE_URL=postgres://secret:secret@url/dbName
MEDUSA_ADMIN_ONBOARDING_NEXTJS_DIRECTORY=eshop-storefront


NODE_ENV=development
```
I do not have a local redis instance

The user was created in the admin panel, i then called the `/auth/user/emailpass/reset-password` endpoint, and used the token to successfully submit the password rest request : `/auth/customer/emailpass/update?token={token}`

Did I miss something ?

### Expected behavior

To get a 200 response when calling /store/customers/me endpoint with correct headers, post user authentication

### Actual behavior

Having a 401 ("message": "Unauthorized") response when calling /store/customers/me endpoint with correct headers

### Link to reproduction repo

https://github.com/Ets-Renard/medusa_issue

**Comment by sradevski** [comment]
It is most likely that you didn't create a customer entity, just an auth identity, see docs here: https://docs.medusajs.com/resources/commerce-modules/auth/authentication-route

If you decode the Auth token you will likely see that the actor_id is null. Let me know if that's not the case and I'll reopen the ticket.

**Comment by A-RENARD** [comment]
Thank you @sradevski , it worked with the auth workflow : 

1) Register user : 
```
POST /auth/customer/emailpass/register
"email": "[...]",
"password": "[...]"
```
At this stage the actor_id is actually null in the token

2) Create user using the token given inresponse for the previous request : 
```
POST /store/customers
Authorization : "Bearer {token}"
x-publishable-api-key : "[...]"
{
    "email": "[...]",
    "first_name": "[...]",
    "last_name": "[...]"
}
```
Doing this i am able to login in the storefront.

Also with this workflow it seems you have to refresh the token with the `POST /auth/token/refresh` endpoint after the user creation before being able to call the `GET /store/customers/me` endpoint

**(Different account, I am @UKFox)**

**Comment by PaulWeinsberg** [comment]
I had the same issue, if you use a reverse proxy forward the protocol too.

In apache : 

RequestHeader set X-Forwarded-Proto "https"
