### ISSUE TITLE
[Bug]: Inventory Reduction Not Reflecting Correct Stock Location for Sales Channels

### ISSUE THREAD

**Issue by arun-prasath2005** [medusajs/medusa#10658]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "NODE_ENV=production medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "cd .medusa/server && yarn install && medusa start",
    "dev": "medusa develop",
    "setup-db": "node ./src/scripts/setup-db.js",
    "migrate-db": "medusa db:migrate",
    "insert-domains": "medusa exec ./src/scripts/insert-domain-template.ts",
    "migrate-clickhouse": "ts-node ./src/scripts/clickhouse-migration.ts",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@clickhouse/client": "^1.7.0",
    "@internationalized/date": "^3.5.6",
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/file": "^2.0.4",
    "@medusajs/framework": "^2.1.1",
    "@medusajs/js-sdk": "latest",
    "@medusajs/medusa": "latest",
    "@medusajs/modules-sdk": "^2.0.4",
    "@medusajs/ui": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "@react-email/components": "^0.0.28",
    "@react-oauth/google": "^0.12.1",
    "@sgftech/payment-razorpay": "^2.1.11",
    "@superset-ui/embedded-sdk": "^0.1.2",
    "@types/d3": "^7.4.3",
    "@types/jsonwebtoken": "^9.0.7",
    "@types/multer": "^1.4.12",
    "@types/xlsx": "^0.0.36",
    "@vicecommerce/medusa-file-r2": "^1.1.1",
    "awilix": "^8.0.1",
    "d3": "^7.9.0",
    "dotenv": "^16.4.5",
    "framer-motion": "^11.11.1",
    "graphql-request": "^7.1.2",
    "jsonwebtoken": "^9.0.2",
    "lucide-react": "^0.447.0",
    "next": "^15.0.3",
    "nodemon": "^3.1.9",
    "openai": "^4.67.3",
    "pg": "^8.13.1",
    "pnpm": "^9.14.2",
    "react-beautiful-dnd": "11.0.2",
    "react-datepicker": "^7.4.0",
    "resend": "^4.0.1",
    "yargs": "^17.7.2",
    "zod": "3.22.4"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@medusajs/ui-preset": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-beautiful-dnd": "^13.1.8",
    "@types/react-dom": "^18.2.25",
    "d3-force": "^3.0.0",
    "jest": "^29.7.0",
    "lucide-react": "^0.441.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-toastify": "^10.0.5",
    "reactflow": "^11.11.4",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11",
    "xlsx": "^0.18.5"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v20.17.0

### Database and its version

Postgres SQL 16.2

### Operating system name and version

Ubuntu 20.04

### What happended?

We are facing an issue where inventory reduction for a product is not occurring in the correct stock location associated with the sales channel. The current behavior incorrectly reduces (reserves) inventory from the first stock location of the product instead of the stock location tied to the specific sales channel.

Steps to Reproduce:

1. Create multiple sales channels (e.g., Channel A, Channel B).
2. Each sales channel should have its own specific stock location (e.g., Stock Location A for Channel A, Stock Location B for Channel B).
3. Assign the same product to both sales channels, ensuring each channel has a unique inventory location.
4. Make a sale through Channel A or Channel B (Preferably Channel B).
5. Check the stock levels in the inventory system after the sale.

### Expected behavior

1. When a product is sold through Channel A, the system should reduce the inventory from Stock Location A, as this is the stock location associated with the sales channel.
2. When a product is sold through Channel B, the inventory should be reduced from Stock Location B instead it creates reservation in Stock Location A.

### Actual behavior

1. When the product is sold through any sales channel, the system reduces the inventory from the first stock location associated with the product, not the stock location tied to the specific sales channel.
2. This causes incorrect inventory management and creates discrepancies, especially when the same product is linked to multiple sales channels with different stock locations.

### Link to reproduction repo

Any latest default Medusa admin and storefront repo should do.

**Comment by arun-prasath2005** [comment]
After probing more and looking at the logic here - https://github.com/medusajs/medusa/blob/v2.1.1/packages/core/core-flows/src/cart/steps/reserve-inventory.ts

import { MathBN, Modules } from "@medusajs/framework/utils"
import { createStep, StepResponse } from "@medusajs/framework/workflows-sdk"
import { BigNumberInput } from "@medusajs/types"

export interface ReserveVariantInventoryStepInput {
  items: {
    id?: string
    inventory_item_id: string
    required_quantity: number
    allow_backorder: boolean
    quantity: BigNumberInput
    location_ids: string[]
  }[]
}

export const reserveInventoryStepId = "reserve-inventory-step"
/**
 * This step reserves the quantity of line items from the associated
 * variant's inventory.
 */
export const reserveInventoryStep = createStep(
  reserveInventoryStepId,
  async (data: ReserveVariantInventoryStepInput, { container }) => {
    const inventoryService = container.resolve(Modules.INVENTORY)

    const locking = container.resolve(Modules.LOCKING)

    const inventoryItemIds: string[] = []

    const items = data.items.map((item) => {
      inventoryItemIds.push(item.inventory_item_id)

      return {
        line_item_id: item.id,
        inventory_item_id: item.inventory_item_id,
        quantity: MathBN.mult(item.required_quantity, item.quantity),
        allow_backorder: item.allow_backorder,
        location_id: item.location_ids[0],
      }
    })

    const reservations = await locking.execute(inventoryItemIds, async () => {
      return await inventoryService.createReservationItems(items)
    })

    return new StepResponse(reservations, {
      reservations: reservations.map((r) => r.id),
      inventoryItemIds,
    })
  },
  async (data, { container }) => {
    if (!data?.reservations?.length) {
      return
    }

    const inventoryService = container.resolve(Modules.INVENTORY)
    const locking = container.resolve(Modules.LOCKING)

    const inventoryItemIds = data.inventoryItemIds
    await locking.execute(inventoryItemIds, async () => {
      await inventoryService.deleteReservationItems(data.reservations)
    })

    return new StepResponse()
  }
)

It seems to be pick up the first location id all the time (which is wrong) instead of picking the location id specific to that sales channel from where the order came from if a product is associated with multiple locations and each location is associated with its own sales channels.

**Comment by fPolic** [comment]
Thanks for the report @arun-prasath2005, we will fix this ASAP.

**Comment by arun-prasath2005** [comment]
Thanks @fPolic for acting on this fast, this is a major blocker for us right now and we hope to see this fixed in the immediate release. Thanks for your help!
