### ISSUE TITLE
[Bug]: After editing a collection, all products within the collection disappear

### ISSUE THREAD

**Issue by tanawinttp** [medusajs/medusa#10664]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "2.1.2",
    "@medusajs/cli": "2.1.2",
    "@medusajs/framework": "2.1.2",
    "@medusajs/medusa": "2.1.2",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "2.1.2",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v20.15.0

### Database and its version

PostgreSQL 14.13

### Operating system name and version

macOs 15.1.1 (24B91)

### Browser name

Google Chrome

### What happended?

When editing something in a collection and clicking save, all the products that were set in that collection disappear completely. I have recorded a screenshot, and I will attach a video as well.

https://github.com/user-attachments/assets/fd655cb4-18b0-4c15-9f2e-91523204c33e

### Expected behavior

The products set in the collection should remain in the collection, even if any changes are made to the collection.

### Actual behavior

product in collection disappear when edited something in collection.

### Link to reproduction repo

https://github.com/medusajs/medusa

**Comment by sgirones** [comment]
hey @tanawinttp, maybe you already did, but could you try to navigate to another page and then return here?

**Comment by tanawinttp** [comment]
https://github.com/user-attachments/assets/35fa7e89-b42c-48c3-8db8-cefc627cda9d

@sgirones I followed your advice, but unfortunately, the products still don’t reappear in the collection. Thank you for the suggestion, but I did try it thoroughly.

**Comment by riqwan** [comment]
Hey @tanawinttp thanks for catching this, I've opened a PR to fix this

**Comment by tanawinttp** [comment]
Thank you so much for this correction. It has been truly helpful to me. I really appreciate it.
@riqwan
