### ISSUE TITLE
"An unexpected error occurred while rendering this page."

### ISSUE THREAD

**Issue by yes-oo** [medusajs/medusa#10693]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

i got this error :
An unexpected error occurred while rendering this page.

after following the docs :
https://docs.medusajs.com/learn/customization/customize-admin/widget

there is no details and i can't fix this error if medusa doesn't provide me with any details about why i got this error 

### How can this issue be resolved?

1. server side logs for this error 
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by yes-oo** [comment]
here the solution that i did :
```js
import type { AdminProduct, DetailWidgetProps } from '@medusajs/framework/types'
import { defineWidgetConfig } from '@medusajs/admin-sdk'
import { clx, Container, Heading, Text } from '@medusajs/ui'
import { QueryClient, QueryClientProvider, useQuery } from '@tanstack/react-query'
import React from 'react'
import { sdk } from '../lib/sdk'

type AdminProductBrand = AdminProduct & {
  brand?: {
    id: string
    name: string
  }
}

// Initialize the QueryClient outside the component to avoid re-creating it
const queryClient = new QueryClient()

function ProductBrandWidget({
  data: product,
}: DetailWidgetProps<AdminProduct>) {
  return (
    <QueryClientProvider client={queryClient}>
      <BrandDetails product={product} />
    </QueryClientProvider>
  )
}

function BrandDetails({ product }: { product: AdminProduct }) {
  const { data: queryResult } = useQuery({
    queryFn: () => sdk.admin.product.retrieve(product.id, {
      fields: '+brand.*',
    }),
    queryKey: [['product', product.id]],
  })

  const brandName = (queryResult?.product as AdminProductBrand)?.brand?.name

  return (
    <Container className="divide-y p-0">
      <div className="flex items-center justify-between px-6 py-4">
        <div>
          <Heading level="h2">Brand</Heading>
        </div>
      </div>
      <div
        className={clx(
          `text-ui-fg-subtle grid grid-cols-2 items-center px-6 py-4`,
        )}
      >
        <Text size="small" weight="plus" leading="compact">
          Name
        </Text>

        <Text
          size="small"
          leading="compact"
          className="whitespace-pre-line text-pretty"
        >
          {brandName || '-'}
        </Text>
      </div>
    </Container>
  )
}

export const config = defineWidgetConfig({
  zone: 'product.details.before',
})

export default ProductBrandWidget
```


now if you don't notice the difference between this and the code in the docs , this is the correct way of using useQuery ( adding client provider which the docs didn't add ) 


have a nice day guys <3

**Comment by yes-oo** [comment]
@shahednasser   please update the docs , the docs code is not right and i did provide the right code in my previous comment شكرا

**Comment by Bernix01** [comment]
Just to clear any doubts for any wanderer through Tanstack issues. having `"@tanstack/react-query": "^5.28.14",` in the `package.json` is enough. No need for client provider. 

The docs however point to `5.64.2` which did cause issues by having `"@tanstack/react-query": "5.64.2",` so bear that in mind.

**Comment by shahednasser** [comment]
@Bernix01 thanks for pointing out the versioning issue, will fix it in the docs 👍🏻
