### ISSUE TITLE
typo on 'Extend Core Flow'

### ISSUE THREAD

**Issue by acandael** [medusajs/medusa#10706]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

the brand specified in the request paramters.

should be: "the brand specified in the request parameters.

### How can this issue be resolved?

1. change "paramters" to "parameters"
2.
3.
...

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for reporting this! Opened a PR to fix it
