### ISSUE TITLE
[Docs] Documentation inconsistency in CMS Module Service guide

### ISSUE THREAD

**Issue by matteovava** [medusajs/medusa#10701]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

There's an inconsistency in the documentation for integrating a CMS system:
https://docs.medusajs.com/learn/customization/integrate-systems/service

The guide first introduces a `CmsModuleService` class, but then shows methods under a separate `BrandClient` class. I think that this is wrong and all all methods (`sendRequest`, `createBrand`, `deleteBrand`, `retrieveBrands`) should be part of the `CmsModuleService` class.

Am i right?

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for reporting this! Yes you're right, it's a typo. Will open a PR to fix it
