### ISSUE TITLE
[Bug]: Custom File upload, is not able to pass file object properly 

### ISSUE THREAD

**Issue by ailoittejoy** [medusajs/medusa#10704]
### Package.json file

```JSON
{
	"name": "medusa-starter-default",
	"version": "0.0.1",
	"description": "A starter for Medusa projects.",
	"author": "Medusa (https://medusajs.com)",
	"license": "MIT",
	"keywords": [
		"sqlite",
		"postgres",
		"typescript",
		"ecommerce",
		"headless",
		"medusa"
	],
	"scripts": {
		"build": "medusa build",
		"seed": "medusa exec ./src/scripts/seed.ts",
		"start": "medusa start",
		"dev": "medusa develop",
		"setup-db": "npx medusa build && npx medusa db:migrate && npx medusa db:sync-links && medusa exec ./src/scripts/seed.ts",
		"test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
		"test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
		"test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
	},
	"dependencies": {
		"@medusajs/admin-sdk": "latest",
		"@medusajs/cli": "latest",
		"@medusajs/framework": "latest",
		"@medusajs/medusa": "latest",
		"@mikro-orm/core": "5.9.7",
		"@mikro-orm/knex": "5.9.7",
		"@mikro-orm/migrations": "5.9.7",
		"@mikro-orm/postgresql": "5.9.7",
		"awilix": "^8.0.1"
		"nodemailer": "^6.9.16",
		"pg": "^8.13.0",
		"zod": "^3.23.8"
	},
	"devDependencies": {
		"@medusajs/test-utils": "latest",
		"@mikro-orm/cli": "5.9.7",
		"@swc/core": "1.5.7",
		"@swc/jest": "^0.2.36",
		"@types/jest": "^29.5.13",
		"@types/node": "^20.0.0",
		"@types/nodemailer": "^6",
		"@types/react": "^18.3.2",
		"@types/react-dom": "^18.2.25",
		"jest": "^29.7.0",
		"prop-types": "^15.8.1",
		"react": "^18.2.0",
		"react-dom": "^18.2.0",
		"ts-node": "^10.9.2",
		"typescript": "^5.6.2",
		"vite": "^5.2.11"
	},
	"engines": {
		"node": ">=20"
	},
	"packageManager": "yarn@4.5.2"
}
```

### Node.js version

v20.16.0

### Database and its version

PostgreSQL 16.2

### Operating system name and version

linux

### Browser name

Chrome

### What happended?

I created a File Provider Module to upload to gcp, file is getting uploaded but we are not able to view that files since file has public access also still same.

Here is the File Module Service
`import { Logger, ProviderFileResultDTO, ProviderUploadFileDTO } from "@medusajs/framework/types"
import { AbstractFileProviderService } from "@medusajs/framework/utils"
import { Storage } from "@google-cloud/storage";

type InjectedDependencies = {
	logger: Logger
}

type Options = {
	privateBucketName: string;
	projectId: string;
	basePublicUrl: string;
	privateKey: string;
}

class GcpFileProviderService extends AbstractFileProviderService {
	protected logger_: Logger
	protected options_: Options

	private storage: Storage;
	static identifier = "gcp-file";

	constructor(
		{ logger }: InjectedDependencies,
		options: Options
	) {
		super()
		this.logger_ = logger;
		this.options_ = options;
		const credentials = JSON.parse(this.options_.privateKey)
		// Initialize GCP Storage
		this.storage = new Storage({
			projectId: this.options_.projectId,
			credentials: {
				private_key: credentials.private_key,
				client_email: credentials.client_email,
			},
		});
	}

	async upload(file: ProviderUploadFileDTO): Promise<ProviderFileResultDTO> {
		try {
			const bucket = this.storage.bucket(this.options_.privateBucketName);
			const r = Math.random().toString(36).substring(7);
			let newFileName = `${Date.now() + r}-${file.filename}`;
			const fileObj = bucket.file(newFileName);
			await fileObj.save(file.content, {
				contentType: file.mimeType,
				metadata: {
					contentType: file.mimeType,
					contentDisposition: "inline"
				},
			});
			await fileObj.makePublic();
			// Check if the file has been made public successfully
			const [metadata] = await fileObj.getMetadata();
			console.log("File Metadata:", metadata);
			const publicUrl = `${this.options_.basePublicUrl}/${this.options_.privateBucketName}/${newFileName}`;
			return { url: publicUrl, key: newFileName };
		} catch (error) {
			console.error('Error upload:', error);
			throw new Error('Unable to upload file');
		}
	}

}

export default GcpFileProviderService`

We teste the above code in Nodejs, it's working perfectly, here is the code
`exports.upload = async (bucketName, file) => {
	const storage = new Storage({
		projectId: 'sample-app-336407',
		keyFilename: path.join(__dirname, './service-account.json'),
	});
	let newFileName = `${Date.now()}-${file.originalname}`;
	const bucket = storage.bucket(bucketName);

	await bucket.file(newFileName).save(file.buffer, {
		contentType: file.mimeType,
		public: true,
		metadata: {
			contentType: file.mimeType,
			contentDisposition: 'inline',
		},
	});
	const publicUrl = `https://storage.googleapis.com/${bucketName}/${newFileName}`;
	console.log('publicUrl', publicUrl);
	return { message: 'File uploaded successfully.', url: publicUrl };
};`

### Expected behavior

After upload we should we able to view the file.

### Actual behavior

After upload file is not viewable. permission is already granted i.e public access is set to true

### Link to reproduction repo

N/A

**Comment by sradevski** [comment]
Hi there, I am not sure how we can help you here, you need to debug why the file is not available. For discussions or help please go to Discord, or specify which part exactly is a bug in Medusa core.

**Comment by ailoittejoy** [comment]
@sradevski I was able to fix vie just adding line
`			const content = Buffer.from(file.content, "binary")
			await fileObj.save(content, {
				contentType: file.mimeType,
				public: true,
				metadata: {
					contentType: file.mimeType,
					contentDisposition: "inline"
				},
			});`
If you see in Nodejs re.file are always in buffer not in binary. Here in medusa file.content is in a binary-encoded string.
This might create confusion in mind of developers, keeping same format in the backend sounds, rather than changing it
