### ISSUE TITLE
[Bug]: Expand customer by customer group not working (storefront)

### ISSUE THREAD

**Issue by fxmb** [medusajs/medusa#10714]
### Package.json file

```JSON
/
```

### Node.js version

v20

### Database and its version

16

### Operating system name and version

Docker

### What happended?

When I try to fetch a customer including their customer group(s) I get a validation error on the server. 

This is my call:

```
 return await sdk.client
    .fetch<{ customer: StoreCustomer }>(`/store/customers/me`, {
      method: "GET",
      query: {
        fields: "*customer_group",
      },
      headers,
      next,
    })
    .then(({ customer }) => customer)
    .catch(() => null)
}
```

My backend throws an error:

`error:   Requested fields [customer_group] are not valid
`
What am I missing here? How else am I supposed to fetch a customers group from the storefront.

Is there an overview of all relations I can call for a specific entity? Would be great if this was typed and not simply a string 

### Expected behavior

Return customer_group

### Actual behavior

Doesnt return Return customer_group

### Link to reproduction repo

none

**Comment by sradevski** [comment]
The field is called `groups`, As documented here: https://docs.medusajs.com/api/admin#customers_customer_schema

**Comment by fxmb** [comment]
I get the same error when extending it by `*groups`...

**Comment by fxmb** [comment]
Is there any update on this? The issue persists:

```error:   Requested fields [groups] are not valid```

**Comment by fxmb** [comment]
Any update on this?

**Comment by fxmb** [comment]
This is still not working...

**Comment by oreldx** [comment]
Same issue where `?expand=groups` isn't rejected, but didn't affect the result.

Quick fix : create a loader for this route `src/loaders/extend-customer-fields.ts`
```ts
export default async function () {
  const imports = (await import(
    '@medusajs/medusa/dist/api/routes/store/customers/index'
  )) as any;
  imports.defaultStoreCustomersRelations = [
    ...imports.defaultStoreCustomersRelations,
    'groups',
  ];
}
```

Note: it's going to provide **groups** everytime in the `store/customers/me` but at least you have it.

**Comment by fxmb** [comment]
Thanks for letting me now. Will try out
