### ISSUE TITLE
Configure Additional Data Validation is confusing

### ISSUE THREAD

**Issue by acandael** [medusajs/medusa#10710]
### What Medusa version and documentation are you using?

2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

the given code example is:

import { defineMiddlewares } from "@medusajs/framework/http"
import { z } from "zod"

export default defineMiddlewares({
  routes: [
    {
      matcher: "/admin/products",
      method: ["POST"],
      additionalDataValidator: {
        brand_id: z.string().optional(),
      },
    },
  ],
})

This is confusing, as we created in the previous chapter a "/admin/brands" route.

### How can this issue be resolved?

1.Indicate that the code should be added to the already existing code:

import {
  defineMiddlewares,
  validateAndTransformBody,
} from "@medusajs/framework/http";

import { z } from "zod";

import { PostAdminCreateBrand } from "./admin/brands/validators";

export default defineMiddlewares({
  routes: [
    {
      matcher: "/admin/brands",
      method: "POST",
      middlewares: [validateAndTransformBody(PostAdminCreateBrand)],
    },
    {
      matcher: "/admin/products",
      method: ["POST"],
      additionalDataValidator: {
        brand_id: z.string().optional(),
      },
    },
  ],
});
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for reporting this! If I'm understanding correctly, the confusing part is the missing middleware for `/admin/brands`, correct?

I'll open a PR to make it clearer that there could be an existing code in the file. We omit the code from the previous chapter so that you can generally follow these guides even if not in the specified order.

**Comment by acandael** [comment]
Hi shahednasser, yes. Under Extend Core Flow, 2. Configure Additional Data Validation,  the docs say:

"So, create src/api/middlewares.ts with the following content:"

This is confusing because in the previous chapters where we extend the system with a brand, we have already created this file with this content:

```
import { 
  defineMiddlewares,
  validateAndTransformBody,
} from "@medusajs/framework/http"
import { PostAdminCreateBrand } from "./admin/brands/validators"

export default defineMiddlewares({
  routes: [
    {
      matcher: "/admin/brands",
      method: "POST",
      middlewares: [
        validateAndTransformBody(PostAdminCreateBrand),
      ],
    },
  ],
})
```

**Comment by shahednasser** [comment]
Got it, thanks for sharing! I've amended the content in the PR to avoid confusion.
