### ISSUE TITLE
Wrong classname in Integrate Systems > CMS Module

### ISSUE THREAD

**Issue by acandael** [medusajs/medusa#10724]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In the second code snippet, the classname is 'BrandClient' while it should be CmsModuleService

### How can this issue be resolved?

1. change classname from 'BrandClient' to CmsModuleService
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Hello, this issue was previously resolved but thank you for reporting! If you're still seeing the typo, maybe try to clear the cache.
