### ISSUE TITLE
[Bug]: Custom Payment Provider Not Initializing

### ISSUE THREAD

**Issue by okechukwu0127** [medusajs/medusa#10730]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "@react-email/components": "^0.0.28",
    "@rokmohar/medusa-plugin-meilisearch": "^0.1.1",
    "awilix": "^8.0.1",
    "bcrypt": "^5.1.1",
    "medusa-payment-paystack": "^2.0.0",
    "pg": "^8.13.0",
    "react-table": "^7.8.0",
    "resend": "^4.0.1",
    "uuid": "^11.0.3"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/cookie-parser": "^1.4.8",
    "@types/jest": "^29.5.14",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-jest": "^29.2.5",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v20.11.0

### Database and its version

postgres:13.5

### Operating system name and version

MacBook Pro , Sonoma 15.2

### Browser name

Chrome

### What happended?

I created a custom payment provider service for my medusa 2 application (identifier as aip_payment). Followed the tutorial at https://docs.medusajs.com/resources/references/payment/provider

<img width="857" alt="image" src="https://github.com/user-attachments/assets/8cc0eab9-45ac-4e90-9a20-37546472ea1b" />

I was able to see the new payment provider record on the `payment_provider` table when i started the medusa admin application

<img width="1086" alt="image" src="https://github.com/user-attachments/assets/f7a76b58-b992-4936-b9b0-c30d2e90b0b6" />

I also added the payment provider to my region successfully
<img width="655" alt="image" src="https://github.com/user-attachments/assets/5aed181b-b1ad-405e-885e-ca2e67322a17" />

I also configured the medusa storefront to recognise the new payment provider and show it as part of the payment options
which also shows up when the customer wants to checkout and make payment.

<table width="100%"><tr>
<td>
<img width="844" alt="image" src="https://github.com/user-attachments/assets/80ae2d56-070f-4a05-bb57-80ccdae7219f" />
</td>
<td>
<img width="786" alt="image" src="https://github.com/user-attachments/assets/626197aa-dfd4-4d62-909f-fba679a2e322" />

</td>
</tr></table>

<img width="994" alt="image" src="https://github.com/user-attachments/assets/0a83597d-1158-416d-bf8b-1ae766c76d3e" />

The issue i notices is this:

When i select my new custom payment provider as the payment option, i get the following error on the backend
and the frontend payment process brakes
  ` error:   Could not resolve 'container'`
  
  
<table width="100%"><tr>
<td>
<img width="824" alt="image" src="https://github.com/user-attachments/assets/0531380e-ee5c-4b27-91cf-acf9d51d033b" />
</td>
<td>
<img width="822" alt="image" src="https://github.com/user-attachments/assets/6cfbcae0-a364-4b26-bf41-d7ac7eaee107" />
</td>
</tr></table>

The error on the store-front log

  `             Performing request to:
            URL: http://localhost:9000/store/payment-collections/pay_col_01JFX9YSB8DK5X5XBGPRVT410V/payment-sessions
            Headers: {
            "accept": "application/json",
            "authorization": "<REDACTED>",
            "content-type": "application/json",
            "x-publishable-api-key": "pk_6bb9039d70d9dee8b9238a2e9e4b1223307fcc74b9cf77a8bdce0f3dfbe3ea1d"
            }

            Received response with status 500

            ⨯ src/lib/util/medusa-error.ts (20:11) @ medusaError
            ⨯ Error: Error setting up the request: An unknown error occurred.
                at medusaError (./src/lib/util/medusa-error.ts:22:15)
            digest: "399351394"
            18 |   } else {
            19 |     // Something happened in setting up the request that triggered an Error
            > 20 |     throw new Error("Error setting up the request: " + error.message)
                |           ^
            21 |   }
            22 | }
            23 |
                POST / ng / checkout ? step = payment 500 in 357ms
 `
  
  
what my medusa-config looks like
**NOTE**
When i added `id: "aip-payment"` to my custome payment provider configuration, i realized the name on the payment_provider table changes to `pp_aip_payment_aip_payment`. Working with that still brakes the application when selected on the storefront

<img width="579" alt="image" src="https://github.com/user-attachments/assets/de22fcbf-bdab-4edd-8931-e42c785a185b" />

### Expected behavior

I expected the application to initialize my custome payment provider initialize method
<img width="795" alt="image" src="https://github.com/user-attachments/assets/090d579b-74ea-47e9-af7d-f6629fd787f3" />

### Actual behavior

When i selected the payment provider option i created from the customer storefront, the application brakes and I was not able to complet checkout

<img width="823" alt="image" src="https://github.com/user-attachments/assets/8f94a99e-540f-4e16-aef5-dc5f2a419b87" />

<img width="839" alt="image" src="https://github.com/user-attachments/assets/e97a470f-ef45-4a36-a9b4-c7a3efd6884e" />

### Link to reproduction repo

https://github.com/AsharamiInnovations/boost-backend-v2/tree/eze/ft/aip-payment

**Comment by shahednasser** [comment]
Hello, the error is because you're resolving `container` in the provider's constructor, which doesn't exist in a module's container (see [here](https://docs.medusajs.com/resources/medusa-container-resources#module-container-resources) the resources you can resolve in a module). Can you let me know what you're trying to achieve?

**Comment by okechukwu0127** [comment]
> Hello, the error is because you're resolving `container` in the provider's constructor, which doesn't exist in a module's container (see [here](https://docs.medusajs.com/resources/medusa-container-resources#module-container-resources) the resources you can resolve in a module). Can you let me know what you're trying to achieve?

Thanks @shahednasser  for your reply,

I am trying to load the paymentModuleService module from the container inside the constructure so that i can use it inside my methods. Thus

**I TRIED THIS TWO APPROACHES**

_inside my constructure i did this_
`this.paymentModuleService = container.resolve(Modules.PAYMENT);`


_inside my authorizePayment method i can do this_
```
 const paymentData = await this.paymentModuleService.authorizePayment(
        externalId
      );
```
      
      
**_I have also tried this approach_**

_inside my contructure i have this_
`this.container = container;`

_inside the authorizePayment method i did this_
 ```
   this.paymentModuleService = this.container.resolve(Modules.PAYMENT);
 const paymentData = await this.paymentModuleService.authorizePayment(
        externalId
      );
```

**APPROACH ONE**
<table width="100%">
<tr>
<td>
<img width="458" alt="image" src="https://github.com/user-attachments/assets/70c606d7-c4e8-4154-a411-a1bb208dc186" />
</td>
<td>
<img width="605" alt="image" src="https://github.com/user-attachments/assets/65da3027-2d10-4ae6-bf51-b381f8df8b8a" />
</td>
</tr>
</table>


**APPROACH TWO**
<table width="100%">
<tr>
<td>
<img width="684" alt="image" src="https://github.com/user-attachments/assets/155179b6-d5c3-4547-b478-02931dfc7875" />
</td>
<td>
<img width="714" alt="image" src="https://github.com/user-attachments/assets/37ff4bb1-d2e9-4821-b9cb-63d195f50149" />
</td>
</tr>
</table>


In the tutorial, they used `this.client` was used and i neer saw were **client** was declaired
<img width="672" alt="image" src="https://github.com/user-attachments/assets/d841972f-d2e1-444c-a49e-4fae013cc156" />

I would appreciate a little clariffication or a pointer on how I can make this work as i feel I am very close to the final peice.

Merry Xmas

**Comment by shahednasser** [comment]
Modules are isolated, which means they can't resolve other modules. Learn more about it in [this documentation](https://docs.medusajs.com/learn/fundamentals/modules/isolation).

The `client` referred to in the code snippets is just a dummy client to showcase how you can send requests to a third-party service. So, for example, if you're integrating Stripe, you initialize the client in the constructor of your payment provider, then use its methods to send requests to stripe in your methods.

We should clarify the documentation around this, so I'll leave this issue open to address it. But basically, replace the `this.client.authorizePayment` part with the logic to authorize the payment based on the third-party payment provider you're integrating. Let me know if this is unclear.
