### ISSUE TITLE
Docs: page can't be scrolled down by arrow keys or shortcuts of Chrome Vim plugin

### ISSUE THREAD

**Issue by hcsum** [medusajs/medusa#10746]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Page can't be scrolled up or down by arrow keys. For users heavily rely on keyboard to scroll up and down a page, it can get very inconvinent to reach for the trackpad or mouse when browsing the docs. Especially when one is working in the editor or terminal and rely solely on keyboard, feel an abrupt break of workflow when needing to look the Medusa docs from time to time. 

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for reporting this! Will look into how we can improve it
