### ISSUE TITLE
Page not found Error

### ISSUE THREAD

**Issue by TALHA0713** [medusajs/medusa#10775]
### What Medusa version and documentation are you using?

v1

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Hi, I am developing a custom payment processing plugin and want to integrate any payment gateway with it. I am following the guide on [this page](https://docs.medusajs.com/v1/modules/carts-and-checkout/backend/add-payment-provider). However, when I click on the link for testing the plugin, it takes me to [this page](https://docs.medusajs.com/development/plugins/create#test-your-plugin), but the page is not showing any data.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by helloquang** [comment]
https://docs.medusajs.com/development/plugins/create#test-your-plugin

Should be this link

https://docs.medusajs.com/v1/development/plugins/create#test-your-plugin

**Comment by TALHA0713** [comment]
Hello @shahednasser,

I was exploring [this page](https://docs.medusajs.com/v1/modules/carts-and-checkout/backend/add-payment-provider) about modules. However, when I followed the instructions to test the module, I referred to [this guide](https://docs.medusajs.com/v1/development/plugins/create#test-your-plugin), and I received a URL related to plugin testing rather than module testing.

Could you please clarify if this is the correct approach or if there is a specific guide for testing modules?

Thank you in advance for your help!
