### ISSUE TITLE
Feature Request - Sentry Integration

### ISSUE THREAD

**Issue by dwene** [medusajs/medusa#1080]
We use Sentry (https://sentry.io/) to keep track of error logs and uncaught exceptions. It would be really nice if there was a plugin that we could use to plug that into sentry, so we are notified when things fail internally.

**Comment by srindom** [comment]
Adrien built an amazing Sentry plugin here: https://github.com/adrien2p/medusa-plugins/tree/main/packages/medusa-plugin-sentry
