### ISSUE TITLE
Error during serving the app with heroku

### ISSUE THREAD

**Issue by Jos36** [medusajs/medusa#1081]
I just deployed a clear medusa instance on Heroku following the official tutorial, installed PostgreSQL and redisToGo.
and this error showed up

> 2022-02-17T23:28:31.988153+00:00 app[web.1]: [ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
> 2022-02-17T23:28:31.988162+00:00 app[web.1]:     at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
> 2022-02-17T23:28:31.988163+00:00 app[web.1]:     at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
> 2022-02-17T23:28:33.995505+00:00 app[web.1]: [ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
> 2022-02-17T23:28:33.995519+00:00 app[web.1]:     at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
> 2022-02-17T23:28:33.995519+00:00 app[web.1]:     at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
> 2022-02-17T23:28:36.003228+00:00 app[web.1]: [ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
> 2022-02-17T23:28:36.003245+00:00 app[web.1]:     at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
> 2022-02-17T23:28:36.003245+00:00 app[web.1]:     at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
> 2022-02-17T23:28:38.009876+00:00 app[web.1]: [ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
> 2022-02-17T23:28:38.009884+00:00 app[web.1]:     at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
> 2022-02-17T23:28:38.009884+00:00 app[web.1]:     at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
> 2022-02-17T23:28:40.019040+00:00 app[web.1]: [ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
> 2022-02-17T23:28:40.019046+00:00 app[web.1]:     at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
> 2022-02-17T23:28:40.019046+00:00 app[web.1]:     at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
> 2022-02-17T23:28:42.027095+00:00 app[web.1]: [ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
> 2022-02-17T23:28:42.027114+00:00 app[web.1]:     at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
> 2022-02-17T23:28:42.027115+00:00 app[web.1]:     at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
> 2022-02-17T23:28:44.051481+00:00 app[web.1]: [ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
> 2022-02-17T23:28:44.051488+00:00 app[web.1]:     at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
> 2022-02-17T23:28:44.051489+00:00 app[web.1]:     at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
> 2022-02-17T23:28:46.061898+00:00 app[web.1]: [ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
> 2022-02-17T23:28:46.061907+00:00 app[web.1]:     at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
> 2022-02-17T23:28:46.061908+00:00 app[web.1]:     at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
> 2022-02-17T23:28:48.068710+00:00 app[web.1]: [ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
> 2022-02-17T23:28:48.068721+00:00 app[web.1]:     at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
> 2022-02-17T23:28:48.068722+00:00 app[web.1]:     at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
> 2022-02-17T23:28:50.073232+00:00 app[web.1]: [ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
> 2022-02-17T23:28:50.073238+00:00 app[web.1]:     at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
> 2022-02-17T23:28:50.073239+00:00 app[web.1]:     at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)

**Comment by adrien2p** [comment]
I think you did not set the redis url properly, 
did you put the « : » after « redis://»  such as « redis://: » ?

**Comment by youssefmohamedsabry** [comment]
thank you for helping, it's a bit tricky I didn't see this at all.

**Comment by olivermrbl** [comment]
Assuming this is resolved, so closing the issue. Let me know if this is not the case @Jos36 :)
