### ISSUE TITLE
Add `POST/DELETE /admin/collections/:id/products/batch` endpoints to @medusajs/medusa-js and medusa-react

### ISSUE THREAD

**Issue by srindom** [medusajs/medusa#1089]
The new batch endpoints introduced by https://github.com/medusajs/medusa/pull/1032 are missing in the client and medusa-react.

**Comment by gaurav1999** [comment]
Request to close this issue. @srindom

**Comment by olivermrbl** [comment]
It is yet to be added to both [`medusa-js`](https://github.com/medusajs/medusa/blob/develop/packages/medusa-js/src/resources/admin/collections.ts) and [`medusa-react`](https://github.com/medusajs/medusa/blob/develop/packages/medusa-react/src/hooks/admin/collections/mutations.ts), so should be kept open @gaurav1999

**Comment by nawed2611** [comment]
Hey! Is this issue still open to work on?

**Comment by kasperkristensen** [comment]
Hey @nawed2611, yes it is. If you are up for it feel free to assign the issue to yourself 😄

**Comment by richardwardza** [comment]
I've picked this up as it seems to be inactive since 05 May..
