### ISSUE TITLE
Add `DELETE /store/auth` to `@medusajs/medusa-js`

### ISSUE THREAD

**Issue by olivermrbl** [medusajs/medusa#1094]
In `medusa-js`, add `signOut()` to the [store AuthResource](https://github.com/medusajs/medusa/blob/master/packages/medusa-js/src/resources/auth.ts).

**Comment by kb-0311** [comment]
hello can you please be a little more like you want a new function called signOut() where you want to delete the store/auth path ?

**Comment by olivermrbl** [comment]
We would like a new method similar to `exists` [here](https://github.com/medusajs/medusa/blob/93bc6a164aa12d9e8b425196e81e0627a1b920ce/packages/medusa-js/src/resources/auth.ts#L35) called `signOut` which send a request to `DELETE /store/auth`. 

Something like:
```
signOut(): ResponsePromise<StoreDeleteAuthRes> {
    const path = `/store/auth`
    return this.client.request("DELETE", path)
  }
```


Hope it makes sense 👍

**Comment by HereBeAndre** [comment]
Hi, I see this issue has been here for a while. If possible, I'd like to pick it up :)

**Comment by Arzamendiaariel** [comment]
Hi, any progress on this?
