### ISSUE TITLE
[Bug] Store API

### ISSUE THREAD

**Issue by adrien2p** [medusajs/medusa#1121]
https://github.com/medusajs/medusa/blob/806c42650cc48eaec790a9009705d5d51683e914/packages/medusa/src/api/routes/store/index.js#L31

It seams that the expected behaviour here is that all the store API routes are under the auth middleware. But, the auth middleware check if there is no error to reject the request otherwise the request is approved . But in reality, when no token are passed through the request, the 3rd argument `info` contains `No auth token`. What was the expected behaviour for the store API. I think something is missing.

**Comment by srindom** [comment]
The middleware here checks if the customer doing the request is authenticated or not. If the customer is authenticated the `req` object is decorated with the user details. As such we are just ignoring if authentication fails as you are still allowed to perform most operations as a "guest".

**Comment by adrien2p** [comment]
Alright, so the customer auth is optional, might be worth to specify it somewhere in the code since we don't understand that easily I think 😂

**Comment by amaidah** [comment]
Is there a way to enforce api key for all store api requests? Would prefer to make it harder to scrape a store than hitting `/store/products`
