### ISSUE TITLE
getDateClassname not defined

### ISSUE THREAD

**Issue by petterssonjohan** [medusajs/medusa#1124]
Get errors when adding a discount:

getDateClassname seems not to be defined in data-picker.tsx

![image](https://user-images.githubusercontent.com/13527694/155887467-a6fa2399-17dc-48c5-b32d-5646a2d51a2a.png)

**Comment by suezzo** [comment]
It seems that the `getDateClassname` function has been already added on the `develop` branch: https://github.com/medusajs/admin/blob/develop/src/components/atoms/date-picker/date-picker.tsx

You can try to use that branch until it lands on the master

**Comment by olivermrbl** [comment]
Thanks for reporting the issue @petterssonjohan. An @suezzo mentions, we've fixed the issue in `develop` and will release a new version of the admin later today. Will keep it open until then 👍
