### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by dwene** [medusajs/medusa#1130]
Hello!

We are building an app that hits the medusa api in a server->server fashion using nestjs. We expose some of the Admin Endpoints (with security and validation), through NestJs Graphql, which uses some fancy reflection to inspect classes and enums to generate a graphql schema. Some of the classes and enums it inspects are exposed by `@medusa/medusa-js`

After the most recent update, I'm running into this error during compile:

```
/Users/derekwene/src/nibll/nibll-home/node_modules/medusa-interfaces/dist/base-service.js:440
}();
 ^
ReferenceError: regeneratorRuntime is not defined
    at /Users/derekwene/src/nibll/nibll-home/node_modules/medusa-interfaces/dist/base-service.js:248:59
    at /Users/derekwene/src/nibll/nibll-home/node_modules/medusa-interfaces/dist/base-service.js:354:6
    at Object.<anonymous> (/Users/derekwene/src/nibll/nibll-home/node_modules/medusa-interfaces/dist/base-service.js:440:2)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .js] (/Users/derekwene/src/nibll/nibll-home/node_modules/ts-node/src/index.ts:1449:43)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
```

I believe I'm seeing this error because `medusa-interfaces` is being compiled using babel, and uses regeneratorRuntime to transpile async functions for older browsers. 

See: https://github.com/medusajs/medusa/blob/master/packages/medusa-interfaces/.babelrc#L5 

I don't really want to have to compile my typescript api code using babel in order to get this working again. Is there a reason why `medusa-interfaces` is being compiled using babel as opposed to just plain old `tsc`? I'd be happy to make a PR to fix that!

**Comment by adrien2p** [comment]
Would be nice to use tsc or equivalent in order to avoid to install more packages @olivermrbl, But I only had this error during the tests. maybe something related to your config?

```
npm i core-js/stable regenerator-runtime/runtime
```

In the mean time, you can install these packages and just importing them at the top of your main file and it should be fine without using babel. I do that in some of my tests file to avoid having to use babel.

```typescript
import 'core-js/stable';
import 'regenerator-runtime/runtime';
```

**Comment by srindom** [comment]
Thanks @adrien2p for the fix - we'd happily accept a PR that moves to tsc instead of babel :)
