### ISSUE TITLE
Extend MoneyAmount and add PriceList

### ISSUE THREAD

**Issue by pKorsholm** [medusajs/medusa#1134]
Extend the existing money amount component with the following fields: 
- type: enum “default” | “sale” | “cost”
- min_quantity: number
- max_quantity: number
- starts_at: timestamp
- ends_at: timestamp
- customer_group_id: string
    - Foreign key to customer group

**Comment by kasperkristensen** [comment]
@pKorsholm @olivermrbl Should Do you think we should remove the `sale_amount` then?

**Comment by olivermrbl** [comment]
I think that reasonable, yes!

Though, one could argue, that we could keep `amount` and `sale_amount` for ease of use and omit the `type` for now, since "cost" is our only additional type right now

**Comment by kasperkristensen** [comment]
# Update to ticket

Extend the existing money amount component with the following fields:

min_quantity: number
max_quantity: number

Other logic is moved to new PriceList entity
