### ISSUE TITLE
Research storage of `customer_id` and `cart_id` for api requests in store

### ISSUE THREAD

**Issue by pKorsholm** [medusajs/medusa#1135]
Research how to best include the `cart_id` in api requests made to the `/store` endpoints in order to support price calculations based on region, country and customer_group

we should look at how other existing solutions solve this issue of session storage and see how we can solve it as unobtrusively  as possible. 

Consider the same approach for `cart_id` as is used for `customer_id` where `req.user.customer_id` is set when a customer logs in.

**Comment by srindom** [comment]
There are two scenarios we are trying to solve for here:

First case is that a customer is going through the purchasing experience and as such expect to see the prices that they will actually pay. By sharing details about the customer and region she is shopping in that will suffice in showing the correct prices. If the customer already has a cart it makes sense to just automatically share the cart id similarly to the cookie method as the cart will contain both customer and region details. However, if the customer doesn't have a cart we need to figure out how the api should allow pricing to be determined. In this case I think it makes sense to allow the client to specify the region to get the price for (customer auth will be handled automatically).

The second case is that the api is not being consumed in a regular browser env; e.g. in the build process of a ssg. In this case you wouldn't want to first create a cart, manage its cookie and then make the request you want to.

So my suggestion is that we start off by introducing query params for the /store/products/* endpoints that may be used to force price selection context. 

We can then introduce a way of controlling session data once we have the simple impl. done :) what are you're thoughts on this?

**Comment by pKorsholm** [comment]
I think that is an okay approach, which allows us to get off the ground quickly. I think implementing a session based region/cart storage will not be a big problem and as long a we can extract the information in the api layer, the specific mechanism should be changeable with relative ease and the technical debt obtained is rather small i think.

**Comment by srindom** [comment]
Great - do you want to create a new ticket that outlines the work to be done on this ticket then? :)

**Comment by srindom** [comment]
Is this ready to be closed?
