### ISSUE TITLE
Add `DiscountCondition` entity

### ISSUE THREAD

**Issue by fPolic** [medusajs/medusa#1143]
- introduce new entity: `DiscountCondition` which should model a discount condition that can be applied to a discount rule
- each discount rule can have an array of discount conditions
- remove `valid_for` from the `DiscountRule`and replace it with `conditions: DiscountCondition[]`

**Comment by olivermrbl** [comment]
I've attached a potential way of modeling the entity. The idea is, that `DiscountRuleConditions` can only hold one type of resource (products, types, tags, etc.), so the `type` field is really only there for ease of use.
```
class DiscountRuleCondition

  @PrimaryColumn()
  id: string

  @Enum
  type: "products" | "product_types" | "product_tags" |   "product_collections" | "customer_groups"

  @ManyToMany(() => Product)
  products: Product[]

  @ManyToMany(() => ProductType)
  product_types: ProductType[]

  @ManyToMany(() => ProductTag)
  product_tags: ProductTag[]

  @ManyToMany(() => ProductCollection)
  product_collections: ProductCollection[]

  @ManyToMany(() => CustomerGroup)
  customer_groups: CustomerGroup[]
```
And then we would add the above entity to `DiscountRules` like you've mentioned in the description like so:
```
class DiscountRule

  @PrimaryColumn()
  id: string
  ...

  @ManyToOne(() => DiscountRuleCondition)
  conditions: DiscountRuleCondition[]
```
