### ISSUE TITLE
No way to register TaxProviders

### ISSUE THREAD

**Issue by dwene** [medusajs/medusa#1190]
I'm working on creating a tax plugin using `zip-tax` using the new tax api. 

I have built my plugin here: https://github.com/lambda-curry/medusa-tax-ziptax/pull/1 but I am struggling to find a way to register the Tax Service with Medusa.

For all the other services (fulfillment, payment, etc), they extend a base class (FulfillmentService, PaymentService), and then are injected into the container using those base classes to know what type of provider they are: https://github.com/medusajs/medusa/blob/806c42650cc48eaec790a9009705d5d51683e914/packages/medusa/src/loaders/plugins.js#L232

But I can't find any code to handle an ITaxService. Honestly I don't think using an interface will work for the container, because interfaces get compiled out when built as javascript, so I think we need a class for `BaseTaxService`, to register tax providers. Then we need the additional code in the TaxProviderService that registers the installed TaxProviderServices and put's them in the database, similar to how it is done for other providers here: 

https://github.com/medusajs/medusa/blob/master/packages/medusa/src/loaders/defaults.js#L89

**Comment by adrien2p** [comment]
From what I can see so far based on the [plugin loader](https://github.com/medusajs/medusa/blob/master/packages/medusa/src/loaders/plugins.js) line 113 you must put your tax calculation strategy under the strategies/tax-calculation directory to take it in count

**Comment by dwene** [comment]
So it seems like there's 2 different things here:

`ITaxService` which seems like it overwrites the `SystemTaxService`
https://github.com/medusajs/medusa/blob/master/packages/medusa/src/services/system-tax.ts#L11
https://github.com/medusajs/medusa/blob/master/packages/medusa/src/interfaces/tax-service.ts#L45

Then there's tax calculation strategies.
https://github.com/medusajs/medusa/blob/master/packages/medusa/src/strategies/tax-calculation.ts
https://github.com/medusajs/medusa/blob/master/packages/medusa/src/interfaces/tax-calculation-strategy.ts

The `TaxCalculationStrategy` seems to take the data that the `ITaxService` returns. There's also a database table for TaxProviders that seems to follow the same pattern as the `FulfillmentProviderService` and `PaymentProviderService`.

**Comment by adrien2p** [comment]
Oh yes indeed 🤪

**Comment by dwene** [comment]
Thanks @srindom ! Let me know if there's anyway I can help!
