### ISSUE TITLE
Can I use Medusa as a sales funnel | sales pages with bumper offers? Or is there a starter template for such? Thanks

### ISSUE THREAD

**Issue by Swifilaboroka** [medusajs/medusa#1223]

**Comment by Swifilaboroka** [comment]
Thanks for your kind replies. Here's a short description (ideally or in
principle). I need to know if I can customize MedusaJS to be something like
a Click Funnels?
- Landing page
- Call to action pop-up (e.g sign up)
- Redirect to product or service page (offer)
- When the visitor (lead) purchases, then a pop up with a supplimentary
offer shows up with 'free bonuses' (offer)
- If they buy , the above step repeats till they decide to checkout.
- If they don't buy, the supplimentary offer, then a down selling [offer
with lower price than that of the (first) up sell], then they are directed
to checkout.
1. If they leave the process without buying, then they get segmented to the
leads with:
a) 'Abandoned cart' for later email marketing

I trust you get an idea.
Thanks in advance 😊

**Comment by klauss194** [comment]
Hi
Let's take them one by one:
- Landing page -> medusa is a software that helps you with the payment/product part of things. To build landing pages you need completely different platforms -> ( like Webflow, GrapeDrop etc.. ) -> and then you would integrate these platforms with medusa ( which would handle your payment page / checkout.
- Call to action pop-up (e.g sign up) -> for this you need either custom code or other software. there are many other apps out there to help you handle pop-ups based on user actions ( I don't know any right now )

What you require is most probably a developer to help you integrate all these.
The only solution that would allow all-in-one that I can think of for this is Wordpress.
However we all know how much of a pain that is.

Hope it helps.

**Comment by olivermrbl** [comment]
Thanks for showing interest! Feature requests have been moved to GitHub Discussions, so closing this :)
