### ISSUE TITLE
[Perf] Performance issues around line items and draft orders

### ISSUE THREAD

**Issue by adrien2p** [medusajs/medusa#1249]
@dwene show me some performance issues around the line items (remove, create) and the draft order interaction
![image](https://user-images.githubusercontent.com/25098370/160202432-10e02893-9344-44ba-ab6f-991bf406bb47.png)

I will have a look but I wanted to know @olivermrbl if this is something you already encounter.

I am sure that in the code base, there is some operations that can be handled out of the request lifecycle if that does not impact directly the client. Finding which part must be processed during the request lifecycle and which part does not required to be processed during the request lifecycle could already improve the response time globally.

Also, as we discussed, we have to look into the queries and run an [EXPLAIN ANALYSE](https://docs.postgresql.fr/13/sql-explain.html) in order to start finding bottleneck and improve queries performances. Some process could also be made directly into the database which as we discussed, help maintaining consistency as well as improve performance since it is done on a low level.

I am waiting your feedback before digging deeper into that as if thats already known and that you have some input I might end up working twice on that 😂

**Comment by srindom** [comment]
@dwene could you give some indication of the size of the draft order cart so we can try to play around with this?

**Comment by dwene** [comment]
At max we have 25 unique product variants in the cart at a time. The typical user probably has around 7 items in the cart though.

**Comment by srindom** [comment]
And what is the update that is being performed?

**Comment by adrien2p** [comment]
I have also suggested to look into the indices usage after analysing the queries since depending on the query an index can end up not being used and therefor slow down the query

**Comment by adrien2p** [comment]
@srindom it seams from my understanding that it is happening when they are swapping lines items, they remove and add lines

**Comment by adrien2p** [comment]
@dwene also, depending on your tests it might be worth looking on the database capabilities, memory, cpu etc to see if there is a sizing problem as well and remove or not one problem

**Comment by dwene** [comment]
Yea it's particularly slow when creating or removing line items.

I think some of it could be fixed by removing unnecessary save loops like this: https://github.com/medusajs/medusa/pull/1219

**Comment by dwene** [comment]
> @dwene also, depending on your tests it might be worth looking on the database capabilities, memory, cpu etc to see if there is a sizing problem as well and remove or not one problem

Yea I will look into that, but I'm running our Nest API against another schema the same database and it's running quick.

**Comment by adrien2p** [comment]
Can you give us the diff between the schemas

**Comment by dwene** [comment]
They are extremely different schemas haha. Our Nest schema contains additional tables specifically needed for our clients food subscription product.

**Comment by dwene** [comment]
![rancher lambdacurry dev_api_v1_namespaces_cattle-monitoring-system_services_http_rancher-monitoring-grafana_80_proxy_d_85a562078cdf77779eaa1add43ccec1e_kubernetes-compute-resources-namespace-pods_orgId=1 refresh=10s var-datasource=default v](https://user-images.githubusercontent.com/12628251/160206948-31b6b4d9-daa6-47bd-ad38-049244f25516.png)

Database looks pretty bored. It's all running in Kubernetes

**Comment by adrien2p** [comment]
@dwene when you say that you run the query against both schemes and that the results are different what is your process to test that at the moment

**Comment by dwene** [comment]
> @dwene when you say that you run the query against both schemes and that the results are different what is your process to test that at the moment

Sorry I think there's a misunderstanding here. I'm running the Medusa database in the same docker container as our Nest Database, and the database seems to be performing well for our Nest database (nibll-home-dev)

<img width="328" alt="image" src="https://user-images.githubusercontent.com/12628251/160207500-b956244c-f4b2-441e-ac61-e11aab12b741.png">

**Comment by adrien2p** [comment]
Ahah alright, not what I though my bad 😂 yeah so we can't compare them

**Comment by adrien2p** [comment]
We will wait @srindom feedback since he has been working around the lines items and see if he got some insight that can help. Then depending on the nature of the issue if it is needed I'll jump into the digging 👍 is that alright for you @dwene ?

**Comment by dwene** [comment]
Yep! Thanks y'all!

**Comment by joekendal** [comment]
There's still a performance issue of 4 seconds in medusa v2. I think this is a serious problem for users.

**Comment by SalahAdDin** [comment]
@joekendal need to open a new issue I think.
