### ISSUE TITLE
Interface for BatchJob strategies

### ISSUE THREAD

**Issue by fPolic** [medusajs/medusa#1264]
**Goal**
Create a common interface that BatchJob strategies implement

**DoD**
- [ ] Create and export IBatchJobStrategy interface in `/interfaces`
- [ ]  Exports AbstractBatchJobStrategy from same file
- [ ]  Strategies loader should register all BatchJobStrategies in an array that can be used from the BatchJobService
- [ ] All handlers should include static props called identifier and batchType which will be used to identify which batch type the handler can be used for

**Comments**
```ts
interface {

  /*
  * Used in the API controller to verify that the `context` param is valid
  */
  validateContext()
  
  /*
  *  Method does the actual processing of the job. Should report back on the progress of the operation.
  */
  processJob()
  
  /*
  *  Method performs the completion of the job. Will not be run if `processJob` has already moved the BatchJob to a `complete` status.
  */
  completeJob()

  /**
   * Validates that the file can be used for processJob
   */
  validateFile(fileLocation: string)

  /**
   * Builds and returns a template file that can be downloaded and filled in
   */
  buildTemplate()
}
```

**Comment by srindom** [comment]
We might need to extend the interface a bit - let's include:
```js
/**
 * Validates that the file can be used for processJob
 */
validateFile(fileLocation: string)

/**
 * Builds and returns a template file that can be downloaded and filled in
 */
buildTemplate()
```

Also, all handlers should include static props called `identifier` and `batchType` which will be used to identify which batch type the handler can be used for.

E.g.
```js
class ProductImportHandler extends AbstractBatchJobHandler {
  static identifier = "my-handler"
  static batchType = "product_import"
}
```
