### ISSUE TITLE
Implement `ProductExportStrategy`

### ISSUE THREAD

**Issue by fPolic** [medusajs/medusa#1266]
- add `ProductExportHandler` class for processing products batch export which implements the common batch job handler interface 

- **depends on:** https://github.com/medusajs/medusa/issues/1264

- [ ] given a context e.g. filters to apply when retrieving products + columns to include in the export the handler should build and stream data in csv format
- [ ] ProductExportStrategy should report progress to the BatchJobService
- [ ] ProductExportStrategy should implement the AbstractBatchJobStrategy
- [ ] ProductExportStrategy should dynamically figure out how many columns it will need to include all the data about the products in the batch. E.g. how many Product Option columns are necessary, image columns, etc.

Columns that should be supported:

- Product Handle
- Product Title
- Product Subtitle
- Product Description
- Product Status
- Product Option Name [1-*]
- Image [1-*]
- Thumbnail
- Profile [match by name]
- Product [Weight - length - width - height]
- Product [hs code, origin country, mid code, material]
- Product Collection [match by name; upsert if none exists]
- Product Type [match by name; upsert if none exists]
- Product Tags [comma separated string]
- Discountable
- External ID
- Variant Title
- SKU
- Barcode
- Inventory Quantity
- Allow backorder
- manage inventory
- Variant Option Value [0-*]
- Variant [Weight - length - width - height]
- Variant [hs code, origin country, mid code, material]
- Price DKK
- Price EUR
- Price [currency code]
- Price [region name]

**Comment by srindom** [comment]
- [ ] given a context e.g. filters to apply when retrieving products + columns to include in the export the handler should build and stream data in csv format
- [ ] ProductExportStrategy should report progress to the BatchJobService
- [ ] ProductExportStrategy should implement the AbstractBatchJobStrategy
- [ ] ProductExportStrategy should dynamically figure out how many columns it will need to include all the data about the products in the batch. E.g. how many Product Option columns are necessary, image columns, etc.

Columns that should be supported:

- Product Handle
- Product Title
- Product Subtitle
- Product Description
- Product Status
- Product Option Name [1-*]
- Image [1-*]
- Thumbnail
- Profile [match by name]
- Product [Weight - length - width - height]
- Product [hs code, origin country, mid code, material]
- Product Collection [match by name; upsert if none exists]
- Product Type [match by name; upsert if none exists]
- Product Tags [comma separated string]
- Discountable
- External ID
- Variant Title
- SKU
- Barcode
- Inventory Quantity
- Allow backorder
- manage inventory
- Variant Option Value [0-*]
- Variant [Weight - length - width - height]
- Variant [hs code, origin country, mid code, material]
- Price DKK
- Price EUR
- Price [currency code]
- Price [region name]
