### ISSUE TITLE
Bug when creating a calculated shipping option

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#1271]
If you send a request to `/admin/shipping-options` with the following body:

```
{
    "name": "My Shipping Option 3",
    "region_id": "reg_01FZ84H044PKYN2N272T5ZS369",
    "provider_id": "my-fulfillment",
    "data": {
        "id": "my-fulfillment-dynamic"
    },
    "price_type": "calculated"
}
```

You'll get an error with the following response:

```
{
    "type": "not_found",
    "message": "Could not find a fulfillment provider with id: undefined"
}
```

Even though it works completely fine when `price_type` is set to `flat_rate`. 

This is due to a bug in [package/medusa/src/services/shipping-option.js](https://github.com/medusajs/medusa/blob/master/packages/medusa/src/services/shipping-option.js). when a shipping option is being created in the service the price type is validated using `validatePriceType_`. If the type is calculated, then this method calls `canCalculate` passing it the `provider_id` and `data`:

https://github.com/medusajs/medusa/blob/2987d94fb61d0557c692a7d87f7b4cd896c17402/packages/medusa/src/services/shipping-option.js#L439-L442

But the canCalculate method in the [fulfillment-provider service](https://github.com/medusajs/medusa/blob/master/packages/medusa/src/services/fulfillment-provider.js) expects the full option object and it tries to access `optoin.provider_id` which is causing the error:

https://github.com/medusajs/medusa/blob/2987d94fb61d0557c692a7d87f7b4cd896c17402/packages/medusa/src/services/fulfillment-provider.js#L63-L66

**Comment by olivermrbl** [comment]
Solved in #1397
