### ISSUE TITLE
API: Cancel a batch operation

### ISSUE THREAD

**Issue by srindom** [medusajs/medusa#1276]
Cancels an operation that is in progress.

```
POST /admin/batch/:id/cancel
```

## DoD
- [ ] endpoint should be idempotent - e.g. calling cancel on an already canceled job is allowed and responds with 200
- [ ] BatchJobs in a completed state should not be cancelable - should fail with 422
- [ ] Should call BatchJobService.cancel; which in turn potentially cancels the jobs in the worker that are currently being processed.

**Comment by olivermrbl** [comment]
Solved in #1379
