### ISSUE TITLE
API: Confirm a batch operation

### ISSUE THREAD

**Issue by srindom** [medusajs/medusa#1277]
Completes a previously `dry_run`'ed job.

```
POST /admin/batch/:id/complete
```

## DoD
- [ ] should be idempotent - i.e. if trying to complete a job that is currently processing the completion step then nothing should happen and endpoint should respond 200
- [ ] only your own jobs can be completed i.e. `req.user.id === batch.created_by` must be true
- [ ] should call BatchJobService.complete which in turn calls the underlying handler. 
- [ ] Endpoint should not wait for the actual processing of the job to complete

**Comment by olivermrbl** [comment]
Solved in #1371
