### ISSUE TITLE
Medusa Backend support for External Database

### ISSUE THREAD

**Issue by Higherings** [medusajs/medusa#1283]
Hello, I'm trying to setup Medusa Backend with an PostgreSQL database running in another server. I do not find any documentation to know how to proceed, is this even possible ?

**Comment by adrien2p** [comment]
Hi there, you can specify the database url which can point to any database even if it is on another server or hosted on any provider.

In your medusa-config under projectConfig you just need to specify the database_url.

For postgres the connection string looks like

`postgres://YourUserName:YourPassword@YourHostname:5432/YourDatabaseName`

**Comment by Higherings** [comment]
@adrien2p Thank you.

**Comment by culy247** [comment]
@adrien2p  How to connect to google cloud sql (postgresql 14)

**Comment by adrien2p** [comment]
@culy247 you just need to specify ht connection string in database url

**Comment by yasirmturk** [comment]
Hi, I am having this problem with vercel & cockroachdb connection strings both

`npx create-medusa-app@latest --db-url postgres://default:XXX@ep-divine-silence-14771088.us-east-1.postgres.vercel-storage.com:5432?sslmode=require`
? What's the name of your project? medusa
? Enter an email for your admin dashboard user admin@yasirmturk.com

Couldn't connect to PostgreSQL using the database URL you passed. Make sure it's correct and try again.

**Comment by maguayo** [comment]
Same error, works when connecting to my local postgres, but can't connect to external URL.
I can access using "psql URL"

**Comment by impactcolor** [comment]
Same here any idea why this happens? With a client I can connect with the credentials but Medusa fails.

**Comment by jacobkerber** [comment]
Just thought I would add some information here. This might be common knowledge, but when connecting to an Azure Postgresql DB you need to add **ssl=true** to the end of the connection URL. solved all of my problems. 

Example:
`postgres://<username>:<password>@<azure-db-url>:<port>/<database-name>?ssl=true`

This gave me the hint:
[https://medium.com/burke-knows-words/using-postgresql-with-azure-and-node-js-4d26801c1807](url)

**Comment by abubakerx1da49** [comment]
to add Vercel PostgreSQL as backend remove this url `postgres://localhost/medusa-starter-default` from these two files

- .env
- medusa-config.js

and add `postgres://xxx:xxxx.vercel-storage.com:5432/verceldb?sslmode=require`.
then run `npm run seed` to seed the database.

**Comment by Sands-45** [comment]
Add double quotes around your external postgress external url and also add ssl=true
