### ISSUE TITLE
[Bug] medusa-cli errors when path contains a `space`

### ISSUE THREAD

**Issue by kasperkristensen** [medusajs/medusa#1284]
Appears as if `medusa-cli` does not handle spaces in paths, causing an error of `<Part of path before space> is not recognized as an internal or external command`. As evident from the picture below submitted by a user and described in #1004.

![image](https://user-images.githubusercontent.com/45367945/161003732-8f793129-c21c-41b2-8eb4-64d39b6099e2.png)

**Comment by adrien2p** [comment]
This is what I use in the medex cli

**Comment by olivermrbl** [comment]
Resolved in #1430
