### ISSUE TITLE
Support filtering price lists by customer groups

### ISSUE THREAD

**Issue by zakariaelas** [medusajs/medusa#1286]
We want to add support for filtering by customer groups. We should extend the `FitlerablePriceListProps` [here](https://github.com/medusajs/medusa/blob/fb33dbaca3f7a66f1f82481cd68f59d733a66a95/packages/medusa/src/types/price-list.ts#L25) to include a `customer_group_id?` field of type `string[]` which would include the list of customer group ids to filter by.

**Comment by ologbonowiwi** [comment]
There should be a new class extending `FitlerablePriceListProps` or `customer_group_id?` should be putted as a field of `FitlerablePriceListProps`?

**Comment by zakariaelas** [comment]
Hello @ologbonowiwi! Sorry for the delayed response. 

Adding `customer_group_id?` as a field to the `FilterablePriceListProps` should be enough ☺️

**Comment by olivermrbl** [comment]
Resolved in #1431
