### ISSUE TITLE
[Bug] free text search in price lists causes an error in core

### ISSUE THREAD

**Issue by zakariaelas** [medusajs/medusa#1289]
Passing a `q` query param to `GET /admin/price-lists/` cause the following error:

<img width="739" alt="image" src="https://user-images.githubusercontent.com/33696020/161133976-9e670791-aa9d-4d54-87bb-6231cbd920a4.png">

This is caused by how we treat the `q` param at the level of the `PriceListService.listAndCount()` method [here](https://github.com/medusajs/medusa/blob/develop/packages/medusa/src/services/price-list.ts#L257). The `q` param should be removed from the `query.where` object. In addition, the presence of the `q` param in the `selector` argument should trigger a query different from the `findAndCount` method of the `PriceListRepository`. You can get inspired from how we do it in the `ProductService` [here](https://github.com/medusajs/medusa/blob/develop/packages/medusa/src/services/product.js#L128-L136), or `DiscountService`, etc.

**Comment by olivermrbl** [comment]
Solved in #1407
