### ISSUE TITLE
Implementation of Razorpay Payment Gateway Provider

### ISSUE THREAD

**Issue by SGFGOV** [medusajs/medusa#1302]

**Comment by SGFGOV** [comment]
the fix is available here [adding razorpay to repo after rebasing](https://github.com/medusajs/medusa/pull/1476#)
#1476

**Comment by olivermrbl** [comment]
Feature requests have been moved to GitHub Discussion. Please re-submit the proposal there, if still relevant :)

**Comment by sushant049** [comment]
error:   Error starting server
Error: Unable to find the plugin "medusa-payment-razorpay".

When updating medusa to v2
