### ISSUE TITLE
set-cookie header missing when environment is set to production

### ISSUE THREAD

**Issue by nmalyschkin** [medusajs/medusa#1305]
## encountered behaviour
When `NODE_ENV=production` the set-cookie header is missing, making authentication impossible.

## steps to recreate:

```sh
medusa new auth-test
cd auth-test
medusa seed -f data/seed.json
NODE_ENV=production medusa start
# OR for reverence in development mode
medusa start
```
When trying to login, where will be no cookie or any kind of token passend with the request.
You can navigate to `localhost:9000/admin/auth` and run the following in the console
```js
fetch("http://localhost:9000/admin/auth", {
  "headers": {
    "accept": "application/json",
    "accept-language": "en-GB,en-US;q=0.9,en;q=0.8,de;q=0.7",
    "cache-control": "no-cache",
    "content-type": "application/json",
    "pragma": "no-cache",
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"99\", \"Google Chrome\";v=\"99\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"macOS\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-site"
  },
  "referrer": "http://localhost:7000/",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"email\":\"admin@medusa-test.com\",\"password\":\"supersecret\"}",
  "method": "POST",
  "mode": "cors",
  "credentials": "omit"
}).then(async res => {
    console.log("headers", [...res.headers]);
    console.log("body", await res.json());
    console.log("response", res);
})
```
While the cookie is httpOnly and will in both cases not be shown in the consoled headers, you can see (or not see it) in the network tab in the dev tools

I was looking in the source code but could not make out the error
https://github.com/medusajs/medusa/blob/master/packages/medusa/src/loaders/express.js#L13

FYI:
I've encountered this bug in production where server and frontend where running with HTTPS

**Comment by nmalyschkin** [comment]
I have set them to "include", still not working

**Comment by nmalyschkin** [comment]
It can't be a CORS problem, since I even try making the request from the same domain.
Same goes for the production system.

**Comment by andruschka** [comment]
+ 1

**Comment by srindom** [comment]
Hmm.. having issues with reproducing

![image](https://user-images.githubusercontent.com/7554214/163174744-ec85ad85-c497-4262-8298-ed22cddb7eea.png)

Wondering if it might be because you don't have Redis running?

**Comment by nmalyschkin** [comment]
If no store is set, than sessions are hold in-memory. But my redis is running this time, since my subscribers get executed properly ;)

In your posted set-cookie header, the SameSite property is missing. Is your environment set to production?

**Comment by olivermrbl** [comment]
> When `NODE_ENV=production` the set-cookie header is missing, making authentication impossible.

When you set `NODE_ENV=production`, we configure `express-session` (library that manages our cookies) with `secure: true`. This config requires you to use an HTTPS connection for `set-cookie` to be included as a header. This is why, you are experiencing it when running it locally. 

Though, it sounds strange, that you are facing the same issue in a production environment with HTTPS set up. Could I get you to provide some details around your hosting / infrastructure?

**Comment by nmalyschkin** [comment]
So I was wrongfully under the impression that the `secure` flag would only alter the cookie header, but not the fact whether the header is set by the backend or not. Turns out it does and since it is behind a proxy it relies on forwarding headers to expose the protocol type.

Currently the backend instance is running dockerized in an EC2 instance, and API Gateway as a reverse proxy.
The admin panel is hosted via CloudFront.

I started investigating the headers set by the gateway and it seems that it uses a [Forwaded](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded) Header rather than the more standard [X-Forwarded-Proto](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto) header.
**This could be my issue!**

**Comment by olivermrbl** [comment]
I believe @nielswart had a somewhat similar issue to this with infrastructure running on AWS (Cloudfront, API gateway), and he managed to solve it. Would you be able to pitch in Niel?

**Comment by nielswart** [comment]
@nmalyschkin @olivermrbl , yeah I had a similar issue, but in the end it turned out that the `NODE_ENV=production` environment variables didn't get passed through to the container running on EC2.  The best way to check is to do a request against the EC2 instance directly and see if all the headers are set correctly.

My guess is that it is probably the API Gateway reverse proxy that is the culprit and you will need to check the configuration.

I placed a Cloudfront distribution directly in front of the EC2 instance, and not an API Gateway reverse proxy, but this is not really ideal and you might not be facing the same issue as I did

**Comment by nmalyschkin** [comment]
@nielswart 
I did a request against the EC2 instance directly and did not get any set-cookie headers.
But I have no https configured directly on the instance and the cookie will not be added over HTTP.

**Comment by nmalyschkin** [comment]
So what ended up to be my problem was that express-session is not supporting the proxy headers that are used by the AWS API Gateway.
Because this is definitely not a medusa issue we can close it here.
Thanks everybody for you help with this issue!

FYI: I haven't found a solution yet. Maybe the easiest way would be to drop the API Gateway and use a ngnix inside the instance. Express-session middleware denied my request to support the new forward header.

**Comment by arjun-mavonic** [comment]
I was having same issue. One reason could be that thirdparty cookies are blocked.

I saw a warning in the network tab which says 
> this way of setting cookie using Set Cookie header is blocked by user preference.

I then unblocked third party cookies and check. Works fine. I am on two completely different domains for medusa server and the admin app. on iPhone both android and iOS blocked me.

**Comment by ZeeshanMehdiDev** [comment]
When I deployed the website on an Ubuntu dedicated server, I encountered a similar issue where the Cookie header was not present in the request headers of the 'me' request, which is causing the customers to be not prefetched. and showing 'unauthorized"

**Comment by baderrami** [comment]
Just add this:

`cookieOptions: {
          secure: false, // Set to false in development
          sameSite: "lax",
          maxAge: 24 * 60 * 60 * 1000, // 1 day
          domain: undefined, // Let it be automatically determined
      },`
   

to your medusa-config.ts. Example:

`import { loadEnv, defineConfig } from '@medusajs/framework/utils'

loadEnv(process.env.NODE_ENV || 'development', process.cwd())

module.exports = defineConfig({
  projectConfig: {
    databaseUrl: process.env.DATABASE_URL,
    redisUrl: process.env.REDIS_URL,
    http: {
      storeCors: process.env.STORE_CORS!,
      adminCors: process.env.ADMIN_CORS!,
      authCors: process.env.AUTH_CORS!,
      jwtSecret: process.env.JWT_SECRET || "supersecret",
      cookieSecret: process.env.COOKIE_SECRET || "supersecret",
    },
      cookieOptions: {
          secure: false, // Set to false in development
          sameSite: "lax",
          maxAge: 24 * 60 * 60 * 1000, // 1 day
          domain: undefined, // Let it be automatically determined
      },
  }
})
`
