### ISSUE TITLE
[Docs] Improvements - Add api end point 

### ISSUE THREAD

**Issue by adrien2p** [medusajs/medusa#1317]
The documentation is lacking the argument that the function router is taking (such as the rootDirectory)

https://docs.medusajs.com/advanced/backend/endpoints/add-storefront/

Also, With the PR I have done about the config #1290, I think the function router should take the configModule instead of the rootDirectory in order to facilitate the usage of the API

**Comment by shahednasser** [comment]
Hi @adrien2p I'll make changes for the rootDirectory argument for now and once your PR gets merged please open a new issue and tag me in it to update the docs 🙂
