### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by swarmlab-hybrid** [medusajs/medusa#1325]
how can I create the following:
`curl -G --data-urlencode "description=search substrring" http://medusa-server:9000/store/products`
what I want is to look at the part of the description   (equivalent to this 'a nice description' .includes ('this') )
I try also with _tags_ array, as well as with the _type_ field
e.g. this 
`curl -G --get --data-urlencode "title=Medusa Sweatshirt"  http://medusa-server:9000/store/products`
work as expected,  but this
`curl -G --get --data-urlencode "title=%Sweatshirt%"  http://medusa-server:9000/store/products`
does not.

**Comment by srindom** [comment]
The default API supports simple text-based search through the `q` param. This will try to match text on the product's title, description, variant titles, variant SKUs and collection title. 

If you want more advanced search capabilities you may install a search plugin like medusa-search-meilisearch or medusa-search-algolia :)

**Comment by swarmlab-hybrid** [comment]
Thank you for your response
Algolia is a great option, but cost is a real consideration.  I chose MeiliSearch and installed from here ` https://github.com/medusajs/medusa/tree/master/packages/medusa-plugin-meilisearch ` with this in medusa-config.js file
 ```
{
    resolve: `medusa-plugin-meilisearch`,
    options: {
      config: {
        host: "http://medusa-search:7700",
        apiKey: "your_master_key"
      },
      settings: {
        products: {
          searchableAttributes: ["title", "description", "variant_sku"],
          displayedAttributes: ["title", "description", "variant_sku"],
        },
      },
    },
  }

```
perfect 
`curl  -X POST  http://medusa-server:9000/store/products/search   -H 'Content-Type: application/json'   --data-binary '{ "q": "Sweat" }' | jq .`  work as expected

I can now continue my Vue Storefront-ui integration  for Medusa.js

Great work!

**Comment by srindom** [comment]
Great to hear! 🎉
