### ISSUE TITLE
Docs: Add Node version requirement to documentation

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#1328]
Add the minimum and maximum node version required to run Medusa.

**Comment by adrien2p** [comment]
as well as maybe update the package.json of each packages accordingly (in the engines options)

**Comment by shahednasser** [comment]
@adrien2p good idea but I think this should be in a different issue since it's not related to the documentation

**Comment by adrien2p** [comment]
Yes I am agree it is just a reminder to avoid getting a diff between the doc and the packages 😅
