### ISSUE TITLE
[Tests] Transaction management missing

### ISSUE THREAD

**Issue by adrien2p** [medusajs/medusa#1333]
At the moment that poses a problem since while I am looking around I often encounter areas where the transactions are missing.

The thing at the moment is that the tests does not reflect that problem since everything is running out of a transaction context and means that we cannot be alerted for missing transaction.

We should probably find a solution to be able to detect places that does not run in the transaction and therefore will lead to concurrent access

**Comment by adrien2p** [comment]
I think of that but maybe it is coming from elsewhere, but the think it that when something is running in an atomicPhase and that the transaction is not pass to another service that could access the data that just have been updated we should get an error but it is not the case

**Comment by srindom** [comment]
Do you have a way that we can reproduce the "unwanted outcome" - I think that I understand the broad strokes of what you are highlighting, but would be very helpful to get clearer steps for exactly where the issue you are describing arises.

**Comment by adrien2p** [comment]
It is more of a global thing. When an atomicPhase is launch a transaction is created, as we have seen lately I have been adding transactions where they was missing. 

When another service is called from a transaction context, the data from the transaction should not be accessible outside of the transaction, which is the classical flow, but at the moment, when a tests is created to tests the behaviour of a method, if there is any missing transaction, there is no error that shows up.

This unexpected behaviour is probably created by [that](https://github.com/medusajs/medusa/blob/master/packages/medusa-test-utils/src/mock-manager.js) which is widely used and does not wrap the logic into a transaction context.

With that in mind, we could suppose that if we were running the tests using real transaction, we could really tests if a method works or not since when the transaction are missing you would either get a concurrent access when trying to access a data that is locked by the transaction, or you would get an error since the computation would be made on non fresh data.

At the moment, without a real transaction context any tests can pass with or without transaction and even with half of the transactions.

I think that the managerMock should not override the transaction method in order to have proper tests.

Don't know if I am clear 😅 let me know

**Comment by adrien2p** [comment]
But the thing is that the integration tests should show up those places with the missing transactions, because there the connection and manager is not mocked am I right ?

**Comment by adrien2p** [comment]
@srindom lets close the issue until I figure out a better explanation and reproduction
