### ISSUE TITLE
[Bug]: Missing required methods from BasePaymentService

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#1362]
`BasePaymentService` has the following methods missing even though they're used in `PaymentProviderService`. This should make them required as not implementing them will cause an error. These methods are:

- `getPaymentData`
- `updatePaymentData`
- `cancelPayment`

**Comment by adrien2p** [comment]
Should it be included in that pr https://github.com/medusajs/medusa/pull/1052 ?

**Comment by srindom** [comment]
@adrien2p I think that would be nice

**Comment by shahednasser** [comment]
An additional detail to add to this: The `retrievePayment` method accepts the `cart` as a parameter:

https://github.com/medusajs/medusa/blob/2e6622ec5d0ae19d1782e583e099000f0a93b051/packages/medusa-interfaces/src/payment-service.js#L29-L37 

However, when this method is used in plugins like PayPal and Stripe it actually accepts the `data` field of the payment:

https://github.com/medusajs/medusa/blob/2e6622ec5d0ae19d1782e583e099000f0a93b051/packages/medusa-payment-stripe/src/services/stripe-provider.js#L179-L190

I think it should be changed accordingly.

**Comment by adrien2p** [comment]
@shahednasser as part of the PR I mentioned above, there is a comment I wrote that expose the fact that this method is not called anywhere. Therefore, depending on @srindom feedback it will be removed from the base payment service.

**Comment by shahednasser** [comment]
I actually had a discussion with @olivermrbl when working on the documentation of payment providers and he mentioned that this will be potentially used in the future to provide a more uniform way of getting the payment data from the third-party provider

**Comment by olivermrbl** [comment]
> this method is not used anywhere

In cases where we have to retrieve the payment object from a third-party payment service in multiple steps and with potential error handling, I think it makes sense to use this method, so we don't have to repeat that logic in multiple method. See the [PayPal provider](https://github.com/medusajs/medusa/blob/master/packages/medusa-payment-paypal/src/services/paypal-provider.js) for reference. Wdyt?

**Comment by adrien2p** [comment]
I will update the method signature then

**Comment by adrien2p** [comment]
@shahednasser @olivermrbl signature updated [here](https://github.com/medusajs/medusa/pull/1052/commits/fae724e412fad80112dd7706c3284950b34e98df). Once that PR will be merged, we will be able to move the migration forward
