### ISSUE TITLE
Add support for deleting prices from a price list by product id or variant id

### ISSUE THREAD

**Issue by zakariaelas** [medusajs/medusa#1375]
We'd like to delete prices of a price list based on the product id or variant id.

One way to do this would be to add a route for each operation:
- `DELETE /admin/price-lists/:id/products/:id`
- `DELETE /admin/price-lists/:id/variants/:id`

Another way could be to extend the existing delete price list route by supporting query params:
- `DELETE /admin/price-lists/:id?variant_id=&product_id=`

Feel free to suggest any alternative approach in the comments!

**Comment by olivermrbl** [comment]
Solved in #1555
