### ISSUE TITLE
[Bug] Listing products in a price list does not return correct prices in variants

### ISSUE THREAD

**Issue by zakariaelas** [medusajs/medusa#1376]
When fetching products in a price list through the `GET /admin/price-lists/:id/products` route, the returned product variants do not contain the correct prices for said price list.

For example, when sending a request to `GET /admin/price-lists/1/products/`, `products.$.variants.$.prices` will not refer to the prices set for said variant in price list 1, instead, it will refer to the default prices set for the variant.

_[Note]: In above snippet, $ refers to some index_

**Comment by olivermrbl** [comment]
Solved in #1416
