### ISSUE TITLE
Docs: Add link to Shipping Architecture overview.

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#1384]
In ["How to Add a Fulfillment Provider"](https://docs.medusajs.com/advanced/backend/shipping/add-fulfillment-provider) guide, in the beginning where it says "check out the overview first." add a link to the [Architecture Overview](https://docs.medusajs.com/advanced/backend/shipping/overview) documentation.

**Comment by shreedharhegde99** [comment]
Hi @shahednasser , I think ["How to add a Fulfillment Provider" ](https://github.com/medusajs/medusa/blob/master/docs/content/advanced/backend/shipping/add-fulfillment-provider.md)
 is not available in `develop` branch. How can I contribute to this..?

**Comment by shreedharhegde99** [comment]
Hi @olivermrbl , will you please help me regarding this..? Thank you.
