### ISSUE TITLE
Can't see customer log out method in `medusa-js` package

### ISSUE THREAD

**Issue by gregorymark** [medusajs/medusa#1391]
I'm on `medusa-js 1.0.7`

I created a new app using `create-medusa-app` using the `gatsby-medusa-starter`, which gives me a storefront and the ability to sign in. So far so good. But I'd like to allow the user to log out. The `clearCustomer` method in `customer-context.js` doesn't delete the session, so as soon as the site fetches the current user again I can access the account details.

As far as I can see in the `medusa-js` package, there's no way to log out or delete a session that corresponds to the store logout method [in the api](https://docs.medusajs.com/api/store/auth/log-out).

Am I missing something or is this planned for a future release?

**Comment by ahmed1107** [comment]
i'm also looking to do the same thing. will be good to see how its done

**Comment by olivermrbl** [comment]
Currently have an open PR for it #1234. We are planning to include it in next release.

**Comment by gregorymark** [comment]
@olivermrbl ah thanks. I’ll check the PRs more carefully next time.
