### ISSUE TITLE
Feature: Allow S3 Uploads to any s3 compatible service

### ISSUE THREAD

**Issue by ShivamJoker** [medusajs/medusa#1399]
Right now when I try to use another s3 provider it gives me error saying
error:   The AWS Access Key Id you provided does not exist in our records.

If you guys could just make it compatible with s3 protocol instead of using amazon only s3

**Comment by ashutoshpw** [comment]
@olivermrbl Should I take this up?

**Comment by ashutoshpw** [comment]
Hey, I like to work on this issue.

**Comment by ashutoshpw** [comment]
PR for this issue [2078](https://github.com/medusajs/medusa/pull/2078)

**Comment by MyWay** [comment]
Same problem here.

**Comment by Coachonko** [comment]
This. There are several services using the S3 API, there is no point in keeping the plugin Amazon S3-specific.
