### ISSUE TITLE
Feature: Allow description & other params to be passed on stripe plugin

### ISSUE THREAD

**Issue by ShivamJoker** [medusajs/medusa#1401]
We can't use stripe in India without providing description, so wherever we are creating intents we need to pass a description via config file.

![image](https://user-images.githubusercontent.com/23727670/164453220-7001a835-b161-444f-bd46-58c8dc24ec72.png)

```js
const paymentIntent = await stripe.paymentIntents.create({
  amount: 1099,
  currency: 'usd',
  description: 'Software development services',
});
```

**Comment by olivermrbl** [comment]
Resolved in #1403
