### ISSUE TITLE
[Enhancement] QueryBuilderService

### ISSUE THREAD

**Issue by adrien2p** [medusajs/medusa#1412]
It seams that the `QueryBuilderService` is actually a set of utilities and the service extends the `BaseService` but does not relied on it, should we move them into the utils directory?

**Goal**

Move the methods into separate utility files under the utils directory and then export them as part of the @medusajs/medusa package API

**Comment by Raaghav4243** [comment]
Hey
Raaghav here, I wish to contribute to this feature. Could you please assign it to me.
Reference: Aviyel
Thanx @renatobenks
