### ISSUE TITLE
Unable to create a customer signup using postman

### ISSUE THREAD

**Issue by tarifrudrapur** [medusajs/medusa#1433]
I have setup a dev server on aws and its running fine. 
But while creating a customer through `http://api.mydomain.com/store/customers`

I am getting `Unauthorized`

I don't think we required any token to use this api, I want to integrate this api in my custom made front end.

**Comment by kasperkristensen** [comment]
Hi @tarifrudrapur, the storefront API does not require a token, the admin however does. So make sure that you are using the correct endpoint. To create a customer account using the storefront API you should use the endpoint `POST /store/customers` and the payload should have the following structure:

```ts
{
  first_name: string
  last_name: string
  email: string
  password: string
  phone?: string // optional
}
```

**Comment by kasperkristensen** [comment]
Hi @tarifrudrapur, the `POST store/customers` endpoints does not require any token to use, so if you are receiving a 401 response it's most likely due to some configuration of your AWS instance. Are you able to POST to any of the other storefront endpoints? 😄

**Comment by tarifrudrapur** [comment]
I have setup this project on ubuntu server, same as we do in local machine, Do i need any additional configuration ?
All the get endpoint is working

**Comment by kasperkristensen** [comment]
@tarifrudrapur have you updated the STORE_CORS in your servers environment variables? It needs to be set to where ever your storefront is hosted. If you are running you storefront locally you could use something like ngrok to expose your local port, as it won't work if you are making requests directly from localhost 😄

**Comment by tarifrudrapur** [comment]
I just configured a subdomain with nginx server blocks and it is working absolutely fine. 

Thanks for the quick response. @kasperkristensen
