### ISSUE TITLE
Typos in `medusa-plugin-sendgrid` documentation causing emails not to send when implemented.

### ISSUE THREAD

**Issue by gregorymark** [medusajs/medusa#1437]
`packages/medusa-plugin-sendgrid/README.md` contains the spelling `cancelled` when it should be `canceled`. Implementing the plugin with the spelling suggested in the docs causes emails to not be sent.

The typo's also in `packages/medusa-plugin-sendgrid/src/services/sendgrid.js`.

Opened a PR to fix - medusajs/medusa#1438

Also, I'm British so I appreciate that it's not exactly wrong ;)

**Comment by olivermrbl** [comment]
Fixed #1438
