### ISSUE TITLE
Draft Order API: Creating shipping_address using string id from admin causes address to come back empty.

### ISSUE THREAD

**Issue by dwene** [medusajs/medusa#1443]
Looks like an issue with the Medusa Draft Orders API, when adding a shipping_address using a string id, the address is lost in the cart creation process.

https://www.loom.com/share/867d576b78c34e35b7deaaba325996f5

**Comment by dwene** [comment]
I think the issue is something to do here: 

https://github.com/medusajs/medusa/blob/master/packages/medusa/src/services/cart.ts#L363

I don't really know what all that code is trying to do, but seems like it might be messing it up, since the billing_address works just fine :)

**Comment by adrien2p** [comment]
@dwene I sent you a DM with a thing to try on your project. I created the [PR](https://github.com/medusajs/medusa/pull/1475) here
