### ISSUE TITLE
Error in `gatsby-source-medusa` concerning export of `sourceUpdatedNodes`

### ISSUE THREAD

**Issue by gregorymark** [medusajs/medusa#1455]
I'm getting an error when using `gatsby-source-medusa@0.0.49` when running `gatsby develop`.

```
ERROR #11329

Your plugins must export known APIs from their gatsby-node.js.

See https://www.gatsbyjs.com/docs/reference/config-files/gatsby-node/ for the list of Gatsby node
APIs.

- The plugin gatsby-source-medusa@0.0.49 is using the API "sourceUpdatedNodes" which is not a known
 API.

Some of the following may help fix the error(s):

- Rename "sourceUpdatedNodes" -> "sourceNodes"
```

It seems to be coming from the `export` in [packages/gatsby-source-medusa/src/gatsby-node.ts](https://github.com/medusajs/medusa/blob/38762961e6d23955c297986edb01a9c5dbe21373/packages/gatsby-source-medusa/src/gatsby-node.ts) when the function `sourceUpdatedNodes` is defined (line 56).

It's not stopping the build so it's not a huge issue. I don't know if it was added because the Gatsby Node APIs are being expanded or something? Just wanted to flag it. I won't open a PR because I'm not confident enough to just delete the export statement.

**Comment by olivermrbl** [comment]
@kasperkristensen Do you know, if this is urgent i.e. in need of a quick fix?

**Comment by kasperkristensen** [comment]
@olivermrbl Will look into it, doubt that it is urgent as think it's just a matter of moving some function definitions out of the node.js file, but will open a PR to resolve it later today 😄
