### ISSUE TITLE
[bug]: Product options are not deleted when associated variant is deleted

### ISSUE THREAD

**Issue by kasperkristensen** [medusajs/medusa#1464]
**How to reproduce**

Create a new variant, with some options, such as `Color: Blue`. Delete the variant, and notice that the opt_val that was generated for the variant is still present in the values of the `Color` product option.

**Expected behaviour** 

When we delete a variant, it's expected that the delete is cascaded such that all `opt_val` with `variant_id: <deleted variant id>` are also removed.

**Comment by olivermrbl** [comment]
Closed #1465
