### ISSUE TITLE
medusa-file-spaces overwites files with the same name

### ISSUE THREAD

**Issue by chemicalkosek** [medusajs/medusa#1467]
When a file is uploaded to a space where a file with the same filename exists, it will be overwritten.
This should not happen as content/shop maintainer might upload files with the same name. This is very common.

There should be appended some unique hash, short-uuid or maybe current timestamp to a filename in such cases (or all cases).

**Comment by adrien2p** [comment]
Should be resolve by [this PR](https://github.com/medusajs/medusa/pull/1474)

**Comment by olivermrbl** [comment]
Resolved in #1474
