### ISSUE TITLE
List-products endpoint does not return prices when queried with search filter

### ISSUE THREAD

**Issue by anup-a** [medusajs/medusa#1484]
After updating from v1.2.1 to v1.3

I'm no longer getting prices in the response of the list-products endpoint when I'm querying with a search filter.

This correctly returns prices -> `GET /products` 
While this does not -> `GET /products?q=text`

Is this expected behavior (given there have been some price selection strategy changes in recent version) ?
If yes, how to eager fetch the prices along with list of products.

**Comment by olivermrbl** [comment]
Solved in #1607
