### ISSUE TITLE
Performance issue loading orders

### ISSUE THREAD

**Issue by dwene** [medusajs/medusa#1497]
Hey medusa team,

I'm noticing that after upgrading to 1.3.0, I'm having some really poor performance with listing orders. I think it might have to do with a new way of calculating totals, but it's taking 10+ seconds on my very beefy laptop to fetch even 15 orders. Maybe I missed a migration script or something?
```
 const orders = await orderService.list(
      { customer_id: id },
      {
        skip,
        take,
        order: { created_at: sortOrder },
        relations: [
          'cart',
          'cart.items',
          'customer',
          'billing_address',
          'shipping_address',
          'discounts',
          'discounts.rule',
          'shipping_methods',
          'payments'
        ],
        select: defaultAdminOrdersFields
      }
    );
```

**Comment by srindom** [comment]
Hi @dwene - sounds annoying; could you give a bit more context about the volume of the data being fetched here? Esp. `cart, cart.items` would be nice to hear about? I just tried doing the same query on 250 orders with no issues. 

Also, is there any particular reason why you do `cart, cart.items` and not just `items`?

**Comment by dwene** [comment]
Hey @srindom ,

I'm only fetching about 10 orders, and each order has about 6-11 items.

What's strange is that the difference between `take: 1` and `take: 2` is massive. take:1 is basically instant, where take:2 takes over 5 seconds.

**Comment by dwene** [comment]
Update: using `listAndCount` is `SIGNIFICANTLY` more performant

**Comment by olivermrbl** [comment]
Hi there. We highly appreciate you filing an issue and showing an interest in improving Medusa.

I apologize for the delayed response.

Moving forward, we aim to do better. But we would like to start fresh. Therefore, we are considering all older issues as stale and closing them, even though they might still be relevant.

Please don’t hesitate to re-open the issue (or create a new one) if you still need a resolution or an answer.

Thanks ❤️
