### ISSUE TITLE
Unable to login using safari - set-cookie error (?)

### ISSUE THREAD

**Issue by peastuti** [medusajs/medusa#1498]
Hi, as discussed before on discord, a strange thing happens in my instances of medusa. 
I'm unable to login into the Admin portal (`GET /admin/auth`) using Safari, instead on Chrome everything goes smoothly.

Here some screenshots of the error on Safari:
![safari-error-1](https://user-images.githubusercontent.com/18187660/167899265-af26c4c3-09b7-44cb-b24d-4c6d5874b14a.png)
![safari-error-2](https://user-images.githubusercontent.com/18187660/167899273-7b80f33c-a9e0-4034-bf85-0883909de9bc.png)

and here are the server logs:
![safari-error-3](https://user-images.githubusercontent.com/18187660/167899284-0f507573-eb9b-456d-9c93-c90ef0668631.png)

no cookies in safari, even though `POST /admin/auth` returns the cookie correctly:

![cookie-safari](https://user-images.githubusercontent.com/18187660/167899577-98be01fc-3174-4746-a75d-50cc3a5b075a.png)

As said before, in Chrome, everything ok:

![chrome-ok-1](https://user-images.githubusercontent.com/18187660/167899638-2a5e3f04-756b-48d4-9c52-d2fa30ed0eed.png)

and here's the server log:

![chrome-ok-2](https://user-images.githubusercontent.com/18187660/167899694-60b48b0f-5f01-4300-9e7f-a2663ce09317.png)

**Comment by peastuti** [comment]
Does anybody have an idea of what's happening?

**Comment by benjaminpreiss** [comment]
I am experiencing the same issue, although I have no working browser (tested Safari, Chrome and Firefox). In my case, no cookies are set. I am selfhosting on https with a lets encrypt cert.

Here is a screenshot of the XHR/fetch requests. Preflight passes successfully.
![image](https://user-images.githubusercontent.com/28349122/177054859-78e9d038-dd41-4dcb-b877-e2d1ba688512.png)
![image](https://user-images.githubusercontent.com/28349122/177055048-9321e223-2d0c-43ed-bb1d-67e69e414ed0.png)

**Comment by AlexDigital974** [comment]
Hi ,

I had the same issue and for now the only way i resolver is to put the api-frontend-admin on the same domains .

Else the cookies is not set i try multiple scneario but safari refuse everything.

Funny thing if you go to Safary -> Privacy setting and you uncheck  "Prevent Cross Site Tracking" it will work......

So for now the simplest way i have 3 different service so to make it work o safari i make it like than
front.domain1.com
admin.domain1.com
api.domain1.com

So they are all on domain1 so IOS/ipad everything work, if you do not that welli dont have an 'easy' solution

**Comment by judocode** [comment]
I don't know if this will help anyone, but my medusa express server is behind an apache2 reverse proxy and what fixed it for me was editing my sites-available conf file to include `RequestHeader set X-Forwarded-Proto "https"` as suggested here: https://github.com/expressjs/session/issues/251#issuecomment-188617002

For me this also required me to run `sudo a2enmod headers` and restarted apache2 with `sudo systemctl restart apache2`

**Comment by AlexDigital974** [comment]
@judocode  you are right , for the first issue i had ,to even make the proxy work  i added  below  my configuration  for the proxy for medusa. This was my first issue.

But `**this does not fix the cookies in Safari/ios.**.`..IF you domain is different .its just make the proxy work overalll.

if you have 
api.mydomainA.com
frontend.DomainB.com

you website will work everywhere except **Ipad/iphone/Desktop Safari.** . and this issue  is NOT LINK to the proxy


```
res.cookie('id',data, { maxAge: 2592000, httpOnly: true, secure: true, sameSite: 'None' });
```

### Nginx config

```
         proxy_set_header Host $host;

        proxy_set_header X-Real-IP $remote_addr;

         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

         proxy_set_header X-Forwarded-Proto $scheme;
```

**Comment by cryptocommerceshop** [comment]
I have the same issue (on all browsers) and I'm not even trying to use different top-level domains. I'm trying to setup Medusa + Admin via nginx reverse proxy as follows:

Admin Frontend: **admin.mysite.com**
Medusa Backend: **backend.mysite.com** 

With nginx config:

```
server {
      listen 443 ssl;
      server_name backend.mysite.com;
      ssl_certificate /etc/letsencrypt/live/mysite.com/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/mysite.com/privkey.pem;
      ssl on;
      location / {
         proxy_pass http://127.0.0.1:9000;   # medusa is running on port 9000
         proxy_set_header        Host $host;
         proxy_set_header        X-Real-IP $remote_addr;
         proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header        X-Forwarded-Proto $scheme;
         proxy_redirect              http://localhost:9000 https://backend.mysite.com;
      }
   }
```

I can confirm I get the Set-Cookie header back after adding all the proxy_set_header entries, but I'm still unable to login on any browser.

Does anybody have a solution?

**Comment by AlexDigital974** [comment]
@cryptocommerceshop 
could you try without the prox_redirect , i don't think you need it , just proxy_pass is enough. im not sure you should be using both at the same time .

below is my full working api nxing conf that work across many version , as long as your domain is the same.

`    location / {
        proxy_set_header Host $host;
        proxy_pass http://127.0.0.1:9000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

         proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x
`

**Comment by gitE0Z9** [comment]
same problem, medusa admin will fail to set cookie for same-site policy and redirect back to login page 

found solution [here](https://github.com/medusajs/admin/issues/596) for cookie problem

**Comment by hukhho** [comment]
how fix?

**Comment by adrien2p** [comment]
If you follow the link above you should be able to find the element of answer. I ll close for now and feel free to reopen
