### ISSUE TITLE
Error while running "medusa develop" - Cannot read properties of undefined

### ISSUE THREAD

**Issue by edgycorner** [medusajs/medusa#1512]
Facing a minor issue when I try to run "medusa develop" after switching to psql(by editing my medusa-config.js):

`Successfully compiled 0 files with Babel (5ms).
TypeError: Cannot read properties of undefined (reading 'projectConfig')
    at /root/medusa/medusa-store/node_modules/@medusajs/medusa/dist/loaders/redis.js:50:30
    at step (/root/medusa/medusa-store/node_modules/@medusajs/medusa/dist/loaders/redis.js:33:23)
    at Object.next (/root/medusa/medusa-store/node_modules/@medusajs/medusa/dist/loaders/redis.js:14:53)
    at /root/medusa/medusa-store/node_modules/@medusajs/medusa/dist/loaders/redis.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/root/medusa/medusa-store/node_modules/@medusajs/medusa/dist/loaders/redis.js:4:12)
    at redisLoader (/root/medusa/medusa-store/node_modules/@medusajs/medusa/dist/loaders/redis.js:47:12)
    at /root/medusa/medusa-store/node_modules/@medusajs/medusa/dist/loaders/index.js:114:62
    at step (/root/medusa/medusa-store/node_modules/@medusajs/medusa/dist/loaders/index.js:52:23)
    at Object.next (/root/medusa/medusa-store/node_modules/@medusajs/medusa/dist/loaders/index.js:33:53)
    at /root/medusa/medusa-store/node_modules/@medusajs/medusa/dist/loaders/index.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/root/medusa/medusa-store/node_modules/@medusajs/medusa/dist/loaders/index.js:23:12)
    at /root/medusa/medusa-store/node_modules/@medusajs/medusa/dist/loaders/index.js:83:12
    at /root/medusa/medusa-store/node_modules/@medusajs/medusa/dist/commands/start.js:59:72
    at step (/root/medusa/medusa-store/node_modules/@medusajs/medusa/dist/commands/start.js:33:23)`

My medusa-config.js:

`const ADMIN_CORS = process.env.ADMIN_CORS || "http://localhost:7000,http://localhost:7001";

// CORS to avoid issues when consuming Medusa from a client
const STORE_CORS = process.env.STORE_CORS || "http://localhost:8000";

// Database URL (here we use a local database called medusa-development)

const DB_USERNAME = medusa;
const DB_PASSWORD = password;
const DB_HOST = localhost;
const DB_PORT = 5432;
const DB_DATABASE = db;

const DATABASE_URL = "postgres://medusa:password@localhost:5432/db";

// Medusa uses Redis, so this needs configuration as well
const REDIS_URL = process.env.REDIS_URL || "redis://localhost:6379";

// Stripe keys
const STRIPE_API_KEY = process.env.STRIPE_API_KEY || "";
const STRIPE_WEBHOOK_SECRET = process.env.STRIPE_WEBHOOK_SECRET || "";

// This is the place to include plugins. See API documentation for a thorough guide on plugins.
const plugins = [
  `medusa-fulfillment-manual`,
  `medusa-payment-manual`,
  // Uncomment to add Stripe support.
  // You can create a Stripe account via: https://stripe.com
  // {
  //   resolve: `medusa-payment-stripe`,
  //   options: {
  //     api_key: STRIPE_API_KEY,
  //     webhook_secret: STRIPE_WEBHOOK_SECRET,
  //   },
  // },
];

module.exports = {
  projectConfig: {
    // redis_url: REDIS_URL,
    database_url: DATABASE_URL,
    database_type: "postgres",
    store_cors: STORE_CORS,
    admin_cors: ADMIN_CORS,
  },
  plugins,
};
`

I have checked both services(psql and redis), they seem to be running fine on their destined ports.

For some reason, it develops without any problem when I am using sqlite.

When I traced back the undefined variable, it was "databasetype". But it seems to be configured under projectConfig in medusa-config.js.

**Comment by adrien2p** [comment]
From the error, it is the projectConfig that is not find. From which directory are you executing the command?

**Comment by edgycorner** [comment]
> From the error, it is the projectConfig that is not find. From which directory are you executing the command? And it seams that it is the redis url that we are trying to pull from the config

I have uncommented redis_url under projectConfig in medusa-config.js.
I am running `medusa develop` after cd into `/root/medusa/medusa-store`

**Comment by adrien2p** [comment]
Yeah uncommenting it will not fix the error since it is projectConfig that can't be pulled ^^ it was just informative to the fact that it was not database type.
Is medusa-store your backend? Can you send a video or a reproduction repository please?

**Comment by edgycorner** [comment]
> Yeah uncommenting it will not fix the error since it is projectConfig that can't be pulled ^^ it was just informative to the fact that it was not database type. Is medusa-store your backend? Can you send a video or a reproduction repository please?


I pushed my local rep here 
https://github.com/edgycorner/medusa-local

Here's a video
https://youtu.be/F5v7JwZsLfM

**Comment by edgycorner** [comment]
This is how I am able to reproduce this bug again:
`medusa new my-medusa-store`
Editing medusa-config.js to:
https://github.com/edgycorner/medusa-local/blob/main/medusa-config.js
`medusa develop`

It always leads to "Cannot read properties of undefined" error.
I am using ubuntu 22.04 droplet with node v16.15.0

**Comment by adrien2p** [comment]
Could you put some quote around the strings in the config.

**Comment by edgycorner** [comment]
> Could you put some quote around the strings in the config.

Yes! 
So foolish of me. It was my own error. Nothing wrong with medusa hehe

I was able to run it perfectly after putting variable strings in quote.
medusa seed -f ./data/seed.json
medusa develop
and now it's running! 

Just got a few warnings. Can I ignore these? :>>
![warn](https://user-images.githubusercontent.com/39706421/168437707-64f72291-de08-486a-880f-9f3f12e57876.JPG)

**Comment by adrien2p** [comment]
Ahah no worries, yes you can ignore them. It is that you did not install the file plugin

**Comment by edgycorner** [comment]
> Ahah no worries, yes you can ignore them. It is that you did not install the file plugin

Thanks for the help!

**Comment by ashish-khoiwal** [comment]
> 

Hi,
I have been facing this same issue for a while now but am not able to get it resolved.
Can you tell me how you resolved this by **putting variable strings in quote** as what I can see, they are already in quotes, no?
eg. `const REDIS_URL = 'redis://localhost:6379';`
