### ISSUE TITLE
Resolution path: db_entities

### ISSUE THREAD

**Issue by Savvy** [medusajs/medusa#1514]
After a fresh install, and following the directions to setup development environment. Upon running the command "medusa develop" I get the error. I also have attempted running "npm run seed" and I get the issue as well however the database connection seems to work fine. 

`Resolution path: db_entities
    at Object.resolve (G:\JavaScriptProjects\my-medusa-server\node_modules\awilix\lib\container.js:240:23)
    at G:\JavaScriptProjects\my-medusa-server\node_modules\@medusajs\medusa\dist\loaders\database.js:48:42
    at step (G:\JavaScriptProjects\my-medusa-server\node_modules\@medusajs\medusa\dist\loaders\database.js:33:23)
    at Object.next (G:\JavaScriptProjects\my-medusa-server\node_modules\@medusajs\medusa\dist\loaders\database.js:14:53)
    at G:\JavaScriptProjects\my-medusa-server\node_modules\@medusajs\medusa\dist\loaders\database.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (G:\JavaScriptProjects\my-medusa-server\node_modules\@medusajs\medusa\dist\loaders\database.js:4:12)
    at G:\JavaScriptProjects\my-medusa-server\node_modules\@medusajs\medusa\dist\loaders\database.js:43:12
    at G:\JavaScriptProjects\my-medusa-server\node_modules\@medusajs\medusa\dist\loaders\index.js:140:65
    at step (G:\JavaScriptProjects\my-medusa-server\node_modules\@medusajs\medusa\dist\loaders\index.js:52:23)
    at Object.next (G:\JavaScriptProjects\my-medusa-server\node_modules\@medusajs\medusa\dist\loaders\index.js:33:53)
    at fulfilled (G:\JavaScriptProjects\my-medusa-server\node_modules\@medusajs\medusa\dist\loaders\index.js:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Comment by adrien2p** [comment]
Could you tell me how you configured you medusa, did you setup the env? Ultimately, could you share a reproducible repo so that it will be easier to find out the etror

**Comment by adrien2p** [comment]
After a long digging we ended up finding that the trouble was caused by windows file system using backslash whereas the glob package interpreted as escape characters. The solution was to move to wsl which stand for Windows Subsystem Linux. @olivermrbl @srindom I think it is worth mentioning that caveat into the documentation as well as the troubleshooting doc and channel for other windows users. Wdyt?

**Comment by accpliuchen** [comment]
Sorry @adrien2p what your mean ? looks like same error with me

**Comment by adrien2p** [comment]
@accpliuchen I supposed your on windows? The windows os file system use \ for the path whereas the glob lib use that character to escape which leads to that issue.
Using wsl on windows enable working on the subsystem linux and therefore use / for the path.

**Comment by accpliuchen** [comment]
@adrien2p  wsl is powershell?

**Comment by accpliuchen** [comment]
I would like to use it by Windows, how to do it ? please let me know, thank you.

**Comment by Savvy** [comment]
> I would like to use it by Windows, how to do it ? please let me know, thank you.

https://docs.microsoft.com/en-us/windows/wsl/install
ttps://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl

**Comment by accpliuchen** [comment]
before I installed it that was working, but it is not working right now, I have to do it by Windows, Could you help me fix it?

**Comment by accpliuchen** [comment]
> > I would like to use it by Windows, how to do it ? please let me know, thank you.
> 
> https://docs.microsoft.com/en-us/windows/wsl/install https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl

I don't want to use wsl, just Windows, do you have any solution for it ?

**Comment by Savvy** [comment]
> > > I would like to use it by Windows, how to do it ? please let me know, thank you.
> > 
> > 
> > https://docs.microsoft.com/en-us/windows/wsl/install https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl
> 
> I don't want to use wsl, just Windows, do you have any solution for it ?

Not as of now. WSL is your best bet as far as I know.

**Comment by adrien2p** [comment]
Hey guys, is that alright with you? Should we close both the issue?s
