### ISSUE TITLE
Payment session does not consider discount while calculating total amount

### ISSUE THREAD

**Issue by anup-a** [medusajs/medusa#1517]
After updating to v1.3, it looks like the payment session does not reduce the total amount by the discount, while it is being correctly calculated in cart.

Note - I'm using the stripe provider plugin.

<img width="451" alt="Screenshot 2022-05-15 at 11 44 35 AM" src="https://user-images.githubusercontent.com/29516633/168459832-d6225dbb-cf53-448c-af96-e8d8a9430efa.png">

**Comment by adrien2p** [comment]
is the stripe-connect a custom provider of yours?

**Comment by anup-a** [comment]
Yes, though it is the exact same code as stripe except for a few stripe specific details. 

I've gone through the code and looks like `discountTotal` is being fetched from line adjustments but for some reason my line item is not getting added in line adjustments table.

I believe this was working before updating to V1.3.

If you guys cannot reproduce it, then maybe issue happened while updating versions.

**Comment by adrien2p** [comment]
did you run the migration script when you've upgraded to 1.3?

**Comment by anup-a** [comment]
Yes I've. Also I think line adjustments table has been added only because of the migrations

**Comment by adrien2p** [comment]
I mean there is the migrations and the script to run. Did you run both?

**Comment by anup-a** [comment]
I just ran `npx medusa migrations run`. Not sure which is the other one.

**Comment by adrien2p** [comment]
You should look at this 😊 https://github.com/medusajs/medusa/blob/977e6086f40c5d5f2adf03155e2ec62c14f35f4d/docs/content/advanced/backend/upgrade-guides/1-3-1.md

**Comment by anup-a** [comment]
Hey, I believe I'm still missing something. Those migrations ran successfully but even then the same issue.

Can you tell me, when does a line-item gets added to the line-item-adjustments table?

**Comment by olivermrbl** [comment]
> Can you tell me, when does a line-item gets added to the line-item-adjustments table?

LineItemAdjustments are generated upon applying a discount [here](https://github.com/medusajs/medusa/blob/40d8d88cb9043d2f0da776b24d4e6071fdccfa0b/packages/medusa/src/services/cart.ts#L1125).

**Comment by olivermrbl** [comment]
@anup-a After having run the [migration scripts](https://github.com/medusajs/medusa/blob/977e6086f40c5d5f2adf03155e2ec62c14f35f4d/docs/content/advanced/backend/upgrade-guides/1-3-1.md) do your LineItems on the order hold any adjustments?

**Comment by anup-a** [comment]
@olivermrbl Yes I line-adjustments table gets corrrectly populated as soon as discount is applied.
