### ISSUE TITLE
Create FileService interface and abstract class in core

### ISSUE THREAD

**Issue by pKorsholm** [medusajs/medusa#1556]
Extend interface with the following methods:

```jsx
uploadStream(filedata: record<string, any>; file: Readable): Promise<string>
downloadStream(fileData): Promise<Readable> -> to be used for import and processing in the core
generatePresignedDownload(resource): Promise<string>
```

This should be the base branch or first pr to be merged to allow the remaining pr’s to be developed independently.

Should we consider creating a batch-file-service in order to differentiate what is required for import/export and handling of images?

**Comment by olivermrbl** [comment]
Solved in #1577
