### ISSUE TITLE
Upload file to storage using a stream

### ISSUE THREAD

**Issue by pKorsholm** [medusajs/medusa#1557]
Implement upload to s3 (test using DO) through the api using streams. 

use case: file export

Implement the `uploadStream` method in the DO file service to export a generated csv file from the core. The file should be generated and uploaded in chunks using streams.

expected outcome 

- An initial implementation for uploading generated files using the fileService `uploadStream` method
- A guide to streaming files in chunks to a storage provider using a fileservice

**Comment by olivermrbl** [comment]
Solved in #1580
