### ISSUE TITLE
upload file to fileservice using fileservice implementation and api

### ISSUE THREAD

**Issue by pKorsholm** [medusajs/medusa#1558]
implement file upload through the api to S3 (test using DO)

use case: file import

The goal is to receive a file in express at `req.files` and to upload that file. The implementation should use #1557.

Initially setting up a dummy endpoint that can be deleted later would be the easiest way to get started with this.

outcome: 

- initial implementation for uploading files through the api using fileService
- guide to setting up fileservice uploads from the api

**Comment by olivermrbl** [comment]
Solved in #1580
