### ISSUE TITLE
Download a file from storage to the core

### ISSUE THREAD

**Issue by pKorsholm** [medusajs/medusa#1559]
Implement the `download` method for S3 (testing using DO)

use case: file import

The goal is to be able to download an entire csv file to memory for processing. The file should be available as stream for partial processing when importing, however should initially be loaded in its entirety.

expected outcome

- initial implementation for downloading entire files from storage using the fileservice
- guide to setting up fileservice downloads

**Comment by olivermrbl** [comment]
Solved in #1588
