### ISSUE TITLE
Generate presigned download link for files in each fileservice

### ISSUE THREAD

**Issue by pKorsholm** [medusajs/medusa#1560]
Implement `generatePresignedDownload(resource): string` 

Given metadata for a file in a protected s3 bucket, generate a presigned download link and return that. Navigating to the presigned link should provide a download of the file for a limited time. (5 minutes initially)

The method should receive information about the exported file and generate the corresponding presigned download link.

**Comment by olivermrbl** [comment]
Solved in #1588
