### ISSUE TITLE
Implement fileservice updates for streaming in spaces

### ISSUE THREAD

**Issue by pKorsholm** [medusajs/medusa#1588]
Implement fileservice methods for streaming in digital ocean plugin

**`getUploadStreamDescriptor`**

use case: file upload through the core

Implement the `getUploadStreamDescriptor` method in the DO file service to export a file from the core. The file should be written to a stream that will upload the chunks to the fileservice as they are provided.

This method should be usable in two ways: 
- when generating a file in the core it should be uploadable in chunks 
- when uploading a file through the core it should be possible to forward the data through streams

expected outcome
- An initial implementation for uploading generated files using the fileService uploadStream method

**`downloadAsStream`**

use case: file import from DO to core

The goal is to be able to download an entire csv file to memory for processing. The file should be available as stream for partial processing when importing, however should initially be loaded in its entirety.

expected outcome
- initial implementation for downloading entire files from storage using the fileservice

**`getPresignedDownload`**

Given metadata for a file in a protected s3 bucket, generate a presigned download link and return that. Navigating to the presigned link should provide a download of the file for a limited time. (5 minutes initially)

The method should receive information about the exported file and generate the corresponding presigned download link.

expected outcome
- initial implementation for providing download links to protected files through the fileservice

Issues: 
- [x] #1557 
- [x]  #1588 
- [x] #1559 
- [x] #1560

**Comment by olivermrbl** [comment]
Solved in #1585
