### ISSUE TITLE
[Proposal][WIP] List DiscountConditions by type

### ISSUE THREAD

**Issue by olivermrbl** [medusajs/medusa#1595]
## Goal
We want to be able to retrieve a specific type of conditions from a DiscountCondition. Can be products, collections, tags, types, and customer groups.

## Proposal
**Endpoint**
```
[GET] /admin/discounts/:discount_id/conditions/:condition_id/types?type=products&offset=0&limit=20
```

**Middleware handler**
_Access control_
```ts
export async function canAccessDiscountCondition(req, res, next) {
  const { discount_id, condition_id } = req.params

  const discountService: DiscountService = req.scope.resolve("discountService")

  const discount = await discountService.retrieve(discount_id, {
    relations: ["rule", "rule.conditions"],
  })

  const existsOnDiscount = discount.rule.conditions.some(
    (c) => c.id === condition_id
  )

  if (!existsOnDiscount) {
    throw new MedusaError(
      MedusaError.Types.NOT_FOUND,
      `Condition with id ${condition_id} does not belong to Discount with id ${discount_id}`
    )
  }

  next()
}
```

**Controller**
_Let's discuss the response object here. Think we need to think of something else than `discount_conditions`, since that would not be semantically correct_
```ts
export default async (req, res) => {
  const { condition_id } = req.params

  const validatedParams = validator(SomeValidatorClassParams, req.params) // { type, offset, limit, ... }

  const discountConditionService: DiscountConditionService = req.scope.resolve("discountConditionService")

  const config = getListConfig<DiscountCondition>(
      ...someFields,
      ...someRelations,
      validatedParams?.fields?.split(",") as (keyof DiscountCondition)[],
      validatedParams?.expand?.split(","),
      validatedParams?.limit,
      validatedParams?.offset,
    )
  
  const discountConditions = await discountConditionService.listAndCountConditionType(config)

  res.json({ discount_conditions: discountConditions })
}
```

**Comment by adrien2p** [comment]
**Guard**
before that guard is applied you will have the `parseQuery` with the default relations and fields required as well as the `getRequestedDiscount` so in the guard you can check if `req.discount` exists or fetch it if does not exists.
so in the end it will probably looks like the following:
```ts
export async function canAccessDiscountCondition(req: Request, res: Response, next: NextFunction) {
  const { discount_id, condition_id } = req.params

  const discountService: DiscountService = req.scope.resolve("discountService")

  const discount = req.discount ?? await discountService.retrieve(discount_id, {
    relations: ["rule", "rule.conditions"]
  })

  const existsOnDiscount = discount.rule.conditions.some(
    (c) => c.id === condition_id
  )

  if (!existsOnDiscount) {
    return next(
      new MedusaError(
        MedusaError.Types.NOT_FOUND,
        `Condition with id ${condition_id} does not belong to Discount with id ${discount_id}`
      )
    )
  }

  next()
}
```

**Handler**
```ts
export default async (req, res) => {
  const discountConditionService: DiscountConditionService = req.scope.resolve("discountConditionService")
  const discountConditions = await discountConditionService.listAndCountConditionType(req.listConfig)

  res.json({ discount_conditions: discountConditions })
}
```

**Comment by olivermrbl** [comment]
Yes, good point. With [1593](https://github.com/medusajs/medusa/pull/1593), we don't need to handle the list config in the controller.

Also I like this response. We could also do:
```
res.json({ conditions: discountConditions, type: req.filterableFields.type })
```

**Comment by adrien2p** [comment]
> Yes, good point. With [1593](https://github.com/medusajs/medusa/pull/1593), we don't need to handle the list config in the controller.
> 
> Also, I like this response. We could also do:
> 
> ```
> res.json({ conditions: discountConditions, type: req.filterableFields.type })
> ```
> 
> Wdyt?

Yes this is even better, that way there is no dynamic value and it is much easier to handle on the front side 👍

**Comment by srindom** [comment]
@kasperkristensen and I have discussed an alternative approach that would be good to get your thoughts on.

The main thought is that the retrieval of the resources on a condition will be delegated to either `ProductService, CollectionService, etc`. (Will stick to Product for simplicity, but should be extended to the other resource types too)

All the list logic etc. will be handled by the existing admin-list-products controller. This would make it possible to do this:
```
GET /admin/products?discount_condition_id=[whatever]
```

To make it simple to discover details about a condition we can change the condition endpoints to work like this:

```
GET /admin/discounts/:id/conditions
```
```js
// Response
{
  conditions: [
    {
      id: "cond_1234",
      type: "product",
      products: {
        count: 352,
        limit: 10,
        offset: 0,
        next: "/admin/products?condition_id=cond_1234&offset=10&limit=10",
        items: [
          { 
            id: "prod_...",
            [other product data]
          },
          [9 other products]
        ]
      }
    },
    [rest of the conditions]
  ],
  [list response stuff],
}
```

In the controller for retrieving conditions we would make use of the `productService` to perform the actual listing:

```js
const condition = await conditionService.retrieve(id)

const productLimit = 10

const [products, productCount] = await productService.listAndCount({ discount_condition_id: id }, { take: productLimit })
condition.products = {
  limit: productLimit,
  offset: 0,
  count: productCount,
  next: `/admin/products?discount_condition_id=${id}&limit=${productLimit}&offset=10`,
  items: products
}

res.json({ condition })
```

This way we avoid making tricky implementations within the `ConditionService` and it will be a super nice API experience. 

The biggest issue that I see with this implementation is that it introduces a new pattern for nested arrays (namely the `{ count, items: [....]` pattern`). However, I think we will have to introduce this pattern at some point anyway so this might as well be the first step towards that.

Wdyt?

**Comment by adrien2p** [comment]
😅 sorry for the clarity, yes I agree on that approach.

we have to be careful with that, from a perf point of view I think it would be fine since it would always be a limited number of objects that we will manipulate, but from the architecture point of view, we don’t want all the services to inject all the other services.

in the other hand, we could still rely on the join from typeorm, but we would have to add something to check if the relation is a many or a one and if it is a many then limiting the query and add some internal metadata. Maybe through building the join as a custom sub query?? Then later we can build the object-like (don’t know how to name it ^^)

relying on the services would break (I think) the expand/fields feature

**Comment by adrien2p** [comment]
After a bit of research, I didn’t find much info on the ability to paginate the relationship’s with typeorm. Which means either going with the services as you mentioned @srindom or the sub query builder as I mentioned. After looking into the code, i can see that the query of the relationship are generally builded in a loop, which means that we could create a sub query builder to limit and prepare the result object and then join the sub query as part of the original query builder. Wdyt?
