### ISSUE TITLE
Feat: Support Amazon-IAM Authentication  of postgres rds via typeorm

### ISSUE THREAD

**Issue by SGFGOV** [medusajs/medusa#1612]
For increased security IAM authentication is advised with postgres as opposed to static password authentication in production environments on AWS. However, at present medusa doesn't seem to have a way to enable this, though the underlying typeorm supports it. 

Approach 
1.use typeorm 0.2.0 and implement optional fields 
Apporach 2 to ugprade to typeorm 0.3.5 datasource 
https://github.com/typeorm/typeorm/blob/master/src/driver/postgres/PostgresConnectionCredentialsOptions.ts

**Comment by adrien2p** [comment]
You can create a pr and propose some changes to take that in count.
You would have to look at the medusa/sec/loaders/database file and look for the migration script located in the medusa/src/commands directory 🚀

**Comment by olivermrbl** [comment]
Feature requests have been moved to GitHub Discussions, so closing this. Feel free to open a new discussion, if this is still of interest :)
