### ISSUE TITLE
Please rename the money_amount table to something sensible

### ISSUE THREAD

**Issue by AlexDigital974** [medusajs/medusa#1616]
all table look to follow some kind of logic/relationship/self explanatory name except this one.

its like product_option is renamed article_choice but nothing like nothing uses 'article' or 'choice'
or
price_list_customer_groups is renamed money_list_client_groups 
customer-> transform to client
price -> transform to money

**Comment by srindom** [comment]
Hi @AlexDigital974 appreciate the input, but this is unfortunately not something that we will be able to do within the foreseeable future, however, think it is a good point to improve the docs to make the discoverability of this easier - will make sure to make a note of it :)

**Comment by srindom** [comment]
@shahednasser maybe we should make reference docs for the DB model?
