### ISSUE TITLE
Initialize Payment Sessions (manual payment)

### ISSUE THREAD

**Issue by kfekairii** [medusajs/medusa#1628]
When i try to Initialize Payment Sessions **[post] /carts/{id}/payment-sessions** , i got a 200 response.

But when I try to create a payment session with **provider_id = manual** **[post] /carts/{id}/payment-session** i got 
`{
    "type": "unexpected_state",
    "message": "Could not find payment session"
}`

**Comment by kfekairii** [comment]
I find the problem,

It must be at least one item in the card,
but i tried to init the payment at the creation of the card 😅

**Comment by herawais** [comment]
> I find the problem,
> 
> It must be at least one item in the card, but i tried to init the payment at the creation of the card 😅

You mean card or cart ?
