### ISSUE TITLE
Docs: rename documentations for consistency

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#1633]
To maintain consistency in the documentation, the "[How to Add a Fulfillment Provider](https://docs.medusajs.com/advanced/backend/shipping/add-fulfillment-provider)" documentation should be renamed to "How to Create a Fulfillment Provider" and it should be renamed in the sidebar to "Create a Fulfillment Provider.

Similarly, the sidebar link to "[How to Create a Payment Provider](https://docs.medusajs.com/advanced/backend/payment/how-to-create-payment-provider)" should be renamed to "Create a Payment Provider"

**Comment by mkaychuks** [comment]
How do one have access to the sidebar??

**Comment by shahednasser** [comment]
@mkaychuks there is already a PR for this but for future reference the sidebar is in `www/docs/sidebar.js`. We have a documentation contribution guideline coming out soon but you can find it in the PR #1611

**Comment by mkaychuks** [comment]
Alright. Thanks for the information. my PR should be closed 😄
