### ISSUE TITLE
Bug: Resent notification replaces parent notification

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#1636]
If a notification is resent using the Resend Notification endpoint, the [resent notification](https://docs.medusajs.com/api/admin/notification/resend-notification) replaced the original notification instead of creating a new one that is associated with the original notification using the `parent_id`.

This is mainly because of the following lines in the `resend` method in the `NotificationService`:

https://github.com/medusajs/medusa/blob/2eb2126fe348565721e05e6f0da01c46bad6185a/packages/medusa/src/services/notification.js#L250-L255

The `id` field should be set as `null` or removed from the `notification` object before its data is used to create the new notification.

**Comment by srindom** [comment]
Happy to accept PRs for this! 

- the PR should include an integration test to verify that the notification is not replaced

**Comment by Wahaj404** [comment]
Hey @srindom, can I work on this?

**Comment by srindom** [comment]
> Hey @srindom, can I work on this?

Yes! Please do :)

**Comment by SounakB** [comment]
Hi, @srindom I would like to work on this one

**Comment by prabureddy** [comment]
Raised a PR for this:- #2178
