### ISSUE TITLE
Docs: Wrong code example for setting up a Next.js storefront

### ISSUE THREAD

**Issue by mariocaleta** [medusajs/medusa#1645]
In https://docs.medusajs.com/how-to/setting-up-a-nextjs-storefront-for-your-medusa-project#link-storefront-to-a-server code example: `const BACKEND_URL = process.env.GATSBY_STORE_URL || "http://localhost:9000"` 

Should be `const BACKEND_URL =
  process.env.NEXT_PUBLIC_MEDUSA_URL || 'http://localhost:9000';`

**Comment by shahednasser** [comment]
Thank you @mariocaleta for submitting this! We actually have a [PR](https://github.com/medusajs/medusa/pull/1579/files) in the work that removes this page as it is no longer necessary.
