### ISSUE TITLE
Update "sqlite3" dependency not useable on newer macs

### ISSUE THREAD

**Issue by Inoir** [medusajs/medusa#1647]
On New Mac this dependency is causing problems and so medusa isnt installable.
Cause of deprecation of python cmd sqllite3 version 5.0.2 is not even possible to use in any way.

Tried to fix this with symlink to python3 cmd, but throws error: 

```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@14.18.1 | darwin | arm64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@14.18.1 | darwin | arm64
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /opt/homebrew/bin/python3 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:383:12)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
```

please update to at least version 5.0.3 so python3 is usable.

https://github.com/TryGhost/node-sqlite3/releases/tag/v5.0.3 
node-gyph 8.x is using new @mapbox/node-pre-gyp cause node-pre-gyp is deprecated and using very very very old and deprecated python2, thats not even installed on newer macs on default setup and not willing to install old buggy things.

Edit:
this PR could be merged?!
https://github.com/medusajs/medusa/pull/1453

**Comment by loyaltytrooper** [comment]
Hi if the mods would like could they please assign this issue to me?
