### ISSUE TITLE
Docs: Remove redis to go from heroku deployment guide

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#1650]
Heroku announced that Redis to Go will be discontinued and removed from all apps on heroku on August 8th. We should update the documentation to remove the usage of Redis to Go and replace it with another add on.

**Comment by octalpixel** [comment]
You can probably have a look at https://upstash.com/ . There is generous free tier for hobby projects

**Comment by shahednasser** [comment]
Thanks for the tip @octalpixel will look into it!
