### ISSUE TITLE
Docs: Gatsby Quickstart Directory

### ISSUE THREAD

**Issue by cboydstun** [medusajs/medusa#1654]
The [Gatsby Medusa Quickstart](https://docs.medusajs.com/starters/gatsby-medusa-starter/) uses the same directory `my-medusa-store` as the [API Quickstart](https://docs.medusajs.com/quickstart/quick-start/). 

## Gatsby Medusa Quickstart:
![image](https://user-images.githubusercontent.com/52934303/173427512-dd6a617e-30b5-4299-a224-54a57dfd177c.png)

## API Quickstart: 
![image](https://user-images.githubusercontent.com/52934303/173427689-00079311-4a05-408c-859f-872c5973cf89.png)

Please consider revising to `gatsby-medusa-store` or some variant. Thanks! =)

**Comment by olivermrbl** [comment]
Great catch - thanks for reporting it in! 💪 

@shahednasser Wdyt? Should we fix it in the Gatsby starter?

**Comment by shahednasser** [comment]
@olivermrbl  We actually have a PR #1579 that should fix this. Thank you for reporting it @cboydstun !

**Comment by olivermrbl** [comment]
Great!
