### ISSUE TITLE
Published product have a "publish" option in product list view, even though they are published

### ISSUE THREAD

**Issue by magnusdr** [medusajs/medusa#1691]
![Screenshot 2022-06-16 at 18 56 54](https://user-images.githubusercontent.com/6572902/174125451-b47acbb4-edde-4d36-9cbb-8c88c130484a.png)

**Comment by olivermrbl** [comment]
Thanks for reporting this one in @magnusdr. Can I get you to open an issue in the [admin repository](https://github.com/medusajs/admin) instead?
