### ISSUE TITLE
Docs: Improve "Features" list in documentation

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#1736]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Improve "Features" list in the documentation to give more details of the different APIs in Medusa.

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by mkaychuks** [comment]
Can you explain this further to help understand.

**Comment by shahednasser** [comment]
It should be a nice page that highlights all of Medusa's available APIs and features, with screenshots from the Admin dashboard where applicable. It should be something similar to the [Features list in the README](https://github.com/medusajs/medusa#features) but expanded.
