### ISSUE TITLE
Types missing when generating REST API client from store-spec3.json 🏷

### ISSUE THREAD

**Issue by magnusdr** [medusajs/medusa#1738]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I want to use `openapi-typescript-codegen` to generate a REST API client for the Medusa admin and store API's. This tools simply takes the OpenAPI JSON file as input, and generates a client in typescript.

The generated code however, is having `any` in the return types from most REST API endpoints. This is because many of the endpoints' `schema` in the `responses` section is missing a `"type"` property.

### How can this issue be resolved?

Add the missing `"type"` properties in the response schemas

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by magnusdr** [comment]
I've been trying to add these type properties *inline*, as it seems like the OpenAPI JSON files is generated using the `scripts/build-openapi.js`. Running this script initially generated a lot of errors caused by misaligned indentation in the inline YAML. After solving this, I'm now getting:

```
Error in store
{
  stack: 'MissingPointerError: Token "orders" does not exist.\n' +
    '    at Pointer.resolve (/Users/magnusdr/medusa/node_modules/@apidevtools/json-schema-ref-parser/lib/pointer.js:94:13)\n' +
    '    at $Ref.resolve (/Users/magnusdr/medusa/node_modules/@apidevtools/json-schema-ref-parser/lib/ref.js:124:20)\n' +
    '    at $Refs._resolve (/Users/magnusdr/medusa/node_modules/@apidevtools/json-schema-ref-parser/lib/refs.js:156:15)\n' +
    '    at dereference$Ref (/Users/magnusdr/medusa/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:140:23)\n' +
    '    at crawl (/Users/magnusdr/medusa/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:69:28)\n' +
    '    at crawl (/Users/magnusdr/medusa/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:78:30)\n' +
    '    at crawl (/Users/magnusdr/medusa/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:78:30)\n' +
    '    at crawl (/Users/magnusdr/medusa/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:78:30)\n' +
    '    at crawl (/Users/magnusdr/medusa/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:78:30)\n' +
    '    at crawl (/Users/magnusdr/medusa/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:78:30)\n' +
    '    at crawl (/Users/magnusdr/medusa/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:78:30)\n' +
    '    at crawl (/Users/magnusdr/medusa/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:78:30)\n' +
    '    at crawl (/Users/magnusdr/medusa/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:78:30)\n' +
    '    at crawl (/Users/magnusdr/medusa/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:78:30)\n' +
    '    at crawl (/Users/magnusdr/medusa/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:78:30)\n' +
    '    at dereference (/Users/magnusdr/medusa/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:19:22)',
  code: 'EMISSINGPOINTER',
  message: 'Token "orders" does not exist.',
  source: '/Users/magnusdr/medusa/',
  path: null,
  toJSON: [Function: toJSON],
  name: 'MissingPointerError',
  footprint: 'null+/Users/magnusdr/medusa/+EMISSINGPOINTER+Token "orders" does not exist.',
  toString: [Function: toString]
}
```

I also get this for `admin`, not just `store`.

May I ask someone on the team point me in the right direction? I assume the generation from inline comments is not the current workflow anymore, as it had so many errors. Should I just directly edit the JSON files?

**Comment by shahednasser** [comment]
Hi @magnusdr thank you for pointing this out! We're actually looking into refactoring the API reference and resolving all these issues to provide a more up-to-date API reference and a better experience on the website

**Comment by magnusdr** [comment]
Nice!

As you are transitioning to Typescript, I'll suggest considering [`zod`](https://www.npmjs.com/package/zod) for input validation on your API endpoints. Good for security and developer experience (produces really nice errors). If you decide to use `zod`, then [`@anatine/zod-openapi`](https://www.npmjs.com/package/@anatine/zod-openapi) could be a great tool for generating the OpenAPI reference files from the input validation code.

Good luck on the refactor, and nice work so far! Let me know if I could be of help 😊

**Comment by shahednasser** [comment]
Thanks for the recommendations! I'll make sure to look into those 🙏🏻

**Comment by olivermrbl** [comment]
@shahednasser should be good to close right?

**Comment by shahednasser** [comment]
Yes
