### ISSUE TITLE
Creating order from cart calculating taxes incorrectly.

### ISSUE THREAD

**Issue by dwene** [medusajs/medusa#1813]
### Describe the bug

When completing the cart and charging the customer, the completed order shows different totals than the cart totals. I believe this is because there's a bug with the new Tax plugin API when creating the order. They payment that is collected through stripe uses the correct payment information though.

Here's a video showing the issue: https://www.loom.com/share/b454168b6000487195f4304e553c556b

### System information

Medusa version (including plugins): 
    "@medusajs/medusa": "1.3.3",
    "@medusajs/medusa-cli": "^1.3.1",
    "@medusajs/medusa-js": "1.2.3",

Node.js version: 14
Database: Postgres
Operating system: OSX 
Browser (if relevant): Chrome

### Steps to reproduce the behavior

1. Setup taxes to compute using a tax plugin, currently we are using the ziptax plugin that I created here: https://github.com/lambda-curry/medusa-tax-ziptax

2. Create a cart with items

3. Setup stripe payments and complete the cart.

4. Notice that order totals are different than cart totals, because tax amounts are different.

### Expected behavior

Tax on cart is the same as completed order

### Screenshots

https://www.loom.com/share/b454168b6000487195f4304e553c556b

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

I believe creating the order is still using the old tax_rate setup in the region. When I change the tax rate in there, it changes on the order, even though everything should be using our ziptax plugin to calculate tax.

**Comment by srindom** [comment]
@dwene - thanks a lot for reporting! Can we jump on a call to debug this? :)

**Comment by olivermrbl** [comment]
Fixed in #1823
