### ISSUE TITLE
Cannot Login to Medusa Admin - Medusa Backend, Server and Admin installed + Seed

### ISSUE THREAD

**Issue by dravasp** [medusajs/medusa#1829]
Medusa Backend, Server and Admin installed + Seed
admin@medusa-test.com
supersecret

Login Credentials - "These credentials do not match our records" Error

Added "medusa user -e abc@abc.com -p abc1234" as well and restarted server but does not recognize

**Comment by olivermrbl** [comment]
I assume this is local; what ports are you running your server and admin on?

**Comment by olivermrbl** [comment]
What response are you receiving on the request? @dravasp 

Sounds super interesting! I would love to hear a bit more about your project, if you don't mind sharing. Are you in our [Discord](https://discord.gg/medusajs)? I can throw you a DM :)

**Comment by dravasp** [comment]
@olivermrbl Following the conversation to discord

**Comment by bytrangle** [comment]
@dravasp Do you still have this issue?

**Comment by websupergirl** [comment]
@dravasp I'd like to know how you solved it as well as you how you restarted the server. I have it set up as per the instructions for DO deployment and I can't find a way to stop the server and start again with the medusa cli.

**Comment by websupergirl** [comment]
I found it was a CORS admin issue, there was a trailing slash and it took another 3-4 doc pages before I found that info about how the urls should be in those options on DO.

**Comment by leikoilja** [comment]
Gosh, it took me hours to debug and realise that the tailing slash in the `ADMIN_CORS` and `STORE_CORS` is the problem 😓 😅  Thanks @websupergirl 💪 
imgo, this should be either handled or added to docs

**Comment by code-sergeant** [comment]
Wow... trailing slash is what got me as well. Was getting pretty frustrated there. Thanks all

**Comment by vitustockholm** [comment]
where was this trailing slash in env file ? ??
