### ISSUE TITLE
Issues with many API calls at the same time.

### ISSUE THREAD

**Issue by dwene** [medusajs/medusa#1834]
### Describe the bug

I'm doing a bulk update on customers using a script and the medusa admin update-customers API.
When trying to perform multiple update calls at the same time for different customers, I often receive this error:

```
error:   Cannot read property 'queryRunner' of undefined
[0] TypeError: Cannot read property 'queryRunner' of undefined
[0]     at CustomerService.<anonymous> (/Users/derekwene/src/nibll-home/apps/home/api-medusa/node_modules/@medusajs/medusa/src/interfaces/transaction-base-service.ts:84:58)
[0]     at step (/Users/derekwene/src/nibll-home/apps/home/api-medusa/node_modules/@medusajs/medusa/dist/interfaces/transaction-base-service.js:44:23)
[0]     at Object.throw (/Users/derekwene/src/nibll-home/apps/home/api-medusa/node_modules/@medusajs/medusa/dist/interfaces/transaction-base-service.js:25:53)
[0]     at rejected (/Users/derekwene/src/nibll-home/apps/home/api-medusa/node_modules/@medusajs/medusa/dist/interfaces/transaction-base-service.js:17:65)
[0]     at runMicrotasks (<anonymous>)
```

Digging further into the error and adding logging using the medusa-dev cli, I believe that is not the real error, but is being masked by a bug in the transactional-base-service code here:

https://github.com/medusajs/medusa/blob/master/packages/medusa/src/interfaces/transaction-base-service.ts#L83

At this point in time, `this.transactionManager_` is undefined. There's an if statement that checks to make sure it's not undefined, but it's run before multiple async function calls.

Adding a console log, the real error is this:

```
Error: Query runner already released. Cannot run queries anymore.
[0]     at QueryRunnerAlreadyReleasedError.<anonymous> (/Users/derekwene/src/nibll-home/apps/home/api-medusa/node_modules/core-js/internals/wrap-error-constructor-with-cause.js:37:62)
[0]     at QueryRunnerAlreadyReleasedError.Error (/Users/derekwene/src/nibll-home/apps/home/api-medusa/node_modules/core-js/modules/es.error.cause.js:28:43)
[0]     at QueryRunnerAlreadyReleasedError.TypeORMError [as constructor] (/Users/derekwene/src/nibll-home/apps/home/api-medusa/src/error/TypeORMError.ts:7:9)
```

When I add some delay between the calls, I don't receive this error anymore. I believe there's an issue with database connections conflicting between different API calls.

When I use the medusa-dev cli to overwrite the update-customer api implementation, and wrap it in a database transaction, the issue is resolved.

### System information

Medusa version (including plugins): 1.3.3
Node.js version: 14
Database: postgres
Operating system: osx
Browser (if relevant): chrome

### Steps to reproduce the behavior

Attempt to make 5+ admin calls to the update-customer admin API.
Notice intermittent errors.

### Expected behavior

No queryRunner errors.

### Screenshots

N/A

### Code snippets

Included above

### Additional context

None

**Comment by srindom** [comment]
We have found the issue as outlined below - thanks for reporting!

- Services in Medusa are singleton
- Every time the API layer calls a service method with an `atomicPhase_` the `atomicPhase_` creates a new TransactionManager that is stored in the service
- If two requests concurrently try to use the same TransactionManager the request that finishes first will release the TransactionManager’s QueryRunner which will in turn make the second request fail because the query runner that is being used is already released.

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/7554214/178935531-d6612e06-9f73-4f2a-99e3-0819566e8443.png">

The plan now is to clean up usage of `atomicPhase` and fix endpoints:
- make sure that all service-level retrieve/list/listAndCount/(other select-only methods) don’t use the atomicPhase_
- If a handler calls an atomicPhase-method the handler MUST wrap that call in a transaction:
```
// src/api/some-handler.js

// 🛑 OLD
myService.serviceThatUsesAtomicPhase()

// ✅ NEW
manager.transaction(t => {
  myService.withTransaction(t).serviceThatUsesAtomicPhase()
})
```

**Comment by maxpanakov** [comment]
As far as I understand, if we need to send a request that uses atomicPhase_, then we need to send it in turn.  Am i right ?

**Comment by olivermrbl** [comment]
Latest release includes a bunch of fixes around transactions in the core. Let us know if the issue persists after having updated to `v1.3.5` 👍

**Comment by eparizzi-clevertech** [comment]
I don't think this is solved unfortunately. I'm running a batch job that migrates customers from an old e-commerce to medusa. If I run it sequentially, everything works great.
As soon as I try to run in batches/pool, I start getting this error randomly... 

I'm on Medusa 1.7.8

**Comment by nickolasgeneral** [comment]
@maxpanakov https://quick-rajesh.github.io/IXQwfKIJlzFN/
