### ISSUE TITLE
[Feature]: Config should not strip off custom props.

### ISSUE THREAD

**Issue by Inoir** [medusajs/medusa#1837]
**Is your feature request related to a problem? Please describe.**
Currently, if you implement custom logic and need some configuration, the default config handling will strip off all properties, so you can use custom config only, if you overwrite configModule.

**Describe the solution you'd like**
Just load the config and dont make it this strict and hard coded.

**Describe alternatives you've considered**
Like i said, currently possible if you overwrite the configModule, but seems kinda unnecessary, since the config gets already loaded, but strips off custom props.

**Additional context**
[Code with strict config return](https://github.com/medusajs/medusa/blob/master/packages/medusa/src/loaders/config.ts#L53)

To fix this, just spread the rest config before projectConfig declaration.

I marked it as feature, since the default app is running without any problems.

**Comment by srindom** [comment]
Would it be okay to have a special part of the config that could be used for customizations?

This way we don't risk collisions in the future: could be `customConfig` or something like that?

**Comment by Inoir** [comment]
Should be okay. also i dont see any reason for, cause the needed props are already hardcoded, if you just spread the config before you defined projectConfig, your hard coded settings will overwrite the custom ones.
Give an example for custom config: https://github.com/adrien2p/medusa-extender

**Comment by srindom** [comment]
@Inoir - We are moving feature requests to GitHub Discussions to keep better track of the most requested features (using the upvote mechanism) and streamline GitHub Issues around bugs. Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!
