### ISSUE TITLE
medusa-payment-razorpay via npm "key_id" is required error

### ISSUE THREAD

**Issue by dravasp** [medusajs/medusa#1841]
Problem - medusa-payment-razorpay via npm "key_id" is required error

Error - Initializing defaultsError: key_id is mandatory

medusa-payment-razorpay": "^2.3.0"
Medusa version (including plugins): medusa-starter-default
Node.js version: v16.15.1

Steps to reproduce Error

npm install medusa-payment-razorpay

.env
RAZORPAY_API_KEY=
RAZORPAY_API_KEY_SECRET=

medusa-config.js
// Razorpay keys

const RAZORPAY_API_KEY = process.env.RAZORPAY_API_KEY  "";
const RAZORPAY_API_KEY_SECRET = process.env.RAZORPAY_API_KEY_SECRET  "";

// This is the place to include plugins. See API documentation for a thorough guide on plugins.
const plugins = [
  medusa-fulfillment-manual,
  medusa-payment-manual,
  {
    resolve: medusa-payment-razorpay,
    options:{
      api_key : process.env.RAZORPAY_API_KEY,
      api_key_secret:process.env.RAZORPAY_API_KEY_SECRET,
  },
},
];

**Comment by dravasp** [comment]
@adrien2p Thanks for the follow up, as I see, it seems to be a dotenv problem followed by a new issue of 

`Initializing databaseMissingDriverError: Wrong driver: "undefined" given. Supported drivers are: "aurora-data-api", "aurora-data-api-pg", "better-sqlite3", "capacitor", "cockroachdb", "cordova", "expo", "mariadb", "mongodb", "mssql", "mysql", "nativescript", "oracle", "postgres", "react-native", "sap", "sqlite", "sqljs".`

Is there a way to correctly solve both these issues?

**Comment by adrien2p** [comment]
You can have a look at that pr and update your config file https://github.com/medusajs/medusa-starter-default/pull/13

@olivermrbl

**Comment by dravasp** [comment]
Added the following 

```
const dotenv = require('dotenv')

 let ENV_FILE_NAME = '';
 switch (process.env.NODE_ENV) {
  case 'production':
    ENV_FILE_NAME = '.env.production';
    break;
  case 'staging':
    ENV_FILE_NAME = '.env.staging';
    break;
  case 'test':
    ENV_FILE_NAME = '.env.test';
    break;
  case 'development':
  default:
    ENV_FILE_NAME = '.env';
    break;
 }

 try {
  dotenv.config({ path: process.cwd() + '/' + ENV_FILE_NAME });
 } catch (e) {
  //handle error
 }
```
to solve the dotenv problem

**Comment by adrien2p** [comment]
Could you share your config file please 👍
