### ISSUE TITLE
Add Product Reviews

### ISSUE THREAD

**Issue by edihasaj** [medusajs/medusa#1869]
Do you guys think is it reasonable to create product customer reviews? To do this there are things in the core functionality of medusa that should be added and related to each other...

![image](https://user-images.githubusercontent.com/34984294/179546366-f4065816-20d9-41cb-a880-8590dce61f1f.png)

**Comment by srindom** [comment]
@edihasaj - I think this would make an excellent candidate for a plugin. High-level thinking here would be:

- create a data model that can hold reviews. Maybe: `name`, `email`, `body`, `product_id`
- create endpoints to manage reviews: 
  - `POST /store/reviews` takes name, email, body and product_id
  - `GET /store/reviews?product_id={id}`
 
You could potentially add business logic that checks if a reviewer has purchased the product before.

**Comment by edihasaj** [comment]
OK, I'll see what I can do here.

**Comment by pucilpet** [comment]
> @edihasaj - I think this would make an excellent candidate for a plugin. High-level thinking here would be:
> 
> - create a data model that can hold reviews. Maybe: `name`, `email`, `body`, `product_id`
> - create endpoints to manage reviews: 
>   - `POST /store/reviews` takes name, email, body and product_id
>   - `GET /store/reviews?product_id={id}`
>  
> You could potentially add business logic that checks if a reviewer has purchased the product before.

I think rating should probably be added to the model (1 to 5 is standard)?

**Comment by edihasaj** [comment]
It should be a field integer to hold the rating value besides the body comment...

**Comment by edihasaj** [comment]
@srindom can we create migrations from the plugin?, where to store them architecturally?

**Comment by shahednasser** [comment]
Hi @edihasaj yes you can! It should be under the `src/migrations` directory. You can read more about it in the [Create a Plugin](https://docs.medusajs.com/advanced/backend/plugins/create#project-structure) documentation.

**Comment by edihasaj** [comment]
Can you guys help me on something.. I can't get to include changes from the medusa migrations run after plugin creation. I can't even get endpoints working in this plugin which is kind of weird. The structure of the plugin and src is like this, code builds and transpiles but it's not linking with the medusa server, I've tried linking and it links successfully I don't know if I got the steps right, probably you can tell some small details I missed?

![image](https://user-images.githubusercontent.com/34984294/180606368-5f12f64f-dd88-4069-b290-b1eafee367a9.png)

Thanks alot.

**Comment by edihasaj** [comment]
@shahednasser ?

**Comment by shahednasser** [comment]
@edihasaj did you run the build or watch command? Because if so then the files under the `src` directory should be transpiled into files in the root. So, for example, after running one of these commands, you should have an `api`, `migrations`, `models`, `repositories`, `services`, and `types` directories. I can only see a `services` directory in the root.

**Comment by edihasaj** [comment]
I've run watch but after I've created plugin functionality, probably I should recreate  the plugin and run the cmd from the beginning. Ok, this info for root folders is good one, I'm gonna see what went wrong, and let you know. Thank you for your support 🙏

**Comment by shahednasser** [comment]
No worries! Let me know if you need more help 🙂

**Comment by edihasaj** [comment]
Thanks @shahednasser in a way that was the case for not generating ts files to js, so I ended up with a hybrid way of both.
