### ISSUE TITLE
Calculated shipping options: Can't see price until shipping method is added to the cart

### ISSUE THREAD

**Issue by dwene** [medusajs/medusa#1877]
## Bug report

Calculated shipping options: Can't see price for calculated shipping options until shipping method is added to the cart.

### Describe the bug

When I'm listing shipping options for a cart, some of the options use calculated prices, but the prices aren't calculated until I add them to the cart as a shipping method.

This is not an ideal experience, because customers won't be able to see estimates on the price, unless they cycle through all the options, adding each one to the cart as a shipping method, to see shipping price with the items in their cart.

It would be ideal if the API described here: https://docs.medusajs.com/api/store/shipping-option/retrieve-shipping-options-for-cart
used the fulfullment-provder's `calculatePrice` function with the cart: https://docs.medusajs.com/references/services/classes/FulfillmentProviderService#calculateprice

### System information

Medusa version (including plugins): 1.3.4
Node.js version: 14
Database: pg
Operating system: osx
Browser (if relevant): N/A

**Comment by srindom** [comment]
Made a quick fix here: https://github.com/medusajs/medusa/pull/1878

Could I get you to checkout the branch and test if it works - will also add a few more test cases :)
