### ISSUE TITLE
Digital Ocean images not showing on the frontstore

### ISSUE THREAD

**Issue by benhammoush** [medusajs/medusa#1885]
Hello, 

I'm using the gatsby contentfull starter with postgresql and digital ocean but when i create a new product and add images in the admin panel, i can't see the images on the frontstore. 

![image](https://user-images.githubusercontent.com/45472564/180193144-597419e6-cde7-4b30-b440-b5719120dbe8.png)

When i click on the product i have this error : 

![image](https://user-images.githubusercontent.com/45472564/180193327-05bfbbb9-ec29-491e-8477-c3e91c7f6f88.png)

The image are well uploaded on my digital ocean bucket from my admin panel.

Any ideas ? 

Thanks

**Comment by kasperkristensen** [comment]
Hi @benhammoush, try to run `gatsby clean` and rebuild your site, this usually helps when this image occurs. Let me know if it helps otherwise I'll dig deeper into it 😄

**Comment by benhammoush** [comment]
Hi @kasperkristensen, still not working. I have this error now. 

![image](https://user-images.githubusercontent.com/45472564/182002680-8dc3443c-a5ec-4c48-90e2-fccf974e375f.png)

I understood that CreateRemoteFileNode don't support special chars but i still can't make it work.

I removed every images then uploaded new one on my digital ocean bucket using the admin panel but look like the website as cached the old url. 

Thanks.

**Comment by benhammoush** [comment]
Hi @kasperkristensen, thanks for the answer. 

I think i may have found the source of my problem. There's an image url stored somewhere that's not valid and i can't find how to fix it.

"Error: url passed to createRemoteFileNode is either missing or not a proper web uri: https://images-0x.fra1.digitaloce  anspaces.com/sweat (3)-1658396716568.png"

I tried to remove every images in the admin panel and replace them without forbidden char but this error keep showing when i rebuild the project. 

It's weird because the image works on the product page but don't show neither in the small component "Featured" or in the cart pophover or in the checkout.

![image](https://user-images.githubusercontent.com/45472564/182006353-6f62acb8-7c7f-4e98-90ca-f34cbe75d49c.png)
![image](https://user-images.githubusercontent.com/45472564/182006394-687da966-ab35-413c-9645-7b9b891cd4c8.png)
![image](https://user-images.githubusercontent.com/45472564/182006404-d43f1162-1412-4776-a2a5-c7df7d5b981b.png)

Thanks for your help.

**Comment by kasperkristensen** [comment]
Hi @benhammoush,

I would guess that it is because the invalid image is stored as the product's thumbnail. Try to set a new thumbnail, clear the cache with `gatsby clean`, and rebuild the site 😄

**Comment by srindom** [comment]
@benhammoush did Kasper's suggestion help you?

**Comment by srindom** [comment]
@benhammoush did Kasper's suggestion solve your issue? :)
