### ISSUE TITLE
Idempotency key conflicted

### ISSUE THREAD

**Issue by Ghiffari** [medusajs/medusa#1887]
### Describe the bug

I'm trying to create new order which includes create cart - select payment session. However I encountered this issue quite a lot via Postman, and sometimes happening in storefront as well. 

I did read [idempotency on documentation](https://docs.medusajs.com/advanced/backend/payment/overview/#idempotency-key)

I knew we can retry steps but sometimes eventhough retried 10+ times still same conflicted issue unless I create a new cart.

I want to know why this is happening and how we can elegantly resolve this problem.

### System information

Medusa version (including plugins):
Node.js version: 16.15.0
Database: postgres
Operating system: ubuntu 20
Browser (if relevant): google chrome / postman

### Steps to reproduce the behavior

1. Hit create cart endpoint
2. Hit any next step of cart process

### Expected behavior

Not encountered idempotency key conflicted

### Screenshots
![Postman_XTrYQCiRMh](https://user-images.githubusercontent.com/14313342/180206413-aeb9ac2b-8692-4f7c-b526-050efdbeb55a.png)

![Postman_liaCJbQUyo](https://user-images.githubusercontent.com/14313342/180206423-05c86819-39b3-494c-9ff6-765d5338d253.png)

**Comment by olivermrbl** [comment]
Issue has been resolved. Let us know if it persists after updating to latest!
