### ISSUE TITLE
Create token for app ( wrong point in documentation )

### ISSUE THREAD

**Issue by pawel-niedzwiecki** [medusajs/medusa#1895]
### Issue Summary

Hey you have wrong information in [documentation](https://docs.medusajs.com/api/admin/apps/generates-a-token-for-an-application) , when i want create token for app , in documentation is wrong point

### How can this issue be resolved?

POST /apps - this is wrong 

POST /admin/apps/authorizations - it is ok point 

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Hello @pawel-niedzwiecki there's actually already a PR #1883 to refactor the API reference website and fix some of the mistakes in the endpoints. Thank you for reporting this issue! 🙂

**Comment by pawel-niedzwiecki** [comment]
No problem :)

**Comment by shahednasser** [comment]
Closed in #1883
