### ISSUE TITLE
Empty request body in GET requests

### ISSUE THREAD

**Issue by ayushbgl** [medusajs/medusa#1898]
### Describe the bug

GET requests from Next JS starter during deployment are sending an empty data dictionary resulting in bad request response from various providers.

### System information

Medusa version (including plugins):
Node.js version: 16.6.0
Database: postgres
Operating system: Mac and Ubuntu
Browser (if relevant): Chrome

### Steps to reproduce the behavior
1. Deploy the backend to Google Cloud Run
2. Deploy the Next JS starter package pointing to that backend.
3. The deployment fails because there's a GET request to the backend with empty data, which is blocked by Google and 400 is returned.

### Expected behavior

The GET requests not to send any request body.

**Comment by adrien2p** [comment]
the pr https://github.com/medusajs/medusa/pull/1900 has been merged and will be part of the next release
