### ISSUE TITLE
Docs: Fix Install Command in Quickstart Guide

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#1904]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In the [Quickstart guide](https://docs.medusajs.com/quickstart/quick-start), The command in the first step is the following:

```bash
npm install -g @medusajs/medusa-cli
```

As we use a plugin to automatically convert npm commands to yarn commands, the command is converted incorrectly.

### How can this issue be resolved?

The command should be changed to the following:

```bash
npm install @medusajs/medusa-cli -g
```

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by Omar8345** [comment]
Me please 😀
