### ISSUE TITLE
Docs: Remove Tutorial link from the footer

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#1906]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In the footer there's a "Docs" column with a tutorial link below it which feels redundant:

![Screen Shot 2022-07-26 at 10 32 55 AM](https://user-images.githubusercontent.com/27354907/180951224-ef481c6d-bc5f-4b88-9bc5-5762b5386e72.png)

### How can this issue be resolved?

The Docs column with the Tutorial link must be removed.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Cool @DeviSriCharan2020412  I've assigned you!

**Comment by DeviSriCharan2020412** [comment]
Can you please tell me in which directory this **footer** class is present? I'm unable to find :(

**Comment by shahednasser** [comment]
This should be changed in `www/docs/docusaurus.config.js` under the `footer` key.

**Comment by saaagarsingh** [comment]
Hey @shahednasser 
Has this issue been resolved?
If not then I would love to fix the issue.
