### ISSUE TITLE
Docs: Add note about creating a database first in Configure your Server

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#1907]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In the Configure your Server documentation under the [PostgreSQL section](https://docs.medusajs.com/usage/configurations#postgresql-configurations), a note should be added that the database must be created first in PostgreSQL.

### How can this issue be resolved?

The note must be added as an admonition. You can learn about it in our [Contribution Guidelines](https://docs.medusajs.com/contribution-guidelines#notes-and-additional-information). Also, please add a link to a guide on how to create the PostgreSQL database (preferably from their official documentation).

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by momoolatunde** [comment]
I would like to fix this issue

**Comment by shahednasser** [comment]
Hi @momoolatunde I've assigned you!
