### ISSUE TITLE
Docs: Add missing link in "What's Next" in Notification Architecture Overview

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#1908]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In Notification Architecture Overview the first bullet point under the [What's Next section](https://docs.medusajs.com/advanced/backend/notification/overview#whats-next-) "Learn how to create your own Notification Provider." should be a link.

### How can this issue be resolved?

Add a link to "how to create your own Notification Provider." to the ["How to Create a Notification Provider" documentation](https://docs.medusajs.com/advanced/backend/notification/how-to-create-notification-provider).

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by ankitzm** [comment]
Hey, would love to work on this issue.

**Comment by shahednasser** [comment]
Great @ankitzm I've assigned you!

**Comment by ankitzm** [comment]
Thanks, started working in the issue !
