### ISSUE TITLE
Docs: Add Deploy to Netlify button to Next.js Quickstart

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#1909]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Add a Deploy to Netlify button to the [Next.js Quickstart guide](https://docs.medusajs.com/starters/nextjs-medusa-starter). The button logic is already implemented so you just need to add it to the documentation.

### How can this issue be resolved?

Add the following button:

```
[![Deploy to Netlify](https://www.netlify.com/img/deploy/button.svg)](https://app.netlify.com/start/deploy?repository=https://github.com/medusajs/nextjs-starter-medusa)
```

It should be under a new header with some text similar to the button in the [Gatsby Storefront Quickstart documentation](https://docs.medusajs.com/starters/gatsby-medusa-starter).

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by ankitzm** [comment]
Would love to take this one too, got some grasp on the docs.
