### ISSUE TITLE
Docs: Improve Docker documentation

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#1910]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The [Quickstart w. Docker](https://docs.medusajs.com/quickstart/quick-start-docker/) documentation needs improvement because:

1. It doesn't follow our style guide
2. The information might not be up to date or might not work
3. It's not in the sidebar

### How can this issue be resolved?

The documentation should:

1. Follow our style guide as indicated in our [contribution guidelines](https://docs.medusajs.com/contribution-guidelines)
2. Make sure the information in it are up to date and work
3. If there are any necessary steps needed to integrate with the storefront or admin that are different from the usual steps of integrating with Medusa, they should be specified.
4. A link to the documentation should be added in the sidebar.

### Requirement

Whoever wants to work on this issue must be experienced with Docker

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by momoolatunde** [comment]
I would like to fix this issue

**Comment by sabakhilji** [comment]
Hi Shahednasser, I would like to fix this issue. Can I?

**Comment by shahednasser** [comment]
I assigned @sabakhilji since @momoolatunde is already working on another issue 🙂

**Comment by Omar8345** [comment]
Hmm it seems @sabakhilji didn't work on it yet, will start a PR

**Comment by shahednasser** [comment]
Hello @sabakhilji are you still working on this? If so, @Omar8345 you shouldn't open a new PR

**Comment by sabakhilji** [comment]
Hi @shahednasser and @ Omar8345 yes I am working on it 
Thanks @shahednasser for assigning me this task:)

**Comment by Omar8345** [comment]
> Hello @sabakhilji are you still working on this? If so, @Omar8345 you shouldn't open a new PR

Okay, seems @sabakhilji is working on it, will leave it to him

**Comment by shahednasser** [comment]
@Omar8345 do you have experience with Docker? The entire documentation needs to be updated so an experience with docker is important

**Comment by Omar8345** [comment]
@shahednasser Yes, I am experienced with **Docker**. I could update it, did @sabakhilji work on it but didn't did the **Docker** thing? Then should I open a new *PR* or what? (*instead add my commit inside his PR, if so which*)

**Comment by shahednasser** [comment]
@Omar8345 just create a new PR. And please make sure to check out the [Contribution Guidelines on our documentation](https://docs.medusajs.com/contribution-guidelines) first.

**Comment by shahednasser** [comment]
This PR is open for contributions 🙏🏻

**Comment by sabakhilji** [comment]
Hi @shahednasser can I try to fix this issue? I am not a pro in Docker but I will try my best to do it.
Thanks!

**Comment by shahednasser** [comment]
Sounds great @sabakhilji I'll assign you

**Comment by sabakhilji** [comment]
Hi, @shahednasser thanks for assigning this task to me. Till now I dockerized the medusa image successfully in a container. Can you please elaborate on what else I need to do to accomplish this task? I observed that some of the issues are already fixed, please let me know what are the requirements to fix this issue.  Please find the image for a dockerized container of medusa.
![Screenshot (9)](https://user-images.githubusercontent.com/52318459/191331804-ecc50b5a-c951-48f9-84d6-048b61396607.png)
![Screenshot (10)](https://user-images.githubusercontent.com/52318459/191332186-7f110baa-6d90-44a8-bfce-d929cc98b73b.png)

**Comment by shahednasser** [comment]
Hi @sabakhilji we need to include correct details in the documentation basically. You can refer to [this PR](https://github.com/medusajs/medusa/pull/2023) for an example.

**Comment by shahednasser** [comment]
Resolved in #2248
