### ISSUE TITLE
Stress test with multiple users

### ISSUE THREAD

**Issue by maxpanakov** [medusajs/medusa#1923]
### Describe the bug

We tested a scenario where several users want to buy products. For this test we use medusa from develop branch with transaction fix.
But we still have and error with transactions.

### System information

Medusa version (including plugins):develop
Node.js version: 16.15.0
Database: postgres
Operating system: ubuntu 20

### Steps to reproduce the behavior

1. Install k6
2. setup  code below
3.  run it 

### Code snippets

import http from 'k6/http';
import { sleep, check } from 'k6';

/* export const options = {
  stages: [
    { duration: '1m', target: 1 },
     { duration: '1m30s', target: 10 },
    { duration: '20s', target: 0 }, 
  ],
};*/
export const options = {
  vus: 3,
  duration: '10s',
};

const updateCart = {
  "shipping_address": {
    "first_name": "test",
    "last_name": "test",
    "address_1": "test",
    "address_2": "2/4",
    "country_code": "id",
    "postal_code": "123123",
    "city": "Test",
    "phone": "88888888888"
  },
  "billing_address": {
    "first_name": "test",
    "last_name": "test",
    "address_1": "test",
    "address_2": "2/4",
    "country_code": "id",
    "postal_code": "123123",
    "city": "Test",
    "phone": "88888888888"
  },

  "email": "test@gmail.com"
}
const host = 'http://localhost:9000/'
const params = {
  headers: {
    'Content-Type': 'application/json'
  }
}
export default function () {
  sleep(Math.floor(Math.random() * 10))

  let res = http.post(host + 'store/carts', JSON.stringify({
    "region_id": "reg_01G5K9N9GWWPWHPKC8HCVQK4Z3",
    "items": [
      {
        "variant_id": "variant_01G5K9NC8E31TX4Y8DX1VXA1XM",
        "quantity": 1
      }
    ]
  }), params);
  // Verify response
  check(res, {
    'status is 200': (r) => r.status === 200,
  });
  console.log(res.json().cart.id);

  sleep(Math.floor(Math.random() * 10))

  const cartId = res.json().cart.id
  res = http.post(host + 'store/carts/' + cartId, JSON.stringify(updateCart), params);
  check(res, {
    'status is 200': (r) => r.status === 200,
  });

  sleep(Math.floor(Math.random() * 10))
  res = http.post(host + 'store/carts/' + cartId + '/payment-sessions');
  check(res, {
    'status is 200': (r) => r.status === 200,
  });

  sleep(Math.floor(Math.random() * 10))
  res = http.post(host + 'store/carts/' + cartId + '/payment-session', JSON.stringify({
    "provider_id": "manual"
  }), params);

  check(res, {
    'status is 200': (r) => r.status === 200,
  });

  sleep(Math.floor(Math.random() * 10))
  res = http.post(host + 'store/carts/' + cartId + '/complete',);
  check(res, {
    'status is 200': (r) => r.status === 200,
  });
}

**Comment by adrien2p** [comment]
The transaction fixes are not in develop they are here #1853 #1855 #1858

**Comment by olivermrbl** [comment]
Fixed in #1853, #1855, #1858. Let us know if the issue persists
