### ISSUE TITLE
 Getting a 404 response when using the payment methods `list` method for the Node JS client

### ISSUE THREAD

**Issue by jaredhill4** [medusajs/medusa#1933]
### Describe the bug

This seems to be because the `customers.paymentMethods.list()` method apparently points to incorrect endpoint.

Currently, it is pointing to `/store/carts/${id}/payment-methods`.

The bug is on this particular line:

https://github.com/medusajs/medusa/blob/2eb2126fe348565721e05e6f0da01c46bad6185a/packages/medusa-js/src/resources/payment-methods.ts#L13

### System information

Medusa version (including plugins): latest

### Expected behavior

Per the API docs, the payment methods `list` method should make a `GET` request to `/store/customers/me/payment-methods`.

**Comment by olivermrbl** [comment]
Nice catch @jaredhill4 - thanks! 

Fixed in #1934

**Comment by jaredhill4** [comment]
> Nice catch @jaredhill4 - thanks!
> 
> Fixed in #1934

Thanks, @olivermrbl!!!
