### ISSUE TITLE
/store/carts 404 (Not Found)

### ISSUE THREAD

**Issue by itailulu** [medusajs/medusa#1964]
### Describe the bug

I followed instructions on the quick-start guide, and installed the Next.js starter.
When loading the frontend i'm getting an error `Unhandled Runtime Error - Error: Request failed with status code 404` and collections and products are not shown.
It seems that the source for this error is the `/store/carts` endpoint returning 404.
I can confirm that other endpoints does work correctly when called from the frontend (products, collections, regions, etc)

### System information

Medusa version (including plugins): 1.3.1
Node.js version: v14.17.6
Database: SQLite
Operating system: Mac Mojave 10.14.6
Browser (if relevant): Chrome 103.0.5060.134

**Comment by olivermrbl** [comment]
Could it be that you've worked with a different Medusa starter before? If so, it might have to do with your browser cache. Can I get you to clear it out and refresh?

Otherwise, we might need @kasperkristensen to have a look at it 👍

**Comment by itailulu** [comment]
You're right! that was it.
Unfortunately now i'm getting 404 on the products endpoint :(

**Comment by olivermrbl** [comment]
> It seems that the cart_id query param is causing this error.

Not sure why you are using a `cart_id` query param for the products endpoints. What made you do that?

**Comment by olivermrbl** [comment]
Closing for now as the original issue has been resolved

**Comment by itailulu** [comment]
I'm not using it, it's added automatically. I quote what I saw in the
devtools network pane.

**Comment by olivermrbl** [comment]
Can I get you to send a screenshot of the request as seen in the network tab?

**Comment by kasperkristensen** [comment]
@olivermrbl  the `cart_id` is added to the request as it is needed to get any discount prices that are relevant for the cart, whether those be region or customer-specific 😄 

@itailulu Please provide the error from your network tab as Oli mentions, it will make it easier to debug. Oen thing I might suggest is to try and delete the cart and region ids stored in localstorage and refresh your page. 

You should also change your DB from SQLite to Postgres as the Next starter will not function when using SQLite, as it is limited to a singe write at the time which will cause issues. 😄

**Comment by olivermrbl** [comment]
> the cart_id is added to the request as it is needed to get any discount prices that are relevant for the cart

Ah obviously! Thanks for reminding me @kasperkristensen and sorry for the confusion @itailulu
