### ISSUE TITLE
DigitalOcean deployment

### ISSUE THREAD

**Issue by marcinliwen** [medusajs/medusa#1973]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Missing package.json file configuration in DigitalOcean deployment instruction. 

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by olivermrbl** [comment]
Can I get you to elaborate on the issue @marcinliwen? I am not sure what missing file configuration you are referring to.

Do you have an idea @shahednasser ?

**Comment by marcinliwen** [comment]
@olivermrbl on this instruction https://docs.medusajs.com/deployments/server/deploying-on-digital-ocean there is no info about changing package.json before deployment. I remember that there was necessary to change "scripts" for "start" and migration event.

**Comment by shahednasser** [comment]
@olivermrbl basically a step similar to this one in the Heroku deployment documentation:

https://docs.medusajs.com/deployments/server/deploying-on-heroku#packagejson

We need to add that the `start` script should include `medusa migrations run`
