### ISSUE TITLE
Docs: fix Next.js link in S3 plugin documentation

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#1977]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In the [S3 Plugin documentation](https://docs.medusajs.com/add-plugins/s3#nextjs-storefront-configuration), the following text can be seen in the "Next.js Storefront Configuration" section:

```
If you’re using a **[Next.js](/starters/nextjs-medusa-starter** storefront,...
```

### How can this issue be resolved?

The bold part above must be fixed to be a link to [this page](https://docs.medusajs.com/starters/nextjs-medusa-starter). However, it should be done using [Markdown links as explained in Docusaurus's documentation](https://docusaurus.io/docs/markdown-features/links).

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by sabakhilji** [comment]
Hi, can I do this?

**Comment by shahednasser** [comment]
Sure I've assigned you 🙂

**Comment by yasier-ansari** [comment]
hello there, this bug is still up ? mind if i work on it ?
