### ISSUE TITLE
withTransaction for payment provider

### ISSUE THREAD

**Issue by maxpanakov** [medusajs/medusa#1981]
**Is your feature request related to a problem? Please describe.**
We have a custom payment provider where we call two methods cartService_.update and cartService_.retrieve without transaction. So i added manager and it's start work with more users at the same time  

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/9987863/182585063-db17e15c-430d-4f61-b874-31d5351ad984.png)
![image](https://user-images.githubusercontent.com/9987863/182585428-474c844c-0bcd-40f3-8ea6-b85685ab2b1e.png)

**Comment by adrien2p** [comment]
it is part of the suite of pr related to https://github.com/medusajs/medusa/pull/1773/files which will allow to extends directly the new Abstract class to directly have access to all of it.

then your provider will be called with the transaction and you will be able to remove the setTransaction method.
