### ISSUE TITLE
error `parse` is not defined in medusa-file-minio plugin

### ISSUE THREAD

**Issue by ancs21** [medusajs/medusa#1990]
## Bug report
error:   parse is not defined in medusa-file-minio plugin

### Describe the bug

```
error:   parse is not defined
ReferenceError: parse is not defined
```

### System information

Medusa version (including plugins):
Node.js version: 18
Database: postgres
Operating system: Windows
Browser (if relevant): Chrome

## Propose solution

Just import `parse` from 'path'

```
import { parse } from "path"
```

**Comment by olivermrbl** [comment]
@pKorsholm Did you ever stumble upon this one while testing?

**Comment by pKorsholm** [comment]
I dont recall getting this error when updating, but yeah, we should add the import for it to work
