### ISSUE TITLE
Product Service

### ISSUE THREAD

**Issue by srindom** [medusajs/medusa#2]
Product Service manages products and to a certain extent product variants through the product variant service.

The product must be able to:

- [x] Create a product
- [x] Update a product
- [x] Retrieve a product
- [x] Delete a product
- [x] Add a product variant
- [x] Change order of product variants
- [x] Remove a product variant
- [ ] Add product images
- [ ] Change order of product images
- [ ] Remove Product images
- [ ] List products depending on different queries
- [x] Decorate products
- [x] Add option to product
- [x] Delete option from product
- [x] Update option title and order

**Comment by olivermrbl** [comment]
Closing this. Remaining functionality is referenced in #31 and #3.
