### ISSUE TITLE
Can't login to admin panel

### ISSUE THREAD

**Issue by import-brain** [medusajs/medusa#2008]
Hi, I setup the storefront, backend, and admin panels using the "quick deploy" buttons on the documentation. I made sure to set the CORS environment variables on the backend and run the `medusa user -e some@email.com -p some-password` command on the server, but I'm getting "These credentials do not match our records" whenever I try to login to the admin panel, with the following 401 errors:
<img width="636" alt="Screenshot 2022-08-07 at 7 54 03 PM" src="https://user-images.githubusercontent.com/68196762/183316182-4601a0a5-4572-45fd-a2fd-ed2cea6b436c.png">

I tried running the `medusa user` command again, but it said that the user with the email I provided was already present in the database, so it's not a database issue.

**Comment by olivermrbl** [comment]
Can I get you to include a screenshot of your network tab?

**Comment by chemicalkosek** [comment]
@import-brain Even though your backend domain is cut out I can see that its domain is probably `herokuapp.com`. This domain is on the public suffix list and those domains can't set cookies. Make sure to attach your own domain to your medusa backend. Also make sure you're running your backend with SSL (https://)

**Comment by import-brain** [comment]
> @import-brain Even though your backend domain is cut out I can see that it is probably `herokuapp.com`. This domain is on the public suffix list and those domains can't set cookies. Make sure to attach your own domain to your medusa backend. Also make sure you're running your backend with SSL (https://). I would do the same for your admin site.

Oh, I have to attach my own domain first? I'll get that setup and get back to you with the results.

**Comment by import-brain** [comment]
> Can I get you to include a screenshot of your network tab?
<img width="653" alt="Screenshot 2022-08-08 at 6 32 13 PM" src="https://user-images.githubusercontent.com/68196762/183525841-eade1dbe-e31d-4a42-8a39-1e174b2e58e4.png">

**Comment by olivermrbl** [comment]
It is highly likely what @chemicalkosek highlighted is the culprit.

**Comment by import-brain** [comment]
@olivermrbl @chemicalkosek Thank you both for all your help! Fixing the `herokuapp` issue by putting a custom domain fixed the issue.

**Comment by arndom** [comment]
@chemicalkosek  sorry to ping you this way, but could the same thing be happening with `microtica`, login works but i'm still unauthorised so I can access the panel. Do I also need a custom domain?

<img width="517" alt="image" src="https://github.com/medusajs/medusa/assets/40564798/965daa47-3f9d-41b9-b8a2-44e950f399b2">

**Comment by chemicalkosek** [comment]
I don't know how `microtica` works but yes, you'll probably need a custom domain.

You can check if your domain is on the public suffix list: https://publicsuffix.org/list/

**Comment by arndom** [comment]
yh it is on the list, a custom domain should solve it, thanks 👍

**Comment by jeevsssss** [comment]
On deploying it , the Admin page keeps giving auth error, on exploring network tab , it's found the Admin is sending the credentials to localhost but not the defined url . 

Even  I have defined in env file and config file but still it's sending to localhost and results in login failure
