### ISSUE TITLE
cannot create product without profile_id via the product service

### ISSUE THREAD

**Issue by richardwardza** [medusajs/medusa#2034]
### Describe the bug

When trying to create a product using the [ProductService.create](https://github.com/medusajs/medusa/blob/0703dd94e88be47fdc61c1caa451c050fbabbef3/packages/medusa/src/services/product.ts#L346) method and not specifying a [profile_id](https://github.com/medusajs/medusa/blob/0703dd94e88be47fdc61c1caa451c050fbabbef3/packages/medusa/src/types/product.ts#L140) (it's optional) then the creation fails with the message: `failed: null value in column "profile_id" violates not-null constraint`

The API `POST /products` is different, it first [retrieves a shipping profile](https://github.com/medusajs/medusa/blob/0703dd94e88be47fdc61c1caa451c050fbabbef3/packages/medusa/src/api/routes/admin/products/create-product.ts#L282) and uses that `id` [in the creation of the product](https://github.com/medusajs/medusa/blob/0703dd94e88be47fdc61c1caa451c050fbabbef3/packages/medusa/src/api/routes/admin/products/create-product.ts#L294)

The other issue is this is not picked up in any of the tests as they use mocks of services and there are no "end to end" service tests.

### System information

Medusa version (including plugins): 1.3.5
Node.js version: v16.15.1
Database: postgres
Operating system: mac
Browser (if relevant):

### Steps to reproduce the behavior

run this "somewhere" - a plugin loader/index is an easy place.
```
const productService: ProductService = container.resolve("productService");
await productService.create({ title: "a product" });
// fails with: failed: null value in column "profile_id" violates not-null constraint
```

### Expected behavior

I would think that it would be best to update the service to retrieve the `profile_id` (similar to the API endpoint) if it is not supplied.

Updating the `profile_id` to be mandatory would be a breaking change to that interface and would require anyone else using it to update their code.

### Code snippets

```
const productService: ProductService = container.resolve("productService");
await productService.create({ title: "a product" });
// fails with: failed: null value in column "profile_id" violates not-null constraint
```

### Additional context

nothing

**Comment by richardwardza** [comment]
I'm happy to do some work on this if needed..

**Comment by richardwardza** [comment]
Doing the shippingProfile lookup in the service [is not the correct way to go](https://github.com/medusajs/medusa/pull/2043#pullrequestreview-1072110248) so re-doing this by making the `profile_id` mandatory and seeing where that takes me.

**Comment by chiubaca** [comment]
Running into this right now... Is there a workaround in the meantime?
