### ISSUE TITLE
Demo store not fetching any items

### ISSUE THREAD

**Issue by salmanshahid7** [medusajs/medusa#2035]
## Bug report
CORs is blocking access to APIs so unable to fetch any data.
### Describe the bug

Access to XMLHttpRequest at 'https://api-demo.medusa-commerce.com/admin/users' from origin 'https://demo.medusajs.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### System information

Medusa version (including plugins):
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by richardwardza** [comment]
Hi @salmanshahid7  - have you done the steps n the docs:
https://docs.medusajs.com/usage/configurations#admin-cors
and
https://docs.medusajs.com/usage/configurations#storefront-cors

do they help?

**Comment by salmanshahid7** [comment]
I'm talking about your store demo. That should be working out of the box.

https://demo.medusajs.com/
Sorry if that wasn't clear

Thanks,
Salman

**Comment by olivermrbl** [comment]
Thanks for reporting it in. Issue has been resolved :)
