### ISSUE TITLE
Storefront REST APIs url

### ISSUE THREAD

**Issue by zul-m** [medusajs/medusa#2041]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The link to the `Storefront REST APIs` on the Overview docs seems to be broken.

![image](https://user-images.githubusercontent.com/39239497/184522430-dd83a67b-0435-47fb-bd0c-16076c2eb82d.png)

![image](https://user-images.githubusercontent.com/39239497/184522379-de773319-04ac-4512-97ac-d03ac0d880d4.png)

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch, thank you for reporting the issue!

**Comment by Himanxu1** [comment]
I want to work on this issue .Please Assign this to me @zul-m

**Comment by zul-m** [comment]
Hey @Himanxu1. Unfortunately, I'm not [part of the "Write access team", or the "Owners team"](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization). Maybe @shahednasser can help.

**Comment by shahednasser** [comment]
@Himanxu1 sure I've assigned you

**Comment by Himanxu1** [comment]
Where did i find the url

**Comment by Himanxu1** [comment]
I have found that this url is broken : (https://docs.medusajs.com/api/store/collection). 
Which url is suppose to be here ?

**Comment by shahednasser** [comment]
@Himanxu1 it should be https://docs.medusajs.com/api/store

**Comment by shahednasser** [comment]
Resolved in #2063
