### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by Boumour** [medusajs/medusa#2053]
wait  - compiling...
event - compiled client and server successfully in 457 ms (1516 modules)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
wait  - compiling /products/[handle] (client and server)...
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
event - compiled client and server successfully in 217 ms (1673 modules)
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 109 ms (1673 modules)
error - Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:220:20) {
  type: 'Error',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    transformRequest: [ null ],
    transformResponse: [ null ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    headers: {
      Accept: 'application/json',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/0.24.0'
    },
    baseURL: 'http://localhost:9000',
    raxConfig: {
      retry: 3,
      backoffType: 'exponential',
      currentRetryAttempt: 3,
      retryDelay: 100,
      httpMethodsToRetry: [Array],
      noResponseRetries: 2,
      checkRetryAfter: true,
      maxRetryAfter: 300000,
      statusCodesToRetry: [Array]
    },
    method: 'get',
    withCredentials: true,
    url: '/store/products?limit=25',
    json: true
  },
  code: 'ECONNRESET',
  status: null,
  page: '/products/[handle]'
}

**Comment by olivermrbl** [comment]
Please use our bug template when opening up an issue. We do not have enough information to properly problem solve on this one.

**Comment by olivermrbl** [comment]
Closing until additional details have been provided

**Comment by kasperkristensen** [comment]
@Boumour Just gonna throw this in here, as I can see you are having an issue with the connection between the Next starter and server resetting. You most likely have some process running on port 9000 other than Medusa, could be something like `PHP-FPM` or something else that runs in the background on localhost port 9000. Either kill all processes on port 9000 and restart your Medusa server, or change the port of your Medusa server to something else like `localhost:9001` and then update `NEXT_PUBLIC_MEDUSA_BACKEND_URL` in your Next starter environment variables to reflect this change.

**Comment by Boumour** [comment]
@kasperkristensen the problem is not the port 9000 for example home page is working fine and fetching the products but the product page when you access to it you got this error  TCP.onStreamRead (node:internal/stream_base_commons:220:20 on the browser also just to let you know the api service works fine on the server side but the nextjs you got the problem of ECONNRESET

**Comment by Boumour** [comment]
<img width="1071" alt="Screenshot 2022-08-17 at 21 26 35" src="https://user-images.githubusercontent.com/29060844/185236730-983e7489-fd5b-4733-8290-4f155d52dca1.png">

**Comment by Boumour** [comment]
<img width="985" alt="Screenshot 2022-08-17 at 21 32 08" src="https://user-images.githubusercontent.com/29060844/185237661-ff98c525-f242-4bf8-9c5e-1e9b564295a0.png">
<img width="838" alt="Screenshot 2022-08-17 at 21 30 54" src="https://user-images.githubusercontent.com/29060844/185237699-d28762c0-cf14-4e39-904a-295da91d616b.png">
<img width="1261" alt="Screenshot 2022-08-17 at 21 29 39" src="https://user-images.githubusercontent.com/29060844/185237792-baff0a38-00a6-45ab-96e6-2ebcf10ffaff.png">
<img width="1276" alt="Screenshot 2022-08-17 at 21 29 27" src="https://user-images.githubusercontent.com/29060844/185237863-7e76f2f2-0e50-4ad2-8b24-9c7c34b56457.png">
<img width="1264" alt="Screenshot 2022-08-17 at 21 29 08" src="https://user-images.githubusercontent.com/29060844/185237890-2241a8d6-c5eb-4563-9e58-9f9283e87011.png">

**Comment by kasperkristensen** [comment]
@Boumour  Have you tried killing everything on port 9000? I just asking because every time someone has brought up this issue, it was due to them running two things on port 9000 simultaneously.  And they had the exact same issue with the `getStaticProps` on the product page failing with ECONNRESET because it's a larger/longer build step which results in more easily being reset due to other things running on the port.

**Comment by jeyip** [comment]
Just wanted to chime in and confirm what @kasperkristensen said, at least for my case. I was seeing similar ECONNRESET issues, and it turns out that `PHP-FPM` was running on port 9000 on my machine. Once I switched Medusa to port 9001, everything resolved 👍
