### ISSUE TITLE
Multilanguage

### ISSUE THREAD

**Issue by markus-gx** [medusajs/medusa#2055]
**Is your feature request related to a problem? Please describe.**
If I would setup a medusa store for local clients e.g in Austria it would be possible that someone does not know English as well as his/her native language German. 

**Describe the solution you'd like**
A language switch in the admin panel and maybe a default lang setting (.env) when initially setting up the admin panel. 
For future contributors, every language outsourced in a file.

**Comment by Keith-Hon** [comment]
Is it possible to have localized names for each product? And the shoppers could switch the site's language

**Comment by yaariyuval** [comment]
I'm also interested in localized names and description for products.
Thanks!

**Comment by schoening** [comment]
I'm literally unable to use MedusaJS because I need multi language support. If anyone would like to point me in the direction of how I can fix this myself / and or contribute this feature to Medusa I would appreciate it!

I think it's important to have a planned out how this feature is supposed to work rather than implementing it haphazardly.

Could we start a dialogue on this perhaps?

**Comment by olivermrbl** [comment]
@markus-gx @Keith-Hon @yaariyuval @schoening Your feedback is highly appreciated. Supporting multiple locales natively in Medusa has been discussed previously but was put on hold as we prioritized other, to us, more impactful features. And really, the same goes for now. We've already planned a tentative roadmap for Q4, and multi-language support is unfortunately not part of it. 

Though, one approach you should consider is to connect a CMS to Medusa (e.g. our Contentful plugin), that allows you to configure multiple locales for all the content. We've helped several large-scale merchants with such a setup, which has worked out quite successfully. 

That being said, we'd love to plan out native support with you (+ community) and assist in the implementation process as much as possible. To kick things off, it would be great to know your exact requirements for the feature and a couple of comments on how you imagine the setup would play out; configurable in admin, configurable in `medusa-config.js` or a third option.

Finally, I think it's worth mentioning that we are currently scoping an extensible Entity API allowing you to add custom attributes to resources in Medusa starting with Product as it is the most obvious one. This feature should give you a set of tools to achieve multi-language content, but it might not be a super intuitive developer experience from a frontend perspective. 

Looking forward to hearing from you!

**Comment by markus-gx** [comment]
The initial requirement for the feature was for the admin panel. Integrating react-i18n or whatever its called in GatsbyJS. I would have done it myself but unfortunately I am coming from Nuxt/VueJS.

So it should be quite simple to add locale files and a lang-switch in the Admin Panel. 
The rest like product translations etc can be easily managed via CMS as @olivermrbl already mentioned.

**Comment by schoening** [comment]
@olivermrbl I would like to know how you solved it for your clients. Do they have to maintain both the medusa admin items and a seperate cms where they have translations for the products?

**Comment by flashjames** [comment]
@olivermrbl how would you recommend about implementing localization right now?

I'll be building a beauty store on medusa and right now I'm figuring out how to do localization - and I could use some guidance
I figured I can write a blog post on this for you, since I'm solving it for myself. But I have some questions how to do it right
I found an issue here about it (: https://github.com/medusajs/medusa/issues/2055) that you helped some clients use strapi, but no guidance how you recommended to do it.
when working with strapi I got stuck here: https://github.com/strapi/strapi/issues/12538

Right now I figured I'd just add a field on Product with https://adrien2p.github.io/medusa-extender
Like title_hr

**Comment by srindom** [comment]
@markus-gx - We are moving feature requests to GitHub Discussions to keep better track of the most requested features (using the upvote mechanism) and streamline GitHub Issues around bugs. Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!

**Comment by spacewalkingninja** [comment]
> @markus-gx @Keith-Hon @yaariyuval @schoening
> 
> Your feedback is highly appreciated. Supporting multiple locales natively in Medusa has been discussed previously but was put on hold as we prioritized other, to us, more impactful features. And really, the same goes for now. We've already planned a tentative roadmap for Q4, and multi-language support is unfortunately not part of it.
> 
> Though, one approach you should consider is to connect a CMS to Medusa (e.g. our Contentful plugin), that allows you to configure multiple locales for all the content. We've helped several large-scale merchants with such a setup, which has worked out quite successfully. Check out some of our setup guides [here](https://docs.medusajs.com/add-plugins/contentful/).
> 
> That being said, we'd love to plan out native support with you (+ community) and assist in the implementation process as much as possible. To kick things off, it would be great to know your exact requirements for the feature and a couple of comments on how you imagine the setup would play out; configurable in admin, configurable in `medusa-config.js` or a third option.
> 
> Finally, I think it's worth mentioning that we are currently scoping an extensible Entity API allowing you to add custom attributes to resources in Medusa starting with Product as it is the most obvious one. This feature should give you a set of tools to achieve multi-language content, but it might not be a super intuitive developer experience from a frontend perspective.
> 
> Looking forward to hearing from you!

HELLO!!!!
EXACT REQUIREMENTS>

1> Multiple language titles and descriptions
2>Change languagr from the front UI
3 Implement now!
