### ISSUE TITLE
Record in line_item table will dulicate from cart when complete cart

### ISSUE THREAD

**Issue by BerlitzPlatina** [medusajs/medusa#2061]
### Describe the bug
When complete a cart, item in cart will duplicate, in order table will make 2 order, once order relation item in cart and once order relation item make from duplicate

### System information

Medusa version (including plugins): 1.3.2
Node.js version: 16
Database: postgres
### Steps to reproduce the behavior
**1. Set payment session**
/store/carts/:id/payment-sessions
**2. Update payment session**
store/carts/:id/payment-sessions/:provider_id
body:
{
    "data": {
        "token": "c913b9f41c7e384d1cce610e22d34e3d80cd9ad8feb2004c218a76bfc165960d"
    }
}
**3. Complete cart**
store/carts/:id/complete
### Screenshots
![image](https://user-images.githubusercontent.com/25698926/185527228-87128e53-09b6-4014-bdb8-9b99037b197c.png)

**Comment by BerlitzPlatina** [comment]
> Can I get you to include the type of storefront you are using and the entire flow of events. The reproducible steps are insufficient as they don't include information on what items are added to the cart before completion.

type of storefront, i use gasby
actually, my cart be configured for duplicate product variant in once cart 
maybe due to my editing

**Comment by olivermrbl** [comment]
Can I get you to provide the exact steps leading to the issue? We still do not have enough information to debug

**Comment by BerlitzPlatina** [comment]
1. I set payment session for cart, i use router /store/carts/:id/payment-sessions
2. i update a payment session with router /store/carts/{id}/payment-sessions/{provider_id}, i use gmo payment
3. i complete cart with router store/carts/{id}/complete
[gmo-provider.zip](https://github.com/medusajs/medusa/files/9390998/gmo-provider.zip)
here my gmo provider

**Comment by BerlitzPlatina** [comment]
i checked and found out due to my code, i use code example from medusa extender
