### ISSUE TITLE
Unable to access `req.body` in custom endpoints

### ISSUE THREAD

**Issue by troykelly** [medusajs/medusa#2064]
### Describe the bug

`req.body` is `undefined` in custom endpoints.

### System information

Medusa version (including plugins): v1.3.5
Node.js version: v18.4.0
Database: Postgres
Operating system: macOS
Browser (if relevant):

### Steps to reproduce the behavior

1. Create an endpoint in `/src/api` that accepts `POST`
2. Send a `POST` to the endpoint with `application/json` content type and JSON in the body
4. `console.log(req.body)` in the processor
6. Be devastated when you see the word `undefined` in your log instead of an Object

### Expected behavior

`req.body` should have the body of the request.

### Code snippets

```typescript
export default async (req, res) => {
    console.log(req.body);

    const validated = await validator(AdminPostDistributorsReq, req.body)

    const distributorService: DistributorService = req.scope.resolve("distributorService")
    const manager: EntityManager = req.scope.resolve("manager")
    const result: Distributor = await manager.transaction(
        async (transactionManager) => {
            return await distributorService
                .withTransaction(transactionManager)
                .create(validated)
        }
    )

    const distributor: Distributor = await distributorService.retrieve(result.id, {
        select: defaultAdminDistributorFields,
        relations: defaultAdminDistributorRelations,
    })

    res.status(200).json({ distributor })
}
```

**Comment by olivermrbl** [comment]
Could it be that you are missing to add `bodyParser.json()` as middleware?

**Comment by troykelly** [comment]
> Could it be that you are missing to add bodyParser.json() as middleware?

I'd almost guarantee it is - apologies. I had assumed that the additional endpoints were later in the chain - and I didn't want to add any parsing to the `app` for fear of breaking the core medusa processor.

I'm assuming I should add it at the start of my processing?

**Comment by olivermrbl** [comment]
Great!

>  I'm still terrified I will break the core app processing.
How come? Anything specific that you are fearing could cause issues? Looking at the code snippet attached, it seems you are following the right pattern, so I don't think you should worry too much
