### ISSUE TITLE
Remove unused QueryBuilderService

### ISSUE THREAD

**Issue by olivermrbl** [medusajs/medusa#2068]
**What**
Remove QueryBuilderService as it is no longer used. 

The following files should be deleted:
- `medusa/src/services/query-builder.js`
- `medusa/src/services/__mocks__/query-builder.js`

Additionally, the export from `medusa/src/services/index.ts` should be removed.

**Comment by sarthakw7** [comment]
Hey, I like to work on this issue.

**Comment by olivermrbl** [comment]
Closed #2104
