### ISSUE TITLE
Docs: fix all links pointing to the API reference

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#2073]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Following our latest refactoring of the API reference, a bunch of links throughout the documentation must be fixed to point to the new API reference.

### How can this issue be resolved?

1. Find all occurrences of `https://docs.medusajs.com/api` under `docs/content`.
2. if the URL is old and does not work, replace it with the new working URL.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by Cwix** [comment]
@shahednasser Want me to go over these while I'm here?

**Comment by shahednasser** [comment]
Sure @Cwix 😄
