### ISSUE TITLE
Main Readme.md does not produce a valid build

### ISSUE THREAD

**Issue by lack-of-gravitas** [medusajs/medusa#2088]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Following the main readme for this repo does not produce a working build. Visiting localhost:9000 produces the below error.

Steps followed- 
![image](https://user-images.githubusercontent.com/10094964/186403625-709fd3c7-fe7a-4f87-b1cd-cb42e58b6b79.png)
![image](https://user-images.githubusercontent.com/10094964/186403698-482e3e74-cb25-4a20-a881-d1bdd1792647.png)

### How can this issue be resolved?

1. Update documentation to be correct.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by olivermrbl** [comment]
Everything seems to be working as expected. You are requesting a non-existing route. Try `http://localhost:9000/health` :)

**Comment by srindom** [comment]
What you see is not an error - there simply isn't any handler registered at the root. You might be looking for:
- Medusa Admin; which you have to install separately -> https://github.com/medusajs/admin
- The storefront API which will in your case be found at http://localhost:9000/store/products ([See storefront reference](https://docs.medusajs.com/api/store/))
- The admin API ([See admn reference](https://docs.medusajs.com/api/admin/))

**Comment by lack-of-gravitas** [comment]
Ok thanks for that -- apologies for the newbie question... been flip flopping between medusa and saleor trying to get something to work and deploy (without sucess so far)./

**Comment by olivermrbl** [comment]
Let us know if we can be of any assistance @lack-of-gravitas :)
