### ISSUE TITLE
Medusa Plugins Documentation

### ISSUE THREAD

**Issue by lack-of-gravitas** [medusajs/medusa#2090]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Attempting to add [medusa](https://github.com/medusajs/medusa)/[packages](https://github.com/medusajs/medusa/tree/master/packages)/medusa-plugin-discount-generator/ to my vanilla install of medusa.

I've got medusa server and medusa admin UI running and have added the above package via yarn (and updated medusa-config js). 

Is there documentation on this plugin and how to expose it via the Admin UI -- or am I expected to understand and expose this functionality by trawling through the package code?

This applies to the other lightly / undocumented plugins -- e.g. sendgrid / mailchimp which appear to do "nothing" on the Admin UI frontend.

### How can this issue be resolved?

Provide documentation for medusa plugins and exposing via Admin UI (where applicable).

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by olivermrbl** [comment]
Just to be sure, you are looking for improved documentation around the plugin right? You did get it up and running with issues

**Comment by kaushalyap** [comment]
Can anyone share what `medusa-plugin-discount-generator` plugin does at high level?

**Comment by Edybee** [comment]
Hi, I can only create documentation on Medusa plugins, but I can't expose them via admin UI. Should I still proceed with the issue?
