### ISSUE TITLE
Throws error at reload when editing code

### ISSUE THREAD

**Issue by HarunKilic** [medusajs/medusa#2098]
### Describe the bug
When developing using `medusa develop`, and editing some code, it throws an error that says the port is already in use. 
The server instance is not closed correctly.

### System information

Medusa version (including plugins): 1.3.5
Node.js version: v16.17.0
Database: PostgreSQL
Operating system: Windows 10 / Windows 11 (Tried on two different PC's)
Browser (if relevant):

### Steps to reproduce the behavior

1. Start a new project using `medusa new ...`
2. Start backend (default environments is enough)
3. Add a custom endpoint
4. Error?

### Expected behavior
The server should restart with same port. 

### Screenshots
![medusa-error](https://user-images.githubusercontent.com/13366825/186694214-2b677cf1-7ff5-4ac4-91cb-46e1038f9f6b.png)

**Comment by carlos-r-l-rodrigues** [comment]
https://github.com/medusajs/medusa/pull/2105

The fix will be available on the next release.

**Comment by HarunKilic** [comment]
> https://github.com/medusajs/medusa/pull/2105
> 
> The fix will be available in the next release.

Glad to hear! :)

**Comment by carlos-r-l-rodrigues** [comment]
Fix in the release [1.3.7](https://github.com/medusajs/medusa/releases/tag/%40medusajs%2Fmedusa%401.3.7)
