### ISSUE TITLE
Cannot create variants when creating new product

### ISSUE THREAD

**Issue by g666nz** [medusajs/medusa#2115]
### Describe the bug
When trying to create variants on creating a new problem when i try to save the new variants i get an error saying "Title must be string".

I make the title "Size" and in the tags add 5ltr, 10ltr

### System information

Medusa version (including plugins): 1.3.5
Node.js version: 14.19.3
Database: Postgresql
Operating system: linux ubuntu 22
Browser (if relevant): Google chrome

### Steps to reproduce the behavior

1. Go to create product in product page
2. Fill in required details and then select Product with variants
3. In the variant section select +add option
4. In the option title input size
5. In the tags add 5ltr, 10ltr
6. Click save as draft on the bottom right of the screen

### Expected behavior

I expect the variants to be saved instead i get an error saying "Medusaerror: title must be a string, title must be a string"

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

error:   title must be a string, title must be a string
MedusaError: title must be a string, title must be a string
    at /home/g666nz/Desktop/aeroponix.in/server/node_modules/@medusajs/medusa/dist/utils/validator.js:127:31
    at step (/home/g666nz/Desktop/aeroponix.in/server/node_modules/@medusajs/medusa/dist/utils/validator.js:44:23)
    at Object.next (/home/g666nz/Desktop/aeroponix.in/server/node_modules/@medusajs/medusa/dist/utils/validator.js:25:53)
    at fulfilled (/home/g666nz/Desktop/aeroponix.in/server/node_modules/@medusajs/medusa/dist/utils/validator.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid_data',
  code: undefined,
  date: 2022-08-28T14:04:18.282Z

### Additional context

Add any other context about the problem here

**Comment by olivermrbl** [comment]
It sounds like you might be missing to fill out the titles of the created variants. See image below:
![Screenshot 2022-08-29 at 09 47 44](https://user-images.githubusercontent.com/59018053/187151296-d0948d4d-9cfd-4b5a-bd70-bfa80933281d.png)

We are soon to release a revamped version of this page, that will include more appropriate error handling

**Comment by g666nz** [comment]
ahhhh, sorry the area wasn't highlighted or had any placeholders didn't know those were input fields. Thank you for the help.
