### ISSUE TITLE
Wishlist missed on product page after refresh

### ISSUE THREAD

**Issue by Wooody82** [medusajs/medusa#2144]
Hi,
I have tried to implement the Wishlist and all seems working fine.  So if we click to add product to wishlist works fine.. then view product the icon is filled.. but If we refresh product page the heart not filled.
Its something with setState I think.. I am trying to fix it....
I followed this post:
https://medusajs.com/blog/how-to-create-a-wishlist-with-medusa

Any idea..

**Comment by Wooody82** [comment]
Hi @olivermrbl 
Thanks for answer, I think I fixed it already. The code related to Wishlist in /frontend/src/templates/product.js
```
  useEffect(() => {
    if (region && region.id !== regionId) {
      navigate(`/${toKebab(region.name)}/${handle}`)
    }
    if(wishlist.items.length > 0){
      var found = wishlist.items.some(i =>i.product_id === product.id)
      if( found ){
        setOnWishlist(true)
      }
    }
  }, [region, handle, regionId, wishlist])
```

**Comment by olivermrbl** [comment]
That's great! Thanks for letting me know :)
