### ISSUE TITLE
Docs: remove the "Prerequisite Background Knowledge" in "Set up your development environment"

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#2145]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The "[Set up your development environment](https://docs.medusajs.com/tutorial/set-up-your-development-environment)" documentation should focus just on the tools that need to be installed.

Furthermore, the tools to be installed should be split to "required" and "optional"

### How can this issue be resolved?

1. Remove the "Prerequisite Background Knowledge" section
2. Change the "Installations" section to the following:
    - Create a "Required Tools" section and move the sections for "Node.js", "Git", and "Medusa CLI" below it.
    - Create a "Optional Tools" section and move the sections "PostgreSQL" and "Redis" below it.
    - Remove "Code Editor" section

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by RAY-EZ** [comment]
I would like to edit to fix the issue. Can you assign it to me.

**Comment by shahednasser** [comment]
Sure I've assigned you!
