### ISSUE TITLE
Docs: add links in the Shipping Architecture Overview documentation to the entities in the Entities Reference

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#2147]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In the [Shipping Architecture Overview](https://docs.medusajs.com/advanced/backend/shipping/overview) documentation, the entities `FulfillmentProvider`, `ShippingProfile`, `ShippingOption`, and `ShippingMethod` are mentioned but not linked.

Also, the heading "ShippingMethod Entity Overview" is a level two heading instead of level three.

### How can this issue be resolved?

1. Link to each of the entities mentioned earlier under the "Entity Overview" of each. For example, Add a link to the `FulfillmentProvider` entity under the "FulfillmentProvider Entity Overview" section. Make sure to only add it to the first time the entity is mentioned in that section.
2. Change the heading "ShippingMethod Entity Overview" to be a level 3 heading.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by gefgu** [comment]
I would love to work on this issue @shahednasser . Can you assign it to me?

**Comment by shahednasser** [comment]
Hi @gefgu sure I'll assign you
