### ISSUE TITLE
Docs: add links in the Payment Architecture Overview documentation to the entities in the Entities Reference

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#2148]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In the [Payment Architecture Overview](https://docs.medusajs.com/advanced/backend/payment/overview) documentation, the entities `PaymentProvider`, `PaymentSession`, and `Payment` are mentioned but not linked.

### How can this issue be resolved?

1. Link to each of the entities mentioned earlier under the "Entity Overview" of each. For example, Add a link to the `PaymentProvider` entity under the "PaymentProvider Entity Overview" section. Make sure to only add it to the first time the entity is mentioned in that section.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by gefgu** [comment]
Hi @shahednasser! I would be happy to work on this issue.

**Comment by shahednasser** [comment]
Hey @gefgu I'll assign you!
