### ISSUE TITLE
Docs: add links in the Notification Architecture Overview documentation to the entities in the Entities Reference

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#2149]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In the [Notification Architecture Overview](https://docs.medusajs.com/advanced/backend/notification/overview) documentation, the entities`NotificationProvider` and `Notification` are mentioned but not linked.

### How can this issue be resolved?

1. Link to each of the entities mentioned earlier under the "Entity Overview" of each. For example, Add a link to the `NotificationProvider` entity under the "NotificationProvider Entity Overview" section. Make sure to only add it to the first time the entity is mentioned in that section.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by sabakhilji** [comment]
Hi @shahednasser can I do this?

**Comment by shahednasser** [comment]
Sorry, @Ravina-Deogadkar I didn't notice your comment. Are you still interested in taking this up?

**Comment by octonawish-akcodes** [comment]
Can I work on this @shahednasser

**Comment by shahednasser** [comment]
Yes @octonawish-akcodes I'll assign you

**Comment by daniloff200** [comment]
Haven't see any work from @octonawish-akcodes for 10 days, so, I made this one by myself
Could this one be reassigned @shahednasser  ?

**Comment by shahednasser** [comment]
Sure @daniloff200 I'll assign you
