### ISSUE TITLE
the current version of the product model allows one collection per product.

### ISSUE THREAD

**Issue by maxpanakov** [medusajs/medusa#2165]
The current version of the product model allows one collection per product. Do you have any plans for a product in multiple collections ?
```ts
@Column({` type: "text", nullable: true })
  collection_id: string | null

  @ManyToOne(() => ProductCollection)
  @JoinColumn({ name: "collection_id" })
  collection: ProductCollection

```

_Originally posted by @almousa1990 in https://github.com/medusajs/medusa/issues/1370#issuecomment-1197078787_

**Comment by olivermrbl** [comment]
Thanks for reporting this in @maxpanakov. We do have plans of revisiting the product domain in the near future. I can't promise anything at this point but the issue you've highlighted here is in out backlog 👍

**Comment by srindom** [comment]
@maxpanakov - We are moving feature requests to GitHub Discussions to keep better track of the most requested features (using the upvote mechanism) and streamline GitHub Issues around bugs. Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!
