### ISSUE TITLE
npm install -g @medusa/medusa-cli returns an E404 not found in the npm registry

### ISSUE THREAD

**Issue by nicodemus-opon** [medusajs/medusa#218]

**Comment by olivermrbl** [comment]
Hi there Nicodemus. 

Thank you for submitting your issue.

I see, that you are using the wrong organization in your npm install command. 

Can you try with `@medusajs/medusa-cli` instead?

That should work.

Looking forward to hearing from you.

**Comment by nicodemus-opon** [comment]
Ok, thanks... Could you please edit it in the readMe
