### ISSUE TITLE
Error running yarn install in windows 10

### ISSUE THREAD

**Issue by Keith-Hon** [medusajs/medusa#2181]
## Bug report

➤ YN0000: ┌ Link step
➤ YN0001: │ Error: While cloning /C:/Users/keith/Desktop/medusa/packages/medusa/node_modules/string-length/node_modules/strip-ansi -> /C:/Users/keith/Desktop/medusa/packages/medusa-plugin-sendgrid/node_modules/table/node_modules/strip-ansi UNKNOWN: unknown error, link 'C:\Users\keith\Desktop\medusa\packages\medusa\node_modules\string-length\node_modules\strip-ansi\license' -> 'C:\Users\keith\Desktop\medusa\packages\medusa-plugin-sendgrid\node_modules\table\node_modules\strip-ansi\license'

### System information

Medusa version (including plugins):  1.3.5
Node.js version: 16.13.0
Database: postgres
Operating system: windows 10
Browser (if relevant):

### Steps to reproduce the behavior

1. Fresh clone of https://github.com/medusajs/medusa.git

2. Run `yarn install`
 
### Expected behavior

Should successfully execute the installation

### Additional context

The above error occurs during link step

**Comment by olivermrbl** [comment]
@Keith-Hon Thanks for reporting it in. Do you have additional logs to share with us? Can't seem to decode much from the one here.

**Comment by theabhayprajapati** [comment]
It worked on windows 11 by the way.
<img width="439" alt="image" src="https://user-images.githubusercontent.com/88815641/189958293-a73efd8c-2dab-4301-a2eb-f1d1dc540d84.png">

**Comment by olivermrbl** [comment]
Closed due to inactivity

**Comment by cf1331** [comment]
For anyone having this issue, try changing `nmMode: hardlinks-global` to `nmMode: hardlinks-local` in [.yarnrc.yml](https://github.com/medusajs/medusa/blob/479ae1e257bb51a3ad1951a47ce76dc726a73fb1/.yarnrc.yml) and running `yarn install`. If that doesn't work, try `nmMode: classic`.  

### Details

I ran into the same issue, although for me it was happening on a different package:
```
➤ YN0000: ┌ Link step
➤ YN0001: │ Error: While cloning /C:/medusa/packages/medusa/node_modules/jest-get-type -> /C:/medusa/node_modules/jest-jasmine2/node_modules/jest-get-type UNKNOWN: unknown error, link 'C:\medusa\packages\medusa\node_modules\jest-get-type\LICENSE' -> 'C:\medusa\node_modules\jest-jasmine2\node_modules\jest-get-type\LICENSE'
```

In #2447, @FeatureSpitter mentioned yarn failing in the linkage part too - I think it's likely the same issue. 

The error from yarn is happening in the call to `xfs.linkPromise()` here: 
https://github.com/yarnpkg/berry/blob/d157755d585627623dfeebff154842dfe29eb871/packages/plugin-nm/sources/NodeModulesLinker.ts#L1078

That function is just a promise wrapper around `fs.link()`, which is failing with `errno: -4094`. 
https://github.com/yarnpkg/berry/blob/d157755d585627623dfeebff154842dfe29eb871/packages/yarnpkg-fslib/sources/NodeFS.ts#L378-L382

I haven't dug any deeper into why it's failing. It will be some underlying error from Windows. `util.getSystemErrorName(-4094)` returns `"UNKNOWN"` which is where the unknown part of the error message comes from.

Changing `nmMode` to `hardlinks-local` fixed it for me. `classic` works too, but it creates copies of modules - see [Yarn Configuration](https://yarnpkg.com/configuration/yarnrc#nmMode).

### System information
Medusa version (including plugins): 1.3.5
Node.js version: 14.20.1
Database: postgres
Operating system: Windows 10 (x64)
Browser (if relevant):
