### ISSUE TITLE
Run medusa-dev -> integration-tests/api

### ISSUE THREAD

**Issue by maxpanakov** [medusajs/medusa#2235]
## Bug report
Can't run medusa-dev command in api filder

### Describe the bug

i can run medusa-dev in the project, but i have a problem with running tests 

### System information

Medusa version (including plugins):develop
Node.js version: 14
Database:
Operating system:
Browser (if relevant):

### Screenshots
![image](https://user-images.githubusercontent.com/9987863/191206280-c5662e36-6a01-4c59-b768-c064306c5cef.png)

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by maxpanakov** [comment]
i tried run with --force-install as well, not helped

**Comment by olivermrbl** [comment]
Can I get you to try the following command: `medusa-dev --force-install --external-registry`
