### ISSUE TITLE
blank screen after opening Regions/Custom gift cards [dashboard]

### ISSUE THREAD

**Issue by muhamedzeema** [medusajs/medusa#2256]
### Describe the bug

Hey, after installing the medusa server and dashboard. i was tried to add Regions or custom gift card but the screen went to white blank screen and stuck at this. 

### System information

Medusa version (including plugins): 1.3.7
Node.js version: v17.1.0
Database: postgress
Browser (if relevant): chrome/safari

### Steps to reproduce the behavior

1. go to settings
2. press Regions
3. white screen 

or 
1. go to Gift Cards
2. press on custom gift card
3. white screen

### Expected behavior

normal screen with its inputs fields 

### Screenshots

https://user-images.githubusercontent.com/71822189/192021435-4d6f7a64-c4ad-45dc-9ae7-2dee1c897d32.mov

**Comment by olivermrbl** [comment]
Thanks for reporting this. I can't seem to reproduce the issue. Can I get you to provide a repro?

**Comment by olivermrbl** [comment]
Solved in this [admin PR](https://github.com/medusajs/admin/pull/711)
