### ISSUE TITLE
Docs: Add a link to the integrations page in the footer

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#2282]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

We should add a link to the Integrations page in the footer.

### How can this issue be resolved?

Add a link to [this page](https://medusajs.notion.site/1a0ada9903874e0185d0b8ce0591b359?v=0631285851ba4021aa07c3b48dd4801a) in the footer under the "More" column.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by tharun634** [comment]
Hello, can I take this up
