### ISSUE TITLE
Docs: Change Introduction label

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#2283]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The introduction page only covers the Architecture overview. Therefore, it makes sense to just make it an "Architecture Overview" page

### How can this issue be resolved?

1. Change the label in the sidebar to "Architecture Overview"
2. Change the main header in the page to be "Architecture Overview", and subheaders to be "Headless Backend", "Admin Dashboard", and "Storefront"

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by Zeesky-code** [comment]
Hello, I am interested in this issue and I would like to work on this. Can you please assign me to the issue?

**Comment by shahednasser** [comment]
Sure @Zeesky-code I'll assign you

**Comment by appledora** [comment]
@shahednasser I made a pull on this a couple of days ago :| I saw some people making PRs without assignments, so I though we don't need explicit assignments for this repo :|
