### ISSUE TITLE
Docs: Remove the "Deploy to Heroku" button from the Quickstart guide

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#2284]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Since Heroku removed their free tier and the button + documentation need updating, we should remove the deploy button from the [Quickstart page](https://docs.medusajs.com/quickstart/quick-start).

### How can this issue be resolved?

1. Remove the deploy button with the text above it "Alternatively,..." in the [Quickstart documentation](https://docs.medusajs.com/quickstart/quick-start).

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by alesbe** [comment]
Hi! I think that I can solve this, can I take it?

**Comment by alesbe** [comment]
I made the PR, let me know if you need anything else :)

**Comment by RJ025** [comment]
just made a PR please look into it

**Comment by shahednasser** [comment]
@alesbe I'll assign you
