### ISSUE TITLE
Docs: Remove info admonitions (callouts) in "Set up your development environment" documentation

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#2285]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The ["Set up your development environment" documentation](https://docs.medusajs.com/tutorial/set-up-your-development-environment) has many admonitions (or callouts) which can be distracting. We should remove the `info` admonitions

### How can this issue be resolved?

1. Remove the `info` admonition at the beginning of every section.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by swetha-h** [comment]
I would like to fix this issue
Can i take it up?

**Comment by shahednasser** [comment]
Sure @swetha-h I'll assign you

**Comment by appledora** [comment]
@shahednasser I think I already made a pull on this a couple of days ago. Could you check?

**Comment by shahednasser** [comment]
@swetha-h are you still working on this?

**Comment by swetha-h** [comment]
> @swetha-h are you still working on this?

I was unable to do it. You can assign this task to someone else

**Comment by appledora** [comment]
@shahednasser can you assign me? I have done it before.
