### ISSUE TITLE
Docs: remove the "Load from .env" section from the "Configure your Server" doc page

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#2286]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The "Load from .env" section in the [Configure your Server documentation](https://docs.medusajs.com/usage/configurations) is no longer relevant now that it is included by default in the starter. We also already have it in the v1.3.0 upgrade guide.

### How can this issue be resolved?

1. Remove the Load from .env section

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by Zeesky-code** [comment]
Hello, I'm interested in working on this issue. Can you please assign me?

**Comment by shahednasser** [comment]
Sure @Zeesky-code I'll assign you
