### ISSUE TITLE
Docs: Remove the "Admin Features Overview" section from the Admin Quickstart

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#2287]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The "Admin Features Overview" section in the [Admin Quickstart](https://docs.medusajs.com/admin/quickstart) was relevant before the user guide. Now, we can substitute it with a link to the user guide.

### How can this issue be resolved?

1. Remove the Admin Features Overview Section
2. Add in its place a "Admin User Guide" section saying that you can learn more about Medusa admin and its features in the user guide with a link to it.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by MarcosRZ** [comment]
Hi! I would like to work on this one!

**Comment by shahednasser** [comment]
Great @MarcosRZ I'll assign you

**Comment by RJ025** [comment]
hey , @MarcosRZ  are you working on this issue

**Comment by MarcosRZ** [comment]
@RJ025 Yes, I am.
