### ISSUE TITLE
Docs: Replace "Install the JS Client" section in "How to Add Cart Functionality"

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#2288]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

To follow a new structure of how-to guides, the "Install JS Client" section in the "[How to Add Cart Functionality" documentation](https://docs.medusajs.com/guides/carts-in-medusa) should be replaced with a section in the "Prerequisites" section.

### How can this issue be resolved?

1. Remove the [Install JS Client section](https://docs.medusajs.com/guides/carts-in-medusa#install-the-js-client)
2. Add under the Prerequisites section a subsection [similar to this one](https://docs.medusajs.com/advanced/admin/import-products#js-client). It should mention details regarding authentication.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by vish-han** [comment]
Hey @shahednasser  I would love to work on this issue and contribute my bit to medusa😊. please assign me.

**Comment by shahednasser** [comment]
Sure @vish-han I'll assign you

**Comment by appledora** [comment]
@shahednasser could you assign me a similar issue?

**Comment by shahednasser** [comment]
At the moment there are no issues left @appledora you're free to open an issue if you find issues in the documentation or just be on the lookout if we create a new issue 😊

**Comment by shahednasser** [comment]
@vish-han are you still working on this?

**Comment by shahednasser** [comment]
Since I got no answer from @vish-han I'll assign you @appledora

**Comment by appledora** [comment]
@shahednasser could you double check that the issue hasn't already been resolved and merged? :|
