### ISSUE TITLE
Docs: Remove the Prerequisites section in Create an Entity documentation

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#2289]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In the Create an Entity documentation the Prerequisites section is no longer necessary as this is now available by default in the starter

### How can this issue be resolved?

1. Remove the [Prerequisites](https://docs.medusajs.com/advanced/backend/entities/#prerequisites) section

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by Zeesky-code** [comment]
Hello, I am interested in this issue and I would like to work on this. Can you please assign me to the issue?

**Comment by ayushthe1** [comment]
Hey ,I created a pr for this issue . Can you please check it out.

**Comment by RJ025** [comment]
I would like to fix this issue

**Comment by ayushthe1** [comment]
Hey @shahednasser . i created a pr fo this issue .Can you please check it and give some feedback.
Thanks

**Comment by RJ025** [comment]
Hey @shahednasser  , I created a pr for this issue .Can you please check it and give some feedback.
Thanks

**Comment by shahednasser** [comment]
I'll assign @RJ025 since I've already assign @Zeesky-code to a couple of other issues and @RJ025 is the person that commented after them
