### ISSUE TITLE
Docs: Add missing link in MailChimp documentation

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#2290]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In the Mailchimp documentation under the [What's Next section](https://docs.medusajs.com/add-plugins/mailchimp#whats-next-), the link to the sendgrid plugin documentation is missing from the first point.

### How can this issue be resolved?

1. Add a link in the [What's Next section](https://docs.medusajs.com/add-plugins/mailchimp#whats-next-) in the first point to the [Sendgrid plugin](https://docs.medusajs.com/add-plugins/sendgrid).

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by Rutam21** [comment]
@shahednasser Please assign this issue to me. Thanks.

**Comment by shahednasser** [comment]
@Rutam21 I've assigned you this issue
