### ISSUE TITLE
Docs: Add Klarna Documentation

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#2291]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

We need documentation to the [Klarna plugin](https://docs.medusajs.com/add-plugins/klarna). It should be similar to the [Stripe](https://docs.medusajs.com/add-plugins/stripe) and [PayPal](https://docs.medusajs.com/add-plugins/paypal) plugins.

### How can this issue be resolved?

1. Add documentation for the Klarna plugin

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by octonawish-akcodes** [comment]
I want to work on this

**Comment by octonawish-akcodes** [comment]
I want to work on this

**Comment by nik132-eng** [comment]
I want to work on this issue can you please assign me so that I can start contributing to hacktoberfest.

**Comment by anudeeps0306** [comment]
I would like to fix this issue

**Comment by shahednasser** [comment]
I've assigned you @octonawish-akcodes

**Comment by shahednasser** [comment]
@octonawish-akcodes are you working on this?

**Comment by shahednasser** [comment]
I'm unassigning @octonawish-akcodes due to inactivity

**Comment by Smartmind12** [comment]
@shahednasser Can you assign this issue to me so that i can work on it!

**Comment by shahednasser** [comment]
Sure I've assigned you @Smartmind12

**Comment by Smartmind12** [comment]
> Sure I've assigned you @Smartmind12

Thankss i will get on it !!

**Comment by akarsh-jain-790** [comment]
@shahednasser can you assign me this issue?

**Comment by bhagatpratham** [comment]
Hey, @Smartmind12 are you working on this?

**Comment by shahednasser** [comment]
@bhagatpratham are you interested in working on this?

**Comment by pratik-codes** [comment]
@shahednasser I would be interested to pick this up. Ill work on it and will send a PR across super soon!

**Comment by shahednasser** [comment]
Sorry forgot this issue is still open. This has been resolved
