### ISSUE TITLE
Docs: Add Gatsby and React-Based Storefront guide for Algolia plugin.

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#2293]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Similar to [this section in the MeiliSearch plugin](https://docs.medusajs.com/add-plugins/meilisearch#add-to-gatsby-and-react-based-storefronts), we should have a section on how to add Algolia search functionality to the Gatsby and React-based storefronts.

### How can this issue be resolved?

1. Add section to integrate Algolia into a Gatsby and React-based storefronts. Although it should be similar to MeiliSearch, the steps should be specific to Algolia. Also, if the steps for Gatsby are different than those of React-based storefronts, you're free to use two different sections.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by vish-han** [comment]
Please Assign me. I would love to work on the issue😊.

**Comment by octonawish-akcodes** [comment]
Please assign this to me

**Comment by shahednasser** [comment]
@vish-han I'll assign you

**Comment by shahednasser** [comment]
@vish-han are you still working on this?

**Comment by shahednasser** [comment]
I'm unassigning @vish-han due to inactivity

**Comment by neelshah2409** [comment]
May I take this isssue @shahednasser

**Comment by shahednasser** [comment]
Sure @neelshah2409 I'll assign you

**Comment by akarsh-jain-790** [comment]
@neelshah2409 are you still working? If not @shahednasser can you assign me this issue?

**Comment by neelshah2409** [comment]
> @neelshah2409 are you still working? If not @shahednasser can you assign me this issue?

Yes I am working just give me some time !!

**Comment by neelshah2409** [comment]
Hey @shahednasser could you just help me where I could add this doc as I have prepared it but not getting the proper path where to attach them.

**Comment by shahednasser** [comment]
Hello @neelshah2409 , it should be put in `docs/content/add-plugins/algolia.md`
