### ISSUE TITLE
Hacktoberfest: Participate in the Medusa Hackathon

### ISSUE THREAD

**Issue by MedusaNick** [medusajs/medusa#2295]
## What is it?
For this year's Hacktoberfest, we are launching our very first Hackathon.

Our Medusa Hackathon is open for contributions until **the Oct 23, 11:59 pm CET**.

**Relevant resources:**
- [Participation Guidelines](https://medusajs.com/blog/medusa-hackathon)
- [Submission thread](https://github.com/medusajs/medusa/discussions/2280)
- [Discord for Q&A](https://discord.com/invite/medusajs)

Once submitted and approved, we will add it to the [submission overview](https://github.com/medusajs/hackathon-oct2022).

## What do you get from participating?
- Medusa Hackathon Tee + Hoodie
- Certificate of Participation
- Chance to win up to $1,500

For more details, see the participation guidelines.

**Comment by Keshraf** [comment]
Excited! 🙌

**Comment by Himanxu1** [comment]
Yooo

**Comment by RachitGarg-12** [comment]
Excited!!

**Comment by Priyam3955** [comment]
Very Excited!!

**Comment by karthiksenthil2803** [comment]
Hello,
Can I create an web application using medusa api and will it be accepted by you for hacktober 2022 ?
Thank You

**Comment by karthiksenthil2803** [comment]
Also, I had'nt pre-registered for the hackathon as I came to know about it a bit late. So will my (submission if done) still count for the swags and the certificate ?

**Comment by rsarthak** [comment]
Excited!!!

**Comment by Dynomin** [comment]
Taking part in it with my team !

**Comment by Edybee** [comment]
Hi, what is the hackathon about? Can one participate via documentation?

**Comment by MedusaNick** [comment]
> Hi, what is the hackathon about? Can one participate via documentation?

You can find more info and sign-up for it via https://medusajs.com/blog/medusa-hackathon

But no, the Hackathon is different than solving Docs issues

**Comment by Edybee** [comment]
Alright

Since I don't code, I'll just skip the competition.

Thanks
