### ISSUE TITLE
Docs: Wrong list order in next.js documentation

### ISSUE THREAD

**Issue by alesbe** [medusajs/medusa#2306]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I've been checking the medusa documentations, and I realized that this list index is wrong, every element is set to 1:

![screenshot](https://i.imgur.com/njyd4wy.png)

[Here is the link](https://docs.medusajs.com/starters/nextjs-medusa-starter)

### How can this issue be resolved?

This issue can be easily solved by renaming the list index, I would like to fix it myself if possible!

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by Chirag8023** [comment]
Kindly assign this to me!

**Comment by alesbe** [comment]
I made a PR fixing this yesterday! #2308

**Comment by shahednasser** [comment]
Thanks for catching this @alesbe ! Will review your PR soon.
