### ISSUE TITLE
Docs: Change title of Storefront Quickstart guides

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#2324]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The [Gatsby storefront quickstart documentation](https://docs.medusajs.com/starters/gatsby-medusa-starter)'s title can be improved to avoid confusion, especially when multiple tabs are open. The same goes for the [Next.js Storefront](https://docs.medusajs.com/starters/nextjs-medusa-starter).

### How can this issue be resolved?

1. Change the title of the Gatsby document to "Gatsby Storefront Quickstart".
2. Change the title of the Next.js document to "Next.js Storefront Quickstart".

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
@appledora would you like to work on this?

**Comment by appledora** [comment]
Thanks a lot @shahednasser . Please assign me this :D

**Comment by shahednasser** [comment]
Cool I assigned you

**Comment by vardhan0604** [comment]
hey @appledora  are you working on it?
