### ISSUE TITLE
Docs: Add additional step for Gatsby and Next.js storefronts

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#2325]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In step 2 of both [Gatsby](https://docs.medusajs.com/starters/gatsby-medusa-starter) and [Next.js](https://docs.medusajs.com/starters/nextjs-medusa-starter) storefront quickstart guides, it is mentioned to "change to the directory" but without that being portrayed in the command.

### How can this issue be resolved?

1. Add to the command of step 2 of both Gatsby and Next.js storefronts the command to change directory (using `cd`).

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
@ayushthe1 would you like to work on this?

**Comment by ayushthe1** [comment]
> @ayushthe1 would you like to work on this?
yes ,i will try to contribute on this issue.

**Comment by ayushthe1** [comment]
> @ayushthe1 would you like to work on this?

yes ,i would love to work on this issue,

**Comment by shahednasser** [comment]
Cool I assigned you

**Comment by ayushthe1** [comment]
@shahednasser could you please review my pr for this issue.
