### ISSUE TITLE
Stuck when port is already in use

### ISSUE THREAD

**Issue by treboryx** [medusajs/medusa#2329]
<img width="898" alt="image" src="https://user-images.githubusercontent.com/5408097/193582503-bef4338d-719f-4de8-802c-59ff863b1622.png">

### Describe the bug

It's stuck at `Creating server` when it has already errored because the port is already in use by another process

### System information

Medusa version (including plugins): latest
Node.js version: 16.17.1
Database: default
Operating system: macOS
Browser (if relevant):

**Comment by rajivharlalka** [comment]
I would like to work on this. Can you assign it to me?

**Comment by olivermrbl** [comment]
You can start the server on a different port by passing it as an argument to our CLI: `yarn start --port=9001`

**Comment by treboryx** [comment]
I know I can use the port argument. I filed this issue because I thought it should behave differently, like everything else.

**Comment by DorianMazur** [comment]
I think this should be reopened.
@olivermrbl 
We can check if the port is available and display proper error message instead of infinite loading.

```
import { createServer } from "net";

const isPortTaken = (port: number, type: 'IPv4' | 'IPv6' = 'IPv4') => {
  let hasError = 0;
  return new Promise((res) => {
    const server = createServer()
      .once('error', err => { if (err) { res(false) } })
      .once('listening', () => {
        server
          .once('close', () => {
            hasError++;
            if (hasError > 1) {
              res(false)
            } else {
              res(true)
            }
          })
          .close()
      })
      .listen(port, type === 'IPv4' ? '0.0.0.0' : '::')
  })

};
```
