### ISSUE TITLE
Images are not showing as host is Geo-Restricted

### ISSUE THREAD

**Issue by Nirzak** [medusajs/medusa#2336]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The documantation here https://docs.medusajs.com/troubleshooting/cors-issues/ is using images hosted on imgur.com which is not accessible from my country. As a result the images are not showing.
Country: Bangladesh
Tried from both my home ISP and cellular ISP.

![imgur](https://user-images.githubusercontent.com/11460645/193621695-3b09b8ef-17ab-4a59-b2dd-af92347c2185.PNG)

### How can this issue be resolved?

1. Images can be self-hosted or hosted on GitHub which is more reliable and widely supported.

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by daniloff200** [comment]
I know, that imgur also banned in Turkey, for example

**Comment by shikhar13012001** [comment]
I would like to work on this issue. Can you please assign this to me? @Nirzak

**Comment by shahednasser** [comment]
Thank you for opening this issue. We'll have to look into different options and probably resolve this with other hosting providers, so we'd have to fix it ourselves. Thank you for everyone interested in contributing!

**Comment by Nirzak** [comment]
> Thank you for opening this issue. We'll have to look into different options and probably resolve this with other hosting providers, so we'd have to fix it ourselves. Thank you for everyone interested in contributing!

Ok @shahednasser but my suggestion is that github can be a good solution with free of cost. Thanks!

**Comment by Nirzak** [comment]
> 

Is this issue still need to stay open? I am closing this as the matter is resolved.
