### ISSUE TITLE
Video Tutorials: Use Case Implementations & Demos

### ISSUE THREAD

**Issue by AudreyLin** [medusajs/medusa#2339]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

Developers are requesting video tutorials for feature implementations, use case examples, and different deployment implementations.  This is a newer platform, but even with its good documentation coverage, there are still questions about how to use and implement some of the features.  

**Describe the solution you'd like**

Video Tutorials or Blog posts with detailed screenshots, media, and documentation of implementation that highlight resources and solutions to common questions or issues encountered.  These can be submitted by the community, the users, the developers, and the company.  

**Describe alternatives you've considered**

Asking others in the community of developers that use this platform for resources. 

**Additional context**

I'm submitting this issue based on a conversation that took place in the [#Free-Talk' Channel of the Medusa Community Discord Server](https://discord.com/channels/876835651130097704/1022513717507788870).  I posted this as an issue to see if the maintainers of this repo will create a more detailed call to action to create specific video or blog tutorials, and add 'Hacktoberfest', 'help-wanted', or other related labels to these issues.  Either that or have Medusa create these tutorials for the developer tutorials themselves.  

Thank you.

**Comment by AudreyLin** [comment]
Also, the community can leave a thread here of the types of tutorials that they want to see and/or what to contribute.

**Comment by shahednasser** [comment]
Hello! Thank you for submitting this issue.

Regarding blog posts, we actually have a [writer's program that you can join](https://medusajs.notion.site/Write-for-us-74a2bf43b4ce43eeba200382f599321a). You can then choose a topic to work on it for our blog and publications.

As for videos we currently don't have any video platform or related content production. We would appreciate though any video content that could help the community if you were to create any on platforms like Youtube 😊

**Comment by srindom** [comment]
@AudreyLin - We are moving feature requests to GitHub Discussions to keep better track of the most requested features (using the upvote mechanism) and streamline GitHub Issues around bugs. Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!

**Comment by AudreyLin** [comment]
@srindom Thank you for letting me know. I will move it there.

**Comment by AudreyLin** [comment]
@shahednasser Thank you.  I don't currently have a Youtube Channel or any video content, but I will see what I can do about the blog content.
