### ISSUE TITLE
Improperly referenced product id when parsing CSV for bulk product update via import strategy

### ISSUE THREAD

**Issue by a-finocchiaro** [medusajs/medusa#2350]
### Describe the bug

In the `ProductImportStrategy` class, the `getImportInstructions` improperly checks the `product.id` for each row. Please see the code snippets section for the exact line.

With it setup this way, products will always be considered new because the `product.id` column is not read here. So products will never be updated.

### Expected behavior

I would expect this to be `row['product.id']` instead.

### Code snippets

https://github.com/medusajs/medusa/blob/bd941309161bcee4fbfc7918d310c426ba8d8f15/packages/medusa/src/strategies/batch-jobs/product/import.ts#L166

**Comment by ayushthe1** [comment]
Hey ,I would like to work on this issue .

**Comment by a-finocchiaro** [comment]
> Hey ,I would like to work on this issue .

Go for it! I have actually already fixed it in another project where I'm actually using medusa, I just haven't done the same on my forked version of it but if you'd like to fix it, you're more than welcome.

**Comment by ayushthe1** [comment]
Thanks @a-finocchiaro .
I made a pr for this issue . Could you please review it.

**Comment by olivermrbl** [comment]
Solved #2351

Again, thanks for the contribution. To show our appreciation, we'd love to send you some swag/merch. If that's of interest reach out to me on our Discord and we'll make it happen! 💪
