### ISSUE TITLE
Docs: Change the font size of the options of sidebar

### ISSUE THREAD

**Issue by shlok2740** [medusajs/medusa#2354]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The font size of the sidebar is too small

### How can this issue be resolved?

1. Increase the size of the option in the sidebar 
2.
3.
...

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by arjunlubana** [comment]
Can you assign this issue to me?

**Comment by shahednasser** [comment]
Thank you for submitting this issue. As this is something related to design, I'll relay your opinion to our design and docs team.

**Comment by SattyamSamania** [comment]
Hey, If the issue is still open I would love to work on this issue. Please assign it to me.
