### ISSUE TITLE
Add CODE_OF_CONDUCT.md file

### ISSUE THREAD

**Issue by abhilipsasahoo03** [medusajs/medusa#2375]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

A code of conduct defines standards for how to engage in a community. It signals an inclusive environment that respects all contributions. It also outlines procedures for addressing problems between members of your project's community. It also contains the organization's contact information such as support email in order for community members to communicate in case they come across some kind of misconduct. I went through the repository and found out that the Code of Conduct file is missing. 

### How can this issue be resolved?

I'd like to add a Code of Conduct file to the project repository. 

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by abhilipsasahoo03** [comment]
@shahednasser can I work on this issue?

**Comment by xoxocrystyle** [comment]
Hey there, may I work on this issue if it hasn't been assigned to anyone yet?

**Comment by abhilipsasahoo03** [comment]
> Hey there, may I work on this issue if it hasn't been assigned to anyone yet? 

I guess there's already a PR open for this. Not sure if it's under review or not.
