### ISSUE TITLE
Lists products having q  params throw error in console

### ISSUE THREAD

**Issue by harshmangalam** [medusajs/medusa#2378]
### Describe the bug

When i make a curl request to get lists of product having q search params it throw out error

```shell

curl --location --request GET 'http://localhost:9000/store/products?q=Shirt'
```

```json
{"code":"unknown_error","type":"unknown_error","message":"An unknown error occurred."}
```

### System information
Medusa CLI version: 1.3.3
Node.js version:v16.17.0
Database:Sqlite
Operating system:Linux mint (20)
Browser (if relevant):

![medusa-err](https://user-images.githubusercontent.com/57381638/194468207-590ad966-4684-4f1d-8de9-06be9a7c1123.png)

**Comment by olivermrbl** [comment]
@harshmangalam You can't use search with SQLite as it does not support the `ILIKE` operator. Switching database to Postgres should resolve your issue.
