### ISSUE TITLE
Kubernetes Helm Support

### ISSUE THREAD

**Issue by tabilzad** [medusajs/medusa#2385]
It'd be nice if there was a helm chart to deploy medusa components on Kubernetes

**Comment by olivermrbl** [comment]
We'd love to accept a PR for that if you are up for it?

**Comment by srindom** [comment]
@tabilzad - We are moving feature requests to GitHub Discussions to keep better track of the most requested features (using the upvote mechanism) and streamline GitHub Issues around bugs. Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!
