### ISSUE TITLE
npx create-medusa-app not able to setup medusa locally

### ISSUE THREAD

**Issue by Gulshanaggarwal** [medusajs/medusa#2388]
### Describe the bug

npx create-medusa-app not able to setup the medusa in local env.

### System information

Medusa version (including plugins):
Node.js version: 16.13.2
Database:
Operating system: Windows
Browser (if relevant):

### Steps to reproduce the behavior

1. Go to 'Command line'
2. Write  'npx create-medusa-app'
3. Choose 'medusa-default-starter'
4. Then select 'Gatsby-Starter '  or any starter from the list

### Expected behavior

It should setup medusa all 3 components locally.
### Screenshots

<img width="652" alt="Annotation 2022-10-08 195555" src="https://user-images.githubusercontent.com/58553401/194712408-36b15baa-4d67-412e-a318-871afae485cb.png">

**Comment by olivermrbl** [comment]
Can't seem to reproduce it. Closing for now. Feel free to open if the issue persists.
