### ISSUE TITLE
`medusa user` throws exception "TypeError: cmd is not a function"

### ISSUE THREAD

**Issue by remy** [medusajs/medusa#2395]
### Describe the bug

Newly installed medusa command line tool. Non-seeded server, am trying to create a new user to access via the admin interface.

<details>
<summary><strong><code>medusa --json --verbose user</code></strong></summary>

<pre><code>medusa user

Create a user

Options:
  --verbose                Turn on verbose output
                                          [boolean] [default: false]
  --no-color, --no-colors  Turn off the color in output
                                          [boolean] [default: false]
  --json                   Turn on the JSON logger
                                          [boolean] [default: false]
  -e, --email              User's email.                    [string]
  -p, --password           User's password.                 [string]
  -i, --id                 User's id.                       [string]
  -h, --help               Show help                       [boolean]
  -v, --version            Show the version of the Medusa CLI and
                           the Medusa package in the current project
                                                           [boolean]
medusa user

Create a user

Options:
  --verbose                Turn on verbose output
                                          [boolean] [default: false]
  --no-color, --no-colors  Turn off the color in output
                                          [boolean] [default: false]
  --json                   Turn on the JSON logger
                                          [boolean] [default: false]
  -e, --email              User's email.                    [string]
  -p, --password           User's password.                 [string]
  -i, --id                 User's id.                       [string]
  -h, --help               Show help                       [boolean]
  -v, --version            Show the version of the Medusa CLI and
                           the Medusa package in the current project
                                                           [boolean]
TypeError: cmd is not a function
    at /usr/local/lib/node_modules/@medusajs/medusa-cli/dist/create-cli.js:309:7
    at /usr/local/lib/node_modules/@medusajs/medusa-cli/dist/create-cli.js:108:24
    at Object.handler (/usr/local/lib/node_modules/@medusajs/medusa-cli/dist/create-cli.js:54:24)
    at Object.runCommand (/usr/local/lib/node_modules/@medusajs/medusa-cli/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/@medusajs/medusa-cli/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.parse (/usr/local/lib/node_modules/@medusajs/medusa-cli/node_modules/yargs/build/lib/yargs.js:584:29)
    at module.exports (/usr/local/lib/node_modules/@medusajs/medusa-cli/dist/create-cli.js:392:6)
    at Object.<anonymous> (/usr/local/lib/node_modules/@medusajs/medusa-cli/dist/index.js:70:27)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)</code></pre>

</details>

If you expand the output above, it seems to spit the output twice, and then bails with the `cmd is not a  function`.

Other `medusa` commands appear to run correctly (certainly `new` works and doesn't error). 

It errors this way with `medusa user -e remy@example.com -p mypassword` and doesn't create the actual user.

### System information

Medusa CLI version: 1.3.3 (the package version for medusa server was 0.0.1, otherwise, `@medusajs/medusa": "^1.3.7"`
Node.js version: v18.8.0
Database: None
Operating system: macOS Big Sur 11.7

### Steps to reproduce the behavior

1. Go go terminal
2. Enter `medusa user`
3. See error (above)

### Expected behavior

Hopefully to be able to create a user :)

**Comment by olivermrbl** [comment]
I can't seem to reproduce the issue with the latest CLI version. Can I get you to try to run `npm install -g @medusajs/medusa@latest` and run `medusa user ... ` again?

**Comment by kasperkristensen** [comment]
@remy Make sure that you are running the command from within your server directory. `cd my-medusa-server && medusa user -e remy@example.com -p mypassword`

**Comment by remy** [comment]
@kasperkristensen that was it! Because `medusa` was a globally installed command, I didn't realise I needed to be in that directory (I guess it makes sense thinking about it, since it's got to connect to the right db, etc).

Thanks!
