### ISSUE TITLE
Docs: Fix missing import in "How to Add Cart Functionality" MDX file

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#2422]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In the [How to Add Cart Functionality MDX file](https://github.com/medusajs/medusa/tree/master/docs/content/guides) there's a missing import for the `Tabs` and `TabItem` components. This makes the tabs not visible in the documentation

### How can this issue be resolved?

1. Add the following import at the beginning of the file:

```
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
```

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by Zeesky-code** [comment]
Hello, I would like to work on this issue.
Can I please be assigned?

**Comment by soundarrajan-official** [comment]
I am interested to solve this issue, so can you assign me for this issue ?
