### ISSUE TITLE
Docs: Add missing tabs in Create a Batch Job Strategy

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#2423]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In the Create a Batch Job Strategy documentation, tabs that should separate the different methods of sending a request (JS Client, Fetch API, and cURL), are missing.

### How can this issue be resolved?

1. Add in the documentation the tabs for each of the request types. You can see a similar implementation in [this documentation](https://github.com/medusajs/medusa/blob/master/docs/content/advanced/admin/import-prices.mdx).

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by najeebkp** [comment]
Hi @shahednasser please assign me this task

**Comment by akarsh-jain-790** [comment]
Hey, I would like to work on this issue.

**Comment by Zeesky-code** [comment]
Hello, I would like to work on this issue? I have already opened a pr
Can I please be assigned?

**Comment by shahednasser** [comment]
Assigned @akarsh-jain-790 for commenting first 😊
