### ISSUE TITLE
SQLite support for restock notification plugin

### ISSUE THREAD

**Issue by kaushalyap** [medusajs/medusa#2445]
**Is your feature request related to a problem? Please describe.**

Currently, [restock notification plugin](https://github.com/medusajs/medusa/tree/master/packages/medusa-plugin-restock-notification) is not supported with sqlite due to unsupported data types (`jsonb`)

**Describe the solution you'd like**

Support restock notification plugin with sqlite

**Describe alternatives you've considered**

Configuring Postgres

**Additional context**

Easier to try out plugins with SQLite.

**Comment by olivermrbl** [comment]
I am adding the `wont fix` label and closing as SQLite should not be used in a production environment, so adding the support in this plugin is not a good waste of time.

However, we will accept a PR if you want to work on it 💪

**Comment by kaushalyap** [comment]
@olivermrbl I do not agree that every case need Postgres, SQLite would do fine for small stores, complex, operational overhead of PG is unnecessary for such cases. SQLite would even do fine for 1M visitors/mo. I would suggest you to read this [article](https://fly.io/blog/all-in-on-sqlite-litestream/) from Ben. Cloudflare is [also using SQLite for their D1 SQL database](https://blog.cloudflare.com/introducing-d1/) product.

> However, we will accept a PR if you want to work on it 

I'll give it a try, when I got more familiar with Medusa.
