### ISSUE TITLE
Impossible to build medusajs

### ISSUE THREAD

**Issue by FeatureSpitter** [medusajs/medusa#2447]
When you checkout this repo, and run `npm i` you get the following error:

```
npm i
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:docs-util/typedoc-plugins/typedoc-frontmatter-plugin
```

I am using node 16 and npm 8.

It seems other users are finding this issue, with the official Dockerfile as well: https://stackoverflow.com/questions/73518758/npm-error-while-generating-docker-image-for-medusajs

**Comment by patrikkarlsson** [comment]
@FeatureSpitter use yarn instead, that should work for you.
