### ISSUE TITLE
Error when only selecting total fields in order service 

### ISSUE THREAD

**Issue by DukeManh** [medusajs/medusa#2450]
### Describe the bug

When only selecting total fields in order service, the select query after transformation will be an empty array and therefore the total fields are not removed from the select.

This gives `TypeORMError: paid_total column was not found in the Order entity`
```ts
    const orders = await this.orderService_.list({
      created_at: { gte: DateUtils.mixedDateToDatetimeString(date) },
    },
      {
        select: ['paid_total', 'refundable_amount'],
      }
     );
```
but this works
```diff
    const orders = await this.orderService_.list({
      created_at: { gte: DateUtils.mixedDateToDatetimeString(date) },
    },
      {
--      select: ['paid_total', 'refundable_amount'],
++      select: [...defaultAdminOrdersFields, 'paid_total', 'refundable_amount'],
      }
     );
```

### Expected behaviour

It should allow selecting only total fields

**Comment by adrien2p** [comment]
will be part of the next release 🚀
