### ISSUE TITLE
Complete checkout with tax plugin seems very unperformant

### ISSUE THREAD

**Issue by dwene** [medusajs/medusa#2451]
## Bug report

I recently installed @adrien2p 's Sentry plugin, which has been super helpful. But it's showing me some seemingly unperformant parts about Medusa's complete checkout flow, particularly around calculating taxes.

I'm using a custom plugin to calculate taxes using the ziptax API. In the plugin, we cache a tax_rate in the database with address as the lookup key.

When I watch the trace logs from sentry, I can see that it's hitting the database to fetch the cached tax rate well over 100 times during the lifetime of the request. This only happens 1 time during my `getTaxLines` implementation, so I have to assume that the `getTaxLines` method is also being called over 100 times during  the complete checkout flow. This seems unnecessary since you can pass all the line items, and shipping options in a single call.

See screenshot below.

### Describe the bug

Seemingly very unperformant code during complete-checkout.

### System information

Medusa version (including plugins): 1.5.0
Node.js version: 16
Database: PG
Operating system: OSX M1
Browser (if relevant): Chrome

### Steps to reproduce the behavior

1. Setup Medusa with the ziptax plugin.
2. Add the sentry plugin.
3. Add a few items to your cart.
4. Complete checkout.
5. Notice it takes over 6 seconds to complete the checkout.
6. Look at the sentry performance metrics for that api call.

### Expected behavior

I would expect that we don't need to recalculate the tax a hundred times during a single checkout.

### Screenshots

![screencapture-sentry-lambdacurry-dev-organizations-sentry-performance-medusa-multivendor-api-34f1f3d66fb742e0bb06770e80417ca4-2022-10-16-14_33_35](https://user-images.githubusercontent.com/12628251/196054669-02af24ef-2625-4d71-9e89-3264719a1c45.png)

**Comment by adrien2p** [comment]
@dwene I ll create a ticket internally and try to investigate that, If I have or need anything i ll contact you

**Comment by dwene** [comment]
Thanks @adrien2p , this is fixed!!
