### ISSUE TITLE
Incorrect Spelling of word medusa in package.json of paypal and stripe plugin

### ISSUE THREAD

**Issue by sebabratakundu** [medusajs/medusa#2453]
## Bug report
The word medusa in description `package.json` file of `payment-stripe` and `payment-paypal` is incorrect.

### System information

Medusa version (including plugins): 1.5.0
Node.js version: 16
Database: PG
Operating system: Window
Browser (if relevant):

### Screenshots
![image](https://user-images.githubusercontent.com/44576979/196102129-75fea499-c9f0-4e97-b994-3dda00159539.png)

**Comment by muhammadawaisshaikh** [comment]
I would like to fix this issue
