### ISSUE TITLE
Performance improvement on Cart

### ISSUE THREAD

**Issue by rrums123** [medusajs/medusa#2465]
Hey,

I found that on cart endpoints maybe need some performance improvement.

In my local test to create cart (`POST /store/carts`) with the payload:
```
{
    "region_id": "reg_01GE6Q2SD8K8FTZ2WJW5JE1ND1",
    "country_code": "gb",
    "items": [{
        "variant_id": "variant_01GERC4XZ04QHXVTG5YEGV2GN4",
        "quantity": 1
      }]
}
```

Cart contains 1 item took 934 ms
Cart contains 2 items took 1278 ms
Cart contains 3 items took 1546 ms
Cart contains 9 items took 8388 ms

### System information

Medusa version (including plugins): 1.5.0
Node.js version: 14.20.1
Database: Postgres
Operating system: MacOS

**Comment by srindom** [comment]
@rrums123 - thanks for reporting; seems there is a bottleneck when getting the correct prices for the line item. We will investigate further and try to make some optimizations in an upcoming release

**Comment by adrien2p** [comment]
@rrums123 I believe that once this pr will have been reviewed and validated it should fix your issue https://github.com/medusajs/medusa/pull/2648

**Comment by rrums123** [comment]
@adrien2p that's a very good news! thank you!
