### ISSUE TITLE
Can we show customer based pricing

### ISSUE THREAD

**Issue by harshajayaweeraXHJ** [medusajs/medusa#2474]
Can we show different pricing for each customer based on their login. Customer based pricing?

**Comment by joeyjurjens** [comment]
You can create a price list, I think this is what you mean.
Pricelists can configure price overrides for certain customer groups.

See demo on pricelist: https://demo.medusajs.com/a/pricing?offset=0&limit=15
See demo on customer groups: https://demo.medusajs.com/a/customers/groups?limit=15&offset=0
