### ISSUE TITLE
Gatsby source plugin populating wrong offset value

### ISSUE THREAD

**Issue by r1cs1** [medusajs/medusa#2476]
### Describe the bug

Gatsby source plugin sets wrong offset value when populating data from medusa. It gets stack at querying the second page for products and collections.

### System information

Gatsby-source-medusa version: 0.1.1

### Steps to reproduce the behavior

1. Create more then 20 collections or more than 200 products
2. Run the gatsby starter storefront
3. You will see only the first 20 collections or first 200 products

### Expected behavior

To have all the collections and products.

### Screenshots

<img width="507" alt="Screen Shot 2022-10-20 at 8 44 41 AM" src="https://user-images.githubusercontent.com/14031030/196875454-d1d03ff7-bc88-4d10-8755-7cd24ceed99a.png">

### Code snippets

Example from the plugin source code:
```
      await medusaRequest(storeUrl, path).then(({ data }) => {
        products = [...products, ...data.products]
        count = data.count
        offset = data.products.length
      })
```

should be:

```
      await medusaRequest(storeUrl, path).then(({ data }) => {
        products = [...products, ...data.products]
        count = data.count
        offset = products.length
      })
```

### Additional context

Already have the fix, will create a PR

**Comment by r1cs1** [comment]
PR for the issue #2477

**Comment by olivermrbl** [comment]
Thanks for filing the issue + PR! It should be good to be merged as soon as it has been updated :)

**Comment by adrien2p** [comment]
@r1cs1 I ve answered you on the pr directly, I believe that we can close this issue
