### ISSUE TITLE
[CORE-983] Custom plugin API endpoints dont work when using `peerDependancies` as recommended by the docs

### ISSUE THREAD

**Issue by chiubaca** [medusajs/medusa#2486]
### Describe the bug

custom plugin API endpoints dont work when using `peerDependancies` as recommended by the [docs](https://docs.medusajs.com/advanced/backend/plugins/create#change-dependencies).

> The recommended change is the following: 

```
"peerDependencies": {
  "@medusajs/medusa": "^1.3.1",
  "medusa-interfaces": "^1.3.0",
  "typeorm": "^0.2.36"
},
"devDependencies": {
  "@babel/cli": "^7.14.3",
  "@babel/core": "^7.14.3",
  "@babel/preset-typescript": "^7.14.5",
  "babel-preset-medusa-package": "^1.1.19",
}
```

If your package.json is setup like this, your custom endpoints are not picked up by Medusa server.

### System information

Medusa version (including plugins): "^1.5.0"
Node.js version: v16.13.0
Database: sqlite
Operating system: mac os 12.4
Browser (if relevant): Arc Browser (Chromium based)

### Steps to reproduce the behavior

Follow the [Create a Plugin](https://docs.medusajs.com/advanced/backend/plugins/create) guide from start to end with a custom endpoint like in the [How to Create Endpoint guide](https://docs.medusajs.com/advanced/backend/endpoints/add).

And set up your package.json as per the instructions in the [Change Dependencies](https://docs.medusajs.com/advanced/backend/plugins/create/#change-dependencies) section. 

When finally installing the plugin, the custom API endpoint does not work. 

If you go back to your plugin package.json and update `"peerDependencies"` to `dependencies` , then reload the medusa server this resolves the problem.

### Expected behavior

The custom plugin should load the custom API endpoint as expected.

### Add any other context about the problem here

- I was using `yarn`

<sub>[CORE-983](https://linear.app/medusajs/issue/CORE-983/custom-plugin-api-endpoints-dont-work-when-using-peerdependancies-as)</sub>

**Comment by chiubaca** [comment]
I think related to https://github.com/medusajs/medusa/pull/1860

**Comment by anup-a** [comment]
I'm facing a similar issue with my custom plugin. It appears that my endpoints are not registering. 

I have tried with `medusa new project` . Interestingly, none of the existing plugins (which register new endpoints) seems to work for me.

**Comment by adrien2p** [comment]
We have a pr that allows to pass a custom flag to node `--preserve-symlinks` which will simplify the local development as it is mainly due to how you install and manage your local deps.

**Comment by chiubaca** [comment]
awesome, looking forward to this dropping

**Comment by Pradeepshivaram** [comment]
Even I am facing the same issue, is it fixed? any timeline?

**Comment by olivermrbl** [comment]
Until this issue has been resolved, we will remove the note on peer deps from the documentation. We'll escalate its priority :)
