### ISSUE TITLE
Typo for unique keyword

### ISSUE THREAD

**Issue by ymaheshwari1** [medusajs/medusa#2488]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

There is a typo for `unique` work in the docs

### How can this issue be resolved?

1. Change `unqiue` to `unique`

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by muhammadawaisshaikh** [comment]
I would like to fix this issue

**Comment by ymaheshwari1** [comment]
> I would like to fix this issue

Hi, thanks for the interest, but a PR already exist for this. https://github.com/medusajs/medusa/pull/2502
