### ISSUE TITLE
Saving multipe products in a row doesn't work via the create method.

### ISSUE THREAD

**Issue by haveamission** [medusajs/medusa#2504]
### Describe the bug

Saving multipe products in a row doesn't work via the create method.

### System information

Medusa version (including plugins): 1.5.0
Node.js version: 14.x
Database: Postgres 14?
Operating system: MacOS Monterey

### Steps to reproduce the behavior

1. In a loop, populate an object
2. Save said object using the create method on the product service

### Expected behavior

Multiple products should be saved

### Screenshots

<img width="974" alt="Screen Shot 2022-10-26 at 2 05 32 PM" src="https://user-images.githubusercontent.com/10475533/198102572-955b9d69-1ac7-4bc2-bf56-061e00d37462.png">

This typically happens for several of the created products.

### Code snippets

```
const productService = req.scope.resolve("productService");
  productList.map(async (product) => {
    const newProduct = {
      title: product.attributes.product_name,
      subtitle: null,
      description: product.attributes.part_description,
      handle: null,
      is_giftcard: false,
      thumbnail: product.attributes.thumbnail,
      profile_id: defaultShoppingProfile,
      weight: product.attributes.dimensions.weight
        ? product.attributes.dimensions.weight
        : null,
      length: product.attributes.dimensions.length
        ? product.attributes.dimensions.length
        : null,
      height: product.attributes.dimensions.height
        ? product.attributes.dimensions.height
        : null,
      width: product.attributes.dimensions.width
        ? product.attributes.dimensions.width
        : null,
      hs_code: null,
      origin_country: originCountry,
      mid_code: null,
      material: null,
      created_at: currentTime,
      updated_at: currentTime,
      deleted_at: null,
      metadata: null,
      collection_id: null,
      type_id: null,
      discountable: true,
      status: "published",
      external_id: null,
    };
    productService.create(newProduct);
  });
```

### Additional context

Object is created via an integrated API. All data is unique. Keep getting error about id not existing, even though id is not populated on the product object to be saved.

**Comment by kasperkristensen** [comment]
Closing this as it was resolved in our Discord.
