### ISSUE TITLE
Endpoint for types, add image support

### ISSUE THREAD

**Issue by edihasaj** [medusajs/medusa#2506]
What do you think of creating a new endpoint for querying product types(categories) and adding some images and thumbnail to that so that we can query products by type and show that in the store?

I was thinking if creating a new plugin for this but since there is some existing model there I thought it would be better to change the core API. What do you guys think?

**Comment by edihasaj** [comment]
@srindom?

**Comment by olivermrbl** [comment]
This is an excellent idea @edihasaj. 

We could break this issue into two: creating a new endpoint for fetching product types and adding additional properties to the product type model. Though the latter might not be as straightforward as the former, as we have to rethink our db model, so my suggestion would be to start with the endpoint.

Let me know what you think :)

**Comment by edihasaj** [comment]
Okay, I agree with the plan. I'll jump on endpoint first 😊

**Comment by edihasaj** [comment]
@olivermrbl the endpoints for types are completed.

Can I continue by adding images and thumbnail properties to type object so that we have like a complete categorizing for showing them on store (in my case)?

<img width="374" alt="image" src="https://user-images.githubusercontent.com/34984294/200138731-e0012173-9f56-43c5-828a-005d021c13f0.png">

**Comment by edihasaj** [comment]
I am planning to add types management from admin panel here:
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/34984294/200138798-b72488e2-6244-476c-a3b0-f16a707c77a4.png">

what do you think?

**Comment by edihasaj** [comment]
<img width="925" alt="1" src="https://user-images.githubusercontent.com/34984294/201542516-fb901521-215e-4dbe-aa16-84c8250d254b.png">

Checkout [the admin changes](https://github.com/medusajs/admin/pull/766)

**Comment by srindom** [comment]
@edihasaj - We are moving feature requests to GitHub Discussions to keep better track of the most requested features (using the upvote mechanism) and streamline GitHub Issues around bugs. Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!

**Comment by Coderamrin** [comment]
Hello @edihasaj 
Have you added the image to your category?
I'm trying to do that too. Couldn't seem to find any solution yet. 

Would be great if I could get a hint or a few resources on how to achieve that. 
Thanks
Amrin
