### ISSUE TITLE
TypeError: cmd is not a function at @medusajs\medusa-cli\dist\create-cli.js:260:7

### ISSUE THREAD

**Issue by edardev** [medusajs/medusa#2509]
### Describe the bug

When trying to run medusa develop get the following error:
TypeError: cmd is not a function
    at C:\Users\user\AppData\Roaming\npm\node_modules\@medusajs\medusa-cli\dist\create-cli.js:260:7

### Screenshots
![image](https://user-images.githubusercontent.com/21114220/198388913-c38b62b9-6986-4341-bf9d-56b6140f31fb.png)

**Comment by adrien2p** [comment]
@carlos-r-l-rodrigues i am not the only one apparently
