### ISSUE TITLE
Allow saving multiple handles based on the same title by appending "-N"

### ISSUE THREAD

**Issue by haveamission** [medusajs/medusa#2510]
**Is your feature request related to a problem? Please describe.**
I was trying to save multiple products for a product importation with a custom API. Due to similar titles on the products, this was throwing an error due to duplicate handle

**Describe the solution you'd like**
If there's a duplicate handle, increment it. So for example if you've got a product title like this:

"Product Title"

And it creates a handle like this:

"product-title"

Then if you have another "Product Title", it should look like this:

"product-title-1" and then "product-title-2", etc, etc

**Describe alternatives you've considered**
Some other sort of incrementing system?

**Comment by srindom** [comment]
@haveamission - We are moving feature requests to GitHub Discussions to keep better track of the most requested features (using the upvote mechanism) and streamline GitHub Issues around bugs. Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!
