### ISSUE TITLE
Address Autocomplete + Embedded Shipping Location 

### ISSUE THREAD

**Issue by nicoestrada** [medusajs/medusa#2512]
**Is your feature request related to a problem? Please describe.**
Implementing a shipping address autocomplete feature and adding an embedded map to the order confirmation page. Similar features are found in typical e-commerce platforms to improve conversion rates and other key metrics.

**Describe the solution you'd like**
To optimize the customer journey flow, an autocomplete feature of shipping location from Google Places API / Lob Address Autocomplete API can save the customer time and keystrokes when confirming an order, thus drastically increasing a store's conversion rate. Furthermore, when a customer does confirm an order, implementing an embedded map of the shipping location can provide a clean and satisfactory interface to ensure with the customer the order will be shipped to the correct location. 

**Describe alternatives you've considered**
Perhaps other API's that utilize addresses that are deliverable across the globe

**Additional context**
Implementing these features can also prevent user type errors when confirming an order.

**Comment by srindom** [comment]
@nicoestrada - We are moving feature requests to GitHub Discussions to keep better track of the most requested features (using the upvote mechanism) and streamline GitHub Issues around bugs. Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!
