### ISSUE TITLE
Order return requested in `medusa-plugin-sendgrid` does not work

### ISSUE THREAD

**Issue by PizzaMyHeart** [medusajs/medusa#2513]
### Describe the bug

When creating an order return request on the store page, no email is sent via Sendgrid. Medusa throws the following error: 
`An error occured while sendgrid was processing a notification for order.return_requested: retrieveDocuments must be overridden by the child class`. 

The plugin works as expected for `order-placed-template` and `order-shipped-template`.

### System information

Medusa version (including plugins): 1.3.3 (`medusa-plugin-sendgrid` version is 1.3.3)
Node.js version: 18.10.0
Database: Postgres 14.5
Redis 7.0.5
Operating system: Ubuntu 20.04.5 LTS

I'm using the default Gatsby Medusa storefront.

### Steps to reproduce the behavior

1. Go to 'Create return' on the Gatsby storefront page.
2. Complete the form and click on 'Confirm Return'.
3. No email is sent. The Medusa server log shows the error as below.

### Expected behavior

The customer should receive an email via Sendgrid upon creating a return request on the store page.

### Code snippets

From the Medusa server log:

```
ESC[32minfoESC[39m:    Processing order.return_requested which has 0 subscribers
Error: retrieveDocuments must be overridden by the child class
    at BaseFulfillmentService.retrieveDocuments (/home/ian/clair-server/node_modules/medusa-interfaces/dist/fulfillment-service.js:113:15)
    at FulfillmentProviderService.<anonymous> (/home/ian/clair-server/node_modules/@medusajs/medusa/dist/services/fulfillment-provider.js:260:48)
    at step (/home/ian/clair-server/node_modules/@medusajs/medusa/dist/services/fulfillment-provider.js:48:23)
    at Object.next (/home/ian/clair-server/node_modules/@medusajs/medusa/dist/services/fulfillment-provider.js:29:53)
    at /home/ian/clair-server/node_modules/@medusajs/medusa/dist/services/fulfillment-provider.js:23:71
    at new Promise (<anonymous>)
    at __awaiter (/home/ian/clair-server/node_modules/@medusajs/medusa/dist/services/fulfillment-provider.js:19:12)
    at FulfillmentProviderService.retrieveDocuments (/home/ian/clair-server/node_modules/@medusajs/medusa/dist/services/fulfillment-provider.js:256:16)
    at SendGridService._callee$ (/home/ian/clair-server/node_modules/medusa-plugin-sendgrid/services/sendgrid.js:129:57)
    at tryCatch (/home/ian/clair-server/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:86:17)
ESC[33mwarnESC[39m:    An error occured while sendgrid was processing a notification for order.return_requested: retrieveDocuments must be overridden by the child class
```

`medusa-config.js`:

```
const plugins = [
  `medusa-fulfillment-manual`,
  `medusa-payment-manual`,
  // Uncomment to add Stripe support.
  // You can create a Stripe account via: https://stripe.com
  // {
  //   resolve: `medusa-payment-stripe`,
  //   options: {
  //     api_key: STRIPE_API_KEY,
  //     webhook_secret: STRIPE_WEBHOOK_SECRET,
  //   },
  // },
  {
    resolve: `medusa-file-minio`,
    options: {
        endpoint: process.env.MINIO_ENDPOINT,
        bucket: process.env.MINIO_BUCKET,
        access_key_id: process.env.MINIO_ACCESS_KEY,
        secret_access_key: process.env.MINIO_SECRET_KEY,
    },
  },
  {
    resolve: `medusa-plugin-sendgrid`,
    options: {
      api_key: process.env.SENDGRID_API_KEY,
      from: process.env.SENDGRID_FROM,
      order_placed_template: process.env.SENDGRID_ORDER_PLACED_ID,
      order_shipped_template: process.env.SENDGRID_ORDER_SHIPPED_ID,
      order_return_requested_template: process.env.SENDGRID_ORDER_RETURN_REQUESTED_ID
    }
  }
];
```

**Comment by olivermrbl** [comment]
Thanks for reporting this bug @PizzaMyHeart. It seems our manual fulfillment provider plugin does not implement `retrieveDocuments` defined in the fulfillment provider interface. 

As this is manual fulfillment, the method in the provider should not hold any business logic, but merely return an empty array like so:
```
async retrieveDocuments(_, _) {
   return []
}
```

If you are up for the task, I'd love to accept a PR for it 💪

**Comment by olivermrbl** [comment]
We expect to deprecate `retrieveDocuments` in an upcoming release in favor of method specific to actions. Will close for now.

**Comment by ghost** [comment]
Any updates on this? Running into the same issue.
