### ISSUE TITLE
Center footer content for small screen devices

### ISSUE THREAD

**Issue by developer-diganta** [medusajs/medusa#2548]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

![image](https://user-images.githubusercontent.com/65999534/199973745-f7306406-cb44-4b4d-8bd2-7f682a2e57b4.png)
The footer content can be centered for mobile devices. The space feels a bit extra on the right at present.

### How can this issue be resolved?

1. Change display properties for small screens

### Are you interested in working on this issue?

- [x] I would like to fix this issue

**Comment by NoahMLoomis** [comment]
Hi, I'll take a look at this today

**Comment by shahednasser** [comment]
Thank you @developer-diganta for reporting this but at the moment we are not planning on making changes to this.
