### ISSUE TITLE
Invalid Relation Items on Orders

### ISSUE THREAD

**Issue by raukaute** [medusajs/medusa#2551]
### Describe the bug

When clicking on customer in admin, the request to /admin/orders?[...]&expand=items returns HTTP 400. Checking the [code](https://github.com/medusajs/medusa/blob/a9c703d56c2678fb509af7f9e1fe2cb65f95ba9d/packages/medusa/src/api/routes/admin/orders/index.ts#L237-L238), _items_ does not seem to be part of any order related allowed relations.

### Steps to reproduce the behavior

1. Create draft order and convert to order (mark as paid)
2. Go to customer page, click on customer belonging to the newly created order
3. Order line items will not show. HTTP 400 Bad Request

### Expected behavior

Endpoint accepts items relation on /admin/orders

**Comment by olivermrbl** [comment]
Fixed in an [Admin PR](https://github.com/medusajs/admin/commit/d42d294c3cc016d33a8b59d96dfd8b411955ed92) for now. 

Though, we should def. allow for relations in our API. I've added an issue in our backlog, but I cannot guarantee when it will be included in a release.

**Comment by raukaute** [comment]
Thanks for the hotfix.

After seeing now that this is actually working in the admin demo I am wondering why the items relation was left behind (probably during the implementation of the AllowedAdminOrderRelations)? There is also a [documentation mismatch](https://docs.medusajs.com/api/admin/#tag/Order/operation/GetOrders).

Thanks again for providing the fix for now. Let me know if I can help with any of this.

**Comment by nicolama-dev** [comment]
@olivermrbl  do you plan to re-allow the relation "item" for this API call in the future versions of the medusa-server ?

**Comment by olivermrbl** [comment]
@nicolama-dev Yes indeed! We have plans to align allowed + default relations across all endpoints, though it is not a high priority compared to other projects in our roadmap. 

Happy to elaborate on the feature and accept a PR for it if anyone is up!

cc @raukaute

**Comment by harshmange44** [comment]
@olivermrbl @raukaute  Hey, I'd like to fix this if it's still open. Could you pls give me a brief context?
