### ISSUE TITLE
Endpoint for options, for filtering and stuff

### ISSUE THREAD

**Issue by edihasaj** [medusajs/medusa#2554]
This feature is to modify the core to release two endpoints for querying the product options in order to display in the store as filtering, the reason is that to query all the products from the database just to get the options to show it's not good, so I thought about adding the endpoints.

@olivermrbl this is pretty much the same as #2506

**Comment by srindom** [comment]
@edihasaj - We are moving feature requests to GitHub Discussions to keep better track of the most requested features (using the upvote mechanism) and streamline GitHub Issues around bugs. Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!
