### ISSUE TITLE
Regex in CORS?

### ISSUE THREAD

**Issue by SaadBazaz** [medusajs/medusa#2556]
**Is your feature request related to a problem? Please describe.**
I'm trying to deploy the storefront on Vercel, with the backend hosted on a custom server.

Since, during the build process, the frontend makes requests for static/server side, there are CORS errors which cause it to fail.

I want to temporarily set the CORS to **any** (i.e. *). Doesn't work.

**Describe the solution you'd like**
Regex-based CORS. e.g.:
*.vercel.app (so that I can safely deploy to Vercel for testing).

**Describe alternatives you've considered**
Listing each and every possible domain in Vercel, but that isn't a good solution.

**Comment by srindom** [comment]
Unfortunately, doesn't look like this is possible: https://stackoverflow.com/questions/18439340/using-a-regular-expression-with-cors

**Comment by SaadBazaz** [comment]
The SO thread gives a pretty interesting solution. Plus, since Medusa is based on Express, there must be a package which handles this well.

Also, even * (ANY) would work for testing, but that doesn't seem to work either...

**Comment by olivermrbl** [comment]
I believe @adrien2p has built a potential workaround in #1935. @adrien2p have you test your changes in a prod. + local env?

**Comment by adrien2p** [comment]
I built this https://github.com/medusajs/medusa/pull/1935 which i tested locally and I think some community members tested the pr for their needs as well

**Comment by SaadBazaz** [comment]
Lgtm. When can we get this bros

**Comment by olivermrbl** [comment]
My apologies for the wording here @adrien2p. Did not mean to indicate that it was not the right implementation! 😅 

@SaadBazaz Will be included in the next release coming out later this week or early next 👍
