### ISSUE TITLE
Docs: Add a Note about running migrations when using PostgreSQL database

### ISSUE THREAD

**Issue by fcavalcantirj** [medusajs/medusa#2596]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Following the tutorial (https://docs.medusajs.com/usage/configurations/) when I switched from **sqlite** to **postgres**, I get an error probably because the database is empty - no schema also, it was recently created from scratch.

That said I tried to use **pgloader** to load the file (medusa-db.sql) into my fresh postgres database and the following error occurs;

`mktplace-medusa git:(master) ✗ pgloader sqlite://medusa-db-copy.sqlite pgsql://medusa@127.0.0.1/database
2022-11-12T13:46:05.006498-05:00 LOG pgloader version "3.6.9"
2022-11-12T13:46:05.007643-05:00 LOG Data errors in '/private/tmp/pgloader/'
2022-11-12T13:46:05.049146-05:00 LOG Migrating from #<SQLITE-CONNECTION sqlite:///Users/fcavalcanti/dev/cannapag/cannapag-mktplace-medusa/medusa-db-copy.sqlite {700B9A22F3}>
2022-11-12T13:46:05.049278-05:00 LOG Migrating into #<PGSQL-CONNECTION pgsql://medusa@127.0.0.1:5432/cannapag {700BEF6A83}>
2022-11-12T13:46:05.174180-05:00 **ERROR Database error 22007: invalid input syntax for type timestamp with time zone: "datetime('now')"**
QUERY: CREATE TABLE image 
(
  id         text,
  created_at timestamptz default 'datetime(''now'')',
  updated_at timestamptz default 'datetime(''now'')',
  deleted_at timestamptz,
  url        text,
  metadata   text
);
2022-11-12T13:46:05.174252-05:00 FATAL Failed to create the schema, see above.
2022-11-12T13:46:05.174952-05:00 LOG report summary reset
       table name     errors       rows      bytes      total time
-----------------  ---------  ---------  ---------  --------------
            fetch          0          0                     0.000s
  fetch meta data          0        498                     0.047s
   Create Schemas          0          0                     0.001s
 Create SQL Types          0          0                     0.003s
    Create tables          0          0                     0.000s
-----------------  ---------  ---------  ---------  --------------
-----------------  ---------  ---------  ---------  --------------
➜ pgloader --version
pgloader version "3.6.9"
compiled with SBCL 2.2.10`

### How can this issue be resolved?

1. ~Having a sql file ready for postgres to import?~

1\. Add a note at the end of the "[PostgreSQL Configurations](https://docs.medusajs.com/usage/configurations/#postgresql-configurations)" section to run migrations after changing to a PostgreSQL database.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by saurabh-lohiya** [comment]
Please refer to this post. The syntax varies in _postgres_ for selecting the current time.

**https://www.postgresqltutorial.com/postgresql-date-functions/postgresql-now/**

**Comment by shahednasser** [comment]
Hi @fcavalcantirj thanks for reporting this! It might be worth indicating in the Configure your Server documentation a note on running migrations first when switching to postgres. I'll change the title of this issue to reflect that and open it for contribution.

As for importing the sqlite database to postgres, I think this is out of the scope of the project and this issue in particular.
