### ISSUE TITLE
401 error for `/store/customers/me`

### ISSUE THREAD

**Issue by LWJerri** [medusajs/medusa#2598]
### Describe the bug

A get `401` error only for the `/store/customers/me` API endpoint.

![image](https://user-images.githubusercontent.com/50290430/201525570-080f4a2b-adf3-4df5-80a2-d9712d7f890f.png)

### System information

Medusa version (including plugins):
- medusa-payment-stripe: ^1.1.47
- @medusajs/medusa: ^1.6.0
Node.js version: v18.10.0
Database: PSQL
Operating system: WSL (Ubuntu)
Browser (if relevant): Google Chrome

### Steps to reproduce the behavior

1. Setup basic medusa templates.
2. Use ngrok to extend local port (I did this for Stripe).
3. Setup `.env`.
4. Run all templates.
5. See error.

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

![image](https://user-images.githubusercontent.com/50290430/201525625-5dac0924-baee-4fd9-837c-9702673dcb6a.png)

### Additional context

My `.env`:
```env
# Some other keys.
ADMIN_CORS=http://3f47-31-40-110-219.ngrok.io,http://localhost:7000,http://localhost:7001
STORE_CORS=http://3f47-31-40-110-219.ngrok.io,http://localhost:8000
```

**Comment by olivermrbl** [comment]
The endpoint requires customer authentication, so creating a customer and signing in on the storefront will resolve the "issue".
