### ISSUE TITLE
Adding affiliate marketing to Medusa

### ISSUE THREAD

**Issue by EdiHadzic** [medusajs/medusa#2602]
**The Idea**
I think it would be great idea to add affiliate marketing system to Medusa. So we can leverage this for better store performance and more sales.  Signed in users would be able to share their generated medusa link for other customers and would be able to get parts of profit from item sales.

**Flow**
-User creates an account and generates unique affiliate link for example www.mystore.com/affiliate/UniqueID
-When other user enters the link a cookie is placed storing the ID 
-If user makes a purchase a % of the sale is awarded to the affiliate account 
-Affiliates could be tracked and managed in Admin panel 

**Possible problems**
Sending funds to the affiliates could be problematic. But it could be resolved with paypal integration or manual payments.

**Comment by srindom** [comment]
@EdiHadzic - We are moving feature requests to GitHub Discussions to keep better track of the most requested features (using the upvote mechanism) and streamline GitHub Issues around bugs. Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!
