### ISSUE TITLE
Does medusa-js client export types?

### ISSUE THREAD

**Issue by nxy7** [medusajs/medusa#2613]
Hello, I've recently stumbled upon Medusa and I'm really impressed with it. I've had some problems with types tho and I don't think it's entirely my fault :P
Right now to use medusa types on frontend you need to have medusajs/medusa installed (and to my understanding it's package used on backend), maybe extracting types useful on frontend like 'Product' to other package would be good idea?

**Comment by adrien2p** [comment]
You are right and we are working on a RFC to extract them out of the core package 🙏

**Comment by nxy7** [comment]
Sorry for pointless issue and thanks for answering :-)
