### ISSUE TITLE
SurrealDB support

### ISSUE THREAD

**Issue by mysticaltech** [medusajs/medusa#2615]
**Is your feature request related to a problem? Please describe.**

PostgresDB is universal however, it lacks document and graph capability, and also the ability to easily planet-scale.

**Describe the solution you'd like**

[SurrealDB](https://surrealdb.com/), one of the hottest [open-source](https://github.com/surrealdb/surrealdb) NewSQL DBs now, solves this completely. It supports SQL-like syntax, removes joins, and supports schemaless documents, graphs, and even dynamic javascript computed fields. It's beyond fast and can be planet-scale without a breeze.

**Additional context**

Supporting it would make Medusa even hotter than it is now, by piggybacking on the huge thrust that SurrealDB is undergoing now! 🚀

**Comment by srindom** [comment]
@mysticaltech - We are moving feature requests to GitHub Discussions to keep better track of the most requested features (using the upvote mechanism) and streamline GitHub Issues around bugs. Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!
