### ISSUE TITLE
`medusa user` CLI command create new member as `member` not as `admin`

### ISSUE THREAD

**Issue by LWJerri** [medusajs/medusa#2617]
**Is your feature request related to a problem? Please describe.**
When the user uses the `medusa user -e example@example.com -p password` CLI command medusa generates a new user as `member`, not as `admin`. I think it's can produce some problems in the future.

**Describe the solution you'd like**
I think we can edit create user option and set the default role as `admin` for the CLI command.

**Comment by srindom** [comment]
@LWJerri - We are moving feature requests to GitHub Discussions to keep better track of the most requested features (using the upvote mechanism) and streamline GitHub Issues around bugs. Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!
