### ISSUE TITLE
Filename coventions.

### ISSUE THREAD

**Issue by SGFGOV** [medusajs/medusa#2626]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Can you please explicitly state the filename conventions. As module resolution is dependent on it. 
For example, a service shouldn't have the word "service" appended to the name.
Filenames can have only "-" no "." else the service may not resolve. etc.

### How can this issue be resolved?

1.Spell out the file name conventions to be followed
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by adrien2p** [comment]
The file name convention for services (as an example) will be test.ts and be registered as testService. If you are not sure about what to resolve you can import the formatRegistrationName utility and pass the path to the file and it will give you the right resolution key. It is not perfect though but it can help you 👍

**Comment by shahednasser** [comment]
Hi @SGFGOV the naming convention is mentioned both in the [Services](https://docs.medusajs.com/advanced/backend/services/overview/#what-are-services) and [Create a Service](https://docs.medusajs.com/advanced/backend/services/create-service#implementation) documentations. However, it might be worth adding a sub-heading for naming convention to make it clearer.

I will close this for now. Thanks!
