### ISSUE TITLE
refund_created event not implemented

### ISSUE THREAD

**Issue by AregMatulyan** [medusajs/medusa#2627]
When Admin does a payment refund, it triggers an event "order.refund_created".
But in the SendGrid plugin that functionality is missing.
<img width="758" alt="Screenshot 2022-11-18 at 10 43 33" src="https://user-images.githubusercontent.com/17296862/202671508-38a3c234-ef15-41ee-b13e-b3b363916f39.png">
<img width="800" alt="Screenshot 2022-11-18 at 10 43 51" src="https://user-images.githubusercontent.com/17296862/202671685-7013f9ce-8c57-4040-96d0-35cfd1cebacb.png">
<img width="528" alt="Screenshot 2022-11-18 at 10 45 32" src="https://user-images.githubusercontent.com/17296862/202671953-fe3cb406-1192-409a-9c38-bce12371b411.png">
https://github.com/medusajs/medusa/blob/master/packages/medusa-plugin-sendgrid/src/services/sendgrid.js#L99

**Comment by olivermrbl** [comment]
Thanks, this would be a great addition.

Happy to accept a PR for it. The implementation is quite straight forward as it should follow the same pattern as with [other email templates](https://github.com/medusajs/medusa/tree/master/packages/medusa-plugin-sendgrid).

**Comment by srindom** [comment]
@AregMatulyan - We are moving feature requests to GitHub Discussions to keep better track of the most requested features (using the upvote mechanism) and streamline GitHub Issues around bugs. Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!
