### ISSUE TITLE
Stripe automatic payment capture does not update the order payment status.

### ISSUE THREAD

**Issue by jimmysafe** [medusajs/medusa#2629]
### Describe the bug

When set to `automatic`, medusa-payment-stripe plugin does not update order payment status accordingly.

### System information

Medusa version (including plugins): Medusa version (including plugins): medusa (1.6.3), medusa-payment-stripe (1.1.45), nextjs-starter-medusa (latest)
Node.js version: 16.15.1
Database: postgres
Operating system: MacOS Monteray
Browser (if relevant): Chrome

### Steps to reproduce the behavior

1. Set `capture: true` in `medusa-config.js` stripe plugin configuration
2. Go and complete checkout on nextjs-starter-medusa
4. In stripe dashboard the payment is captured correctly.
5. In medusa admin panel the order payment status stays in Awaiting instead of being Paid.

### Expected behavior

When setting up automatic payment capture we expect to see an updated order payment status that reflects stripe dashboard payment status.

### Screenshots

Stripe Dashboard:

<img width="1396" alt="Screenshot 2022-11-18 at 14 18 39" src="https://user-images.githubusercontent.com/12184812/202714168-c3b919c5-1ddb-4617-bf59-6c1b0c297ffa.png">

Medusa Admin:

<img width="712" alt="Screenshot 2022-11-18 at 14 19 11" src="https://user-images.githubusercontent.com/12184812/202714260-f5632381-2551-428e-b577-78c081fd9e0d.png">

### Code snippets

```
  {
    resolve: `medusa-payment-stripe`,
    options: {
      api_key: STRIPE_API_KEY,
      webhook_secret: STRIPE_WEBHOOK_SECRET, // empty
      capture: true,
    },
  },
```

### Additional context

Add any other context about the problem here

**Comment by oxgen1** [comment]
+1

**Comment by andrea-spotsoftware** [comment]
same for paypal?

**Comment by Bravco** [comment]
+1

**Comment by alessioacella** [comment]
+1

**Comment by HatemAbushaala** [comment]
+1

**Comment by raynay-r** [comment]
Can you please re-open this bug? It is still happening for me with the following versions:
```  json
"dependencies": {
    "@medusajs/admin": "7.1.8",
    "@medusajs/cache-inmemory": "^1.8.9",
    "@medusajs/cache-redis": "^1.8.9",
    "@medusajs/event-bus-local": "^1.9.7",
    "@medusajs/event-bus-redis": "^1.8.10",
    "@medusajs/file-local": "^1.0.2",
    "@medusajs/medusa": "1.18.1",
    "@tanstack/react-query": "4.22.0",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "dotenv": "16.3.1",
    "express": "^4.17.2",
    "medusa-fulfillment-manual": "^1.1.38",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.24",
    "medusa-payment-stripe": "^6.0.6",
    "prism-react-renderer": "^2.0.4",
    "typeorm": "^0.3.16"
}
```
I get the exact same behavior with the exact same configuration like mentioned in the bug description.

There are multiple people in this issue which run into this bug after it was closed. Someone also posted a workaround in the associated PR: https://github.com/medusajs/medusa/pull/3100#issuecomment-1770711681

Thanks!

**Comment by Rahul-kumar-007** [comment]
I am also facing the same issue : 
 my medusa-config.js file conatain these  : 
 "dependencies": {
    "@medusajs/admin": "7.1.8-dev-1705908501580",
    "@medusajs/cache-inmemory": "1.8.10-dev-1705908501580",
    "@medusajs/cache-redis": "1.9.0-dev-1705908501580",
    "@medusajs/event-bus-local": "1.9.7-dev-1705908501580",
    "@medusajs/event-bus-redis": "1.8.10-dev-1705908501580",
    "@medusajs/file-local": "^1.0.2",
    "@medusajs/inventory": "1.11.4-dev-1705908501580",
    "@medusajs/medusa": "1.18.1-dev-1705908501580",
    "@medusajs/stock-location": "1.11.3-dev-1705908501580",
    "@tanstack/react-query": "4.22.0",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "dotenv": "16.3.1",
    "express": "^4.17.2",
    "medusa-file-s3": "1.4.0-dev-1705908501580",
    "medusa-fulfillment-manual": "^1.1.38",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.24",
    "medusa-payment-stripe": "6.0.6-dev-1705908501580",
    "prism-react-renderer": "^2.0.4",
    "typeorm": "^0.3.16"
  },
  
  After  payement is successfull ,when i go to  the admin panel , it is still showing  "Capture  payment" button.

**Comment by woolz** [comment]
+1

**Comment by danielmark0116** [comment]
do you have webhooks set up correctly?

**Comment by Kushal2024** [comment]
Any update on this as getting same issue in razorpay plugin
