### ISSUE TITLE
Concurrent user and admin sessions causes unauthenticated access to other accounts

### ISSUE THREAD

**Issue by a-finocchiaro** [medusajs/medusa#2633]
### Describe the bug

This is a bug with how `req.session` behaves when a user has authenticated as an admin and a customer on the same browser. The jwt holds the authenticated user's ID and the authenticated customer's ID. When a user is authenticated, `req.user` has a `userId` that equals the ID of the authenticated user. Similarly, when a customer is authenticated, `req.user` has a `customer_id` that holds the ID of the customer. 

The problem comes when a user is authenticated as an admin, then authenticates as a customer, the jwt is overwritten. This means that if a user is authenticated as an admin, they can navigate to the storefront and will automatically be logged in as a random customer without needing any credentials. Likewise, if that user logs in as their customer account and then goes to the admin, their session in the admin will change to a random admin user that may or may not be the one they were originally logged in as.

### Steps to reproduce the behavior

1. Configure multiple users and customers in your DB, this makes the problem more obvious
2. Send a `POST` to `/admin/auth` to authenticate as an admin
3. Send a `GET` to `/store/auth` and it will return a random customer, indicating that customer is "authenticated"

In the storefront/admin UI it can be replicated like this:

DO THIS ON THE SAME BROWSER IN SEPARATE TABS
1. authenticate in the admin UI
2. navigate to the storefront, and a random customer will be logged in
3. log out as that customer and in as another (or the same customer, it probably doesn't matter)
4. go back to the admin and the session will change to a random admin user but will not require authentication.

### Expected behavior

The expected behavior is where I am a little confused and would like a little bit of guidance from the Medusa team. On my project that I use medusa for, I made it so only 1 session can be active at a time. This seems like the best solution security-wise to me, but also I wasn't really sure of how to manage 2 concurrent sessions without having leaking like this and random weird issues.

I would like to know if the medusa team thinks that only allowing one active session is the way to solve this, or if there is a way to manage 2 concurrent sessions. If there is, I would like a little guidance on how that could be done, because I've looked for solutions there but nothing seems like it would work for this use case. 

### Additional context

The following things should probably be changed to solve the issue:

- `UserService.retrieve` and `CustomerService.retrieve` should not return a user record when `undefined` is passed as an ID. It should probably throw an error, but I noticed that throwing an error in either of these methods causes the medusa server to crash when used with the admin UI. Via API the error is handled correctly though, so I don't understand why the server doesn't handle the throw properly instead of crashing. In the fix in my project, I make it just `return` so the user or customer is `{}`
- The `req.session` should either be cleared before another authentication for both store and admin to force a single session, or there should be some way to handle 2 concurrent sessions. In the fix for my local project, I clear the session on every new auth request in a middleware to force a single active session.

I would love to contribute a solution for this since I already have looked at it quite a bit and developed a patch in the project I have been using medusa for, I think I would just want some guidance first on how the medusa team thinks the sessions should be handled. 

Thank you!

**Comment by jbeckton** [comment]
wow, I wonder what other security flaws medusa has?

**Comment by olivermrbl** [comment]
@a-finocchiaro Highly appreciate the elaborate description of the issue as well as the reproducible steps!

We'd be more than happy to accept a PR for this - the sooner, the better 💪 

In regards to session handling, we will discuss it internally and get back to you as soon as possible. Until then, I think we should aim to push a (potentially temporary) fix to eliminate the security concern immediately.

**Comment by a-finocchiaro** [comment]
@olivermrbl no problem at all! Let me know too if your team has any questions when you all discuss it.

I will put something together and get a PR written for you all to review in the meantime to mitigate the security concern.

Thanks for the response!

**Comment by olivermrbl** [comment]
@a-finocchiaro Deleting this issue for security reasons. Can I get you to reach out on Discord or email for follow up discussion?
