### ISSUE TITLE
Docker build fail for npm install

### ISSUE THREAD

**Issue by amirping** [medusajs/medusa#2636]
### Describe the bug

Building the  docker file will fail because of the nom installation step.

`RUN npm install -g npm@latest` will try to install the last version of node, which not compatiable with the node version used in the dockerfile '17.1.0'
to fix it u need to update the dockerfile and change 
`RUN npm install -g npm@latest`
with 
`RUN npm install -g npm@8.1.2`

### System information

Medusa version (including plugins):
Node.js version: 17.1.0
Database: postgresql
Operating system: macos
Browser (if relevant):

### Steps to reproduce the behavior

1. run docker-compose up

### Expected behavior

Should install compatible NPM version to that specific node version.

**Comment by olivermrbl** [comment]
Thanks for reporting @amirping. We'd be happy to accept a PR, if you are up for it :)

**Comment by amirping** [comment]
Hello @olivermrbl , done :D.

**Comment by pKorsholm** [comment]
Closing this as I've merged the pr, thanks again for your contribution @amirping 😄
