### ISSUE TITLE
node module flag for cli

### ISSUE THREAD

**Issue by devsamuelv** [medusajs/medusa#2638]
**Is your feature request related to a problem? Please describe.**
I have an issue with the medusa cli I have a medusa server project included in a turbo repo project, however because of how turbo repo handles project dependencies they are all located in one central node_modules directory however because its not where medusa expects it I can't use `medusa develop` which depends on babel from node_modules.

**Describe the solution you'd like**
I would like the `medusa develop` command to have an optional flag that allows the user to specify the location of the node_modules file instead of assuming that it's always going to be located in the medusa project.

**Describe alternatives you've considered**
I thought of linking the node_modules in the medusa project to the turborepo node_modules folder however that is not a scalable solution.

**Additional context**
```
hustle-store:dev: The system cannot find the path specified.
hustle-store:dev: Error: Command failed: "C:\Users\capts\Desktop\code\org\Elite-Digital-Crew\turborepo-test\apps\hustle-store\node_modules\.bin\babel" src -d dist
hustle-store:dev:     at checkExecSyncError (node:child_process:828:11)
hustle-store:dev:     at execSync (node:child_process:899:15)
hustle-store:dev:     at C:\Users\capts\Desktop\code\org\Elite-Digital-Crew\turborepo-test\node_modules\@medusajs\medusa\dist\commands\develop.js:82:42
hustle-store:dev:     at step (C:\Users\capts\Desktop\code\org\Elite-Digital-Crew\turborepo-test\node_modules\@medusajs\medusa\dist\commands\develop.js:33:23)
hustle-store:dev:     at Object.next (C:\Users\capts\Desktop\code\org\Elite-Digital-Crew\turborepo-test\node_modules\@medusajs\medusa\dist\commands\develop.js:14:53)
hustle-store:dev:     at C:\Users\capts\Desktop\code\org\Elite-Digital-Crew\turborepo-test\node_modules\@medusajs\medusa\dist\commands\develop.js:8:71
hustle-store:dev:     at new Promise (<anonymous>)
hustle-store:dev:     at __awaiter (C:\Users\capts\Desktop\code\org\Elite-Digital-Crew\turborepo-test\node_modules\@medusajs\medusa\dist\commands\develop.js:4:12)
hustle-store:dev:     at default_1 (C:\Users\capts\Desktop\code\org\Elite-Digital-Crew\turborepo-test\node_modules\@medusajs\medusa\dist\commands\develop.js:74:12) {
hustle-store:dev:   status: 1,
hustle-store:dev:   signal: null,
hustle-store:dev:   output: [ null, null, null ],
hustle-store:dev:   pid: 48840,
hustle-store:dev:   stdout: null,
hustle-store:dev:   stderr: null
hustle-store:dev: }
```

**Comment by srindom** [comment]
@devsamuelv - We are moving feature requests to GitHub Discussions to keep better track of the most requested features (using the upvote mechanism) and streamline GitHub Issues around bugs. Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!

**Comment by jeroenkroese** [comment]
I have created a feature request here: https://github.com/medusajs/medusa/discussions/4424
