### ISSUE TITLE
Docs(Code Issue): Code Issue in 'Override Price Selection' Page

### ISSUE THREAD

**Issue by 204050** [medusajs/medusa#2643]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I have found two issues:

1. In section **1** the example injects a ProductService with the name `productsService`, however the `productsService` does not exist. I think it should be `productService`.
2. When injecting the `productService` instead the DIC complains about a cyclic dependency.

Tested on a fresh installation of medusa using the cli.

### How can this issue be resolved?

A service which does not violate the dependency chain could be used as a better example instead.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for reporting this! @204050 Will make sure this issue is resolved 👍🏻
