### ISSUE TITLE
Docs(local-development): Getting started with local development of medusa (core/backend) - Not updating change made to medusa

### ISSUE THREAD

**Issue by flashjames** [medusajs/medusa#2644]
**Is your feature request related to a problem? Please describe.**
Make it easier to understand how to get changes made to local https://github.com/medusajs/medusa/ to propagate to own medusa backend.

I'm getting familiar medusa to implement localization for my own project.

And to familiarize myself I needed a local develop enviroment.
https://docs.medusajs.com/usage/local-development was of help to get started.

I forked https://github.com/medusajs/medusa/ cloned and then ran "medusa-dev --set-path-to-repo `pwd`"

I ran "npx create-medusa-app" and got the following directory structure:
`(base) prox@prox-MS-7A70:~/byq/my-medusa-store$ ls -lah
total 20K
drwxrwxr-x  5 prox prox 4,0K nov 21 14:09 .
drwxrwxr-x 11 prox prox 4,0K nov 21 14:03 ..
drwxrwxr-x  9 prox prox 4,0K nov 21 14:16 admin
drwxrwxr-x  8 prox prox 4,0K nov 21 14:17 backend
drwxrwxr-x  7 prox prox 4,0K nov 21 14:09 storefront`

cd byq/backend for two terminals and ran:
- medusa-dev
- yarn start

So I decided to make a change in https://github.com/medusajs/medusa/blob/master/packages/medusa/src/loaders/index.ts
`const stratAct = Logger.success(stratActivity, "Strategies initialized222445993") || {}`

And it didnt propagate to byq/backend/ (yarn start)

To get it to get propagated I had to do:
~/byq/medusa/packages/medusa$ yarn watch

**Describe the solution you'd like**
Either add this to https://docs.medusajs.com/usage/local-development or possibly even better make medusa-dev automatically do this.

**Additional context**
I can make a PR for this, but I would like to know if this is intended to be like it is or if my ideas above are good.

I got stuck with this for a few hours, so I figured this may be a problem for other's getting started developing medusa.

Also I found this page very late - https://docs.medusajs.com/usage/create-medusa-app feel like this way should be mentioned as early as this page: https://docs.medusajs.com/quickstart/quick-start

Or alternatively under: https://docs.medusajs.com/tutorial/set-up-your-development-environment

**Comment by denerFernandes** [comment]
Hi @flashjames, yesterday I also started studying jellyfish with the same goal. And I agree with you, the way this is done is unclear, moreover the medusa-dev cli copies the files to the server's node-modules, but the server watch doesn't look at the node_modules.

Off Topic: Can you tell me how you think about implementing localization, I have the same goal.

**Comment by flashjames** [comment]
@denerFernandes  I'll be working on localization today, think I figured out how to do it in a clean way yesterday, without making changes to core medusa. Will update when I've written enough code.

**Comment by shahednasser** [comment]
Thank you for reporting this @flashjames I'll make sure we add the necessary information regarding the watch command in our documentation!

**Comment by behrouz-shafaati** [comment]
The local development documentation in [this link](https://docs.medusajs.com/v1/development/fundamentals/local-development) does still work for Medusa v2?
