### ISSUE TITLE
Thirdparty or Verified authentication for storefront clients.

### ISSUE THREAD

**Issue by anand-010** [medusajs/medusa#2673]
I am a newbie and trying to implement medusajs but on the documentation the only authentication method for client users is email password and uses no email verification or forgot password methods.
Integration with Aws cognito, Firebase or Auth0 is the best methods to do it quickly.
A customisable function, module or plugin on ther server to verify jwt token from firebase or others and load information associated with userid on serverside would be sececure way to do it.

**Comment by olivermrbl** [comment]
Closing this in favor of this Discussion touching upon the same topic. 

We are planning to scope an authentication abstraction soon, that will allow you to seamlessly add other authentication strategies than the one shipped as default.
