### ISSUE TITLE
Square Payments Integration

### ISSUE THREAD

**Issue by JanieHuang** [medusajs/medusa#2674]
**Is your feature request related to a problem? Please describe.**
I want to be able to integrate and use Square payments as a plugin. 
https://developer.squareup.com/reference/square/payments-api

**Describe the solution you'd like**
A plugin to use Square payments. Basically the stripe plugin, but for Square 

**Describe alternatives you've considered**

**Additional context**
I have a POS with Square with my in-person payments. Ideally, I would like to stick to one platform and also use Square for online transactions as well so I can pull sales reports from one place (Square)

**Comment by srindom** [comment]
Hi @JanieHuang - there is currently no timeline for adding Square payments to the official plugins. That said, it is easy to create a payment provider for Medusa if you (or someone else) are up for it, I would recommend that you build it.

There is a guide to building payment plugins here: https://docs.medusajs.com/advanced/backend/payment/how-to-create-payment-provider/

I will be happy to do a review on your work if you just @-mention me in your repo :)

**Comment by srindom** [comment]
@JanieHuang - We are moving feature requests to GitHub Discussions to keep better track of the most requested features (using the upvote mechanism) and streamline GitHub Issues around bugs. Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!
