### ISSUE TITLE
Updating a shipping_address or billing_address field erases country_code

### ISSUE THREAD

**Issue by chemicalkosek** [medusajs/medusa#2682]
### Describe the bug

When updating either shipping_address or billing_address field it also makes `country_code` `null`

### System information

Medusa version (including plugins): 1.6.4

### Steps to reproduce the behavior

1. Create a cart
2. Update shipping_address.country_code and first_name
```javascript
//route:
POST /store/carts/{cartId}
//payload
{
    "shipping_address": {
        "country_code": "pl",
        "first_name": "LeBron"
    }
}
```
3. Update shipping address last_name
```javascript
//route:
POST /store/carts/{cartId}
//payload
{
    "shipping_address": {
        "last_name": "James"
    }
}
```
4. See `country_code` being `null` in the response. `first_name` is intact.

### Expected behavior

`country_code` is not made null in shipping_address or billing_address when updating its fields.

**Comment by olivermrbl** [comment]
Thanks for reporting this one! Fix coming in #2683
