### ISSUE TITLE
Draft order email should be optional

### ISSUE THREAD

**Issue by josetr** [medusajs/medusa#2686]
**Is your feature request related to a problem? Please describe.**
I want to make an anonymous sale, in-person, where the customer may not want to provide an email.

**Describe the solution you'd like**
Draft order API shouldn't require an email

**Comment by olivermrbl** [comment]
Thanks for filing this issue @josetr. It is an excellent suggestion. Will make sure to add it to our backlog.

Also, happy to accept a PR for it 💪

**Comment by srindom** [comment]
@josetr - We are moving feature requests to GitHub Discussions to keep better track of the most requested features (using the upvote mechanism) and streamline GitHub Issues around bugs. Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!
