### ISSUE TITLE
`q` parameter not working from the product endpoint with sales channels enabled

### ISSUE THREAD

**Issue by durdenx** [medusajs/medusa#2688]
### Describe the bug

When i use the `q` (search) parameter from the product endpoint with sales channels enabled i get the following error:

```
error:   No entity column "sales_channel_id" was found.
EntityColumnNotFound: No entity column "sales_channel_id" was found.
```

### System information

Medusa version (including plugins):

- "@medusajs/medusa": "^1.6.4",
- "@medusajs/medusa-js": "^1.3.3",
- "@medusajs/medusa-cli": "^1.3.4",
- "medusa-fulfillment-manual": "^1.1.31",
- "medusa-interfaces": "^1.3.3",
- "medusa-payment-manual": "^1.0.16",
- "medusa-payment-stripe": "^1.1.47",
- "typeorm": "^0.2.45"
- SALES CHANNELS enabled
- Node.js version: 18.12.1
- Database: postgres 13.8
- Operating system: MacOS 12.6.1
- Browser (if relevant): 107.0.5304.110

### Steps to reproduce the behavior

```ts
await ctx.medusa.admin.products.list({
  sales_channel_id: salesChannelId,
  q: "something",
  offset,
  limit,
});
```

### Expected behavior

The query won't crash.

**Comment by srindom** [comment]
Hi @durdenx, can you check that you have run your migrations after enabling the sales channels feature flag? 

```
$ medusa migrations run
```

**Comment by durdenx** [comment]
Hi @srindom,

Yes i have run migrations. `sales_channel` and `product_sales_channel` tables have been created in the database.

Btw filtering from the sales_channel_id seems to work.
