### ISSUE TITLE
Error: Network Error starting medusa storefront nextjs service

### ISSUE THREAD

**Issue by robertomlj** [medusajs/medusa#2691]
I installed medusa storefront nextjs, updated all the packages, made all the necessary settings in next.config.js and store.config.js, but whenever I start the service, I receive the following error in the browser:

![1](https://user-images.githubusercontent.com/53835386/204356018-623bcbd4-b683-4851-b995-ab93ea922d34.png)

Errors in browser console:

![2](https://user-images.githubusercontent.com/53835386/204356088-2bac244f-fd84-403a-90c9-75088e217590.png)

Errors in network browser:

![3](https://user-images.githubusercontent.com/53835386/204356179-08459114-42a8-4f0c-9d50-fcf3d774131c.png)

It seems to me to be a CORS error, but I correctly configured the url of store_cors and admin_cors in the medusa-server .env

![4](https://user-images.githubusercontent.com/53835386/204356827-3bf8175f-5e96-4e63-9f57-ce74b6c0f54c.png)
![5](https://user-images.githubusercontent.com/53835386/204356862-01dff30b-b0d9-4574-9914-21774643221a.png)
![6](https://user-images.githubusercontent.com/53835386/204356887-eec39224-de4d-4899-a8fa-09aa950c0e65.png)

Services and versions:

<sub>
Node.js v16.16.0,
@medusajs/medusa v1.6.3,
medusa-react v3.0.1",
next v12.2.0,
react v17.0.2,
</sub>

**Comment by chemicalkosek** [comment]
You have forgot to remove the issue number from starter repo issue 😉

Can you `console.log(STORE_CORS)` inside medusa-config.js and see what it prints

**Comment by robertomlj** [comment]
![Captura de tela de 2022-11-29 10-02-33](https://user-images.githubusercontent.com/53835386/204549431-ff5db4f5-e26a-4be1-a922-25d66331a818.png)

**Comment by chemicalkosek** [comment]
Looks good. Are you running this in some VM or docker?

**Comment by robertomlj** [comment]
I don't know what could have happened, but I had to restart my machine and as soon as the system booted, the error just disappeared!!!!

![Captura de tela de 2022-11-29 10-36-20](https://user-images.githubusercontent.com/53835386/204557751-5a2dc832-ca1e-4593-bdc5-052d7fa44712.png)

**Comment by chemicalkosek** [comment]
Great, close both issues then :)
