### ISSUE TITLE
`medusa-file-s3` plugin fails on `export-orders` Batch Job

### ISSUE THREAD

**Issue by diselostudio** [medusajs/medusa#2693]
### Describe the bug

Hi there 👋 
I've installed the `medusa-file-s3` plugin into my eCommerce and set up to work with my Amazon account. Right after that I've tested it by editing some products media and all good there, I got the proper assets on the bucket. But when running actions that trigger a batch-job I get an error reading: 

`"code":"unknown","message":"Please add a file service plugin in order to manipulate files in Medusa"`

I ve also tried my own service extending the `AbstractFileService` class using some s3 compatible providers or Cloudinary, and I  get the same result there. So I am thinking that maybe the problem is on the batch-job itself getting injected a different FileService as the message I get is the one at the default file service:

https://github.com/medusajs/medusa/blob/master/packages/medusa/src/services/file.ts

Thank you so much in advance.

### System information

Medusa version (including plugins): 1.6.5 
Node.js version: 18
Database: PostgreSQL
Operating system: MacOS 

### Steps to reproduce the behavior

1. Install `meduse-file-s3` plugin.
2. Request a `export-orders` batch-job (can do it from Admin panel)
3. Watch incoming request in console
4. Batch process should fail

### Expected behavior

A .csv file shows up in the configured bucket.

**Comment by olivermrbl** [comment]
@diselostudio I can't seem to reproduce your issue.

Have you installed the S3 plugin in your `medusa-config.js` ?

```
const plugins = [
  {
    resolve: `medusa-file-s3`,
    options: {
      s3_url: "some_url",
      bucket: "some_bucket",
      access_key_id: "",
      secret_access_key: "",
      region: "",
    },
  },
];
```

**Comment by diselostudio** [comment]
Hi @olivermrbl thanks for your quick response.
Yes, did all the steps and have the configuration running and already working for other uploads. The thing is that I get the same error on any service extending AbstractFileService. 

Is there any way to debug dependencies that get injected on the batch-job process ?
Thanks

**Comment by pKorsholm** [comment]
Hi @diselostudio 

I think you might be running an older version of the s3 plugin from before the necessary operations for batch jobs were implemented, which happened in version 1.1.6.

Can you verify that the `medusa-file-s3` version you are running is either 1.1.6 or newer (1.1.7 is the latest release)?

**Comment by diselostudio** [comment]
Hi @pKorsholm yes, I do have `"medusa-file-s3": "^1.1.7"` on my package.json. As said before, this is happening on any Service extending the AbstractFileService.

**Comment by olivermrbl** [comment]
@diselostudio Can I get you to try the following:
- Delete `/dist` folder in your own project
- Remove your custom abstract file service
- Install latest `@medusajs/medusa` + `medusa-file-s3` (sounds like you've already done this)
- Attempt to export orders once more

**Comment by olivermrbl** [comment]
@diselostudio Any updates?
