### ISSUE TITLE
Add Multi-Vendor feature

### ISSUE THREAD

**Issue by docimin** [medusajs/medusa#2698]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add the ability to allow (Multi-)Vendors to sell Digital & Physical products, the ability for them to create shipment tracking (DHL, USPS etc.), as well as automatic transfers (payments) through Stripe Connect & PayPal.

**Comment by srindom** [comment]
@docimin - We are moving feature requests to GitHub Discussions to keep better track of the most requested features (using the upvote mechanism) and streamline GitHub Issues around bugs. Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!
