### ISSUE TITLE
Medusa-plugin-auth breaks sign in with user and password. 

### ISSUE THREAD

**Issue by juansoler** [medusajs/medusa#2708]
### Describe the bug

Hey there, I configured sign in with Google and it works. But now I have a problem, the normal login (user and password) is not working. If I disabled medusa-plugin-auth it works again normal login.  

https://github.com/medusajs/medusa/blob/6cea109caa7d859fb3e4dd8beaff3d35246ed8f3/packages/medusa/src/api/routes/store/customers/index.ts#L37

Doing some reach, the problem is there(link above), it changes something so get-customer it's not called. If that line is commented the normal login works and google sign in works but stopped working sign out from the account 🤣

Adrien talk about it in Discord and there is a posible solution. 

https://discord.com/channels/876835651130097704/1027894657444741120/1047809668178792450

### System information

Medusa version (including plugins): 1.6.5
Node.js version: 14
Database: postgres
Operating system: ubuntu 22.04
Browser (if relevant):

### Steps to reproduce the behavior

1. Go to 'Sign in.'
2. Write credentials 
3. Click on ''Sign"
4. It throws an error (customer doesn't exist)
5. See error

### Expected behavior

It's expected to be signed and redirect to home screen already logged. 

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here
@adrien2p

**Comment by adrien2p** [comment]
Can I get you to open it in the auth plugin repo please as it is a bug during the process of aligning the auth plugin to the security fix from medusa
