### ISSUE TITLE
Notes attached to a draft order are lost when converting it to a normal order

### ISSUE THREAD

**Issue by josetr** [medusajs/medusa#2720]

**Comment by josetr** [comment]
> as we don't support notes on draft orders

From what I understand, you can attach notes to any resource, including those that don't exist, at least that's what the source code is telling me, but if you do attach a note to a draft order, there is no code that would make sure it's kept once the draft order is a converted to a normal order.

Shopify API allows you to attach a note to a draft order. I don't see a reason why we shouldn't support the same thing.

**Comment by olivermrbl** [comment]
> as we don't support notes on draft orders in our admin system.

Yes, I was referring to the lack of support from a UI perspective. You'd have to do it directly through the API. That's why I want to understand your use case :)

**Comment by josetr** [comment]
I'm just making customs changes on my admin fork to fit my needs. One of them is adding the ability to attach notes to draft orders. It seems like a normal use case that most other people will eventually need, as a draft order should be as close as possible to a normal order.

**Comment by olivermrbl** [comment]
After giving this some thought, I believe introducing this logic would be an opinionated decision as it is not a given that all businesses want their draft order notes to be transferred to their related order. 

I recommend adding a subscriber to `order.placed` or `draft_order.completed` that copies the note from the draft order to the order. 

Hope this makes sense :)

**Comment by josetr** [comment]
It is not a given that all businesses want their draft order notes to disappear either. Shopify does keep the draft order note when it's converted, and if MedusaJS is marketed as "The Open Source Shopify Alternative", shouldn't we behave as similarly as possible unless there is a good reason not to?

Removing some data from a draft order when it's converted to a normal order doesn't seem like the right default behavior to me. It certainly won't be the expected default from all the people that are migrating from Shopify.

**Comment by olivermrbl** [comment]
Completely understand the rationale. That said, our extensibility allows you to achieve this exact functionality without forcing notes to be transferred, so we actually cater to both cases - which I believe is even better :)

The subscriber would look like:
```ts
class OrderSubscriber {
  constructor({ eventBusService, noteService }) {
    this.eventBus_ = eventBusService

    this.noteService_ = noteService

    this.eventBus_.subscribe("draft_order.completed", this.addNoteToOrder)
  }

  addNoteToOrder = async (data) => {
    const doNotes = await this.noteService_.list({ resource_id: data.id }) // query notes for draft order

    // add notes to order
    await Promise.all(
      doNotes.map(async (note) => {
        await this.noteService_.create({
          resource_id: data.order_id,
          resource_type: "order",
          message: note.message,
          user_id: note.user_id,
        })
      })
    )
  }
}

export default OrderSubscriber

```

**Comment by josetr** [comment]
It's certainly better to have the ability to support both use cases as you've shown in the example, however, I still think it's the wrong default. I believe the people that actually want their draft order notes to disappear are the minority. Most businesses want to keep as much data related to their customers as possible, not less.
