### ISSUE TITLE
Export types

### ISSUE THREAD

**Issue by finom** [medusajs/medusa#2739]
**Is your feature request related to a problem? Please describe.**
By the time being I have to use long paths to extract data types and the only data type I've used so far is Product and it's retrieved that way:

```js
import { Product } from '@medusajs/medusa/dist/models/product';
```

**Describe the solution you'd like**
I'd like those types to be exported nicely like

```js
import { Product } from '@medusajs/medusa';
```

**Comment by kasperkristensen** [comment]
Hi @finom, you should be able to import types the way would like to:

```ts
import { Product } from "@medusajs/medusa"
```
The only reason I can think of that would prevent that from being possible, would be if you are running a very old version of Medusa, from when we first started our TS migration.

**Comment by finom** [comment]
@kasperkristensen sorry, my bad, you're right.
