### ISSUE TITLE
Removing discount from cart doesn't remove line adjustments from database

### ISSUE THREAD

**Issue by josetr** [medusajs/medusa#2742]
### System information

Medusa version (including plugins): 1.6.5
Node.js version: 18.12.0
Database: PostgreSQL
Operating system: Windows 10
Browser (if relevant):

### Steps to reproduce the behavior

1. Create 20% off discount
2. Create draft order using 20% discount
4. Remove discount https://docs.medusajs.com/api/admin/#tag/Draft-Order/operation/PostDraftOrdersDraftOrder

If you now fetch the draft order, all the line items will still report "adjustments", even tho they have no effect.

### Expected behavior

The adjustments property for each line item should be empty after removing all discounts

### Screenshots

![image](https://user-images.githubusercontent.com/37419832/206417005-b52998eb-e2d3-402a-84d2-30469ce0523f.png)

**Comment by olivermrbl** [comment]
Thanks for reporting this. We will attend to this asap. 

Though, you can rest assured that the adjustments will not be included in totals computation.

**Comment by josetr** [comment]
I did mention that it has no effect but the problem that I now have is that since the returned adjustments property is incorrect, and the `[post] /admin/draft-orders/{id}` response is the result of calling `orderService.retrieve` rather than `orderService.retrieveWithTotals`, I have no way to get the new line item price, other than fetching the whole order using `[get] /admin/draft-orders/{id}` once again, which will actually use `retrieveWithTotals`.

Perhaps all the endpoints that modify the order should use `orderService.retrieveWithTotals` rather than `orderService.retrieve`?

What do you think?

**Comment by olivermrbl** [comment]
Got it! Yes, I think we should definitely use `retrieveWithTotals` in all endpoints.

**Comment by olivermrbl** [comment]
Should be solved in [this PR](https://github.com/medusajs/medusa/pull/2667). Item totals is added in `retrieve`.

**Comment by josetr** [comment]
> Should be solved in [this PR](https://github.com/medusajs/medusa/pull/2667). Item totals are added in `retrieve`.

This PR modifies `OrderService`, not `DraftOrderService` so it won't solve my issue.

I've also noticed that some draft order endpoints call orderService.retrieve inside the db transaction and some others call after the transaction scope ends. There is no consistency.

**Comment by olivermrbl** [comment]
OP's issue resolved in #2751. If you want to track your issue regarding totals calculation, please open a new one :)
