### ISSUE TITLE
"redis_url not found. A fake redis instance will be used."

### ISSUE THREAD

**Issue by komali2** [medusajs/medusa#2749]
### Describe the bug

In my digitalocean deployment of medusajs server's console, I'm doing

```
npm install @medusajs/medusa-cli -g
medusa user --email <EMAIL> --password <PASSWORD>
```

And see an error about redis. However, I have the redis server url set as per the readme: 

https://docs.medusajs.com/deployments/server/deploying-on-digital-ocean

https://docs.medusajs.com/deployments/server/deploying-on-digital-ocean

My config looks like: 

```
DB_USERNAME=${db.USERNAME}
DB_PASSWORD=${db.PASSWORD}
DB_HOST=${db.HOSTNAME}
DB_PORT=${db.PORT}
DB_DATABASE=${db.DATABASE}
REDIS_URL=${redis.DATABASE_URL}
JWT_SECRET=<<redacted>>
COOKIE_SECRET=<<redacted>>
NPM_CONFIG_PRODUCTION=false
NODE_ENV=production
ADMIN_CORS=<<redacted>>
```

I appear to have redis attached:

![Screenshot from 2022-12-09 14-36-55](https://user-images.githubusercontent.com/8533113/206640366-194e6194-5cc3-4bea-a235-b9b044f3a6f8.png)

### System information

Medusa version (including plugins): Current
Node.js version: `v16.18.1`
Database: Postgresql
Operating system: whatever digital ocean gave me

### Steps to reproduce the behavior

1. Verbatim follow instructions for deployment to digital ocean

### Expected behavior

I expect redis database URL to resolve properly. 

### Screenshots

See above, happy to upload more as needed. 

### Code snippets

None

**Comment by shahednasser** [comment]
Hi @komali2 , can you share your `medusa-config.js`? Make sure to remove any secrets from the code before posting it here

**Comment by komali2** [comment]
Thanks, it appears the redis URL project config property is commented by default.

**Comment by impactcolor** [comment]
The error also happens on install thou.  Using the install command before the user has the config file.  It gives the error on the. build.
`✔ Project Built
An error occurred while preparing project: Error: An error occurred while running migrations: [medusa-config] ⚠️ redis_url not found. A fake redis instance will be used.`

**Comment by tossivahva** [comment]
By default in `medusa-config.ts` there is a 'missing?' line: 

`redisUrl: process.env.REDIS_URL`
