### ISSUE TITLE
Import Products Stuck in Processing

### ISSUE THREAD

**Issue by himanshuahuja96** [medusajs/medusa#2756]
### Describe the bug
In my microtica.com deployment product import is not working. It is stuck in processing for the last 20 minutes. I am using the default sample data file for import.

### System information

Medusa version (including plugins): 
  "dependencies": {
    "@medusajs/medusa": "^1.6.0",
    "@medusajs/medusa-cli": "^1.3.3",
    "medusa-file-s3": "^1.1.7",
    "medusa-fulfillment-manual": "^1.1.31",
    "medusa-interfaces": "^1.3.3",
    "medusa-payment-manual": "^1.0.16",
    "medusa-payment-stripe": "^1.1.45",
    "typeorm": "^0.2.36"
  },

Node.js version: node:16.16.0
Database: sqllite

### Steps to reproduce the behavior

1. Go to 'Products'
2. Click on 'Import Products'
3. Scroll down to 'Unsure about how to arrange your list?'
4. Download Sample file
5. Upload

### Expected behavior
It should successfully import the file.

### Screenshots
<img width="844" alt="Screenshot 2022-12-09 at 10 42 58 PM" src="https://user-images.githubusercontent.com/18248507/206827469-05ef095c-242f-4b1f-bffe-b3e0b8a2b8ae.png">

**Comment by olivermrbl** [comment]
Does your server log contain any errors related to the product import?

**Comment by adrien2p** [comment]
And does the batch job in the db contains any errors?

**Comment by RegisHubelia** [comment]
I've had that with a stuck import batch.  Ended up stopping the instance, truncate-cascate the table batch_job and restart the instance and it was fine.

**Comment by nilsegger** [comment]
I had the same problem and get the following error:

An error occurred while processing batch.created: Error: The csv file parsing failed due to: Unable to treat column Product External ID from the csv file. No target column found in the provided schema
Error: The csv file parsing failed due to: Unable to treat column Product External ID from the csv file. No target column found in the provided schema.

**Comment by adrien2p** [comment]
The first issue should now display an error. We still need to update the template

**Comment by olivermrbl** [comment]
> The csv file parsing failed due to: Unable to treat column Product External ID from the csv file

@nilsegger Not directly related to OPs issue, but I believe you are facing this issue because the column is named `Product External Id` with a lowercase `d` in `Id`

**Comment by adrien2p** [comment]
@olivermrbl looks like you already updated the template. @nilsegger is your admin up to date?

**Comment by nilsegger** [comment]
> > The csv file parsing failed due to: Unable to treat column Product External ID from the csv file
> 
> @nilsegger Not directly related to OPs issue, but I believe you are facing this issue because the column is named `Product External Id` with a lowercase `d` in `Id`.
> 
> Can I get you to try that?

@olivermrbl the lowercase d was not the problem. It was the lowercase `i` in `Product Id`, upper case `d` in `Product External ID`, lowercase `i` in `Variant Id`, lowercase `b` in `Variant Allow Backorder`, lowercase `i` in `Variant Manage Inventory`.

With these headers I got it working:
`Product Id;Product Handle;Product Title;Product Subtitle;Product Description;Product Status;Product Thumbnail;Product Weight;Product Length;Product Width;Product Height;Product HS Code;Product Origin Country;Product MID Code;Product Material;Product Collection Title;Product Collection Handle;Product Type;Product Tags;Product Discountable;Product External Id;Product Profile Name;Product Profile Type;Variant Id;Variant Title;Variant SKU;Variant Barcode;Variant Inventory Quantity;Variant Allow Backorder;Variant Manage Inventory;Variant Weight;Variant Length;Variant Width;Variant Height;Variant HS Code;Variant Origin Country;Variant MID Code;Variant Material;Price EUR;Price USD;Option 1 Name;Option 1 Value;Image 1 Url;Image 2 Url`

@adrien2p I downloaded it a bit over a week ago, could be that I'm already no longer up to date...

**Comment by olivermrbl** [comment]
The product import template was [updated last week](https://github.com/medusajs/admin/pull/829)

**Comment by IgorKhomenko** [comment]
We also face Import stuck when there is something wrong with the template data

Should it really stuck rather than properly processing and report an error?

**Comment by adrien2p** [comment]
@IgorKhomenko the error is stored on the batch job and can be used in the ui to display the error.  The job status once failed should have changed. You can see in the results if there is any error.

@olivermrbl didn’t we already did something to display the errors back to the user?

**Comment by olivermrbl** [comment]
We haven't added the descriptive UI yet. @IgorKhomenko Did you manage to solve your issue?

**Comment by IgorKhomenko** [comment]
@olivermrbl I implemented job errors UI (in drawer), that was pretty straight forward. 

There is just one very strange thing.
Sometimes, when an error happens in background job, the jobs API got stuck, means it started returning http 504 status code infinitely, until the server restarted.

**Comment by AbhinavChavareTechcopain** [comment]
An error occurred while processing batch.created: TypeError: Cannot read properties of undefined (reading 'withTransaction') how to solve this any comments?
this error is getting me while I am customising the strategy imports.,I want add storeid inside the products table while importing the products .csv file

**Comment by AbhinavChavareTechcopain** [comment]
When we try to customize the strategy imports and specify the static batchType = "product-import" 

preprocessing fails what should I do?

**Comment by rpfelgueiras** [comment]
I am unable to import product and I get the following error: fileService.uploadProtected is not a function
The batch job is not even created. 
What is the problem? Any help please?
