### ISSUE TITLE
Personalized field in product options

### ISSUE THREAD

**Issue by juansoler** [medusajs/medusa#2757]
**Describe the solution you'd like**
Hi, It would be nice that product contains a text field which the customer can write down text when is selecting the options of the product. 

Ex: A cup of coffee with your name

Color: Red
Text to print: Medusa JS

Another problem related is that once the order is placed, it doesn't appear the options selected in Medusa Admin. Just appear the variant. 

THANK YOU!

**Comment by adrien2p** [comment]
When creating a line item in your cart, you can pass a metadata object. You might add a metadata into your product or variant to tell that it is customisable and require a name, use that to display it properly in your store and when the customer add it to the cart, you get this data and store it in the metadata of the line item you will create on the cart. 

@patrick-medusajs @riqwan here it looks like another example for custom attributes which would be to know that the product is customisable and maybe the type of input you want to show and its name to then save it later on the line item of the cart to be then used by the store.

**Comment by juansoler** [comment]
@adrien2p thank you for your response. I'll try and share it. Thank you!

**Comment by srindom** [comment]
@juansoler - We are moving feature requests to GitHub Discussions to keep better track of the most requested features (using the upvote mechanism) and streamline GitHub Issues around bugs. Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!
