### ISSUE TITLE
Typo in medusa js-client documentation

### ISSUE THREAD

**Issue by jhoffmann99** [medusajs/medusa#2790]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In https://docs.medusajs.com/references/js-client/classes/CartsResource is a typo.

In the sentence "If not provuided, we will generate one for the request." is a typo. Instead of "provided" it says "provuided".

### How can this issue be resolved?

1. Update the readme file. Replace the incorrect "provuided" with the word "provided"
2.
3.
...

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for finding this @jhoffmann99 ! Feel free to go ahead and work on this 🙂
