### ISSUE TITLE
Can't clone medusa repository because of invalid file path on windows

### ISSUE THREAD

**Issue by jhoffmann99** [medusajs/medusa#2794]
### Describe the bug

The master branch contains file paths that are considered invalid on windows OS.

The error message is:
invalid path 'docs/api/admin/code_samples/JavaScript/publishable-api-keys_:id_sales-channels/getundefined'

### System information

Medusa version (including plugins): doesn't matter
Node.js version: doesn't matter
Database: doesn't matter
Operating system: windows
Browser (if relevant): doesn't matter

### Steps to reproduce the behavior

1. Fork the official medusa repository
2. On your windows local machine clone the previously forked medusa repository
3. See the error in the terminal window

### Expected behavior

The repository get's cloned to the local machine and the master branch is checked out.

### Screenshots

![Uploading image.png…]()

### Additional context

The bug was introduced yesterday.

**Comment by jhoffmann99** [comment]
![medusa-invalid-file-path](https://user-images.githubusercontent.com/42183679/207549109-79b3692b-9c72-4609-8ee3-519fc88926a7.png)

**Comment by shahednasser** [comment]
Thank you for reporting this @jhoffmann99 ! This seems to be an issue with the API reference documentation generated from comments in one of our new endpoints. Will create a PR to fix it!

**Comment by shahednasser** [comment]
This issue should be fixed now @jhoffmann99 can you try again?

**Comment by jhoffmann99** [comment]
I tried it again. The bug is fixed.
