### ISSUE TITLE
[CORE-909] Missing user sign up documentation

### ISSUE THREAD

**Issue by finom** [medusajs/medusa#2806]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I'm trying to find out how to sign up a user but it seems like documentation doesn't have this information https://docs.medusajs.com/api/store/#tag/Auth

### How can this issue be resolved?

Give an advice and add a note to the documentation on how to register a user. Thanks!

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

<sub>[CORE-909](https://linear.app/medusajs/issue/CORE-909/missing-user-sign-up-documentation)</sub>

**Comment by shahednasser** [comment]
Resolved in #2910
