### ISSUE TITLE
Edit Variant Button glitched

### ISSUE THREAD

**Issue by AltayAkkus** [medusajs/medusa#2822]
## Bug report
When trying to edit a variant, the radix button is put under the next variant, so the UI becomes very ugly.

### Describe the bug
The `z-index` set to the radix button does not work properly, because the parent element is neither `position: relative` nor does it have a own `z-index` set, so the `z-index` of the parent div is automatically higher than the highest child `z-index`, so our radix button is not shown over the elements.

### System information

Medusa version (including plugins): demo.medusajs.com, so latest.
Node.js version: demo.medusajs.com
Database: demo.medusajs.com
Operating system: Windows 10
Browser (if relevant): Firefox (latest) and Chrome (latest)

### Steps to reproduce the behavior

1. Go to [demo.medusajs.com](https://demo.medusajs.com/a/products/prod_01GMD3C4K9STFS7MAA0V8G9K6A)
2. Click on Variants -> Edit Variants
3. Click a random three-point menu
![grafik](https://user-images.githubusercontent.com/7849969/208301883-c94185ed-11c0-4def-bf1f-e8dc2c7f054c.png)
### Expected behavior

![grafik](https://user-images.githubusercontent.com/7849969/208301987-d68a4e42-863d-40a9-b157-63d8e67231af.png)

**Comment by olivermrbl** [comment]
Thanks for filing an issue. I cannot reproduce it on my Mac, so it must be tied to your OS. Can I get you to open the issue in our [admin repository](https://github.com/medusajs/admin) and we'll have a look at it asap?

**Comment by jhoffmann99** [comment]
I'm interested in fixing the bug. Can you assign it to me ?

**Comment by olivermrbl** [comment]
That's great @jhoffmann99! Feel to give it a go :)

**Comment by jhoffmann99** [comment]
I was able to reproduce the issue on my windows 10 machine. However I couldn't find a solution yet.

**Comment by AltayAkkus** [comment]
I can fix the bug when someone points me to the correct file, I could not find it :D

**Comment by AltayAkkus** [comment]
[Reported](https://github.com/medusajs/admin/issues/842) and [fixed](https://github.com/medusajs/admin/pull/843)
