### ISSUE TITLE
Docs: add git as in the prerequisites section of the Quickstart Guide

### ISSUE THREAD

**Issue by shahednasser** [medusajs/medusa#2850]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Developers that don't have git installed will get an error when they run the `medusa new` command. So, it should be added in the prerequisites section.

### How can this issue be resolved?

1. Add git to the list of prerequisites in the Quickstart guide. You can link to [our docs](https://docs.medusajs.com/tutorial/set-up-your-development-environment#git) on how to install it.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by akarsh-jain-790** [comment]
@shahednasser I would like to fix this issue

**Comment by shahednasser** [comment]
Sure I've assigned you @akarsh-jain-790
