### ISSUE TITLE
MedusaJS Installation errors. 

### ISSUE THREAD

**Issue by eduleongh** [medusajs/medusa#2895]
Hi

I hope someone can help me.

I tried to install MedusaJS on Debian11(raspberry version).

node -v =  v12.22.12
npm -v = 7.5.2

I run bellow and i get an error. 

root@raspberry:~# npm install -g @medusajs/medusa-cli
medusa new my-store --seed
cd my-store
medusa develop
npx create-next-app -e https://github.com/medusajs/nextjs-starter-medusa my-storefront
Even tried with
npm exec create-medusa-app --legacy-peer-deps

added 293 packages, and audited 294 packages in 18s

37 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

![Personal_22 1_cJ7tVfpISY](https://user-images.githubusercontent.com/69003815/209359713-4a1d9742-29ec-4c12-8f39-1dfe72b645a7.png)
![Personal_22 1_I3XhiDwUJY](https://user-images.githubusercontent.com/69003815/209359716-d23cf9c6-39f5-4fcf-886f-56e796adddd6.png)
![Personal_22 1_qqT3bpBEWf](https://user-images.githubusercontent.com/69003815/209359719-0c3ebf70-89f8-44a9-8e1b-3ac40c79f21b.png)
![Personal_22 1_jM3sq9HaB2](https://user-images.githubusercontent.com/69003815/209359721-49fe668c-61a9-42b5-8fea-f61e32072007.png)

**Comment by InderdeepBajwa** [comment]
Not a bug. Please run `npm install` in the directory before running `medusa develop`

**Comment by olivermrbl** [comment]
@eduleongh I can't seem to reproduce. Can I get you to ensure you are using the latest CLI version by running `npm install -g @medusajs/medusa-cli`?
