### ISSUE TITLE
[service]: OrderService

### ISSUE THREAD

**Issue by srindom** [medusajs/medusa#29]
We need an order service that can create orders from a cart, handle communication with payment 
and fulfillment providers and manage returns, changes etc.

**Comment by srindom** [comment]
Order Statuses: "not fulfilled", "fulfilled", "completed", "archived", "canceled", "returned"

- create
- update
- cancel (only possible if payment not captured and order not shipped)
- return (takes returned LineItems)
  - automatically refund money depending on payment provider
- capturePayment
   - check payment method
   - get provider
   - call `provider.capture`
- createFulfillment
   - check shipping methods
   - get fulfillment providers
   - send order(s) to fulfillment provider (note: the order may need partition depending on how many shipping profiles the line items cover.)

**Comment by olivermrbl** [comment]
Do you we provide the order to `provider.capture` or should we fetch a `totalsService.getTotal()` and give that as argument?
