### ISSUE TITLE
Stripe Plugin 500 from Server on Checkout - StripeInvalidRequestError Invalid integer NaN

### ISSUE THREAD

**Issue by fxmb** [medusajs/medusa#2919]
## Bug Report
- When checking out in storefront the "spinner" for stripe payments spins indefinitely
- Server returns constant 500 with `StripeInvalidRequestError Invalid integer NaN `
- Unable to perform a stripe payment

## Solution
- We downgraded our Stripe plugin version to `1.1.49` on the server which seemed to have resolved the issue.
- [This](https://github.com/medusajs/medusa/pull/2743/files#diff-72cc0018e2ea0d7f2d5aad7bd7c0ce4da3151d22975ca52cbf45048ff1beaebc) is the suspicious commit that might have caused the issue

👉 [The Discord discussion around this issue and how it was resolved](https://discord.com/channels/876835651130097704/1057742575013998774/1057742575013998774)

**Comment by olivermrbl** [comment]
Thanks for reporting this one @fxmb. We will investigate asap. Most core engineers are out-of-office these days, so will likely be at the beginning of the new year. Hope this is cool!

**Comment by olivermrbl** [comment]
Just looping in @adrien2p to eventually look at this issue.

**Comment by adrien2p** [comment]
The latest version of medusa stripe requires medusa >= 1.7.1 whereas medusa >= 1.7.1 is backwards compatible with any version of medusa stripe.

Cc @olivermrbl

**Comment by adrien2p** [comment]
https://discord.com/channels/876835651130097704/1057742575013998774/1059035487244914688

For reference

Cc @olivermrbl

**Comment by olivermrbl** [comment]
Thanks for chiming in @adrien2p!
