### ISSUE TITLE
[CORE-945] ComparisonOperator validation does not work as documented in Medusa API docs.

### ISSUE THREAD

**Issue by dwene** [medusajs/medusa#2925]
## Bug report
As far as I can tell, none of api query param based comparison operators work.

ex: https://docs.medusajs.com/api/store/#tag/Region/operation/GetRegionsRegion

states I should be able to filter regions by their created_at date by doing something like this.

`/store/regions?created_at={"gt":"2019-08-24T14:15:22Z"}`

But I always receive a validation error saying

`nested property created_at must be either object or array.`

This appears to be true of all query param based api requests where fields that have `DateComparisonOperator` and `NumericComparisonOperator`

I was able to solve this using medusa-extender by using the `@Transform` annotation like this:

```
export const jsonSerializedObjectMapper = value => {
  if (typeof value === 'string' && value.startsWith('{') && value.endsWith('}')) {
    try {
      return JSON.parse(value);
    } catch (error) {
      return value;
    }
  }
};
...



export class StoreGetRegionsParams {
....

  @IsOptional()
  @ValidateNested()
  @Transform(({ value }) => jsonSerializedStringMapper(value))
  @Type(() => DateComparisonOperator)
  updated_at?: DateComparisonOperator
}

```

But maybe I'm incorrectly serializing the object as a query param for it to work with express automatically?

### System information

Medusa version (including plugins): 1.7.2
Node.js version: 16
Database: PG
Operating system: N/A
Browser (if relevant): N/A

### Steps to reproduce the behavior

1. try going to url ${MEDUSA_API_URL}/store/regions?created_at={"gt":"2019-08-24T14:15:22Z"}
2. Notice validation error

### Expected behavior

API filters by created_at date as described.

<sub>[CORE-945](https://linear.app/medusajs/issue/CORE-945/comparisonoperator-validation-does-not-work-as-documented-in-medusa)</sub>

**Comment by olivermrbl** [comment]
To parse objects as query params in Express, you must use the bracket notation. The one you’ve attached here, would be:
[url]/admin/orders?created_at[lt]=2019-08-24T14:15:22Z

[This blog post](https://masteringjs.io/tutorials/express/query-parameters) details the topic quite well.

Thanks for filing the issue. It would make sense to add an entry in our documentation on this 👍
