### ISSUE TITLE
Collection metadata is null at @medusajs/medusa-js

### ISSUE THREAD

**Issue by finom** [medusajs/medusa#2936]
### Describe the bug

`medusa.collections.list()` returns the list but all items have `metadata: null`. At the same time if I use REST API `/store/collections` the metadata field contains the metadata.

<img width="113" alt="image" src="https://user-images.githubusercontent.com/1082083/210424084-8a5d3e22-085e-4b23-ad6d-3efc99279d90.png">

<img width="1654" alt="image" src="https://user-images.githubusercontent.com/1082083/210424322-9ccd4e3d-a60a-4b3a-8354-9786573570d9.png">

### System information

Medusa version (including plugins): 1.3.5
Node.js version:
Database: PostgreSQL
Operating system: MacOS
Browser (if relevant): Not relevant

### Steps to reproduce the behavior

1. Create a collection at medusa admin
2. Add custom metadata
3. Check what `medusa.collections.list()` and `/store/collections` return

### Expected behavior

Metadata should include the metadata

**Comment by olivermrbl** [comment]
I can't seem to reproduce your issue. Metadata is showing up in my response running with `@medusajs/medusa-js@1.3.5` and `@medusajs/medusa@1.7.0`. From what type of client are you consuming the JS SDK?

**Comment by finom** [comment]
Sorry, that's my side issue...
