### ISSUE TITLE
Sendgrid Giftcard - this.giftCardService_ is undefined in medusa-plugin-sendgrid/src/sendgrid.js

### ISSUE THREAD

**Issue by RegisHubelia** [medusajs/medusa#2938]
## Bug report

When adding the gift_card_created_template configuration to the medusa-plugin-sendgrid, and try to add a custom gift card from the admin panel, an error occurs in the backend "Cannot read properties of undefined (reading 'retrieve')".  Upon investigation, I found that the "this.giftCardService_" is not defined in the class SendGrid 

`
class SendGridService extends NotificationService {
  static identifier = "sendgrid"

  /**
   * @param {Object} options - options defined in `medusa-config.js`
   *    e.g.
   *    {
   *      api_key: SendGrid api key
   *      from: Medusa <hello@medusa.example>,
   *      order_placed_template: 01234,
   *      order_updated_template: 56789,
   *      order_canceled_template: 4242,
   *      user_password_reset_template: 0000,
   *      customer_password_reset_template: 1111,
   *    }
   */
  constructor(
    {
      storeService,
      orderService,
      returnService,
      swapService,
      cartService,
      lineItemService,
      claimService,
      fulfillmentService,
      fulfillmentProviderService,
      totalsService,
      productVariantService,
    },
    options
  ) {
    super()

    this.options_ = options

    this.fulfillmentProviderService_ = fulfillmentProviderService
    this.storeService_ = storeService
    this.lineItemService_ = lineItemService
    this.orderService_ = orderService
    this.cartService_ = cartService
    this.claimService_ = claimService
    this.returnService_ = returnService
    this.swapService_ = swapService
    this.fulfillmentService_ = fulfillmentService
    this.totalsService_ = totalsService
    this.productVariantService_ = productVariantService
`

But is called at line 579:

`
async gcCreatedData({ id }) {
    const giftCard = await this.giftCardService_.retrieve(id, {
      relations: ["region", "order"],
    })

    if (!giftCard.order) {
      return
    }
`

### System information

Medusa version (including plugins):
        "@medusajs/medusa": "^1.7.2",
        "@medusajs/medusa-cli": "^1.3.5",
        "@sendgrid/mail": "^7.7.0",
        "aws-sdk": "^2.1281.0",
        "dayjs": "^1.11.7",
        "express": "^4.18.2",
        "medusa-core-utils": "^1.1.37",
        "medusa-extender": "^1.7.8",
        "medusa-fulfillment-manual": "^1.1.33",
        "medusa-interfaces": "^1.3.3",
        "medusa-payment-manual": "^1.0.18",
        "medusa-payment-paypal": "^1.2.6",
        "medusa-payment-stripe": "^1.1.50",
        "medusa-plugin-mailchimp": "^1.1.43",
        "medusa-plugin-sendgrid": "^1.3.4",
        "meilisearch": "^0.30.0",
        "typeorm": "^0.2.36"

**Comment by olivermrbl** [comment]
Solved in #2941
