### ISSUE TITLE
Deploy Your Medusa Server on Heroku - STACKHERO_REDIS_URL_TLS now REDIS_URL_TLS

### ISSUE THREAD

**Issue by edwardwcorbett** [medusajs/medusa#2944]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Running 'heroku config:get STACKHERO_REDIS_URL_TLS' returns nothing but 'heroku config:get REDIS_URL_TLS' returns the information needed in the next step

### How can this issue be resolved?

1. Update STACKHERO_REDIS_URL_TLS to REDIS_URL_TLS in the documentation

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
[Stackhero's documentation](https://devcenter.heroku.com/articles/stackhero-redis#provisioning-the-add-on) still names this configuration as `STACKHERO_REDIS_URL_TLS` but will look into it in case.
