### ISSUE TITLE
Medusa Starter Contentful README.md - typo

### ISSUE THREAD

**Issue by edwardwcorbett** [medusajs/medusa#2946]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In the prerequisites section, the second sentence starts with "Please not.." and it should start with "Please note.."

### How can this issue be resolved?

1. Update the second sentence of the prerequisites section of the Medusa Starter Contentful README.md to "Please note the Contentful plugin requires Redis."

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for opening this issue @edwardwcorbett but I believe this issue/PR should be opened in the [medusa-starter-contentful](https://github.com/medusajs/medusa-starter-contentful) repository instead.
