### ISSUE TITLE
Docs(Code Issue): Code Issue in /advanced/backend/payment/how-to-create-payment-provider/

### ISSUE THREAD

**Issue by Toti91** [medusajs/medusa#2957]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Hello! When copying the example service from the docs, typescript complains that `AbstractPaymentService` is not generic.

https://docs.medusajs.com/advanced/backend/payment/how-to-create-payment-provider/#create-a-payment-provider

![image](https://user-images.githubusercontent.com/16031201/211034534-8f6777f6-9441-430b-a9df-292e07603744.png)

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
This has been fixed now. Thank you!
