### ISSUE TITLE
Billing and shipping addresses not present in server's response when customer logs in

### ISSUE THREAD

**Issue by Hemann55** [medusajs/medusa#2977]
### Describe the bug

Customer registers, goes through the checkout flow, successfully places an order and logs out.

The customer then logs back in but previously entered billing and shipping addresses are not present in the server's response

According to docs, medusa.auth.authenticate({email:__, password:__}) should return previously entered billing and shipping addresses on successfully login. This would be helpful to auto-fill the data for subsequent checkouts

### System information

Medusa version: 1.7.1
Node.js version: 18.12.1
Database: postgres
Operating system: Manjaro Linux

### Expected behavior

Medusa server should return previously entered billing and shipping addresses

**Comment by Hemann55** [comment]
Sorry I was not clear earlier. I did add them separately

For adding a billing address -
medusa.customers.update({billing_address: payload})

For adding a shipping address -
medusa.customers.addresses.addAddress({ address: payload })

This works for the logged in session and I get the customer object with added addresses in the server's response. No issues here.

But if the customer logs out and logs back in, the authentication endpoint -
medusa.auth.authenticate({email:, password:}) does not return the previously entered addresses. Which IMO and according to docs(https://docs.medusajs.com/api/store/#tag/Auth/operation/PostAuth), it should.

**Comment by olivermrbl** [comment]
Sorry for the misunderstanding. You are absolutely right. 

I don't find the issue pressing, so I can't give it high priority internally, but if you are up for it, I'd love to accept a PR. You would need to add the default relations in the call to retrieve the customer [here](https://github.com/medusajs/medusa/blob/dd87e62536d66f4edd492af5d551d3d361eb2a29/packages/medusa/src/api/routes/store/auth/create-session.ts#L93). The default relations are exported from [this file](https://github.com/medusajs/medusa/blob/dd87e62536d66f4edd492af5d551d3d361eb2a29/packages/medusa/src/api/routes/store/customers/index.ts#L78). If you tackle this, we should extend those relations with `order, order.items`.
