### ISSUE TITLE
[CORE-985] Issue with draft orders using custom products

### ISSUE THREAD

**Issue by RegisHubelia** [medusajs/medusa#3001]
When creating a draft order with custom items and trying to mark the draft order as paid - I end up with the error message "Tax line must be joined in order to calculate taxes" - but the order is created and is marked as paid.  When you try to go in the order (from the admin panel) - we end up having a spinner that never stops.  After looking at the logs on the backend side, I can see that there are no "variant" as the field is null.  

The issue seems to be that  a default variant should be created/linked when adding a custom product - or the draft orders processes should be reviewed following the "new-totals" addition back in november.  My guess is that while building this - draft orders weren't considered.

The 1st line that causes an issue when trying to view the order is line 115 of new-totals.ts

        if (items.some((item) => !item.variant)) {
          throw new MedusaError(
            MedusaError.Types.INVALID_DATA,
            "Unable to fetch tax lines to compute line item totals as one of the item variant is missing but required for the tax lines to be computed. Might be due to a missing relation items.variant"
          )
        }

Commenting makes it so it go further but gives another error along the way about variant not being joined.

<sub>[CORE-985](https://linear.app/medusajs/issue/CORE-985/issue-with-draft-orders-using-custom-products)</sub>

**Comment by olivermrbl** [comment]
Thanks for reporting this one. We'll give it highest priority!

**Comment by olivermrbl** [comment]
Will be part of v1.7.4 :)

**Comment by DidierGuyon** [comment]
I am encountering this issue on Medusa version: `1.20.6`, the error that I am getting is: `Cannot compute line item refund amount, tax lines are missing from the line item`. Error comes from
 `if (!isDefined(lineItem.tax_lines)) {
      throw new MedusaError(
        MedusaError.Types.UNEXPECTED_STATE,
        "Cannot compute line item refund amount, tax lines are missing from the line item"
      )
   }`
    line 361 till 366 from new-totals service
