### ISSUE TITLE
How to Install a specific version instead of latest one.

### ISSUE THREAD

**Issue by chiragjain1293** [medusajs/medusa#3032]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Hi,

Doc seem to be installing latest version only, where frontend is broken. Is there any way to install any other version or doc pointing to how to use any other version.

TIA

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [x] I would like to fix this issue

**Comment by olivermrbl** [comment]
Not entirely sure, what package you are referring to, but you can specify version when installing:
```
yarn add @medusajs/medusa@1.7.3
// or
npm install @medusajs/medusa@1.7.3
```

Closing this issue as it is unrelated to Medusa.
