### ISSUE TITLE
Loaders last file not registered

### ISSUE THREAD

**Issue by maxpanakov** [medusajs/medusa#3056]
## Bug report
i have loaders on my project and the last one is always an registed, to fix that i added empty file called z.js, to fix it, but it's weird 
![image](https://user-images.githubusercontent.com/9987863/213169756-12478075-27d7-4fa3-97ea-f13e8b36f909.png)

Medusa version (including plugins):1.7.3
Node.js version:16
Database:post
Operating system:ubuntu
Browser (if relevant):

**Comment by olivermrbl** [comment]
I have tried to debug this one a couple of times by now, and it seems to be related to how the JS code is compiled. The only possible solution I can provide right now is to try to build your project using `tsc` instead of babel, as they produce two different outputs.
