### ISSUE TITLE
[medusa]: ValidateEmail_ function

### ISSUE THREAD

**Issue by klefcodes** [medusajs/medusa#307]
In `UserService` there is a function called `ValidateEmail_`. I guess what it is meant to do is to validate an email address. But currently what it's doing is just returning the `email`.

This can be found in `medusa/src/services/user.js`

@srindom kindly look into it. Thanks 🙂

**Comment by albertpak** [comment]
👋 hi - @klefcodes @srindom what were you thinking about doing here? just a simple regex? or implementation of some sort of service, i.e.

- [SendGrid|Email Address Validation API](https://sendgrid.com/solutions/email-api/email-address-validation-api/)
- [Mailgun|emial validation](https://www.mailgun.com/email-validation/)
- [Various APIs](https://rapidapi.com/collection/email-validation-verification-api)
