### ISSUE TITLE
GetProductTypes operation documentation for JS Client is wrong

### ISSUE THREAD

**Issue by IgorKhomenko** [medusajs/medusa#3096]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Following this page 
https://docs.medusajs.com/api/store/#tag/Product-Type/operation/GetProductTypes

it provides a JS Client example:

```
import Medusa from "@medusajs/medusa-js"
const medusa = new Medusa({ baseUrl: MEDUSA_BACKEND_URL, maxRetries: 3 })
// must be previously logged in or use api token
medusa.store.productTypes.list()
.then(({ product_types }) => {
  console.log(product_types.length);
});
```

which seems to be wrong, cause there is no `store` property in `medusa` object: https://github.com/medusajs/medusa/blob/master/packages/medusa-js/src/index.ts#L34

But there is a direct property `productTypes`, so an example should look like the following:

```
import Medusa from "@medusajs/medusa-js"
const medusa = new Medusa({ baseUrl: MEDUSA_BACKEND_URL, maxRetries: 3 })
// must be previously logged in or use api token
medusa.productTypes.list()
.then(({ product_types }) => {
  console.log(product_types.length);
});
```

### How can this issue be resolved?

1. Update JS Client documentation for GetProductTypes operation

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch! Thanks for reporting this
