### ISSUE TITLE
@medusajs/medusa v1.7.5 - Module '"@medusajs/medusa"' has no exported member 'AbstractPaymentProcessor'

### ISSUE THREAD

**Issue by kevin-aminzadeh** [medusajs/medusa#3113]
### Describe the bug
The `@medusajs/medusa` package doesn't currently export the new Payment Processor interfaces. 

This issue comes to light when following the official _**How to Create a Payment Provider**_ documentation which appears to be outdated and uses the deprecated `AbstractPaymentService` interface in the examples.

Using the `AbstractPaymentService` interface as per the docs, leads to the following TS warning/error:

> @deprecated — use the AbstractPaymentProcessor instead
>
> 'AbstractPaymentService' is deprecated.

However since the Payment Processor interfaces aren't currently exported in `interfaces/index.d.ts`, `AbstractPaymentProcessor` can't be imported from `@medusajs/medusa` and has to be imported directly from `@medusajs/medusa/dist/interfaces/payment-processor` instead which isn't immediately obvious.

### System information

Medusa version (including plugins): v1.7.5
Node.js version: v18.12.1
Database: N/A
Operating system: Windows 11
Browser (if relevant): N/A

### Steps to reproduce the behavior

1. Follow the official _**Create a Plugin**_ documentation [here](https://docs.medusajs.com/advanced/backend/plugins/create/) to create a plugin boilerplate.
2. Follow the official _**How to Create a Payment Provider**_ guide [here](https://docs.medusajs.com/advanced/backend/payment/how-to-create-payment-provider/) and create the payment provider service boilerplate (`src/services/my-payment.ts`) as per the documentation.
4. Note the deprecation warning when extending the `AbstractPaymentService`
5. Verify that the recommended `AbstractPaymentProcessor` interface provided in the warning can't be imported from `@medusajs/medsa`
6. Review `node_modules/@medusajs/medusa/dist/interfaces/index.d.ts` and verify that the `AbstractPaymentProcessor` interfaces are not being exported.

### Expected behavior

`PaymentProcessor` interfaces should be exported members of `@medusajs/medusa` and documentation should be in sync with implementation.

### Screenshots

![medusa-interface-bug](https://user-images.githubusercontent.com/62059361/214732732-d52dfd4f-3106-48ee-b86a-a5d34f0ebf11.jpg)
![medusa-interface-bug-2](https://user-images.githubusercontent.com/62059361/214732745-cfc2e124-b3a1-4906-91a7-7263854136ff.jpg)

**Comment by olivermrbl** [comment]
@adrien2p Any chance you could have a look at this one?

**Comment by adrien2p** [comment]
@olivermrbl @kevin-aminzadeh the payment processor is not yet released entirely. It was a mistake to mark it as deprecated. You should use the AbstractPaymentService and not paying attention to the deprecation message. We have a pr which should be merged soon and will allow you to use the new approach. One last thing and it will be merged and part of the next release. After that, the deprecated method will still be supported for a little while since our current payment plugins also depends on it.

Sorry for the miss leading here
