### ISSUE TITLE
Typo in the Admin Setup & Deployment section of the Developer Docs

### ISSUE THREAD

**Issue by CatherineKiiru** [medusajs/medusa#3115]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

There's is an error in the Test it out > Demo Credentials paragraph, under the Setup and Deployment section. The command reads as this:

npm run seed

But it should actually be:

npm run --seed. 

I'd like to take on this issue and make the correction.

### How can this issue be resolved?

1. Making a correction to the documentation.
2.
3.
...

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for reporting this issue @CatherineKiiru , but it's actually not incorrect. As the paragraph mentions, if you forget to add the `--seed` option to the `medusa new` command while creating the server, you can later run the `seed` command to seed your database.

I'll be closing this issue now. Let me know if it's not so clear 🙂

**Comment by CatherineKiiru** [comment]
It makes sense now. Thank you for the clarification.

**Comment by shahednasser** [comment]
Thanks for the tip @CatherineKiiru !
