### ISSUE TITLE
[CORE-1123] Validate input to order creation

### ISSUE THREAD

**Issue by finom** [medusajs/medusa#3119]
### Describe the bug

I'm trying to complete an order with the following code:

```
const { cart } = await medusa.carts.createPaymentSessions(medusaCartId)
await medusa.carts.setPaymentSession(medusaCartId, {
        provider_id: cart.payment_sessions[0].provider_id, // manual
})
const { type, data } = await medusa.carts.complete(medusaCartId);
```

But the last line throws an error.

![](https://uploads.linear.app/6afc998d-0125-4bd5-a791-94d2bbd42b7c/10a9ff5d-3769-432d-9a50-7a594f4e2c09/d8114171-a721-4d18-8ce4-e3d71c8e63b6)

![](https://uploads.linear.app/6afc998d-0125-4bd5-a791-94d2bbd42b7c/23409e2b-879c-4ea9-b276-8fef20b96eb2/464249c7-4117-4ac9-8e8e-7b6069dfb9e5)

If I call medusa.carts.complete with the same cart ID again I get

![](https://uploads.linear.app/6afc998d-0125-4bd5-a791-94d2bbd42b7c/b06f8709-912a-4473-bce7-6185a14d79c2/c30d0908-8191-458a-9d3e-dd3b50edded3)

Any thoughts how to fix that? Thank you!

### System information

Medusa version (including plugins): 1.6.0
Node.js version: 18.3.0
Database: Postgres
Operating system: Heroku (I think Linux)
Browser (if relevant): Not relevant

### Steps to reproduce the behavior

See description.

### Expected behavior

An order should be placed.

UPD
That's what server-side log shows:

```
{
	"level": "error",
	"message": "null value in column \"customer_id\" of relation \"order\" violates not-null constraint",
	"stack": [{
		"columnNumber": 28,
		"fileName": "/app/node_modules/typeorm/error/TypeORMError.js",
		"functionName": "QueryFailedError.TypeORMError [as constructor]",
		"lineNumber": 9,
		"methodName": "TypeORMError [as constructor]",
		"native": false,
		"typeName": "QueryFailedError"
	}, {
		"columnNumber": 28,
		"fileName": "/app/node_modules/typeorm/error/QueryFailedError.js",
		"functionName": "new QueryFailedError",
		"lineNumber": 13,
		"methodName": null,
		"native": false,
		"typeName": null
	}, {
		"columnNumber": 31,
		"fileName": "/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js",
		"functionName": null,
		"lineNumber": 281,
		"methodName": null,
		"native": false,
		"typeName": "PostgresQueryRunner"
	}, {
		"columnNumber": 27,
		"fileName": "/app/node_modules/tslib/tslib.js",
		"functionName": "step",
		"lineNumber": 144,
		"methodName": null,
		"native": false,
		"typeName": null
	}, {
		"columnNumber": 57,
		"fileName": "/app/node_modules/tslib/tslib.js",
		"functionName": "Object.throw",
		"lineNumber": 125,
		"methodName": "throw",
		"native": false,
		"typeName": "Object"
	}, {
		"columnNumber": 69,
		"fileName": "/app/node_modules/tslib/tslib.js",
		"functionName": "rejected",
		"lineNumber": 116,
		"methodName": null,
		"native": false,
		"typeName": null
	}, {
		"columnNumber": 5,
		"fileName": "node:internal/process/task_queues",
		"functionName": "process.processTicksAndRejections",
		"lineNumber": 95,
		"methodName": "processTicksAndRejections",
		"native": false,
		"typeName": "process"
	}],
	"timestamp": "2023-01-26 19:45:00"
}
```

<sub>From [SyncLinear.com](https://synclinear.com) | [CORE-1123](https://linear.app/medusajs/issue/CORE-1123/validate-input-to-order-creation)</sub>

**Comment by finom** [comment]
I found out how to fix that. I needed to set email:

```js
await medusa.carts.update(currentUser.medusaCartId, {
      email
});
```

But I don't close the issue because I think the API should return a proper error instead of the "unknown error".

**Comment by olivermrbl** [comment]
Thanks for filing this issue @finom. We should indeed validate the order data and throw a more descriptive error. I've added it to our backlog :)
