### ISSUE TITLE
Cannot remove region price

### ISSUE THREAD

**Issue by rrums123** [medusajs/medusa#3125]
## Bug report
Cannot remove region price from admin panel

### Describe the bug
Already remove region price value from the field, but it was not removed from DB.
From admin panel, already sent correct payload (no region prices sent to server)

### System information

Medusa version (including plugins): 1.7.5
Node.js version: 16.18
Database: postgres
Operating system: MacOS or Linux
Browser (if relevant): Chrome

### Steps to reproduce the behavior

1. Set any region prices
2. Update the variant
3. Remove region prices from the field
4. Update variant
5. Region price still there

### Expected behavior

Region prices should be removed

### Screenshots

<img width="716" alt="Screenshot 2023-01-27 at 5 55 55 PM" src="https://user-images.githubusercontent.com/100153954/215069864-2b296d41-336e-4d19-8792-e352b9fdc370.png">

when removing region prices, admin panel send only currency prices
but it wasn't removed
<img width="352" alt="Screenshot 2023-01-27 at 5 59 43 PM" src="https://user-images.githubusercontent.com/100153954/215070758-b26fd283-a4db-4415-b70e-c19f628c9357.png">

**Comment by harshmange44** [comment]
@rrums123 Hey, how did you remove the region prices from the field. Afaik, you can update the region prices in variants but can't remove this?

**Comment by rrums123** [comment]
@harshmange44 i remove the value, then save, the value persist.
expected behaviour that price should be removed or it will ruined store prices
in this case I want to use only default currency price
