### ISSUE TITLE
Stripe webhook payment_intent.succeeded, payment not captured

### ISSUE THREAD

**Issue by nekszt** [medusajs/medusa#3146]
Hello,

### Describe the bug

Capture payment with Stripe is not working. I think there is a race condition.

### System information

Latest updates
Medusa version: 1.7.5
Stripe version: 1.1.51
Node: 17.1.0

### Steps to reproduce the behavior

- `medusa-payment-stripe` is configured with the option `capture` set to `true`
- Stripe webhook `payment_intent.succeeded`

### Screenshots
![stripe_before_complete](https://user-images.githubusercontent.com/10143046/215671285-1e8f92b8-1eb9-466c-9791-709d6fcb3039.png)

Are there issues with transactions?
Could the complete order action overwrite the payment/order status.

The webhook is well received by medusa (medusa and stripe logs), and if I trigger it again from Stripe payment status becomes `Paid`.
How can it be solved quickly? We could try to set a delay on the webhook to see if there is a race condition.

**Comment by olivermrbl** [comment]
Solved in #3100. Will be part of release next week :)

**Comment by olivermrbl** [comment]
The snapshot action does not seem to run successfully, so I've published one manually:

```
yarn add medusa-payment-stripe@1.1.52-snapshot-20230131134920
```

**Comment by nekszt** [comment]
Thank you ! I have taken this one. It's working ;)
