### ISSUE TITLE
[CORE-1065] Shipping Profile type is null

### ISSUE THREAD

**Issue by msohailhussain** [medusajs/medusa#3151]
When trying to create a shipping profile by providing the below payload.
```
{
  "name": "shipping_profile_name"
}
```

An exception is coming up. 
```
null value in column "type" of relation "shipping_profile" violates not-null constraint
QueryFailedError: null value in column "type" of relation "shipping_profile" violates not-null constraint
```
When providing payload 
```
{
  "name": "shipping_profile_name",
  "type": "custom"
}
```
Getting this error. 
```
error:   property type should not exist
Error: property type should not exist
```

How I can create a shipping profile?

<sub>[CORE-1065](https://linear.app/medusajs/issue/CORE-1065/shipping-profile-type-is-null)</sub>

**Comment by olivermrbl** [comment]
Thanks for filing the issue. I'll add it to our backlog right away :)
