### ISSUE TITLE
Cannot create a new Product

### ISSUE THREAD

**Issue by LokutS2i** [medusajs/medusa#3158]
### Describe the bug

Hi, I just wanted to create a new product. But a can't because medusa server returned an error while saving the new product that I do not understand:

![image](https://user-images.githubusercontent.com/102290895/216146582-8aa6d22d-6dc6-4e98-b857-3a8f1cf19c01.png)

### System information

Medusa version (including plugins): latest
Node.js version: 16.15.0
Database: by default
Operating system: Windows 11
Browser (if relevant): Chrome

### Steps to reproduce the behavior

1. Install, seed and run medusa server
2. Install and run medusa admin
3. Go to Products
4. Fill and save a product form

I simply installed medusa server and medusa admin following the quick start guide and simply tried to add a product. Maybe I forgot a step but I'm a beginner with medusa so be forgiving with me, thanks for any help!

**Comment by olivermrbl** [comment]
I'll look into this one. In the meantime, can I get you to try to [configure your server to run with Postgres](https://docs.medusajs.com/usage/configurations) instead of SQLite?

**Comment by gwrst** [comment]
<img width="1559" alt="image" src="https://user-images.githubusercontent.com/102539042/216300977-b7fd1158-46e2-4719-9f4d-e605c1de3a0b.png">
Same problem with postres db

**Comment by LokutS2i** [comment]
@olivermrbl I allready did it and I have the same problem....

**Comment by olivermrbl** [comment]
Got it - thanks for filing the issue. I've added it to our backlog with high urgency!

**Comment by gwrst** [comment]
It works when you disable default channel, add product, enable Default channel and Add product to channel

**Comment by olivermrbl** [comment]
We've identified the culprit. Pushing a fix asap :)

**Comment by LokutS2i** [comment]
Thanks @olivermrbl 🙏🏼

**Comment by olivermrbl** [comment]
@kasperkristensen solved this in [878](https://github.com/medusajs/admin/pull/878)
