### ISSUE TITLE
[CORE-1071] Customer group discount does not work.

### ISSUE THREAD

**Issue by magdafiktus** [medusajs/medusa#3163]
### Describe the bug

Customer group discount does not work.

### System information

"@medusajs/medusa": "1.7.2-snapshot-20221228134959",
"@medusajs/medusa-cli": "^1.3.5",
"medusa-core-utils": "^1.1.36",
"medusa-file-spaces": "1.3.1",
"medusa-fulfillment-manual": "1.1.31",
"medusa-fulfillment-webshipper": "^1.3.3",
"medusa-interfaces": "1.3.3",
"medusa-payment-adyen": "1.1.39",
"medusa-payment-klarna": "1.3.4",
"medusa-payment-manual": "^1.0.19",
"medusa-payment-paypal": "1.2.6",
"medusa-payment-stripe": "1.1.49",
"medusa-plugin-brightpearl": "1.3.2",
"medusa-plugin-contentful": "^1.2.3",
"medusa-plugin-discount-generator": "1.1.19",
"medusa-plugin-ip-lookup": "1.2.1",
"medusa-plugin-meilisearch": "1.0.0",
"medusa-plugin-restock-notification": "2.0.0",
"medusa-plugin-segment": "^1.3.0",
"medusa-plugin-sendgrid": "1.3.3",
"medusa-plugin-sentry": "^1.2.3",
"medusa-plugin-slack-notification": "1.3.4",
"medusa-plugin-wishlist": "1.1.37",
"medusa-test-utils": "1.1.37",
Node -> v16.x
OS -> Ubuntu 18.04 
(https://teklafabrics.slack.com/archives/D02Q3RLSUCA/p1674042777633589)
Database -> Postgres

### Steps to reproduce the behavior

1. Create a customer group
2. create a 10% discount with the condition that it is for this customer group
3. publish it
4. shop on the website, add the email in the checkout and/or log in
5. the discount is not rejected but it does not change the price

### Expected behavior

The discount should be applied at the checkout

<sub>[CORE-1071](https://linear.app/medusajs/issue/CORE-1071/customer-group-discount-does-not-work)</sub>

**Comment by olivermrbl** [comment]
@magdafiktus Issue has been identified. Will be part of next release :)

**Comment by magdafiktus** [comment]
This still does not work for me. I make a condition that a code is for specific group only, but when I apply discount code without giving the email or logging it works anyways.
