### ISSUE TITLE
Bug: PayPal `sandbox` environment variable is checked incorrectly

### ISSUE THREAD

**Issue by InderdeepBajwa** [medusajs/medusa#3165]
### Describe the bug

The PayPal plugin has an issue where the environment variable is checked for its existence whereas it should be checked for its truthy value.

Code in context: https://github.com/medusajs/medusa/blob/master/packages/medusa-payment-paypal/src/services/paypal-provider.js#L30

The code `if (this.options_.sandbox)` checks if the variable `sandbox` is defined in the environment variable `PAYPAL_SANDBOX`. Since the environment variables are treated as strings, the value of `PAYPAL_SANDBOX=false` is still interpreted as truthy in code `if (this.options_.sandbox)` because the variable `sandbox` exists.

It is advisable to either change it to something like `if (this.options_.sandbox === "false")` or casting the variable into a boolean.

### System information

 N/A. The bug is in the code.

### Steps to reproduce the behavior

1. Install the Medusa PayPal plugin2. 
2. Set the value of environment variable `PAYPAL_SANDBOX` to false
3. Current code still treats the sandbox variable as true regardless of the value of `PAYPAL_SANDBOX`

### Expected behavior

`PAYPAL_SANDBOX=false` should disable sandbox environment
`PAYPAL_SANDBOX=true` should enable sandbox environment

### Screenshots

 N/A. The bug is in the code.

### Code snippets

[If applicable, add code samples to help explain your problem](https://github.com/medusajs/medusa/blob/master/packages/medusa-payment-paypal/src/services/paypal-provider.js#L30)

### Additional context

N/A

**Comment by InderdeepBajwa** [comment]
PR is here: https://github.com/medusajs/medusa/pull/3166

**Comment by daysgobye** [comment]
OMG thank you I lost 2 days to this bug for anyone else waiting for this  pr to merge you can do what I did remove your paypal sandbox settings flag 
<img width="442" alt="image" src="https://github.com/medusajs/medusa/assets/38364556/af025b6e-9c9e-4831-95eb-0a7c2133e7af">

**Comment by InderdeepBajwa** [comment]
Glad you found a temporary fix for this problem @daysgobye! I checked the new version of PayPal provider code that is rewritten in TypeScript and didn't find a similar reference sandbox checking. It may be that this is no longer relevant on newer releases. I'll close this issue out.

**Comment by mythical0beast** [comment]
this temporary  fix is not working
