### ISSUE TITLE
TypeError after creating empty file and deleting it in `src/services` directory

### ISSUE THREAD

**Issue by Hemann55** [medusajs/medusa#3167]
### Describe the bug

TypeError after creating empty file and deleting it in `src/services` directory

### System information

Medusa version (including plugins): 1.6.0, 1.7.5
Node.js version: v16.18.0
Database: postgres and sqlite
Operating system: linux
Browser (if relevant):

### Steps to reproduce the behavior

1. Install a fresh instance of Medusa by using `medusa new my-medusa-store --seed`

2. Create an empty file in /services directory using [Medusa's naming convention](https://docs.medusajs.com/advanced/backend/services/create-service)

3. Run the server and you get the following error:

`
TypeError: Cannot read properties of undefined (reading 'prototype')
    at ...pathToMedusaFolder/my-medusa-store/node_modules/@medusajs/medusa/dist/loaders/plugins.js:352:54
    at step (...pathToMedusaFolder/my-medusa-store/node_modules/@medusajs/medusa/dist/loaders/plugins.js:33:23)
    at Object.next (...pathToMedusaFolder/my-medusa-store/node_modules/@medusajs/medusa/dist/loaders/plugins.js:14:53)
    at ...pathToMedusaFolder/my-medusa-store/node_modules/@medusajs/medusa/dist/loaders/plugins.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (...pathToMedusaFolder/my-medusa-store/node_modules/@medusajs/medusa/dist/loaders/plugins.js:4:12)
    at ...pathToMedusaFolder/my-medusa-store/node_modules/@medusajs/medusa/dist/loaders/plugins.js:344:87
    at Array.map (<anonymous>)
    at ...pathToMedusaFolder/my-medusa-store/node_modules/@medusajs/medusa/dist/loaders/plugins.js:344:60
    at step (...pathToMedusaFolder/my-medusa-store/node_modules/@medusajs/medusa
⠇ Initializing plugins
`

4. Now delete the file and run the server to get the same error.

### Expected behavior

Work in progress empty files or files deleted from `src/services` directory should not throw this error.

**Comment by olivermrbl** [comment]
Thanks for filing the issue. We will treat this as an enhancement and not a bug. The server runs with a correct service implementation
