### ISSUE TITLE
[CORE-1070] Swap links charge for return shipping (even if we have changed it manually)

### ISSUE THREAD

**Issue by magdafiktus** [medusajs/medusa#3170]
**Describe the bug**
Swap links charge for return shipping (even if we have changed it manually)

System information
"@medusajs/medusa": "1.7.2-snapshot-20221228134959",
"@medusajs/medusa-cli": "^1.3.5",
"medusa-core-utils": "^1.1.36",
"medusa-file-spaces": "1.3.1",
"medusa-fulfillment-manual": "1.1.31",
"medusa-fulfillment-webshipper": "^1.3.3",
"medusa-interfaces": "1.3.3",
"medusa-payment-adyen": "1.1.39",
"medusa-payment-klarna": "1.3.4",
"medusa-payment-manual": "^1.0.19",
"medusa-payment-paypal": "1.2.6",
"medusa-payment-stripe": "1.1.49",
"medusa-plugin-brightpearl": "1.3.2",
"medusa-plugin-contentful": "^1.2.3",
"medusa-plugin-discount-generator": "1.1.19",
"medusa-plugin-ip-lookup": "1.2.1",
"medusa-plugin-meilisearch": "1.0.0",
"medusa-plugin-restock-notification": "2.0.0",
"medusa-plugin-segment": "^1.3.0",
"medusa-plugin-sendgrid": "1.3.3",
"medusa-plugin-sentry": "^1.2.3",
"medusa-plugin-slack-notification": "1.3.4",
"medusa-plugin-wishlist": "1.1.37",
"medusa-test-utils": "1.1.37",
Node -> v16.x
OS -> Ubuntu 18.04
Database -> Postgres<!--

**Steps to reproduce the behavior**
1. Buy something
2. Swap it fx for another color
3. Customer tries to return an item to get the new item and gets charged
4. CS tries to change it but the customer still gets charged

**Expected behavior**
The new item in the swap should have the same discount unless the new items is non discountable

<img width="855" alt="Screenshot 2022-09-05 at 13 45 32" src="https://user-images.githubusercontent.com/116171296/216584089-e0ecb041-d683-4e65-af7a-ffec1f5edaa5.png">

<img width="516" alt="Screenshot 2023-02-03 at 16 02 23" src="https://user-images.githubusercontent.com/116171296/216636320-f6cfafc4-0d26-4889-a384-bde54ba150c9.png">

<sub>[CORE-1070](https://linear.app/medusajs/issue/CORE-1070/swap-links-charge-for-return-shipping-even-if-we-have-changed-it)</sub>

**Comment by srindom** [comment]
Can't reproduce
