### ISSUE TITLE
[CORE-1084] Cannot receive swaps and returns

### ISSUE THREAD

**Issue by magdafiktus** [medusajs/medusa#3173]
**Describe the bug**

The screen goes blank when we click on "Receive return". Therefore, we cannot process the swap and ship the new item. 
We are currently using old Medusa for receiving returns on swaps. They seem to be failing, when there is not a cost of return shipping on the return. 

System information
"@medusajs/medusa": "1.7.2-snapshot-20221228134959",
"@medusajs/medusa-cli": "^1.3.5",
"medusa-core-utils": "^1.1.36",
"medusa-file-spaces": "1.3.1",
"medusa-fulfillment-manual": "1.1.31",
"medusa-fulfillment-webshipper": "^1.3.3",
"medusa-interfaces": "1.3.3",
"medusa-payment-adyen": "1.1.39",
"medusa-payment-klarna": "1.3.4",
"medusa-payment-manual": "^1.0.19",
"medusa-payment-paypal": "1.2.6",
"medusa-payment-stripe": "1.1.49",
"medusa-plugin-brightpearl": "1.3.2",
"medusa-plugin-contentful": "^1.2.3",
"medusa-plugin-discount-generator": "1.1.19",
"medusa-plugin-ip-lookup": "1.2.1",
"medusa-plugin-meilisearch": "1.0.0",
"medusa-plugin-restock-notification": "2.0.0",
"medusa-plugin-segment": "^1.3.0",
"medusa-plugin-sendgrid": "1.3.3",
"medusa-plugin-sentry": "^1.2.3",
"medusa-plugin-slack-notification": "1.3.4",
"medusa-plugin-wishlist": "1.1.37",
"medusa-test-utils": "1.1.37",
Node -> v16.x
OS -> Ubuntu 18.04
Database -> Postgres<!--

**Steps to reproduce the behavior**
1. Buy something
2. try to return it
3. receive return in the system
4. page goes blank

**Expected behavior**
The page does not go blank

![Skærmbillede 2022-11-16 kl  14 38 43](https://user-images.githubusercontent.com/116171296/216586625-b2f72b7a-a582-47e1-be7c-19ded0a1ce93.png)
![Skærmbillede 2022-12-14 kl  14 17 00](https://user-images.githubusercontent.com/116171296/216586629-7fb50ab8-3b14-4ba4-bc03-f7847dfa8956.png)

<sub>[CORE-1084](https://linear.app/medusajs/issue/CORE-1084/cannot-receive-swaps-and-returns)</sub>

**Comment by olivermrbl** [comment]
Fixed in [#880](https://github.com/medusajs/admin/pull/880)
