### ISSUE TITLE
Store Route doesn't get billing_address relation

### ISSUE THREAD

**Issue by OD91** [medusajs/medusa#3182]
### Describe the bug
In the Medusa Storefront: After successful checkout I would like to display an order confirmation page where I among others show the `billing_address` from the Order. However my Order object just receives the shipping_address and NOT the billing_address (undefined). The issue probably lies here: https://github.com/medusajs/medusa/blob/master/packages/medusa/src/api/routes/store/orders/index.ts#L48 --> The store route doesn't get the billing_address relation. 

### Expected behavior

Getting the `billing_address` relation in the Medusa Storefront (so that I can display my b2b customers a proper order confirmation including their billing address).

**Comment by fxmb** [comment]
Having the same issue. Does anyone know what is going on?

**Comment by olivermrbl** [comment]
> Does anyone know what is going on?

It is currently not part of the response. We'll make sure to make it queryable asap :)

**Comment by olivermrbl** [comment]
@fPolic added `billing_address` as an allowed relation. Will be part of release this week

**Comment by fxmb** [comment]
so this is part of 1.7.6? Thanks so much!

**Comment by chemicalkosek** [comment]
It should be as per changelog. It has been added as allowed relation, not default relation so it still needs expanding. 
@olivermrbl But I have tested this in postman by expanding `billing_address` and it still doesn't return it. It doesn't error out tho.

```
http://localhost:9000/store/orders/ORDER_ID?expand=billing_address
```

**Comment by OD91** [comment]
I am also still not able to receive the `billing_address`....

**Comment by olivermrbl** [comment]
@OD91 We will publish a follow-up release with #3219 included later today :)

**Comment by fxmb** [comment]
How can I update the store to this version? It is still at 1.7.6 not including the billing address?

**Comment by olivermrbl** [comment]
Will be part of next release. Hoping to push it out tomorrow. 

You can test it out by installing the next version `@medusajs/medusa@next`

**Comment by OD91** [comment]
Problem still exists on 1.7.7....

**Comment by fxmb** [comment]
I do not get it when calling from the medusa client such as:

`const fetchOrder = async (id: string) => {
  return await medusaClient.orders
    .retrieve(id, { expand: "billing_address" })
    .then(({ order }) => order)
}`

This only returns the regular order ID object without the billing address....

**Comment by fxmb** [comment]
I am assuming my syntax is flawed from above somehow... When I call it via HTTP route directly it works just fine...

**Comment by fxmb** [comment]
Can anyone help why this is not working in our case?

**Comment by olivermrbl** [comment]
@fxmb Query params are not supported on `GET /store/orders/:id` in `@medusajs/medusa-js` - none of `GET /store/*/:id` endpoints allow for this as of now. 

You'll have to query the API directly with Axios or the likes. Alternatively, you can [extend the client](https://github.com/medusajs/medusa/issues/3082) from `@medusajs/medusa-js` with a new method for your specific usecase, that properly handles query params.

**Comment by fxmb** [comment]
That is interesting. Thanks for clarifying. I found this confusing as nothing is written about this in the docs - at least nothing I found / read. Got it to work now though. Thanks.
