### ISSUE TITLE
[CORE-1089] Adding gift card to shopping basket fails with missing sales channel

### ISSUE THREAD

**Issue by artkaas** [medusajs/medusa#3188]
### Describe the bug

Trying to add gift card to shopping basket fails with the following error:

`
Error: The product "Gift card" must belongs to the sales channel on which the cart has been created.
    at CartService.<anonymous> (/medusa-server/node_modules/@medusajs/medusa/dist/services/cart.js:629:55)
    at step (/medusa-server/node_modules/@medusajs/medusa/dist/services/cart.js:59:23)
    at Object.next (/medusa-server/node_modules/@medusajs/medusa/dist/services/cart.js:40:53)
    at fulfilled (/medusa-server/node_modules/@medusajs/medusa/dist/services/cart.js:31:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'invalid_data',
  code: undefined,
  date: 2023-01-26T20:00:26.958Z
`

### System information

Medusa version (including plugins): medusa 1.7.5, nextjs-starter-medusa (latest)
Node.js version: 18.11.0
Database: PostgreSQL
Operating system: macOS Monteray
Browser (if relevant): Safari

### Steps to reproduce the behavior

1. Define gift card in medusa admin
2. Modify nextjs-starter-medusa to display gift card as product
3. Click on a gift card product to add it to shopping basket
5. See the server error above

### Expected behavior

Gift card product to be successfully added to shopping basket

### Additional context

Assigning gift card product to default sales channel solves the problem. It was done manually inserting new row into product_sales_channel table in PostgreSQL database. 

<sub>[CORE-1089](https://linear.app/medusajs/issue/CORE-1089/adding-gift-card-to-shopping-basket-fails-with-missing-sales-channel)</sub>

**Comment by olivermrbl** [comment]
@artkaas Thanks for filing this issue. We'll attend to a fix asap. Hope to include it in v1.7.6 releasing tomorrow :)

**Comment by olivermrbl** [comment]
Did you run the [migration script](https://docs.medusajs.com/advanced/backend/upgrade-guides/medusa-core/1-7-3) to add all products to the default sales channel?

**Comment by artkaas** [comment]
Yes, I was running the script when upgrading to medusa 1.7.3 several days ago. But the gift card did not exist in the system at that time. I have added the gift card product only recently and it is not assigned to the default sales channel.

**Comment by olivermrbl** [comment]
Got it. Make sense! We are on it 👍
