### ISSUE TITLE
[CORE-1097] History of purchased gift cards does not display order id

### ISSUE THREAD

**Issue by artkaas** [medusajs/medusa#3189]
### Describe the bug

History of purchased gift cards does not display order id in medusa admin

### System information

Medusa version (including plugins): medusa 1.7.5, medusa admin (latest)
Node.js version: 18.11.0
Database: PostgreSQL
Operating system: macOS Monteray
Browser (if relevant): Safari

### Steps to reproduce the behavior

1. Go to Gift Cards section of medusa admin
2. See gift card history missing order id

### Expected behavior

Order id of a transaction as part of which a given gift card has been purchased should be displayed.

### Screenshots

<img width="1302" alt="gift-cards" src="https://user-images.githubusercontent.com/23141356/217084530-eb11021e-19af-4c67-b1c3-ae8f1604c24c.png">

<sub>[CORE-1097](https://linear.app/medusajs/issue/CORE-1097/history-of-purchased-gift-cards-does-not-display-order-id)</sub>

**Comment by olivermrbl** [comment]
Solved in [#885](https://github.com/medusajs/admin/pull/885)
