### ISSUE TITLE
[CORE-1104] Cannot add free shipping to draft orders

### ISSUE THREAD

**Issue by magdafiktus** [medusajs/medusa#3195]
**Describe the bug**

When we change the price of the shipping to 0, the price will still show once the draft order has been created.

Example draft Order #277

System information
"@medusajs/medusa": "1.7.2-snapshot-20221228134959",
"@medusajs/medusa-cli": "^1.3.5",
"medusa-core-utils": "^1.1.36",
"medusa-file-spaces": "1.3.1",
"medusa-fulfillment-manual": "1.1.31",
"medusa-fulfillment-webshipper": "^1.3.3",
"medusa-interfaces": "1.3.3",
"medusa-payment-adyen": "1.1.39",
"medusa-payment-klarna": "1.3.4",
"medusa-payment-manual": "^1.0.19",
"medusa-payment-paypal": "1.2.6",
"medusa-payment-stripe": "1.1.49",
"medusa-plugin-brightpearl": "1.3.2",
"medusa-plugin-contentful": "^1.2.3",
"medusa-plugin-discount-generator": "1.1.19",
"medusa-plugin-ip-lookup": "1.2.1",
"medusa-plugin-meilisearch": "1.0.0",
"medusa-plugin-restock-notification": "2.0.0",
"medusa-plugin-segment": "^1.3.0",
"medusa-plugin-sendgrid": "1.3.3",
"medusa-plugin-sentry": "^1.2.3",
"medusa-plugin-slack-notification": "1.3.4",
"medusa-plugin-wishlist": "1.1.37",
"medusa-test-utils": "1.1.37",
Node -> v16.x
OS -> Ubuntu 18.04
Database -> Postgres<!--

**Steps to reproduce the behavior**
1.Make a draft order
2. Make the shipping price 0

**Expected behavior**

Free shipping

<sub>[CORE-1104](https://linear.app/medusajs/issue/CORE-1104/cannot-add-free-shipping-to-draft-orders)</sub>

**Comment by adrien2p** [comment]
Once a shipping option is applied, it creates a shipping method and snapshots the price. If you then change the price, it seems normal that if an order has a price, this price does not change no?

If as a customer, for example, you get a price, if the price then changes, the customer should still have the price displayed being applied.

cc: @olivermrbl

**Comment by olivermrbl** [comment]
@adrien2p I believe the issue is, that setting a custom shipping price in the flow to create a DraftOrder does not work. It ignores the custom price upon completing the flow.

**Comment by olivermrbl** [comment]
Setting a custom shipping price in the flow to create a DraftOrder does not work. It ignores the custom price upon completing it

**Comment by adrien2p** [comment]
I ll have a quick look soone. @magdafiktus can you confirm that it is the issue before I jump on it please 🙏

**Comment by magdafiktus** [comment]
> 

Hey Adrien, checked two more times and it is definitely not working :) even though we change price to 0, the end result still shows local shipping pricing

**Comment by olivermrbl** [comment]
Solved in [#888](https://github.com/medusajs/admin/pull/888)

**Comment by magdafiktus** [comment]
yay awesome thanks guys!

**Comment by magdafiktus** [comment]
we set the price to 0 but it is still added
