### ISSUE TITLE
Fix amount discount codes not working

### ISSUE THREAD

**Issue by magdafiktus** [medusajs/medusa#3196]
**Describe the bug**

Fix amount discount does not get applied

System information
"@medusajs/medusa": "1.7.2-snapshot-20221228134959",
"@medusajs/medusa-cli": "^1.3.5",
"medusa-core-utils": "^1.1.36",
"medusa-file-spaces": "1.3.1",
"medusa-fulfillment-manual": "1.1.31",
"medusa-fulfillment-webshipper": "^1.3.3",
"medusa-interfaces": "1.3.3",
"medusa-payment-adyen": "1.1.39",
"medusa-payment-klarna": "1.3.4",
"medusa-payment-manual": "^1.0.19",
"medusa-payment-paypal": "1.2.6",
"medusa-payment-stripe": "1.1.49",
"medusa-plugin-brightpearl": "1.3.2",
"medusa-plugin-contentful": "^1.2.3",
"medusa-plugin-discount-generator": "1.1.19",
"medusa-plugin-ip-lookup": "1.2.1",
"medusa-plugin-meilisearch": "1.0.0",
"medusa-plugin-restock-notification": "2.0.0",
"medusa-plugin-segment": "^1.3.0",
"medusa-plugin-sendgrid": "1.3.3",
"medusa-plugin-sentry": "^1.2.3",
"medusa-plugin-slack-notification": "1.3.4",
"medusa-plugin-wishlist": "1.1.37",
"medusa-test-utils": "1.1.37",
Node -> v16.x
OS -> Ubuntu 18.04
Database -> Postgres<!--

**Steps to reproduce the behavior**
1.Make a fixed amount discount code
2. Add items to basket
3. apply the code

**Expected behavior**

the code would work for the whole basket, not per item

**Comment by adrien2p** [comment]
what do you mean by the whole basket and not per item? if the discount is set to be applied on the total, then the amount is distributed proportionally on each item. it the discount is set to be per item then it is applied per item and finally with a percentage it applied a percentage on the item
