### ISSUE TITLE
Product Variant update method does not work when metadata is null

### ISSUE THREAD

**Issue by haveamission** [medusajs/medusa#3201]
### Describe the bug

When attempting to update a product variant, using the update method does not work if metadata is null. As the code should theoretically account for this

https://github.com/medusajs/medusa/blob/master/packages/medusa/src/services/product-variant.ts

```
      if (typeof metadata === "object") {
        variant.metadata = setMetadata(variant as ProductVariant, metadata)
      }
```
Yet, when metadata is null, setMetadata is still being run:

```
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at setMetadata (/Users/andy/Desktop/Projects/pm-medusa/node_modules/@medusajs/medusa/dist/utils/set-metadata.js:54:39)
    at ProductVariantService.<anonymous> (/Users/andy/Desktop/Projects/pm-medusa/node_modules/@medusajs/medusa/dist/services/product-variant.js:388:88)
    at step (/Users/andy/Desktop/Projects/pm-medusa/node_modules/@medusajs/medusa/dist/services/product-variant.js:59:23)
    at Object.next (/Users/andy/Desktop/Projects/pm-medusa/node_modules/@medusajs/medusa/dist/services/product-variant.js:40:53)
    at fulfilled (/Users/andy/Desktop/Projects/pm-medusa/node_modules/@medusajs/medusa/dist/services/product-variant.js:31:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### System information

Medusa version (including plugins): 1.7.5
Node.js version: 16.x
Database: Postgres
Operating system: MacOS 12.5

### Steps to reproduce the behavior

1. Create a new product variant
2. Create a new object for this product variant with some new data - ensure metadata is null
3. Attempt to update the product variant with this new object

### Expected behavior

Updated product variant with no error

### Additional context

I feel the error is pretty straight-forward.

**Comment by olivermrbl** [comment]
@haveamission What are you attempting to do? Setting existing product variant metadata to `null`? 

You are not seeing your expected result because `null` is treated as an `object` in Javascript, so this if-condition checks out. And when we try to loop over the metadata (which is `null` for your case), an error is thrown.

**Comment by olivermrbl** [comment]
To set metadata entries to be `null`, you should pass an empty string like so:
```
metadata: {
  some_key: ""
}
```

Though, this is not released yet. Will be part of v1.7.6 coming out later today.

**Comment by haveamission** [comment]
> @haveamission What are you attempting to do? Setting existing product variant metadata to `null`?
> 
> You are not seeing your expected result because `null` is treated as an `object` in Javascript, so this if-condition checks out. And when we try to loop over the metadata (which is `null` for your case), an error is thrown.

No, I was trying to update a product variant that already had null metadata with some new other data. Because metadata was null, this also threw an error

**Comment by haveamission** [comment]
> To set metadata entries to be `null`, you should pass an empty string like so:
> 
> ```
> metadata: {
>   some_key: ""
> }
> ```
> 
> Though, this is not released yet. Will be part of v1.7.6 coming out later today.

Yeah, as a workaround, I was currently setting metadata to be `{}` which avoided the error
