### ISSUE TITLE
Getting this error  ( No QueryClient set, use QueryClientProvider to set one) on run  storefront , am using yarn run  dev . 

### ISSUE THREAD

**Issue by Felexonyango** [medusajs/medusa#3214]
![Screenshot (20)](https://user-images.githubusercontent.com/58067903/217744724-2f697238-b59e-4709-bfd8-b4cb372d8b31.png)
 kindly check into it

**Comment by Felexonyango** [comment]
this is _app.tsx  import { MEDUSA_BACKEND_URL, queryClient } from "@lib/config"
import { AccountProvider } from "@lib/context/account-context"
import { CartDropdownProvider } from "@lib/context/cart-dropdown-context"
import { MobileMenuProvider } from "@lib/context/mobile-menu-context"
import { StoreProvider } from "@lib/context/store-context"
import { Hydrate,QueryClient,QueryClientProvider } from "@tanstack/react-query"
import { CartProvider, MedusaProvider } from "medusa-react"
import "styles/globals.css"
import { AppPropsWithLayout } from "types/global"

function App({
  Component,
  pageProps,
}: AppPropsWithLayout<{ dehydratedState?: unknown }>) {
  const getLayout = Component.getLayout ?? ((page) => page)

  return (
    <MedusaProvider
      baseUrl={MEDUSA_BACKEND_URL}
      queryClientProviderProps={{
        client: queryClient,
      }}
    >
      <Hydrate state={pageProps.dehydratedState}>
        <CartDropdownProvider>
          <MobileMenuProvider>
            <CartProvider>
              <StoreProvider>
                <AccountProvider>
                  {getLayout(<Component {...pageProps} />)}
                </AccountProvider>
              </StoreProvider>
            </CartProvider>
          </MobileMenuProvider>
        </CartDropdownProvider>
      </Hydrate>
    </MedusaProvider>
  )
}

export default App

**Comment by chemicalkosek** [comment]
You need to follow this guide: <https://docs.medusajs.com/advanced/backend/upgrade-guides/medusa-react/4-0-2#fix-no-queryclient-set-errors>

**Comment by chemicalkosek** [comment]
Actually if you use that workaround with `medusa-react@4.0.4` it will break again, so you can just update `medusa-react` to `4.0.4`

**Comment by olivermrbl** [comment]
Thanks @chemicalkosek!
