### ISSUE TITLE
[CORE-1114] When adding a product, medusa doesn't assign a default sales channel

### ISSUE THREAD

**Issue by chemicalkosek** [medusajs/medusa#3225]
### Describe the bug

Not sure if this is admin or core issue but the UI in admin states that it should assign the default sales channel to product.
It is not happening.
![image](https://user-images.githubusercontent.com/11018707/217882792-f20f08e4-e450-42a1-9269-d841be09e3ad.png)

### System information

The latest admin pull
Medusa version (including plugins): 1.7.6
Node.js version: 18.14
Database: postgres
Operating system: Ubuntu 22.04
Browser (if relevant):

### Steps to reproduce the behavior

1. Add a product without selecting sales channel
2. See the product not having a sales channel assigned.

![image](https://user-images.githubusercontent.com/11018707/217883995-5faa1802-64ff-446c-8c26-57fa4c322e32.png)

### Expected behavior

Have default sales channel assigned when adding a product.

<sub>[CORE-1114](https://linear.app/medusajs/issue/CORE-1114/when-adding-a-product-medusa-doesnt-assign-a-default-sales-channel)</sub>

**Comment by olivermrbl** [comment]
Thanks for filing this one @chemicalkosek. It seems, the issue only occurs, if you don't expand the "Organize" section in the form. We'll make sure to attend to a fix asap :)

**Comment by olivermrbl** [comment]
Solved in #3249
