### ISSUE TITLE
possible-bug(loader, plugins, performance): Services of plugins are not loaded as singleton

### ISSUE THREAD

**Issue by flashjames** [medusajs/medusa#3270]
### Describe the bug
All services (those under my-custom-plugin/src/services/) of a plugin does not get cached, i.e. the service is re-created for each request coming to medusa.

### Easy fix (what you would probably expect)
An easy fix would be to add .singleton() to the loader responsible for adding plugin services. What I can see this is added on all services part of core.

This is how services added under backend-medusa/src/services are treated. See: https://github.com/medusajs/medusa/blob/master/packages/medusa/src/loaders/services.ts#L31

#### Code now
```
container.register({
          [name]: asFunction(
            (cradle) => new loaded(cradle, pluginDetails.options)
          ),
        })
```

https://github.com/medusajs/medusa/blob/master/packages/medusa/src/loaders/plugins.ts#L470

#### Should possibly be:

```
container.register({
          [name]: asFunction(
            (cradle) => new loaded(cradle, pluginDetails.options)
          ).singleton(),
        })
```

### Other solution
The best possible solution would probably be to be able to set scope/lifetime on a service. But that would be more work I reckon.

medusa-extender has this as a decorator: 
```
@Service({ scope: 'SCOPED' })
export default class MyCustomService {
}
```

## What I do right now (workaround - if somebody else has this problem)

Make a custom loader under my-plugin/src/loaders/index.ts.
```
import { asFunction, asClass } from "awilix"
import ProductService from "../services_/product" // directory named services_ so the default plugin loaders dont pick up the service
const loader = (container) => {
  const loaded = require(ProductService).default
  container.register({
        ["productService"]: asClass(
          (cradle) => new loaded(cradle)
        ).singleton(),
      })
}
export default loader

```
### On another note, to make it easier to start working on a plugin
Add to these docs https://docs.medusajs.com/advanced/backend/plugins/create
That plugins placed under my-medusa-backend/plugins/ will be picked up by default.

### System information

Medusa version (including plugins): [ef148cb9f41f8f41548d8f33b8f7c24abffc9339](https://github.com/medusajs/medusa/commit/ef148cb9f41f8f41548d8f33b8f7c24abffc9339)

**Comment by olivermrbl** [comment]
LIFETIME configuration support has been added. Check out the documentation [here](https://docs.medusajs.com/development/services/create-service#service-life-time).
