### ISSUE TITLE
Probably a bug in listProducts & listVariants in PriceList service.

### ISSUE THREAD

**Issue by Tygore** [medusajs/medusa#3289]
### Describe the bug
PriceListService methods listProducts and listVariants returns all products/variants in the database, not those contained in this price list.
If I specify the variant ID in the selector, it returns this product to me in any case, whether it is in this price list or not.

### System information

Medusa version (including plugins): 1.7.7
Node.js version: 18.13.0
Operating system: linux

### Steps to reproduce the behavior
```
1)
      const allPrice = await priceListServiceTx.listVariants("pl_01GSHJZDGBH21SM038SXXW8ASN");

2)
      const variantExistInPriceList = await priceListServiceTx.listVariants(
        "pl_01GSHJZDGBH21SM038SXXW8ASN",
        {
           id: "variant_01GQ21A9S72M5MAGJKGD2SWV0N", //not in price list
        },
        // {},
        // true
      );
```

### Expected behavior

In allPrice - I expect the method to return variants or products that are in this price list.
In variantExistInPriceList - I expect the method to return the product if it is in the price list, and if not, then null (or an empty array, object)

**Comment by adrien2p** [comment]
Indeed, it seams that these methods are querying the variants and products without any constraints on the price list. It does the opposite which is listing all products or variants and attaching the prices that are part of the price list id provided.

@olivermrbl was that the intended behaviour ?

**Comment by harshmange44** [comment]
@adrien2p Do you think line-218 could be the issue? (File: money-amount.ts repo)
<img width="677" alt="Screenshot 2023-04-18 at 2 37 05 AM" src="https://user-images.githubusercontent.com/47944044/232611533-569bb311-f356-4a4d-afef-42e6e4232e4e.png">

**Comment by adrien2p** [comment]
Can you tell me if the issue persist please.

Please don't hesitate to re-open the issue (or create a new one) if you still need a resolution or an answer.

Thanks ❤️
