### ISSUE TITLE
(Might be user error) - Having issues with the 'Help us get better' page in Medusa admin - it doesn't go away

### ISSUE THREAD

**Issue by warm-bagel** [medusajs/medusa#3290]
## Bug report
'Help us get better' page won't go away.
### Describe the bug
Literally the description above. I can add an image if you like, but the 'Help us get better' page pops up in medusa admin every time I log in, then no matter what route I take, when I click the Blue Continue button at the bottom right, it's like a blue loading ring of death. It never sends you the information I guess.. I cleared my cache, same thing. 
Just FYI: 
Admin is hosted on Netlify
Server is hosted on heroku
Both seem to be working well. I am only still using seed data.

I swear there must be somewhere that I made a mistake, but I really don't know!

Thank you!! 

### System information

Medusa version (including plugins): 1.3.5 (CLI Version)
Node.js version: 19.1.0
Database: Redis 7.0.7-0, but it looks like there are two hosted in heroku and the one that is 'attached' as DATABASE is heroku postgres. I'm not super clear on these
Operating system: I'm using MacOS Ventura 13.1, but have tested this problem on multiple mobile phones and other's PCs
Browser (if relevant): Have tested in multiple

### Steps to reproduce the behavior

1. Go to my medusa admin site (I can provide test creds)
2. Click on Continue, when the 'Help us get better' page pops up
3. Scroll down to Nowhere
4. See error -- It just never goes away

### Expected behavior
For it to go away and let me use my admin site

### Screenshots
<img width="760" alt="Screenshot 2023-02-18 at 12 09 27 PM" src="https://user-images.githubusercontent.com/33528848/219892969-124b67e1-5c2e-4270-80d9-20c64b734ae0.png">

### Code snippets
NA

**Comment by josetr** [comment]
It seems like the url given to `__MEDUSA_BACKEND_URL__` should not end with a `slash`, otherwise, we will end up with a `https://domain:9000//admin/analytics-configs` request that will always fail.

**Comment by olivermrbl** [comment]
Thanks for pitching in @josetr. This is highly likely the case 👍

**Comment by warm-bagel** [comment]
Y'all were correct! Thank you! And actually, I had some other issues too that I worked out. Thanks!
