### ISSUE TITLE
Cron jobs randomly registered and never gets executed

### ISSUE THREAD

**Issue by bentrynning** [medusajs/medusa#3320]
I have testet with different setups on local machine and also asked in Discord help sections for anyone els with this issue. But without luck. So I will try to describe the issue here.

### Cron jobs not registered or running as expected

Cron jobs with both the new `jobSchedulerService` and the old `eventBusService` are often not registered when Medusa server starts. But common for them all is that none of the cron jobs get triggered to run. I have tried with both the `"* * * * *"` execute every minute or `"0 0 * * *"` every hour. But never see any job execution in the terminal log. 

Also if you have more the on loader in the loader folder most of the time only one of them is registered.

(edit) Today i noticed that it only the last file in the loaders folder thats not being registred. If you add a new file lets say
`file1.js`
`file2.js`
Then its only the first file that gets registred. If you add another one like
`file1.js`
`file2.js`
`file3.js`
Then file1 and 2 gets registred but not file3. etc. 

Eks job
```js
const myJob = async (container, options) => {
  const jobSchedulerService: JobSchedulerService = container.resolve(
    "jobSchedulerService"
  );

  jobSchedulerService.create(
    "my-console-job",
    {},
    "* * * * *",
    async () => {
      console.log("my-console-job executed");
    },
    { keepExisting: false }
  );
};

export default myJob;
```

### System information

Medusa version (including plugins): 1.6.0 and up to 1.7.8
Node.js version: 18.14.2 lts and v19.4.0
Database: Both postgres 12 / 14 and Sqlite
Operating system: mac / linux docker for redis and db
Browser (if relevant):

### Steps to reproduce the behavior

1. `npm install @medusajs/medusa-cli -g`
2.  update deps to lates version or stay on current
3. `medusa new my-medusa-store --seed`
4. `docker-compose up -d` to start a medusa redis and backend (can remove medusa build from docker-compose)
5.  create a loader folder in src and create a new cron file as the example above. 
6.  start medusa sever with `yarn start`

### Screenshot
3 jobs
![image](https://user-images.githubusercontent.com/2891064/220753164-51f32c13-9bd6-4825-889e-5adc40075515.png)

2 registred
![image](https://user-images.githubusercontent.com/2891064/220753117-c08f421b-c9b0-4f11-9ee6-3d11c1c3eb04.png)

### Expected behavior

Expect to see all registered job in Medusa server logs when running and  current jobs being executed

### Additional context
I have also noticed that with medusa develop sometimes the files in src is not created before Medusa server start. 
So to be sure you have to run `yarn / npm build` first.

**Comment by olivermrbl** [comment]
@bentrynning What compiler are you using? Babel?

**Comment by bentrynning** [comment]
@olivermrbl I just use the default build setup that comes with medusa when generated from the cli
I also tested with swc with as little transformation as possible (did not make a difference). 
But have not tried with plain tsc, are you using tsc in the build command by default for Medusa now ?

**Comment by bentrynning** [comment]
> hey, i also have this problem, but i fixed that by adding empty file-> z.js to the folder) #3316

Yep but that I still have the problem with the cron jobs not being executed, but will try @olivermrbl solution with tsc. Just need a repo with example setup for the tsconfig if I need something specific.

**Comment by bentrynning** [comment]
@olivermrbl 

Tested with tsc now, same thing files are beeing registered but none of the are executed. 
My docker-compose setup is like this

```yaml
services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-docker

  redis:
    image: redis
    ports:
      - "6379:6379"
```
REDIS_URL = redis://localhost:6379

I can see that Medusa connects to redis db, but don't se any event i the logs or in the terminal log after server start:
![image](https://user-images.githubusercontent.com/2891064/221022791-cdbe9898-ee7a-4bba-a63f-9447677d6d92.png)

**Comment by bentrynning** [comment]
I have been digging some more, and it looks like if you have one job that fails to execute all other jobs will also stop and no new just will start after that. How can you manage or see all the added cron jobs? I see that you can install son gui to bull that is used under the hood. But is there a way to manages this without overriding Medusa core ?

**Comment by olivermrbl** [comment]
Have you [configured Redis in `medusa-config.js`](https://docs.medusajs.com/tutorial/set-up-your-development-environment#redis)? I don't see any mentions of that.

**Comment by olivermrbl** [comment]
> 

That PR seems unrelated to this issue. Did you link the correct one?

**Comment by maxpanakov** [comment]
@olivermrbl, sry, #3056

**Comment by bentrynning** [comment]
> Have you [configured Redis in `medusa-config.js`](https://docs.medusajs.com/tutorial/set-up-your-development-environment#redis)? I don't see any mention of that.

Yep also mention above  what redis url I use in the comment with screenshots :) 
```js
  projectConfig: {
    redis_url: REDIS_URL,
```

But if you se my last comment it looks like it works the first time, but if on of the corn jobs fails every one els will stop running as well. So is there a way to manage all added cron jobs or how can u see whats been added etc ? :)

**Comment by bentrynning** [comment]
Here are some status dato from the redis store. Building 3 cron jobs all simple ones this is what I see in redis DB

```json
127.0.0.1:6379> KEYS *
 1) "bull:scheduled-jobs:queue:repeat:6872dd5f1d405f28f2a6ee1783cda903:1677255240000"
 2) "bull:scheduled-jobs:queue:failed"
 3) "bull:scheduled-jobs:queue:repeat"
 4) "bull:scheduled-jobs:queue:repeat:4cbf23d5f43b0a0b4028b1b7b7b1d682:1677255180000"
 5) "bull:scheduled-jobs:queue:repeat:7e61c98f744403f054bed08fddb0d002:1677255180000"
 6) "bull:scheduled-jobs:queue:repeat:e849d1546c9fa7d545bac089c9a980cf:1677255240000"
 7) "bull:scheduled-jobs:queue:repeat:6872dd5f1d405f28f2a6ee1783cda903:1677255180000"
 8) "bull:scheduled-jobs:queue:repeat:4cbf23d5f43b0a0b4028b1b7b7b1d682:1677255240000"
 9) "bull:scheduled-jobs:queue:delayed"
10) "bull:scheduled-jobs:queue:repeat:7e61c98f744403f054bed08fddb0d002:1677255240000"
11) "bull:EventBusService:queue:stalled-check"
12) "bull:scheduled-jobs:queue:stalled-check"
13) "bull:scheduled-jobs:queue:id"
14) "bull:scheduled-jobs:queue:repeat:e849d1546c9fa7d545bac089c9a980cf:1677255180000"
127.0.0.1:6379> 
```

Example cron job that is created are
```
import JobSchedulerService from "@medusajs/medusa/dist/services/job-scheduler";

const myCJob = async (container, options) => {
  const jobSchedulerService: JobSchedulerService = container.resolve(
    "jobSchedulerService"
  );

  jobSchedulerService.create(
    "my-c-job",
    {},
    "* * * * *",
    async () => {
      console.log("my-c-job executed");
    },
    { keepExisting: false }
  );
};

export default myCJob;
```

All 3 cron jobs are equal just different names. So not sure what I get the fail or delayed status in Redis.

**Comment by bentrynning** [comment]
Some of these jobs seams to come from my other project witch is running on a different docker postgresql db and redis. And those instances of docker db and redis are not running. Since I have set up a new test project on the side, just for debugging thus issue. So not sure how the old cron jobs are added to the new redis instance. 
 
 So where are cron jobs store in medusa db, I see a stagejob table, but don't see any of the registred cron jobs there. :)

**Comment by bentrynning** [comment]
This is getting stranger and stranger. I delete all my docker postgresql and Redis instances. 
- Restart my macbook so memory is cleared.
- Go in the new medusa project
- Run docker-compose up -d to create new DB and Redis instances. 
- Run yarn seed to fill the empty database with data

Then check my Redis instance and woops without even starting the medusa server Redis has gets some of the old cron jobs in. Not sure how and where Redis receives this data from 🤔  

```js
127.0.0.1:6379> KEYS *
1) "bull:scheduled-jobs:queue:repeat"
2) "bull:scheduled-jobs:queue:repeat:6872dd5f1d405f28f2a6ee1783cda903:1677257640000"
3) "bull:scheduled-jobs:queue:id"
4) "bull:scheduled-jobs:queue:delayed"
5) "bull:scheduled-jobs:queue:repeat:e849d1546c9fa7d545bac089c9a980cf:1677257640000"
6) "bull:scheduled-jobs:queue:repeat:4cbf23d5f43b0a0b4028b1b7b7b1d682:1677257640000"
127.0.0.1:6379> 
```

**Comment by bentrynning** [comment]
Here is the error message stored in Redis:
```js
[
  "Error: Missing process handler for job type my-second-job\n    at Queue.processJob (/Users/bentrynning/Git/my-medusa-store/node_modules/bull/lib/queue.js:1102:7)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
]
```

```js
{
  "repeat": {
      "count": 8,
      "key": "my-second-job::::* * * * *",
      "cron": "* * * * *"
  },
  "jobId": "repeat:e849d1546c9fa7d545bac089c9a980cf:1677268920000",
  "delay": 59974,
  "timestamp": 1677268860026,
  "prevMillis": 1677268920000,
  "attempts": 1
}
```

**Comment by olivermrbl** [comment]
> So is there a way to manage all added cron jobs, or how can you see whats been added etc

Not a solution to your problem, but I recommend [RedisInsight](https://redis.com/redis-enterprise/redis-insight/) if you want a GUI for Redis. For some cases, I find it easier to use than the CLI.

> Also when you test are you running redis in a docker container

Unfortunately, I don't have experience running Redis in a container, so I can't be of much help in this regard. I'll play around with our JobScheduler early next week and try to reproduce your issue. Will get back to you as soon as possible.

>When you have time can you share your tsc config for when it works for you

@adrien2p will you share your `tsc` config?

**Comment by bentrynning** [comment]
@olivermrbl thanks for heads up and info :) 

The docker container setup is what your Medusajs server comes with when you initialise a new Medusa backend from your cli :) 

Ill try to debug and test some more tonight while I wait for your result from testing when you have time 🙏

**Comment by olivermrbl** [comment]
> The docker container setup is what your Medusajs server comes with when you initialise a new Medusa backend from your cli

The docker files in the starter project are community maintained. More detailed versions can be found in [this repository](https://github.com/medusajs/docker-medusa). Don't hesitate to open PRs with changes as you dig out these issues - we'd be happy to accept that :)

I'll keep you posted on my tests!

**Comment by olivermrbl** [comment]
@bentrynning, will you test the latest changes when time allows for it? I am closing the issue in the meantime. Feel free to reopen if your issues persist.

**Comment by bentrynning** [comment]
> @bentrynning, will you test the latest changes when time allows for it? I am closing the issue in the meantime. Feel free to reopen if your issues persist.

Testing tonight!

**Comment by olivermrbl** [comment]
@bentrynning have you had a chance to test it out? 😊

**Comment by adrien2p** [comment]
here is my ts config in my local project

```json
{
  "compilerOptions": {
    "lib": [
      "es5",
      "es6",
      "es2019"
    ],
    "target": "es5",
    "outDir": "./dist",
    "esModuleInterop": true,
    "declaration": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "noImplicitReturns": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "noImplicitThis": true,
    "allowJs": true,
    "skipLibCheck": true,
    "downlevelIteration": true,
    "rootDir": "src"
  },
  "include": [
    "./src/**/*",
    "src/index.d.ts"
  ],
  "exclude": [
    "./dist/**/*",
    "./src/**/__tests__",
    "./src/**/__mocks__",
    "node_modules"
  ]
}

```
