### ISSUE TITLE
Active payment session gets deleted from cart when cart total = 0

### ISSUE THREAD

**Issue by chemicalkosek** [medusajs/medusa#3336]
### Describe the bug

I was trying to help out with this issue: https://github.com/medusajs/medusa/issues/3333, and while seeking for a reproduction I have noticed then when cart is emptied (total is 0), only the active payment session gets deleted from the cart. 

### System information

Medusa version (including plugins): 1.7.8, stripe 1.1.53
Node.js version: 18.12.1
Database: postgres

### Steps to reproduce the behavior

In my case I have three payment providers (stripe, stripe-blik, stripe-przelewy24)

1. Add item to cart
2. Create payment sessions -> `cart.payment_sessions.length === 3`
3. Set payment session.
4. Remove item from cart (cart total = 0)
5. See in the returned response `cart.payment_sessions.length === 2`

If you run setPaymentSession again using any of the remaining sessions (after adding an item again), the missing  payment_session will reappear.

### Expected behavior

Edit: Initially I thought it shouldn't be deleted but I believe the intended behavior is that all payment sessions are deleted

### Additional context

As requested, Adrien's initial thoughts on the issue:
_the initiated one calls remove on session entity while the other ones call delete
which might defer_

**Comment by olivermrbl** [comment]
@adrien2p Will you be able to assist here 😊

**Comment by adrien2p** [comment]
@olivermrbl yes sure 👌
