### ISSUE TITLE
Multi - vendor plugin

### ISSUE THREAD

**Issue by pragnikadia** [medusajs/medusa#3348]
does medusa provide multi-vendor plugin??.. if yes then how can we install that in existing medusa project

**Comment by SGFGOV** [comment]
Short answer is what do you mean by multivendor?

Do you mean a marketplace vendor module or a shopify like multi store?

**Comment by pragnikadia** [comment]
marketplace vendor module

**Comment by pragnikadia** [comment]
is there any update, can just please let me know that if it is posible via any plugin or do i have to customized on my side, can you give me some reference??

**Comment by SGFGOV** [comment]
Have you used the market place example using the extender

**Comment by pragnikadia** [comment]
can you give me resource link here

**Comment by olivermrbl** [comment]
Closing this as this is not a bug. Please take a look at our Discussions for feature requests. The [multi-vendor feature has already been requested](https://github.com/medusajs/medusa/discussions/2769).
