### ISSUE TITLE
[CORE-1301] addPrices service not working to update price

### ISSUE THREAD

**Issue by nicolama-dev** [medusajs/medusa#3369]
## Bug report

addPrices service not working to update price

### Describe the bug

It seems the addPrices service from priceLists does not work to update an existing price in the priceList.
The creation of a price works well however if we pass the id of an existing price_amount it does nothing.
In the add-price-batch.ts we can see in the comments that passing AdminPriceListPricesUpdateReq should work.

### System information

Medusa version (including plugins): 1.7.9

### Expected behavior

Update the price_amount

### Code snippets

`    const updatedPrice: AdminPriceListPricesUpdateReq = {
      id: money_amount_id
      amount: Math.round(originalPrice.amount * (1 - discount)),
      currency_code: originalPrice.currency_code,
      min_quantity,
      max_quantity,
      variant_id: variant.id,
    };

    await this.#manager.transaction(async (transactionManager) => {
      await this.priceListService
        .withTransaction(transactionManager)
        .addPrices(priceList.id, [updatedPrice]);
    });

`

<sub>[CORE-1301](https://linear.app/medusajs/issue/CORE-1301/addprices-service-not-working-to-update-price)</sub>

**Comment by fPolic** [comment]
Hey @nicolama-dev, if you wish to upsert prices the `priceList.update` method should be used. The `addPrices` will add new prices or replace all prices in the price list with new ones.
So if we replace `addPrices`  with `update` in the example above you should get the desired behaviour.
