### ISSUE TITLE
[CORE-1300] BatchJob rerunning completed jobs

### ISSUE THREAD

**Issue by SGFGOV** [medusajs/medusa#3427]
## Bug report

BatchJobService re runs completed jobs, and throws an exception  saying cannot 

code:
undefined
date:
Thu Mar 09 2023 10:44:42 GMT+0000 (Coordinated Universal Time)
message:
'Cannot mark a batch job as processing if the status is different that confirmed'
type:
'not_allowed'
stack:
'Error: Cannot ma
### System information

Medusa version (including plugins):1.7.9+
Node.js version: 16+
Database: postgres
Operating system: linux
Browser (if relevant):

### Steps to reproduce the behavior

Create 50 batches with 50 products each. Some batches fail. 

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

<sub>[CORE-1300](https://linear.app/medusajs/issue/CORE-1300/batchjob-rerunning-completed-jobs)</sub>

**Comment by adrien2p** [comment]
Are you sure that the batch jobs are re running after completion? A batch job runs only when one of the following events is emitted: 
- CREATED
- CONFIRMED

Could you share the following information:
- The staged_job if there is any 
- The batch job tuple (all the data please)

**Comment by SGFGOV** [comment]
Hi @adrien2p , thanks for taking this up. I'll send you the data asap.  I'm not sure if the bug exists in 1.8 because you are forcefully removing old failed events. In the older versions the events would persist in redis until redis cache was flushed or event was emitted succefully. For example if we reset the server during dev, the cache may not be flushed and old events were remitted

**Comment by SGFGOV** [comment]
I'm unable to recreate this issue in 1.8 however, when the server does crash I seem to get a related error like this

Error: Missing lock for job job_01GYFXSK1E38MB28Z441DGGNVB. failed
    at Scripts.finishedErrors (<path to application folder>/node_modules/bullmq/dist/cjs/classes/scripts.js:218:24)
    at Job.moveToFailed (<path to application folder>/node_modules/bullmq/dist/cjs/classes/job.js:406:32)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async handleFailed (<path to application folder>/node_modules/bullmq/dist/cjs/classes/worker.js:331:21)
    at async Worker.retryIfFailed (<path to application folder>/node_modules/bullmq/dist/cjs/classes/worker.js:520:24)

**Comment by SGFGOV** [comment]
This was because the ACK wasn't received by the redis stream for the particular job event. So even though the job was completed it attempted to retry it. ACK wasn't received because the server may have been reset during the run.  I've not observed this with the latest release, perhaps because we remove unsuccessful events.
