### ISSUE TITLE
Couldn't launch storefront with create-medusa-app installation (Server, admin are fine)

### ISSUE THREAD

**Issue by sushant4849** [medusajs/medusa#3428]
I installed medusa with create-medusa-app on windows with next.js starter. Did no other modifications so far.

Server and admin are launching fine with yarn start on port's 9000 and 7000 respectively. But storefront is always failing irrespective of whatever I tried. I tried "yarn run dev", "yarn dev" - both failing with below error. npm run dev too fails. "Yarn start" failing because it needs a production build.

C:\Users\mypc\my-medusa-store\storefront>yarn run dev
yarn run v1.22.19
warning ..\..\package.json: No license field
$ next dev -p 8000
ready - started server on 0.0.0.0:8000, url: http://localhost:8000
next.config.js {
  "reactStrictMode": true,
  "images": {
    "domains": [
      "medusa-public-images.s3.eu-west-1.amazonaws.com",
      "localhost"
    ]
  },
  "env": {}
}
error Command failed with exit code 3221225477.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by kasperkristensen** [comment]
Hi @sushant4849 

From doing a quick google search, the exit code `3221225477` seems to stem from issues with windows access violations usually. We don't have much we can do to help you here, as it is entirely related to your local environment. 

Here are some of the things you can look into:

- Check your Node version, and if you are running a dated version, upgrade to at least > 14.
- Check if your antivirus software is blocking node processes.
