### ISSUE TITLE
Docs(Code Issue): Code Issue in /advanced/backend/payment/how-to-create-payment-provider

### ISSUE THREAD

**Issue by milasantacruz** [medusajs/medusa#3439]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The problem:  Im getting this error while following the instructions to create a Payment service un a medusajs backend

Module '"@medusajs/medusa"' has no exported member 'PaymentContext'.
Module '"@medusajs/medusa"' has no exported member 'PaymentSessionResponse'.

This is my package.json

```
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Sebastian Rindom <skrindom@gmail.com>",
  "license": "MIT",
  "scripts": {
    "seed": "medusa seed -f ./data/seed.json",
    "build": "babel src -d dist --extensions \".ts,.js\"",
    "start": "medusa develop"
  },
  "dependencies": {
    "@medusajs/medusa": "^1.6.0",
    "@medusajs/medusa-cli": "^1.3.3",
    "medusa-file-minio": "^1.1.1",
    "medusa-fulfillment-manual": "^1.1.31",
    "medusa-interfaces": "^1.3.3",
    "medusa-payment-manual": "^1.0.16",
    "medusa-payment-stripe": "^1.1.45",
    "medusa-plugin-strapi": "^1.0.7-dev",
    "mercadopago": "^1.5.14",
    "typeorm": "^0.2.36"
  },
  "repository": "https://github.com/medusajs/medusa-starter-default.git",
  "keywords": [
    "sqlite",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "devDependencies": {
    "@babel/cli": "^7.18.10",
    "@babel/core": "^7.18.10",
    "@babel/preset-typescript": "^7.14.5",
    "babel-preset-medusa-package": "^1.1.19"
  }
}

```

thanks in advance

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Hi @milasantacruz can you share the code for your payment service? Also, when you run the command `npm list @medusajs/medusa` what is the output?

**Comment by milasantacruz** [comment]
@shahednasser  Thanks for your reply. I finally figured it out, I updated my medusa package to 1.7.12 and the problem solved

**Comment by shahednasser** [comment]
Great to hear! I'll close this issue then 👍🏻
