### ISSUE TITLE
Why are you sending phishing links?

### ISSUE THREAD

**Issue by sw-yx** [medusajs/medusa#344]
i received this email today from you.

![image](https://user-images.githubusercontent.com/6764957/129955263-a9668da5-2347-4176-9a35-dfe56b434a6b.png)

1. you are scraping github users and sending unsolicited email
2. you are sending shady af phishing links 
3. i am reporting you to github.

**Comment by srindom** [comment]
Hi @sw-yx, really sorry to see this - we are definitely not trying to scam anyone and will 100% make sure to fix this straight away!
