### ISSUE TITLE
Medusa admin 502 Bad Gateway

### ISSUE THREAD

**Issue by MG-Musty** [medusajs/medusa#3455]
## Bug report
I run the server to open the admin panel after perfectly installing it , but when i try opening the port 7000 in my browser it kept say 502 Bad gateway so i have search and look for help no solution till now.
### System information

Medusa version (including plugins):
Node.js version:
Database: medusa-admin
Operating system: Github codespace
Browser (if relevant): Chrome

### Screenshots

![medusa](https://user-images.githubusercontent.com/106968663/224507692-ec5cddc5-b868-4d55-abff-205cee7f4e4a.png)

![med 502](https://user-images.githubusercontent.com/106968663/224507710-35071821-2d35-4919-b2dc-0192557a32bc.png)

**Comment by olivermrbl** [comment]
@MG-Musty I am not sure, we can be of much help. In your terminal, it clearly states, that the admin is running on `http://localhost:7000`, which works as expected, I presume. 

Are you trying to access it via a proxy or similar? 

In any case, I will not treat this as an issue, as it is not directly related to an issue with our core engine.
