### ISSUE TITLE
Unable to access Medusa Admin interface remotely (Localhost:7000 works fine)

### ISSUE THREAD

**Issue by sushant4849** [medusajs/medusa#3456]
Medusa admin seems to be running and listening fine at local port 7000. But refusing connections when trying to access it remotely.

It's refusing connections through external IP address. It's not a firewall issue at all. I totally disabled firewalls, both in cloud hosting provider console and also with "sudo ufw disable".

For example,
telnet localhost 7000
 _responds_
telnet 65.33.20.221 7000
 _fails_

I tried starting with external ip address flag "npm run start -- --host 65.33.20.221". I even attempted playing with few settings in vite.config.ts. I also tried it in different cloud hosting services. Nothing works.

Medusa server has no such issue. Resolves fine on both localhost and from public IP address.

This issue seems to be already posted by someone earlier: https://github.com/medusajs/admin/issues/827

But has no resolution, so posting it again here.

**Comment by olivermrbl** [comment]
I will not treat this as an issue, as it is not directly related to our core engine but more a problem with your deployment setup. I suggest you ask for help in Discord, as I am afraid, we will not be able to provide much input for now.
