### ISSUE TITLE
401 responses in the admin panel

### ISSUE THREAD

**Issue by gabriel-frattini** [medusajs/medusa#3488]
### Describe the bug

After i login to the admin panel all requests get 401 responses with 'Unauthorized' as body. (It happens on Chrome, safari and firefox)

<img width="608" alt="Screenshot 2023-03-15 at 19 23 05" src="https://user-images.githubusercontent.com/96744665/225406552-424134bf-1f57-40b7-b49e-c0d5be2cc959.png">

After I get logged in the initial page load does a lot of requests so I just took a screenshot on one of them to show what it looks like

The request headers looks like this

<img width="699" alt="Screenshot 2023-03-15 at 17 49 08" src="https://user-images.githubusercontent.com/96744665/225381954-eeef6bbb-d14a-4e61-98ec-5d5c0efb781a.png">

And the response headers like this

<img width="704" alt="Screenshot 2023-03-15 at 17 46 34" src="https://user-images.githubusercontent.com/96744665/225381413-4f3eccfd-b881-42fa-ad3e-6e65da558597.png">

and the response 

<img width="211" alt="Screenshot 2023-03-15 at 18 04 25" src="https://user-images.githubusercontent.com/96744665/225385952-0d88eaa6-f98a-488b-9e40-9b8300c9fac6.png">

When i navigate to the server's domain I can see that the cookie has been set

<img width="633" alt="Screenshot 2023-03-15 at 19 19 32" src="https://user-images.githubusercontent.com/96744665/225405822-3b9e03b7-0bfb-40d9-9250-28b0f437a98b.png">

On localhost it works, I don't get any 401 responses after login there.

### System information

Medusa version (including plugins): 1.6.0
Node.js version: v16.19.1
Database: postgres
Operating system: linux
Browser (if relevant): chrome

### Expected behavior

I should be authorized and all requests should get 200 status code back 

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

The server is hosted on digitalocean's app platform and the admin panel is on vercel. Both have their nameservers managed by another domain registrar and also have SSL there.

The server is at https://api.my-domain.se and the admin panel is at https://admin.my-domain.se

I also set `NODE_ENV=production` as recommended in this comment https://github.com/medusajs/admin/issues/596#issuecomment-1153603558

**Comment by gabriel-frattini** [comment]
I closed and reopened this issue because I thought I had a fix but It was not that.

**Comment by kasperkristensen** [comment]
Hi @gabriel-frattini 

This can be due to a variety of issues, here are some things that you can look into:

1. Both your server and admin should use HTTPS, when the server is run in a production environment, otherwise cookies can't be set.
2. Make sure your domains aren't on the public suffix list, e.g. `*.heroku.app`, `*.vercel.app`, etc.
3. macOS blocks cross-domain cookies from being set by default, in order to get around this your admin and server need to share a domain. You can achieve this by using subdomains, e.g. `api.mydomain.com` and `admin.mydomain.com`.
4. Since you haven't specified anything surrounding your setup I can't know for sure but if you are using something like NGINX you will also need to set it up accordingly to allow cookies to be set.

I am closing this as it is not related to Medusa, but due to the requirements for how to work with cookies in production not being met somehow. If you have any more questions surrounding this then I would suggest that you join our Discord, where you will be able to receive help from others that have experience with setting their server and admin up on different setups. 😄

**Comment by stephane-klein** [comment]
@gabriel-frattini have you fix your issue? I have the same error with this setup: https://github.com/stephane-klein/medusa-hosting-playground :thinking:.

**Comment by chemicalkosek** [comment]
@stephane-klein It's not a fix, it's merely a workaround. 

I would suggest to read my post here: https://github.com/medusajs/medusa/issues/2314#issuecomment-1422429232
You can also hop into Medusa discord server if you still have issues with `production` NODE_ENV

**Comment by nehalahmadkhan** [comment]
I am having the same issue, mine is hosted on a digital ocean droplet with Nginx.
It works fine on the local host when I run npm start and access the admin UI at http://localhost:9000/app 
but when I try to do the same on the server with same env vaiables it just redirects me back to the login page.
it gives 401 errors like this
![image](https://github.com/medusajs/medusa/assets/72778495/063cff71-f12c-4a16-8e5c-55a34d2ac876)
here are details of one of the request
![image](https://github.com/medusajs/medusa/assets/72778495/6c72bdd0-142d-42ff-b8e0-a3fe0a3ce97f)

here are my evs
```
DATABASE_TYPE=postgres
DATABASE_URL=postgresql://.....
JWT_SECRET=bVra...
COOKIE_SECRET=J31X...
NPM_CONFIG_PRODUCTION=false
YARN_PRODUCTION=false
NODE_ENV=production

```
also when I try to fetch normal store API like https://api.everydayoptics.in/store/products it works fine:
![image](https://github.com/medusajs/medusa/assets/72778495/3690887b-2b91-4d93-b995-e6d3e6bc935e)


I am using the default admin panel on the same domain, so it should not be a CORS error.
Here is my Nginx config I just left the root routes(everydayoptics.in and www.everydayoptics.in) to show the default Nginx page for now and use the API subdomain (api.everydayoptics.in) for the backend and admin panel.

  ```
server {
        listen 80;
        listen [::]:80;
        server_name everydayoptics.in www.everydayoptics.in api.everydayoptics.in;
        return 301 https://$host$request_uri;
    }

  server {
      listen 443 ssl;
      listen [::]:443 ssl;
      server_name www.everydayoptics.in;
  
      ssl_certificate /etc/letsencrypt/live/everydayoptics.in/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/everydayoptics.in/privkey.pem;
      include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
      ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
  
      return 301 https://everydayoptics.in$request_uri;
  }
  
  server {
  
      server_name everydayoptics.in;
  
      listen [::]:443 ssl ipv6only=on; # managed by Certbot
      listen 443 ssl; # managed by Certbot
      ssl_certificate /etc/letsencrypt/live/everydayoptics.in/fullchain.pem; # managed by Certbot
      ssl_certificate_key /etc/letsencrypt/live/everydayoptics.in/privkey.pem; # managed by Certbot
      include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
      ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
  
      location / {
          try_files $uri $uri/ =404;
      }
  
  }
  
  server {
      server_name api.everydayoptics.in;
  
      listen [::]:443 ssl ipv6only=on; # managed by Certbot
      listen 443 ssl; # managed by Certbot
      ssl_certificate /etc/letsencrypt/live/everydayoptics.in/fullchain.pem; # managed by Certbot
      ssl_certificate_key /etc/letsencrypt/live/everydayoptics.in/privkey.pem; # managed by Certbot
      include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
      ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
  
      location / {
          proxy_pass http://localhost:9000;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection 'upgrade';
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;
      }
  
  }
```

**Comment by fipso** [comment]
I had the same issue with nginx and was able to fix it with those options:
```
location / {
		proxy_set_header Host $host;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $http_connection;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header X-Scheme $scheme;

		proxy_pass http://127.0.0.1:9000;
	}
```

**Comment by Reomar** [comment]
did you solve it?

**Comment by piereligio** [comment]
I solved it altering the medusa-config.js . The issue was if you redefined the path from resolve: "@medusajs/admin" options and you ran medusa with medusa develop.
Personally I added a variable in my env for solving it. If it exists (only where I run medusa start), then it's used, otherwise it's null.

**Comment by gyurka00** [comment]
@piereligio 
Can you explain a bit more what did you do to solve it?
Did you solved it for v1 or v2?
https://docs.medusajs.com/v1/admin/configuration

**Comment by piereligio** [comment]
> @piereligio 
> Can you explain a bit more what did you do to solve it?
> Did you solved it for v1 or v2?
> https://docs.medusajs.com/v1/admin/configuration

I am on Medusa 1.7.2

**Comment by raweber42** [comment]
For people trying to deploy with Docker: It's definitely a CORS issue. See also here: https://github.com/medusajs/medusa/discussions/11722
