### ISSUE TITLE
Documentation for `Advanced` concepts is missing

### ISSUE THREAD

**Issue by MandelaK** [medusajs/medusa#3501]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Documentation for `Advanced` concepts are missing from the hosted docs pages. I noticed this as I was following along a guide on creating a custom payment provider... The links are returned even when a user searches on the docs page, but the resulting pages return a 404... You can test this by attempting to visit this page -> https://docs.medusajs.com/advanced/backend/payment/how-to-create-payment-provider/ 

This, and most links that were under the `advanced` guides are missing

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for reporting this @MandelaK will issue a fix right away! In the meantime, you can access the documentation [here](https://docs.medusajs.com/modules/carts-and-checkout/backend/add-payment-provider).
