### ISSUE TITLE
PUT admin/products/:product_id/variants/:variant_id returns stale variant prices

### ISSUE THREAD

**Issue by dwene** [medusajs/medusa#3503]
### Describe the bug

When updating prices in the Medusa Admin, I noticed that the API was returning the old price after update.

After some investigation, it looks like the default price-selection-strategy is caching prices for 30 seconds, and the cache is not invalidated as part of `ProductVariantService.update`.

It seems like we probably need an additional function added to `IPriceSelectionStrategy` that informs the service that the price has been updated, so it can invalidate any caches it is using.

I was able to hack in a fix using the extender like this:

```
export interface ConstructorArgs {
  cacheService: CacheService;
}

@Service({ override: MedusaProductVariantService })
export class ProductVariantService extends MedusaProductVariantService {
  protected cacheService: CacheService;
  constructor(args: ConstructorArgs) {
    super(arguments[0]);
    this.cacheService = args.cacheService;
  }

  protected async updateVariantPricesBatch(data: UpdateVariantPricesData[]): Promise<void> {
    await super.updateVariantPricesBatch(data);
    for (const variant_id of new Set(...data.map(d => d.variantId))) {
      await this.cacheService.invalidate(`ps:${variant_id}*`);
    }
  }
}

```

But obviously it's a hack because it assumes we are using the default price selection strategy, and that cache key doesn't change :)

### System information

Medusa version (including plugins): 1.7.14
Node.js version: 16
Database: Postgres
Operating system: OSX
Browser (if relevant): N/A

### Steps to reproduce the behavior

Create a product in the admin
Attempt to update one of the variant prices a few times.
Notice the old price is returned sometimes

### Expected behavior

Updating variant price should update immediately, not return an old value

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by olivermrbl** [comment]
Thanks for filing this issue @dwene. We've escalated the priority on this one. The solution we've decided to go with is to move the cache invalidation from the subscriber to the ProductVariantService :)

**Comment by olivermrbl** [comment]
@dwene We would appreciate a review of #3553, if time allows. Aim to merge one of the coming days :)
