### ISSUE TITLE
retrieveBySKU relations "product.type" only returns type_id and not product.type

### ISSUE THREAD

**Issue by jono-allen** [medusajs/medusa#3506]
## Bug report
retrieveBySKU relations "product.type" only returns type_id and not product.type
Expect `productVariant.product.type.value` to be returned from the query

### Describe the bug

When querying `retrieveBySKU` via `productVariantService`
```
  const productVariant = await productVariantService.retrieveBySKU(sku, {
      relations: ['product', 'product.type', 'options', 'options.option'],
  });
```
ProductVariant.Product.type is undefined when specifying it in the relations to be returned.
ProductVaraint.options.option is returned

### System information

Medusa version (including plugins):1.7.8
Node.js version: v16.17.0
Database: Postgres 14
Operating system: macOS 13.1
Browser (if relevant):

### Actual behaviour
productVariant.options[].id is present
productVariant.product.type_id is present
productVariant.product.type.id is undefined

### Expected behaviour
productVariant.product.type.id is present
productVariant.product.type_id is present

### Screenshots

![carbon](https://user-images.githubusercontent.com/6656869/225774755-4e7844ad-0f4c-43f8-925e-dc824e167ded.png)

**Comment by olivermrbl** [comment]
Thanks for reporting this one @jono-allen. This issue has been resolved in 1.8 coming out very soon. Closing this for now.
