### ISSUE TITLE
CORS blocks request to Admin endpoint despite being configured

### ISSUE THREAD

**Issue by AlexTechNoir** [medusajs/medusa#3520]
### Describe the bug

Good day!

I have a custom Admin endpoint with CORS and auth configuration:
`src/api/index.ts`:
```javascript
import { Router } from "express"
import authenticate from "@medusajs/medusa/dist/api/middlewares/authenticate"
import { getConfigFile, parseCorsOrigins } from "medusa-core-utils"
import { ConfigModule } from "@medusajs/medusa/dist/types/global"
import cors from "cors"
import bodyParser from "body-parser"

export default (rootDirectory, pluginOptions) => {
  const router = Router()

  const { configModule } = 
    getConfigFile<ConfigModule>(rootDirectory, "medusa-config")
  const { projectConfig } = configModule

  const adminCorsOptions = {
    origin: projectConfig.admin_cors.split(","),
    credentials: true,
  }

  router.use(bodyParser.json())
  router.options("/admin/downloadable_assets", cors(adminCorsOptions))
  router.post("/admin/downloadable_assets", cors(adminCorsOptions), authenticate(), (req, res) => {
    
    if (!req.user) {
      res.status(401).json({ message: "Not authorized" })
    }

    const downloadableAssetService = req.scope.resolve("downloadableAssetService")
    const data = downloadableAssetService.createOrUpdateFileUrl(
      req.body.variant_id,
      req.body.file_url
    )

    res.json({ data })
  })

  return router
}
```
CORS is configured in `medusa-config.js`:
```javascript
...

const ADMIN_CORS = process.env.ADMIN_CORS || "http://localhost:7000,http://localhost:7001";

...

module.exports = {
  projectConfig: {
    // redis_url: REDIS_URL,
    // For more production-like environment install PostgresQL
    database_url: DATABASE_URL,
    database_type: "postgres",
    database_database: "./medusa-db.sql",
    database_logging: true,
    // database_type: "sqlite",
    store_cors: STORE_CORS,
    admin_cors: ADMIN_CORS,
  },
  plugins,
};
```
With env var being `ADMIN_CORS=http://localhost:7000`

I'm making a POST request from this function:
```javascript
async function testRequest() {

  const data = await fetch(
    "http://localhost:9000/admin/downloadable_assets",
    {
      method: "POST",
      credentials: "include",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        variant_id: variantId,
        file_url: url,
      }),
    }
  )
    .then((response) => response.json())
    .catch((err) => console.error("Err: ", err))

  console.log(data)
}
testRequest()
```
When the `response` object is json parsed, console prints: `SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON`, which means it sends HTML with error

When I inspect unparsed `response` object in console (`.then((response) => console.log(response))`), it shows that the error is related to CORS:
![111](https://user-images.githubusercontent.com/43852391/226171074-08a22b7b-2c5e-4935-a37b-868e21bee88f.jpg)

I've done all configurations mentioned in docs, but error still appears.

Can anyone tell me what is wrong here?

**Comment by olivermrbl** [comment]
@AlexTechNoir, I can't seem to reproduce your issue. I pasted your API handler into a new Medusa project, which worked as expected. Though I did so without the call to the `downloadableAssetService`, so it might be related to one. 

Can you wrap the resolver and method call in a try/catch to see if it spits out any errors?

```
try {
  const downloadableAssetService = req.scope.resolve("downloadableAssetService")
  const data = downloadableAssetService.createOrUpdateFileUrl(
  req.body.variant_id,
  req.body.file_url
  )
catch (error) {
  console.log(error)
}

**Comment by AlexTechNoir** [comment]
The issue was that the endpoint couldn't resolve Service, which in its turn had problem with calling Repository, which I named in plural form, that should be singular, probably according to its singular file name or singular name of imported Entity. 

I didn't know that naming rules explained in Service docs are also applied to other types of modules, like Repo 🤷‍♂️

Thank you, Oliver, sorry for bothering!
