### ISSUE TITLE
Package(medusa-file-spaces): Npm error installing package

### ISSUE THREAD

**Issue by masserra** [medusajs/medusa#3564]
## Bug report
Error installing [medusa-file-spaces](https://github.com/medusajs/medusa/tree/master/packages/medusa-file-spaces) package using NPM but not using YARN.

### Describe the bug
When installing the package using NPM we get the following error...
```
npm ERR! Could not resolve dependency:
npm ERR! peer medusa-interfaces@"1.3.7-ci-issue-20230322190222" from medusa-file-spaces@1.3.6-ci-issue-20230322190222
```
...although when adding it with YARN it all works fine.

(For a complete look at the logs for both the NPM and YARN attempts please see images bellow)

### System information

Medusa version (including plugins):
```
"@medusajs/medusa": "^1.6.0",
"@medusajs/medusa-cli": "^1.3.3",
"medusa-file-spaces": "^1.3.6-ci-issue-20230322190222",
"medusa-fulfillment-manual": "^1.1.31",
"medusa-interfaces": "^1.3.3",
"medusa-payment-manual": "^1.0.16",
"medusa-payment-stripe": "^1.1.45",
"typeorm": "^0.2.36"
```
Node.js version: v16.19.1
Database: SQLite
Operating system: macOS Ventura - Version 13.2.1 (22D68)

### Steps to reproduce the behavior

1. Install the medusaJS server/backend (either separately or by using the `create-medusa-app`, tried both)
2. Cd into it and `npm install medusa-file-spaces` (either after or before seeding, tried both)
3. See the error forming
4. Attempt now `yarn add medusa-file-spaces`
5. See it working without issues

### Screenshots

<img width="870" alt="Screenshot 2023-03-23 at 19 58 29" src="https://user-images.githubusercontent.com/5798388/227342934-e091a973-4c5d-4615-b7c0-ea008dc70ccd.png">
<img width="1440" alt="Screenshot 2023-03-23 at 19 58 48" src="https://user-images.githubusercontent.com/5798388/227342967-e161aae6-205c-4e5c-a4bb-c4af028edb0a.png">

**Comment by kasperkristensen** [comment]
@masserra Seems like a snapshot version somehow ended up as the `@latest` version. We will look into fixing it, for the time being you can install the actual latest releasing using `npm install medusa-file-spaces@1.3.5`

**Comment by MaxvandeLaar** [comment]
In case you aren't aware yet, this issue occurs for multiple plugins. I noticed the same for `medusa-fulfillment-manual` and `medusa-payment-manual`. I guess there are probably more.

**Comment by olivermrbl** [comment]
@MaxvandeLaar Should be solved. Sorry for the inconvenience. Will close the issue for now.
