### ISSUE TITLE
bug(medusa-payment-stripe): Stripe not showing up as payment provider

### ISSUE THREAD

**Issue by flashjames** [medusajs/medusa#3565]
As title says, Stripe not showing up as payment provider in admin interface

I followed these guides:

- https://docs.medusajs.com/plugins/payment/stripe
- https://docs.medusajs.com/modules/carts-and-checkout/backend/add-payment-provider

And I get stuck here:
https://docs.medusajs.com/user-guide/regions/providers#manage-payment-providers

As stripe payment provider isnt listed there, only manual.

And this is how admin looks:
![image](https://user-images.githubusercontent.com/359702/227456083-eaf3163b-83d9-4c91-b5c0-812b4134f588.png)

## Medusa versions
- Medusa backend: Tried with the @latest and the current master of medusa
- Medusa admin: Tried with @lastest and the current master branch

Note: Will be investigating were the issue is right now.

There's a discussion on the same issue: https://github.com/medusajs/medusa/discussions/2915
I've done the following steps, referenced in the discussion. It's seems like multiple people has the same issue.

> Can I get you to ensure, you've performed the following steps:
> 
>     * Installed the Stripe plugin (`medusa-payment-stripe`) via npm
> 
> 
> ```
> yarn add medusa-payment-stripe@latest
> ```
> 
>     * Added the Stripe plugin configuration in your `medusa-config.js`
> 
> 
> ```ts
> {
>     resolve: `medusa-payment-stripe`,
>     options: {
>       api_key: "api_key",
>       webhook_secret: "wh_secret,
>     },
>   },
> ```
> 
> Stripe will only appear in Medusa Admin, if these steps are configured correctly

**Comment by srindom** [comment]
@adrien2p

**Comment by flashjames** [comment]
Now I'm looking into it..

```
http://localhost:9000/admin/store/payment-providers

{
    "payment_providers": [
        {
            "id": "stripe-przelewy24",
            "is_installed": true
        },
        {
            "id": "stripe",
            "is_installed": true
        },
        {
            "id": "stripe-ideal",
            "is_installed": true
        },
        {
            "id": "stripe-giropay",
            "is_installed": true
        },
        {
            "id": "stripe-blik",
            "is_installed": true
        },
        {
            "id": "stripe-bancontact",
            "is_installed": true
        },
        {
            "id": "manual",
            "is_installed": true
        }
    ]
```

**Comment by chemicalkosek** [comment]
@flashjames Yes, it changed from `master` to `main` somewhere in autumn. It changed from Gatsby to Vite+React

**Comment by Gunkev** [comment]
@flashjames I just checked and I have the latest admin updates. I am using medusa 1.3.8
