### ISSUE TITLE
I keep getting network error when trying to fetch store products

### ISSUE THREAD

**Issue by EmmanuelTheCoder** [medusajs/medusa#3571]
Hi,

I keep getting the below network error when I try to fetch store products

![error img](https://user-images.githubusercontent.com/55356373/227490921-91e9c1e5-cfc7-4981-b15a-fa00c32f105d.png)

Any help?

**Comment by chemicalkosek** [comment]
Have you changed the `NEXT_PUBLIC_MEDUSA_BACKEND_URL` env var in the storefront?
You shouldn't have there `https://` but `http://`
