### ISSUE TITLE
medusa-file-s3 overrides a file if upload a file with same name 

### ISSUE THREAD

**Issue by IgorKhomenko** [medusajs/medusa#3599]
### Describe the bug

`medusa-file-s3` plugin overrides a file if upload a file with same name, e.g. `1.jpg`.
This is because here we use `file.originalname` as an S3 object key https://github.com/medusajs/medusa/blob/master/packages/medusa-file-s3/src/services/s3.js#L38

It would be great if we can use the same key formation flow as in minio plugin - https://github.com/medusajs/medusa/blob/master/packages/medusa-file-minio/src/services/minio.js#L41 - where a datetime is used as a part of key name;

### System information

Medusa version (including plugins): 1.6.x
Node.js version: 16.x 
Database: PG
Operating system: AWS Linux
Browser (if relevant): Chrome

### Steps to reproduce the behavior

1. Go to Medusa dashboard
2. Click on Create product
3. Fill with some basic info.
4. Then add media to product, e.g. a file with name `1.jpg`
5. Later, edit same product, add a new diff media, but with same name `1.jpg`

### Expected behavior

Files with same name should be treated as diff files in S3 and stored using diff keys, not same.

### Screenshots

none

### Code snippets

none

### Additional context

none

**Comment by olivermrbl** [comment]
@IgorKhomenko this would be a good improvement to the plugin. Would you be up for opening a PR with the changes?

**Comment by olivermrbl** [comment]
@chemicalkosek is right - I didn't check the actual implementation. What version are you using @IgorKhomenko? Upgrading the plugin might solve your issue.

**Comment by IgorKhomenko** [comment]
@chemicalkosek right, spaces and minio add it, but not s3. I will make a PR

**Comment by olivermrbl** [comment]
@IgorKhomenko yes, you can copy from either Spaces or Minio

**Comment by IgorKhomenko** [comment]
Here we are https://github.com/medusajs/medusa/pull/3601

**Comment by olivermrbl** [comment]
Thanks @IgorKhomenko! Will be part of next release 💪
