### ISSUE TITLE
[plugin] Strapi CMS plugin

### ISSUE THREAD

**Issue by olivermrbl** [medusajs/medusa#361]
_**Important: Skeleton initiated on branch `feat/strapi`**_

**What**
We want to add a `medusa-plugin-strapi`, that allows for content management. Should use an almost identical approach as `medusa-plugin-contentful`.

**How**
Should trigger content creation and updates in Strapi on:
- `product.created`
- `product.updated`
- `product.deleted`
- `product-variant.created`
- `product-variant.updated`
- `product-variant.deleted`
- `region.created`
- `region.updated`
- `region.deleted`

**Comment by Deathwish98** [comment]
Can I work on this ?

**Comment by olivermrbl** [comment]
Sure @Deathwish98 ! That sould be great! :) Let me know, if you need any help getting started.

**Comment by olivermrbl** [comment]
See [plugin](https://github.com/Deathwish98/medusa-plugin-strapi) for details.
