### ISSUE TITLE
[CORE-1299] Duplicating a product in Medusa Admin mixes up the resultant product's options

### ISSUE THREAD

**Issue by raidsrc** [medusajs/medusa#3674]
### Describe the bug

When you duplicate a product using Medusa Admin's "duplicate product" feature, the resulting product's choices for options will be shuffled around. See images in the "Screenshots" section.

This occurs for products and variants with many options, but you only need two options to see the issue. It's worse for products with many options because the shuffling occurs through all of the options. And when there are many products and many variants, the shuffling occurs for many of the variants, which is a huge problem.

This mixup is not just an issue with how the data is displayed. It occurs on the backend and is written to the database. See screenshots 6 and onwards.

### System information

Medusa version (including plugins): 1.3.3, Redis, MinIO, and PayPal enabled
Node.js version: 16.14.1
Database: Postgres
Operating system: Windows 10
Browser (if relevant): Firefox Version 111

### Steps to reproduce the behavior

1. Create a product with at least two variants and at least two options. Make sure you fill in the prices and all the other necessary fields.
2. On the products page, click the three dots on the right-hand side of the product. Click "Duplicate."
3. Inspect the product's variants. For some of the variants, options will be all mixed up and will look incorrect. 

### Expected behavior

I expected options not to be shuffled around.

### Screenshots

1: Creating a product titled "shuffled options."
![57fu1dnPyr](https://user-images.githubusercontent.com/20936991/229187749-4a3d6b3f-0f75-4425-b4a8-ee9d40b123c4.png)

2: Here are the options and variants of said product: it comes in colors of blue and red and sizes of small and large.
![RuYaSCnOXX](https://user-images.githubusercontent.com/20936991/229187839-3505319d-edaf-47b7-b263-27f4f9e2262e.png)

3: Click the "Duplicate" button found here for this product.
![4UK3lWtbI1](https://user-images.githubusercontent.com/20936991/229188180-fc068006-d12b-4912-94fe-a16473027565.png)

4: I duplicated the product. Take a look at the options within the Variants section. "Small" appears under "Color" and "Blue" appears under "Size." That's not how I wrote the first product.
![6qVXNhCq8H](https://user-images.githubusercontent.com/20936991/229188026-e8e8107e-87ac-446e-b140-fd48465d4a66.png)

5: Detailed view of the first variant. Color and Size have been shuffled around.
![JidnDAJL0T](https://user-images.githubusercontent.com/20936991/229188576-b48996ac-f9ff-4572-a429-a020a6668c93.png)

6: Here's the response from the Store API's products list endpoint, GET http://localhost:9000/store/products. I'm looking at the duplicated product's options at products[0].options. Take note of the id for both options. This is what it should be. 
![MC7OvbxqZU](https://user-images.githubusercontent.com/20936991/229190903-d2668897-d79e-4741-9228-6cb64b7f6332.png)

7. Now I'm looking at the options for the duplicated product's first variant at products[0].variants[0].options. There is a mismatch between the id's shown previously and the option_id's shown here. There's something wrong. 
![q8UveRLkge](https://user-images.githubusercontent.com/20936991/229191177-916ce014-acbc-4fdc-b7fa-a1cdf3cbd2c0.png)

### Additional context

This is my first GitHub bug report. Also, Medusa has been really cool so far and a pleasure to work with. I appreciate the work of the Medusa team a lot. Keep it up.

<sub>[CORE-1299](https://linear.app/medusajs/issue/CORE-1299/duplicating-a-product-in-medusa-admin-mixes-up-the-resultant-products)</sub>

**Comment by pratik-codes** [comment]
This looks like an easy fix. @olivermrbl @srindom verifies the issue is relevant. I can work to fix it.

**Comment by olivermrbl** [comment]
Thanks for filing this @raidsrc - we will investigate.

@pratik-codes I am happy to accept a PR for it. What's your suggestion for fixing the issue?

**Comment by pratik-codes** [comment]
@olivermrbl I think there is some mismatch of data sent from the frontend when duplicating or the way the API is written on the backend. If you still want me to proceed I can investigate and get back to you.

**Comment by olivermrbl** [comment]
@adrien2p will you share your findings and add next steps, if any? :)

**Comment by adrien2p** [comment]
@raidsrc you might want to upgrade your medusa version, you are running a very old version of the core. With newer version I can't reproduce your issue anymore

**Comment by raidsrc** [comment]
Ever since updating to Medusa 1.8.0, the issue has vanished. Thanks, everyone.
