### ISSUE TITLE
(v1.8 RC.5): Draft Order Creation with Managing Inventory

### ISSUE THREAD

**Issue by juanzgc** [medusajs/medusa#3681]
### Describe the bug

Discord Thread: https://discord.com/channels/876835651130097704/1092180149186871347/1092180149186871347

Currently, an Admin is unable to Create a Draft Order if they have Stock Location set up with multiple Sales Channels. The reason being is because:
1. Draft Orders always sets the Sales Channel to the `Default Sales Channel` created by Medusa
2. Draft Orders don't allow the Admin to select the Stock Location (`location_id`), when selecting a product variant

Therefore, upon marking the Draft Order as paid. An error is thrown.
```
Can't insert null value in field location_id on insert in table reservation_item
```
### System information

```
  "dependencies": {
    "@medusajs/admin": "1.0.0-rc.5",
    "@medusajs/cache-redis": "1.8.0-rc.2",
    "@medusajs/event-bus-redis": "1.8.0-rc.3",
    "@medusajs/inventory": "1.8.0-rc.3",
    "@medusajs/medusa": "1.8.0-rc.5",
    "@medusajs/stock-location": "1.8.0-rc.2",
    "awilix": "^8.0.0",
    "dotenv": "^12.0.4",
    "express": "^4.17.1",
    "medusa-fulfillment-manual": "^1.1.36",
    "medusa-interfaces": "^1.3.6",
    "medusa-payment-manual": "^1.0.22",
    "pg": "^8.10.0",
    "typeorm": "^0.3.12"
  },
```

#### Step 1: Create a Product Variant with 2 Stock Locations ####
**Important:** ⚠️ Don't use the Default Sales Channel on the Product ⚠️
 
<img width="867" alt="image" src="https://user-images.githubusercontent.com/24414523/229377610-89db1763-f5e9-44e7-80f4-fbbf9c0a3293.png">

<img width="722" alt="image" src="https://user-images.githubusercontent.com/24414523/229377430-0a59e31e-19f9-4660-9636-675e8f3e9868.png">

<img width="1300" alt="image" src="https://user-images.githubusercontent.com/24414523/229377445-b2fdd98a-5f03-477c-bbd7-b38179bce0b7.png">

#### Step 2: Create a Draft Order and Add an existing Product ####

👀 As you can tell, the `0` in the image below most likely represents: 0 Available Stocked Variants.
This is because the Create Draft Order, is using the Default Sales Channel which we don't have setup on the Product (I'm assuming)

<img width="756" alt="image" src="https://user-images.githubusercontent.com/24414523/229377513-0422f971-2e91-4fb5-bbb5-be3d7ab50f53.png">

#### Step 3: Mark Draft Order as Paid ####

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/24414523/229377772-75734f37-81d1-4cfb-b28f-4efc4e0a1eeb.png">

<img width="520" alt="image" src="https://user-images.githubusercontent.com/24414523/229377794-7d495f30-b60f-4b06-a3d8-b14fad526dd4.png">

Raw Draft Order Cart:
```
{
sales_channel_id:"sc_01GX1Q932G5WV11KSSE4GSXFCJ"
}
```

### Expected behavior

The error in this case is that upon selecting a Product for the Draft Order, the Admin is never allowed to select either:
- Sales Channel
- Location

Therefore, upon marking the Draft Order as Paid. A `location_id` is never set, and an error is thrown.

I believe an Admin should be prompted to select a `Sales Channel` and also the `Inventory Location` from which the product should be selected:
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/24414523/229377981-e330d944-553d-4cfe-8f8b-5f4fd196c9c7.png">

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by olivermrbl** [comment]
@juanzgc – can we close this in favor of #3723 ?
