### ISSUE TITLE
(v1.8 RC.5): Product Inventory Count Error

### ISSUE THREAD

**Issue by juanzgc** [medusajs/medusa#3682]
### Describe the bug

The Product Admin UI View shows the incorrect number of available Inventory for a variant that has multiple Sales Channels in a Stock Location.

Currently, a product with a variant:
- Location A: `1 Available Stock` **(1 Sales Channel)**
- Location B: `3 Available Stock` **(2 Sales Channels)**

Displays: `7 in stock for 1 variant(s)`. <- Incorrect
Instead of adding `1 + 3` = 4 Available stock, it seems to be multiplying the stock by the # of sales channels associated.
`1 + 3*2` = 7, which is the incorrect number of available stock.

### System information
```
  "dependencies": {
    "@medusajs/admin": "1.0.0-rc.5",
    "@medusajs/cache-redis": "1.8.0-rc.2",
    "@medusajs/event-bus-redis": "1.8.0-rc.3",
    "@medusajs/inventory": "1.8.0-rc.3",
    "@medusajs/medusa": "1.8.0-rc.5",
    "@medusajs/stock-location": "1.8.0-rc.2",
    "awilix": "^8.0.0",
    "dotenv": "^12.0.4",
    "express": "^4.17.1",
    "medusa-fulfillment-manual": "^1.1.36",
    "medusa-interfaces": "^1.3.6",
    "medusa-payment-manual": "^1.0.22",
    "pg": "^8.10.0",
    "typeorm": "^0.3.12"
  },
```

#### Step 1 ####
Create 2 Stock Locations and 3 Sales Channel (2 User Created, and 1 Default Sales Channel).

<img width="1314" alt="image" src="https://user-images.githubusercontent.com/24414523/229378666-8486c0c5-f844-42fb-83dc-489f6b569fdc.png">

#### Step 2 ####

Create a Product with 3 Sales Channels and Add 2 Locations

<img width="863" alt="image" src="https://user-images.githubusercontent.com/24414523/229378605-d419bed8-5d17-47a7-ae13-df16a964147c.png">

<img width="732" alt="image" src="https://user-images.githubusercontent.com/24414523/229378651-ce706219-7fea-4944-96c7-2ce8223739e6.png">

#### Step 3 ####

View `Products`, and notice the incorrect number of available stock.

<img width="1294" alt="image" src="https://user-images.githubusercontent.com/24414523/229378720-85b5ba81-eafe-4e16-9874-9e8827c7be42.png">

#### Step 4 (Optional) ####

As a test to show that the number is truly incorrect, add a 4th Sales Channel to a Stock Location and see as the number of available stock increases, without you ever actually increasing the stock on the variant.

### Expected behavior

Total available stock should be a sum of the stock from all Locations. It should not multiply this number by the Sales Channel.

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by pKorsholm** [comment]
Hi Juan

Thanks for reporting this! Will get on is asap
