### ISSUE TITLE
Ensure line item bundles are fulfilled from the same provider

### ISSUE THREAD

**Issue by olivermrbl** [medusajs/medusa#37]
We need to add validation (maybe in Cart- or OrderService), that ensures the products in a line item bundle is fulfilled from the same provider. This means, that`lineItem.content[0]...lineItem.content[n-1]` should all belong to the same shipping method / profile. 

Our OrderService currently only support this scenario, hence the need for the validation.

**Comment by srindom** [comment]
This is a restriction on the (not yet started) `medusa-plugin-bundles`.
