### ISSUE TITLE
Taxes of shipping_methods are not added in the shipping_total

### ISSUE THREAD

**Issue by Hemann55** [medusajs/medusa#3708]
I have enabled tax inclusive pricing for a region and am getting the correct pricing in shipping_methods array. But currently, the shipping_total is the sum of all shipping_method's subtotals. This means that the final cart/order total will not include tax for the shipping methods

I think the shipping_total should be sum of all shipping_method's total (not subtotal).

**Comment by attmn** [comment]
I've ran into the same issue with "discount_total". I would assume "gift_card_total" also has this problem. Whatever value you write in the Admin panel has additonal tax percentage added to it when displaying in cart/checkout. 

Eventhough tax is supposed to be included in that value already.
