### ISSUE TITLE
Can't use customer saved payment methods anymore after v1.8.0

### ISSUE THREAD

**Issue by dwene** [medusajs/medusa#3722]
## Bug report

It looks like the new Payment Processor API doesn't allow us to used customer saved payment methods anymore. The `paymentProvider.retrieveSavedMethods` has been removed. Also attempting to update the paymentSession of a cart gives this error.

```
message: 'The payment provider stripe is of type PaymentProcessor. PaymentProcessors cannot update payment session data.'
```

So there is no way for me to update the stripe paymentIntent to used a saved payment method.

### System information

Medusa version (including plugins): 1.8.0
Node.js version: 16
Database: Postgres
Operating system: N/A
Browser (if relevant):

### Expected behavior

I would like to still offer the option to save payment methods to customers so when they login they don't have to input their payment information again.

### Screenshots

Prevents me from allowing the customer to choose their payment method at checkout like seen here:

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/12628251/229926540-13d888fe-0736-41f3-a683-fb0c5a88dad7.png">

**Comment by Gustavodacrvi** [comment]
I'm having the same issue, did you find a solution? I'll try to only use the initializePayment method for now.

**Comment by Toti91** [comment]
[I am having the same issue](https://github.com/medusajs/medusa/issues/4076)

**Comment by Gustavodacrvi** [comment]
I got around this bug by saving the data that I need in the address metadata field:

```
await updateCart({
       billing_address: {
		// address data here...
					
		metadata: {
			...cart.value?.billing_address.metadata,
		       method,
		},
	}
})
```

**Comment by olivermrbl** [comment]
The support for updating sessions was introduced again in #4442
