### ISSUE TITLE
v1.8 Draft Order Bugs / Improvements

### ISSUE THREAD

**Issue by juanzgc** [medusajs/medusa#3723]
### Describe the bug

Below, I've included a list of bugs / optional improvements from the latest `v1.8` release. Thank you to the Core team for all of the hard work on getting this released!

- [ ] Issue 1: Adding a product that is **not** the `Default Sales Channel`, sets the variant price to `0` **(Bug)**
- [ ] Issue 2: Creating a Draft Order, without fulfilling, doesn't set the item as reserved **(Potential Bug / Improvement)**
- [ ] Issue 3: Finding existing customer doesn't default general settings **(Improvement)**
- [ ] Issue 4: Pressing `back` resets form inputs **(Improvement)**
- [ ] Issue 5: Post Draft Order Creation: Requires setting the Inventory Location twice - Allocate Order Items & Create Fulfillment **(Improvement)**

### System information

```
  "dependencies": {
    "@medusajs/admin": "^2.0.0",
    "@medusajs/cache-redis": "^1.8.0",
    "@medusajs/event-bus-redis": "^1.8.0",
    "@medusajs/inventory": "^1.8.0",
    "@medusajs/medusa": "^1.8.0",
    "@medusajs/stock-location": "^1.8.0",
    "medusa-fulfillment-manual": "^1.1.36",
    "medusa-interfaces": "^1.3.6",
    "medusa-payment-manual": "^1.0.22",
    "pg": "^8.10.0",
    "typeorm": "^0.3.12"
  },
```

#### Issue 1: 🐛 Adding a product that is **not** the `Default Sales Channel`, sets the variant price to `0` 🐛 

Leading back to the previous issue https://github.com/medusajs/medusa/issues/3681, since at the point of creating a draft order a Sales Channel isn't selected, an Admin is unable to add Products to a Draft Order if the **product variant** is not under the Default Sales Channel. Important to note, product variant, and not the product itself.

This, leads to the item cost being set to `0`, and ultimately leads to a `null constraint` PG error at the point of creating the Draft Order.

#### Issue 2: Creating a Draft Order, without fulfilling, doesn't set the item as reserved

After creating a draft order and setting the draft order as paid, the item does not become **reserved**. Therefore, potentially allowing for overbooking a product variant. The item only decreases the stock once on the Order, the fulfillment and order item allocation is set. We might want to reserve the item beforehand, and this goes a bit hand-in-hand with the previous issue which recommends that on the Draft Order an Admin should be able to choose a Sales Channel and Location.

#### Issue 3: Finding existing customer doesn't default general settings

Improvement: An admin might expect that during a draft order creation they are able to find an existing customer and populate the general settings such as: `First Name, Last Name, Company (if exists), Phone (if exists)`.

Currently this is not the case. Mind you this is not an issue and only a potential improvement for the Admin use case 😇 

#### Issue 4: Pressing `back` resets form inputs

During a Draft Order creation fill out the customer and shipping details **(Step 4).** Then press the back button on the form to return to **Step 3**. Upon returning to **Step 4**, the customer information and shipping details are no longer saved.

Not an issue, but a potential UX improvement 😇 

#### Issue 5: Post Draft Order Creation: Requires setting the Inventory Location twice - Allocate Order Items & Create Fulfillment

After completing a Draft Order and setting the order as `Paid`, an Admin should complete Allocation of Order Items to a Location and Creating the Fulfillment with the designated Location. In this case it prompts the Admin to select the location **twice**.

A better UX experience might be to set the Location once, which should designate these two fields.

A second improvement, and a potential bug 🐛 -> **Only** display locations associated with the Order's `Sales Channel`. Otherwise, you'd potentially allow for an order to be Associated with Sales Channel A, even though Sales Channel A is not associated with the Location selected. 

### Additional context

Thanks again for all of the hard work and feel free to say no to any of these points listed above. I included them for transparency and once we prioritize them I can definitely create a few PRs to fix them.

**Comment by pKorsholm** [comment]
Hi @juanzgc 

Thanks for checking it out and raising these points 😄 

just to address a couple of them related to inventory management. 

#2 we're currently adding allocation management to the draft order overview, this will allow you to reserve items before the draft order is payed, and the reservations will follow from the draft order to the sales order once it has been payed. It's a bit of manual work still but should allow you to have longer lived draft orders while ensuring not overbooking. (will be in the next release)

#5 With the solution to #2 you won't have to re-allocate line items (though still allocate them on the draft order). Generally we've opted to give maximum control of fulfillments to the user hence we've not limited the options for warehouses, however I think we could definitely automatically select the location of the first allocation when opening the create-fulfillment modal, wdyt about that? 

note: We don't require allocations of inventory before fulfillment if you are pushing through an order quickly you can go straight to fulfillment.

**Comment by raukaute** [comment]
I would like to add that currently it is also not possible to set a custom price for an existing line item. Changing the price in the step where the line item is added works, however to no effect to the final order.

**Comment by andriinuts** [comment]
Is this bug frozen? I think that reducing variants quantity after draft order payment it's critical for a bigger store that has more than one sales channel.

**Comment by pKorsholm** [comment]
Not frozen, we settled for allowing you to manually allocate when you've created the draft order, this will ensure that quantities are initially reserved when still in "draft-order" state, and reservations follows onto each order

**Comment by andriinuts** [comment]
> Not frozen, we settled for allowing you to manually allocate when you've created the draft order, this will ensure that quantities are initially reserved when still in "draft-order" state, and reservations follows onto each order

But then it requires to use new inventory module and it's not possible to use anymore build core variant inventory, right?
