### ISSUE TITLE
[1.8.0] ioredis unable to connect with redis besides localhost

### ISSUE THREAD

**Issue by HuegelMensch** [medusajs/medusa#3733]
## Bug report
ioredis unable to connect with redis besides localhost.
### Describe the bug
ioredis unable to connect with redis besides localhost
### System information

Medusa version (including plugins): 18.0
Node.js version: 16.13.0
Database: Postgres
Operating system: Ubuntu 20.04
Browser (if relevant):

### Steps to reproduce the behavior

1. medusa new my-medusa-store
3. change the .env to use a redis
4. medusa develop

![Unbenannt](https://user-images.githubusercontent.com/19792468/230060397-10d795cf-f02a-4ff0-909e-a6efeedbe9c6.png)

**Comment by HuegelMensch** [comment]
![image](https://user-images.githubusercontent.com/19792468/230065441-c075d7c9-e1cf-4b3e-b412-2fb71ccd4c60.png)
can be closed i guess. but the connection URL on top worked on a previous version of medusa.

**Comment by olivermrbl** [comment]
> but the connection URL on top worked on a previous version of medusa.

Can I get you to elaborate on this? I am not sure I understand.
