### ISSUE TITLE
Bug: "ILIKE" doesn't exist in sqlite

### ISSUE THREAD

**Issue by pKorsholm** [medusajs/medusa#374]
**What?**
- using ILIKE when querying the database causes backend to crash when using SQLite

**Why?**
- SQLite doesn't support 'ILIKE' queries

suggested solution:
    Move query building to the repository and make the repository aware of the underlying database

**Comment by mariusa** [comment]
Or, simply use Postgres in local env too and have the team focus on more valuable issues.

**Comment by olivermrbl** [comment]
Closed #393
