### ISSUE TITLE
[v1.8.0] Error while following the quick start guide using yarn create medusa-app

### ISSUE THREAD

**Issue by vladimirpekez** [medusajs/medusa#3743]
### Describe the bug

⠏ Seeding database phase just hangs up on Mac with Node 16

### System information

Medusa version (including plugins): 1.8.0
Node.js version: 16
Database: N/A
Operating system: Mac OS Ventura
Browser (if relevant):  N/A

### Steps to reproduce the behavior

host@192 Projects % yarn create medusa-app

yarn create v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "create-medusa-app@0.0.10" with binaries:
      - create-medusa-app
✔ Where should your project be installed? · my-medusa-store
✔ Which Medusa starter would you like to install? · medusa-starter-default
✔ Which storefront starter would you like to install? · Next.js Starter
⠏ Creating new project from git: https://github.com/medusajs/medusa-starter-default.git
✔ Created starter directory layout

⠙ Installing packages...
✔ Packages installed
Initialising git in my-medusa-store/backend
Create initial git commit in my-medusa-store/backend
⠹ Seeding database
> medusa-starter-default@0.0.1 seed
> medusa seed -f ./data/seed.json

╔════════════════════════════════════════════════════════════════════════╗
║                                                                        ║
║   Medusa collects anonymous usage analytics                            ║
║   to help improve Medusa for all users.                                ║
║                                                                        ║
║   If you'd like to opt-out, you can use `medusa telemetry --disable`   ║
║                                                                        ║
║                                                                        ║
╚════════════════════════════════════════════════════════════════════════╝
error:   An error occurred while connecting to Redis:
 Error: Connection is closed.
warn:    Local Event Bus installed. This is not recommended for production.
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
warn:    You don't have any notification provider plugins installed. You may want to add one to your project.
warn:    You don't have any taxProviders provider plugins installed. You may want to add one to your project.
warn:    No search engine provider was found: make sure to include a search plugin to enable searching
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
info:    Processing sales_channel.created which has 0 subscribers
info:    Processing user.created which has 0 subscribers
info:    Processing region.created which has 0 subscribers
info:    Processing region.created which has 0 subscribers
info:    Processing product.created which has 0 subscribers
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.
    at Socket.<anonymous> (/Users/user/Projects/my-medusa-store/backend/node_modules/ioredis/built/redis/event_handler.js:182:37)
    at Object.onceWrapper (node:events:628:26)
    at Socket.emit (node:events:513:28)
    at TCP.<anonymous> (node:net:301:12)
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
info:    Processing sales_channel.created which has 0 subscribers
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
⠙ Seeding database
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
⠇ Seeding database

**Comment by vladutstoica** [comment]
Hi there!

As far as I understood from the new 1.8.0 release, the backend expects you to have a working Redis instance before you run the _yarn create medusa-app_, explicitly before you run _medusa seed --seed-file="./data/seed.json"_ or _yarn seed_ from the backend folder. I don't know if it's intended behaviour or not.

> error: An error occurred while connecting to Redis:
Error: Connection is closed.

Quick fix:
- Create a Redis instance (ex. using Docker: `docker run --name redis -p 6379:6379 -d redis`).

After successfully creating the Redis instance, you'll see that it's served on: _localhost:6379_, which is where Medusa expects it to be as stated in _medusa-config.js_: `const REDIS_URL = process.env.REDIS_URL || "redis://localhost:6379";` so you can return to the installation process.

You could also create a Docker container for Postgres as is anyway the recommended way of using the medusaJS core:
```
docker run --name postgres -e POSTGRES_USER=postgres \
  -e POSTGRES_PASSWORD=postgres -e \
  POSTGRES_DB=medusa-docker -p 5432:5432 -d postgres
```

I hope it helps!

**Comment by olivermrbl** [comment]
@vladutstoica Thanks for pitching in. This is correct. You do not have Redis running, which causes your server to hang. You can disable Redis in development by commenting out the `REDIS_URL` in your medusa-config.js. Though, you will need it in a production environment.

**Comment by vladimirpekez** [comment]
@vladutstoica Thanks - I thought so by the messages but the Quick Start guide just doesn't mention that :)

Now it went through.

user@192 Projects % docker ps
CONTAINER ID   IMAGE      COMMAND                  CREATED          STATUS          PORTS                    NAMES
6471cb9fe0f6   postgres   "docker-entrypoint.s…"   6 seconds ago    Up 5 seconds    0.0.0.0:5432->5432/tcp   postgres
026048f4742a   redis      "docker-entrypoint.s…"   36 seconds ago   Up 34 seconds   0.0.0.0:6379->6379/tcp   redis

name@192 Projects % >....                                                                                                                                    
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "create-medusa-app@0.0.10" with binaries:
      - create-medusa-app
✔ Where should your project be installed? · my-medusa-store
✔ Which Medusa starter would you like to install? · medusa-starter-default
✔ Which storefront starter would you like to install? · Next.js Starter
⠋ Creating new project from git: https://github.com/medusajs/medusa-starter-default.git
✔ Created starter directory layout

⠙ Installing packages...
✔ Packages installed
Initialising git in my-medusa-store/backend
Create initial git commit in my-medusa-store/backend
⠙ Seeding database
> medusa-starter-default@0.0.1 seed
> medusa seed -f ./data/seed.json

[medusa-config] ⚠<fe0f> redis_url not found. A fake redis instance will be used.
info:    Using fake Redis
warn:    Local Event Bus installed. This is not recommended for production.
warn:    You don't have any notification provider plugins installed. You may want to add one to your project.
warn:    You don't have any taxProviders provider plugins installed. You may want to add one to your project.
warn:    No search engine provider was found: make sure to include a search plugin to enable searching
⠸ Seeding database
✔ Seed completed
⠦ Creating new project from git: https://github.com/medusajs/nextjs-starter-medusa.git
✔ Created starter directory layout

⠹ Installing packages...
✔ Packages installed
Initialising git in my-medusa-store/storefront
Create initial git commit in my-medusa-store/storefront

  Your project is ready 🚀. The available commands are:
  
    Medusa API
    cd my-medusa-store/backend
    yarn start
  

    Storefront
    cd my-medusa-store/storefront
    yarn dev
    
✨  Done in 122.58s.

**Comment by tiendq** [comment]
@vladimirpekez  I don't know why this issue was closed while the bug is still there without any fix. 

I just followed https://docs.medusajs.com/create-medusa-app with `yarn` option and could not start `yarn start` with backend. Yes, because of this error `Error: connect ECONNREFUSED 127.0.0.1:5432`.

Ok, so I started a Postgres instance and `yarn start` again, and got a new error `Error: Migrations missing. Please run 'medusa migrations run' and try again.`

Ok, just run what it asked for, and so what, one more error `zsh: command not found: medusa`.

Quick start failed miserably and nothing mentioned in the quick start guide neither troubleshooting section.
