### ISSUE TITLE
[v1.8.0] Cannot run Medusa Storefront when Following Quick Start guide

### ISSUE THREAD

**Issue by vladimirpekez** [medusajs/medusa#3746]
### System information

Medusa version (including plugins): 1.8.0.
Node.js version: 16
Database: Postgres
Operating system: Mac OS X Ventura
Browser (if relevant): Chrome latest

### Steps to reproduce the behavior

Follow instructions at https://docs.medusajs.com/create-medusa-app

Backend seems to be started fine, but frontend reports error once localhost port 8000 is loaded in chrome:

Frontend:
host@192 storefront % yarn dev
yarn run v1.22.19
$ next dev -p 8000
ready - started server on 0.0.0.0:8000, url: http://localhost:8000
next.config.js {
  "reactStrictMode": true,
  "images": {
    "domains": [
      "medusa-public-images.s3.eu-west-1.amazonaws.com",
      "localhost"
    ]
  },
  "env": {}
}
info  - Downloading WASM swc package...
info  - Using wasm build of next-swc
warn  - Attempted to load @next/swc-darwin-x64, but it was not installed
event - compiled client and server successfully in 5.3s (337 modules)
wait  - compiling...
event - compiled successfully in 235 ms (296 modules)
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

wait  - compiling / (client and server)...
event - compiled client and server successfully in 3.5s (943 modules)
error - SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
    at async link (internal/modules/esm/module_job.js:42:21) {
  page: '/'
}
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 134 ms (944 modules)
SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
    at async link (internal/modules/esm/module_job.js:42:21) {
  page: '/'
}
wait  - compiling /404 (client and server)...
event - compiled client and server successfully in 399 ms (940 modules)
SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
    at async link (internal/modules/esm/module_job.js:42:21) {
  page: '/'
}

Backend:
host@192 backend % yarn start
yarn run v1.22.19
$ yarn build && medusa start
$ yarn run clean && tsc -p tsconfig.json
$ ./node_modules/.bin/rimraf dist
[medusa-config] ⚠️ redis_url not found. A fake redis instance will be used.
info:    Using fake Redis
✔ Models initialized – 12ms
✔ Plugin models initialized – 2ms
✔ Strategies initialized – 20ms
⠋ Initializing modules
✔ Modules initialized – 4ms
✔ Database initialized – 364ms
✔ Repositories initialized – 23ms
✔ Services initialized – 54ms
✔ Express intialized – 3ms
✔ Plugins intialized – 5ms
✔ Subscribers initialized – 7ms
✔ API initialized – 42ms
⠋ Initializing defaults
info:    Processing sales_channel.created which has 0 subscribers
info:    Processing user.created which has 0 subscribers
info:    Processing region.created which has 0 subscribers
info:    Processing region.created which has 0 subscribers
info:    Processing product.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
warn:    You don't have any notification provider plugins installed. You may want to add one to your project.
✔ Defaults initialized – 33ms
⠋ Initializing search engine indexing
✔ Indexing event emitted – 6ms
✔ Server is ready on port: 9000 – 8ms

**Comment by olivermrbl** [comment]
Please see [this issue](https://github.com/medusajs/medusa/issues/3358#issuecomment-1453225804) to ensure this is not a duplicate.

**Comment by vladimirpekez** [comment]
Hey @olivermrbl, I check the issue and it mentions older android based browsers, a I am on latest chrome and safari on Mac OS X Ventura:

<img width="967" alt="image" src="https://user-images.githubusercontent.com/4521621/230327612-f192f4eb-e156-4621-ad30-bb8d19ffb46b.png">

Chrome Version 111.0.5563.146 (Official Build) (arm64)

**Comment by vladimirpekez** [comment]
@olivermrbl I just deleted node_modules and tried npm package manager instead of yarn, but same result:

user@192 storefront % npm run dev

> medusa-next@1.0.3 dev /Users/user/Projects/my-medusa-store/storefront
> next dev -p 8000

ready - started server on 0.0.0.0:8000, url: http://localhost:8000
info  - Loaded env from /Users/user/Projects/my-medusa-store/storefront/.env
next.config.js {
  "reactStrictMode": true,
  "images": {
    "domains": [
      "medusa-public-images.s3.eu-west-1.amazonaws.com",
      "localhost"
    ]
  },
  "env": {}
}
event - compiled client and server successfully in 1634 ms (337 modules)
wait  - compiling...
event - compiled successfully in 240 ms (296 modules)
wait  - compiling / (client and server)...
wait  - compiling /404 (client and server)...
event - compiled client and server successfully in 867 ms (946 modules)
SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
    at async link (internal/modules/esm/module_job.js:42:21)
error - SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
    at async link (internal/modules/esm/module_job.js:42:21) {
  page: '/'
}
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 261 ms (947 modules)
SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
    at async link (internal/modules/esm/module_job.js:42:21) {
  page: '/'
}
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
Error: Failed to fetch update manifest Internal Server Error
    at http://localhost:8000/_next/static/chunks/fallback/webpack.js?ts=1680786932326:1164:37
error - SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
    at async link (internal/modules/esm/module_job.js:42:21) {
  page: '/'
}
SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
    at async link (internal/modules/esm/module_job.js:42:21) {
  page: '/'
}

**Comment by vladimirpekez** [comment]
@olivermrbl Ok, got it node 12 was the culprit, somehow this project was using node 12, on node 16 there's no problems:

user@192 storefront % node -v
v12.22.0
**user@192 storefront % nvm use 16**
