### ISSUE TITLE
Categories can not be added because `parent_category_id` cannot be NULL

### ISSUE THREAD

**Issue by janmei** [medusajs/medusa#3762]
### Describe the bug

After a fresh install of Medusa and activating the Category Feature no Categories can be added, with the error in the console saying that `parent_product_category` cannot be NULL. Which makes sense because there are no categories in the Database. 

### System information

Medusa version (including plugins):
```
    "@babel/preset-typescript": "^7.21.4",
    "@medusajs/admin": "^2.0.0",
    "@medusajs/cache-inmemory": "^1.8.0",
    "@medusajs/cache-redis": "^1.8.0",
    "@medusajs/event-bus-local": "^1.8.0",
    "@medusajs/event-bus-redis": "^1.8.0",
    "@medusajs/medusa": "^1.8.0",
    "@medusajs/medusa-cli": "^1.3.9",
    "babel-preset-medusa-package": "^1.1.13",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "express": "^4.17.2",
    "medusa-fulfillment-manual": "^1.1.37",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.23",
    "medusa-payment-stripe": "^2.0.0",
    "typeorm": "^0.3.11"
```
Node.js version: 18.14. 
Database: SQLite
Operating system: Mac
Browser (if relevant):

### Steps to reproduce the behavior

1. Install Medusa with the Demo Seed
2. Activate the Categories Module 
3. Try adding a new Category
4. Error should pop up.

### Expected behavior

Have the option to create a parent category

**Comment by olivermrbl** [comment]
This is a known issue with SQLite. Enabling Postgres should resolve this issue.

**Comment by olivermrbl** [comment]
Closing this issue for now. Let me know if changing to Postgres does not solve the issue.
