### ISSUE TITLE
[v1.8.0] Demo storefront returning 401 Unauthorised on GET http://localhost:9000/store/customers/me

### ISSUE THREAD

**Issue by vladimirpekez** [medusajs/medusa#3764]
### Describe the bug

I have followed the quick start guide to setup the default backend and frontend Medusa storefront but when I try to add to cart any item I get:

Request URL: http://localhost:9000/store/customers/me
Response: 401 Unauthorized

### System information

Medusa version (including plugins): 1.8.0. default "demo" setup
Node.js version: 16
Database: Postgres
Operating system: Mac OS X Ventura
Browser (if relevant): Chrome latest

### Steps to reproduce the behavior

1. Pick any item 
2. Click add to cart

### Screenshots

<img width="1705" alt="image" src="https://user-images.githubusercontent.com/4521621/230556434-48e47152-305c-4954-9d8c-208e869375e6.png">

**Comment by olivermrbl** [comment]
@vladimirpekez I am quite sure that the 401 is unrelated to add to cart. We are trying to authenticate you, such that if you had special product prices defined, those would be shown instead of the standard prices. 

Are you unable to add to cart? If so, can you share the network request, that fails?

**Comment by ggofron** [comment]
I have similar issue on default storefront, when I go to cart I see 2 GET requests to http://localhost:9000/store/customers/me
Is it needed? When I'm not logged in I just see 2 401's

**Comment by vladimirpekez** [comment]
@olivermrbl I managed to add a product to the cart despite these auth errors. So it seems this is expected behavior?

**Comment by olivermrbl** [comment]
Yes, it is expected behaviour.
