### ISSUE TITLE
[medusa-file-s3] Images not deleted on remove from product

### ISSUE THREAD

**Issue by eliottha** [medusajs/medusa#3774]
### Describe the bug

The product images nor thumbnail do not seem to be deleted after removing them in the admin. Is it possible this feature is not yet implemented?

Thank you,
Eliott

**Comment by olivermrbl** [comment]
Yes, deleting the product in Medusa will not trigger a delete in S3. Can you please submit this feature request to our GitHub Discussions 🙏 

In the meantime, I imagine a simple subscriber to event `"product.updated"` could do the job for you.

**Comment by eliottha** [comment]
Dear Oliver,

Thank you for your reply.
If it's okay with you, I'd look into this myself and eventually create a PR once implemented?

Have a great day,
Eliott

**Comment by olivermrbl** [comment]
@eliottha That would be great - let me know if I can assist.

**Comment by eliottha** [comment]
@olivermrbl 

To my first investigation, it looks like updating the images calls the [`upsertImages`](https://github.com/medusajs/medusa/blob/develop/packages/medusa/src/repositories/image.ts#L23) function.

So right now the images are not deleted from the database (image table either), upon trying out locally this seems to be correct. However I don't think this is the place to delete the images from the database, what would be the right approach? Add another function to clean up unused images linked to a product?

Eliott

**Comment by kimhwanhoon** [comment]
Has it been solved?
