### ISSUE TITLE
S3 plugin error: [CredentialsError]: Missing credentials in config

### ISSUE THREAD

**Issue by kracas** [medusajs/medusa#3775]
### Describe the bug

S3 plugin throws this error when trying to upload a product image:

```
Error [CredentialsError]: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
    at IncomingMessage.<anonymous> (/project/node_modules/aws-sdk/lib/util.js:912:34)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  statusCode: 404,
  retryable: false,
  time: 2023-04-09T04:57:01.526Z,
  code: 'CredentialsError',
  originalError: {
    message: 'Could not load credentials from any providers',
    statusCode: 404,
    retryable: false,
    time: 2023-04-09T04:57:01.526Z,
    code: 'CredentialsError',
    originalError: {
      message: 'EC2 Metadata roleName request returned error',
      statusCode: 404,
      retryable: false,
      time: 2023-04-09T04:57:01.526Z
    }
  }
}
```

According to [AWS documentation](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/global-config-object.html), updates you make to the global AWS.config object don't apply to previously created service objects. However, in s3.js of the plugin, the AWS.config is updated after the S3 service object is created, therefore the config data is not passed to S3 and the error appears.

### System information

Medusa version (including plugins):
"medusa-file-s3": "^1.1.12"
"@medusajs/medusa": "^1.8.0"
"@medusajs/admin": "^2.0.0"
Node.js version: 18.15.0
Database: postgres
Operating system: ubuntu 22.04

### Steps to reproduce the behavior

1. yarn add medusa-file-s3
2. Add to medusa-config:
 {
    resolve: `medusa-file-s3`,
    options: {
      endpoint: process.env.S3_URL,
      bucket: process.env.S3_BUCKET,
      region: process.env.S3_REGION,
      access_key_id: process.env.S3_ACCESS_KEY_ID,
      secret_access_key: process.env.S3_SECRET_ACCESS_KEY,
    },
  },
3. Upload a product image

**Comment by eliottha** [comment]
Works fine for me using:
```
  {
    resolve: `medusa-file-s3`,
    options: {
      s3_url: process.env.S3_URL,
      bucket: process.env.S3_BUCKET,
      region: process.env.S3_REGION,
      access_key_id: process.env.S3_ACCESS_KEY_ID,
      secret_access_key: process.env.S3_SECRET_ACCESS_KEY,
      aws_config_option: {},
    },
  },
```

**Comment by olivermrbl** [comment]
No errors here either using:
```
{
    resolve: "medusa-file-s3",
    options: {
      bucket: S3_BUCKET,
      s3_url: S3_URL,
      access_key_id: S3_ACCESS_KEY_ID,
      secret_access_key: S3_SECRET_ACCESS_KEY,
      region: S3_REGION,
    },
  },
```
Please ensure that you've configured your plugin correctly with the right permissions.

**Comment by kracas** [comment]
I'm using Oracle object storage (which has S3 compatibility api) and it's working with #3776 changes. Which S3 plugin version are you using? #3260 broke it for me.

**Comment by olivermrbl** [comment]
I use the latest version.

**Comment by olivermrbl** [comment]
@dwene opened a PR last week to migrate the S3 plugin to TypeScript. I will give that PR higher priority, so it might be worth trying it out to see if it solves your issue. And if not, request changes that will.

**Comment by eliottha** [comment]
> I'm using Oracle object storage (which has S3 compatibility api) and it's working with #3776 changes. Which S3 plugin version are you using? #3260 broke it for me.

Latest version as well.
I'll try with Oracle Object storage and see if I get the same problem.

**Comment by kracas** [comment]
> @dwene opened a PR last week to migrate the S3 plugin to TypeScript. I will give that PR higher priority, so it might be worth trying it out to see if it solves your issue. And if not, request changes that will.

Yes, #3740 fixes this issue problem. I'll close #3776.

**Comment by olivermrbl** [comment]
@kracas Great. I will attend to a review later today or tomorrow 👍
