### ISSUE TITLE
Bug: Uncaught SyntaxError: The requested module '/@fs/Users/mitchellewulonu/demo-medusa-admin/node_modules/react-dom/index.js?v=b90c7b1b' does not provide an export named 'flushSync' (at index.module.js?v=b90c7b1b:3:9)

### ISSUE THREAD

**Issue by mitchellewulonu** [medusajs/medusa#3783]
### Describe the bug
Hello,

I'm following Option 2: Install and Serve Admin Separately at https://docs.medusajs.com/admin/quickstart locally on my mac mini but im getting the following error and admin site doesn't load

Error
Uncaught SyntaxError: The requested module '/@fs/Users/mitchellewulonu/demo-medusa-admin/node_modules/react-dom/index.js?v=b90c7b1b' does not provide an export named 'flushSync' (at index.module.js?v=b90c7b1b:3:9)

### System information

Medusa version (including plugins): Medusajs(1.8.0) & @Medusa/admin(2.0.0)
Node.js version: 18.11.0
Database: Postgres
Operating system: macOS Monterey
Browser (if relevant): 

### Steps to reproduce the behaviour

Option 2: Install and Serve Admin Separately at https://docs.medusajs.com/admin/quickstart 

step 3 npm run dev:admin

### Expected behaviour

Admin Panel site should render on local machine

### Screenshots

![Screenshot 2023-04-10 at 00 10 40](https://user-images.githubusercontent.com/33165742/230865139-6fd7ad93-e55b-4c70-9cb7-a9962794c037.png)

### Code snippets

    "dev:admin": "medusa-admin dev",

I think there is a bug. Could you please advise on this and also how to deploy to Vercel with option 2

Thank you for your attention to this issue.

**Comment by mitchellewulonu** [comment]
I finally figured out how to deploy admin to Vercel using option 2. 

Make sure your package.json build and start commands are like the below:

   "build": "medusa-admin build --deployment",
    "start": "npm run dev:admin", 

Override vercel Output directory to 'build' (default location by 'medusa-admin build' as outlined in medusajs admin docs ) 

set framework to vite

**Comment by mitchellewulonu** [comment]
this bug only happens when I want to run admin locally using medusa-admin dev

**Comment by olivermrbl** [comment]
@mitchellewulonu – we've identified the culprit and are working on a fix to publish asap :)

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
