### ISSUE TITLE
bug(add products): Adding products with many variants makes node go OOM

### ISSUE THREAD

**Issue by flashjames** [medusajs/medusa#3787]
### Describe the bug

Adding many products after each other to endpoint POST /admin/products, with many product variants makes node/medusa process go OOM.

Happens when many product variants or possibly many images, but it seems like the former.

### System information

Medusa version (including plugins): 1.8.0
Node.js version: 18.12.1
Database: postgres
Operating system: ubunu 22.04 lts

### Steps to reproduce the behavior

Add products with many variants, POST /admin/products. 3 products with around 30 variants added after each other seems to trigger it every time. For every product added with many variants, medusa stops responding for requests for a while.

Possibly need to add a few 100 products..

This bug didn't happen before I upgraded to 1.8.0.

### Workaround
When a product being added has many variants, make script adding products sleep for await sleep(r.variants.length*3). Then medusa seems to recover.

### Additional context

I have feature flag for categories enabled.

medusa dev
```
::ffff:127.0.0.1 - - [10/Apr/2023:13:21:46 +0000] "POST /admin/products HTTP/1.1" 200 54811 "-" "axios/1.1.3"
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers
info:    Processing product-variant.created which has 0 subscribers

<--- Last few GCs --->

[2679853:0x52f3200]  1736145 ms: Scavenge 4050.4 (4130.7) -> 4046.6 (4131.7) MB, 8.3 / 0.0 ms  (average mu = 0.546, current mu = 0.371) allocation failure; 
[2679853:0x52f3200]  1736168 ms: Scavenge 4051.2 (4131.7) -> 4048.2 (4134.4) MB, 10.6 / 0.0 ms  (average mu = 0.546, current mu = 0.371) task; 
[2679853:0x52f3200]  1737785 ms: Scavenge 4054.1 (4134.4) -> 4050.6 (4151.7) MB, 1593.0 / 0.0 ms  (average mu = 0.546, current mu = 0.371) allocation failure; 


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb6e500 node::Abort() [/home/prox/.nvm/versions/node/v18.12.1/bin/node]
 2: 0xa7e632  [/home/prox/.nvm/versions/node/v18.12.1/bin/node]
 3: 0xd47f20 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/prox/.nvm/versions/node/v18.12.1/bin/node]
 4: 0xd482c7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/prox/.nvm/versions/node/v18.12.1/bin/node]
 5: 0xf25685  [/home/prox/.nvm/versions/node/v18.12.1/bin/node]
 6: 0xf37b6d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/prox/.nvm/versions/node/v18.12.1/bin/node]
 7: 0xf1226e v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/prox/.nvm/versions/node/v18.12.1/bin/node]
 8: 0xf13637 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/prox/.nvm/versions/node/v18.12.1/bin/node]
 9: 0xef3b80 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/home/prox/.nvm/versions/node/v18.12.1/bin/node]
10: 0xeeb5f4 v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawWithImmortalMap(int, v8::internal::AllocationType, v8::internal::Map, v8::internal::AllocationAlignment) [/home/prox/.nvm/versions/node/v18.12.1/bin/node]
11: 0xeed988 v8::internal::FactoryBase<v8::internal::Factory>::NewRawTwoByteString(int, v8::internal::AllocationType) [/home/prox/.nvm/versions/node/v18.12.1/bin/node]
12: 0xef6e3c v8::internal::Factory::NewStringFromUtf8(v8::base::Vector<char const> const&, v8::internal::AllocationType) [/home/prox/.nvm/versions/node/v18.12.1/bin/node]
13: 0xd56fd3 v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::NewStringType, int) [/home/prox/.nvm/versions/node/v18.12.1/bin/node]
14: 0xc54b31  [/home/prox/.nvm/versions/node/v18.12.1/bin/node]
15: 0xb443b6  [/home/prox/.nvm/versions/node/v18.12.1/bin/node]
16: 0x166f26f  [/home/prox/.nvm/versions/node/v18.12.1/bin/node]
```

htop output:
![image](https://user-images.githubusercontent.com/359702/230906350-d03f857a-8784-4055-963c-e84ce93d2032.png)

**Comment by fsyntax** [comment]
Same issue happening to me, after hitting a product route with 40+ variants on the Admin.

```
<--- Last few GCs --->

[7732:000002BE1C50D6E0]    67284 ms: Mark-sweep 4044.5 (4135.9) -> 4034.4 (4139.4) MB, 521.2 / 0.0 ms  (average mu = 0.504, current mu = 0.039) allocation failure; scavenge might not succeed
[7732:000002BE1C50D6E0]    68342 ms: Mark-sweep 4050.3 (4139.7) -> 4040.1 (4145.4) MB, 1036.0 / 0.0 ms  (average mu = 0.243, current mu = 0.020) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF6072E9E7F node_api_throw_syntax_error+175967
 2: 00007FF607270C06 SSL_get_quiet_shutdown+65750
 3: 00007FF607271FC2 SSL_get_quiet_shutdown+70802
 4: 00007FF607D0A214 v8::Isolate::ReportExternalAllocationLimitReached+116
 5: 00007FF607CF5572 v8::Isolate::Exit+674
 6: 00007FF607B773CC v8::internal::EmbedderStackStateScope::ExplicitScopeForTesting+124
 7: 00007FF607B745EB v8::internal::Heap::CollectGarbage+3963
 8: 00007FF607B8A823 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath+2099
 9: 00007FF607B8B0CD v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath+93
10: 00007FF607B93D50 v8::internal::Factory::AllocateRawWithAllocationSite+784
11: 00007FF607B9BC86 v8::internal::Factory::NewJSArrayWithUnverifiedElements+182
12: 00007FF607B9B31C v8::internal::Factory::NewJSArray+188
13: 00007FF607A9BEAC v8::base::TimeDelta::operator!=+19548
14: 00007FF607A9FEFF v8::base::TimeDelta::operator!=+36015
15: 00007FF607A9EF4A v8::base::TimeDelta::operator!=+31994
16: 00007FF607C9E604 v8::internal::Builtins::code+98836
17: 00007FF607C9E780 v8::internal::Builtins::code+99216
18: 00007FF607DA79B1 v8::internal::SetupIsolateDelegate::SetupHeap+558449
19: 00007FF5A7C3A70E
```

Occuring on a local environment.
Node: `v18.13.0`
Medusa: `1.8.0`
Medusa Admin Plugin: `2.0.0`

**Comment by olivermrbl** [comment]
Thanks for filing this. We will attend to this asap. 

What modules do you have enabled?

**Comment by flashjames** [comment]
> Thanks for filing this. We will attend to this asap.
> 
> What modules do you have enabled?


```
plugins: [
    `medusa-fulfillment-manual`,
    `medusa-payment-manual`,
    "medusa-product-translation",
    "medusa-payment-stripe
    ],

    featureFlags: {
    product_categories: true,
  },
    modules: {
    eventBus: {
      resolve: "@medusajs/event-bus-redis",
      options: {
        redisUrl: REDIS_URL
      }
    },
    cacheService: {
      resolve: "@medusajs/cache-redis",
      options: {
        redisUrl: REDIS_URL
      }
    }
  },


```

**Comment by adrien2p** [comment]
I ve done a test on my side
- node 18
- medusa 1.8
- event bus redis 1.8
- cache redis 1.8
- 4 instances using pm2 to simulate your different instances
So far, I've been able to create 15 products consecutively including 50 variants and each variant with a price included in the prices, here is my memory.

<img width="2607" alt="Screenshot 2023-04-11 at 11 34 27" src="https://user-images.githubusercontent.com/25098370/231119891-1b6db1cb-6d44-4a4b-8ea4-1a5d94d6ff20.png">

I am unable to reproduce at the moment

**Comment by adrien2p** [comment]
Would you be able to provide us with a reproducible repository that includes your lock file as well as a script that create the product and produce that behaviour and that we can run on our side to test?

**Comment by flashjames** [comment]
Yes, but can we talk on discord - maybe we can come up with something faster to test this.
I wrote a message to you, my nick on discord is same as here "theflashjames"
@adrien2p

**Comment by flashjames** [comment]
So adrien2p helped me figure out the error. And it was a bad practice on my end that caused it.

Basically I added too much metadata on the product object, which probably caused some library in the stack go nuts causing node/medusa process to go oom.

Full discussion here: https://discord.com/channels/876835651130097704/1096330485241761835

@fsyntax Did you solve the problem yourself? If not, try removing metadata from the data you're passing the endpoint.

**Comment by flashjames** [comment]
@adrien2p I thought a bit more about the problems I had, and that possibly other people setting up their store on medusa might have with the same problem and ways to mitigate this.

## Context
The reason I ran into the problem with OOM when adding products. was that medusa started to hang in production on railway when I upgraded to medusa 1.8.0. Without any logs about that the process hanged, it just stopped serving requests and I couldnt find anything in the logs or any weird cpu/ram usage.

Since I'm not live yet I figured, let's reset database and start from scratch and that's when I ran into this problem that medusa went OOM when adding products.
Now it's apparent the reason medusa stopped serving requests in production (seemingly randomly) was because of the big metadata object I had added to products.

## Why did I add that much metadata to products object
I figured, I might need some data later, why not add all data I get from supplier (bigbuy) on metadata field, it's just regular json.
You told me it's a bad practice and it's clear it is, but I didn't now this since it was the first time a worked with a database json field.

## Is it possible other people might run into this problem later?
I think there might be many people starting developing their store with medusa in the future, that have the same thought process as me "let's just put all product feed data as a field on metadata, there's some data I might need later" and that don't know this is a bad practice. I would call myself an average programmer even though I've programmed for 15 years, if I can do this error I reckon lots of people might have the same thought process as me, especially programmers that have no experience of the json field and that's bad practice to puch much data on it.

The problem is, it's really hard to debug this error and know what's causing it especially if at some point POST /admin/products handles big metadata objects well, but then it causes medusa to hang randomly when serving does products.

## Suggestion on how to avoid this, or at least give debug info that can point the developer in the right direction. With varying degrees of investment of time
- Simplest: Give console.log output on GET /store/products and POST /admin/products when adding/retrieving big metadata objects over a certain size
- Solve the root cause and add tests for metadata - which I reckon is not worth the investment of time.

And again, thank you @adrien2p for helping me figure this out.
