### ISSUE TITLE
Multi-tenant support

### ISSUE THREAD

**Issue by mariusa** [medusajs/medusa#383]
Hi,

Quoting ngellner on HN:
> On Multi-tenant functionality: This feature will come soon; we will launch a concept called "Stores" in the near future to enable you to control multiple shops/branches from one place

You probably refer to one company having multiple shops.

To clarify, Multi-tenant is like Shopify: completely different companies which sign up, each company with their own (single or multiple) stores.
This are hosted in the same database by design, not with hacks like having a separate schema for each company.

Multi-tenant support would be the differentiator between Medusa and most other open source commerce solutions (including Vendure), which don't offer it.

**Comment by cyraid** [comment]
Was this completed though? Where is the multi-tenant support?

**Comment by coopbri** [comment]
Following up with @cyraid's comment, I believe this should be reopened unless I'm missing something?

**Comment by SalahAdDin** [comment]
Why is this closed @srindom ?

**Comment by oliverstreissi** [comment]
Just in case you are still looking for a solution, [vendure](https://vendure.io/) has multi-tenant support out of the box.

**Comment by SalahAdDin** [comment]
> Just in case you are still looking for a solution, [vendure](https://vendure.io/) has multi-tenant support out of the box.

yeah, but we want this feature on Medusa.

**Comment by kuyazee** [comment]
up

**Comment by kazGuido** [comment]
would this fit the definition of a marketplace which is cited in the recipes ? anyway, just here to express my support for the idea

**Comment by SalahAdDin** [comment]
> would this fit the definition of a marketplace which is cited in the recipes ? anyway, just here to express my support for the idea

which one?

**Comment by kazGuido** [comment]
https://docs.medusajs.com/recipes/marketplace this one

**Comment by mist998** [comment]
Check out store module and multi-tenant support, but seemingly these stores are still parked under same company (or don't have company concept).
[https://docs.medusajs.com/v2/resources/commerce-modules/store](https://docs.medusajs.com/v2/resources/commerce-modules/store) this

**Comment by SalahAdDin** [comment]
> Check out store module and multi-tenant support, but seemingly these stores are still parked under same company (or don't have company concept). https://docs.medusajs.com/v2/resources/commerce-modules/store this

what do you mean parked under same company?

**Comment by zohairhadi** [comment]
Why is this closed? No comments from the maintainers?

**Comment by coopbri** [comment]
> Why is this closed? No comments from the maintainers?

Yeah I would just recommend switching to https://vendure.io/ or similar -- toxic FOSS behavior. If you know others aside from Vendure @zohairhadi I am all ears!

**Comment by zohairhadi** [comment]
> > Why is this closed? No comments from the maintainers?
> 
> Yeah I would just recommend switching to https://vendure.io/ or similar -- toxic FOSS behavior. If you know others aside from Vendure @zohairhadi I am all ears!

@coopbri this is the closest thing to a multi tenant feature which i could find in medusa, could try looking into this https://www.reddit.com/r/webdev/comments/157ga9z/comment/jtau439/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

Aside from this, wooCommerce it is 💀 (forced to regress)

**Comment by coopbri** [comment]
x

> > > Why is this closed? No comments from the maintainers?
> > 
> > 
> > Yeah I would just recommend switching to [vendure.io](https://vendure.io/) or similar -- toxic FOSS behavior. If you know others aside from Vendure @zohairhadi I am all ears!
> 
> @coopbri this is the closest thing to a multi tenant feature which i could find in medusa, could try looking into this [reddit.com/r/webdev/comments/157ga9z/comment/jtau439?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button](https://www.reddit.com/r/webdev/comments/157ga9z/comment/jtau439/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)
> 
> Aside from this, wooCommerce it is 💀

Thanks for sharing! I'll check this out! Oh man, I thought we were done with WooCommerce :joy:

**Comment by nileshtrivedi** [comment]
Hello everyone,

I'm new to Medusa and medusa-extender. Would love to know what the current state of multi-tenancy support in Medusa is. 

Is the official [Marketplace Recipe](https://docs.medusajs.com/resources/recipes/marketplace) as capable as full multi-tenancy? If not, what compromises are involved? For eg: can each store be assigned a separate domain name? Would every store have a separate instance of the admin dashboard too?

**Comment by nileshtrivedi** [comment]
I noticed this in the marketplace recipe:

> Only super admins can access the Medusa Admin, not vendor admins. So, if you need a dashboard specific to each vendor admin, you will need to build a custom dashboard with the necessary features.

This basically means that the given recipe is not actually complete even as a marketplace, let alone a multi-tenant ecommerce product (i.e. Shopify equivalent).

I also came across [Mercur](https://www.mercurjs.com/) ([github](https://github.com/mercurjs/mercur)) which is an open-source marketplace built on top of Medusa. But that too does not provide true multi-tenancy. For eg, [vendors cannot use custom domains](https://github.com/mercurjs/mercur/issues/389).

**Comment by SalahAdDin** [comment]
> I noticed this in the marketplace recipe:
> 
> > Only super admins can access the Medusa Admin, not vendor admins. So, if you need a dashboard specific to each vendor admin, you will need to build a custom dashboard with the necessary features.
> 
> This basically means that the given recipe is not actually complete even as a marketplace, let alone a multi-tenant ecommerce product (i.e. Shopify equivalent).
> 
> I also came across [Mercur](https://www.mercurjs.com/) ([github](https://github.com/mercurjs/mercur)) which is an open-source marketplace built on top of Medusa. But that too does not provide true multi-tenancy. For eg, [vendors cannot use custom domains](https://github.com/mercurjs/mercur/issues/389).

it is suppose to be a multitenance, and also, there is other recipe for it.

What about  Vendor e-commerce? I don't remember its name now.

**Comment by nileshtrivedi** [comment]
@SalahAdDin It's Vendure.io. They have [this guide for multi-vendor marketplaces](https://docs.vendure.io/guides/how-to/multi-vendor-marketplaces/), but it seems the same also works for true multi-tenancy (i.e. completely separate shops). They achieve this via the idea of [sales channels](https://docs.vendure.io/guides/core-concepts/channels/).

[Medusa does have Sales Channels](https://docs.medusajs.com/resources/commerce-modules/sales-channel), but it is not clear if all entities are channel-aware. Without that, it cannot be used to implement multi-tenancy.

**Comment by SalahAdDin** [comment]
> [@SalahAdDin](https://github.com/SalahAdDin) It's Vendure.io. They have [this guide for multi-vendor marketplaces](https://docs.vendure.io/guides/how-to/multi-vendor-marketplaces/), but it seems the same also works for true multi-tenancy (i.e. completely separate shops). They achieve this via the idea of [sales channels](https://docs.vendure.io/guides/core-concepts/channels/).
> 
> [Medusa does have Sales Channels](https://docs.medusajs.com/resources/commerce-modules/sales-channel), but it is not clear if all entities are channel-aware. Without that, it cannot be used to implement multi-tenancy.

Let's ask about it in Medusa team.

**Comment by tom-aniol** [comment]
Coming back to your initial question @mariusa: We ([Rigby)](https://rigbyjs.com/) have had many conversations about multi-tenancy and multi-store setups in Medusa and decided to do a deep dive as eBook: [Multi-Tenant Architecture in Medusa](https://www.rigbyjs.com/resources/multi-tenant-architecture), covering the different technical approaches and trade-offs.

You can also read a summary on the official Medusa blog: [Building a multi-tenant commerce platform with Medusa](https://medusajs.com/blog/multi-tenant-rigby/), written by our CTO.

Regarding the multi-vendor marketplace model (thanks @nileshtrivedi for the mention), we created [Mercur](https://mercurjs.com/) to cover these requirements, which can be integrated with multi-tenancy as well. We've also [compared it with other marketplace platforms on the market](https://www.rigbyjs.com/resources/top-multi-vendor-marketplace-platforms) to show the architectural differences.

Hope it helps in your projects!

**Comment by SalahAdDin** [comment]
> Coming back to your initial question [@mariusa](https://github.com/mariusa): We ([Rigby)](https://rigbyjs.com/) have had many conversations about multi-tenancy and multi-store setups in Medusa and decided to do a deep dive as eBook: [Multi-Tenant Architecture in Medusa](https://www.rigbyjs.com/resources/multi-tenant-architecture), covering the different technical approaches and trade-offs.
> 
> You can also read a summary on the official Medusa blog: [Building a multi-tenant commerce platform with Medusa](https://medusajs.com/blog/multi-tenant-rigby/), written by our CTO.
> 
> Regarding the multi-vendor marketplace model (thanks [@nileshtrivedi](https://github.com/nileshtrivedi) for the mention), we created [Mercur](https://mercurjs.com/) to cover these requirements, which can be integrated with multi-tenancy as well. We've also [compared it with other marketplace platforms on the market](https://www.rigbyjs.com/resources/top-multi-vendor-marketplace-platforms) to show the architectural differences.
> 
> Hope it helps in your projects!

Looks nice!
