### ISSUE TITLE
Use HTTPS on medusa backend/Mixed Content issues.

### ISSUE THREAD

**Issue by stackpanda** [medusajs/medusa#3844]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Currently I am running my medusa store backend on a Ubuntu 20.04 server box on my local network with a forwarded 9000 port for the medusa backend but I host my storefront on netlify to make sure my server is safe, secure, and seperate from any issues. The only issues are that I cannot use the ip address for my server for the storefront because the medusa backend doesn't serve on https, but today I switched to the Next.js storefront and now none of my product images will load because the storefront is trying to reach my backend's ip address. I have to use the [Tunnel Mole Software](url) to tunnel my server through a https address. Is there any way that I can make the medusa backend serve on https with my ip address? Thanks

### How can this issue be resolved?

1. FIgure out how to serve my medusa backend on https
2. Or Make my medusa backend use the tunnel url

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by SGFGOV** [comment]
The simplest way would be to terminate https on your load balancer

**Comment by stackpanda** [comment]
Kinda slow here, I have no idea what that means or how to do that.

**Comment by umairraza96** [comment]
You can also create a subdomain and attach it to your server and enable https on that.
You can also look into services like [TunnelMole](https://tunnelmole.com/)

**Comment by pevey** [comment]
For any deployed node app (including the medusa backend), I think it is considered best practice to use some sort of reverse proxy if you need the public to access it via the web.

I am most familiar with nginx.  Here are the basic docs for it.
https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/

Here's a guide I found by Googling.  I haven't actually read through the guide to see if it's good, but it might be helpful.
https://betterstack.com/community/guides/scaling-nodejs/nodejs-reverse-proxy-nginx/

I think this issue should be closed and perhaps moved to discussions.

**Comment by stackpanda** [comment]
I was using a reverse proxy, but now I am switching to using my port forward because I now have my public ip address linked to a domain and I will setup cloudflare later down the road. The issue is that I cannot get my backend server to use HTTPS. When I try to access the server with https://mydomain.com it says invaild response.

**Comment by pevey** [comment]
This is why you should use a proxy.  You cannot (well, you can, but you SHOULD not) just forward any nodejs app, including medusa, directly to the web.

Since you mentioned Cloudflare, I would suggest you look into using a cloudflared tunnel to your medusa server and then expose it at your custom domain.   These tunnels are just a particular type of reverse proxy.  That way, cloudflare will access your http server on port 9000, and cloudflare will take care of making sure all access on the web is https only.

**Comment by stackpanda** [comment]
I am going to use a proper reverse proxy (I was using a node tunneling service). I host my Next.js storefront on netlify and when I was using a tunneling service, no images were loading and I wasn't able to login to my account on the storefront and when I was looking at the developer console I noticed that the storefront was trying to fetch the images using my server's public ip address. I am confused why this is happening and I have been bouncing from method to method for exposing my server and fixing this issue. I don't know why this is happening and I cannpt figure out how to get the Medusa server to use the one tunneled address.

**Comment by stackpanda** [comment]
I realize what the issue is. I host the images on a local database, therefore it tries to fetch from that database that hasn't been exposed. Still doesn't explain why I cannot add anything to cart or login.

**Comment by stackpanda** [comment]
I have fixed everything. Thank you to everyone who replied in the thread you guys helped alot.

**Comment by piereligio** [comment]
> I have fixed everything. Thank you to everyone who replied in the thread you guys helped alot.

How did you solve? Did you end up using a reverse proxy or not? Did you have to expose your images database too?
