### ISSUE TITLE
In admin panel "invite you team" option doesn't work

### ISSUE THREAD

**Issue by harshajayaweeraXHJ** [medusajs/medusa#3847]
In admin panel "invite you team" option doesn't work

In admin panel "invite you team" option doesn't work. when I click on the button it pops up and let me enter email and select the member type. When click submit in backend it shows 200 success.

`[15/Apr/2023:12:33:39 +0000] "POST /admin/invites HTTP/1.1" 200 2 "https://admin.mydomain.app/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"`

also following message

`{"level":"info","message":"Processing invite.created which has 0 subscribers","timestamp":"2023-04-15 12:33:40"}`

But I never receive the email. 

I did set up the **medusa-plugin-sendgrid** plugin as well (assuming it's what required to send invitation email)
Here's the plugin configuration

```
{
    resolve: `medusa-plugin-sendgrid`,
    options: {
      api_key: process.env.SENDGRID_API_KEY,
      from: process.env.SENDGRID_FROM,
      order_placed_template:
      process.env.SENDGRID_ORDER_PLACED_ID,
      localization: {
        "de-DE": { // locale key
          order_placed_template:
          process.env.SENDGRID_ORDER_PLACED_ID_LOCALIZED,
        },
      },
    },
  }
```

But I get no invitation at all

### System information

My versions are as follow

"@medusajs/medusa": "^1.6.0"
"medusa-plugin-sendgrid": "^1.3.9"
Node.js version: 18.15.0
NPM:  9.5.0
Database: postgresql
Operating system: Ubuntu on heroku
Browser (if relevant): Chrome

**Comment by olivermrbl** [comment]
The SendGrid plugin does not support invites out of the box. You will have to create a custom subscriber listening on event `invite.created` and use the method `sendEmail` in the SendGridService to send out an email. Remember every type of notification in SendGrid relies on a template, so you will have to create one for the invite too.

**Comment by harshajayaweeraXHJ** [comment]
@olivermrbl  Thanks. But what should I do with **data.token** parameter received from the subscribe function. Should I create an invitation link out of that. If so how can I do it. What should be the link format in order to send the invitation email.
Can you please explain. Thanks

**Comment by olivermrbl** [comment]
The invite URL sent to users should be structured like so: `https://[your-medusa-admin-url]/invite?token=${token}`

**Comment by harshajayaweeraXHJ** [comment]
It worked perfectly. Thanks
