### ISSUE TITLE
Is the frontend page of medusa opensource ?

### ISSUE THREAD

**Issue by CodeWizarz** [medusajs/medusa#3851]
# Hey I recently stumbled upon your website and was impressed with the components used. I'm curious to know if the website source code is open source and available on GitHub? If so, I'd love to take a look and learn from it. Sorry if this was innappropriate.

**Comment by olivermrbl** [comment]
Our website is, unfortunately, not open source. Though, we are contemplating making it public when it has reached a state appropriate for that.
