### ISSUE TITLE
Problem starting

### ISSUE THREAD

**Issue by stvoidmain** [medusajs/medusa#3857]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Tried with npm, yarn and pnpm, same result always, 
There's no more messages than this ones, i tried in both ways, using `create-medusa-app` and `medusa new my-medusa-store --seed`, both fail

> medusa-starter-default@0.0.1 clean
> cross-env ./node_modules/.bin/rimraf dist

[medusa-config] ⚠️ redis_url not found. A fake redis instance will be used.
[medusa-config] ⚠️ jwt_secret not found. fallback to either cookie_secret or default 'supersecret'.
[medusa-config] ⚠️ cookie_secret not found. fallback to either cookie_secret or default 'supersecret'.
{"level":"info","message":"Using fake Redis","timestamp":"2023-04-17 09:33:29"}
{"activity_id":"01GY7K9DRJR5PBB87FFVF47K3Q","config":{},"level":"info","message":"Initializing models\r\n","timestamp":"2023-04-17 09:33:29"}
{"activity_id":"01GY7K9DRJR5PBB87FFVF47K3Q","duration":36,"level":"info","message":"Models initialized","timestamp":"2023-04-17 09:33:29"}
{"activity_id":"01GY7K9DSQJWW21QM6FZEDA1NS","config":{},"level":"info","message":"Initializing plugin models\r\n","timestamp":"2023-04-17 09:33:29"}
{"activity_id":"01GY7K9DSQJWW21QM6FZEDA1NS","duration":6,"level":"info","message":"Plugin models initialized","timestamp":"2023-04-17 09:33:29"}
{"activity_id":"01GY7K9DSY1653RPR8DF004X88","config":{},"level":"info","message":"Initializing strategies\r\n","timestamp":"2023-04-17 09:33:29"}
{"activity_id":"01GY7K9DSY1653RPR8DF004X88","duration":2,"level":"info","message":"Strategies initialized","timestamp":"2023-04-17 09:33:29"}
{"activity_id":"01GY7K9DT0271Y2K3077TV9Y6A","config":{},"level":"info","message":"Initializing modules\r\n","timestamp":"2023-04-17 09:33:29"}
{"level":"warn","message":"Local Event Bus installed. This is not recommended for production.","timestamp":"2023-04-17 09:33:29"}
{"activity_id":"01GY7K9DT0271Y2K3077TV9Y6A","duration":15,"level":"info","message":"Modules initialized","timestamp":"2023-04-17 09:33:29"}
{"activity_id":"01GY7K9DTG20J03K41AF2J7E4H","config":{},"level":"info","message":"Initializing database\r\n","timestamp":"2023-04-17 09:33:29"}
{"activity_id":"01GY7K9DTG20J03K41AF2J7E4H","duration":1078,"level":"info","message":"Database initialized","timestamp":"2023-04-17 09:33:30"}
{"activity_id":"01GY7K9EWBPZTXF6EQGQNS649B","config":{},"level":"info","message":"Initializing repositories\r\n","timestamp":"2023-04-17 09:33:30"}
{"activity_id":"01GY7K9EWBPZTXF6EQGQNS649B","duration":64,"level":"info","message":"Repositories initialized","timestamp":"2023-04-17 09:33:30"}
{"activity_id":"01GY7K9EYCPVKE6PVM23NDB826","config":{},"level":"info","message":"Initializing services\r\n","timestamp":"2023-04-17 09:33:30"}
{"activity_id":"01GY7K9EYCPVKE6PVM23NDB826","duration":1,"level":"info","message":"Services initialized","timestamp":"2023-04-17 09:33:30"}
{"activity_id":"01GY7K9EYES7FR7V7RP5045V5J","config":{},"level":"info","message":"Initializing express\r\n","timestamp":"2023-04-17 09:33:30"}
{"level":"error","message":"Error starting server","stack":[{"columnNumber":23,"fileName":"E:\\Proyectos\\Orion\\my-medusa-store\\backend\\node_modules\\awilix\\lib\\container.js","functionName":"Object.resolve","lineNumber":252,"methodName":"resolve","native":false,"typeName":"Object"},{"columnNumber":37,"fileName":"E:\\Proyectos\\Orion\\my-medusa-store\\backend\\node_modules\\@medusajs\\medusa\\dist\\loaders\\passport.js","functionName":null,"lineNumber":51,"methodName":null,"native":false,"typeName":null},{"columnNumber":23,"fileName":"E:\\Proyectos\\Orion\\my-medusa-store\\backend\\node_modules\\@medusajs\\medusa\\dist\\loaders\\passport.js","functionName":"step","lineNumber":33,"methodName":null,"native":false,"typeName":null},{"columnNumber":53,"fileName":"E:\\Proyectos\\Orion\\my-medusa-store\\backend\\node_modules\\@medusajs\\medusa\\dist\\loaders\\passport.js","functionName":"Object.next","lineNumber":14,"methodName":"next","native":false,"typeName":"Object"},{"columnNumber":71,"fileName":"E:\\Proyectos\\Orion\\my-medusa-store\\backend\\node_modules\\@medusajs\\medusa\\dist\\loaders\\passport.js","functionName":null,"lineNumber":8,"methodName":null,"native":false,"typeName":null},{"columnNumber":null,"fileName":null,"functionName":"new Promise","lineNumber":null,"methodName":null,"native":false,"typeName":null},{"columnNumber":12,"fileName":"E:\\Proyectos\\Orion\\my-medusa-store\\backend\\node_modules\\@medusajs\\medusa\\dist\\loaders\\passport.js","functionName":"__awaiter","lineNumber":4,"methodName":null,"native":false,"typeName":null},{"columnNumber":12,"fileName":"E:\\Proyectos\\Orion\\my-medusa-store\\backend\\node_modules\\@medusajs\\medusa\\dist\\loaders\\passport.js","functionName":null,"lineNumber":48,"methodName":null,"native":false,"typeName":null},{"columnNumber":65,"fileName":"E:\\Proyectos\\Orion\\my-medusa-store\\backend\\node_modules\\@medusajs\\medusa\\dist\\loaders\\index.js","functionName":null,"lineNumber":173,"methodName":null,"native":false,"typeName":null},{"columnNumber":23,"fileName":"E:\\Proyectos\\Orion\\my-medusa-store\\backend\\node_modules\\@medusajs\\medusa\\dist\\loaders\\index.js","functionName":"step","lineNumber":56,"methodName":null,"native":false,"typeName":null}],"timestamp":"2023-04-17 09:33:30"}

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by pevey** [comment]
What commands are you using after `create-medusa-app` or `medusa new my-medusa-store --seed`?

Are you doing the install and medusa migration run?  Are you using medusa develop or making a build first?  What command do you use to start the server?

**Comment by stvoidmain** [comment]
I tried both ways, both fail, there is no migration instruction on the site on those two quickstarts (full app and just store) the install is done automatically, migration I don't think is needed because I'm just using the SqlLite, I just want to get it working.

**Comment by stvoidmain** [comment]
I got it with better format if I do:
`cross-env npm run build && node --preserve-symlinks index.js`

> medusa-starter-default@0.0.1 build
> cross-env npm run clean && tsc -p tsconfig.json


> medusa-starter-default@0.0.1 clean
> cross-env ./node_modules/.bin/rimraf dist

Config:
{
  jwtSecret: 'supersecret',
  cookieSecret: 'supersecret',
  database_database: './medusa-db.db',
  database_type: 'sqlite',
  store_cors: 'http://localhost:8000',
  admin_cors: 'http://localhost:7000,http://localhost:7001'
}
[medusa-config] ⚠️ redis_url not found. A fake redis instance will be used.
{"level":"info","message":"Using fake Redis","timestamp":"2023-04-18 12:46:07"}
{"activity_id":"01GYAGPVH2M58GCVX96TE5GQAS","config":{},"level":"info","message":"Initializing models\r\n","timestamp":"2023-04-18 12:46:07"}
{"activity_id":"01GYAGPVH2M58GCVX96TE5GQAS","duration":35,"level":"info","message":"Models initialized","timestamp":"2023-04-18 12:46:07"}
{"activity_id":"01GYAGPVJ7HJCE2XDZ8T7N3NNP","config":{},"level":"info","message":"Initializing plugin models\r\n","timestamp":"2023-04-18 12:46:07"}
{"activity_id":"01GYAGPVJ7HJCE2XDZ8T7N3NNP","duration":5,"level":"info","message":"Plugin models initialized","timestamp":"2023-04-18 12:46:07"}
{"activity_id":"01GYAGPVJDPA496Z5YD0X7XX0X","config":{},"level":"info","message":"Initializing strategies\r\n","timestamp":"2023-04-18 12:46:07"}
{"activity_id":"01GYAGPVJDPA496Z5YD0X7XX0X","duration":1,"level":"info","message":"Strategies initialized","timestamp":"2023-04-18 12:46:07"}
{"activity_id":"01GYAGPVJFYHKM7K7FG17HERWQ","config":{},"level":"info","message":"Initializing modules\r\n","timestamp":"2023-04-18 12:46:07"}
{"level":"warn","message":"Local Event Bus installed. This is not recommended for production.","timestamp":"2023-04-18 12:46:07"}
{"activity_id":"01GYAGPVJFYHKM7K7FG17HERWQ","duration":13,"level":"info","message":"Modules initialized","timestamp":"2023-04-18 12:46:07"}
{"activity_id":"01GYAGPVJXFXWQYB24YH3XJCEN","config":{},"level":"info","message":"Initializing database\r\n","timestamp":"2023-04-18 12:46:07"}
{"activity_id":"01GYAGPVJXFXWQYB24YH3XJCEN","duration":975,"level":"info","message":"Database initialized","timestamp":"2023-04-18 12:46:08"}
{"activity_id":"01GYAGPWHEB18RB085M3BJ6D7Q","config":{},"level":"info","message":"Initializing repositories\r\n","timestamp":"2023-04-18 12:46:08"}
{"activity_id":"01GYAGPWHEB18RB085M3BJ6D7Q","duration":109,"level":"info","message":"Repositories initialized","timestamp":"2023-04-18 12:46:08"}
{"activity_id":"01GYAGPWMW5197KNW73HKCSP2V","config":{},"level":"info","message":"Initializing services\r\n","timestamp":"2023-04-18 12:46:08"}
{"activity_id":"01GYAGPWMW5197KNW73HKCSP2V","duration":2,"level":"info","message":"Services initialized","timestamp":"2023-04-18 12:46:08"}
{"activity_id":"01GYAGPWMZ0WBFB5NCQYSNQJ59","config":{},"level":"info","message":"Initializing express\r\n","timestamp":"2023-04-18 12:46:08"}
Error starting server AwilixResolutionError: Could not resolve 'authService'.

Resolution path: authService
    at Object.resolve (E:\Proyectos\Orion\my-medusa-store\backend\node_modules\awilix\lib\container.js:252:23)
    at E:\Proyectos\Orion\my-medusa-store\backend\node_modules\@medusajs\medusa\dist\loaders\passport.js:51:37
    at step (E:\Proyectos\Orion\my-medusa-store\backend\node_modules\@medusajs\medusa\dist\loaders\passport.js:33:23)
    at Object.next (E:\Proyectos\Orion\my-medusa-store\backend\node_modules\@medusajs\medusa\dist\loaders\passport.js:14:53)
    at E:\Proyectos\Orion\my-medusa-store\backend\node_modules\@medusajs\medusa\dist\loaders\passport.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\Proyectos\Orion\my-medusa-store\backend\node_modules\@medusajs\medusa\dist\loaders\passport.js:4:12)
    at E:\Proyectos\Orion\my-medusa-store\backend\node_modules\@medusajs\medusa\dist\loaders\passport.js:48:12
    at E:\Proyectos\Orion\my-medusa-store\backend\node_modules\@medusajs\medusa\dist\loaders\index.js:173:65
    at step (E:\Proyectos\Orion\my-medusa-store\backend\node_modules\@medusajs\medusa\dist\loaders\index.js:56:23)

**Comment by Gunkev** [comment]
Hey guys, I am also having an error almost similar to yours after upgrading to Medusa 1.9.0. Please what does ` typeorm_1.DataSource is not a constructor`

```[medusa-config] ⚠️ redis_url not found. A fake redis instance will be used.
info:    Using fake Redis
√ Models initialized – 59ms
√ Plugin models initialized – 11ms
√ Strategies initialized – 112ms
- Initializing modules
warn:    Local Event Bus installed. This is not recommended fo√ Modules initialized – 38ms
- Initializing database
error:   Error starting server
TypeError: typeorm_1.DataSource is not a constructor
    at backend\node_modules\@medusajs\medusa\dist\loaders\database.js:64:42
    at step (\backend\node_modules\@medusajs\medusa\dist\loaders\database.js:33:23)
    at Object.next (\backend\node_modules\@medusajs\medusa\dist\loaders\database.js:14:53)
    at \backend\node_modules\@medusajs\medusa\dist\loaders\database.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (backend\node_modules\@medusajs\medusa\dist\loaders\database.js:4:12)
```

**Comment by olivermrbl** [comment]
@Gunkev – have you followed the upgrade guide? Looks like you haven't bumped Typeorm.

**Comment by Gunkev** [comment]
@olivermrbl Thanks I missed the Typeorm settings. 
However, I am getting this new error

```| Initializing defaults
error:   An error occurred while processing cart.customer_updated: QueryFailedError: SQLITE_ERROR: cannot start a transaction within a transaction
error:   An error occurred while processing cart.customer_updated: QueryFailedError: SQLITE_ERROR: cannot start a transaction within a transaction
error:   An error occurred while processing cart.customer_updated: QueryFailedError: SQLITE_ERROR: cannot start a transaction within a transaction
error:   Error starting server
TransactionNotStartedError: Transaction is not started yet, start transaction before committing or rolling it back.
    at SqliteQueryRunner.commitTransaction (\backend\node_modules\typeorm\driver\sqlite-abstract\AbstractSqliteQueryRunner.js:92:19)
    at EntityManager.transaction (\backend\node_modules\typeorm\entity-manager\EntityManager.js:74:31)
```

**Comment by PlasticLizard** [comment]
I'm also getting this error - fresh install, following the getting started guide.

**Comment by pevey** [comment]
I believe the option of using sqllite has recently been deprecated.

**Comment by olivermrbl** [comment]
SQLite support will be dropped in the next release, so I recommend changing the database configuration to Postgres and try again.

**Comment by rida-re** [comment]
Hello, 
You can fix that problem, try changing your dependancy  in package.json "typeorm" with this version : "^0.3.16".
you can use this command line: `yarn add typeorm`

> Hey guys, I am also having an error almost similar to yours after upgrading to Medusa 1.9.0. Please what does ` typeorm_1.DataSource is not a constructor`
> 
> ```
> info:    Using fake Redis
> √ Models initialized – 59ms
> √ Plugin models initialized – 11ms
> √ Strategies initialized – 112ms
> - Initializing modules
> warn:    Local Event Bus installed. This is not recommended fo√ Modules initialized – 38ms
> - Initializing database
> error:   Error starting server
> TypeError: typeorm_1.DataSource is not a constructor
>     at backend\node_modules\@medusajs\medusa\dist\loaders\database.js:64:42
>     at step (\backend\node_modules\@medusajs\medusa\dist\loaders\database.js:33:23)
>     at Object.next (\backend\node_modules\@medusajs\medusa\dist\loaders\database.js:14:53)
>     at \backend\node_modules\@medusajs\medusa\dist\loaders\database.js:8:71
>     at new Promise (<anonymous>)
>     at __awaiter (backend\node_modules\@medusajs\medusa\dist\loaders\database.js:4:12)
> ```

Hello, 
You can fix that problem, try changing your dependancy  in package.json "typeorm" with this version : "^0.3.16".
you can use this command line: `yarn add typeorm`

**Comment by rameen0165** [comment]
error:   Error starting server
Error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string
    at Object.continueSession (C:\Users\dell\Desktop\ecom\my-medusa-store\backend\node_modules\pg\lib\crypto\sasl.js:24:11)
    at Client._handleAuthSASLContinue (C:\Users\dell\Desktop\ecom\my-medusa-store\backend\node_modules\pg\lib\client.js:272:18)
    at Connection.emit (node:events:511:28)
    at C:\Users\dell\Desktop\ecom\my-medusa-store\backend\node_modules\pg\lib\connection.js:117:12
    at Parser.parse (C:\Users\dell\Desktop\ecom\my-medusa-store\backend\node_modules\pg-protocol\dist\parser.js:40:17)
    at Socket.<anonymous> (C:\Users\dell\Desktop\ecom\my-medusa-store\backend\node_modules\pg-protocol\dist\index.js:11:42)
    at Socket.emit (node:events:511:28)
    at addChunk (node:internal/streams/readable:332:12)
    at readableAddChunk (node:internal/streams/readable:305:9)
    at Readable.push (node:internal/streams/readable:242:10)

**Comment by pevey** [comment]
The basic cause of this error is that the application is not able to parse your postgresql password from the url in the settings.  This could be because the password is not set or perhaps because it contains special characters or perhaps some other reason.

**Comment by shahednasser** [comment]
Closing this issue as it seems outdated now or related to database credentials. Feel free to reopen it if the issue occurs again.
