### ISSUE TITLE
Align `POST /swaps` and `POST /returns` payloads

### ISSUE THREAD

**Issue by srindom** [medusajs/medusa#386]
In [/api/routes/store/create-return.js](https://github.com/medusajs/medusa/blob/master/packages/medusa/src/api/routes/store/returns/create-return.js) the payload calls for:

```js
    return_shipping: Validator.object()
      .keys({
        option_id: Validator.string().optional(),
      })
      .optional(),
```

and in [/api/routes/store/create-swap.js](https://github.com/medusajs/medusa/blob/master/packages/medusa/src/api/routes/store/swaps/create-swap.js) the payload calls for: 

```js
    return_shipping_option: Validator.string().optional(),
```

These should be aligned so that both use:
```js
    return_shipping_option: Validator.string().optional(),
```

**Comment by gaurav1999** [comment]
Request to close the issue as it's fixed.

**Comment by olivermrbl** [comment]
Not implemented yet. Feel free to give it a go. [This nested payload](https://github.com/medusajs/medusa/blob/7e306af6871f4911a988ccf7934771519c466f3f/packages/medusa/src/api/routes/store/returns/create-return.ts#L222) should be removed and return shipping in the [general payload](https://github.com/medusajs/medusa/blob/7e306af6871f4911a988ccf7934771519c466f3f/packages/medusa/src/api/routes/store/returns/create-return.ts#L259) for the endpoint should be changed to:
```
 return_shipping_option: Validator.string().optional(),
```

Please ensure that tests are passing

**Comment by gaurav1999** [comment]
Cool, taking a look.

**Comment by AnshulAngaria** [comment]
Hi @olivermrbl , @srindom , I would like to work on this if this is still open.
