### ISSUE TITLE
Performance problems with products

### ISSUE THREAD

**Issue by solisation** [medusajs/medusa#3862]
## Performance problems with 100 variants per product (v1.8)

The variants have 5 options

### Admin dashboard

**This is the error message when opening a product in the admin dashboard:**

Unexpected Application Error!
Request failed with status code 502
Error: Request failed with status code 502
    at Bg (https://*.de/app/assets/index-66e8218d.js:264:25635)
    at Hg (https://*.de/app/assets/index-66e8218d.js:264:25818)
    at XMLHttpRequest.te (https://*.de/app/assets/index-66e8218d.js:265:1989)
💿 Hey developer 👋

**With a product with only 30 variants, it loads very long, but opens it**

**Comment by cristian25cd** [comment]
I'm also having trouble loading products. On Sentry the error seems to be related with multiple queries against `money_amount` table:
![image](https://user-images.githubusercontent.com/8431304/232837938-93e9039a-eee4-4740-a832-deb2cdcde754.png)


The Queries:
`SELECT "ma"."id" AS "ma_id", "ma"."created_at" AS "ma_created_at", "ma"."updated_at" AS "ma_updated_at", "ma"."deleted_at" AS "ma_deleted_at", "ma"."currency_code" AS "ma_currency_code", "ma"."amount" AS "ma_amount", "ma"."min_quantity" AS "ma_min_quantity", "ma"."max_quantity" AS "ma_max_quantity", "ma"."price_list_id" AS "ma_price_list_id", "ma"."variant_id" AS "ma_variant_id", "ma"."region_id" AS "ma_region_id", "price_list"."id" AS "price_list_id", "price_list"."created_at" AS "price_list_created_at", "price_list"."updated_at" AS "price_list_updated_at", "price_list"."deleted_at" AS "price_list_deleted_at", "price_list"."name" AS "price_list_name", "price_list"."description" AS "price_list_description", "price_list"."type" AS "price_list_type", "price_list"."status" AS "price_list_status", "price_list"."starts_at" AS "price_list_starts_at", "price_list"."ends_at" AS "price_list_ends_at", "price_list"."includes_tax" AS "price_list_includes_tax", "currency"."includes_tax" AS "currency_includes_tax", "currency"."code" AS "currency_code", "region"."includes_tax" AS "region_includes_tax", "region"."id" AS "region_id" FROM "money_amount" "ma" LEFT JOIN "price_list" "price_list" ON "price_list"."id"="ma"."price_list_id" AND ("price_list"."deleted_at" IS NULL)  LEFT JOIN "currency" "currency" ON "currency"."code"="ma"."currency_code"  LEFT JOIN "region" "region" ON "region"."id"="ma"."region_id" AND ("region"."deleted_at" IS NULL)  LEFT JOIN "price_list_customer_groups" "price_list_cgroup" ON "price_list_cgroup"."price_list_id"="price_list"."id" LEFT JOIN "customer_group" "cgroup" ON "cgroup"."id"="price_list_cgroup"."customer_group_id" AND ("cgroup"."deleted_at" IS NULL) WHERE ( "ma"."variant_id" = $1 AND ("ma"."price_list_id" is null or "price_list"."status" = 'active') AND ("price_list"."ends_at" is null OR "price_list"."ends_at" > $2) AND ("price_list"."starts_at" is null OR "price_list"."starts_at" < $3) AND "cgroup"."id" is null ) AND ( "ma"."deleted_at" IS NULL )`

`SELECT COUNT(DISTINCT("ma"."id")) AS "cnt" FROM "money_amount" "ma" LEFT JOIN "price_list" "price_list" ON "price_list"."id"="ma"."price_list_id" AND ("price_list"."deleted_at" IS NULL)  LEFT JOIN "currency" "currency" ON "currency"."code"="ma"."currency_code"  LEFT JOIN "region" "region" ON "region"."id"="ma"."region_id" AND ("region"."deleted_at" IS NULL)  LEFT JOIN "price_list_customer_groups" "price_list_cgroup" ON "price_list_cgroup"."price_list_id"="price_list"."id" LEFT JOIN "customer_group" "cgroup" ON "cgroup"."id"="price_list_cgroup"."customer_group_id" AND ("cgroup"."deleted_at" IS NULL) WHERE ( "ma"."variant_id" = $1 AND ("ma"."price_list_id" is null or "price_list"."status" = 'active') AND ("price_list"."ends_at" is null OR "price_list"."ends_at" > $2) AND ("price_list"."starts_at" is null OR "price_list"."starts_at" < $3) AND "cgroup"."id" is null ) AND ( "ma"."deleted_at" IS NULL )`

**Comment by olivermrbl** [comment]
@ri-t @cristian25cd Please follow our issue template, so we have the context to assist you. Closing until then.
