### ISSUE TITLE
bug(backend): Stops serving requests on /store/products and /store/categories only on production

### ISSUE THREAD

**Issue by flashjames** [medusajs/medusa#3868]
# Notice: 
- I'm not able to make this reproducible locally (without vercel storefront deployment in fronte it), only with storefront on vercel
- I'm opening this as an issue if somebody else run into the same problem, and also as a way to document this for myself
- Feel free to close since I can't reproduce it locally, and if this becomes a thing other's run into, I'm open to collaborating on making it reproducible/understanding what happens on medusa level
- I need to solve this at some point, since the workaround disables nextjs prefetching
- I've spent about a week hunting down this issue, but I've not looked into what happens at medusajs level - mainly since I've not been able to reproduce it locally and that I found a workaround

## Bug report
Medusa stops responding for requests to /store/products and /store/categories, but it responds on /
Happened after upgrade to medusa 1.8.0

### Steps to reproduce the behavior

1. Go to first page, 
2. Go to a category page and scroll a few products pages 
3. Go to a new category page and scroll a few pages 
4.  => Medusa stops responding

Video showing when it happens:
[Screencast from 2023-04-16 12:45:27.webm](https://user-images.githubusercontent.com/359702/232731320-b5a4d2cc-0bb5-45af-9c8c-91727a513475.webm)

## What I've narrowed it down to and tested
- It's some requests that frontend/vercel makes to backend that triggers the error
  - To test: Use vercel deployment and use the local medusajs backend (api) 
- It's not nginx that's the problem
  - Tested lots of different nginx workarounds
  - Tested removing nginx (i.e. connect directly to medusa)
  - Removing https
  - Tested different load balancers
- It's not a ram issue 
 - Nginx shows "reported that client prematurely closed connection, so upstream connection is closed too while sending request to upstream" after error triggered" and some stackoverflow post said this could indicate ram issues
 - running next build && next start and have the production server's api url in it and using localhost:7002 and do the steps mentioned above.
   - This does not the trigger the error only using storefront on vercel
   - To do next: Understand which calls frontend on vercel does but not when running storefront locally, end especially what's different about the calls

## Context
- Info about database for backend medusa:  Around 30 000 products and 500 product categories
- The bug happened after upgrade to medusa 1.8.0
  - I've reset the database after upgrade (with medusa seed) and re-added the products and categories again. This signals to me it's shouldnt be a faulty database problem

### System information

Medusa version (including plugins):
Node.js version:
Database: Postgresql
Operating system: Ubuntu and each part needed for medusa backend in an individual docker
Browser (if relevant): Tested with firefox/chrome/chromium, all of them triggers the bug

# Workaround
Disable nextjs prefetching of < Link >

Add this to src/pages/_app.tsx (to disable prefetching on <Link> globally..
```
import { useRouter } from "next/router"
import { useMemo } from "react"
const router = useRouter()

useMemo(() => {
  const prefetch = router.prefetch
  router.prefetch = async () => { }
  return () => { router.prefetch = prefetch }
}, [router])
```
For other workarounds, see: https://github.com/vercel/next.js/discussions/24437#discussioncomment-4160205

Details on nextjs prefetching - "nextjs disable prefetch on hover over <Link>": https://www.phind.com/search?cache=a33152b5-c2ee-4092-931f-d76cccab561d
It's not possible do disable prefetching on <Link> hover with <Link prefetch={false}> in the current storefront nextjs version, but prefetch={false} disables prefetch on hover too in next 13.

**Comment by flashjames** [comment]
Another reason why I didn't follow through on actually trying to understand what causes the issue in medusa is that there's not really any logging to help understand why an error happens.

But I know you have this in the backlog: https://github.com/medusajs/medusa/discussions/2841

**Comment by chemicalkosek** [comment]
This could have been fixed in https://github.com/medusajs/medusa/pull/3829
Can you try Medusa 1.8.2?

**Comment by chemicalkosek** [comment]
This could have been fixed in https://github.com/medusajs/medusa/pull/3829
Can you try medusa 1.8.2?

**Comment by tabilzad** [comment]
I'm running 1.8.2 and also getting this issue when building the store frontend with docker. After generating static pages, the backend stops responding.

**Comment by olivermrbl** [comment]
Please see [this comment](https://github.com/medusajs/medusa/issues/3874#issuecomment-1537377399) and report back.

**Comment by olivermrbl** [comment]
Will close this for now. @flashjames please let me know if this is still an issue. Happy to reopen :)
