### ISSUE TITLE
Complete cart in Payment Stripe Plugin not working

### ISSUE THREAD

**Issue by pepijn-vanvlaanderen** [medusajs/medusa#3871]
### Describe the bug

When running the Medusa Stripe payment plugin in combination with for example iDEAL payments a webhook event for the `payment_intent.succeeded` from Stripe is fired to the Medusa Stripe hook endpoint. The event is received properly, only there is an error when the `idempotencyKey` is retrieved, since it does not exist first time over a MedusaError is thrown. 

The issue is located here: https://github.com/medusajs/medusa/blob/d85d7bb6d4d3641c834b775a77e7e50b4cdf8326/packages/medusa-payment-stripe/src/api/utils/utils.ts#L229

I tried to resolve it by catching it and set an undefined value:
```
    let idempotencyKey = await idempotencyKeyServiceTx.retrieve({
      request_path: "/stripe/hooks",
      idempotency_key: eventId,
    }).catch(() => undefined)
```

However in that case still there is no Order created from the Cart

### System information

Medusa version (including plugins): 1.8.2
Medusa Stripe Plugin version: 2.0.2
Node.js version: v18
Database: Postgres 15
Operating system: MacOS
Browser (if relevant): -

### Steps to reproduce the behavior

1. Buy something through a storefront
2. Use Stripe with iDEAL to pay the order 
3. Make sure Stripe events are enabled for your Medusa backend
4. See the webhook being called and errors to a 409

### Expected behavior

An order was created for the cart.

**Comment by pepijn-vanvlaanderen** [comment]
@adrien2p I also commented on your PR https://github.com/medusajs/medusa/pull/4025, but added this comment here as reference to the original issue.

**Comment by adrien2p** [comment]
@pepijn-vanvlaanderen just seen your comment sorry, could you update your pr to only add the withTransaction please 🙏

**Comment by DidierGuyon** [comment]
@adrien2p The PR is updated, should be ready for merge.

**Comment by maxxlt** [comment]
is this released? I'm still facing with this issue

**Comment by nickmonad** [comment]
Still seeing this issue with `medusa-payment-stripe` `v6.0.2`
