### ISSUE TITLE
Product's metadata is removed from meilisearch's index(and possibly any other search engine) when updating a product

### ISSUE THREAD

**Issue by Gustavodacrvi** [medusajs/medusa#3900]
## Bug report

I'm using the product's metadata to filter and search products using Meilisearch, I have some attributes like "sales" for example, where you can track how many sales a given product has.

When starting the server, the metadata field is properly indexed as it should, but as soon as you update the product(like the title), the metadata field disappears from the index.

### System information

Medusa version (including plugins): 1.8.0
"@medusajs/medusa-cli": "^1.3.9",
"medusa-plugin-meilisearch": "^2.0.0",

Node.js version: v19.0.0
Database: postgres
Operating system: Windows 11(I'm developing from Docker though)

### Steps to reproduce the behavior

1. Add some metadata to any product, for example: "{ test: true }"
2. Add "metadata.test" to meilisearch's filterableFields attribute, and try filtering products.
3. Update this product's title/description to anything.
4. The same filter now should not work, as the metadata field has been removed.

### Expected behavior

The fields that are indexed initially(with npm run start) should not change later once a user updates the product.

### My Solution

After exploring the source code, I'm pretty sure the problem is on [this file](https://github.com/medusajs/medusa/blob/30ee10fddd7d8e2f7d742101aad10d2c688ac98e/packages/medusa/src/subscribers/product.js), on the "handleProductUpdate" method, it calls "retrieveProduct", where the "select" parameter receives the "searchFields" variable that does not contain the "metadata" field. This means every time the user updates a product, the metadata field is removed from the index of the search engine.

I believe this can be fixed by simply adding the metadata field, or perhaps removing the "select" attribute completely and simply indexing the entire product again, just like it happens initially.

I ended up creating another subscriber that listens to "product.updated" and does the same thing, without removing "metadata", as a workaround for now:

```
reindexMetadata = async (data) => {
		const product = await this.productService.retrieve(data.id, {
			relations: [
				"variants",
				"tags",
				"type",
				"collection",
				"variants.prices",
				"variants.options",
				"options",
			],
		})
		await this.meilisearchService.addDocuments("products", [product], "products")
	};
```

**Comment by olivermrbl** [comment]
Nice catch @Gustavodacrvi. Opened a PR that resolves your issue. Can I get you to give it a review? :)

**Comment by alsherif-khalaf** [comment]
> Nice catch @Gustavodacrvi. Opened a PR that resolves your issue. Can I get you to give it a review? :)

it is working fine but without price
```ts
settings: {
        products: {
          indexSettings: {
            searchableAttributes: ["title", "subtitle","description", "variant_sku", "metadata.title_ar"],
            displayedAttributes: [
              "id",
              "title",
              "subtitle",
              "description",
              "variant_sku",
              "thumbnail",
              "handle",
              "metadata.title_ar"
            ],
          },
          primaryKey: "id",
          transformer: (product) => {
            const { id, title, subtitle, description, thumbnail, handle, metadata } = product
            const titleAR = product.metadata.title_ar
            return {
              id,
              title,
              subtitle,
              titleAR,
              description,
              thumbnail,
              handle,
              price: product.variants[0].prices[0].amount,
              metadata
            }
          },
        },

```
