### ISSUE TITLE
Medusa OAS CLI tool throws error

### ISSUE THREAD

**Issue by sats268842** [medusajs/medusa#3911]
### Describe the bug

Getting error running Medusa OAS CLI Command:

command: 
yarn medusa-oas oas --type store --out-dir ./build/oas 

Error:
🟣 Generating OAS - store
🔴 Invalid OAS - store {
  stack: 'MissingPointerError: Token "schemas" does not exist.\n' +
    '    at Pointer.resolve (\node_modules\@readme\json-schema-ref-parser\lib\pointer.js:94:13)\n' +
    '    at $Ref.resolve node_modules\@readme\json-schema-ref-parser\lib\ref.js:118:20)\n' +
    '    at $Refs._resolve (\node_modules\@readme\json-schema-ref-parser\lib\refs.js:162:15)\n' +
    '    at dereference$Ref (\node_modules\@readme\json-schema-ref-parser\lib\dereference.js:186:25)\n' +
    '    at crawl (\manna-foods-medusa-api\node_modules\@readme\json-schema-ref-parser\lib\dereference.js:88:28)\n' +
    '    at crawl \node_modules\@readme\json-schema-ref-parser\lib\dereference.js:115:28)\n' +
    '    at crawl (\node_modules\@readme\json-schema-ref-parser\lib\dereference.js:115:28)\n' +
    '    at crawl (\node_modules\@readme\json-schema-ref-parser\lib\dereference.js:115:28)\n' +
    '    at crawl (\node_modules\@readme\json-schema-ref-parser\lib\dereference.js:115:28)\n' +
    '    at crawl (\node_modules\@readme\json-schema-ref-parser\lib\dereference.js:115:28)',
  code: 'EMISSINGPOINTER',
  message: 'Token "schemas" does not exist.',
  source: '/',
  path: null,
  toJSON: [Function: toJSON],
  name: 'MissingPointerError',
  footprint: 'null+d://+EMISSINGPOINTER+Token "schemas" does not exist.',
  toString: [Function: toString]
}

### System information

Medusa version (including plugins):
     "@babel/preset-typescript": "^7.21.4",
    "@medusajs/admin": "^2.0.2",
    "@medusajs/cache-inmemory": "^1.8.0",
    "@medusajs/cache-redis": "^1.8.0",
    "@medusajs/event-bus-local": "^1.8.0",
    "@medusajs/event-bus-redis": "^1.8.0",
    "@medusajs/medusa": "^1.8.2",
    "@medusajs/medusa-cli": "^1.3.10",
    "@medusajs/medusa-oas-cli": "^0.2.2"

Node.js version: v18.14.0
Database: Postgres V15
Operating system: Win11
Browser (if relevant):

### Steps to reproduce the behavior

1. Run the command from the root folder of backend ("yarn medusa-oas oas --type store --out-dir ./build/oas ")

### Expected behavior

It will produce open api schemas and documentation

**Comment by nikhil-1911** [comment]
any update on this error?

**Comment by zulianrizki** [comment]
Not working in windows 10 but working when using `wsl`

**Comment by mortifia** [comment]
same bug in windows 11
node 20

**Comment by microCloudCode** [comment]
same bug  in windows 10

**Comment by HumansIt** [comment]
any news about this ??

**Comment by herawais** [comment]
How to trace OAS errors, as it dont show the origin of problem

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
