### ISSUE TITLE
Price list's calculated_price not being indexed by meilisearch

### ISSUE THREAD

**Issue by Gustavodacrvi** [medusajs/medusa#3912]
## Bug report

In my app, I have a "catalog" page, where users can see all products, and this page is fully controlled by meilisearch. I want to sort them and show the discounted products at the top. I'm trying to do that with price lists.

However, the calculated_price is not being indexed by meilisearch, which means it's currently not possible to show promotions like (10% off) from the search engine.

Fetching from medusa directly:
![image](https://user-images.githubusercontent.com/45800674/234007320-a0434d82-5b78-4a71-a401-c40c632d5963.png)

From meilisearch:
![image](https://user-images.githubusercontent.com/45800674/234007504-7b7caee1-9541-49b8-8229-233a68616850.png)
Note: I know it's possible to see the price list on the "prices", however, that array always shows all the price overrides, regardless of whether the price list is active or not.

I've also noted that the default currency is not being used by the [context object](https://docs.medusajs.com/modules/price-lists/price-selection-strategy#context-object) on the price [calculation strategy](https://github.com/medusajs/medusa/blob/30ee10fddd7d8e2f7d742101aad10d2c688ac98e/packages/medusa/src/strategies/price-selection.ts), so I need to explicitly specify the currency I want(with ?currency_code=eur), but I think it would make more sense to use the default currency whenever possible, especially considering I only have one currency in my app.

### System information

Medusa version (including plugins): 1.8.0
"@medusajs/medusa-cli": "^1.3.9",
"medusa-plugin-meilisearch": "^2.0.0",

Node.js version: v19.0.0
Database: postgres
Operating system: Windows 11(I'm developing from Docker though)

### Steps to reproduce the behavior

1. Add any product.
2. Add any price list promotion to this product.
3. Fetch this product from medusa itself(/store/products/{id}), the calculated_price will be correct.
4. Search for this product using meilisearch, the calculated_price won't be there. 

### Expected behavior

calculated_price should be somehow indexable by meilisearch. Use the default currency for the context object.

**Comment by tsvetann** [comment]
@olivermrbl I am also investing efforts in meilisearch and am blocked by lack of product price in meilisearch. What would be the correct direction here to achieve product pricing in meilisearch? I can see you have labeled this issue as a feature. I am willing to have a look and possibly add default currency/region if we can align and agree what is the best strategy here. Thanks

**Comment by herawais** [comment]
Any update so far ?

**Comment by NicolasGorga** [comment]
Hello any updated on this?

**Comment by Dr4x3nCD** [comment]
Bonjour, avez-vous des nouvelles à ce sujet ?
