### ISSUE TITLE
Add Iranian Toman currency

### ISSUE THREAD

**Issue by samyarkd** [medusajs/medusa#3913]
### Describe the bug
I'd like to add Iranian Toman currency to Medusa which described in this feature request : https://github.com/medusajs/medusa/discussions/3850

### Steps to reproduce the behavior
When you want to add a new currency there is no Iranian Toman.

### Expected behavior

Since most of the people in Iran use Toman as their primary it's expected to have Iranian Toman currency in the list too.

### Additional context

I opened this issue as described in the CONTRIBUTION guide and i'd like to add it to the currencies list

**Comment by olivermrbl** [comment]
@samyarkd Thanks - I'd be happy to accept a PR for it. Let me know if you need help :)

**Comment by curllog** [comment]
@olivermrbl Hi can you please review https://github.com/medusajs/medusa/pull/4878
thanks
