### ISSUE TITLE
Capture method does not change to automatic

### ISSUE THREAD

**Issue by nikhil-1911** [medusajs/medusa#3927]
As you can see the capture_method is still in manual even though I am setting the 'capture' flag to true in medusa store project 

I want payments to be captured automatically. 

Could you please look into this, thanks!

**Comment by chemicalkosek** [comment]
It is supposed to be in stripe plugin options, not admin options.

**Comment by nikhil-1911** [comment]
@chemicalkosek  Put it under stripe and it worked! Thanks.
