### ISSUE TITLE
Unable to install @medusajs/admin

### ISSUE THREAD

**Issue by imash96** [medusajs/medusa#3940]
## Bug report

Fail to install @medusajs/admin becuase of dependencies mismatch

### System information

Medusa version (including plugins): 1.9.0
Node.js version: 18.16.0
Database: postgresql
Operating system: Win 11
Browser (if relevant): Chrome

### Steps to reproduce the behavior

1. Go to cmd and install @medusajs/admin using npm
2. See error :
npm i @medusajs/admin
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: medusa-starter-default@0.0.1
npm ERR! Found: @medusajs/medusa@1.8.2
npm ERR! node_modules/@medusajs/medusa
npm ERR!   peer @medusajs/medusa@"1.8.2" from medusa-payment-stripe@2.0.2
npm ERR!   node_modules/medusa-payment-stripe
npm ERR!     medusa-payment-stripe@"^2.0.0" from the root project
npm ERR!   @medusajs/medusa@"^1.8.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! @medusajs/admin@"*" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @medusajs/medusa@1.9.0
npm ERR! node_modules/@medusajs/medusa
npm ERR!   peer @medusajs/medusa@"1.9.0" from @medusajs/admin@3.0.0
npm ERR!   node_modules/@medusajs/admin
npm ERR!     @medusajs/admin@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\username\AppData\Local\npm-cache\_logs\2023-04-27T07_20_01_706Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Local\npm-cache\_logs\2023-04-27T07_20_01_706Z-debug-0.log

### Expected behavior

I was expecting that @medusajs/admin get install without any error

### Screenshots

![image](https://user-images.githubusercontent.com/18481370/234790098-aff3fcd3-2126-4deb-9994-61070b60f32d.png)

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

I am using npm to install all the packages

**Comment by mewulonu** [comment]
I faced similar issue when trying to do fresh "npm install". I ran "npm install --legacy-peer-deps" and installed fine. Maybe try "npm install @medusajs/admin --legacy-peer-deps"

**Comment by lauriskuznecovs** [comment]
I got this working by updating related packages which is correct action at this point.
```
npm install @medusajs/medusa@latest @medusajs/medusa-cli@latest medusa-payment-stripe@latest
```

But there is still one thing wrong, migration fails for default starter kit.
Using Node.js v16.20, all updated also all other production dependencies which came from default starter kit.
```
➜  backend git:(master) ✗ npx medusa migrations run
[medusa-config] ⚠️ redis_url not found. A fake redis instance will be used.
[medusa-config] ⚠️ redis_url not found. A fake redis instance will be used.
query: PRAGMA foreign_keys = OFF
query: PRAGMA foreign_keys = OFF
query: BEGIN TRANSACTION
query: SELECT * FROM "sqlite_master" WHERE "type" = 'table' AND "name" = 'typeorm_metadata'
query: COMMIT
query: PRAGMA foreign_keys = ON
query: PRAGMA foreign_keys = ON
query: SELECT * FROM "sqlite_master" WHERE "type" = 'table' AND "name" = 'migrations'
query: CREATE TABLE "migrations" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "timestamp" bigint NOT NULL, "name" varchar NOT NULL)
query: SELECT * FROM "migrations" "migrations" ORDER BY "id" DESC
0 migrations are already loaded in the database.
64 migrations were found in the source code.
64 migrations are new migrations must be executed.
query: PRAGMA foreign_keys = OFF
query: BEGIN TRANSACTION
query: CREATE TABLE "fulfillment_provider" ("id" character varying NOT NULL, "is_installed" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_beb35a6de60a6c4f91d5ae57e44" PRIMARY KEY ("id"))
query failed: CREATE TABLE "fulfillment_provider" ("id" character varying NOT NULL, "is_installed" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_beb35a6de60a6c4f91d5ae57e44" PRIMARY KEY ("id"))
error: Error: SQLITE_ERROR: table "fulfillment_provider" already exists
query: ROLLBACK
QueryFailedError: SQLITE_ERROR: table "fulfillment_provider" already exists
    at handler (/home/lauris/Projects/learning/medusa-store/backend/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:81:26)
    at replacement (/home/lauris/Projects/learning/medusa-store/backend/node_modules/sqlite3/lib/trace.js:25:27)
    at Statement.errBack (/home/lauris/Projects/learning/medusa-store/backend/node_modules/sqlite3/lib/sqlite3.js:15:21) {
  query: 'CREATE TABLE "fulfillment_provider" ("id" character varying NOT NULL, "is_installed" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_beb35a6de60a6c4f91d5ae57e44" PRIMARY KEY ("id"))',
  parameters: undefined,
  driverError: Error: SQLITE_ERROR: table "fulfillment_provider" already exists
  --> in Database#all('CREATE TABLE "fulfillment_provider" ("id" character varying NOT NULL, "is_installed" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_beb35a6de60a6c4f91d5ae57e44" PRIMARY KEY ("id"))', undefined, [Function: handler])
      at execute (/home/lauris/Projects/learning/medusa-store/backend/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:62:46)
      at /home/lauris/Projects/learning/medusa-store/backend/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:103:19 {
    errno: 1,
    code: 'SQLITE_ERROR',
    __augmented: true
  },
  errno: 1,
  code: 'SQLITE_ERROR',
  __augmented: true
}

```

**Comment by lauriskuznecovs** [comment]
Basically here are a steps to reproduce:

1. `npx create-medusa-app`
2. Choose: medusa-starter-default
3. Choose: Next.js Starter
4. Trying to follow this guild to install Admin UI: https://docs.medusajs.com/admin/quickstart which fails.
5. Update medusa backend: npm install @medusajs/medusa@latest @medusajs/medusa-cli@latest medusa-payment-stripe@latest
6. Then steps described here should work: https://docs.medusajs.com/admin/quickstart
7. Then next thing what needs to be done is execute migrations which is described here: https://docs.medusajs.com/upgrade-guides/medusa-core/1-9-0
And here all breaks.
See error log in my previous comment.

**Comment by pavelstianko** [comment]
Same problem - I had to use npm install @medusajs/admin --legacy-peer-deps

**Comment by haramishra** [comment]
You can use [nvm](https://github.com/nvm-sh/nvm) to change the node version.

`$ nvm install v16.20`
`$ nvm use v16.20`

you can use node version 16 in one terminal and version 18 in another make sure to set node v18 as default

`$ nvm alias default v18.16`
`$ nvm use`

**Comment by pavelstianko** [comment]
Not working even in 16.20 :( only way is to use --legacy-peer-deps

**Comment by BlainMaguire** [comment]
Perhaps the way to resolve this is to get the ```medusa-payment-stripe plugin``` to use the newer version of medusa as a dependency? It might just need an update and maybe worth raising a PR for it.

Hey @lauriskuznecovs based on that error it looks like you're trying to run migrations on an SQLITE database, which I don't think is supported.

On the starter default, I set up a PostgreSQL database and then set:
```DATABASE_TYPE=postgres```
Along with ```DATABASE_URL``` in the ```.env``` file, I didn't have any issues running migrations.
