### ISSUE TITLE
Docs(Code Issue): Code Issue in /modules/carts-and-checkout/backend/add-fulfillment-provider

### ISSUE THREAD

**Issue by guillmelo** [medusajs/medusa#3947]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The call to super(container) results in a compilation error in version 1.8.2 and 1.9.0

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for reporting this @guillmelo! Will open a fix for it
