### ISSUE TITLE
miniIO related documentation contains an error

### ISSUE THREAD

**Issue by vladimirpekez** [medusajs/medusa#3957]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Documentation regarding miniIO on https://docs.medusajs.com/plugins/file-service/minio states that following command should be run to start miniIO service:

minio backend ~/minio --console-address :9090 --address :9001

But minio does not have such command and thus this results in:

minio backend ~/minio --console-address :9090 --address :9001
**‘backend’ is not a minio sub-command. See ‘minio --help’.**

The correct command is:

minio **server**  ~/minio --console-address :9090 --address :9001

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [x] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for reporting this @vladimirpekez ! Will issue a fix for it

**Comment by shahednasser** [comment]
Or if you feel like opening a fix feel free to do so 😄

**Comment by vladimirpekez** [comment]
@shahednasser here's the PR https://github.com/medusajs/medusa/pull/3972
