### ISSUE TITLE
Docs(Code Issue): Code Issue in /development/entities/create

### ISSUE THREAD

**Issue by ricmello** [medusajs/medusa#3958]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In [Step 5: Use Your Entity](https://docs.medusajs.com/development/entities/create#step-5-use-your-entity), docs are assigning a variable `this.postRepository` which doesn't exist.

### How can this issue be resolved?

1. import the PostRepository created on previous step:
  `import PostRepository from "../repositories/post";`
2. declare variable in the service class: 
  `protected readonly postRepository: typeof PostRepository`

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for reporting this @ricmello ! Feel free to open a fix for the issue 👍🏻
