### ISSUE TITLE
Tax Setting route problem @admin

### ISSUE THREAD

**Issue by pavelstianko** [medusajs/medusa#3961]
There is route problem in Tax Settings (Setting > Tax Settings). The destination url is relative so it goes to `/app/app/a/settings/taxes` and throw error page. Should be absolute like '/app/a/settings/taxes'

**Comment by olivermrbl** [comment]
@pavelstianko – I can't seem to reproduce. What version of admin are you using?

**Comment by pavelstianko** [comment]
I am using @medusajs/admin@3.0.0 and @medusajs/medusa@1.9.0 (node v16.14.2). I also tried the new blank install and it is the same


https://user-images.githubusercontent.com/13132639/235431499-8ce39855-5326-48dc-a323-3138f0af90ba.mov

**Comment by ThomasFranchi** [comment]
Same problem here with a fresh install.  I can access the tax settings by removing "/app/app" in the url.
"@medusajs/admin": "^3.0.0"
"@medusajs/medusa": "^1.8.0",
