### ISSUE TITLE
Confusing "future" word use in local development documentation

### ISSUE THREAD

**Issue by vladimirpekez** [medusajs/medusa#3973]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Documentation regarding local development on URL:

https://docs.medusajs.com/development/fundamentals/local-development

in an Overview section contains a text snippet:

Whether you want to implement something differently, introduce a new **future** as part of Medusa’s core ...

I believe that intention of the author was to specify "feature", a not "future".

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
That's a typo 😅 thanks for catching that! Feel free to open a PR to fix it

**Comment by karti16** [comment]
@shahednasser here is the pr #3977
