### ISSUE TITLE
Routes problem (orders, customers, ...)

### ISSUE THREAD

**Issue by pavelstianko** [medusajs/medusa#4005]
### Describe the bug

Can't open detail page of Order, Customer, Discount, Gift card and pricing.

### System information

Medusa version (including plugins): @medusajs/admin@3.0.0 and @medusajs/medusa@1.9.0
Node.js version: node v16.14.2
Database: PG
Browser: Chrome 112

### Steps to reproduce the behavior

1. Open admin dashboard
2. Show orders list
3. Select order to display detail

### Expected behavior

Order url is /app/a/order_01GZ9EG5ZWCM5W9R15897J8C4B and should be /app/a/orders/order_01GZ9EG5ZWCM5W9R15897J8C4B (same for customers, discounts, ...)

To diplay detail page I have to add /orders/ to route

### Screenshots

https://user-images.githubusercontent.com/13132639/235972742-0a3f5fbd-a9a5-4501-9925-25fb77a924ce.mov

**Comment by olivermrbl** [comment]
Fixed in #3989 + #3999 - releasing tomorrow :)

**Comment by pavelstianko** [comment]
Thank you for speed fix! :)

**Comment by olivermrbl** [comment]
Part of [v1.10.0](https://github.com/medusajs/medusa/releases/tag/v1.10.0)
