### ISSUE TITLE
 Medusa Meilisearch plugin not indexing products and returning a warning instead

### ISSUE THREAD

**Issue by mohamed-achich** [medusajs/medusa#4027]
When attempting to use the Medusa Meilisearch plugin, the products in the database are not being indexed and 
when i send a post request on the following url : "http://localhost:9000/store/products/search" the backend is returning the warning "warn: This is an empty method: search must be overridden a the child class" 

plugin version : medusa-plugin-meilisearch": "^2.0.3" 

medusa-config.js : 
{
    resolve: `medusa-plugin-meilisearch`,
    options: {
      // config object passed when creating an instance
      // of the MeiliSearch client
      config: {
        host: process.env.MEILISEARCH_HOST,
        apiKey: process.env.MEILISEARCH_API_KEY,
      },
      settings: {
        products: {
          indexSettings: {
            searchableAttributes: ["title", "description", "variant_sku"],
            displayedAttributes: [
              "title",
              "description",
              "variant_sku",
              "thumbnail",
              "handle",
            ],
          },
          primaryKey: "id",
          transform: (product) => ({
            id: product.id,
            // other attributes...
          }),
        },
      },
    },
  },

**Comment by pevey** [comment]
What version of medusa are you running?

And also, what version of meilisearch (not the plugin, but the service)?

**Comment by mohamed-achich** [comment]
Thank you for your response, 

Medusa version : v1.9.0

Meilisearch version : v1.1.1

**Comment by pevey** [comment]
I'm not yet able to reproduce this on a clean install on ubuntu.  What platform are you on?  When you start your meilisearch service, do you get any console errors?  Can you access your meilisearch instance directly using curl?

**Comment by mohamed-achich** [comment]
i am using meilisearch cloud (pay as you go plan ) during development, is this causing the problem ?

**Comment by pevey** [comment]
It shouldn't make a difference, as far as I know.  Here are some things I would try in your shoes:

- Are you able to access your cloud instance directly using curl?

- Have you customized the search endpoint in any way?  

- If this is not a clean install of 1.9, try a clean install in a different directory, and see if you get the same error.

- What exactly is the full message you are getting, both in the console where medusa is running and also the full response from the API endpoint.

EDIT:
- Also, check the meili service error logs if those are available in the cloud service.

**Comment by pevey** [comment]
Actually, looking at the above, I was mistaken about the medusa version.  I have tested v1.8 and v1.10.  I have not tested v1.9.

Maybe try upgrading to 1.10.

**Comment by mohamed-achich** [comment]
Thank you for your assistance.

I have not made any changes to the search endpoint. Despite trying to downgrade Medusa version to v1.8, the issue still persists. However, the Meilisearch endpoint is functioning correctly, as I was able to retrieve my indexes without any issues.

Upon further investigation, I found that the Medusa default search service's search function is causing the warning message to appear. Here is the function:

file : https://github.com/medusajs/medusa/blob/develop/packages/medusa/src/services/search.ts

```typescript
  async search(
    indexName: string,
    query: unknown,
    options: unknown
  ): Promise<{ hits: unknown[] }> {
    this.logger_.warn(
      "This is an empty method: search must be overridden a the child class"
    )
    return { hits: [] }
  }
``` 

Shouldn't this function be overridden by the Medusa Meilisearch plugin?

**Comment by pevey** [comment]
Is there a reason you would not want to upgrade to the latest version?  Medusa v1.9 was known to have some issues with subscribers.  I don't know all the details, as I skipped that version.  But to be of further help, I would need to be able to reproduce the error with the latest versions.  So far, I cannot reproduce the error.

**Comment by mohamed-achich** [comment]
upgrading to medusa v1.10 fixed the issue, thank you @pevey
