### ISSUE TITLE
Cannot publish sales channel initially created as draft through Medusa admin GUI

### ISSUE THREAD

**Issue by vladimirpekez** [medusajs/medusa#4028]
### Describe the bug

Cannot publish sales channel initially created as draft through Medusa admin GUI. There's no option available to publish draft channel.

### System information

Medusa version (including plugins): 1.8.0
Node.js version: 16
Database: Postgres latest
Operating system: Mac OS Ventura
Browser (if relevant): Chrome

### Steps to reproduce the behavior

1. Go to Medusa Admin > Settings > Sales Channels
2. Click on + icon and crate a new sales channel as a draft
3. I cannot find an option to publish the newly created draft channel whatever I try

### Expected behavior

There should be a way in Medusa Admin GUI to publish a sales channel created as draft

### Screenshots

![image](https://user-images.githubusercontent.com/4521621/236570648-c99e6dd4-e295-4758-a131-1eb0829added.png)

**Comment by olivermrbl** [comment]
You can enable it by using the button in the top right corner: 

<img width="320" alt="CleanShot 2023-05-07 at 12 14 09@2x" src="https://user-images.githubusercontent.com/59018053/236671459-6470d730-ea76-4dca-8bc1-f56614a05d54.png">
