### ISSUE TITLE
Unable to choose payment method in the storefront

### ISSUE THREAD

**Issue by Gunkev** [medusajs/medusa#4030]
Before creating the issue I checked this #2601 

I am unable to select Stripe as a payment in the storefront. Each time I select stripe it loads and nothing happens

### System information

I recently upgraded to Medusa v10.0.1 using this [procedure](https://docs.medusajs.com/upgrade-guides) :
Node.js version: 18.16.0
Database: I am using the default database with a fake Redis
Operating system: Windows 10

### Steps to reproduce the behavior

1. Go to the admin dashboard ->settings->regions and add a region then select payment type
![stip](https://user-images.githubusercontent.com/36812576/236620917-4eda44cf-cfa1-46f7-bc62-83ea2fadb0b6.PNG)

2. I am using the Nexxtjs storefront. Go to the storefront, log in, add the product and proceed to checkout
4. Scroll down to the payment and choose stripe

![paymentty](https://user-images.githubusercontent.com/36812576/236621026-1a0ae8d4-e6b7-4721-a42f-6feca02baca7.PNG)

 See error
```
10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0"
error:   Could not find a payment provider with id: stripe
Error: Could not find a payment provider with id: stripe
    at PaymentProviderService.retrieveProvider \backend\node_modules\@medusajs\medusa\dist\services\payment-provider.js:493:19)
    at PaymentProviderService.<anonymous> (e\backend\node_modules\@medusajs\medusa\dist\services\payment-provider.js:265:57)
    at step (\backend\node_modules\@medusajs\medusa\dist\services\payment-provider.js:48:23)
    at Object.next (\backend\node_modules\@medusajs\medusa\dist\services\payment-provider.js:29:53)
    at \backend\node_modules\@medusajs\medusa\dist\services\payment-provider.js:23:71
    at new Promise (<anonymous>)
    at __awaiter (\backend\node_modules\@medusajs\medusa\dist\services\payment-provider.js:19:12)
    at\backend\node_modules\@medusajs\medusa\dist\services\payment-provider.js:255:107
    at PaymentProviderService.<anonymous> (\backend\node_modules\@medusajs\medusa\dist\interfaces\transaction-base-service.js:106:62)
    at step (\backend\node_modules\@medusajs\medusa\dist\interfaces\transaction-base-service.js:33:23) {
  type: 'not_found',
  code: undefined,
  date: 2023-05-06T11:01:15.786Z
}
```

### Expected behavior

When stripe is selected, normally it should display the form to input card number, CVC and expiration date

**Comment by Gunkev** [comment]
Even when I want to cancel an order 

```
Could not find a payment provider with id: stripe
Error: Could not find a payment provider with id: stripe
```
I have cross checked my strip configuration and everything is in place. Please does this have to do with the database?

**Comment by olivermrbl** [comment]
Hi there. We highly appreciate you filing an issue and showing an interest in improving Medusa.

I apologize for the delayed response.

Moving forward, we aim to do better. But we would like to start fresh. Therefore, we are considering all older issues as stale and closing them, even though they might still be relevant.

Please don’t hesitate to re-open the issue (or create a new one) if you still need a resolution or an answer.

Thanks ❤️

**Comment by Kushal2024** [comment]
Getting same issue with phonepe as added provider in payment_provider table and region_payment_provider table but still getting this .

**Comment by julianengel** [comment]
Seconding. 

.medusaClient.regions.retrievePaymentProviders is not a function

**Comment by Kushal2024** [comment]
but there is region_payment_providers table

**Comment by julianengel** [comment]
Yeah, seems to be an JS SDK issue, doing a fetch it works without problem. Thank you @Kushal2024

**Comment by Kushal2024** [comment]
Thanks for help. It's working now. @julianengel
