### ISSUE TITLE
Cannot add new Product Type nor Collection through Medusa Admin GUI

### ISSUE THREAD

**Issue by vladimirpekez** [medusajs/medusa#4033]
### Describe the bug

I am assessing the Medusa admin panel for its suitability in an enterprise environment. I presume that Product Type, Product Collections, and Product Attributes are designed to support product search and filtering on the storefront.

However, I cannot find an option to add any of these aforementioned elements through the Medusa admin interface.

Is this a deliberate design choice? If so, is there an alternative method to add these entities, such as through an API?

### System information

Medusa version (including plugins): 1.8.0
Node.js version: 16
Database: postgres
Operating system: Mac OS X Ventura
Browser (if relevant): Chrome

### Steps to reproduce the behavior

1. Go to Admin GUI,
2. Click on Products,
3. You cannot add new Product Type, Collection nor Attribute using GUI. You can only choose existing records - as this is default QuickStart there are none.

### Expected behavior

I assume that user can add Product Type(s), Collection(s) and Attribute(s) using Admin GUI

### Screenshots

![image](https://user-images.githubusercontent.com/4521621/236672228-226b2ef3-cca0-4255-9779-2b01441128b8.png)

**Comment by olivermrbl** [comment]
Product type can be created "in-line", if you type in the input field:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/59018053/236672396-360a12d6-6949-4648-88f2-df8470bc42ca.png">

Product collections exist in their own domain in the products overview:

<img width="426" alt="image" src="https://user-images.githubusercontent.com/59018053/236672419-78a6cfe2-5efb-45ac-88ea-d15f7d99334f.png">

Product attributes are a fixed set of properties and can be populated by expanding the collapsible:
<img width="910" alt="CleanShot 2023-05-07 at 12 35 00@2x" src="https://user-images.githubusercontent.com/59018053/236672481-c7c0e85e-a766-414d-8ce0-6cca31b85306.png">
