### ISSUE TITLE
SQLite + Categories = SQLITE_Constraint error

### ISSUE THREAD

**Issue by spacewalkingninja** [medusajs/medusa#4042]
Just installed latest revision of the medusa CMS. I've been having this problem since before though.
So on my new install whenever I try to create a category I get:

error:   SQLITE_CONSTRAINT: NOT NULL constraint failed: product_category.parent_category_id
QueryFailedError: SQLITE_CONSTRAINT: NOT NULL constraint failed: product_category.parent_category_id
    at Statement.handler (/home/aquaorinoco/m2/my-medusa-store/backend/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:81:26) {
  query: `INSERT INTO "product_category"("id", "created_at", "updated_at", "name", "description", "handle", "is_active", "is_internal", "parent_category_id", "rank", "mpath") VALUES (?, datetime('now'), datetime('now'), ?, ?, ?, 1, 0, NULL, 0, '')`,
  parameters: [ 'pcat_01GZY870ZF4G9HK3VX5Q9XN5NB', 'Shop', '', 'shop' ],
  driverError: [Error: SQLITE_CONSTRAINT: NOT NULL constraint failed: product_category.parent_category_id] {
    errno: 19,
    code: 'SQLITE_CONSTRAINT'
  },
  errno: 19,
  code: 'SQLITE_CONSTRAINT'
}

**Comment by olivermrbl** [comment]
Can I get you to [change database to Postgres](https://docs.medusajs.com/development/backend/configurations#postgresql-configurations) and try again? SQLite support will be dropped very soon.

**Comment by spacewalkingninja** [comment]
yeah I imagined that would've been the case, but I was betting on SQLite as Postgres requires a whopping 20 megs of RAM for every connection, and for small scale this is imo, a overhead that would be unnecessary as SQLite works well for DB's up to ~1TB.
Will change to PostGres and try again..
