### ISSUE TITLE
Postgres Configuration not working

### ISSUE THREAD

**Issue by gfong0199** [medusajs/medusa#4043]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Hello guys, im trying to change to postgress database, and im facing issues after I run medusa migrations run,
I'm not sure whats happening there.
`URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at Function.parseConnectionUrl (C:\Users\andre\Documents\CODING\Ecommerce\admin-backend\my-medusa-store\node_modules\typeorm\driver\DriverUtils.js:159:23)
    at Function.buildDriverOptions (C:\Users\andre\Documents\CODING\Ecommerce\admin-backend\my-medusa-store\node_modules\typeorm\driver\DriverUtils.js:47:43)
    at new PostgresDriver (C:\Users\andre\Documents\CODING\Ecommerce\admin-backend\my-medusa-store\node_modules\typeorm\driver\postgres\PostgresDriver.js:219:51)
    at DriverFactory.create (C:\Users\andre\Documents\CODING\Ecommerce\admin-backend\my-medusa-store\node_modules\typeorm\driver\DriverFactory.js:36:24)
    at new DataSource (C:\Users\andre\Documents\CODING\Ecommerce\admin-backend\my-medusa-store\node_modules\typeorm\data-source\DataSource.js:53:59)
    at C:\Users\andre\Documents\CODING\Ecommerce\admin-backend\my-medusa-store\node_modules\@medusajs\medusa\dist\loaders\database.js:64:42
    at step (C:\Users\andre\Documents\CODING\Ecommerce\admin-backend\my-medusa-store\node_modules\@medusajs\medusa\dist\loaders\database.js:33:23)
    at Object.next (C:\Users\andre\Documents\CODING\Ecommerce\admin-backend\my-medusa-store\node_modules\@medusajs\medusa\dist\loaders\database.js:14:53)
    at C:\Users\andre\Documents\CODING\Ecommerce\admin-backend\my-medusa-store\node_modules\@medusajs\medusa\dist\loaders\database.js:8:71`

this is my medusa-config.js
`const dotenv = require("dotenv");

let ENV_FILE_NAME = "";
switch (process.env.NODE_ENV) {
    case "production":
        ENV_FILE_NAME = ".env.production";
        break;
    case "staging":
        ENV_FILE_NAME = ".env.staging";
        break;
    case "test":
        ENV_FILE_NAME = ".env.test";
        break;
    case "development":
    default:
        ENV_FILE_NAME = ".env";
        break;
}

try {
    dotenv.config({ path: process.cwd() + "/" + ENV_FILE_NAME });
} catch (e) {}

const DATABASE_TYPE = "postgres";

// CORS when consuming Medusa from admin
const ADMIN_CORS =
    process.env.ADMIN_CORS || "http://localhost:7000,http://localhost:7001";

// CORS to avoid issues when consuming Medusa from a client
const STORE_CORS = process.env.STORE_CORS || "http://localhost:8000";

// Database URL (here we use a local database called medusa-development)
const DATABASE_URL =
    process.env.DATABASE_URL || "postgres://localhost/medusa-store";

// Medusa uses Redis, so this needs configuration as well
const REDIS_URL = process.env.REDIS_URL || "redis://localhost:6379";

// Stripe keys
const STRIPE_API_KEY = process.env.STRIPE_API_KEY || "";
const STRIPE_WEBHOOK_SECRET = process.env.STRIPE_WEBHOOK_SECRET || "";

// Melisearch keys
const MEILISEARCH_HOST = process.env.MEILISEARCH_HOST || "";
const MEILISEARCH_API_KEY = process.env.MEILISEARCH_API_KEY || "";

// This is the place to include plugins. See API documentation for a thorough guide on plugins.
const plugins = [
    `medusa-fulfillment-manual`,
    `medusa-payment-manual`,
    // To enable the admin plugin, uncomment the following lines and run `yarn add @medusajs/admin`
    {
        resolve: "@medusajs/admin",
        /** @type {import('@medusajs/admin').PluginOptions} */
        options: {
            autoRebuild: true,
        },
    },
    {
        resolve: "medusa-payment-stripe",
        options: {
            api_key: STRIPE_API_KEY,
        },
    },
];

/** @type {import('@medusajs/medusa').ConfigModule} */
module.exports = {
    projectConfig: {
        // redis_url: REDIS_URL,
        // For more production-like environment install PostgresQL
        database_url: DATABASE_URL,
        database_type: "postgres",
        redis_url: REDIS_URL,
        // database_database: "./medusa-db.sql",
        // database_type: "sqlite",
        store_cors: STORE_CORS,
        admin_cors: ADMIN_CORS,
    },
    plugins,
};`

.env
`
DATABASE_TYPE=postgres
DATABASE_URL="postgres://postgres:123456@127.0.0.1:5432/dummy"
`

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by pevey** [comment]
You’re likely to run into a number of issues if you are running postgres and Medusa in a windows environment. If your dev machine is windows, try installing Ubuntu via wsl. It will save you trouble in the long run.

**Comment by olivermrbl** [comment]
I don't think this is related to Windows, but I might be wrong. 

Can you try to pass the environment variables directly to `projectConfig` instead of via a .env-file?

**Comment by gfong0199** [comment]
I resolved it by dockerizing the backend, its working on PostgreSQL now
