### ISSUE TITLE
Cannot receive a return without issuing a refund

### ISSUE THREAD

**Issue by magdafiktus** [medusajs/medusa#4052]
**Describe the bug**
Issue when we have shipped a claim due to the order being lost/shipped back to the returned and we receive the original order back at warehouse
 
System information
"@medusajs/medusa": "1.9.0",
"@medusajs/medusa-cli": "^1.3.5",
"medusa-core-utils": "^1.1.36",
"medusa-file-spaces": "1.3.1",
"medusa-fulfillment-manual": "1.1.31",
"medusa-fulfillment-webshipper": "^1.3.3",
"medusa-interfaces": "1.3.3",
"medusa-payment-adyen": "1.1.39",
"medusa-payment-klarna": "1.3.4",
"medusa-payment-manual": "^1.0.19",
"medusa-payment-paypal": "1.2.6",
"medusa-payment-stripe": "1.1.49",
"medusa-plugin-brightpearl": "1.3.2",
"medusa-plugin-contentful": "^1.2.3",
"medusa-plugin-discount-generator": "1.1.19",
"medusa-plugin-ip-lookup": "1.2.1",
"medusa-plugin-meilisearch": "1.0.0",
"medusa-plugin-restock-notification": "2.0.0",
"medusa-plugin-segment": "^1.3.0",
"medusa-plugin-sendgrid": "1.3.3",
"medusa-plugin-sentry": "^1.2.3",
"medusa-plugin-slack-notification": "1.3.4",
"medusa-plugin-wishlist": "1.1.37",
"medusa-test-utils": "1.1.37",
Node -> v16.x
OS -> Ubuntu 18.04
Database -> Postgres<!--
 
**Steps to reproduce the behavior**
1. Buy something
2. it gets lost on the way
3. it comes back to the warehouse
4. try to make a return
 
**Expected behavior**
Receive a return without issuing a refund

**Comment by srindom** [comment]
Setting the refund amount to 0 when you create and receive a return is possible. Feel free to reopen and add more details if that is not sufficient.
