### ISSUE TITLE
medusa-file-spaces is not considering content-type of file

### ISSUE THREAD

**Issue by quiloos39** [medusajs/medusa#4063]
When user uploads a file to medusa using `medusa-file-spaces` plugin, metadata for `Content-Type` is not specified and it becomes `application/octet-stream` by default. 

This is leads to strange behaviours where if you are using Stripe Checkout Sessions, product images you uploaded to spaces will be not shown.

**Comment by LeonAlvarez** [comment]
Same issue here:

<img width="759" alt="image" src="https://github.com/medusajs/medusa/assets/22636643/f6368584-8a0b-4d95-b939-e2b7c82ddffe">

<img width="752" alt="image" src="https://github.com/medusajs/medusa/assets/22636643/b5a473c1-2688-4c0f-a082-098c535f5363">

 "@medusajs/medusa": "^1.10.1",
 "medusa-file-spaces": "^1.3.6",
