### ISSUE TITLE
PaymentProcessor doesn't allow updating data

### ISSUE THREAD

**Issue by Toti91** [medusajs/medusa#4076]
### Describe the bug

PaymentProcessor throws the following error when trying to update the payment session data:
`The payment provider saltpay is of type PaymentProcessor. PaymentProcessors cannot update payment session data.`

I am implementing a custom payment with the new PaymentProcessor API. 
When a user enters their card info in the front-end I want to save that data into to the payment session data:

### System information

Medusa version (including plugins): 1.8
Node.js version: 16.13.0
Database: postgres
Operating system: MacOS Ventura
Browser (if relevant): Chrome

### Steps to reproduce the behavior

1. Setup a custom PaymentProcessor
2. Try to update session data from frontend:
```ts
// frontend

await medusaClient.carts.updatePaymentSession(
  paymentSession.cart_id,
  paymentSession.provider_id,
  {
    data: {
     cardInfo: {
       card: data.card,
       expiry: data.expiry,
       cvc: data.cvc,
     },
  },
},
```
3. Medusa throws the error

### Expected behavior

The PaymentProcessor should update the session data

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

updatePayment method in the PaymentProcessor
```ts
async updatePayment(
    context: PaymentProcessorContext,
  ): Promise<void | PaymentProcessorError | PaymentProcessorSessionResponse> {
    this.logger_.info('updatePayment CALLED')

    return {
      session_data: context.paymentSessionData,
      update_requests: { customer_metadata: {} },
    }
  }
```

frontend code when a user submits their credit-card info:
```ts
// frontend

await medusaClient.carts.updatePaymentSession(
  paymentSession.cart_id,
  paymentSession.provider_id,
  {
    data: {
     cardInfo: {
       card: data.card,
       expiry: data.expiry,
       cvc: data.cvc,
     },
  },
},
```

### Additional context

[This issue describes the same problem](https://github.com/medusajs/medusa/issues/3722#issue-1654597216)

**Comment by andrea-spotsoftware** [comment]
Any update on this? Or valid workarounds

**Comment by Toti91** [comment]
> Any update on this? Or valid workarounds

No update but workaround [here](https://github.com/medusajs/medusa/issues/3722#issuecomment-1559867893)

**Comment by adrien2p** [comment]
working on it https://github.com/medusajs/medusa/pull/4442

**Comment by olivermrbl** [comment]
@Toti91 – if we publish a snapshot with the changes in #4442 , would you be able to confirm that everything works as expected on your side?

**Comment by Toti91** [comment]
> @Toti91 – if we publish a snapshot with the changes in #4442 , would you be able to confirm that everything works as expected on your side?

@olivermrbl Sorry I didn't see this in time. 

I updated and tried this on 1.12.2 and I am able to confirm that this works as expected now! 👍
