### ISSUE TITLE
Meilisearch with postgres

### ISSUE THREAD

**Issue by viltersander** [medusajs/medusa#4082]
### Preliminary Checks

- [ ] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

So i try to index products with medusa, but it can't get my products from postgres database. I have it set up locally, but if I index my products, i get 0 hits, when i send request to the backend with query. I can see my products from http://localhost:9000/store/products, but in the meilisearch dashboard it also shows 0 products. How to set it up correctly? I have index name, host and api key, postgres database connection, all set up. Packages installed from medusa docs etc.

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by olivermrbl** [comment]
Can you confirm that the Meilisearch plugin is getting installed correctly?

**Comment by viltersander** [comment]
Yes, it worked before, when I had sqlite, but i changed it to postgres, after that it didn't work anymore. I deleted the index and did it again, still nothing. I see no errors also in my terminal.

**Comment by olivermrbl** [comment]
Can I get you to try to manually trigger a search indexing event by running the following SQL query:
```
insert into staged_job (id, event_name, data) values ('test', 'SEARCH_INDEX_EVENT', '{}')
```

**Comment by viltersander** [comment]
yeah i did it, but if i select the staged_job table i have 0 rows there. In the terminal i get, 
info:    Processing SEARCH_INDEX_EVENT which has 1 subscribers
warn:    This is an empty method: addDocuments must be overridden by a child class

**Comment by olivermrbl** [comment]
> warn: This is an empty method: addDocuments must be overridden by a child class

This warning message tells me your plugin is not installed correctly as reported [here](https://github.com/medusajs/medusa/issues/4027#issuecomment-1537208323). Can I get you to ensure you've bumped `@medusajs/medusa` and `medusa-plugin-meilisearch` to the latest versions? :)

**Comment by viltersander** [comment]
I think i have the latest ones? 
`"dependencies": {
    "@babel/preset-typescript": "^7.21.4",
    "@medusajs/admin": "^3.0.0",
    "@medusajs/cache-inmemory": "^1.8.0",
    "@medusajs/cache-redis": "^1.8.0",
    "@medusajs/event-bus-local": "^1.8.0",
    "@medusajs/event-bus-redis": "^1.8.0",
    "@medusajs/medusa": "^1.10.1",
    "@medusajs/medusa-cli": "^1.3.11",
    "@meilisearch/instant-meilisearch": "^0.13.0",
    "babel-preset-medusa-package": "^1.1.13",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "express": "^4.17.2",
    "medusa-file-minio": "^1.2.0",
    "medusa-fulfillment-manual": "^1.1.37",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.23",
    "medusa-payment-stripe": "^3.0.0",
    "medusa-plugin-algolia": "^0.2.15",
    "medusa-plugin-meilisearch": "^2.0.4",
    "meilisearch": "^0.32.3",
    "pg": "^8.10.0",
    "typeorm": "^0.3.11"
  },`

**Comment by pevey** [comment]
There are a couple of people in discord also reporting this issue: https://discord.com/channels/876835651130097704/1098015733822267392

I can't narrow it down.  In the main codebase I'm working on, I'm using medusa 1.10.0 and the latest versions of meilisearch server and plugin, and I have no indexing issues.  Changes to products are reflected in the search results immediately.

Later today, I will do a test env with everything bumped to latest and see what happens.

@viltersander and anyone else having this issue, is this with the server started in dev mode or production?

**Comment by viltersander** [comment]
> There are a couple of people in discord also reporting this issue: https://discord.com/channels/876835651130097704/1098015733822267392
> 
> I can't narrow it down. In the main codebase I'm working on, I'm using medusa 1.10.0 and the latest versions of meilisearch server and plugin, and I have no indexing issues. Changes to products are reflected in the search results immediately.
> 
> Later today, I will do a test env with everything bumped to latest and see what happens.
> 
> @viltersander and anyone else having this issue, is this with the server started in dev mode or production?

I have everything set up locally

**Comment by olivermrbl** [comment]
~~@viltersander – are you using Postgres?~~

I realise you added that you do in the issue description. Nvm.

**Comment by viltersander** [comment]
> ~@viltersander – are you using Postgres?~
> 
> I realise you added that you do in the issue description. Nvm.

Yep

**Comment by pevey** [comment]
I've tried many things today, but I cannot reproduce this issue.  If I were in your shoes, here are the things I would look at next:

1) Can you confirm that meilisearch-http is up and running well before you try to start the medusa server?

2) Have you properly configured your master key, and are you using the same key both to start meilisearch-http and in your medusa .env file?

3) If your meilisearch instance already has any stored data, try deleting it and letting medusa generate all new data.

**Comment by viltersander** [comment]
> I've tried many things today, but I cannot reproduce this issue. If I were in your shoes, here are the things I would look at next:
> 
> 1. Can you confirm that meilisearch-http is up and running well before you try to start the medusa server?
> 2. Have you properly configured your master key, and are you using the same key both to start meilisearch-http and in your medusa .env file?
> 3. If your meilisearch instance already has any stored data, try deleting it and letting medusa generate all new data.

Yes i have meilisearch running. I use same master key for both. I deleted the index, I can see it deleted from my meilisearch dashboard because it asks to index, and so tried again, after the indexing, I do get products index in my meilisearch dashboard again, but with 0 products. So I don't know what could be the problem.

**Comment by viltersander** [comment]
Anyway, still haven't found fix for it.  :(

**Comment by pevey** [comment]
I've spent quite a bit of time looking, but I was not able to reproduce. If you post your entire medusa-config file, I will take a look.

**Comment by viltersander** [comment]
> I've spent quite a bit of time looking, but I was not able to reproduce. If you post your entire medusa-config file, I will take a look.
Sure, 
`const dotenv = require("dotenv");

let ENV_FILE_NAME = "";
switch (process.env.NODE_ENV) {
  case "production":
    ENV_FILE_NAME = ".env.production";
    break;
  case "staging":
    ENV_FILE_NAME = ".env.staging";
    break;
  case "test":
    ENV_FILE_NAME = ".env.test";
    break;
  case "development":
  default:
    ENV_FILE_NAME = ".env";
    break;
}

try {
  dotenv.config({ path: process.cwd() + "/" + ENV_FILE_NAME });
} catch (e) {}

// CORS when consuming Medusa from admin
const ADMIN_CORS =
  process.env.ADMIN_CORS || "http://localhost:7000,http://localhost:7001";

// CORS to avoid issues when consuming Medusa from a client
const STORE_CORS = process.env.STORE_CORS || "http://localhost:8000";

const DATABASE_TYPE = process.env.DATABASE_TYPE || "postgres";
const DATABASE_URL = process.env.DATABASE_URL || "postgres://localhost/medusa";
const REDIS_URL = process.env.REDIS_URL || "redis://localhost:6379";

const plugins = [
  `medusa-fulfillment-manual`,
  `medusa-payment-manual`,
  {
    resolve: "@medusajs/admin",
    /** @type {import('@medusajs/admin').PluginOptions} */
    options: {
      autoRebuild: true,
    },
  },
  {
    resolve: `medusa-plugin-meilisearch`,
    options: {
      config: {
        host: process.env.MEILISEARCH_HOST,
        apiKey: process.env.MEILISEARCH_API_KEY,
      },
      settings: {
        products: {
          indexSettings: {
            searchableAttributes: [
              "title", 
              "description",
            ],
            displayedAttributes: [
              "title", 
              "description", 
              "thumbnail", 
              "handle",
            ],
          },
          primaryKey: "id",
          transform: (product) => {
            console.log(product); // Add this line to log the transformed product object
            return {
              id: product.id,
              // other attributes...
            };
          },
        },
      },
    },
  },
  {
    resolve: `medusa-file-minio`,
    options: {
        endpoint: process.env.MINIO_ENDPOINT,
        bucket: process.env.MINIO_BUCKET,
        access_key_id: process.env.MINIO_ACCESS_KEY,
        secret_access_key: process.env.MINIO_SECRET_KEY,
    },
  },
];

const modules = {
  /*eventBus: {
    resolve: "@medusajs/event-bus-redis",
    options: {
      redisUrl: REDIS_URL
    }
  },
  cacheService: {
    resolve: "@medusajs/cache-redis",
    options: {
      redisUrl: REDIS_URL
    }
  },*/
}

/** @type {import('@medusajs/medusa').ConfigModule["projectConfig"]} */
const projectConfig = {
  jwtSecret: process.env.JWT_SECRET,
  cookieSecret: process.env.COOKIE_SECRET,
  database_database: "./medusa-db.sql",
  database_type: DATABASE_TYPE,
  store_cors: STORE_CORS,
  admin_cors: ADMIN_CORS,
  // Uncomment the following lines to enable REDIS
  // redis_url = REDIS_URL
}

if (DATABASE_URL && DATABASE_TYPE === "postgres") {
  projectConfig.database_url = DATABASE_URL;
  delete projectConfig["database_database"];
}


/** @type {import('@medusajs/medusa').ConfigModule} */
module.exports = {
  projectConfig,
  plugins,
	modules,
};
`

**Comment by viltersander** [comment]
`const dotenv = require("dotenv");

let ENV_FILE_NAME = "";
switch (process.env.NODE_ENV) {
  case "production":
    ENV_FILE_NAME = ".env.production";
    break;
  case "staging":
    ENV_FILE_NAME = ".env.staging";
    break;
  case "test":
    ENV_FILE_NAME = ".env.test";
    break;
  case "development":
  default:
    ENV_FILE_NAME = ".env";
    break;
}

try {
  dotenv.config({ path: process.cwd() + "/" + ENV_FILE_NAME });
} catch (e) {}

// CORS when consuming Medusa from admin
const ADMIN_CORS =
  process.env.ADMIN_CORS || "http://localhost:7000,http://localhost:7001";

// CORS to avoid issues when consuming Medusa from a client
const STORE_CORS = process.env.STORE_CORS || "http://localhost:8000";

const DATABASE_TYPE = process.env.DATABASE_TYPE || "postgres";
const DATABASE_URL = process.env.DATABASE_URL || "postgres://localhost/medusa";
const REDIS_URL = process.env.REDIS_URL || "redis://localhost:6379";

const plugins = [
  `medusa-fulfillment-manual`,
  `medusa-payment-manual`,
  {
    resolve: "@medusajs/admin",
    /** @type {import('@medusajs/admin').PluginOptions} */
    options: {
      autoRebuild: true,
    },
  },
  {
    resolve: `medusa-plugin-meilisearch`,
    options: {
      config: {
        host: process.env.MEILISEARCH_HOST,
        apiKey: process.env.MEILISEARCH_API_KEY,
      },
      settings: {
        products: {
          indexSettings: {
            searchableAttributes: [
              "title", 
              "description",
            ],
            displayedAttributes: [
              "title", 
              "description", 
              "thumbnail", 
              "handle",
            ],
          },
          primaryKey: "id",
          transform: (product) => {
            return {
              id: product.id,
              // other attributes...
            };
          },
        },
      },
    },
  },
  {
    resolve: `medusa-file-minio`,
    options: {
        endpoint: process.env.MINIO_ENDPOINT,
        bucket: process.env.MINIO_BUCKET,
        access_key_id: process.env.MINIO_ACCESS_KEY,
        secret_access_key: process.env.MINIO_SECRET_KEY,
    },
  },
];

const modules = {
  /*eventBus: {
    resolve: "@medusajs/event-bus-redis",
    options: {
      redisUrl: REDIS_URL
    }
  },
  cacheService: {
    resolve: "@medusajs/cache-redis",
    options: {
      redisUrl: REDIS_URL
    }
  },*/
}

/** @type {import('@medusajs/medusa').ConfigModule["projectConfig"]} */
const projectConfig = {
  jwtSecret: process.env.JWT_SECRET,
  cookieSecret: process.env.COOKIE_SECRET,
  database_database: "./medusa-db.sql",
  database_type: DATABASE_TYPE,
  store_cors: STORE_CORS,
  admin_cors: ADMIN_CORS,
  // Uncomment the following lines to enable REDIS
  // redis_url = REDIS_URL
}

if (DATABASE_URL && DATABASE_TYPE === "postgres") {
  projectConfig.database_url = DATABASE_URL;
  delete projectConfig["database_database"];
}


/** @type {import('@medusajs/medusa').ConfigModule} */
module.exports = {
  projectConfig,
  plugins,
	modules,
};
`

**Comment by pevey** [comment]
And you have these set in your env?:

`        host: process.env.MEILISEARCH_HOST,
        apiKey: process.env.MEILISEARCH_API_KEY,
`

And you're able to access via curl with the above settings?

**Comment by viltersander** [comment]
Yes, in my .env, I have those there. I can yeah.

**Comment by viltersander** [comment]
I fixed it, so simple fix. Just need to use yarn if you install meilisearch plugin, with npm it didn't work, don't know why.

**Comment by pavlotsyhanok** [comment]
fix for me was adding plugin through:

`yarn add medusa-plugin-meilisearch`

and firing up medusa backend from:

`yarn run dev`

instead of

`npx medusa develop`

**Comment by Mazhar905** [comment]
I'm facing the same issue with Meili search
Version
Medusa: 1.2.9
Meilisearch: 1.1.1

Meili search running on localhost
 `GET /store/products/search HTTP/1.0" 404 70 "-" "PostmanRuntime/7.37.3`
 
 Install the plugin using `yarn add medusa-plugin-meilisearch`
 and run the medusa using
 `yarn run dev`
