### ISSUE TITLE
[1.10.1] Category id is displayed instead of the category name

### ISSUE THREAD

**Issue by tsvetann** [medusajs/medusa#4087]
## Bug report
When a category is assigned to a product under the Organize Product section of the product edit modal in the admin, it is displayed as ID instead of label. Please see screenshot below. Even though my category is: `Women` it show as integer 1. This is confusing for the store administrators

### Describe the bug

![Screenshot 2023-05-12 at 16 22 19](https://github.com/medusajs/medusa/assets/2565891/939488af-4810-4876-8fbf-7ad9f680d629)

### System information

Medusa version (including plugins): ^1.10.1
Node.js version: 16.X
Database: postgres
Operating system: MacOS
Browser (if relevant): Chrome

### Steps to reproduce the behavior

1. Go to Product detail page
2. Click on Edit General Information
3. Scroll down to Organize Product -> Categories (categories flag must be enabled)

### Expected behavior

I would expect to see the category label (in my case `Women`)

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by riqwan** [comment]
hey @tsvetann, thanks for sharing this. 

Thats not the ID of the categories, thats the count of categories that were assigned to the product.

If you hover over the number for a second, you will see the list of categories assigned in a tooltip.

Will add a note to review the design for this one.

**Comment by tsvetann** [comment]
Thanks @riqwan for the clarification. In any case it would be better to have a readable label I think. Thanks
