### ISSUE TITLE
Unable to upload file with Medusa-file-s3 

### ISSUE THREAD

**Issue by Gunkev** [medusajs/medusa#4090]
## Bug report
Hi guys. I am unable to upload file to medusa dashboard

### Describe the bug
After installing the medusa-file-s3 plugin ad adding the necessary configs. I am still unable to upload a file. It's telling me to add a file service plugin

### System information

Medusa version : 1.10.0
Node.js version: 18.16.0
Database: sqlite
Operating system: Windows 10
Browser: Firefox

### Steps to reproduce the behavior

1. Install the medusa-file-s3 plugin: `yarn add medusa-file-s3`
2. Add env variables
 ```
S3_URL=<YOUR_BUCKET_URL>
S3_BUCKET=<YOUR_BUCKET_NAME>
S3_REGION=<YOUR_BUCKET_REGION>
S3_ACCESS_KEY_ID=<YOUR_ACCESS_KEY_ID>
S3_SECRET_ACCESS_KEY=<YOUR_SECRET_ACCESS_KEY>
```
3. Add plugin in `medusa-config.js` as instructed in the doc
```
const plugins = [
  // ...
  {
    resolve: `medusa-file-s3`,
    options: {
        s3_url: process.env.S3_URL,
        bucket: process.env.S3_BUCKET,
        region: process.env.S3_REGION,
        access_key_id: process.env.S3_ACCESS_KEY_ID,
        secret_access_key: process.env.S3_SECRET_ACCESS_KEY,
    },
  },
]
```
4. run the server  `yarn run start`
5. Login in the admin dashboard
6. Choose the product menu and click on add products
7. Add products details and media and finally click on publish product.

### Expected behavior
Normally the file should be uploaded and product created

However, I am getting this error in the console
```
error:   Please add a file service plugin in order to manipulate files in Medusa
Error: Please add a file service plugin in order to manipulate files in Medusa
    at DefaultFileService.<anonymous> (store-medusa\my-medusa-store\node_modules\@medusajs\medusa\dist\services\file.js:64:23)
I equally get this warning in the console
```

This is my medusa-config.js file
```
const dotenv = require("dotenv");

let ENV_FILE_NAME = "";
switch (process.env.NODE_ENV) {
  case "production":
    ENV_FILE_NAME = ".env.production";
    break;
  case "staging":
    ENV_FILE_NAME = ".env.staging";
    break;
  case "test":
    ENV_FILE_NAME = ".env.test";
    break;
  case "development":
  default:
    ENV_FILE_NAME = ".env";
    break;
}

try {
  dotenv.config({path: process.cwd() + "/" + ENV_FILE_NAME});
} catch (e) {}

// CORS when consuming Medusa from admin
const ADMIN_CORS =
  process.env.ADMIN_CORS || "http://localhost:7000,http://localhost:7001";

// CORS to avoid issues when consuming Medusa from a client
const STORE_CORS = process.env.STORE_CORS || "http://localhost:8000";

const DATABASE_TYPE = process.env.DATABASE_TYPE || "sqlite";
const DATABASE_URL =
  process.env.DATABASE_URL || "postgres://localhost/medusa-store";
const REDIS_URL = process.env.REDIS_URL || "redis://localhost:6379";

const plugins = [
  `medusa-fulfillment-manual`,
  `medusa-payment-manual`,
  {
    resolve: `medusa-file-s3`,
    options: {
      s3_url: process.env.S3_URL,
      bucket: process.env.S3_BUCKET,
      aws_config_object: {
        region: process.env.S3_REGION,
        access_key_id: process.env.S3_ACCESS_KEY_ID,
        secret_access_key: process.env.S3_SECRET_ACCESS_KEY,
      },
    },
    resolve: "@medusajs/admin",
    /** @type {import('@medusajs/admin').PluginOptions} */
    options: {},
  },
];

const modules = {
  /*eventBus: {
    resolve: "@medusajs/event-bus-redis",
    options: {
      redisUrl: REDIS_URL
    }
  },
  cacheService: {
    resolve: "@medusajs/cache-redis",
    options: {
      redisUrl: REDIS_URL
    }
  },*/
};

/** @type {import('@medusajs/medusa').ConfigModule["projectConfig"]} */
const projectConfig = {
  jwtSecret: process.env.JWT_SECRET,
  cookieSecret: process.env.COOKIE_SECRET,
  database_database: "./medusa-db.sql",
  database_type: DATABASE_TYPE,
  store_cors: STORE_CORS,
  admin_cors: ADMIN_CORS,
  // Uncomment the following lines to enable REDIS
  // redis_url: REDIS_URL
};

if (DATABASE_URL && DATABASE_TYPE === "postgres") {
  projectConfig.database_url = DATABASE_URL;
  delete projectConfig["database_database"];
}

/** @type {import('@medusajs/medusa').ConfigModule} */
module.exports = {
  projectConfig,
  plugins,
  modules,
};
```

**Comment by ripvannwinkler** [comment]
I too am getting this error running `v1.10.1`. It seems that Medusa is unable to resolve the file service plugin, but doesn't spit out any errors.

	const plugins = [
		`medusa-fulfillment-manual`,
		`medusa-payment-manual`,
		{
			resolve: '@medusajs/admin',
			/** @type {import('@medusajs/admin').PluginOptions} */
			options: {
				autoRebuild: true,
			},
		},
		{
			resolve: '@myscope/medusa-file-local',
			
		},
	];

The server starts without error, but `fileService` resolves to the DefaultFileService.

The relevant directory structure from my backend's node_modules dir is:

![image](https://github.com/medusajs/medusa/assets/130069/7d31b059-4a2c-4a15-8b75-782fc384e8d7)


Seems to be related to https://github.com/medusajs/medusa/issues/4070#issue-1704317767

I was able to force the service to load using a custom loader:

    import { asClass } from "awilix";
    import type { AwilixContainer } from "awilix"
    import LocalFileService from "../services/local-file";

    export default async (
      container: AwilixContainer,
      config: Record<string, unknown>
    ): Promise<void> => {
      console.info("Loading local file service");
      container.register("fileService", asClass(LocalFileService).singleton())
      console.info("Ending loader...")
    }

So it's not an issue with the custom service implementation. The plugin resolution seems to not override the DefaultFileService with my implementation of AbstractFileService. I'm using a basic example from the docs to test:

	import type { DeleteFileType, FileServiceGetUploadStreamResult, FileServiceUploadResult, GetUploadedFileType, UploadStreamDescriptorType } from '@medusajs/medusa';
	import { AbstractFileService } from '@medusajs/medusa';

	class LocalFileService extends AbstractFileService {
		constructor(container: any, options: any) {
			super(container, options);
		}

		upload(fileData: Express.Multer.File): Promise<FileServiceUploadResult> {
			throw new Error('Method not implemented.');
		}
		uploadProtected(fileData: Express.Multer.File): Promise<FileServiceUploadResult> {
			throw new Error('Method not implemented.');
		}
		delete(fileData: DeleteFileType): Promise<void> {
			throw new Error('Method not implemented.');
		}
		getUploadStreamDescriptor(fileData: UploadStreamDescriptorType): Promise<FileServiceGetUploadStreamResult> {
			throw new Error('Method not implemented.');
		}
		getDownloadStream(fileData: GetUploadedFileType): Promise<NodeJS.ReadableStream> {
			throw new Error('Method not implemented.');
		}
		getPresignedDownloadUrl(fileData: GetUploadedFileType): Promise<string> {
			throw new Error('Method not implemented.');
		}
	}

	export default LocalFileService;

**Comment by ripvannwinkler** [comment]
So I've been messing with this all day. It seems to boil down to the `isFileService` utility method checking `instanceof AbstractFileService`, which returns false no matter what I do.

Here's the compiled plugin:

```javascript
var LocalFileService = /** @class */ (function (_super) {
    __extends(LocalFileService, _super);
    function LocalFileService(_a, options) {
        var logger = _a.logger;
        var _this = _super.call(this, {}, options) || this;
        // tried with and without the statement below...
        Object.setPrototypeOf(_this, LocalFileService.prototype);
        _this.logger = logger;
        _this.options = __assign(__assign({}, defaultOptions), options);
        // ensure directories exist
        node_fs_1.default.mkdirSync(_this.options.publicPath, { recursive: true });
        node_fs_1.default.mkdirSync(_this.options.privatePath, { recursive: true });
        return _this;
    }
    LocalFileService.prototype.delete = function (fileData) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        // TODO: add security check
                        this.logger.debug('deleting file', fileData.fileKey);
                        return [4 /*yield*/, node_fs_1.default.promises.rm(fileData.fileKey)];
                    case 1:
                        _a.sent();
                        return [2 /*return*/];
                }
            });
        });
    };
    LocalFileService.prototype.getDownloadStream = function (fileData) {
        return __awaiter(this, void 0, void 0, function () {
            var fileName;
            return __generator(this, function (_a) {
                // TODO: add security check
                this.logger.debug('getting download stream', fileData.fileKey);
                fileName = "".concat(this.options.serverUrl, "/").concat(fileData.fileKey);
                return [2 /*return*/, node_fs_1.default.createReadStream(fileName)];
            });
        });
    };
    LocalFileService.prototype.getPresignedDownloadUrl = function (fileData) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                // TODO: add security check
                this.logger.debug('getting presigned download url', fileData.fileKey);
                return [2 /*return*/, "".concat(this.options.serverUrl, "/").concat(fileData.fileKey)];
            });
        });
    };
    LocalFileService.prototype.getUploadStreamDescriptor = function (fileData) {
        return __awaiter(this, void 0, void 0, function () {
            var acl, filename, _a, filePath, fileKey, fileUrl, writeStream, passThrough;
            return __generator(this, function (_b) {
                acl = fileData.acl;
                filename = "".concat(fileData.name, ".").concat(fileData.ext);
                _a = this.getFileDetails({ filename: filename, acl: acl }), filePath = _a.filePath, fileKey = _a.fileKey, fileUrl = _a.fileUrl;
                this.logger.debug('getting upload stream descriptor', fileKey);
                if (node_fs_1.default.existsSync(filePath)) {
                    throw new Error('File already exists');
                }
                writeStream = node_fs_1.default.createWriteStream(filePath);
                passThrough = new stream.PassThrough();
                passThrough.pipe(writeStream);
                return [2 /*return*/, {
                        url: fileUrl,
                        fileKey: fileKey,
                        writeStream: passThrough,
                        promise: Promise.resolve(),
                    }];
            });
        });
    };
    LocalFileService.prototype.upload = function (fileData) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, this.uploadFile(fileData)];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    LocalFileService.prototype.uploadProtected = function (fileData) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, this.uploadFile(fileData, { acl: 'private' })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    LocalFileService.prototype.uploadFile = function (fileData, _a) {
        var _b = _a === void 0 ? {} : _a, _c = _b.acl, acl = _c === void 0 ? '' : _c;
        return __awaiter(this, void 0, void 0, function () {
            var filename, _d, filePath, fileUrl;
            return __generator(this, function (_e) {
                switch (_e.label) {
                    case 0:
                        filename = fileData.originalname;
                        _d = this.getFileDetails({ filename: filename, acl: acl }), filePath = _d.filePath, fileUrl = _d.fileUrl;
                        this.logger.debug('uploading file', filePath);
                        return [4 /*yield*/, node_fs_1.default.promises.copyFile(fileData.path, filePath)];
                    case 1:
                        _e.sent();
                        return [2 /*return*/, { url: fileUrl }];
                }
            });
        });
    };
    LocalFileService.prototype.getFileDetails = function (_a) {
        var _b = _a.filename, filename = _b === void 0 ? '' : _b, _c = _a.acl, acl = _c === void 0 ? '' : _c;
        var basePath = (0, trim_1.trimEnd)(acl === 'private' //
            ? this.options.privatePath
            : this.options.publicPath, '/');
        var baseUrl = (0, trim_1.trimEnd)(this.options.serverUrl, '/');
        var guid = node_crypto_1.default.randomUUID();
        var fileKey = "".concat(basePath, "/").concat(guid, "-").concat(filename);
        var filePath = "".concat(basePath, "/").concat(guid, "-").concat(filename);
        var fileUrl = "".concat(baseUrl, "/").concat(fileKey).toString();
        return {
            fileKey: fileKey,
            filePath: filePath,
            fileUrl: fileUrl,
        };
    };
    return LocalFileService;
}(medusa_1.AbstractFileService));
```

And here's a screenshot of a debugger attached to a .js file in my medusa backend project:

https://i.imgur.com/mEFn49G.png

I copy/pasted the tsconfig.json from the medusa-file-s3 project to be sure it wasn't a typescript configuration issue.

Cannot for the life of me figure out what to do next.

**Comment by chemicalkosek** [comment]
@Gunkev It seems you have `resolve: medusa-file-s3` and `resolve: "@medusajs/admin"` under the same object in plugins array.

The second `resolve` key overwrites the first one, since js object can't have two keys with the same name.

**Comment by pevey** [comment]
Did you configure cors on your bucket? A number of people are using the file s3 plugin with 1.10.1 without issue, so it is not a blanket issue of it not working. There must be something that can be adjusted to make it work. My first place to troubleshoot if I were you would be the bucket permissions. 

Edit:  I also just saw kosek’s response. Definitely fix that first. That may resolve it.

**Comment by tsvetann** [comment]
@ripvannwinkler how do you start your server locally? Can you try to run `NODE_ENV=development node --preserve-symlinks ./index.js` to start your medusa backend?

**Comment by pevey** [comment]
> @ripvannwinkler how do you start your server locally? Can you try to run `NODE_ENV=development node --preserve-symlinks ./index.js` to start your medusa backend?

I might be mistaken, but I don't believe he is trying to load a customized plugin.  If he is installing from npm server, this shouldn't affect the results.

**Comment by pevey** [comment]
> @ripvannwinkler how do you start your server locally? Can you try to run `NODE_ENV=development node --preserve-symlinks ./index.js` to start your medusa backend?


Thinking about it now, there _could_ be a similar issue at play if the plugin and the medusa server are using/expecting different versions of medusa-interfaces.  The OP is running 1.10.0, so I'm thinking that would probably not cause a conflict.  But it's worth bumping absolutely everything to the latest versions just to be sure.

**Comment by olivermrbl** [comment]
@Gunkev – as @chemicalkosek has mentioned, you are missing a "closing" parenthesis in your `medusa-file-s3` entry in the `plugins` array.

@ripvannwinkler – can I get you to create a dedicated issue for your problem? It is unrelated to OP's issue.

**Comment by ripvannwinkler** [comment]
@olivermrbl I think my issue was related to another [bug](https://github.com/medusajs/medusa/issues/1945#issuecomment-1546979613)

Thanks for responding!

**Comment by ZeeshanMehdiDev** [comment]
is it working with V2 ?
