### ISSUE TITLE
 The engine "node" is incompatible with this module. Expected version ">=12.0.0". Got "10.24.1" when running yarn install in storefront, My node version is 20.1.0

### ISSUE THREAD

**Issue by gatwirival** [medusajs/medusa#4096]
## Bug report
error @medusajs/medusa-js@1.3.10: The engine "node" is incompatible with this module. Expected version ">=12.0.0". Got "10.24.1"
error Found incompatible module.

### Describe the bug
When I run `yarn install` in storefront I get the above error.Although when I run `node -v` my node version is `20.1.0`

### What I have tried
- Uninstalling and reinstalling node globally
- Restarting my terminal and IDE

### System information
Medusa version (including plugins):1.3.10
Node.js version:20.1.0
Database: Medusa-db.sql
Operating system:Ubuntu

### Steps to reproduce the behavior
- Create a new Medusa app
- Select Medusa-starter default
- Select next.js starter as your storefront
-    cd my-medusa-store/storefront
- When I run `yarn dev` I get this error 
- Run `yarn install`

### Expected behavior
When I run `yarn dev` I get this error 
```
started server on 0.0.0.0:8000, url: http://localhost:8000
(node:7052) UnhandledPromiseRejectionWarning: /home/gatwiri/my-medusa-store/storefront/node_modules/next/dist/server/next-server.js:110
    compression = this.nextConfig.compress && this.nextConfig.target === "server" ? (0, _compression).default() : undefined;
                ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Timeout.getServerImpl [as _onTimeout] (/home/gatwiri/my-medusa-store/storefront/node_modules/next/dist/server/next.js:59:71)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
(node:7052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7052) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
Error: Not supported
    at Object.loadConfig [as default] (/home/gatwiri/my-medusa-store/storefront/node_modules/next/dist/server/config.js:68:78)
error Command failed with exit code 1.
```
-  I run `yarn install` and experience the above

A clear and concise description of what you expected to happen

### Screenshots
![Screenshot from 2023-05-15 02-14-55](https://github.com/medusajs/medusa/assets/61587290/96997bef-20d0-47d9-a6cd-299233f4604b)
![Screenshot from 2023-05-15 02-15-17](https://github.com/medusajs/medusa/assets/61587290/2a2f3431-48f5-4ab6-a294-2998a5cf6bb4)
![Screenshot from 2023-05-15 02-15-34](https://github.com/medusajs/medusa/assets/61587290/b089f1ee-4956-42db-9515-395830d790b8)

**Comment by riqwan** [comment]
Hey @gatwirival. This seems to be a configuration issue on your machine. You can see in the error message that yarn is using node 10.24.1.

My recommendation here would be to use `nvm` to install node and eliminate configuration issues, reinstall yarn and go through the steps again. 

Additionally, use node 16 or 18, as Medusa is better tested on those versions if you still come across issues with node 20.

**Comment by pevey** [comment]
Node 20 is bleeding edge. That may be why yarn is not recognizing it. It comes with a new permissions api that will likely break a lot of things at first.

**Comment by gatwirival** [comment]
> Hey @gatwirival. This seems to be a configuration issue on your machine. You can see in the error message that yarn is using node 10.24.1.
> 
> My recommendation here would be to use `nvm` to install node and eliminate configuration issues, reinstall yarn and go through the steps again.
> 
> Additionally, use node 16 or 18, as Medusa is better tested on those versions if you still come across issues with node 20.

Thanks, let me do so

**Comment by gatwirival** [comment]
Fixed

**Comment by riqwan** [comment]
Glad to hear that @gatwirival! Can you share what worked so that it helps others in the future as well?

**Comment by gatwirival** [comment]
I installed node version 16 using `nvm` and made it default. Uninstalled and reinstalled yarn, then rebuilt the starter app again.
