### ISSUE TITLE
Typo in Condition Type Relations section in Discounts Architecture

### ISSUE THREAD

**Issue by ashutoshkrris** [medusajs/medusa#4112]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

There are a few typos in the documentation of **Condition Type Relations** section in **Discounts Architecture** page.
In the last three relations description, all of them mention *is an array of product types*. 

![Screenshot 2023-05-16 162127](https://github.com/medusajs/medusa/assets/47353498/28363aca-7a91-4847-bc54-a9c4ef2d8d47)

### How can this issue be resolved?

1. Go to docs > content > modules > discounts > discounts.md file
2. Scroll down to the Condition Type Relations section
3. Make required changes.

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for catching this! Feel free to open a PR with the fix
