### ISSUE TITLE
medusa-plugin-meliesearch test code in npm

### ISSUE THREAD

**Issue by SGFGOV** [medusajs/medusa#4140]
## Bug report

Thjere seem  test code in the npm medusa-plugin-meliesearch of 2.0.5

The loader in the npm has the following code (dist/loader/test.js)

exports.default = (function (container, options) { return __awaiter(void 0, void 0, void 0, function () {
    return __generator(this, function (_a) {
        console.log("heelo");
        return [2 /*return*/];
    });
}); });

### Steps to reproduce the behavior

Available if you open up the npm in nodemodules
### Expected behavior

No functioning test code in npm

### Screenshots

If applicable, add screenshots to help explain your problem

**Comment by olivermrbl** [comment]
@SGFGOV - thanks for highlighting this. I will publish a new version without it :)
