### ISSUE TITLE
Admin Docs and Storefront Docs very slow

### ISSUE THREAD

**Issue by err0x1a** [medusajs/medusa#4152]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I have noticed that the documentation's loading speed is significantly slow, and in some cases, it fails to load altogether. Only in Storefront API and Admin API.

### How can this issue be resolved?

Despite my attempts, I haven't been able to pinpoint the specific problem. 
Attached to this issue a image showcasing a loading time of 3 minutes.
![medusajs-docs](https://github.com/medusajs/medusa/assets/324835/6fcdc9d4-3a67-44e7-85f1-bc45b51a2694)

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by Chetax** [comment]
I would Like to Fix This Issue

**Comment by gmonarque** [comment]
Yes, it's painfully slow :(

**Comment by shahednasser** [comment]
Thank you everyone for reporting this issue! We're aware of it and are planning a fix for it sometime soon.
