### ISSUE TITLE
Customer billing address cascade

### ISSUE THREAD

**Issue by olivermrbl** [medusajs/medusa#417]
When we create a customer with a billing address attached, we should create the billing address in the DB as well.

Adding: `cascade: ["insert"]` to the column options should be sufficient, but an integration test should be able to confirm this.

**Comment by grimxreaper** [comment]
Hi! I'd like to try my hand at this but not sure which files to look into/alter for this. Do you mind giving me more details?

**Comment by zakariaelas** [comment]
@grimxreaper that's awesome! For a starter, in the [customer](https://github.com/medusajs/medusa/blob/master/packages/medusa/src/models/customer.ts#L40) model, we'd like to automatically create a billing address row when we create a customer with a billing address. Our `billing_address` property should look something like this:
```
@OneToOne(() => Address, { cascade: ["insert"] })
@JoinColumn({ name: "billing_address_id" })
billing_address: Address
```

If you're not familiar with typeorm and/or cascades, this is a good (and quick) start to understand [how to do it](https://orkhan.gitbook.io/typeorm/docs/relations#cascade-options) in typeorm (ORM we're using).

**Comment by harrybasra95** [comment]
@srindom  is this issue fixed or not? I see two PRs raised but both have closed status.

**Comment by ivanskodje** [comment]
@olivermrbl 
Seeing this as part of "good first issue" with two closed PRs and no explanation, does not seem like a good first impression to potential contributers. Please consider closing this if this is no longer wanted.
