### ISSUE TITLE
Bug: Team user invite link is incorrect

### ISSUE THREAD

**Issue by felipemullen** [medusajs/medusa#4182]
Recreating this issue here as mentioned in the [original ticket in the admin repository](https://github.com/medusajs/admin/issues/929#issuecomment-1562498223)

## Bug report

Team member invite links are broken (url is incorrect)

### Describe the bug

When creating an invite for a team member, the generated link does not match the deployed admin page url. This happens from the admin ui as well as in the generated email.

### System information

Medusa version (including plugins): 
    "@medusajs/admin": "^5.0.0",
    "@medusajs/medusa": "^1.11.0",

Node.js version: v16.20.0
Database: PostgreSQL
Operating system: debian / MacOS
Browser (if relevant): any

### Steps to reproduce the behavior

1. Go to the settings page for team members
2. Click on 'Invite users'
3. Fill in email and select role
4. Click invite
5. Note the new user in the list of users
6. copy the invite link
7. note that the link does not contain the prefix for your admin page

### Expected behavior

The link should look like 

```
http://localhost:9000/app/invite?token=<token value>`
```

Instead of 

```
http://localhost:9000/invite?token=<token value>
```

### Screenshots

N/A, see [original ticket in admin repo](https://github.com/medusajs/admin/issues/929)

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

I have attempted to add `path: 'adm'` to the plugin import options, but the same error occurs

**Comment by kasperkristensen** [comment]
Fixed in #4173, as Oli mentioned in the other issue you can fix it until the next release by setting a invite link in the settings page.
