### ISSUE TITLE
Error when adding a new tax rate

### ISSUE THREAD

**Issue by kbiits** [medusajs/medusa#4186]
### Describe the bug

Got unknown error when trying to create a new tax rate for a region

### System information

Medusa version (including plugins): ^1.11.0
@medusajs/admin: ^5.0.0
@medusajs/medusa-cli: ^1.3.14
Node.js version: 18.12.1
Database: postgresql
Operating system: windows 11
Browser (if relevant): Google Chrome

### Steps to reproduce the behavior
Go to settings -> tax settings -> choose a region -> click new tax rate -> fill name, tax rate and tax code -> create

### Expected behavior
A new tax rate created

### Screenshots
Request Body
![image](https://github.com/medusajs/medusa/assets/67781184/465991ae-0852-410f-b988-3054773c9824)

API Response
![image](https://github.com/medusajs/medusa/assets/67781184/65a0e9a7-2e4d-45bf-b64e-fb3149d8d2ed)

Error log
![image](https://github.com/medusajs/medusa/assets/67781184/62712621-20ab-4582-84c3-3de2720e4890)

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context
The root cause seems like from the request validator

**Comment by olivermrbl** [comment]
Thanks for highlighting this. Will be fixed in #4189
