### ISSUE TITLE
Is it me or are the API references terribly slow?

### ISSUE THREAD

**Issue by BorisKamp** [medusajs/medusa#4195]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Everything is very unresponsive on Chrome on my MBP.
See the video here:
https://www.awesomescreenshot.com/video/17828990?key=8b3a46311c11c598a81b8390388a4cb4

unfortunately, as it is expected, when I record, it works: the navigation clicks with my mouse make the screen jump to the right position, this works (but normally is very unresponsive for me). 

The real problem can be seen with the search option, As soon as my mouse is there, I click it, nothing happens, after a bit of time the search modal pops up and my chrome tab freezes, (all other tabs & website work for me, so it's def not my internet or macbook. After a while, the search modal disappears and the tab is responsive again.

Am I the only one with this problem? As it's very annoying for someone who's starting with MedusaJS and wants to read the API references while implementing.

### How can this issue be resolved?

Find the problem and fix it.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for reporting this @BorisKamp ! We're actually aware of this issue and we're looking for the best way to resolve it at the moment.

**Comment by BorisKamp** [comment]
> Thank you for reporting this @BorisKamp ! We're actually aware of this issue and we're looking for the best way to resolve it at the moment.

Okay! Good to know it is indeed a problem and not just me or my machine. Good luck fixing it.

**Comment by greendesertsnow** [comment]
it's because of postgres and strapi which medusa is built upon... so, there won't be a solution to that.

**Comment by StephixOne** [comment]
> it's because of postgres and strapi which medusa is built upon... so, there won't be a solution to that.

The issue is clearly referring to the docs, and furthermore, Medusa is not build with Strapi in any way?
