### ISSUE TITLE
Custom Endpoints Only Work in Dev Mode After File Saved and Server Restarted

### ISSUE THREAD

**Issue by pevey** [medusajs/medusa#4197]
### Describe the bug

If you have a custom route that uses CORS, the route will not be available when you first start your server.  If you start in dev mode and then re-save the file, it will trigger something that causes that route to work as expected.

### System information

Medusa version (including plugins): 1.11.0
Node.js version: 18
Database: postgres
Operating system: ubuntu
Browser (if relevant): chrome latest

### Steps to reproduce the behavior

Here's a reliable way to reproduce the error that might help track it down.
```
import { Router } from "express"
import cors from "cors"
import configLoader from "@medusajs/medusa/dist/loaders/config"

export default (rootDirectory: string): Router | Router[] => {

    const config = configLoader(rootDirectory)
    const storeCorsOptions = { origin: config.projectConfig.store_cors.split(","), credentials: true, }
   const adminCorsOptions = { origin: config.projectConfig.admin_cors.split(","), credentials: true, }

   const router = Router()

    router.get("/hello", cors(storeCorsOptions), async (req, res) => {
    //router.get("/hello", async (req, res) => {

        return res.json({ greeting: "Hello" })
    })

  return router
}
```
If you include CORS in your router.get function, the route will NOT load the first time after the server starts.  You get a 404.  You have to got into the file and save it.  After that, the server will recognize it, and you get a 200.

If instead you comment that line and use the version without CORS, it will work the very first time without having to save the file again after the server starts.

### Additional context

More detail in this Discord thread: https://discord.com/channels/876835651130097704/1104313178755711026

**Comment by pevey** [comment]
This is a duplicate of https://github.com/medusajs/medusa/issues/4061

Sorry, I knew I had seen it somewhere before, but I was thinking it was just the Discord thread and a Github issue needed to be made.

This is an easily reproducible issue with the endpoint code above on a fresh Medusa backend install.

@adevinwild, did you ever manage to resolve this?

Thanks.

**Comment by adevinwild** [comment]
I really feel like I have a problem with CORS and no matter how I import it, it still doesn't work.
I tried to change the execution order of my cors, a first one that will target `store` and a second one that will target a regex `admin`.

It seemed to work better than before, but still a problem.

I decided to put the CORS on each of the existing routes and **everything works**.... hoping that one day a solution will be found to this problem...

**Comment by adrien2p** [comment]
@adevinwild have you retried since we merged the pr in the starter with the tsconfig update?

**Comment by adevinwild** [comment]
hi @adrien2p

my `tsconfig.json` was ok, I think that the issue was with mostly with the `cors` package, I decided to use `cors` on every route and I haven't had a problem since so... guess it's fixed ?

**Comment by adrien2p** [comment]
@adevinwild can you share me your custom API when you apply the cors globally and not route by route please

**Comment by adevinwild** [comment]
> @adevinwild can you share me your custom API when you apply the cors globally and not route by route please

I no longer have the code, but roughly speaking, I applied the same regex as here: https://github.com/shahednasser/medusa-1.8-marketplace-tutorial/blob/master/src/api/index.ts

**Comment by adrien2p** [comment]
I ve just updated the starter [default](https://github.com/medusajs/medusa-starter-default/pull/54/files) you can see how I exclude the auth

**Comment by adevinwild** [comment]
@adrien2p thanks I will check it asap
