### ISSUE TITLE
OAS generates docs with errors

### ISSUE THREAD

**Issue by levshkatov** [medusajs/medusa#4199]
### Describe the bug

Perhaps it's a duplicate of the issues regarding "slow docs on the site," but it pertains to the generation of OAS using `@medusajs/medusa-oas-cli`. I'm attempting to generate the default OAS, import it into Swagger editor or Postman, and afterward, I encounter some errors. I can import the Store API with some errors, but the Admin API completely hangs Swagger editor.

### System information

Medusa version (including plugins): 1.11.0
Node.js version: 18.16.0
Database: PostgreSQL
Operating system: Ubuntu 22.04
Browser (if relevant): Google Chrome

### Steps to reproduce the behavior

1. `npm i @medusajs/medusa-cli -g`
2. `medusa new medusa-temp  && cd medusa-temp`
3. `npm i -D @medusajs/medusa-oas-cli`
4. `npx medusa-oas oas --type store --out-dir ./src/oas` or `npx medusa-oas oas --type admin --out-dir ./src/oas`
5. Import docs into Swagger editor or Postman

### Screenshots

![image](https://github.com/medusajs/medusa/assets/8928626/98eba957-4cbc-408c-ab64-e4603fc3b0b8)

**Comment by thejspro** [comment]
This. I tried importing the collections to Postman and Insomnia, and Admin API won't import no matter what. I tried 1.12, 1.11 and 1.10.1, same problem.

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
