### ISSUE TITLE
In the documentation there is medusa-admin, but I can't find it

### ISSUE THREAD

**Issue by craftalpian** [medusajs/medusa#4202]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Hi, I followed the tutorial which is in the documentation available at the following link https://docs.medusajs.com/upgrade-guides/admin/1-0-0#preserving-customizations-in-the-admin . Initially, I was expecting to be able to customize the admin view by ejecting it using the following code `medusa-admin eject -o <output_directory>`. However my command line displays 

> 'medusa-admin' is not recognized as an internal or external command, operable program or batch file.

![image](https://github.com/medusajs/medusa/assets/20887453/6800b06d-e27d-41b3-9100-fc46aa8b5cf6)

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by kasperkristensen** [comment]
Hi @craftalpian, 

The error message is because you haven’t added the Admin CLI to your path. If you don’t want to do that you can either run the command using `npx medusa-admin -o <path>`, or you could add it as a script to your package.json.

**Comment by craftalpian** [comment]
Thank you @kasperkristensen ! May I ask one more thing? After ejecting medusa-admin, is there any other configuration that I need to set up? Because I didn't find it in the medusajs docs. I just found __MEDUSA_BACKEND_URL__, do I need to change that to my production backend url?
<img width="257" alt="image" src="https://github.com/medusajs/medusa/assets/20887453/f905a6cb-2b81-470a-9645-fd28e55f7009">

**Comment by kasperkristensen** [comment]
@craftalpian yes you need to change that. The variable is set in the vite.config.ts that is generated when you eject. You can hardcode your server URL there, or you can set it to an env variable, and then set that in Vercel (or wherever you are hosting your admin).
