### ISSUE TITLE
Docs(Code Issue): Code Issue in /development/endpoints/create

### ISSUE THREAD

**Issue by scalpo** [medusajs/medusa#4218]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

On https://docs.medusajs.com/development/endpoints/create

Line 21 in src/api/index.ts in the sample should be
anotherRouter.get("/store/*", (req, res, next) => {
and not
router.get("/store/*", (req, res, next) => {

### How can this issue be resolved?

1. confirm it's an issue
2. update https://docs.medusajs.com/development/endpoints/create
3.
...

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch @scalpo ! ~Feel free to open a PR and fix it~ I just saw that you did 😄

**Comment by shahednasser** [comment]
Fixed in #4219
