### ISSUE TITLE
Generating API Fixtures

### ISSUE THREAD

**Issue by olivermrbl** [medusajs/medusa#422]
Generate fixtures for models returned by our API. Instead of having one huuuge file with all of our fixtures, we would like to split these up, such that we have a dedicated file for each entity.

API Fixtures checklist → https://www.notion.so/medusajs/API-Fixtures-checklist-5abf366ac6784d4681344b97b3d4aedf

Loom on how to do API fixtures: https://www.loom.com/share/230b0c3ec59144bebbfa7029d31fd1fb

Admin:
- [x] Collections
- [x] Notes
- [x] Notifications
- [ ] Regions (in progress)
- [ ] Shipping Option (in progress)

Store:
- [x] Customer
- [x] Return Reason

**Comment by samrath-sudesh-acharya** [comment]
i would like to do some of the some of the api fixture

**Comment by srindom** [comment]
@samrath-sudesh-acharya if you can list the ones you are going for that would be great :)

**Comment by samrath-sudesh-acharya** [comment]
@srindom  i am starting with Collections in admin . 😄

**Comment by srindom** [comment]
@samrath-sudesh-acharya Sorry this was already done in [#427](https://github.com/medusajs/medusa/pull/427).

How about going for admin/Notes? :)

**Comment by samrath-sudesh-acharya** [comment]
ok cool i will go for that
👍

**Comment by samrath-sudesh-acharya** [comment]
@srindom i cant find integration-tests/docs file in the repo. Could you please help

**Comment by srindom** [comment]
Hi @samrath-sudesh-acharya, the skeleton code should be on the branch [docs/api](https://github.com/medusajs/medusa/tree/docs/api).

This is also the branch you should be branching out from :)

**Comment by samrath-sudesh-acharya** [comment]
ok thanks

**Comment by JakeVdub** [comment]
I'd like to help with this, can I do the "Regions" in "Admin"?

**Comment by olivermrbl** [comment]
Yeah sure @JakeVdub !

**Comment by olivermrbl** [comment]
Update:
- @zakariaelas  -> Shipping Options in admin
- @samrath-sudesh-acharya -> Notes in admin
- @JakeVdub -> Regions in admin
