### ISSUE TITLE
[Build error] Error: While cloning /medusa/packages/utils/node_modules/jest-validate

### ISSUE THREAD

**Issue by lizarddapp** [medusajs/medusa#4220]
![image](https://github.com/medusajs/medusa/assets/91373078/c33a6b5b-55e7-4be7-8f45-bd1674b5085f)

➤ YN0001: │ Error: While cloning /C:/Users/Lim An Chong/Documents/Github/medusa/packages/utils/node_modules/jest-validate 
-> /C:/Users/Lim An Chong/Documents/Github/medusa/packages/medusa-plugin-slack-notification/node_modules/jest-validate UNKNOWN: unknown error, link 'C:\Users\Lim An Chong\Documents\Github\medusa\packages\utils\node_modules\jest-validate\LICENSE' -> 'C:\Users\Lim An Chong\Documents\Github\medusa\packages\medusa-plugin-slack-notification\node_modules\jest-validate\LICENSE'

### System information

Medusa version v1.12.0
Node.js version: v16.20.0 / v18.5.0
Database: postgres
Operating system: Windows 10
Browser (if relevant):

### Steps to reproduce the behavior
1. run 
````yarn install````

**Comment by adrien2p** [comment]
it could be due to the spaces in your path, can you try to remove the spaces or escape them

**Comment by luluhoc** [comment]
@adrien2p trying to install and build monorepo on windows and it fails i don't have spaces in my path

```
➤ YN0001: │ Error: While cloning /C:/Users/admin/Desktop/dev/medusa/packages/oas/openapi-typescript-codegen/node_modules/jest-haste-map -> /C:/Users/admin/Desktop/dev/medusa/packages/admin-ui/node_modules/jest-haste-map UNKNOWN: unknown error, link 'C:\Users\admin\Desktop\dev\medusa\packages\oas\openapi-typescript-codegen\node_modules\jest-haste-map\build\types.js' -> 'C:\Users\admin\Desktop\dev\medusa\packages\admin-ui\node_modules\jest-haste-map\build\types.js'
```

**Comment by adrien2p** [comment]
don't you have anything else than this error? here looks like an issue with jest-hate-map no?

**Comment by luluhoc** [comment]
@adrien2p When I try to yarn & yarn build I get this error on Windows, on my mac the install and build went smoothly,

I have tried to delete all node_modules and clear yarn cache nothing works.

```

➤ YN0000: └ Completed in 0s 774ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 2s 411ms
➤ YN0000: ┌ Link step
➤ YN0001: │ Error: While cloning /C:/Users/admin/Desktop/dev/medusa/packages/oas/openapi-typescript-codegen/node_modules/jest-haste-map -> /C:/Users/admin/Desktop/dev/medusa/packages/admin-ui/node_modules/jest-haste-map UNKNOWN: unknown error, link 'C:\Users\admin\Desktop\dev\medusa\packages\oas\openapi-typescript-codegen\node_modules\jest-haste-map\build\types.js' -> 'C:\Users\admin\Desktop\dev\medusa\packages\admin-ui\node_modules\jest-haste-map\build\types.js'
➤ YN0000: └ Completed in 1m 26s
➤ YN0000: Failed with errors in 1m 29s

```
