### ISSUE TITLE
Difference between the quickstart backend and the backend setup section

### ISSUE THREAD

**Issue by kleenkanteen** [medusajs/medusa#4226]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I am following this guide: https://medusajs.com/blog/extending-medusa-usecase-marketplace/

Under the "Prerequisites" section, it says:
"This article assumes you already have a Medusa backend with v1.8 of Medusa installed. If not, you can learn how to install it [here](https://docs.medusajs.com/development/backend/install)."

I have the quickstart already downloaded though which has a backend. The link it directs to is the separate section just for the backend.

I have looked around in the documentation but cannot figure out how the backend made by https://docs.medusajs.com/create-medusa-app differs from https://docs.medusajs.com/development/backend/install. It would be nice if there was a part in the backend install page that explained the difference between them so I know which to choose when starting.

### How can this issue be resolved?

1. Adding to https://docs.medusajs.com/development/backend/install how the quickstart backend differs from the backend install guide

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Hi @kleenkanteen , thanks for reporting this issue! The `create-medusa-app` command allows you to create a full Medusa project including a backend and a storefront and without the need for you to install the medusa CLI tool globally. The backend quickstart uses the CLI tool and installs only the backend, without any extras.

We're also working on improving the `create-medusa-app` command to become more useful and provide a better experience.

As a summary, you would use the `create-medusa-app` for a guided setup, whereas the backend quickstart provides you more control over the setup of your Medusa backend. However, the backend installed by either approaches is the same.

I'll close this issue for now. Let me know if you have any other questions!

**Comment by kleenkanteen** [comment]
That makes sense, thanks.

**Comment by kleenkanteen** [comment]
Looking back, the backends are different since the backend setup guide tells you how to configure Postgres. The quickstart didn't prompt me for Postgres credentials even though the docs said it would. The guide I am following (linked in my post above) requires Postgres due to SQLite being out of support now. If you are using the quickstart, you have to go through basically the same steps as the backend setup guide except downloading the medusa cli.

This difference is not apparent also. The quickstart should note that it's just for demonstration purposes, and if someone wants to build something with medusa, they should start from the backend setup guide.
