### ISSUE TITLE
Meilisearch transform option doesn't seem to work

### ISSUE THREAD

**Issue by ShivamJoker** [medusajs/medusa#4237]
## Bug report
I am trying to add price for  Meilisearch resolve option doesn't seem to work

### System information

Medusa version (including plugins):
```
    "@medusajs/admin": "^6.0.0",
    "@medusajs/cache-inmemory": "^1.8.7",
    "@medusajs/cache-redis": "^1.8.7",
    "@medusajs/event-bus-local": "^1.9.4",
    "@medusajs/event-bus-redis": "^1.8.7",
    "@medusajs/medusa": "^1.12.0",
    "@medusajs/medusa-cli": "^1.3.15",
    "medusa-file-s3": "^1.2.0",
    "medusa-fulfillment-manual": "^1.1.37",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.23",
    "medusa-payment-stripe": "^6.0.0",
    "medusa-plugin-meilisearch": "^2.0.7",
    "medusa-plugin-segment": "^1.3.5",
    "medusa-plugin-sendgrid": "^1.3.9",
```

Node.js version: 18
Database: postgres/redis/event-bus
Operating system: linux (Arch)

### Steps to reproduce the behavior
Install meilisearch plugin and use the transform option:

```js
 {
    resolve: "medusa-plugin-meilisearch",
    options: {
      config: {
        host: process.env.MEILISEARCH_HOST,
        apiKey: process.env.MEILISEARCH_API_KEY,
      },
      settings: {
        products: {
          indexSettings: {
            searchableAttributes: ["title", "description", "variant_sku"],
            displayedAttributes: [
              "title",
              "description",
              "variant_sku",
              "thumbnail",
              "handle",
            ],
          },
          primaryKey: "id",
          transform: (product) => {
            console.log("price");
            const price = product.variants[0].prices.reduce((_, price) => {
              if (price.currency_code === "inr") {
                return price.amount;
              }
            });
            return {
              // id: product.id,
            };
          },
        },
      },
    },
  },

```

### Expected behavior

There should be a log when running the server.
Initially I was returning price in the object but in search index it was nowhere.

You can find the entire repo: https://github.com/curiosta/curiosta-backend/tree/plugins

**Comment by FaZeRs** [comment]
Looked through meilisearch plugin source and found that it's `transformer` instead of `transform`

https://github.com/medusajs/medusa/blob/develop/packages/medusa-plugin-meilisearch/src/services/meilisearch.ts#L111

**Comment by ShivamJoker** [comment]
Oh I see.
If you go to example it's written `transform`.

https://docs.medusajs.com/plugins/search/meilisearch#index-settings

![image](https://github.com/medusajs/medusa/assets/23727670/24d5fc16-93f7-4c0f-8e30-7dc1d27660ce)


Ok it works after changing it to `transformer`.

Can we update the docs?

Thanks a lot.
