### ISSUE TITLE
Postgres credential not prompted on command "medusa new my-medusa-store"

### ISSUE THREAD

**Issue by kleenkanteen** [medusajs/medusa#4241]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I am following this guide: https://docs.medusajs.com/development/backend/install

I installed the cli with pnpm using pnpx btw. On windows 10, latest version.

In step "2. Create a new Medusa project", it says "You'll then be asked to specify your PostgreSQL database credentials". I was not asked to specify them. Picture attached of my terminal output. I tried this command once again in another folder and I got the same output.

![image](https://github.com/medusajs/medusa/assets/67878058/dc9adf41-95d1-4d8c-8206-978757352050)

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for reporting this issue. Please make sure you're using the latest version of the Medusa CLI.

**Comment by kleenkanteen** [comment]
Interestingly, doing `npm uninstall -g @medusajs/medusa-cli` then `npm install -g @medusajs/medusa-cli` and running `medusa new backend` worked to prompt the credentials. Thanks.
