### ISSUE TITLE
Quick start failed miserably

### ISSUE THREAD

**Issue by tiendq** [medusajs/medusa#4243]
I don't know why this #3743 was closed while the bug is still there without any fix.

I just followed https://docs.medusajs.com/create-medusa-app with yarn option and could not start yarn start with backend. Yes, because of this error `Error: connect ECONNREFUSED 127.0.0.1:5432.`

Ok, so I started a Postgres instance and `yarn start` again, and got a new error `Error: Migrations missing. Please run 'medusa migrations run' and try again`.

Ok, just run what it asked for, and so what, one more error `zsh: command not found: medusa`.

Quick start failed miserably and nothing mentioned in the quick start guide neither troubleshooting section.

**Comment by tiendq** [comment]
Restart everything again (with a running Postgres instance) and faced a new error `Error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string`.

So does this quick start work for anyone?

**Comment by kleenkanteen** [comment]
@tiendq dude why would you add the status that it needs triaging then assign it yourself to the cofounder of medusa? Let them handle it in time. Also it's the weekend so the team is quiet.

Don't follow the quickstart. It misses the configuration steps you need. It's confusing that it doesn't tell you, I know. Start from scratch using the backend setup guide then install the frontend separately as well. 

For the client password must be a string, classic mistake I made as well as my teammate. Your DATABASE_URL is wrong in your .env file.

The proper format is this: 
DATABASE_URL="postgres:/USERNAME:PASSWORD@localhost:PORT/DATABASE_NAME

for example:
example: "postgres://postgres:epic@localhost:5432/postgres"

**Comment by chemicalkosek** [comment]
> @tiendq dude why would you add the status that it needs triaging then assign it yourself to the cofounder of medusa? Let them handle it in time. Also it's the weekend so the team is quiet.

Because it's automatic like that

**Comment by kleenkanteen** [comment]
ah I see

**Comment by pevey** [comment]
>one more error `zsh: command not found: medusa`.

The documentation may assume you have yarn or npm set up so that globally installed packages are in your path.  If you don't have your package manager set up that way, try adding `npx` before the command.

In other words, `npx medusa migrations run`

Does that help?

**Comment by kleenkanteen** [comment]
Did you install the medusa cli stated in the backend quickstart?

**Comment by kleenkanteen** [comment]
@pevey technically it should `npx @medusajs/medusa-cli migrations run` according to https://docs.medusajs.com/development/backend/configurations

**Comment by shahednasser** [comment]
Hey guys, thank you for reporting this issue! Since we previously used SQLite the steps in the guide were sufficient, but now they need to be more elaborate. I've created a PR #4245 to resolve this issue and hopefully make these steps clearer in the docs.

**Comment by tiendq** [comment]
> @tiendq dude why would you add the status that it needs triaging then assign it yourself to the cofounder of medusa? Let them handle it in time. Also it's the weekend so the team is quiet.
> 
> Don't follow the quickstart. It misses the configuration steps you need. It's confusing that it doesn't tell you, I know. Start from scratch using the backend setup guide then install the frontend separately as well.
> 
> For the client password must be a string, classic mistake I made as well as my teammate. Your DATABASE_URL is wrong in your .env file.
> 
> The proper format is this: DATABASE_URL="postgres:/USERNAME:PASSWORD@localhost:PORT/DATABASE_NAME
> 
> for example: example: "postgres://postgres:epic@localhost:5432/postgres"

I know and often use the connection string format you said, but there is no `DATABASE_URL` in `.env` at all. And if you look into `medusa.config.js` you will see default `DATABASE_URL` is a bit strange to me e.g. it has no port number.

**Comment by ivanushkaPr** [comment]
So what was the solution for this ticket? I cannot understand it.

**Comment by kleenkanteen** [comment]
What error message are you getting? You have to edit your .env file to add
the connection details to postgres
