### ISSUE TITLE
Cannot install Contentful starter template

### ISSUE THREAD

**Issue by Hero-from-HeroPixel** [medusajs/medusa#4251]
## Bug report
Unable to install contentful starter template
### Describe the bug
Getting npm install error when following the instructions for installing the contentful template
medusa fails to completely install the node modules and storefront after receiving this error.
### System information
Medusa version (including plugins): medusa CLI: 1.12.0 
Node.js version: 18.16.0
Database: PostgreSQL
Operating system: Windows 11
Browser (if relevant): 

### Steps to reproduce the behavior

1. Install a fresh new medusa app using any package manager, I tried all 3.
2. Choose the contentful starter
3. Any frontend option
4. Error should occur when installing dependencies

### Expected behavior

Expected to install without errors and to install the frontend as well

### Screenshots
![image](https://github.com/medusajs/medusa/assets/23283848/7d72f5b5-857c-4eea-8a3f-48b87461a7ed)

If applicable, add screenshots to help explain your problem

### Code snippets

Error log from terminal:

> > npm ERR! code ERESOLVE
> npm ERR! ERESOLVE could not resolve
> npm ERR!
> npm ERR! While resolving: medusa-starter-contentful@0.0.1
> npm ERR! Found: medusa-interfaces@1.3.7
> npm ERR! node_modules/medusa-interfaces
> npm ERR!   medusa-interfaces@"^1.1.21" from the root project
> npm ERR!   peer medusa-interfaces@"1.3.7" from @medusajs/medusa@1.12.0
> npm ERR!   node_modules/@medusajs/medusa
> npm ERR!     @medusajs/medusa@"^1.1.37" from the root project
> npm ERR!   2 more (medusa-fulfillment-manual, medusa-payment-manual)
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! medusa-payment-stripe@"^1.1.23" from the root project
> npm ERR!
> npm ERR! Conflicting peer dependency: medusa-interfaces@1.3.6
> npm ERR! node_modules/medusa-interfaces
> npm ERR!   peer medusa-interfaces@"1.3.6" from medusa-payment-stripe@1.1.53
> npm ERR!   node_modules/medusa-payment-stripe
> npm ERR!     medusa-payment-stripe@"^1.1.23" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR!
> npm ERR!

### Additional context

Add any other context about the problem here

**Comment by Haiko-E** [comment]
I've been playing around with the contentful setup aswell. But i go from error to error. The last commit from that repo has been 2 years ago. A lot of dependencies are not there or outdated. 

but with this error, i removed the medusa-payment-stripe from the package.json, after that npm install, and after that installed the medusa-payment-stripe again

**Comment by moheldesoqy** [comment]
Did you manage to setup contentful with medusa?

**Comment by Haiko-E** [comment]
Nope, I stopped trying. A lot of stuff wasn't working properly.

Op zo 31 mrt. 2024 12:07 schreef mohamed ***@***.***>:

**Comment by shahednasser** [comment]
Hello, the contentful template is deprecated, to integrate Medusa with Contentful, refer to [this documentation](https://docs.medusajs.com/plugins/cms/contentful)

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
