### ISSUE TITLE
Generating a client with medusa-oas results in invalid hooks

### ISSUE THREAD

**Issue by yanniz0r** [medusajs/medusa#4260]
### Describe the bug

When generating hooks through the medusa-oas cli, the generated hooks are using the Medusa Store context from outside of the corresponding hooks. This leads to the following error when using the hooks:
```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component.
```

### System information

Medusa version (including plugins): 1.11.0
Node.js version: v18.14.2
Database: Sqlite
Operating system: Mac OS 13.4

### Steps to reproduce the behavior

1. Generate the client for a given open api specification with `medusa-oas client --type store --src-file ./store.oas.json`
2. Import a hook inside of a react frontend (eg. `useAuth`) and call it
3. The above mentioned error should be visible

### Expected behavior

The `const { client } = useMedusaStore()` line should be inside of each hook individually to ensure compliance with reacts rules of hooks. It should basically look like this:

### Code snippets

This is how the code is generated:

```typescript
const { client } = useMedusaStore()

export const useAuthGetSession = (
  options: UseQueryOptionsWrapper<Awaited<ReturnType<typeof client.auth.getSession>>> = {}
) => {
  const { data, ...rest } = useQuery<Awaited<ReturnType<typeof client.auth.getSession>>>(
    ['auth', 'getSession'],
    () => client.auth.getSession(),
    options
  );
  return { ...data, ...rest } as const
};
```

This is how the code should look (from my perspective):

```typescript
export const useAuthGetSession = (
  options: UseQueryOptionsWrapper<Awaited<ReturnType<typeof client.auth.getSession>>> = {}
) => {
  const { client } = useMedusaStore()
  const { data, ...rest } = useQuery<Awaited<ReturnType<typeof client.auth.getSession>>>(
    ['auth', 'getSession'],
    () => client.auth.getSession(),
    options
  );
  return { ...data, ...rest } as const
};
```

### Additional context

I'm building the client as an extra package inside a monorepo. This package is built with plain tsc, and consumed in a next js app.

**Comment by yanniz0r** [comment]
I built a small repo where the issue is visible: https://github.com/yanniz0r/medusa-oas-reproduction
Please let me know if I can assist with further info.

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
