### ISSUE TITLE
Collection API response is not returning any products

### ISSUE THREAD

**Issue by onamkrverma** [medusajs/medusa#4264]
### Describe the bug

[Collection list](https://docs.medusajs.com/api/store#tag/Collections)  api response is not returning any products.

### System information

Medusa version (including plugins):
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Steps to reproduce the behavior

1. Go to http://localhost:9000/store/collections?expand=products

### Expected behavior
According to medusa docs [collection list](https://docs.medusajs.com/api/store#tag/Collections)  `The Products contained in the Product Collection. Available if the relation products is expanded.` but I am getting this error 
`{"type":"invalid_data","message":"property expand should not exist"}`

### Screenshots

![image](https://github.com/medusajs/medusa/assets/106578262/d2c2f3fc-29fd-4111-81eb-899dc8d8c9e6)

Without expand parameter I am getting this response ( http://localhost:9000/store/collections)
`{
  "collections": [
    {
      "id": "pcol_id",
      "created_at": "2023-05-17T08:27:32.350Z",
      "updated_at": "2023-05-17T08:27:32.350Z",
      "deleted_at": null,
      "title": "Feature product",
      "handle": "feature",
      "metadata": {}
    }
 ],
  "count": 1,
  "limit": 10,
  "offset": 0
}`

**Comment by pevey** [comment]
I think for what you are looking to do, you might want to use the products endpoint instead.  You can do:
```
/store/products?collection_id[]=${id}
```

**Comment by olivermrbl** [comment]
What @pevey said. Closing this for now. You can submit feature requests in our GitHub Discussions :)
