### ISSUE TITLE
Impossible pass an order on my local

### ISSUE THREAD

**Issue by rida-re** [medusajs/medusa#4266]
Hello,
I can't pass an order on my local, I have this following error :
![image](https://github.com/medusajs/medusa/assets/58844180/a5cadab1-7128-4c3a-a980-fa2344897a28)

**Trace log :**
`./src/modules/checkout/components/billing_address/index.tsx
Error: 
  x Unexpected token `ConnectForm`. Expected jsx identifier
    ,-[C:\Users\Rida\worksapace\medusa\my-medusa-storefront\src\modules\checkout\components\billing_address\index.tsx:5:1]
  5 | 
  6 | const BillingAddress = () => {
  7 |   return (
  8 |     <ConnectForm<CheckoutFormValues>>
    :      ^^^^^^^^^^^
  9 |       {({ register, formState: { errors, touchedFields } }) => (
 10 |         <div className="grid grid-cols-1 gap-y-2">
 10 |           <div className="grid grid-cols-2 gap-x-2">
    `----

Caused by:
    Syntax Error`

**Comment by olivermrbl** [comment]
Closing this issue as:
- Issue does not follow our template
- Error message is not readable
- Seems more related to our storefront project
