### ISSUE TITLE
Medusa migration not working

### ISSUE THREAD

**Issue by Norbeboy1** [medusajs/medusa#4269]
### Describe the bug

I have a sql file under src/migrations folder with a create table and insert into queries.

I start the server and i got this error:

⠋ Initializing database
error:   Error starting server
Error: Migrations missing. Please run 'medusa migrations run' and try again.
    at C:\Norbi\DcBank\Medusa azure\medusa-backend\node_modules\@medusajs\medusa\dist\loaders\database.js:99:31
    at step (C:\Norbi\DcBank\Medusa azure\medusa-backend\node_modules\@medusajs\medusa\dist\loaders\database.js:33:23)
    at Object.throw (C:\Norbi\DcBank\Medusa azure\medusa-backend\node_modules\@medusajs\medusa\dist\loaders\database.js:14:53)
    at rejected (C:\Norbi\DcBank\Medusa azure\medusa-backend\node_modules\@medusajs\medusa\dist\loaders\database.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

I tried to run 'medusa migrations run' but it's giving me this error:

medusa : File C:\Users\User\AppData\Roaming\npm\medusa.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.

### System information

Medusa version (including plugins):
Node.js version: 19
Database: postgresql
Operating system: windows 10
Browser (if relevant):

### Steps to reproduce the behavior

1. Create a sql file under migrations folder
2. Start the server

### Expected behavior

The server starts and the queries are ran successfully.

**Comment by olivermrbl** [comment]
Did you follow the link in the error message to try to resolve your issue?

`For more information, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.`

**Comment by Norbeboy1** [comment]
@olivermrbl Yes, it worked thank you, i thought the problem is from medusa.
But now the problem is that in the migration file i create a table named "custom_options" and it is not created in my database ... all of the tables from medusa are created for example "cart" and so on

**Comment by olivermrbl** [comment]
Have you followed [our guide](https://docs.medusajs.com/development/entities/migrations/create)? You might be missing a build step :)

**Comment by Tobi-dev** [comment]
Same issue here for me.
Migrations only work when i add medusa-extender plugin to the config.

My Steps:
Creating a Migration through the TypeORM CLI:


`npx typeorm migration:create src/migrations/UserChanged`

Add some SQL to the up/down method

`yarn build`

so the dist/migrations folder gets generated

`npx @medusajs/medusa-cli migrations run`

-> "No migrations are pending" and nothing changed in the DB.
![Screenshot 2023-06-09 at 14 15 16](https://github.com/medusajs/medusa/assets/26602092/4f4bd366-a040-42f2-a4f2-0eed0253cc61)


Followed the Guide now atleast 10 times.

I also followed the "Extend an Entity" Guide. Also no success so far...

I also asked the community yesterday, but no answers so far: https://discordapp.com/channels/876835651130097704/1116324244268265523/1116324244268265523

**Comment by kleenkanteen** [comment]
@Tobi-dev in the postgres db look for the migrations table, a new row should be added. Try manually adding it to see if you can force it. Use npm for building also.

**Comment by Norbeboy1** [comment]
It worked for me, thank you, it was just a bit weird to do the steps
