### ISSUE TITLE
Extending core entity not working

### ISSUE THREAD

**Issue by imash96** [medusajs/medusa#4271]
### Describe the bug

I have created a new model file in src/models to accept customer measurements. Then I try to exdend the core entity "Customer" to create a @OneToMany and @ManyToOne relation usign medusa and typeorm guide. Every thing is looking good then I run "npm run build" and "npx typeorm migration:generate -d datasource.js src/migrations/MeasurementCreate" to generate migration but still I am getting a error as below

>Error during migration generation:
TypeORMError: Entity metadata for Customer#billing_address was not found. Check if you specified a correct entity object and if it's connected in the connection options.

### System information

Medusa version (including plugins): v1.12.0
Node.js version: v18.16.0
Database: Postgres
Operating system: Windows 11

### Steps to reproduce the behavior

1. Create a new model file
2. Extend the core entity to create relation between the new model and core entity.
3. Then generate migration file using typeorm

I have attached the both the model files If there are any problem in that please suggest.

Model Files
[customer.txt](https://github.com/medusajs/medusa/files/11707629/customer.txt)
[measurement.txt](https://github.com/medusajs/medusa/files/11707631/measurement.txt)

Repositorie Files
[customer.txt](https://github.com/medusajs/medusa/files/11707646/customer.txt)
[measurement.txt](https://github.com/medusajs/medusa/files/11707647/measurement.txt)

**Comment by imash96** [comment]
@olivermrbl Can you please help me on this it's urgent

**Comment by adrien2p** [comment]
can you share your datasource please. Also I suggest you to look at this [thread](https://github.com/medusajs/medusa/discussions/3366)

**Comment by imash96** [comment]
Hi @adrien2p,

My previous datasource 

const { DataSource } = require("typeorm")

```
const AppDataSource = new DataSource({
  type: "postgres",
  url: "postgres://postgres@localhost/medusa",
  entities: [
    "./dist/models/*.js",
  ],
  migrations: [
    "./dist/migrations/*.js",
  ],
})

module.exports = {
  datasource: AppDataSource,
}
```

After adding below line to migrations and entities the above error was gone but the generated migration is looking wired.

```
entities: [
  "./dist/models/*.js",
  "./node_modules/@medusajs/medusa/dist/models/*.js",
],
migrations: [
  "./dist/migrations/*.js",
  "./node_modules/@medusajs/medusa/dist/migrations/*.js",
],
```

I have attached the geneated migration file.
[1686753173327-MeasurementCreate.txt](https://github.com/medusajs/medusa/files/11747736/1686753173327-MeasurementCreate.txt)


Please guide me how to solve this.

**Comment by imash96** [comment]
Is there any one who can help me please @adrien2p @olivermrbl @l4u

**Comment by adrien2p** [comment]
Unfortunately this is not something we can solve straight away. I suggest you to remove the content that does not correspond to what you have done or to write it manually. This will be improved as we move to the modules splitting

**Comment by dfcan** [comment]
Im having the same exact issue

```
TypeORMError: Entity metadata for Customer#billing_address was not found. Check if you specified a correct entity object and if it's connected in the connection options.
```

Has there been any progress/change on this issue?  

It seems like the only work around is to write migrations manually.  And that means we'll need to do that for all migrations going forward, which isn't ideal.

**Comment by microCloudCode** [comment]
same exact issue
![image](https://github.com/medusajs/medusa/assets/46712199/d497fbbf-9226-441c-8933-0aaf8471c0dc)

**Comment by microCloudCode** [comment]
@adrien2p Is the current solution limited to manual coding only?

**Comment by adrien2p** [comment]
what do you mean @microCloudCode ?

**Comment by microCloudCode** [comment]
@adrien2p What I mean is, can the migrations only be created manually at the moment? The automatically generated migrations have issues.

**Comment by adrien2p** [comment]
yes indeed, unless you clean everything that is not related to your modification from the autogenerated

**Comment by microCloudCode** [comment]
Is there a plan to resolve this issue?

**Comment by aldo-roman** [comment]
@imash96 Why is this closed? There is no fix provided

**Comment by prathameshkurunkar7** [comment]
Any work around for generating migration file for extended entity?

**Comment by ghost** [comment]
I'm seeing the same issue - the Customer class exported from `@medusajs/medusa` v7.1.7 doesn't seem to have any TypeORM decorators on it, meaning that the migration fails to generate as it can't find the relevant entity metadata for the fields on the class.

![image](https://github.com/medusajs/medusa/assets/115482091/999ce279-5258-44be-b8e7-e045bfcbee4a)

**Comment by ghost** [comment]
Okay, so since posting the above I asked a question on the Medusa Discord community and was directed to [this thread](https://discord.com/channels/876835651130097704/1165258128019951626/1176273233641754664), where it's pointed out that the `datasource.js` file for your TypeORM CLI needs to include the entities and migrations in the compiled `@medusajs/medusa` node module. I now realise that those values were also mentioned in one of OP's comments, but I'd missed them previously so I assume the others on here might have missed them too.

For example:

```ts
// datasource.ts
const { DataSource } = require("typeorm")

const AppDataSource = new DataSource({
  type: "postgres",
  url: "postgres://postgres:postgres@localhost:5432/medusa",
  synchronize: false,
  entities: [
    "dist/models/*.js",
    'node_modules/@medusajs/medusa/dist/models/!(*.index.js)',
  ],
  migrations: [
    "dist/migrations/*.js",
    'node_modules/@medusajs/medusa/dist/migrations/*.js',
  ],
})

module.exports = {
  datasource: AppDataSource,
}
```

Thanks to Juan Z on Discord for the fix.

**Comment by luisorbaiceta** [comment]
In my case this didn't solve the issue as it generated a huge migrations file and didn't just add the new column I extended...

**Comment by ghost** [comment]
@luisorbaiceta - yes, I think that's a known issue. See the above question:

---

**microCodeCloud**
> @adrien2p What I mean is, can the migrations only be created manually at the moment? The automatically generated migrations have issues.

---

**adrien2p**
> yes indeed, unless you clean everything that is not related to your modification from the autogenerated

**Comment by luisorbaiceta** [comment]
Is there a plan to remove manual steps for migrations?

**Comment by rein1410** [comment]
Do you guys plan to fix this anytime soon? Honestly this is really terrible developer experience.

**Comment by adrien2p** [comment]
This is an issue with typeorm mostly, they always have issue when issues across packages, so unfortunately we can do much about it

**Comment by Civile** [comment]
@barnabycollins-s2z your solution worked for me as well. My datasource entities and migrations were pointing at files ending with .js while my real files are ending with *.ts. I think its an issue realted to the datasource configuration file. Make sure that entities and migrations are pointing to the right resources


`const { DataSource } = require("typeorm")

const AppDataSource = new DataSource({
  type: "postgres",
  port: 5432,
  username: "postgres",
  password: "root",
  database: "medusa-GFuR",
  entities: [
    "dist/models/*.ts",
  ],
  migrations: [
    "dist/migrations/*.ts",
  ],
})

module.exports = {
  datasource: AppDataSource,
}`

**Comment by darrylmorley** [comment]
> Okay, so since posting the above I asked a question on the Medusa Discord community and was directed to [this thread](https://discord.com/channels/876835651130097704/1165258128019951626/1176273233641754664), where it's pointed out that the `datasource.js` file for your TypeORM CLI needs to include the entities and migrations in the compiled `@medusajs/medusa` node module. I now realise that those values were also mentioned in one of OP's comments, but I'd missed them previously so I assume the others on here might have missed them too.
> 
> For example:
> 
> ```ts
> // datasource.ts
> const { DataSource } = require("typeorm")
> 
> const AppDataSource = new DataSource({
>   type: "postgres",
>   url: "postgres://postgres:postgres@localhost:5432/medusa",
>   synchronize: false,
>   entities: [
>     "dist/models/*.js",
>     'node_modules/@medusajs/medusa/dist/models/!(*.index.js)',
>   ],
>   migrations: [
>     "dist/migrations/*.js",
>     'node_modules/@medusajs/medusa/dist/migrations/*.js',
>   ],
> })
> 
> module.exports = {
>   datasource: AppDataSource,
> }
> ```
> 
> Thanks to Juan Z on Discord for the fix.

Maybe this should be in the example provided in the docs?

**Comment by rein1410** [comment]
> > Okay, so since posting the above I asked a question on the Medusa Discord community and was directed to [this thread](https://discord.com/channels/876835651130097704/1165258128019951626/1176273233641754664), where it's pointed out that the `datasource.js` file for your TypeORM CLI needs to include the entities and migrations in the compiled `@medusajs/medusa` node module. I now realise that those values were also mentioned in one of OP's comments, but I'd missed them previously so I assume the others on here might have missed them too.
> > For example:
> > ```ts
> > // datasource.ts
> > const { DataSource } = require("typeorm")
> > 
> > const AppDataSource = new DataSource({
> >   type: "postgres",
> >   url: "postgres://postgres:postgres@localhost:5432/medusa",
> >   synchronize: false,
> >   entities: [
> >     "dist/models/*.js",
> >     'node_modules/@medusajs/medusa/dist/models/!(*.index.js)',
> >   ],
> >   migrations: [
> >     "dist/migrations/*.js",
> >     'node_modules/@medusajs/medusa/dist/migrations/*.js',
> >   ],
> > })
> > 
> > module.exports = {
> >   datasource: AppDataSource,
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thanks to Juan Z on Discord for the fix.
> 
> Maybe this should be in the example provided in the docs?



> In my case this didn't solve the issue as it generated a huge migrations file and didn't just add the new column I extended...

**Comment by darrylmorley** [comment]
@chanhhanh Yes seeing this too. So as this is closed, is there a better way?

**Comment by tunchunairarko** [comment]
In my case I forgot to put @Entity decorator and the issue was fixed

**Comment by lucasfontesgaspareto** [comment]
guys, tired of correcting migration scripts I decided to make a very difficult decision and after 15 minutes bringing against chatgpt prompts, I did it!

I asked chatgpt to create a script that takes a file where there are queries to be removed from another file.

in the scenario we currently have we can do it like this:

1. in datasource.json, comment out the import of the files from the project you work on, generate a migration with only the source code files

```typescript
const { DataSource } = require('typeorm')

require('@medusajs/medusa/dist/models')

const AppDataSource = new DataSource({
  type: 'postgres',
  port: 5432,
  username: 'postgres',
  password: 'admin',
  database: 'medusa-rbjV',
  synchronize: false,
  entities: [
    // 'dist/models/*.js',
    'node_modules/@medusajs/medusa/dist/models/!(*.index.js)'
  ],
  migrations: [
    // 'dist/migrations/*.js',
    'node_modules/@medusajs/medusa/dist/migrations/*.js'
  ]
})

module.exports = {
  datasource: AppDataSource
}
```

take all the queries generated in this migration and create a `queries-to-remove.txt` file

after that you can return the `datasource.json` file to its name and generate a new migration that will contain the queries from your project and the source code.

create a file called `filter_queries.sh`

```bash
#!/bin/bash

# Verificar se os argumentos foram fornecidos
if [ "$#" -ne 3 ]; then
    echo "Uso: $0 <arquivo-alvo> <arquivo-para-remover> <arquivo-de-saida>"
    exit 1
fi

# Arquivos de entrada
TARGET_FILE=$1
REMOVE_FILE=$2
OUTPUT_FILE=$3

# Criar um arquivo temporário para armazenar o resultado
cp "$TARGET_FILE" "$OUTPUT_FILE"

# Iterar sobre cada linha do arquivo REMOVE_FILE
while IFS= read -r line_to_remove; do
  # Escapar caracteres especiais para grep
  escaped_line=$(echo "$line_to_remove" | sed 's/[\/&]/\\&/g')
  # Usar sed para remover linhas que correspondem à linha atual a ser removida
  sed -i "/$escaped_line/d" "$OUTPUT_FILE"
done < "$REMOVE_FILE"

echo "Novo arquivo gerado: $OUTPUT_FILE"
```

run example: ```./filter_queries.sh 1717187216275-UpdateProductRelation.ts to-remove.txt filtered_UpdateProductRelation.ts```


ENJOY 🔥
