### ISSUE TITLE
Error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string

### ISSUE THREAD

**Issue by joshholly** [medusajs/medusa#4280]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

When I try to run the backend I get the error:

Error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by pevey** [comment]
Someone recently had this issue, and it turned out their Postgres password had special characters, and that was causing an issue with the connection string.  If your password has special characters, could you try changing that?  Also, please post the format of your postgres url.

**Comment by shahednasser** [comment]
Hi @joshholly please refer to [this troubleshooting guide](https://docs.medusajs.com/troubleshooting/database-error) on this error. Will be closing the issue for now. Let me know if it doesn't work out.

**Comment by ivanushkaPr** [comment]
> Hi @joshholly please refer to [this troubleshooting guide](https://docs.medusajs.com/troubleshooting/database-error) on this error. Will be closing the issue for now. Let me know if it doesn't work out.

That doesnt helped me. After clonin repo, install necessary files via yarn install, building it and adding meduca-cli, i cannot connect  to database.

Furthermore i added necessarty enviroment variables to .end file, to bashrs, and even to windows as global variables and user variables.

But in the end im getting the message - SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string,
and the logged password value is null.

So i need some help or maybe, i should create a bug ticket.

**Comment by shahednasser** [comment]
Hi @ivanushkaPr 

You mentioned "cloning the repo". Which repo do you mean exactly? Did you try installing with `create-medusa-app` as explained in [this guide](https://docs.medusajs.com/create-medusa-app)?

Can you give more details about your setup? i.e. your OS, Node version, any tools you're using, etc...

Also, is your database a local database, remote, or using a Docker container?

Finally, can you share the content of your `.env` file (omitting any sensitive data such as passwords).

**Comment by JustAndrew-pixel** [comment]
Hi @shahednasser

I've got apparently the same problem as @ivanushkaPr. At first a new project was created via `create-medusa-app` following the guide. After the first setup the project has been pushed into a separate repository for other team members to "clone" the project. Maybe @ivanushkaPr means exactly that under "after clonin repo".

 After `yarn install` I've tried to execute `npx medusa migrations run` or `npx @medusajs/medusa-cli@latest seed -f ./data/seed.json`, but have ` SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string`.
 
 It looks like backend doesn't have credentials to connect to the PostgresSql to execute following command, if the project was cloned and not created usual way.

**Comment by shahednasser** [comment]
@JustAndrew-pixel thanks for providing details. From what i understand, the database URL is then not set in an environment variable or in a `.env` file, which means it's not passed to the Medusa configurations. You can then set the `DATABASE_URL` to your database connection, which will automatically pass the URL to the Medusa configurations. Learn more [here](https://docs.medusajs.com/development/backend/configurations#database_url)

**Comment by JustAndrew-pixel** [comment]
@shahednasser thanks for your fast answer!

After definition `.env` file I don't recieve `SASL: SCRAM-SERVER-FIRST-MESSAGE` error anymore.

But with following database url `DATABASE_URL=postgres://postgres:mypassword@localhost/medusa` and a new created `medusa` database in PostgresSQL have a problem `Error: The specified PostgreSQL database does not exist. Please create it and try again.
database "medusa" does not exist`.

But if I try to connect e.g. to `template0` db, it requests to execute migration what means it work. Do you have any suggestions?

**Comment by shahednasser** [comment]
You must create a new database (for example `medusa`), then run the following command in the Medusa backend to run migrations (reflecting tables in the database you created):

```bash
npx medusa migrations run
```

You can also use the seed command to add demo data to the database:

```bash
npm run seed
# or
yarn seed
```

If you seed the data, you can login to your admin with the email `admin@medusa-test.com` and password `supersecret`. Alternatively, you can create a user with the [user command](https://docs.medusajs.com/cli/reference#user)

This should be enough info to get your Medusa backend up and running. If you have any other problems, feel free to look through the docs or refer to our [discord server](https://discord.gg/medusajs) for help!

**Comment by adoel90** [comment]
I faced this problem when try to make my own plugin, while trying `npx medusa plugin:db:generate` get exactly this error message "Error: SASL: SCRAM-SERVER blablabla". A few moment later....

Finally can generate the "migration folder" due to put .env file as well (before, i tought for creating pluggin doesn't need to put the .env file, actually we also should create .env file) :

```
DB_USERNAME=postgres
DB_PASSWORD=D0N'TBEANG
DB_HOST=localhost
DB_PORT=5432
DB_NAME=financev1
```


Thanks Medusa Team :)
