### ISSUE TITLE
Blog post is outdated

### ISSUE THREAD

**Issue by kleenkanteen** [medusajs/medusa#4281]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In this blog article: [https://medusajs.com/blog/beginner-guide-to-node-js-ecommerce-platform-understanding-the-medusa-server/](https://medusajs.com/blog/beginner-guide-to-node-js-ecommerce-platform-understanding-the-medusa-server/) it says "the admin dashboard runs on port 7000 or 7001".

In the part where it says "To dive deeper into endpoints in Medusa, check out the documentation on how to add endpoints for [Admin](https://docs.medusajs.com/advanced/backend/endpoints/add-admin/) and for [Storefront](https://docs.medusajs.com/advanced/backend/endpoints/add-storefront).", the 2 links are outdated. I wanted to see them.

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for pointing this out! We're aware that many old blog posts are outdated, considering it's difficult to fix them when new changes occur. Make sure to always rely on the documentation for updated information.
