### ISSUE TITLE
Postgres example url incorrect

### ISSUE THREAD

**Issue by kleenkanteen** [medusajs/medusa#4282]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Here: [https://docs.medusajs.com/development/backend/configurations#postgresql-configurations](https://docs.medusajs.com/development/backend/configurations#postgresql-configurations), it says "For example, the connection URL can be postgres://postgres@localhost/medusa-store". The example URL does not have the password or port inside it.

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for opening this issue! This isn't incorrect, as you can connect to Postgres without a password if your installation/user supports it. As for the port, if it's not supplied then the default port `5432` is used.
