### ISSUE TITLE
Upload image not working

### ISSUE THREAD

**Issue by Norbeboy1** [medusajs/medusa#4306]
### Describe the bug

I am creating a new product and i am uploading an image and then i am publishing the product.
I created a file service with azure and the plugin is working fine, i can actually see the image uploaded in my azure blob storage.
But when i click on the Publish product, the site is not doing anything, nothing is happening in the frontend, i can see the api calls from the logs and i don't get any errors.
What did i miss?

### System information

Medusa version (including plugins):
Node.js version: 19
Database: postgres
Operating system: windows
Browser (if relevant):

### Steps to reproduce the behavior

1. Create a new product from medusa backend
2. Upload an image
3. Click on Publish product

### Expected behavior

The product is created and it is redirecting me to the products page

### Additional context

**Comment by tsvetann** [comment]
@Norbeboy1 is the issue you are describing that the images do not load on the storefront? What stack are you using for FE?

**Comment by Norbeboy1** [comment]
Nevermind, i resolved the issue ... it was because i didn't provide the url to medusa ... now it works
