### ISSUE TITLE
having error while running the backend

### ISSUE THREAD

**Issue by pratham-yuxo** [medusajs/medusa#4312]
## Bug report
1. First I cloned the repo nextjs-starter-medusa https://github.com/medusajs/nextjs-starter-medusa, frontend was working fine but it was giving me error because there was no backend running.
2. For backend, I refer to this guide https://docs.medusajs.com/create-medusa-app , when i was running yarn start , then I got this error  
` Error starting server
Error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string`
this is my .env.local file 

`JWT_SECRET=something`
`COOKIE_SECRET=something`
`DATABASE_TYPE=postgres`
`DATABASE_URL=postgres://localhost/medusa-store`
`REDIS_URL=redis://localhost:6379`
`DB_HOST="127.0.0.1"`
`DB_USERNAME=medusa-store`
`DB_PASSWORD="my password" `

Node.js version: 16.14.2
Database: postgresql
Operating system: windows

Can you help me out ?
What am I doing wrong here?

**Comment by pevey** [comment]
Your DATABASE_URL is incomplete, which is causing the error.  This link might help: https://stackoverflow.com/questions/3582552/what-is-the-format-for-the-postgresql-connection-string-url

**Comment by shahednasser** [comment]
Hi @pratham-yuxo , make sure your `DATABASE_URL` matches the format `postgres://[user][:password]@[host][:port]/[dbname]` you can learn more about it [here](https://docs.medusajs.com/development/backend/configurations#postgresql-configurations)

**Comment by pratham-yuxo** [comment]
Actually I changed my format and it worked but i have to put my url directly into the medusa.config.js file , somehow it's not taking the value present in .env.template . I tried changing it to .env.local but it didn't worked, What I have to do to solve this?
`JWT_SECRET=something`
`COOKIE_SECRET=something`
`DATABASE_TYPE=postgres`
`DATABASE_URL=postgres://pratham:mypassword@localhost:5432/medusa-store`
`REDIS_URL=redis://localhost:6379`
`DB_HOST="127.0.0.1"`
`DB_USERNAME=pratham`
`DB_PASSWORD=mypassword`

I made a new user and tried to do this but it didn't work

**Comment by shahednasser** [comment]
The file name should be `.env`

**Comment by pratham-yuxo** [comment]
> The file name should be `.env`

yeah,thank you it worked.
but while running `npx @medusajs/medusa-cli@latest migrations run` it is giving me this error
`error: error: permission denied for schema public`
What can be the reason?

**Comment by shahednasser** [comment]
This is a postgres error and is likely related to your postgres user permissions. You can find some help [here](https://stackoverflow.com/questions/67276391/why-am-i-getting-a-permission-denied-error-for-schema-public-on-pgadmin-4)

**Comment by pevey** [comment]
Are you using Supabase as your postgres db by chance?  If so, see this thread: https://github.com/medusajs/medusa/discussions/4100

**Comment by pratham-yuxo** [comment]
> This is a postgres error and is likely related to your postgres user permissions. You can find some help [here](https://stackoverflow.com/questions/67276391/why-am-i-getting-a-permission-denied-error-for-schema-public-on-pgadmin-4)

I made my user the super user and it worked, thanks a lot.
Actually, Now I am getting a CORS error.
What can be the issue?

**Comment by shahednasser** [comment]
You can find troubleshooting guide for CORS [here](https://docs.medusajs.com/troubleshooting/cors-issues)

**Comment by pratham-yuxo** [comment]
I have same setting as in the docs , frontend is running on port 8000 and backend on port 9000. But still I'm getting the CORS error while doing  `yarn dev` in frontend.

**Comment by pevey** [comment]
@pratham-yuxo ,

Would you mind joining the Discord?  There is a Help section there where you could post a thread for assistance.  If you post your full medusa-config.js there and pics of the exact errors you are getting, someone might be able to help you.

https://discord.gg/medusajs

This issues section on GitHub is more for reproducible issues (with all specifics on how to reproduce) that definitely need developer attention.

**Comment by pratham-yuxo** [comment]
okay, thanks. I'll join.
