### ISSUE TITLE
Small improvements to create-medusa-app documentation

### ISSUE THREAD

**Issue by moltenform** [medusajs/medusa#4313]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I got my medusa app up and running without too much trouble, but I thought I'd recommend some changes on the create medusa app instructions to make it quicker for others. See the below section for what I recommend changing/fixing.

### How can this issue be resolved?

For the page https://docs.medusajs.com/create-medusa-app
I suggest the following changes/fixes:

1)
```
in "step 5", instead of 
DATABASE_URL=<YOUR_DATABASE_URL>
I suggest writing
create a database named medusastore and use the string
DATABASE_URL=postgres://[user][:password]@[host][:port]/medusastore

that way I don't have to look through the other document to figure out what to do.
```

(note also that the docs say medusa-store, but my postgres doesn't like the hyphen in the database name, I had better results with medusastore)

2)
```
clarify that running 
npx @medusajs/medusa-cli@latest migrations run
and
npx @medusajs/medusa-cli@latest seed -f ./data/seed.json
should be done from the backend directory.
```

3)
```
move the excerpt in "step 4" to the end of the document.
Step 4 has a part that says
"Your project is ready. The available commands are:

Medusa API
cd my-medusa-store/backend
yarn start

Storefront
cd my-medusa-store/storefront
yarn dev"
The console does show the message at this point. But the docs should say
not to run the backend until later, when the database hasn't been set up yet.
So I recommend moving this to the end of the doc.
```

(PS: Thanks for including pnpm alongside npm and yarn. And thank you for building medusa!)

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by pevey** [comment]
This is very helpful feedback.

**Comment by shahednasser** [comment]
Thanks for the feedback @moltenform ! We're actually launching soon a new and improved experience for `create-medusa-app` including improved documentation. Stay tuned!
