### ISSUE TITLE
Custom files (service,model,etc) not loaded in first load of `dev` command and not loaded at all when using `start` command

### ISSUE THREAD

**Issue by zulianrizki** [medusajs/medusa#4324]
### Describe the bug
The `develop` command in Medusa v1.12.0 is behaving unexpectedly. When it is initially run, Babel only compiles 0 files, displaying the message "Successfully compiled 0 files with Babel (4ms)". However, after making changes to a file and saving it, the recompile process works as expected. For instance, Babel shows "Successfully compiled 1 file with Babel (251ms)" after modifying a `test.ts` file.

Moreover, custom files do not seem to be loaded when using the `start` command.

### System information

Medusa: 1.12.0
Node.js version: 18.16
Database: Postgres
Operating system: Ubuntu via WSL

### Steps to reproduce the behavior

1. Create a new project.
2. Create a new service in `src/services/test.ts`.
3. Run the `dev` command.
4. Observe that Babel shows "Successfully compiled 0 files with Babel (4ms)".
5. Make a small change to the `test.ts` file and save it.
6. Observe that Babel shows "Successfully compiled 1 file with Babel (251ms)".

### Expected behavior

Babel should compile all files during the initial run.

### Additional context

Upon inspecting the source code, a potential inconsistency was noticed in how Babel is invoked. The relevant sections from `packages/medusa/src/commands/develop.js` are as follows:
when initializing
```
 44 execSync(`"${babelPath}" src -d dist`, {
 45   cwd: directory,
 46   stdio: ["ignore", process.stdout, process.stderr],
 47 })
```
And when rebuilding on file changes,
```
75 execSync(`${babelPath} src -d dist --extensions ".ts,.js"`, {
76    cwd: directory,
77    stdio: ["pipe", process.stdout, process.stderr],
78  })
```

quoted from https://babeljs.io/docs/babel-preset-typescript
```
You will need to specify --extensions ".ts" for @babel/cli & @babel/node cli's to handle .ts files.
```

Maybe that the flag --extensions ".ts,.js" should also be added to the initialization code.

**Comment by tsvetann** [comment]
Can you elaborate more on what you mean by custom files? Are you developing your custom plugin or just adding files in the /src folder?

**Comment by zulianrizki** [comment]
> Can you elaborate more on what you mean by custom files? Are you developing your custom plugin or just adding files in the /src folder?

just adding files in the `/src` folder such as `src/models/custom_model.ts` or `src/service/custom_service.ts`

**Comment by pevey** [comment]
This has been fixed for newly created Medusa projects, but if you are working in an older project folder, you have to apply the fix yourself. 

https://discord.com/channels/876835651130097704/1104313178755711026/1112875861071384576

Edit your tsconfig file:

```
"esModuleInterop": false,
```

Change this to true.

**Comment by zulianrizki** [comment]
> This has been fixed for newly created Medusa projects, but if you are working in an older project folder, you have to apply the fix yourself.
> 
> https://discord.com/channels/876835651130097704/1104313178755711026/1112875861071384576
> 
> Edit your tsconfig file:
> 
> ```
> "esModuleInterop": false,
> ```
> 
> Change this to true.

got it.
It works now, thanks
