### ISSUE TITLE
Several "Cannot find module" after installing the medusa package

### ISSUE THREAD

**Issue by TrisMarzec** [medusajs/medusa#4329]
### Describe the bug

While creating a custom storefront with angular some errors are coming up while starting. He is unable to find specific modules in the given directory. That's because it's initially wrong. After changing it hard to the right one plenty more Errors are occurring for different modules. I don't know if this is version specific or why it cannot find all this stuff.
Reinstaling the packages doesn't work either.

### System information

Medusa version (including plugins): "@medusajs/medusa-js": "^6.0.0", "@medusajs/types": "^1.8.7"
Node.js version: v.20.3.0
Operating system: MacOS

### Steps to reproduce the behavior

`yarn add @medusajs/medusa-js`

`yarn add @medusajs/types`

`yarn start`

### Occurred Errors

`Error: node_modules/@medusajs/medusa-js/dist/index.d.ts:3:28 - error TS2307: Cannot find module '@medusajs/medusa/dist/types/common' or its corresponding type declarations.
`

![BF6CBD6A-7342-495B-9E18-9BB91BB14E2E](https://github.com/medusajs/medusa/assets/110892700/a0d992c8-3daa-4daf-a925-d82f879af1d6)

**Comment by pevey** [comment]
As far as I know, Medusa (and most packages it relies on) are not yet compatible with node v20.  It may be quite some time before they are because of the new permissions api.

**Comment by alainpaulinn** [comment]
I have the same issue

**Comment by hampusboas** [comment]
Any plans on fixing this?

**Comment by medAzizRezgui** [comment]
same, here. any luck with it?

**Comment by hampusboas** [comment]
> same, here. any luck with it?

No, i am currently writing my own TS implementation for Angular.

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏

**Comment by abhishek-clima** [comment]
any luck?
