### ISSUE TITLE
Email provider for development

### ISSUE THREAD

**Issue by srindom** [medusajs/medusa#433]
Right now you must install a notification plugin such as `medusa-plugin-sendgrid` in order to send transactional emails. It would be nice to have a no-prereqs solution that can be used for dev purposes. Maybe the [sendemail](https://www.npmjs.com/package/sendmail) can be used.

For implementation details check [`medusa-plugin-sendgrid`](https://github.com/medusajs/medusa/tree/master/packages/medusa-plugin-sendgrid).

**Comment by princefishthrower** [comment]
@srindom - something like `sendmail` will still have to be added to medusa's `package.json` as a dev dependency right? If that's the case, I could potentially try this one too! Then we'll need a way of knowing if the system is in development mode... I'm sure that's possible in medusa too.

**Comment by srindom** [comment]
@princefishthrower cool thanks! I should probably specify a bit further here. My idea was actually to have a new plugin created which uses `sendemail` for dispatching messages instead of a 3rd party solution like Sendgrid, AWS SES, Mailgun, etc. 

Usage of the plugin should be something like this:

`yarn add medusa-plugin-sendemail`

```javascript
// medusa-config.js

module.exports = {
  ...,
  plugins: [
    `medusa-plugin-sendemail`,
    ...
  ]
}
```

The plugin would then listen for events like `order.placed` which would trigger a dispatch of a transactional email. Similarly to the way [`medusa-plugin-sendgrid`](https://github.com/medusajs/medusa/tree/master/packages/medusa-plugin-sendgrid) works.

Does this make sense? :D

**Comment by princefishthrower** [comment]
@srindom - so this would become a new folder under `packages` in this repo, correct? I have some experience with template engines, I guess I'll look in `medusa-plugin-sendemail` and see what templates exist.

**Comment by chtnnh** [comment]
@srindom @olivermrbl is it absolutely essential to use the package mentioned? Could I add a dependency like [this](https://www.npmjs.com/package/email-templates) ?

**Comment by olivermrbl** [comment]
Hey @chtnnh ! We don't have any set and stone requirements for the plugin, so feel free to choose whatever you find most useful :)
