### ISSUE TITLE
Migrations on fresh install do not work

### ISSUE THREAD

**Issue by Niblu** [medusajs/medusa#4340]
### Describe the bug

On creating a fresh medusa install with medusa new [name], 

When trying to run migrations with npx @medusajs/medusa-cli@latest migrations run (or medusa migrations run), it returns the following error:

```
NIblu-iMac:backend2 Niblu$ medusa migrations run
[medusa-config] ⚠️ redis_url not found. A fake redis instance will be used.
[medusa-config] ⚠️ redis_url not found. A fake redis instance will be used.
query: SELECT * FROM current_schema()
query: SELECT version();
query: select * from migrations
query failed: select * from migrations
error: error: relation "migrations" does not exist
Error: Migrations missing. Please run 'medusa migrations run' and try again.
```

I cannot set up the database for medusa at all... 

### System information

Medusa version (including plugins): 
    "@medusajs/admin": "^6.0.0",
    "@medusajs/cache-inmemory": "^1.8.7",
    "@medusajs/cache-redis": "^1.8.7",
    "@medusajs/event-bus-local": "^1.9.4",
    "@medusajs/event-bus-redis": "^1.8.7",
    "@medusajs/file-local": "^1.0.1",
    "@medusajs/medusa": "^1.12.0",
Node.js version: 20-0
Database: postgresql
Operating system: mac OS ventura 13.4
Browser (if relevant): /

### Steps to reproduce the behavior

1. Install medusa with medusa new [name]
2. skip the database setup
3. connect your own db in .env
4. medusa migrations run

### Expected behavior

Migrations fill the connected database with required tables for medusa to work.

### Additional context

I am sure I have the connection right, I manage to create a migrations table if I seed, but then hangs. I tried every step, different databases (hosted, local etc), reinstall node modules with yarn and npm... nothing works. If I connect to local DB at install instead of skipping, it creates the database and says migrations complete, but the database is empty.

Will attempt to setup database "backend2" with credentials:
  user: Niblu
  password: ***
  database: postgres
  port: 5432
  host: localhost
Do you wish to continue with these credentials?

           Continue
✔ Created database "backend2" – 191ms
✔ Database migrations completed. – 13199ms
info:    Your new Medusa project is ready for you! To start developing run:

after this, backend2 db is created and is empty. Migrations run return the same error from above.

It looks to me as if the migrate command cannot find initial migrations or doesn't know it's initial migrations time... 

This worked flawlessly in the past, so I have no idea what changed. Can someone please tell me if this is happening to me only?

**Comment by hfzi** [comment]
Have you tried another version? I get the same error. postgresql 15 installed

**Comment by nparoski** [comment]
any progress @Niblu @olivermrbl

**Comment by teddybee** [comment]
I ran into issue as well.

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
