### ISSUE TITLE
carts and navigating to the product kinda slowely

### ISSUE THREAD

**Issue by Adamkaram** [medusajs/medusa#4342]
hi everyone thanx for this amazing project 

## it's my first time to deal with medusajs and i love it but in order to summerize the issues i had faced 

first : dealing with navigation to specifec produect take than 2 / 3  seconde to complete it's kinda bugy 
look at this image and u will find multiable request i don't know why they occur in first place 
![Screenshot 2023-06-18 115002](https://github.com/medusajs/medusa/assets/52092726/cce80d95-707e-4e56-b2a5-f4cd915d1101)
4 GET request to navigating to item? why 

sec : shoping bag or cart doesn't work as it should be even if i tried 10 times 
![Screenshot 2023-06-18 115752](https://github.com/medusajs/medusa/assets/52092726/9e98acde-7608-4c61-a6ab-9d314cf76f5d)

also why there's too muchHTTP 409 Conflict response 
![Screenshot 2023-06-18 115849](https://github.com/medusajs/medusa/assets/52092726/27e66efa-f607-4d92-8ea4-9bba32551cc3)

### System information

Medusa version (last version):
Node.js version: last version
Database: railway postgres 
Operating system: windows 10 
Browser (if relevant): chrome last version

**Comment by olivermrbl** [comment]
AFAICT, this is not an issue, so I will close this for now.
