### ISSUE TITLE
Add Claim Reasons

### ISSUE THREAD

**Issue by srindom** [medusajs/medusa#435]
On returns we have support for creating dynamic Return Reasons that can be nested. We would like a similar way of handling Claim Reasons.

We already have a notion of Claim Reasons in the core but [these are currently defined through an enum](https://github.com/medusajs/medusa/blob/master/packages/medusa/src/models/claim-item.ts).

**Comment by princefishthrower** [comment]
@srindom - I'd be willing to take this on. Can I also get a link to the code where those dynamic Return Reasons are?

**Comment by srindom** [comment]
@princefishthrower so cool thanks!

You can check the service implementation here: https://github.com/medusajs/medusa/blob/master/packages/medusa/src/services/return-reason.js

The API layer is implemented here: https://github.com/medusajs/medusa/tree/master/packages/medusa/src/api/routes/admin/return-reasons

Will be happy to assist if you have any questions :)

**Comment by princefishthrower** [comment]
@srindom - just made a pull request for this: https://github.com/medusajs/medusa/pull/451

One question I have - how or where can I test for these new changes? I see there is an automatic CI / CD, so I guess I'll have to add something somewhere - let me know!

One other question, why is the API layer written in plain JavaScript with `.js` files while the rest of the repository is in TypeScript? 😄  Might be 'fun' to convert the API layer to TypeScript as well. 😂

**Comment by srindom** [comment]
Closing as stale
