### ISSUE TITLE
Expand parameter not supported properly in products.retrieve() method in JS Client

### ISSUE THREAD

**Issue by rasmuslian** [medusajs/medusa#4350]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Hi,
The documentation for the products.retrieve() method in the JS client is incorrect, since the expand query parameter is documented to work but in fact is not supported in the JS client library.

The docs are at this link:
https://docs.medusajs.com/api/store#tag/Products/operation/GetProductsProduct

See image below also:
![image](https://github.com/medusajs/medusa/assets/36270308/5f468fc5-12d6-43a9-ab49-1dbab10594ff)

Maybe this can be implemented in the JS client? Or at least change the docs.

Thanks!

### How can this issue be resolved?

1. Implement the expand query param in the JS client

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Closing this issue as the new API reference adds a note about the expand property's availability in endpoints.

**Comment by haiderchristoph** [comment]
@shahednasser could you please provide a link to that note? I can't find anything about it and the original issue seems to still be there. Cannot pass query params to `products.retrieve()`.

**Comment by shahednasser** [comment]
Hello @haiderchristoph , the `retrieve` method is missing the capability to pass query parameters. However, you can use `fetch` or `axios` to send a request and pass query parameters instead.
