### ISSUE TITLE
How to make a provider without a new plugin

### ISSUE THREAD

**Issue by Norbeboy1** [medusajs/medusa#4353]
## Bug report

As now, i already have a fulfillment plugin working with medusa:
- i made a plugin
- published it to npm registry
- than import it to medusa
And everything works, but it's a bit time consuming to always publish the plugin for every change, even in development phase.

Is there an easier way to do it? Like extending the classes directly from the project? so no plugins, I tried it but is not working.

I tried now to make a tax provider, and it is working directly from medusa backend.

But it didn't worked with the file storage and with the fulfillment ... i needed to do a plugin

### System information

Medusa version (including plugins):
Node.js version:
Database:
Operating system:
Browser (if relevant):

**Comment by olivermrbl** [comment]
Missing context. Happen to open again, if provided.

**Comment by Norbeboy1** [comment]
sorry, the description was put inside comment lines

**Comment by olivermrbl** [comment]
Yes, you should be able to build your "plugins" directly in your project. 

Are you seeing any errors when trying to do this for file storage and fulfillment? Or do they not get registered?
