### ISSUE TITLE
Docs(Code Issue): Code Issue in /create-medusa-app

### ISSUE THREAD

**Issue by habibullahturkmen** [medusajs/medusa#4357]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

![image](https://github.com/medusajs/medusa/assets/11511274/6b98a28a-eb16-4ba0-9553-6bea3893255c)

Replace `yarn create medusa-app@latest` with `yarn create medusa-app`

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch! Will resolve this 👍🏻
