### ISSUE TITLE
medusa-plugin-algolia

### ISSUE THREAD

**Issue by olivermrbl** [medusajs/medusa#436]
We would like to add a search plugin for Algolia. See [MeiliSearch here](https://github.com/medusajs/medusa/tree/feat/meilisearch-plugin/packages/medusa-plugin-meilisearch) for inspiration.

**Comment by rolwin100** [comment]
@olivermrbl I will take this up

**Comment by srindom** [comment]
@rolwin100: @zakariaelas is your man if you have questions, he did the Meilisearch plugin :)

**Comment by zakariaelas** [comment]
@rolwin100 really cool! Feel free to ping me if anything pops up!

**Comment by rolwin100** [comment]
yo @zakariaelas sure

**Comment by zakariaelas** [comment]
@rolwin100 hello! of course, let's take it to discord :)

**Comment by olivermrbl** [comment]
Closed #718
