### ISSUE TITLE
Duplicate product scrambles the variant option values

### ISSUE THREAD

**Issue by viicslen** [medusajs/medusa#4360]
### Describe the bug

When duplicating a product with multiple variants and variants options, it scrambles the variant option values for the duplicate product. 

### System information

Medusa version (including plugins): v1.12.1
Node.js version: 19
Database: Postgres
Operating system: Linux
Browser (if relevant): Microsoft Edge

### Steps to reproduce the behavior

1. Go to 'Products'
2. Create a product with multiple variants and variant options
3. Click on the product's menu (...)
4. Click on "Duplicate"
5. Check variants

### Expected behavior

A clear and concise description of what you expected to happen

#### Original
![image](https://github.com/medusajs/medusa/assets/39545521/21f69cb9-657c-458c-a525-8ebbaa9a2f84)

#### Duplicate
![image](https://github.com/medusajs/medusa/assets/39545521/766f736d-b1c1-4ac2-8ee6-7f28b897d82c)

**Comment by kasperkristensen** [comment]
Hi @viicslen, could you please include the version of `@medusajs/admin` you are using? We fixed a similar issue 3 weeks ago, so just want to make sure that you are using the latest admin version.

**Comment by viicslen** [comment]
I was using an old version of the admin (3.0.0). However I updated `@medusajs/admin` to v6.0.1 and tried again but the same thing happened

Here's my dep list now
```json
{
    "@medusajs/admin": "^6.0.1",
    "@medusajs/cache-redis": "1.8.8",
    "@medusajs/event-bus-local": "1.9.5",
    "@medusajs/event-bus-redis": "1.8.8",
    "@medusajs/medusa": "1.12.1",
    "@medusajs/medusa-cli": "^1.3.16",
    "dotenv": "^16.3.1",
    "medusa-extender": "^1.8.8",
    "medusa-file-local": "^2.0.9",
    "medusa-file-minio": "^1.2.1",
    "medusa-file-s3": "^1.2.1",
    "medusa-fulfillment-manual": "^1.1.38",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.24",
    "medusa-payment-stripe": "^6.0.1",
    "medusa-plugin-filestorage-local": "^0.1.2",
    "medusa-plugin-meilisearch": "^2.0.7",
    "medusa-plugin-sendgrid": "^1.3.9",
    "medusa-plugin-strapi": "^1.0.8-dev",
    "typeorm": "^0.3.16"
}
```

**Comment by kasperkristensen** [comment]
@viicslen Did you rebuild the admin, using `medusa-admin build`, after updating the version? I can't reproduce your issue, using a fresh build with the latest admin version.

**Comment by viicslen** [comment]
Ahh sorry about that, forgot to rebuild the admin. It's working as expected now.

**Comment by kasperkristensen** [comment]
@viicslen Great to hear!
