### ISSUE TITLE
Meili plugin not working due to version mismatch

### ISSUE THREAD

**Issue by ripvannwinkler** [medusajs/medusa#4366]
## Bug report

Upgraded medusa to 1.12.1 w/ @medusajs/utils@1.9.1 and the medusa-plugin-meilisearch plugin stopped working. 

### Describe the bug

It appears that even though the package.json in the repo for the plugin refers to 1.9.1 of the utils package, the published package still refers to 1.9.0.

See: https://www.npmjs.com/package/medusa-plugin-meilisearch/v/2.0.7?activeTab=code

Running `yarn why @medusajs/utils` on my machine shows the problem (near the bottom).
```
 chris@DESKTOP-03T9E4R D:\....\backend  main  yarn why @medusajs/utils             
├─ @medusajs/event-bus-local@npm:1.9.5
│  └─ @medusajs/utils@npm:1.9.1 (via npm:^1.9.1)
│
├─ @medusajs/event-bus-redis@npm:1.8.8
│  └─ @medusajs/utils@npm:1.9.1 (via npm:^1.9.1)
│
├─ @medusajs/medusa-cli@npm:1.3.16
│  └─ @medusajs/utils@npm:1.9.1 (via npm:^1.9.1)
├─ @medusajs/medusa@patch:@medusajs/medusa@npm%3A1.12.1#./.yarn/patches/@medusajs-medusa-npm-1.12.1-eb4747f43e.patch::version=1.12.1&hash=381aed&locator=root-workspace-0b6124%40workspace%3A. [46758]
│  └─ @medusajs/utils@npm:1.9.1 (via npm:^1.9.1)
│
├─ @medusajs/medusa@patch:@medusajs/medusa@npm%3A1.12.1#./.yarn/patches/@medusajs-medusa-npm-1.12.1-eb4747f43e.patch::version=1.12.1&hash=381aed&locator=root-workspace-0b6124%40workspace%3A. [73ed8]
│  └─ @medusajs/utils@npm:1.9.1 (via npm:^1.9.1)
│
├─ @medusajs/modules-sdk@npm:1.8.8
│  └─ @medusajs/utils@npm:1.9.1 (via npm:^1.9.1)
│
└─ medusa-plugin-meilisearch@npm:2.0.7
   └─ @medusajs/utils@npm:1.9.0 (via npm:1.9.0)
```
### Steps to reproduce the behavior

1. Upgrade medusa packages to 1.12.1
2. Run the storefront and try to search products
3. Receive a backend log message stating `warn: This is an empty method: search must be overridden a the child class`

### Expected behavior

The search plugin should load the correct utils version and work as normal.

**Comment by olivermrbl** [comment]
Sorry fo the inconvenience. Can I get you to try to install the latest version of the Meilisearch plugin?

**Comment by ripvannwinkler** [comment]
Yes this fixes the issue.
