### ISSUE TITLE
Bug: Admin UI Routes broken in Beta

### ISSUE THREAD

**Issue by Bhuvi100** [medusajs/medusa#4372]
## Bug report
Adding new pages to using the Admin UI Routes is broken. I know Admin UI is still in Beta, just wanted to let it know and get fixed as soon as possible.

### Describe the bug
I exactly followed the steps in the documentation, added a new file src/admin/routes/custom/page.tsx. But when I ran the build command, it fails to build and throws an error that the route is invalid.

I have went through the code myself and I hope I located it. It is located at https://github.com/medusajs/medusa/blob/20fe560432e7c277fb43327c3ee47d491657c59c/packages/admin-ui/src/node/utils/validate-extensions.ts#L251 . The validation for the route path should be fixed and the file extension should be cleaned before passing to the validation method. Also, the extension should be removed on the route too.

### System information

Medusa version (including plugins): 1.12.1-beta-20230619170349
Medusa Admin: 7.0.0-beta-20230619170349
Medusa Admin UI: 2.0.0-beta-20230619170349

### Steps to reproduce the behavior

1. Follow steps mentioned in https://docs.medusajs.com/admin/routes
2. Run build command after add the custom page
3. See error

### Expected behavior

Should remove the file extensions and should build successfully and display the page.

### Screenshots

![image](https://github.com/medusajs/medusa/assets/81316368/93d8eac1-6e5b-4fa5-956a-5e9b7cb7a428)

**Comment by kasperkristensen** [comment]
Hi @Bhuvi100, thanks for reporting it I will get right on it. I think the issues stems from the validation failing on Windows paths, which I assume you are on judging by the path that is printed (can you confirm?), as it works fine for me (macOS).

**Comment by Bhuvi100** [comment]
> Hi @Bhuvi100, thanks for reporting it I will get right on it. I think the issues stems from the validation failing on Windows paths, which I assume you are on judging by the path that is printed (can you confirm?), as it works fine for me (macOS).

Hey @kasperkristensen,
Yes I'm on Windows but I'm not sure whether this is linked to any specific os since I feel the issue is with cleaning the file extension before processing it further. I don't use macOS, so I'm not sure how it returns the path, does macOS returns file path without the extension?

**Comment by kasperkristensen** [comment]
@Bhuvi100 Thanks for getting back so quickly. 

No macOS does not return the path without the file extensions, but I've used a regex before we get to this point, which removes the extension. But since that regex matches by `/page.[t|j]sx?` it fails on Windows because in that case, it would be `\page.tsx`. 

When we then get to the validate function the extension was never removed, and even if it had we would then fail on the validation only allowing the special characters `/` and `:`. It's a simple matter of normalizing the path earlier on in the process. I'll open a PR, and get one of my coworkers that have a Windows machine to test it in the morning :)

**Comment by Bhuvi100** [comment]
> @Bhuvi100 Thanks for getting back so quickly. 
> 
> No macOS does not return the path without the file extensions, but I've used a regex before we get to this point, which removes the extension. But since that regex matches by `/page.[t|j]sx?` it fails on Windows because in that case, it would be `\page.tsx`. 
> 
> When we then get to the validate function the extension was never removed, and even if it had we would then fail on the validation only allowing the special characters `/` and `:`. It's a simple matter of normalizing the path earlier on in the process. I'll open a PR, and get one of my coworkers that have a Windows machine to test it in the morning :) 

Cool understood, I didn't see the regex that does that, and yep thanks to you too for getting back quickly and finding the cause of the issue.

**Comment by kasperkristensen** [comment]
Fixed in latest versions of beta releases
