### ISSUE TITLE
create-medusa-app: Next storefront error 

### ISSUE THREAD

**Issue by kjcsb1** [medusajs/medusa#438]
After running create-medusa-app I get the following error when navigating to the Next storefront at http://localhost:8000/.

```
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'toLowerCase')

Source
utils/prices.js (24:64) @ eval

  22 | 
  23 |   let moneyAmount = variant.prices.find(
> 24 |     (p) => p.currency_code.toLowerCase() === cart.currency_code.toLowerCase()
     |                                                                ^
  25 |   );
  26 | 
  27 |   if (moneyAmount && moneyAmount.amount) {
```

The backend is running and the admin interface works fine.

**Comment by kasperkristensen** [comment]
Hi @kjcsb1 thanks for pointing out the error. It is due to the error which was also pointed out in [#9](https://github.com/medusajs/nextjs-starter-medusa/issues/9). I will be fixing it shortly so you can get up and running soon! 👍
