### ISSUE TITLE
Cannot change MEDUSA_BACKEND_URL

### ISSUE THREAD

**Issue by duongductrong** [medusajs/medusa#4391]
## Bug report
- Based on the document, we can change the backend_url (MEDUSA_BACKEND_URL) by following this way (https://docs.medusajs.com/admin/quickstart#build-command-options). 
- I will try to change the MEDUSA_BACKEND_URL value based on the document 
![CleanShot 2023-06-23 at 11 31 15](https://github.com/medusajs/medusa/assets/39333905/f4ec4a99-63f3-4182-8854-38dbb095a461)

**BECAUSE PORT 9000 IS ALREADY FOR ANOTHER PROCESS ON MY COMPUTER. SO I NEED TO CHANGE TO PORT 5000**

Now, let me set port 5000 for the backend server and set MEDUSA_BACKEND_URL = 5000 for the admin UI. 

Change package.json
```json
{
"scripts": {
    "clean": "cross-env ./node_modules/.bin/rimraf dist",
    "build": "cross-env npm run clean && npm run build:server && npm run build:admin",
    "build:server": "cross-env npm run clean && tsc -p tsconfig.server.json",
    "build:admin": "cross-env medusa-admin build --backend=localhost:5000", // "or --backend localhost:5000 still not working"
    "watch": "cross-env tsc --watch",
    "test": "cross-env jest",
    "seed": "cross-env medusa seed -f ./data/seed.json",
    "start": "cross-env npm run build && medusa start -p 5000",
    "start:custom": "cross-env npm run build && node --preserve-symlinks index.js",
    "dev": "cross-env npm run build:server && npm run build:admin && medusa develop -p 5000",
    "dev:admin": "medusa-admin dev"
  }
}

// use: yarn dev
```

Continue, I will run that script (yarn dev), open the localhost:7001 and expect it will change, but it also a call to http://localhost:9000
![CleanShot 2023-06-23 at 11 41 42](https://github.com/medusajs/medusa/assets/39333905/2d4e6661-ffef-452d-8dc6-013eb602d907)

Now, I'm checking it on the `.cache/admin/src/services/request.js` path and it will get the MEDUSA_BACKEND_URL from `.cache/admin/src/constants/medusa-backend-url.ts`. In this path, it defined the MEDUSA_BACKEND_URL as a constant variable, it looks like this:
```js
export const MEDUSA_BACKEND_URL = "http://localhost:9000"
```

### Describe the bug
I cannot change the MEDUSA_BACKEND_URL because it's a constant variable (always set MEDUSA_BACKEND_URL=localhost:9000) 

### System information

Medusa version (including plugins):
Node.js version: v18.15.0
Database: postgresql
Operating system: Macos Bigsur
Browser (if relevant): Chrome 114.0.5735.133 (Official Build) (arm64)

### Steps to reproduce the behavior

1. Setup package.json based on https://docs.medusajs.com/admin/quickstart#build-command-options 
2. Run the script `yarn dev` on package.json
3. Open localhost:7001
4. The network error, that always calls to http://localhost:9000, instead I was re-setup http://localhost:5000

### Expected behavior

Admin UI should call to my `-b` or `--backend` argument i was setup

### Screenshots

**See BUG_REPORT**

**Comment by kasperkristensen** [comment]
Hi @duongductrong, thanks for reporting the issue, it has been fixed and will be part of the next `beta` release of `@medusajs/admin`. Until the new beta version is released you can use these two snapshots:

```sh
yarn add @medusajs/admin@7.0.0-snapshot-20230623104058
```
```sh
yarn add @medusajs/medusa@1.12.2-snapshot-20230623104058
```

Using those snapshots, you can change your `dev` script to this:

```json
"scripts": {
  "dev": "cross-env npm run build:server && medusa develop -p 5000",
}
```

The Admin will pick up the port that you are running your Medusa server, and in your case, it will instead make requests to `http://localhost:5000`

Let me know if everything works out

**Comment by duongductrong** [comment]
Hi @kasperkristensen , 
Thanks for your reply to my issue. I tried and it worked. Medusa is an open source for e-commerce with great potential, I hope it has many other features in the future 💯

**Comment by Tech-Non** [comment]
Hey, I've got a similar issue. Even with the snapshot versions mentioned. When I run the build command
`"build:admin": "cross-env medusa-admin build --backend https://api.example.com"` and deploy the admin UI, any product images I upload still point to "localhost:9000". They get uploaded correctly to the backend, but their accompanying url when the entry is created points to localhost. When I manually change this URL to point to the backend URL, theyre correctly saved. It's just the metadata that is wrong when creating a product.

**Comment by olivermrbl** [comment]
@Tech-Non – to me, this sounds like an issue with your file plugin. Can I get you to ensure, you've installed a production-ready file plugin and not the `@medusajs/file-local`, which is meant for development only?

You can find a range of different provider guides in our documentation [here](https://docs.medusajs.com/plugins/file-service/spaces).

**Comment by apurv-dolphin** [comment]
how can i change my backed URL for both admin and front store in Medusa js. its by default target localhost 9000 and i want to target my IP. so my team member can also use this. i change my dev script in admin side. i am just started learn a Medusa js. any idea about how I can do this??
![how-can-i-change-my-backed-url-for-both-admin-and-front-v0-nvb7ndqcq0yc1](https://github.com/medusajs/medusa/assets/108326439/18ac3d06-11b3-41ac-a5d1-c5b1e8336b0f)

**Comment by shamun-khatri** [comment]
@apurv-dolphin I also want to change the user to IP.

**Comment by shamun-khatri** [comment]
@apurv-dolphin I think I found a way you can use  --host to assign custom host like IP

for example npx medusa start --host <Your IP>

**Comment by apurv-dolphin** [comment]
> @apurv-dolphin I think I found a way you can use --host to assign custom host like IP
> 
> for example npx medusa start --host

@shamun-khatri   npx medusa start --host
 Do you know if this command is working for you? its little bit confusing me.
