### ISSUE TITLE
Docs(Code Issue): Code Issue in /modules/taxes/backend/create-tax-provider

### ISSUE THREAD

**Issue by Fullstak-nl** [medusajs/medusa#4408]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

[Step 2](https://docs.medusajs.com/modules/taxes/backend/create-tax-provider#step-2-define-identifier) has the following code
```tsx
static identifer ...
```

There's a typo in **identifier**

### How can this issue be resolved?

1. Change `identifer` to `identifier`

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch @Fullstak-nl thanks for reporting this!
