### ISSUE TITLE
[bug] Reset password token return always a status 204 instead of 200

### ISSUE THREAD

**Issue by rida-re** [medusajs/medusa#4411]
### Describe the bug

Hello,
I tried to use a reset password in my project,but I found a minor bug in your API traitment: medusa\src\api\routes\store\customers\reset-password-token.ts
the funtion return always a status 204

### System information

Medusa version (including plugins):   ^1.12.1
Node.js version:v16.15.0
Database:postgres
Operating system:windows
Browser (if relevant): chrome

### Screenshots

![image](https://github.com/medusajs/medusa/assets/58844180/fc78168b-d431-4157-a0bf-4fbe38772039)

### Code snippets

`  const validated = (await validator(
    StorePostCustomersCustomerPasswordTokenReq,
    req.body
  )) as StorePostCustomersCustomerPasswordTokenReq

  const customerService: CustomerService = req.scope.resolve(
    "customerService"
  ) as CustomerService

  const customer = await customerService
    .retrieveRegisteredByEmail(validated.email)
    .catch(() => undefined)

  if (customer) {
    // Will generate a token and send it to the customer via an email provider
    const manager: EntityManager = req.scope.resolve("manager")
    await manager.transaction(async (transactionManager) => {
      return await customerService
        .withTransaction(transactionManager)
        .generateResetPasswordToken(customer.id)
// TODO return status 200 here :   res.sendStatus(200)
    })
  }

  res.sendStatus(204)
}`

**Comment by pevey** [comment]
I believe this is intended so as not to leak whether the given email has an account. You are meant to call the endpoint to request a token, and if such a user exists, they will get an email with the token. If they do not exist, nothing happens. Either way, the endpoint returns 204, which is the “success but no data to give you” response code.

**Comment by rida-re** [comment]
Hello @pevey,
Thanks for your comment.
I have to inform you I used this enpoint : "POST /store/customers/password-token" for generating the token reset password.
So when I call this endpoint with param "email",the service check if the customer existe or no in database then he sends an email but the service recturme alwyas 204.
In this case we can't know if the service send an email or no. 

These pictures explain all

- **Email existe :** 

![image](https://github.com/medusajs/medusa/assets/58844180/ba278b76-d155-43c3-bc8a-709dff8fde57)

- **Email not existe:**

![image](https://github.com/medusajs/medusa/assets/58844180/8bd96f71-c30c-40de-ab8f-543fe3485d13)
![image](https://github.com/medusajs/medusa/assets/58844180/e62e52e8-19de-4473-9c87-1de67e172323)

**Comment by pevey** [comment]
You are supposed to always get 204. It is not a bug. If the response were different for email addresses where a customer exists versus email addresses where a customer does not exist, that would be a security issue. 

You have all the information you need in either case. The request was received and successfully processed by the backend. If such a user exists, an email with a reset token was sent. You don’t need to know more. This is in line with best practices.

**Comment by rida-re** [comment]
@pevey 
yeah I see, but in this case I think this service needs some improvement like trace the logs or return an object with a message for example :
{
"status": ...
"error" : "customer isn't existe"
}

because it is difficult to analyze this case.
