### ISSUE TITLE
Service Resolving gives unexpected names for services

### ISSUE THREAD

**Issue by Bhuvi100** [medusajs/medusa#4417]
<!--

## Bug report
Resolving plugin services works in an unexpected behavior

### Describe the bug
When loading plugin services, the resolving name of the services changes from system to system.
The expected behavior is the camel case of the service, which is resolved in Windows.

### System information

Medusa version (including plugins): 7.0.0-beta-20230624084632

Operating system: Ubuntu and Windows

### Expected behavior
Resolving service names in Ubuntu must be in camel case

### Screenshots
![image](https://github.com/medusajs/medusa/assets/81316368/5bbc9355-c90f-4210-af68-b8f4e2482f79)
The first one is from Ubuntu.
![image](https://github.com/medusajs/medusa/assets/81316368/ee31945b-6c23-4ced-8b34-f2f71552a3d8)
The second one is from Windows.

### Additional context
I have console logged loaders/plugins.js
![image](https://github.com/medusajs/medusa/assets/81316368/65574f51-d60d-442a-af19-6189979a9b56)

**Comment by Bhuvi100** [comment]
Short summary: Resolving plugin service names in different systems behave differently. In Windows, it is in expected format, in camel case. But in Ubuntu, it's not in camel case. Have attached images for reference.

 In Ubuntu:
![image](https://github.com/medusajs/medusa/assets/81316368/dbb6a5cb-a267-48ca-bfcf-d419448328e1)

In Windows:
![image](https://github.com/medusajs/medusa/assets/81316368/5bbeb3f7-a952-4c34-9a35-82ff726b7798)


I have console logged in loades/plugins.js
![image](https://github.com/medusajs/medusa/assets/81316368/29fdaa7f-d439-42e1-929a-e384981185b0)

**Comment by olivermrbl** [comment]
Thanks for sharing this.

Using a kebab-case convention for your files, should give you the expected behavior i.e. identical service names regardless of OS.

**Comment by Bhuvi100** [comment]
![image](https://github.com/medusajs/medusa/assets/81316368/96bc4a27-679a-4a78-9e19-8bd36ec2fa1f)
Doesn't seem so

**Comment by olivermrbl** [comment]
Sorry, I confused kebab and snake for a second. Updated my comment.
