### ISSUE TITLE
Error 404 in order requests after deployment in production (static html export)

### ISSUE THREAD

**Issue by rida-re** [medusajs/medusa#4429]
### Describe the bug

Hello,
I prepared and configured medusa storefront on a production server, so all the pages are working fine except for the commands.
I always receive status 404 Not Found after a little analysis I found that the query does not find the static resource \_next\data\wKRYvAXKkwVlp5sVEMmFR
I share with you the captures which explain the situation well.
Thank you

### System information

Medusa version (including plugins):
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Steps to reproduce the behavior

1. Go to '.http://localhost:8000/account/orders'

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

![image](https://github.com/medusajs/medusa/assets/58844180/0257f273-983f-457a-b53e-a0e4db7a1bd0)
![image](https://github.com/medusajs/medusa/assets/58844180/535c0898-863f-4706-ab37-07e841fe2fc2)
![image](https://github.com/medusajs/medusa/assets/58844180/747caea5-7685-4f7f-ae69-0cfd382ef66f)

### Code snippets
I followed this doc : https://nextjs.org/docs/pages/building-your-application/deploying/static-exports

`const { withStoreConfig } = require("./store-config")
const store = require("./store.config.json")

module.exports = withStoreConfig({
  output: 'export',
  features: store.features,
  reactStrictMode: true,
  experimental: {
    //newNextLinkBehavior: false,
  },
  images: {
    domains: ["medusa-public-images.s3.eu-west-1.amazonaws.com", "localhost"],
    unoptimized: true,
  },
  // time in seconds of no pages generating during static
  // generation before timing out
  staticPageGenerationTimeout: 1000,
})

console.log("next.config.js", JSON.stringify(module.exports, null, 2))
`

**Comment by ivanskodje** [comment]
@rida-rechrache I am taking a shot in the dark here, but this looks like a frontend app yes?
The backend app is port 9000 by default, you might have to change it from 8000 to 9000 in those calls.

**Comment by rida-re** [comment]
@ivanskodje Yes it is a frontend app.i haven’t a problem with a port or a connection with backend.
like i said All the query to backend are working good except the query orders.
The commands I launched for production :
Yarn build = next build
Yarn export = next export

**Comment by ivanskodje** [comment]
> @ivanskodje Yes it is a frontend app.i haven’t a problem with a port or a connection with backend. like i said All the query to backend are working good except the query orders. The commands I launched for production : Yarn build = next build Yarn export = next export

If the query to backend are working, can please verify which port the successful queries are using? 
Do the query URLs use port 9000 or 8000?

**Comment by rida-re** [comment]
It use Port 8000
But With 9000 isn’t working the query
I think you don’t understand my situation.

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
