### ISSUE TITLE
Does Medusa.js architecture support creating an order before payment

### ISSUE THREAD

**Issue by microCloudCode** [medusajs/medusa#4460]
In my application, users place an order first and then proceed with the payment at a later stage. I want to allow users to make the payment after the order is created, and ensure that the payment status of the order can be properly tracked and updated.

I have reviewed the documentation of Medusa.js, but couldn't find explicit information regarding this feature. Therefore, I would like to reach out to the community to inquire if anyone has implemented similar functionality using the Medusa.js architecture or if any suggestions and guidance can be provided.

**Comment by RegisWeduLabs** [comment]
Ideally, you can use the draft order admin API to create orders without payments to stay in the logic flow of Medusa.  We had a use case like this and that's what we ended up doing.

**Comment by microCloudCode** [comment]
Thanks

**Comment by WASIF738871** [comment]
Hi, @RegisHubelia I have created draft order using admin API but order doesn't reflect on medusa backend UI because it's not coming in /admin/orders end point what to do for that?

**Comment by RegisWeduLabs** [comment]
Hi @WASIF738871 - did you click on "Drafts" in the admin panel to see if the order was there?  Draft orders and actual orders are separated in the Admin UI.

**Comment by WASIF738871** [comment]
@RegisHubelia No I can't see "Draft" module in my admin panel.
![Screenshot 2024-12-30 212352](https://github.com/user-attachments/assets/260c0d64-868c-440a-abd4-2f4de5d4b264)

**Comment by RegisWeduLabs** [comment]
It's a tab in the orders Menu.
![screenshot_2024-12-30-115130](https://github.com/user-attachments/assets/c85d189b-b837-4f0b-a6aa-9cf16c77f1bd)

**Comment by WASIF738871** [comment]
@RegisHubelia for me there is no "Drafts" tab. I installed medusa backend using medusa document. Should I install it again or you have any suggestion for me.
![Screenshot 2024-12-31 111206](https://github.com/user-attachments/assets/85e515cc-1cfc-4f3c-a96c-9b27b1ce4601)

**Comment by timmaier** [comment]
Hey @WASIF738871 I also had the same issue when testing medusa for feasibility. 

Looks like the draft orders pre-built UI is not available in v2 yet. https://github.com/medusajs/medusa/issues/9826
