### ISSUE TITLE
Extending ProductCategory result in TypeError: this.findDescendantsTree is not a function

### ISSUE THREAD

**Issue by imash96** [medusajs/medusa#4461]
### Describe the bug

I have extended the enitity of product-category.ts file to include some custom fiels. Every this work perfectly the endpoint _/store/product-categories_ also working correctly but when I add the query _/store/product-categories?include_descendants_tree=true_ this result an error in the backend **TypeError: this.findDescendantsTree is not a function**

If I delete all the files related to product-category in src folder then every thing works perfecly as before. So bacically I am not able to extend product-category entity.

### System information

Medusa version (including plugins): 1.12.1
Node.js version:  v18.16.0
Database: Postgres
Operating system: Windows 11

### Steps to reproduce the behavior

1. Extend product-category entity with some random text fields extend the repositorie for product-category
2. start the server and hit the endpoint /store/product-categories?include_descendants_tree=true
3. See error

### Expected behavior

Expected behaviour was that every core entity functions should run without any error even after extending some fields.

### Additional context

```
error:   this.findDescendantsTree is not a function
TypeError: this.findDescendantsTree is not a function
    at Repository.<anonymous> (F:\Projects\website\***\backend\node_modules\@medusajs\medusa\dist\repositories\product-category.js:162:71)
    at step (F:\Projects\website\***\backend\node_modules\@medusajs\medusa\dist\repositories\product-category.js:44:23)
    at Object.next (F:\Projects\website\***\backend\node_modules\@medusajs\medusa\dist\repositories\product-category.js:25:53)
    at F:\Projects\website\***\backend\node_modules\@medusajs\medusa\dist\repositories\product-category.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (F:\Projects\website\***\backend\node_modules\@medusajs\medusa\dist\repositories\product-category.js:15:12)
    at F:\Projects\website\***\backend\node_modules\@medusajs\medusa\dist\repositories\product-category.js:157:109
    at Array.map (<anonymous>)
    at Repository.<anonymous> (F:\Projects\website\***\backend\node_modules\@medusajs\medusa\dist\repositories\product-category.js:157:69)
    at step (F:\Projects\website\***\backend\node_modules\@medusajs\medusa\dist\repositories\product-category.js:44:23)
```

**Comment by riqwan** [comment]
Can you share the code that you wrote to extend this? @imash96 

Note: ProductCategory is a TreeRepository from typeorm. If you're extending it, use `getTreeRepository`

**Comment by imash96** [comment]
@riqwan thankx for your help this solve my initial problem but a new error is now faced. When I try to seed the database or create new category using admin ui result in an error: TypeORMError: Cyclic dependency: "ProductCategory"

I have to remove all the files related to product-category in src directory and then restart the server and then seed or create category and again add the models and repository to get my results.

```
TypeORMError: Cyclic dependency: "ProductCategory"
    at visit (F:\Projects\website\****\backend\node_modules\typeorm\persistence\SubjectTopoligicalSorter.js:147:23)
    at visit (F:\Projects\website\****\backend\node_modules\typeorm\persistence\SubjectTopoligicalSorter.js:164:21)
    at SubjectTopoligicalSorter.toposort (F:\Projects\website\****\backend\node_modules\typeorm\persistence\SubjectTopoligicalSorter.js:143:17)
    at SubjectTopoligicalSorter.sort (F:\Projects\website\****\backend\node_modules\typeorm\persistence\SubjectTopoligicalSorter.js:53:45)
    at SubjectExecutor.execute (F:\Projects\website\****\backend\node_modules\typeorm\persistence\SubjectExecutor.js:91:108)        
    at EntityPersistExecutor.execute (F:\Projects\website\****\backend\node_modules\typeorm\persistence\EntityPersistExecutor.js:140:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

models/product-category.ts

```
import { Column, Entity, Tree } from "typeorm"
import { DbAwareColumn, ProductCategory as MedusaProductCategory } from "@medusajs/medusa"

@Entity()
@Tree("materialized-path")
export class ProductCategory extends MedusaProductCategory {
    @Column({ type: "varchar", nullable: true })
    customattribute: string | null

    @Column({ type: "varchar", nullable: true })
    imgsrc: string | null

    @Column({ type: "varchar", nullable: true })
    alt: string | null

    @DbAwareColumn({ type: "jsonb", nullable: true })
    metadata: Record<string, unknown>
}
```

repositories/product-category.ts
```
import { ProductCategory } from "../models/product-category"
import { dataSource } from "@medusajs/medusa/dist/loaders/database"
import { ProductCategoryRepository as MedusaProductCategoryRepository } from "@medusajs/medusa/dist/repositories/product-category"

export const ProductCategoryRepository = dataSource
  .getTreeRepository(ProductCategory)
  .extend({
    ...Object.assign(
      MedusaProductCategoryRepository,
      { target: ProductCategory }
    ),
  })

export default ProductCategoryRepository;
```

**Comment by adrien2p** [comment]
When extending a tree repository, you need to re define the column that have a relation to itself (children, parent) in order to apply the new product category to them as well. Otherwise it create a cyclic issue

**Comment by dadebulba** [comment]
Hi, I'm also interested in extending the ProductCategory type and repository, could you provide an example? @imash96 did you manage to solve the issue?

**Comment by olivermrbl** [comment]
Just reiterating @adrien2p's comment. In the extended Product Category model, you must define the parent-child relationship such that your extended model references itself instead of the default one. 

Essentially, your extension will look something along these lines:

```ts
@Entity()
@Tree("materialized-path")
export class ProductCategory extends MedusaProductCategory {
    @Column({ type: "varchar", nullable: true })
    customattribute: string | null

    // ...other custom props

    @TreeParent()
    @JoinColumn({ name: "parent_category_id" })
    // @ts-ignore
    parent_category: ProductCategory | null;

    @TreeChildren({ cascade: true })
    // @ts-ignore
    category_children: ProductCategory[];
}
```

**Comment by olivermrbl** [comment]
@dadebulba – let us know if this helps :)

**Comment by dadebulba** [comment]
Thank you @olivermrbl for me is working fine, I really appreciate your help

**Comment by jaiminTH** [comment]
@dadebulba @riqwan @adrien2p Can you please look into my problem in [this](https://github.com/medusajs/medusa/discussions/4185#discussioncomment-6624365) comments section?
