### ISSUE TITLE
[Docs] Incorrect documentation for search endpoint

### ISSUE THREAD

**Issue by isaac-mcfadyen** [medusajs/medusa#4465]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In the docs for the search endpoint (https://docs.medusajs.com/api/store#tag/Products/operation/PostProductsSearch), the search query is indicated as a query parameter, like `https://example.com?q=<search query>`.

However, according to my own testing and this blog post (https://medusajs.com/blog/meilisearch-medusa/), it's actually a parameter passed in the JSON body like `{"q": "<search query>"}`, meaning the docs are incorrect.

### How can this issue be resolved?

Depending on the source of this issue:
1. Perhaps the docs engine is automatically assuming POST body parameters are actually query parameters?
2. Perhaps the schema used to generate the docs is incorrect?
3. Perhaps the actual endpoint was updated without updating the docs?

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch @isaac-mcfadyen ! Will open a PR to fix this 👍🏻
