### ISSUE TITLE
Saving two variants with the same option value results in error

### ISSUE THREAD

**Issue by Arsenalist** [medusajs/medusa#4469]
When creating a product with two variants with the same option value results in an error indicating that the `product_option_value.value` field has duplicates. However, when creating a product with one variant with option value A, saving the product, and hen creating another variant with option value A results in no error. This is inconsistent behaviour. 

I propose that this check be removed as there are valid use cases where two variants can have the same option value.

**Comment by adrien2p** [comment]
I would like to understand a bit more, how the customer choose the right product variant when they have the same options? Could you elaborate a bit more on that.

Also, I agree that the behaviour you are describing seems to be inconsistent. But when I look at the `validateVariantsToCreate_` you should receive that error in both cases, but I think it does not work as intended and we should add a constrain at the db level wich would also simplify that method. cc @olivermrbl

**Comment by Arsenalist** [comment]
I am selling tickets with two price tiers. The two tiers are represented as variants. The show times are options in that variant. The shows happen at the same time. 

I really hope we don’t add a DB constraint.

**Comment by adrien2p** [comment]
So in your case you need the variants to have the same options to represent the same show time right? wouldn't you have something like:
- 20:00 (1)
- 20:00 (2)
etc for the different tier?

**Comment by olivermrbl** [comment]
I would like to understand the issue more in-depth before we proceed with any changes. Could I get you to share the object shapes of the product options + product variants that led to an error?

As @adrien2p's points out, you could have Tier and Showtime as product options and add variants for each combination. The attached screenshot might be helpful:

<img width="829" alt="CleanShot 2023-07-09 at 13 09 20@2x" src="https://github.com/medusajs/medusa/assets/59018053/2a783c63-66f9-4fc5-8424-fcbae5d99b51">

**Comment by olivermrbl** [comment]
Also next time, please use our template when filing an issue. It makes it much easier and quicker for us to help and debug your problem.

**Comment by Arsenalist** [comment]
Example:

```product_variants[0].options[0].value = time of showtime, 8pm
product_variants[0].title = description of show (regular seats)
product_variants[0].prices[0] = price of show, $30

product_variants[1].options[0].value = time of showtime, 8pm
product_variants[1].title = description of show (premium seats)
product_variants[1].prices[0] = price of show, $50```

In the above example I have the same value for showtime (8pm) which is not allowed by Medusa.

**Comment by sradevski** [comment]
Hey, thanks for the report! 

I think in this case you can just name your variants `8pm Basic` and `8pm Premium` to distinguish between the tiers.

If you are still facing issues with v1, please open a new ticket and we will address it as soon as possible. Thanks! 🙏
