### ISSUE TITLE
Access admin panel ?

### ISSUE THREAD

**Issue by blackyzero** [medusajs/medusa#448]
Hello,

I just finish the installation, how could i access admin panel (like demo) ? 

Thank you.

**Comment by olivermrbl** [comment]
Great!

You can set up your own admin in very few steps. See [this guide](https://github.com/medusajs/admin#-setting-up-admin) :)

**Comment by blackyzero** [comment]
Nice. the installation goes well. Thanks.

Question, how could i make it binding on specific ip address instead of localhost as default?

**Comment by blackyzero** [comment]
I found a way do this by adding
`gatsby develop -H 0.0.0.0`

Now, i don't know default admin account to login or how should i create it?

Thanks a lot.

**Comment by kasperkristensen** [comment]
Hi @blackyzero,

The default admin account is email: admin@medusa-test.com // password: supersecret. You can find it in [seed.json](https://github.com/medusajs/medusa-starter-default/blob/master/data/seed.json)

**Comment by olivermrbl** [comment]
^^ 👍 

@blackyzero Otherwise, you can always create your own users with `medusa user -e some@email.com -p some_password`

**Comment by blackyzero** [comment]
Great ! Thanks @kasperkristensen @olivermrbl 

I tried with default admin account which is in seed.json, not work
Then, also tried with new account which is created by command, but not work also.

The login screen doesn't show any error after inputing the account. I don't see any related login log from ongoing terminal.

Do you have any idea how to get login log and solve this issue?
Thanks.

**Comment by olivermrbl** [comment]
Are you running the admin on `http://localhost:7000` and the server on `http://localhost:9000`? :)

**Comment by blackyzero** [comment]
Hi @olivermrbl 

Yes. please see below

> root@medusa:~# lsof -Pni |grep 8000
> node     5891  root   20u  IPv6  28420      0t0  TCP *:8000 (LISTEN)
> node     5891  root   25u  IPv6  36911      0t0  TCP 10.0.0.38:8000->10.0.0.67:50699 (ESTABLISHED)
> root@medusa:~#
> root@medusa:~# lsof -Pni |grep 9000
> node     5834  root   23u  IPv6  28369      0t0  TCP *:9000 (LISTEN)
> root@medusa:~#
> root@medusa:~# lsof -Pni |grep 7000
> node     6184  root   21u  IPv4  28973      0t0  TCP *:7000 (LISTEN)
> node     6184  root   29u  IPv4  37101      0t0  TCP 10.0.0.38:7000->10.0.0.67:50826 (ESTABLISHED)
> node     6184  root   40u  IPv4  37155      0t0  TCP 10.0.0.38:7000->10.0.0.67:50835 (ESTABLISHED)
> root@medusa:~#

**Comment by olivermrbl** [comment]
@blackyzero Hmm and you are not seeing CORS issues in the browser developer console for the requests?

**Comment by blackyzero** [comment]
It seems it's still trying to connect to http://localhost:9000 (attached)

```POST http://localhost:9000/admin/auth net::ERR_CONNECTION_REFUSED```

https://ibb.co/P4hTJtF

**Comment by olivermrbl** [comment]
Have you added `10.0.0.38` to ADMIN_CORS in your `medusa-config.js` ? :)

**Comment by blackyzero** [comment]
Yes, i did
```
root@medusa:/opt/services/my-medusa-store# cat medusa-config.js
// CORS when consuming Medusa from admin
const ADMIN_CORS = process.env.ADMIN_CORS || "http://10.0.0.38:7000";

// CORS to avoid issues when consuming Medusa from a client
const STORE_CORS = process.env.STORE_CORS || "http://10.0.0.38:8000";

// Database URL (here we use a local database called medusa-development)
const DATABASE_URL =
  process.env.DATABASE_URL || "postgres://localhost/medusa-store";

// Medusa uses Redis, so this needs configuration as well
const REDIS_URL = process.env.REDIS_URL || "redis://10.0.0.38:6379";

```

**Comment by olivermrbl** [comment]
Hmm very weird indeed. Do you see any logs in your terminal? (where Medusa is running)

**Comment by blackyzero** [comment]
No, i don't have any related log during login.

root@medusa:/opt/services/my-medusa-store# medusa develop

```
� Services initialized � 179ms
� Subscribers initialized � 16ms
� Express intialized � 4ms
� Plugins intialized � 9ms
� API initialized � 191ms
⠹ Initializing defaultswarn:    You don't have any notification provider plugins installed. You may want to add one to your project.
� Defaults initialized � 277ms
� Server is ready on port: 9000 � 6ms
::ffff:10.0.0.38 - - [03/Oct/2021:13:43:15 +0000] "GET /store/products HTTP/1.1" 200 5051 "-" "axios/0.21.4"
::ffff:10.0.0.67 - - [03/Oct/2021:13:43:16 +0000] "GET /store/products HTTP/1.1" 304 - "http://10.0.0.38:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36"
::ffff:10.0.0.67 - - [03/Oct/2021:13:43:16 +0000] "GET /store/carts/cart_01FH0SF19R63B4CAX0FRD9ZQYD HTTP/1.1" 304 - "http://10.0.0.38:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36"
::ffff:10.0.0.38 - - [03/Oct/2021:14:15:42 +0000] "GET /store/products HTTP/1.1" 200 5051 "-" "axios/0.21.4"
::ffff:10.0.0.67 - - [03/Oct/2021:14:15:43 +0000] "GET /store/products HTTP/1.1" 304 - "http://10.0.0.38:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36"
::ffff:10.0.0.67 - - [03/Oct/2021:14:15:43 +0000] "GET /store/carts/cart_01FH0SF19R63B4CAX0FRD9ZQYD HTTP/1.1" 304 - "http://10.0.0.38:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36"
::ffff:10.0.0.67 - - [03/Oct/2021:14:15:46 +0000] "GET / HTTP/1.1" 404 139 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36"
::ffff:10.0.0.67 - - [03/Oct/2021:14:15:46 +0000] "GET /robots.txt HTTP/1.1" 404 149 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36"
```
root@medusa:/opt/services/my-medusa-store/my-medusa-storefront# npm run dev

```
> medusa-nextjs-starter@0.1.0 dev /opt/services/my-medusa-store/my-medusa-storefront
> next dev -p 8000

ready - started server on 0.0.0.0:8000, url: http://localhost:8000
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
event - compiled successfully
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
event - build page: /
wait  - compiling...
event - compiled successfully
wait  - compiling...
event - compiled successfully
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
wait  - compiling...
event - compiled successfully

```

root@medusa:/opt/services/my-medusa-store/medusa-admin# yarn start
```
yarn run v1.22.15
$ npm run develop
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1633271894675-0.11731834009923148/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> medusa-admin@0.1.0 develop /opt/services/my-medusa-store/medusa-admin
> gatsby develop -H 0.0.0.0 -p 7000

Debugger listening on ws://127.0.0.1:9229/e607f895-56ca-44b7-ba8d-b3f6730a7448
For help, see: https://nodejs.org/en/docs/inspector
success open and validate gatsby-configs - 0.033s
success load plugins - 0.625s
success onPreInit - 0.065s
success initialize cache - 0.064s
success copy gatsby files - 0.114s
success onPreBootstrap - 0.011s
success createSchemaCustomization - 0.024s
success Checking for changed pages - 0.004s
success source and transform nodes - 0.081s
success building schema - 0.333s
success createPages - 0.002s
success Checking for changed pages - 0.002s
success createPagesStatefully - 0.103s
success update schema - 0.044s
success write out redirect data - 0.007s
success Build manifest and related icons - 0.134s
success onPostBootstrap - 0.151s
info bootstrap finished - 6.161s
success onPreExtractQueries - 0.002s
success extract queries from components - 0.540s
success write out requires - 0.044s
success run static queries - 0.051s - 1/1 19.59/s
success run page queries - 0.064s - 6/6 94.11/s
warn Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
⠀
You can now view medusa-admin in the browser.
⠀
  Local:            http://localhost:7000/
  On Your Network:  http://10.0.0.38:7000/
⠀
View GraphiQL, an in-browser IDE, to explore your site's data and schema
⠀
  Local:            http://localhost:7000/___graphql
  On Your Network:  http://10.0.0.38:7000/___graphql
⠀
Note that the development build is not optimized.
To create a production build, use gatsby build
⠀
success Building development bundle - 14.070s
```

**Comment by olivermrbl** [comment]
And nothing can be seen in the networks tab of your browser developer console either? It's really hard to debug with only this console message.

**Comment by blackyzero** [comment]
well, i don't see any error in Network tab, the only error which is showing in Console as attached below

https://ibb.co/P4hTJtF

https://ibb.co/QXFvWzM

**Comment by olivermrbl** [comment]
Hi there @blackyzero! Still experiencing this issue? :)

**Comment by olivermrbl** [comment]
Closed due to inactivity

**Comment by teddybee** [comment]
I have the same problem. 

`Access to XMLHttpRequest at 'http://192.168.0.13:9010/admin/auth' from origin 'http://192.168.0.14:7000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

In the docker compose environment part I set this:
ADMIN_CORS: "192.168.0.14:7000, 192.168.0.14:7001"
