### ISSUE TITLE
An error occurred while processing batch.created: TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by lohazo** [medusajs/medusa#4497]
## Bug report
I got this error every time i tried to upload a prices list.
An error occurred while processing batch.created: TypeError: Cannot read properties of undefined (reading 'split')
### Describe the bug
After i uploaded prices list csv file (the file is uploaded in storage bucket and key saved), i got "{"level":"warn","message":"An error occurred while processing batch.created: TypeError: Cannot read properties of undefined (reading 'split')","timestamp":"2023-07-11 04:39:53"}" in the backend server.
And this is batch_job result `{"errors": ["Cannot read properties of undefined (reading 'split')"]}`
### System information

Medusa version (including plugins):1.12.1 with [medusa-files-s3]
Node.js version: v18.16.0
Database: Postgresql
Operating system: Debian 12
Browser (if relevant):

### Steps to reproduce the behavior

1. Go to Pricing page in admin and then select one price list.
2. Click on `Import price list`
3. Wait

### Expected behavior
Perform price update batch job successfully without error.

### Screenshots
<img width="1264" alt="Screenshot 2023-07-11 at 11 52 56" src="https://github.com/medusajs/medusa/assets/6048013/7759e7b0-744c-4141-8f8b-4df595f79412">

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
