### ISSUE TITLE
Failure to Display Error Message for Missing Customized File, Resulting in 404 Errors for Customized API Calls

### ISSUE THREAD

**Issue by quang-ng** [medusajs/medusa#4510]
### Describe the bug

The system is not displaying an error message when a customized file is missing, even though customized API calls are resulting in 404 errors. Although the build is successful, the lack of an error message is causing confusion and making it difficult to identify and resolve the issue.

### System information

Medusa version (including plugins): 1.7.8
Node.js version: 17
Database: PostgreSQL
Operating system: Ubuntu
Browser (if relevant):

### Steps to reproduce the behavior

1. Create a index.ts file in a `src/api` folder
2. Try to import something doesn't exists.  Ex: `import {something} from "./not-exitsts-file"
3. Build and start the server

### Expected behavior

Build fail and missing file error message display.

### Current behavior
Although the build is successful and the server starts without issue, attempts to access customized APIs result in 404 errors. In contrast, built-in APIs remain accessible.

**Comment by giangvo1125** [comment]
I faced the same issue.

**Comment by olivermrbl** [comment]
Solved in https://github.com/medusajs/medusa/pull/4410
