### ISSUE TITLE
Some widget injection zones are not implemented

### ISSUE THREAD

**Issue by SimonsThijs** [medusajs/medusa#4515]
### Describe the bug

Admin injection zones have been introduced some time ago. I noticed that some of the injection zones do not work because they are not implemented in the admin ui. E.g. the zones 'order.details.before' and 'order.details.after' work but the zones 'customer.details.before' and 'customer.details.after' do not work.

It seems like the injection zones that are not working are only missing the code that injects the widget into the html. For e.g. the customer injection zone only the code seems to be missing in this file: admin-ui/ui/src/domain/customers/details/index.tsx

### System information

Medusa version (including plugins): @medusajs/medusa 1.12.2, @medusajs/admin 7.0.0-beta-20230619170349
Node.js version: 20.2.0
Database: Postgres
Operating system: MacOs

### Steps to reproduce the behavior

1. Create a widget for the customer details page
2. Widget is not shown in the admin

### Expected behavior

The widget should be displayed in at the right injection zone. In this case the injection zone 'customer.details.before'

**Comment by SimonsThijs** [comment]
It might be that the problem was that the injection zone is just 'customer.details' instead of 'customer.details.before' and 'customer.details.after'  (see: https://github.com/medusajs/medusa/blob/e0aab04ff26f5927a2b110ab362b471a21739386/packages/admin-ui/ui/src/domain/customers/details/index.tsx#L147C41-L147C41 ) . I got it to work now, however i think it should still be changed to 'customer.details.before' and 'customer.details.after'.

**Comment by olivermrbl** [comment]
I believe most widget zones are implemented. Please ensure, you are running on the latest beta version.

For example, the customer details widgets can be seen [here](https://github.com/medusajs/medusa/blob/feat/admin-extensions/packages/admin-ui/ui/src/domain/customers/details/index.tsx).

**Comment by SimonsThijs** [comment]
Issue has indeed been fixed in one of the latest beta releases. 
Thank you!
