### ISSUE TITLE
Ready to Develop with docker-compose Postgres and Redis Setup 

### ISSUE THREAD

**Issue by lohnsonok** [medusajs/medusa#453]
I setup a docker-compose Postgres and Redis containers to work with Medusa Server but not working

> start
> medusa develop

Successfully compiled 0 files with Babel (4ms).
✔ Models initialized – 299ms
✔ Plugin models initialized – 23ms
✔ Repositories initialized – 152ms
⠸ Initializing database

It lock on initialise database. I currently only work with sqlite. 

## Expected 
Should work with docker database container

**Comment by olivermrbl** [comment]
Hi @lohnsonok, thanks for trying out Medusa.

Would love to have a look at the docker-compose setup. Could you push it to a repo, such that I can reproduce your env.? :) 

Otherwise, maybe you could paste the file in here.

**Comment by lohnsonok** [comment]
> Hi @lohnsonok, thanks for trying out Medusa.
> 
> Would love to have a look at the docker-compose setup. Could you push it to a repo, such that I can reproduce your env.? :)
> 
> Otherwise, maybe you could paste the file in here.
Thank you for fast answer. Please check here
[Medusa-postgres-redis-docker](https://github.com/lohnsonok/medusa-postgres-redis-docker)

**Comment by olivermrbl** [comment]
> > Hi @lohnsonok, thanks for trying out Medusa.
> > Would love to have a look at the docker-compose setup. Could you push it to a repo, such that I can reproduce your env.? :)
> > Otherwise, maybe you could paste the file in here.
> 
> Thank you for fast answer. Please check here [Medusa-postgres-redis-docker](https://github.com/lohnsonok/medusa-postgres-redis-docker)

Thanks! Will have a look tonight :)

**Comment by olivermrbl** [comment]
@lohnsonok Would you also like your Medusa server to be dockerized or only the Redis and Postgres?

**Comment by olivermrbl** [comment]
See repository with Docker setups [here](https://github.com/medusajs/docker-medusa).

Alternatively, check out the Docker setup in our [starter](https://github.com/medusajs/medusa-starter-default) :)
