### ISSUE TITLE
Unable to delete line items from cart after failed checkout

### ISSUE THREAD

**Issue by paulschwahn** [medusajs/medusa#4531]
### Describe the bug

When attempting to delete an item from the cart after a failed checkout (e.g., due to low stock quantity), the deletion operation fails. I suspect this is because the tax lines associated with the cart line items have already been created and linked, resulting in a foreign key constraint violation during the deletion process.

After a bit more research and logging I found the SQL error resulting in the line item deletion fail:
```
query: 'DELETE FROM "line_item" WHERE "id" = $1',
parameters: [ 'item_01H57MES4DHXK66VBVJJV1A9AG' ],
driverError: error: update or delete on table "line_item" violates foreign key constraint "FK_5077fa54b0d037e984385dfe8ad" on table "line_item_tax_line"
detail: 'Key (id)=(item_01H57MES4DHXK66VBVJJV1A9AG) is still referenced from table "line_item_tax_line".'
```

### System information

Medusa version (including plugins): 1.12.2 (medusa), using nextjs-starter-medusa as storefront base
Node.js version: v18.15.0
Database: postgres 14.5-1.pgdg110+1
Operating system: macos
Browser (if relevant): chrome 114.0.5735.198 arm64

### Steps to reproduce the behavior

1. Add an item to the cart in browser 1
2. Add another item in browser 2 so that the quantity + browser 1 qty would exceed the stock qty
3. Place order with browser 2
4. Place order with browser 1 and get the "`Variant with id: variant_... does not have the required inventory`" error
5. Go back to cart and try to delete any item

### Expected behavior

Deleting a line item from the cart should be possible even after a failed checkout. The associated tax lines should also be properly handled, allowing successful deletion without violating any foreign key constraints.

### Code snippets

https://github.com/medusajs/medusa/blob/fe6586e560ad20ec59df4727bb8a7f1f42072f4a/packages/medusa/src/services/cart.ts#L515-L517

### Additional context

I was able to fix this temporarily by changing the given code snippet from `delete` to `deleteWithTaxLines`

**Comment by Loque18** [comment]
was this fixed ?
