### ISSUE TITLE
Can't create a custom giftcard in medusa admin

### ISSUE THREAD

**Issue by magdafiktus** [medusajs/medusa#4544]
Describe the bug
Can't create a custom giftcard in medusa admin
 
System information
"@medusajs/admin": "6.0.1",
"@medusajs/cache-redis": "1.8.8",
"@medusajs/event-bus-redis": "1.8.8",
"@medusajs/inventory": "1.9.1",
"@medusajs/medusa": "^1.12.1",
"@medusajs/medusa-cli": "1.3.16",
"@medusajs/stock-location": "1.9.1",
"@types/express": "^4.17.17",
"babel-preset-medusa-package": "1.1.19",
"contentful": "^7.14.7",
"cors": "^2.8.5",
"cross-env": "^7.0.2",
"csv-stringify": "5.3.2",
"easy-soap-request": "^3.3.3",
"express": "^4.17.1",
"joi": "^17.3.0",
"medusa-core-utils": "1.2.0",
"medusa-file-spaces": "1.3.7",
"medusa-fulfillment-webshipper": "1.3.11-snapshot-20230626084333",
"medusa-interfaces": "1.3.7",
"medusa-payment-adyen": "1.1.44",
"medusa-payment-klarna": "1.3.10",
"medusa-payment-manual": "1.0.24",
"medusa-payment-paypal": "6.0.1",
"medusa-payment-stripe": "6.0.1",
"medusa-plugin-brightpearl": "1.3.10-snapshot-20230621150344",
"medusa-plugin-contentful": "1.2.10",
"medusa-plugin-discount-generator": "1.1.27",
"medusa-plugin-ip-lookup": "1.2.8",
"medusa-plugin-meilisearch": "2.0.8",
"medusa-plugin-restock-notification": "7.0.2",
"medusa-plugin-segment": "1.3.6",
"medusa-plugin-sendgrid": "1.3.9",
"medusa-plugin-sentry": "^1.4.2",
"medusa-plugin-slack-notification": "1.3.9",
"medusa-plugin-wishlist": "1.1.43",
"medusa-test-utils": "^1.1.41",

Steps to reproduce the behavior
1. go to giftcards in the admin
2. press +custom gift card
3. nothing arrives to email
4. the generated code does not work
 
Expected behavior
the indicated email gets a working giftcard code

**Comment by olivermrbl** [comment]
Can I get you to ensure, you've added a SendGrid email template for the event `gift_card.created`? 

Will investigate the issue with the code.

**Comment by magdafiktus** [comment]
Right, yes we should do that, thanks. But still, should not the code work either way? I mean it is generated in Medusa so for now I could just copy it and send directly to the customer, right?

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
