### ISSUE TITLE
 Property "invitation_code" was not found in "Customer".

### ISSUE THREAD

**Issue by microCloudCode** [medusajs/medusa#4549]
![image](https://github.com/medusajs/medusa/assets/46712199/34e2198c-7e62-4c6b-96bd-5d6c6e5f5f47)
![image](https://github.com/medusajs/medusa/assets/46712199/cd8ba710-500d-4418-af82-041d84c440b8)
I expanded the 'customers' entity following the steps, but when I request '/store/customers/me', I receive the following error
![image](https://github.com/medusajs/medusa/assets/46712199/05325e38-fddf-45ec-929e-a36f9eca2caf)

**Comment by microCloudCode** [comment]
@adrien2p help

**Comment by adrien2p** [comment]
Have you ran your migrations? What is your entity file name?

**Comment by microCloudCode** [comment]
![image](https://github.com/medusajs/medusa/assets/46712199/bc89b6f4-9cb9-4a91-ac9d-44182650d891)
![image](https://github.com/medusajs/medusa/assets/46712199/80b5dcea-754c-4f56-96a5-1c78b5117b1f)
@adrien2p

**Comment by adrien2p** [comment]
You are not obliged to mention me for every message or issue. We might not be in the same timezone and i have other things to do as well. I look when i van and ill come back to you in time

**Comment by microCloudCode** [comment]
ok sorry

**Comment by microCloudCode** [comment]
solved
