### ISSUE TITLE
Problems when using Inventory module - purchasable property returns incorrect information

### ISSUE THREAD

**Issue by thejspro** [medusajs/medusa#4554]
## Bug report

I have setup the Inventory module following the guide in the official documentation, but I have encountered several serious problems when trying to use it, as it does not seem to function correctly.

All of problems occur on a fresh Medusa installation.

1. When using the Inventory module, the same product variation, shows as `purchasable: true` when retrieved via the `/store/product/product_ID` endpoint, but when retrieved by the `/store/variation/variation_ID` endpoint it shows as `purchasable: false`. Please refer to JSON snippets below:

/store/products/prod_01H5PZHGN8Y8SY83T8WK769F4K?expand=variants
```
{
  "product": {
    "id": "prod_01H5PZHGN8Y8SY83T8WK769F4K",
    "title": "Test product",
    "subtitle": "",
    "status": "published",
    "external_id": null,
    "description": null,
    "handle": "test-product",
    "is_giftcard": false,
    "discountable": false,
    "thumbnail": null,
    "profile_id": "sp_01H5PMNZY1HJWTBBTRHS5RTDNQ",
    "collection_id": null,
    "type_id": null,
    "weight": null,
    "length": null,
    "height": null,
    "width": null,
    "hs_code": null,
    "origin_country": null,
    "mid_code": null,
    "material": null,
    "created_at": "2023-07-19T11:46:06.622Z",
    "updated_at": "2023-07-19T12:22:16.149Z",
    "deleted_at": null,
    "metadata": {
      
    },
    "variants": [
      {
        "id": "variant_01H5PZK49DYTYHMM4WW84ND0E6",
        "created_at": "2023-07-19T11:46:59.490Z",
        "updated_at": "2023-07-19T12:09:11.323Z",
        "deleted_at": null,
        "title": "Green - S",
        "product_id": "prod_01H5PZHGN8Y8SY83T8WK769F4K",
        "sku": null,
        "barcode": null,
        "ean": null,
        "upc": null,
        "variant_rank": 0,
        "inventory_quantity": 60,
        "allow_backorder": false,
        "manage_inventory": true,
        "hs_code": null,
        "origin_country": null,
        "mid_code": null,
        "material": null,
        "weight": null,
        "length": null,
        "height": null,
        "width": null,
        "metadata": {
          
        },
        "purchasable": true
      }
    ]
  }
}
```

/store/variants/variant_01H5PZK49DYTYHMM4WW84ND0E6?expand
```
{
  "variant": {
    "id": "variant_01H5PZK49DYTYHMM4WW84ND0E6",
    "created_at": "2023-07-19T11:46:59.490Z",
    "updated_at": "2023-07-19T12:09:11.323Z",
    "deleted_at": null,
    "title": "Green - S",
    "product_id": "prod_01H5PZHGN8Y8SY83T8WK769F4K",
    "sku": null,
    "barcode": null,
    "ean": null,
    "upc": null,
    "variant_rank": 0,
    "allow_backorder": false,
    "manage_inventory": true,
    "hs_code": null,
    "origin_country": null,
    "mid_code": null,
    "material": null,
    "weight": null,
    "length": null,
    "height": null,
    "width": null,
    "metadata": {
      
    },
    "prices": [
      {
        "id": "ma_01H5PZMRXFTGD4TYA70VVZ8PSW",
        "created_at": "2023-07-19T11:47:53.381Z",
        "updated_at": "2023-07-19T11:47:53.381Z",
        "deleted_at": null,
        "currency_code": "eur",
        "amount": 100000,
        "min_quantity": null,
        "max_quantity": null,
        "price_list_id": null,
        "variant_id": "variant_01H5PZK49DYTYHMM4WW84ND0E6",
        "region_id": null,
        "price_list": null
      },
      {
        "id": "ma_01H5PZTRT3R12C9TE3Y708JQQF",
        "created_at": "2023-07-19T11:51:09.885Z",
        "updated_at": "2023-07-19T11:51:09.885Z",
        "deleted_at": null,
        "currency_code": "eur",
        "amount": 90000,
        "min_quantity": null,
        "max_quantity": null,
        "price_list_id": "pl_01H5PZTRSZQC9CTSZHCJKWWJ3D",
        "variant_id": "variant_01H5PZK49DYTYHMM4WW84ND0E6",
        "region_id": null,
        "price_list": {
          "id": "pl_01H5PZTRSZQC9CTSZHCJKWWJ3D",
          "created_at": "2023-07-19T11:51:09.885Z",
          "updated_at": "2023-07-19T12:23:35.183Z",
          "deleted_at": null,
          "name": "Supplier A",
          "description": "Discounts from supplier A",
          "type": "override",
          "status": "active",
          "starts_at": "2023-07-19T11:51:01.067Z",
          "ends_at": "2023-07-26T11:51:01.068Z"
        }
      },
      {
        "id": "ma_01H5Q0MRHJTTEKZR2S4FNC8QWH",
        "created_at": "2023-07-19T12:05:21.579Z",
        "updated_at": "2023-07-19T12:05:21.579Z",
        "deleted_at": null,
        "currency_code": "pln",
        "amount": 300000,
        "min_quantity": null,
        "max_quantity": null,
        "price_list_id": "pl_01H5PZTRSZQC9CTSZHCJKWWJ3D",
        "variant_id": "variant_01H5PZK49DYTYHMM4WW84ND0E6",
        "region_id": null,
        "price_list": {
          "id": "pl_01H5PZTRSZQC9CTSZHCJKWWJ3D",
          "created_at": "2023-07-19T11:51:09.885Z",
          "updated_at": "2023-07-19T12:23:35.183Z",
          "deleted_at": null,
          "name": "Supplier A",
          "description": "Discounts from supplier A",
          "type": "override",
          "status": "active",
          "starts_at": "2023-07-19T11:51:01.067Z",
          "ends_at": "2023-07-26T11:51:01.068Z"
        }
      }
    ],
    "original_price": null,
    "calculated_price": null,
    "original_price_incl_tax": null,
    "calculated_price_incl_tax": null,
    "original_tax": null,
    "calculated_tax": null,
    "tax_rates": null,
    "purchasable": false
  }
}
```

2. Unable to match the stock location to product variant

Scenario:

The variant for Product A has a base price of 1000 EUR.
It is stocked by Supplier A and Supplier B.
Supplier A sells Product A for 900 EUR and Supplier B sells the same Product A for 950 EUR.
Supplier A has 100 of Product A in stock and Supplier B has 0 of Product A in stock.

Given the above scenario, I need to know the following information, to be able to correctly show this product to my customer:

Is the product variant in stock?
Who has the product variant in stock?
Do the suppliers that have the product in stock, offer specific discounts on this product variant?

Depending on who has the product in stock and what their prices are, the customer might see a different availability and pricing information in my storefront.

I figured that I could use price lists and stock locations to achieve this, but there is no way to match the variant to a location and to a price list.

This is impossible mostly due to the fact that the stock location information is not published when retrieving variant information. If I had stock information available for each variant, I could try and match the variant ID to the stock location and to the price list ID.

Apologies for an incoherent post, but English is not my first language, hope it makes sense!

### System information

Medusa version (including plugins):
```
"@medusajs/inventory": "^1.9.1",
"@medusajs/medusa": "1.12.2",
"@medusajs/stock-location": "^1.9.1",
```

Node.js version: `v20.0.0`
Database: PostgreSQL 15
Operating system: OS X Ventura 13.4.1 (c)

**Comment by pKorsholm** [comment]
Hi John

Thanks for reporting this! 

You are absolutely right about #1 being a bug, this should be fixed in #4556 .

Wrt. #2 we’ve intentionally not included warehouses in the variant resposes. You can definitely get the stock location availability for a variant using a custom endpoint to see exactly where items are available and in which quantities. In your custom endpoint you could use the following methods to join locations for a specific variant: 

```
productVariantInventoryService.listByVariantId

joinLevels (is a util)

stockLocationService.list
```

(docs for adding a custom endpoint are here: https://docs.medusajs.com/development/endpoints/create)

It sounds like what you are planning will probably require you to add custom functionality to medusa at some point, we have some great docs to take you through that process with endpoints, entities, services etc. 😄

**Comment by thejspro** [comment]
Thanks for such a quick reply.

I'm not familiar with the architecture of Medusa, and was wondering if I could do this without using the Services but with the Admin API instead?

Perhaps I could query the product inventory first, then query the product variant for price and return the matching one.

I would hide the API calls to the Admin API behind a server-side Next.js route. Would that work?

I'm a front-end developer primarily, and I'm not very comfortable with the Medusa code.

**Comment by pKorsholm** [comment]
It sounds like that would work out and you could get the locations for a variant. Just beware to not invoke the admin from the client side.

you might want to list locations as well if you need them, but you can just use the endpoint for that as well 😄 

Just note that with regard to pricing etc. and the suppliers you mentioned you might run into coding something serverside at some point
