### ISSUE TITLE
Quick start doesn't work

### ISSUE THREAD

**Issue by ThinkFar** [medusajs/medusa#4562]
When using npx create-medusa-app@latest the following error comes up and makes the setup fail:

npx create-medusa-app@latest
Need to install the following packages:
  create-medusa-app@1.0.3
Ok to proceed? (y) 
? What's the name of your project? my-medusa-store
? Enter your Postgres username postgres
? Enter your Postgres password [hidden]
? Enter an email for your admin dashboard user admin@medusa-test.com
🚀 Starting project setup, this may take a few minutes.
✔ Created project directory
✔ Database medusa--NrJ created
✔ Installed Dependencies
✔ Project Built                                                                                                                                 An error occurred while preparing project: Error: An error occurred while running migrations: npm WARN deprecated @oclif/screen@1.0.4: Deprecated in favor of @oclif/core                                                                                                                       npm WARN deprecated cli-ux@5.6.7: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.

**Comment by shahednasser** [comment]
@ThinkFar can you try changing to the `my-medusa-store` and run `npx @medusajs/medusa-cli@latest migrations run` then share the output here?

**Comment by ThinkFar** [comment]
root@medusa:~/my-medusa-store# npx @medusajs/medusa-cli@latest migrations run
[medusa-config] ⚠️ redis_url not found. A fake redis instance will be used.
[medusa-config] ⚠️ jwt_secret not found. fallback to either cookie_secret or default 'supersecret'.
[medusa-config] ⚠️ cookie_secret not found. fallback to either cookie_secret or default 'supersecret'.
[medusa-config] ⚠️ redis_url not found. A fake redis instance will be used.
[medusa-config] ⚠️ jwt_secret not found. fallback to either cookie_secret or default 'supersecret'.
[medusa-config] ⚠️ cookie_secret not found. fallback to either cookie_secret or default 'supersecret'.
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at DriverUtils.parseConnectionUrl (/root/my-medusa-store/node_modules/typeorm/driver/DriverUtils.js:159:23)
    at DriverUtils.buildDriverOptions (/root/my-medusa-store/node_modules/typeorm/driver/DriverUtils.js:47:43)
    at new PostgresDriver (/root/my-medusa-store/node_modules/typeorm/driver/postgres/PostgresDriver.js:219:51)
    at DriverFactory.create (/root/my-medusa-store/node_modules/typeorm/driver/DriverFactory.js:36:24)
    at new DataSource (/root/my-medusa-store/node_modules/typeorm/data-source/DataSource.js:53:59)
    at /root/my-medusa-store/node_modules/@medusajs/medusa/dist/loaders/database.js:64:42
    at step (/root/my-medusa-store/node_modules/@medusajs/medusa/dist/loaders/database.js:33:23)
    at Object.next (/root/my-medusa-store/node_modules/@medusajs/medusa/dist/loaders/database.js:14:53)
    at /root/my-medusa-store/node_modules/@medusajs/medusa/dist/loaders/database.js:8:71

**Comment by ThinkFar** [comment]
@shahednasser I've attached above.

**Comment by shahednasser** [comment]
Looks like the Postgres URL is incorrect. Can you share the value of `DATABASE_URL` in `.env`? You can replace the sensitive data with anything else, just want to check the format

**Comment by ThinkFar** [comment]
process.env.DATABASE_URL || "postgres://localhost/medusa-store";
–––––––––––
I've literally just typed the quick start command "npx create-medusa-app@latest" on a fresh Debian with all preparations installed. It's reporting that it creates the databases successfully, so I don't understand. The connection must be correct for that to happen.

**Comment by shahednasser** [comment]
can you get the value from `.env`, and not from `medusa-config.js`? According to the error you received above, the URL in the environment variable isn't formatted correctly. This could be due to special characters in the username or password. This isn't related to whether the database was created or not. This could be a bug, so it would be helpful if you can share the value in `.env` to figure out the issue.

**Comment by ThinkFar** [comment]
There is no .env file located in the my-medusa-store directory.

**Comment by shahednasser** [comment]
If a `.env` file does not exist, then the database URL would be `postgres://localhost/medusa-store` which would produce a different error.

Can you try adding the following in `medusa-config.js` after the declaration of `DATABASE_URL`:

```ts
console.log(DATABASE_URL)
```

Just to try a different approach of figuring out the problem here.

**Comment by ThinkFar** [comment]
root@medusa:~/my-medusa-store# npx @medusajs/medusa-cli@latest migrations run                                                                                                                                                               postgres://postgres:PASSWORD@localhost/medusa-1qQV                                                                                                                              [medusa-config] ⚠️ redis_url not found.  A fake redis instance will be used.                                                                                                                                                                 [medusa-config] ⚠️  jwt_secret not found. fallback to either cookie_secret or default 'supersecret'.                                                                                                                                         [medusa-config] ⚠️ cookie_secret  not found. fallback to either cookie_secret or default 'supersecret'.                                                                                                                                      [medusa-config] ⚠️  redis_url not found. A fake redis instance will be used.                                                                                                                                                                 [medusa-config] ⚠️  jwt_secret not found. fallback to either cookie_secret or default 'supersecret'.                                                                                                                                         [medusa-config] ⚠️  cookie_secret not found. fallback to either cookie_secret or default 'supersecret'.                                                                                                                                      URIError: URI malformed                                                                                                                                                                                                                         at decodeURIComponent (<anonymous>)                                                                                                                                                                                                         at DriverUtils.parseConnectionUrl (/root/my-medusa-store/node_modules/typeorm/driver/DriverUtils.js:159:23)                                                                                                                                 at DriverUtils.buildDriverOptions (/root/my-medusa-store/node_modules/typeorm/driver/DriverUtils.js:47:43)                                                                                                                                  at new PostgresDriver (/root/my-medusa-store/node_modules/typeorm/driver/postgres/PostgresDriver.js:219:51)                                                                                                                                 at DriverFactory.create (/root/my-medusa-store/node_modules/typeorm/driver/DriverFactory.js:36:24)                                                                                                                                          at new DataSource (/root/my-medusa-store/node_modules/typeorm/data-source/DataSource.js:53:59)                                                                                                                                              at /root/my-medusa-store/node_modules/@medusajs/medusa/dist/loaders/database.js:64:42                                                                                                                                                       at step (/root/my-medusa-store/node_modules/@medusajs/medusa/dist/loaders/database.js:33:23)                                                                                                                                                at Object.next (/root/my-medusa-store/node_modules/@medusajs/medusa/dist/loaders/database.js:14:53)                                                                                                                                         at /root/my-medusa-store/node_modules/@medusajs/medusa/dist/loaders/database.js:8:71

**Comment by ThinkFar** [comment]
Never mind, I found out what the issue was. I was using a password with unsupported characters.
I guess you can't use special characters.

**Comment by shahednasser** [comment]
Thanks for letting me know! I think we need to resolve that as part of the tool. Can you let me know what the unsupported characters were?

**Comment by ThinkFar** [comment]
@*^%^$!^
These were all the special characters included in the previous unsupported password.
I am not entirely sure which ones are not supported.
