### ISSUE TITLE
Docs(Code Issue): Code Issue in /development/endpoints/create

### ISSUE THREAD

**Issue by odhekar** [medusajs/medusa#4570]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Wrong import statement in sample code for Protected Routes.

The import statement should be  
`import { authenticate } from "@medusajs/medusa";`  
and not  
`import authenticate from "@medusajs/medusa/dist/api/middlewares/authenticate-customer";`

### How can this issue be resolved?

Update the docs to show the correct import statement
`import { authenticate } from "@medusajs/medusa";`

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Hello! Can you share what Medusa version you're using? The import in the docs should work for the latest version (`1.12.3`) of Medusa.

**Comment by odhekar** [comment]
```
  "dependencies": {
    "@medusajs/admin": "^6.0.2-beta-20230705211101",
    "@medusajs/cache-inmemory": "^1.8.7",
    "@medusajs/cache-redis": "^1.8.7",
    "@medusajs/event-bus-local": "^1.9.4",
    "@medusajs/event-bus-redis": "^1.8.7",
    "@medusajs/file-local": "^1.0.1",
    "@medusajs/medusa": "^1.12.2-beta-20230705211101",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "dotenv": "^16.1.4",
    "express": "^4.17.2",
    "medusa-fulfillment-manual": "^1.1.37",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.23",
    "medusa-payment-stripe": "^6.0.0",
    "medusa-plugin-auth": "^1.6.0",
    "typeorm": "^0.3.16"
  },
```

**Comment by shahednasser** [comment]
Ok just checked and you're correct about this. I'll open a PR to fix this. Thanks for submitting the issue!
