### ISSUE TITLE
Sendgrid Plugin 

### ISSUE THREAD

**Issue by iamanle** [medusajs/medusa#4573]
### Describe the bug

I recently installed the sendgrid plugin and encounter the issue of undefined sendMail which is marked as resolved here (https://github.com/medusajs/medusa/issues/4522). I upgraded to the latest sendgrid plugin version then encounter a new bug 

```
3|fliv-medusa-v1  | 130.176.162.72 - - [20/Jul/2023:05:36:12 +0000] "GET /store/products?cart_id=cart_01H5RWQD7AX4YMCMETAJ2YAEEN&id%5B0%5D=prod_01H4QMRWVTR856HXCVYZTR6QNT&is_giftcard=false HTTP/1.1" 200 4120 "-" "Dart/2.19 (dart:io)"
3|fliv-medusa-v1  | {"level":"error","message":"Forbidden","stack":[{"columnNumber":29,"fileName":"node_modules/@sendgrid/client/src/classes/client.js","functionName":null,"lineNumber":146,"methodName":null,"native":false,"typeName":null},{"columnNumber":null,"fileName":null,"functionName":"runMicrotasks","lineNumber":null,"methodName":null,"native":false,"typeName":null},{"columnNumber":5,"fileName":"node:internal/process/task_queues","functionName":"processTicksAndRejections","lineNumber":96,"methodName":null,"native":false,"typeName":null}],"timestamp":"2023-07-20 05:36:13"}
2|fliv-medusa-v1  | 130.176.162.163 - - [20/Jul/2023:05:36:14 +0000] "GET /store/products?cart_id=cart_01H5RWQD7AX4YMCMETAJ2YAEEN&id%5B0%5D=prod_01H4QMRWVTR856HXCVYZTR6QNT&is_giftcard=false HTTP/1.1" 200 4120 "-" "Dart/2.19 (dart:io)"
``` 

### System information

Medusa version (including plugins): 1.10.0
Sendgrid plugin: 1.3.11
Node.js version: 16.20.0
Database: Postgres 
Operating system: Mac, Ubuntu
Browser (if relevant):

### Steps to reproduce the behavior

1. Install sendgrid plugin
2. Set up env as instruction
```
    resolve: `medusa-plugin-sendgrid`,
    options: {
      api_key: process.env.SENDGRID_API_KEY,
      from: 'hello@xyz.ef',
      order_placed_template: 'd-8482c8dab0b84a2d9c61e52d5474a23c',
    },
```
3. Create order

### Expected behavior

Receive email through sendgrid

**Comment by olivermrbl** [comment]
I believe this issue concerns your configuration of SendGrid and not Medusa. I've found this [issue](https://stackoverflow.com/questions/61149142/node-js-sendgrid-mail-403-forbidden-error), that might provide some guidance on how to resolve it.

Let me know if the issue persist.

**Comment by iamanle** [comment]
thank you for taking a look
