### ISSUE TITLE
calculated_price showing price from a price list that does not apply to the customer browsing the site

### ISSUE THREAD

**Issue by sam-thewise** [medusajs/medusa#4576]
### Describe the bug

I have multiple price lists for different customer groups. 

I have a customer that is part of group "GROUP1" They have a price of $7 for an item. Let's call him "customer A"
I have another group with a price list attached called "GROUP2" They have a price of $5 for an item.

When retrieving the product from the front end using the /store/products endpoint, logged in as "customer A" who is part of "GROUP1", the calculated_price for the product appears to be the price for "GROUP2".

### System information

Medusa version (including plugins): 1.11.0
Node.js version: 18
Database: PostgreSQL
Operating system: Linux
Browser (if relevant): Chrome

### Steps to reproduce the behavior

Create a group, GROUP1.
Create a price list for GROUP1, an override, link to to GROUP1.
Add a price for an SKU at $7.
Assign that group to customer A.

Create another group GROUP2.
Create a price list for GROUP2, an override list, link to GROUP2.
Add a price for an SKU at $5.

Call the /store/products endpoint when logged in with "customer A" in the front end.

The calculated_price will be the price for GROUP2.

### Expected behavior

Customer A should have a calculated_price for $7, not $5 from GROUP2.

**Comment by pKorsholm** [comment]
should be fixed by #4578
