### ISSUE TITLE
Transactional Emails - SendGrid

### ISSUE THREAD

**Issue by srindom** [medusajs/medusa#46]
We need a plugin: `medusa-plugin-sendgrid`, which will hook into `order.placed` events and sends an order confirmation to the customer. Other emails may also be relevant.

**Comment by olivermrbl** [comment]
In `medusa-config.js`, define the templates to use for the different events: template_ids

Create service, that can send whatever emails are desired

Subscribe to order.placed
Subscribe to order.update -> tracking number
Subscribe to order.cancelled
