### ISSUE TITLE
Unable to import the products using .csv file from medusa-admin

### ISSUE THREAD

**Issue by HarkiratShopism1** [medusajs/medusa#4610]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I want to bulk upload the products from my previous database to medusa for that I am using minio file system with medusa-backend and I tried to import the products using a .csv file to the medusa-admin but the file is not getting accepted or its throwing an error in the notification bar as "Error Import Failed" or previously I was getting "Batch job cancelled".

These are the steps I am following to import products -
1. Open medusa-admin
2. Navigate to the products page
3. Click on import file button
4. Modal opens -> upload the .csv file

Please find attached the file type I am using 
[Bib products.csv](https://github.com/medusajs/medusa/files/12180336/Bib.products.csv)

Thank you 

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by olivermrbl** [comment]
@HarkiratShopism1 – as far as I can tell, you are not using the provided schema.

There are several incorrect columns in the file you've attached here e.g. "Product id" should be "Product Id" and "Product Mid Code" should be "Product MID Code".

Please download a new template from admin and try again :)
