### ISSUE TITLE
I created another user using npx @medusajs/medusa-cli user -e test@email.com -p pass but Anable to login using it

### ISSUE THREAD

**Issue by Pavanpatil0744** [medusajs/medusa#4628]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Hello,
I have created one user using 
npx @medusajs/medusa-cli user -e test@email.com -p pass

and after some time I created a new user with the same command but could not log in with the second user
getting These credentials do not match our records. while logging.
Please assist.

Regards,
pavan patil.

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
@Pavanpatil0744 when you run the command the second time, what's the output you see? Can you share both the command and the output?

**Comment by pevey** [comment]
You will also get this error if the browser is unable to reach the server, which could be caused by many possible issues.  The most common are the server is unreachable (not running or 404) or because of a CORS error.  Opening your browser console to see the error will help you troubleshoot.

**Comment by shahednasser** [comment]
Closing this issue for lack of response.
