### ISSUE TITLE
Cyclic dependency: "Discount"

### ISSUE THREAD

**Issue by CervarlCG** [medusajs/medusa#4633]
### Describe the bug

When extending the Discount model and tried to create an discount on the admin dashboard (or API) i'm getting the next error 
`error: Cyclic dependency: "Discount"
TypeORMError: Cyclic dependency: "Discount"`

```
import { Column, Entity, JoinColumn, ManyToOne, Index, Tree } from "typeorm";
import { Discount as MedusaDiscount } from "@medusajs/medusa";
import { Store } from "./store";

@Entity()
@Index("discount_storeid_code_unique_constraint", ["store", "code"], {
  where: "deleted_at IS NULL",
})
export class Discount extends MedusaDiscount {
  @Column()
  code: string;

  @Column({ nullable: false })
  store_id: string;

  @ManyToOne(() => Store, (store) => store.id)
  @JoinColumn({ name: "store_id" })
  store: Store;
}

```
### System information

Medusa version (including plugins): 1.13.0
Node.js version: 16.16.0
Database: PostgreSQL 15.1 (Ubuntu 15.1-1.pgdg20.04+1) on aarch64-unknown-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit
Operating system: Ubuntu 22.04.2 LTS
Browser (if relevant): Chrome

### Steps to reproduce the behavior

1. Go to src/models and create a class that extends the discount entity
2. Try to create a discount

### Expected behavior

The record is created on the database

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by CervarlCG** [comment]
Ok after debugging i fixed it by reimplementing the parent_discount that point to itself but for some reason when extending the Discount entity it stopped working

```
@Entity()
@Index("discount_storeid_code_unique_constraint", ["store", "code"], {
  where: "deleted_at IS NULL",
})
export class Discount extends MedusaDiscount {
  @ManyToOne(() => Discount)
  @JoinColumn({ name: "parent_discount_id" })
  parent_discount: Discount;

  @Column({ nullable: false })
  store_id: string;

  @ManyToOne(() => Store, (store) => store.id)
  @JoinColumn({ name: "store_id" })
  store: Store;
}

```

**Comment by jaiminTH** [comment]
@CervarlCG  I Just wanted to thank you for solving my problem. Your help made a big difference! 🤩
