### ISSUE TITLE
Generate store API fixtures for Product Variant

### ISSUE THREAD

**Issue by olivermrbl** [medusajs/medusa#464]
Generate fixtures for models returned by our API. Instead of having one huuuge file with all of our fixtures, we would like to split these up, such that we have a dedicated file for each entity.

This ticket is for **Store Product Variant**

API Fixtures checklist → https://www.notion.so/medusajs/API-Fixtures-checklist-5abf366ac6784d4681344b97b3d4aedf

Loom on how to do API fixtures: https://www.loom.com/share/230b0c3ec59144bebbfa7029d31fd1fb

**Comment by olivermrbl** [comment]
Hi @JakeVdub ! Did you get a chance to figure this one out? Would love to help out, if you have any questions :)

**Comment by JakeVdub** [comment]
I did not get a chance to figure this out, if somebody else wants to take the issue they are free to
