### ISSUE TITLE
Fix minor issue regarding create fulfillment for an order docs

### ISSUE THREAD

**Issue by specture48** [medusajs/medusa#4644]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

regarding order fulfillment creation section
there is minor mistake 

https://docs.medusajs.com/references/services/classes/OrderService#createfulfillment

![image](https://github.com/medusajs/medusa/assets/26096372/7507a4c3-0afa-4ea1-8dd5-6a7858ed5eeb)

### How can this issue be resolved?

just rename these two lines

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for spotting this! You can fix these issues in the comments [here](https://github.com/medusajs/medusa/blob/483bf2e544275b977259dfe8b47a766a8d93051d/packages/medusa/src/services/order.ts#L1358-L1367)
