### ISSUE TITLE
products relation cannot be expanded as mentioned in docs in store->get collection endpoint

### ISSUE THREAD

**Issue by specture48** [medusajs/medusa#4647]
## Bug report
products relation cannot be expanded as mentioned in docs in store->get collection endpoint
### System information

Medusa version (including plugins):
Node.js version:18
Database:postgresql

### Steps to reproduce the behavior

1. Go to 
/store/collections/:id?expand=products
2. result is like
result:
{
    "collection": {
        "id": "pcol_01H6NZF3V6SF05YPNCKC9F9M73",
        "created_at": "2023-07-31T12:41:15.363Z",
        "updated_at": "2023-07-31T12:41:15.363Z",
        "deleted_at": null,
        "title": "dsa",
        "handle": "dsa",
        "metadata": null
    }
}

### Expected behavior
result:
{
    "collection": {
        "id": "pcol_01H6NZF3V6SF05YPNCKC9F9M73",
        "created_at": "2023-07-31T12:41:15.363Z",
        "updated_at": "2023-07-31T12:41:15.363Z",
        "deleted_at": null,
        "title": "dsa",
        "handle": "dsa",
        "metadata": null,
        "products":[]
    }
}

#reasons
the main issue here, retrieve is taking only the id, not expand options(it ignores the expand options)
https://github.com/medusajs/medusa/blob/develop/packages/medusa/src/api/routes/store/collections/get-collection.ts#L53

### Additional context
docs 
https://docs.medusajs.com/api/store#tag/Collections/operation/GetCollectionsCollection

**Comment by olivermrbl** [comment]
Thanks for highlighting. You're right, this is not currently supported. Happy to accept a PR with the changes :)

Until it ships, you can filter products by collection id like so:
```
GET /store/products?collection_id[]=some_id
```

**Comment by specture48** [comment]
but what about pagination of products relation, maybe it is better to keep the search by "products?collection_id[]=some_id"
and just remove it from docs

@olivermrbl 
wdut?

**Comment by srindom** [comment]
@specture48 yes this is a good point - there is a docs issue on this here: https://github.com/medusajs/medusa/issues/4809

Will close this :)
