### ISSUE TITLE
Goods export transactions require a billing and a shipping address.

### ISSUE THREAD

**Issue by imash96** [medusajs/medusa#4661]
### System information

Medusa version (including plugins): 1.12.3
Node.js version: 18
Database: postgres
Operating system:
Browser (if relevant):

### Steps to reproduce the behavior

1. Go to checkout page
2. Click on Checkout button
3. See error

How to add shipping_details to stripe request

**Comment by imash96** [comment]
@olivermrbl @adrien2p can you please help me.

**Comment by imash96** [comment]
@olivermrbl @adrien2p please help

**Comment by adrien2p** [comment]
@imash96 can you please stop pinging everyday, it is becoming annoying. We are doing our best to prioritize issues. we will come back to you as soon as we can, in the mean time I let you feel all the missing information you havn't provided please

**Comment by srindom** [comment]
@imash96 - I am not sure what the issue is here can you please describe it in more detail?

**Comment by imash96** [comment]
Hi @srindom,

I am using you storefront stater and with only some ui modification 

When I click on checkout button on checkout page after selection Stripe Credit Card as payment method I am receiveing error as shown in screenshot. Also I have searched a lot but didn't find any method to set shipping method during checkout.

![image](https://github.com/medusajs/medusa/assets/18481370/8e740e4f-86a3-41c1-9901-0b284d47a4a9)

Can you please help me to resolve it.

**Comment by imash96** [comment]
@olivermrbl please help 🙏 how to achieve this.

![IMG_20230829_235816](https://github.com/medusajs/medusa/assets/18481370/ebb533fa-f530-4dc1-8663-8832695c2617)

**Comment by imash96** [comment]
Hi,

As I figured out medusa PaymentProviderService has a method createSession which call provider.initiatePayment of [medusa-payment-stripe](https://github.com/medusajs/medusa/tree/develop/packages/medusa-payment-stripe)/[src](https://github.com/medusajs/medusa/tree/develop/packages/medusa-payment-stripe/src)/[core](https://github.com/medusajs/medusa/tree/develop/packages/medusa-payment-stripe/src/core)/stripe-base.ts

method initiatePayment receive customer as well as email in context and while creating customer for stripe
stripe_.customers.create({email})
Only customer email is send in the payload I think for my case I have to send customer.shipping_addresses in payload.

How can I override initiatePayment method of medusa-payment-stripe

If I cannot override the initiatePayment can you please add this to your code and have a flag in medusa-config.js to add customer.shipping_addresses to payload while creating customer in stripe

Thank you

**Comment by imash96** [comment]
I am really sorry for this. I got this issue resolved.
In future If anyone getting this issue please do the following.
In you payment button where you call the confirmCardPayment method pass the shipping detail outside payment_method.
I was adding shipping detail in payment_method that why I was getting errors.

> stripe.confirmCardPayment(session.data.client_secret as string, {
>     payment_method: {
>         card: cardElement,
>         billing_details: { .... },
>     },
>     shipping: { ... }
