### ISSUE TITLE
DELETE draft order always returns 200, even if invalid id

### ISSUE THREAD

**Issue by BorisKamp** [medusajs/medusa#4663]
Im using medusa `1.12.2` on node `v18.16.1` on my Mac on localhost.

Whenever I call `{{medusa-host}}/admin/draft-orders/:id` I get a `200` success response. Even when I call `{{medusa-host}}/admin/draft-orders/sadfc` for example. I expect a `404` not found in this case.

Am I the only one or can anybody else confirm?

**Comment by olivermrbl** [comment]
@BorisKamp, our DELETEs are idempotent and will respond with 200 regardless of whether the resource exists or not.
