### ISSUE TITLE
Price list customer group selector is broken in the admin portal

### ISSUE THREAD

**Issue by BorisKamp** [medusajs/medusa#4664]
Im using medusa `1.12.2` on node `v18.16.1` on my Mac on localhost.

1. Go to http://localhost:9000/app/a/pricing/new
2. Click `configuration` and toggle `Customer availabilty` on.
3. (make sure you have existing customer groups)
4. Click in the select box and start typing. Nothing happens.

What i expect:
1. Show all groups when clicking the select box, just like the other selectboxes in the admin portal.
2. filter the results when typing.

See a video of what I see here: https://www.awesomescreenshot.com/video/19601231?key=e509741b7f2a0e84c7cbf9c583293ff8

**Comment by olivermrbl** [comment]
Thanks for highlighting. Solved in #4670 :)
