### ISSUE TITLE
Backend deployment to Railway fails

### ISSUE THREAD

**Issue by masterleopold** [medusajs/medusa#4668]
### Describe the bug

I've tried to deploy the backend to Railway by following [docs](https://docs.medusajs.com/deployments/server/deploying-on-railway) but it fails initializing that shows "Deployment Failed during build process" on Railway. 

### System information

Medusa version (including plugins): 1.13.1-beta-20230727162508
Node.js version: v18.16.0
Database: postgres
Railway Plan: Hobby Plan (Memory per container: 8GB, CPU per container 8 vCPU)

### Steps to reproduce the behavior

1. Create and setup Medusa project by following [this doc](https://docs.medusajs.com/create-medusa-app)
2. Deploy the backend to Railway by following [this doc](https://docs.medusajs.com/deployments/server/deploying-on-railway)

### Screenshots
Railway variables
<img width="851" alt="Screenshot 2023-08-02 at 15 24 04" src="https://github.com/medusajs/medusa/assets/461528/aef35df8-93ec-48e9-81b4-2c6352563920">

### Code snippets

Build logs
>  ﻿
#1 [internal] load .dockerignore
﻿#1 transferring context: 2B done
﻿#1 DONE 0.1s
﻿#2 [internal] load build definition from Dockerfile
﻿#2 transferring dockerfile: 2.28kB done
﻿#2 DONE 0.1s
﻿﻿#3 [internal] load metadata for ghcr.io/railwayapp/nixpacks:ubuntu-1690243402
﻿#3 DONE 0.1s
﻿#4 [stage-0  1/10] FROM ghcr.io/railwayapp/nixpacks:ubuntu-1690243402@sha256:1a7dc562bf1f13299c20e55f8a72a287cb16dfea072fe4d20d084cfe23494afd
﻿#4 DONE 0.0s
﻿#5 [internal] load build context
﻿#5 transferring context: 104.44kB done
﻿#5 DONE 0.1s
﻿#6 [stage-0  2/10] WORKDIR /app/
﻿#6 CACHED
﻿#7 [stage-0  3/10] COPY .nixpacks/nixpkgs-293a28df6d7ff3dec1e61e37cc4ee6e6c0fb0847.nix .nixpacks/nixpkgs-293a28df6d7ff3dec1e61e37cc4ee6e6c0fb0847.nix
﻿#7 CACHED
﻿#8 [stage-0  4/10] RUN nix-env -if .nixpacks/nixpkgs-293a28df6d7ff3dec1e61e37cc4ee6e6c0fb0847.nix && nix-collect-garbage -d
﻿#8 CACHED
﻿#9 [stage-0  5/10] COPY . /app/.
﻿#9 DONE 0.1s > ﻿#10 [stage-0  6/10] RUN --mount=type=cache,id=s/2a092d57-73cb-4844-8728-97a2b4dede44-/root/npm,target=/root/.npm npm
> ﻿﻿#10 1.060 npm WARN config production Use `--omit=dev` instead.
﻿﻿﻿> #10 3.980 npm ERR! code ERESOLVE
﻿#10 3.983 npm ERR! ERESOLVE unable to resolve dependency tree
﻿#10 3.983 npm ERR!
﻿#10 3.983 npm ERR! While resolving: medusa-starter-default@0.0.1
﻿#10 3.983 npm ERR! Found: @medusajs/medusa@1.13.1-beta-20230727162508
﻿#10 3.983 npm ERR! node_modules/@medusajs/medusa
﻿#10 3.984 npm ERR!   @medusajs/medusa@"1.13.1-beta-20230727162508" from the root project
﻿#10 3.984 npm ERR!
﻿#10 3.984 npm ERR! Could not resolve dependency:
﻿#10 3.984 npm ERR! peer @medusajs/medusa@"1.12.4-snapshot-20230721100123" from @medusajs/admin@7.0.0-snapshot-20230721100123
﻿#10 3.984 npm ERR! node_modules/@medusajs/admin
﻿#10 3.984 npm ERR!   @medusajs/admin@"^7.0.0-beta-20230727162508" from the root project
﻿#10 3.984 npm ERR!
﻿#10 3.984 npm ERR! Fix the upstream dependency conflict, or retry
﻿#10 3.984 npm ERR! this command with --force, or --legacy-peer-deps
﻿#10 3.984 npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
﻿#10 3.984 npm ERR!
﻿#10 3.984 npm ERR! See /root/.npm/eresolve-report.txt for a full report.
﻿#10 3.986
﻿#10 3.986 npm ERR! A complete log of this run can be found in:
﻿#10 3.986 npm ERR!     /root/.npm/_logs/2023-08-02T05_58_51_316Z-debug-0.log
﻿#10 ERROR: process "/bin/bash -ol pipefail -c npm i" did not complete successfully: exit code: 1
﻿[stage-0  6/10] RUN --mount=type=cache,id=s/2a092d57-73cb-4844-8728-97a2b4dede44-/root/npm,target=/root/.npm npm i:
﻿#10 3.984 npm ERR!   @medusajs/admin@"^7.0.0-beta-20230727162508" from the root project
﻿#10 3.984 npm ERR!
﻿#10 3.984 npm ERR! Fix the upstream dependency conflict, or retry
﻿#10 3.984 npm ERR! this command with --force, or --legacy-peer-deps
﻿#10 3.984 npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
﻿#10 3.984 npm ERR!
﻿#10 3.984 npm ERR! See /root/.npm/eresolve-report.txt for a full report.
﻿#10 3.986
﻿#10 3.986 npm ERR! A complete log of this run can be found in:
﻿#10 3.986 npm ERR!     /root/.npm/_logs/2023-08-02T05_58_51_316Z-debug-0.log
﻿-----
﻿Dockerfile:20
﻿-------------------
﻿18 |     ENV NIXPACKS_PATH /app/node_modules/.bin:$NIXPACKS_PATH
﻿19 |     COPY . /app/.
﻿20 | >>> RUN --mount=type=cache,id=s/2a092d57-73cb-4844-8728-97a2b4dede44-/root/npm,target=/root/.npm npm i
﻿21 |
﻿22 |     # build phase
﻿-------------------
﻿ERROR: failed to solve: process "/bin/bash -ol pipefail -c npm i" did not complete successfully: exit code: 1
﻿Error: Docker build failed
﻿
----
`package.json`
> {
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Sebastian Rindom <skrindom@gmail.com>",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "clean": "cross-env ./node_modules/.bin/rimraf dist",
    "build": "cross-env npm run clean && npm run build:server && npm run build:admin",
    "build:server": "cross-env npm run clean && tsc -p tsconfig.json",
    "build:admin": "cross-env medusa-admin build",
    "watch": "cross-env tsc --watch",
    "test": "cross-env jest",
    "seed": "cross-env medusa seed -f ./data/seed.json",
    "start": "cross-env npm run build && medusa start",
    "start:custom": "cross-env npm run build && node --preserve-symlinks --trace-warnings index.js",
    "dev": "cross-env npm run build:server && medusa develop"
  },
  "dependencies": {
    "@medusajs/admin": "^7.0.0-beta-20230727162508",
    "@medusajs/cache-inmemory": "^1.8.7",
    "@medusajs/cache-redis": "^1.8.7",
    "@medusajs/event-bus-local": "^1.9.4",
    "@medusajs/event-bus-redis": "^1.8.7",
      "@medusajs/file-local": "^1.0.1",
      "@medusajs/medusa": "1.13.1-beta-20230727162508",
    "@tanstack/react-query": "4.22.0",
    "babel-preset-medusa-package": "^1.1.13",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "dotenv": "16.0.3",
    "express": "^4.17.2",
    "medusa-fulfillment-manual": "^1.1.37",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.23",
    "medusa-payment-stripe": "^6.0.2",
    "prism-react-renderer": "^2.0.4",
    "typeorm": "^0.3.16"
  },
  "devDependencies": {
    "@babel/cli": "^7.14.3",
    "@babel/core": "^7.14.3",
    "@babel/preset-typescript": "^7.21.4",
    "@medusajs/medusa-cli": "^1.3.16",
    "@types/express": "^4.17.13",
    "@types/jest": "^27.4.0",
    "@types/node": "^17.0.8",
    "babel-preset-medusa-package": "^1.1.13",
    "cross-env": "^7.0.3",
    "eslint": "^6.8.0",
    "jest": "^27.3.1",
    "mongoose": "^5.13.14",
    "rimraf": "^3.0.2",
    "ts-jest": "^27.0.7",
    "ts-loader": "^9.2.6",
    "typescript": "^4.5.2"
  },
  "jest": {
    "globals": {
      "ts-jest": {
        "tsconfig": "tsconfig.spec.json"
      }
    },
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "testPathIgnorePatterns": [
      "/node_modules/",
      "<rootDir>/node_modules/"
    ],
    "rootDir": "src",
    "testRegex": "(/__tests__/.*|\\.(test|spec))\\.(ts|js)$",
    "transform": {
      ".ts": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "./coverage",
    "testEnvironment": "node"
  }
}
------

### Additional context

I'm attaching my `medusa-config.js` file
[medusa-config.js.zip](https://github.com/medusajs/medusa/files/12236605/medusa-config.js.zip)

**Comment by srindom** [comment]
This was solved in Discord I believe? Issue was a faulty yarn.lock - fix was to delete the lock file, run yarn again and commit.

**Comment by masterleopold** [comment]
> This was solved in Discord I believe? Issue was a faulty yarn.lock - fix was to delete the lock file, run yarn again and commit.

Yes, thanks @srindom
