### ISSUE TITLE
Not getting shipping option after I add min max subtotal

### ISSUE THREAD

**Issue by onamkrverma** [medusajs/medusa#4671]
### Describe the bug
I have 3 shipping options and added Min. subtotal and Max. subtotal in one of these in requirement list. But after adding these requirements. I am not getting those shipping option in Api response and if i remove these requirements then i am getting all 3 shipping options.

### System information

Medusa version (including plugins):
Node.js version: 
Database:
Operating system:
Browser (if relevant):

### Steps to reproduce the behavior

1. Go to admin dashboard setting 
2. Click on region and add Min. subtotal and Max. subtotal in shipping options requirement.
3. Call this [shipping option](https://docs.medusajs.com/api/store#tag/Shipping-Options/operation/GetShippingOptions) api 

### Expected behavior
It should list all available shipping options whatever Min. subtotal and Max. subtotal requirement added in shipping options or not.

### Screenshots
1. Added Min. subtotal and Max. subtotal in DHL shipping options.
![image](https://github.com/medusajs/medusa/assets/106578262/db976267-cb58-4fe7-8bbf-63015bef5d8e)

2. I am getting Fedex and Indian post but not getting DHL in shipping options response
<img width="661" alt="image" src="https://github.com/medusajs/medusa/assets/106578262/c1e9ea6a-b0c4-4603-b3a8-1727e9f1fdbe">

3. After Removing Min. subtotal and Max. subtotal from DHL shipping options
![image](https://github.com/medusajs/medusa/assets/106578262/f1658e00-79f3-4298-9d8d-1676d6975b1f)

4. Now i am getting all 3 shipping options including DHL in api response.
<img width="654" alt="image" src="https://github.com/medusajs/medusa/assets/106578262/5805b972-9b72-4957-a6c9-f800378ff3bf">

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by jaymehta20** [comment]
After adding the min-max subtotal in the admin dashboard the delivery option doesn't show on the front end could be that the cart total doesn't fall in the range of the min-max subtotal of your admin dashboard.

Try min 1 and max 1000 in all delivery options and buy something less than 1000 and check if the issue still persists

**Comment by onamkrverma** [comment]
@jaymehta20 Thanks, you said right because of cart total does not fall in that min-max subtotal range that's why that shipping option was not showing.

**Comment by rightalign-io** [comment]
hi, did you ever come right with this - no one is helping me with this error for month now on discord and i sm following google now trying to fix this damn thing?

**Comment by onamkrverma** [comment]
> hi, did you ever come right with this - no one is helping me with this error for month now on discord and i sm following google now trying to fix this damn thing?

@rightalign-io Please read above comments, solution discussed in above comments
