### ISSUE TITLE
Incorrect amount deducted for return shipping

### ISSUE THREAD

**Issue by magdafiktus** [medusajs/medusa#4686]
Describe the bug
When receiving returns an incorrect amount is deducted from the refund for most Danish orders (but not all)

System information
"@medusajs/admin": "6.0.1",
"@medusajs/cache-redis": "1.8.8",
"@medusajs/event-bus-redis": "1.8.8",
"@medusajs/inventory": "1.9.1",
"@medusajs/medusa": "^1.12.1",
"@medusajs/medusa-cli": "1.3.16",
"@medusajs/stock-location": "1.9.1",
"@types/express": "^4.17.17",
"babel-preset-medusa-package": "1.1.19",
"contentful": "^7.14.7",
"cors": "^2.8.5",
"cross-env": "^7.0.2",
"csv-stringify": "5.3.2",
"easy-soap-request": "^3.3.3",
"express": "^4.17.1",
"joi": "^17.3.0",
"medusa-core-utils": "1.2.0",
"medusa-file-spaces": "1.3.7",
"medusa-fulfillment-webshipper": "1.3.11-snapshot-20230626084333",
"medusa-interfaces": "1.3.7",
"medusa-payment-adyen": "1.1.44",
"medusa-payment-klarna": "1.3.10",
"medusa-payment-manual": "1.0.24",
"medusa-payment-paypal": "6.0.1",
"medusa-payment-stripe": "6.0.1",
"medusa-plugin-brightpearl": "1.3.10-snapshot-20230621150344",
"medusa-plugin-contentful": "1.2.10",
"medusa-plugin-discount-generator": "1.1.27",
"medusa-plugin-ip-lookup": "1.2.8",
"medusa-plugin-meilisearch": "2.0.8",
"medusa-plugin-restock-notification": "7.0.2",
"medusa-plugin-segment": "1.3.6",
"medusa-plugin-sendgrid": "1.3.9",
"medusa-plugin-sentry": "^1.4.2",
"medusa-plugin-slack-notification": "1.3.9",
"medusa-plugin-wishlist": "1.1.43",
"medusa-test-utils": "^1.1.41",

Steps to reproduce the behavior
receive returns

<img width="614" alt="Screenshot 2023-08-03 at 11 04 40" src="https://github.com/medusajs/medusa/assets/116171296/f644275b-8746-4fdf-b4e3-42bad3ad0633">

Expected behavior
the amount is correct

**Comment by srindom** [comment]
It's very hard for us to resolve bugs without further details - would be helpful if you could add more information. For example:

1. What is "the correct amount"? As in, what is the numerical value you expect to see?
2. You mention that it only happens for some Danish orders - have you noticed a pattern?
3. Please add more details to the steps to reproduce. I.e., I assume that a return was created for the order before you clicked receive - so how was it created? By a customer (through the API), by you (through the admin panel), did you add shipping, etc.

**Comment by magdafiktus** [comment]
1. The correct amount for Danish returns should be 50 DKK. The correct amount for the German order (127120) should be 12 €. I would never expect to see a number with decimals. 
2. It does not only happen to Danish orders. However, it might be limited to countries with VAT included. 
3. The return shipping will only appear if return shipping was added when creating the return. When creating the returns, the cost of the return shipping is set automatically. The customer cannot change it. We can change it, however, we would only change it is we give them free shipping and change it to 0. 
We cannot see if a return has been created by the customer or us, and therefore I'm unable to conduct research.

**Comment by josipmatichr** [comment]
Hi! The issue could potentially be in the way shippingTotal is calculated when return is created using store api - the shippingMethod.price could potentially have tax included so most likely additional tax is being included here.

When creating a return through admin this doesn't seem to happen since the condition is not fulfilled, i.e. data.refund_amount is not undefined.

<img width="1126" alt="image" src="https://github.com/medusajs/medusa/assets/17700878/e7645ab7-027a-4fa8-ab2e-71ca52527fe5">

What do you think?
