### ISSUE TITLE
Generate store API fixture for Swaps

### ISSUE THREAD

**Issue by olivermrbl** [medusajs/medusa#469]
Generate fixtures for models returned by our API. Instead of having one huuuge file with all of our fixtures, we would like to split these up, such that we have a dedicated file for each entity.

This ticket is for **Store Swap fixture**

API Fixtures checklist → https://www.notion.so/medusajs/API-Fixtures-checklist-5abf366ac6784d4681344b97b3d4aedf

Loom on how to do API fixtures: https://www.loom.com/share/230b0c3ec59144bebbfa7029d31fd1fb

**Comment by Dgiulian** [comment]
Hello, I would like to work on this issue

**Comment by olivermrbl** [comment]
Sure @Dgiulian ! That would be great. Let me know, if you need any help getting started :)

**Comment by olivermrbl** [comment]
Closed #492 . Many thanks @Dgiulian 👍
