### ISSUE TITLE
Invite Service is not exported in Services

### ISSUE THREAD

**Issue by louismurerwa** [medusajs/medusa#4690]
Hello Folks,

I am in the process of trying to extend the InviteService in Meddusa but it seems its not exported here -> https://github.com/medusajs/medusa/blob/develop/packages/medusa/src/services/index.ts.

Could someone help me with this issue?

**Comment by okechukwu0127** [comment]
@louismurerwa I just experience this same issue as I try to extend the inviteService

I checked  `node_modules/@medusajs/medusa/dist/services/index.d.ts` and realized that `export { default as InviteService } from "./invite";` is missing from the list.


After adding it myself, I was able to import the inviteService but when i build, i get the error

`Error starting server
Error: Cannot register inviteService. Make sure to default export a service class in /Users/oeze/Documents/asharami/ash-market/ash-market/dist/services/invite.js`


So as it stands, extending it myself causes the application to brake after build.

Can any one assist me on this ?
