### ISSUE TITLE
Product View Page is not working

### ISSUE THREAD

**Issue by Pardhu-lekkala** [medusajs/medusa#4691]
Hi Everyone,

1)I made medusa frontend and admin deployed at aws s3.Everything is working but when i click on product to view for product details and checkout process it throwing below error:
But in local it's working fine
![image](https://github.com/medusajs/medusa/assets/89535944/31c9dff7-c2aa-4eef-baf6-927bd0558120)

2)Am able to upload thumbnails for products,It showing successfully uploaded but if come to products section the thumbnails are broken images because in products api  thumbnail is null but on upload it showed successful,It's happening in localhost also:
![image](https://github.com/medusajs/medusa/assets/89535944/bca4e651-6e9f-4fba-b47a-47b731424d2a)

Below are the deployed s3 links for medusa:
http://medusa-admin.s3-website.ap-south-1.amazonaws.com
http://e-comerce-main.s3-website.ap-south-1.amazonaws.com

Please get me out from this issue!

**Comment by bvhml** [comment]
Hi, I'm facing the same issue. I saw that the URL for the images is using http://localhost:9000 although I've changed the MEDUSA_ADMIN_BACKEND_URL to a different value.

**Comment by bvhml** [comment]
[https://docs.medusajs.com/plugins/file-service/local](medusaJS-docs)
Check your medusa-config.js to include the plugin with the required options:

medusa-config.js
```js
const plugins = [
  // ...
  {
    resolve: `@medusajs/file-local`,
    options: {
      // optional
    },
  },
]
```

Options
You can pass the plugin the following options:

upload_dir: a string indicating the relative path to upload the files to. By default, it's uploads/images.
**backend_url**: a string indicating the URL of your backend. This is helpful if you deploy your backend or change the port used. By default, it's http://localhost:9000.

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
