### ISSUE TITLE
create-medusa-app fails with error: Cannot find module '@medusajs/types'

### ISSUE THREAD

**Issue by a11rew** [medusajs/medusa#4699]
### Describe the bug

Creating a new Medusa project using the create-medusa-app cli as described in the documentation fails with the error "Cannot find module '@medusajs/types'".

This happens with any of the package managers; yarn, npm or pnpm

### System information

Medusa version (including plugins): create-medusa-app@1.0.4
Node.js version: v18.16.0
Database: PostgresQL
Operating system: MacOS Ventura 13.5
Browser (if relevant):

### Steps to reproduce the behavior

1. Run yarn create medusa-app with a fresh install of create-medusa-app

### Expected behavior

The CLI loads, allowing the user to scaffold an app

### Screenshots

![Screenshot 2023-08-05 at 10 59 02 AM](https://github.com/medusajs/medusa/assets/87580113/4d7b6fb3-bb3b-456d-98e5-83bb28b06b87)

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by olivermrbl** [comment]
This was fixed in 1.0.4. You must have a cache that needs busting. 

On mac, please do `rm -rf ~/.npm/_npx/` or wherever your `npx` cache is located and run the `create-medusa-app` command again :)
