### ISSUE TITLE
Jack Simms wants to pay 0 GBP to have this issue fixed

### ISSUE THREAD

**Issue by SoftwareSimms** [medusajs/medusa#4700]
Please help me set this up 
 For more details visit [https://mintycode.io](https://mintycode.io/profile?action=CREATOR_SUPPORT_MODAL&requestId=a3c43574-0cfe-4044-83e6-045bb89783ab&owner=medusajs&name=medusa)

**Comment by olivermrbl** [comment]
Anything unrelated to bugs, should use GitHub Discussions :)
