### ISSUE TITLE
Admin: Delete region button

### ISSUE THREAD

**Issue by olivermrbl** [medusajs/medusa#471]
Currently, our admin system does not support deleting a region. We should simply add a button, that sends: 
`DELETE /admin/regions/:region_id`

[Set up your project to get started with admin](https://docs.medusa-commerce.com/how-to/create-medusa-app)

[Link to admin repo](https://github.com/medusajs/admin)

Add an "ellipsis drowdown" by the red rectangle shown below:
![image](https://user-images.githubusercontent.com/59018053/136352855-998b12de-443c-4f6e-95e4-8af7e845b9d2.png)

The drop down can pretty much be copy / pasted from order details overview. Then simply change the options.

**Comment by sridhar-5** [comment]
@Sukriti-sood are you working on this? if not I'm interested in taking up this issue.

**Comment by Sukriti-sood** [comment]
I am working on it,will update soon

**Comment by prabureddy** [comment]
Hi @olivermrbl 

Can I take up this issue? I will be completing it soon with Delete API integration
