### ISSUE TITLE
Add Ordering to List Products 

### ISSUE THREAD

**Issue by srindom** [medusajs/medusa#472]
In [`GET /admin/products`](https://github.com/medusajs/medusa/blob/master/packages/medusa/src/api/routes/admin/products/list-products.js) and [`GET /store/products`](https://github.com/medusajs/medusa/blob/master/packages/medusa/src/api/routes/store/products/list-products.js) clients should be able to specify the ordering of the results through an `order` query param.

The API should work like this:
`?order=title` should return products ordered by title in lexicographical order
`?order=-title` should return products ordered by title in reverse lexicographical order
`?order=created_at` should return products ordered by creation date oldest to newest
`?order=-created_at` should return products ordered by creation date newest to oldest

The change should parse the query param and send the correct `listConfig` to the service layer e.g. `?order=-created_at` should result in:
```
const listConfig = {
  ...,
  order: { created_at: "DESC" }
}
```

Ordering should only be allowed for `title, created_at, updated_at` for now.

Testing should include unit tests for the API controllers and integration tests for the endpoints with at least 3 products.

**Comment by adrien2p** [comment]
Should not we allow the user to send an array of type `{ column: string; id: 'ASC' | 'DESC' ; }[]` I think its more explicit for new user in a code base than adding `-` to the field what do you think ? It is also more straight forward to build the correct query I think

**Comment by adrien2p** [comment]
I also think we should be able to order by any column available in the entity and not restricting the fields. Validating that the column is part of the schema can be done dynamically.
