### ISSUE TITLE
medusa-plugin-algolia doesn't sync updated values in products index

### ISSUE THREAD

**Issue by DmitryYegorov** [medusajs/medusa#4721]
### Describe the bug

` "@medusajs/admin": "^3.0.0",
    "@medusajs/cache-inmemory": "^1.8.0",
    "@medusajs/cache-redis": "^1.8.0",
    "@medusajs/event-bus-local": "^1.9.6",
    "@medusajs/event-bus-redis": "^1.8.0",
    "@medusajs/medusa": "^1.9.0",
    "@medusajs/medusa-cli": "^1.3.9",`

Every time when I try to updated or create new product record in products table in Medusa I don't see updated in Algolia datasource. New products don't sync with Algolia datasource.

plugin declaration:

` {
        resolve: "medusa-plugin-algolia",
        options: {
            applicationId: process.env.ALGOLIA_APP_ID,
            adminApiKey: process.env.ALGOLIA_ADMIN_API_KEY,
            settings: {
                products: {
                    indexSettings: {
                        searchableAttributes: ["title", "description"],
                        attributesToRetrieve: [
                            "id",
                            "title",
                            "description",
                            "handle",
                            "thumbnail",
                            "images",
                            "color",
                            "configuration",
                        ],
                    },
                    transformer: (product) => ({
                        id: product.id,
                        title: product.title || 'none',
                        handle: product.handle || 'none',
                        color: product.color || 'none',
                        configuration: product.configuration || 'none',
                        variants: product.variants || 'none',
                        thumbnail: product.thumbnail || 'none',
                        images: product.images || 'none',
                    }),
                },
            },
        },
    },
`

### System information

Medusa version:
` "@medusajs/admin": "^3.0.0",
    "@medusajs/cache-inmemory": "^1.8.0",
    "@medusajs/cache-redis": "^1.8.0",
    "@medusajs/event-bus-local": "^1.9.6",
    "@medusajs/event-bus-redis": "^1.8.0",
    "@medusajs/medusa": "^1.9.0",
    "@medusajs/medusa-cli": "^1.3.9",`
Node.js version: 16
Database: postgres
Operating system: windows 11

### Steps to reproduce the behavior

1. Go to medusa-admin
2. Create new product entity
3. New product will not be setted in algolia datasource

### Expected behavior

With updating or creating new product entities their must be existed in Algolia datasource

**Comment by tsvetann** [comment]
Algolia requires objectID not id

**Comment by DmitryYegorov** [comment]
> Algolia requires objectID not id

I guess it should be noticed in documentation, because it has example without `objectID` with `id` only

**Comment by olivermrbl** [comment]
@DmitryYegorov, that is a fair point!

@shahednasser when time allows for it, will you tweak the example to say:
```
transformer: (product) => ({
  objectID: product.id // objectID is required by Algolia
...
```

**Comment by shahednasser** [comment]
Someone actually opener a PR with it yesterday #4734 but we haven't merged it yet. Will merge it once all tests pass 😇

**Comment by olivermrbl** [comment]
Ahh nice, thanks! 😍

**Comment by goseivietnam** [comment]
I change to objectID, but it's not fixed
