### ISSUE TITLE
Admin UI - Categories selection in Product Details Edit General Information is showing numbers instead of category names

### ISSUE THREAD

**Issue by tsemachh** [medusajs/medusa#4740]
### Describe the bug

When creating new product we can choose a category to associate with the product.
After product is created when we enter Edit General Information the category display is number of categories instead of the category name
### System information
Medusa version:
    "@medusajs/admin": "7.0.0-beta-20230727162508",
    "@medusajs/cache-inmemory": "^1.8.7",
    "@medusajs/cache-redis": "^1.8.7",
    "@medusajs/event-bus-local": "^1.9.4",
    "@medusajs/event-bus-redis": "^1.8.7",
    "@medusajs/file-local": "^1.0.1",
    "@medusajs/medusa": "1.13.1-beta-20230727162508",
    "medusa-fulfillment-manual": "^1.1.37",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.23",
    "medusa-payment-stripe": "^6.0.1",
    "medusa-plugin-meilisearch": "^2.0.10",
    "medusa-plugin-smtp": "^1.2.0",
Node.js version: v18.12.1
Database: Postgrea 10.4
Operating system: Windows 10
Browser (if relevant): Chrome latest

### Steps to reproduce the behavior
1. Create new Product
2. Associate categorie to the product
3. Save the Product
4. Enter the product - > Edit General Information
Category appears as number of categories instead of original category names

### Expected behavior
Categories in Product appear as they have selected in product creation.
(Having numbers is redundant when you have so much place for the categories)
### Screenshots
![image](https://github.com/medusajs/medusa/assets/2004954/4941d8ad-cd4e-4db1-95d8-3ce1a38b7af9)
![image](https://github.com/medusajs/medusa/assets/2004954/3b0ba7ca-0259-4b89-90ae-64acbab5107a)
### Developer Notes
Maybe it's good to have there Multi autocomplete from the list of existing categories

**Comment by olivermrbl** [comment]
Appreciate your suggestion. However, we will stick with the current UI :)
