### ISSUE TITLE
Docs(Code Issue): Code Issue in /modules/carts-and-checkout/storefront/implement-checkout-flow

### ISSUE THREAD

**Issue by elliotsoomro** [medusajs/medusa#4744]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The method name and mutation used in the Complete Cart step is incorrect: https://docs.medusajs.com/modules/carts-and-checkout/storefront/implement-checkout-flow#complete-cart

### How can this issue be resolved?

1. Rename method name to "handleCompleteCheckout"
2. Rename mutation to "completeCheckout"

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for submitting this issue! Will open a PR to fix it
