### ISSUE TITLE
Generate admin API fixture for Store

### ISSUE THREAD

**Issue by olivermrbl** [medusajs/medusa#475]
Generate fixtures for models returned by our API. Instead of having one huuuge file with all of our fixtures, we would like to split these up, such that we have a dedicated file for each entity.

This ticket is for **Admin Store (entity) fixture**

API Fixtures checklist → https://www.notion.so/medusajs/API-Fixtures-checklist-5abf366ac6784d4681344b97b3d4aedf

Loom on how to do API fixtures: https://www.loom.com/share/230b0c3ec59144bebbfa7029d31fd1fb

**Comment by Hanaffi** [comment]
@olivermrbl Can you assign this to me please?

**Comment by Hanaffi** [comment]
@olivermrbl Yes, It looks interesting. :)

**Comment by olivermrbl** [comment]
Hey @Hanaffi ! Did you get a chance to have a look at this one? Would love to help out, if you need anything :)

**Comment by Leobl** [comment]
Hello @olivermrbl, if that's still open, may I give this a try?
