### ISSUE TITLE
Cart complete failed with 500 status. Unknown_error

### ISSUE THREAD

**Issue by Glebario** [medusajs/medusa#4754]
### Describe the bug

I am developing an application with a Medusa backend and admin, but with a custom frontend. The frontend is developed on React but without medusa hooks. I only use open api meduza. I only use ''**manual**'' plugins: **"medusa-fulfillment-manual"**, **"medusa-payment-manual"** After selecting the shipping method and the payment method, I complete the cart and get an unknown_error.
Moreover, on the backend server I receive the following message: **QueryFailedError: SQLITE_CONSTRAINT: UNIQUE constraint failed: payment.cart_id.**

_I rewired my custom frontend to the basic medusa frontend and I get the same error in the same place. Therefore, I suspect that there is a problem in the backend or I have not configured something somewhere_

### Screenshots

<img width="1440" alt="Снимок экрана 2023-08-13 в 16 42 03" src="https://github.com/medusajs/medusa/assets/50720344/d8381b1c-c37d-4c53-8684-042916119fed">
<img width="1440" alt="Снимок экрана 2023-08-13 в 16 42 13" src="https://github.com/medusajs/medusa/assets/50720344/3b02c3b6-4eb4-45c6-aeed-695e6909e5ce">
BackEnd package.json
<img width="802" alt="Снимок экрана 2023-08-13 в 16 37 46" src="https://github.com/medusajs/medusa/assets/50720344/39e448d3-b0a8-4d88-9faa-5c306119e51e">
BackEnd error message
<img width="1440" alt="Снимок экрана 2023-08-13 в 16 49 58" src="https://github.com/medusajs/medusa/assets/50720344/c97466d6-49cb-4b8c-acd2-1b7252cdae45">
FrontEnd package.json
<img width="802" alt="Снимок экрана 2023-08-13 в 16 37 19" src="https://github.com/medusajs/medusa/assets/50720344/cbf814e3-3b94-40c3-a8f4-b1e3ecb6e1f9">

### Code snippets

`{
    "cart": {
        "object": "cart",
        "id": "cart_01H6NMHVE2TSVFW8C4EFJ6R663",
        "gift_cards": [],
        "region": {
            "id": "reg_01H0WA2PN95P1GRXCCEV08HAK2",
            "created_at": "2023-05-20T10:07:58.000Z",
            "updated_at": "2023-07-23T11:52:37.000Z",
            "deleted_at": null,
            "name": "Ukraine",
            "currency_code": "uah",
            "tax_rate": 0,
            "tax_code": "0000",
            "gift_cards_taxable": true,
            "automatic_taxes": true,
            "tax_provider_id": null,
            "metadata": {},
            "countries": [
                {
                    "id": 233,
                    "iso_2": "ua",
                    "iso_3": "ukr",
                    "num_code": 804,
                    "name": "UKRAINE",
                    "display_name": "Ukraine",
                    "region_id": "reg_01H0WA2PN95P1GRXCCEV08HAK2"
                }
            ],
            "payment_providers": [
                {
                    "id": "manual",
                    "is_installed": true
                }
            ],
            "tax_rates": []
        },
        "items": [
            {
                "id": "item_01H6NMJ48SQEBSQ6HP90G73H3D",
                "created_at": "2023-07-31T09:30:39.000Z",
                "updated_at": "2023-08-13T13:49:33.000Z",
                "cart_id": "cart_01H6NMHVE2TSVFW8C4EFJ6R663",
                "order_id": null,
                "swap_id": null,
                "claim_order_id": null,
                "original_item_id": null,
                "order_edit_id": null,
                "title": "Burger",
                "description": "SECOND",
                "thumbnail": "http://localhost:9000/uploads/images.jpeg",
                "is_return": false,
                "is_giftcard": false,
                "should_merge": true,
                "allow_discounts": true,
                "has_shipping": true,
                "unit_price": 15000,
                "variant_id": "variant_01H5Z95XMJYS84PN1SCMK4Y3Y4",
                "quantity": 1,
                "fulfilled_quantity": null,
                "returned_quantity": null,
                "shipped_quantity": null,
                "metadata": {},
                "variant": {
                    "id": "variant_01H5Z95XMJYS84PN1SCMK4Y3Y4",
                    "created_at": "2023-07-22T17:08:27.000Z",
                    "updated_at": "2023-07-23T16:30:34.000Z",
                    "deleted_at": null,
                    "title": "SECOND",
                    "product_id": "prod_01H5QW7HAPPBSBJRFGE7A34QW5",
                    "sku": null,
                    "barcode": null,
                    "ean": null,
                    "upc": null,
                    "variant_rank": 1,
                    "inventory_quantity": 10,
                    "allow_backorder": false,
                    "manage_inventory": false,
                    "hs_code": null,
                    "origin_country": null,
                    "mid_code": null,
                    "material": null,
                    "weight": null,
                    "length": null,
                    "height": null,
                    "width": null,
                    "metadata": {},
                    "product": {
                        "id": "prod_01H5QW7HAPPBSBJRFGE7A34QW5",
                        "created_at": "2023-07-19T20:07:28.000Z",
                        "updated_at": "2023-07-23T11:44:55.000Z",
                        "deleted_at": null,
                        "title": "Burger",
                        "subtitle": "Standart-burger",
                        "description": "Nullam neque massa, congue nec placerat in, ultricies ut purus. Nulla facilisi. Vivamus viverra facilisis dolor, nec faucibus justo varius vitae. Phasellus sagittis urna eget justo dictum tincidunt.",
                        "handle": "standart-burger",
                        "is_giftcard": false,
                        "status": "published",
                        "thumbnail": "http://localhost:9000/uploads/images.jpeg",
                        "profile_id": "sp_01H0T4PPFGD6VRFWFCQ9E7E7PT",
                        "weight": 300,
                        "length": null,
                        "height": null,
                        "width": null,
                        "hs_code": null,
                        "origin_country": "UA",
                        "mid_code": null,
                        "material": "meat, tomato",
                        "collection_id": "pcol_01H5Z8QNNWWV75PJGRBWZPEXGY",
                        "type_id": null,
                        "discountable": true,
                        "external_id": null,
                        "metadata": {}
                    }
                },
                "adjustments": [],
                "tax_lines": [
                    {
                        "rate": 0,
                        "name": "default",
                        "code": "default",
                        "item_id": "item_01H6NMJ48SQEBSQ6HP90G73H3D"
                    }
                ],
                "subtotal": 15000,
                "discount_total": 0,
                "total": 15000,
                "original_total": 15000,
                "original_tax_total": 0,
                "tax_total": 0,
                "raw_discount_total": 0
            },
            {
                "id": "item_01H7QJH9PA11KGRPN3EB2CGP51",
                "created_at": "2023-08-13T13:49:26.000Z",
                "updated_at": "2023-08-13T13:49:33.000Z",
                "cart_id": "cart_01H6NMHVE2TSVFW8C4EFJ6R663",
                "order_id": null,
                "swap_id": null,
                "claim_order_id": null,
                "original_item_id": null,
                "order_edit_id": null,
                "title": "Burger",
                "description": "FIRST",
                "thumbnail": "http://localhost:9000/uploads/images.jpeg",
                "is_return": false,
                "is_giftcard": false,
                "should_merge": true,
                "allow_discounts": true,
                "has_shipping": true,
                "unit_price": 10000,
                "variant_id": "variant_01H5Z94Q8FFN9XDNY8J4AX3BS9",
                "quantity": 1,
                "fulfilled_quantity": null,
                "returned_quantity": null,
                "shipped_quantity": null,
                "metadata": {},
                "variant": {
                    "id": "variant_01H5Z94Q8FFN9XDNY8J4AX3BS9",
                    "created_at": "2023-07-22T17:07:48.000Z",
                    "updated_at": "2023-07-23T16:30:34.000Z",
                    "deleted_at": null,
                    "title": "FIRST",
                    "product_id": "prod_01H5QW7HAPPBSBJRFGE7A34QW5",
                    "sku": null,
                    "barcode": null,
                    "ean": null,
                    "upc": null,
                    "variant_rank": 0,
                    "inventory_quantity": 10,
                    "allow_backorder": false,
                    "manage_inventory": false,
                    "hs_code": null,
                    "origin_country": null,
                    "mid_code": null,
                    "material": null,
                    "weight": null,
                    "length": null,
                    "height": null,
                    "width": null,
                    "metadata": {},
                    "product": {
                        "id": "prod_01H5QW7HAPPBSBJRFGE7A34QW5",
                        "created_at": "2023-07-19T20:07:28.000Z",
                        "updated_at": "2023-07-23T11:44:55.000Z",
                        "deleted_at": null,
                        "title": "Burger",
                        "subtitle": "Standart-burger",
                        "description": "Nullam neque massa, congue nec placerat in, ultricies ut purus. Nulla facilisi. Vivamus viverra facilisis dolor, nec faucibus justo varius vitae. Phasellus sagittis urna eget justo dictum tincidunt.",
                        "handle": "standart-burger",
                        "is_giftcard": false,
                        "status": "published",
                        "thumbnail": "http://localhost:9000/uploads/images.jpeg",
                        "profile_id": "sp_01H0T4PPFGD6VRFWFCQ9E7E7PT",
                        "weight": 300,
                        "length": null,
                        "height": null,
                        "width": null,
                        "hs_code": null,
                        "origin_country": "UA",
                        "mid_code": null,
                        "material": "meat, tomato",
                        "collection_id": "pcol_01H5Z8QNNWWV75PJGRBWZPEXGY",
                        "type_id": null,
                        "discountable": true,
                        "external_id": null,
                        "metadata": {}
                    }
                },
                "adjustments": [],
                "tax_lines": [
                    {
                        "rate": 0,
                        "name": "default",
                        "code": "default",
                        "item_id": "item_01H7QJH9PA11KGRPN3EB2CGP51"
                    }
                ],
                "subtotal": 10000,
                "discount_total": 0,
                "total": 10000,
                "original_total": 10000,
                "original_tax_total": 0,
                "tax_total": 0,
                "raw_discount_total": 0
            }
        ],
        "payment": {
            "id": "pay_01H6NMNXB2STQFHB5QSNFSZX27",
            "created_at": "2023-07-31T09:32:43.000Z",
            "updated_at": "2023-07-31T09:32:43.000Z",
            "swap_id": null,
            "cart_id": "cart_01H6NMHVE2TSVFW8C4EFJ6R663",
            "order_id": null,
            "amount": 1015000,
            "currency_code": "uah",
            "amount_refunded": 0,
            "provider_id": "manual",
            "data": {
                "status": "authorized"
            },
            "captured_at": null,
            "canceled_at": null,
            "metadata": null,
            "idempotency_key": null
        },
        "shipping_address": {
            "id": "addr_01H6NMHVE2NC6DDTY9S8N0T1DG",
            "created_at": "2023-07-31T09:30:30.000Z",
            "updated_at": "2023-07-31T09:30:49.000Z",
            "deleted_at": null,
            "customer_id": null,
            "company": null,
            "first_name": "Gleb",
            "last_name": "Sukhovoy",
            "address_1": "dsvfsf ewfwefwef",
            "address_2": null,
            "city": "Kharkov",
            "country_code": "ua",
            "province": null,
            "postal_code": "10300",
            "phone": "+380685576574",
            "metadata": null
        },
        "billing_address": {
            "id": "addr_01H6NMJDK6F690HH09RT10CP6D",
            "created_at": "2023-07-31T09:30:49.000Z",
            "updated_at": "2023-07-31T09:30:49.000Z",
            "deleted_at": null,
            "customer_id": null,
            "company": null,
            "first_name": "Gleb",
            "last_name": "Sukhovoy",
            "address_1": "dsvfsf ewfwefwef",
            "address_2": null,
            "city": "Kharkov",
            "country_code": "ua",
            "province": null,
            "postal_code": "10300",
            "phone": "+380685576574",
            "metadata": null
        },
        "shipping_methods": [
            {
                "id": "sm_01H7QJHH1HQ93YSGYMYF612926",
                "shipping_option_id": "so_01H6MKBVPM0EKF0K1JP7WZZN3A",
                "order_id": null,
                "claim_order_id": null,
                "cart_id": "cart_01H6NMHVE2TSVFW8C4EFJ6R663",
                "swap_id": null,
                "return_id": null,
                "price": 1000000,
                "data": {},
                "shipping_option": {
                    "id": "so_01H6MKBVPM0EKF0K1JP7WZZN3A",
                    "created_at": "2023-07-30T23:50:31.000Z",
                    "updated_at": "2023-07-31T09:32:33.000Z",
                    "deleted_at": null,
                    "name": "Default",
                    "region_id": "reg_01H0WA2PN95P1GRXCCEV08HAK2",
                    "profile_id": "sp_01H0T4PPFGD6VRFWFCQ9E7E7PT",
                    "provider_id": "manual",
                    "price_type": "flat_rate",
                    "amount": 1000000,
                    "is_return": false,
                    "admin_only": false,
                    "data": {
                        "id": "manual-fulfillment"
                    },
                    "metadata": {}
                },
                "tax_lines": [
                    {
                        "rate": 0,
                        "name": "default",
                        "code": "default",
                        "shipping_method_id": "sm_01H7QJHH1HQ93YSGYMYF612926"
                    }
                ],
                "original_total": 1000000,
                "total": 1000000,
                "subtotal": 1000000,
                "original_tax_total": 0,
                "tax_total": 0
            }
        ],
        "payment_sessions": [
            {
                "id": "ps_01H6NMNX9CGEX5AH3S7H0GJ38F",
                "created_at": "2023-07-31T09:32:43.000Z",
                "updated_at": "2023-08-13T13:49:26.000Z",
                "cart_id": "cart_01H6NMHVE2TSVFW8C4EFJ6R663",
                "provider_id": "manual",
                "is_selected": true,
                "is_initiated": true,
                "status": "authorized",
                "data": {
                    "status": "authorized"
                },
                "idempotency_key": null,
                "amount": 1025000,
                "payment_authorized_at": "2023-07-31T09:32:43.733Z"
            }
        ],
        "payment_session": {
            "id": "ps_01H6NMNX9CGEX5AH3S7H0GJ38F",
            "created_at": "2023-07-31T09:32:43.000Z",
            "updated_at": "2023-08-13T13:49:26.000Z",
            "cart_id": "cart_01H6NMHVE2TSVFW8C4EFJ6R663",
            "provider_id": "manual",
            "is_selected": true,
            "is_initiated": true,
            "status": "authorized",
            "data": {
                "status": "authorized"
            },
            "idempotency_key": null,
            "amount": 1025000,
            "payment_authorized_at": "2023-07-31T09:32:43.733Z"
        },
        "discounts": [],
        "sales_channel": {
            "id": "sc_01H0T4PPFPG8F14QWQGSDCWMMJ",
            "created_at": "2023-05-19T13:55:33.000Z",
            "updated_at": "2023-05-19T13:55:33.000Z",
            "deleted_at": null,
            "name": "Default Sales Channel",
            "description": "Created by Medusa",
            "is_disabled": false,
            "metadata": null
        },
        "created_at": "2023-07-31T09:30:30.000Z",
        "updated_at": "2023-07-31T09:32:43.000Z",
        "deleted_at": null,
        "email": "manual@gmail.com",
        "billing_address_id": "addr_01H6NMJDK6F690HH09RT10CP6D",
        "shipping_address_id": "addr_01H6NMHVE2NC6DDTY9S8N0T1DG",
        "region_id": "reg_01H0WA2PN95P1GRXCCEV08HAK2",
        "customer_id": "cus_01H6MEXY6ST99YPRZGY3RZTRX7",
        "payment_id": "pay_01H6NMNXB2STQFHB5QSNFSZX27",
        "type": "default",
        "completed_at": null,
        "payment_authorized_at": "2023-07-31T09:32:43.747Z",
        "idempotency_key": null,
        "context": {
            "ip": "::1",
            "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
        },
        "metadata": null,
        "sales_channel_id": "sc_01H0T4PPFPG8F14QWQGSDCWMMJ",
        "subtotal": 25000,
        "discount_total": 0,
        "item_tax_total": 0,
        "shipping_total": 1000000,
        "shipping_tax_total": 0,
        "gift_card_total": 0,
        "gift_card_tax_total": 0,
        "tax_total": 0,
        "raw_discount_total": 0,
        "total": 1025000
    },
    "data": {
        "object": "cart",
        "id": "cart_01H6NMHVE2TSVFW8C4EFJ6R663",
        "gift_cards": [],
        "region": {
            "id": "reg_01H0WA2PN95P1GRXCCEV08HAK2",
            "created_at": "2023-05-20T10:07:58.000Z",
            "updated_at": "2023-07-23T11:52:37.000Z",
            "deleted_at": null,
            "name": "Ukraine",
            "currency_code": "uah",
            "tax_rate": 0,
            "tax_code": "0000",
            "gift_cards_taxable": true,
            "automatic_taxes": true,
            "tax_provider_id": null,
            "metadata": {},
            "countries": [
                {
                    "id": 233,
                    "iso_2": "ua",
                    "iso_3": "ukr",
                    "num_code": 804,
                    "name": "UKRAINE",
                    "display_name": "Ukraine",
                    "region_id": "reg_01H0WA2PN95P1GRXCCEV08HAK2"
                }
            ],
            "payment_providers": [
                {
                    "id": "manual",
                    "is_installed": true
                }
            ],
            "tax_rates": []
        },
        "items": [
            {
                "id": "item_01H6NMJ48SQEBSQ6HP90G73H3D",
                "created_at": "2023-07-31T09:30:39.000Z",
                "updated_at": "2023-08-13T13:49:33.000Z",
                "cart_id": "cart_01H6NMHVE2TSVFW8C4EFJ6R663",
                "order_id": null,
                "swap_id": null,
                "claim_order_id": null,
                "original_item_id": null,
                "order_edit_id": null,
                "title": "Burger",
                "description": "SECOND",
                "thumbnail": "http://localhost:9000/uploads/images.jpeg",
                "is_return": false,
                "is_giftcard": false,
                "should_merge": true,
                "allow_discounts": true,
                "has_shipping": true,
                "unit_price": 15000,
                "variant_id": "variant_01H5Z95XMJYS84PN1SCMK4Y3Y4",
                "quantity": 1,
                "fulfilled_quantity": null,
                "returned_quantity": null,
                "shipped_quantity": null,
                "metadata": {},
                "variant": {
                    "id": "variant_01H5Z95XMJYS84PN1SCMK4Y3Y4",
                    "created_at": "2023-07-22T17:08:27.000Z",
                    "updated_at": "2023-07-23T16:30:34.000Z",
                    "deleted_at": null,
                    "title": "SECOND",
                    "product_id": "prod_01H5QW7HAPPBSBJRFGE7A34QW5",
                    "sku": null,
                    "barcode": null,
                    "ean": null,
                    "upc": null,
                    "variant_rank": 1,
                    "inventory_quantity": 10,
                    "allow_backorder": false,
                    "manage_inventory": false,
                    "hs_code": null,
                    "origin_country": null,
                    "mid_code": null,
                    "material": null,
                    "weight": null,
                    "length": null,
                    "height": null,
                    "width": null,
                    "metadata": {},
                    "product": {
                        "id": "prod_01H5QW7HAPPBSBJRFGE7A34QW5",
                        "created_at": "2023-07-19T20:07:28.000Z",
                        "updated_at": "2023-07-23T11:44:55.000Z",
                        "deleted_at": null,
                        "title": "Burger",
                        "subtitle": "Standart-burger",
                        "description": "Nullam neque massa, congue nec placerat in, ultricies ut purus. Nulla facilisi. Vivamus viverra facilisis dolor, nec faucibus justo varius vitae. Phasellus sagittis urna eget justo dictum tincidunt.",
                        "handle": "standart-burger",
                        "is_giftcard": false,
                        "status": "published",
                        "thumbnail": "http://localhost:9000/uploads/images.jpeg",
                        "profile_id": "sp_01H0T4PPFGD6VRFWFCQ9E7E7PT",
                        "weight": 300,
                        "length": null,
                        "height": null,
                        "width": null,
                        "hs_code": null,
                        "origin_country": "UA",
                        "mid_code": null,
                        "material": "meat, tomato",
                        "collection_id": "pcol_01H5Z8QNNWWV75PJGRBWZPEXGY",
                        "type_id": null,
                        "discountable": true,
                        "external_id": null,
                        "metadata": {}
                    }
                },
                "adjustments": [],
                "tax_lines": [
                    {
                        "rate": 0,
                        "name": "default",
                        "code": "default",
                        "item_id": "item_01H6NMJ48SQEBSQ6HP90G73H3D"
                    }
                ],
                "subtotal": 15000,
                "discount_total": 0,
                "total": 15000,
                "original_total": 15000,
                "original_tax_total": 0,
                "tax_total": 0,
                "raw_discount_total": 0
            },
            {
                "id": "item_01H7QJH9PA11KGRPN3EB2CGP51",
                "created_at": "2023-08-13T13:49:26.000Z",
                "updated_at": "2023-08-13T13:49:33.000Z",
                "cart_id": "cart_01H6NMHVE2TSVFW8C4EFJ6R663",
                "order_id": null,
                "swap_id": null,
                "claim_order_id": null,
                "original_item_id": null,
                "order_edit_id": null,
                "title": "Burger",
                "description": "FIRST",
                "thumbnail": "http://localhost:9000/uploads/images.jpeg",
                "is_return": false,
                "is_giftcard": false,
                "should_merge": true,
                "allow_discounts": true,
                "has_shipping": true,
                "unit_price": 10000,
                "variant_id": "variant_01H5Z94Q8FFN9XDNY8J4AX3BS9",
                "quantity": 1,
                "fulfilled_quantity": null,
                "returned_quantity": null,
                "shipped_quantity": null,
                "metadata": {},
                "variant": {
                    "id": "variant_01H5Z94Q8FFN9XDNY8J4AX3BS9",
                    "created_at": "2023-07-22T17:07:48.000Z",
                    "updated_at": "2023-07-23T16:30:34.000Z",
                    "deleted_at": null,
                    "title": "FIRST",
                    "product_id": "prod_01H5QW7HAPPBSBJRFGE7A34QW5",
                    "sku": null,
                    "barcode": null,
                    "ean": null,
                    "upc": null,
                    "variant_rank": 0,
                    "inventory_quantity": 10,
                    "allow_backorder": false,
                    "manage_inventory": false,
                    "hs_code": null,
                    "origin_country": null,
                    "mid_code": null,
                    "material": null,
                    "weight": null,
                    "length": null,
                    "height": null,
                    "width": null,
                    "metadata": {},
                    "product": {
                        "id": "prod_01H5QW7HAPPBSBJRFGE7A34QW5",
                        "created_at": "2023-07-19T20:07:28.000Z",
                        "updated_at": "2023-07-23T11:44:55.000Z",
                        "deleted_at": null,
                        "title": "Burger",
                        "subtitle": "Standart-burger",
                        "description": "Nullam neque massa, congue nec placerat in, ultricies ut purus. Nulla facilisi. Vivamus viverra facilisis dolor, nec faucibus justo varius vitae. Phasellus sagittis urna eget justo dictum tincidunt.",
                        "handle": "standart-burger",
                        "is_giftcard": false,
                        "status": "published",
                        "thumbnail": "http://localhost:9000/uploads/images.jpeg",
                        "profile_id": "sp_01H0T4PPFGD6VRFWFCQ9E7E7PT",
                        "weight": 300,
                        "length": null,
                        "height": null,
                        "width": null,
                        "hs_code": null,
                        "origin_country": "UA",
                        "mid_code": null,
                        "material": "meat, tomato",
                        "collection_id": "pcol_01H5Z8QNNWWV75PJGRBWZPEXGY",
                        "type_id": null,
                        "discountable": true,
                        "external_id": null,
                        "metadata": {}
                    }
                },
                "adjustments": [],
                "tax_lines": [
                    {
                        "rate": 0,
                        "name": "default",
                        "code": "default",
                        "item_id": "item_01H7QJH9PA11KGRPN3EB2CGP51"
                    }
                ],
                "subtotal": 10000,
                "discount_total": 0,
                "total": 10000,
                "original_total": 10000,
                "original_tax_total": 0,
                "tax_total": 0,
                "raw_discount_total": 0
            }
        ],
        "payment": {
            "id": "pay_01H6NMNXB2STQFHB5QSNFSZX27",
            "created_at": "2023-07-31T09:32:43.000Z",
            "updated_at": "2023-07-31T09:32:43.000Z",
            "swap_id": null,
            "cart_id": "cart_01H6NMHVE2TSVFW8C4EFJ6R663",
            "order_id": null,
            "amount": 1015000,
            "currency_code": "uah",
            "amount_refunded": 0,
            "provider_id": "manual",
            "data": {
                "status": "authorized"
            },
            "captured_at": null,
            "canceled_at": null,
            "metadata": null,
            "idempotency_key": null
        },
        "shipping_address": {
            "id": "addr_01H6NMHVE2NC6DDTY9S8N0T1DG",
            "created_at": "2023-07-31T09:30:30.000Z",
            "updated_at": "2023-07-31T09:30:49.000Z",
            "deleted_at": null,
            "customer_id": null,
            "company": null,
            "first_name": "Gleb",
            "last_name": "Sukhovoy",
            "address_1": "dsvfsf ewfwefwef",
            "address_2": null,
            "city": "Kharkov",
            "country_code": "ua",
            "province": null,
            "postal_code": "10300",
            "phone": "+380685576574",
            "metadata": null
        },
        "billing_address": {
            "id": "addr_01H6NMJDK6F690HH09RT10CP6D",
            "created_at": "2023-07-31T09:30:49.000Z",
            "updated_at": "2023-07-31T09:30:49.000Z",
            "deleted_at": null,
            "customer_id": null,
            "company": null,
            "first_name": "Gleb",
            "last_name": "Sukhovoy",
            "address_1": "dsvfsf ewfwefwef",
            "address_2": null,
            "city": "Kharkov",
            "country_code": "ua",
            "province": null,
            "postal_code": "10300",
            "phone": "+380685576574",
            "metadata": null
        },
        "shipping_methods": [
            {
                "id": "sm_01H7QJHH1HQ93YSGYMYF612926",
                "shipping_option_id": "so_01H6MKBVPM0EKF0K1JP7WZZN3A",
                "order_id": null,
                "claim_order_id": null,
                "cart_id": "cart_01H6NMHVE2TSVFW8C4EFJ6R663",
                "swap_id": null,
                "return_id": null,
                "price": 1000000,
                "data": {},
                "shipping_option": {
                    "id": "so_01H6MKBVPM0EKF0K1JP7WZZN3A",
                    "created_at": "2023-07-30T23:50:31.000Z",
                    "updated_at": "2023-07-31T09:32:33.000Z",
                    "deleted_at": null,
                    "name": "Default",
                    "region_id": "reg_01H0WA2PN95P1GRXCCEV08HAK2",
                    "profile_id": "sp_01H0T4PPFGD6VRFWFCQ9E7E7PT",
                    "provider_id": "manual",
                    "price_type": "flat_rate",
                    "amount": 1000000,
                    "is_return": false,
                    "admin_only": false,
                    "data": {
                        "id": "manual-fulfillment"
                    },
                    "metadata": {}
                },
                "tax_lines": [
                    {
                        "rate": 0,
                        "name": "default",
                        "code": "default",
                        "shipping_method_id": "sm_01H7QJHH1HQ93YSGYMYF612926"
                    }
                ],
                "original_total": 1000000,
                "total": 1000000,
                "subtotal": 1000000,
                "original_tax_total": 0,
                "tax_total": 0
            }
        ],
        "payment_sessions": [
            {
                "id": "ps_01H6NMNX9CGEX5AH3S7H0GJ38F",
                "created_at": "2023-07-31T09:32:43.000Z",
                "updated_at": "2023-08-13T13:49:26.000Z",
                "cart_id": "cart_01H6NMHVE2TSVFW8C4EFJ6R663",
                "provider_id": "manual",
                "is_selected": true,
                "is_initiated": true,
                "status": "authorized",
                "data": {
                    "status": "authorized"
                },
                "idempotency_key": null,
                "amount": 1025000,
                "payment_authorized_at": "2023-07-31T09:32:43.733Z"
            }
        ],
        "payment_session": {
            "id": "ps_01H6NMNX9CGEX5AH3S7H0GJ38F",
            "created_at": "2023-07-31T09:32:43.000Z",
            "updated_at": "2023-08-13T13:49:26.000Z",
            "cart_id": "cart_01H6NMHVE2TSVFW8C4EFJ6R663",
            "provider_id": "manual",
            "is_selected": true,
            "is_initiated": true,
            "status": "authorized",
            "data": {
                "status": "authorized"
            },
            "idempotency_key": null,
            "amount": 1025000,
            "payment_authorized_at": "2023-07-31T09:32:43.733Z"
        },
        "discounts": [],
        "sales_channel": {
            "id": "sc_01H0T4PPFPG8F14QWQGSDCWMMJ",
            "created_at": "2023-05-19T13:55:33.000Z",
            "updated_at": "2023-05-19T13:55:33.000Z",
            "deleted_at": null,
            "name": "Default Sales Channel",
            "description": "Created by Medusa",
            "is_disabled": false,
            "metadata": null
        },
        "created_at": "2023-07-31T09:30:30.000Z",
        "updated_at": "2023-07-31T09:32:43.000Z",
        "deleted_at": null,
        "email": "manual@gmail.com",
        "billing_address_id": "addr_01H6NMJDK6F690HH09RT10CP6D",
        "shipping_address_id": "addr_01H6NMHVE2NC6DDTY9S8N0T1DG",
        "region_id": "reg_01H0WA2PN95P1GRXCCEV08HAK2",
        "customer_id": "cus_01H6MEXY6ST99YPRZGY3RZTRX7",
        "payment_id": "pay_01H6NMNXB2STQFHB5QSNFSZX27",
        "type": "default",
        "completed_at": null,
        "payment_authorized_at": "2023-07-31T09:32:43.747Z",
        "idempotency_key": null,
        "context": {
            "ip": "::1",
            "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
        },
        "metadata": null,
        "sales_channel_id": "sc_01H0T4PPFPG8F14QWQGSDCWMMJ",
        "subtotal": 25000,
        "discount_total": 0,
        "item_tax_total": 0,
        "shipping_total": 1000000,
        "shipping_tax_total": 0,
        "gift_card_total": 0,
        "gift_card_tax_total": 0,
        "tax_total": 0,
        "total": 1025000
    }
}`
complete cart object

**Comment by srindom** [comment]
Hi @Glebario - we are deprecating SQLite support. Can you please try setting up Postgres and see if the problem persists?

**Comment by Glebario** [comment]
@srindom I migrated to Postgres and after all work fine. Thanks!
