### ISSUE TITLE
Generate admin API fixture for Shipping Profile

### ISSUE THREAD

**Issue by olivermrbl** [medusajs/medusa#476]
Generate fixtures for models returned by our API. Instead of having one huuuge file with all of our fixtures, we would like to split these up, such that we have a dedicated file for each entity.

This ticket is for **Admin Shipping Profile fixture**

API Fixtures checklist → https://www.notion.so/medusajs/API-Fixtures-checklist-5abf366ac6784d4681344b97b3d4aedf

Loom on how to do API fixtures: https://www.loom.com/share/230b0c3ec59144bebbfa7029d31fd1fb

**Comment by olivermrbl** [comment]
Hi @lyqht ! Sure. Would be great :) Let me know, if you need help getting started.

**Comment by lyqht** [comment]
hi @olivermrbl , sorry i would like to drop this issue.

**Comment by olivermrbl** [comment]
Many thanks @l4u .. As mentioned, reach out to me on Discord. Would love to send some swag your way ❤️ 

Closed #699
