### ISSUE TITLE
The inventory of product information obtained through the interface store/products and admin/products for the same product is inconsistent

### ISSUE THREAD

**Issue by joezhou9865** [medusajs/medusa#4762]
The inventory of products obtained through the interface store/products is 0
            {
                    "id": "variant_01H7HT5KVAZP0VSCYNZ4HCT5KQ",
                    "created_at": "2023-08-11T08:07:25.140Z",
                    "updated_at": "2023-08-11T09:22:07.349Z",
                    "deleted_at": null,
                    "title": "red / XL",
                    "product_id": "prod_01H7HT5KR2X79JY4WA3RMHC6Y9",
                    "sku": "JK123",
                    "barcode": "33",
                    "ean": "111",
                    "upc": "22",
                    "variant_rank": 0,
                    **"inventory_quantity": 0,**
                    "allow_backorder": false,
                    "manage_inventory": true,
                    "hs_code": null,
                    "origin_country": "CN",
                    "mid_code": null,
                    "material": null,
                    "weight": 4,
                    "length": 2,
                    "height": 3,
                    "width": 1,
                    "metadata": {}
                }
The inventory of goods obtained through the interface admin/products is correct
              {
                   id:"variant_01H7HT5KVAZP0VSCYNZ4HCT5KQ",
                   created_at:"2023-08-11T08:07:25.140Z",
                   updated_at:"2023-08-11T09:22:07.349Z",
                  deleted_at:null,
                  title:"red / XL",
                  product_id:"prod_01H7HT5KR2X79JY4WA3RMHC6Y9",
                  sku:"JK123",
                  barcode:"33",
                  ean:"111",
                  upc:"22",
                  variant_rank:0,
                  **inventory_quantity:4,**
                  allow_backorder:false,
                  manage_inventory:true,
                  hs_code:null,
                  origin_country:"CN",
                  mid_code:null,
                  material:null,
                  weight:4,
                  length:2,
                  height:3,
                  width:1,
             }

**Comment by alsherif-khalaf** [comment]
What was the problem ?
