### ISSUE TITLE
Cannot cancel order with more than 9 line-items

### ISSUE THREAD

**Issue by tonhuynhit** [medusajs/medusa#4763]
### Describe the bug
When order has more than 9 line-items, the systeam will hange on and need to restart

### System information
Medusa version 1.12.0
Node.js version: 18.15.0
@medusajs/inventory : 1.9.0
Database: Azure Database for PostgreSQL flexible server 14.7
Operating system: Docker linux

### Steps to reproduce the behavior
1. Setup backend with multiple warehouse feature (install inventory, stock-location, event-bus with redis)
2. Go to admin site > Order > Draft and create a draft order with 10 line-items
3. Then mark as paid this item
4. Go to order has been created from Draft order, and cancel it
5. Error will happen

As investigated, we found some thing from eventBusService:
https://github.com/medusajs/medusa/blob/4a448b68fde90beb956375018ac833f6478726e6/packages/inventory/src/services/reservation-item.ts#L278C24-L278C24

1. No response from EventBusService, and system will hange on 
2. EventBusService use different transaction, so if there're something wrong, the event-bus still fire event

### Expected behavior
This order should be able to cancel

**Comment by srindom** [comment]
I couldn't reproduce this issue - see the PR above for the integration test. 

A few questions:
1. Does the system become unresponsive, or do you actually see an error in your server console?
2. Which event bus module are you using?
3. Have you tried upgrading to the latest version?

**Comment by tonhuynhit** [comment]
Hi @srindom ,

1. System doesn't response, the cancel api status is still pending. We tried to refresh page, then system hange on
2. We use  @medusajs/event-bus-redis: 1.8.7, and point to Azure for Redis service
3. We haven't upgrading to latest version yet, let me try and get back to you

**Comment by tonhuynhit** [comment]
Hi @srindom,

The issue has been disappeard when upgraded to v1.14.0

Our Dev team had been deeped in  code and found that when deleting reservation items, it has been added transactionManager into subsequence call, and make sure that data is consistent if there's any issue (transaction will be rollback), and maybe reduce number of  open connections to database that can be reach threshold.

Code change:
https://github.com/medusajs/medusa/blob/ecb491031281ab49ee7d0f8ec364e09fb399ad20/packages/medusa/src/services/product-variant-inventory.ts#L730C23-L730C23
