### ISSUE TITLE
Generate admin API fixture for Returns

### ISSUE THREAD

**Issue by olivermrbl** [medusajs/medusa#477]
Generate fixtures for models returned by our API. Instead of having one huuuge file with all of our fixtures, we would like to split these up, such that we have a dedicated file for each entity.

This ticket is for **Admin Returns fixture**

API Fixtures checklist → https://www.notion.so/medusajs/API-Fixtures-checklist-5abf366ac6784d4681344b97b3d4aedf

Loom on how to do API fixtures: https://www.loom.com/share/230b0c3ec59144bebbfa7029d31fd1fb

**Comment by hphan9** [comment]
Hi @olivermrbl, How could I edit the endpoint for the Jira ticket ? 
In the API Fixtures checklist, it mentioned: "Before you begin the process please specify in the Jira ticket which endpoints you will be creating fixtures for."
Thank you

**Comment by olivermrbl** [comment]
> Hi @olivermrbl, How could I edit the endpoint for the Jira ticket ? In the API Fixtures checklist, it mentioned: "Before you begin the process please specify in the Jira ticket which endpoints you will be creating fixtures for." Thank you

Jira is not used for this ticket any longer. We are doing it all here in Github. I will make sure to update the checklist. Thanks for pointing it out 👍

**Comment by hphan9** [comment]
Hi @olivermrbl ,
I am sorry. 
After running yarn Boostrap successfully.  I could not find integration-tests/docs/ in the medusa folder.
Am I missing something?
