### ISSUE TITLE
`medusa-plugin-elasticsearch`

### ISSUE THREAD

**Issue by olivermrbl** [medusajs/medusa#478]
We would like to add a search plugin for ElasticSearch. See [MeiliSearch here](https://github.com/medusajs/medusa/tree/feat/meilisearch-plugin/packages/medusa-plugin-meilisearch) for inspiration.

**Comment by olivermrbl** [comment]
Sure @Sukriti-sood ! That would be great. Will assign you to it. Let me know, if you need help getting started 👍

**Comment by Sukriti-sood** [comment]
@olivermrbl Can you share the Link to Discord Group,Link present in Repo is Expired.

**Comment by Sukriti-sood** [comment]
> https://discord.gg/9ukkVvad

This is invalid

**Comment by olivermrbl** [comment]
Can you try this link: https://discord.gg/Paqc5ySry5

**Comment by olivermrbl** [comment]
Closed #691
