### ISSUE TITLE
`medusa-plugin-sanity` CMS plugin

### ISSUE THREAD

**Issue by srindom** [medusajs/medusa#479]
It should be really easy for developers to integrate Medusa with the CMS system [Sanity](https://www.sanity.io/). 

Similar to the way that the [Contentful plugin](https://github.com/medusajs/medusa/tree/master/packages/medusa-plugin-contentful) works, users should be able to add `medusa-plugin-sanity` to their `medusa-config.js` file and synchronization should start. The entities to synchronize are:

- Products
  - Incl. options
- Product Variants
  - Incl. options and prices
- Regions

If possible the synchronization should be a two-way sync making it possible to update fields like `title, subtitle, handle, etc.` from Sanity.

**Comment by Aman-Kaushik13** [comment]
hey needed a bit help here as I am not much familiar with Contentful
` ...
assets.push({
            sys: {
              type: "Link",
              linkType: "Asset",
              id: finalAsset.sys.id,
            },
          })
...
return assets;

` 
what is this part used for? and what should I change this to in the sanity plugin?

**Comment by Aman-Kaushik13** [comment]
also what would be the easiest way to test and see if the plugin works, when its done?

**Comment by srindom** [comment]
@Aman-Kaushik13 The Contentful plugin uploads any images that are placed on a product. The code you are referring to is first going through all the product images (`product.images`) and then uploading them to Contentful as assets. After that is done all the assets are being published with the `asset.processForAllLocales().then(...)`. The final step just converts the published assets to the format that contentful uses in order to link Contentful Assets to a Contentful Entry before returning. 

Does that clarify your question?

**Comment by Aman-Kaushik13** [comment]
I have got the main idea, and with that.... I can continue working on the plugin. Thanks for taking out the time to answer :)

**Comment by srindom** [comment]
In regards to testing it would be great if you could add unit tests for your service similar to the tests you see here: https://github.com/medusajs/medusa/blob/master/packages/medusa-plugin-contentful/src/services/__tests__/contentful.js

Also it would be great if you can outline the steps to take in order to setup the plugin; this way we can go through the steps when reviewing. If you feel like taking it to the next level it'd be really cool if you could provide a test repo, but this is not required :)
