### ISSUE TITLE
Fulfillment Provider Plugin

### ISSUE THREAD

**Issue by srindom** [medusajs/medusa#48]
We need a fulfillment provider plugin - could be something like Webshipper or PrimeCargo.

**Comment by olivermrbl** [comment]
**Fulfillment service walkthrough:**

`getFulfillmentOptions()`
-

`validateFulfillmentData(data, cart)`
-

`validateOption(data)`
-

`canCalculate(data)`
-

`calculatePrice(data)`
-

`createOrder()`
-
