### ISSUE TITLE
`medusa-plugin-datocms` CMS plugin

### ISSUE THREAD

**Issue by srindom** [medusajs/medusa#480]
It should be really easy for developers to integrate Medusa with [Dato CMS](https://www.datocms.com/). 

Similar to the way that the [Contentful plugin](https://github.com/medusajs/medusa/tree/master/packages/medusa-plugin-contentful) works, users should be able to add `medusa-plugin-sanity` to their `medusa-config.js` file and synchronization should start. The entities to synchronize are:

- Products
  - Incl. options
- Product Variants
  - Incl. options and prices
- Regions

If possible the synchronization should be a two-way sync making it possible to update fields like `title, subtitle, handle, etc.` from Dato CMS.

**Comment by srindom** [comment]
Very cool! Go for it 💪

**Comment by giuseppecutuli** [comment]
Hej @srindom, can i work on this issue?

**Comment by srindom** [comment]
Closing as stale
