### ISSUE TITLE
`medusa-starter-default`: Docker support

### ISSUE THREAD

**Issue by olivermrbl** [medusajs/medusa#481]
We would like to add Docker support to our [Medusa Starter](https://github.com/medusajs/medusa-starter-default).

Optimally, we would like to run everything using `docker-compose`, but this would require us to add hot reloading to the container that holds the Medusa Node.js server.

Alternatively, we could simply run the Postgres DB and Redis server in containers and then connect to those from a locally running Medusa Node.js server.

Oh and other suggestions are very welcome!

**Comment by olivermrbl** [comment]
Would be great! @Yuhanun 

This issue is really not so much for the core, but for the [`medusa-starter-default`](https://github.com/medusajs/medusa-starter-default). Optimally we would use a docker-compose to spin up all resources; Medusa, Postgres, and Redis, but, as mentioned, if we choose to go down this path, support for hot reloading the Node.js container is required.

Yes, the approach in which we mount the Medusa project by creating a volume should suffice. We've tried this out a couple of times, but never had a version ready to include in the repo. Let me know, if I should try to dig out those files :) 

My response prob. does not help you a lot but more clarifies that 1) this issue is not for the core, and 2) hot reloading using volumes is a good approach.

**Comment by Yuhanun** [comment]
> 
> 
> Would be great! @Yuhanun
> 
> This issue is really not so much for the core, but for the [`medusa-starter-default`](https://github.com/medusajs/medusa-starter-default). Optimally we would use a docker-compose to spin up all resources; Medusa, Postgres, and Redis, but, as mentioned, if we choose to go down this path, support for hot reloading the Node.js container is required.
> 
> Yes, the approach in which we mount the Medusa project by creating a volume should suffice. We've tried this out a couple of times, but never had a version ready to include in the repo. Let me know, if I should try to dig out those files :)
> 
> My response prob. does not help you a lot but more clarifies that 1) this issue is not for the core, and 2) lets go with mounting the Node.js project.

So how do you see the usage of this? Do you just see this all being in the starter repo? And then when you npm start, it'll launch the containers or?... I thought the usage would be embedded into `medusa develop` but that doens't seem to be what you want it to be.

**Comment by edleeman17** [comment]
I'd like to express my interesting in helping out too. Very much like to get a production docker-compose file up and running (without hot reloading) that can be deployed as a stack to any server.

**Comment by olivermrbl** [comment]
See the [starter](https://github.com/medusajs/medusa-starter-default) for a working Docker setup.
