### ISSUE TITLE
Categories not displayed in frontend

### ISSUE THREAD

**Issue by spacewalkingninja** [medusajs/medusa#4810]
## Bug report
@olivermrbl hello i am here to say that I enabled categories the feature and unfrotunately what happens is that I still get 404 on the frontend, make it like prestashop and thirtybees so its like in the old times when we were scriptkiddies and just installed a cms and it already has a theme that actually manages to show the categories lol 
### System information

Medusa version (including plugins):
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by srindom** [comment]
Please follow the bug reporting template - we can't reproduce the issue with the description you have provided.

**Comment by spacewalkingninja** [comment]
> 

HAHAHAHAHHAHAHAHAHAHAH!!!!! lol lol lol lol lol lol lol lol listen to what you write, smells like malicious complience. 
So, basically what I am trying to tell you is that the DEFAULT STOREFRONT DOES NOT HAVE CVATEGORIES, DEFAULT STOREFRONT ONLY HAS COLLECTIONS. WITH FLAG CATEGORIES ON, I HAVE NO ACCESS TO THE CATEGORIES WHEN I ACCESS STOREFRONT BECAUSE IT IS NOT IMPLEMENTED.

**Comment by srindom** [comment]
Appreciate you taking the time to flag it, but we are unfortunately not able to reproduce the issue with the details you have provided. If you could add a few more details that would be helpful.
