### ISSUE TITLE
There are no categories with flag categories ON

### ISSUE THREAD

**Issue by spacewalkingninja** [medusajs/medusa#4813]
@olivermrbl I am assigning this to you and to my big friend @srindom
Challenges:
1st  : you have to find the bug, it is an esaster egg you yourselves have hidden
2nd: This is the big challenge for you, deliver an actual CMS that online vendors can use.

So here is the bug.
In PRESTASHIOP and THIRTYBEES  when you install NEW cms, **there is categories by DEFAULT**. Nothing hard? Apparently hardfor medusa.
Anyway, I aklready know medusa's dumbn ways of turning categories on because for some reason you couldn't make it by default.
THAT IS OK, TRUST ME IT IS OK.
problem is
there is no USER INTERFACE CATEGORIES PAGE OUTSIDE OF ADMIN!
THE DEFAULT THEME DOES NOT HAVE A CATEGORIES PAGE.
FIX IT!
I am very very saddened with your attitude and lack of fixes to the things I post. It smells tome you are waiting for ME TO FIX UR PROBLEMS!
Which is not happening **NOT** cause I don't want, but _because you write code in bad ways.,_ I say use liteSQL cuz its low on RAM you go use postOGREsql, which uses 20 mb ram per connection. You couldve just used mysql.
You couldve just used phpmysqlcssjs and it would work.
**FIX UI FRONT END CATEGORY PAGE DOES NOT EXIST MAKE IT EXIST**
**MAKE APP/(main)/categories/routes.ts**

**Comment by spacewalkingninja** [comment]
where is **_FIX!!?!?!?!?????!?!!!!!!!!!!!???????!?!?!?!?!?!?_** @olivermrbl @srindom

**Comment by spacewalkingninja** [comment]
more info for @olivermrbl and @srindom :
when I make api request to backend 
```
<title>Error</title>
</head>
<body>
<pre>Cannot GET /store/categories</pre>
```

**Comment by olivermrbl** [comment]
@spacewalkingninja, please keep a respectful tone.

Closing as this is not meeting Issue reporting requirements, as seen in the templates.
