### ISSUE TITLE
API Ref(admin): Issue in List Product Categories

### ISSUE THREAD

**Issue by dsks-pawn** [medusajs/medusa#4816]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I still use the product's api normally, in the case of product categories, am I missing something config?
I tried the following in the document: **medusa.admin.productCategories.list()**

but always return 404 error code.
  Error: Request failed with status code 404
     at createError (D:\vinco\mds_be_beta\node_modules\@medusajs\medusa-js\node_modules\axios\lib\core\createError.js:16:15)
     at settle (D:\vinco\mds_be_beta\node_modules\@medusajs\medusa-js\node_modules\axios\lib\core\settle.js:17:12)
     at IncomingMessage.handleStreamEnd (D:\vinco\mds_be_beta\node_modules\@medusajs\medusa-js\node_modules\axios\lib\adapters\http.js:293:11)
     at IncomingMessage.emit (node:events:525:35)
     at endReadableNT (node:internal/streams/readable:1358:12)

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for submitting this issue @dsks-pawn . Can I get you to confirm that you have the product categories feature flag enabled? You can learn more about enabilng it [here](https://docs.medusajs.com/development/feature-flags/toggle).

**Comment by dsks-pawn** [comment]
> Thank you for submitting this issue @dsks-pawn . Can I get you to confirm that you have the product categories feature flag enabled? You can learn more about enabilng it [here](https://docs.medusajs.com/development/feature-flags/toggle).

Thanks for the help, I solved the problem adding MEDUSA_FF_PRODUCT_CATEGORIES to .env
It will be easy for medusa newbies like me to warn to add this option to product categories

**Comment by shahednasser** [comment]
There's actually a "feature flag" badge next to the [endpoint's title in the API reference](https://docs.medusajs.com/api/admin#product-categories_getproductcategories). If you hover over it, you should find the necessary instructions.

Will close this issue as resolved

**Comment by vasilemidrigan** [comment]
> Thank you for submitting this issue @dsks-pawn . Can I get you to confirm that you have the product categories feature flag enabled? You can learn more about enabilng it [here](https://docs.medusajs.com/development/feature-flags/toggle).

Works! So as I see, we have flags as a solution to integrate new features gradually in application, until we make sure they work fine.

**Comment by shahednasser** [comment]
Yes @vasilemidrigan that's true

**Comment by itdev13** [comment]
all apis are working but create product category is not working. Its giving CORS issue why? @vasilemidrigan

**Comment by RajDubariya** [comment]
@Varma2116 

If you want to use product categories on the storefront, refer to this link :
[https://docs.medusajs.com/modules/products/categories](url)

If you want to use  product categories on the admin side, refer to this link :
[https://docs.medusajs.com/modules/products/admin/manage-categories](url)
