### ISSUE TITLE
Healthcheck Fails after Default Deployment to Railway from Medusa Docs

### ISSUE THREAD

**Issue by samhenderson511** [medusajs/medusa#4824]
### Describe the bug

After running a default deployment to Railway using the provided steps from the Medusa documentation, the healthcheck consistently failed. The service repeatedly returned “service unavailable” across all attempts.

### System information

Medusa version (including plugins): backend template
Node.js version: not sure
Database: Postgres and redis
Operating system: n/a
Browser (if relevant):

### Steps to reproduce the behavior

	1.	Follow the default deployment guide provided by Medusa for Railway.
	2.	Observe the healthcheck status after deployment.

### Expected behavior

The healthcheck should succeed and the service should be available.

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

```
Pushing [==================================================>]  670.8MB 76f1e49ca557
Pushed  76f1e49ca557
2919c052-6a54-4066-93cb-f2dc99018ef8: digest: sha256:1242fafbc7ccd3baa728cd52af4586839547c039e1c46fb9b469660e1eae9678 size: 2842
Publish time: 34.01 seconds

Starting Healthcheck

Path: /health
Retry window: 5m0s

Attempt #1 failed with service unavailable. Continuing to retry...
... Attempt #14 failed with service unavailable. Continuing to retry for 28s

1/1 replicas never became healthy!
Healthcheck failed!
```

**Comment by hassanthegooner** [comment]
Also seeing this issue with a fresh `Create Medusa App` project and following the default deployment guide

**Comment by samhenderson511** [comment]
I think I've fixed it, you need to enable redis in the medusa.config.js file under projectConfig

**Comment by hassanthegooner** [comment]
@samhenderson511 I've got that enabled:

```js
const modules = {
  eventBus: {
    resolve: "@medusajs/event-bus-redis",
    options: {
      redisUrl: REDIS_URL
    }
  },
  cacheService: {
    resolve: "@medusajs/cache-redis",
    options: {
      redisUrl: REDIS_URL
    }
  }
};
```

Can I ask what scripts do you have in your package.json? And did you add a `nixpacks.toml` file as per [step 1 in the instructions](https://docs.medusajs.com/deployments/server/deploying-on-railway#optional-step-1-add-nixpacks-configurations)?

**Comment by shahednasser** [comment]
@samhenderson511 thank you for submitting this issue! Just to clarify, the error you faced was solved by adding the [redis_url configuration](https://docs.medusajs.com/development/backend/configurations#redis_url)? This would help us improve the documentation.

**Comment by samhenderson511** [comment]
@hassanthegooner @shahednasser sorry my last message wasn't very clear. I don't have a nixpacks config file in my project but this is what the end of my medusa config looks like

```
/** @type {import('@medusajs/medusa').ConfigModule["projectConfig"]} */
const projectConfig = {
  jwtSecret: process.env.JWT_SECRET,
  cookieSecret: process.env.COOKIE_SECRET,
  store_cors: STORE_CORS,
  database_url: DATABASE_URL,
  admin_cors: ADMIN_CORS,
  redis_url: REDIS_URL,
  database_type: "postgres",
};

/** @type {import('@medusajs/medusa').ConfigModule} */
module.exports = {
  projectConfig,
  plugins,
  modules,
};
```

**Comment by hassanthegooner** [comment]
@samhenderson511 weirdly, it deployed successfully for me only when I change the Start Command on Railway to `medusa migrations run && medusa develop`

<img width="1035" alt="image" src="https://github.com/medusajs/medusa/assets/13663684/eb0bf47a-6d32-4ce8-bf2c-da1e9d5c8b40">

**Comment by shahednasser** [comment]
@hassanthegooner so it didn't work when the start command was `medusa migrations run && medusa start` as indicated by the docs?

**Comment by samhenderson511** [comment]
So it turns out that successful deployment was a red herring. Future deployments haven't worked and the successful deployment kept crashing with

```
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
﻿
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
﻿
81.141.138.121 - - [23/Aug/2023:16:11:39 +0000] "GET / HTTP/1.1" 500 148 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
﻿
AbortError: GET can't be processed. The connection is already closed.
```

I'm getting the original healthcheck errors again now.

**Comment by hassanthegooner** [comment]
@samhenderson511 I've actually got it working reliably now but just the backend. 

I think that these are the **essential** steps to get it working:
- Remove @medusajs/admin from the `plugins` array
- Changed the **Build Command** in Railway to `yarn run build:server`
- The **Start Command** in Railway is set to the recommended `medusa migrations run && medusa start`

I also changed a few package.json scripts though I'm not 100% sure that the changes were necessary:
```json
{
    "clean": "./node_modules/.bin/rimraf dist",
    "build": "npm run build:server && npm run build:admin",
    "build:server": "tsc -p tsconfig.json",
    "build:admin": "medusa-admin build",
    "watch": "cross-env tsc --watch",
    "test": "cross-env jest",
    "seed": "cross-env medusa seed -f ./data/seed.json",
    "start": "npm run build && medusa start",
    "start:custom": "npm run build && node --preserve-symlinks --trace-warnings index.js",
    "dev": "cross-env npm run build:server && medusa develop"
  }
```

My config file:
```js
const dotenv = require("dotenv");

let ENV_FILE_NAME = "";
switch (process.env.NODE_ENV) {
  case "production":
    ENV_FILE_NAME = ".env.production";
    break;
  case "staging":
    ENV_FILE_NAME = ".env.staging";
    break;
  case "test":
    ENV_FILE_NAME = ".env.test";
    break;
  case "development":
  default:
    ENV_FILE_NAME = ".env";
    break;
}

try {
  dotenv.config({ path: process.cwd() + "/" + ENV_FILE_NAME });
} catch (e) {}

// CORS when consuming Medusa from admin
const ADMIN_CORS =
  process.env.ADMIN_CORS || "http://localhost:7000,http://localhost:7001";

// CORS to avoid issues when consuming Medusa from a client
const STORE_CORS = process.env.STORE_CORS || "http://localhost:8000";

const DATABASE_URL =
  process.env.DATABASE_URL || "postgres://localhost/medusa-store";

const REDIS_URL = process.env.REDIS_URL || "redis://localhost:6379";

console.log("REDIS_URL", REDIS_URL);
console.log("process.env.NODE_ENV", process.env.NODE_ENV);

const plugins = [
  `medusa-fulfillment-manual`,
  `medusa-payment-manual`,
  {
    resolve: `@medusajs/file-local`,
    options: {
      upload_dir: "uploads",
    },
  },
  // {
  //   resolve: "@medusajs/admin",
  //   /** @type {import('@medusajs/admin').PluginOptions} */
  //   options: {
  //     autoRebuild: true,
      // develop: {
      //   open: process.env.OPEN_BROWSER !== "false",
      // },
  //   },
  // }
];

const modules = {
  eventBus: {
    resolve: "@medusajs/event-bus-redis",
    options: {
      redisUrl: REDIS_URL
    }
  },
  cacheService: {
    resolve: "@medusajs/cache-redis",
    options: {
      redisUrl: REDIS_URL
    }
  }
};

/** @type {import('@medusajs/medusa').ConfigModule["projectConfig"]} */
const projectConfig = {
  jwtSecret: process.env.JWT_SECRET,
  cookieSecret: process.env.COOKIE_SECRET,
  store_cors: STORE_CORS,
  database_url: DATABASE_URL,
  admin_cors: ADMIN_CORS,
  redis_url: REDIS_URL
};

/** @type {import('@medusajs/medusa').ConfigModule} */
module.exports = {
  projectConfig,
  plugins,
  modules,
};
```

Worth noting again that this results in just the Medusa backend deployment so will attempt to deploy the admin separately on Vercel if I can't get the admin to work on Railway

**Comment by samhenderson511** [comment]
@hassanthegooner thank you for this! I'll give it a go. Have you tried to connect an admin deployment to it yet?

**Comment by hassanthegooner** [comment]
@samhenderson511 got the admin deployed on Vercel and connected to the backend on Railway! Will do a bit more testing in the morning then share my process if it all works well 🥲

**Comment by shahednasser** [comment]
Thank you guys for weighing in on your experience. I don't think the admin is related to the errors you've been getting, as looking at the errors @samhenderson511 posted, it seems like it's trying to connect to redis at `127.0.0.1:6379`. Did you set the Redis environment variables correctly as [indicated in the docs](https://docs.medusajs.com/deployments/server/deploying-on-railway#configure-environment-variables)? Make sure that you set it correctly for all Redis connections (such as modules) or use the same redis environment variables for all of them.

**Comment by hassanthegooner** [comment]
@samhenderson511 can confirm that I have the admin working via Vercel and that it's connected to the backend so I'm able to login, create a product etc. 

A few changes I made to deploying to Railway:
- Set the @medusajs/admin plugin's `autoRebuild` option to `false`
- Changed the `build:admin` script in my package.json to `medusa-admin build --deployment`
- Changed the **Build Command** in Railway back to `yarn run build`
- The Start Command in Railway is set to the recommended medusa migrations run && medusa start

So my medusa-config.js plugins looks like so:
```js
const plugins = [
  `medusa-fulfillment-manual`,
  `medusa-payment-manual`,
  {
    resolve: `@medusajs/file-local`,
    options: {
      upload_dir: "uploads",
    },
  },
  {
    resolve: "@medusajs/admin",
    /** @type {import('@medusajs/admin').PluginOptions} */
    options: {
      autoRebuild: false,
    },
  }
];
```

My package.json scripts:
```json
{
    "clean": "./node_modules/.bin/rimraf dist",
    "build": "npm run build:server && npm run build:admin",
    "build:server": "tsc -p tsconfig.json",
    "build:admin": "medusa-admin build --deployment",
    "watch": "cross-env tsc --watch",
    "test": "cross-env jest",
    "seed": "cross-env medusa seed -f ./data/seed.json",
    "start": "npm run build && medusa start",
    "start:custom": "npm run build && node --preserve-symlinks --trace-warnings index.js",
    "dev": "cross-env npm run build:server && medusa develop"
  }
```

I also have environment variables pointing towards the Railway Postgres and Redis instances as mentioned by @shahednasser above.

```
COOKIE_SECRET=your_secret
DATABASE_TYPE=postgres
JWT_SECRET=your_secret
PORT=9000
DATABASE_URL=${{Postgres.DATABASE_URL}}
REDIS_URL=${{Redis.REDIS_URL}}
```

I then followed the instructions to deploy the admin to Vercel here: https://docs.medusajs.com/deployments/admin/deploying-on-vercel

**Comment by samhenderson511** [comment]
@shahednasser @hassanthegooner I've only just managed to test this solution, I'm still getting this redis error on the backend:
``` console
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379

at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
```
My env variables seem to be correct
``` env
REDISHOST=${{Redis.REDISHOST}}
REDISPASSWORD=${{Redis.REDISPASSWORD}}
REDISPORT=${{Redis.REDISPORT}}
REDISUSER=${{Redis.REDISUSER}}
REDIS_URL=${{Redis.REDIS_URL}}
```
And my medusa-config.js is exactly the same as yours:

``` javascript
const dotenv = require("dotenv");

let ENV_FILE_NAME = "";
switch (process.env.NODE_ENV) {
  case "production":
    ENV_FILE_NAME = ".env.production";
    break;
  case "staging":
    ENV_FILE_NAME = ".env.staging";
    break;
  case "test":
    ENV_FILE_NAME = ".env.test";
    break;
  case "development":
  default:
    ENV_FILE_NAME = ".env";
    break;
}

try {
  dotenv.config({ path: process.cwd() + "/" + ENV_FILE_NAME });
} catch (e) {}

// CORS when consuming Medusa from admin
const ADMIN_CORS =
  process.env.ADMIN_CORS || "http://localhost:7000,http://localhost:7001";

// CORS to avoid issues when consuming Medusa from a client
const STORE_CORS = process.env.STORE_CORS || "http://localhost:8000";

const DATABASE_URL =
  process.env.DATABASE_URL || "postgres://localhost/medusa-store";

const REDIS_URL = process.env.REDIS_URL || "redis://localhost:6379";

const plugins = [
  `medusa-fulfillment-manual`,
  `medusa-payment-manual`,
  {
    resolve: `@medusajs/file-local`,
    options: {
      upload_dir: "uploads",
    },
  },
  {
    resolve: "@medusajs/admin",
    /** @type {import('@medusajs/admin').PluginOptions} */
    options: {
      autoRebuild: false,
    },
  },
];

const modules = {
  eventBus: {
    resolve: "@medusajs/event-bus-redis",
    options: {
      redisUrl: REDIS_URL,
    },
  },
  cacheService: {
    resolve: "@medusajs/cache-redis",
    options: {
      redisUrl: REDIS_URL,
    },
  },
};

/** @type {import('@medusajs/medusa').ConfigModule["projectConfig"]} */
const projectConfig = {
  jwtSecret: process.env.JWT_SECRET,
  cookieSecret: process.env.COOKIE_SECRET,
  store_cors: STORE_CORS,
  database_url: DATABASE_URL,
  admin_cors: ADMIN_CORS,
  redis_url: REDIS_URL,
};

/** @type {import('@medusajs/medusa').ConfigModule} */
module.exports = {
  projectConfig,
  plugins,
  modules,
};
```
package scripts are also the same:
``` json
  "scripts": {
    "clean": "./node_modules/.bin/rimraf dist",
    "build": "npm run build:server && npm run build:admin",
    "build:server": "tsc -p tsconfig.json",
    "build:admin": "medusa-admin build --deployment",
    "watch": "cross-env tsc --watch",
    "test": "cross-env jest",
    "seed": "cross-env medusa seed -f ./data/seed.json",
    "start": "npm run build && medusa start",
    "start:custom": "npm run build && node --preserve-symlinks --trace-warnings index.js",
    "dev": "cross-env npm run build:server && medusa develop"
  },
```

Any ideas?

**Comment by hassanthegooner** [comment]
Do you have a redis instance on Railway? Maybe you can restart the database if so.

<img width="416" alt="image" src="https://github.com/medusajs/medusa/assets/13663684/74286194-47dd-4ba0-a7e7-0819f1f4a7a6">

Also, ensure that `REDIS_URL` env variable for the Github app is set to `${{Redis.REDIS_URL}}`

**Comment by samhenderson511** [comment]
Thank you @shahednasser , I have the backend working now, Railway just wasn't picking up the right env variable for some reason. I'm now having trouble with the admin dashboard. When I try to login it returns a 405:
``` console
Failed to load resource: the server responded with a status of 405 () ... from my railway deployment domain
```

**Comment by samhenderson511** [comment]
Ah I've got it! my MEDUSA_BACKEND_URL wasn't in the format https://domain.com, it was just domain.com

**Comment by shahednasser** [comment]
Glad you figured it out! Is it ok to close this issue now? 😇

**Comment by samhenderson511** [comment]
Yes, thank you

**Comment by nonfungibletunji** [comment]
i am getting the health check fails.....after using the deploy to railway button in the repo
```Javascript
const dotenv = require("dotenv");

let ENV_FILE_NAME = "";
switch (process.env.NODE_ENV) {
  case "production":
    ENV_FILE_NAME = ".env.production";
    break;
  case "staging":
    ENV_FILE_NAME = ".env.staging";
    break;
  case "test":
    ENV_FILE_NAME = ".env.test";
    break;
  case "development":
  default:
    ENV_FILE_NAME = ".env";
    break;
}

try {
  dotenv.config({ path: process.cwd() + "/" + ENV_FILE_NAME });
} catch (e) {}

// CORS when consuming Medusa from admin
const ADMIN_CORS =
  process.env.ADMIN_CORS || "http://localhost:7000,http://localhost:7001";

// CORS to avoid issues when consuming Medusa from a client
const STORE_CORS = process.env.STORE_CORS || "http://localhost:8000";

const DATABASE_URL =
  process.env.DATABASE_URL || "postgres://localhost/medusa-store";

const REDIS_URL = process.env.REDIS_URL || "redis://localhost:6379";

const plugins = [
  `medusa-fulfillment-manual`,
  `medusa-payment-manual`,
  {
    resolve: `@medusajs/file-local`,
    options: {
      upload_dir: "uploads",
    },
  },
  {
    resolve: "@medusajs/admin",
    /** @type {import('@medusajs/admin').PluginOptions} */
    options: {
      autoRebuild: false,
      develop: {
        open: process.env.OPEN_BROWSER !== "false",
      },
    },
  },
];

const modules = {
  eventBus: {
    resolve: "@medusajs/event-bus-redis",
    options: {
      redisUrl: REDIS_URL
    }
  },
  cacheService: {
    resolve: "@medusajs/cache-redis",
    options: {
      redisUrl: REDIS_URL
    }
  },
};

/** @type {import('@medusajs/medusa').ConfigModule["projectConfig"]} */
const projectConfig = {
  jwtSecret: process.env.JWT_SECRET,
  cookieSecret: process.env.COOKIE_SECRET,
  store_cors: STORE_CORS,
  database_url: DATABASE_URL,
  admin_cors: ADMIN_CORS,
  // Uncomment the following lines to enable REDIS
  redis_url: REDIS_URL
};

/** @type {import('@medusajs/medusa').ConfigModule} */
module.exports = {
  projectConfig,
  plugins,
  modules,
};
```

**Comment by samhenderson511** [comment]
@nonfungibletunji Did you get it working? I would try restarting the redis service and maybe remove the localhost fallback url.

**Comment by jpizzle34** [comment]
For me the problem was that the medusa backend service couldn't connect to the postgres instance (and redis). I had to change the following environment variables in the medusa backend service to properly reference the Postgres and Redis services in railway:

`DATABASE_URL`: from `${{Postgresql.DATABASE_URL}}`  to `${{postgresql.DATABASE_URL}}`
`REDIS_URL`: from `${{Redis.DATABASE_URL}}`  to `${{redis.REDIS_URL}}`

So, just change uppercase to lowercase for the postgres and redis service names. The railway UI will provide you with feedback as you type by showing autocomplete suggestions. 

Also you may notice that once you update the variables, railway will automatically merge variables that have the same reference.

**Comment by modzincltd** [comment]
Incase this helps anyone else the problem I was getting an error saying health checked failed deploying to digital ocean apps.

In the medusa docs it says more time is needed between the build and health check so I set the deley health check to 300s and it seems to work. so have a look on your hosting and see if this option is there.

I assume medusa takes a little longer than standard node apps to completely spin up .

hope this helps someone

**Comment by volkan0x** [comment]
> @samhenderson511 I've actually got it working reliably now but just the backend.
> 
> I think that these are the **essential** steps to get it working:
> 
> * Remove @medusajs/admin from the `plugins` array
> * Changed the **Build Command** in Railway to `yarn run build:server`
> * The **Start Command** in Railway is set to the recommended `medusa migrations run && medusa start`
> 
> I also changed a few package.json scripts though I'm not 100% sure that the changes were necessary:
> 
> ```json
> {
>     "clean": "./node_modules/.bin/rimraf dist",
>     "build": "npm run build:server && npm run build:admin",
>     "build:server": "tsc -p tsconfig.json",
>     "build:admin": "medusa-admin build",
>     "watch": "cross-env tsc --watch",
>     "test": "cross-env jest",
>     "seed": "cross-env medusa seed -f ./data/seed.json",
>     "start": "npm run build && medusa start",
>     "start:custom": "npm run build && node --preserve-symlinks --trace-warnings index.js",
>     "dev": "cross-env npm run build:server && medusa develop"
>   }
> ```
> 
> My config file:
> 
> ```js
> const dotenv = require("dotenv");
> 
> let ENV_FILE_NAME = "";
> switch (process.env.NODE_ENV) {
>   case "production":
>     ENV_FILE_NAME = ".env.production";
>     break;
>   case "staging":
>     ENV_FILE_NAME = ".env.staging";
>     break;
>   case "test":
>     ENV_FILE_NAME = ".env.test";
>     break;
>   case "development":
>   default:
>     ENV_FILE_NAME = ".env";
>     break;
> }
> 
> try {
>   dotenv.config({ path: process.cwd() + "/" + ENV_FILE_NAME });
> } catch (e) {}
> 
> // CORS when consuming Medusa from admin
> const ADMIN_CORS =
>   process.env.ADMIN_CORS || "http://localhost:7000,http://localhost:7001";
> 
> // CORS to avoid issues when consuming Medusa from a client
> const STORE_CORS = process.env.STORE_CORS || "http://localhost:8000";
> 
> const DATABASE_URL =
>   process.env.DATABASE_URL || "postgres://localhost/medusa-store";
> 
> const REDIS_URL = process.env.REDIS_URL || "redis://localhost:6379";
> 
> console.log("REDIS_URL", REDIS_URL);
> console.log("process.env.NODE_ENV", process.env.NODE_ENV);
> 
> const plugins = [
>   `medusa-fulfillment-manual`,
>   `medusa-payment-manual`,
>   {
>     resolve: `@medusajs/file-local`,
>     options: {
>       upload_dir: "uploads",
>     },
>   },
>   // {
>   //   resolve: "@medusajs/admin",
>   //   /** @type {import('@medusajs/admin').PluginOptions} */
>   //   options: {
>   //     autoRebuild: true,
>       // develop: {
>       //   open: process.env.OPEN_BROWSER !== "false",
>       // },
>   //   },
>   // }
> ];
> 
> const modules = {
>   eventBus: {
>     resolve: "@medusajs/event-bus-redis",
>     options: {
>       redisUrl: REDIS_URL
>     }
>   },
>   cacheService: {
>     resolve: "@medusajs/cache-redis",
>     options: {
>       redisUrl: REDIS_URL
>     }
>   }
> };
> 
> /** @type {import('@medusajs/medusa').ConfigModule["projectConfig"]} */
> const projectConfig = {
>   jwtSecret: process.env.JWT_SECRET,
>   cookieSecret: process.env.COOKIE_SECRET,
>   store_cors: STORE_CORS,
>   database_url: DATABASE_URL,
>   admin_cors: ADMIN_CORS,
>   redis_url: REDIS_URL
> };
> 
> /** @type {import('@medusajs/medusa').ConfigModule} */
> module.exports = {
>   projectConfig,
>   plugins,
>   modules,
> };
> ```
> 
> Worth noting again that this results in just the Medusa backend deployment so will attempt to deploy the admin separately on Vercel if I can't get the admin to work on Railway

this fixed my railway deployment issue but i had to change the `yarn` to `npm` in Build command in Railway for some reason:

 `npm run build:server`
