### ISSUE TITLE
Create a Product, admin endpoint returns "Invalid API Token" error even though it was generated via admin UI's Settings > Publishable API Keys section

### ISSUE THREAD

**Issue by harshajayaweeraXHJ** [medusajs/medusa#4828]
"Create a Product" admin endpoint returns "Invalid API Token" error even though it was generated via admin UI's Settings > Publishable API Keys section as show below

<img width="1568" alt="image" src="https://github.com/medusajs/medusa/assets/10755531/be687c0d-8fce-475c-a38e-7da7b9e998c0">

This is the curl address I used

```
curl --location '<my_backend_url_here>/admin/products' \
--header 'Authorization: Bearer <KEY_GENERATED_ABOVE>' \
--header 'Content-Type: application/json' \
--data '{
    "title": "Shirt"
}'
```
and it returns following error 

```
{
    "code": "unknown_error",
    "type": "unknown_error",
    "message": "An unknown error occurred."
}
```

But when I looked at the logs I see following error 

{"level":"error","message":"Invalid API Token","timestamp":"......"}

Any idea what is causing this

**Comment by fPolic** [comment]
The header for publishable keys is: `x-publishable-api-key` but publishable API keys are not API auth tokens

**Comment by harshajayaweeraXHJ** [comment]
@fPolic 
I see. How can I generate API auth tokens? Can you please explain

**Comment by olivermrbl** [comment]
@harshajayaweeraXHJ, you can't generate API tokens through the admin dashboard yet. You'll have to either insert it directly in the database on one of your user entities. Alternatively, use the API via curl or our client. Read more [here](https://docs.medusajs.com/api/admin#authentication).

**Comment by harshajayaweeraXHJ** [comment]
@olivermrbl What does "sid" mean and where can I obtain it from
<img width="549" alt="Screen Shot 2023-08-23 at 1 22 13 AM" src="https://github.com/medusajs/medusa/assets/10755531/9f6d6c93-a26c-4fe9-a4f4-3fea1cfd7f46">

Also if I'm not mistaken and "sid" is not some sort of authentication id or token, this endpoint is unauthenticated right?. So pretty much anyone with backend url and add access token to the backend?

**Comment by harshajayaweeraXHJ** [comment]
Found it. Posting here for anyone who might come across the same issue.

1. Run following api call with your login credentials
```
curl --location '<BACKEND_URL>/admin/auth' \
--header 'Content-Type: application/json' \
--data-raw '{
  "email": "<YOUR_EMAIL>",
  "password": "<YOUR_PASSWORD>"
}'

```
2. In the response and response headers you can find the user id and sid

3. Then you can follow the instructions in the [link](https://docs.medusajs.com/api/admin#authentication) @olivermrbl mentioned above to add your access token
