### ISSUE TITLE
Medusa seeding script causing errors on staging environments 

### ISSUE THREAD

**Issue by kstoklosa** [medusajs/medusa#4844]
### Describe the bug

I have created a configuration for my backend project. Every time I deploy a new version of the backend, I want to use the `medusa seed` command. Most of the time, I update the seed file every time a new migration occurs. Unfortunately, I am not able to run seed script afterwards, because this is breaking my staging preview deployments with errors such as `Error: A user with the same email already exists.`

### System information

Medusa version (including plugins): 1.12.4-canary-20230724143258
Node.js version: 18.x.x
Database: Postgres
Operating system: MacOS Ventura 13.4
Browser (if relevant): - 

### Steps to reproduce the behavior

1. Deploy your medusa backend with medusa seed script as a release command
2. Deploy your app for the second time, try to seed your database once again
3. Error stops the deployment

### Expected behavior

I want to be able to run seed script without the need of dropping database first. 

### Additional context

From what I've observed, the seed script from Medusa is using transactions with create methods for services. Replacing them with the upsert method would fix that issue (it should be implemented for all existing services), but it might produce some unexpected behaviors for other users who are unaware of that. Another way to handle this would be to wrap the transaction with a try/catch block and provide descriptive error handling without throwing an actual error.

**Comment by johncarmack1984** [comment]
Encountering same issue here. I concur either using upsert (or something like Laravel's [db:seed --force](https://laravel.com/docs/10.x/seeding#forcing-seeding-production)) would be helpful when setting up dev, testing, and staging environments.

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏

@thetutlage something to consider when working on the migration CLI
