### ISSUE TITLE
Events don't get processed after reconnect to the lost database connection

### ISSUE THREAD

**Issue by hanam1ni** [medusajs/medusa#4848]
### Describe the bug

When Medusa's backend reestablishes the connection with the database after it loses the connection, any events that are enqueued afterward won't get processed until the Medusa's backend is restarted

### System information

- Medusa version (including plugins):
  - @medusajs/cache-redis: 1.8.0
  - @medusajs/event-bus-redis: 1.8.9
  - @medusajs/medusa: 1.13.0
  - @medusajs/medusa-cli: 1.3.8
- Node.js version: v18.15.0
- Database: Postgres 10.4
- Operating system: Mac 13.2

### Steps to reproduce the behavior

1. Create a dummy subscriber for reproducing the issue
```ts
// src/subscribers/hello-subscriber.ts
class HelloSubscriber {
  constructor({ eventBusService }) {
    eventBusService.subscribe("hello", this.greetings);
  }

  greetings = () => {
    console.log("WORLD");
  };
}

export default HelloSubscriber;
```
2. Emit the event from one of the REST API endpoint
```ts
// src/api/admin/orders/listOrders.ts
export default async (req, res) => {
  const eventBusService = req.scope.resolve("eventBusService");
  await eventBusService.emit("hello", { data: "PAYLOAD" });
  
  return res.json({});
}
```
3. Make a request to the REST API endpoint, the console should print the "WORLD" Message
<img width="486" alt="image" src="https://github.com/medusajs/medusa/assets/14077479/f6f56053-abda-4b04-87a5-09a54b939e87">

4. Stop the database container for a few seconds and start the container again
5. Make a request to the same API endpoint, the console should not print the "WORLD" message

### Expected behavior

When Medusa's backend lost the database connection due to the database being down for a few seconds. After the Medusa's backend is able to reconnect to the database, any events that are enqueued afterward should get processed as usual

### Additional context

This can happen in production applications, my application is deployed to DigitalOcean with a managed database. The managed database gets updated regularly by DigitalOcean, during the update the application gets disconnected from the database for a few minutes.

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
