### ISSUE TITLE
API Ref(admin): Issue in Get Variant's Inventory

### ISSUE THREAD

**Issue by VAN0VICH** [medusajs/medusa#4849]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The logic of getting variant's inventory is not shown. 

### How can this issue be resolved?

1. Replace it with the getting variant's inventory api.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Not sure what the issue exactly is. Can you elaborate?

**Comment by VAN0VICH** [comment]
Oh, I apologise. In **Admin api** -> **product variants** -> **get variant's inventory**, in the sample request instead of medusa.admin.variants.list() should be medusa.admin.variants.getInventory(id), and I just wonder what the variant's inventory response is. 

Just by looking at this code from the repository, I am confused what the response is.

`
const inventory = await client.admin.variants.getInventory(variant.id)

          return await Promise.all(
            inventory.variant.inventory
              .map(async (item) => {
                return Promise.all(
                  stock_locations.map(async (stock_location) => {
                    client.admin.inventoryItems.createLocationLevel(item.id!, {
                      location_id: stock_location.location_id,
                      stocked_quantity: stock_location.stocked_quantity,
                    })
                  })
                )
              })
              .flat()
          )`

**Comment by shahednasser** [comment]
Oh thanks for catching this! Will issue a fix right away.

As for the response, it should be something like this:

```ts
medusa.admin.variants.getInventory(variantId)
.then(({ variant }) => {
  console.log(variant.inventory, variant.sales_channel_availability)
})
```

It's the same response described in the request in the API reference, although that one has variant.variant, which I'll also fix.

**Comment by VAN0VICH** [comment]
in the code snippet above, I'm still confused how `variant.inventory` gets mapped if it's an object. For the reference, it is from admin-ui folder, inside createStockLocationsForVariants() function

**Comment by shahednasser** [comment]
@LordPachimari I've updated the [API reference](https://docs.medusajs.com/api/admin#product-variants_getvariantsvariantinventory) with the correct code example and response schema.

As for the `createStockLocationsForVariants` function you mention this is a different scope

**Comment by Asad886** [comment]
how to get variant inventory item any admin api end point which return inventory item id of variant in admin v2 api's
