### ISSUE TITLE
Guide on how to deploy on AWS

### ISSUE THREAD

**Issue by olivermrbl** [medusajs/medusa#485]
Currently, we have guide for deploying on Heroku, DigitalOcean and Qovery. We would like to add a guide on how to deploy Medusa on AWS resources.

Components: 
- Medusa Node.js application (Could be ECS, Fargate, etc.)
- Postgres DB (Could be RDS, Aurora)
- Redis (Could be ElastiCache)

One could potentially use Docker for the Medusa application.

Follow same format as our [Heroku guide](https://docs.medusa-commerce.com/how-to/deploying-on-heroku)

**Comment by viveakrt** [comment]
Hi , Could I work on that issue? Thank you

**Comment by olivermrbl** [comment]
Hi @viveakrt ! Yes indeed! Let me know, if you need help getting started

**Comment by olivermrbl** [comment]
Hey @viveakrt ! How are things going? Let me know if I can be of your assistance 👍

**Comment by KailashVenthan** [comment]
https://pevey.com/medusa-server-on-ubuntu

**Comment by mumbaigirl** [comment]
Not recommed to use https://pevey.com/medusa-server-on-ubuntu , this guide is not complete and also it throws erros after installation , the nginx proxy isnt working.

**Comment by NicolasGorga** [comment]
Hello is there any update to this? Currently trying to deploy to AWS and having a difficult time
