### ISSUE TITLE
Custom fulfillmentProvider, `fulfillment`params in cancelFulfillment is empty

### ISSUE THREAD

**Issue by BorisKamp** [medusajs/medusa#4850]
Im using Medusa `1.13.1`.

I have a custom fulfillmentProvider, I created it following the guide here
https://docs.medusajs.com/modules/carts-and-checkout/backend/add-fulfillment-provider#cancelfulfillment

When I implement the `cancelFulfillment` method like so:
```javascript
  cancelFulfillment(fulfillment) {
    console.dir(fulfillment)
    return axios.delete('https://todays.picqer.com/api/v1/orders/' + fulfillment.metadata.picqer_order_id, this.picqerAuthConfig)
      .then((response) => {
        return response.data
      })
      .catch((e) => {
        console.dir(e)
        throw e
      })
  }
```

And trigger it by calling `{{medusa-host}}/admin/orders/:orderid/fulfillments/:fulfillmentId/cancel`, the `fulfillment` = `{}`
Why is this? It's supposed to return the fulfillment object right so I can use it like so `fulfillment.metadata.picqer_order_id`?

**Comment by olivermrbl** [comment]
The `cancelFulfillment` method in fulfillment plugins receives the `data` of a given fulfillment - not the entire fulfillment entity. You'll find the method being called in the fulfillment provider [here](https://github.com/medusajs/medusa/blob/af09a4b7b40aad60a06d994fcfd75a05d359f8ff/packages/medusa/src/services/fulfillment-provider.ts#L142).

Therefore, I recommend you store your `picger_order_id` in the `data` property of the fulfillment upon creation, so you can cancel it later using data from the data property.

Your `cancelFulfillment` method will then look something along these lines:
```ts
 cancelFulfillment(fulfillmentData) {
    const picqerOrderId = fulfillmentData.id // or whatever you choose to use as the key for the id

    return axios.delete('https://todays.picqer.com/api/v1/orders/' + picqerOrderId, this.picqerAuthConfig)
      .then((response) => {
        return response.data
      })
      .catch((e) => {
        console.dir(e)
        throw e
      })
  }
```

This is similar to how fulfillments are [handled in our Webshipper plugin](https://github.com/medusajs/medusa/blob/af09a4b7b40aad60a06d994fcfd75a05d359f8ff/packages/medusa-fulfillment-webshipper/src/services/webshipper-fulfillment.js#L575).

Hope this helps!

**Comment by BorisKamp** [comment]
> 

Thank you, that helps for sure. I created a workaround for now by using the `order.fulfillment_canceled` notifier and cancel the picqer order from there.

Im trying to do it trough the `createFulfillment` in my manual class now, but I don't know how to set the `data` of the fulfillment. 
I've tried the following and both dont work:
```
        fulfillment.data.picqer_order_id = res1.data.idorder
        methodData.data = res1.data.idorder
```

And I see [here](https://github.com/medusajs/medusa/blob/af09a4b7b40aad60a06d994fcfd75a05d359f8ff/packages/medusa/src/services/fulfillment.ts#L231) that it's set as empty object always. Can I even set it?

**Comment by olivermrbl** [comment]
Just five lines below the code linked to, the [fulfillment data is set with the response from the fulfillment provider](https://github.com/medusajs/medusa/blob/af09a4b7b40aad60a06d994fcfd75a05d359f8ff/packages/medusa/src/services/fulfillment.ts#L236).

Whatever you return from your `createFulfillment` method in your provider will be set as the `data` of the fulfillment.

It will likely look something along these lines:
```ts
createFulfillment({ ... }) {
    // create Picqer order through axios
    const order = axios.post('https://todays.picqer.com/api/v1/orders/', this.picqerAuthConfig)
      .then((response) => {
        return response.data
      })

    return order.id
  }
```

**Comment by BorisKamp** [comment]
Thank you Oliver!

I ended up with this:
```javascript
createFulfillment({ ... }) {
.....
   // Post to Picqer
    const picqerOrder = await axios.post('https://todays.picqer.com/api/v1/orders', body, this.picqerAuthConfig)
      .then(async (res1) => {
        // Process the order
        await axios.post('https://todays.picqer.com/api/v1/orders/' + res1.data.idorder + '/process', null, this.picqerAuthConfig)
          .catch((e) => {
            console.dir(e)
            throw e
          })

        return res1.data
      })
      .catch((e) => {
        console.dir(e)
        throw e
      })

    return {
      picqer_order_id: picqerOrder.idorder,
    }
}
```

I find it unclear from the docs that whatever you return from your createFulfillment method in your provider will be set as the data of the fulfillment. Maybe thats just me tho. 

Same for this:
https://docs.medusajs.com/modules/carts-and-checkout/backend/add-fulfillment-provider#cancelfulfillment

I expect that `fulfillment` from `cancelFulfillment(fulfillment)` contains the full fulfillment, not just the `fulfillment.data`. I understand that if you're capable enough you can make that up from the source code, but I can't.

Just a tip on doc improvements.

**Comment by olivermrbl** [comment]
Appreciate the input Boris!

Looping in @shahednasser to have a look at possibly changing the fulfillment documentation :)

**Comment by shahednasser** [comment]
Thanks for the feedback @BorisKamp ! Will look into possible improvements in the documentation
