### ISSUE TITLE
API Ref(admin): Issue in Create a Product Variant

### ISSUE THREAD

**Issue by dsks-pawn** [medusajs/medusa#4852]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

When I create the product variant and pass the options price with the following value:
![image](https://github.com/medusajs/medusa/assets/36871547/63bb24b4-0d50-49be-8b32-2018e648348d)

When I go back to the store front, the home page, it seems that the product price is not being displayed as I would like.
![image](https://github.com/medusajs/medusa/assets/36871547/1ecb8539-a5a9-4411-9585-0a0a5b169df4)

I check the data returned by the product demo in the vartiants array, in each object will see these options
![image](https://github.com/medusajs/medusa/assets/36871547/62f0bb4b-1108-4ce1-9204-5091d383022b)

The products I create do not have the above options
Is that the cause? How can I fix this?

1 Another problem is that I see in the money_amout table storing the price with type int4, when the return price is 1950 I see displayed in the store front as €19.50?
Will the price stored in the database divided by 100 be the displayed price, or will it parse according to some logic?

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Did you pass the same prices as in the image? Because it so, it seems like you need to set the price in the region you've chosen.

As for how the prices are stored and displayed in the storefront, you can learn more about it [here](https://docs.medusajs.com/modules/products/#storing-the-product-variants-price) and [here](https://docs.medusajs.com/modules/products/storefront/show-products#display-product-price)

**Comment by dsks-pawn** [comment]
> Did you pass the same prices as in the image? Because it so, it seems like you need to set the price in the region you've chosen.
> 
> As for how the prices are stored and displayed in the storefront, you can learn more about it [here](https://docs.medusajs.com/modules/products/#storing-the-product-variants-price) and [here](https://docs.medusajs.com/modules/products/storefront/show-products#display-product-price)


Sorry that I may not have understood what you mean, but I will try to describe the problem I am having in as much detail as possible.
As mentioned above, I have successfully created a product variant based on the method: medusa.admin.products.createVariant, and the array prices just passed in objects with 2 options amout and currency_code.

![image](https://github.com/medusajs/medusa/assets/36871547/cae345ea-5f27-4f81-8842-b1b35f8a8bfc)

We can see the data in the money_amout table as above, eur is the default product created by medusa, and usd is my new creation. They are no different at all.

Outside the storefront when accessing the product detail page, call the api http://localhost:9000/store/products?id=917ec83d-fbe8-4aa0-80d5-baaf4d0d8d19&cart_id=cart_01H8NTRM03RH14ZEGAZVXWFSMD

Comparing the data my product generates against the default medusa generates, in each object in the array variants fields are missing

 "original_price": ,
 "calculated_price": ,
 "calculated_price_type": "",
 "original_price_incl_tax": ,
 "calculated_price_incl_tax": ,
 "original_tax": ,
 "calculated_tax":
 
 Medusa default product: https://jsonformatter.org/a8ea2f
 Product test: https://jsonformatter.org/6a5b83

**Comment by dsks-pawn** [comment]
after checking i see the price will show based on cart id, but why does it always generate cart with region_id with currency eur?![image](https://github.com/medusajs/medusa/assets/36871547/7385f295-caa2-453d-b284-1680d2043c28)
![image](https://github.com/medusajs/medusa/assets/36871547/99d92249-d442-460d-8259-c6760372fc1b)

I also tried reconfiguring the region as follows:

![image](https://github.com/medusajs/medusa/assets/36871547/f7961eda-e3a9-4509-ad57-4339e7f18470)

how can i fix this?

**Comment by shahednasser** [comment]
If you're not setting a specific region for your cart, the first region will be added automatically to it. You can learn how to set a region for your cart [here](https://docs.medusajs.com/modules/carts-and-checkout/storefront/implement-cart#create-a-cart), and then when you pass the cart ID the region/currency associated with it will be used to show the prices

**Comment by dsks-pawn** [comment]
> Nếu bạn không đặt khu vực cụ thể cho giỏ hàng của mình thì khu vực đầu tiên sẽ tự động được thêm vào đó. Bạn có thể tìm hiểu cách đặt khu vực cho giỏ hàng của mình [tại đây](https://docs.medusajs.com/modules/carts-and-checkout/storefront/implement-cart#create-a-cart) và sau đó khi bạn chuyển ID giỏ hàng, khu vực/đơn vị tiền tệ được liên kết với khu vực đó sẽ được sử dụng để hiển thị giá

Thank you very much for your help, I have fixed this problem

**Comment by shahednasser** [comment]
Great! Will close the issue now
