### ISSUE TITLE
There is no default categories template

### ISSUE THREAD

**Issue by spacewalkingninja** [medusajs/medusa#4872]
Hello!
I have noticed that there is a collections template that is active by default and the nextjs storefront supports it, there i a flag to activate categories, but no UI page for the user to access the categories.
**_HOW DO WE DO THIS?????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????? I NEED THIS ASAP!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! @olivermrbl YOU ARE ASSIGNED BY LAW DECREEE AS OF RIGHTNOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!_**

**Comment by olivermrbl** [comment]
@spacewalkingninja, please keep a positive and respectful tone. If you have feature requests, please use our GitHub Discussions. The Issues are for bug reports only.
