### ISSUE TITLE
(Admin) decimalSeparator cannot be the same as groupSeparator

### ISSUE THREAD

**Issue by alessioacella** [medusajs/medusa#4873]
**Preliminary Checks**

- [x] This issue is not a duplicate. Searched into https://github.com/medusajs/medusa/issues
- [x] Tested on different node versions (16.20, 17, 18)
- [x] Tested on different @medusajs/admin versions (6.0.5, 7.0.0)

**Issue Summary**

1. Login as Admin
2. Open a product
3. Go to the "Variants" section and click on the right menu with three dots 
4. Click on "Edit Prices"

The "Edit Prices" modal will throw this error: "decimalSeparator cannot be the same as groupSeparator"

1. Screenshot of the "$Edit Prices" button

<img width="860" alt="edit-prices-button" src="https://github.com/medusajs/medusa/assets/9121207/b3604b81-8a52-4d89-8675-8b94d1bebc81">

2. Screenshot of the error (Admin version 6.0.0)

<img width="1195" alt="edit-prices-error" src="https://github.com/medusajs/medusa/assets/9121207/3072bd48-1bb2-4deb-9fb3-56342a019016">

_If I am doing anything wrong. Please guide me!_

**How can this issue be resolved?**

In the "currency-cell.tsx" component you wil find:

<img width="773" alt="edit-prices-error-code" src="https://github.com/medusajs/medusa/assets/9121207/f511d205-f63a-40c2-8a98-250361f8667f">

The package "react-currency-input-field" is asking to specify a groupSeparator different from decimalSeparator, which can be done like the following:

<img width="664" alt="edit-prices-error-code-with-fix" src="https://github.com/medusajs/medusa/assets/9121207/213f479f-933f-4072-a1cb-d8736f4e365a">

**Optimization / Off-topic comment**

I think it might be better to let an administrator to directly config these separators through store settings / account preferences (decimal separator, group separator)

**Comment by olivermrbl** [comment]
@alessioacella can you give this snapshot a spin and let us know if it works? 

```
@medusajs/admin-ui@2.0.2-snapshot-20230828111041
```

**Comment by olivermrbl** [comment]
@alessioacella can you give this snapshot a spin and let us know if it works?
```
@medusajs/admin@7.0.2-snapshot-20230828113532
```
