### ISSUE TITLE
Medusa does not pass health checks on Digital Ocean App Platform after following documentation

### ISSUE THREAD

**Issue by devcshort** [medusajs/medusa#4874]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

After following the documentation to a T, I was unable to get Medusa to run on Digital Ocean app platform. After fiddling around with the scripts and settings I was able to get it to run. I'd love to work on updating and enhancing the documentation to better cover this scenario for others who may run in to similar issues.

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for submitting the issue @devcshort , of course you can help update the documentation if you find anything outdated! Just send a PR with your updates. Make sure to check out our [contribution guidelines](https://docs.medusajs.com/contribution-guidelines) for more help on this.

**Comment by Mic-Hawkins** [comment]
@devcshort Wondering what solution you found, as I'm having the same issue myself.

**Comment by devcshort** [comment]
> @devcshort Wondering what solution you found, as I'm having the same issue myself.

If you're in the Medusa discord then I have a thread open that discusses it

**Comment by Mic-Hawkins** [comment]
> If you're in the Medusa discord then I have a thread open that discusses it

I wasn't, but I am now... Thanks, that helped a lot, as I was stumped with the build scripts.

**Comment by shahednasser** [comment]
Thank you both for the input on the deployment process to digitalocean. I've followed through the deployment steps and found what's missing/can be improved, and opened a PR with it.
