### ISSUE TITLE
creating discount without providing start date,will result discount with endDate smaller than startDate

### ISSUE THREAD

**Issue by specture48** [medusajs/medusa#4875]
### Steps to reproduce the behavior

create discount without providing start_date will assign today to the startDate,if you provide enddate smaller than today 
the discount will be created  successfully (that's wrong)

### Expected behavior
it shoud throw validation error

**Comment by olivermrbl** [comment]
@specture48 - thanks for highlighting this case. Validating the expiry date would be a great addition. However, I would expect merchants to configure their discounts sensibly, so this has little to no urgency.

**Comment by olivermrbl** [comment]
That said, I would happily accept a PR, if you are up for the task :)
