### ISSUE TITLE
Adding multiple giftcards results in amount drawn from all

### ISSUE THREAD

**Issue by mortenengel** [medusajs/medusa#4892]
### Describe the bug

Our storefront has enabled adding multiple giftcards to the order, when this is done, the full amount is drawn from both giftcards:
![image](https://github.com/medusajs/medusa/assets/38915779/af20c448-601c-43f8-8f88-904e95674d33)

Upon first inspection of the code I can't quite identify the problem. https://github.com/medusajs/medusa/blob/a1110b34383e4626197e572eac05b1a6164cabcb/packages/medusa/src/services/order.ts#L733 

### System information

Medusa version (including plugins): 1.14
Node.js version: 18.16
Database: postgres
Operating system: linux (prod) windows (dev)
Browser (if relevant): -

### Steps to reproduce the behavior

1. Create 2 custom gift cards in backend
2. Add both to the same basket (not possible on default storefront, but can be done via API)
   POST:   [admin-url]/store/carts/[cartid]    {"gift_cards":[{"code":"[CODE]"}]}
3. Create order
4. See the order in backend, and check the giftcards. Both have had the amount withdrawn

### Expected behavior

If one giftcard covers the entire amount, only spend from that - otherwise start spending from next giftcard.

+ Additional "nice to have" - order gift cards by Expiration date first and remaining balance second, making sure the oldest and smallest gift cards are spent first.

### Screenshots

![image](https://github.com/medusajs/medusa/assets/38915779/af20c448-601c-43f8-8f88-904e95674d33)

**Comment by mortenengel** [comment]
I have started looking into this.

The issue is actually not that both gift cards are withdrawn the amount - one is only withdrawn 0 - it's a display bug that shows that they both have 29.50 euro transactions.

Screenshot from gift_card_transaction table:
![image](https://github.com/medusajs/medusa/assets/38915779/ad4d6fed-5020-4d41-8f33-ba760d526a6e)

That means there are 2 things to fix

1. In the order service, we should stop iterating giftcards once no more money is needed, no need to make 0€ transactions
2. In the order summary component, we need to switch to render the total amount from the gift card transaction amount instead of the order gift_card_total https://github.com/medusajs/medusa/blob/85fa90d9c6c82743b4d9e15d83cec66ebc6cecff/packages/admin-ui/ui/src/domain/orders/details/detail-cards/summary.tsx#L228C47-L228C47

I will make pull requests for these.

**Comment by mortenengel** [comment]
Pull request created.

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
