### ISSUE TITLE
401 returned when requesting a password reset

### ISSUE THREAD

**Issue by samhenderson511** [medusajs/medusa#4894]
# Bug report #

## Describe the bug ##
When attempting to request a password reset from the Medusa starter admin interface, a 401 Unauthorized error is consistently returned. This error occurs both when fetching batch jobs and when trying to generate a password reset token for a user. The docs suggest that the email is all that's required for the reset-token endpoint

> This endpoint requires the email parameter in the request body, which is the email of the user requesting to reset their password.
> The request does not return any data. The response code will be 204 if the request was processed successfully.

## System information ##
Medusa version (including plugins):
```json
    "@medusajs/admin": "^7.0.1",
    "@medusajs/cache-inmemory": "^1.8.8",
    "@medusajs/cache-redis": "^1.8.8",
    "@medusajs/event-bus-local": "^1.9.6",
    "@medusajs/event-bus-redis": "^1.8.9",
    "@medusajs/file-local": "^1.0.2",
    "@medusajs/medusa": "^1.15.0",
    "medusa-fulfillment-manual": "^1.1.38",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.24",
    "medusa-payment-stripe": "^6.0.3",
    "medusa-plugin-sendgrid": "^1.3.11",
    "medusa-react": "^9.0.4",
```
Node.js version: 18
Database: Postgres
Operating system: MacOS 14.0 Beta (23A5328b)
Browser Arc 1.5.0

## Steps to reproduce the behavior ##
1. Go to the Medusa admin login page.
2. Click on 'Forgot Password'.
3. Enter a registered email address.
4. Click on 'Send reset instructions'.
5. Observe the 401 Unauthorized error in the console.

## Expected behavior ##
Upon entering a registered email address and clicking on 'Send reset instructions', a password reset email should be sent to the provided email address without any errors.

## Code snippets ##
What I can find in the starter template:

```jsx
const { mutate, isLoading } = useAdminSendResetPasswordToken()
...
mutate(
  {
    email: values.email,
  },
  {
    onSuccess: () => {
      setSentMail(true)
    },
    onError: (error) => {
      notification("Error", getErrorMessage(error), "error")
    },
  }
)
```

## Additional context ##
The issue seems to be consistent, as multiple 401 Unauthorized errors are observed in the server logs when trying to fetch batch jobs and generate a password reset token. This suggests there might be an authentication or configuration issue on the server side but there are no useful errors shown on the server logs

**Comment by shahednasser** [comment]
@samhenderson511 this was an issue we discovered in the medusa starter and have fixed it, but, unfortunately, if you had created your Medusa project before the fix it won't be fixed on your end.

To resolve it, you can change line 37 of `src/api/index.ts` to the following:

```ts
router.use(
    /\/admin\/((?!auth)(?!invites)(?!users\/reset-password)(?!users\/password-token).*)/,
    authenticate()
  );
```

**Comment by samhenderson511** [comment]
@shahednasser thank you! I've added the starter template as a remote so should be able to pull updates from it in the future.
