### ISSUE TITLE
cypto.getRandomValues() not supported.

### ISSUE THREAD

**Issue by Bludvikk** [medusajs/medusa#4897]
Medusa Client. customers.create() Expo React Native Issue
I was trying to implement a function where a user signs-up.

### System information

Medusa version Latest:
Node.js version: 18
Database: postgresql
Operating system: Windows 11
Browser (if relevant):

### Steps to reproduce the behavior

1. Go to Account
2. You will be prompted to sign-up or login.
3. Input credentials, first_name, last_name, password, email
4. LOGS.  [Error: crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported]

### Expected behavior

It should redirect to the Home Screen where a session is created.

### Screenshots

![image](https://github.com/medusajs/medusa/assets/47531106/91d58ca9-059b-405e-adaa-97ca810d0981)
![image](https://github.com/medusajs/medusa/assets/47531106/5a721e24-aadf-46b7-9c9a-3ef70af9e8b7)
![image](https://github.com/medusajs/medusa/assets/47531106/72d3aeb4-c957-4529-9c5c-3bcd34fc383e)

**Comment by srindom** [comment]
Is this error showing up in your server console or your frontend implementation console?

**Comment by Bludvikk** [comment]
In the server console, I use react hook form and the field values are good, it's just when calling the onSubmit.

Also, I tried to create a user using curl, it was successful, but still cannot login with medusa.auth.

Register and Signing in in the front-end does not work

**Comment by Bludvikk** [comment]
Figured it out myself, I just added 

import "react-native-get-random-values" at the top of the file.

**Comment by Bludvikk** [comment]
using medusa auth on React Native requires you to import "react-native-get-random-values' at the top of the file.

This issue is resolved. GG
