### ISSUE TITLE
How to construct the user (admin) and customer reset password link?

### ISSUE THREAD

**Issue by cellis** [medusajs/medusa#4905]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

To what links should the `user_password_reset_template` link to, and how should we construct the link in the email template?

### How can this issue be resolved?

1. The https://docs.medusajs.com/plugins/notifications/sendgrid#user-password-reset could be rewritten to include what link to go to.

### Are you interested in working on this issue?

- [x] I would like to fix this issue

**Comment by cellis** [comment]
I figured out how to do it. It looks something like this:

`
https://localhost:7001/reset-password?email={{email}}&token={{token}}
`

**Comment by AbhinavChavareTechcopain** [comment]
@cellis please elaborate in brief how to achieve this ,where do we get this token.
I have installed the send grid plugin with the API and user_reset_password
but we don't get the mail,
getting 204 No Content while trying to reset the password to the user admin.
![image](https://github.com/medusajs/medusa/assets/126047812/113b56b8-b778-4121-9e76-2a4a5c33ebf7)

**Comment by cellis** [comment]
@AbhinavChavareTechcopain the {{email}} and {{token}} variables are provided by Medusa. Sendgrid templates knows how to interpolate anything inside of {{}}, so you can just place {{email}} and {{token}} anywhere in your template to test that it comes through. But your problem is different. You need to ensure you have a sendgrid auth key and that it is enabled and set in the dotenv. Also make sure the worker process that actually sends the email is running! Hope this helps.

**Comment by AbhinavChavareTechcopain** [comment]
@cellis thanks for your guidance,
I have installed SendGrid account with SENDGRID_API_KEY 
![image](https://github.com/medusajs/medusa/assets/126047812/531660d5-5e20-4cb7-9e01-004cc167fdea)
I have confirmed that mail from the Send grid is going when we try it manually.
as 
![image](https://github.com/medusajs/medusa/assets/126047812/ce3f8b59-5db1-4864-8c68-b576da9fbc07)

![image](https://github.com/medusajs/medusa/assets/126047812/405c0202-cd4c-4cea-8e5b-3ba036b4ff92)
Unable to get a token.
please comment on this.
thanks for your time and consideration.

**Comment by CokePlusFanta** [comment]
@AbhinavChavareTechcopain 

Token is in data.token object, which event to subscriber provides.

export default async function handleUserPasswordReset({
    data,
    eventName,
    container,
    pluginOptions,
}: SubscriberArgs<Record<string, string>>) {
    const emailService = new EmailService();
    await emailService.sendEmail(
        data.email,
        `subject`,
        generateResetEmail(data.token)
    );
}
