### ISSUE TITLE
Bug: issue when refunding payments with a discount

### ISSUE THREAD

**Issue by maxmandia** [medusajs/medusa#4934]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Hi, 

Having an issue refunding a payment for all orders where discounts are applied. We're using the admin dashboard as an admin to refund the payments for a vendor and receiving the following error:

```
code: "unknown_error"
message: "An unknown error occurred."
type: "unknown_error"
```

We're using version 1.7.12 of Mesdusa. Any ideas would be appreciated!

### How can this issue be resolved?

1. Create a vendor and create a product
2. Create a discount and apply the discount to the product
3. Create another user to purchase this product
4. As an admin, attempt to refund the purchase. Any amount should produce an error
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for submitting this issue @maxmandia ! As this issue isn't related to documentation, I'll change the title/labels to ensure that the right team pick it up. Hope that's alright with you 😇

**Comment by maxmandia** [comment]
Closing as the problem was internal to our own codebase
