### ISSUE TITLE
200 OK for js endpoint with content type 'text/html'

### ISSUE THREAD

**Issue by yogo1212** [medusajs/medusa#4935]
## Bug report

medusa returns a 200 OK with HTML body and `text/html` content type for the `.js` endpoint queried from the admin UI login page.

### Describe the bug

```
curl -D - -H'Host: medusa.domain.com' 'http://localhost:1234/app/runtime~main.96a2eec3.js'
HTTP/1.1 200 OK
X-Powered-By: Express
Cache-Control: no-cache
Vary: Origin, Cache-Control
Content-Type: text/html; charset=utf-8
Content-Length: 444
ETag: W/"1bc-clfdW1Rubq/yqgGp+OYfe2QMkQ4"
Date: Fri, 01 Sep 2023 19:00:21 GMT
Connection: keep-alive
Keep-Alive: timeout=5

<!doctype html><html lang="en"><head><meta charset="UTF-8"/><link rel="icon" type="image/svg+xml" href="/logo.svg"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>Medusa</title><script defer="defer" src="/app/runtime~main.96a2eec3.js"></script><script defer="defer" src="/app/main.0210744b.js"></script><link href="/app/main.a7ce3584fa2696495756.css" rel="stylesheet"></head><body><div id="root"></div></body></html>
```

### System information

Medusa version (including plugins):
```
    "@medusajs/admin": "^7.0.1",
    "@medusajs/cache-inmemory": "^1.8.8",
    "@medusajs/cache-redis": "^1.8.8",
    "@medusajs/event-bus-local": "^1.9.6",
    "@medusajs/event-bus-redis": "^1.8.9",
    "@medusajs/file-local": "^1.0.2",
    "@medusajs/medusa": "^1.15.0",
```
Node.js version: `v18.17.1`
Database: postgres
Operating system: Linux

### Steps to reproduce the behavior

1. Go to '/app' with the network log open
2. See error

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
