### ISSUE TITLE
Error: Command "yarn build:admin" exited with 1 during medusa-admin vercel deployment

### ISSUE THREAD

**Issue by ikritiuk** [medusajs/medusa#4940]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I have an error during medusa-admin vercel deployment.
The log is attached:

TypeError: Cannot read properties of undefined (reading 'plugins')
--
16:50:10.896 | at loadConfig (/vercel/path0/node_modules/@medusajs/admin/utils/load-config.js:8:31)
16:50:10.897 | at Command.<anonymous> (/vercel/path0/node_modules/@medusajs/admin/commands/build.js:50:49)
16:50:10.897 | at step (/vercel/path0/node_modules/@medusajs/admin/commands/build.js:33:23)
16:50:10.897 | at Object.next (/vercel/path0/node_modules/@medusajs/admin/commands/build.js:14:53)
16:50:10.897 | at /vercel/path0/node_modules/@medusajs/admin/commands/build.js:8:71
16:50:10.897 | at new Promise (<anonymous>)
16:50:10.897 | at __awaiter (/vercel/path0/node_modules/@medusajs/admin/commands/build.js:4:12)
16:50:10.897 | at Command.build (/vercel/path0/node_modules/@medusajs/admin/commands/build.js:45:12)
16:50:10.897 | at Command.listener [as _actionHandler] (/vercel/path0/node_modules/@medusajs/admin/node_modules/commander/lib/command.js:482:17)
16:50:10.897 | at /vercel/path0/node_modules/@medusajs/admin/node_modules/commander/lib/command.js:1283:65
16:50:10.915 | error Command failed with exit code 1.
16:50:10.915 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
16:50:10.940 | Error: Command "yarn build:admin" exited with 1

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by nonfungibletunji** [comment]
any solution?

**Comment by olivermrbl** [comment]
This could be an issue with your `medusa-config.js`. Can you start your server locally?

**Comment by kailashv7** [comment]
@ikritiuk  you have cloned the wrong repository. You need to use medusa-starter-default. https://github.com/medusajs/medusa-starter-default. to build admin.

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
