### ISSUE TITLE
Security Vulnerability: Node-Fetch Version

### ISSUE THREAD

**Issue by Atamastar** [medusajs/medusa#4952]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

 I have discovered a security vulnerability in the node-fetch dependency used by the @medusajs/admin package. This vulnerability allows an unauthorized actor to expose sensitive information due to improper handling of redirects. The potential impact of this vulnerability is significant, as it can lead to exposure of sensitive data.

Affected Versions: This vulnerability affects node-fetch versions up to and including 2.6.6, which is used as a dependency in the @segment/analytics-next package, a dependency of @medusajs/admin.

Steps to Reproduce: To reproduce the vulnerability:

Install the affected package with an affected node-fetch version.
Trigger a request that results in a redirect.
Observe that sensitive information may be exposed to an unauthorized actor.
Expected Behavior: When following a redirect, sensitive information should not be exposed to unauthorized actors.

Actual Behavior: The vulnerability allows an unauthorized actor to access sensitive information when a redirect occurs.

### How can this issue be resolved?

This vulnerability was discovered during a security audit of the @medusajs/admin package's dependencies. As a security best practice, it is recommended to update the node-fetch dependency to 3.3.2 version.
https://www.npmjs.com/package/node-fetch

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
