### ISSUE TITLE
medusa-payment-paypal: Add endpoint url for paypal webhook

### ISSUE THREAD

**Issue by ghiottimartin** [medusajs/medusa#4954]
While looking at [the paypal documentation](https://docs.medusajs.com/plugins/payment/paypal) it should say which endpoint to use for the paypal webhook:

"The endpoint for Paypal’s webhook on your Medusa backend is `{BACKEND_URL}/paypal/hooks`. So, add that endpoint in its field. Make sure to replace {BACKEND_URL} with the URL to your backend."

### How can this issue be resolved?

1. Add in the documentation the endpoint for paypal webhook

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for submitting this issue! Feel free to open a PR to fix it 😄

**Comment by ghiottimartin** [comment]
> Thank you for submitting this issue! Feel free to open a PR to fix it 😄

No problem! I created the PR:
https://github.com/medusajs/medusa/pull/4956
