### ISSUE TITLE
Lists of products not showing in storefront, but individual products are

### ISSUE THREAD

**Issue by nimonian** [medusajs/medusa#4958]
I have deployed the admin backend on Railway and the Next frontend on Vercel. Things are almost working, but:

### the list of featured products is not showing

I just get skeleton loaders no matter what, no products

![image](https://github.com/medusajs/medusa/assets/12779491/cb753f08-dfcd-4f8e-a17e-4eefb6427250)

### collections are not showing

Nothing shows despite there being 3 products in this collection

![image](https://github.com/medusajs/medusa/assets/12779491/54424592-76cf-4146-abf8-59fc6b1b7117)

### but individual items _are_showing

this proves that everything is set up correctly, so I do not understand why the lists of products are not showing

![image](https://github.com/medusajs/medusa/assets/12779491/9d30f0da-4307-4437-9c64-c9435f1c3835)

### System information

Medusa version (including plugins): 

```json
  "dependencies": {
    "@headlessui/react": "^1.6.1",
    "@hookform/error-message": "^2.0.0",
    "@medusajs/medusa-js": "^6.0.0",
    "@meilisearch/instant-meilisearch": "^0.7.1",
    "@paypal/paypal-js": "^5.0.6",
    "@paypal/react-paypal-js": "^7.8.1",
    "@stripe/react-stripe-js": "^1.7.2",
    "@stripe/stripe-js": "^1.29.0",
    "@tanstack/react-query": "^4.22.4",
    "clsx": "^1.1.1",
    "lodash": "^4.17.21",
    "medusa-react": "^9.0.0",
    "next": "^13.4.5",
    "react": "^18.2.0",
    "react-country-flag": "^3.0.2",
    "react-dom": "^18.2.0",
    "react-hook-form": "^7.30.0",
    "react-instantsearch-hooks-web": "^6.29.0",
    "react-intersection-observer": "^9.3.4",
    "sharp": "^0.30.7"
  },
```

Node.js version: 18.x
Database: Postgres
Operating system:
Browser (if relevant):

### Steps to reproduce the behavior

1. Deploy backend
2. Add items on admin
3. Deploy frontend
4. Individual items load, but lists of items do not (features items, collections)

### Expected behavior

I should see lists of items in the storefront (e.g. on the homepage)

### Additional context

It works locally

**Comment by tsvetann** [comment]
How do you query for the list of items?

**Comment by olivermrbl** [comment]
Does your server log show errors? Or your browser console?

**Comment by nimonian** [comment]
It turns out, the whole issue was caused by there being no region set in the admin dashboard. I created a default region and now everything works.
