### ISSUE TITLE
Send extra data to Sendgrid templates

### ISSUE THREAD

**Issue by cellis** [medusajs/medusa#4975]
Hello! I wasn't able to find a way to send extra data to the Sendgrid templates, so I forked `medusa-plugin-sendgrid` and created `medusa-plugin-sendgrid-extras`. You can find it here: https://www.npmjs.com/package/medusa-plugin-sendgrid-extras

[source code](https://github.com/cellis/medusa-plugin-sendgrid-extras)

I don't have time to make a proper PR right now, but it does work for me, hopefully it helps someone else.

**Comment by olivermrbl** [comment]
Appreciate the contribution! 

However, our issues board is meant for bugs only. If you've included the correct plugin keywords in the `package.json`, it will be featured on our [plugin page](https://medusajs.com/plugins/).

Thanks!
