### ISSUE TITLE
chore: Make packages/medusa/src/services/cart.js pass linting

### ISSUE THREAD

**Issue by srindom** [medusajs/medusa#498]
In an effort to improve our code quality we want to have make sure that all files in the repo pass linting. 

Please see this guide for a step-by-step guide for how to complete this task: https://www.notion.so/medusajs/Lint-challenge-checklist-b4efc761cb36499abf4726cad0dd02e4

🚀

**Comment by linares-m** [comment]
Hi, I'd like to help with this task. It would be my first issue, so if you have the patience for that, feel free to assign this to me!

**Comment by linares-m** [comment]
Hey, Sebastian, hope you're doing well. Thanks for your patience with this one. I'm a noob, so I'm learning a ton. 

  1.)  An issue came up having to do with the CRLF line endings when I ran ESLint. 
        I was able to get cart.js to pass the test but I had to apply `--fix` to remove these Prettier CRLF errors.
        I attached photos for context. 
  2.) Also note that I was using `npx eslint cart.js` and used NPM for the tasks. 
         If there are any issues with any of this let me know. 

I'll go ahead and add the updated files. But if there are any issues, I'm more than happy to review and edit. 

Thanks!

**Comment by olivermrbl** [comment]
Thanks to both of you for solving the issue. Would love to show our appreciation by sending some swag out for you. Reach out to me on Discord or mail and we can figure it out! ❤️ 

Closed #700
