### ISSUE TITLE
migrate-inventory-items uses default dotenv.config()

### ISSUE THREAD

**Issue by UrbanLauren** [medusajs/medusa#5021]
Link to source documentation where bug is: https://github.com/medusajs/medusa/blob/develop/packages/medusa/src/scripts/migrate-inventory-items.ts

dotenv.config() should be in 

let ENV_FILE_NAME = "";
switch (process.env.NODE_ENV) {
  case "production":
    ENV_FILE_NAME = ".env.production";
    break;
  case "staging":
    ENV_FILE_NAME = ".env.staging";
    break;
  case "test":
    ENV_FILE_NAME = ".env.test";
    break;
  case "development":
    ENV_FILE_NAME = ".env.development";
    break;
  default:
    ENV_FILE_NAME = ".env";
    break;
}

try {
  dotenv.config({ path: process.cwd() + "/" + ENV_FILE_NAME });
} catch (e) {}

### System information
Medusa version (including plugins): 1.15.0
Node.js version: 18.7.1
Operating system: Mac.OS

**Comment by johncarmack1984** [comment]
Same, encounted an issue when trying to run this script locally yesterday, the dotenv config is only set up to look for .env, so if you're using .env.development Postgres throws an error as it tries to log in using the default local user

![Screenshot 2023-09-12 at 3 21 50 PM](https://github.com/medusajs/medusa/assets/20649979/e57cb55b-60df-4ed4-bf93-3b9239c0c717)

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
