### ISSUE TITLE
Docs(Code Issue): Code Issue in /plugins/cms/strapi

### ISSUE THREAD

**Issue by yogo1212** [medusajs/medusa#5030]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

`npx create-strapi-app strapi-medusa --template shahednasser/strapi-medusa-template`

```
Error: ⛔️ Template installation failed: Could not find package shahednasser/strapi-medusa-template on npm
    at createProject (/root/.npm/_npx/f5b733dbc92df62b/node_modules/@strapi/generate-new/dist/create-project.js:99:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for pointing this out @yogo1212 . I think this is an error rather than it being outdated. Will open a PR that fixes this.

**Comment by shahednasser** [comment]
Thank you for pointing this out @yogo1212 . As mentioned in the Strapi documentation, this plugin is a community plugin so it's not heavily updated. However, I'll take the time to look into improving the documentation with other solutions.

**Comment by yogo1212** [comment]
@shahednasser no problem and thank *you* for your work :slightly_smiling_face:
