### ISSUE TITLE
Guide to create a PaymentProcessor is outdated

### ISSUE THREAD

**Issue by olavurdj** [medusajs/medusa#5033]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

On the  "How to Create a Payment Processor" document (see https://docs.medusajs.com/modules/carts-and-checkout/backend/add-payment-provider), many of the examples still use `AbstractPaymentService` as the base class. This makes them harder to follow for anyone wanting to implement Payment Processors.

### How can this issue be resolved?

1. Revamp the guide to consistently use the `PaymentProcessor` API.

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for pointing this out @olavurdj  . I think this is an error rather than it being outdated. Will open a PR that fixes this.
