### ISSUE TITLE
Not sure if medusa storefront is compatible with a library with many interactive components?

### ISSUE THREAD

**Issue by dsks-pawn** [medusajs/medusa#5044]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I took a look at https://docs.medusajs.com/ui and found these components to be insufficient for me. I want to add a library with elements that work with javascript

I tried adding https://tailwind-elements.com/docs/react/getting-started/quick-start/ but it will break the layout because of css incompatibility.
Can you give me some powerful libraries that can be compatible with medusa storefront?
Thank!

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by pevey** [comment]
> I want to add a library with elements that work with javascript

These elements are built with javascript.  They are made to fit in with the existing Medusa Admin application.  They are meant to be used by people wanting to extend that application or build new applications in the same style.

You can use absolutely whatever framework and libraries you want for your own application. 

For instance, I have a SvelteKit frontend that uses Melt-UI.  But I still use @medusajs/ui to extend the Admin.

**Comment by shahednasser** [comment]
I'll be closing this as it's not an issue. Feel free to ask more about this either using GitHub Discussions or our Discord server.
