### ISSUE TITLE
API Ref(store): Issue in Get Product Variants

### ISSUE THREAD

**Issue by Djarma** [medusajs/medusa#5045]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

[Get product variants store api endpoint](https://docs.medusajs.com/api/store#product-variants_getvariants) documentation says that fields can be used as query parameter to filter **fields** included in returned product variants

<img width="492" alt="image" src="https://github.com/medusajs/medusa/assets/19561575/9f5a3435-0ba4-4aec-b69e-e55f36e6bcd2">

but it throws an error

<img width="738" alt="image" src="https://github.com/medusajs/medusa/assets/19561575/4973c38e-e1f4-456a-bf6a-18f29782776a">

![image](https://github.com/medusajs/medusa/assets/19561575/89b90421-08c8-4fa0-8563-3fffafcc0173)

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for submitting this issue! After taking a look at the [List Product Variants endpoint](https://github.com/medusajs/medusa/blob/develop/packages/medusa/src/api/routes/store/variants/list-variants.ts) I can see that this is not a documentation error, so this could be a bug

cc @olivermrbl

**Comment by olivermrbl** [comment]
I'll have a look at this. Thanks for filing the issue.

Are you intentionally using the list endpoint to fetch variants by id? 

If you are only querying for a single variant, I suggest you use the get endpoint instead:
```
.../store/variants/variant_1234?fields=id
```

`fields` is a supported param (and works) in this route :)

**Comment by Djarma** [comment]
We need to list all variants and paginate them, this was just for test

**Comment by Djarma** [comment]
Is it possible to tag, build and push this to https://www.npmjs.com/package/@medusajs/medusa-js?activeTab=versions?

**Comment by olivermrbl** [comment]
@Djarma not sure what you mean. The fix will be part of the next release, which will be cut later today :)
