### ISSUE TITLE
Cannot install medusa framework

### ISSUE THREAD

**Issue by MustacheDab** [medusajs/medusa#5056]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

![eroare](https://github.com/medusajs/medusa/assets/122554860/d6082bf8-55af-43f8-9a57-67c4972b36ba)

### How can this issue be resolved?

1.
2.
3.
...
no idea

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for opening this issue! Will open a fix for it

**Comment by shahednasser** [comment]
Can I get you to try the command again with this snapshot:

```bash
npx create-medusa-app@1.2.1-snapshot-20230914142151 --with-nextjs-starter
```
