### ISSUE TITLE
Issue with Type mismatch in @medusajs/client-types

### ISSUE THREAD

**Issue by imash96** [medusajs/medusa#5058]
### Describe the bug
I was trying to remove the types dependencies on @medusajs/medusa from my storefont project. The issue I faced during this process is the types in @medusajs/client-types mismatch with @medusajs/medusa like example below.

Type of Customer in @medusajs/medusa is
```
export declare class Customer extends SoftDeletableEntity {
    email: string;
    first_name: string;
    last_name: string;
    billing_address_id: string | null;
    billing_address: Address;
    shipping_addresses: Address[];
    password_hash: string;
    phone: string;
    has_account: boolean;
    orders: Order[];
    groups: CustomerGroup[];
    metadata: Record<string, unknown>;
    private beforeInsert;
}
```
while in type of Customer in @medusajs/client-types is
```
export interface Customer {
    id: string;
    email: string;
    first_name: string | null;
    last_name: string | null;
    billing_address_id: string | null;
    billing_address?: Address | null;
    shipping_addresses?: Array<Address>;
    phone: string | null;
    has_account: boolean;
    orders?: Array<Order>;
    groups?: Array<CustomerGroup>;
    created_at: string;
    updated_at: string;
    deleted_at: string | null;
    metadata: Record<string, any> | null;
}

```
in  @medusajs/client-types many properties are optional/undefined(?) like orders, groups, billing_address etc. also the type of created_at, updated_at are string while in @medusajs/medusa they are of type Date.

These minor mismatch are in all the model of @medusajs/client-types that why I am not able to remove dependencies on @medusajs/medusa from my storefont project.
```
Argument of type 'Omit<import(".../node_modules/@medusajs/medusa/dist/models/customer").Customer, "password_hash"> | undefined' is not assignable to parameter of type 'Omit<Customer, "password_hash"> | undefined'.
  Type 'Omit<import(".../node_modules/@medusajs/medusa/dist/models/customer").Customer, "password_hash">' is not assignable to type 'Omit<Customer, "password_hash">'.
    Types of property 'billing_address' are incompatible.
      Type 'import(".../node_modules/@medusajs/medusa/dist/models/address").Address' is not assignable to type 'import(".../node_modules/@medusajs/client-types/dist/lib/models/Address").Address'.
```

### System information

Medusa version (including plugins): 1.15.1
Node.js version: 18.17.1
Database: Postgres
Operating system: Windows

### Steps to reproduce the behavior

1. Import type from @medusajs/client-types
2. use "medusa-react" to get data from server
3. Define any function with parameter having type from @medusajs/client-types 
4. Pass the varibale of "medusa-react" to the function you will see error of type mismatch

### Expected behavior

Both the types from @medusajs/client-types and @medusajs/medusa should be compatible with each other.

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
