### ISSUE TITLE
`create-medusa-app` with `--no-boilerplate` is not working

### ISSUE THREAD

**Issue by abathellier** [medusajs/medusa#5063]
### Describe the bug

Using `pnpm dlx create-medusa-app@latest --no-boilerplate --skip-db` still includes all the onboarding stuff.

### System information

Medusa version (including plugins):
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Steps to reproduce the behavior

```
$ pnpm dlx create-medusa-app@latest --no-boilerplate --skip-db
```

The generated app includes the onboarding stuff.

### Expected behavior

`--no-boilerplate`: A flag that removes all files added for an enhanced onboarding experience (files under src/admin, src/api, etc...). This is helpful if you want to create a clean project, and is only recommended if you're familiar with Medusa.

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by shahednasser** [comment]
Thank you for submitting this issue @durdenx . I wasn't able to reproduce this on my end, so would be great to get more context from you. Can you share with me what onboarding files you found exactly? If you can share the structure you have under `src` would be great.

**Comment by abathellier** [comment]
@shahednasser, I tested it outside of my project, and I couldn't reproduce it either. Sorry for any inconvenience.

**Comment by shahednasser** [comment]
All good! If you face any other problems feel free to open new issues
