### ISSUE TITLE
Calculated price not returned when passing in expand field to /store/products/:id

### ISSUE THREAD

**Issue by Arsenalist** [medusajs/medusa#5068]
Medusa: 1.15

To reproduce:

- Setup a price list with a product
- Call `/store/products/:d?region_id=region_id` (you'll see calculated_price being returned)
- Now call `/store/products/:d?region_id=region_id&expand=anyRelation` (calculated_price no longer being returned)

**Comment by olivermrbl** [comment]
@adrien2p, do you have time to investigate this? If a bug, it would be great to include in today's release.

**Comment by adrien2p** [comment]
@Arsenalist thanks for the issue, in regards to the expand property, you have to know that in order to get the prices returned the expand needs to contains variants and variants.prices for the prices to be calculated. see
```ts
const shouldSetPricing = ["variants", "variants.prices"].every((relation) =>
    req.retrieveConfig.relations?.includes(relation)
  )
```

When you pass your expand with `anyRelation` could you share us what relations are you passing please?

**Comment by Arsenalist** [comment]
Yes I checked the code. It also doesn’t work with variant and variant.prices being passed.

**Comment by adrien2p** [comment]
I ll investigate this

**Comment by adrien2p** [comment]
If I set expand without `variants,variants.prices` I don't get the calculated, but if I set them, then I get the calculated using 1.15.1

<img width="1340" alt="Screenshot 2023-09-15 at 12 18 03" src="https://github.com/medusajs/medusa/assets/25098370/996c4987-b1d7-452c-b9d9-7f45a8fbdf3b">

**Comment by Arsenalist** [comment]
Can you add a custom relation in addition to price and variants.price and see if you get them?

**Comment by Arsenalist** [comment]
Actually, I take that back. It works when I pass in variants,variants.prices. Can we update the docs to say this?

**Comment by Arsenalist** [comment]
I can make a PR if you are OK with it.

**Comment by adrien2p** [comment]
Yes I think it can be a good idea, @shahednasser what do you think

**Comment by shahednasser** [comment]
That's a good idea to include. I would include it in the `description` comment in [the List Products endpoint](https://github.com/medusajs/medusa/blob/develop/packages/medusa/src/api/routes/store/products/list-products.ts). A note that says something like `if you pass the expand parameter to expand relations, make sure to include variants,variants.prices to still retrieve the variant prices`.

**Comment by Arsenalist** [comment]
Or what if you always just add it automatically when region_id or cart_id is specified?

**Comment by olivermrbl** [comment]
Closing as the initially reported issue has been resolved :)
