### ISSUE TITLE
API Ref(admin): Issue in Update a Customer

### ISSUE THREAD

**Issue by udaykumar2104** [medusajs/medusa#5078]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

while updating the customer getting an error
{
    "code": "unknown_error",
    "type": "unknown_error",
    "message": "An unknown error occurred."
}

in console i got 
 driverError: error: relation "public.favourites" does not exist
      at D:\watermelon_be\watermelon-medusa\node_modules\pg\lib\client.js:526:17
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async PostgresQueryRunner.query (D:\watermelon_be\watermelon-medusa\node_modules\typeorm\driver\postgres\PostgresQueryRunner.js:178:25)

### How can this issue be resolved?

1.i am not sure
2.
3.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by olivermrbl** [comment]
The relation `favourites` does not exist on the core Customer entity, so I assume you've extended it with this yourself. Unfortunately, we won't be able to help much with the information provided. However, it does look like you could be missing to apply a migration.
