### ISSUE TITLE
Algolia Search Indexing

### ISSUE THREAD

**Issue by samhenderson511** [medusajs/medusa#5088]
### Describe the bug

Algolia plugin isn't being recognised by the medusa backend, throwing "no search engine provider found" with the plugin installed and config set in medusa.config.

### System information

Medusa version (including plugins):
``` json
"@medusajs/admin": "^7.1.0",
    "@medusajs/cache-inmemory": "^1.8.8",
    "@medusajs/cache-redis": "^1.8.8",
    "@medusajs/event-bus-local": "^1.9.6",
    "@medusajs/event-bus-redis": "^1.8.9",
    "@medusajs/file-local": "^1.0.2",
    "@medusajs/icons": "^1.0.0",
    "@medusajs/medusa": "^1.16.0",
    "@medusajs/ui": "^1.0.0",
    "@medusajs/utils": "^1.10.1",
"medusa-file-github": "^0.0.7",
    "medusa-fulfillment-manual": "^1.1.38",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.24",
    "medusa-payment-stripe": "^6.0.4",
    "medusa-plugin-algolia": "^0.2.20",
    "medusa-plugin-sendgrid": "^1.3.11",
    "medusa-react": "^9.0.5",
"@medusajs/medusa-cli": "^1.3.21",
```
Node.js version: v18.17.1
Database: Postgres
Operating system: MacOS 14.0 (23A339)
Browser (if relevant): 

### Steps to reproduce the behavior

1. Follow algolia set up on Medusa docs
2. Deploy backend to Railway

### Expected behavior

I expect to see an index of my products in the algolia app 

### Screenshots

Console logs
``` console
Initializing search engine indexing

No search engine provider was found: make sure to include a search plugin to enable searching

Indexing event emitted

Creating server

Server is ready on port: 9000
```

Env variables are set
<img width="462" alt="Screenshot 2023-09-16 at 10 25 28" src="https://github.com/medusajs/medusa/assets/86521077/865c0872-6bc9-4231-988a-19585abd1e20">

### Code snippets

Medusa config

``` js
const plugins = [
  `medusa-fulfillment-manual`,
  `medusa-payment-manual`,
  {
    resolve: `medusa-plugin-algolia`,
    options: {
      applicationId: process.env.ALGOLIA_APP_ID,
      adminApiKey: process.env.ALGOLIA_ADMIN_API_KEY,
      settings: {
        products: {
          indexSettings: {
            searchableAttributes: ["title", "description"],
            attributesToRetrieve: [
              "id",
              "title",
              "description",
              "handle",
              "thumbnail",
              "variants",
              "variant_sku",
              "options",
            ],
          },
          transformer: (product) => ({
            id: product.id,
          }),
        },
      },
    },
  },
```

**Comment by tsvetann** [comment]
Can you try to re-install the plugin? Also algolia doesn't support id but rather objectID

**Comment by samhenderson511** [comment]
That doesn't seem to have helped, the only thing I haven't done according to the docs is my package versions are different?

**Comment by samhenderson511** [comment]
Update: I can see in the Algolia API logs that it's updating the settings for the index on every deployment but it isn't adding any records.

**Comment by tsvetann** [comment]
check the console for errors. You have to change id with the specific object id from algolia

**Comment by olivermrbl** [comment]
As @tsvetann's states, Algolia expects the ID of the documents to be `objectID` :)

**Comment by minhhai2209** [comment]
Please fix the documentation then

![image](https://github.com/medusajs/medusa/assets/338700/240d4693-dae9-4912-b6bc-a598902b71e3)

**Comment by DoubleOTheven** [comment]
> Please fix the documentation then
> 
> ![image](https://private-user-images.githubusercontent.com/338700/289344606-240d4693-dae9-4912-b6bc-a598902b71e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MDgzNDUsIm5iZiI6MTcxMzkwODA0NSwicGF0aCI6Ii8zMzg3MDAvMjg5MzQ0NjA2LTI0MGQ0NjkzLWRhZTktNDkxMi1iNmJjLWE1OTg5MDJiNzFlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QyMTM0MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTNkMzNjNWQ5ODUyNjA1ODRiZDVhNGIwY2JiYTY5NDM2Zjc0ZTgzMGE0Y2JlNjlhM2VlNTBmM2FjMmQ5ZTYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6-vkr1XLFHdE3s89t2woMSyPF0sC8SQbKHTIcvfDcRQ)

This example is missing the `transformer` function listed just above in the docs.

```js
const plugins = [
  // ...
  {
    resolve: `medusa-plugin-algolia`,
    options: {
      // other options...
    settings: {
      indexName: {
        indexSettings: {
          searchableAttributes,
          attributesToRetrieve,
        },
        transformer: (product) => ({ 
          objectID: product.id, 
          // other attributes...
        }),
      },
    },
    },
  },
]
```

**Comment by ejwhite7** [comment]
Can you share the example of how you fixed this?

**Comment by uno-b** [comment]
> Update: I can see in the Algolia API logs that it's updating the settings for the index on every deployment but it isn't adding any records.

Getting the same issue here. I've updated the transformer to return an object with the objectID, and it's still not indexing the products. In fact, when I logged the product in the transformer, it's not even running.

**Comment by uno-b** [comment]
Fixed. The transformer function was not running at all. Apparently the problem was with the event-bus-redis. When I changed to event-bus-local, it works. I'll have to address this issue once more down the road for production.
