### ISSUE TITLE
Docs(Code Issue): Code Issue in /modules/orders/storefront/retrieve-order-details

### ISSUE THREAD

**Issue by odhekar** [medusajs/medusa#5099]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Retrieve order by display id sample code for medusa-react shows useOrder with order id instead.
```typescript
  const { 
    order, 
    isLoading, 
  } = useOrders(orderId)
```

### How can this issue be resolved?

Update sample code for medusa-react,
```typescript
  const { 
    order, 
    isLoading, 
  } = useOrders(displayid)
```

This is pure guess based on sample for js client. I am still learning medusa and just going through docs.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for opening this issue @odhekar . Just looked at the code block in the docs and it's actually entirely incorrect, since it should accept and object similar to the Medusa JS Client 😅 Will open a fix for it

**Comment by odhekar** [comment]
So does this mean the orderId example is wrong too?
