### ISSUE TITLE
Incorrect native symbol for Indian Rupee in the admin dashboard

### ISSUE THREAD

**Issue by odhekar** [medusajs/medusa#5105]
### Describe the bug

The admin dashboard uses `টকা` as native symbol (`symbol_native`) for Indian Rupee instead of `₹` 

### System information

Medusa version (including plugins):
Node.js version: 18.16.1
Database: 15.3-1.pgdg120+1
Operating system: Ubuntu Linux

### Steps to reproduce the behavior

1. Open admin dashboard
2. Go to Settings > Currencies and add Indian Rupee as a currency option
3. Add a region with Indian Rupee as a currency.
4. You will now see `টকা` used everywhere the currency symbol is show. Continue below for one such case.
5. Go to Products and create a product "Test"
6. Open the Test product details page
7. Under Variants, click Add Variant
8. Expand Pricing. See screenshot below.

### Expected behavior

Admin dashboard should us the proper native symbol ₹ for Indian rupee

### Screenshots

![image](https://github.com/medusajs/medusa/assets/34801801/aae820c6-fce0-4152-83ff-2ff3894d9527)

### Code snippets

The bug is present here: https://github.com/medusajs/medusa/blob/4710520c35886c1df7dd934e7950b6309e1f78df/packages/admin-ui/ui/src/utils/currencies.ts#L451
```typescript
  INR: {
    symbol: "Rs",
    name: "Indian Rupee",
    symbol_native: "টকা",
    decimal_digits: 2,
    rounding: 0,
    code: "INR",
    name_plural: "Indian rupees",
  },
```

**Comment by tushar-nath** [comment]
@odhekar - I would like to fix this, can you assign it to me please?

**Comment by tushar-nath** [comment]
@odhekar - any update on this?

**Comment by odhekar** [comment]
@tushar-nath I'm not a maintainer of this project. In any case, a PR was created as you can see above.

**Comment by odhekar** [comment]
@shahednasser is there a way we can increase visibility of this issue?

**Comment by shahednasser** [comment]
I think there's a PR already open for this. @olivermrbl any chance we can look into into this?

**Comment by odhekar** [comment]
PR #6453 fixed this.
