### ISSUE TITLE
Admin UI modal add variant causes pointer events none to block further interaction

### ISSUE THREAD

**Issue by pepijn-vanvlaanderen** [medusajs/medusa#5107]
### Describe the bug

In the latest release of the admin UI there is an issue introduced when opening for example the Product Variants modal. When you close it again, the pointer events are set to none on the document body.

### System information

Medusa version (including plugins):
Node.js version: v20
Database: Postgres
Operating system: MacOs
Browser (if relevant):

### Steps to reproduce the behavior

1. Go to a product detail page
2. Click on the three dots to add a variant
3. This opens a popover, which toggles the document body to pointer events none
4. Click on add variant
5. This opens the Add variant modal, which toggles the document body pointer events to be removed 
6. Close the modal, this toggles the pointer events again, but since in 5 it was removed, it now sets it again
7. Further interaction is impossible 

### Expected behavior

No pointer events none on the body when closing a modal or popover.

**Comment by olivermrbl** [comment]
Thanks for highlighting @pepijn-vanvlaanderen; we will investigate and patch it right away!

**Comment by olivermrbl** [comment]
@fPolic – any chance you could also have a look at this one? 🙏

**Comment by fPolic** [comment]
On it @olivermrbl

**Comment by pepijn-vanvlaanderen** [comment]
@fPolic / @olivermrbl I am not sure the connected PR is going to resolve the issue. The same package remains installed by the looks of it. Also I tried to install different versions of radix ui react dialog throuh yarn resolutions. But none of these versions work: v1.0.2 / v1.0.3 / v1.0.4

Edit: also I see this issue report on the Radix UI repo https://github.com/radix-ui/primitives/issues/2355

**Comment by fPolic** [comment]
hey @pepijn-vanvlaanderen, I'm not sure how you've tested the package installation but the fix is working for me locally and deployed to a staging environment. We will be releasing a new admin version with the fix probably later today. If the issue is still present then, we can reopen the issue.

**Comment by pepijn-vanvlaanderen** [comment]
Hi @fPolic, just pulled in the latest release, however the issue still persists.
```
@medusajs/admin: 7.1.1
@medusajs/admin-ui: 2.1.1
```
For clarification, see the attached screen recording and the toggling of the pointer events on the body element when going through the modals.

https://github.com/medusajs/medusa/assets/7559384/df7184dc-7de4-4ffb-8ff9-9ccf446c59c4

**Comment by fPolic** [comment]
Hi @pepijn-vanvlaanderen, that's really odd - I'm able to reproduce your issue on my end only if I manually install a lower version of this package with e.g. `yarn add @radix-ui/react-dialog@1.0.2`.

What is the version you have in `node_modules/@radix-ui/react-dialog` (you might have another package depending on 1.0.2 in your project)? Also, could I get you to run `yarn add @radix-ui/react-dialog@1.0.4` as a test?

**Comment by pepijn-vanvlaanderen** [comment]
Hi @fPolic, thanks for your reply. I forget to remove the resolution on which I forced it to an older version, removed it and retested and it works! Thanks for your time.

**Comment by LuisCarrilloR** [comment]
HI! Is this still an issue? I tried to use `@radix-ui/react-dialog@1.0.4` and I am still experiencing the same thing.

I confirmed that the node_modules package installed is v1.0.4

**Comment by coinlordd** [comment]
I'm still experiencing this issue on Medusa 2.2.0.

**Comment by a-kouyate** [comment]
Still have the problem in Medusa v2

**Comment by ibkrebecca** [comment]
> Still have the problem in Medusa v2

did you happen to find any solution for this?
