### ISSUE TITLE
chore: Make packages/medusa/src/services/middleware.js pass linting 

### ISSUE THREAD

**Issue by srindom** [medusajs/medusa#511]
In an effort to improve our code quality we want to have make sure that all files in the repo pass linting.

Please see this guide for a step-by-step guide for how to complete this task: https://www.notion.so/medusajs/Lint-challenge-checklist-b4efc761cb36499abf4726cad0dd02e4

🚀

**Comment by saurabh042** [comment]
Hey @melan96 are you working on this? If not, I would like to work on this. Can you please confirm

**Comment by sidverma32** [comment]
@srindom  Can i pick this up?
