### ISSUE TITLE
[admin] Exported product list CSV doesn't contain product metadata fields

### ISSUE THREAD

**Issue by genox** [medusajs/medusa#5116]
### Describe the bug

I have a test product with multiple variants. The product itself has metadata fields attached. When I export products as CSV, metadata fields are not included.

### System information

Medusa version (including plugins): latest
Node.js version: 18
Database: latest
Operating system: macOS
Browser (if relevant):

### Steps to reproduce the behavior

1. Create new product
2. Add metadata
3. Add variants
4. Generate CSV export on product list view
5. Download and open
6. Notice the absence of metadata fields

### Expected behavior

As a user, I expect metadata fields to be exportable and importable, just like variant option fields currently already are.

**Comment by olivermrbl** [comment]
We'd like to keep our issues tab free of improvement/enhancement requests. Could I get you to move this to a GH Discussion? 🙏
