### ISSUE TITLE
[docs] Add article/tutorial that outlines custom attribute addition to product entity including UI

### ISSUE THREAD

**Issue by genox** [medusajs/medusa#5117]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

One of the first things someone is going to want to do is to add an additional attribute to a product. I just started using MedusaJS, read the docs up and down and searched discord, gh issues and discussions to figure out how to add a text input field to the product create/edit form - I couldn't figure it out.

I was able to add attributes to the entity and all fragments required to have the field show up in the model including migrations but there is nothing in the docs on how to add this field to the product create/edit form.

Up until now, I wasn't able to figure it out. And according to a search on discord, I am not the only one struggling with this. :)

In my humble newbie opinion, this is the perfect entry level tutorial that shows the "full stack" in action and should therefore be created as such. A tutorial that ties together all the small detail parts including the admin UI.

### How can this issue be resolved?

Basically, an article that outlines all the required steps to add an input field or maybe even a select dropdown to the product information form by extending the product entity. From start to finish. Along the way, people learn all the minimum basics to work with Medusa and touched every part once.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by genox** [comment]
On a sidenote, for now I would greatly appreciate on how it is actually possible to add that field to the UI so I can continue working with Medusa. Is it even possible? I found no "hook" for the form.

**Comment by shahednasser** [comment]
Thank you for submitting this issue @genox . If you mean add fields in the Medusa form in the admin, then I would suggest using our [Admin Widgets](https://docs.medusajs.com/admin/widgets). Widgets can be injected into different zones in the admin. In this case, you can inject it into the `product.details.before` or `product.details.after` as explained in the docs.

Please note that a lot of these features are newly introduced and we're constantly looking into not only documenting them, but also ensuring that we provide a good and clear learning experience. I think you provide a good suggestion, and would be something I'd discuss with the team.

In the meantime, as I explained you can use admin widgets which are already documented. Please let me know if you're looking for something different instead.

**Comment by genox** [comment]
Yes, this was my fall back. I would have assumed those fields magically showed up in the "Attributes" tab though. After all, it is there for "Attributes" ;-)

Can you point me to an example of a plugin that persists data to a product entity? It is a lot of code to write for a simple attribute, so having at least a starter template of sorts that could be copy pasted for the most part would speed up things for newbies significantly.

**Comment by shahednasser** [comment]
You don't need to write that logic yourself (if I'm understanding you correctly). You can use the `productService.save` method to save changes to the Product entity.

For example, if you're using it in an endpoint:

```ts
router.post("/custom-endpoint", (req, res) => {
   const productService = req.scope.resolve("productService")
  
  productService.save({
   // pass your custom data to the object
  })
})
```

Make sure that in this case, if you're using TypeScript, you add a TypeScript declaration file as explained [here](https://docs.medusajs.com/development/entities/extend-entity#optional-step-3-create-a-typescript-declaration-file) to avoid errors.

You can alternatively access the `ProductRepository` as explained [here](https://docs.medusajs.com/development/entities/repositories#using-custom-repositories-in-other-resources) and use its `save` method as well. However, it's generally encouraged to use services that use the repository in their underlying logic.

Note that services, repositories, and other resources can be accessed in endpoints, other services, etc... through dependency injection, which you can learn more about [here](https://docs.medusajs.com/development/fundamentals/dependency-injection).

**Comment by olivermrbl** [comment]
Can we please convert this to a GitHub Discussion, as this is a feature request? Our Issues tracker is dedicated to bug reports.

**Comment by genox** [comment]
> Can we please convert this to a GitHub Discussion, as this is a feature request? Our Issues tracker is dedicated to bug reports.

Apologies. Sure, but how to convert?

**Comment by genox** [comment]
> You don't need to write that logic yourself (if I'm understanding you correctly). You can use the `productService.save` method to save changes to the Product entity.
> 
> For example, if you're using it in an endpoint:
> 
> ```ts
> router.post("/custom-endpoint", (req, res) => {
>    const productService = req.scope.resolve("productService")
>   
>   productService.save({
>    // pass your custom data to the object
>   })
> })
> ```
> 
> Make sure that in this case, if you're using TypeScript, you add a TypeScript declaration file as explained [here](https://docs.medusajs.com/development/entities/extend-entity#optional-step-3-create-a-typescript-declaration-file) to avoid errors.
> 
> You can alternatively access the `ProductRepository` as explained [here](https://docs.medusajs.com/development/entities/repositories#using-custom-repositories-in-other-resources) and use its `save` method as well. However, it's generally encouraged to use services that use the repository in their underlying logic.
> 
> Note that services, repositories, and other resources can be accessed in endpoints, other services, etc... through dependency injection, which you can learn more about [here](https://docs.medusajs.com/development/fundamentals/dependency-injection).

Thank you, I will look into this.
