### ISSUE TITLE
Adding line items with an invalid variant id gives a 500 error

### ISSUE THREAD

**Issue by Alexnortung** [medusajs/medusa#5132]
### Describe the bug

Adding line items with an invalid variant id gives a 500 error.

### System information

Medusa version (including plugins): 1.16.0-canary-20230831100806
Node.js version: 18
Database: postgres 15.4
Operating system: NixOS

### Steps to reproduce the behavior

1. Create a product with a variant and price
2. use the `useCreateLineItem` hook (from medusa-react) and call add item with `{ quantity: 1, variantId: "" }`
3. See error in medusa terminal and 500 error in browser console.

### Expected behavior

I would expect the medusa api to return a 400 error explaining that I provided an invalid variant id

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

The bug seem to originate from this part of the code. Maybe there should be called `variantsMap.has()` first? Or there should be a not undefined null or undefined check after the get :)

https://github.com/medusajs/medusa/blob/a37e0b44d4ab3679408b5a7a465a7e1c8dce8901/packages/medusa/src/services/line-item.ts#L283-L285

**Comment by olivermrbl** [comment]
@adrien2p – any chance you could have a look at this? 🙏

**Comment by adrien2p** [comment]
I ll jump on it 👍

**Comment by adrien2p** [comment]
I have created a pr here if you want to follow @Alexnortung https://github.com/medusajs/medusa/pull/5145

**Comment by olivermrbl** [comment]
Solved in #5145
