### ISSUE TITLE
API Ref(admin): Issue in List a Product's Variants

### ISSUE THREAD

**Issue by DylDelport** [medusajs/medusa#5135]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

For the endpoint "/admin/products/{id}/variants", the API documentation response properties are not actually returned:
**API Docs** 
![image](https://github.com/medusajs/medusa/assets/31354787/4faf9028-29fa-45f4-8cb2-16804949a333)

**Actual Response**
![image](https://github.com/medusajs/medusa/assets/31354787/b00fb3f6-329c-46ef-ae67-ca0611d753c6)

### How can this issue be resolved?

1. Either the documentation needs to be changed to be accurate
2.  The endpoint needs to return more fields.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for submitting this issue @DylDelport 

@olivermrbl looking at the source code, I can see that this is due to only having in `defaultAdminGetProductsVariantsFields` the `id` and `product_id`. Is this is the intended behavior? If so, I can fix up the documentation, but just wanted to check with you first.

@DylDelport for now, you can resolve this by passing the `expand` and `fields` parameters with the relations and fields you want to include in the response.

**Comment by DylDelport** [comment]
@shahednasser thanks for the prompt reply. I attempted to use the expand and field parameters but this results in a 500 Internal Server Error. Are you able replicate this issue?

**Comment by shahednasser** [comment]
@DylDelport just tried it out and wasn't able to reproduce it. Can you provide us with the exact expand/fields parameters you've used, and what error you can see in the Medusa backend logs?

**Comment by DylDelport** [comment]
@shahednasser curious as to where I've gone wrong then.
**endpoint_url**: /admin/products/prod_01HAEV47VB07T7ETGS79GMNZFG/variants?fields=variants&expand=variants

![image](https://github.com/medusajs/medusa/assets/31354787/9df2341a-b821-4cb5-b237-7655f67a264a)

response_status: 500 Internal Server Error
response:
{
    "code": "unknown_error",
    "type": "unknown_error",
    "message": "An unknown error occurred."
}

**Comment by shahednasser** [comment]
You should pass in `expand` and `fields` the relations and fields of a variant. So, for example `expand=prices&fields=title,sku`
