### ISSUE TITLE
plugin error

### ISSUE THREAD

**Issue by udaykumar2104** [medusajs/medusa#5139]
error:   Error starting server
TypeError: Cannot read properties of undefined (reading 'prototype')
    at registerPaymentServiceFromClass

### System information

Medusa version (including plugins):
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by olivermrbl** [comment]
Needs more information. Closing until provided.

**Comment by udaykumar2104** [comment]
i had resolved the issue it is from my side

**Comment by gaurav0909-max** [comment]
@udaykumar2104 can you please elaborate as this issue also happened with me.

**Comment by YaminNather** [comment]
I have the same issue. It only happens when I include my custom plugin. There should be better error messages, or a template for plugins, I followed the documentation for creating a plugin but I am still getting this error and not sure how to debug it.
