### ISSUE TITLE
API Ref(store): Issue in Update Customer

### ISSUE THREAD

**Issue by udaykumar2104** [medusajs/medusa#5143]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

i need send a updating email(like your account is active) to the user how can i do that..?

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by olivermrbl** [comment]
Our GitHub Issues is reserved for bug reports only. Please use GitHub Discussions or Discord for Q/A and general help requests :)
