### ISSUE TITLE
Missing 'categories' attribute in Product object after Admin updates with Meilisearch Plugin

### ISSUE THREAD

**Issue by Am1n3** [medusajs/medusa#5144]
### Describe the bug

I'm using the Meilisearch plugin and the transformer function (that accepts a product as a parameter) to index custom attributes. When the application restarts and the index event is fired, every thing works as expected.

BUT, when the product is updated through the Admin, the product object that gets passed to the transformer function is missing the categories attribute.

I believe the same thing happen when using Algolia.

### System information

Medusa version : 1.16.0
Meilisearch version : 2.0.10
Node.js version: v18.12.1
Database: postgres
Operating system: macOS Ventura 13.4.1

### Steps to reproduce the behavior

1. Add a simple console log to the transformer function in medusa-config.js
```
const plugins = [
  // ...
  {
      resolve: `medusa-plugin-meilisearch`,
      options: {
        config: {
          host: process.env.MEILISEARCH_HOST,
          apiKey: process.env.MEILISEARCH_API_KEY,
        },
        settings: {
          products: {
            indexSettings: {
              searchableAttributes: ['title', 'description'],
              displayedAttributes: [
                'title',
                'description',
              ],
            },
            primaryKey: 'id',
            transformer: (product) => {
              console.log("### Product ===>", JSON.stringify(product, null, 2))
              return {
                id: product.id,
                title: product.title,
                description: product.description,
              };
            },
          },
        },
      },
    }
]
```
2. Restart the app. If you check the console you'll see that the categories attribute is present.
3. Go to the admin and update the product. If you check the console you'll notice that the categories attribute is missing.

### Expected behavior

When a product is updated through the admin, the product object that get passed to the transformer function for indexing must have a categories attribute.

**Comment by P-de-Jong** [comment]
I ran into the same problem. I added a loader in the`src/loaders` folder.

```typescript
export default async function () {
  const searchRelations = (await import(
    '@medusajs/utils/dist/search/search-relations'
  )) as any;

  searchRelations.defaultSearchIndexingProductRelations = [
    ...searchRelations.defaultSearchIndexingProductRelations,
    'categories',
  ];
}
```

Now it loads the categories when indexing :)

**Comment by alsherif-khalaf** [comment]
> I ran into the same problem. I added a loader in the`src/loaders` folder.
> 
> ```ts
> export default async function () {
>   const searchRelations = (await import(
>     '@medusajs/utils/dist/search/search-relations'
>   )) as any;
> 
>   searchRelations.defaultSearchIndexingProductRelations = [
>     ...searchRelations.defaultSearchIndexingProductRelations,
>     'categories',
>   ];
> }
> ```
> 
> Now it loads the categories when indexing :)

is this fix need to rebuild medusa packages from node-modules?
