### ISSUE TITLE
Unable to find plugin "medusa-plugin-ses"

### ISSUE THREAD

**Issue by dsks-pawn** [medusajs/medusa#5150]
### Describe the bug
![image](https://github.com/medusajs/medusa/assets/36871547/87ba986a-99fa-48c5-bfaf-2377ec11ecb3)

I'm following this document, I don't see any mention of installing a package? Have I missed any steps? Please let me know, thanks!
https://medusajs.com/plugins/medusa-plugin-ses/

**Comment by pevey** [comment]
I'll update the docs. You need to type and run:

`yarn add medusa-plugin-ses`

inside your medusa backend folder.

**Comment by dsks-pawn** [comment]
> I'll update the docs. You need to type and run:
> 
> `yarn add medusa-plugin-ses`
> 
> inside your medusa backend folder.

I tried it and it worked, thank you very much
