### ISSUE TITLE
Medusa Admin fails to fetch language files

### ISSUE THREAD

**Issue by kevinfurmanski** [medusajs/medusa#5151]
Hi!

I am getting the following errors in my browser when i18next is trying to fetch language files:

<img width="1431" alt="Screenshot 2023-09-19 at 21 25 26" src="https://github.com/medusajs/medusa/assets/2817726/6aad58a9-6ffc-418e-8a4a-ab3438d180cd">
<img width="1431" alt="Screenshot 2023-09-19 at 21 25 36" src="https://github.com/medusajs/medusa/assets/2817726/b93e3a9c-c12b-489b-a3ea-00c0d32faf4e">

As you can see there is a double slash after the backend URL which I think has something to do with the fact that in https://github.com/medusajs/medusa/blob/889154c440e3a95042979d78446eb5f3f5585020/packages/admin-ui/ui/src/i18n/index.ts#L22 there is a trailing slash when the ADMIN_PATH has a default value of '/'

**Comment by olivermrbl** [comment]
@kevinfurmanski, thanks – will attend to this right away!

**Comment by olivermrbl** [comment]
@kevinfurmanski any chance I could get you to try `@medusajs/admin@7.1.2-next-20230920164215
` ? 🙏

**Comment by kevinfurmanski** [comment]
@olivermrbl I have tried and it works as it should :)
