### ISSUE TITLE
[medusa-ui] Select's option container z-index is lower than Modal container's z-index

### ISSUE THREAD

**Issue by genox** [medusajs/medusa#5153]
### Describe the bug

Trying to display a Select in a Modal doesn't work as expected because the Select's dropdown component is hidden behind the Modal.

<img width="330" alt="Screenshot 2023-09-20 at 08 46 57" src="https://github.com/medusajs/medusa/assets/5611407/d406f2a4-0786-4ee5-a268-b1e6a0c54b1b">

### System information

Medusa version (including plugins): @latest
Node.js version: 18
Database: pg
Operating system: macos
Browser (if relevant): chrome

### Steps to reproduce the behavior

1. make a modal component
2. add a select component to the modal's body
3. try to select an option
4. notice absence of option list on screen while it is rendered in the document body

### Expected behavior

I expect the Select component to be aware of its stacking context. This isn't possible out of the box since the modal and the option list are both portals; they don't share the same isolation context.

Possible solutions:

- Mention stacking context in the docs and that it needs to be considered manually on a case by case basis
- Implement a react context that allows children components to keep track of their parents z-index and increment their own if needed

**Comment by kasperkristensen** [comment]
Hi @genox

There is already an issue for this over in the appropriate repository: https://github.com/medusajs/ui/issues/81

You will need to set a z-index on the Select.Content in order for it to render above the modal. 

Thanks for your suggestions on possible fixes, I'll take them under consideration, and I hope to push a new release to the UI package soon that will fix the issues related to component stacking.

I am closing this issue in favor of the one in the UI repo, but it is something I will be working on a fix for very soon. 🙂
