### ISSUE TITLE
Dynamic usage with Amazon SES like Sendgird?

### ISSUE THREAD

**Issue by dsks-pawn** [medusajs/medusa#5179]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I'm using medusa-plugin-ses for sending mail, but I can't find in the plugin's documentation something like sendgird below:
![image](https://github.com/medusajs/medusa/assets/36871547/3785594a-7092-4c4e-b403-a1854b4d9e14)

Please tell me what I should do, thanks!

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by pevey** [comment]
https://github.com/pevey/medusa-plugin-ses

**Comment by dsks-pawn** [comment]
![image](https://github.com/medusajs/medusa/assets/36871547/2d7c18c3-fcd4-4c7e-a2ff-5359a9fca160)


> https://github.com/pevey/medusa-plugin-ses

Sorry for not testing and replying sooner, I know this issue has been closed, but please help me how to import a scope for a service. Thank

**Comment by pevey** [comment]
You're case is a little different than calling from a separate service.  

If you're extending a class,  I think you can access the methods of the class you're extending by referring to it as 'super.'  For instance, super.sendEmail(...)

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/super

**Comment by pevey** [comment]
Don't extend AbstractNotificatonService.  Extend sesService.  You can only have one Notification provider.  If you make your own, the one from the plugin can't be loaded.

**Comment by dsks-pawn** [comment]
> Don't extend AbstractNotificatonService. Extend sesService. You can only have one Notification provider. If you make your own, the one from the plugin can't be loaded.

![image](https://github.com/medusajs/medusa/assets/36871547/46d910fd-a21b-4997-92e7-6a284893f4c4)

Sorry for not understanding what you mean because I'm actually new to medusa. I just want to do something really basic with document. I want to send mail with ses here.
Is there an easy way to do it and an example for me, please!

![image](https://github.com/medusajs/medusa/assets/36871547/3f424ee2-5f88-4c84-81ba-09a9cf4e0667)
I also tried other ways like trying to import and extend from SESService but it didn't work

**Comment by pevey** [comment]
I think what you want to do is create a subscriber, not modify the service.  You can read about subscribers here: https://docs.medusajs.com/development/events/create-subscriber

Please read through the docs first.  I know it takes a lot of time to read through them, but keep in mind they also took a lot of time for people to write, and it saves time responding to individual questions.  If you still need help, there's the Medusa Discord server which has a channel dedicated to Help questions:  https://discord.gg/r9MskmrH
