### ISSUE TITLE
Docs(Code Issue): Code Issue in /development/entities/extend-entity

### ISSUE THREAD

**Issue by riivostolts** [medusajs/medusa#5180]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The 3rd step (adding TypeScript support) of extending the entity tutorial does not seem to work as described. Perhaps the path described is wrong or I'm doing something wrong, but having the index.d.ts file directly in src directory did not extend the Product interface. I tried it even with a fresh backend application built with `medusa new my-medusa-store` command.

However it did seem to pick up the type extension once I moved the index.d.ts file inside of any one of the directories inside of src directory. But I'm not really sure if it's the way to go.

### How can this issue be resolved?

Moving the index.d.ts file into of any one of the directories inside of src directory.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
I can't seem to reproduce this issue, but will add a note about it in the docs in case someone else runs into this issue.
