### ISSUE TITLE
Guide does not work at all outdated

### ISSUE THREAD

**Issue by yersultanur** [medusajs/medusa#5182]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Even if I do all by the guide changes made in strapi or medusa does not work vice versa 

### How can this issue be resolved?

1. Make it work
2.
3.
...

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by jbeckton** [comment]
Two problems I am having...

1. During setup it asked me for an admin email but not the password, I cannot log into the admin app for the first time and the guide mentions that I should have been assked for a password.


Step 6: Log into admin dashboard
Once the project is prepared, the Medusa backend will start and the admin dashboard will be opened in your default browser. You'll then be asked to enter a password for the admin email you entered earlier, as well as other account information.

Once you're logged in, you can start using Medusa! Try following the setup guide to create your first product and order.


The only password I was asked for during set up was for the database, I tried that for the admin login and it did not work.


3. Right after install I cannot hit the admin site using https.

**Comment by jbeckton** [comment]
after 5 or 6 times trying I decided to add a few params to the command and it looks like that helped...

npx create-medusa-app@latest --seed --no-browser


But what am I supposed to do with this?

![image](https://github.com/medusajs/medusa/assets/2669585/15deb311-5999-476c-b9db-406af03b5912)

**Comment by shahednasser** [comment]
Hey guys, thank you for sharing your issues. Seem like these are two different issues, so @jbeckton if the solution in this comment doesn't work, please open another issue to avoid confusion.

@yersultanur From what I gather you're trying to install strapi, we're aware that the strapi plugin in the docs isn't working properly and will be updating the guide to use another community plugin.

@jbeckton when you run `npx create-medusa-app@latest` and the installation finishes, an admin window opens and you'll be shown a form to enter your password. Once you enter the password, a user is created for you and you can log in. If that's not happening, please open another issue with more details about the command you're running and what you see in the admin.

**Comment by yersultanur** [comment]
@shahednasser thank you will be waiting for it, it has too many issues for me to describe.
Typescript doesn't work, even if I install fresh strapi and add template docs it doesn't work. 
When I am done with the JavaScript install, it looks like all okay, but the connection doesn't operate vice-versa, you just publish random staff.

**Comment by shahednasser** [comment]
Got it. If you want you can refer to [this community plugin](https://github.com/SGFGOV/medusa-strapi-repo), which is what we'll be documenting.

Will close this issue for now.
