### ISSUE TITLE
HTTPS?

### ISSUE THREAD

**Issue by jbeckton** [medusajs/medusa#5183]
After install the admin panel will not load using https, if I use http it will load but then when trying to accept an invite it blows up trying to call the backend with https.

I can hit the backend with curl using http and get data back but not https. 

using the cli if I generate another invite when I try and accept it blows up.

TypeError
Cannot read properties of undefined (reading '0')
Call Stack
 getErrorMessage
  webpack-internal:///29495:12:12
 eval
  webpack-internal:///7185:373:118
 step
  webpack-internal:///7185:237:23
 Object.eval [as throw]
  webpack-internal:///7185:178:20
 asyncGeneratorStep
  webpack-internal:///7185:42:28
 _throw
  webpack-internal:///7185:63:17

train wreck

**Comment by olivermrbl** [comment]
Can you provide reproducible steps? :)

Also, please keep a respectful tone. Hopefully, we'll be able to figure out what's bugging you.

**Comment by jbeckton** [comment]
There is nothing wrong with my tone. I posted that at midnight last night so my sentences were short and to the point.  

The steps to reproduce are in the docs, I followed this guide.
https://docs.medusajs.com/create-medusa-app

At the end of the install when the browser pops open it tries to load the admin using https and that's where it ends, the admin app won't load when using https. When I force it to http the admin app will load but as soon as it tries to make calls to the backend it falls apart because the backend calls are using https. 


initially used the npx create-medusa-app command about 6 times and then tried a few more times using the cli new command. Every time I try and hit the admin app right after installation the browser says...

Latest Edge Browser
![image](https://github.com/medusajs/medusa/assets/2669585/14578abb-1faa-4b5f-a1a8-15132ed43471)


Latest Chrome
![image](https://github.com/medusajs/medusa/assets/2669585/14d74e1d-4029-4b37-a750-d1841917cac2)


After fighting with this for a few hours I was able to get Chrome to stop redirecting from http to https and I was able to load the admin app but Edge will ignore the settings that are supposed suppress this behavior so the admin app will not run the admin app locally due to the local ssl issues. 

Is there no way to instruct medusa to run under https locally?

**Comment by jbeckton** [comment]
Finally found a workaround.

Option #1:  Never use Microsoft Edge for running local apps.


Microsoft Edge browser may redirect HTTP URLs to HTTPS URLs for local web applications. This can cause issues when trying to access local web applications that are not configured for HTTPS. There are a few ways to disable this feature:

Option #2: One way is to delete the HSTS settings for the local URL from Edge’s internal settings. [You can do this by typing edge://net-internals/#hsts in the address bar, scrolling down to the section below, entering the local URL, and then clicking “Delete” ](https://stackoverflow.com/questions/63825407/microsoft-edge-redirects-http-localhost-to-https-localhost)[1](https://stackoverflow.com/questions/63825407/microsoft-edge-redirects-http-localhost-to-https-localhost).

Option #3: Another way is to disable the Automatic HTTPS feature in Edge’s settings. [To do this, type edge://settings/privacy in the address bar, scroll down to the Security section, and turn off the “Automatically switch to more secure connections with Automatic HTTPS” option ](https://geekermag.com/how-to-enable-and-disable-automatic-https-for-urls-in-microsoft-edge/)[2](https://geekermag.com/how-to-enable-and-disable-automatic-https-for-urls-in-microsoft-edge/).


Option #3 never worked despite trying it several times. Option #2 worked great. Option #1 works great as well.
