### ISSUE TITLE
Not everything is cached on product's page (nextjs starter kit)

### ISSUE THREAD

**Issue by LorenzoElenkov** [medusajs/medusa#5185]
## Bug report

Reproducible on Next.js Starter kit.
Product's page is revalidated every hour by default. There are some product's details that are not cached though.

### Describe the bug

When changing a product's details (e.g. name, description, adding or removing variants), they are not reflected immediately (which is understandable since we have `REVALIDATE_WINDOW` variable which is default `1000 * 60 * 60` - 1 hour.
However, if I change the pricing of any of the variants, this change can be observed immediately.

### System information

Medusa version (including plugins): v1.3.21
Node.js version: v16.16.0
Database: PostgreSQL
Operating system: Windows 11
Browser (if relevant):

### Steps to reproduce the behavior

1. Go to Admin UI and create a new product with the following details - title, description, variants, attributes, etc.
2. Go to Storefront and navigate to the newly created product's page - new product was created and can be seen.
3. Go back to Admin UI and navigate to the edit page of the newly created product.
4. Change Title, description, add or remove variants, change price of variants, modify attributes and any other details you want.
5. Go back to the Storefront and navigate to the edited product's page.
6. You will observe that the only change that is reflected is the variants' price. Description, title, etc. are the old values (cached ones)

### Expected behavior

It is expected that all details will be cached. This can be easily solved by setting the revalidate time of `medusaRequest` header to `0`

### Screenshots

![image](https://github.com/medusajs/medusa/assets/95830881/f76aff20-fd7d-4532-ae87-b3a567935ac8)
Revalidate window variable found in `storefront/lib/medusa-fetch/index.ts`

![image](https://github.com/medusajs/medusa/assets/95830881/137292e7-65f8-442a-939b-a3f9f519bb98)
The method which invokes the server-side fetching of the product and pass it to the `ProductTemplate` component.

![image](https://github.com/medusajs/medusa/assets/95830881/6af0edd7-0e53-439b-bb04-b809c29914c4)
Since I want to have my backend separated, PRODUCT MODULE is not enabled so we fallback to `medusaRequest`

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by olivermrbl** [comment]
Please open this issue in the [Next.js starter project](https://github.com/medusajs/nextjs-starter-medusa)
