### ISSUE TITLE
@medusajs/inventory wrong allocation after completing draft order

### ISSUE THREAD

**Issue by andriinuts** [medusajs/medusa#5198]
### Describe the bug

If after creating draft order manager will allocate items (reserve in the draft order page) and send link to the customer to make a payment, after completing order in store endpoint order successfully created but adding one more reservation, so the same item reserved twice.

### System information

Medusa version (including plugins):
"@medusajs/medusa": "^1.16.1",
"@medusajs/inventory": "^1.9.2",
"@medusajs/stock-location": "^1.9.1",

### Steps to reproduce the behavior

1. Create draft order with one selected product
2. Allocate this item on the draft order page (reserve it)
3. Copy link to the storefront payment and complete this order using store endpoint
4. Open successfully created order from the draft order, you will see that this item is reserved twice

### Expected behavior

Item should not be reserved twice for the same order.

**Comment by andriinuts** [comment]
up

**Comment by erikengervall** [comment]
Ran into this today as well, docs didn't mention anything regarding handling inventory manually.

**Comment by erikengervall** [comment]
@andriinuts was this addressed in recent versions (haven't upgraded in a bit) or is this a duplicate?

**Comment by andriinuts** [comment]
> @andriinuts was this addressed in recent versions (haven't upgraded in a bit) or is this a duplicate?

I guess they are redoing all the modules so this ticket will not make sense
