### ISSUE TITLE
chore: Make packages/medusa/src/services/query-builder.js pass linting

### ISSUE THREAD

**Issue by srindom** [medusajs/medusa#520]
In an effort to improve our code quality we want to have make sure that all files in the repo pass linting.

Please see this guide for a step-by-step guide for how to complete this task: https://www.notion.so/medusajs/Lint-challenge-checklist-b4efc761cb36499abf4726cad0dd02e4

🚀

**Comment by olivermrbl** [comment]
Sure! thanks @FominSergiy

**Comment by FominSergiy** [comment]
hey guys, a total side note. A lot of `chore/lint` issues look beginner friendly to me (I myself mark October as my first month of Open Source contributions).

There is a tag `first-timers-only` -- which is referenced in this page https://github.com/mungell/awesome-for-beginners (it also publishes such issues in this twitter account - https://twitter.com/first_tmrs_only)

Not sure if you want to implement it, but in case you do, this should give you additional exposure.

**Comment by olivermrbl** [comment]
Thank you for your contribution @FominSergiy ! ❤️ 

And thanks for the reference. Will definitely check that out 👍

Closed #550
