### ISSUE TITLE
[medusajs/ui] Focus Modal cannot be closed when using property open

### ISSUE THREAD

**Issue by dsks-pawn** [medusajs/medusa#5206]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

![image](https://github.com/medusajs/medusa/assets/36871547/67713c93-e7fe-4818-9ded-63074e91e1fb)

I tried using the focus modal as below. I want it to be able to close and open the modal if a button is clicked in another location, so I don't use FocusModal.Trigger but use a state called "openModal".
Everything is fine, but the default close button is not working, how can I fix it?

![image](https://github.com/medusajs/medusa/assets/36871547/64d59b83-d782-47db-b806-dcd04b2c7771)

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by dsks-pawn** [comment]
i fixed this by not using FocusModel.Heading, instead using
```
 <div className={
              'border-ui-border-base flex items-start justify-between gap-x-4 border-b p-4'
            }
          >
            <div className="flex items-center gap-x-2">
              <Dialog.Close asChild>
                <Button variant="transparent" size={'small'} format={'icon'}>
                  <XMark onClick={() => setOpenModal(false)} />
                </Button>
              </Dialog.Close>
              <Kbd>esc</Kbd>
            </div>
            <div>
              <Button onClick={handleUpdateMailTemplate}>Save</Button>
            </div>
          </div>
```

**Comment by kasperkristensen** [comment]
Hi @dsks-pawn, in the future please use the relevant repo to report any issues you have with the UI package https://github.com/medusajs/ui.

When you take control of the Modal you also need to provide an `onOpenChange` function that allows the modal to update its state. In your case you should update your code like this:

```tsx
<FocusModal defaultOpen={false} open={openModal} onOpenChange={setOpenModal}>
....
```

Closing the issue, as everything is working as expected :)
