### ISSUE TITLE
Admin UI / Pricing Module - Invalid data: amount must be an integer

### ISSUE THREAD

**Issue by jpizzle34** [medusajs/medusa#5226]
### Describe the bug

When editing product-variant prices via the admin ui pricing module, you cannot save a price of 19.99. Attempting save the price results in a HTTP 400 Bad request `message: amount must be an integer number` from the backend.

### System information

Medusa version (including plugins): 10.16.1 with Inventory and Stock Location Modules
Node.js version: v18
Database: Postgres
Operating system:
Browser (if relevant):

### Steps to reproduce the behavior

1. Go to 'Products'
2. Select an existing product to edit.
3. In the 'Variants' section, click the three dots > 'Edit Prices'
4. Input a price of 19.99 for any variant.
5. Click 'Save' and see error 'Failed to save prices'

### Expected behavior

Updating prices to 19.99 is succesful.

### Screenshots

![image](https://github.com/medusajs/medusa/assets/48883158/d50ab7e6-acdc-4b9a-9b39-e2d2b3a9e01b)

### Code snippets

```http
POST
/admin/products/<product_id>/variants/<variant_id>
```

Payload sent:
```json
{"prices":[{"id":"ma_01HBAR7TXG5Q2DYN5TV7CCFWY6","amount":2199,"region_id":null,"currency_code":"eur"},{"id":"ma_01HBAR7TXGXRMR9KAVJ874FJZP","amount":1998.9999999999998,"region_id":null,"currency_code":"usd"}]}
```

### Additional context

Seems to work for 21.99 eur but not 19.99 usd in this example. Notice the floating point error in the body of the http request above.

**Comment by harshajayaweeraXHJ** [comment]
I get the same error. Having trouble in production due to this. Any solution?

**Comment by olivermrbl** [comment]
This should have been solved in https://github.com/medusajs/medusa/pull/5456. Can you update to latest and try again?

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
