### ISSUE TITLE
Cannot scroll in tax rates columns

### ISSUE THREAD

**Issue by Alexnortung** [medusajs/medusa#5229]
### Describe the bug

If I have added too many regions, then I cannot scroll in the regions container in the taxes settings.

### System information

Medusa version (including plugins): 1.16.0 (admin: 7.1.0)
Node.js version: 18
Database: postgres
Operating system: NixOS
Browser (if relevant): firefox

### Steps to reproduce the behavior

1. Add some regions to your medusa installation (5 should be enough or more if you don't want to make your window smaller in step 4)
2. Go to settings -> taxes
4. Make your window smaller in height
5. See that it is not possible to scroll in either the left or right container

### Expected behavior

I would expect that I could scroll in both containers

### Screenshots

![billede](https://github.com/medusajs/medusa/assets/1552267/edb3ae74-b060-437f-b6bf-803763b9a6c4)

![billede](https://github.com/medusajs/medusa/assets/1552267/5eea2e0f-be3e-421d-ab49-441561aac95f)

### Additional context

It looks like one of the containers have overflow hidden, maybe this should only be overflow-x hidden?

**Comment by olivermrbl** [comment]
@kasperkristensen, can you find time to look into this one?
