### ISSUE TITLE
Cannot set inventory to 0

### ISSUE THREAD

**Issue by Alexnortung** [medusajs/medusa#5230]
### Describe the bug

When I try to set inventory of a variant to 0, and save the variant, then the inventory doesn't change

### System information

Medusa version (including plugins): 1.16.0 (admin: 7.1.0)
Node.js version: 18
Database: postgres
Operating system: NixOS
Browser (if relevant): firefox

### Steps to reproduce the behavior

1. Create a mew product
3. Create a new variant for that product and set "quantity in stock" to an aribtrary value greater than 0
4. Edit the variant
5. Set the "quantity in stock" to 0
6. Click save
7. See that the quantity did not change.

### Expected behavior

Expected it to be set to 0

**Comment by quang-ng** [comment]
I believe there might be an issue in the Admin Dashboard regarding the submission of a request to `admin/products/<product-id>/variants/<variants-id>` when the inventory is 0. In this case, the payload is lacking the inventory_quantity field.

**Comment by quang-ng** [comment]
Could I take this issue?

**Comment by olivermrbl** [comment]
@quang-ng This has been solved in #5173
