### ISSUE TITLE
Admin Invite Flow Throws 500 Error 

### ISSUE THREAD

**Issue by pevey** [medusajs/medusa#5245]
While setting up notifications for admin user invites on a fresh Medusa install and testing the flow, I noticed a couple of issues, one major and one minor:

1) When the user navigates to http://localhost:7001/invite?email={user_email}&token={{token}}, the invite is accepted and the password is saved, but then there is a 500 error in the admin app.  The uncaught error seems to be caused by a 404 call to http://localhost:9000/admin/analytics-configs.  

2) When accepting an invite via the API, not using the admin app, an error is thrown if the first_name and last_name properties are not included on user in the request.  They can be empty strings, but an error is thrown if they are not present.  This is a very minor issue, but ideally the validator should be modified so that they are not be required.

**Comment by olivermrbl** [comment]
@pevey, can I get you to extract 1. to a separate issue for tracking? Closing this, as 2. has been solved.

**Comment by pevey** [comment]
I don't believe this should be closed because the minor issue (#2) has been addressed.  The main, larger issue (#1) is a major issue that gives a very bad impression to new users setting up Medusa for the first time.

There is no need to set up a separate issue, as another user already reported it separately just after I did.

**Comment by olivermrbl** [comment]
Your issue does not follow our bug-reporting template. If you update the description accordingly, I will happily reopen it. Just thought it would be easier to open a new :)

**Comment by pevey** [comment]
Seems strange to be a stickler when someone is trying to help out by reporting a major issue.

In any case, a separate issue was already reported here: https://github.com/medusajs/medusa/issues/5260

**Comment by olivermrbl** [comment]
I can't seem to reproduce your issue, but I might be missing something.

Can I get you to add the steps leading to the error?
