### ISSUE TITLE
Setup a new Medusa project, getting an error on Admin Login Screen

### ISSUE THREAD

**Issue by manikmi** [medusajs/medusa#5260]
### Describe the bug

Brought a new medusa project by following:
1. Install Postgres using docker
2. medusa using npx create-medusa-app@latest with storefront as well.

Getting error on admin login page as attached in screenshots section

### System information

Medusa version (including plugins): 
    "@medusajs/admin": "^7.1.1",
    "@medusajs/cache-inmemory": "^1.8.8",
    "@medusajs/cache-redis": "^1.8.8",
    "@medusajs/event-bus-local": "^1.9.6",
    "@medusajs/event-bus-redis": "^1.8.9",
    "@medusajs/file-local": "^1.0.2",
    "@medusajs/icons": "^1.0.0",
    "@medusajs/medusa": "^1.16.0",
    "@medusajs/ui": "^1.0.0",
    "medusa-fulfillment-manual": "^1.1.38",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.24",
    "medusa-payment-stripe": "^6.0.4",
    "prism-react-renderer": "^2.0.4",
Node.js version: v16.20.2 using nvm
Database: Postgres using docker: https://dso.docker.com/images/postgres/digests/sha256:2ce090cb411df61ba37bf3fc41e6f8318a9bde5d5aede82beb92e5f83640bdfa 
Operating system: Mac Ventura 13.6
Browser (if relevant): Chrome

### Steps to reproduce the behavior

1. Install Postgres using docker and run it on port 5432
2. Run medusa using npx create-medusa-app@latest with storefront as well
3. Load the admin login page
4. See error as attached in screen shot

### Expected behavior

The page should load correctly

### Screenshots

<img width="1433" alt="image" src="https://github.com/medusajs/medusa/assets/797398/4f10bf5c-ba89-47b5-a6b7-db8b3b5b69dd">

**Comment by pevey** [comment]
This may be related to this: https://github.com/medusajs/medusa/issues/5245

**Comment by manik-ushur** [comment]
Any pointers, how to solve this issue?

**Comment by pevey** [comment]
If it's the same error as in the link I posted, it occurs after the password is set. If you go to the url bar and manually go to the main page of the admin, it should work.

**Comment by manikmi** [comment]
Thanks Lacey. Do you also see the same issues as I have pasted the screenshot?

Yes, if I ignore and move on, the login works.

Can somebody from support team help?

**Comment by pevey** [comment]
The error is generic, unfortunately. So I can't be sure. But it's almost certainly the same bug. I'm sure it will be prioritized for a fix.

**Comment by olivermrbl** [comment]
Solved in https://github.com/medusajs/medusa/pull/5467
