### ISSUE TITLE
Quantity pricing not updated when adding existing item again

### ISSUE THREAD

**Issue by pepijn-vanvlaanderen** [medusajs/medusa#5270]
### Describe the bug

In the latest Medusa release a fix is introduced for proper quantity pricing, however this did not cover the scenario when someone adds an existing item in the cart.

### Steps to reproduce the behavior

1. Create a quantity price list for product X that normally costs €100,- but on price list with min quantity 2 €90,-
2. Create a cart through the API
3. Add product X with quantity 1 to the cart, see indeed a unit price of €100,-
4. Add product X with quantity 1 to the cart, see still a unit price of €100,-, while now it should be €90,-

### Expected behavior

Quantity should be updated to match the price list rules when adding through https://docs.medusajs.com/api/store#carts_postcartscartlineitems

I have opened a PR to fix the issue: https://github.com/medusajs/medusa/pull/5269

**Comment by BorisKamp** [comment]
For me the quantity pricing & pricelist don't work at all. I was made aware of missing relations in customer endpoints on my thread here:
https://discord.com/channels/876835651130097704/1135954658121236640

Im getting quite worried with Medusa's capability to reply to bug reports here (I have some open for a while) and bugs that sneak trough in releases.

**Comment by pepijn-vanvlaanderen** [comment]
Hi @BorisKamp, bit off topic for this bug report. However, do you have a custom price selection strategy in place? Without my PR and on the latest v1.17.0 the quantity based discounts do work properly if you add directly with a quantity for which a price override is applicable.

Also regarding the mentioned Discord threat, I don't think a missing relation should matter when having customer group specific price lists. The customer ID is read from the session and used in the price selection strategy to lookup available prices, maybe you can copy the price selection strategy from core and log and test from there.

Furthermore this is an open-source project with many focuses, not only your requirements, so try to be constructive and maybe even contribute solutions.

**Comment by BorisKamp** [comment]
> Hi @BorisKamp, bit off topic for this bug report. However, do you have a custom price selection strategy in place? Without my PR and on the latest v1.17.0 the quantity based discounts do work properly if you add directly with a quantity for which a price override is applicable.
> 
> Also regarding the mentioned Discord threat, I don't think a missing relation should matter when having customer group specific price lists. The customer ID is read from the session and used in the price selection strategy to lookup available prices, maybe you can copy the price selection strategy from core and log and test from there.
> 
> Furthermore this is an open-source project with many focuses, not only your requirements, so try to be constructive and maybe even contribute solutions.

Thank you for your reply. I will not reply with the intention of solving my problem as that's not my intention and off-topic indeed.

I am aware of the open source nature and am trying to contribute as much as possible by creating (as detailled as possible) reports for the bugs/issues I encounter. My hope is that they will be resolved so we get a better Medusa and that  other developer that read it might be helped with.

Thanks for the insight.

**Comment by olivermrbl** [comment]
Thanks for reporting this @pepijn-vanvlaanderen. And for pitching in @BorisKamp.

We're doing our best to balance community efforts and ("internal") feature-building. Looping in @pKorsholm. We'll push to get back as soon as possible. Thank you for your patience :)

**Comment by BorisKamp** [comment]
Might be related
https://github.com/medusajs/medusa/issues/5274

**Comment by pKorsholm** [comment]
should be fixed by #5275

**Comment by adrien2p** [comment]
@pepijn-vanvlaanderen I am currently generating a snapshot. so you should be able to test it once it is generated on the pr. let us know

**Comment by pepijn-vanvlaanderen** [comment]
@adrien2p tested with the latest snapshot and it works!
