### ISSUE TITLE
draft order update line item price broken

### ISSUE THREAD

**Issue by BorisKamp** [medusajs/medusa#5274]
Medusa `1.17.0`

Okay, I'm getting a bit confused here if it's just my installation/setup or if there just many bugs surrounding the pricelist/quantity at the moment. 
[I have this issue open as well, might be related](https://github.com/medusajs/medusa/issues/5261).

Well, regarding this issue. I have created a draft order and add a line item to it using `{{medusa-host}}/admin/draft-orders/dorder_01H5MPT3HCR24FY86ZP1SXK6K0/line-items`:
```json
{
    "unit_price": 4000,
    "quantity": 10,
    "variant_id": "variant_01H5MGMWTZZ40XTN76TEH7YJNA"
}
```

Note here, the actual price of the variant is `4860`, but I override the price. The `draftorder.cart.subtotal` is now `40000` which is spot on. However, when I call the following:
```json
{
    "unit_price": 4000,
    "quantity": 9
}
```

to update the line item (`{{medusa-host}}/admin/draft-orders/dorder_01H5MPT3HCR24FY86ZP1SXK6K0/line-items/item_01HBRAR20BDARYF5676H6SCFH3`), the `variant.unit_price` is reset to `4860` which is the variant's listing price...

This is new since I updated to Medusa `1.17.0` and breaks my customer's draftorder UI as they cannot set custom prices anymore.

It it just me or or this an actual bug? I am starting to doubt myself since this and my other bug report are quite serious and am thinking I might actually do something wrong myself....

**Comment by BorisKamp** [comment]
I can verify that when I downgrade to Medusa `1.16.0` that I no longer have this issue. So it sneaked it with `1.17.0`....

**Comment by pKorsholm** [comment]
Thanks for reporting this 😄 

should be fixed by #5275

**Comment by BorisKamp** [comment]
> Thanks for reporting this 😄
> 
> should be fixed by #5275

Will this be fixed in the next release?

**Comment by adrien2p** [comment]
@BorisKamp It should be fixed in the next release. You can test the snapshot that will be generated [here](https://github.com/medusajs/medusa/pull/5278)

**Comment by olivermrbl** [comment]
@BorisKamp closing this. Let us know if the issue persists with the latest versions.
