### ISSUE TITLE
API - Unable to create options after product and variant creation

### ISSUE THREAD

**Issue by rickylabs** [medusajs/medusa#5276]
## Bug report

Similar issue: https://github.com/medusajs/medusa/issues/4738#issue-1844733911 but occured also using API with error 500

![Error log](https://github.com/medusajs/medusa/assets/129366361/dc2bdd14-174a-44fc-ad05-bfa7ce29033d)

### Describe the bug

Unable to create product option after minimal product creation. Same apply for product created with initial variant (without option).

https://github.com/medusajs/medusa/assets/129366361/a88501ee-77db-441e-b2ed-4c217ffc7b63

### System information

Medusa version (including plugins): 1.17.0
Node.js version: 18
Database: postgres 
Operating system: linux 

### Expected behavior

We should be able to create product options after product creation from the ADMIN and the API

### Code snippets

Product payload:
```
{
  "id": "prod_01HBVMB47TJQFB378D6D7PRJS1",
  "created_at": "2023-10-03T20:40:46.065Z",
  "updated_at": "2023-10-03T20:40:46.065Z",
  "deleted_at": null,
  "title": "T-Shirt",
  "subtitle": null,
  "description": null,
  "handle": "t-shirt",
  "is_giftcard": false,
  "status": "draft",
  "thumbnail": null,
  "weight": null,
  "length": null,
  "height": null,
  "width": null,
  "hs_code": null,
  "origin_country": null,
  "mid_code": null,
  "material": null,
  "collection_id": null,
  "type_id": null,
  "discountable": true,
  "external_id": null,
  "metadata": null,
  "store_id": null,
  "categories": [],
  "collection": null,
  "images": [],
  "options": [],
  "profiles": [
    {
      "id": "sp_01H7AR90DYBFFKSMM43510Z0ZX",
      "created_at": "2023-08-08T14:19:38.864Z",
      "updated_at": "2023-08-08T14:19:38.864Z",
      "deleted_at": null,
      "name": "Default Shipping Profile",
      "type": "default",
      "metadata": null
    }
  ],
  "profile": {
    "id": "sp_01H7AR90DYBFFKSMM43510Z0ZX",
    "created_at": "2023-08-08T14:19:38.864Z",
    "updated_at": "2023-08-08T14:19:38.864Z",
    "deleted_at": null,
    "name": "Default Shipping Profile",
    "type": "default",
    "metadata": null
  },
  "profile_id": "sp_01H7AR90DYBFFKSMM43510Z0ZX",
  "sales_channels": [
    {
      "id": "sc_01H7AR90KRFBP4FK84B6F9D0RC",
      "created_at": "2023-08-08T14:19:38.864Z",
      "updated_at": "2023-08-08T15:39:06.669Z",
      "deleted_at": null,
      "name": "Kooko Lausanne",
      "description": "Secteur lausannois",
      "is_disabled": false,
      "metadata": null
    }
  ],
  "store": null,
  "tags": [],
  "type": null,
  "variants": []
}
```

### Additional context

Tested using postman with different Auth strategies with and without initial variant

Table product & product_option was empty

### Side note

We need the ability to create product without variant and add variants and options afterwards because we're syncing our data from our ERP with N8N and in most scenarios variants and options might not be yet created or necessary.

### Linked question (probably belong to discussion thread)

- Is it possible/planned to create generic options that can be re-used across all catalog ?
- Is it possible/planned to cumulate "options" that would be additional "items" linked to a product like selecting different sauce for a meal ? Ideally theses "options" would have a fixed price that cumulate to the product variant original price ? Or do you see a better approach for that use case ?

I assume these two scenarios would need custom code just wondering if itheses could be considered "core features" that might be added later ?

**Comment by adrien2p** [comment]
Same as for the other issue, I ve done some testing and recorded the API interaction in order to create the option and the values through the variant update, which is the classic flow. can you let me know more about the issue you are encountering?

https://github.com/medusajs/medusa/assets/25098370/073e5e9d-15f8-4cce-8c49-3d82bc744a2a

**Comment by rickylabs** [comment]
@adrien2p sorry for the delay I've added more context to describe the issue.

Also unrelated but in my postgres DB the table product_shipping_profile lacks a column with primary key not sure if it's an excpected behaviour.

**Comment by adrien2p** [comment]
Could you share your medusa config please, cause of you look the video I ve attached, i am doing the exact same thing as you and it work. So i would like to be sure that i have the same setup including modules and feature flags to better find the issue.

Also, do you have any customization that i should je aware of? The issue seems to comes from the productService.retrieve method, from what i can see the buildQuery does not seem to return the expected result in your case and relations is pulled from it. Are you up to date of all the packages including the utils?


Also, for your question in regards to the pivot table, yes it is intended

**Comment by rickylabs** [comment]
medusa config plus product service:
[medusa-config.zip](https://github.com/medusajs/medusa/files/12797012/medusa-config.zip)

Yes indeed I did some customization related to marketplace (followed official doc though)

I think that your workflow was a bit different you created a variant "One Size" with a default option and then added another option right ?

**Comment by adrien2p** [comment]
Yes i had a variant and an option already, but it doesn't explain your issue with the relation. Can you share the customization you have, you might have a customisation on the product service i suppose and i suspect i might comes from there. If you can log the the args passed to the buildQuery and maybe the result of the builQuery we might find something there. To do that you can just go to the line that you can find in the stack trace and you ll see the place.

**Comment by rickylabs** [comment]
Adapted code from [here](https://medusajs.com/blog/extending-medusa-usecase-marketplace/#extend-the-product-service) as below to add more verbose

```javascript
    async retrieve(productId: string, config?: FindProductConfig): Promise<Product> {
        console.log("productId", productId)
        console.log("config", config)
        config.relations = [
            ...(config.relations || []),
            'store'
        ]

        try {
            const product = await super.retrieve(productId, config);
            if (product?.store?.id && this.loggedInUser_?.store_id && product.store.id !== this.loggedInUser_.store_id) {
                // Throw error if you don't want a product to be accessible to other stores
                throw new Error('Product does not exist in store.');
            }

            console.log(product)

            return product
        } catch (e) {
            console.error(e)
        }
    }
```

log :

```
::1 - - [03/Oct/2023:21:37:51 +0000] "POST /admin/auth HTTP/1.1" 200 278 "-" "PostmanRuntime/7.32.3"
productId prod_01HBVMB47TJQFB378D6D7PRJS1
config { relations: [ 'options', 'variants' ] }
{
  id: 'prod_01HBVMB47TJQFB378D6D7PRJS1',
  beforeInsert: [Function (anonymous)],
  beforeUpdate: [Function (anonymous)],
  afterLoad: [Function (anonymous)],
  created_at: 2023-10-03T20:40:46.065Z,
  updated_at: 2023-10-03T20:40:46.065Z,
  deleted_at: null,
  options: [],
  store: null,
  variants: []
}
productId prod_01HBVMB47TJQFB378D6D7PRJS1
config undefined
error:   Cannot read properties of undefined (reading 'relations')
TypeError: Cannot read properties of undefined (reading 'relations')
    at ProductService.retrieve (C:\DEV\kooko-medusa\medusa\dist\services\product.js:39:24)
    at ProductService.<anonymous> (C:\DEV\kooko-medusa\medusa\node_modules\@medusajs\medusa\dist\services\product.js:778:72)
    at step (C:\DEV\kooko-medusa\medusa\node_modules\@medusajs\medusa\dist\services\product.js:59:23)
    at Object.next (C:\DEV\kooko-medusa\medusa\node_modules\@medusajs\medusa\dist\services\product.js:40:53)
    at fulfilled (C:\DEV\kooko-medusa\medusa\node_modules\@medusajs\medusa\dist\services\product.js:31:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
::1 - - [03/Oct/2023:21:38:01 +0000] "POST /admin/products/prod_01HBVMB47TJQFB378D6D7PRJS1/options HTTP/1.1" 500 86 "-" "PostmanRuntime/7.32.3"

```

it seems service is called twice (any idea why ?) and second time config is empty

Edit: solved by checking if config exist before updating object, anway strange issue. I think we can close the issue since it's related to marketplace customization maybe an update of medusa doc to handle such case would be nice !

Also any feedback on my two linked question in my original post ?

Thank you for your time, appreciate !

**Comment by adrien2p** [comment]
The fact that is it called twice seems weird, you should look around your customisation or look at the callee stack. 
One thing, you should always take into consideration that `config` is optional and therefore can be undefined by nature.
I would suggest the following:
```ts
config ??= {} // You can also add an initializer on the argument
config.relations ??= []
config.relations.push("store")
```

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
