### ISSUE TITLE
Missing file in digital-products recipe?

### ISSUE THREAD

**Issue by ryan-feagin** [medusajs/medusa#5277]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I think I found an issue while following the instructions for [recipes/digital-products](https://docs.medusajs.com/recipes/digital-products).  src/services/product-media.ts imports from "../repositories/product-media", but I don't see where the instructions show creating that repository.

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for pointing this out! Will open a PR to fix this
