### ISSUE TITLE
S3 file plugin upload to specific directory

### ISSUE THREAD

**Issue by pepijn-vanvlaanderen** [medusajs/medusa#5292]
## Feature request

Currently it is not possible to upload all your Medusa files into a specific directory with the S3 plugin. We reuse 1 bucket for a project for Medusa but also storefront, and sometimes also different environments as well.

A structure in our bucket would often look like:
- development
  - medusa
  - storefront
- staging
  - medusa
  - storefront
- production
  - medusa
  - storefront

### Proposed fix
See https://github.com/medusajs/medusa/pull/5291

**Comment by olivermrbl** [comment]
Solved in #5291, thanks!
