### ISSUE TITLE
API Ref(store): Issue data delivery for cart empty 

### ISSUE THREAD

**Issue by dsks-pawn** [medusajs/medusa#5299]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

After adding the product to the cart, I proceed to checkout. After entering the shipping and billing address, I wait for delivery data but it returns an empty array?
I checked in the admin site and database, it's completely normal (default data).
I can't check how the code in api /store/shipping-options/cart-id is written? What should I do to get response delivery? Thank!

![image](https://github.com/medusajs/medusa/assets/36871547/58659532-e1e7-44c4-a1ad-473356b876b2)

![image](https://github.com/medusajs/medusa/assets/36871547/bea6d003-4fec-4d2f-81dd-6b733d2d8045)

![image](https://github.com/medusajs/medusa/assets/36871547/fe3e036f-390f-4376-890a-db931d4d6429)

![image](https://github.com/medusajs/medusa/assets/36871547/97a3fa86-d2a3-4582-80b2-210df7393917)

![image](https://github.com/medusajs/medusa/assets/36871547/f1945102-7395-4ef2-b5f7-f95663548bc0)

![image](https://github.com/medusajs/medusa/assets/36871547/4376c0f5-ccad-4243-99b3-ae7ac674bcc9)

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by olivermrbl** [comment]
Are you using a fresh install? The missing shipping options could indicate that your products are not part of the default shipping profile in your store.

**Comment by dsks-pawn** [comment]
> Are you using a fresh install? The missing shipping options could indicate that your products are not part of the default shipping profile in your store.

Thank you for your support, my product was created by running a synchronous job on another system, it seems I missed this case.

**Comment by dsks-pawn** [comment]
> Are you using a fresh install? The missing shipping options could indicate that your products are not part of the default shipping profile in your store.

As mentioned above, I sync multiple products from other systems. So I created products in bulk using the repository and not through the admin api to increase performance, so there must have been a lack of data somewhere.
In case I cannot get this delivery, I have added the necessary data to the **product_shipping_profile** table, but it still does not work. Can you tell me where else I need to supplement? Thank!
