### ISSUE TITLE
Issues creating a new product with a variant with money amount

### ISSUE THREAD

**Issue by ConnysCode** [medusajs/medusa#5306]
## Bug report

Hi there,

It's been a while since we last reached out. I hope you're all doing well.

I'm writing to you today because we've encountered an issue with inserting new products in Medusa, and I could use some assistance in resolving it.

When attempting to create a new product, even with the most basic data, we've noticed that Medusa is not correctly handling the money amount. I want to clarify that I may be missing something obvious, but here's a simplified version of how we're trying to create a product:
```ts
await this.productService_.create(
  {
    ...productPayload, variants: [
      {
        title: "Default",
        sku: product.SUPPLIER_PID._text,
        prices: [{ amount: 1, currency_code: "eur" }],
        inventory_quantity: 100,
      },
    ]
  }
);
```

However, it seems that the insert query is not capturing the money amount correctly. Here's the relevant error message we're encountering:

```json
{
    "query": "INSERT INTO \"public\".\"product_variant_money_amount\"(\"variant_id\", \"money_amount_id\") VALUES ($1, DEFAULT)",
    "parameters": [
        "variant_01HC2VRNTCZTASV9EPJ0BM3NCW"
    ],
    "driverError": {
        "length": 342,
        "name": "error",
        "severity": "ERROR",
        "code": "23502",
        "detail": "Failing row contains (null, null, variant_01HC2VRNTCZTASV9EPJ0BM3NCW, null, 2023-10-06 16:05:10.897964+00, 2023-10-06 16:05:10.897964+00).",
        "schema": "public",
        "table": "product_variant_money_amount",
        "column": "id",
        "file": "execMain.c",
        "line": "1883",
        "routine": "ExecConstraints"
    },
    "length": 342,
    "severity": "ERROR",
    "code": "23502",
    "detail": "Failing row contains (null, null, variant_01HC2VRNTCZTASV9EPJ0BM3NCW, null, 2023-10-06 16:05:10.897964+00, 2023-10-06 16:05:10.897964+00).",
    "schema": "public",
    "table": "product_variant_money_amount",
    "column": "id",
    "file": "execMain.c",
    "line": "1883",
    "routine": "ExecConstraints"
}
```

From what I understand, it appears that Medusa is trying to create a new relation with a default value for the money amount, when it should be set to 1 in this particular case.

Thank you very much for your help! :heart:

---

### System information

Medusa version: v17.0.0
Node.js version: v20.5.1
Database: Postgresql
Operating system: MacOS 14.0

**Comment by olivermrbl** [comment]
@ConnysCode – thanks for filing this issue. If you want to interface directly with our services instead of our Rest API, you'll need to create variants and their prices subsequent to creating the product. You can see the flow of events in the `POST /admin/products` handler. 

https://github.com/medusajs/medusa/blob/441844ed8972f37f972ae60749a362937e7469f1/packages/medusa/src/api/routes/admin/products/create-product.ts#L170-L256

**Comment by ConnysCode** [comment]
Hey @olivermrbl
Thank you for your response. I've noticed this behavior in the core route, but it seems like something has changed recently. I however couldn't find any information about breaking changes related to this in the upgrade guides.

We've been using this method to import products in our production service for several months, and it has just now suddenly stopped working (we did not even upgrade recently). Are you certain that it's not possible to create them in this way? If that's the case, could you please explain why Medusa doesn't catch this and omits the variants value when creating a new product? This seems especially puzzling because when updating a product, you can't include a variant as well. So, I don't see the point of including them in the creation interface.

**Comment by olivermrbl** [comment]
I might have found the culprit. In [v1.16.0](https://github.com/medusajs/medusa/releases/tag/v1.16.0), we updated the relationship between money amounts (prices) and product variants from a many-to-one to a many-to-many. This was a breaking change. 

Can you check if the migration from this release has been run against your database?

Try to run:
```
SELECT * FROM "migrations";
```

The change has been applied if you see a migration named `dropMoneyAmountConstraintsForPricingModule1692953518123`.

Creating variants and prices directly using the `ProductService` is not supported in versions after 1.16.0.

I'll forward this to our team to see if we can add back the support for the updated schema. Until then, you'll have to use a combination of services to achieve this. You can use the handler I linked to in a previous message as source of inspiration.

**Comment by ConnysCode** [comment]
@olivermrbl Thanks for the info! Seeing this feature again would be amazing.

It would've been nice, to see that breaking change in the upgrade info tho ^^
https://docs.medusajs.com/upgrade-guides/medusa-core/1-17-0#overview
