### ISSUE TITLE
Broken link: Custom Admin Endpoint Documentation

### ISSUE THREAD

**Issue by spaultify** [medusajs/medusa#5311]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I was reading this [introductory guide for Medusa](https://medusajs.com/blog/beginner-guide-to-node-js-ecommerce-platform-understanding-the-medusa-server/#what-is-a-custom-endpoint-in-medusa) and under the section [What is a custom endpoint in Medusa?](https://medusajs.com/blog/beginner-guide-to-node-js-ecommerce-platform-understanding-the-medusa-server/#what-is-a-custom-endpoint-in-medusa), the links for further readings on how to create endpoints for Admin and Storefront is broken :(

### How can this issue be resolved?

Kindly update the documentation with the updated links or perhaps it would be better if the clicks on the introductory guide would redirect readers to the latest version of the guide (since the article was written last July 2022). Thank you!

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for reporting this! I'll look into fixing it, but I highly encourage referring to the documentation instead of the blog, as the blog has a lot of outdated details.

You can refer to [this guide](https://docs.medusajs.com/development/endpoints/create) on creating an endpoint.

**Comment by shahednasser** [comment]
Link has been fixed.
