### ISSUE TITLE
Cannot login with Firefox, but I can login with Chromium based browsers

### ISSUE THREAD

**Issue by sarbazx** [medusajs/medusa#5336]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:9000/admin/batch-jobs?limit=100. (Reason: CORS request did not succeed). Status code: (null).

### Describe the bug

Try to login to Admin with Firefox Developer Edition Browser

### System information

Medusa version (including plugins):
Node.js version: v20.5.0
Database: Postgresql
Operating system: MacOS Sonoma
Browser (if relevant): Firefox Developer Edition

### Steps to reproduce the behavior

1. Go to http://localhost:7001/login/
2. Try to login
3. Open console

### Expected behavior

Should be able to login to admin panel just like with any other browser

### Screenshots

If applicable, add screenshots to help explain your problem
![CleanShot 2023-10-09 at 22 39 31@2x](https://github.com/medusajs/medusa/assets/5629946/e11bdad1-389a-46ec-a292-278b9cfb9442)

**Comment by samhenderson511** [comment]
I had this issue with Safari, they said you have to host the backend and admin dashboard on the same domain for it to work without CORS errors

**Comment by sarbazx** [comment]
> I had this issue with Safari, they said you have to host the backend and admin dashboard on the same domain for it to work without CORS errors

it is on localhost, does it matter? @samhenderson511

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
