### ISSUE TITLE
Hacktoberfest request: Add translations to Admin

### ISSUE THREAD

**Issue by VariableVic** [medusajs/medusa#5346]
Hi all!

We'd like to translate our admin interface to make it more accessible to a wider audience. This task involves translating all the interface elements, labels, and messages into a language of your choice. To see which translations are already in place, check the [locales folder](https://github.com/medusajs/medusa/tree/develop/packages/admin-ui/ui/public/locales). Any other language is welcome.

**Steps to Complete:**

1. Create a translation file in `packages/admin-ui/ui/public/locales/{locale-code}/translation.json`
2. Translate all keys, you can check the existing translation files for reference.
3. Add your language to the `supportedLanguages` array in `packages/admin-ui/ui/src/i18n/index.ts`
4. Test the translated interface for accuracy and completeness.
5. Create a PR and add the `Hacktoberfest` tag.

**Deadline:**
Please complete the translation by the end of the month.

**Hacktoberfest:**

This issue is part of [Hacktoberfest](https://hacktoberfest.com/), an event that encourages open source contributions. By participating in Hacktoberfest, you can help improve this and other open source projects and plant trees while you’re at it!

**In progress:**
- Hindi: @its-kunal 
- Kannada: @vineetjk 
- Tamil: @prajjwalkumar17 
- Vietnamese: @huuduc2312
- Telgu: @Harshwardhan9431 

**Merged:**
- Bosnian: @samiralibabic 
- Croatian: @anamarijapapic

**Comment by its-kunal** [comment]
Is this issue available, I can translate it to Hindi. I want to contribute

**Comment by samiralibabic** [comment]
I can do Bosnian/Croatian/Serbian translations.

**Comment by anamarijapapic** [comment]
@samiralibabic, I've just submitted a PR for the Croatian translation. Please feel free to review it and, if helpful, use it for Bosnian/Serbian.

**Comment by VariableVic** [comment]
@its-kunal @samiralibabic @anamarijapapic  - Awesome, thanks all. I'll update the opening post to avoid double work.

**Comment by vineetjk** [comment]
I would like to contribute with Kannada ( Indian regional language ).

**Comment by VariableVic** [comment]
> I would like to contribute with Kannada ( Indian regional language ).

Thanks @vineetjk, added it to the WIP list!

**Comment by samiralibabic** [comment]
I've created PR for Bosnian, but I won't be doing Serbian.

Let's leave it for other newcomers. 

They can rely on what @anamarijapapic and I already did, as there should be minimal differences.

**Comment by pepijn-vanvlaanderen** [comment]
For anyone who wants to speed up translating, you can give ChatGPT a command like: "Can you translate the following json object, only translate the values not the keys and preserve content between double curly brackets. Translate from English to XX."

It does not handle the whole json file, but if you split the file in some chunks it works. Afterwards just scan and check if it is acceptable or update any translation to your liking.

**Comment by prajjwalkumar17** [comment]
I want to contribute I can translate for Español and Tamil as well if needed

**Comment by VariableVic** [comment]
@prajjwalkumar17 Awesome, added to the WIP list.

Thanks for the contributions so far all, keep it up!

**Comment by prajjwalkumar17** [comment]
Hey @VariableVic can I raise 2 Pr's for these 2 languages namely Spanish and Tamil will it be fine??

**Comment by VariableVic** [comment]
@prajjwalkumar17 Yep perfectly fine 👍🏻

**Comment by Excrillix** [comment]
@VariableVic I would like to contribute with French and Telgu.

**Comment by VariableVic** [comment]
Thanks @Harshwardhan9431, added them!

**Comment by VariableVic** [comment]
@prajjwalkumar17 @Harshwardhan9431 Guys, just double checked the locales folder and French and Spanish translations are already in place! But feel free to add/improve.

**Comment by prajjwalkumar17** [comment]
Sure the tranlations are correct only in es but the keys are pretty random I will sort them properly and create a PR for es

**Comment by prajjwalkumar17** [comment]
Hey @VariableVic should I open a PR for sorting some of the other languages that are currently present too ??

**Comment by prajjwalkumar17** [comment]
I have raised the [PR](https://github.com/medusajs/medusa/pull/5463) for tamil language and sorted the keys for spanish in this [PR](https://github.com/medusajs/medusa/pull/5461)

**Comment by its-kunal** [comment]
Hi @VariableVic, Added Hindi translation for admin-UI, and created a pull request #5452.

**Comment by TejasMate** [comment]
@VariableVic, I would like to contribute with Marathi

**Comment by undercontr** [comment]
Hello, I am currently translating to Turkish, but I saw that some words on the app is not translated, I am hundred percent sure that all keys are translated, still some translations are not showing on the screen, they are still English.

Any suggestion about this?

**Comment by sradevski** [comment]
Hey all, thanks for the contributions! We'll be closing this ticket, and we will maybe do another similar round when the time comes to translate the v2 admin, stay tuned!
