### ISSUE TITLE
[Docs] Typo in entity path under adding relations section

### ISSUE THREAD

**Issue by danielolamide** [medusajs/medusa#5350]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Just a small typo around the entity file paths. Specifically under the [Adding Relations](https://docs.medusajs.com/development/entities/create#adding-relations) section. I assume the file path for the Author entity should be `src/models/author.ts`

### How can this issue be resolved?

1. Just fixing the typo
2.
3.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for opening this issue! Yes it's a typo 😅 Will open a PR to fix it.
