### ISSUE TITLE
Price list is not working while changing item quantity in cart

### ISSUE THREAD

**Issue by d1sna** [medusajs/medusa#5359]
I have created price list with condition depends on quantity - 3 different prices for one variant of product 
first price: 
`{amount:3250
min_quantity:1
max_quantity:null}`

second price: 
`{amount:3200
min_quantity:2
max_quantity:null}`

third price: 
`{amount:3150
min_quantity:3
max_quantity:null}`

while i add item to EMPTY cart by post request  ( [https://docs.medusajs.com/api/store#carts_postcartscartlineitems](url) ) it works fine, but if i add item to cart with same item - price is keeping amount (unit_price field) of existing item's price inside cart

Example: 

Added to empty cart one item, price from price list is working fine : 
<img width="1061" alt="Снимок экрана 2023-10-12 в 10 27 15" src="https://github.com/medusajs/medusa/assets/56303300/aa32d7ff-f8a4-42fb-8491-5411abd51361">

Added to cart from above two more same items, price steel keeping like quantity equals one :
<img width="1061" alt="Снимок экрана 2023-10-12 в 10 28 06" src="https://github.com/medusajs/medusa/assets/56303300/4d5a6384-6f50-492f-8434-b052a031086a">

But if i add to EMPTY cart three items in one time - it's working again: 
<img width="1061" alt="Снимок экрана 2023-10-12 в 10 28 44" src="https://github.com/medusajs/medusa/assets/56303300/35fc294c-8fe8-41d8-abed-541157ab30e4">

**Question: is this correct behavior or not?**

ps: i have tried different types prices, switched price list between "sale" and "override", set maximum quantity with same number from minimum, tried to use update line item request for cart

pss: if admin panel one time would have interface to change not only prices but quantity inside prices it would be perfect

**Comment by pKorsholm** [comment]
Thanks for reporting this. 

This is not the correct behavior but a fix for this was merged with the latest release

what version of medusa are you using?

**Comment by d1sna** [comment]
> Thanks for reporting this.
> 
> This is not the correct behavior but a fix for this was merged with the latest release
> 
> what version of medusa are you using?

updated to 1.17.1 and yeah it's working, THANK YOU !
