### ISSUE TITLE
Page Not Found for link https://docs.medusajs.com/development/notification-service/create-notification-service

### ISSUE THREAD

**Issue by gisioraelvis** [medusajs/medusa#5379]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Trying to access [create-notification-service](https://docs.medusajs.com/development/notification-service/create-notification-service) on the `How to Create a Plugin` recipe redirects to `Page Not Found`. 

![image](https://github.com/medusajs/medusa/assets/67643652/8222c73e-b73d-45de-a47e-8eaf911dad53)

Also noticed on the create plugin [Development Resources](https://docs.medusajs.com/development/plugins/create#development-resources) section clicking on the `Create a Notification Service` navigates to the wrong page https://docs.medusajs.com/development/file-service/create-file-service.

![Screenshot 2023-10-16 111912](https://github.com/medusajs/medusa/assets/67643652/1fe0c021-7d63-4d2a-9fd0-192060c90714)

### How can this issue be resolved?

1. Update the links with the correct page.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for opening this issue! Will open a PR to address this. If you're still looking for the link it's [here](https://docs.medusajs.com/development/notification/create-notification-provider).
