### ISSUE TITLE
Medusa container Dependency injection issue in cart service.

### ISSUE THREAD

**Issue by NitishGameChanges** [medusajs/medusa#5384]
### Describe the bug
Our model is based on a subdomain, meaning multiple websites are hosted on the same Medusa backend, and based on the subdomain relevant data is served. 

We are setting up scope in middleware like 
req.scope.register({
            currentStore: {
                resolve: () => store // we find the get scope based on domain from which is it called 
            }
  
});

When cart complete api  (store/carts/cart_01HCYA3V594FHSW3KKQYJSKQWF/complete  POST) is hit, 
Method name protected async updateUnitPrices_(
    cart: Cart,
    regionId?: string,
    customer_id?: string
  ) from cart service is called. This is an overridden function in our case, so our function gets called from Medusa. 
Inside this function, we try to get currentStore by this.container.currentStore. 
The data that we get from this.container.currentStore is not the latest data, it is the store which was set for the first time. 
For other Services, this.container.currentStore gives the expected result. 
The wrong currentStore is resulted only in this function.

Before upgrade to 1.17.0 , this was working fine. 

### System information

Medusa version (including plugins): 
    "@medusajs/cache-redis": "1.8.8",
    "@medusajs/event-bus-local": "1.9.6",
    "@medusajs/event-bus-redis": "1.8.9",
    "@medusajs/medusa": "1.17.0",
    "@medusajs/medusa-cli": "1.3.21",
    "@medusajs/utils": "1.10.3",

Node.js version: v16.19.0
Database: Postgre SQL 
Operating system: mac
Browser (if relevant): chrome (not relevent)

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
