### ISSUE TITLE
Admin : translated status causes product publishing errors for non-english

### ISSUE THREAD

**Issue by bqst** [medusajs/medusa#5388]
### Describe the bug

When the user's language setting is set to a language other than English (in this case, French), it becomes impossible to publish/unpublish a product from the admin panel. An error message appears stating: "Erreur: status must be one of the following values: draft, proposed, published, rejected."

### System information

Medusa version (including plugins): 
```
    "@medusajs/admin": "^7.1.4",
    "@medusajs/cache-inmemory": "^1.8.7",
    "@medusajs/cache-redis": "^1.8.7",
    "@medusajs/event-bus-local": "^1.9.6",
    "@medusajs/event-bus-redis": "^1.8.9",
    "@medusajs/file-local": "^1.0.2",
    "@medusajs/inventory": "^1.10.0",
    "@medusajs/medusa": "^1.17.1",
    "@medusajs/stock-location": "^1.10.0",
    "@medusajs/ui": "^2.2.0",
    "medusa-file-minio": "^1.3.0",
    "medusa-fulfillment-manual": "^1.1.37",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.23",
    "medusa-payment-paypal": "^6.0.2",
    "medusa-payment-stripe": "^6.0.3",
    "medusa-plugin-algolia": "^0.2.20",
```
Node.js version: 18
Database: pg

### Steps to reproduce the behavior

1. Go to the admin panel
2. Set the user's language to French
3. Attempt to publish or unpublish a product
4. See error message

### Expected behavior

I expect to be able to publish or unpublish a product regardless of the user's language setting.

### Additional context

It seems like the language setting is affecting the validation for product statuses, possibly due to localization issues. This is limiting the usability for non-English speaking users.

Additionally, upon inspecting the network traffic, it's evident that the POST request payload is sending the translated status. For instance, sending `"{status: "Brouillon"}"` instead of the expected enum values like `"draft"`. This might be the root cause of the issue.

**Comment by olivermrbl** [comment]
Hmm, this is strange. I can't seem to reproduce the error. See video attached below:

https://github.com/medusajs/medusa/assets/59018053/0b1e5744-f4dc-47ac-a2bd-587fac21aa35

Also, in the implementation, we are specifically using either "draft" or "published" regardless of the product status translation:
https://github.com/medusajs/medusa/blob/2d74ec256ff348979eebc45d09d06b1a743b9b6b/packages/admin-ui/ui/src/hooks/use-edit-product-actions.tsx#L132

Can you confirm, that we are attempting to update the product status in the same place?

**Comment by olivermrbl** [comment]
I found the issue. You can't update status through the list overview. Thanks for filing the issue!

We will fix this right away and include it in this week's release.
