### ISSUE TITLE
Commerce Modules and API Reference docs not in sync /// search endpoint

### ISSUE THREAD

**Issue by bytkb** [medusajs/medusa#5392]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In the developer docs under the e-commerce modules there is a mistake. The according page: https://docs.medusajs.com/modules/products/storefront/show-products#search-products. Here it says that the search item should be passed as a query parameter but when trying this doesn't work. If you go to the API Reference page: https://docs.medusajs.com/api/store#products_postproductssearch, you can see the query should be sent in the body as json. These docs are not in line with each other. I first tried to send the query through the params and I thought the enpoint didn't work. 

I don't know if there are more places where the dev docs and the API reference are not in line but seems good to fix it and check other parts of the docs.

### How can this issue be resolved?

1. Make the docs in line with each other

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for opening this issue! I'll open a PR to fix this issue. Feel free to open an issue if you find other errors.
