### ISSUE TITLE
API Ref(admin): Issue in User Login (JWT)

### ISSUE THREAD

**Issue by nadeemdevs** [medusajs/medusa#5402]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

invalid endpoint `/admin/token`

### How can this issue be resolved?

shouldnt it be `/admin/auth/token`

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for opening this issue! You're correct, it should be `/admin/auth/token`. I'll open a PR to fix it.
