### ISSUE TITLE
Klarna does not work

### ISSUE THREAD

**Issue by Mohamad-Jaallouk** [medusajs/medusa#5405]
I follow the docs to install Klarna. When I go to payment a circle icon spins without instead of showing payments methods.

**On client side I get:** 
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
xhr.js:210     POST http://localhost:9000/store/carts/cart_01HD0Z64RFP12FDTDCQ2NFNAS9/payment-sessions 500 (Internal Server Error)

**On server side I get:**
 response: {
    status: 400,
    statusText: 'Bad Request',
    headers: {
      date: 'Wed, 18 Oct 2023 09:01:31 GMT',
      'content-type': 'application/json',
      'content-length': '489',
      connection: 'close',
      server: 'envoy',
      'cache-control': 'max-age=0, no-cache, no-store',
      pragma: 'no-cache',
      'klarna-correlation-id': '5b1e1b8e-9cc9-4c90-93a9-d73ff205bf76',
      'render-time': '0',
      'x-envoy-upstream-service-time': '10',
      'strict-transport-security': 'max-age=31536000; includeSubDomains',
      'x-ratelimit-limit': '40, 40;w=1',
      'x-ratelimit-remaining': '37',
      'x-ratelimit-reset': '1'
    },
    config: {
      url: '/checkout/v3/orders',
      method: 'post',
      data: '{"merchant_data":"cart_01HD108C27Y3RS2GBMK8APRZ7E","locale":"en-US","order_lines":[{"name":"Medusa Sweatpants","tax_rate":0,"quantity":1,"unit_price":3350,"total_amount":3350,"total_tax_amount":0,"total_discount_amount":0},{"name":"PostFake Standard","quantity":1,"type":"shipping_fee","unit_price":1000,"tax_rate":0,"total_amount":1000,"total_tax_amount":0}],"billing_address":{"email":"E","street_address":"K","street_address2":"","postal_code":"6","city":"E","country":"se"},"purchase_country":"SE","order_amount":4350,"order_tax_amount":0,"purchase_currency":"EUR","merchant_urls":{"terms":"<YOUR_KLARNA_TERMS_URL>","checkout":"<YOUR_KLARNA_CHECKOUT_URL>","confirmation":"<YOUR_KLARNA_CONFIRMATION_URL>","push":"http://localhost:9000/klarna/push?klarna_order_id={checkout.order.id}","shipping_option_update":"http://localhost:9000/klarna/shipping","address_update":"http://localhost:9000/klarna/address"},"selected_shipping_option":{"id":"so_01HCZ224FAT2JBCWHDT1F8WF8R","name":"PostFake Standard","price":1000,"tax_amount":0,"tax_rate":0},"shipping_options":[{"id":"so_01HCZ224FAT2JBCWHDT1F8WF8R","name":"PostFake Standard","price":1000,"tax_amount":0,"tax_rate":0},{"id":"so_01HCZ224KF9VPCENBJJD6W748B","name":"PostFake Express","price":1500,"tax_amount":0,"tax_rate":0}]}',
      headers: [Object],
      auth: [Object],
      baseURL: 'https://api.klarna.com',.......

### System information

Medusa version (including plugins): Medusa 1.17.1, Klarna 1.3.10
Node.js version: 18
Database: 15
Operating system: windows, I tried on Ubuntu as well
Browser (if relevant): Chrome

**Comment by Mohamad-Jaallouk** [comment]
After some debugging, I resolved several issues, but it still does not work.

In klarna-provider.js, I added console.log for easier debugging:

async createPayment(cart) {
    try {
        const order = await this.cartToKlarnaOrder(cart);

        return await this.klarna_
            .post(this.klarnaOrderUrl_, order)
            .then(({ data }) => data);
    } catch (error) {
        console.log(error.response.data.error_messages);
        // this.logger_.error(error);
        // throw error;
    }
}

The output was:

> [
>   'Bad value: merchant_urls.shipping_option_update (must be a valid https URI), merchant_urls.address_update (must be a valid https URI), merchant_urls.confirmation (must be a valid http or https URI), merchant_urls.terms (must be a valid http or https URI), merchant_urls.confirmation (Invalid URI), merchant_urls.checkout (must be a valid http or https URI)'
> ]

I added the missing fields and used ngrok, as I'm developing on http://localhost. Now, those problems have been resolved. However, it's still not functioning properly. The new error I received is:

> error:   Cannot read properties of undefined (reading 'session_data')
> TypeError: Cannot read properties of undefined (reading 'session_data')
>     at PaymentProviderService.<anonymous> (C:\dev\my-medusa-store\node_modules\@medusajs\medusa\dist\services\payment-provider.js:295:77)
>     at step (C:\dev\my-medusa-store\node_modules\@medusajs\medusa\dist\services\payment-provider.js:48:23)
>     at Object.next (C:\dev\my-medusa-store\node_modules\@medusajs\medusa\dist\services\payment-provider.js:29:53)
>     at fulfilled (C:\dev\my-medusa-store\node_modules\@medusajs\medusa\dist\services\payment-provider.js:20:58)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> I've cleaned up the gramm

**Comment by Mohamad-Jaallouk** [comment]
Rolling back to Medusa 1.17.0 solved the problem. However, Klarna is not implemented in the NextJS storefront. Here is an example of the errors in the storefront:

```
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'title')

Source
src\modules\checkout\components\payment-container\index.tsx (57:56) @ title

  55 | <div className="flex flex-col text-left">
  56 |   <h3 className="text-base-semi leading-none text-gray-900">
> 57 |     {PaymentInfoMap[paymentSession.provider_id].title}
     |                                                ^
  58 |   </h3>
  59 |   <span className="text-gray-700 text-small-regular mt-2">
  60 |     {PaymentInfoMap[paymentSession.provider_id].description}
```

**Comment by tm-fd** [comment]
Any updates on this?

**Comment by tm-fd** [comment]
They should call it klarna checkout not Klarna payment because all api calls are towards Klarna checkout API

**Comment by tm-fd** [comment]
it should be called klarna checkout plugin because they are using klarna checkout api
