### ISSUE TITLE
Subscribe button out of div and maki irresponsive website

### ISSUE THREAD

**Issue by techmannih** [medusajs/medusa#5413]
Hello 
I found an issue in your website in which "subscribe" button is out of div for many pixels 320pz to 340px
Which make irresponsive website 
I want to work on this issue ...assign me this issue 
![Screenshot_2023-10-19_01-17-37](https://github.com/medusajs/medusa/assets/125847751/67718795-f0d2-49fd-9a41-2309784440a5)

**Comment by shahednasser** [comment]
Thank you for reporting this issue, but I couldn't reproduce it. I'll forward it to our internal team though. Our main website is not open for contributions at the moment.
