### ISSUE TITLE
401 responses on /app/login

### ISSUE THREAD

**Issue by yogo1212** [medusajs/medusa#5415]
### Describe the bug

The login page on my fresh install of medusa loops.
Medusa is running in production mode, the page is served through nginx using TLS, the cookie secret is set, the domain is not on the public suffix list.
The POST to `/admin/auth` returns 200 but the subsequent GET returns `401 Unauthorized` (see screenshot below).

### System information

Medusa version (including plugins): 7.0.1
Node.js version: 18
Database: postgres
Operating system: Linux
Browser (if relevant):-

### Steps to reproduce the behavior

1. Go to '/app/login'
2. Enter credentials
3. Click 'Continue'

### Expected behavior

Successful logon.

### Screenshots

![medusa](https://github.com/medusajs/medusa/assets/5165324/5a5d4dcd-0dfa-4205-b754-3dd05119cc19)

**Comment by pepijn-vanvlaanderen** [comment]
Your response headers do not contain a Set-Cookie, which should be the case. You probably need to change your server config to pass the proper headers.

**Comment by yogo1212** [comment]
@pepijn-vanvlaanderen Hi and thanks for your reply :-)

There's a nginx between me and the server.
I've reduced the location definition to this:

```
location / { 
  proxy_pass http://docker_medusa;

  proxy_set_header Host $host;
  proxy_set_header X-Forwarded-Protocol $scheme;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header Forwarded "$proxy_add_forwarded;proto=$scheme;host=$host";

  proxy_redirect off;
  proxy_buffering off;
}
```

**Comment by yogo1212** [comment]
By 'server', do you mean nginx or Medusa?

Regarding nginx, I found this:
https://github.com/medusajs/medusa/issues/1305

> I started investigating the headers set by the gateway and it seems that it uses a [Forwaded](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded) Header rather than the more standard [X-Forwarded-Proto](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto) header.

How could I check if this is an issue with express?

**Comment by yogo1212** [comment]
I found the cause:

Express uses the `X-Forwarded-Proto` header to (quietly) decide whether or not to send the cookie - and if it's not present, it assumes `http` (resulting in no cookie being send).
I started off using the `Forwarded` header specified in rfc7239 (2014), assuming it would be well-supported nine years later.
I then altered and stripped down the nginx configuration step-by-step until I arrived at (what I thought was) the bare minimum configuration required by the documentation.
It still didn't work, which is why I opened this issue.

But I made a mistake while copy typing: `X-Forwarded-Protocol` != `X-Forwarded-Proto`.

**Comment by kim-hanho** [comment]
To someone who might be struggling with this issue. After nearly two days with this problem by changing nginx settings, it turned out that running `npm run start` is executed in develop mode instead of **production**. I strongly recommend doing `console.log(process.env.NODE_ENV)` and make sure your server is running on **production**.

**Comment by ramish18** [comment]
> To someone who might be struggling with this issue. After nearly two days with this problem by changing nginx settings, it turned out that running `npm run start` is executed in develop mode instead of **production**. I strongly recommend doing `console.log(process.env.NODE_ENV)` and make sure your server is running on **production**.

This worked for me
