### ISSUE TITLE
Docs(Code Issue): Code Issue in /modules/carts-and-checkout/backend/add-payment-provider

### ISSUE THREAD

**Issue by 99power** [medusajs/medusa#5424]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Getting an error when using the example or following the docs for the payment processor: Non-abstract class 'MyPaymentProcessor' does not implement inherited abstract member 'updatePaymentData' from class 'AbstractPaymentProcessor'.

### How can this issue be resolved?

1. Add updatePaymentData to the Docs and the example code
2. Remove updatePaymentData to be mandatory (not sure what it does)

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for reporting this! The `updatePaymentData` is missing from the documentation. Will open a PR to add it shortly.

In the meantime, you can check [how it's implemented in the Stripe plugin](https://github.com/medusajs/medusa/blob/b38f73726dfc908b334b2a91a091a83d2dfd1dd5/packages/medusa-payment-stripe/src/core/stripe-base.ts#L289) as an example. Sorry for the inconvenience!
