### ISSUE TITLE
Admin product update broken

### ISSUE THREAD

**Issue by FaZeRs** [medusajs/medusa#5426]
### Describe the bug

On new Medusa release it's not possible to update any Product field without passing `status` field

### System information

Medusa version (including plugins): 1.17.2
Node.js version: 20.5
Database: PostgreSql
Operating system: Ubuntu
Browser (if relevant):

### Steps to reproduce the behavior

Can see code example bellow of how to reproduce this error

### Expected behavior

It should be possible to update any product field without need to add `status` field as it was before release

### Screenshots

![Screenshot from 2023-10-19 20-53-44](https://github.com/medusajs/medusa/assets/9529341/20d3687e-bbd6-44a9-b4e1-373248949e80)

### Code snippets

```js
import { useAdminUpdateProduct } from "medusa-react";
const { mutate } = useAdminUpdateProduct(1);
mutate({ weight: 100 });
```

**Comment by olivermrbl** [comment]
Nice catch, thanks for filing the issue. I've opened #5428 fixing it.

This is only an issue with the generated type, so until this has landed in a release, you'll have to ignore the TS error.
