### ISSUE TITLE
Docs(Code Issue): Code Issue in /plugins/payment/stripe

### ISSUE THREAD

**Issue by JaydenWN** [medusajs/medusa#5427]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

https://docs.medusajs.com/plugins/payment/stripe

Under custom storefront 'implement the workflow'

isStripeAvailable is checking for processor_id, cart.payment_sessions uses provider_id

### How can this issue be resolved?

1. Replace session.processor_id with session.provider_id
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for submitting this issue! Will open a PR to fix it
