### ISSUE TITLE
error:   relation "public.products" does not exist

### ISSUE THREAD

**Issue by Chou-ZBG** [medusajs/medusa#5445]
We are looking to develop an e-commerce website on Medusa, and our current version is 1.12.0. Following the official Upgrade Guides step by step, we attempted to upgrade it to the latest version, 1.17.x.

However, when trying to fetch products or orders in the Medusa admin, we encountered the following issue: "error: relation 'public.products' does not exist." Additionally, when clicking on products or orders, the content was not displayed.

Based on my interpretation of the error message, I renamed the "product" table in the database to "products." This allowed the content to be displayed when clicking on "products." But, a new issue arose: "error: column ProductCollection__ProductCollection_products.customAttribute does not exist."

I suspect that this is related to database migrations, but I'm not sure where I went wrong. Can someone please help me understand what might be the problem, and how to resolve all these issues?

**Comment by olivermrbl** [comment]
I highly recommend not to tamper with the core database schemas, especially their naming. It looks like your renaming of the product table has led to cascading errors across the code base. Modifying core schemas also makes it very hard for us to resolve issues, as they can be very specific to your customizations.

Can I get you to outline what changes you've made, so I can try to help from here? 

I'll close the issue, since this is a wont-fix, but I'll try to get back if you provide me with more information.

**Comment by Chou-ZBG** [comment]
Hi Oli,

I hope this email finds you well. I wanted to thank you for closing issue
#5445 on GitHub. Your prompt action is appreciated.


Allow me to rephrase the current situation: I'm attempting to develop a
project using MedusaJS. I was previously using version 1.12.0, and now I
want to upgrade it to version 1.17.2. To do this, I referred to the Upgrade
Guides on the official website and followed the version upgrade steps. What
I mean is, I executed the upgrade steps as described, first upgrading to
1.13.0, then to 1.15.0, followed by 1.16.0, and finally 1.17.0. I also ran
the migrations as recommended. However, I encountered some issues in the
end.


So, I opened an issue to check if others have faced a similar situation.
Later, I attempted something else. I used the Medusa CLI to create a
completely new project, configured it with the database address, pointing
it to the existing database. Then, I re-ran the migrations. As of now, it
seems like there are no apparent issues. Could you please confirm if this
approach is correct? If you have any better suggestions, please let me know.

Best regards,
Max Chou

Oli Juhl ***@***.***> 于2023年10月23日周一 14:03写道：
