### ISSUE TITLE
Stripe plugin: Switching from test to live mode will make existing customers unable to start a payment session

### ISSUE THREAD

**Issue by Alexnortung** [medusajs/medusa#5451]
### Describe the bug

The stripe plugin saves a stripe customer id on the medusa customer, this can cause an issue when switching from test to live mode.
The problem is that the plugin does not create a new stripe customer if the customer id is set on the medusa customer. So when the payment intent is made, stripe will give an error that the customer does not exist, but exists in the test workspace. 

### System information

Medusa version (including plugins): 1.17.2
Node.js version: 18
Database: postgres
Operating system: Linux

### Steps to reproduce the behavior

1. Set stripe account to test mode
2. install stripe plugin
3. create a payment session for test@example.com and place an order
4. switch stripe account to live mode
5. try to create a payment session for test@example.com and receive a bad request error.

### Expected behavior

I would expect the plugin to fallback to creating a new customer in stripe, whether the customer already exists in test mode or not.

**Comment by olivermrbl** [comment]
This is a known "issue" with testing the Stripe plugin in test + production mode using the same database. We won't fix this any time soon. You are more than welcome to suggest and contribute with a better way of handling this.

Until then, you can update metadata on all customers with raw SQL if you don't store anything else of importance in there.
