### ISSUE TITLE
Variants key not available in products object after adding categories

### ISSUE THREAD

**Issue by patxiworks** [medusajs/medusa#5478]
## Bug report

Adding the categories relation when retrieving products using the MedusaJS client throws an error.

### Describe the bug

I tried to include the `categories` key in the product object that is generated by the MedusaJS client using the following code:

`const { products, count, offset } = await medusaClient.products.list({
    expand: "categories",
    limit: 12,
    offset: pageParam,
    ...queryParams,
  })`

This code worked successfully but the `variants` key was no longer available in the product list and threw an error where it was referenced.

### System information

Medusa version : 1.17.2
Node.js version: 18.18
Operating system: MacOS 12.4

### Steps to reproduce the behavior

Run the above code and try to call products.variants

### Expected behavior

The `variants` key should remain when the `categories` key is added

### Screenshots

Before adding categories relation:
![image](https://github.com/medusajs/medusa/assets/8594521/a436fc8f-e861-431b-88e3-6a21bd4e3ce2)

After adding categories relation (no `variants` key):
![image](https://github.com/medusajs/medusa/assets/8594521/a34b8f7e-1d4f-47fa-8f2a-053256be8bbf)

Sorry if the images are too large!

**Comment by chemicalkosek** [comment]
Not only variants are missing but all other relations. That's because when you use `expand` it only expands the relations mentioned.

Follow the docs about expanding multiple relations: [https://docs.medusajs.com/api/store#expanding-fields](https://docs.medusajs.com/api/store#expanding-fields)

```javascript
await medusaClient.products.list({ expand: "variants,categories" })
```

**Comment by patxiworks** [comment]
Thanks @chemicalkosek. It doesn't seem very intuitive though. But I guess I'll have to go through the docs more closely.
