### ISSUE TITLE
Cannot read custom attribute to extended Entity

### ISSUE THREAD

**Issue by camfeghali** [medusajs/medusa#5485]
### Describe the bug
Cannot see `customAttribute` in the dashboard after going through the steps highlighted in the [docs](https://docs.medusajs.com/development/entities/extend-entity#response-fields)

### System information

Medusa version: @medusajs/admin: "7.1.5"
Node.js version: 16.0.0
Database: postgresql

### Steps to reproduce

1. `src/models/product.ts`
```
import { Column, Entity } from 'typeorm';
import {
  Product as MedusaProduct,
} from '@medusajs/medusa';

@Entity()
export class Product extends MedusaProduct {
  @Column()
  customAttribute: string;
}
```

2. `src/index.d.ts`
```
export declare module "@medusajs/medusa/dist/models/product" {
  declare interface Product {
    customAttribute: string;
  }
}
```

3. `src/migrations/1698418847400-AddProductCustomAttribute.ts`
```
import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddProductCustomAttribute1698418847400
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      'ALTER TABLE "product"' + ' ADD COLUMN "customAttribute" text'
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      'ALTER TABLE "product" DROP COLUMN "customAttribute"'
    );
  }
}

```

4. `src/loaders/extend-product-fields.ts`
```
export default async function () {
  const imports = (await import(
    '@medusajs/medusa/dist/api/routes/store/products/index'
  )) as any;
  imports.allowedStoreProductsFields = [
    ...imports.allowedStoreProductsFields,
    'customAttribute',
  ];
  imports.defaultStoreProductsFields = [
    ...imports.defaultStoreProductsFields,
    'customAttribute',
  ];
}
```

I then ran `yarn build` and `npx medusa migrations run`. I see the `customAttribute` column in my database.
**I did not** extend the validator, because I understand that it's a request validator, while currently I just want to read the new attribute.

### Expected behavior

I expect: 

- At least that my newly `customAttribute` property is available in the product response when I print it in the console of the Admin UI.
- There is a `customAttribute` field that shows up somewhere in the product detail page of the Admin UI

### Screenshots

<img width="408" alt="Screenshot 2023-10-28 at 10 25 33" src="https://github.com/medusajs/medusa/assets/5472504/1f0e76c2-3859-4145-827e-f58f695e9cc4">

I'm probably missing something, but can't figure out what. Any help would be much appreciated.

**Comment by shahednasser** [comment]
@camfeghali From my understanding you're trying to retrieve the custom attribute from the admin, but you've extended the default fields of the store endpoint. You should extend the fields in `packages/medusa/src/api/routes/admin/products/index.ts` instead.

**Comment by camfeghali** [comment]
Hey @shahednasser thanks for getting back to me, you're right, I am  trying to retrieve the custom attribute from the admin.

I changed the loader to be the following, and still I don't see changes in the Admin UI:

```
export default async function () {
  const imports = (await import(
    '@medusajs/medusa/dist/api/routes/admin/products/index'
  )) as any;

  imports.allowedAdminProductsFields = [
    ...imports.defaultAdminProductFields,
    'customAttribute',
  ];
  imports.defaultAdminProductsFields = [
    ...imports.defaultAdminProductFields,
    'customAttribute',
  ];
}
```

I noticed that the file path you mention has `packages/medusa` prepended to it; while my project starts with `src/api/routes/...`, why is that ?

**Comment by shahednasser** [comment]
> I noticed that the file path you mention has packages/medusa prepended to it; while my project starts with src/api/routes/..., why is that ?

No I just copied the path from this monorepository 😄 your path is correct.

I just tested it out, and the issue seems the names of the imports in the loader. Basically, your loader file should be like this:

```
export default async function () {
  const imports = (await import(
    '@medusajs/medusa/dist/api/routes/admin/products/index'
  )) as any;

  imports.defaultAdminProductFields = [
    ...imports.defaultAdminProductFields,
    'customAttribute',
  ];
}
```

The admin index file exports `defaultAdminProductFields` instead of `defaultAdminProductFields`. It also doesn't export an `allowedAdminProductsFields` variable.

Let me know if this works

**Comment by camfeghali** [comment]
@shahednasser it worked! thank you very much. Have a nice day :)
