### ISSUE TITLE
Cannot POST Admin API route - Error 404

### ISSUE THREAD

**Issue by AlexTechNoir** [medusajs/medusa#5488]
Hello!

I'm trying new API routes in Medusa 1.17.2

I've created `api/admin/test/route.ts`:
```typescript
import type { MedusaRequest, MedusaResponse, } from "@medusajs/medusa"

export const POST = async (req: MedusaRequest, res: MedusaResponse) => {
  console.log('hit!', req)
  const { body, user } = req
  const { userId } = user
  
  if (!userId) {
    return res.status(401).json({ message: "Not authorized" })
  }

  const { key } = body

  if (!key) {
    return res.status(404).json({ message: "No data specified", code: "NO_DATA" })
  }

  res.json({
    message: "check",
  })
}
```

My fetching code on Admin:
```javascript
    try {
      const r = await fetch("http://localhost:9000/admin/test", {
        method: "POST",
        credentials: "include",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          key: "value",
        }),
      })
      if (!r.ok) {
        const err = await r.text()
        throw {
          err_msg: `Error ${r.status}`,
          err_obj: err,
        }
      }
      const data = await r.json()
    } catch (err) {
      console.error("Err: ", err)
    }
```

I run `npm run build` and I see test route in `dist` folder, but when I fetch it returns HTML response with message "Cannot POST /admin/test".

![Untitled](https://github.com/medusajs/medusa/assets/43852391/1bd865f9-8436-4704-9865-3b992682379a)

I don't see my console.log in `route.ts`, so it looks like it doesn't see my route.

Can anyone help me?

**Comment by shahednasser** [comment]
Just to clarify, you created the route in `src/api/admin/test/route.ts` right? (I don't see `src` in the path you've mentioned).

**Comment by AlexTechNoir** [comment]
Yes, it is in `src`

**Comment by shahednasser** [comment]
I just tested it out, and I can't reproduce the issue. Can you make sure you're using the latest Medusa version?

**Comment by AlexTechNoir** [comment]
My dependencies:
```json
    "dependencies": {
        "@medusajs/cache-inmemory": "^1.8.8",
        "@medusajs/event-bus-local": "^1.9.6",
        "@medusajs/medusa": "^1.17.2",
        "@medusajs/medusa-cli": "^1.3.21",
        "medusa-file-cloudinary": "^1.0.2",
        "medusa-fulfillment-manual": "^1.1.38",
        "medusa-interfaces": "^1.3.7",
        "medusa-payment-manual": "^1.0.24",
        "medusa-payment-stripe": "^6.0.3",
        "typeorm": "^0.3.17",
        "uuid": "^9.0.1"
    },
```

**Comment by shahednasser** [comment]
Thanks for clarifying! @kasperkristensen can you look into this?

**Comment by mingeee** [comment]
@AlexTechNoir your { key } in `api/admin/test/route.ts` is undefined.

have you tried converting the body to json?

**Comment by AlexTechNoir** [comment]
No need, the docs [say](https://docs.medusajs.com/development/api-routes/create#parse-request-body-parameters) it's auto parsed if the incoming request has `"Content-Type": "application/json"` header, which I attached

The key is undefined, because `body` from destructured `req` object flashes red and says `Property body does not exist on type MedusaRequest.ts(2339)` - I have yet to solve this, but I don't think it's connected as the route seems not being hit at all

**Comment by olivermrbl** [comment]
@AlexTechNoir, what OS are you on?

**Comment by AlexTechNoir** [comment]
Windows 10

**Comment by olivermrbl** [comment]
> Windows 10

There's a known issue with API Routes on Windows. We are working on a [fix](https://github.com/medusajs/medusa/pull/5497).

Any chance you could give this snapshot a spin?

```
yarn add @medusajs/medusa@1.17.3-snapshot-20231030105059
```

**Comment by AlexTechNoir** [comment]
Yes, it works now, thanks!

The `body` is still highlighted red as non-existent, but its payload is visible through console

Also, its mandatory to append `return` keyword before `res` to return the response to Admin, contrary to docs' example

Can I use this fresh version or should I roll back to 1.17.2 and wait for stable release?

**Comment by olivermrbl** [comment]
Great, thanks for testing! cc @kasperkristensen 

We'll release 1.17.3 later today. Up to you what you want to do until then.
