### ISSUE TITLE
Authentication error for the Admin Dashboard in Elastic Beanstalk

### ISSUE THREAD

**Issue by lucaslrolim** [medusajs/medusa#5490]
### Describe the bug

I have a similar problem to the one described in [issue 5415](https://github.com/medusajs/medusa/issues/5415). I have followed all the steps to configure Medusa in Elastic Beanstalk, but it still presents the following problem:

- My POST auth request to login into the Admin Dashboard is returning 200, but  without the attribute "Set Cookie". Because of that, it become impossible to effectively login and use the admin dashboard.

I tried to customize my Ngix in the way below, but it doesn't make any effect to solve the issue:

```
location / {
	proxy_pass          http://127.0.0.1:8080;
        proxy_http_version  1.1;

        proxy_set_header    Connection          $connection_upgrade;
        proxy_set_header    Upgrade             $http_upgrade;
        proxy_set_header    Host                $host;
        proxy_set_header    X-Real-IP           $remote_addr;
        proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto   $scheme;
        proxy_pass_request_headers on;
        proxy_cookie_path / /;
        proxy_redirect off;
        proxy_buffering off;
}
```

### System information

Medusa version (including plugins): Core 1.17.2 and Medusa Admin 7.1.5
Node.js version: 18
Database: postgres
Operating system: Linux
Browser (if relevant):-

### Steps to reproduce the behavior

Go to '/app/login'
Enter credentials
Click 'Continue'
See error

### Expected behavior

Successful authentication

**Comment by NicolasGorga** [comment]
Hello, could you share how you were able to initialli deploy the backend in EBS? I am trying different things out and it is always failing to deploy the source bundle for me (doing it from the console)
