### ISSUE TITLE
401 Unauthorized when making requests to /admin/products

### ISSUE THREAD

**Issue by camfeghali** [medusajs/medusa#5509]
### Goal
I'm trying to programmatically access /admin routes from a script/postman using a api token as the authentication method.

Essentialy, I want to achieve what is highlighted in the docs [here](https://docs.medusajs.com/api/admin#products_getproducts).

I'm confused as to how I can get a `api_token`, given that it's different than the `publishable_api_token`.

Any help would be much appreciated.

**Comment by olivermrbl** [comment]
@camfeghali, you have to generate an API token (e.g. using uuid) and insert it in the database in your `user` record in column `api_token`. We are aware that this process is tedious. Admin support for managing tokens will likely be added in the future.
