### ISSUE TITLE
Medusa is not working with turborepos

### ISSUE THREAD

**Issue by Xxsource98** [medusajs/medusa#5544]
### Describe the bug
Hi, I am working on a turborepo project where I would like to use medusa with nextjs and some custom packages. First problem is that I can not start medusa app with ```turbo run dev```. Possible fix is disable hoisting in package.json for yarn workspaces for modules like @medusajs/admin, @medusajs/medusa... 
Okay it got fixed, but when I want to use custom package with my custom payment processor from package/ directory medusa isn't reading services from that. Subscribers works fine but I can not use my custom services like fulfillment service or payment processor. But when I put my custom package in node_modules in medusa project directory then it works fine. It seems like linking not working. 
Is medusa even "supported" by turborepos? Is there any ways to fix it?

### System information

Medusa version (including plugins): 1.17.2
Node.js version: 18.71.1
Database: postgres
Operating system: Ubuntu 22.04
Browser (if relevant): Brave

### Screenshots
![image](https://github.com/medusajs/medusa/assets/36642285/2883318a-3a93-4dbe-a2f6-a62cf23e624c)

**Comment by vholik** [comment]
I solved this problem when using yarn workspaces monorepository. `yarn add @medusajs/medusa` solved this problem

**Comment by sradevski** [comment]
Medusa v2.0 is supported with a turborepo setup (we have a couple running like that already). We won't be adding any support for v1 unfortunately, so I'll close this ticket.
