### ISSUE TITLE
Empty backend admin  during medusa server running -  blank admin page

### ISSUE THREAD

**Issue by Sylvesterx1** [medusajs/medusa#5549]
I running both storefront starter template and backend admin.

Frontend template working correct.

When I curl for admin backend, I see only:
[root@vim1999 ~]# curl http://localhost:7001
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/logo.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Medusa</title>
  <script defer src="/runtime~main.bundle.js"></script><script defer src="/main.bundle.js"></script><link href="/main.css" rel="stylesheet"></head>
  <body>
    <div id="root"></div>
  </body>
</html>
[root@vim1999 ~]#

When I curl for storefront, I correct see  full layout page.

For test Both I set proxy reverse to domain and now domain.com store front working perfect. But when I access to domain.com/admin I see blank page.  of course in browser code inspection visible above code from curl.

Medusa server is turned on correctly and does not return any errors. ngnix, Node 18.

Browser admin console inspection return this:
![image](https://github.com/medusajs/medusa/assets/35328055/1a3fcf7e-bcff-4d05-8d5f-dad07f7d1a27)

**Comment by Sylvesterx1** [comment]
Resolved. Wrong  reverse proxy endpoint. I put in  domain.com/admin but work  with domain.com I thnk need adjust in  configuration files to work in /admin

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
