### ISSUE TITLE
Failed to load resource: net::ERR_CONNECTION_REFUSED - localhost 

### ISSUE THREAD

**Issue by Sylvesterx1** [medusajs/medusa#5553]
1. NGINX
2. Medusa latest

I running both Medusa storefront and Medusa backend.

In Ngnix.conf I set reverse proxy for domain:
proxy_pass http://localhost:7001;

Now I can access to admin panel from browser by enter domain.com

Issue;
in code inspection application try fetch data from localhost instant of from domain:
Failed to load resource: net::ERR_CONNECTION_REFUSED
localhost:9000/admin/auth:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_REFUSED
localhost:9000/admin/store/:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_REFUSED
localhost:9000/admin/users:1 
        
       Failed to load resource: net::ERR_CONNECTION_REFUSED
localhost:9000/admin/auth:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_REFUSED
main.bundle.js:10 Error: Network Error
    at e.exports (main.bundle.js:1:53770)
    at v.onerror (main.bundle.js:1:48310)
f @ main.bundle.js:10
y @ main.bundle.js:10
(anonymous) @ main.bundle.js:10
Promise.catch (async)
v @ main.bundle.js:10
(anonymous) @ main.bundle.js:10
main.bundle.js:1 
        
        
       GET http://localhost:9000/admin/auth net::ERR_CONNECTION_REFUSED
(anonymous) @ main.bundle.js:1
e.exports @ main.bundle.js:1
e.exports @ main.bundle.js:1
c.request @ main.bundle.js:1
(anonymous) @ main.bundle.js:1
request @ main.bundle.js:1
getSession @ main.bundle.js:1
(anonymous) @ main.bundle.js:10
fetchFn @ main.bundle.js:10
v @ main.bundle.js:10
(anonymous) @ main.bundle.js:10
main.bundle.js:1 
        
        
    .....

How can I edit this API endpoint from localhost to domain ?

1) I try edit in  my-medusa-store (backend) .env file and set storecors = .., http://domain.com after rebuild app still  try get data from localhost.

**Comment by ceednee** [comment]
+1 
Same issue. I'm still looking for the solution.

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏

**Comment by himesh2005** [comment]
is the failed to fetch means, the backend is not fetching the data with mongodb as its not either saving too, the information of the user
