### ISSUE TITLE
Digital Products recipe example code bug

### ISSUE THREAD

**Issue by piereligio** [medusajs/medusa#5554]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The issue I'm reporting is all about the mime_type not getting captured by the digital product creation route and service, and for this the creation fails.

### How can this issue be resolved?

1. /src/api/admin/product-media/route.ts
Add mime_type parameter at line 41 and 52 (parameters of the const POST, and of productMediaService.create )
2. /src/services/product-media.ts
Add:  
   | "mime_type"  
at line 132 (parameters of async create(...) function )

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for pointing this out! Will open a PR to fix it.

**Comment by piereligio** [comment]
Thanks for the fast fix.

I've also noticed some other problems, one of which seems quite complex to solve (for me at least). It's at the ending of the recipe, the part of the delivery of the file. There are authentication problems in that part, and I honestly don't understand how to solve that.

How is the storefront API supposed to pass the authentication data to the backend API? This looks like it's the issue, but I'm struggling to find info about in the documentation. Should I use jwt? Or some other way?
