### ISSUE TITLE
CORS BLOCKED - Access to XMLHttpRequest at. No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by Sylvesterx1** [medusajs/medusa#5560]
Admin working 
Storefront issue.

When I access directly to link API in browser I see correct json result:
https://api.aray.pl/store/product-categories

`{"count":5,"offset":0,"limit":100,"product_categories":[{"id":"pcat_pants","created_at":"2023-11-05T12:17:49.508Z","updated_at":"2023-11-05T12:17:49.508Z","name":"Pants","description":"","handle":"pants","parent_category_id":null,"rank":0,"category_children":[],"parent_category":null},{"id":"pcat_shirts","created_at":"2023-11-05T12:17:49.508Z","updated_at":"2023-11-05T12:17:4..`

But from storefront in log console not possible fetch data from api endpoints to store:

foreach return error:
`Access to XMLHttpRequest at 'https://api.aray.pl/store/product-categories' from origin 'https://aray.pl' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by Sylvesterx1** [comment]
Not possible login to admin panel etc:
main.bundle.js:1 
        
        
       POST http://localhost:9000/admin/auth net::ERR_CONNECTION_REFUSED
(anonymous) @ main.bundle.js:1
e.exports @ main.bundle.js:1
e.exports @ main.bundle.js:1
c.request @ main.bundle.js:1
(anonymous) @ main.bundle.js:1
request @ main.bundle.js:1
createSession @ main.bundle.js:1
(anonymous) @ main.bundle.js:10
fn @ main.bundle.js:10
v @ main.bundle.js:10
t.createRetryer @ main.bundle.js:10
(anonymous) @ main.bundle.js:10
execute @ main.bundle.js:10
await in execute (async)
mutate @ main.bundle.js:10
(anonymous) @ main.bundle.js:10
(anonymous) @ <anon>:103
(anonymous) @ main.bundle.js:46
await in (anonymous) (async)
g @ main.bundle.js:14
r1 @ main.bundle.js:14
r7 @ main.bundle.js:14
(anonymous) @ main.bundle.js:26
iz @ main.bundle.js:26
(anonymous) @ main.bundle.js:26
iV @ main.bundle.js:26
(anonymous) @ main.bundle.js:26
fR @ main.bundle.js:26
rY @ main.bundle.js:14
iJ @ main.bundle.js:26
(anonymous) @ main.bundle.js:14
ob @ main.bundle.js:14
og @ main.bundle.js:14

**Comment by Sylvesterx1** [comment]
Resolved by add in .env store cors with https

**Comment by shahednasser** [comment]
You can learn more about setting the CORS options in [our documentation](https://docs.medusajs.com/development/backend/configurations#admin_cors-and-store_cors). Will close this issue as it's resolved.
