### ISSUE TITLE
Setting decimal price on price list shows a NaN value

### ISSUE THREAD

**Issue by apu314** [medusajs/medusa#5565]
### Describe the bug

When creating a new price list, assign products and then assign prices for the products. If the price contains some decimals, like 9.79 (or 9,79), it shows NaN (not a number). To bypass this bug, i have to set the number to a non decimal value and then set the decimal value by setting it in the corresponding table in the database.

### System information

Medusa version (including plugins):
Dependencies:
- "@medusajs/admin": "^7.1.6"
- "@medusajs/cache-inmemory": "^1.8.9"
- "@medusajs/cache-redis": "^1.8.9"
- "@medusajs/event-bus-local": "^1.9.7"
- "@medusajs/event-bus-redis": "^1.8.10"
- "@medusajs/file-local": "^1.0.2"
- "@medusajs/medusa": "^1.17.3"
- "medusa-fulfillment-manual": "^1.1.38"
- "medusa-interfaces": "^1.3.7"
- "medusa-payment-manual": "^1.0.24"
- "medusa-payment-stripe": "^6.0.5"
- "medusa-plugin-wishlist": "^1.1.43"
DevDependencies:
- "@medusajs/medusa-cli": "^1.3.21"
- "babel-preset-medusa-package": "^1.1.19"
Node.js version: v18.18.0
Database: PostgreSQL 15.1
Operating system: Mac OS Sonoma 14.0
Browser (if relevant): Brave 1.50.120

### Steps to reproduce the behavior

1. Go to Prices
2. Click on A created pricelist (or create a new one)
3. Add a new product or edit a product list previously added
4. Set a decimal price (in Euros)
5. See error (NaN)

### Expected behavior

The decimal price should show and saved in database correctly as a decimal

### Screenshots

![CleanShot 2023-11-05 at 19 19 14@2x](https://github.com/medusajs/medusa/assets/3430301/754fa9f7-f2f1-4246-bc86-bfccc3f9fc70)

**Comment by kasperkristensen** [comment]
Hi @apu314, thanks for bringing it to our attention. 

I've opened a PR to address the issue #5566. In the meantime you can avoid the issue by changing your locale, to something that uses `.` as the decimal separator, such as the US, so that you won't have to manually fix the values in your DB.

**Comment by apu314** [comment]
Hi @kasperkristensen, thank you for your reply and opening a PR with the fix.

I've seen that the library used for that input, [react-currency-input-field](https://github.com/cchanxzy/react-currency-input-field), recently updated the version.
Here is the version that probably solves this: https://github.com/cchanxzy/react-currency-input-field/releases/tag/v3.6.11

**Comment by Jean-EmmanuelP** [comment]
Not sure but I think there is another issue if i try typing 22.99 the amount value will be 2299
