### ISSUE TITLE
Unhandled Runtime Error: Error: Passing props on "Fragment"!  The current component <Listbox /> is rendering a "Fragment". However we need to passthrough the following props:   - defaultValue   - ref  You can apply a few solutions:   - Add an `as="..."` prop, to ensure that we render an actual element instead of a "Fragment".   - Render a single element as the child so that we can forward the props onto that element.

### ISSUE THREAD

**Issue by jiarenlim** [medusajs/medusa#5567]
## Bug report
Unhandled Runtime Error: Error: Passing props on "Fragment"!  The current component <Listbox /> is rendering a "Fragment". However we need to passthrough the following props:   - defaultValue   - ref  You can apply a few solutions:   - Add an `as="..."` prop, to ensure that we render an actual element instead of a "Fragment".   - Render a single element as the child so that we can forward the props onto that element.

### Describe the bug
this issue occured when i "npm run dev" just after my installation with this command : pnpm dlx create-medusa-app@latest --db-url [mydburllink] --with-nextjs-starter, then i just went to my admin panel and store front, but in the store front it will show this error 
![image](https://github.com/medusajs/medusa/assets/67389513/f2b74c4b-a0b6-4659-a9fb-f4340efae28b)

### System information

Medusa version (including plugins):
Node.js version: v18.12.1
Database: supabase postgres
Operating system: windows 10
Browser (if relevant): chrome

### Steps to reproduce the behavior

1. use the command above
2. npm run dev
3. go to the store front

### Expected behavior

there is supposed to be no errors 

### Screenshots
![image](https://github.com/medusajs/medusa/assets/67389513/f2b74c4b-a0b6-4659-a9fb-f4340efae28b)

### Code snippets
just the codes untouched of using the command above (after npm run dev)

**Comment by samwh1te** [comment]
Same here. Getting this error just going through the regular `pnpm create medusa-app@latest` and it shows every page on the storefront except the homepage. Should be an issue on the nextjs-starter-medusa repo though? Same error when trying out a few other versions of create-medusa-app too

**Comment by shnoman97** [comment]
Just pass the `as={"span"}` in `<ListBox>` on line 56. 
<img width="840" alt="image" src="https://github.com/medusajs/medusa/assets/60171953/90ce5601-cbea-44c1-b257-b195dc0ef368">

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
