### ISSUE TITLE
vercel frontend deployment error

### ISSUE THREAD

**Issue by Jamyisverycool** [medusajs/medusa#5573]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

![image](https://github.com/medusajs/medusa/assets/97376423/678c4ead-e112-471d-ba1a-dacbfa379342)
waited an entire hour and doesn't deploy.. help

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by woniuxingdong** [comment]
@Jamylaureys I've met this before. For a workaround, just add the environment variable like this indicating:

![image](https://github.com/medusajs/medusa/assets/5960481/af9c725b-40eb-4c62-8381-7fb1f9eeced7)

And the value could be arbitrary, as it will not be used if you're not using product module.

![image](https://github.com/medusajs/medusa/assets/5960481/565b1e7f-f2ef-4b98-8e37-ab862c42d133)

For end user, it's really misleading even they don't use the product module, but still need to set this environment variable.

**Comment by Soapistic** [comment]
If you're not using the Serverless Product Module, either delete the src/app/api directory(it's safe) or exclude it in .gitignore

**Comment by shahednasser** [comment]
Details around solving this are now included in [this documentation](https://docs.medusajs.com/deployments/storefront/deploying-next-on-vercel#storefront-preparations)
