### ISSUE TITLE
Missing `metadata` Attributes in Product Category

### ISSUE THREAD

**Issue by bqst** [medusajs/medusa#5598]
### Describe the bug

`metadata` (jsonb) attributes are available for Product Collections and Tags but not for Product Categories. 

### System information

System information
Medusa version (including plugins): 1.17.3
Node.js version: 18.17.1
Database: postgres (PostgreSQL) 14.9
Operating system: MacOS
Browser (if relevant): Chrome

### Steps to reproduce the behavior

1. Navigate to the Product Category section in the MedusaJS admin panel.
2. Attempt to add or update metadata (jsonb) attributes for a category.
3. Observe that there is no option or field to add or update metadata for categories, unlike in product collections or tags.

### Expected behavior

I expected to find metadata (jsonb) attributes in the Product Category, similar to what is available in product collections and tags. This feature is essential for extending the capabilities of categories, such as adding custom data or attributes that are specific to certain categories.

### Additional context

Having metadata for categories is crucial for custom implementations that rely on extended information tied to each category. This feature would bring Product Categories in line with other entities in MedusaJS and enhance the overall flexibility of the platform.

**Comment by olivermrbl** [comment]
Thanks @bqst – this is great. Appreciate the contribution. We'll push to get this included in the next release :)

**Comment by olivermrbl** [comment]
Closing this issue, as feature requests belong in our GitHub Discussions.
