### ISSUE TITLE
Error starting server TypeError: (0 , modules_sdk_1.registerModules) is not a function

### ISSUE THREAD

**Issue by stanley-tarce** [medusajs/medusa#5605]
## Bug report
Error starting Medusa Backend, error response is `TypeError: (0 , modules_sdk_1.registerModules) is not a function`
### Describe the bug
Not sure what happened but when I tried to open Medusa server on my local, I kept on getting this error specified. Earlier, I was able to run the service with no problems. I just noticed the problem when I deployed it on our production layer and then suddenly it also happened to my local (after refreshing the packages).
Cannot start Medusa Server `medusa start` or `medusa develop` due to the error stated below
### System information
MacOS
### Medusa version (including plugins):
```json
{
  "dependencies": {
    "@medusajs/admin": "7.1.2",
    "@medusajs/cache-inmemory": "^1.8.8",
    "@medusajs/cache-redis": "^1.8.8",
    "@medusajs/event-bus-local": "^1.9.6",
    "@medusajs/event-bus-redis": "^1.8.9",
    "@medusajs/file-local": "^1.0.1",
    "@medusajs/medusa": "1.17.0",
    "@medusajs/medusa-js": "6.0.4",
    "@medusajs/ui": "2.0.0",
    "medusa-core-utils": "^1.2.0",
    "medusa-file-s3": "^1.3.1",
    "medusa-fulfillment-manual": "^1.1.38",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.24",
    "medusa-payment-stripe": "^6.0.3",
    "medusa-payment-stripe-paynow": "^1.0.0",
    "medusa-plugin-algolia": "^0.2.20",
    "medusa-plugin-variant-images": "^1.0.4",
    "medusa-react": "^9.0.4"
  },
  "devDependencies": {
    "babel-preset-medusa-package": "^1.1.13"
  }
}
```
### Node.js version: 
18.17.1
### Database: 
PostgresQL
### Operating system: 
MacOS

### Steps to reproduce the behavior
1. Just simply run medusa start or medusa develop

### Expected behavior
You should see this error: 
<img width="1058" alt="Screenshot 2023-11-10 at 10 46 20 PM" src="https://github.com/medusajs/medusa/assets/79818058/b7704ace-9b1e-48d9-8de3-69c83af0fdf7">

EDIT: 
I followed the solution from this issue https://github.com/medusajs/medusa/issues/5606#issue-1987845158 and it worked on my end.

**Comment by IDIRYACINE** [comment]
I had the same issue plus missing swc-loader from the dev dependencies . this error was caused by a missing @medusajs/modules-sdk . It seems like some bad commit is causing all of these issues . at this point the medusa default starter is just broken

**Comment by stepmixx** [comment]
I have the same issue in my deploy on railway it was working good and after setting a custom domain this suddenly happened, I tried putting the @medusajs/modules-sdk in dependencies, resolutions and both. And none worked.

![image](https://github.com/medusajs/medusa/assets/54951161/35c943ff-b878-4d44-a40a-664a4bada323)

**Comment by IDIRYACINE** [comment]
> I have the same issue in my deploy on railway it was working good and after setting a custom domain this suddenly happened, I tried putting the @medusajs/modules-sdk in dependencies, resolutions and both. And none worked.
> 
> ![image](https://user-images.githubusercontent.com/54951161/282212046-35c943ff-b878-4d44-a40a-664a4bada323.png)

Try using yarn for installing dependencies on the project/monorepo this fixed some issues and missing dependencies for me (was using bun, then pnpnm before trying going purely with yarn)

**Comment by ishaiktaher** [comment]
Same issue while starting `medusa develop` 

`error:   Error starting server
TypeError: (0 , modules_sdk_1.registerModules) is not a function
    at /Users/my-medusa-store/node_modules/@medusajs/medusa/dist/loaders/index.js:148:82
    at step (/Users/my-medusa-store/node_modules/@medusajs/medusa/dist/loaders/index.js:56:23)
    at Object.next (/Users/my-medusa-store/node_modules/@medusajs/medusa/dist/loaders/index.js:37:53)
    at fulfilled (/Users/my-medusa-store/node_modules/@medusajs/medusa/dist/loaders/index.js:28:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
`

**Comment by IDIRYACINE** [comment]
I got everything to work properly using bun and turborepo following as mentioned in [#4532 ](https://github.com/medusajs/medusa/issues/4532#issuecomment-1700908959)

The issue is mainly occuring in monorepo settings . the solution is just a workaround until a proper fix is put in place 

creating a symlink to the monorepo node_modules fixes the issue 
`ln -s <turborepo-root>/node_modules/  <turborepo-root>/apps/medusa/node_modules`
note : replace  turborepo-root with the full path to your monorepo folder 

I also made the following changes to the package.json
- replaced npm run with bun
- replaced  ./node_modules/.bin/rimraf  with rimraf

**Comment by FedeBatt** [comment]
@IDIRYACINE Not work's for me 😅

**Comment by olivermrbl** [comment]
@stanley-tarce, can I get you to try with the latest version of `@medusajs/medusa`?

**Comment by stanley-tarce** [comment]
@olivermrbl Updating to `"@medusajs/medusa": "1.17.4"` worked! I've also removed the resolutions in the `package.json` and it still runs fine.

**Comment by devonsydney** [comment]
This happened to me too. The strange thing is that it was on a fully working instance of Medusa on 1.17.3 that I was working with for days. Then suddenly the server crashed and redeploys stopped working, just got that error over and over. Upgrading to 1.17.4 worked but this is very concerning that something failed after-the-fact like this. Perhaps a module got upgraded with breaking changes that was only picked up on redeploy?

**Comment by montpc** [comment]
was debugging here same exact error

root@srv436783:/var/www/medusa-backend# npx @medusajs/medusa migrations run
[medusa-config] ⚠️ redis_url not found. A fake redis instance will be used.
[medusa-config] ⚠️ redis_url not found. A fake redis instance will be used.
TypeError: (0 , modules_sdk_1.registerModules) is not a function
    at getInternalModules (/var/www/medusa-backend/node_modules/@medusajs/medusa/dist/commands/utils/get-migrations.js:130:63)
    at getModuleMigrations (/var/www/medusa-backend/node_modules/@medusajs/medusa/dist/commands/utils/get-migrations.js:234:25)
    at getModuleSharedResources (/var/www/medusa-backend/node_modules/@medusajs/medusa/dist/commands/utils/get-migrations.js:273:57)
    at /var/www/medusa-backend/node_modules/@medusajs/medusa/dist/commands/migrate.js:84:82
    at step (/var/www/medusa-backend/node_modules/@medusajs/medusa/dist/commands/migrate.js:56:23)
    at Object.next (/var/www/medusa-backend/node_modules/@medusajs/medusa/dist/commands/migrate.js:37:53)
    at /var/www/medusa-backend/node_modules/@medusajs/medusa/dist/commands/migrate.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (/var/www/medusa-backend/node_modules/@medusajs/medusa/dist/commands/migrate.js:27:12)
    at getDataSource (/var/www/medusa-backend/node_modules/@medusajs/medusa/dist/commands/migrate.js:76:51)

**Comment by montpc** [comment]
it doesn't happen when using 'npx create-medusa-app@latest'

only when using yarn

just tested twice

**Comment by stepmixx** [comment]
> @stanley-tarce, can I get you to try with the latest version of `@medusajs/medusa`?

this worked for me too :DDD

**Comment by g-wills** [comment]
1.17.3 was not working, installed 1.17.4 and migrations ran

**Comment by victorlabigar** [comment]
This worked for me as well

> @stanley-tarce, can I get you to try with the latest version of `@medusajs/medusa`?

Yes, this worked for me as well!

**Comment by kb-0912** [comment]
I got the same problem but after upgrade to 1.17.4 the server can't be started without any error.

**Comment by mohammad1990** [comment]
I got the same problem after I upgraded to 1.18, I can't without an error. 
I get an error "Compiling Webpack heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch"

**Comment by genox** [comment]
I updated from 1.17 to 1.18 and now I get this error in deployments, too. The server doesn't start. I am using yarn to install and build.

**Comment by olivermrbl** [comment]
@genox, can I get you to ensure all your Medusa packages are running on the latest version and report back?

The issue occurs because of conflicting versions of dependencies between packages. We are actively investigating how we can improve our release process to eliminate it entirely.

Will keep this thread updated.

**Comment by genox** [comment]
> @genox, can I get you to ensure all your Medusa packages are running on the latest version and report back?
> 
> The issue occurs because of conflicting versions of dependencies between packages. We are actively investigating how we can improve our release process to eliminate it entirely.
> 
> Will keep this thread updated.

Yes, making sure all versions align is what solved the issue for me. It seems like there was an older version in the lockfile due to one of my custom plugins.
