### ISSUE TITLE
GET Product request not showing "Categories", but should show them like it does for "Collections"

### ISSUE THREAD

**Issue by Jarpiino** [medusajs/medusa#5609]
### Describe the bug

/api/products/{handle} does not include category object.
(https://docs.medusajs.com/api/store#products_getproductsproduct)

### System information

System information
Medusa version (including plugins): 1.17.3
Node.js version: 20.9.0
Database: postgres (PostgreSQL) 16
Operating system: Windows 11
Browser (if relevant): Chrome

### Steps to reproduce the behavior

1. Fetch product details

### Expected behavior

Like showing product collections the response should be showing product categories.

**Comment by olivermrbl** [comment]
Are you using the `expand=categories` query param to include the categories on products? Categories are not part of the default relations.

Your request should look something like this:
```
GET /store/products/[product_id]?expand=categories
```

**Comment by Jarpiino** [comment]
I'm getting the details with Categories included when I fetch the product list.
![working with extra fetch](https://github.com/medusajs/medusa/assets/28261664/8cb66a06-d3de-4e90-9dba-47a7780c1afb)

But not with current product's api fetch.
![image](https://github.com/medusajs/medusa/assets/28261664/aaf3bb6a-6b2e-4292-8134-b904aca4418e)
![image](https://github.com/medusajs/medusa/assets/28261664/9b7785be-2116-47bb-861c-c79283aa0569)

**Comment by olivermrbl** [comment]
I imagine this is happening because you do not have the Product Module installed. You can enable it, however, this is an experimental feature, so please use it with caution.

If you want to continue with the standard setup, you'll need to add the `expand=` param to the request being fired on line 48. This should include categories on your products :)

**Comment by Jarpiino** [comment]
Thank you for trying to help, but I still cannot get it to work.
const { products } = await medusaRequest(
    "GET",
    "/products?expand=categories",
    {
      query: {
        handle,
      },
    }
  )

![image](https://github.com/medusajs/medusa/assets/28261664/b5a85c63-35d8-4346-88a5-89781cc5dc2f)

**Comment by chemicalkosek** [comment]
What you're doing now translates to two questionmarks in url, which won't work.
Look how medusaRequest is implemented: <https://github.com/medusajs/nextjs-starter-medusa/blob/6af7ca1d283c1d86ec9177d4ef4980faaad07395/src/lib/medusa-fetch/index.ts#L6>

```javascript
const { products ] = await medusaRequest(
  "GET",
  "/products",
  { 
    query: {
      handle,
      expand: ["categories"],
      }
    }
   )
   ```
   Or as one string without query object

**Comment by Jarpiino** [comment]
I've looked into how medusaRequest is implemented, but sadly even when I get the seemingly correct URL structure, it still does not work for me.
![image](https://github.com/medusajs/medusa/assets/28261664/4d132cf6-2f31-44f4-a875-bede33e779ee)
![image](https://github.com/medusajs/medusa/assets/28261664/63f8d630-ab04-49de-a966-1e8455ee33cf)

Also when trying your example I get url like this:
![image](https://github.com/medusajs/medusa/assets/28261664/a60154c2-23af-4b0c-a8f6-2a2960854e1a)

**Comment by chemicalkosek** [comment]
I have written it without testing. Seems `expand` is a string, not array. 
For your issue you'll need to include `variants` in expand. See: <https://docs.medusajs.com/api/store#expanding-fields>
Try like this:
```javascript
const { products ] = await medusaRequest(
  "GET",
  "/products",
  { 
    query: {
      handle,
      expand: "categories,variants,variants.options"
      }
    }
   )
```
Or the way you're doing.

**Comment by Jarpiino** [comment]
Now the URL is like that:
![image](https://github.com/medusajs/medusa/assets/28261664/38dd4ef5-4781-49fd-8235-7e6091d50f66)

And I'm getting another error:
![image](https://github.com/medusajs/medusa/assets/28261664/fa33c95f-f0f6-44db-b2aa-a61a563a1770)

**Comment by chemicalkosek** [comment]
It's because you have written:
`"categories,variants,variant.options"`
It's:
`"categories,variants,variants.options"`

**Comment by Jarpiino** [comment]
Finally it works, thank you guys so much. 
Now I found out that images were missing so I got that fixed aswell by adding images to the list:
`"categories,variants,variants.options,images,variants.prices,options.values,options"`

**Comment by Aliozzaim** [comment]
hey thanks it works now !  

```
export const getProductByHandle = cache(async function (
  handle: string,
): Promise<{ product: PricedProduct }> {
  const headers = getMedusaHeaders(['products'])

  const product = await medusaClient.products
    .list({ handle, expand: 'categories' }, headers)
    .then(({ products }) => products[0])
    .catch((err) => {
      throw err
    })

  return { product }
})
```
