### ISSUE TITLE
HEROKU DEPLOY at=error code=H10 desc="App crashed" method=GET path="/

### ISSUE THREAD

**Issue by FedeBatt** [medusajs/medusa#5610]
## Bug report
Error when i deploy my backend on Heroku at=error code=H10 desc="App crashed" method=GET path="/

### Describe the bug

Not sure what happened but when I tried to open Medusa on my Heroku URL , I kept on getting this error specified.

### System information
MacOS

Medusa version (including plugins):
"dependencies": { 
    "@medusajs/admin": "7.1.6",
    "@medusajs/cache-inmemory": "^1.8.9",
    "@medusajs/cache-redis": "^1.8.9",
    "@medusajs/event-bus-local": "^1.9.7",
    "@medusajs/event-bus-redis": "^1.8.10",
    "@medusajs/file-local": "^1.0.2",
    "@medusajs/medusa": "^1.17.4",
    "@tanstack/react-query": "4.22.0",
    "babel-preset-medusa-package": "^1.1.13",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "dotenv": "16.0.3",
    "express": "^4.17.2",
    "medusa-fulfillment-manual": "^1.1.38",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.24",
    "medusa-payment-stripe": "^6.0.5",
    "prism-react-renderer": "^2.0.4",
    "typeorm": "^0.3.16"
  },

### Expected behavior

When i Open app i expected Cannot get /

**Comment by olivermrbl** [comment]
@FedeBatt, does your Heroku log tell you anything? Unfortunately, I can't help you with the amount of details provided here. It can be caused by many things.

**Comment by FedeBatt** [comment]
@olivermrbl Finally i found the error, was a conection problem with Data base and/or Redis. So i checked my medusa-config.js and also check the database has conection.
