### ISSUE TITLE
Enhancement: Medusajs Backend + Vercel Integration

### ISSUE THREAD

**Issue by Archish27** [medusajs/medusa#5628]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Need medusajs backend integration with vercel. Vercel does provide connecting to postgresql store.

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
It's not possible to deploy the Medusa backend on Vercel. You can however create a PostgreSQL database in Vercel, then use its connection URL in a Medusa backend deployed on another hosting provider.

You can refer to this documentation for deployment options of the Medusa backend: https://docs.medusajs.com/deployments/server/
