### ISSUE TITLE
medusa-ui line numbers in CodeBlock component affects the position of code content

### ISSUE THREAD

**Issue by abmenzel** [medusajs/medusa#5639]
### Describe the bug

When line numbers are applied in the CodeBlock component and the number of lines is 10 or more, the code jumps based on the length of the line number.

### System information

Medusa UI 2.2.1

### Steps to reproduce the behavior

1. Add a CodeBlock component with a code snippet with more than 10 lines
2. See the bug

### Expected behavior

The code should be positioned based on the largest line number

### Screenshots

<img width="604" alt="Screenshot 2023-11-15 at 11 06 05" src="https://github.com/medusajs/medusa/assets/3914467/9932621a-d631-4476-b7ec-8180932a6284">

### Code snippets

```jsx
	<CodeBlock
		snippets={[
			{
				code: code,
				label: `
				medusa develop
				✔ Models initialized – 14ms
				✔ Repositories initialized – 35ms
				✔ Strategies initialized – 24ms
				✔ Modules initialized – 1ms
				✔ Database initialized – 654ms
				✔ Services initialized – 7ms
				✔ Express intialized – 5ms
				✔ Plugins intialized – 7ms
				✔ Subscribers initialized – 6ms
				✔ API initialized – 28ms
				✔ Server is ready on port: 9000
				`,
				language: 'bash',
			},
		]}>
		<CodeBlock.Header />
		<CodeBlock.Body />
	</CodeBlock>
```

**Comment by kasperkristensen** [comment]
Hi @abmenzel, I pushed a fixed and it should hopefully be part of the next release this week, in the meantime you can use this snapshot:

```
yarn add @medusajs/ui@2.2.2-snapshot-20231115122605
```

**Comment by abmenzel** [comment]
Neat @kasperkristensen thanks for the quick fix!
