### ISSUE TITLE
Yarn build is failing on develop branch

### ISSUE THREAD

**Issue by susaurabh-git** [medusajs/medusa#5659]
### Describe the bug

I get the following error when executing ``` yarn build ```

### System information

Medusa version (including plugins): develop branch
Node.js version: 19.6.1
Database: postgresql@16
Operating system: macOS Monterey
Browser (if relevant):

### Steps to reproduce the behavior

1. git clone code from develop branch
2. yarn install
3. yarn build
``` @medusajs/medusa:build: cache miss, executing d29cb75d616ae3c1
@medusajs/medusa:build: src/api/middlewares/index.ts(24,1): error TS2742: The inferred type of 'default' cannot be named without a reference to 'express-serve-static-core/node_modules/@types/qs'. This is likely not portable. A type annotation is necessary.
@medusajs/medusa:build: ERROR: command finished with error: command (/medusa/packages/medusa) yarn run build exited (1)
@medusajs/medusa#build: command (/medusa/packages/medusa) yarn run build exited (1)
``` 

### Expected behavior

build should be successful

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by xyzones** [comment]
@susaurabh-git I had similar issue and I solved with the following

```
git reset --hard HEAD # or clone the repo again
yarn set version 3.2.1
echo 'nmMode: "hardlinks-local"' >> ~/.yarnrc.yml      
yarn install
yarn build
```

output:
```
 Tasks:    72 successful, 72 total
Cached:    72 cached, 72 total
  Time:    2.188s >>> FULL TURBO
```                            

I hope this helps.

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
