### ISSUE TITLE
AwilixResolutionError: Could not resolve 'loggedInUser'.

### ISSUE THREAD

**Issue by nadeemdevs** [medusajs/medusa#5681]
### Describe the bug

```
AwilixResolutionError: Could not resolve 'loggedInUser'.

Resolution path: authService -> userService -> loggedInUser
```

I recently downgraded awilix package to v8.0.1, (https://github.com/medusajs/medusa/issues/5606#issuecomment-1814968027)
and after that I'm getting this error
I did follow this [doc](https://docs.medusajs.com/troubleshooting/awilix-resolution-error) but still the same error
tried upgrading awilix to v9.0.0, again I'm getting this [error](https://github.com/medusajs/medusa/issues/5606)

### System information
medusa: v1.17.4

**Comment by faris-mohamed10** [comment]
same here.

**Comment by oliwerhelsen** [comment]
Same for me. Have followed the docs and set the lifetime without success.

**Comment by nadeemdevs** [comment]
@olivermrbl hey, is there a way to fix this?
we can't deploy our backend and dashboard due to this error

**Comment by oliwerhelsen** [comment]
Hi @Nadeem34513,

Have you added the authenticate() middleware from MedusaJS? When adding new middlewares the custom one comes first in the list of middlewares. I solved it by doing this:

`{
 matcher: "/admin/products",
 middlewares: [authenticate(),registerLoggedInUser],
},`

**Comment by kburakf** [comment]
Hello everyone,

I am having the same issue for version `1.20.0`

I followed the official doc but it shows the same error anyway

- https://docs.medusajs.com/troubleshooting/awilix-resolution-error

even tho I added `LIFE_TIME` to related services, still getting the same `AwilixResolutionError` error for `loggedInUser`.

and I used that middleware in `index.ts` like this:

`  router.use(
    /\/admin\/[^(auth)].*/,
    cors(adminCors),
    authenticate(),
    registerLoggedInUser
  );`
  
  is there any solution so far?

**Comment by kburakf** [comment]
@Nadeem34513 **logged-in-user.ts** was under **middlewares** folder. i moved that folder to **api** folder and renamed it as **middlewares.ts** and now its working for me

**Comment by nadeemdevs** [comment]
> @Nadeem34513 **logged-in-user.ts** was under **middlewares** folder. i moved that folder to **api** folder and renamed it as **middlewares.ts** and now its working for me

Yep, this worked
Thanks!

**Comment by aminapatil** [comment]
@kburakf  after making above changes still facing same issue.Is there any other solution ?


`Could not resolve 'loggedInUser'.\n\nResolution path: userService -> loggedInUser`

![Screenshot from 2024-04-01 21-28-41](https://github.com/medusajs/medusa/assets/100195382/d9131c2e-83e1-4342-a5dc-bc856410e06e)

**Comment by Edan-Swipik** [comment]
> [aminapatil](/aminapatil)

the `middleware.ts file` needs to be `src/api/middleware.ts` not `src/api/middlewares/middleware.ts`

**Comment by oliwerhelsen** [comment]
Yes, as @Edan-Swipik said, middlewares.ts should live under api root. 

here is an example of loggedin user:

```
src/api/middlewares.ts

```
```
import type {
  MedusaNextFunction,
  MedusaRequest,
  MedusaResponse,
  MiddlewaresConfig,
  User,
  UserService,
} from "@medusajs/medusa";
import { authenticate } from "@medusajs/medusa";

const registerLoggedInUser = async (
  req: MedusaRequest,
  res: MedusaResponse,
  next: MedusaNextFunction
) => {
  let loggedInUser: User | null = null;

  if (req.user && req.user.userId) {
    const userService = req.scope.resolve("userService") as UserService;
    loggedInUser = await userService.retrieve(req.user.userId);
  }

  req.scope.register({
    loggedInUser: {
      resolve: () => loggedInUser,
    },
  });

  next();
};

export const config: MiddlewaresConfig = {
  routes: [
    {
      matcher: "/admin/*",
      middlewares: [authenticate(), registerLoggedInUser],
    },
  ],
};

**Comment by aminapatil** [comment]
- Thank you @Edan-Swipik  and @oliwerhelsen ,but after making above changes still getting same error .  Is there any changes required in `api/index.ts ` file?
Resolution path: authService -> userService -> SalesChannelService

its working in productService but not in other services

**Comment by raquelhortab** [comment]
why was this closed? we get AwilixResolutionError: Could not resolve 'container'

```
class FavouriteSolutionService extends TransactionBaseService {

    protected readonly loggedInCustomer: User | null

    constructor({ container }) {
        super(container);
        try {
            this.loggedInCustomer = container.loggedInCustomer
        } catch (e) {
            // avoid errors when backend first runs
        }
    }

    async listFavouriteSolutions() {


        const repo = this.activeManager_.getRepository(FavouriteSolution)
        return await repo.find({ where: { customer_id: this.loggedInCustomer.id } });
    }
}

```
