### ISSUE TITLE
Storefront currency does not change even after changing it in backend

### ISSUE THREAD

**Issue by andromeda1911** [medusajs/medusa#5684]
I have added INR currency in the backend and made it the default currency.
![image](https://github.com/medusajs/medusa/assets/21165701/9454fdd1-3fb3-4dd6-86a9-f6f68fa3a80c)

I have added INR prices to all the products in the backend

![image](https://github.com/medusajs/medusa/assets/21165701/fe6da7fe-c9f5-4e1a-87ea-8b1db4cdd327)

![image](https://github.com/medusajs/medusa/assets/21165701/b43cbb95-63dc-4179-b6fd-be0b4f359698)

As you can see in the storefront, I am still seeing price in Euros. How can I change this to show price in INR? Thanks.

Medusa version (including plugins): 1.3.21
Node.js version: v18.17.0
Database: postgres
Operating system: Windows
Browser (if relevant): Chrome

**Comment by olivermrbl** [comment]
Did you create a region with INR as a currency and select it in the storefront? :)

Read more about the Region <> Currency setup [in our documentation](https://docs.medusajs.com/user-guide/regions/).

**Comment by andromeda1911** [comment]
@olivermrbl I had to delete the EU region to get it to work. Not sure why that happened. But it works now thanks!

**Comment by riqwan** [comment]
Glad to hear it works, closing this for now. Feel free to reopen if you come across this again.

**Comment by aceassured** [comment]
> @olivermrbl I had to delete the EU region to get it to work. Not sure why that happened. But it works now thanks!

I had to delete the EU region to get it to work have you deleted in front or or medusa admin page andro because I'm also getting same error. please guide me on this.

**Comment by Bobata-constantlyafk** [comment]
Hello 👋, running Medusa v2.0

I changed the currency and region, but I receive this error when I load the storefront: 
Error: Region with id reg_01JBWHBTEYA995FZ46VPZT5BH4 not found when populating the pricing context

What I did:
- Made a new region and currency.
- Set new region and currency as default
- Deleted old region (Europe)
- Updated pricelist

![Screenshot 2024-11-10 112611](https://github.com/user-attachments/assets/829bf0a4-f3cf-4f34-8c3e-0d4e6cb9b75e)

**Comment by nigelLosi93** [comment]
Hi, getting the same error "Error: Region with id reg_01KC43XS2F2SE5EQ33Q4WK2XTS not found when populating the pricing context". I've tried resetting the regions but and tried creating a new pricelist, but the issue isn't going away. Can anybody provide additional details on how they solved the issue?
