### ISSUE TITLE
Unable to see the entire product name in admin order details

### ISSUE THREAD

**Issue by mortenengel** [medusajs/medusa#5700]
### Describe the bug

Naming this a bug might be an overstatement, but I wouldn't quite call it a feature request either. It's just a quality of life thing.
Our marketeers are unhappy with the admin order overview and the fact that they can not see the entire product name when it gets just a bit long (which most of the products are).
It is cut off by the class max-w-[185px] on the div container around

As I can see, the 185 can easily be made longer - but the span should also include a title attribute, to make it possible to see even longer texts in hover (like shown in the screenshot below)

### System information

Medusa version (including plugins): medusa-admin 7.1.7
Node.js version: not relevant
Database: not relevant
Operating system: not relevant
Browser (if relevant): not relevant 

### Steps to reproduce the behavior

1. Go to orders
2. Click on an order that has a product with a long name

### Expected behavior

Being able to see which product has been ordered without having to edit the order

### Screenshots

![image](https://github.com/medusajs/medusa/assets/38915779/8dec0277-c1b1-4dba-89af-98abd27305fd)

### Additional context

I don't mind doing the PR for this - but as making the container wider will have an impact on smaller screens, I would like to have a go from the designer whether that will be okay, or if we should go for multiple lines, or only have the title solution

**Comment by olivermrbl** [comment]
Thanks for reporting this @mortenengel. Will forward it to our design team and get back with possible ways of solving this :)

**Comment by mortenengel** [comment]
@olivermrbl any updates on this?
