### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '<method_name>')

### ISSUE THREAD

**Issue by nadeemdevs** [medusajs/medusa#5706]
### Describe the bug

I am getting this error whenever i use any other service inside user service

### System information

Medusa version (including plugins):
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by olivermrbl** [comment]
Happy to help, but please fill out the issue template :)
