### ISSUE TITLE
medusa-admin element overflow

### ISSUE THREAD

**Issue by SGFGOV** [medusajs/medusa#5722]
When the admin is resized, we get this error, the edit media button is overflowing, along with title text

![image](https://github.com/medusajs/medusa/assets/97059996/ac6b8e1b-7163-49af-867b-58f51e45cd09)

**Comment by kasperkristensen** [comment]
Hi @SGFGOV,

You have already opened this exact same issue here: [#5378](https://github.com/medusajs/medusa/issues/5378).

We are aware of it and it is something we are looking to improve on in the near future. 

Closing the issue as it is a duplicate.

**Comment by SGFGOV** [comment]
Oops.. didn't realize I had already opened it
