### ISSUE TITLE
Can not start Medusa application in monorepository (yarn workspaces)

### ISSUE THREAD

**Issue by vholik** [medusajs/medusa#5757]
## Bug report

Can not deploy Medusajs application with using yarn workspaces

### Describe the bug
We are using yarn workspaces. When we are deploying it using Dockerfile we get this error: 

```
[2023-11-28 17:22:00] yarn run v1.18.0
[2023-11-28 17:22:00] $ yarn workspace server start
[2023-11-28 17:22:01] warning package.json: "dependencies" has dependency "babel-preset-medusa-package" with range "^1.1.13" that collides with a dependency in "devDependencies" of the same name with version "^1.1.19"
[2023-11-28 17:22:01] $ cross-env npm run build && medusa start
[2023-11-28 17:22:01] /bin/sh: 1: cross-env: not found
[2023-11-28 17:22:01] error Command failed with exit code 127.
[2023-11-28 17:22:01] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[2023-11-28 17:22:01] error Command failed.
[2023-11-28 17:22:01] Exit code: 127
[2023-11-28 17:22:01] Command: /usr/local/bin/node
[2023-11-28 17:22:01] Arguments: /app/medusa/.yarn/releases/yarn-1.18.0.cjs start
[2023-11-28 17:22:01] Directory: /app/medusa/packages/server
[2023-11-28 17:22:01] Output:
```

Here is our Dockerfile
```
FROM node:20.9.0
WORKDIR /app/medusa

COPY package.json .
COPY yarn.* .

RUN apt-get update

RUN npm install npm@10.1.0 -g

RUN npm install @medusajs/medusa-cli@latest -g

RUN yarn install

COPY . .

CMD ["npm", "run", "start"]
```

and root package.json: 

```
{
  "private": true,
  "workspaces": {
    "packages": [
      "packages/*"
    ],
    "nohoist": [
      "**/@medusajs",
      "**/@medusajs/**",
      "**medusa**"
    ]
  },
  "scripts": {
    "start": "yarn workspace server start"
  }
}

```

### System information

Medusa version (including plugins): Medusa 1.17.4, medusa CLI latest
Node.js version: In docker file 20.9.0 (Tried on older versions problem still occur)
Database: Inrelevant
Operating system: Docker (works locally on my windows 11)
Browser (if relevant):

### Steps to reproduce the behavior

Use yarn workspaces with package using medusa js

### Expected behavior

![image](https://github.com/medusajs/medusa/assets/109461604/54f30e5f-3029-4b2a-a67d-9846ba92ded5)

### Screenshots

![image](https://github.com/medusajs/medusa/assets/109461604/43d4670a-ca16-4411-956e-7a093929bb5a)

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Here is my monorepository structure: 
```
packages.json
  packages/
    server/
      package.json 
    admin/
      package.json
```

Add any other context about the problem here

**Comment by genox** [comment]
Not a solution to your problem, but.. I was trying to run medusa as part of a workspaces project but was never able to run it well. I had to settle down with having the medusa-backend workspace treated as a regular project within the workspaces. This works by adding an empty yarn.lock and running yarn install and making sure it isn't picked up in the root's package.json `workspaces`. At least this allows larger setups to use monorepo structure even though the backend requires special treatment.

If someone found a way to make medusa backend play nicely within a yarn workspaces project, please post your solution.

**Comment by vholik** [comment]
I'll close this issue as I just forked medusa-ui repo and migrated from webpack to vite for better develop experience and newest Medusajs version.

**Comment by strawberry-choco** [comment]
> Not a solution to your problem, but.. I was trying to run medusa as part of a workspaces project but was never able to run it well. I had to settle down with having the medusa-backend workspace treated as a regular project within the workspaces. This works by adding an empty yarn.lock and running yarn install and making sure it isn't picked up in the root's package.json `workspaces`. At least this allows larger setups to use monorepo structure even though the backend requires special treatment.
> 
> If someone found a way to make medusa backend play nicely within a yarn workspaces project, please post your solution.

We solved it with `yarn workspaces focus <workspace-name> --production`, which only installs needed dependencies of that single package and copied `node_modules` into the docker image.
