### ISSUE TITLE
Can't add metadata when making HTTP request to update Order

### ISSUE THREAD

**Issue by camfeghali** [medusajs/medusa#5764]
### Describe the bug

When making a http POST to `/admin/orders/:id` to add/update the metadata prop, I receive a a 400 Bad Request response with the following body:
```
{
    "type": "invalid_data",
    "message": "property metadata should not exist"
}
```

### Steps to reproduce the behavior
This is a curl command to reproduce, change `<YOUR_DOMAIN>`, `<ORDER_ID>` and `<API_TOKEN>`.

```
curl --location '<YOUR_DOMAIN>/admin/orders/<ORDER_ID>?expand=%3Cstring%3E&fields=%3Cstring%3E' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'x-medusa-access-token: <API_TOKEN>' \
--header 'Authorization: Bearer {{bearerToken}}' \
--header 'Cookie: connect.sid=s%3AP3jcW1SnS5Q4wJsnlvYqb_Xa2D252veh.%2FEXZrE4lvTtxq%2Bcd5sWXwzWKhCBGUx55UsCjfR6vpsk' \
--data '{
    "metadata": {"b2b": true}
}'
```
### Expected behavior

I expect to be able to add metadata to an order.

### Screenshots

<img width="493" alt="Screenshot 2023-11-29 at 13 20 37" src="https://github.com/medusajs/medusa/assets/5472504/ea1db9c0-6db1-4194-9b43-5c661b12777a">

I understand that this may not be a bug but expected behavior. But then how can one add/update metadata on an order ? Or where should it be stored ? And why is there a prop in the AdminUI if I can't update it?

**Comment by rkmcdonnell** [comment]
I am having the same issue.  Does anyone know if this is expected behavior?  Updating metadata via HTTP would be extremely useful.

**Comment by kenchoong** [comment]
This still happen at July 2024. 
Not sure how can this be solve
