### ISSUE TITLE
Create cart for logged in customer using customer_id

### ISSUE THREAD

**Issue by hampusboas** [medusajs/medusa#5767]
### Describe the bug

Hi, the documentation says the following for the "create cart" endpoint, store API:

"If a customer is logged in, make sure to pass its ID or email within the cart's details so that the cart is attached to the customer."

But when i pass customer_id to post body i receive following error: 
`{"type":"invalid_data","message":"property customer_id should not exist"}`

is the property naming wrong? Our can i not create a cart for the customer?

### System information

Medusa version (including plugins): v1.18.1
Node.js version:
Database: postgres
Operating system: 
Browser (if relevant):

### Steps to reproduce the behavior

1. Create cart to store api passing customer_id.

### Expected behavior

Return a cart with customer_id set.

**Comment by kasperkristensen** [comment]
Hi @hampusboas,

You can't pass a customer ID to the create cart endpoint, and you don't have to. If the user is already logged in, when the cart is created, the user will automatically be associated with the cart.

This is handled here in the [endpoint handler](https://github.com/medusajs/medusa/blob/f802e2460f4eb6c9d120a24f371b4edb70a3caa1/packages/medusa/src/api/routes/store/carts/create-cart.ts#L158-L163).

The section of the docs you are referring to is for the case where the user creates a cart, and then logs in / signs up, here is the text in full:

"A customer might add items to their cart, then creates an account or log in. In that case, you should ensure that the cart is associated with the logged-in customer moving forward."

In that case, you should **update** the cart with the users id.

The flow for that in sudo code would be something along the lines of:

```ts
const authenticateCustomer = async (email: string, password: string) => {
  const { customer } = await medusaClient.auth.authenticate({
    email,
    password
  })

  const cartId = localStorage.getItem("medusa_cart_id")
  
  // If you have a cartId in local storage, you can update the cart with the customer id
  if (cartId) {
      await medusaClient.carts.update(cartId, {
        customer_id: customer.id,
      })
  }
}
```

**Comment by hampusboas** [comment]
@kasperkristensen Ok, thank you for the clarification =)!
