### ISSUE TITLE
Get original price from line item in cart response when a sale prices is active

### ISSUE THREAD

**Issue by hampusboas** [medusajs/medusa#5770]
## Bug report

Hi,

When i get my cart after adding some products to the cart. The cart items response objects original total price and total price is the same. Even the unit price is the same as the sale price. The price and calculations are correct but how can i get the original price? 

I'm currently logged in and using price lists for sale override. The current method for the price lists is set to sale. The cart object is linked to the logged in customer.

The returned original total should be the original price and not the sale price?

### System information

Medusa version (including plugins): v1.18.1
Node.js version:
Database: postgrees
Operating system:
Browser (if relevant):

### Steps to reproduce the behavior

1. Login to frontend
2. Create a new cart
3. Add a discounted product
4. Check cart response, items: for total, original total and unit price

**Comment by hampusboas** [comment]
Just a thought, do i need to fetch the variants on cart update and map variants in cart to get the original price? If this is the case it would be a nice feature if the carts line items could contain the original price...

**Comment by riqwan** [comment]
Hey @hampusboas,

If you've set the price list type to sale, the original total price and total price should be different, but if you set it to override, then you need to fetch the original price by manipulating the context in the pricing service with the variant ids you need the price for.

Fair warning though, there is some caching within the pricing service, do take a look to see if that cache is being invalidated when changing your price list from override to sale.

**Comment by hampusboas** [comment]
@riqwan , thank you for the reply, i will try again. Just to be clear this are the products in the cart object and not the product list. I solved it by adding the original price to the line item meta-data. This was just for display the original price in the cart.

**Comment by riqwan** [comment]
Ah, I see. Sorry I misunderstood @hampusboas 

The cart only stores the final value of the items, so what you did there is one solution you could use. 

If you look at the storefront, we basically query the products again before loading the cart to achieve this - https://next.medusajs.com/products/corporate-commando-throne (try adding this to cart)

**Comment by hampusboas** [comment]
Thank you @riqwan, i looked at the source code for the storefront and i see what they did there. But it would be very neat to have this implemented in the cart as default instead of the extra requests. On the other hand is it maybe to expensive 
for the cart recalculation/creation process to do this. 

It would also be nice if cart contained the total amount of the total discount the user received. Today the discount value in the cart is only applied from coupons.

**Comment by pepijn-vanvlaanderen** [comment]
@olivermrbl maybe good for a discussion to look into specifically the working of sale prices from the price lists. Additionally to the above thread, if you checkout an order afterwards it is also not clear where a discounted price comes from. A paper trail back to the price list or original money amount would be very convenient to have.
