### ISSUE TITLE
Currency error

### ISSUE THREAD

**Issue by devTugu** [medusajs/medusa#5771]
Describe the bug
MNT currency is not working

System information
Medusa version (including plugins): 1.18
Node.js version: 20.0.5
Database: postgres
Operating system: MacOs Sonoma
Browser (if relevant): All

Steps to reproduce the behavior
Enable and Select MNT as default currency.
Go to Medusa Admin > Products > New Product > Add variants > Pricing. Some error

<img width="1506" alt="Screenshot 2023-11-30 at 10 14 43" src="https://github.com/medusajs/medusa/assets/53719454/dbf8d9b1-8a46-4456-b03b-ba29654083c3">

**Comment by olivermrbl** [comment]
Will be added in #5489 :)
