### ISSUE TITLE
Minor confusion in product onboarding info

### ISSUE THREAD

**Issue by dbradmit** [medusajs/medusa#5779]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

While looking through the onboarding I noticed this sentence, "Products is Medusa represent the products you sell." This doesn't make sense. I think it might should read "Products _in_ Medusa...".

https://github.com/productinfo/medusa/blob/5c77029cb021690a4f617b83b4999ed55bf9dea1/www/apps/docs/content/admin/onboarding.md?plain=1#L1659 

### How can this issue be resolved?

I believe "_is_" might just need to be changed to "_in_".

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for the heads up! Will update this in both the starter default used to create the Medusa backend and in the docs
