### ISSUE TITLE
API Ref(store): Issue in Request Password Reset

### ISSUE THREAD

**Issue by harzh307** [medusajs/medusa#5783]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

the smtp email is not firing after setting up the medusa.config file as documented

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [x] I would like to fix this issue

**Comment by shahednasser** [comment]
Can you clarify more what plugin you're using? Depending on the plugin you're using, you may need to [create a subscriber](https://docs.medusajs.com/development/events/create-subscriber) that listens to the `customer.password_reset` event (learn more about the event [here](https://docs.medusajs.com/development/events/events-list#customer-events))

**Comment by shahednasser** [comment]
Closing this issue for lack of responsiveness. Feel free to reopen with more details.
