### ISSUE TITLE
Getting Cors on admin even after following the guide

### ISSUE THREAD

**Issue by oliwerhelsen** [medusajs/medusa#5784]
### Describe the bug

I am trying to create a session by using "useAdminLogin" from medusa-react. But I keep getting cors issue even though the configuration is done accordingly. 

### System information

Medusa version (including plugins):
Node.js version: v21.1.0
Database: Postgres 
Operating system: macOS Sonoma
Browser (if relevant): Chrome

### Steps to reproduce the behavior

1. Create dummy application
2. Setup medusa-react following the guide on medusa docs.
3. Try to login. 

### Expected behavior

Getting a session cookie.

### Screenshots

![Screenshot 2023-12-01 at 10 53 28](https://github.com/medusajs/medusa/assets/2570700/88a73878-b524-4e51-9d59-3edd693b3d3b)
![Screenshot 2023-12-01 at 10 53 05](https://github.com/medusajs/medusa/assets/2570700/0b34665f-2e4e-4675-94d1-969e140a6a4f)
![Screenshot 2023-12-01 at 10 52 24](https://github.com/medusajs/medusa/assets/2570700/26a9bd2b-76e9-46a1-8004-757dc65ba91d)
![Screenshot 2023-12-01 at 10 51 51](https://github.com/medusajs/medusa/assets/2570700/852db42d-0453-4fef-b1df-3fa7b5886049)
![Screenshot 2023-12-01 at 10 51 43](https://github.com/medusajs/medusa/assets/2570700/3f22d247-35df-4d61-8061-6a007a3f3646)

**Comment by bkvaiude** [comment]
@oliwerhelsen How did it worked for you? 
I have upgraded medusa version to 1.18.1 and latest medusa admin package. 
Now, I'm getting the same error! Please provide more insights on the fix!

**Comment by bkvaiude** [comment]
It is strange! I was using windows with ubuntu via WSL feature! After restarting the machine it started working!

**Comment by oliwerhelsen** [comment]
@bkvaiude nice that it worked out for you. My problem was that I didn't provide the protocol in my client application. MEDUSA_BASE_URL most be with http/-s 🤦
