### ISSUE TITLE
Typo in 'Delete Variant' Section

### ISSUE THREAD

**Issue by IdekDude** [medusajs/medusa#5787]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Found a typo in the 'Delete Variant' section. https://docs.medusajs.com/user-guide/products/manage#delete-a-variant

You can see that it says "Find the variant you want to duplicate in the Variants section.", this is incorrect and 'duplicate' should be replaced with 'delete'

### How can this issue be resolved?

1. Change 'duplicate' to 'delete

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for catching this! Feel free to fix it by [updating the page](https://github.com/medusajs/medusa/edit/develop/www/apps/docs/content/user-guide/products/manage.mdx)

**Comment by riqwan** [comment]
Thanks for the contribution @IdekDude! PR will be merged soon. :)
