### ISSUE TITLE
docs: incorrect sidebar element shown as selected on scroll

### ISSUE THREAD

**Issue by vasilemidrigan** [medusajs/medusa#5788]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

When clicking on Update Product we don't have the style effect of clicking the element as we have for other similar elements. I guess is a style issue, or something related to that. 

### How can this issue be resolved?

I guess it is somehow related to styling, or something like that. Not a big deal, or a big problem. Just noticed it. 

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
@vasilemidrigan thank you for submitting this issue. It's not clear what style effect you mean, can you elaborate? Is it an issue in the docs or somewhere else?

**Comment by vasilemidrigan** [comment]
> @vasilemidrigan thank you for submitting this issue. It's not clear what style effect you mean, can you elaborate? Is it an issue in the docs or somewhere else?

I'm not really sure if this is worth to see right now, but anyway. I was talking about the style effect from docs page https://docs.medusajs.com/api/admin#products_getproducts , can be other pages as well. When you click to select a specific functionality from the sidebar, like in the picture below: 

![dfdffff](https://github.com/medusajs/medusa/assets/85345009/32f1a847-77a1-470d-8e5f-08d639e33b57)


So we can see there is now selected effect when clicking Create a Product and List Products. I guess this is somehow related with styles. Anyway, maybe it doesn't seem really important right now. I don't know.

**Comment by shahednasser** [comment]
Got it, thanks for submitting this issue! Will look more into it

**Comment by shahednasser** [comment]
Closing this issue as it has been fixed.
