### ISSUE TITLE
Not able to get a store started 

### ISSUE THREAD

**Issue by dallin-humphrey** [medusajs/medusa#5799]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I have a vercel db set up and ready to go and I've been trying to set up a new project and I cant get anything to work. Either it doesn't attach to the vercel db link or when I try and run it without a db option it tells me this below:
I've upgraded using node 20.10.0

PS C:\Users\dalli\OneDrive\Desktop\opalvia> **npx create-medusa-app@latest --skip-db**
? What's the name of your project? opalvia
🚀 Starting project setup, this may take a few minutes.
√ Created project directory
√ Installed Dependencies
An error occurred while preparing project: Error: Command failed: **npm run build**
The filename, directory name, or volume label syntax is incorrect.

### How can this issue be resolved?

1. I really just want to be able to get a medusa project set up and all hosted on vercel. 
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by Kainkainkain** [comment]
I think `--skip-db` might be for devs who are going to manually connect it to an existing db they already have (like for some manual migration process they are doing) rather than being for developing db-less. 

I ended up running postgres in a docker container for local dev. 

Or you could connect it directly to your vercel db if you have its URL user and pass ready during the npx install.

**Comment by shahednasser** [comment]
@dallin-humphrey thank you for opening this issue. Regarding the vercel DB, as [explained in the docs](https://docs.medusajs.com/create-medusa-app#step-1-run-create-medusa-app), you have to provide the URL of the database with `--db-url`. 

As for the error you're facing, it seems like it could be a bug on Windows operating systems. For now, can you instead setup Medusa with the [medusa new command](https://docs.medusajs.com/development/backend/install)? You can then set the URL to your Vercel DB using the [database_url configuration](https://docs.medusajs.com/development/backend/configurations#database_url).

**Comment by shahednasser** [comment]
Closing this for lack of responsiveness. Feel free to reopen when you have more details.
