### ISSUE TITLE
NotificationService sendNotification not called?

### ISSUE THREAD

**Issue by inallermunde** [medusajs/medusa#580]
Hello there,

I'm having a problem with implementing a custom notification service. I followed the tutorial in the docs for creating a notification service and also looked at the source code for the sendgrid service.
Here's my code for the service:
```javascript
// src/services/nodemailer.js
import { NotificationService } from "medusa-interfaces";

class NodemailerService extends NotificationService {
    static identifier = "nodemailer";

    constructor({orderService}, options) {
        super();
        // This gets called
        this.options = options;
        this.orderService = orderService;
    }

    async sendNotification(eventName, eventData, attachmentGenerator) {
        console.log(eventName, eventData); // This doesn't get called
    }

    async resendNotification(eventName, eventData, attachmentGenerator) {
        console.log(eventName, eventData); // This also doesn't get called
    }    
}

export default NodemailerService;
```
And here for the subscriber:
```javascript
// src/subscribers/order.js
class OrderSubscriber {
    constructor({ notificationService }) {
        notificationService.subscribe("order.placed", "nodemailer");
        notificationService.subscribe("order.shipment_created", "nodemailer");
    }
}

export default OrderSubscriber;
```

As the comments suggest, the two calls to console.log don't seem to do anything, since I can't see anything in the terminal. I don't know where the problem could be, since both constructors are getting called (when I put a console.log in there, I get an output in the terminal).

Thanks in advance for helping me out!

**Comment by inallermunde** [comment]
Hi @olivermrbl,

thanks for the quick response, I was indeed running without redis. I uncommented the redis url in the config, and now it works! I appreciate the support of you guys.

**Comment by olivermrbl** [comment]
I'm glad it worked out! Let me know if anything else comes up 👍

**Comment by kspacja** [comment]
Should it work with `@medusajs/event-bus-local` as well, or only with redis one?

**Comment by Adityagndusharma** [comment]
> Should it work with `@medusajs/event-bus-local` as well, or only with redis one?

I have the same doubt.

**Comment by NicolasGorga** [comment]
Has anyone been able to make it work without Redus configured?
