### ISSUE TITLE
Migrations are broken on 1.18 with Multi Warehouse

### ISSUE THREAD

**Issue by alightinastorm** [medusajs/medusa#5821]
### Describe the bug

The Multi Warehouse module seems incompatible with newest 1.18

### System information

Medusa version (including plugins): 1.18.1 (upgraded from 1.17)
Node.js version: latest
Database: postgres
Operating system: macos
Browser (if relevant): --

### Steps to reproduce the behavior

1. Create medusa 1.17 app, apply multi warehouse migrations
2. Update to 1.18
3. run 1.18 migrations
4. Error initializing link modules. TypeError: Cannot read properties of undefined (reading 'foreignKey')

### Expected behavior

Expected it to migrate without error messages

### Additional context

Logging the joinerConfig from "link-modules" package - generateGraphQLSchema function:
```
{
  isLink: true,
  isReadOnlyLink: true,
  extends: [ { serviceName: 'inventoryService', relationship: [Object] } ]
}
```

Seems like there is some graphql linking being done, which fails?

**Comment by adrien2p** [comment]
weird, this method is supposed to check that
```
if (!joinerConfig.isReadOnlyLink) {
```

@olivermrbl could it be a changeset issue?/
@robodove can you share me what you have the following file `link-modules/dist/utils/generate-schema.js` in your node modules

**Comment by alightinastorm** [comment]
> weird, this method is supposed to check that
> 
> ```
> 
> if (!joinerConfig.isReadOnlyLink) {
> 
> ```
> 
> 
> 
> @olivermrbl could it be a changeset issue?/
> 
> @robodove can you share me what you have the following file `link-modules/dist/utils/generate-schema.js` in your node modules

upgrading to 1.20 magically solved it!

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
