### ISSUE TITLE
Unable to change shipping price type

### ISSUE THREAD

**Issue by Xxsource98** [medusajs/medusa#5824]
## Bug report
I can not change Price Type in Shipping Option from "Flat Rate" to "Calculated".

### Describe the bug
When I am trying to, I am getting notification with success message, but it is not updating. I have to recreate shipping option.
### System information

Medusa version (including plugins): 1.18.0
Node.js version: 18.17.1
Database: postgresql
Operating system: ubuntu 20.04
Browser (if relevant): brave

**Comment by oliwerhelsen** [comment]
Please provide the payload for your request and also the error message that you have been given.

**Comment by Xxsource98** [comment]
Hi, sorry for late answer. The problem is there is no any error on updating. It is like just not applying update in backend function. Even when I set "calculated" from "flat_rate" it is still sending "old" data of shipping option:

(When I wanted to change to "calculated" type on "test1" shipping option)
http://localhost:9000/admin/shipping-options/so_01HHCMHCYMYAF4SG32KAH1E80R
POST 200 OK
{"name":"test1","requirements":[],"admin_only":false,"amount":100,"metadata":{}}
