### ISSUE TITLE
Medusa Admin UI new product cannot edit price

### ISSUE THREAD

**Issue by pepijn-vanvlaanderen** [medusajs/medusa#5827]
### Describe the bug

When you create a new product and variant from the Medusa Admin UI, you are not able to edit prices.

### System information

Medusa version (including plugins): 1.18.1

### Steps to reproduce the behavior

1. Go to Products
2. Click on New product
3. Fill in dummy title
4. Click on Publish product
5. On the product edit detail page go to the Variants section, click the three dots and click on Add variant
6. Fill in dummy variant title, save and close
7. Click again on the three dots and click on Edit prices
8. There is no UI to edit the variant price.

### Expected behavior

Expected to see the currency input field for the variant

### Screenshots

![Scherm­afbeelding 2023-12-08 om 14 11 21](https://github.com/medusajs/medusa/assets/7559384/c9eec865-2960-4d8a-9e61-13c16e1ca7f0)

### Additional context

When using the product import strategy to load product variants and prices, the UI works as expected, it is only when there are no records for prices on a variant.

**Comment by olivermrbl** [comment]
If you click "View" in the top left, you can select the currencies you want to edit for the variant.

Perhaps "View" isn't the right term to use for this button. Will forward this to our team :)

**Comment by pepijn-vanvlaanderen** [comment]
Ah yes that shows the fields, thanks! Maybe preselecting (one of) the currencies would be an option.
