### ISSUE TITLE
Stripe credit card information not saved

### ISSUE THREAD

**Issue by iwbiz** [medusajs/medusa#5832]
### Describe the bug

I have setup my stripe plugin and try to do a test payment but the credit card information is not being saved after filling the fields and proceed to the review step. The card is being displayed as undefined and the Place Order button seems disabled. The console does not show any errors or network errors.

### System information
Medusa version (including plugins): @medusajs/medusa at ^1.18.1, @medusa/admin at ^7.1.8
Node.js version: 18.16.0
Database: postgres
Operating system: macOS
Browser (if relevant): Chrome

### Steps to reproduce the behavior
1. Add a product to cart
2. Go to checkout
3. Enter Stripe test credit card information (4242 4242 4242 4242)
4. Click on continue to preview
5. The credit card information displays as undefined
6. Clicking on the Place order button doesn't do anything (probably because the card information is undefined)

### Expected behavior
Should save the credit card information and the Place order button should continue the Stripe payment session.

### Screenshots
Entering the credit card information
![Screenshot 2023-12-08 at 10 39 41 PM](https://github.com/medusajs/medusa/assets/28648479/f5aece25-86ad-420b-bd82-54406641bc87)

After clicking continue to preview the credit card information seems not being saved
![Screenshot 2023-12-08 at 10 39 49 PM](https://github.com/medusajs/medusa/assets/28648479/4610adba-4cf8-430c-9481-60bda493343f)

**Comment by chrislaai** [comment]
I ran into the same issue and ended up going back to version 1.18.0, hoping it will be fixed in the next version.

**Comment by iwbiz** [comment]
> I ran into the same issue and ended up going back to version 1.18.0, hoping it will be fixed in the next version.

Hmm interesting. It didn't work for me. Did you downgrade anything on the store front as well?
