### ISSUE TITLE
How to add shipping method

### ISSUE THREAD

**Issue by manikmi** [medusajs/medusa#5839]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Trying to configure ship rocket into my medusa admin. Able to add the plugin using this documentation: https://medusajs.com/plugins/medusa-fulfillment-shiprocket/. But, cant add the shipping option, as no options in the Shipping Profile and Fulfillment method. Can somebody help in adding the Shipping profile and fulfillment method.

<img width="737" alt="image" src="https://github.com/medusajs/medusa/assets/797398/0bb51a79-45e0-47d8-a0a7-7a8f62aad332">
<img width="733" alt="image" src="https://github.com/medusajs/medusa/assets/797398/5d66fe0d-e31a-4e30-a333-ccdda674105e">

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by olivermrbl** [comment]
Have you added Shiprocket to the list of available fulfillment providers in the Region?

**Comment by manikmi** [comment]
Thanks @olivermrbl for the quick response. Yes, I did.
![image](https://github.com/medusajs/medusa/assets/797398/bd96f791-2717-4586-9018-bf1a1bfe9994)

**Comment by manikmi** [comment]
@olivermrbl / community, any ideas here? Is there some thing I am doing wrong?

**Comment by SAM-AEL** [comment]
> @olivermrbl / community, any ideas here? Is there some thing I am doing wrong?

same here.

![image](https://github.com/medusajs/medusa/assets/14927758/f6244803-aa31-459b-9e7d-a5dc1994f827)

![image](https://github.com/medusajs/medusa/assets/14927758/ffc02520-017e-49dd-91eb-3855cc45da77)

**Comment by manikmi** [comment]
> Have you added Shiprocket to the list of available fulfillment providers in the Region?

Yes, I did. Somehow, I did miss your response here @olivermrbl 
<img width="729" alt="image" src="https://github.com/medusajs/medusa/assets/797398/23a2744c-e9af-4fbf-b18c-3075a05b4598">

**Comment by manikmi** [comment]
@olivermrbl Any ideas / updates around this ticket?

**Comment by manikmi** [comment]
@olivermrbl  I see the label as "status: Needs more". What does this mean? Are you looking for inputs from me?

**Comment by olivermrbl** [comment]
@manikmi, can you provide a reproduction in a repository?

**Comment by manikmi** [comment]
> @manikmi, can you provide a reproduction in a repository?

Thankyou @olivermrbl sent you an invite to my repo.

**Comment by manikmi** [comment]
@olivermrbl are you able to access the repo?

**Comment by chintantis** [comment]
After delete region from admin dashboard i got this error "Region with reg_01HS0EM8CC393D77B45M3J64FK was not found"
in shipping option api , anyone have any solution ?

**Comment by shubhamchoudhary-2003** [comment]
You got this shop Rocket working

**Comment by rahatsayyed** [comment]
Having same issue. Selected Shiprocket
![image](https://github.com/medusajs/medusa/assets/70068895/eddf3fae-7b99-46c6-9b85-8b481f1833cb)

**Comment by rahatsayyed** [comment]
@manikmi @SAM-AEL 
if you still have the same issue then you need to fix env variables
I had same issue and now it is fixed

1. make sure you have created API user in shiprocket. `settings > api > add user`
2. add these details to env and make sure to enclose in quotes ` '...'` also add 7 digits channel id.
this should fix your error
