### ISSUE TITLE
missing property from validation schema in update product route

### ISSUE THREAD

**Issue by zakariaelas** [medusajs/medusa#584]
The `upc` field is missing from the `variants` [validation schema](https://github.com/medusajs/medusa/blob/develop/packages/medusa/src/api/routes/admin/products/update-product.js#L240-L288) in the `POST /admin/products/:product_id` route. 

We'd really appreciate it if someone can push a fix along with a unit test to ensure the change is reflected. This is the test [file](https://github.com/medusajs/medusa/blob/develop/packages/medusa/src/api/routes/admin/products/__tests__/update-product.js) you'll need to adjust.

Feel free to reach out if you need help!

**Comment by olivermrbl** [comment]
Closed #592
