### ISSUE TITLE
File Service - DigitalOcean Spaces documentation Out of date

### ISSUE THREAD

**Issue by Kainkainkain** [medusajs/medusa#5844]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary
[https://docs.medusajs.com/plugins/file-service/spaces](https://docs.medusajs.com/plugins/file-service/spaces)
These instructions are out of date, DigitalOcean have updated their screens leaving some ambiguity on some values. 
the endpoint isn't found where described and looks different to how documentation presents it. 

1
medusa doc example has a <YOUR_SPACE_ENDPOINT> being fra1.digitaloceanspaces.com

but in DigitalOcean now, the endpoint has two options:
Origin Endpoint 
and
CDN Endpoint 
and both have full URLS starting at HTTPS like so:
Origin https://spacenamehere.syd1.digitaloceanspaces.com
CDN  https://spacenamehere.syd1.cdn.digitaloceanspaces.com

So the documentation just needs to say:
use either origin or if using CDN option, use CDN
<YOUR_SPACE_ENDPOINT> should have "https://spacename" removed. 
E.g. For CDN endpoint https://spacenamehere.syd1.cdn.digitaloceanspaces.com
have 
SPACE_ENDPOINT=syd1.cdn.digitaloceanspaces.com

 

### How can this issue be resolved?

1. Someone that knows what happens with the values can update documentation to instruct what exactly goes into these values. 
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for opening this issue @Kainkainkain ! Will take some time to look into updating it
