### ISSUE TITLE
Product retrieval cpu intensive 1.8.1

### ISSUE THREAD

**Issue by mewulonu** [medusajs/medusa#5847]
### Describe the bug

The medusa retrieve product by handle query is cpu intensive, see sql below

SELECT "product"."id" AS "product_id", "product"."created_at" AS "product_created_at", "product"."updated_at" AS "product_updated_at", "product"."deleted_at" AS "product_deleted_at", "product"."title" AS "product_title", "product"."subtitle" AS "product_subtitle", "product"."description" AS "product_description", "product"."handle" AS "product_handle", "product"."is_giftcard" AS "product_is_giftcard", "product"."status" AS "product_status", "product"."thumbnail" AS "product_thumbnail", "product"."profile_id" AS "product_profile_id", "product"."weight" AS "product_weight", "product"."length" AS "product_length", "product"."height" AS "product_height", "product"."width" AS "product_width", "product"."hs_code" AS "product_hs_code", "product"."origin_country" AS "product_origin_country", "product"."mid_code" AS "product_mid_code", "product"."material" AS "product_material", "product"."collection_id" AS "product_collection_id", "product"."type_id" AS "product_type_id", "product"."discountable" AS "product_discountable", "product"."external_id" AS "product_external_id", "product"."metadata" AS "product_metadata", "product"."authorName" AS "product_authorName", "product"."isbn" AS "product_isbn", "product"."publisher" AS "product_publisher", "product"."publishedDate" AS "product_publishedDate", "product"."language" AS "product_language", "product"."book_type" AS "product_book_type", "product"."sales_rank" AS "product_sales_rank", "product"."age" AS "product_age", "product"."category_level" AS "product_category_level", "product"."category_list" AS "product_category_list", "product"."book_price" AS "product_book_price", "product__product_variants"."id" AS "product__product_variants_id", "product__product_variants"."created_at" AS "product__product_variants_created_at", "product__product_variants"."updated_at" AS "product__product_variants_updated_at", "product__product_variants"."deleted_at" AS "product__product_variants_deleted_at", "product__product_variants"."title" AS "product__product_variants_title", "product__product_variants"."product_id" AS "product__product_variants_product_id", "product__product_variants"."sku" AS "product__product_variants_sku", "product__product_variants"."barcode" AS "product__product_variants_barcode", "product__product_variants"."ean" AS "product__product_variants_ean", "product__product_variants"."upc" AS "product__product_variants_upc", "product__product_variants"."variant_rank" AS "product__product_variants_variant_rank", "product__product_variants"."inventory_quantity" AS "product__product_variants_inventory_quantity", "product__product_variants"."allow_backorder" AS "product__product_variants_allow_backorder", "product__product_variants"."manage_inventory" AS "product__product_variants_manage_inventory", "product__product_variants"."hs_code" AS "product__product_variants_hs_code", "product__product_variants"."origin_country" AS "product__product_variants_origin_country", "product__product_variants"."mid_code" AS "product__product_variants_mid_code", "product__product_variants"."material" AS "product__product_variants_material", "product__product_variants"."weight" AS "product__product_variants_weight", "product__product_variants"."length" AS "product__product_variants_length", "product__product_variants"."height" AS "product__product_variants_height", "product__product_variants"."width" AS "product__product_variants_width", "product__product_variants"."metadata" AS "product__product_variants_metadata", "product__product_variants__product__product_variants_prices"."id" AS "product__product_variants__product__product_variants_prices_id", "product__product_variants__product__product_variants_prices"."created_at" AS "b4a18719879aa86adb23436554889b9d58e6db1dcc62039a9d1672076a98ce8", "product__product_variants__product__product_variants_prices"."updated_at" AS "0fa0b28c0029e00242c8b9cddcb038681fda90eec22544a19e862a001d10835", "product__product_variants__product__product_variants_prices"."deleted_at" AS "e22d5d34925a15652cf0299a42680e8f4a74157ab28c02c9af8dccf941f2044", "product__product_variants__product__product_variants_prices"."currency_code" AS "99255d1c0257be2e15b18e47af52be7895569dc772ac03aec3ace7745179098", "product__product_variants__product__product_variants_prices"."amount" AS "bbe1c69a279c15ca38150d9335e84975f81b0569f9633acd14f3bbebb79c808", "product__product_variants__product__product_variants_prices"."min_quantity" AS "a7239d43a4d4a308972f30d30fb74a6f7a452af4e0130ab79bb96a07c6ac83b", "product__product_variants__product__product_variants_prices"."max_quantity" AS "a2d50d2b3b0936bc336b01619033310368313c92e0755f1dc25310d4aa937cc", "product__product_variants__product__product_variants_prices"."price_list_id" AS "30bd3807e78f7d2264ea77d677f01710da3c37cdac7ccf5033511982d560b2d", "product__product_variants__product__product_variants_prices"."variant_id" AS "6bba99b70a49484ecf0e0ce7181db60dc7aa1c2111908960f406d36d6837166", "product__product_variants__product__product_variants_prices"."region_id" AS "a85406cc26eb8421ed3f3641ccb83ab05b77244a25e2a2ec7fc5ba204100076", "product__product_variants__product__product_variants_options"."id" AS "product__product_variants__product__product_variants_options_id", "product__product_variants__product__product_variants_options"."created_at" AS "ccddb736f7c6d022880a5dcdca6fa24ea1e573422d2ab19757939481f6248eb", "product__product_variants__product__product_variants_options"."updated_at" AS "abcd4d3ccc37f2d91c9ec8e484102bdf32a123afd91639fbc86bb0f0057a004", "product__product_variants__product__product_variants_options"."deleted_at" AS "cc94c93187ae9299e9f3d52766b5c93338d5d3bfd50ef3c0f2dfc38fc6d2dc6", "product__product_variants__product__product_variants_options"."value" AS "2359fcf73cf6e64c5248e3391274ca41964cc3f2cdb3ff8ecce4fb5214976ce", "product__product_variants__product__product_variants_options"."option_id" AS "a44b336c2775c5100c26635f89c9e27d1171e9d81823370f8003406fbc66b4b", "product__product_variants__product__product_variants_options"."variant_id" AS "d1a0422e8f74c8ccae4b2458784437ae5568b07435f1c9eb80e0386427c549a", "product__product_variants__product__product_variants_options"."metadata" AS "64f72f841b161e9633acc5d93812771e2e3b243b3b7f52108d8a52c8692c2ee", "product__product_options"."id" AS "product__product_options_id", "product__product_options"."created_at" AS "product__product_options_created_at", "product__product_options"."updated_at" AS "product__product_options_updated_at", "product__product_options"."deleted_at" AS "product__product_options_deleted_at", "product__product_options"."title" AS "product__product_options_title", "product__product_options"."product_id" AS "product__product_options_product_id", "product__product_options"."metadata" AS "product__product_options_metadata", "product__product_options__product__product_options_values"."id" AS "product__product_options__product__product_options_values_id", "product__product_options__product__product_options_values"."created_at" AS "fae8b5b863b4f192893ed1e18e8ada6bcb36c9f68dbe823a8534a7aab0dadf7", "product__product_options__product__product_options_values"."updated_at" AS "dfee30cffed7309f5638e3003ab5aaec87683e09455119489c904913a135911", "product__product_options__product__product_options_values"."deleted_at" AS "dc05e190a3a4eef20ee13ff17a8bd7adee2ee823232abc86c2a31e7a05ce78a", "product__product_options__product__product_options_values"."value" AS "product__product_options__product__product_options_values_value", "product__product_options__product__product_options_values"."option_id" AS "8519a16e3c3e6ef79dd747a5d302f91eb1cd51624c31ebf7ef66b205cfaed3f", "product__product_options__product__product_options_values"."variant_id" AS "d7d4f7e1d984009e8bde35e884557b3881f5b7a8f5bd1c367ccc259c04f2b27", "product__product_options__product__product_options_values"."metadata" AS "a682d13d12c08b3784d48135c9da2a8ec239a9a13302a126050e4684fd49ff6", "product__product_images"."id" AS "product__product_images_id", "product__product_images"."created_at" AS "product__product_images_created_at", "product__product_images"."updated_at" AS "product__product_images_updated_at", "product__product_images"."deleted_at" AS "product__product_images_deleted_at", "product__product_images"."url" AS "product__product_images_url", "product__product_images"."metadata" AS "product__product_images_metadata", "product__product_tags"."id" AS "product__product_tags_id", "product__product_tags"."created_at" AS "product__product_tags_created_at", "product__product_tags"."updated_at" AS "product__product_tags_updated_at", "product__product_tags"."deleted_at" AS "product__product_tags_deleted_at", "product__product_tags"."value" AS "product__product_tags_value", "product__product_tags"."metadata" AS "product__product_tags_metadata", "product__product_collection"."id" AS "product__product_collection_id", "product__product_collection"."created_at" AS "product__product_collection_created_at", "product__product_collection"."updated_at" AS "product__product_collection_updated_at", "product__product_collection"."deleted_at" AS "product__product_collection_deleted_at", "product__product_collection"."title" AS "product__product_collection_title", "product__product_collection"."handle" AS "product__product_collection_handle", "product__product_collection"."metadata" AS "product__product_collection_metadata", "product__product_type"."id" AS "product__product_type_id", "product__product_type"."created_at" AS "product__product_type_created_at", "product__product_type"."updated_at" AS "product__product_type_updated_at", "product__product_type"."deleted_at" AS "product__product_type_deleted_at", "product__product_type"."value" AS "product__product_type_value", "product__product_type"."metadata" AS "product__product_type_metadata", "product__product_dubray_categories"."id" AS "product__product_dubray_categories_id", "product__product_dubray_categories"."created_at" AS "product__product_dubray_categories_created_at", "product__product_dubray_categories"."updated_at" AS "product__product_dubray_categories_updated_at", "product__product_dubray_categories"."external_code" AS "product__product_dubray_categories_external_code", "product__product_dubray_categories"."title" AS "product__product_dubray_categories_title", "product__product_dubray_categories"."slug" AS "product__product_dubray_categories_slug", "product__product_dubray_categories"."parent_id" AS "product__product_dubray_categories_parent_id", "product__product_dubray_categories"."metadata" AS "product__product_dubray_categories_metadata", "product__product_dubray_categories"."deleted_at" AS "product__product_dubray_categories_deleted_at", "product__product_warehouses"."id" AS "product__product_warehouses_id", "product__product_warehouses"."created_at" AS "product__product_warehouses_created_at", "product__product_warehouses"."updated_at" AS "product__product_warehouses_updated_at", "product__product_warehouses"."contentful_id" AS "product__product_warehouses_contentful_id", "product__product_warehouses"."name" AS "product__product_warehouses_name", "product__product_warehouses"."code" AS "product__product_warehouses_code", "product__product_warehouses"."archived" AS "product__product_warehouses_archived", "product__product_warehouses"."priority" AS "product__product_warehouses_priority", "product__product_warehouses"."delivery_info" AS "product__product_warehouses_delivery_info", "product__product_warehouses"."delivery_methods" AS "product__product_warehouses_delivery_methods", "product__product_warehouses"."deleted_at" AS "product__product_warehouses_deleted_at", "product__product_stocks"."id" AS "product__product_stocks_id", "product__product_stocks"."created_at" AS "product__product_stocks_created_at", "product__product_stocks"."updated_at" AS "product__product_stocks_updated_at", "product__product_stocks"."product_warehouse_id" AS "product__product_stocks_product_warehouse_id", "product__product_stocks"."product_id" AS "product__product_stocks_product_id", "product__product_stocks"."stock_level" AS "product__product_stocks_stock_level" FROM "product" "product" LEFT JOIN (SELECT * FROM "product_variant" "v" WHERE "v"."deleted_at" IS NULL ORDER BY "v"."variant_rank" ASC) "variants" ON "product"."id" = variants.product_id  LEFT JOIN "product_variant" "product__product_variants" ON "product__product_variants"."product_id"="product"."id" AND ("product__product_variants"."deleted_at" IS NULL)  LEFT JOIN "money_amount" "product__product_variants__product__product_variants_prices" ON "product__product_variants__product__product_variants_prices"."variant_id"="product__product_variants"."id" AND ("product__product_variants__product__product_variants_prices"."deleted_at" IS NULL)  LEFT JOIN "product_option_value" "product__product_variants__product__product_variants_options" ON "product__product_variants__product__product_variants_options"."variant_id"="product__product_variants"."id" AND ("product__product_variants__product__product_variants_options"."deleted_at" IS NULL)  LEFT JOIN "product_option" "product__product_options" ON "product__product_options"."product_id"="product"."id" AND ("product__product_options"."deleted_at" IS NULL)  LEFT JOIN "product_option_value" "product__product_options__product__product_options_values" ON "product__product_options__product__product_options_values"."option_id"="product__product_options"."id" AND ("product__product_options__product__product_options_values"."deleted_at" IS NULL)  LEFT JOIN "product_images" "product_product__product_images" ON "product_product__product_images"."product_id"="product"."id" LEFT JOIN "image" "product__product_images" ON "product__product_images"."id"="product_product__product_images"."image_id" AND ("product__product_images"."deleted_at" IS NULL)  LEFT JOIN "product_tags" "product_product__product_tags" ON "product_product__product_tags"."product_id"="product"."id" LEFT JOIN "product_tag" "product__product_tags" ON "product__product_tags"."id"="product_product__product_tags"."product_tag_id" AND ("product__product_tags"."deleted_at" IS NULL)  LEFT JOIN "product_collection" "product__product_collection" ON "product__product_collection"."id"="product"."collection_id" AND ("product__product_collection"."deleted_at" IS NULL)  LEFT JOIN "product_type" "product__product_type" ON "product__product_type"."id"="product"."type_id" AND ("product__product_type"."deleted_at" IS NULL)  LEFT JOIN "dubray_product_categories" "product_product__product_dubray_categories" ON "product_product__product_dubray_categories"."product_id"="product"."id" LEFT JOIN "dubray_product_category" "product__product_dubray_categories" ON "product__product_dubray_categories"."id"="product_product__product_dubray_categories"."product_category_id"  LEFT JOIN "product_warehouse_stock" "product_product__product_warehouses" ON "product_product__product_warehouses"."product_id"="product"."id" LEFT JOIN "product_warehouse" "product__product_warehouses" ON "product__product_warehouses"."id"="product_product__product_warehouses"."product_warehouse_id"  LEFT JOIN "product_warehouse_stock" "product__product_stocks" ON "product__product_stocks"."product_id"="product"."id" WHERE ( ("product"."handle" = $1) ) AND ( "product"."deleted_at" IS NULL )

### System information

Medusa version (including plugins): 1.8.1
TypeORM: 0.3.11
Node.js version: 16
Database: Postgres(4 cores)
Operating system: Amazon Linux

### Steps to reproduce the behaviour

call product retrieval in medusa engine(productService.retrieveByHandle etc.)

### Expected behavior

CPU usage during call

### Screenshots

If applicable, add screenshots to help explain your problem

![image](https://github.com/medusajs/medusa/assets/119587507/e0666e59-c818-4c9f-a126-27aea4a39608)

### Code snippets

await productService.retrieveByHandle(id, {
        relations: [...defaultStoreProductsRelations/* , 'categories' */],
        cart_id: validated.cart_id,
        customer_id: customer_id,
        region_id: validated.region_id,
        currency_code: validated.currency_code,
        include_discount_prices: true,
      });

### Additional context

During high traffic period this can cause db cpu usuage to spike and crash db

**Comment by adrien2p** [comment]
This is due to typeorm more than medusa itself, it will be worth doing the same test with the product module in the future

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
