### ISSUE TITLE
Not able to connect with remote database

### ISSUE THREAD

**Issue by impactcolor** [medusajs/medusa#5851]
According to the documentation in two areas of the documentation:
Configurations/database_url:

    postgres://[user][:password]@[host][:port]/[dbname]
You set the database url like so:

    module.exports = {
      projectConfig: {
        database_url: process.env.DATABASE_URL,
        // ...
      },
      // ...
    }

You can also Create Medusa App like so:

    npx create-medusa-app@latest --db-url postgres://[user][:password]@[host][:port]/[dbname]

When I run either of the above with those exact settings:

    npx create-medusa-app@latest --db-url postgres://impctUsr:password@164.90.xxx.xxx:5432/impactcolorDB

I get the errors:
`Couldn't connect to PostgreSQL using the database URL you passed. Make sure it's correct and try again.` or when just trying to migrate and having it configured in the .env

[![TypeError \[ERR_INVALID_URL\]: Invalid URL: postgres://impctUsr:password@164.90.xxx.xxx:5432/impactcolorDB][1]][1]

I can confirm that the credentials work from a local client connection to my report database.  Any idea what I'm doing wrong?

**Comment by shahednasser** [comment]
Thanks for opening this issue @impactcolor . Can you try to add the `?sslmode=require` to the URL with the `create-medusa-app` command like so:

```bash
npx create-medusa-app@latest --db-url postgres://impctUsr:password@164.90.xxx.xxx:5432/impactcolorDB?sslmode=require
```

**Comment by impactcolor** [comment]
@shahednasser tried it just now it says "zsh: no matches found: postgres://impctUsr:password@164.90.xxx.xxx:5432/impactcolorDB?sslmode=require"

**Comment by shahednasser** [comment]
Oh sorry you should wrap the URL with double quotes:

```bash
npx create-medusa-app@latest --db-url "postgres://impctUsr:password@164.90.xxx.xxx:5432/impactcolorDB?sslmode=require"
```

**Comment by impactcolor** [comment]
@shahednasser thank you, I wrapped it in quotes and it gives the same error.

**Comment by shahednasser** [comment]
Does your password have any special characters? We've had users face issues with a similar situation. If so, can you try using a password without special characters and see if that works?

**Comment by impactcolor** [comment]
That was it, thank you! It ran with a new password with no special characters and removing the ssl:
`npx create-medusa-app@latest --db-url "postgres://impctUsr:passwordWithNoSpecialCharacters@164.90.xxx.xxx:5432/impactcolorDB"`

**Comment by shahednasser** [comment]
Great to hear @impactcolor ! In the `create-medusa-app` command we encode special characters in your password to avoid that problem. However, if you're entering your URL with `--db-url`, you either have to encode the special characters yourself or use a password without special characters. Will make sure to add a note about this in the docs to avoid confusion for other developers 👍🏻

**Comment by impactcolor** [comment]
@shahednasser Hi! quick question on the vercel setup as indicated in the medusa create app.  To create a project with vercel it's like this:
`npx create-medusa-app@latest --db-url  "postgres://default:************@ep-divine-sasdfd-71233951.us-west-2.postgres.vercel-storage.com:5432/verceldb"`
However this doesn't work it gives the error: Couldn't connect to PostgreSQL using the database URL you passed. Make sure it's correct and try again.
I ensured the password doesn't have any special characters only numbers and alpha.  Any idea why this happens?

**Comment by shahednasser** [comment]
As indicated in the docs, for vercel you must append `?sslmode=require` to the end of the URL. For example:

```bash
npx create-medusa-app@latest --db-url  "postgres://default:************@ep-divine-sasdfd-71233951.us-west-2.postgres.vercel-storage.com:5432/verceldb?sslmode=require"
```

Will close this issue, let me know if you face any other problems.

**Comment by vitustockholm** [comment]
this post is better than documention at all. youtube trends was saying medusajs is best documentated, it was only paid ad guys! So much documentation and its kind of uselesssss without this post
