### ISSUE TITLE
Sendgrid throws error

### ISSUE THREAD

**Issue by SGFGOV** [medusajs/medusa#5856]
Whenver I attempt to send a message via sendgrid using the notification service I get this error

error: error: null value in column "resource_id" of relation "notification" violates not-null constraint
error:   unable to send message via email:null value in column "resource_id" of relation "notification" violates not-null constraint

All I'm doing is this after installing the sendgrid plugin 

 await this.notificationService.send("send_otp", {
                    otp: theOtp,
                    validity: customer.otpExpiry,
                    email
                }, "sendgrid");

**Comment by SGFGOV** [comment]
I just needed to include a message id

await this.notificationService.send("send_otp", {
otp: theOtp,
id: XXXXXX
validity: customer.otpExpiry,
email
}, "sendgrid");

I wish this mentioned in the documentation as this id is used to resend the message

**Comment by shahednasser** [comment]
Thanks for mentioning this @SGFGOV , can you explain more what ID exactly did you pass? Not sure if this is the expected behaviour

**Comment by SGFGOV** [comment]
@shahednasser , one needs to pass a unique random string as id as a part of the event data. 
all I did create a string like `msg_sendgrid_${new Date()}`

await this.notificationService.send("send_otp", {
otp: theOtp,
id: `msg_sendgrid_${new Date()}`,
validity: customer.otpExpiry,
email
}, "sendgrid");
The typings should have taken care of it but, unfortunately the sendgrid API is still in js not ts, so is missing the typings. So an update in the documentation maybe a short term fix

**Comment by shahednasser** [comment]
@olivermrbl just to confirm: is this the expected behavior of notification services/sendgrid? I don't see the ID as required in [SendGrid's types](https://github.com/sendgrid/sendgrid-nodejs/blob/main/packages/helpers/classes/mail.d.ts#L171)
