### ISSUE TITLE
Product Exports and Imports dont include Metadata

### ISSUE THREAD

**Issue by Kainkainkain** [medusajs/medusa#5864]
##Bug 

Product Exports and Imports don't include Metadata.

When I look in postgres 
SELECT * FROM public.product

I see the metadata field so I should be as simple as the other items to import. The format is JSON after all. 

Metadata is a great way to add additional data for front end storefront without having to modify medusa with complex entity extensions. 

For other readers looking for a solution - currently I am: 
Using the SKU, slug(handle) as unique identifiers and preparing data manually for direct SQL manipulation in postgres. 

### Steps to replicate
1. Export products. 
2. Look for a metadata column in export

**Comment by alsherif-khalaf** [comment]
is there any solution ?

**Comment by namnguyenn17** [comment]
Have you resolved this issue yet?

**Comment by abudiar** [comment]
I have noticed that Medusa tries to lookup the database, and is pretty generic.
I've had success importing using the column name "Product Metadata" in the CSV file where the value can be a stringified JSON.
