### ISSUE TITLE
Orders have 0 items occasionally

### ISSUE THREAD

**Issue by khanh-to-niteco** [medusajs/medusa#5865]
### Describe the bug

The issue seems to happen in `OrderEditService.confirm`

![image](https://github.com/medusajs/medusa/assets/71063731/b54ce5aa-d2ea-4142-b7cb-5030a347b882)

Since these 2 updates are run in parallel, if the second request finishes before the first request, the order_id of all line items are updated to `null` (including those of second request)

This is possible if we look inside the `LineItemService.update` method

![image](https://github.com/medusajs/medusa/assets/71063731/ebdbca67-be90-493a-a308-cf37e7ec389b)

And go deep inside the `list` method down to Typeorm level

![image](https://github.com/medusajs/medusa/assets/71063731/b5d5718f-8a77-46d5-a885-be9e47dbb24b)

In case the first request go down to await the `startTransaction` inside Typeorm and there is a network or DB server delay with that particular start transaction command, then the second request could finish all the update.

Then the first request continues execution and list all the line items to update to `null` (including those of the second request)

We are able to reproduce the issue consistently by adding a sleep after the `startTransaction` for the first request.

This is just one particular case where we can run into issues, but in general, when data to be updated could overlap, we could run into concurrency issues 

### System information

Medusa version (including plugins): Medusa 1.17.4
Node.js version: 18.0
Database: Postgres
Operating system: 
Browser (if relevant):

**Comment by olivermrbl** [comment]
@khanh-to-niteco, thanks for reporting the issue. We'll investigate this right away and patch it asap :)
