### ISSUE TITLE
TypeScript Error: Property 'product_medias' does not exist on type 'ProductVariant'

### ISSUE THREAD

**Issue by MarNeumann** [medusajs/medusa#5873]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

While implementing the digital product delivery feature as outlined in the MedusaJS documentation ([https://docs.medusajs.com/recipes/digital-products#deliver-digital-products-to-the-customer](https://docs.medusajs.com/recipes/digital-products#deliver-digital-products-to-the-customer)), I encountered a TypeScript error when running the provided `handle-order.ts` script.

**Error Message:** The TypeScript compiler throws the following error: `Property 'product_medias' does not exist on type 'ProductVariant'.ts(2339)`

**Steps to Reproduce:**

1.  Follow the digital product delivery recipe from the MedusaJS documentation.
2.  Use the provided `handle-order.ts` script in a MedusaJS project.
3.  Run the script or compile the project.

**Expected Behavior:** The script should compile without errors, allowing for the retrieval of product media associated with a product variant in an order.

**Actual Behavior:** TypeScript compilation fails with the error indicating that 'product\_medias' is not a recognized property of 'ProductVariant'.

**Additional Information:**

*   The relevant code snippet where the error occurs is as follows:
    
    `if (!item.variant.product_medias.length) {`
and
   `item.variant.product_medias.forEach(async (productMedia) => { `

    
*   This issue seems to be related to type definitions in the MedusaJS framework or a potential mismatch between the documentation and the actual API.

**Possible Solutions or Suggestions:**

*   Clarification on whether 'product\_medias' is a valid property of 'ProductVariant' in the latest version of MedusaJS.
*   If 'product\_medias' is valid, advice on resolving the TypeScript error.
*   If the property is deprecated or renamed, an update to the documentation and an alternative approach to achieve the same functionality.

**Environment:**

*   MedusaJS Version: 1.18.1
*   TypeScript Version: 4.5.2
*   Node.js Version: 20.10.0

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for reporting this error @MarNeumann . I think the problem is because of a missing `index.d.ts` in the examples of the recipe. just to clarify, `product_medias` is not available in Medusa natively and it's only added through this guide. So, to fix the type error, create the file `src/index.d.ts` with the following content:

```ts
import { ProductMedia } from "./models/product-media";

export declare module "@medusajs/medusa/dist/models/product-variant" {
  declare interface ProductVariant {
    product_medias: ProductMedia[];
  }
}
```

Considering you'd like to fix this issue, can you submit a PR adding this file to the digital products recipe? Source file in `www/apps/docs/content/recipes/digital-products.mdx`. I'd add it in the "Example: Create ProductMedia Entity" collapsible.

**Comment by MarNeumann** [comment]
Hi @shahednasser, thanks for the fast reply! I tried to follow your your supposed solution. This did result in a

`'export' modifier cannot be applied to ambient modules and module augmentations since they are always visible.ts(2668)`. 

I tried to fix this new error by updating the declaration. Unfortunately this didn't solve the issue.
```typescript
import { ProductMedia } from "./models/product-media";

declare module "@medusajs/medusa/dist/models/product-variant" {
    interface ProductVariant {
        product_medias: ProductMedia[];
    }
}
```

**Comment by shahednasser** [comment]
Can you try renaming `index.d.ts` to `types.d.ts` or move it to a subdirectory like `src/types`? I heard from some users that this solved the problem for them 😄

**Comment by MarNeumann** [comment]
Thank you so much! This solved the issue.
