### ISSUE TITLE
I run "medusa-dev --set-path-to-repo `pwd`" but the error appear

### ISSUE THREAD

**Issue by bekmarc** [medusajs/medusa#5884]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

D:\language\nodejs>medusa-dev --set-path-to-repo `pwd`
C:\Users\gpous\AppData\Local\Yarn\Data\global\node_modules\string-width\index.js:2
const stripAnsi = require('strip-ansi');
                  ^

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\gpous\AppData\Local\Yarn\Data\global\node_modules\strip-ansi\index.js from C:\Users\gpous\AppData\Local\Yarn\Data\global\node_modules\string-width\index.js not supported.
Instead change the require of C:\Users\gpous\AppData\Local\Yarn\Data\global\node_modules\strip-ansi\index.js in C:\Users\gpous\AppData\Local\Yarn\Data\global\node_modules\string-width\index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\Users\gpous\AppData\Local\Yarn\Data\global\node_modules\string-width\index.js:2:19)
    at Object.<anonymous> (C:\Users\gpous\AppData\Local\Yarn\Data\global\node_modules\yargs\build\lib\usage.js:12:21)
    at Object.<anonymous> (C:\Users\gpous\AppData\Local\Yarn\Data\global\node_modules\yargs\build\lib\yargs.js:7:17)
    at Object.<anonymous> (C:\Users\gpous\AppData\Local\Yarn\Data\global\node_modules\yargs\yargs.js:7:27)
    at Object.<anonymous> (C:\Users\gpous\AppData\Local\Yarn\Data\global\node_modules\medusa-dev-cli\dist\index.js:14:15) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.18.2

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by xyzones** [comment]
@bekmarc try the following

- delete the `yarn.lock` and `node_modules` from `C:\Users\gpous\AppData\Local\Yarn\Data\global\`
- run `yarn set version classic`
- install medusa-dev-cli with `yarn global add medusa-dev-cli`

once the `medusa-dev-cli` is installed go to the medusa local git folder and remove the `yarn.lock` and `node_modules` followed by `yarn install` and `yarn build`

i am also suggesting to use node v20

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
