### ISSUE TITLE
Missing redis_options inside job scheduler

### ISSUE THREAD

**Issue by kstoklosa** [medusajs/medusa#5893]
## Bug report

In the `JobSchedulerService` class of the medusa package library, the Redis instance is not being created with the `redis_options` parameter. This leads to an inability to change the IP family for the Redis instance, even when these options are specified in the configuration. 

Consequently, this forces the use of a public connection string for Redis deployments, such as those on fly.io, instead of allowing a private connection configuration, there is no chance to use ipv6 family. This issue limits the flexibility and security of Redis deployments in different environments.

### System information

Medusa version (including plugins): ^1.19.0
Node.js version: 18.13.0
Database: PostgreSQL
Operating system: -
Browser (if relevant): - 

### Steps to reproduce the behavior

1. Provide projectConfig config with redis_options object inside `medusa-config.js` file.
2. Notice that the Redis instance inside JobScheduler does not use the provided redis_options.

### Expected behavior

Redis instance within the `JobSchedulerService` class includes the redis_options specified in the config.projectConfig. 

### Code snippets

```
// Relevant portion of the JobSchedulerService constructor

const connection = new Redis(config.projectConfig.redis_url, {
  maxRetriesPerRequest: null,
  enableReadyCheck: false,
  // Missing incorporation of redis_options from config
});
```

### Additional context

Add any other context about the problem here

**Comment by pepijn-vanvlaanderen** [comment]
Until the PR is merged: since ioredis is used, you could actually append the Redis URL with `?family=6`.
