### ISSUE TITLE
ADMIN - Ui freezes/ becomes unresponsive after modal close

### ISSUE THREAD

**Issue by raukaute** [medusajs/medusa#5896]
## Bug report

After closing a modal in the admin (e.g. via container menu/ actionables) the UI is blocked due to "pointer-events: none" style not being removed from document body. See screenshot.

### Steps to reproduce the behavior

1. Go to Admin, Product Details
2. Click on Edit Variants
3. Close Modal

### Expected behavior

Remove style from body to release ui for further interaction.

### Screenshots

<img width="1487" alt="image" src="https://github.com/medusajs/medusa/assets/57749196/7a3884b3-0846-4b05-8f80-0a1139907180">

**Comment by coinlordd** [comment]
This issue is still there, or at the very least when importing the Drawer.

**Comment by jason13657** [comment]
same issue

**Comment by ibkrebecca** [comment]
> same issue

did you find any solution on this?
