### ISSUE TITLE
Wishlist Plugin - Links in docs are not correct

### ISSUE THREAD

**Issue by Edan-Swipik** [medusajs/medusa#5909]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

links in the doc are pointing to /store/**customer**/<CUSTOMER_ID>/wishlist
while they need to point to /store/customer**s**/<CUSTOMER_ID>/wishlist

### How can this issue be resolved?

1. change `customer` to `customers` in the documentation for api routes for this plugin

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for catching this! Will open a PR to fix it.
