### ISSUE TITLE
Cart APIs have high latency 

### ISSUE THREAD

**Issue by nadeemdevs** [medusajs/medusa#5913]
## Bug report

For some reason cart API takes around 7-10 seconds to get a response if its a 200 status code
Similarly the create address API shows infinite loading on postman, but a record is being created with the default values(such as id, country code etc) without a response 

### System information

Medusa version (including plugins): 1.17.4
Node.js version: LTS
Database: postgres
Operating system: windows 11
Browser (if relevant): firefox

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by olivermrbl** [comment]
Can you tell us a bit more about your setup? Are you experiencing this in your local environment? Have you made any customizations? Are you performing specific steps, that we should know about?

**Comment by nadeemdevs** [comment]
we are building a marketplace (with multiple vendors) and of course a lot of the modules are custom build expect the cart, order and few others. we been using the neon.tech db on free tier for local and thought that was the problem, and later switch to render but the issue still exists. 
also the order APIs inside the admin dashboard are fast but creating cart, adding line items, creating payment sessions, selecting payment session, completing carts from the custom storefront takes an average of 10 seconds to get a response

**Comment by nadeemdevs** [comment]
[fixed]: changed our db to aws rds
