### ISSUE TITLE
Cannot expand fields when retrieving orders in Medusa JS client

### ISSUE THREAD

**Issue by aldo-roman** [medusajs/medusa#5922]
### Describe the bug

The retrieve order API accepts a `expand` parameter, which is exposed in other methods (eg, in lookup order or in the Admin API), but not in the JS client method `medusa.orders.retrieve`

### System information

Medusa version (including plugins): ^6.1.1
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Expected behavior

The API exposes fields and expand parameters as other methods do.

### Additional context

It is even possible to do code injection by doing:

```ts
medusa.orders.retrieve(`${params.id}?expand=...`);
```

**Comment by olivermrbl** [comment]
Expand is passed as part of the second param to `retrieve` in our JS SDK.
```
medusa.orders.retrieve(params.id, { expand: "items" });
```


I recommend giving [the documentation](https://docs.medusajs.com/js-client/overview#expanding-fields) a read.

**Comment by aldo-roman** [comment]
@olivermrbl it does not

The second parameter is custom headers for the network request, not configuration. 

Please give it a try, check the types as well as the implementation of this method. 

As said in the ticket description, it is accepted in other methods, but not in retrieve.

**Comment by olivermrbl** [comment]
@aldo-roman, I apologise. I missed that you were querying orders in the Store API. You are right; this is currently not supported.

Would you be up for sending a PR for this? :)
