### ISSUE TITLE
Admin UI not logging out automatically if session expired

### ISSUE THREAD

**Issue by genox** [medusajs/medusa#5925]
### Describe the bug

Once a session times out, the admin UI should reload and show the login view. Currently, a session times out, giving the user the impression that everything is fine while data is no longer displayed. Not sure if this is related - didn't dig in to how data is persisted in the UI - but today I was adding some collections that showed up in the UI list after I clicked publish and wanted to add some products but I couldn't see any in the products list - reminding me that the session probably expired. After hard reloading I no longer saw any collections, leaving me to think that they probably weren't persisted to start with.

### System information

Medusa version (including plugins): all current versions at date of writing.

### Steps to reproduce the behavior

1. Log in
2. Leave browser window open until session expires
3. Click around in the UI and notice the missing data in lists etc.
4. Try to add a collection and see what happens (unconfirmed)
5. Hard reload the page to see the login view

### Expected behavior

The admin app should reload / navigate to the login screen once a session is expired.

**Comment by olivermrbl** [comment]
Thanks for filing this request @genox. @kasperkristensen, worth having in mind for the upcoming admin updates. Shouldn't be much work.
