### ISSUE TITLE
zero-decimal currencies are beeing divided by 100 

### ISSUE THREAD

**Issue by Dalvae** [medusajs/medusa#5932]
Bug report

We are encountering an issue where Chilean Pesos (CLP) prices are being processed as decimal-based currencies in our application. As a zero-decimal currency, CLP should not be divided by 100, but currently, all CLP amounts are being treated this way, leading to incorrect price calculations and display.
System information

    Medusa version (including plugins): [1.18.1]
    Node.js version: [Node.js 17]
    Database: [postresql]
    Operating system: [ubuntu.server]

Steps to reproduce the behavior

    Set the application currency to CLP.
    Input or retrieve a product price, for example, 1000 CLP.
    Observe that the price is being processed and displayed as 10 CLP, indicating an incorrect division by 100.

Expected behavior

For zero-decimal currencies like CLP, the amount should be treated as the smallest currency unit without conversion. Therefore, a price of 1000 CLP should be processed and displayed exactly as 1000 CLP, without being divided by 100.

Screenshots

![frontend display](https://github.com/medusajs/medusa/assets/101679648/a7f155b6-ec9b-43c9-96df-02392ea0c87c)
![json response](https://github.com/medusajs/medusa/assets/101679648/d9ca61b2-3d90-48b1-aa0e-5dd5393381f6)

This is the [helper](https://github.com/medusajs/medusa/blob/a3460e5a1aacecc1b51f0f5eb5e913fd3aecc8d2/packages/medusa-react/src/helpers/index.ts#L129) function, thanks to @VariableVic

**Comment by olivermrbl** [comment]
Our Next.js starter uses our `medusa-react` to convert raw prices to a human-readable amount. Right now, it uses a [hardcoded list of no-division currencies](https://github.com/medusajs/medusa/blob/76332ca6c153a786acc07d3f06ff45c3b9346fd3/packages/medusa-react/src/helpers/index.ts#L129). We are aware that this is a sub-optimal way of handling it, but it's what we have to work with for now. 

I am happy to accept a PR adding CLP to the list. Alternatively, you can use our utils in `medusa-react` to handle the price displaying yourself following a similar approach as to what we do.

Update: I realise you are aware of the hardcoded list already. Let me know how you want to proceed from here, and I can help :)
