### ISSUE TITLE
Docs(Code Issue): Code Issue in /deployments/server/deploying-on-railway

### ISSUE THREAD

**Issue by Kainkainkain** [medusajs/medusa#5935]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The deploy documentation has a Railway deploy button. 
I followed that and can't log in (since there is no user)
I see instruction to connect Railway.
Documentation at https://docs.medusajs.com/deployments/server/deploying-on-railway#create-admin-user
doesn't mention whether to connect Railway Link to Redis, Postgres or Backend(medusa). 

Trying Railway, Railway Login, Railway Link > choose Backend, 
then try the railway run npx medusa user --email example@example.com --password complexPassword1234!!

and i get error 

npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in: C:\Users\ZZZ\AppData\Local\npm-cache\_logs\2023-12-20T02_00_07_412Z-debug-0.log:
0 verbose cli C:\Program Files\nodejs\node.exe C:\Users\zzz\AppData\Roaming\nvm\v18.18.0\node_modules\npm\bin\npm-cli.js
1 info using npm@9.8.1
2 info using node@v18.18.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:C:\Users\zzz\AppData\Roaming\nvm\v18.18.0\node_modules\npm\npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:C:\Users\zzz\Documents\GitHub\medusabackend-zzzv2\.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:C:\Users\zzz\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Program Files\nodejs\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 7ms
17 timing npm:load:configload Completed in 7ms
18 timing config:load:flatten Completed in 2ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm exec medusa user --email zzz@zzz.com --password complexPassword1234!!
22 verbose argv "exec" "--" "medusa" "user" "--email" "zzz@zzz.com" "--password" "complexPassword1234!!"
23 timing npm:load:setTitle Completed in 1ms
24 timing npm:load:display Completed in 1ms
25 verbose logfile logs-max:10 dir:C:\Users\zzz\AppData\Local\npm-cache\_logs\2023-12-20T01_57_50_583Z-
26 verbose logfile C:\Users\zzz\AppData\Local\npm-cache\_logs\2023-12-20T01_57_50_583Z-debug-0.log
27 timing npm:load:logFile Completed in 8ms
28 timing npm:load:timers Completed in 1ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 45ms
31 silly logfile start cleaning logs, removing 4 files
32 timing arborist:ctor Completed in 1ms
33 silly logfile error removing log file C:\Users\zzz\AppData\Local\npm-cache\_logs\2023-12-20T00_20_29_182Z-debug-0.log [Error: EPERM: operation not permitted, lstat 'C:\Users\zzz\AppData\Local\npm-cache\_logs\2023-12-20T00_20_29_182Z-debug-0.log'] {
33 silly logfile   errno: -4048,
33 silly logfile   code: 'EPERM',
33 silly logfile   syscall: 'lstat',
33 silly logfile   path: 'C:\\Users\\zzz\\AppData\\Local\\npm-cache\\_logs\\2023-12-20T00_20_29_182Z-debug-0.log'
33 silly logfile }
34 silly logfile error removing log file C:\Users\zzz\AppData\Local\npm-cache\_logs\2023-12-20T00_20_23_810Z-debug-0.log [Error: EPERM: operation not permitted, lstat 'C:\Users\zzz\AppData\Local\npm-cache\_logs\2023-12-20T00_20_23_810Z-debug-0.log'] {
34 silly logfile   errno: -4048,
34 silly logfile   code: 'EPERM',
34 silly logfile   syscall: 'lstat',
34 silly logfile   path: 'C:\\Users\\zzz\\AppData\\Local\\npm-cache\\_logs\\2023-12-20T00_20_23_810Z-debug-0.log'
34 silly logfile }
35 silly logfile done cleaning log files
36 http fetch GET 200 https://registry.npmjs.org/medusa 1038ms (cache miss)
37 timing command:exec Completed in 1058ms
38 verbose stack Error: could not determine executable to run
38 verbose stack     at getBinFromManifest (C:\Users\zzz\AppData\Roaming\nvm\v18.18.0\node_modules\npm\node_modules\libnpmexec\lib\get-bin-from-manifest.js:17:23)
38 verbose stack     at exec (C:\Users\zzz\AppData\Roaming\nvm\v18.18.0\node_modules\npm\node_modules\libnpmexec\lib\index.js:188:15)
38 verbose stack     at async module.exports (C:\Users\zzz\AppData\Roaming\nvm\v18.18.0\node_modules\npm\lib\cli-entry.js:61:5)
39 verbose pkgid medusa@0.0.3
40 verbose cwd C:\Users\zzz\Documents\GitHub\medusabackend-zzzv2
41 verbose Windows_NT 10.0.19045
42 verbose node v18.18.0
43 verbose npm  v9.8.1
44 error could not determine executable to run
45 verbose exit 1
46 timing npm Completed in 1408ms
47 verbose code 1
48 error A complete log of this run can be found in: C:\Users\zzz\AppData\Local\npm-cache\_logs\2023-12-20T01_57_50_583Z-debug-0.log

 So I can't really use the deployment. Perhaps I missed something. 
Looking at the code it looks like the error starts after it it gets medusa

### How can this issue be resolved?

1. Try and set up a railway deploy with button from https://docs.medusajs.com/deployments/server/deploying-on-railway
2. try to add an admin user
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
The error you posted seems to be an error related to NPM not being able to access the cache on your machine, hence the "operation not permitted" message. This doesn't seem to be an error related to Medusa or Railway. It's most probably related to permissions not being set correctly for your NPM installation.

**Comment by shahednasser** [comment]
Closing this for lack of responsiveness. Feel free to re-open with more information.

**Comment by iaremarkus** [comment]
For anyone else who ends up here, I had the same issue and the missing piece of the documentation, is that you need to run `npm i` in your local Medusa project, before trying to do the `railway` command to add the default user.

The command that creates the user on your Railway app, uses the local medusa package to do this, so you need to install it first :)
