### ISSUE TITLE
docs: env variable naming consistency for Redis event bus and cache modules

### ISSUE THREAD

**Issue by gursuj** [medusajs/medusa#5936]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The environment variables for the Redis modules are named according to the module (`CACHE_REDIS_URL` & `EVENTS_REDIS_URL`). However, they both use the same redis url as the value. Even the starter code generated by `create-medusa-app` sets the same name for them [here](https://github.com/medusajs/medusa-starter-default/blob/0cabe2a139c9687c10484e967464cd51a25f840b/medusa-config.js#L61-L67). I can submit a PR that renames them. Just wanted to ask which occurences are safe to rename.

### Occurrences to rename:
*Module documentation uses the variable name in 2 places(setting the env variable and using it in `medusa-config.js` code snippet)*
- [ ] [Cache module](https://github.com/medusajs/medusa/blob/a3460e5a1aacecc1b51f0f5eb5e913fd3aecc8d2/www/apps/docs/content/development/cache/modules/redis.md?plain=1#L44)
- [ ] [Events module](https://github.com/medusajs/medusa/blob/a3460e5a1aacecc1b51f0f5eb5e913fd3aecc8d2/www/apps/docs/content/development/events/modules/redis.md?plain=1#L47)
- Not sure if these 2 should be renamed
  - [ ] [Backend configration](https://github.com/medusajs/medusa/blob/a3460e5a1aacecc1b51f0f5eb5e913fd3aecc8d2/www/apps/docs/content/development/backend/configurations.md?plain=1#L434)
  - [ ] [Backend deployment on Heroku](https://github.com/medusajs/medusa/blob/a3460e5a1aacecc1b51f0f5eb5e913fd3aecc8d2/www/apps/docs/content/deployments/server/deploying-on-heroku.mdx#L154)

There might be more occurences because both Github code search and the search in the docs site didn't find some of the above ones.

### How can this issue be resolved?

Rename occurences of `CACHE_REDIS_URL`, `EVENTS_REDIS_URL` & `EVENT_REDIS_URL` to `REDIS_URL`

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for submitting this issue. The modules can use different connection URLs, hence the different environment variable names in the docs. If someone wants to use the same URL they can simply use the environment variable of their choice.

However, I'm all for changing `EVENT_REDIS_URL` to `EVENTS_REDIS_URL`. That probably was just a typo. If you're interested to fix it, please go ahead and open a PR 😇

**Comment by gursuj** [comment]
Ah thanks for clearing that up. Will make a PR once I get home
