### ISSUE TITLE
Missing Price Input Field in Admin Panel

### ISSUE THREAD

**Issue by Garnett1314** [medusajs/medusa#5939]
## Overview
I initiated a new Medusa project using the command:

npx create-medusa-app@latest

After setting up the database connection and creating the store project, I proceeded to the admin page. I followed the testing steps as outlined in the documentation and successfully completed them.

### issue

Now, as I attempt to add my own products to the store, I encounter an issue in the admin panel when setting up the price list. Specifically, when I try to add a new price to a product, there seems to be no field available for entering the price.
![Snipaste_2023-12-20_16-11-13](https://github.com/medusajs/medusa/assets/31092354/352a47a2-4695-4ebc-b564-fe6e2459d52a)

**Comment by olivermrbl** [comment]
It looks like your product is missing variants. Prices are added at the product variant level. Can I get you to check this?

**Comment by Garnett1314** [comment]
Thank you very much for your advice, I can add it now, thank you again.
