### ISSUE TITLE
Order Timeline events - empty actions

### ISSUE THREAD

**Issue by damienroche** [medusajs/medusa#5940]
## Bug report

On order timeline there's two actions button to copy payment link and mark order as paid. Those two actions are just triggerring a `console.log("TODO")` 
Have you planned to implement the logic behind ?
See `/packages/admin-ui/ui/src/components/molecules/timeline-events/order-edit/payment-required.tsx`

Also there's another `console.log("TODO")` in `/packages/admin-ui/ui/src/components/molecules/timeline-events/order-edit/created.tsx`

### Screenshots

<img width="558" alt="Capture d’écran 2023-12-20 à 10 30 22" src="https://github.com/medusajs/medusa/assets/1529058/0624f757-d3d9-43f1-b1a2-9adc6bc2a0da">

**Comment by olivermrbl** [comment]
Thanks for filing the issue. We expect to implement these actions in the near future as part of [updating Medusa Admin](https://github.com/medusajs/medusa/discussions/5954).

**Comment by namnguyenn17** [comment]
It's been almost half of the year. Did the Medusa team resolve the issue yet @olivermrbl ? Now, I have this case when I click Mark as Paid, just show console log TODO. Thanks for your replying
