### ISSUE TITLE
useAdminCapturePayment doesn't work

### ISSUE THREAD

**Issue by luckyrsa56** [medusajs/medusa#5947]
Hello 
After payment was checked successfully using the transaction API, I want to update the status with capture status
Medusa-react offers this custom hook. I think we can update the payment status using this hook.
But it doesn't work 
import { useCart,useAdminOrder,useAdminCapturePayment} from "medusa-react";
import { redirec,useParams } from "next/navigation";
import { useEffect, useState } from "react"
import { contentfulClient } from "@/lib/config";
import { pageContentIds } from "@/lib/contentful-ref";

export default function Page() {
  const { completeCheckout } = useCart();

  // capturing payment status 
  const adminPaymentCapture = useAdminCapturePayment(localStorage.getItem('order'))
  const clientSecret = new URLSearchParams(window.location.search).get(
    "status"
  );
  const [paymentStatus, setPaymentStatus] = useState(clientSecret);
  const [pageData,setPageData] = useState()
  const params = useParams();
  const lang = params.lang;
  useEffect(()=>{
    contentfulClient
    .getEntry(pageContentIds.checkout, { locale: lang })
    .then(({ fields }) => {
      setPageData(fields);
    });
  },[clientSecret, completeCheckout]);
  useEffect(()=>{
    adminPaymentCapture.mutate() 
   },[paymentStatus])

**Comment by olivermrbl** [comment]
@luckyrsa56, it looks like you are trying to use an admin hook in your storefront. Admin hooks require admin-user authentication and should not/can't be used in unauthenticated territory such as storefronts. 

I would recommend you either [capture the payment in your admin dashboard](https://docs.medusajs.com/user-guide/orders/payments) or [create a subscriber](https://docs.medusajs.com/development/events/create-subscriber) on `order.placed`, that does the job for you.
