### ISSUE TITLE
Unexpected JS File Request After Hot Updates in Development Environment

### ISSUE THREAD

**Issue by BarryZhan** [medusajs/medusa#5949]
### Describe the bug

After running the development environment and making hot updates to files, a request is made to open a js file. The content of this file is as follows:

file path xxxx\@babel+cli@7.14.3_@babel+core@7.14.3\node_modules\@babel\cli\bin\babel.js
```javascript
#!/usr/bin/env node
require("../lib/babel");
```

This issue persists even after switching from yarn to pnpm and rebooting the computer.

### System information

Medusa version (including plugins):  7.1.9
Node.js version:  v18.15.0_
Operating system: windows 11 

### Steps to reproduce the behavior

1. Run pnpm dlx create-medusa-app@latest init project
2. Run the development environment
3. Make modifications to the files triggering hot updates
4. A request is made to open a js file with the aforementioned content

### Expected behavior

The expected behavior is that after making hot updates to files, no such requests to open the js file should be made.

### Screenshots

![1703142899603](https://github.com/medusajs/medusa/assets/11763811/441185e1-b65f-43f4-a825-5e99f3bfcf7a)

### Additional context

This issue persists across package managers (yarn and pnpm) and system reboots. Any help or guidance would be greatly appreciated.

---

Please let me know if you need any additional information to help diagnose and fix this issue.

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
