### ISSUE TITLE
hello i cant log in to the admin panel it keeps writing "these credentials do not match"

### ISSUE THREAD

**Issue by Nobleic** [medusajs/medusa#5962]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

hello i cant log in to the admin panel it keeps writing "these credentials do not match"

### How can this issue be resolved?

i need default password to log in

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by desneck** [comment]
Using medusa-cli, you can create a new admin user:

user
Creates a new admin user.

`medusa user --email <email> [--password <password>]`

**Comment by olivermrbl** [comment]
@Nobleic, please ensure you have created a user as per @desneck's comment. If your issue persists, please fill out the issue template. Closing until then :)

**Comment by Nobleic** [comment]
Thank you am greatful 😊😊
