### ISSUE TITLE
Undefined User in middlewares

### ISSUE THREAD

**Issue by lukebui** [medusajs/medusa#5964]
### Describe the bug

According to the example on how to [create a middleware](https://docs.medusajs.com/development/api-routes/example-logged-in-user), the `req.user` property should show the currently logged in user. However, when applying a middleware to existing routes, the `req.user` is `undefined`. Applying to custom routes will correctly attach the `user` record to the `MedusaRequest`.

### System information

Medusa version (including plugins): v1.19.0
Node.js version: v18 or v20
Database: Postgres (duh)
Operating system: Linux
Browser (if relevant):

### Steps to reproduce the behavior

Step 1: Create a new app using the `medusa new` command and the default starter template.

Step 2: Create a middleware to `console.log` the current logged in user at path `src/api/middlewares.ts`:
``` typescript
import {
  MedusaNextFunction,
  MedusaRequest,
  MedusaResponse,
  MiddlewaresConfig,
} from "@medusajs/medusa";

export const config: MiddlewaresConfig = {
  routes: [
    {
      matcher: "*",
      middlewares: [
        (
          req: MedusaRequest,
          _res: MedusaResponse,
          next: MedusaNextFunction
        ) => {
          console.log(req.user);
          next();
        },
      ],
    },
  ],
};
```

Step 3: Create a custom API route at `src/api/admin/hello/route.ts`:
``` typescript
import { MedusaRequest, MedusaResponse } from "@medusajs/medusa";

export async function GET(_req: MedusaRequest, res: MedusaResponse) {
  res.send("Hello there.");
}
```

Step 4: Run the dev server using `npm run dev`.

### Expected behavior

When accessing an existing route, e.g. `/admin/products` using Postman, the console log for `req.user` would be `undefined`. But for the custom route `/admin/hello`, the app correctly log the current user (or should I say `{userId: '<string>'}`).

### Update 1:
I tried:
``` typescript
import {
  MedusaNextFunction,
  MedusaRequest,
  MedusaResponse,
  MiddlewaresConfig,
  authenticate
} from "@medusajs/medusa";

export const config: MiddlewaresConfig = {
  routes: [
    {
      matcher: "*",
      middlewares: [
        authenticate(),
        (
          req: MedusaRequest,
          _res: MedusaResponse,
          next: MedusaNextFunction
        ) => {
          console.log(req.user);
          next();
        },
      ],
    },
  ],
};
```
but the program gets caught in an infinite loop.

**Comment by lukebui** [comment]
@adrien2p has helped me to find the solution.

First, the `authenticate` middleware must be called before custom middleware for protected routes. Second, one must remember to whitelist unprotected routes such as auth.

This should be in the documentation.

**Comment by lukebui** [comment]
Does applying custom middlewares override all default ones?

**Comment by adrien2p** [comment]
No it doesn't, but applying them on core route will apply the custom ones first

**Comment by helkaroui** [comment]
I'm trying to follow your blog on extending medusa to Marketplace https://medusajs.com/blog/extending-medusa-usecase-marketplace/

And I have the same issue with the middleware :
![image](https://github.com/medusajs/medusa/assets/22795356/241d06a7-50cb-4007-88f7-da8ab26b88a1)
when using the custom middleware requests are not authenticated :
![image](https://github.com/medusajs/medusa/assets/22795356/8511f0fa-7d4b-4fb8-80c4-057b0fc4fb7d)

What is the recommended way to apply authentication middleware before the custom ones ?

**Comment by adrien2p** [comment]
you need to apply the authenticate middleware first

**Comment by pmltechpile** [comment]
> you need to apply the authenticate middleware first

I am also experiencing a similar issue. I extended three services: Product, Store and User. For both the Product and Store I am able to pull the loggedInUser just fine however for the User service, I am getting a null value when I pull the loggedInUser from the container. This is what I have for the MiddlewaresConfig where I apply the authenticate middleware first as you have advised to do: 

![MiddlewaresConfig](https://github.com/medusajs/medusa/assets/126093677/0ba03bed-9a3a-41c2-98ac-16d384ee67f3)

**Comment by pmltechpile** [comment]
> > you need to apply the authenticate middleware first
> 
> I am also experiencing a similar issue. I extended three services: Product, Store and User. For both the Product and Store I am able to pull the loggedInUser just fine however for the User service, I am getting a null value when I pull the loggedInUser from the container. This is what I have for the MiddlewaresConfig where I apply the authenticate middleware first as you have advised to do:
> 
> ![MiddlewaresConfig](https://private-user-images.githubusercontent.com/126093677/299870563-0ba03bed-9a3a-41c2-98ac-16d384ee67f3.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyOTI0OTksIm5iZiI6MTcwNjI5MjE5OSwicGF0aCI6Ii8xMjYwOTM2NzcvMjk5ODcwNTYzLTBiYTAzYmVkLTlhM2EtNDFjMi05OGFjLTE2ZDM4NGVlNjdmMy5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQxODAzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjUyMWFjODJiOTFlMjg5OTVjMjMwMWExMTE2MGEwNjNjNDdmZjIxOTkxZmZiMWNmMzA3ZTE0NjkwYjE5OWNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7EWwJdhqmg1OFYYAlLcN8NX78tTjt0uhw_rvtuJbCBo)

Ok I got it to work with the help of other members in the discord. Ultimately one had a solution to make the service TRANSIENT and not SCOPED. This was the only service that differs from the other services I have extended (PRODUCT, ORDERS and STORE) whicha are all made to be SCOPED. Extremely confused as to why this is the case but at least it's working now and I hope this helps others when running across this issue. IMO this issue should not be marked as closed as per the docs (https://docs.medusajs.com/development/services/extend-service) we are encouraged to make the extended service SCOPED.

**Comment by vholik** [comment]
> > > you need to apply the authenticate middleware first
> > 
> > 
> > I am also experiencing a similar issue. I extended three services: Product, Store and User. For both the Product and Store I am able to pull the loggedInUser just fine however for the User service, I am getting a null value when I pull the loggedInUser from the container. This is what I have for the MiddlewaresConfig where I apply the authenticate middleware first as you have advised to do:
> > ![MiddlewaresConfig](https://private-user-images.githubusercontent.com/126093677/299870563-0ba03bed-9a3a-41c2-98ac-16d384ee67f3.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyOTI0OTksIm5iZiI6MTcwNjI5MjE5OSwicGF0aCI6Ii8xMjYwOTM2NzcvMjk5ODcwNTYzLTBiYTAzYmVkLTlhM2EtNDFjMi05OGFjLTE2ZDM4NGVlNjdmMy5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQxODAzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjUyMWFjODJiOTFlMjg5OTVjMjMwMWExMTE2MGEwNjNjNDdmZjIxOTkxZmZiMWNmMzA3ZTE0NjkwYjE5OWNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7EWwJdhqmg1OFYYAlLcN8NX78tTjt0uhw_rvtuJbCBo)
> 
> Ok I got it to work with the help of other members in the discord. Ultimately one had a solution to make the service TRANSIENT and not SCOPED. This was the only service that differs from the other services I have extended (PRODUCT, ORDERS and STORE) whicha are all made to be SCOPED. Extremely confused as to why this is the case but at least it's working now and I hope this helps others when running across this issue. IMO this issue should not be marked as closed as per the docs (https://docs.medusajs.com/development/services/extend-service) we are encouraged to make the extended service SCOPED.

Can confirm that marking user service as `SCOPED` will result in not registering dependency in awilix (in my case `loggedInUser`). Marking service as `TRANSIENT` solved this issue.

**Comment by andrei-s-making-science** [comment]
Hi everyone,
Having an issue with middlewares:

### Summary
Playing around with authorization middleware, bit similar to https://docs.medusajs.com/modules/users/backend/rbac
When adding middleware for `/admin/*` routes - `req.user, req.session.user_id` are `undefined` for the **core** `/admin` routes (e.g. `GET /admin/users`).  For `/admin/custom` routes - `req.user, req.session.user_id` are defined.
Applicable to any type of the auth: `cookies, bearer token, api_token`.

Would really appreciate your help.

#### Debugging
1. If i add authenticate() middleware - req.user will be **defined** for the **core** `/admin` routes, but **CORS** errors will appear on admin UI for some of the endpoints: `GET /admin/users, GET /admin/store, GET /invites`, but some of the endpoints do not throw CORS e.g. 
   1.  If i additionally add cors() middleware -  same issue as described in 1. 
2. `req.app._router.stack` in **custom** middleware contains the **authenticate** middleware, but looks like it's not applied.
   1. documentation mentions that there is no need of adding authenticate() or cors() middlewares, as they are in place, which seems to be right, but not sure exactly how medusa code operates (looks like i need more time for this).
4. cookies, tokens exist in `req`


### Context
#### Configuration
##### package.json
```
"dependencies": {
    "@medusajs/cache-inmemory": "^1.8.9",
    "@medusajs/cache-redis": "^1.8.9",
    "@medusajs/event-bus-local": "^1.9.7",
    "@medusajs/event-bus-redis": "^1.8.10",
    "@medusajs/file-local": "^1.0.2",
    "@medusajs/inventory": "^1.11.6",
    "@medusajs/medusa": "^1.20.2",
    "@medusajs/stock-location": "^1.11.5",
    "awilix": "^8.0.1",
    "body-parser": "^1.19.0",
    "class-validator": "^0.14.1",
    "cors": "^2.8.5",
    "dotenv": "16.3.1",
    "express": "^4.17.2",
    "medusa-core-utils": "^1.2.1",
    "medusa-fulfillment-manual": "^1.1.39",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.24",
    "medusa-plugin-strapi": "*",
    "typeorm": "^0.3.16"
  },
  "devDependencies": {
    "@babel/cli": "^7.14.3",
    "@babel/core": "^7.14.3",
    "@babel/preset-typescript": "^7.21.4",
    "@medusajs/medusa-cli": "^1.3.21",
    "@types/express": "^4.17.13",
    "@types/jest": "^27.4.0",
    "@types/jsonwebtoken": "^9.0.5",
    "@types/node": "^18.19.3",
    "@typescript-eslint/eslint-plugin": "^6.16.0",
    "@typescript-eslint/parser": "^6.16.0",
    "babel-preset-medusa-package": "^1.1.19",
    "cross-env": "^7.0.3",
    "eslint": "^8.56.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-airbnb-typescript": "^17.1.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-import": "^2.29.1",
    "eslint-plugin-prettier": "^5.1.2",
    "husky": "^8.0.3",
    "jest": "^27.3.1",
    "lint-staged": "^15.2.0",
    "prettier": "^3.1.1",
    "ts-jest": "^27.0.7",
    "ts-loader": "^9.2.6",
    "typescript": "^4.5.2"
  },
```

#### Code
##### /src/api/middlewares.ts
```
import { MiddlewaresConfig, authenticate } from '@medusajs/medusa';
import authorize from './middlewares/authorize';
import log from './middlewares/log';

export const config: MiddlewaresConfig = {
  routes: [
    {
      // TODO: verify if analytics-config requires auth. Throwing CORS at the moment.
      matcher: /^\/admin\/(?!auth|analytics-config|users\/reset-password|users\/password-token|invites\/accept).*/,
      // TODO: verify why authenticate throws cors and why req.user doesn't exist in case no authenticate()
      middlewares: [authorize],
    },
  ],
};
```
##### /src/api/middlewares/authorize.ts
Not sharing a code as of redundancy, tried an empty log middleware - same result as described in Summary section e.g.
```
import type { MedusaNextFunction, MedusaRequest, MedusaResponse } from '@medusajs/medusa';

async function log(req: MedusaRequest, res: MedusaResponse, next: MedusaNextFunction): Promise<void> {
  console.warn(`:::req.app._router.stack`, req.app._router.stack);
  console.warn(
    `:::req.app._router.stack`,
    req.app._router.stack.map((element: { handle: () => unknown }) => element.handle?.toString()),
  );
  console.warn(`:::req.user`, req.user);
  console.warn(`:::req.session`, req.session);

  next();
}

export default log;
```

**Comment by marcopadillo** [comment]
Anyone else encountering a CORS issue when adding a product with the following middleware config:
```
export const config: MiddlewaresConfig = {
  routes: [
    {
      matcher: /\/admin\/[^(auth)].*/,
      middlewares: [authenticate(), registerLoggedInUser],
    },
  ],
}
```
![image](https://github.com/medusajs/medusa/assets/2935561/a9b1bfb1-b9d8-4ab5-a460-bd139bda82d1)

Adding `cors()` inside the `middlewares` array would solve this problem, but `loggedInUser` will revert to being undefined again. It seems the sequence of middlewares inside the array does not matter.

**Comment by niioo** [comment]
facing the same issue

**Comment by niioo** [comment]
has anyone fixed this??

**Comment by kim-hanho** [comment]
This is not a bug from Medusa, but from the multi-stage dependencies.
The issue is that your service(e.g `ProductService()`) is constructed before the loggedInUser data is injected.

`LoggedInUserMiddleware` uses `UserService()` as dependency, and (in my case) my `UserService` uses `ShippingProfileService` as dependency.
Because Medusa core's `ShippingProfileService` uses `ProductService` as dependency, so it means that... when I try to call UserService from LoggedInUserMiddleware, UserService -> ShippingProfileService -> ProductService has been constructed in a sequence.

So the `ProductService` which does not has `LoggedInUser` data inside, is being reused for the whole request.

So please check your UserService()'s dependencies.

My solution is create a custom service which does not has any dependent services and use it inside of LoggedInUserMiddleware, instead of using UserService.

```
class IndependentUserService extends TransactionBaseService {
  // Service that does not have any dependency in other services

  protected userRepository_: typeof UserRepository

  constructor(container) {
    super(container)

    this.userRepository_ = container.userRepository;
  }

  async retrieve(userId: string, config: FindConfig<User> = {}): Promise<User> {
    if (!isDefined(userId)) {
      throw new MedusaError(
        MedusaError.Types.NOT_FOUND,
        `"userId" must be defined`
      )
    }

    const userRepo = this.activeManager_.withRepository(this.userRepository_)
    const query = buildQuery({ id: userId }, config)

    const users = await userRepo.find(query)

    if (!users.length) {
      throw new MedusaError(
        MedusaError.Types.NOT_FOUND,
        `User with id: ${userId} was not found`
      )
    }

    return users[0]
  }
}

export default IndependentUserService
```

and

in loggedInUser middleware
```
    ...
    if (req.user && req.user.userId) {
      const independentUserService =
        req.scope.resolve("independentUserService") as IndependentUserService
      loggedInUser = await independentUserService.retrieve(req.user.userId)
    }

    req.scope.register({
      loggedInUser: {
        resolve: () => loggedInUser,
      },
    })
    ...
```

**Comment by EdgarSilvaAlluxi** [comment]
> Anyone else encountering a CORS issue when adding a product with the following middleware config:
> 
> ```
> export const config: MiddlewaresConfig = {
>   routes: [
>     {
>       matcher: /\/admin\/[^(auth)].*/,
>       middlewares: [authenticate(), registerLoggedInUser],
>     },
>   ],
> }
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/2935561/311075365-a9b1bfb1-b9d8-4ab5-a460-bd139bda82d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2NDU4OTcsIm5iZiI6MTcyNTY0NTU5NywicGF0aCI6Ii8yOTM1NTYxLzMxMTA3NTM2NS1hOWIxYmZiMS1iOWQ4LTRhYjUtYTQ2MC1iZDEzOWJkYTgyZDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDZUMTc1OTU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWVmZGZjMDk1ZDljNTg4NmE3MjZlYTU1YmM0YjBkNWY5NDU3MjE5MWYxMjU5MmIzMmM3NjNhZTRhYWFkYzdjMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uzjPZQxW21gsAGrgI2-mFyGkpjQiThCDvEUOILegrag)
> 
> Adding `cors()` inside the `middlewares` array would solve this problem, but `loggedInUser` will revert to being undefined again. It seems the sequence of middlewares inside the array does not matter.

Did you fixed the issue? im facing the same problem...

**Comment by u11d-bartlomiej-galezowski** [comment]
https://github.com/medusajs/medusa/issues/6585#issuecomment-1987722220

Here is workaround for that issue.
