### ISSUE TITLE
Incorrect price of product, returned by api.

### ISSUE THREAD

**Issue by ivanushkaPr** [medusajs/medusa#5965]
## Bug report

Incorrect product price returned by Medusa.

### Describe the bug

In the admin cabinet create any product and its variant. Then add price as decimel to a variant.
On blur event, medusa will add two zeros after comma. And after fetching product,
you will get product price multiplied by 100.

As example, if you set product price as 100, you will get 1000. Is it correct behavior?

### System information

Medusa version (including plugins):  
   "@medusajs/admin": "7.1.8",
    "@medusajs/cache-inmemory": "^1.8.9",
    "@medusajs/cache-redis": "^1.8.9",
    "@medusajs/event-bus-local": "^1.9.7",
    "@medusajs/event-bus-redis": "^1.8.10",
    "@medusajs/file-local": "^1.0.2",
    "@medusajs/medusa": "1.18.1",
Node.js version: 18.0.0
Database: PostgreSql
Operating system: Windows 11
Browser (if relevant):

### Steps to reproduce the behavior

1. Go to Admin panel.
2. Create product.
3. Create product variant.
4. Add price to product variant.
5. Fetch data on storefront.
6. You will get product price multiplied by 100.

### Expected behavior

Returned entered product price. If you set product price as 100, medusa returns 100.

**Comment by adrien2p** [comment]
Yes it is correct, the price is saved in cents always for rounding mitigation

**Comment by adrien2p** [comment]
I close since this is the expected behaviour, as I mentioned, feel free to re open if you find something

**Comment by nourr23** [comment]
> I close since this is the expected behaviour, as I mentioned, feel free to re open if you find something

Hello, well it's not, I'm using TND currency (tunisian currency) and whenever I add a price, I will get * 10 in the store front 

![Capture d'écran 2024-07-03 214912](https://github.com/medusajs/medusa/assets/94909965/c7cacb1c-bf77-41b6-b498-8ee04d84b476)


![Capture d'écran 2024-07-03 215035](https://github.com/medusajs/medusa/assets/94909965/fa2cf886-6396-4013-bc9d-6e5744122f32)


![Capture d'écran 2024-07-03 215118](https://github.com/medusajs/medusa/assets/94909965/e09d00bb-b42e-4dc6-b9d0-d2d772be3181)

![Capture d'écran 2024-07-03 215151](https://github.com/medusajs/medusa/assets/94909965/8f9b8478-438d-4c02-892a-7100054ebc88)
