### ISSUE TITLE
Get Started button in Navbar is not styled properly in Mobile view

### ISSUE THREAD

**Issue by shaikahmadnawaz** [medusajs/medusa#5975]
### Description
The "Get Started" button in the mobile view lacks proper styling. It appears without a background or any distinctive styling, unlike the desktop view. The suggested improvement is to add a background color to the "Get Started" button in the mobile view, similar to its appearance in the desktop view.

### Expected Behavior
The "Get Started" button in the mobile view should have consistent styling, including a background color, to match the desktop view.

### Screenshots
- Desktop View:
  ![Desktop View](https://github.com/medusajs/medusa/assets/96189881/6334ce72-f921-4668-bd26-ad80f4cbaa14)

- Mobile View:
  ![Mobile View](https://github.com/medusajs/medusa/assets/96189881/10416ad4-b5af-4729-ab7e-4e9c35571f5c)

**Comment by olivermrbl** [comment]
Appreciate the suggestion, but this is by design :)

**Comment by shaikahmadnawaz** [comment]
> Appreciate the suggestion, but this is by design :)

Okay 👍🏻
