### ISSUE TITLE
Price issue with TND

### ISSUE THREAD

**Issue by amirping** [medusajs/medusa#5976]
### Describe the bug

I cannot set the correct price in TND from the admin dashboard, and the returned price is being multiplied by 100.
from the dashboard, I can only enter the price in this format (XX.XX) while in TND the price is (XX.XXX).
the problem is that even if we set a price for example 65, the returned price is 65000, and by using formatAmount it will render to 650,000 even when passing the right local.

### System information

Medusa version (including plugins): 1.18.1
Node.js version: v16.15.1
Database: postgres:latest
Operating system: mac os
Browser (if relevant): firefox

### Expected behavior

can set the price correctly based on the currency.

### Screenshots
entering the price limited to xx.xx
<img width="353" alt="Screenshot 2023-12-30 at 16 32 03" src="https://github.com/medusajs/medusa/assets/3626339/b2ca001c-cff8-4b66-9304-fc2c3cdcfe57">
price is shown as xx.xxx
![image](https://github.com/medusajs/medusa/assets/3626339/1a8ca843-fa06-4734-b18f-b7f2f4cdc930)
price returned after formatAmount, while the returned in API is 25000
![image](https://github.com/medusajs/medusa/assets/3626339/d99e4afb-1d1c-4d59-97d3-270bb11918d4)

**Comment by adrien2p** [comment]
In the database the price is always saved in cents that is why it is multiplied by 100, this is to prevent rounding issues. 

From what I can see, the formatAmount is calling the Intl.NumberFormnat under the hood. the value pass to it is (price/100) since the price is saved in cents in the db it is then divided by 100 to get it back to the proper value. when I try it such as 
```ts
new Intl.NumberFormat("en-US", {
  style: "currency",
  currency: "TND",
  minimumFractionDigits: undefined,
  maximumFractionDigits: undefined,
}).format(2566 / 100)
```
I get the proper result of `'TND 25.660'`. So I don't see how you get this result unless you are already manipulating the amount on your side.

**Comment by amir-saadallah** [comment]
I managed to fix the price at the storefront level using 
```
formatAmount({
        amount: cheapestVariant.calculated_price / 10,
        region: cart.region,
        includeTaxes: false,
        locale: 'fr-TN',
      })
```
but the remaining problem is that we cannot set a 3 decimal value in the admin "xx.xxx" it only accepts 2 digits.

**Comment by amirping** [comment]
I managed to fix the price at the storefront level using

```
formatAmount({
  amount: cheapestVariant.calculated_price / 10,
  region: cart.region,
  includeTaxes: false,
  locale: 'fr-TN',
})
```
but the remaining problem is that we cannot set a 3 decimal value in the admin "xx.xxx" it only accepts 2 digits.
