### ISSUE TITLE
Investigate price structure to support different prices across regions / collections / etc..

### ISSUE THREAD

**Issue by olivermrbl** [medusajs/medusa#6]

**Comment by srindom** [comment]
I think this is covered well in the ProductVariantService. Each product can have multiple prices, one for each currency that is supported and one for each region that is supported. E.g. you can have:

```js
[
  {
    currency_code: "EUR",
    amount: 100,
  },
  {
    region_id: [region with specific pricing],
    currency_code: "EUR",
    amount: 120,
  },
  {
    currency_code: "DKK",
    amount: 1000,
  }
]
```

The price in all EUR regions would be 100 unless the customer is shopping from `[region with specific pricing]`, all regions with DKK currency will have price 1000.
