### ISSUE TITLE
Error 404 with Mailchimp subscribe

### ISSUE THREAD

**Issue by lfdadev** [medusajs/medusa#6013]
### Describe the bug

I can't get the Mailchimp subscription to work. I get 404 error

### System information

Medusa version (including plugins): 1.19.0
Mailchimp: 1.1.50
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Steps to reproduce the behavior

I get error 404 when I subscribe a new email

### Screenshots

![image](https://github.com/medusajs/medusa/assets/151443436/bcbeee7c-f6be-4dd7-be93-b90cf3a5d624)
![image](https://github.com/medusajs/medusa/assets/151443436/fc11422e-b7d0-4392-bd16-2e85b7f5b98a)

My form

![image](https://github.com/medusajs/medusa/assets/151443436/898e7d5e-fc92-4b03-b31d-bffffbe78bb8)
![image](https://github.com/medusajs/medusa/assets/151443436/7c255057-39a6-41db-ac2a-228955d17bc4)
![image](https://github.com/medusajs/medusa/assets/151443436/6e240664-1eea-47fb-a878-0f80385a7148)

### Additional context

I followed the guide from the docs.

**Comment by adrien2p** [comment]
Are you sure the plugin is loaded correctly? Do you have any logs on your server when starting?

**Comment by adrien2p** [comment]
can you share your plugin section of the medusa config

**Comment by lfdadev** [comment]
![image](https://github.com/medusajs/medusa/assets/151443436/4f8243c3-c2b7-4ac8-891b-14308faacd48)
![image](https://github.com/medusajs/medusa/assets/151443436/740f0e53-94b8-4009-8e1c-0eafca34adf4)



> Are you sure the plugin is loaded correctly? Do you have any logs on your server when starting?

I dont have any log about Mailchimp

**Comment by lfdadev** [comment]
When I test the route /mailchimp/subscribe I dont receive any

**Comment by adrien2p** [comment]
looks like the version 1.1.5 does not include the build output.

cc @olivermrbl we should re publish the plugin including the output files

**Comment by adrien2p** [comment]
@lfdadev I suggest you to downgrade until the new version is released

**Comment by lfdadev** [comment]
> @lfdadev I suggest you to downgrade until the new version is released

Which version can I use?

**Comment by adrien2p** [comment]
I would say 1.1.49

**Comment by lfdadev** [comment]
> I would say 1.1.49

Ok, I will try

**Comment by adrien2p** [comment]
keep me posted 👍

**Comment by lfdadev** [comment]
> I would say 1.1.49

Tested with that version and it worked perfect! Thanks!!!

**Comment by lfdadev** [comment]
It worked locally, but not in production. I got Cors error

![image](https://github.com/medusajs/medusa/assets/151443436/3eff863b-7dcc-41b8-8573-c97fe638761b)

**Comment by adrien2p** [comment]
The plugin router is configured to use the store_cors
```ts
  const corsOptions = {
    origin: parseCorsOrigins(config.projectConfig.store_cors || ""),
    credentials: true,
  }

  app.use("/mailchimp", router)

  router.use(cors(corsOptions))
```

Are you sure it is properly configured?

**Comment by lfdadev** [comment]
> The plugin router is configured to use the store_cors
> 
> ```ts
>   const corsOptions = {
>     origin: parseCorsOrigins(config.projectConfig.store_cors || ""),
>     credentials: true,
>   }
> 
>   app.use("/mailchimp", router)
> 
>   router.use(cors(corsOptions))
> ```
> 
> Are you sure it is properly configured?

![image](https://github.com/medusajs/medusa/assets/151443436/1b1f20c4-1359-4444-acbd-d7b0b493a758)

I did it on this way. Locally working perfect. I didnt change nothing

**Comment by lfdadev** [comment]
![image](https://github.com/medusajs/medusa/assets/151443436/9dfcfc5c-5892-4610-b870-a5b1c01fa00c)

Mi package

**Comment by lfdadev** [comment]
some fix?

**Comment by davidFCDev** [comment]
@adrien2p 
A mate on the discord told me to try his version and it worked. "medusa-plugin-mailchimp-wine": "^1.1.56" 
My cors error got fixed. If you wanna compare

**Comment by stepmixx** [comment]
something about this? it throws CORS error for me too in production with the version 1.1.49. In development works fine. And only the POST route, the PUT route doesn't work.

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
