### ISSUE TITLE
客户-邮箱

### ISSUE THREAD

**Issue by czw333221** [medusajs/medusa#6015]
### Preliminary Checks

- [x] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

把电子邮箱必须改成手机号码必须或电子邮箱必须二选一

### How can this issue be resolved?

1.
3.
...

### Are you interested in working on this issue?

- [x] I would like to fix this issue

**Comment by srindom** [comment]
Can you please open your issue in English? :)

**Comment by czw333221** [comment]
The only way to register is to change the email registration to a phone number or email.
