### ISSUE TITLE
Data is inconsistent when the system crashes in the middle of handling an event.

### ISSUE THREAD

**Issue by khanh-to-niteco** [medusajs/medusa#6016]
### Describe the bug

When the first transaction is committed (e.x placing an order), the event corresponding to that transaction is saved in the same transaction to the `staged_job` table. Then the enqueuer polls that table to fire the event and delete the event immediately **without waiting for the event handlers to finish**. This results in an issue that the event handler was shutdown in the middle of processing the event (in our PROD) due to other causes (Azure recycles the app,..), the event was not fired again upon restart because it was deleted.

In order to reproduce the issue consistently, we placed a sleep on line 52 in below image, then after the event was fired, we manually shutdown the app, then restarted the app, we could observe that the data was not consistent anymore

![image](https://github.com/medusajs/medusa/assets/71063731/21cc0fa5-4429-42ef-b89b-ad35e3957406)

### System information

Medusa version (including plugins): 1.17.4
Node.js version: 18
Database: Postgres
Operating system: 
Browser (if relevant):

**Comment by adrien2p** [comment]
shouldn't the event still be in redis to be processed by bull?

**Comment by khanh-to-niteco** [comment]
Hi @adrien2p ,

Our tests showed that the events in redis were not re-processed. 

I believe Redis stores data in memory by default, so there are also other cases to handle even if the events could be retried from Redis.

**Comment by olivermrbl** [comment]
Have you tried to [configure the Redis Event Bus](https://docs.medusajs.com/development/events/modules/redis#step-3-add-configuration) to retry failed jobs? 

By default, we only attempt to process a job once. What I fear could happen in your scenario is that BullMQ attempts to process your job from the queue, but because you have killed the process, it expectedly fails. Then, BullMQ will move the job to a `failed` state and not retry it unless configured to do so.

You can read more about how BullMQ handles failed jobs in their [documentation](https://docs.bullmq.io/guide/retrying-failing-jobs).

You can verify if this is the case by inspecting your Redis instance looking for jobs in a failed state, or by configuring the Redis Event Bus like so:
```
eventBus: {
  resolve: "@medusajs/event-bus-redis",
  options: { 
    redisUrl: "...",
    jobOptions: {
      attempts: 2
    }
  },
},
```

**Comment by khanh-to-niteco** [comment]
Hi @olivermrbl ,

Thanks, we will try this.

I have another question regarding idempotency in all of Medusa event handlers. Because with the way the event bus is implemented in Medusa, we need retries to ensure data consistency, but to handle retries properly, we need to handle idempotency.

We will take care of idempotency in our custom code, but need to be sure that Medusa also handles it as well

**Comment by khanh-to-niteco** [comment]
Hi @olivermrbl ,

We have tried your suggestion:

```
eventBus: {
  resolve: "@medusajs/event-bus-redis",
  options: { 
    redisUrl: "...",
    jobOptions: {
      attempts: 2
    } 
  },
},
```

We observed 2 things:

1. Redis event bus (Bullmq) does not retry on startup after crash. I guess the server was shut down unexpectedly and did not have any chance to mark the job as failed to be retried later.
2. Redis event bus (Bullmq) automatically retries when the event handler runs for long time, even when the handler runs successfully. This is expected, since bullmq thinks that the job may have failed and retried, we could solve this with idempotency.

But anyway, do you think that we should use bullmq for event processing?

1. Does it look more like a tool for doing background jobs instead of handling events?
2. Can we get rid of bullmq and delete the staged_job in the same transaction of running all the handlers or delete the staged_job when all handlers have finished successfully? In case there is an issue in any handlers or there is an unexpected shut down. Upon restart, the event loop in Medusa platform can retry the staged job or mark the job as failed in case it exceeds a number of retries? This is similar to dead-letter queues, this case should be rare and usually due to bugs in the system that need developer attention.
3. Should we replace bullmq with another tool more suitable for events processing?
  
With the current design of the event handling in Medusa, the event handlers run on different transactions than the original transaction, so in case there is a commited transaction in between, we may run into some consistency issues, please provide your thoughts.

My initial thought of a solution to this problem is to separate the way we handle the events:

1. Event handlers that need to run in the same transaction of the original transaction dispatching the event. We don't need retries because all are in the same transaction.
2. Event handlers that can be run "async" like the current implementation of Medusa for handlers that don't need transactions or cannot have transactions, like sending an email to another system or sending integration events to other bounded context (in microservices terms). So retries could be done for these kinds of handlers.

To implement this, we need a new subscriber class, and maybe in the `emit` method, we can call all the subscribers that need that same transaction

![image](https://github.com/medusajs/medusa/assets/71063731/1b78e59d-b20d-44f5-b372-8efe2bf2b8cd)
