### ISSUE TITLE
Allow line items with quantity zero

### ISSUE THREAD

**Issue by aldo-roman** [medusajs/medusa#6037]
### Describe the bug

When updating a line item using quantity zero, Medusa removes the line item instead.

The current code assumes that updating the quantity to zero necessarily means deletion.

### System information

Medusa version (including plugins):
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Steps to reproduce the behavior

1. Add items to cart
2. Do `cart.updateLineItem(cartId, lineItemId, { quantity: 0 }`
3. Line item is removed from cart

### Expected behavior

The line item has quantity zero

### Additional context

We have a use case for toggling line items during the checkout process, so users can compare/assess which items make more sense for them to buy. Toggling means removing items from the totals, thus making quantity zero. 

Currently, Medusa removes the item from the cart, which makes it impossible to toggle it back.

If I wanted to remove an item from the cart, I would use the `cart.removeLineItem` method.

As far as I know, there is no workaround, nor a status in line item to mark as disabled.

https://github.com/medusajs/medusa/blob/18de90e603389e5bdb7aa803f36bc9100869607f/packages/medusa/src/api/routes/store/carts/update-line-item.ts#L110-L112

**Comment by srindom** [comment]
We don't plan to support line items with zero quantity. 

Is it a strict requirement to have this done on the backend? Otherwise, you could compute the totals on the front-end.

E.g., have client-side state that keeps track of which items the customer want to exclude from the totals calculation and then sum `items.totals` to show the price? 

Also, out of curiosity - think this is a cool customer experience, would love to know what kinds of products you are selling? :)

**Comment by aldo-roman** [comment]
@srindom We rent billboards. Users usually have ideal/preferred locations and a limited or capped budget, but ultimately have to choose a subset of their preferred billboards to fit the budget.

Making it thru Medusa is easier and faster. I guess the workaround is to add all items to the cart and then subtract the total of disabled items. But this is manual code that we shouldn't need :(

Is it too difficult for Medusa to support zero quantities? How can we make this possible? I am willing to contribute code for this.
