### ISSUE TITLE
Cannot expand items.variant.product in order

### ISSUE THREAD

**Issue by aldo-roman** [medusajs/medusa#6043]
### Describe the bug

When getting an order, I need the product information. The `lookupOrder` method accepts `expand` attribute, but fails when expanding `items.variant.product`, even tho the product is expandable.

### System information

Medusa version (including plugins):
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Steps to reproduce the behavior

1. Look up an order with `expand: 'items.variant.product'`
2. Log fails with `Relations [items.variant.product] are not valid`

### Expected behavior

Order returns correctly

### Code snippets

```ts
const { order } = await medusa.orders.lookupOrder({
  display_id: Number.parseInt(params.display_id),
  email: customer.email,
  expand: 'items.variant.product',
});
```

**Comment by srindom** [comment]
Can you try: `expand: 'items,items.variant,items.variant.product',`

**Comment by aldo-roman** [comment]
Hello @srindom 

I just tried:

```ts
const { order } = await medusa.orders.lookupOrder({
	display_id: ...,
	email: ...,
	expand: 'items,items.variant,items.variant.product',
});
```

It still fails with
```js
{
      type: 'invalid_data',
      message: 'Relations [items.variant.product] are not valid'
}
```

**Comment by olivermrbl** [comment]
This is expected, as you are not currently allowed to expand `items.variant.product` on this endpoint. If you would like to send a PR for it, I would be happy to accept it. 

[This list of allowed relations](https://github.com/medusajs/medusa/blob/8472460f533322cc4535199aa768ac163021bc79/packages/medusa/src/api/routes/store/orders/index.ts#L84) should be updated to contain `items.variant.product`. 

Please add an integration test, if you choose to proceed.

Let me know :)

**Comment by aldo-roman** [comment]
hello @olivermrbl I understand that this is not allowed, but the issue remains. 

IMHO, we should keep this issue open until a fix is provided, as this behaviour is not consistent with the documentation.

I am happy to contribute the code as soon as my current project is launched.
