### ISSUE TITLE
social login returns {"exist": false}

### ISSUE THREAD

**Issue by nadeemdevs** [medusajs/medusa#6047]
### Describe the bug

I'm using `medusa-plugin-auth` package for social logins (google and facebook) and whenever I hit the auth path, I get this response: 
`{ "exists": false }`

It was working well back in November, haven't updated the package or changed any config in google cloud platform or meta developer account
### System information

Medusa version (including plugins): v1.17.4
medusa-plugin-auth:  v1.8.3

### Screenshots

![Screenshot 2024-01-10 151137](https://github.com/medusajs/medusa/assets/65117082/2d1fbb8a-d87b-4398-82f0-4f87cf42ee41)

### Code snippets

`

    /** @type {import('medusa-plugin-auth').AuthOptions} */
    options: {
      google: {
        clientID: process.env.GOOGLE_CLIENT_ID,
        clientSecret: process.env.GOOGLE_CLIENT_SECRET,
        store: {
          callbackUrl: "${process.env.BACKEND_URL}/store/auth/google/cb",
          failureRedirect: "${STORE_URL}/login",
          successRedirect: "${STORE_URL}/",
          authPath: "/store/auth/google",
          authCallbackPath: "/store/auth/google/cb",
        },
      },
      facebook: {
        clientID: process.env.FACEBOOK_CLIENT_ID,
        clientSecret: process.env.FACEBOOK_CLIENT_SECRET,
        store: {
          callbackUrl: "${process.env.BACKEND_URL}/store/auth/facebook/cb",
          failureRedirect: "${STORE_URL}/login",
          successRedirect: "${STORE_URL}/",
          // authPath: "/store/auth/facebook",
          authCallbackPath: "/store/auth/facebook/cb",
        },
      },
    },
  },
`

### Additional context

Add any other context about the problem here

**Comment by srindom** [comment]
medusa-plugin-auth is a community plugin please open it in the repo here instead: https://github.com/adrien2p/medusa-plugins
