### ISSUE TITLE
utils_1.SearchUtils.isSearchService is not a function

### ISSUE THREAD

**Issue by Kushal-starr** [medusajs/medusa#6070]
Suddenly I started getting 'utils_1.SearchUtils.isSearchService is not a function' error while I'm running the servers on any environment.

TypeError: utils_1.SearchUtils.isSearchService is not a function
    at /Users/0366mpind/Documents/commerce_rails_api/node_modules/@medusajs/medusa/dist/loaders/plugins.js:524:70
    at step (/Users/0366mpind/Documents/commerce_rails_api/node_modules/@medusajs/medusa/dist/loaders/plugins.js:56:23)
    at Object.next (/Users/0366mpind/Documents/commerce_rails_api/node_modules/@medusajs/medusa/dist/loaders/plugins.js:37:53)
    at /Users/0366mpind/Documents/commerce_rails_api/node_modules/@medusajs/medusa/dist/loaders/plugins.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/0366mpind/Documents/commerce_rails_api/node_modules/@medusajs/medusa/dist/loaders/plugins.js:27:12)
    at /Users/0366mpind/Documents/commerce_rails_api/node_modules/@medusajs/medusa/dist/loaders/plugins.js:473:99
    at Array.map (<anonymous>)
    at /Users/0366mpind/Documents/commerce_rails_api/node_modules/@medusajs/medusa/dist/loaders/plugins.js:473:72
    at step (/Users/0366mpind/Documents/commerce_rails_api/node_modules/@medusajs/medusa/dist/loaders/plugins.js:56:23)

Any suggestions will be help to resolve this issue. Thanks!

**Comment by estubmo** [comment]
Having the same issue. Possibly related to changes in packages/medusa-interfaces/src/search-service.js

**Comment by olivermrbl** [comment]
Can I get you to ensure all your Medusa packages are running on the latest version? This issue is caused by breaking changes in the most recent release.

**Comment by estubmo** [comment]
Indeed, it was. I had updated all packages, but somehow @medusajs/medusa was stuck on 1.19. Updating to 1.20 solved the issue.

**Comment by igops** [comment]
This is a really frustrating bug. Perhaps medusa released a new module without incrementing the version? Actually, it broke complete setup based on v1.19 :(

**Comment by olivermrbl** [comment]
@igops, did the issue persist after upgrading all your Medusa packages to the latest version?

**Comment by igops** [comment]
@olivermrbl upgrade to 1.20 helped, we were forced to upgrade actually because of that. What I'm saying is that Medusa team should not break the existing (LTS?) version by releasing an inconsistent dependency. If a dep contains breaking changes, it should not be installed **automatically** as it happened today.

**Comment by menty44** [comment]
> This is a really frustrating bug. Perhaps medusa released a new module without incrementing the version? Actually, it broke complete setup based on v1.19 :(

This has worked for me. NB: make sure you delete the node_modules
