### ISSUE TITLE
Content localizations

### ISSUE THREAD

**Issue by shadoo77** [medusajs/medusa#6076]
Hello
I've just checked the documentation and played around, It literally fits my requirements, EXCEPT one thing which is multilingual content especially product's title and description.
I took a look at upcoming features and found nothing related.
Are you aiming to add this in nearly future ?

Thanks in advance
Shadi

**Comment by shahednasser** [comment]
Hi @shadoo77 , I believed I answered you on discord but just for reference, to localize CMS content in Medusa, you need to use external services such as Contentful and Strapi.

You can follow the documentation for Contentful plugin here: https://docs.medusajs.com/plugins/cms/contentful

As for Strapi, I'll be updating the docs soon to use instructions for this community plugin: https://github.com/SGFGOV/medusa-strapi-repo/tree/master

You can also refer to our plugins library for available community CMS plugins: https://medusajs.com/plugins/?filters=CMS

If you want to create your own plugin, refer to this guide: https://docs.medusajs.com/development/plugins/create

**Comment by shadoo77** [comment]
Thanks anyway for your reply
Now I'm thinking more of develop a plugin to do the job
But yea I appreciate it
