### ISSUE TITLE
Typo in docs: createFulfillment example

### ISSUE THREAD

**Issue by stephanboersma** [medusajs/medusa#6082]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

https://docs.medusajs.com/modules/carts-and-checkout/backend/add-fulfillment-provider#createfulfillment

`items: LineItem` should be `items: LineItem[]`

```
class MyFulfillmentService extends AbstractFulfillmentService {
  // ...
  async createFulfillment(
    data: Record<string, unknown>,
    items: LineItem[],
    order: Order,
    fulfillment: Fulfillment
  ) {
    // No data is being sent anywhere
    // No data to be stored in the fulfillment's data object
    return {}
  }
}
```

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by olivermrbl** [comment]
@stephanboersma, nice catch. We'll get this updated as soon as possible.

cc @shahednasser
