### ISSUE TITLE
Problem when adding products/variants to cart with same currency configured for different regions

### ISSUE THREAD

**Issue by kenny007** [medusajs/medusa#6091]
## Bug report
Problem when adding products/variants to the cart with same currency configured for different regions
### Describe the bug
I have created different regions with the same currency and have different prices configured for the variants in the different regions but the prices of the variants are in the same currency, when I add a variant to the cart it selects the lowest price using the price of the variant in another region instead (So it uses the lowest price in that currency which happens to be in another region). I've attached a screenshot of the behavior, the price crossed out is the one that is supposed to be used instead of the lowest one shown in the cart which is the price configured in another region. The price configured for that region for the variant should be used instead of using the lowest price from another region.

### System information

Medusa version (including plugins):
Node.js version: ^1.17.2
Database:
Operating system: Windows, Linux
Browser (if relevant):

### Steps to reproduce the behavior

1. Create different regions e.g AU and AS)
2. Configure the same currency e.g NGN for both regions
3. Add a variant and configure prices for the different regions in the same currency. Ensure that one price is higher than the other
4. Go to the storefront and try to add the variant to the cart. It will use the lowest price from another region that is of the same currency.

### Expected behavior

The expected behavior is that the price for the region in that currency should be used instead of the lowest price available in that currency across regions. It should consider the region when making this selection.

### Screenshots
![medusa_bug](https://github.com/medusajs/medusa/assets/5065193/a877412d-3895-4f7e-93d9-13a50e461d8a)

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by adrien2p** [comment]
Is the region specified on your cart? you might need to specify it in order to prevent this miss match

**Comment by kenny007** [comment]
@adrien2p, yes the region is specified in the cart. Or do you mean the cause of the issue is that the cart is not updated with the new region when changing the region on the UI?

**Comment by igotDiamonds** [comment]
Can confirm, even after updating cart with `region_id`, all calculations and prices remain as for the default region.

**Comment by haiderchristoph** [comment]
Can confirm the described behaviour as-well. I would expect, that the workflow that adds a line item respects the cart's `region_id`, but unfortunately it does not.

Hope there will be a fix for this soon!

**Comment by TCAA-Web** [comment]
Can confirm this issue. Spent hours debugging my code, but no matter what i do the region_id on the cart is never updated. However. It seems as if the response from my updateCart mutation actually returns the updated cart, it just never gets set in the provider.
