### ISSUE TITLE
Cannot read properties of undefined (reading '0'))

### ISSUE THREAD

**Issue by skdishansachin** [medusajs/medusa#6097]
## Bug report
TypeError when creating an admin user (Cannot read properties of undefined (reading '0'))

### Describe the bug

I followed the instructions in the documentation to set up a new project. After completing the initial setup, I was directed to the onboarding process where I had to input my password and confirm it. The email I provided during project creation was used for this process. However, after inputting my password and confirming it, an error message was displayed.

### System information

Medusa version (including plugins): 1.20.0
Node.js version: v20.10.0
Database: postgres 16
Operating system: Debian (GitHub codespace)
Browser (if relevant): chrome

### Steps to reproduce the behavior

1. The general steps for initial project setup.
2.  Enter the password and password comfirmation
3. Click the `create account`

### Expected behavior

I would like to see After the admin account creation I was redirected to the admin panel.

### Screenshots

![image](https://github.com/medusajs/medusa/assets/134765302/bebc7b0c-bb38-456f-9b14-d4ce31f9a218)

### Code snippets

```
TypeError
Cannot read properties of undefined (reading '0')
Call Stack
 i
  main.bundle.js:44:227889
 undefined
  _cache_admin_src_pages_invite_tsx.chunk.js:1:7303
 undefined
  _cache_admin_src_pages_invite_tsx.chunk.js:1:6474
 Object.throw
  _cache_admin_src_pages_invite_tsx.chunk.js:1:6579
 D
  _cache_admin_src_pages_invite_tsx.chunk.js:1:2968
 c
  _cache_admin_src_pages_invite_tsx.chunk.js:1:7481

```

Thank you.

**Comment by shahednasser** [comment]
Can you ensure that in your GitHub workspace port forwarding is configured for port `9000`? You can refer to [this guide](https://docs.github.com/en/codespaces/developing-in-a-codespace/forwarding-ports-in-your-codespace) on how to do it.

**Comment by skdishansachin** [comment]
> Can you ensure that in your GitHub workspace port forwarding is configured for port `9000`? You can refer to [this guide](https://docs.github.com/en/codespaces/developing-in-a-codespace/forwarding-ports-in-your-codespace) on how to do it.

Yes the port forwarding is configured but still the error persists

**Comment by shahednasser** [comment]
If you try to login and you check the network tab in the developer tools, are the requests being sent to `localhost:9000`? And are they successful?

**Comment by skdishansachin** [comment]
> If you try to login and you check the network tab in the developer tools, are the requests being sent to `localhost:9000`? And are they successful?

There is a resource is not found error

**Comment by shahednasser** [comment]
Can you show me a screenshot of the network tab? Especially the login request.

**Comment by skdishansachin** [comment]
![image](https://github.com/medusajs/medusa/assets/134765302/6c1b3fce-1640-472c-ae5a-bd6099d8472c)

Port forwarding

![image](https://github.com/medusajs/medusa/assets/134765302/66e11c35-83bc-46ab-bab6-e5fc412120f6)

**Comment by shahednasser** [comment]
This is a CORS error since GitHub codespaces is exposing the address `127.0.0.1:7001`. Can you add the following variable to your `.env` file:

```bash
ADMIN_CORS=http://localhost:7001,http://127.0.0.1:7001
```

Then restart the backend and try again

**Comment by srindom** [comment]
@skdishansachin did Shahed's suggesting solve your problem? If so please close the issue :)

**Comment by skdishansachin** [comment]
> @skdishansachin did Shahed's suggesting solve your problem? If so please close the issue :)

No, I still have the problem. Anyway changed my mind about creating an e-commerce store from Sketch. @shahednasser Thank you for the effort.

**Comment by Moreiq** [comment]
Hello, the issue persists in the latest version.

**Comment by cgonzaleztx** [comment]
I encountered the exact same issue.

**Comment by shahednasser** [comment]
Hi @cgonzaleztx can you give me the details of your setup process? Including what OS / Node version you're using
