### ISSUE TITLE
Swap order

### ISSUE THREAD

**Issue by vishwaskhd** [medusajs/medusa#6123]
### Describe the bug
 When exchanging order and trying to create fulfillment it shows "Cannot fulfill an swap that doesn't have shipping methods"  even after selecting shipping option.

### System information

Medusa version (including plugins):
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Steps to reproduce the behavior

1. Go to Admin panel
2. Click on order and there go to order details , In that in timeline click on "Register Exchange"
3. In register exchange after selecting all the options and also a shipping method creating a exchange.
4. After that in Timeline select fulfill exchange. In that create fulfillment box will appear and then on clicking create fulfillment it shows me error
5. See error

### Expected behavior

Even after selecting the shipping method, it shows me no shipping method available. Might be the issue that shipping address is not saving in database while creating a swap.

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by srindom** [comment]
@vishwaskhd - thanks for opening the issue.

When you create the exchange you select the shipping option to be used for the return shipment. (I realize this isn't super clear from the current UI - we'll look into that cc: @kasperkristensen, @ludvig18)

The error you are getting refers to the outbound shipment not being set. The typical flow that an exchange would go through is this:

1. Admin creates exchange from dashboard.
2. Customer gets link with exchange details.
3. Customer selects the shipping method they prefer and pays any difference that may arise from the exchange.
4. Exchange gets processed and fulfilled.

There is not currently a way to select the shipping method for an exchange from the admin dashboard so without the customer flow (or a customization) you will not be able to fulfill the exchange.

**Comment by vishwaskhd** [comment]
Okay @srindom , Where did customer gets that link, as I can not find in email?

**Comment by srindom** [comment]
You need to set up an email provider like SendGrid and configure it to send swap creation emails. In your store settings, you can specify the link that the customer should go to in your storefront to confirm their swap. 

Additionally, you have to build out the storefront experience for managing the swap confirmation process. You can read more about it here: https://docs.medusajs.com/modules/orders/storefront/create-swap.

I will close this issue for now as it isn't a bug - feel free to open a discussion instead if you want further input :)

**Comment by sumanchy88** [comment]
Hi @vishwaskhd - I need some help on the same issue. Is your issue resolved and if yes, how you managed to pass the shipping method from store front and process the payment flow for swap order. Could you please help sharing some information on it. Thanks.
