### ISSUE TITLE
Unhandled Runtime Error: adapter is not a function

### ISSUE THREAD

**Issue by nabilAparicio** [medusajs/medusa#6133]
**Bug Report**
**Describe the Bug**
I am encountering an issue with MedusaJS when executing requests on NextJS Edge runtime. The bug seems to be associated with Axios, displaying the error: 'Unhandled Runtime Error: adapter is not a function.'

**System Information**
Medusa Version: "@medusajs/medusa-js": "^6.1.5", "medusa-react": "^9.0.13"
Node.js Version: [Not relevant]
Database: [Not relevant]
Operating System: [Not relevant]
Browser: [Not relevant]

**Steps to Reproduce the Behavior**
Initialize a Next.js project.
Install medusajs and medusa-react.
Initialize an instance of a MedusaJS client.
Switch Page runtime to edge
Attempt to fetch data using a method such as medusaClient.products.list().

**Expected Behavior**
The expectation is to successfully fetch data in the same manner as when using a Node.js runtime environment.

**Screenshots**
_yarn run dev_
![image](https://github.com/medusajs/medusa/assets/87939719/6c2c11f9-281c-4b9b-90c0-a98820b8cbd5)

_yarn build
yarn start_
![image](https://github.com/medusajs/medusa/assets/87939719/c4ea434d-8b32-40fb-9e41-59e646421def)

**Code Snippets**
A minimal repository reproducing the bug can be found here: [MedusaJS Minimal Bug Reproduction](https://github.com/nabilAparicio/MedusaJS-MinimalBugRepro)

**Comment by lekterable** [comment]
same issue here
