### ISSUE TITLE
Product Categories are not appearing with feature flag enabled

### ISSUE THREAD

**Issue by AlexTechNoir** [medusajs/medusa#6135]
### Describe the bug

Good day!

I wanted to try Product Categories feature. I enabled both `MEDUSA_FF_PRODUCT_CATEGORIES=true` and `module.exports = { featureFlags: { product_categories: true, }, }` flags, just to be sure, run `npx medusa migrations run`, but still don't see this feature in Admin (I suppose it should appear either among the tabs on the left or inside the Products tab, correct me if I'm wrong)

### System information

Medusa version (including plugins): 1.19
Node.js version: 18.16.1
Database: PostgreSQL
Operating system: Win 10
Browser (if relevant):

### Steps to reproduce the behavior

1. Setup Medusa project with PostgreSQL
2. Enable Product Categories flag, run `npx medusa migrations run`
3. See error

### Expected behavior

Working Product Categories feature

**Comment by xyzones** [comment]
@AlexTechNoir when you start the app do you see

`info:    Using flag MEDUSA_FF_PRODUCT_CATEGORIES from environment with value true` or similar

after compilation?

**Comment by AlexTechNoir** [comment]
No, nothing like that... 

The only suspicious message I see is some error at the start of launch:
```bash
Error: Cannot find module '@medusajs/admin'
Require stack:
- C:\Users\Alex\Desktop\Project\backend\node_modules\@medusajs\medusa\dist\commands\utils\resolve-admin-cli.js        
- C:\Users\Alex\Desktop\Project\backend\node_modules\@medusajs\medusa\dist\commands\develop.js
- C:\Users\Alex\Desktop\Project\backend\node_modules\@medusajs\medusa-cli\dist\create-cli.js
- C:\Users\Alex\Desktop\Project\backend\node_modules\@medusajs\medusa-cli\dist\index.js
- C:\Users\Alex\Desktop\Project\backend\node_modules\@medusajs\medusa\dist\bin\medusa.js
- C:\Users\Alex\Desktop\Project\backend\node_modules\@medusajs\medusa\cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Function.resolve (node:internal/modules/cjs/helpers:116:19)
    at resolveAdminCLI (C:\Users\Alex\Desktop\Project\backend\node_modules\@medusajs\medusa\dist\commands\utils\resolve-admin-cli.js:10:46)
    at C:\Users\Alex\Desktop\Project\backend\node_modules\@medusajs\medusa\dist\commands\develop.js:137:58
    at step (C:\Users\Alex\Desktop\Project\backend\node_modules\@medusajs\medusa\dist\commands\develop.js:44:23)      
    at Object.next (C:\Users\Alex\Desktop\Project\backend\node_modules\@medusajs\medusa\dist\commands\develop.js:25:53)
    at C:\Users\Alex\Desktop\Project\backend\node_modules\@medusajs\medusa\dist\commands\develop.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Alex\Desktop\Project\backend\node_modules\@medusajs\medusa\dist\commands\develop.js:15:12) 
    at default_1 (C:\Users\Alex\Desktop\Project\backend\node_modules\@medusajs\medusa\dist\commands\develop.js:93:12) 
{
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Alex\\Desktop\\Project\\backend\\node_modules\\@medusajs\\medusa\\dist\\commands\\utils\\resolve-admin-cli.js',
    'C:\\Users\\Alex\\Desktop\\Project\\backend\\node_modules\\@medusajs\\medusa\\dist\\commands\\develop.js',      
    'C:\\Users\\Alex\\Desktop\\Project\\backend\\node_modules\\@medusajs\\medusa-cli\\dist\\create-cli.js',
    'C:\\Users\\Alex\\Desktop\\Project\\backend\\node_modules\\@medusajs\\medusa-cli\\dist\\index.js',
    'C:\\Users\\Alex\\Desktop\\Project\\backend\\node_modules\\@medusajs\\medusa\\dist\\bin\\medusa.js',
    'C:\\Users\\Alex\\Desktop\\Project\\backend\\node_modules\\@medusajs\\medusa\\cli.js'
```

and then it launches successfully, but I don't think it is related, it was happening before enabling flags

**Comment by AlexTechNoir** [comment]
Yes, I see it

`info:    Using flag MEDUSA_FF_PRODUCT_CATEGORIES from environment with value true`

**Comment by xyzones** [comment]
@AlexTechNoir Well, it should show up on the right ...

![image](https://github.com/medusajs/medusa/assets/1039118/3218d833-2753-4bd3-b890-920b79a8efc4)

**Comment by AlexTechNoir** [comment]
Doesn't show... During the server launch I also have an error like this:
```bash
Error: Cannot find module '@medusajs/admin'
Require stack:
- C:\Users\Alex\Desktop\Project\backend\node_modules\@medusajs\medusa\dist\commands\utils\resolve-admin-cli.js
- C:\Users\Alex\Desktop\Project\backend\node_modules\@medusajs\medusa\dist\commands\develop.js
- C:\Users\Alex\Desktop\Project\backend\node_modules\@medusajs\medusa-cli\dist\create-cli.js
- C:\Users\Alex\Desktop\Project\backend\node_modules\@medusajs\medusa-cli\dist\index.js
- C:\Users\Alex\Desktop\Project\backend\node_modules\@medusajs\medusa\dist\bin\medusa.js
- C:\Users\Alex\Desktop\Project\backend\node_modules\@medusajs\medusa\cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Function.resolve (node:internal/modules/cjs/helpers:116:19)
    at resolveAdminCLI (C:\Users\Alex\Desktop\Project\backend\node_modules\@medusajs\medusa\dist\commands\utils\resolve-admin-cli.js:10:46)
    at C:\Users\Alex\Desktop\Project\backend\node_modules\@medusajs\medusa\dist\commands\develop.js:137:58
    at step (C:\Users\Alex\Desktop\Project\backend\node_modules\@medusajs\medusa\dist\commands\develop.js:44:23)        
    at Object.next (C:\Users\Alex\Desktop\Project\backend\node_modules\@medusajs\medusa\dist\commands\develop.js:25:53) 
    at C:\Users\Alex\Desktop\Project\backend\node_modules\@medusajs\medusa\dist\commands\develop.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Alex\Desktop\Project\backend\node_modules\@medusajs\medusa\dist\commands\develop.js:15:12)   
    at default_1 (C:\Users\Alex\Desktop\Project\backend\node_modules\@medusajs\medusa\dist\commands\develop.js:93:12) { 
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Alex\\Desktop\\Project\\backend\\node_modules\\@medusajs\\medusa\\dist\\commands\\utils\\resolve-admin-cli.js',
    'C:\\Users\\Alex\\Desktop\\Project\\backend\\node_modules\\@medusajs\\medusa\\dist\\commands\\develop.js',        
    'C:\\Users\\Alex\\Desktop\\Project\\backend\\node_modules\\@medusajs\\medusa-cli\\dist\\create-cli.js',
    'C:\\Users\\Alex\\Desktop\\Project\\backend\\node_modules\\@medusajs\\medusa-cli\\dist\\index.js',
    'C:\\Users\\Alex\\Desktop\\Project\\backend\\node_modules\\@medusajs\\medusa\\dist\\bin\\medusa.js',
    'C:\\Users\\Alex\\Desktop\\Project\\backend\\node_modules\\@medusajs\\medusa\\cli.js'
  ]
}
```

then it runs successfully. Can it be related?

**Comment by xyzones** [comment]
Possible, how you did the upgrade?

**Comment by AlexTechNoir** [comment]
I'm always following the docs when upgrading

Edit: I installed `@medusajs/admin` module into backend, error is gone, but nothing's changed, no Categories still, I guess it's not related...

**Comment by xyzones** [comment]
@AlexTechNoir can you fire up a test env with a fresh backend? Do a copy of your db and connect to it and lets see if still not showing

**Comment by AlexTechNoir** [comment]
Created a new backend repo, connected to current DB, enabled flags, run migrations, yet still nothing. Can it be interoperability issue? I had some in the past just because my OS wasn't compatible

**Comment by xyzones** [comment]
@AlexTechNoir to eliminate data issue would you mind to try with fresh db?

**Comment by AlexTechNoir** [comment]
K, it took me a while to understand why feature is not working, TLDR: because my project was created before Medusa v1.8 with separate repos for backend and Admin frontent

I was trying to enable the feature in separate Admin repo, and I assume new features are meant to be for the newer version of Admin, which, since v1.8, is a package that is installed inside backend repo (also, it explains `Cannot find module '@medusajs/admin'` error in newly updated versions of Medusa backend - Admin package is not installing during backend updates)

Currently, I created a fresh test Medusa backend with fresh database, launched my older separate Admin repo and, of course, no Categories feature appeared. But when I launched newer Admin from freshly created backend - voila, Categories are there

So, I guess, it's not possible to enable this feature in older versions of Admin that lives in separate repo

@xyzones thank you for your time!

**Comment by xyzones** [comment]
You should be able to update the old repo for sure.

**Comment by AlexTechNoir** [comment]
I'll try to update backend correctly, but the problem is I made lots of modifications in Admin dashboard for the custom features, and I can't just copy them into new one, because there is the whole new way to configure new Admin, like "widget injections" and so on, and JSX of Admin is no longer directly accessible, since it's a package now

**Comment by iamkabelomoobi** [comment]
> @AlexTechNoir Well, it should show up on the right ...
> 
> ![image](https://private-user-images.githubusercontent.com/1039118/298639175-3218d833-2753-4bd3-b890-920b79a8efc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwOTMzNTYsIm5iZiI6MTcyODA5MzA1NiwicGF0aCI6Ii8xMDM5MTE4LzI5ODYzOTE3NS0zMjE4ZDgzMy0yNzUzLTRiZDMtYjg5MC05MjBiNzlhOGVmYzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDVUMDE1MDU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmIzMTRmZDg5YjM5MzY1NjkxYjcyM2QyNzNkODU4YWFmZWY5YTg4ZmJiMDFlMTMxNzJiNDVjZjYxOTZjZDE5NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.nD6wwrJPGHOg1i2hLkx7qDIyI7MVevZOZZKL6q6oq74)

Hi, i set the env and ran ```npx medusa migrations run``` but when i add a new category i get an error occured and when i try again i get duplicate category error, but i cant see any cateegories.
