### ISSUE TITLE
Not able to use MedusaContainer in a FulfillmentProvider.

### ISSUE THREAD

**Issue by stephanboersma** [medusajs/medusa#6146]
### Describe the bug

When using `container.resolve("logger")` in my fulfillment provider, the backend does not load the provider and outputs:
`warn:    You don't have any fulfillment provider plugins installed. You may want to add one to your project.`

### System information

I recently updated all medusa packages to latest version.

Medusa version (including plugins): 1.20.0
Node.js version: 18.17
Database: postgres latest
Operating system: MacOS

```json
{
"dependencies": {
    "@medusajs/admin": "7.1.10",
    "@medusajs/cache-inmemory": "^1.8.10",
    "@medusajs/cache-redis": "^1.9.0",
    "@medusajs/event-bus-local": "^1.9.7",
    "@medusajs/event-bus-redis": "^1.8.10",
    "@medusajs/file-local": "^1.0.2",
    "@medusajs/medusa": "1.20.0",
    "@medusajs/utils": "^1.11.3",
    "@medusajs/workflows-sdk": "^0.1.1",
    "@tanstack/react-query": "4.22.0",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "dotenv": "16.0.3",
    "express": "^4.17.2",
    "jsonwebtoken": "^9.0.2",
    "medusa-fulfillment-manual": "^1.1.39",
    "medusa-interfaces": "^1.3.8",
    "medusa-payment-manual": "^1.0.24",
    "medusa-payment-stripe": "^6.0.7",
    "medusa-plugin-meilisearch": "^2.0.10",
    "prism-react-renderer": "^2.0.4",
    "typeorm": "^0.3.19"
  },
  "devDependencies": {
    "@babel/cli": "^7.14.3",
    "@babel/core": "^7.14.3",
    "@babel/preset-typescript": "^7.21.4",
    "@medusajs/medusa-cli": "^1.3.22",
    "@types/express": "^4.17.13",
    "@types/jest": "^27.4.0",
    "@types/jsonwebtoken": "^9.0.5",
    "@types/node": "^17.0.8",
    "@typescript-eslint/eslint-plugin": "^6.13.1",
    "babel-preset-medusa-package": "^1.1.19",
    "cross-env": "^7.0.3",
    "eslint": "^8.54.0",
    "jest": "^27.3.1",
    "openapi-typescript-codegen": "^0.27.0",
    "rimraf": "^3.0.2",
    "ts-jest": "^27.0.7",
    "ts-loader": "^9.2.6",
    "typescript": "^5.3.3"
  },
}
```

### Steps to reproduce the behavior

1. Create a fulfillment provider that extends AbstractFulfillmentProvider
2. call `super(container)` in the constructor
3. Attempt to resolve a service: `container.resolve("logger")`
4. Observe that the fulfillment provider is not recognized at startup

### Expected behavior

I expect the provider to be available and usable when using the MedusaContainer to resolve services

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

Working example:
```typescript
export default class ShipmondoFulfillmentService extends AbstractFulfillmentService {

    static identifier = "shipmondo-fulfillment";

    private logger_: Logger;

    constructor(container: MedusaContainer) {
        super(container);
        // this.logger_ = container.resolve("logger");
    }
}
```

Not working example:
```typescript
export default class ShipmondoFulfillmentService extends AbstractFulfillmentService {

    static identifier = "shipmondo-fulfillment";

    private logger_: Logger;

    constructor(container: MedusaContainer) {
        super(container);
        this.logger_ = container.resolve("logger");
    }
```
### Additional context

Add any other context about the problem here

**Comment by srindom** [comment]
When accessing the container from services you can simply do `container.[dependency]`; the resolve method shouldn't be used. 

I.e., this should work
```
export default class ShipmondoFulfillmentService extends AbstractFulfillmentService {

    static identifier = "shipmondo-fulfillment";

    private logger_: Logger;

    constructor(container: MedusaContainer) {
        super(container);
        this.logger_ = container.logger;
    }
}
```

**Comment by stephanboersma** [comment]
Hi @srindom ,

Thank you for the quick response in the weekend :) I think it is worth adding to the docs how to resolve dependencies in services - especially when it is done differently depending on the context. Subscribers and api routes use `.resolve`.

Typescript does not let me access the dependency directly. Any idea what might be wrong? If I remove the typing then container is `any`. I'm not super stoked about that though.

<img width="790" alt="image" src="https://github.com/medusajs/medusa/assets/32750681/13b6bed9-2631-45b0-8327-3c7d731f0e8c">
