### ISSUE TITLE
Cyclic dependencies problem for searchService

### ISSUE THREAD

**Issue by kim-hanho** [medusajs/medusa#6196]
### Describe the bug

```
AwilixResolutionError: Could not resolve 'shippingProfileService'. Cyclic dependencies detected.

Resolution path: shippingProfileService -> productService -> searchService -> algoliaService -> orderService -> shippingProfileService
```

By following documentation of [https://docs.medusajs.com/development/search/create](https://docs.medusajs.com/development/search/create), when we use ProductService (or other services such as orderService) using dependency injection in constructor, the error came out.

### System information

Medusa version (including plugins): 1.20.0
Node.js version: v18.17
Database:
Operating system:
Browser (if relevant):

### Steps to reproduce the behavior

Do example code of injecting productService [https://docs.medusajs.com/development/search/create#constructor](https://docs.medusajs.com/development/search/create#constructor)
```typescript
// ...
import { ProductService } from "@medusajs/medusa"

type InjectedDependencies = {
  productService: ProductService
}

class MySearchService extends AbstractSearchService {
  // ...
  protected readonly productService_: ProductService

  constructor({ productService }: InjectedDependencies) {
    // @ts-expect-error prefer-rest-params
    super(...arguments)
    this.productService_ = productService

    // you can also initialize a client that
    // communicates with a third-party service.
    this.client = new Client(options)
  }

  // ...
}
```

### Expected behavior

No error

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏

**Comment by FaZeRs** [comment]
I'm facing the same issue. This happens if I want to inject any dependency into SearchService
