### ISSUE TITLE
[CartService]: Merge lines if identical line-item exists

### ISSUE THREAD

**Issue by srindom** [medusajs/medusa#62]
If posting a line item with a variant that the customer already has in her cart. The quantity should increase instead of a new item being created.

**Comment by olivermrbl** [comment]
Haven't you already added functionality, that supports this? Maybe I am mistaken.
```
async addLineItem(cartId, lineItem) {
    ...
    const currentItem = cart.items.find(line =>
      _.isEqual(line.content, validatedLineItem.content)
    )
    ...
}
```
