### ISSUE TITLE
Simple entity extended according to documentation throws a strange error

### ISSUE THREAD

**Issue by zajacjakub** [medusajs/medusa#6226]
### Describe the bug

Extending an entity in newly created MedusaJS app does not work. I am trying to to add a simple string attribute **"customAttribute"** to the **"cart"** entity and set the value with store api for updating the cart. I am trying to do that according to the documentation, following it in every step. I managed to reproduce the bug several times and I always end up with the same error message I cant understand.

### System information

Medusa version (including plugins):
`"@medusajs/admin": "7.1.10",
    "@medusajs/cache-inmemory": "^1.8.9",
    "@medusajs/cache-redis": "^1.8.9",
    "@medusajs/event-bus-local": "^1.9.7",
    "@medusajs/event-bus-redis": "^1.8.10",
    "@medusajs/file-local": "^1.0.3",
    "@medusajs/medusa": "1.20.1",`
Node.js version: v20.11.0
Database: postgres
Operating system: Windows 11 Pro

### Steps to reproduce the behavior

1. Create clean new MedusaJS app with Next.js storefront:
`npx create-medusa-app@latest`
2. Extend the entity according to the documentation:
I want to extend **cart** entity with string **customAttribute**:

Model:
**src/models/cart.ts:**
```
import {Column, Entity} from "typeorm"
import {Cart as MedusaCart} from "@medusajs/medusa"

@Entity()
export class Cart extends MedusaCart {
    @Column()
    customAttribute: string
}
```

Typescript definition:
**src/index.d.ts**
```
export declare module "@medusajs/medusa/dist/models/cart" {
    declare interface Cart {
        customAttribute: string;
    }
}
```

Migration:
**1706207465587-CartAddCustomAttributeCollumn.ts**
```
import { MigrationInterface, QueryRunner } from "typeorm"

export class CartAddCustomAttributeCollumn1706207465587 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(
            "ALTER TABLE \"cart\"" +
            " ADD COLUMN \"customAttribute\" text"
        )
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(
            "ALTER TABLE \"cart\" DROP COLUMN \"customAttribute\""
        )
    }

}
```

3. Building the project:
`npm run build`

4. Running the migration properly changes the database:
`npx medusa migrations run`

I checked the database schema and the collumn is there:
<img width="533" alt="image" src="https://github.com/medusajs/medusa/assets/67701008/b377ccf1-f89f-40b5-a0f3-2880bcf57c43">

5. Extend the validator so the customAttribute can be set from store:
**src/api/index.ts:**

```
import {registerOverriddenValidators} from "@medusajs/medusa"
import {
    StorePostCartsCartReq as MedusaStorePostCartsCartReq,
} from "@medusajs/medusa/dist/api/routes/store/carts/update-cart"
import {IsString} from "class-validator"

class StorePostCartsCartReq extends MedusaStorePostCartsCartReq {
    @IsString()
    customAttribute: string
}

registerOverriddenValidators(StorePostCartsCartReq)
```

6. Extending the Cart Store response fields:
**src/loaders/extend-cart-fields.ts**

```
export default async function () {
    const imports = (await import(
        "@medusajs/medusa/dist/api/routes/store/carts/index"
        )) as any
    imports.defaultStoreCartFields = [
        ...imports.defaultStoreCartFields,
        "customAttribute",
    ]
}
```

7. Build the project:
`npm run build`

8. Run the app:
`npm run dev`

9. Create a test product in admin, run the storefront to create a Cart in database.

10. Try to update the existing cart with customAttribute through Postman:
`POST http://localhost:9000/store/carts/cart_01HN0Z69GA2JZE36MDM3KQR68G`
Payload:
`
{
    "customAttribute": "test"
}
`
Response:
`
{
    "code": "unknown_error",
    "type": "unknown_error",
    "message": "An unknown error occurred."
}
`
MedusaJS log throws error:
<img width="1204" alt="image" src="https://github.com/medusajs/medusa/assets/67701008/56274aea-996c-4628-9149-41ff273af4e6">

`
error:   syntax error at or near ")"
QueryFailedError: syntax error at or near ")"
    at PostgresQueryRunner.query (F:\Projects\gargantua\be\node_modules\typeorm\driver\postgres\PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SelectQueryBuilder.loadRawResults (F:\Projects\gargantua\be\node_modules\typeorm\query-builder\SelectQueryBuilder.js:2183:25)
    at async SelectQueryBuilder.executeEntitiesAndRawResults (F:\Projects\gargantua\be\node_modules\typeorm\query-builder\SelectQueryBuilder.js:2034:26)
    at async SelectQueryBuilder.getRawAndEntities (F:\Projects\gargantua\be\node_modules\typeorm\query-builder\SelectQueryBuilder.js:684:29)
    at async SelectQueryBuilder.getMany (F:\Projects\gargantua\be\node_modules\typeorm\query-builder\SelectQueryBuilder.js:750:25)
    at async Promise.allSettled (index 0) {
  query: 'SELECT "cart"."id" AS "cart_id", "billing_address"."id" AS "billing_address_id", "billing_address"."created_at" AS "billing_address_created_at", "billing_address"."updated_at" AS "billing_address_updated_at", "billing_address"."deleted_at" AS "billing_address_deleted_at", "billing_address"."customer_id" AS "billing_address_customer_id", "billing_address"."company" AS "billing_address_company", "billing_address"."first_name" AS "billing_address_first_name", "billing_address"."last_name" AS "billing_address_last_name", "billing_address"."address_1" AS "billing_address_address_1", "billing_address"."address_2" AS "billing_address_address_2", "billing_address"."city" AS "billing_address_city", "billing_address"."country_code" AS "billing_address_country_code", "billing_address"."province" AS "billing_address_province", "billing_address"."postal_code" AS "billing_address_postal_code", "billing_address"."phone" AS "billing_address_phone", "billing_address"."metadata" AS "billing_address_metadata" FROM "public"."cart" "cart" LEFT JOIN "public"."address" "billing_address" ON "billing_address"."id"="cart"."billing_address_id" AND ("billing_address"."deleted_at" IS NULL) WHERE ( "cart"."id" IN () ) AND ( "cart"."deleted_at" IS NULL )',
  parameters: [],
  driverError: error: syntax error at or near ")"
      at F:\Projects\gargantua\be\node_modules\pg\lib\client.js:526:17
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async PostgresQueryRunner.query (F:\Projects\gargantua\be\node_modules\typeorm\driver\postgres\PostgresQueryRunner.js:178:25)
      at async SelectQueryBuilder.loadRawResults (F:\Projects\gargantua\be\node_modules\typeorm\query-builder\SelectQueryBuilder.js:2183:25)
      at async SelectQueryBuilder.executeEntitiesAndRawResults (F:\Projects\gargantua\be\node_modules\typeorm\query-builder\SelectQueryBuilder.js:2034:26)
      at async SelectQueryBuilder.getRawAndEntities (F:\Projects\gargantua\be\node_modules\typeorm\query-builder\SelectQueryBuilder.js:684:29)
      at async SelectQueryBuilder.getMany (F:\Projects\gargantua\be\node_modules\typeorm\query-builder\SelectQueryBuilder.js:750:25)
      at async Promise.allSettled (index 0) {
    length: 92,
    severity: 'ERROR',
    code: '42601',
    detail: undefined,
    hint: undefined,
    position: '1205',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'scan.l',
    line: '1245',
    routine: 'scanner_yyerror'
  },
  length: 92,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '1205',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1245',
  routine: 'scanner_yyerror'
}
::1 - - [25/Jan/2024:19:02:34 +0000] "POST /store/carts/cart_01HN0Z69GA2JZE36MDM3KQR68G HTTP/1.1" 500 86 "-" "PostmanRuntime/7.36.1"
`

### Expected behavior

I expect the update process to success and change the customAttribute of selected cart.

**Comment by zajacjakub** [comment]
The interesting thing is, that when I comment the **extend-cart-fields.ts**, the situation changes. The app will not crash, but the value of customAttribute will not save to the databse:

**extend-cart-fields.ts**
```
export default async function () {
    // const imports = (await import(
    //     "@medusajs/medusa/dist/api/routes/store/carts/index"
    //     )) as any
    // imports.defaultStoreCartFields = [
    //     ...imports.defaultStoreCartFields,
    //     "customAttribute",
    // ]
}
```

**Comment by xyzones** [comment]
@zajacjakub this is a query error. `position: '1205',` which is  

`WHERE ( "cart"."id" IN () )`  missing cart id from the where clause

**Comment by zajacjakub** [comment]
@xyzones it looks like the cart id is missing, but i am sending it as a path parameter according to documentation https://docs.medusajs.com/api/store#carts_postcartscart

**Comment by xyzones** [comment]
https://github.com/medusajs/medusa/blob/5a550e73b40c200c878903c8542e322025ba4728/packages/medusa/src/api/routes/store/carts/index.ts#L222


This is the problem? this is empty

**Comment by xyzones** [comment]
Adding `id` to the validator removes the error, however the new field is not saved but email is.

Validation works as if not string error is shown. Field is correctly retrieved from the database and `GET` returns it

**Comment by zajacjakub** [comment]
@xyzones thank you very much for your contribution. After I added the "id" to the validators, the error is gone, but I really dont understand why should I do that. I assume it's part of the bug... The attribute is still not saving to the DB, exactly as you write.

**Comment by kelvinnmugendi** [comment]
@zajacjakub did you find a better way to handle this. Experiencing the same

**Comment by zajacjakub** [comment]
Hello @kevinrobert3 ,
I managed to bypass the issue, not resolve it. My solution is functional and perhaps acceptable in my scenario, but I believe it may not be suitable for everyone. 

My solution involves not using the existing REST API call for modifying the cart that MedusaJS already includes, but rather creating a new REST API endpoint that only takes my new attribute as input and saves it to the database. It works smoothly.

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
