### ISSUE TITLE
Docs(Code Issue): Code Issue in /modules/products/admin/import-products

### ISSUE THREAD

**Issue by irab** [medusajs/medusa#6264]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

**_Using latest Admin package release version: `"@medusajs/admin": "7.1.10"`_**

The [current cURL doco for importing products](https://docs.medusajs.com/modules/products/admin/import-products) specifies the API Token is provided with `-H 'Authorization: Bearer <API_TOKEN>'` but calls made with this header fail with an `Unauthorized` response. 

Calling the API with the following cURL header option works: `-H 'x-medusa-access-token: <API_TOKEN>'`

I can possibly raise a PR to fix the documentation if I get confirmation that this is the correct approach?

### How can this issue be resolved?

The API doco for cURL commands are updated to `-H 'x-medusa-access-token: <API_TOKEN>'` wherever `-H 'Authorization: Bearer <API_TOKEN>'` occurs.

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for opening this issue! That's true, it should be `-H 'x-medusa-access-token: <API_TOKEN>'`. I think this is a change we missed to make in the main docs but have made in the API reference.

Would you be up to make the change in all files under `www/apps/docs/content` as this is probably used in different places? It should be a quick find-and-replace

**Comment by irab** [comment]
Yes, happy to ❤️

Will raise a PR in a bit.
