### ISSUE TITLE
Admin dashboard blocked on Chrome and Safari due to Cookie “connect.sid” misusing "SameSite" attribute

### ISSUE THREAD

**Issue by z33bs** [medusajs/medusa#6266]
### Describe the bug

Issue occurs when deploying admin dashboard separately to the backend. 

When testing on localhost, admin can authorise no-problem. 

BUT...

When deploying to Vercel, admin can authorise in Firefox✅, not on Chrome❌ and Safari❌. I've verified that this is NOT a CORS issue. Firefox gives a clue why with a console warning about incorrect use of SameSite and further warning that soon the connect.sid cookie won't be sent in future requests.

> Cookie “connect.sid” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

When inspecting the network requests in Chrome indeed it shows a similar warning with the PreFlight request and asserts that the cookie was blocked (see Screenshot attached)

### Suggested Fix
Set SameSite=None for the connection.sid cookie when running admin via medusa-admin develop 

### System information

Medusa version: 1.20.1 & admin 7.10.1:
Node.js version: 18
Database: postgres
Operating system: Vercel deploy
Browser (if relevant): Chrome & Safari

### Steps to reproduce the behavior

Deploy on Vercel with the following minimal installation. See package.json and config below. Note, I decided to use dist/ as outDir and instruct vercel to go here. Also using the develop comand to fire up the admin independently. As stated this minimal configuration runs perfectly when browsing with Firefox currently (v122 release)

```
"packageManager": "yarn@4.0.2",
"scripts": {
    "build": "medusa-admin build --deployment",
    "start": "medusa-admin develop"
  },
  "dependencies": {
    "@medusajs/admin": "^7.1.10",
    "@medusajs/medusa": "^1.20.1"
}
```

and medusa.config.js
```
const plugins = [
    {
        resolve: "@medusajs/admin",
        /** @type {import('@medusajs/admin').PluginOptions} */
        options: {
            serve: false,
            autoRebuild: false,
            backend: process.env.MEDUSA_ADMIN_BACKEND_URL,
            path: "/",
            outDir: "dist",
            // we're using medusa-admin develop in production for now
            develop: {
                open: false,
                port: 7001,
                logLevel: "verbose", //"error" | "none" | "warn" | "info" | "log" | "verbose"
                stats: "debug", //"normal" | "debug"
                allowedHosts: "auto" //"auto" | "all" | string[]
                // webSocketURL: undefined, //https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers
                // see Medusa docs for object sub-params
            }
        }
    }
]

module.exports = {
    // projectConfig,
    // modules,
    plugins
}
```

### Expected behavior
Admin lets user log in successfully.

### Screenshots

<img width="993" alt="image" src="https://github.com/medusajs/medusa/assets/19351631/f831028c-0035-4178-8f93-6add7c9d306e">

### Code snippets

N/A

### Additional context

N/A

**Comment by poiuyt183** [comment]
I catch the same error, how did you fix it

**Comment by poiuyt183** [comment]
[kasperkristensen](https://github.com/kasperkristensen) Help me, please!

**Comment by rossjaydev155** [comment]
some news?
