### ISSUE TITLE
deleteVariantPrices does not delete pvma in PriceListService

### ISSUE THREAD

**Issue by nicolama-dev** [medusajs/medusa#6280]
### Describe the bug

Since variant_id column was deleted from money_amount we have the product_variant_money_amount table.

However it seems that the deleteVariantPrices does not delete the pvma. It only delete the money amount.

### System information

Medusa version (including plugins): 1.20.1

### Steps to reproduce the behavior

1. Adding variant to the pricelist

`    const newPrice: AdminPriceListPricesUpdateReq = {
      amount: Math.round(originalPrice.amount * (1 - discount)),
      currency_code: originalPrice.currency_code,
      min_quantity,
      max_quantity,
      variant_id: variant.id,
    };`

`    await this.manager_.transaction(async (transactionManager) => {
      await this.container_.priceListService
        .withTransaction(transactionManager)
        .addPrices(priceListId, [newPrice]);
    });`

2. Delete the variant form the pricelist

`      await this.manager_.transaction(async (transactionManager) => {
        return await this.container_.priceListService
          .withTransaction(transactionManager)
          .deleteVariantPrices(priceListId, [variant.id]);
      });`

### Expected behavior

The pvma should be soft deleted like the money_amount
For now only the ma is being deleted and the pvma stays with a NULL deleted_at column.

**Comment by markochia** [comment]
+1 to this issue. Hopefully it can be re-opened.

The `product_variant_money_amount` record becomes orphaned since the field `money_amount_id` doesn't also have a foreign key index to `money_amount` to raise the restriction.
