### ISSUE TITLE
Draft order custom fields are being validated but saved as 'null' in database

### ISSUE THREAD

**Issue by LucasAleDeveloper** [medusajs/medusa#6287]
### Describe the bug

New extended custom fields aint being saved on create (draft_order -> create) and its a bit odd.. because products -> create seems to be working without any issues (i extended the same field there and is being successfully saved in DB) 

### System information
 
Medusa version (including plugins):  1.17.1
Node.js version: 18.18 
Database: Postgress
Operating system: W11
Browser (if relevant): Brave

### Steps to reproduce the behavior

1. Extend `draft_order` entity
2. Setup the new entity like the docs explain (migration, loader, validator, model: [named `draft_order.ts`])
3. Make a post request
4. New field is validated but alwayss with "null" value 

### Expected behavior

New fields are created, configurated (loader, validator, model) and finally saved after the POST request. 

### Screenshots

![image](https://github.com/medusajs/medusa/assets/46502330/ebc28495-6f20-404c-8f6a-5bfd315ff025)

`storeId` and  `organizationId`  aint being saved

**Comment by MatiasJRB** [comment]
step2
que documentacion? link
step3
que request? link a postman

screenshots ❌ 
info de la request + jsons ✅

**Comment by LucasAleDeveloper** [comment]
https://github.com/medusajs/medusa/blob/develop/packages/medusa/src/services/draft-order.ts

Might be related? The base service isnt saving the whole `data` object, just some parts, and.. the new custom fields are passed in the data object. 

In the other hand, the products service (which works) uses the spread operator to insert the other fields (`...rest`)

**Comment by BorisKamp** [comment]
Good find @LucasAleDeveloper , I am having the same issue.
I extended the draft order model, can see the field in the responses and in the postgresql table but I cannot update the value, nor do the filters work which I added for the new field. but I guess that is related.

As a workaround for now I created a custom endpoint to set the field:
```javascript
import type { 
  MedusaRequest, 
  MedusaResponse,
} from "@medusajs/medusa"

import { DraftOrder } from "@medusajs/medusa"
import { EntityManager } from "typeorm"

export const POST = async (
  req: MedusaRequest, 
  res: MedusaResponse
) => {
  const manager: EntityManager = req.scope.resolve("manager")
  const draftOrderRepo = manager.getRepository(DraftOrder)

  const draftOrder = await draftOrderRepo.findOne({
    where: {
      id: req.params.id
    }
  })

  if (req.body.bb_company_slug)  {
    draftOrder.bb_company_slug = req.body.bb_company_slug
  }

  const newDraftOrder = await draftOrderRepo.save(draftOrder)

  return res.json({
    draft_order: newDraftOrder
  })
}
```

But that feels very hacky as we should just do it trough the core `{{medusa-host}}/admin/draft-orders/:id` endpoint.

Maybe @shahednasser can help us out as she helped me earlier today with something similair?

**Comment by shahednasser** [comment]
I think with the current implementation of the draft order it would be best to either create a new endpoint or [extending the service](https://docs.medusajs.com/development/services/extend-service). However, we try not to recommend extending services too much, so if creating an endpoint works for you I suggest doing that.

**Comment by BorisKamp** [comment]
Yeah so I will tweak my custom endpoint a bit more to make it nicer and use that. Any reason why the core draft order endpoints are like that? Filters do not work and added fields cannot be used in create/update @shahednasser ?

**Comment by shahednasser** [comment]
Some of these endpoints were created a long time ago. We're now moving towards a different way of implementing all these services into modules, and with the release of V2 of Medusa, there will be a lot of DX improvements. So for now, unfortunately you have to do a workaround for cases like these.

**Comment by BorisKamp** [comment]
Makes sense @shahednasser .
I bump into another issue with those fields. I want to set a custom draftOrder field in my `/src/subscribers/draft-order-notifier.ts` file.

This is my file:
```javascript
import axios from "axios";

class DraftOrderSubscriber {
  protected readonly draftOrderService
  protected readonly draftOrderRepo
  protected readonly cartService
  config = {
    relations: ['cart', 'cart.items', 'cart.shipping_address', 'cart.billing_address', 'cart.customer'],
  }

  constructor({ draftOrderService, cartService, eventBusService }) {
    eventBusService.subscribe('draft_order.created', this.draftOrderCreated)
    eventBusService.subscribe('draft_order.updated', this.draftOrderUpdated)
    eventBusService.subscribe('draft_order.deleted', this.draftOrderDeleted)
    this.draftOrderService = draftOrderService
    this.cartService = cartService
  }

  draftOrderCreated = async (data) => {
        // Set bb_company_slug field on draft order (used for search)
        console.dir(draftOrder.cart.metadata.birdblocker_company)
        if (draftOrder.cart.metadata.birdblocker_company) {
          draftOrder.bb_company_slug = draftOrder.cart.metadata.birdblocker_company.slug
          const newDraftOrder = await this.draftOrderRepo.save(draftOrder)
          console.dir(newDraftOrder)
        }
      })
      .catch((e) => {
        console.dir(e)
      })
  }

export default DraftOrderSubscriber
```

But I have no clue where to get `draftOrderRepo` from, how do I set it, somewhere in the constructor I suppose?

**Comment by shahednasser** [comment]
Please refer to this guide on [creating subscribers](https://docs.medusajs.com/development/events/create-subscriber). We've improved the DX it's recommended to use it moving forward.

As for the repository, you'll need to resolve the entity manager from the dependency container and use it to get the repository. For example:

```ts
const manager = container.scope.resolve("manager")
const draftOrderRepo = manager.getRepository(DraftOrder)
```

Make sure to import `DraftOrder` at the beginning of the file.

But why do you need the repository? why not just use the `DraftOrderService`? That's the recommended approach

**Comment by BorisKamp** [comment]
> Please refer to this guide on [creating subscribers](https://docs.medusajs.com/development/events/create-subscriber). We've improved the DX it's recommended to use it moving forward.
> 
> As for the repository, you'll need to resolve the entity manager from the dependency container and use it to get the repository. For example:
> 
> ```ts
> const manager = container.scope.resolve("manager")
> const draftOrderRepo = manager.getRepository(DraftOrder)
> ```
> 
> Make sure to import `DraftOrder` at the beginning of the file.
> 
> But why do you need the repository? why not just use the `DraftOrderService`? That's the recommended approach

Thank you, I indeed found out there's a new subscriber-way since v1.18.0
I refactored to that and now it works.

I use the repo instead of the service because with the service I cannot update the value, it is ignored it seems....
