### ISSUE TITLE
[Bug] "Paid Total" is  is incorrect if the order contains deleted discounts

### ISSUE THREAD

**Issue by maxpanakov** [medusajs/medusa#6291]
### Describe the bug

paid_total will be less then total, if order has a discounts which is soft deleted

### System information

Medusa version :1.20.1

### Steps to reproduce the behavior

1. Create the order from the cart with discount
2. Delete the discount
4. Compare paid_total with total

**Comment by maxpanakov** [comment]
Solution:
inside OrderRepository
```
const ITEMS_REL_NAME = "items"
const REGION_REL_NAME = "region"
const DISCOUNTS_REL_NAME = "discounts"

const WITH_DELETED_REL_NAMES = [
    ITEMS_REL_NAME,
    REGION_REL_NAME,
    DISCOUNTS_REL_NAME
]
return this.find({
  withDeleted: WITH_DELETED_REL_NAMES.includes(topLevel),
})
```

**Comment by olivermrbl** [comment]
Nice catch, would you be up for sending a PR with the fix + test?

**Comment by pepijn-vanvlaanderen** [comment]
@olivermrbl we ran into this issue as well, I opened a PR with the fix (https://github.com/medusajs/medusa/pull/6837)

**Comment by olivermrbl** [comment]
Thanks @pepijn-vanvlaanderen, will be part of next release.
