### ISSUE TITLE
QueryClient defaultMutationOptions unavailable when used in the MedusaProvider

### ISSUE THREAD

**Issue by jeroenvanhattem** [medusajs/medusa#6298]
## Bug report
TypeError: (0 , _swc_helpers_class_private_field_get__WEBPACK_IMPORTED_MODULE_1__._)(...).defaultMutationOptions is not a function

### Describe the bug
The provider can't access `defaultMutationOptions` on the `queryClient`, while I can access it in the code.

### System information

Medusa version (including plugins): 6.1.6
Node.js version: 18
Database: Postgres
Operating system: Mac
Browser (if relevant): Arc (Chromium)

### Steps to reproduce the behavior

1. Create Next.js project (latest)
2. Install Medusa
3. Use the providers.

### Expected behavior
No errors
A clear and concise description of what you expected to happen

### Screenshots
<img width="978" alt="image" src="https://github.com/medusajs/medusa/assets/15092050/014bdb4d-3587-4360-a3e1-084614989371">

### Code snippets
`
"use client";

import React from "react";
import { Provider } from "react-redux";
import { store } from "redux-store/store";
import { CartProvider, MedusaProvider } from "medusa-react";
import { QueryClient } from "@tanstack/react-query";

const queryClient = new QueryClient({
	defaultOptions: {
		mutations: {},
	},
});

export const Providers = ({ children }: { children: React.JSX.Element }) => {
	return (
		<Provider store={store}>
			<MedusaProvider
				baseUrl={process.env.NEXT_PUBLIC_MEDUSA_BACKEND_URL!}
				queryClientProviderProps={{ client: queryClient }}
			>
				<CartProvider>{children}</CartProvider>
			</MedusaProvider>
		</Provider>
	);
};
`

### Additional context

Add any other context about the problem here

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
