### ISSUE TITLE
Admin dashboard: Create sample order failed

### ISSUE THREAD

**Issue by billybillydev** [medusajs/medusa#6304]
### Describe the bug

In a fresh local medusa project, I attempted to create a sample order by following the onboardings steps in admin dashboard. To click on button "Create Sample Order" does nothing. I noticed this error in terminal:

`error:   The shipping option is not available in the cart's region
Error: The shipping option is not available in the cart's region
    at ShippingOptionService.<anonymous>
.
.
.
backend/node_modules/@medusajs/medusa/dist/services/shipping-option.js:40:53) {
  type: 'invalid_data',
  code: undefined,
  date: 2024-02-01T22:09:49.560Z
}`

Database is running from a docker container

### System information

Medusa version (including plugins):
    "@medusajs/admin": "7.1.10",
    "@medusajs/cache-inmemory": "^1.8.9",
    "@medusajs/cache-redis": "^1.8.9",
    "@medusajs/event-bus-local": "^1.9.7",
    "@medusajs/event-bus-redis": "^1.8.10",
    "@medusajs/file-local": "^1.0.3",
    "@medusajs/medusa": "1.20.1",
    "medusa-fulfillment-manual": "^1.1.39",
    "medusa-interfaces": "^1.3.8",
    "medusa-payment-manual": "^1.0.24",
    "medusa-payment-stripe": "^6.0.7",
    "@medusajs/medusa-cli": "^1.3.21",
Node.js version: v18.18.0
Database: postgresql
Operating system: MacOS Venture Version 13.2.1 (22D68)
Browser (if relevant): Google Chrome version 121.0.6167.85 (Official Build) (arm64)

### Steps to reproduce the behavior

1. Go to admin dashboard after sign in ;
2. Click on "Begin setup" from the _Get Started_ block ;
3. Pass first and second step (create and preview sample product) ;
4. See error by clicking on "Create sample order" button ;

### Expected behavior

Successfully create a sample order in orders list below _Get Started_ block.

### Screenshots

<img width="1321" alt="Screenshot 2024-02-01 at 23 41 41" src="https://github.com/medusajs/medusa/assets/146948649/f938eb1a-eae3-46cb-8957-e10e69363092">

### Additional context

Watching this [youtube video](https://www.youtube.com/watch?v=sWjfAueW5NU)

**Comment by xyzones** [comment]
Have you checked you region setting?

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
