### ISSUE TITLE
Performance issues with a lot of orders and customers

### ISSUE THREAD

**Issue by khanh-to-niteco** [medusajs/medusa#6307]
### Describe the bug

We were doing load tests with about 120K orders and 100K customers. Then we tried to load orders in admin UI with pagination, the system were not responding. After checking the Postgres database, the CPU usage was almost 100%.

After some investigation, it seemed that when loading orders, we need to join with customer table (with 100K rows)

![image](https://github.com/medusajs/medusa/assets/71063731/63a8527e-d52b-4f2f-838e-c5f16f0c72d0)

The customer table has only 1 index, but it is not a clustered index on the primary key

![image](https://github.com/medusajs/medusa/assets/71063731/84be0343-9c56-4f79-958c-99e2df6f3861)

After trying to add a clustered index on the customer.id column, we observed huge performance improvements, the paged orders now takes only about 2s to load.

### System information

Medusa version (including plugins): 1.17.4
Node.js version: 18
Database: Postgres
Operating system: Linux
Browser (if relevant):

**Comment by olivermrbl** [comment]
@adrien2p, will you be able to have a look at this?

**Comment by adrien2p** [comment]
I have started a work on that domain sometimes ago [here](https://github.com/medusajs/medusa/pull/4315/files#diff-5926af32d4a19655c35db7bd86e5ff5a8d0ea1aaa82a3bacf85b1abc0466bd4a) which leads to massive improvements as well. could you look at those [indexes](https://github.com/medusajs/medusa/blob/a211993960be8225a160ca136b25e35b75a7aac5/packages/medusa/src/migrations/1699564794650-update-order-customer-address-indexes.ts) and see if that works for you as well?

cc @olivermrbl

**Comment by khanh-to-niteco** [comment]
Hi @adrien2p ,

Not sure if indexes can help with count. I added clustered index in the test before. There are some articles pointing out issues with count and alternatives:

https://www.cybertec-postgresql.com/en/postgresql-count-made-fast/
https://www.citusdata.com/blog/2016/10/12/count-performance/
