### ISSUE TITLE
Server is not responding under load tests.

### ISSUE THREAD

**Issue by khanh-to-niteco** [medusajs/medusa#6318]
### Describe the bug

We were doing load tests with a sudden spike in load. Then the server was not responding anymore.

Through investigation, we found that there were more than 1K events in the `staged_job` table.
Then looking at our application insight logs, we got a lot of errors like this

![image](https://github.com/medusajs/medusa/assets/71063731/07ee3e83-c14c-4f82-8aee-7f981cc263a4)

It seemed that the root cause was due to the event loop of Medusa loading 1K of events per iteration and dispatching them at the same time which overwhelmed the connection pool. Upon retrying in the next iteration, the events failed again and never completed.

We are using `event-bus-local`, not sure yet if this occurs to `event-bus-redis` as well. 

But is it possible to make it work also for `event-bus-local`? Maybe to reduce the batch size so the events eventually complete ?

### System information

Medusa version (including plugins): 1.17.4
Node.js version: 18
Database: Postgres
Operating system: Linux
Browser (if relevant):

**Comment by olivermrbl** [comment]
Can you share the script you are using for load-testing? We can set this up on our side, but would prolong the time to resolution.

**Comment by khanh-to-niteco** [comment]
Hi @olivermrbl ,

The script is built based on our app, so it may not work for you. We can try and let you know.

But do you think it is a good idea to have this number configurable? Each app can adjust based on their workload.

**Comment by olivermrbl** [comment]
@khanh-to-niteco, I don't have any strong arguments against making it configurable, so I am happy to go with that. Would you like to send a PR for it?

**Comment by khanh-to-niteco** [comment]
Hi @olivermrbl ,

We have tried with a batch size of 100 and observed very good results. 

So making this number configurable would work for many apps built on top of Medusa. This is Medusa framework so I think it's easier for you to update on your side.

**Comment by olivermrbl** [comment]
Sure, we'll attend to it when time allows for it.
