### ISSUE TITLE
Installation fails when installing legacy-peer-deps

### ISSUE THREAD

**Issue by csmithbrian** [medusajs/medusa#6325]
### Describe the bug

Creating a new medusa app via command line with the command npx create-medusa-app@latest --seed fails with the following log:
An error occurred while preparing project: Error: Command failed: npm install --legacy-peer-deps
...
npm ERR! code EIDLETIMEOUT
npm ERR! Idle timeout reached for host `registry.npmjs.org:443`

npm ERR! A complete log of this run can be found in: C:\Users\<USER>\AppData\Local\npm-cache\_logs\2024-02-06T01_26_11_065Z-debug-0.log

The following information is available at the end of the logfile:

11363 timing reifyNode:node_modules/@esbuild/win32-x64 Completed in 310396ms
11364 verbose stack Error: Idle timeout reached for host `registry.npmjs.org:443`
11364 verbose stack     at TLSSocket.<anonymous> (C:\Users\<USER>\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\agent\lib\agents.js:153:24)
11364 verbose stack     at Object.onceWrapper (node:events:632:28)
11364 verbose stack     at TLSSocket.emit (node:events:530:35)
11364 verbose stack     at Socket._onTimeout (node:net:589:8)
11364 verbose stack     at listOnTimeout (node:internal/timers:573:17)
11364 verbose stack     at process.processTimers (node:internal/timers:514:7)
11365 verbose cwd C:\Users\<USER>\<APP_NAME>
11366 verbose Windows_NT 10.0.19045
11367 verbose node v20.11.0
11368 verbose npm  v10.4.0
11369 error code EIDLETIMEOUT
11370 error Idle timeout reached for host `registry.npmjs.org:443`
11371 verbose exit 1
11372 timing npm Completed in 426753ms
11373 verbose unfinished npm timer command:install 1707182771401
11374 verbose unfinished npm timer reify 1707182771403
11375 verbose unfinished npm timer reify:unpack 1707182887397
11376 verbose unfinished npm timer reifyNode:node_modules/@segment/analytics-next 1707182887434
11377 verbose code 1

### System information

Medusa version (including plugins): 1.3.22
Node.js version: 20.11.0
Database: PostGRES 16.1
Operating system: Windows 10 Pro 22H2 Build 19045.3930
Browser (if relevant):

### Steps to reproduce the behavior

Occurs during initial install on fresh machine. 
Install prerequisites (see versions) and run npx create-medusa-app@latest --seed in a new cmd window

### Expected behavior

Installation succeeds

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by shahednasser** [comment]
Seems like a connection issue since the error is a timeout. I recommend either trying again or installing yarn and running the installation again.

**Comment by alexandrosk** [comment]
I have the exact same problem, was this solved?

**Comment by csmithbrian** [comment]
@alexandrosk I installed yarn and was successful.
