### ISSUE TITLE
Incorrect Link to `io-redis’s documentation` (https://docs.medusajs.com/development/cache/modules/redis)

### ISSUE THREAD

**Issue by sidd-kulk** [medusajs/medusa#6334]
### Preliminary Checks

- [ ] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I am on page https://docs.medusajs.com/development/cache/modules/redis to understand the Redis module details.
There is a link on the page with label `io-redis’s documentation` which points to https://luin.github.io/ioredis/index.html#RedisOptions, but I am getting 404 when trying to access.  

<img width="1298" alt="Screenshot 2024-02-07 at 10 15 20 AM" src="https://github.com/medusajs/medusa/assets/6894/85e79c93-9b19-4b22-95c3-d029b3b8365b">

Please share the correct link and I would be happy to raise a PR. 

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by sidd-kulk** [comment]
I believe the correct link should be:
https://github.com/redis/ioredis

**Comment by shahednasser** [comment]
Thanks for opening this issue! The URL should be https://redis.github.io/ioredis/classes/Redis.html#options can you open a PR with the fix?

**Comment by sidd-kulk** [comment]
Done:
https://github.com/medusajs/medusa/pull/6337
