### ISSUE TITLE
All custom Admin API routes result to 404 if you require sharp library into at least one of them

### ISSUE THREAD

**Issue by AlexTechNoir** [medusajs/medusa#6336]
### Describe the bug

Good day!

During the development suddenly all custom Admin API routes shown error 404 in the console, even "onboarding" official example. After investigating I found out that the reason is a single line in one of the custom API routes:
```node
  const sharp = require('sharp')
```
It seems it is specifically sharp library that causes errors, I tried to require other libs with the same syntax - no problems emerged. It doesn't matter which file this line is present in - it breaks all of API routes (not sure about Store API - I don't have an opportunity to test it for now)

When I comment the above line out, everything is working again

### System information

Medusa version (including plugins): 1.20.0
Node.js version: 18.16.1
Database: PostgreSQL
Operating system: Win 10
Browser (if relevant):

### Steps to reproduce the behavior

1. Setup Medusa project
2. Create custom Admin API endpoint
3. Install sharp library `npm install sharp` and import it into API route file: `const sharp = require('sharp')`
4. Run the project with `npx medusa develop` and open browser console. After logging in you will see that "admin/onboarding" shows 404 error - the same will happen with other custom API endpoints when you interact with them

### Expected behavior

Working custom Admin API endpoints

### Screenshots

After logging in:

![err](https://github.com/medusajs/medusa/assets/43852391/5204321c-6fe3-49cb-aacc-7d497bf9ecae)

**Comment by AlexTechNoir** [comment]
I came across several GitHub issues in Sharp repo that highlighted Sharp's compatibility problems with Edge runtime (and as a result - problems with deploying Sharp on services like Vercel and Cloudflare Workers). I'm assuming this also can somehow be related with Medusa's API Routes being based on Next.js 13 App Router

The errors have disappeared after downgrading Sharp to ver.0.32.6, but I'm going to leave this opened as it probably need a real solution, not a workaround

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏

**Comment by Mohhaliim** [comment]
you ever fixed this? i'm on medusa 1.20.8, used to work fine and suddenly it started giving me 404s for the routes I built

**Comment by AlexTechNoir** [comment]
@Mohhaliim downgrade Sharp to ver.0.32.6 as I mentioned above or submit a new issue with your case as Stevche suggested
