### ISSUE TITLE
 Error during migration generation: with typeorm migration:generate

### ISSUE THREAD

**Issue by ehtisham-afzal** [medusajs/medusa#6339]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

###  migration generate returns error while generating a migration file
`
TypeORMError: Entity metadata for Product#images was not found. Check if you specified a correct entity object and if it's connected in the connection options.
`

**Comment by fvcoder** [comment]
I have the same problem

**Comment by dpdenton** [comment]
I have the same problem.

I have the `medusa-custom-attributes' plugin installed which also extends the Product entity; not sure if that makes a difference

**Comment by facundocapua** [comment]
I have the same problem.

**Comment by HansiDerSweater** [comment]
I got the same problem when trying to extend the product entity (creating the migration)

**Comment by Dominic-Preap** [comment]
Facing the same issue.
