### ISSUE TITLE
Admin reaches localhost for authentication resulting in blocked (invalid credentials even if you enter right one ) 

### ISSUE THREAD

**Issue by jeevsssss** [medusajs/medusa#6340]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

in documentation , it is mentioned to use --development in script , and add the backend url to env file , yet the admin page reached to localhost instead of the url defined in env file

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by traverseitops** [comment]
I have the same issue. Can anyone help? No matter what I do, seems like admin will only connect to localhost

**Comment by shahednasser** [comment]
This issue has been previously fixed. Feel free to reopen it if you're still having trouble.
