### ISSUE TITLE
Docs(Code Issue): Code Issue in /starters/nextjs-medusa-starter - expiresAt Update for new year

### ISSUE THREAD

**Issue by addlightness** [medusajs/medusa#6356]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Expires at needs to be updated to accommodate for the new year

### How can this issue be resolved?

curl \
  -X POST '<MEILISEARCH_URL>/keys' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer <MEILISEARCH_MASTER_KEY>' \
  --data-binary '{
    "description": "Search products",
    "actions": ["search"],
    "indexes": ["products"],
    "expiresAt": "2025-01-01T00:00:00Z"

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for catching this! Feel free to open a PR to resolve this issue.

**Comment by shahednasser** [comment]
This issue has been fixed.
