### ISSUE TITLE
fetching order from 3rd party and integrating with medusa

### ISSUE THREAD

**Issue by Kushal-starr** [medusajs/medusa#6376]
Problem/feature statement:- I like to integrate the neto-store with my medusa backend, i.e., I want the order created in my medusa should be visible in neto also.

For that I'm using the event-bus.

But, I'm stuck with the approach, how should I proceed. 

Any helping hands will be appreciated.

Thanks!

**Comment by olivermrbl** [comment]
Please open this as a question or discussion in our Github Discussions. The issue board is for bug reports only.
