### ISSUE TITLE
Typos - Associate order fulfillemnts and returns with a stock location. 

### ISSUE THREAD

**Issue by 001bharathchetty** [medusajs/medusa#6389]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Typos - Associate order fulfillments and returns with a stock location, in Inventory section.  Page link - https://docs.medusajs.com/modules/overview

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for reporting this issue! Feel free to open a PR to fix it.
