### ISSUE TITLE
Move test API request to `medusa-test-utils`

### ISSUE THREAD

**Issue by olivermrbl** [medusajs/medusa#64]
Move the test request from `/helper` in `medusa` to `medusa-test-utils`, such that this can be used in all packages and plugins.

**Comment by srindom** [comment]
I considered this as well and actually wanted to do it when we made `medusa-test-utils`, however, I found an issue with having to share the loader functionality, which creates all the endpoints, across two packages. So we will somehow have to make the loader available to `medusa-test-utils`
