### ISSUE TITLE
[plugin: medusa-payment-paypal] Using a wrong http method for PayPal payment authorization

### ISSUE THREAD

**Issue by brucexiu** [medusajs/medusa#6424]
### Describe the bug

I'm integrating PayPal Payment method in sandbox env. When PayPal called a webhook to my server, I found my server always response 404. Finally I found the wrong payment method used in the plugin.

In medusa log:
![image](https://github.com/medusajs/medusa/assets/3021100/8ac811b9-e0b2-4dd5-a201-6553e8e404d1)

But in the message body of the webhook api in Paypal dashboard:
![image](https://github.com/medusajs/medusa/assets/3021100/b03fd030-4765-491c-b088-49c0dbd0a792)

And I also tried in Postman. It did work to use get method but response 404 instead of using POST. 

Here is the related code in repo.

https://github.com/medusajs/medusa/blob/v1.20.2/packages/medusa-payment-paypal/src/core/paypal-http-client.ts#L54-L73
https://github.com/medusajs/medusa/blob/v1.20.2/packages/medusa-payment-paypal/src/core/paypal-sdk.ts#L115-L121

Please fix it, thanks.

### System information

Medusa version (including plugins): Medusa: 1.16.0. medusa-payment-paypal:6.0.2
Node.js version: v18
Database: pg
Operating system: bullseye
Browser (if relevant):

**Comment by SalahAdDin** [comment]
@brucexiu any advance on it?
