### ISSUE TITLE
The Indian Rupee symbol looks incorrect

### ISSUE THREAD

**Issue by explorer2309** [medusajs/medusa#6430]
## Bug report
I have set the region to India and I am trying to add prices.
Although the feature is working, the Rupee symbol in the price screen looks incorrect.

### Screenshots
![image](https://github.com/medusajs/medusa/assets/4947704/6b9222bb-06ef-419e-9a12-45055e260db5)

**Comment by garvitmaloo** [comment]
I can work on this issue.. assign it to me

**Comment by leoalipazaga** [comment]
Fixed on this [PR](https://github.com/medusajs/medusa/pull/6453)
