### ISSUE TITLE
NextJS storefront creation error

### ISSUE THREAD

**Issue by papebarka** [medusajs/medusa#6450]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

When trying to create a new NextJS Store front as described in the documentation, we get an invalid github error.

`npx create-next-app -e https://github.com/medusajs/nextjs-starter-medusa my-medusa-storefront
`

Output

`
Found invalid GitHub URL: "https://github.com/medusajs/nextjs-starter-medusa/". Please fix the URL and try again.
`

**Comment by leoalipazaga** [comment]
Hi, make sure that you have v18 or greater of nodejs.

**Comment by beyourahi** [comment]
> Hi, make sure that you have v18 or greater of nodejs.

I've used both node 18 and 20 and still getting the same error

**Comment by shahednasser** [comment]
Hey guys, as reported in issue #6930, this is most likely an error in the installed `create-next-app` version so please use the `@latest` version and try again.
