### ISSUE TITLE
'405 Method Not Allowed' Error on deploying to Vercel

### ISSUE THREAD

**Issue by kelvinnmugendi** [medusajs/medusa#6457]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

When working locally all API requests work perfectly.
I followed the docs on deploying to Vercel https://docs.medusajs.com/deployments/admin/deploying-on-vercel
Only I get an error here "405 Method Not Allowed" on trying to sign in. 
Everything works perfectly on local

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by crnls** [comment]
Is your backend already live on a public url?

**Comment by kelvinnmugendi** [comment]
Hey @crnls. This I created before finding your issue https://github.com/medusajs/nextjs-starter-medusa/issues/273 like we were discussing
