### ISSUE TITLE
Algolia index sync is failing because of byte size 

### ISSUE THREAD

**Issue by alexandrosk** [medusajs/medusa#6476]
## Bug report
Algolia Index sync is failing. 
Pretty standard setup of medusa products, my github repo is this https://github.com/alexandrosk/medusa-marketplace

### Describe the bug

When trying to sync data the index is failing because of 
`Record at the position 0 objectID=prod_01HQ0ZVZGV4MK33JGBG1M4MK8G is too big size=15234/10000 bytes. Please have a look at https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/in-depth/index-and-records-size-and-usage-limitations/#record-size-limits`

The product looks like this 
`{
  "requests": [
    {
      "action": "updateObject",
      "body": {
        "id": "prod_01HQ0ZVZGV4MK33JGBG1M4MK8G",
        "created_at": "2024-02-19T15:31:03.919Z",
        "updated_at": "2024-02-19T15:31:03.919Z",
        "deleted_at": null,
        "title": "Medusa T-Shirt",
        "subtitle": null,
        "description": "Reimagine the feeling of a classic T-shirt. With our cotton T-shirts, everyday essentials no longer have to be ordinary.",
        "handle": "medusa-t-shirt",
        "is_giftcard": false,
        "status": "published",
        "thumbnail": "https://medusa-public-images.s3.eu-west-1.amazonaws.com/tee-black-front.png",
        "weight": 400,
        "length": null,
        "height": null,
        "width": null,
        "hs_code": null,
        "origin_country": null,
        "mid_code": null,
        "material": null,
        "collection_id": "pcol_01HQ0ZTXXFK6C0DKPFSEN750XW",
        "type_id": null,
        "discountable": true,
        "external_id": null,
        "metadata": null

[...]

Request body has been truncated.`

My medusa.config.js looks like this 
`{
    resolve: `medusa-plugin-algolia`,
    options: {
      applicationId: process.env.ALGOLIA_APP_ID,
      adminApiKey: process.env.ALGOLIA_ADMIN_API_KEY,
      settings: {
        products: {
          indexSettings: {
            searchableAttributes: ["title"],
            attributesToRetrieve: [
              "id",
              "title",
              "description",
              "handle",
              "thumbnail",
              "images",
            ],
            filterableAttributes: ["tags", "category", "type", "title"],
          },
          primaryKey: "id",
        },
      },
    },
  },`

### System information

Medusa version (including plugins):
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by olivermrbl** [comment]
Could you try transforming your product to reduce the size of it using the `transformer` setting of the plugin?

https://docs.medusajs.com/plugins/search/algolia#install-the-algolia-plugin

**Comment by alexandrosk** [comment]
Thanks @olivermrbl 
So I had 2 issues, I used the transformer first before writing but didn't restart npm run dev to take the changes.
Then to make this work I had to remove the variants actually 

So having this 
```
transformer: function (product) {
            return {
              objectID: product.id,
              title: product.title,
              description: product.description,
              handle: product.handle,
              thumbnail: product.thumbnail,
              // other attributes...
            }
          },
```

Works fine, thanks! resolved
