### ISSUE TITLE
Heroku server keeps crashing after 20-30 seconds

### ISSUE THREAD

**Issue by crnls** [medusajs/medusa#6477]
For a brief time, everything works and I can connect my admin (deployed on Vercel) to the backend (deployed on Heroku) but after a few seconds (also when i dont do anything) the Heroku server crashes. Possible cause could be a mistake in medusa-config.js and/or package.json (shared below). 

### Error log
[
  {
    "timestamp": "2024-02-22T14:57:08.368789+00:00",
    "process": "app[web.1]",
    "activity_id": "01HQ8N3ZA8JZ88R4226G3X353T",
    "level": "info",
    "message": "Registering route [GET] - /store/custom"
  },
  {
    "timestamp": "2024-02-22T14:57:08.368848+00:00",
    "process": "app[web.1]",
    "activity_id": "01HQ8N3ZA8JZ88R4226G3X353T",
    "level": "info",
    "message": "Registering route [GET] - /admin/onboarding"
  },
  {
    "timestamp": "2024-02-22T14:57:08.368899+00:00",
    "process": "app[web.1]",
    "activity_id": "01HQ8N3ZA8JZ88R4226G3X353T",
    "level": "info",
    "message": "Registering route [POST] - /admin/onboarding"
  },
  {
    "timestamp": "2024-02-22T14:57:08.368949+00:00",
    "process": "app[web.1]",
    "activity_id": "01HQ8N3ZA8JZ88R4226G3X353T",
    "level": "info",
    "message": "Registering route [GET] - /admin/custom"
  },
  {
    "timestamp": "2024-02-22T14:57:08.369001+00:00",
    "process": "app[web.1]",
    "activity_id": "01HQ8N3ZA8JZ88R4226G3X353T",
    "level": "info",
    "message": "Registering route [GET] - /store/custom"
  },
  {
    "timestamp": "2024-02-22T14:57:08.369143+00:00",
    "process": "app[web.1]",
    "activity_id": "01HQ8N3ZA8JZ88R4226G3X353T",
    "level": "info",
    "message": "Routes loaded in 30.45 ms"
  },
  {
    "timestamp": "2024-02-22T14:57:08.371023+00:00",
    "process": "app[web.1]",
    "activity_id": "01HQ8N3ZA8JZ88R4226G3X353T",
    "level": "info",
    "message": "Plugins initialized",
    "duration": 458
  },
  {
    "timestamp": "2024-02-22T14:57:08.377206+00:00",
    "process": "app[web.1]",
    "activity_id": "01HQ8N3ZRRMZ39F1QS1ZGVMYGX",
    "level": "info",
    "message": "Initializing subscribers",
    "config": {}
  },
  {
    "timestamp": "2024-02-22T14:57:08.389675+00:00",
    "process": "app[web.1]",
    "activity_id": "01HQ8N3ZRRMZ39F1QS1ZGVMYGX",
    "level": "info",
    "message": "Subscribers initialized",
    "duration": 12
  },
  {
    "timestamp": "2024-02-22T14:57:08.393789+00:00",
    "process": "app[web.1]",
    "activity_id": "01HQ8N3ZS9RXXW5AK2976FGRHX",
    "level": "info",
    "message": "Initializing API",
    "config": {}
  },
  {
    "timestamp": "2024-02-22T14:57:08.442559+00:00",
    "process": "app[web.1]",
    "activity_id": "01HQ8N3ZS9RXXW5AK2976FGRHX",
    "level": "info",
    "message": "API initialized",
    "duration": 48
  },
  {
    "timestamp": "2024-02-22T14:57:08.535005+00:00",
    "process": "app[web.1]",
    "activity_id": "01HQ8N3ZXPMRYJAS4X05AY5R46",
    "level": "info",
    "message": "Initializing defaults",
    "config": {}
  },
  {
    "timestamp": "2024-02-22T14:57:09.008854+00:00",
    "process": "app[web.1]",
    "level": "warn",
    "message": "You don't have any notification provider plugins installed. You may want to add one to your project."
  },
  {
    "timestamp": "2024-02-22T14:57:09.020025+00:00",
    "process": "app[web.1]",
    "level": "warn",
    "message": "You don't have any taxProviders provider plugins installed. You may want to add one to your project."
  },
  {
    "timestamp": "2024-02-22T14:57:09.834046+00:00",
    "process": "app[web.1]",
    "activity_id": "01HQ8N3ZXPMRYJAS4X05AY5R46",
    "level": "info",
    "message": "Defaults initialized",
    "duration": 1299
  },
  {
    "timestamp": "2024-02-22T14:57:09.839370+00:00",
    "process": "app[web.1]",
    "activity_id": "01HQ8N416EJYPQXSMGTGX54162",
    "level": "info",
    "message": "Initializing search engine indexing",
    "config": {}
  },
  {
    "timestamp": "2024-02-22T14:57:09.843739+00:00",
    "process": "app[web.1]",
    "level": "warn",
    "message": "No search engine provider was found: make sure to include a search plugin to enable searching"
  },
  {
    "timestamp": "2024-02-22T14:57:09.844085+00:00",
    "process": "app[web.1]",
    "activity_id": "01HQ8N416EJYPQXSMGTGX54162",
    "level": "info",
    "message": "Indexing event emitted",
    "duration": 4
  },
  {
    "timestamp": "2024-02-22T14:57:09.848324+00:00",
    "process": "app[web.1]",
    "activity_id": "01HQ8N416R3444V6MHJFCTKWAH",
    "level": "info",
    "message": "Creating server",
    "config": {}
  },
  {
    "timestamp": "2024-02-22T14:57:09.857877+00:00",
    "process": "app[web.1]",
    "activity_id": "01HQ8N416R3444V6MHJFCTKWAH",
    "level": "info",
    "message": "Server is ready on port: 59965",
    "duration": 9
  },
  {
    "timestamp": "2024-02-22T14:57:10.467262+00:00",
    "process": "heroku[web.1]",
    "message": "State changed from starting to up"
  },
  {
    "timestamp": "2024-02-22T14:57:11.933216+00:00",
    "process": "heroku[router]",
    "message": "at=info method=GET path=\"/\" host=dev.wantsandneeds.nl request_id=5d9d92ef-ad8c-48c3-b4db-381fdde024eb fwd=\"54.247.57.72\" dyno=web.1 connect=1ms service=167ms status=404 bytes=573 protocol=https"
  },
  {
    "timestamp": "2024-02-22T14:57:11.960810+00:00",
    "process": "app[web.1]",
    "message": "54.247.57.72 - - [22/Feb/2024:14:57:11 +0000] \"GET / HTTP/1.1\" 404 139 \"-\" \"Mozilla/5.0 (X11; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0\""
  },
  {
    "timestamp": "2024-02-22T14:57:11.996435+00:00",
    "process": "app[web.1]",
    "message": "54.247.57.72 - - [22/Feb/2024:14:57:11 +0000] \"GET / HTTP/1.1\" 404 139 \"-\" \"Mozilla/5.0 (X11; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0\""
  },
  {
    "timestamp": "2024-02-22T14:57:11.996537+00:00",
    "process": "heroku[router]",
    "message": "at=info method=GET path=\"/\" host=dev.wantsandneeds.nl request_id=a7bae2bd-9787-4f09-96ed-c470f2a7b73f fwd=\"54.247.57.72\" dyno=web.1 connect=1ms service=31ms status=404 bytes=383 protocol=http"
  },
  {
    "timestamp": "2024-02-22T14:57:18.958758+00:00",
    "process": "heroku[web.1]",
    "message": "Process running mem=522M(100.9%)",
    "level": "error",
    "error": "R14 (Memory quota exceeded)"
  },
  {
    "timestamp": "2024-02-22T14:57:37.000000+00:00",
    "process": "app[api]",
    "message": "Build succeeded"
  },
  {
    "timestamp": "2024-02-22T14:57:40.410349+00:00",
    "process": "heroku[web.1]",
    "message": "Process running mem=997M(194.9%)",
    "level": "error",
    "error": "R14 (Memory quota exceeded)"
  },
  {
    "timestamp": "2024-02-22T14:57:43.437414+00:00",
    "process": "heroku[router]",
    "message": "at=info method=GET path=\"/admin/batch-jobs?limit=100\" host=dev.wantsandneeds.nl request_id=e407da8a-40f2-478c-ba0c-f4ae385f0eb9 fwd=\"95.98.118.55\" dyno=web.1 connect=1ms service=2873ms status=200 bytes=372 protocol=https"
  },
  {
    "timestamp": "2024-02-22T14:57:43.442428+00:00",
    "process": "app[web.1]",
    "message": "95.98.118.55 - - [22/Feb/2024:14:57:43 +0000] \"GET /admin/batch-jobs?limit=100 HTTP/1.1\" 200 50 \"https://admin.wantsandneeds.nl/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36\""
  },
  {
    "timestamp": "2024-02-22T14:57:44.707680+00:00",
    "process": "heroku[router]",
    "message": "at=info method=GET path=\"/admin/auth\" host=dev.wantsandneeds.nl request_id=b27104a3-1bc1-46ff-b4cc-a738710dc354 fwd=\"95.98.118.55\" dyno=web.1 connect=0ms service=1108ms status=200 bytes=578 protocol=https"
  },
  {
    "timestamp": "2024-02-22T14:57:44.708395+00:00",
    "process": "app[web.1]",
    "message": "95.98.118.55 - - [22/Feb/2024:14:57:44 +0000] \"GET /admin/auth HTTP/1.1\" 200 255 \"https://admin.wantsandneeds.nl/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36\""
  },
  {
    "timestamp": "2024-02-22T14:57:45.201707+00:00",
    "process": "app[web.1]",
    "message": "95.98.118.55 - - [22/Feb/2024:14:57:45 +0000] \"GET /admin/store/ HTTP/1.1\" 304 - \"https://admin.wantsandneeds.nl/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36\""
  },
  {
    "timestamp": "2024-02-22T14:57:45.201789+00:00",
    "process": "heroku[router]",
    "message": "at=info method=GET path=\"/admin/store/\" host=dev.wantsandneeds.nl request_id=e2ef7906-c1f7-4eb4-bffe-97ef066943e8 fwd=\"95.98.118.55\" dyno=web.1 connect=0ms service=1596ms status=304 bytes=266 protocol=https"
  },
  {
    "timestamp": "2024-02-22T14:57:46.136603+00:00",
    "process": "heroku[router]",
    "message": "at=info method=GET path=\"/admin/onboarding\" host=dev.wantsandneeds.nl request_id=b993677d-8b11-4250-859c-de12485d99b8 fwd=\"95.98.118.55\" dyno=web.1 connect=0ms service=1325ms status=304 bytes=265 protocol=https"
  },
  {
    "timestamp": "2024-02-22T14:57:46.136704+00:00",
    "process": "app[web.1]",
    "message": "95.98.118.55 - - [22/Feb/2024:14:57:46 +0000] \"GET /admin/onboarding HTTP/1.1\" 304 - \"https://admin.wantsandneeds.nl/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36\""
  },
  {
    "timestamp": "2024-02-22T14:57:46.366587+00:00",
    "process": "app[web.1]",
    "message": "95.98.118.55 - - [22/Feb/2024:14:57:46 +0000] \"GET /admin/sales-channels?limit=10 HTTP/1.1\" 304 - \"https://admin.wantsandneeds.nl/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36\""
  },
  {
    "timestamp": "2024-02-22T14:57:46.366689+00:00",
    "process": "heroku[router]",
    "message": "at=info method=GET path=\"/admin/sales-channels?limit=10\" host=dev.wantsandneeds.nl request_id=0ed05882-df16-4fa8-9542-3d46af5a4971 fwd=\"95.98.118.55\" dyno=web.1 connect=0ms service=1109ms status=304 bytes=266 protocol=https"
  },
  {
    "timestamp": "2024-02-22T14:57:46.377209+00:00",
    "process": "app[web.1]",
    "message": "95.98.118.55 - - [22/Feb/2024:14:57:46 +0000] \"GET /admin/users HTTP/1.1\" 304 - \"https://admin.wantsandneeds.nl/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36\""
  },
  {
    "timestamp": "2024-02-22T14:57:46.377393+00:00",
    "process": "heroku[router]",
    "message": "at=info method=GET path=\"/admin/users\" host=dev.wantsandneeds.nl request_id=3c35d4f9-e97e-4551-b1b0-d996dc0e6ff8 fwd=\"95.98.118.55\" dyno=web.1 connect=0ms service=2661ms status=304 bytes=266 protocol=https"
  },
  {
    "timestamp": "2024-02-22T14:57:46.393572+00:00",
    "process": "heroku[router]",
    "message": "at=info method=GET path=\"/admin/batch-jobs?limit=100\" host=dev.wantsandneeds.nl request_id=836c30a0-6226-43e7-aae9-7c8fc74f590a fwd=\"95.98.118.55\" dyno=web.1 connect=0ms service=2794ms status=200 bytes=372 protocol=https"
  },
  {
    "timestamp": "2024-02-22T14:57:46.394455+00:00",
    "process": "app[web.1]",
    "message": "95.98.118.55 - - [22/Feb/2024:14:57:46 +0000] \"GET /admin/batch-jobs?limit=100 HTTP/1.1\" 200 50 \"https://admin.wantsandneeds.nl/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36\""
  },
  {
    "timestamp": "2024-02-22T14:57:46.867213+00:00",
    "process": "heroku[router]",
    "message": "at=info method=GET path=\"/admin/analytics-configs\" host=dev.wantsandneeds.nl request_id=d7b9b42d-7ad8-4b1d-b688-c366fa2b9cc4 fwd=\"95.98.118.55\" dyno=web.1 connect=0ms service=687ms status=304 bytes=265 protocol=https"
  },
  {
    "timestamp": "2024-02-22T14:57:46.872914+00:00",
    "process": "app[web.1]",
    "message": "95.98.118.55 - - [22/Feb/2024:14:57:46 +0000] \"GET /admin/analytics-configs HTTP/1.1\" 304 - \"https://admin.wantsandneeds.nl/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36\""
  },
  {
    "timestamp": "2024-02-22T14:57:47.182507+00:00",
    "process": "heroku[router]",
    "message": "at=info method=GET path=\"/admin/regions?offset=0&limit=10\" host=dev.wantsandneeds.nl request_id=60082c46-90a9-4e49-8960-31aa99c85228 fwd=\"95.98.118.55\" dyno=web.1 connect=1ms service=2280ms status=304 bytes=266 protocol=https"
  },
  {
    "timestamp": "2024-02-22T14:57:47.184334+00:00",
    "process": "app[web.1]",
    "message": "95.98.118.55 - - [22/Feb/2024:14:57:47 +0000] \"GET /admin/regions?offset=0&limit=10 HTTP/1.1\" 304 - \"https://admin.wantsandneeds.nl/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36\""
  },
  {
    "timestamp": "2024-02-22T14:57:47.770247+00:00",
    "process": "app[web.1]",
    "message": "95.98.118.55 - - [22/Feb/2024:14:57:47 +0000] \"GET /admin/orders?expand=customer%2Cshipping_address&fields=id%2Cstatus%2Cdisplay_id%2Ccreated_at%2Cemail%2Cfulfillment_status%2Cpayment_status%2Ctotal%2Ccurrency_code&offset=0&limit=15 HTTP/1.1\" 304 - \"https://admin.wantsandneeds.nl/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36\""
  },
  {
    "timestamp": "2024-02-22T14:57:47.770474+00:00",
    "process": "heroku[router]",
    "message": "at=info method=GET path=\"/admin/orders?expand=customer%2Cshipping_address&fields=id%2Cstatus%2Cdisplay_id%2Ccreated_at%2Cemail%2Cfulfillment_status%2Cpayment_status%2Ctotal%2Ccurrency_code&offset=0&limit=15\" host=dev.wantsandneeds.nl request_id=4651c8a5-045b-4b00-8413-737898d2693d fwd=\"95.98.118.55\" dyno=web.1 connect=0ms service=2867ms status=304 bytes=266 protocol=https"
  },
  {
    "timestamp": "2024-02-22T14:57:51.861802+00:00",
    "process": "heroku[router]",
    "message": "at=info method=GET path=\"/admin/batch-jobs?limit=100\" host=dev.wantsandneeds.nl request_id=1a1c297a-8d97-4b85-ab9c-2ffa7677fe47 fwd=\"95.98.118.55\" dyno=web.1 connect=0ms service=223ms status=304 bytes=265 protocol=https"
  },
  {
    "timestamp": "2024-02-22T14:57:51.863761+00:00",
    "process": "app[web.1]",
    "message": "95.98.118.55 - - [22/Feb/2024:14:57:51 +0000] \"GET /admin/batch-jobs?limit=100 HTTP/1.1\" 304 - \"https://admin.wantsandneeds.nl/\" \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36\""
  },
  {
    "timestamp": "2024-02-22T14:58:02.147139+00:00",
    "process": "heroku[web.1]",
    "message": "Process running mem=1163M(227.2%)",
    "level": "critical",
    "error": "R15 (Memory quota vastly exceeded)"
  },
  {
    "timestamp": "2024-02-22T14:58:02.149397+00:00",
    "process": "heroku[web.1]",
    "message": "Error R15 (Memory quota vastly exceeded)"
  },
  {
    "timestamp": "2024-02-22T14:58:02.151517+00:00",
    "process": "heroku[web.1]",
    "message": "Stopping process with SIGKILL"
  },
  {
    "timestamp": "2024-02-22T14:58:02.372841+00:00",
    "process": "heroku[web.1]",
    "message": "Process exited with status 137"
  },
  {
    "timestamp": "2024-02-22T14:58:02.396829+00:00",
    "process": "heroku[web.1]",
    "message": "State changed from up to crashed"
  },
  {
    "timestamp": "2024-02-22T14:58:32.009362+00:00",
    "process": "heroku[router]",
    "level": "error",
    "error": "H10",
    "description": "App crashed",
    "method": "GET",
    "path": "/admin/batch-jobs?limit=100",
    "host": "dev.wantsandneeds.nl",
    "request_id": "e74f40bc-3a7b-4f09-aff4-03dc2d7a8053",
    "fwd": "95.98.118.55"
  },
  ...
  {
    "timestamp": "2024-02-22T15:01:22.297069+00:00",
    "process": "heroku[router]",
    "level": "error",
    "error": "H10",
    "description": "App crashed",
    "method": "GET",
    "path": "/admin/batch-jobs?limit=100",
    "host": "dev.wantsandneeds.nl",
    "request_id": "52f92fdf-0e2e-4e68-971b",
    "fwd": "95.98.118.55"
  }
]

### medusa-config.js

`const dotenv = require("dotenv");

console.log("Starting configuration setup...");

let ENV_FILE_NAME = "";
switch (process.env.NODE_ENV) {
  case "production":
    ENV_FILE_NAME = ".env.production";
    console.log("Environment set to production");
    break;
  case "staging":
    ENV_FILE_NAME = ".env.staging";
    console.log("Environment set to staging");
    break;
  case "test":
    ENV_FILE_NAME = ".env.test";
    console.log("Environment set to test");
    break;
  case "development":
  default:
    ENV_FILE_NAME = ".env";
    console.log("Environment set to development (default)");
    break;
}

console.log(`Loading environment variables from: ${ENV_FILE_NAME}`);
dotenv.config({ path: process.cwd() + "/" + ENV_FILE_NAME });

// After loading .env file
console.log("Environment variables loaded. Verifying required variables...");

// List of required environment variables
const requiredEnv = [
  "ADMIN_CORS",
  "STORE_CORS",
  "DATABASE_URL",
  "REDIS_URL",
  "JWT_SECRET",
  "COOKIE_SECRET"
];

const missingEnvVars = requiredEnv.filter(envVar => !process.env[envVar]);

if (missingEnvVars.length > 0) {
  console.error("Missing required environment variables:", missingEnvVars.join(", "));
  // Consider throwing an error or exiting the process if these are critical
  // throw new Error("Missing required environment variables.");
  // process.exit(1);
} else {
  console.log("All required environment variables are present.");
}

console.log("Configuring CORS, Database URL, and other settings...");

// CORS when consuming Medusa from admin
const ADMIN_CORS = process.env.ADMIN_CORS || "http://localhost:7000,http://localhost:7001";
console.log(`ADMIN_CORS set to: ${ADMIN_CORS}`);

// CORS to avoid issues when consuming Medusa from a client
const STORE_CORS = process.env.STORE_CORS || "http://localhost:8000";
console.log(`STORE_CORS set to: ${STORE_CORS}`);

const DATABASE_URL = process.env.DATABASE_URL || "postgres://localhost/medusa-starter-default";
console.log(`DATABASE_URL set to: ${DATABASE_URL}`);

const REDIS_URL = process.env.REDIS_URL || "redis://localhost:6379";
console.log(`REDIS_URL set to: ${REDIS_URL}`);

console.log("Configuring plugins and modules...");

const plugins = [
  `medusa-fulfillment-manual`,
  `medusa-payment-manual`,
  {
    resolve: `@medusajs/file-local`,
    options: {
      upload_dir: "uploads",
    },
  },
  {
    resolve: "@medusajs/admin",
    /** @type {import('@medusajs/admin').PluginOptions} */
    options: {
      autoRebuild: false,
      develop: {
        open: process.env.OPEN_BROWSER !== "false",
      },
    },
  },
];

console.log("Plugins configured.");

const modules = {
  // Uncomment and configure the following lines as needed
  eventBus: {
    resolve: "@medusajs/event-bus-redis",
    options: {
      redisUrl: REDIS_URL
    }
  },
  cacheService: {
    resolve: "@medusajs/cache-redis",
    options: {
      redisUrl: REDIS_URL
    }
  },
};

console.log("Modules configured.");

console.log("Finalizing project configuration...");

const projectConfig = {
  jwtSecret: process.env.JWT_SECRET,
  cookieSecret: process.env.COOKIE_SECRET,
  store_cors: STORE_CORS,
  database_url: DATABASE_URL,
  admin_cors: ADMIN_CORS,
  redis_url: REDIS_URL,
  // Additional configuration as needed
};

console.log("Configuration setup complete.");

module.exports = {
  projectConfig: {
    ...projectConfig,
    database_type: "postgres",
    database_extra: process.env.NODE_ENV !== "development" ? { ssl: { rejectUnauthorized: false } } : {},
  },
  plugins,
  modules,
};

console.log("Configuration file fully loaded.");
`

### package.json

`{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "clean": "cross-env ./node_modules/.bin/rimraf dist",
    "build": "babel src -d dist --extensions \".ts,.js\"",
    "build:server": "cross-env npm run clean && tsc -p tsconfig.server.json",
    "build:admin": "medusa-admin build --deployment",
    "watch": "cross-env tsc --watch",
    "test": "cross-env jest",
    "seed": "cross-env medusa seed -f ./data/seed.json",
        "serve": "medusa start",
    "heroku-postbuild": "medusa migrations run",
    "prepare": "npm run build",
    "start": "medusa develop",
    "start:custom": "cross-env npm run build && node --preserve-symlinks --trace-warnings index.js",
    "dev": "cross-env npm run build:server && medusa develop"
  },
  "dependencies": {
    "@medusajs/admin": "^7.1.11",
    "@medusajs/cache-inmemory": "^1.8.9",
    "@medusajs/cache-redis": "^1.8.9",
    "@medusajs/event-bus-local": "^1.9.8",
    "@medusajs/event-bus-redis": "^1.8.11",
    "@medusajs/file-local": "^1.0.3",
    "@medusajs/medusa": "1.20.2",
    "@tanstack/react-query": "4.22.0",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "dotenv": "16.3.1",
    "express": "^4.17.2",
    "medusa-fulfillment-manual": "^1.1.39",
    "medusa-interfaces": "^1.3.8",
    "medusa-payment-manual": "^1.0.24",
    "medusa-payment-stripe": "^6.0.7",
    "prism-react-renderer": "^2.0.4",
    "typeorm": "^0.3.16"
  },
  "devDependencies": {
    "@babel/cli": "^7.14.3",
    "@babel/core": "^7.14.3",
    "@babel/preset-typescript": "^7.21.4",
    "@medusajs/medusa-cli": "^1.3.21",
    "@types/express": "^4.17.13",
    "@types/jest": "^27.4.0",
    "@types/node": "^17.0.8",
    "babel-preset-medusa-package": "^1.1.19",
    "cross-env": "^7.0.3",
    "eslint": "^6.8.0",
    "jest": "^27.3.1",
    "rimraf": "^3.0.2",
    "ts-jest": "^27.0.7",
    "ts-loader": "^9.2.6",
    "typescript": "^4.5.2"
  },
  "jest": {
    "globals": {
      "ts-jest": {
        "tsconfig": "tsconfig.spec.json"
      }
    },
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "testPathIgnorePatterns": [
      "/node_modules/",
      "<rootDir>/node_modules/"
    ],
    "rootDir": "src",
    "testRegex": "(/__tests__/.*|\\.(test|spec))\\.(ts|js)$",
    "transform": {
      ".ts": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "./coverage",
    "testEnvironment": "node"
  },
  "overrides": {
    "@medusajs/admin-ui": {
      "@medusajs/ui-preset": "^1.1.2"
    }
  },
  "resolutions": {
    "@medusajs/ui-preset": "^1.1.2"
  }
}`

**Comment by olivermrbl** [comment]
Please post the logs in a readable format.

**Comment by crnls** [comment]
> Please post the logs in a readable format.

@olivermrbl Edited for clarity, thanks for letting me know.

**Comment by crnls** [comment]
This was fixed my removing every mention of the medusa admin in package.json build scripts and medusa-config.js. Even though I followed the guides step-for-step, the heroku server kept trying to deploy the admin as well (admin is already deployed on vercel).
