### ISSUE TITLE
Admin customer groups api errors

### ISSUE THREAD

**Issue by shethshlok** [medusajs/medusa#6479]
Bug report

Describe the bug
I have my Medusa Admin set up as a plugin with the backend configured with NODE_ENV set to development. The Admin panel seems to work fine, as I am able to add products and edit them. However, I am encountering an issue where I am unable to add any customers to customer groups.

System information
Medusa version (including plugins): Medusa Admin 7.1.11, Medusa 1.20.1
Node.js version: 20.11.0
Database: postgres
Operating system: Ubuntu 20
Browser (if relevant): Safari and Brave ( both not working )
Steps to reproduce the behavior
1. Go to admin, customers and then customer groups
2. Click on a customer groups and edit customers
3. Select Edit customers
4. try to add another customer to the group
Expected behavior
I expected to be able to see the list of customers in the list to add them to the customer group

Screenshots
Here is the screenshot of the browser console:
<img width="1470" alt="Screenshot 2024-02-22 at 2 30 08 AM" src="https://github.com/medusajs/medusa/assets/92412925/2d17010c-f3eb-4a29-91f1-dd391b403173">

Screenshot of the backend logs:
<img width="1283" alt="Screenshot 2024-02-22 at 2 37 17 AM" src="https://github.com/medusajs/medusa/assets/92412925/22ca82d0-7dc5-414e-ae4c-bb46f81d79aa">

Additional context
I have been stuck on this issue for days and would appreciate any assistance. Here is a screenshot of the browser console for reference. Please help, @olivermrbl.

**Comment by SalahAdDin** [comment]
@xyzones your PR was closed.
