### ISSUE TITLE
formatVariantPrice working incorrectly for RSD (Serbian Currency)

### ISSUE THREAD

**Issue by simovicaleksa** [medusajs/medusa#6488]
### Bug description
As described in the title the `formatVariantPrice` function is not working correctly for Serbian RSD currency. For example if I input the price of 4000 RSD in admin and use the code below it shows in storefront as `RSD 40.00` instead of `RSD 4000.00` as it should.

Code Snippet:
```tsx
import { formatVariantPrice } from "medusa-react";

const formattedAmount = formatVariantPrice({ variant, region: regionInfo });

// formattedAmount: RSD 40.00
// expected: RSD 4000.00
```

### System information

Medusa version: "@medusajs/medusa-js": "^6.1.7"
Node.js version:  v20.9.0
Operating system: Windows 10

### Steps to reproduce the behavior

in **admin**:
1. add RSD currency.
2. set RSD as default currency for a region.
3. add product that has price in RSD (`4000.00 RSD` in this example).

in **storefront**:
1. use `formatVariantPrice` with added product `variant` and `region` as arguments.

### Expected behavior
Get a **100x** value from what the `formatVariantPrice` outputs.

### Screenshots
![image](https://github.com/medusajs/medusa/assets/102186502/16f108d9-da65-418d-a475-cf56cebcb806)
![image](https://github.com/medusajs/medusa/assets/102186502/7a3ce837-b6db-44c1-b730-4b3ec886d19f)

**Comment by SalahAdDin** [comment]
@Aleksa1312 any update on this?
