### ISSUE TITLE
Typo in Configurations/database_url [:post] instead of [:port]

### ISSUE THREAD

**Issue by nkhar** [medusajs/medusa#6502]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

There is a typo:
https://docs.medusajs.com/development/backend/configurations#database_url
instead of [:port] there is [:post]
[:post]: an optional port that the PostgreSQL server is listening on. By default, it's 5432. When provided, make sure to put : before the port.

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch! You can fix it [here](https://github.com/medusajs/medusa/blob/3b18f399c120d5bf2e5ede3b043b20271d65b31a/packages/types/src/common/config-module.ts#L249)

**Comment by nkhar** [comment]
@shahednasser thank you for helping with the fix. 

This is my first open source contribution to Medusa JS and in fact this is my first contribution to JS/TS repository. There are likely to be mistakes in the PR. Please feel free to provide any feedback so that I can improve my contribution.

https://github.com/medusajs/medusa/pull/6505
