### ISSUE TITLE
Razorpay order_id ,'An error occurred in updatePayment:\r\n`order_id` is mandatory'  and also in client side "usecheckout" from checkout-context file is not available in latest medusa 

### ISSUE THREAD

**Issue by suganyasai1026** [medusajs/medusa#6511]
## Bug report
import { useCheckout } from "@lib/context/checkout-context"
file not available and 
data: {
      code: '',
      type: 'invalid_data',
      message: 'An error occurred in updatePayment:\r\n`order_id` is mandatory'
    }
  },

### Code snippets
const plugins = [
  {
    resolve: `medusa-payment-razorpay`,
    options: {
      key_id: process.env.RAZORPAY_ID ?? "",
      key_secret: process.env.RAZORPAY_SECRET?? "",
      razorpay_account: process.env.RAZORPAY_ACCOUNT??"",
      automatic_expiry_period: 30,
      // /any value between 12minuts and 30 days expressed in minutes/
      manual_expiry_period: 20,
      refund_speed: "normal",
      webhook_secret: process.env.RAZORPAY_SECRET??"",
    }
  },
  
  documentation :https://medusajs.com/plugins/medusa-payment-razorpay/
If applicable, add code samples to help explain your problem

**Comment by theStonedSage** [comment]
Hey @suganyasai1026 I am also trying to integrate razorpay and facing the exact same issue

were you able to solve this ?

**Comment by suganyasai1026** [comment]
no

**Comment by sumanchy88** [comment]
There are two issues with respect to plugin - 
1. order_id needs to be added in file `medusa-core/packages/medusa/src/interfaces/payment-processor.ts` which is consumed by plugin `medusa-payment-razorpay` 
2. order_id needs to be added in plugin `medusa-payment-razorpay` under file `src/core/razorpay-base.ts` in methods - 
```
async initiatePayment(
    context: PaymentProcessorContext
  ): Promise<PaymentProcessorError | PaymentProcessorSessionResponse> {
    const intentRequestData = this.getPaymentIntentOptions();
    const {
      email,
      currency_code,
      amount,
      resource_id,
      customer,
      paymentSessionData,
      order_id
    } = context;
```
and 
```
async updatePayment(
    context: PaymentProcessorContext
  ): Promise<PaymentProcessorError | PaymentProcessorSessionResponse | void> {
    const { amount, customer, paymentSessionData, currency_code, order_id } = context;
```

**Comment by rishabh-zangoh** [comment]
@suganyasai1026 or @sumanchy88 did you people find any solution for this as i am facing the same issue

**Comment by whiletrueee** [comment]
Hey! Guys I am facing the same issue, any solutions ?

**Comment by manishkumar212111** [comment]
Any solution I still looking ?

**Comment by rahatsayyed** [comment]
@suganyasai1026 @whiletrueee @theStonedSage @sumanchy88 @rishabh-zangoh @manishkumar212111 


can you help me with this error. 
I have completed entire steps but I the payment button is disabled 
updated 3 files (constants.tsx, payment-button/index.tsx, payment-button/razorpay-payment-button.tsx and env.local with keyidas rzp_test_... storename and discription
![image](https://github.com/SGFGOV/medusa-payment-razorpay/assets/70068895/9ef79543-3a9d-4b80-b4ee-1e3e957c26f2)
![image](https://github.com/SGFGOV/medusa-payment-razorpay/assets/70068895/5bd6fcd9-4748-4c95-af67-d2fa41e80098)

**Comment by manishkumar212111** [comment]
@youreachedrahat Please use this https://digitaldrift.blog/programming/medusa-payment-razorpay-poorvika-plugin-7

**Comment by rahatsayyed** [comment]
I ran this command `npm i medusa-payment-razorpay-poorvika` to install 
but still getting this issue no 
```
⠋ Initializing plugin models
error:   Error starting server
Error: Unable to find plugin "medusa-payment-razorpay". Perhaps you need to install its package?
```

**Comment by manishkumar212111** [comment]
Also update plugin name in Medusa-config

**Comment by rahatsayyed** [comment]
Now I have same issue as others

```
error:   unable to retrieve customer from cart
error:   unable to find razorpay customer
error:   no customer billing found:
no customer billing found null
Error: no customer billing found:
no customer billing found null



{
  type: 'invalid_data',
  code: '',
  date: 2024-07-09T14:47:51.706Z
}
```


client side
```
message: 'no customer billing found:\r\nno customer billing found null'
```

**Comment by manishkumar212111** [comment]
Create new customer and then try

**Comment by rahatsayyed** [comment]
already have user

![image](https://github.com/medusajs/medusa/assets/70068895/57797fa7-5639-49b2-8fea-70fad68cf24c)

**Comment by rahatsayyed** [comment]
```
⠋ Initializing defaults
TypeError: Cannot read properties of undefined (reading 'getRepeatableJobs')
```

is it related

**Comment by MikhailNarkevich** [comment]
@youreachedrahat  Do you have any updates?
I get the error `TypeError: Cannot read properties of undefined (reading 'getRepeatableJobs')`
Using the plugin from the community `medusa-plugin-postmark`, maybe if you know a solution to your problem with this error it will help me too
Thanks in advance for your answer

**Comment by rahatsayyed** [comment]
@MikhailNarkevich unfortunately no.
I reinstalled and added the plugin then it works

**Comment by manishkumar212111** [comment]
Please read this I have updated this library with new one https://digitaldrift.blog/programming/medusa-payment-razorpay-poorvika-plugin-7. It's working and fully tested
