### ISSUE TITLE
Payment session is undefined when using Stripe in test mode. 

### ISSUE THREAD

**Issue by SyedYaseen** [medusajs/medusa#6517]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Works fine when live mode creds are provided. 
Using a fresh database with migrations and seed data.

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by scrlkx** [comment]
I'm facing this often. I'm not sure about what's the problem though. I'm using test credentials indeed, but as far as I can see the error appears to be random, sometimes working properly.

**Comment by scrlkx** [comment]
It seems that, if I disable other payment methods (like manual) for the region, it works nicely with no more issues. Maybe we can do some debug and get some more information?
