### ISSUE TITLE
Docs(Code Issue): Code Issue in /starters/nextjs-medusa-starter

### ISSUE THREAD

**Issue by greendesertsnow** [medusajs/medusa#6545]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Gives this error and I have absolutely no clue why this happens.

An error occurred while installing Next.js storefront: Error: Command failed: npx create-next-app -e https://github.com/medusajs/nextjs-starter-medusa ff-storefront

![image](https://github.com/medusajs/medusa/assets/88274580/68fa2f50-33c3-4374-b24f-653ca5b51b66)

Tried it without storefront, it gives other errors. Node version is 21:
An error occurred while preparing project: Error: Command failed: npm install --legacy-peer-deps
![image](https://github.com/medusajs/medusa/assets/88274580/2bd9fc4e-195a-4b6d-81f1-572246a0433e)

### How can this issue be resolved?

1. By having a more understandable installation process
2. Not mixing yarn and npm throughout the project
3. Having a proper Dockerfile to handle the installation.
4. Going through the documentation and checking each code to see if they throw error...
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for submitting this issue. Can you try installing yarn? We use `npm` as a fallback but sometimes that causes issues when installing dependencies. You can instead try changing to the directory created after the error occurs, running `npm install --legacy-peer-deps` and sharing the error output

**Comment by greendesertsnow** [comment]
I don't get to chose the installer
It's Medusa's decision to jump from yarn to npm during installation 
This is the command I ran. It doesn't matter pnpm or npm, and there's no yarn installation command in the docs. Please check.
https://docs.medusajs.com/create-medusa-app#step-1-run-create-medusa-app

If you want me to go to the directory of the broken installation and run `yarn install` then things get installed. But this is not a smooth experience.

Why don't you guys just upgrade your node version from 17 to 21 already?!

**Comment by greendesertsnow** [comment]
In order to solve it

Go and change the node version to the LTS
```sh
npm install -g n
n 20.11.1
```
