### ISSUE TITLE
Discount coupon is not expired on abandoned cart

### ISSUE THREAD

**Issue by kb-0912** [medusajs/medusa#6551]
Example: 

- Store has discount coupon has expired date (Example: Jan 30 2024)

- Customer add the coupon code to their cart (any date before Jan 30 2024) but they're not complete the order

- Customer comeback after expired date (Example: Feb 20 2024) to complete the order / add new items to their cart => the coupon still working.

In this case, the coupon should be removed before customer complete the order

**Comment by alessioacella** [comment]
up

**Comment by mezzat11** [comment]
This critical issue @olivermrbl and effecting business .
