### ISSUE TITLE
401 Unauthorized retrieving customer information

### ISSUE THREAD

**Issue by QueeNFrisk** [medusajs/medusa#6569]
### Describe the bug
I have just installed and set up Medusa, and I'm using the JS Client with Vue 3. Within my interface, I need to determine if the user is logged in and, if so, display certain information. However, I am encountering an error (Figure 1)

### System information

Medusa version (including plugins): 1.20.2 (Figure 2)
Node.js version: 20.11.0
Database: 16.2.1
Operating system: Windows 11 23H2 x64
Browser (if relevant): Brave V1.63.165 / Google Chrome V122.0.6261.95 

### Steps to reproduce the behavior

[ Fresh installation ]

### Expected behavior
Within my interface, I need to determine if the user is logged in and, if so, display certain information

### Screenshots
![image](https://github.com/medusajs/medusa/assets/11914764/6c50671d-e9ae-4557-b7ec-36d9cf8f2437)
*[Figure 1]*

![image](https://github.com/medusajs/medusa/assets/11914764/4a5ed0ef-9b8a-4eb4-808e-db65593eae12)
*[Figure 2] - Backend package.json*

![image](https://github.com/medusajs/medusa/assets/11914764/e1c8eb7c-8783-4553-aae9-92e636cefd8f)
*Frontend medusa-config.js*

### Code snippets

![image](https://github.com/medusajs/medusa/assets/11914764/093049fd-dc3c-494b-aafa-bd49d3ae5335)
*I've already tried with and without "Custom Headers"; with http://127.0.0.1:9000 and http://localhost:9000*

### Additional context

Add any other context about the problem here

**Comment by olivermrbl** [comment]
Please provide reproducible steps, otherwise we can't help.

**Comment by QueeNFrisk** [comment]
> Medusa new storebackend
> cd storebackend
> Medusa develop

Basicaly that.

**Comment by QueeNFrisk** [comment]
Project deleted
