### ISSUE TITLE
Product page returns 500 error after fresh install and deployment

### ISSUE THREAD

**Issue by guillermotti** [medusajs/medusa#6571]
### Describe the bug

I've just deployed all the components (backend, admin and storefront) and navigating to a product is returning a 500 error in the frontend deployed in Vercel. Backend and admin are deployed using a Dockerfile in Fly.io.

Locally with the same code, everything is working fine. I'm opening the backend+admin and storefront separetely with `npm run dev`.

### System information

Medusa version (including plugins): 7.1.11
Node.js version: 20
Database: Postgresql
Operating system: MacOS
Browser (if relevant): 

### Steps to reproduce the behavior

Navigating to https://damnswag.com/es/store works fine but opening a product like https://damnswag.com/es/products/medusa returns a 500 error. 

### Expected behavior

The product should not return any error.

### Screenshots

<img width="434" alt="image" src="https://github.com/medusajs/medusa/assets/27063578/d84905eb-f21d-462a-92c8-608cfc98c860">

### Additional context

Backend logs

```
 2024-03-02T19:00:12.802 app[7811173b620238] mad [info] 66.241.124.235 - - [02/Mar/2024:19:00:12 +0000] "GET /store/products/prod_01HR06R19J5TA5TSEJ9ZMCZFRZ?region_id=reg_01HR06R169V7KZKTERX24X4PGQ HTTP/1.1" 200 19955 "-" "axios/0.24.0"

2024-03-02T19:02:20.419 app[7811173b620238] mad [info] 66.241.124.235 - - [02/Mar/2024:19:02:20 +0000] "GET /store/regions HTTP/1.1" 200 683 "-" "Vercel Edge Functions"

2024-03-02T19:02:23.582 app[7811173b620238] mad [info] 66.241.124.235 - - [02/Mar/2024:19:02:23 +0000] "GET /store/regions HTTP/1.1" 200 683 "-" "Vercel Edge Functions" 
```

**Comment by olivermrbl** [comment]
This information doesn't help us. The logs you have provided show a status code 200.

If you provide the error message, we can try to help.

**Comment by cheejiayuan512** [comment]
getting this error too, no error messages on the runtime logs on the backend i deployed on digitalocean

its a frontend issue, from vercel logs:

 ⨯ [Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: 'DYNAMIC_SERVER_USAGE',
  page: '/sg/products/medusa-t-shirt'
}
Error: Runtime exited with error: exit status 1
Runtime.ExitError


https://stackoverflow.com/questions/76305664/next-js-error-in-production-mode-digest-1782794309

If anyone is deploying to Vercel, please uncomment generateStaticParams from the src/app/[countryCode]/main/products/[handle]/page.tsx file. Making my explanation more verbose as there seems to be a lot of new devs trying this project out

![image](https://github.com/medusajs/medusa/assets/13083403/cd46e7a9-93df-4625-83a9-969aa580bd79)

**Comment by bruno-espino** [comment]
Thanks @cheejiayuan512, I was having the same issue.
Did you find a better way to do this or did you just leave this piece of code commented?

**Comment by cheejiayuan512** [comment]
Didn't manage to get more time to work on a proper fix unfortunately, let me know if you do!
    On Thursday, 20 June 2024 at 05:45:02 am SGT, Bruno Espino ***@***.***> wrote:  
 
 


Thanks @cheejiayuan512, I was having the same issue.
Did you find a better way to do this or did you just leave this piece of code commented?

**Comment by redareda9** [comment]
Same problem here on a fresh install with Digital Ocean

**Comment by sradevski** [comment]
Hey all, if you are only experiencing this issue on your hosting, it is likely an issue with your configuration. For help with such issues, please reach out on Discord, as the github issues are strictly used for reporting bugs with the platform itself. Thanks!

**Comment by redareda9** [comment]
Hi @sradevski, 

This doesn't seem to be a bug with the configuration. 

For me, the problem was solved by adding 
`export const dynamic = "force-dynamic"`

just after 
`export default ProductTemplate`

on this file: /src/modules/products/templates/index.tsx

**Comment by fxck** [comment]
Also getting this, fresh install of latest medusa and storefront, nothing changed over the default installation. Adding `export const dynamic = "force-dynamic"` doesn't seem to help, no error shown on the server.

**Comment by fxck** [comment]
At least another 4 people reporting on Discord 

https://discord.com/channels/876835651130097704/1303993726795911259/1303993726795911259
https://discord.com/channels/876835651130097704/1252406570852286537/1252406570852286537

Seems to be problem with the code rather than hosting.

**Comment by kanrio** [comment]
same error here any solution ?

**Comment by Ivaylo-Korakov** [comment]
I just ran into the same issue - there seems to have been a change in next between versions `15.0.3` and `15.2.3` that started causing this error - following the updated docs and everything it does seem that you can't have static routes if at any point in the render of that static route you access cookies. (That was the case before as well but it failed silently) This happens because we use the next/headers when calling `listProducts` or `listRegions` etc.

In the `listRegions` we use the `getCacheOptions` which uses `cookies` but we have a check like this:
```ts
  if (typeof window !== "undefined") {
    return {}
  }
```
so that works without an issue.   
But in our `listProducts` we have both `getCacheOptions` and `getAuthHeaders`. 

`getAuthHeaders` doesn't have a check like that so every time Next JS tries to staticly generate that page it tries to read cookies which is imposible. The weird thing is that you don't need to have a Medusa JWT in the Auth header in order to get a product or list all products. 

To solve the issue either add a similar check as `getCacheOptions` in `getAuthHeaders` or do as I did and just remove the whole need for getting auth headers with JWT for just loading the products.

**Comment by abdrhxyii** [comment]
I fixed the issue by below two changes

src/lib/data/cookies.ts
```
import "server-only"
import { cookies as nextCookies } from "next/headers"

export const getAuthHeaders = async (): Promise<
  { authorization: string } | {}
> => {
  if (typeof window !== "undefined") {
    return {}
  }

  try {
    const cookies = await nextCookies()
    const token = cookies.get("_medusa_jwt")?.value

    if (!token) {
      return {}
    }

    return { authorization: `Bearer ${token}` }
  } catch {
    return {}
  }
}
```

src/modules/products/templates/index.tsx

```
export default ProductTemplate
export const dynamic = "force-dynamic"
```

**Comment by skndash96** [comment]
just comment out generateStaticParams() function wherever you find it. (i found 3 files)
works for me.
