### ISSUE TITLE
 An error occurred while processing SEARCH_INDEX_EVENT (Meilisearch)

### ISSUE THREAD

**Issue by kaisiant** [medusajs/medusa#6574]
### Describe the bug

Not able to create index, it stated authorization header is missing. Tried curl, it works.

### System information

"@medusajs/medusa": "1.20.0",
"medusa-plugin-meilisearch": "^2.0.10",
meilisearch: v1.3.4

### Screenshots

<img width="805" alt="image" src="https://github.com/medusajs/medusa/assets/26655111/33ef7bc4-64ff-49d8-8e40-c541eca330b6">

### Code snippets
```

{
    resolve: `medusa-plugin-meilisearch`,
    options: {
      // config object passed when creating an instance
      // of the MeiliSearch client
      config: {
        host: process.env.MEILISEARCH_HOST,
        apiKey: process.env.MEILISEARCH_API_KEY,
      },
      settings: {
        products: {
          indexSettings: {
            searchableAttributes: [
              "title", 
              "variant_sku",
            ],
            displayedAttributes: [
              "id", 
              "title", 
              "variant_sku", 
              "thumbnail", 
              "handle",
            ],
          },
          primaryKey: "id",
        },
      },
    },
  },
```

**Comment by nfzv** [comment]
May I ask if you are actually providing the MEILISEARCH_API_KEY env variable?

Here are some reasons you might get this error:
1. Using an api key header instead of Authorization header with Bearer token.
2. Not providing any token (env variable is not set)
3. Your Meilisearch issued api key for backend is obsolete, make sure to make GET /keys request to check if everything is alright.

**Comment by kaisiant** [comment]
<img width="598" alt="image" src="https://github.com/medusajs/medusa/assets/26655111/106d0649-7593-49e4-aa85-505dc56555f0">


> May I ask if you are actually providing the MEILISEARCH_API_KEY env variable?
> 
> Here are some reasons you might get this error:
> 
> 1. Using an api key header instead of Authorization header with Bearer token.
> 2. Not providing any token (env variable is not set)
> 3. Your Meilisearch issued api key for backend is obsolete, make sure to make GET /keys request to check if everything is alright.

1. I am using master key.
2. The variable is set in railway
3. The master key is valid, i had used it to generate api key

**Comment by kaisiant** [comment]
lol, the host need to include the `https`.
