### ISSUE TITLE
Getting Error in medusa-store-analytics 

### ISSUE THREAD

**Issue by AbhinavChavareTechcopain** [medusajs/medusa#6583]
We have developed an Ecommerce marketplace with some customization,
Now we need the store analytics  but when we insert into medusa and run, we are getting error
Please guide for the same

### System information
Node.js version: v18.12.1
Database: PostgreSQL
   "@medusajs/medusa": "^1.18.1",
    "@rsc-labs/medusa-store-analytics": "^0.7.0",
    
    
![image](https://github.com/medusajs/medusa/assets/126047812/5f304a40-cf87-40bb-bf51-effb7e4837d7)
![image](https://github.com/medusajs/medusa/assets/126047812/965920d4-2f50-48fc-a828-7482e211e946)

**Comment by olivermrbl** [comment]
Can I get you to ensure you have the latest version of `medusa-interfaces` installed?

**Comment by AbhinavChavareTechcopain** [comment]
Sorry for delay,
We have installed latest version of  "medusa-interfaces": "^1.3.8", but getting error like
![image](https://github.com/medusajs/medusa/assets/126047812/21233276-437c-4839-942d-981278e4613c)
![image](https://github.com/medusajs/medusa/assets/126047812/6a3fd174-fccd-424d-b8ac-2d030bae1eae)
![image](https://github.com/medusajs/medusa/assets/126047812/613a77f0-6b21-45ef-a647-6bb32c550072)

**Comment by AbhinavChavareTechcopain** [comment]
Awaiting for reply.

**Comment by AbhinavChavareTechcopain** [comment]
Awaiting for reply
________________________________

**Comment by AbhinavChavareTechcopain** [comment]
Please reply,
I am waiting, need to remove this bug.

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
