### ISSUE TITLE
"Property expand should not exist" error for "/admin/returns" API route 

### ISSUE THREAD

**Issue by AlexTechNoir** [medusajs/medusa#6587]
### Describe the bug

Good day!

I tried to request `/admin/returns?expand=items.item` route, but terminal says it's not expandable:

```bash
error:   property expand should not exist
Error: property expand should not exist
    at C:\Users\Alex\Desktop\medusa-project\node_modules\@medusajs\medusa\dist\utils\validator.js:153:31
    at step (C:\Users\Alex\Desktop\medusa-project\node_modules\@medusajs\medusa\dist\utils\validator.js:44:23)
    at Object.next (C:\Users\Alex\Desktop\medusa-project\node_modules\@medusajs\medusa\dist\utils\validator.js:25:53)  
    at fulfilled (C:\Users\Alex\Desktop\medusa-project\node_modules\@medusajs\medusa\dist\utils\validator.js:16:58) {  
  type: 'invalid_data',
  code: undefined,
  date: 2024-03-05T14:56:16.211Z
}
::1 - - [05/Mar/2024:14:56:16 +0000] "GET /admin/returns?expand=items.item HTTP/1.1" 400 68 "http://localhost:7001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
```

Without `expand`, route is working properly

### System information

Medusa version (including plugins): 1.20.0
Node.js version: 18.16.1
Database: PostgreSQL
Operating system: Win 10
Browser (if relevant):

### Steps to reproduce the behavior

1. Setup Medusa project
2. Create any Admin page/component and make a request to `/admin/returns?expand=items.item`
3. See error in terminal

### Expected behavior

Expandable API route

**Comment by olivermrbl** [comment]
@AlexTechNoir, thanks for highlighting. Would you like to send a PR for it? We will not prioritize this in the near future. You should follow the same pattern applied in many other endpoints. Let me know, and I can help.

**Comment by AlexTechNoir** [comment]
I don't know auto-tests, so I can't contribute, if that's a requirement
