### ISSUE TITLE
Can't able to export orders 

### ISSUE THREAD

**Issue by gaurav0909-max** [medusajs/medusa#6613]
In medusa admin panel , I got an issue like when trying to export orders in orders page,
I got download failed error.

### System information

Medusa version (including plugins):1.20.2
Node.js version:latest
Database:PostgreSQL
Operating system:windows
Browser (if relevant):chrome

1. Go to admin panel : http://localhost:7001/a/orders?offset=0&limit=15
2. Click on "Export orders" button
3. Downloaded successfully is displayed but not actually it happened.
4. see error of download failed in notification history.

### Screenshots
![Export-orders jpg](https://github.com/medusajs/medusa/assets/81897751/2a3e41f7-5511-44b9-8f39-5633f8b6621f)

Waiting for the valuable answer from any community member or main contributors.

**Comment by olivermrbl** [comment]
Can you share any error logs you are seeing in your terminal?

Also, do you have a [file plugin](https://docs.medusajs.com/plugins/file-service/) installed? If not, please install one and try again.

**Comment by gaurav0909-max** [comment]
I have already installed medusa-file-cloudinary package.Is it enough or not?
![Terminal-logs jpg](https://github.com/medusajs/medusa/assets/81897751/ffb9c6d8-66b8-43fb-8855-c3ab95f8b9c7)
here is my terminal logs may it helps you to resolve this issue.

**Comment by olivermrbl** [comment]
It looks like your file plugin is not up to date with our [file service interface](https://github.com/medusajs/medusa/blob/a516e7bcbabb7ecaf0f7ee4238085c6fd68d90e8/packages/medusa/src/interfaces/file-service.ts#L81). It is missing the method `getUploadStreamDescriptor`.

I suggest you try one of our official plugins, or alternatively update the plugin to contain implementations of all methods.

Closing for now.
