### ISSUE TITLE
MVR is missing from currencies.ts

### ISSUE THREAD

**Issue by ismathz** [medusajs/medusa#6619]
### Describe the bug

Maldivian Rufiyaa (MVR) is missing from currencies.js, hence not able to use it for setting price of products.

### System information

Medusa version: 1.19
Medusa Admin version: 7.1.9

### Steps to reproduce the behavior

1. In the admin UI, go to 'Settings > Currencies'
2. Click on 'Edit currencies'
3. Click on 'Add currencies'
4. MVR is not available

### Expected behavior

Maldivian Rufiyaa (MVR) to be available on the list of currencies in admin settings.

### Additional context

It is possible to run a database migration and add MVR to the currencies table, and add it as a currency from settings. However, it's not possible to set a price of a variant for that currency, and it throws an error because the admin UI reads additional currency data from currencies.ts.

### Requested fix

Add the following MVR data to the currencies list in these two files
1. `medusa/packages/admin-ui/ui/src/utils/currencies.ts`
2. `medusa/packages/utils/src/defaults/currencies.ts`

MVR data:
```
MVR: {
   symbol: "MVR",
   name: "Maldivian Rufiyaa",
   symbol_native: "ރ",
   decimal_digits: 2,
   rounding: 0,
   code: "MVR",
   name_plural: "rufiyaa",
},
```

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
