### ISSUE TITLE
Docs(Code Issue): Code Issue in /development/entities/extend-entity

### ISSUE THREAD

**Issue by mullerjk** [medusajs/medusa#6637]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The correct path is `src/migrations/1680013376180-changeProduct.ts`
 and the doc says `src/migration/1680013376180-changeProduct.ts`.

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch! Will open a PR to fix it
