### ISSUE TITLE
Docs(Code Issue): Code Issue in /modules/regions-and-currencies/admin/manage-regions

### ISSUE THREAD

**Issue by masrur-mmrs** [medusajs/medusa#6642]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

```prepare-shipping-options.ts
import { Region } from "@medusajs/medusa";
import type Medusa from "@medusajs/medusa-js"

export default async function prepareShippingOptions (client: Medusa, region: Region) {
  let { shipping_options } = await client.admin.shippingOptions.list()
  if (!shipping_options.length) {
    shipping_options = [(await client.admin.shippingOptions.create({
      "name": "PostFake Standard",
      "region_id": region.id,
      "provider_id": "manual",
      "data": {
        "id": "manual-fulfillment"
      },
      "price_type": "flat_rate",
      "amount": 1000,
    })).shipping_option]
  }

  return shipping_options
}``

Type '"flat_rate"' is not assignable to type 'ShippingOptionPriceType'.ts(2322)
create-shipping-option.d.ts(198, 5): The expected type comes from property 'price_type' which is declared here on type 'AdminPostShippingOptionsReq'
(property) AdminPostShippingOptionsReq.price_type: ShippingOptionPriceType

### How can this issue be resolved?

If "flat_rate" is not assignable to the type ShippingOptionPriceType, it means that "flat_rate" is not a valid value for the price_type property. We need to find out what values are acceptable for price_type and use one of those values.


### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for opening this issue. As mentioned in this [troubleshooting page](https://docs.medusajs.com/troubleshooting/admin-webpack-build-types) it's not possible to use Medusa types in Admin customizations. So, in the onboarding admin widget we use the string value of the expected type and add `// @ts-ignore` to avoid TypeScript errors as seen [here](https://github.com/medusajs/medusa-starter-default/blob/334299e2517bd3d21060e99d67017f1539894265/src/admin/utils/prepare-shipping-options.ts#L16)

You can find the expected value in place of the `ShippingOptionPriceType` type in [this reference](https://docs.medusajs.com/references/entities/enums/entities.ShippingOptionPriceType)
