### ISSUE TITLE
customHeaders Is not Working

### ISSUE THREAD

**Issue by th-disha** [medusajs/medusa#6660]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Type '{ children: Element; baseUrl: string; queryClientProviderProps: { client: QueryClient; }; customHeaders: { "x-no-compression": boolean; "x-store-id": string; }; }' is not assignable to type 'IntrinsicAttributes & MedusaProviderProps'.
  Property 'customHeaders' does not exist on type 'IntrinsicAttributes & MedusaProviderProps'

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by olivermrbl** [comment]
Please provide reproducible steps. Closing until then.
