### ISSUE TITLE
Accessing nested fields

### ISSUE THREAD

**Issue by ybirader** [medusajs/medusa#6662]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

For nested field, we usually use the `expand` parameter e.g. `expand: options`, to expand the options field on a product variant.

However, the docs are silent on how to get doubly nested fields e.g. to get the option field for each option, one would assume it would be `options.option`. However this does not work.

How can this be achieved?

### How can this issue be resolved?

1. Add info how to access nested fields to docs

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by D1Atomics** [comment]
@ybirader  Did you find a workaround or a solution?

**Comment by LukasMod** [comment]
Maybe it depends on endpoint. For listing all products from `/store/products` I use `expand=variants.prices` to get variants with nested prices array.

**Comment by shahednasser** [comment]
As @LukasMod mentioned, dot notation works for nested relations (will make sure to add a note about it in the docs).

However, for the original issue, it's unclear to me what you mean by `options.option`. options don't have a nested `option` relation. Can you clarify @ybirader ?

**Comment by shahednasser** [comment]
Closing this for lack of information. feel free to re-open it with more details.

**Comment by marianvlad** [comment]
There is an "option" field on expandable "options" field on [https://docs.medusajs.com/api/store#product-variants_getvariants](https://docs.medusajs.com/api/store#product-variants_getvariants) documentation. I mean how we can get the products variants if we want to make a filter like color, size with the api?

![Screenshot 2024-10-03 at 22 52 49](https://github.com/user-attachments/assets/7f259266-30d9-4b8e-9deb-ee2616a6617c)

How to get the Color option with the API?
![Screenshot 2024-10-03 at 22 56 01](https://github.com/user-attachments/assets/fbbb3466-0a35-4dba-84dd-0307031a72ef)

**Comment by marianvlad** [comment]
Anyway I found this [https://github.com/vholik/medusa-custom-attributes](https://github.com/vholik/medusa-custom-attributes)
