### ISSUE TITLE
Region and Currency code options missing on Price List.

### ISSUE THREAD

**Issue by dmiric** [medusajs/medusa#6670]
### Describe the bug

According to documentation these should be Price list options:

> Price List Conditions
> You can control when a price list is applied using a set of conditions. Only when these conditions are met can the price list be applied.
> 
>You can use any of the following conditions:
>
>Start and/or expiry date: You can set a start date, an end date, or both to define when the prices in the list should be applied.
>Customer group: You can choose a customer group to apply the prices for. Customers that belong to this group will see the prices you set in the list, which customers that don’t belong to the group can’t see.
>Minimum and/or maximum quantity: You can specify the minimum quantity, the maximum quantity, or both minimum and maximum quantities of a product variant required to be in the customer’s cart to apply a price in a price list.
>**Region: You can specify a specific region where a price in the price list is available in. Only customers accessing your store from that region can see these prices.
>Currency Code: You can specify a currency code where a price in the price list is available in. Only customers accessing your store from regions that use this currency can see these prices.**

I can't see last two Region and Currency code on a fresh installation. Is this a bug or are those features not yet implemented?

**Comment by kasperkristensen** [comment]
Hi @dmiric,

It's referring to the fact that you can add region and/or currency prices to a Price List, eg. `prices: [{ amount: 1000, currency_code: "usd", //... }, { amount: 500, region_id: "reg_1234567", // ... }]`. 

The price with the `region_id` will only be available in that region, where the price with a `currency_code` will be available in all regions using that `currency_code`, unless there is a price with that regions id, which in that case takes precedence over the currency price.

**Comment by dmiric** [comment]
Ah ok I get it now. 

Thank you.
