### ISSUE TITLE
You ask for my postgres username ... but then fail claiming a database with that name does not exist!?

### ISSUE THREAD

**Issue by blaasvaer** [medusajs/medusa#6676]
### Describe the bug

Postgres is up and running, have created a user with password, a database named "medusa_test" (for testing this crap).

Then this shit happens:

`$ What's the name of your project? (my-medusa-store) ` [ENTER]
`$ Enter an email for your admin dashboard user (admin@medusa-test.com) ` Change e-mail and [ENTER]
`$ Would you like to create the Next.js storefront? You can also create it later (y/N) ` y [ENTER]
`$ Enter your Postgres username (postgres)` type medusa_user [ENTER] (the user I created in postgres)
`$ Enter your Postgres password [input is hidden]` typing password [ENTER] (the password I created in postgres for that user)
`$ Couldn't connect to PostgreSQL because of the following error: error: database "medusa_user" does not exist.`

Now, why does it claim that a database with my username doesn't exist? I KNOW that, but it was asking me for my username, NOT the database name.

WHY?

### System information

Medusa version (including plugins):
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by blaasvaer** [comment]
So, you actually force me to create BOTH a username AND a database of THE SAME NAME in order for this to work.

Not cool.

**Comment by blaasvaer** [comment]
OK, never mind. I'm NOT spending a single more minute on this crap ... this is what I end up with after this 'weird' Sign Up experience ...

`
Uncaught runtime errors:
ERROR
n is undefined
i@http://localhost:7001/main.bundle.js:689:516
63281/A/a/<@http://localhost:7001/_cache_admin_src_pages_invite_tsx.chunk.js:5:5570
63281/A/a/l/</<@http://localhost:7001/_cache_admin_src_pages_invite_tsx.chunk.js:5:4741
63281/A/a/l/<@http://localhost:7001/_cache_admin_src_pages_invite_tsx.chunk.js:5:4846
_@http://localhost:7001/_cache_admin_src_pages_invite_tsx.chunk.js:5:1239
l@http://localhost:7001/_cache_admin_src_pages_invite_tsx.chunk.js:5:5749
`

**Comment by olivermrbl** [comment]
Sorry to hear you had a bad experience. Happy to help, but please keep a friendly tone. Closing until help is requested.

**Comment by aureliendebord** [comment]
Hello @olivermrbl Is that required that the database name and username have the same name?

I am facing the same problem :

> ? What's the name of your project? my-medusa-store
> ? Enter an email for your admin dashboard user admin@medusa-test.com
> ? Would you like to create the Next.js storefront? You can also create it later Yes
> ? Enter your Postgres username aurelien
> ? Enter your Postgres password [hidden]
> Couldn't connect to PostgreSQL because of the following error: error: database "aurelien" does not exist.

The cli asks for a postgres username but the error message is about the database name. It's hard to figure whats wrong or what is the needed information here.
