### ISSUE TITLE
While importing the products, My variants are getting created as products only

### ISSUE THREAD

**Issue by Kushal-starr** [medusajs/medusa#6683]
While I'm importing the Products using the CSV file via documentation, my variants are also getting imported as a products only.

Any suggestions, how to resolve this. Is any key/values needs to change.

My help, its urgent!!!

Thanks in advance.

**Comment by Kushal-starr** [comment]
@olivermrbl could you look into the above mentioned issue. Thanks!

**Comment by sradevski** [comment]
Hey, please make sure you [go through the docs](https://docs.medusajs.com/modules/products/admin/import-products) and you use the same CSV format as suggested there. Thanks!
