### ISSUE TITLE
API Ref(admin): Issue in List Orders

### ISSUE THREAD

**Issue by BorisKamp** [medusajs/medusa#6690]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I did not find how to specify the `sort` in combination with the `order`. I had to dive in the code to find this comment line:
`The field to sort the data by. By default, the sort order is ascending. To change the order to descending, prefix the field name with '-'.`
in `@medusajs/medusa/dist/api/routes/admin/orders/list-orders.d.ts` to figure out I need to prefix with `-` or not.

Would be nice if this is documented in the API docs in the param description! And does'nt hurt to mention how to `order` on nested data, if this is possible at all, for example: `customer.first_name`.

### How can this issue be resolved?

Make the docs clearer

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Hello, thank you for your input! We actually do mention this under the [Pagination](https://docs.medusajs.com/api/admin#pagination) section. You'll find a sort order sub-section with details on this.

**Comment by BorisKamp** [comment]
> Hello, thank you for your input! We actually do mention this under the [Pagination](https://docs.medusajs.com/api/admin#pagination) section. You'll find a sort order sub-section with details on this.

Ah I see, well it doesn't hurt to link to that pagination section from other parts of the API docs right? And what about nested relational fields like in my example above?
