### ISSUE TITLE
Docs(Code Issue): Code Issue in /development/backend/prepare-environment

### ISSUE THREAD

**Issue by Falowo** [medusajs/medusa#6716]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

the error is when I tried this command there is many deprecated warning ( node -v    v20.11.1)
sudo npm install @medusajs/medusa-cli -g
[sudo] password for *****: 
npm WARN deprecated @oclif/screen@1.0.4: Deprecated in favor of @oclif/core
npm WARN deprecated @oclif/command@1.8.36: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated @oclif/help@1.0.15: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated @oclif/errors@1.3.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated @oclif/errors@1.3.5: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated @oclif/config@1.18.16: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated @oclif/config@1.18.17: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated @oclif/parser@3.8.17: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated @oclif/config@1.18.2: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated cli-ux@5.6.7: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.

added 330 packages in 22s

48 packages are looking for funding
  run `npm fund` for details

then when creating new project 

k0xxx:~$ medusa new my-project --seed
╔════════════════════════════════════════════════════════════════════════╗
║                                                                        ║
║   Medusa collects anonymous usage analytics                            ║
║   to help improve Medusa for all users.                                ║
║                                                                        ║
║   If you'd like to opt-out, you can use `medusa telemetry --disable`   ║
║                                                                        ║
║                                                                        ║
╚════════════════════════════════════════════════════════════════════════╝
✔ Created starter directory layout – 718ms
info:    Installing packages...

info:    Preferred package manager set to "npm"
npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm WARN deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead
npm WARN deprecated @oclif/config@1.18.16: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated domexception@2.0.1: Use your platform's native DOMException instead
npm WARN deprecated @oclif/screen@1.0.4: Deprecated in favor of @oclif/core
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
npm WARN deprecated @oclif/help@1.0.15: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated @oclif/command@1.8.36: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated @oclif/errors@1.3.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated @oclif/errors@1.3.5: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated @oclif/parser@3.8.17: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated @oclif/config@1.18.17: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated @oclif/config@1.18.2: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated cli-ux@5.6.7: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated core-js@1.2.7: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 7
npm ERR! path /home/josselin/kominifa-medusa/node_modules/@stdlib/number-float64-base-normalize
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild

npm ERR! A complete log of this run can be found in: /home/josselin/.npm/_logs/2024-03-16T22_40_41_250Z-debug-0.log
Error: Command failed with exit code 7: npm install
    at makeError (/usr/local/lib/node_modules/@medusajs/medusa-cli/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/usr/local/lib/node_modules/@medusajs/medusa-cli/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async install (/usr/local/lib/node_modules/@medusajs/medusa-cli/dist/commands/new.js:113:13)
    at async clone (/usr/local/lib/node_modules/@medusajs/medusa-cli/dist/commands/new.js:173:5)
    at async newStarter (/usr/local/lib/node_modules/@medusajs/medusa-cli/dist/commands/new.js:486:9) {
  shortMessage: 'Command failed with exit code 7: npm install',
  command: 'npm install',
  escapedCommand: 'npm install',
  exitCode: 7,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
k0xxx:~$ cd my-project/
k0xxx:~/my-project$ ls
data              package.json  tsconfig.admin.json   tsconfig.spec.json
index.js          README.md     tsconfig.json
medusa-config.js  src           tsconfig.server.json

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by VENGENCE7** [comment]
Facing the same issue in my cloud run deployment, but its working fine locally

**Comment by shahednasser** [comment]
Hello, we've found an issue related to a dependency of another dependency. The issue occurs on node v20+ when using `npm`. We're looking for a permanent solution, but for now, can you try installing `@stdlib/number-float64-base-normalize@0.0.8` and try the installation again?

**Comment by VENGENCE7** [comment]
Damn, that worked, thank you so much.

**Comment by shahednasser** [comment]
Great! Will close this issue for now
