### ISSUE TITLE
page crash after hovering the mouse over the linked text "Stripe plugin"

### ISSUE THREAD

**Issue by izabelaskoczylas** [medusajs/medusa#6720]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Steps to reproduce:
1. open - https://docs.medusajs.com/recipes/ecommerce 
2. right click and select "translate to Polish"
3. hover the mouse over the linked text "Stripe plugin"
environment - win 11 pro, chrome ver 122.0.6261.129
![1](https://github.com/medusajs/medusa/assets/157287011/e578b251-9ab8-45ac-bca2-c171fd6fc2c8)
![2](https://github.com/medusajs/medusa/assets/157287011/a0762dac-5738-4e2b-bc57-1d3f78f82af7)

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Closing this issue for being similar to issue #7738
