### ISSUE TITLE
medusa-react always loading

### ISSUE THREAD

**Issue by amunrarara** [medusajs/medusa#6724]
### Describe the bug

Following the Medusa React docs to-the-tee: https://docs.medusajs.com/medusa-react/overview

When using medusa-react, the hooks I've tested (useProducts, useCreateCart) are successfully sending GET requests to my server, which logs a response such as: 

`::1 - - [18/Mar/2024:03:38:55 +0000] "GET /store/products?expand=variants HTTP/1.1" 200 2242 "http://localhost:5173/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"`

However, the "products" object never arrives, and the "isLoading" state is always true.

A similar issue occurs with the "createCart" function from useCreateCart. The server logs

`::1 - - [18/Mar/2024:03:41:02 +0000] "OPTIONS /store/carts HTTP/1.1" 204 0 "http://localhost:5173/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"`

 but `createCart.mutate({})` only returns undefined, and I verified the DB doesn't have a single row in it with `medusa=# SELECT * FROM public.cart`;

However, **the following curl request returns products just fine**: 

`curl "http://localhost:9000/store/products" -H "x-publishable-key: KEY_REDACTED"`

Does my backend need additional configuration or somethin'?

### System information

Medusa version (including plugins):
"dependencies": {
    "@medusajs/admin": "7.1.11",
    "@medusajs/cache-inmemory": "^1.8.9",
    "@medusajs/cache-redis": "^1.8.9",
    "@medusajs/event-bus-local": "^1.9.8",
    "@medusajs/event-bus-redis": "^1.8.11",
    "@medusajs/file-local": "^1.0.3",
    "@medusajs/medusa": "1.20.2",
    "@tanstack/react-query": "4.22.0",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "dotenv": "16.3.1",
    "express": "^4.17.2",
    "medusa-fulfillment-manual": "^1.1.39",
    "medusa-interfaces": "^1.3.8",
    "medusa-payment-manual": "^1.0.24",
    "medusa-payment-stripe": "^6.0.7",
    "prism-react-renderer": "^2.0.4",
    "typeorm": "^0.3.16"
  },
  "devDependencies": {
    "@babel/cli": "^7.14.3",
    "@babel/core": "^7.14.3",
    "@babel/preset-typescript": "^7.21.4",
    "@medusajs/medusa-cli": "^1.3.21",
    "@types/express": "^4.17.13",
    "@types/jest": "^27.4.0",
    "@types/node": "^17.0.8",
    "babel-preset-medusa-package": "^1.1.19",
    "cross-env": "^7.0.3",
    "eslint": "^6.8.0",
    "jest": "^27.3.1",
    "rimraf": "^3.0.2",
    "ts-jest": "^27.0.7",
    "ts-loader": "^9.2.6",
    "typescript": "^4.5.2"
  },

Database: Postgres (latest) via Docker
Operating system: MacOS 12
Browser (if relevant): Arc Chromium
Server Repo: https://github.com/amunrarara/backend-medusa

### Steps to reproduce the behavior

1. Clone the server from https://github.com/amunrarara/backend-medusa, run migrations, and seed it
2. Follow the instructions on the Medusa React docs (https://docs.medusajs.com/medusa-react/overview) to get a simple Medusa React project running
3. Follow instructions up to Queries, so that you have a component that uses useProducts to GET request from the server

### Expected behavior

Products should be returning via the hook

**Comment by amunrarara** [comment]
Pinging for a bump!

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
