### ISSUE TITLE
Product variant creation error

### ISSUE THREAD

**Issue by Andresser17** [medusajs/medusa#6738]
### Describe the bug

I can't create more than a product variant.

### System information

  "dependencies": {
    "@medusajs/admin": "7.1.11",
    "@medusajs/cache-inmemory": "^1.8.9",
    "@medusajs/cache-redis": "^1.8.9",
    "@medusajs/event-bus-local": "^1.9.8",
    "@medusajs/event-bus-redis": "^1.8.11",
    "@medusajs/file-local": "^1.0.3",
    "@medusajs/medusa": "1.20.2",
    "@tanstack/react-query": "4.22.0",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "dotenv": "16.3.1",
    "express": "^4.17.2",
    "medusa-fulfillment-manual": "^1.1.39",
    "medusa-interfaces": "^1.3.8",
    "medusa-payment-manual": "^1.0.24",
    "medusa-payment-stripe": "^6.0.7",
    "prism-react-renderer": "^2.0.4",
    "typeorm": "^0.3.16"
  },
  "devDependencies": {
    "@babel/cli": "^7.14.3",
    "@babel/core": "^7.14.3",
    "@babel/preset-typescript": "^7.21.4",
    "@medusajs/medusa-cli": "^1.3.21",
    "@types/express": "^4.17.13",
    "@types/jest": "^27.4.0",
    "@types/node": "^17.0.8",
    "babel-preset-medusa-package": "^1.1.19",
    "cross-env": "^7.0.3",
    "eslint": "^6.8.0",
    "jest": "^27.3.1",
    "rimraf": "^3.0.2",
    "ts-jest": "^27.0.7",
    "ts-loader": "^9.2.6",
    "typescript": "^4.5.2"
  },

Node.js version: 18.19.1
Database: PostgreSQL 16
Operating system: Windows 10 21H2
Browser (if relevant): Edge

### Steps to reproduce the behavior

1. Go to 'Edit Product'
2. Click on 'Add Variant' or 'Duplicate Variant'
3. Write a different name in 'Custom Title' field

### Expected behavior

Create more than a product variant.

### Screenshots

![image](https://github.com/medusajs/medusa/assets/40070068/b677f0d4-7dfc-44fd-9fbe-3d3dc87b3690)

**Comment by justAnArthur** [comment]
+1

**Comment by sradevski** [comment]
Each variant has to have different options, and be unique (as the error suggests). Please define options and select them before you try to create a variant.
