### ISSUE TITLE
Cannot place order due to duplicate payment

### ISSUE THREAD

**Issue by ybirader** [medusajs/medusa#6745]
I have a shopping cart that I am trying to complete.

So far, I have added items to the shopping cart, created the required payment sessions, added shipping options, and the payment method.

When I attempt to place the order, I get the following error: 

```js
    data: {
      code: 'invalid_request_error',
      type: 'duplicate_error',
      message: 'Payment with cart_id cart_01HS63SE7GJM7EDMD1FPMMJK52 already exists.
```

To debug, I ran `const notReady = !cart || !cart.shipping_address || !cart.billing_address || !cart.email || cart.shipping_methods.length < 1` to check if the cart has the required fields, which returns `false`.

Also, `cart.payment_session.status` returns `authorized`.

I'm not sure what I'm doing wrong here.

EDIT: I refreshed the cart, added the items back so that the cart was in a `pending`state and retried- it worked. This suggests that after the payment has been authorised and if a failure arises, the customer is not able to retry, since a payment entry associated with the cart has been added to the database.

Is there a way around this? I noticed that the idempotency key on the cart is `null`- not sure if this has any bearing.

**Comment by R-Art-project** [comment]
I have the same error

**Comment by khalilxg** [comment]
did you resolve it ?  idont wont to manually delete the cartid from the table !

**Comment by KareemAbbas1** [comment]
+1

**Comment by hohai1001** [comment]
+1
