### ISSUE TITLE
Order entity does not have a `refunded` status

### ISSUE THREAD

**Issue by danielrodcaball** [medusajs/medusa#6783]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The [Orders Architecture Overview](https://docs.medusajs.com/modules/orders) doc page states that one of the possible statuses of an order is `refunded`. This does not seem to be true, the `order_status_enum` only allows the following values: 

```'pending', 'completed', 'archived', 'canceled', 'requires_action'```

### How can this issue be resolved?

1. Remove the `refunded` status as a possible state in the order entity.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch! pushed a fix to PR #7978
