### ISSUE TITLE
price change in Kuwait currency (Kuwaiti Dinar)

### ISSUE THREAD

**Issue by q8gazy** [medusajs/medusa#6833]
### Describe the bug
when you add Kuwait currency (Kuwaiti Dinar) to your store and add the price to a Product like 5 in KWD (Kuwaiti Dinar) the price shown in the storefront is 50

![c18829c92d717d53b2e1e306b81e96bc](https://github.com/medusajs/medusa/assets/26827552/86ade8aa-a60c-4be3-9cf1-e99c52203d8b)
![fd18afc4513b0db17b57aa0571cca23d](https://github.com/medusajs/medusa/assets/26827552/b91aaf79-ac89-403b-b6fc-bc43bc190157)

**Comment by taimoor-shan** [comment]
Same here for Pakistani Rupee
