### ISSUE TITLE
Feature Suggestion: Base-price for products which price is dependant on i.e. their weight

### ISSUE THREAD

**Issue by inallermunde** [medusajs/medusa#688]
Hello there,

I have a feature suggestion:
Similar to the weight and the dimension properties of a product, a "base-price" property in which you can specify a weight or dimension (i.e. 1kg) and a price which lets the customer easily compare this product to similar products that might have a different weight, but are essentially the same. This would help customers to not have to calculate the value of a product. As far as I know this is a rule in Germany as well, to have a "Grundpreis" = "base price" for products like coffee.

If I need to elaborate, let me know.

**Comment by srindom** [comment]
Hi! Is the idea here that the price should be dynamically calculated or is it something that you would like to be able to expose in the front end, as some additional information about a product. In the latter case you could maybe just do something like this:

```javascript

const variant = {
  ...,
  prices: [
    ..., // other currency prices
    {
      currency_code: "eur",
      amount: 5000 // €50.00
    }
  ],
  weight: "0.2" // kg
}

const moneyAmount = getMoneyAmount(variant, "eur") // finds the correct price -> { currency_code: "eur", amount: 5000 }
const pricePerKg = 1 / parseFloat(variant.weight) * moneyAmount.amount // $250.00
```

**Comment by inallermunde** [comment]
Hi,
That could be a possible solution as long as all products have the same weight / unit for their base price.
But as soon as we have a product where the base price is i.e. per liter, it would not work anymore.
Thats why i want to be able to set the base price with its unit individually for each product.

**Comment by olivermrbl** [comment]
Hi @inallermunde – please move this feature request to our GitHub Discussions board if still relevant for you :)
