### ISSUE TITLE
getting error while   npx create-medusa-app@latest

### ISSUE THREAD

**Issue by techUdayMungalpara** [medusajs/medusa#6884]
### Describe the bug

An error occurred while installing Next.js storefront: Error: Command failed: npx create-next-app -e https://github.com/medusajs/nextjs-starter-medusa my-medusa-store-storefront

### System information

Medusa version (including plugins):
Node.js version:v20.12.0
Database:v20.12.0
Operating system:ubntu 22.01
Browser (if relevant):

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets
npx create-medusa-app@latest
? What's the name of your project? my-medusa-store
? Enter an email for your admin dashboard user admin@medusa-test.com
? Would you like to create the Next.js storefront? You can also create it later Yes
? Enter your Postgres username postgres
? Enter your Postgres password [hidden]
🚀 Starting project setup, this may take a few minutes.
✔ Created project directory
⠧ Installing Next.js Storefront...

   ┌─────────────────────────────── 💡 Medusa Tips ────────────────────────────────┐
   │                                                                               │
   │   You can specify the inventory of products per location and sales channel.   │
   │                                                                               │
   └───────────────────────────────────────────────────────────────────────────────┘
An error occurred while installing Next.js storefront: Error: Command failed: npx create-next-app -e https://github.com/medusajs/nextjs-starter-medusa my-medusa-store-storefront
/as/my-medusa-store$ ls
data      medusa-config.js  README.md  tsconfig.admin.json  tsconfig.server.json  yarn.lock
index.js  package.json      src        tsconfig.json        tsconfig.spec.json

If applicable, add code samples to help explain your problem

### Additional context

try to create medusa store wirh create-medusa-app@latest but getting error try to find many way to solve error but not able to find solution .

**Comment by techUdayMungalpara** [comment]
udaym@uday-m:/mnt/ /sd$ npx create-medusa-app
Need to install the following packages:
create-medusa-app@1.2.7
Ok to proceed? (y) y
? What's the name of your project? my-medusa-store
? Enter an email for your admin dashboard user admin@medusa-test.com
? Would you like to create the Next.js storefront? You can also create it later No
? Enter your Postgres username postgres
? Enter your Postgres password [hidden]
🚀 Starting project setup, this may take a few minutes.
✔ Created project directory
✔ Database medusa-OWLe created
An error occurred while preparing project: Error: Command failed: npm install --legacy-peer-deps

**Comment by shahednasser** [comment]
Hi @techUdayMungalpara , can you try to install with the Next.js storefront using this snapshot and adding a `--verbose` option:

```bash
npx create-medusa-app@1.2.8-snapshot-20240329154849 --verbose
```

this will show us the entire log of creating the storefront/backend

As for the second error that you reported `Error: Command failed: npm install --legacy-peer-deps`, are there no more details other than this? If not, maybe also try with the `--verbose` option above.

**Comment by techUdayMungalpara** [comment]
VERBOSE LOG: The following error occured when connecting to the database: Error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string
![Screenshot from 2024-03-30 13-10-43](https://github.com/medusajs/medusa/assets/105286180/615997c1-e574-432c-a3db-906f33e9a269)
![Screenshot from 2024-03-30 13-10-50](https://github.com/medusajs/medusa/assets/105286180/3058b248-7b87-47b9-bd0c-68c586925e96)

**Comment by severinlandolt** [comment]
Don't know if its related
![CleanShot 2024-04-08 at 01 43 06@2x](https://github.com/medusajs/medusa/assets/41927988/2b745260-b899-473b-b96d-36aa26f18d24)

**Comment by shahednasser** [comment]
Thank you both for more details, currently looking into resolving this issue.

For now, can you change into the created directory of your project and try running `npx medusa migrations run` in it? You can then create a user using the command:

```bash
npx medusa user -e admin@medusa-test.com -p supersecret
```

and run the `dev` command to start your Medusa backend.

You can also use the `medusa new` command as explained [here](https://docs.medusajs.com/development/backend/install).

**Comment by techUdayMungalpara** [comment]
Issue resolved. Thank you to the Medusa team and community! 🎉
