### ISSUE TITLE
Medusa UI Change Theme Icon uncentered

### ISSUE THREAD

**Issue by Noah-Haf** [medusajs/medusa#6887]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Hi,

On ``docs.medusajs.com/ui`` the switch theme button icon is uncentered: 

![image](https://github.com/medusajs/medusa/assets/61884850/513a8c89-ff0e-42a3-b1e7-75ab9ef2d0f8)

On ``docs.medusajs.com`` the icon seems to be centred: 

![image](https://github.com/medusajs/medusa/assets/61884850/32264bb1-17c2-4bc7-afc5-7cc556c1d673)

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for reporting this. It's not due to centering, the sizes of the icons is just different, and moving forward we'll likely keep the design of the UI one. Will close this issue for now.
