### ISSUE TITLE
NotFound the https://docs.medusajs.comapi/store#carts_postcartscartpaymentsession

### ISSUE THREAD

**Issue by paulootavio** [medusajs/medusa#6888]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Hi 

I just want to report that the link https://docs.medusajs.comapi/store#carts_postcartscartpaymentsession at the documentation at is broken

![image](https://github.com/medusajs/medusa/assets/4235190/8a4d1221-582c-43f7-84b8-c7622bb246a6)

link: https://docs.medusajs.com/modules/carts-and-checkout/storefront/implement-checkout-flow

### How can this issue be resolved?

1. Is a simple error just find the correct url and update the doc
2.
3.
...

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for opening this issue! Seems like a missing backslash before `api`. So, it should be  https://docs.medusajs.com/api/store#carts_postcartscartpaymentsession

Would you like to open a PR that fixes this?
