### ISSUE TITLE
Update the medusa-plugin-wishlist dependencies

### ISSUE THREAD

**Issue by Saba-Shavidze** [medusajs/medusa#6926]
Please update the dependencies of`wishlist-plugin` for the latest version of medusa:

```ts
While resolving: commerce@1.0.0
npm ERR! Found: medusa-interfaces@1.3.8
npm ERR! node_modules/medusa-interfaces
npm ERR!   peer medusa-interfaces@"^1.3.7" from @medusajs/file-local@1.0.3
npm ERR!   node_modules/@medusajs/file-local
npm ERR!     @medusajs/file-local@"^1.0.3" from the root project
npm ERR!   peer medusa-interfaces@"^1.3.7" from @medusajs/medusa@1.20.4
npm ERR!   node_modules/@medusajs/medusa
npm ERR!     peerOptional @medusajs/medusa@">1.19" from medusa-test-utils@1.1.43
npm ERR!     node_modules/@medusajs/medusa/node_modules/medusa-test-utils
npm ERR!       medusa-test-utils@"^1.1.43" from @medusajs/medusa@1.20.4
npm ERR!     @medusajs/medusa@"^1.20.4" from the root project
npm ERR!   3 more (medusa-fulfillment-manual, medusa-payment-manual, the root project)
```

**Comment by shahednasser** [comment]
Hello, can you try installing with `npm` and using `--legacy-peer-deps` option?

**Comment by theogenejr** [comment]
I did that and it installs successfully. However, it does not work.

**Comment by SubhrajitDG** [comment]
Running into same issue. The Wishlist plugin was last worked on 2 years ago, support for this is not available anymore?

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
