### ISSUE TITLE
Found invalid GitHub URL: "https://github.com/medusajs/nextjs-starter-medusa". Please fix the URL and try again.

### ISSUE THREAD

**Issue by MutisoMuli** [medusajs/medusa#6930]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

![image](https://github.com/medusajs/medusa/assets/136011037/08cefb5e-2a0a-40b1-8876-b182544ebfdc)

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Hi @MutisoMuli can you ensure you're using the latest version of `create-next-app`? This seems to be an issue in their CLI tool rather than in the URL

**Comment by MutisoMuli** [comment]
thank you for quick response
