### ISSUE TITLE
use "npx medusa  user" get " QueryFailedError: duplicate key value violates unique constraint" error

### ISSUE THREAD

**Issue by yunfengsay** [medusajs/medusa#6938]
## Bug report
I am transforming my pg database from railway to supabase without data  follow these steps
1. change DATABASE_URL to supabase
2. run `npx medusa user -e test@gmail.com -p test ` to create a new admin 
when I run step 2 , my terminal get QueryFailedError: duplicate key value violates unique constraint "PK_ea94f42b6c88e9191c3649d7522"

### Describe the bug
![image](https://github.com/medusajs/medusa/assets/15527378/ea0e5775-7b55-481c-bc26-1345302ea81a)
I had find the key in node_moudles/medusajs/medusa/dist/migrations/1611063162649-initial_schema.js. I don't know what is this file for and why this file could beak my add user action .
![image](https://github.com/medusajs/medusa/assets/15527378/56e945de-5b63-4680-9a31-2b86d1cd7139)

### System information

Medusa version (including plugins):
Node.js version: v21.0.0
Database: PostgreSQL 15.1 (Ubuntu 15.1-1.pgdg20.04+1) on aarch64-unknown-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0, 64-bit
Operating system: Ubuntu 23.10
Browser (if relevant):

### Steps to reproduce the behavior

1. npx medusa user -e test@gmail.com -p test

**Comment by sradevski** [comment]
Hey, thanks for the report! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket since it no longer applies to our new setup, or the issue has already been fixed. If you are still facing issues with v1,
please open a new ticket and we will address it as soon as possible. Thanks! 🙏
