### ISSUE TITLE
Missing ProductCategoryProduct Modal

### ISSUE THREAD

**Issue by jagadeesh-si** [medusajs/medusa#6940]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

What:
There is no ProductCategoryProduct modal for ProductCategoryProduct Entity

why:
To create custom service : In my case i need productCategoryProduct modal to do inner join with productVariant modal

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Not sure exactly what you mean, but if you're using product category features make sure the feature flag `product_categories` is enabled. Learn more about enabling feature flags in [this guide](https://docs.medusajs.com/development/feature-flags/toggle)

**Comment by shahednasser** [comment]
Closing this issue due to lack of interactivity, feel free to re-open if you have more details.
