### ISSUE TITLE
Missing Modal for ProductCategoryProduct 

### ISSUE THREAD

**Issue by jagadeesh-si** [medusajs/medusa#6941]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

What:
There is no ProductCategoryProduct modal for ProductCategoryProduct Entity

why:
To create custom service : In my case i need productCategoryProduct modal to do inner join with productVariant modal

### How can this issue be resolved?

.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Closing this as it's a duplicate of another issue

**Comment by jagadeesh-si** [comment]
Please share me link of the duplicate issue

**Comment by shahednasser** [comment]
You created it in this issue #6940
