### ISSUE TITLE
Cannot create return shipping option of type calculated

### ISSUE THREAD

**Issue by gempain** [medusajs/medusa#6949]
### Describe the bug

When trying to save a new return shipping option of type "Calculated", I always get this error:

```
Shipping options of type `flat_rate` must have an `amount`
```

### System information

Medusa version (including plugins): latest
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Expected behavior

No error should be thrown.

### Screenshots

<img width="1263" alt="Screenshot 2024-04-04 at 23 35 56" src="https://github.com/medusajs/medusa/assets/13135149/8d6dfee7-2f84-491f-9842-b37fd7cd4175">

**Comment by hadicph** [comment]
If you would like to use the calculated price type the shipping option should support that.
I dont think the default return does.
In order to do that you would create a fulfillment method, the following documentation shows how to create a calculate price inside the method: https://docs.medusajs.com/modules/carts-and-checkout/backend/add-fulfillment-provider#calculateprice

**Comment by gempain** [comment]
I already implemented a custom fulfilment service which handles all the methods mentioned in the docs. In fact, I can fulfil orders just fine. The error message above is triggered by the medusa admin backend, not by the fulfilment service. The API is not accepting the payload that the admin interface is sending.

I also tried to create a fixe cost option, then edit it and change its type to calculated. The form can be saved just fine, but if you reopen it, the changes are not persisted and the type dropdown still shows fixed cost.

**Comment by hadicph** [comment]
> I already implemented a custom fulfilment service which handles all the methods mentioned in the docs. In fact, I can fulfil orders just fine. The error message above is triggered by the medusa admin backend, not by the fulfilment service. The API is not accepting the payload that the admin interface is sending.
> 
> I also tried to create a fixe cost option, then edit it and change its type to calculated. The form can be saved just fine, but if you reopen it, the changes are not persisted and the type dropdown still shows fixed cost.

Just reproduced all behaviors you mentioned on a custom fulfillment provider, was initially tested on a normal shipping method.👍
