### ISSUE TITLE
Error 500 when adding product to price list

### ISSUE THREAD

**Issue by hex-grammer** [medusajs/medusa#6950]
### Describe the bug

Encountering a "Request failed with status code 500" error when attempting to add a new product and price into a price list.

### System information

Medusa version (including plugins): 1.20.2
Node.js version: 18.17.0
Database: postgresql
Operating system: Windows 10

### Steps to reproduce the behavior

1. Add a new product into a price list.
2. Add price to the product.
3. Click "submit and close".
4. Observe the error.

### Expected behavior

Successful addition of product and price into the price list without encountering a 500 error.

### Screenshots

![image](https://github.com/medusajs/medusa/assets/67379271/e6b8e774-084e-4e46-a16f-c59bf6093a63)

![image](https://github.com/medusajs/medusa/assets/67379271/3c3ce3d4-ce17-43a5-816c-e3cc539c8432)

![image](https://github.com/medusajs/medusa/assets/67379271/dc3beedb-ef88-4c8c-af4a-914c3e57307a)

![image](https://github.com/medusajs/medusa/assets/67379271/b72ba72f-bcf2-4544-961b-ce9bcb0bf2f6)

**Comment by sradevski** [comment]
Hey, please provide more logs on the exact error that happened on the backend, we cannot debug with just this information. Closing the ticket until then, please reopen if the issue persists.
