### ISSUE TITLE
Error Reading Region After Creation

### ISSUE THREAD

**Issue by christopherzulu0** [medusajs/medusa#6966]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

can't read the properties of name.region

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
The issue is not clear, can you provide more details? Why are you accessing `name.region`?

**Comment by christopherzulu0** [comment]
when l am creating a region , that's what l get

**Comment by shahednasser** [comment]
Are you creating the region in the admin or in your code? Can you provide code snippets of the request and response?

**Comment by christopherzulu0** [comment]
Admin Dasboard

**Comment by shahednasser** [comment]
I need you to share a screenshot of the admin/response it receives to be able to help you out and understand the issue better

**Comment by christopherzulu0** [comment]
It shows the response in the attached image

**Comment by christopherzulu0** [comment]
Here is the error on the page that displays the regions, after creating it.

**Comment by shahednasser** [comment]
Seems like your images aren't being sent along with your messages, you probably need to upload them through github

**Comment by christopherzulu0** [comment]
oh. l am running it locally and using supabase for the database

**Comment by christopherzulu0** [comment]
But l have tried to host it on Railway. But the issue is that, the backend
is crashing after some time. l am using a free plan,since l am customizing
it

**Comment by shahednasser** [comment]
Sorry that's not enough information on the error you're facing. Please provide screenshots/code snippets of request/response causing the error

**Comment by christopherzulu0** [comment]
I installed a plugin for stripe, but l can't make payments with the card.
Attached below, is the screenshot of the error,l am getting.

**Comment by shahednasser** [comment]
Closing this issue due to lack of information. Feel free to re-open it with more details.
