### ISSUE TITLE
Add docs for how to manage products

### ISSUE THREAD

**Issue by srindom** [medusajs/medusa#697]
We want to add documentation about how to create and manage products in Medusa

- Products vs Product Variants (when does it make sense to create variants)
- Product Options - each variant must have a unique option value combination
- Other product fields
- Prices in Medusa
- Explain how to create a product 
  - from API: https://docs.medusa-commerce.com/api/admin/product/create-a-product
  - from admin (with screenshots)

Write up should go here: https://github.com/medusajs/medusa/tree/master/docs/content/guides

**Comment by Sukriti-sood** [comment]
@srindom Can I work on this

**Comment by srindom** [comment]
@Sukriti-sood Feel free to give it a go - let me know if you need help with some of the concepts :)

**Comment by srindom** [comment]
@Sukriti-sood let me know if you need help or want feedback on a first draft? :)
