### ISSUE TITLE
Failed To create new product

### ISSUE THREAD

**Issue by habitoz** [medusajs/medusa#6971]
## Bug report
create new product returns "Variant options do not contain value for color\nCannot read properties of undefined (reading 'length')"
### Describe the bug
while creating new product  the system returns invalid data response with the following message "Variant options do not contain value for color\nCannot read properties of undefined (reading 'length')"
### System information

Medusa version 1.20.4
Node.js version: 20
Database: postgresql
Operating system:
Browser (if relevant):

### Steps to reproduce the behavior
<code>
{
    "title": "T-shirt",
    "handle": "",
    "discountable": true,
    "is_giftcard": false,
    "options": [
        {
            "title": "Color"
        }
    ],
    "variants": [
        {
            "title": "White",
            "inventory_quantity": 100,
            "prices": [],
            "allow_backorder": false,
            "options": [
                {
                    "value": "White"
                }
            ],
            "manage_inventory": true
        }
    ],
    "status": "published",
    "sales_channels": [],
    "thumbnail": "http://localhost:9000/uploads/1712326573462-tshirt2.jpeg"
}
</code>

### Expected behavior
it should create new product

### Screenshots

![image](https://github.com/medusajs/medusa/assets/47148933/001cd2b6-f40b-4780-8263-cf48c88c07c3)

**Comment by humbleEwan** [comment]
I think you need to create variants separately and then assign the array of variants to the product.
