### ISSUE TITLE
Include extra reminder to swap out "client-id" in the PayPalScriptProcessor when going live with PayPay payments

### ISSUE THREAD

**Issue by ajz003** [medusajs/medusa#6974]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Include extra reminder to swap out "client-id" in the PayPalScriptProcessor when going live with PayPay payments when using `nextjs-starter-medusa`. The Sandbox mode works with the default "test" string, but if it isn't change when going live, attempting to pay with PayPal makes the pop-up window fail.

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Closed due to the explanation in [this comment](https://github.com/medusajs/medusa/pull/6975#issuecomment-2042036716)

**Comment by mythical0beast** [comment]
im sorry how to fix this issue is not explained is just mentioned they will get on to it

no explanation has been made

**Comment by shahednasser** [comment]
Hello @mythical0beast this issue has been fixed in the next.js starter in [this commit](https://github.com/medusajs/nextjs-starter-medusa/commit/bf88eac93609cc84f78f76336411a929047726bf). If you're still facing this issue, either pull from upstream the changes in the starter or make the fix manually in your code.

**Comment by mythical0beast** [comment]
Hey @shahednasser I have manually made the adjustment but with no success 
![image](https://github.com/medusajs/medusa/assets/144207147/d62ff2d0-4634-4647-bd6c-312426a88b36)
![image](https://github.com/medusajs/medusa/assets/144207147/056922ed-3f27-4d60-b9cc-b8ce7ff1cae1)
![image](https://github.com/medusajs/medusa/assets/144207147/9a4d61ed-c493-471a-bbab-0e7f1a2ebc7d)
![image](https://github.com/medusajs/medusa/assets/144207147/3f5757a8-916d-4cec-bfd3-2233d2bf1050)


I have verified these credentials are for live mode and are correct

**Comment by shahednasser** [comment]
Did you set the `NEXT_PUBLIC_PAYPAL_CLIENT_ID` environment variable in your Next.js starter?

**Comment by mythical0beast** [comment]
yes @shahednasser i have also set in the starter 
![image](https://github.com/medusajs/medusa/assets/144207147/224d5c2a-32b0-4848-a3a0-9d2d82d81883)

**Comment by shahednasser** [comment]
The error seems in the backend actually, not the frontend. So this isn't related to the original issue. I would advise you to make sure the keys are set correctly in your plugin's configuration as explained in [this documentation](https://docs.medusajs.com/plugins/payment/paypal#install-the-paypal-plugin)

**Comment by mythical0beast** [comment]
![image](https://github.com/medusajs/medusa/assets/144207147/6d60140c-ec55-47a5-8da5-1f334f8c6535)
i have reviewed the details multiple times and verified they are correct but this is error i receive when i visit checkout page

**Comment by mythical0beast** [comment]
is okay i fixed it

**Comment by HaruNoYukki** [comment]
@mythical0beast  how did you solve this?

**Comment by artyymcflyy** [comment]
@mythical0beast Im running into a similar issue. Can you share how you fixed your issue?
