### ISSUE TITLE
I customized a payment processor and linked it to the node_model as a yarn link, but I can't find my customized payment method under the Manage Payment Providers page. May I ask which step is wrong and can you give me help?

### ISSUE THREAD

**Issue by Garnett1314** [medusajs/medusa#7032]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I customized a payment processor and linked it to the node_model as a yarn link, but I can't find my customized payment method under the Manage Payment Providers page. May I ask which step is wrong and can you give me help?

### How can this issue be resolved?

I customized a payment processor and linked it to the node_model as a yarn link, but I can't find my customized payment method under the Manage Payment Providers page. May I ask which step is wrong and can you give me help?

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by hadicph** [comment]
I think the approach taken in medusa to customize a payment processor is to create a payment service file inside src/services in your backend projects, you can follow the following documentation provided: https://docs.medusajs.com/modules/carts-and-checkout/backend/add-payment-provider
It sounds like you are creating a separate package that you are linking, taking that approach can be slightly more difficult, but in case you would like to do that remember to also add the package to medusa-config.js
Hope this helps :)

**Comment by shahednasser** [comment]
The fix mentioned by @hadicph should work, so will close this issue. feel free to re-open it if you face more trouble.

**Comment by hadicph** [comment]
> The fix mentioned by @hadicph should work, so will close this issue. feel free to re-open it if you face more trouble.

Can I please ask you to mark the answer as correct ? 👀
