### ISSUE TITLE
New payment plugin error on nextjs front end button

### ISSUE THREAD

**Issue by czw333221** [medusajs/medusa#7059]
## Bug report

Error: Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server". {transitional: ..., adapter: function, transformRequest: ..., transformResponse: ..., timeout: ..., xsrfCookieName: ..., xsrfHeaderName: ..., maxContentLength: ..., maxBodyLength: ..., validateStatus: ..., headers: ..., baseURL: ..., raxConfig: ..., method: ..., withCredentials: ..., url: ..., json: ..., data: ...} ^^^^^^^^

### Describe the bug

New alipay payment plugin appears in nextjs storefront checkout page review

### System information

Medusa version (including plugins): latest version
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Steps to reproduce the behavior

1.go to alipay official application sandbox ：https://open.alipay.com/develop/sandbox/app
2. run "yarn add payment-alipay
3. Fill in the alipay appid, public key, etc. into .env
4.Configure alipay sdk in "medusa-config.js".
5. Go to place an order

### Expected behavior

The final step of checkout appears:Error: Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server". {transitional: ..., adapter: function, transformRequest: ..., transformResponse: ..., timeout: ..., xsrfCookieName: ..., xsrfHeaderName: ..., maxContentLength: ..., maxBodyLength: ..., validateStatus: ..., headers: ..., baseURL: ..., raxConfig: ..., method: ..., withCredentials: ..., url: ..., json: ..., data: ...} ^^^^^^^^

### Screenshots
![Snipaste_2024-04-11_22-45-43](https://github.com/medusajs/medusa/assets/134688991/e4d4904e-40a7-4a5a-b7da-5c1c99a4d463)

### Code snippets

const AlipayPaymentButton = ({
  cart,
  notReady,
}: {
  cart: Omit<Cart, "refundable_amount" | "refunded_total">
  notReady: boolean
}) => {
  const [submitting, setSubmitting] = useState(false)
  const [errorMessage, setErrorMessage] = useState<string | null>(null)

  const onPaymentCompleted = async () => {
    await placeOrder().catch((err) => {
      setErrorMessage(err.toString())
      setSubmitting(false)
    })
  }

  const handlePayment = () => {
    setSubmitting(true)

    onPaymentCompleted()
  }

  return (
    <>
      <Button disabled={notReady}
        isLoading={submitting}
        onClick={handlePayment}
        size="large">
        下订单
      </Button>
      <ErrorMessage error={errorMessage} />
    </>
  )
}

### Additional context

I'm trying to resolve this error by responding to the backend request for "bode" to "handlePayment".

**Comment by hammerwang666** [comment]
@czw333221 兄弟请问这个问题解决了吗, 我在接入medusa的tabby支付, 也遇到这问题了

**Comment by hammerwang666** [comment]
@shahednasser I have the same issue, please help.
