### ISSUE TITLE
Trying to use bun for development

### ISSUE THREAD

**Issue by techbro76** [medusajs/medusa#7065]
## Bug report

Error while running the bun dev command inside a docker oven/bun:1.1.3 image.

**devspace ./app # bun dev**
$ cross-env bun run build:server && medusa develop
$ cross-env bun run clean && tsc -p tsconfig.server.json
$ cross-env ./node_modules/.bin/rimraf dist
114 |                     console.log((0, boxen_1.default)(defaultMessage, defaultConfig));
115 |                     configStore.setConfig("star.prompted", true);
116 |                 }
117 |                 process.exit(0);
118 |             });
119 |             (0, child_process_1.execSync)("npx --no-install babel src -d dist --ignore \"src/admin/**\"", {
                          ^
error: Invalid stdio option "[object EventEmitter]"
      at node:child_process:360:47
      at map (:1:21)
      at node:child_process:164:47
      at node:child_process:213:45
      at /app/node_modules/@medusajs/medusa/dist/commands/develop.js:119:17
      at step (/app/node_modules/@medusajs/medusa/dist/commands/develop.js:44:18)
      at /app/node_modules/@medusajs/medusa/dist/commands/develop.js:25:53
      at /app/node_modules/@medusajs/medusa/dist/commands/develop.js:19:9
      at new Promise (:1:21)
      at /app/node_modules/@medusajs/medusa/dist/commands/develop.js:15:12
error: script "dev" exited with code 1

For me from the error it looks like the npx command is hardcoded, however bunx could be used instead.

### Describe the bug

The bug is the hardcoded npx command usage which cannot be modified for the medusa develop.

However it looks like the whole medusa command is dependent on node.

**devspace ./app # medusa develop**
/usr/bin/env: 'node': No such file or directory

### Steps to reproduce the behavior

1. Run the oven/bun:1.1.3
2. Install the medusa cli -> bun add -g @medusajs/medusa-cli@1.3.22
4. Try to run medusa dev command inside any project
5. See error

### Expected behavior

Development environment starts as intended

**Comment by olivermrbl** [comment]
We will not focus on making Medusa compatible with bun any time soon, so marking this as wont-fix. Hopefully, this will be possible as `bun` moves toward full Node compatibility.
