### ISSUE TITLE
How is Route activated in the api folder of the "medusa-payment-paypal" plugin?

### ISSUE THREAD

**Issue by czw333221** [medusajs/medusa#7066]
Creating a new payment plugin requires creating api routes but I don't know how to start the routes in the plugin.

**Comment by czw333221** [comment]
Error: Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server".
  {transitional: ..., adapter: function, transformRequest: ..., transformResponse: ..., timeout: ..., xsrfCookieName: ..., xsrfHeaderName: ..., maxContentLength: ..., maxBodyLength: ..., validateStatus: ..., headers: ..., baseURL: ..., raxConfig: ..., method: ..., withCredentials: ..., url: ..., json: ..., data: ...}
                               ^^^^^^^^
    at stringify (<anonymous>)

**Comment by olivermrbl** [comment]
I suggest you start by reading our documentation about [API Routes](https://docs.medusajs.com/development/api-routes/overview) and browse how these are built in the [Stripe plugin](https://github.com/medusajs/medusa/tree/develop/packages/medusa-payment-stripe/src/api). Then, feel free to come back with questions.

**Comment by czw333221** [comment]
> I suggest you start by reading our documentation about [API Routes](https://docs.medusajs.com/development/api-routes/overview) and browse how these are built in the [Stripe plugin](https://github.com/medusajs/medusa/tree/develop/packages/medusa-payment-stripe/src/api). Then, feel free to come back with questions.

I created alipay payment plugin but don't know how to receive webhooks in front end, can you teach me? Thank you 🙏

**Comment by czw333221** [comment]
The current difficulty is the call to the handlePayment function after the front-end button is clicked, which needs to jump to the payment link, receive the webhooks response, determine the payment completion status, complete the cart, jump to the order, and determine if the order is complete or not (that's all I know).

Also, if you add the completed cart to the backend webhooks, will the order be lost?

**Comment by Lorde627** [comment]
https://www.npmjs.com/package/medusa-alipay?activeTab=code
This could be useful.
