### ISSUE TITLE
Out of stock with Allow backorders enabled

### ISSUE THREAD

**Issue by charlesoestergaard** [medusajs/medusa#7067]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

If we disable the `Manage inventory` and enable the `Allow backorders` we get error "Out of stock". We sell a product thats always on stock. So we dont wanna set a stock quantity for each product.

### How can this issue be resolved?

1. Disable Manage inventoy
2. Enable Allow backorders
3. Check if product can be added to cart.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by olivermrbl** [comment]
This is due to an incorrect check in the storefront, you can indeed add to cart when inventory management is disabled. I've [opened a PR](https://github.com/medusajs/nextjs-starter-medusa/pull/308), should be fixed soon. Until then, you can incorporate those changes in your own project.
