### ISSUE TITLE
Docs(Code Issue): Code Issue in /plugins/notifications/sendgrid

### ISSUE THREAD

**Issue by riivostolts** [medusajs/medusa#7068]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

There is a wrong key shown in the docs for "Order Shipment Created" template. `order_shipped_template` does not pass the condition in **sendgrid.js**'s **getTemplateId** function.  

### How can this issue be resolved?

1. `order_shipped_template` should be renamed to `order_shipment_created_template`

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch! Seems like it's a bug in the sendgrid plugin, where if the template is passed in the plugin's options without a locale, it looks for `order_shipment_created_template`, whereas in the localized options, it looks for `order_shipped_template`.

Will report it and add a temporary note in the docs
