### ISSUE TITLE
Import Products Stuck in Processing

### ISSUE THREAD

**Issue by rpfelgueiras** [medusajs/medusa#7082]
### Describe the bug

I can't import products because there is one generic error: Import failed.
Looking into the logs I can find the following error
`error: fileService.uploadProtected is not a function`

### System information

Medusa version (including plugins):
"dependencies": {
    "@medusajs/admin": "7.1.11",
    "@medusajs/cache-inmemory": "^1.8.9",
    "@medusajs/cache-redis": "^1.8.9",
    "@medusajs/event-bus-local": "^1.9.8",
    "@medusajs/event-bus-redis": "^1.8.11",
    "@medusajs/file-local": "^1.0.3",
    "@medusajs/medusa": "1.20.2",
    "@tanstack/react-query": "4.22.0",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "dotenv": "16.3.1",
    "express": "^4.17.2",
    "medusa-file-cloudinary": "^1.0.2",
    "medusa-fulfillment-manual": "^1.1.39",
    "medusa-interfaces": "^1.3.8",
    "medusa-payment-manual": "^1.0.24",
    "medusa-payment-stripe": "^6.0.7",
    "prism-react-renderer": "^2.0.4",
    "typeorm": "^0.3.16"
  },

Node.js version: I can't check that. I am using Railway
Database: Postgres
Operating system:
Browser (if relevant):

### Steps to reproduce the behavior

1. Go to Products > Import Products
2. Click on Import Products
3. Select the sample file previously downloaded
4. Try to import that sample file
5. See error

### Expected behavior

I was expecting the products to be imported.

### Additional context

I took a look at the batch_job and it was empty. Meaning that the import job didn't even start. Right?

**Comment by olivermrbl** [comment]
As far as I can see, the [file plugin you are using](https://github.com/NiketanG/medusa-file-cloudinary/blob/main/src/services/cloudinary.js) does not support protected uploads, which is also described by the error message.

You can use one of the [official file plugins](https://docs.medusajs.com/plugins/file-service/) or build a new one for Cloudinary yourself, that is fully compatible with the file provider interface.

**Comment by rpfelgueiras** [comment]
Thanks a lot!

**Comment by Balogunolalere** [comment]
hi @rpfelgueiras please how did you fix? i am using cloudinary also with the same bug

**Comment by rpfelgueiras** [comment]
I stopped using that particular Cloudinary plugin and started using one of the [official file plugins](https://docs.medusajs.com/plugins/file-service).
