### ISSUE TITLE
[v2] AwilixResolutionError: Could not resolve 'userService'

### ISSUE THREAD

**Issue by AminulBD** [medusajs/medusa#7107]
Hi,

I'm trying to explore v2 of medusa. I've created new project with `--v2` flag. For example:  `npx create-medusa-app@latest --v2`

It's create new project, migrate tables and open url on the browser. But it doesn't create any users. When i try to create user manually it's throw this error `AwilixResolutionError: Could not resolve 'userService'.` with this command ` medusa user -e admin@medusa.test -p secret`

Is there anyone else facing the same issue? Or just me?

_Originally posted by @AminulBD in https://github.com/medusajs/medusa/discussions/7106_

**Comment by olivermrbl** [comment]
Please see my comment on the discussion.
