### ISSUE TITLE
Checkout flow stripe: An error occurred in InitiatePayment during the creation of the stripe payment intent

### ISSUE THREAD

**Issue by davidparys** [medusajs/medusa#7111]
### Describe the bug
Hello, I am having a little bit of an issue, currently building a storefront with the js-client, and I am creating a checkout session with the stripe provider, I am running into the following issue when:

- After generating a `$medusa.carts.createPaymentSessions` (as per [doc](https://docs.medusajs.com/modules/carts-and-checkout/storefront/implement-checkout-flow#payment-step) + [stripe module](https://docs.medusajs.com/plugins/payment/stripe)) for my cart ID, I received the following `payment_sessions` in my cart:

```JSON
/// StoreCartsRes || cart.payment_sessions
[
    {
        "id": "ps_01HW0J61ZM1C5Q5C020KKZC50M",
        "created_at": "2024-04-21T14:50:24.077Z",
        "updated_at": "2024-04-21T15:04:58.516Z",
        "cart_id": "cart_01HW0HZ35BQW6JPM264Y417ATD",
        "provider_id": "manual",
        "is_selected": null,
        "is_initiated": false,
        "status": "pending",
        "data": {},
        "idempotency_key": null,
        "amount": 97818,
        "payment_authorized_at": null
    },
    {
        "id": "ps_01HW0J61ZN8J8R52710SQKSRV2",
        "created_at": "2024-04-21T14:50:24.077Z",
        "updated_at": "2024-04-21T15:04:58.516Z",
        "cart_id": "cart_01HW0HZ35BQW6JPM264Y417ATD",
        "provider_id": "stripe-bancontact",
        "is_selected": null,
        "is_initiated": false,
        "status": "pending",
        "data": {},
        "idempotency_key": null,
        "amount": 97818,
        "payment_authorized_at": null
    },
    {
        "id": "ps_01HW0J61ZNYRMZJR2XEPVFPXMV",
        "created_at": "2024-04-21T14:50:24.077Z",
        "updated_at": "2024-04-21T15:04:58.516Z",
        "cart_id": "cart_01HW0HZ35BQW6JPM264Y417ATD",
        "provider_id": "stripe-giropay",
        "is_selected": null,
        "is_initiated": false,
        "status": "pending",
        "data": {},
        "idempotency_key": null,
        "amount": 97818,
        "payment_authorized_at": null
    },
    {
        "id": "ps_01HW0J61ZNNNYWWZWTRAMBSM0C",
        "created_at": "2024-04-21T14:50:24.077Z",
        "updated_at": "2024-04-21T15:04:58.516Z",
        "cart_id": "cart_01HW0HZ35BQW6JPM264Y417ATD",
        "provider_id": "stripe-ideal",
        "is_selected": null,
        "is_initiated": false,
        "status": "pending",
        "data": {},
        "idempotency_key": null,
        "amount": 97818,
        "payment_authorized_at": null
    },
    {
        "id": "ps_01HW0J61ZNK0771STTYGRY98VN",
        "created_at": "2024-04-21T14:50:24.077Z",
        "updated_at": "2024-04-21T15:04:58.516Z",
        "cart_id": "cart_01HW0HZ35BQW6JPM264Y417ATD",
        "provider_id": "stripe-blik",
        "is_selected": null,
        "is_initiated": false,
        "status": "pending",
        "data": {
            "id": "pi_3P81tqLncb1cbHug112IioWx",
            "amount": 97818,
            "object": "payment_intent",
            "review": null,
            "source": null,
            "status": "requires_payment_method",
            "created": 1713711710,
            "invoice": null,
            "currency": "pln",
            "customer": "xxxxx",
            "livemode": false,
            "metadata": {
                "resource_id": "cart_01HW0HZ35BQW6JPM264Y417ATD"
            },
            "shipping": null,
            "processing": null,
            "application": null,
            "canceled_at": null,
            "description": null,
            "next_action": null,
            "on_behalf_of": null,
            "client_secret": "xxx",
            "latest_charge": null,
            "receipt_email": "xxxxx",
            "transfer_data": null,
            "amount_details": {
                "tip": {}
            },
            "capture_method": "automatic",
            "payment_method": null,
            "transfer_group": null,
            "amount_received": 0,
            "amount_capturable": 0,
            "last_payment_error": null,
            "setup_future_usage": null,
            "cancellation_reason": null,
            "confirmation_method": "automatic",
            "payment_method_types": [
                "blik"
            ],
            "statement_descriptor": null,
            "application_fee_amount": null,
            "payment_method_options": {
                "blik": {}
            },
            "automatic_payment_methods": null,
            "statement_descriptor_suffix": null,
            "payment_method_configuration_details": null
        },
        "idempotency_key": null,
        "amount": 97818,
        "payment_authorized_at": null
    },
    {
        "id": "ps_01HW0J61ZN59FZ070R0Q9RG84A",
        "created_at": "2024-04-21T14:50:24.077Z",
        "updated_at": "2024-04-21T15:04:58.516Z",
        "cart_id": "cart_01HW0HZ35BQW6JPM264Y417ATD",
        "provider_id": "stripe-przelewy24",
        "is_selected": null,
        "is_initiated": false,
        "status": "pending",
        "data": {
            "id": "xxx",
            "amount": 97818,
            "object": "payment_intent",
            "review": null,
            "source": null,
            "status": "requires_payment_method",
            "created": 1713711721,
            "invoice": null,
            "currency": "pln",
            "customer": "xxxxx",
            "livemode": false,
            "metadata": {
                "resource_id": "cart_01HW0HZ35BQW6JPM264Y417ATD"
            },
            "shipping": null,
            "processing": null,
            "application": null,
            "canceled_at": null,
            "description": null,
            "next_action": null,
            "on_behalf_of": null,
            "client_secret": "xxx",
            "latest_charge": null,
            "receipt_email": "xxxxx",
            "transfer_data": null,
            "amount_details": {
                "tip": {}
            },
            "capture_method": "automatic",
            "payment_method": null,
            "transfer_group": null,
            "amount_received": 0,
            "amount_capturable": 0,
            "last_payment_error": null,
            "setup_future_usage": null,
            "cancellation_reason": null,
            "confirmation_method": "automatic",
            "payment_method_types": [
                "p24"
            ],
            "statement_descriptor": null,
            "application_fee_amount": null,
            "payment_method_options": {
                "p24": {}
            },
            "automatic_payment_methods": null,
            "statement_descriptor_suffix": null,
            "payment_method_configuration_details": null
        },
        "idempotency_key": null,
        "amount": 97818,
        "payment_authorized_at": null
    },
    {
        "id": "ps_01HW0J61ZNN9M47MB9J2QH44F9",
        "created_at": "2024-04-21T14:50:24.077Z",
        "updated_at": "2024-04-21T15:04:58.516Z",
        "cart_id": "cart_01HW0HZ35BQW6JPM264Y417ATD",
        "provider_id": "stripe",
        "is_selected": true,
        "is_initiated": true,
        "status": "pending",
        "data": {
            "id": "",
            "amount": 97818,
            "object": "payment_intent",
            "review": null,
            "source": null,
            "status": "requires_payment_method",
            "created": 1713711900,
            "invoice": null,
            "currency": "pln",
            "customer": "xxxxx",
            "livemode": false,
            "metadata": {
                "resource_id": "cart_01HW0HZ35BQW6JPM264Y417ATD"
            },
            "shipping": null,
            "processing": null,
            "application": null,
            "canceled_at": null,
            "description": null,
            "next_action": null,
            "on_behalf_of": null,
            "client_secret": "xxx",
            "latest_charge": null,
            "receipt_email": "xxxxx",
            "transfer_data": null,
            "amount_details": {
                "tip": {}
            },
            "capture_method": "manual",
            "payment_method": null,
            "transfer_group": null,
            "amount_received": 0,
            "amount_capturable": 0,
            "last_payment_error": null,
            "setup_future_usage": null,
            "cancellation_reason": null,
            "confirmation_method": "automatic",
            "payment_method_types": [
                "card"
            ],
            "statement_descriptor": null,
            "application_fee_amount": null,
            "payment_method_options": {
                "card": {
                    "network": null,
                    "installments": null,
                    "mandate_options": null,
                    "request_three_d_secure": "automatic"
                }
            },
            "automatic_payment_methods": null,
            "statement_descriptor_suffix": null,
            "payment_method_configuration_details": null
        },
        "idempotency_key": null,
        "amount": 97818,
        "payment_authorized_at": null
    }
]
```

As you can see some of these have the `data` object, and some don't, and this is problematic for `$medusa.carts.setPaymentSession` as this needs a client_secret for my Stripe Elements to load up, so the ones that have data work perfectly fine and the ones that don't obviously throw an error message.

```
{
    "type": "invalid_data",
    "message": "An error occurred in InitiatePayment during the creation of the stripe payment intent"
}
```

Unfortunately not much more in the medusa logs.

- So I initially thought it would because of the cart's region, or shipping information being incorrect -- as the ones that don't work are made for Germans, while the Polish ones work (przelewy 24 or blik) as my cart was initially in Poland. 
- I checked my stripe account and the not working payment methods are active and okay
- I did not try webhooks, as I worked only in local development but I feel like this is irrelevant 
- The other payment methods work well and I can achieve an order completion

It is not mentioned in the [stripe module docs](https://docs.medusajs.com/plugins/payment/stripe#implement-the-workflow) how to deal with `stripe-xxx` payment providers, 

Any clues?

### System information

Medusa version (including plugins): 1.20.4  / stripe: 6.0.9
Node.js version: v21.6.1
Database: Postgre

**Comment by R-Art-project** [comment]
I think you should validate that your stripe account accepts all the payment methods you are asking for. Or, in effect, that you have them authorized to receive payments in that way.

**Comment by davidparys** [comment]
> I think you should validate that your stripe account accepts all the payment methods you are asking for. Or, in effect, that you have them authorized to receive payments in that way.

<img width="1022" alt="Screenshot 2024-04-28 at 13 00 43" src="https://github.com/medusajs/medusa/assets/56082497/ae991bd7-b1a0-4703-bdda-ba79bac2070e">

I currently have the same stripe account running on a different shop platform and these payment methods are working perfectly fine. I'm starting to think it has something to do with region, but after changing it on medusa it did not affect anything, so I am wondering what could it be.

**Comment by R-Art-project** [comment]
I have a very similar or the same error. In my case I am implementing stripe but manually not through the plugin.
The stripe component is mounted correctly on the front and the payment is made successfully (in stripe). But in Medusa the payment is never authorized and as a consequence the order is never created.
I suspect that the fact that the payment is not authorized is related to the error described here.
If I find a solution I will post it here

Error in frontend
![Screenshot 2024-04-30 at 11 42 40 PM](https://github.com/medusajs/medusa/assets/66227758/1dec755e-1e35-4259-b137-e403f51f6e75)

Error in backend:

![Screenshot 2024-04-30 at 11 43 56 PM](https://github.com/medusajs/medusa/assets/66227758/41ac65fe-7ca4-49b9-9b35-005ad9ea7929)

But payment succeeded 🤯
![Screenshot 2024-04-30 at 11 44 38 PM](https://github.com/medusajs/medusa/assets/66227758/165e47c8-5f50-44c7-a89d-7f3e78f56e9c)

**Comment by R-Art-project** [comment]
@davidparys Some update about this issue?

**Comment by davidparys** [comment]
> @davidparys Some update about this issue?

I have at the moment resigned from the providers that did not work I am not sure how to approach this issue. 

Your issue seems a little bit more different as medusa needs to know that the payment session has been completed, I suppose there are some stripe.api involved to see if the payment_session has been finished when you call the complete cart function

**Comment by R-Art-project** [comment]
> > @davidparys Some update about this issue?
> 
> I have at the moment resigned from the providers that did not work I am not sure how to approach this issue.
> 
> Your issue seems a little bit more different as medusa needs to know that the payment session has been completed, I suppose there are some stripe.api involved to see if the payment_session has been finished when you call the complete cart function

No, look i have the same problem... I keep investigating
![Screenshot 2024-05-01 at 10 55 28 PM](https://github.com/medusajs/medusa/assets/66227758/f6928a6d-5b72-4496-94f8-ced567a9c02a)

**Comment by R-Art-project** [comment]
@davidparys Can you verify that all paymet providers are installed?
is_installed -> true

<img width="349" alt="Screenshot 2024-05-02 at 9 06 13 PM" src="https://github.com/medusajs/medusa/assets/66227758/b606c2b0-bf87-4d03-b7e9-7db05380fb02">

**Comment by aliyaus** [comment]
> I have a very similar or the same error. In my case I am implementing stripe but manually not through the plugin. The stripe component is mounted correctly on the front and the payment is made successfully (in stripe). But in Medusa the payment is never authorized and as a consequence the order is never created. I suspect that the fact that the payment is not authorized is related to the error described here. If I find a solution I will post it here
> 
> Error in frontend ![Screenshot 2024-04-30 at 11 42 40 PM](https://private-user-images.githubusercontent.com/66227758/327057058-1dec755e-1e35-4259-b137-e403f51f6e75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MTU2MDIsIm5iZiI6MTcyNTQxNTMwMiwicGF0aCI6Ii82NjIyNzc1OC8zMjcwNTcwNTgtMWRlYzc1NWUtMWUzNS00MjU5LWIxMzctZTQwM2Y1MWY2ZTc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDAyMDE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxZGQ4MDRiNmQ2NDY1NzJhN2NhOTM2YWFjMmQ1YjAzYjYzNmRiZGRlZmFjM2UwZDU4ZGUxMWQ0YTZmODNjZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7HtBl2z2T47RmroKW7B3RoXwN6KJL_VKRyVkNnmhSYE)
> 
> Error in backend:
> 
> ![Screenshot 2024-04-30 at 11 43 56 PM](https://private-user-images.githubusercontent.com/66227758/327057205-41ac65fe-7ca4-49b9-9b35-005ad9ea7929.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MTU2MDIsIm5iZiI6MTcyNTQxNTMwMiwicGF0aCI6Ii82NjIyNzc1OC8zMjcwNTcyMDUtNDFhYzY1ZmUtN2NhNC00OWI5LTliMzUtMDA1YWQ5ZWE3OTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDAyMDE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2Y2YwMmJkNTcxMTM1YTZlNjM5ZDQ3NmQ5YmE0Y2I1ZGE5ZTQyNzA2MGFlYjkyOTMzYmI2MTA3ZGFmMTEwZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aSOe0PTiO5n6hvWR4NuMyroB87chRAVkVDp97RtNe7c)
> 
> But payment succeeded 🤯 ![Screenshot 2024-04-30 at 11 44 38 PM](https://private-user-images.githubusercontent.com/66227758/327057287-165e47c8-5f50-44c7-a89d-7f3e78f56e9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MTU2MDIsIm5iZiI6MTcyNTQxNTMwMiwicGF0aCI6Ii82NjIyNzc1OC8zMjcwNTcyODctMTY1ZTQ3YzgtNWY1MC00NGM3LWE4OWQtN2YzZTc4ZjU2ZTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDAyMDE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNzJkZmNhMjQ4NWI2YzZhYjVhYTkwOWYzZGNjZGM2M2JmZjMyMjcyNjM0YzExNWNhODIxOGYzOWQ0ODNjNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0VDunQ9T_S0J8bxVXHruupfnDROniQMIshgjfj-jNrQ)

Am also facing the same issue while implementing Stripe manually instead of using the plugin. I don't see the same error message I just see that the order never gets created even though I call medusa.cart.complete on stripe.checkout.session.complete
