### ISSUE TITLE
Can eventbusservice send events from the plugin to the frontend?

### ISSUE THREAD

**Issue by czw333221** [medusajs/medusa#7145]
Can eventbusservice send events from the plugin to the frontend?

I'm creating a payment plugin, but the payment plugin doesn't provide a companion front-end button component. I want to trigger the click function and then receive the server plugin payment success event.

After receiving the payment success, call the complete cart function.

**Comment by shahednasser** [comment]
Hello, to create a payment plugin, you must create a payment processor as explained [here](https://docs.medusajs.com/modules/carts-and-checkout/backend/add-payment-provider).

Once the payment plugin is created and installed in the backend, you enable it in a region. Then, during checkout, the user can use it if it's available in their region.

If you're creating a custom frontend, then it's useful to follow [this guide on implementing checkout ](https://docs.medusajs.com/modules/carts-and-checkout/storefront/implement-checkout-flow). A payment session is created for every applicable payment processor, and if the user uses the payment session of your custom plugin, then you show them the button.

Closing this issue as it's not an issue. If you have further questions, feel free to open a discussion.

**Comment by czw333221** [comment]
> Hello, to create a payment plugin, you must create a payment processor as explained [here](https://docs.medusajs.com/modules/carts-and-checkout/backend/add-payment-provider).
> 
> Once the payment plugin is created and installed in the backend, you enable it in a region. Then, during checkout, the user can use it if it's available in their region.
> 
> If you're creating a custom frontend, then it's useful to follow [this guide on implementing checkout ](https://docs.medusajs.com/modules/carts-and-checkout/storefront/implement-checkout-flow). A payment session is created for every applicable payment processor, and if the user uses the payment session of your custom plugin, then you show them the button.
> 
> Closing this issue as it's not an issue. If you have further questions, feel free to open a discussion.

Thanks for the answer. The payment processor has been created and I would like to subscribe to the payment status on the front end via eventbusservice when receiving webhooks.

**Comment by shahednasser** [comment]
The event bus service doesn't work on the frontend, it works in the backend. The payment processor will be used as part of the checkout process, so all you need to do is create on the frontend the button used for the payment and show it when its associated payment session is selected.

**Comment by czw333221** [comment]
The payment button is created, my problem now is that I need to get the payment status in the button onclick, my solution now is to use SSE to get the payment status to trigger the onPaymentCompleted function. My solution is to use SSE to get the payment status to trigger the onPaymentCompleted function.
