### ISSUE TITLE
Getting CORS while implementing the steps given in docs

### ISSUE THREAD

**Issue by niioo** [medusajs/medusa#7146]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Getting CORS while implementing the steps given in docs

**Comment by shahednasser** [comment]
Can you elaborate? Not sure what steps you were trying to perform.

**Comment by dmiric** [comment]
I can elaborate :)

I cloned feat/v2 branch on my local machine, (Win10, Node 20 LTS). 
Created a new instance with "medusa new" using directory where I cloned feat/v2 as source. 
Installation went well no errors. 
I seeded the data and ran medusa develop command. 
It opened on localhost:7001 but when I try to login I get CORS error in network tab.
Hopefully that helps.

**Comment by shahednasser** [comment]
@dmiric  The admin dashboard doesn't support v2 at the moment, and I don't think the original issue is related to that.

Closing this issue, feel free to reopen it @niioo with more details.
