### ISSUE TITLE
Docs describing how to retrieve a cart with ReactJS not clear

### ISSUE THREAD

**Issue by joeldodich** [medusajs/medusa#7165]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

https://docs.medusajs.com/modules/carts-and-checkout/storefront/implement-cart

It is not very clear how the react cart component knows what cart to retrieve. There is a note about a path paramenter, but I could not find details describing what that parameter should be called or how to implement.

### How can this issue be resolved?

1. Update to reflect suggested implementation
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
As mentioned in the [create a cart](https://docs.medusajs.com/modules/carts-and-checkout/storefront/implement-cart#create-a-cart) section, the cart ID is saved in the localstorage. So, in your code you can check for it whenever necessary (such as to retrieve the cart). Once the order is placed or the customer logs out, you have to clear the cart ID from the local storage (which is also mentioned in the [retrieve cart](https://docs.medusajs.com/modules/carts-and-checkout/storefront/implement-cart#retrieve-a-cart) section.)

**Comment by joeldodich** [comment]
@shahednasser I guess what was unclear is that vanilla JS code example, the user has to pass a `cart_id` which matches the ID saved in the previous step you mention. In the ReactJS code, there is no reference to how the hook interacts with the local variable. Does it need to be the variable same name? Can I pass a different name? Do I need to use a separate hook to get the cart using the ID _then_ can use the cart object? 

As someone who is reading the docs and trying to put it all together, this is not clear to me. If you feel this is all implied and obvious, feel free to leave unchanged.

**Comment by shahednasser** [comment]
Can you specify which section you mean?

**Comment by ausazh** [comment]
I think I've come across the same confusion here, it's specifically with this code block:

[https://docs.medusajs.com/modules/carts-and-checkout/storefront/implement-cart#retrieve-a-cart](https://docs.medusajs.com/modules/carts-and-checkout/storefront/implement-cart#retrieve-a-cart)

The comment above mentions "You can retrieve the cart at any given point using its ID with the following code snippet", which is fine for the Medusa JS Client code `medusa.carts.retrieve(id)`, but the Medusa React code `const { cart } = useCart()` doesn't mention how to get a specific cart based on localStorage - I might have expected something like `const { cart } = useCart(id)` for example.

From my reading of the docs, while I understand how to *set* the localStorage "cart_id" value, I can't see anywhere where the localStorage "cart_id" value is *used* in Medusa React (as opposed to Medusa JS).

**Comment by shahednasser** [comment]
Good point @ausazh , it is mentioned but i guess the section should've been clearer about Medusa React.

As mentioned in the [prerequisites section](https://docs.medusajs.com/modules/carts-and-checkout/storefront/implement-cart#medusa-react), you must have `CartProvider` high in your component tree as explained [here](https://docs.medusajs.com/medusa-react/overview#cartprovider). Then, you would be able to retrieve the cart just using `useCart`.

I'll re-open the issue to make the text clearer. Thanks for the input!
