### ISSUE TITLE
docs: fix subscriber getPresignedDownloadUrl logic in digital products recipe

### ISSUE THREAD

**Issue by eskoniarek** [medusajs/medusa#7170]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

When running handleOrderPlaced example code, line 55 seems to run before the download urls are pushed to the urls array. Meaning that the dynamic link in handlebars is never sent regardless of whether there are actually any urls or not.

### How can this issue be resolved?

```
const urls = []
  for (const item of order.items) {
    const productMedias = await productMediaService.retrieveMediasByVariant(item.variant)
    const downloadUrl = await Promise.all(
      productMedias.map(async (productMedia) => {
        // get the download URL from the file service
        return await fileService.getPresignedDownloadUrl({
          fileKey: productMedia.file_key,
          isPrivate: true,
        })
      })
    )
  
    urls.push(...downloadUrl)
  }

```
This will:
1. Remove the early return if any item has no media
2. Properly wait for all the pre-signed URL promises to resolve for each item's media
3. Concatenate the resolved media URLs into the urls array

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch! I think the main problem is that the code snippet in the documentation uses `forEach` rather than `map`.

Feel free to open a PR to fix it

**Comment by eskoniarek** [comment]
@shahednasser thanks for the amazing documentation as well ! Will do for sure.

**Comment by shahednasser** [comment]
Thanks for the kind words 🙏 Looking forward to your PR!
