### ISSUE TITLE
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default. This is no longer the case. Verify if you need this module and configure a polyfill for it.

### ISSUE THREAD

**Issue by nyctonio** [medusajs/medusa#7186]
I have created a plugin but on its installation i am getting the error

ERROR in ./node_modules/@ritesh/medusa-brands/dist/admin/_virtual_entry.js 9:0-32
Module not found: Error: Can't resolve 'stream' in '/Users/nio/official/medusa/medusa-backend/node_modules/@ritesh/medusa-brands/dist/admin'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

**Comment by radoslaw-sz** [comment]
hi @nyctonio  - from what I can see the error is located in "@ritesh/medusa-brands" which looks like custom implementation, not related to Medusa core. I do not think it is related to Medusa itself as the error indicates problem with 'stream' module located in your custom implementation.

**Comment by sradevski** [comment]
This doesn't seem to be an issue with Medusa, closing. Please reach out on Discord if you need assistance from the community.
