### ISSUE TITLE
The browser opens undefined:7001 on a new project

### ISSUE THREAD

**Issue by kopec** [medusajs/medusa#7197]
When starting a new project with npx @medusajs/medusa-cli new store, and runing yarn && yarn run dev the application opens http://undefined:7001. I suppose it has something to do with this commit: https://github.com/medusajs/medusa/pull/7128

**Comment by soljae** [comment]
I have the same issue after upgrading medusajs

**Comment by shahednasser** [comment]
Hey guys, thank you for submitting this issue. We've issued a new release of Medusa (v1.20.6) that fixes this issue. Please install and use the latest version.

**Comment by soljae** [comment]
I've upgraded to v1.20.6, but it didn't resolve the issue for me @shahednasser

**Comment by shahednasser** [comment]
Sorry but can you also update the `@medusajs/admin` to v7.1.13 and try again?

**Comment by soljae** [comment]
No worries. My current @medusajs/admin version is v7.1.13

**Comment by shahednasser** [comment]
Can you try creating a new project and see if you're facing the same error? Sorry but I can't reproduce it on my end

**Comment by kopec** [comment]
> I've upgraded to v1.20.6, but it didn't resolve the issue for me @shahednasser

You have to be on @medusajs/admin version 7.1.14.

**Comment by soljae** [comment]
> > I've upgraded to v1.20.6, but it didn't resolve the issue for me @shahednasser
> 
> You have to be on @medusajs/admin version 7.1.14.

This fixed it. Thank you.
