### ISSUE TITLE
Drawer UI component in admin opens full screen

### ISSUE THREAD

**Issue by kopec** [medusajs/medusa#7221]
It seems like some css classes are not present when extending the admin dashboard with certain UI components. Namely Drawer. When placing this component inside an admin page, it behaves like a full screen modal. Missing classes are sm:right-2 sm:max-w-[560px] among others. It was working ok on 1.18.x. It started this behaviour when jumping to 1.20.x.

**Comment by vholik** [comment]
Having the same issue

**Comment by kopec** [comment]
Hi @vholik, thank you for confirming this issue. Have you found any solution yet?

**Comment by kopec** [comment]
@shahednasser could you have a look at this? I'd appreciate any hint on this. Thank you.

**Comment by shahednasser** [comment]
Maybe @kasperkristensen can help out here

**Comment by kopec** [comment]
Hi guys, any update on this? @kasperkristensen I'd appreciate any hint where to look for the fix.

**Comment by infsahitya** [comment]
Yes, the drawer component is opening in full screen instead of opening on the right pane of the screen. Any suggestions and solutions will be helpful a lot.

![Screenshot 2024-06-29 160345](https://github.com/medusajs/medusa/assets/16413342/74d042cc-a5d1-4857-b9d9-ca1f8383dbbf)

**Comment by quiloos39** [comment]
inside <Drawer.Content /> add `className="right-0 max-w-[400px]"`

**Comment by devcshort** [comment]
> className="right-0 max-w-[400px]"

This partly fixes it, although the animations still look like they are for full screen :/
