### ISSUE TITLE
How to add new Typesense plugin to plugin page?

### ISSUE THREAD

**Issue by ybirader** [medusajs/medusa#7237]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I've created a [Medusa Typesense plugin](https://github.com/ybirader/medusa-plugin-typesense) for a personal project.

I realised that this maybe useful to the community so have published it as an npm package, as per the "create plugin" docs.

How do I get it published on the main Medusa plugin directory?

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by radoslaw-sz** [comment]
hi @ybirader  - what do you mean by "published on the main Medusa plugin directory" ? You mean push to Medusa main repository? If yes, then I do think that Medusa repository contains only plugins provided by the core team, not by community.

**Comment by shahednasser** [comment]
Hi @ybirader thanks for creating the plugin! If you mean our main website's plugin directory, it has a script that looks up new plugins every now and then and adds them to the directory. So, if you have the necessary keywords as explained in [this doc](https://docs.medusajs.com/development/plugins/publish), the script will pick it up soon and add it to the directory.

Closing this issue as it's not an issue.
