### ISSUE TITLE
Docs(Code Issue): Code Issue in /development/backend/configurations

### ISSUE THREAD

**Issue by leotammaro** [medusajs/medusa#7241]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

## Details

This example for DATABASE_URL doesnt have password from db

### How can this issue be resolved?

Could change 
from `DATABASE_URL=postgres://postgres@localhost/medusa-store` 
to `DATABASE_URL=postgres://postgres:123456@localhost/medusa-store`

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you @leotammaro , however, this example isn't incorrect as the password is optional (depending on your setup). We still mention the expected connection URL format and where to include the password in the same documentation.
