### ISSUE TITLE
Cart APis Taking really long

### ISSUE THREAD

**Issue by VENGENCE7** [medusajs/medusa#7244]
## Bug report
Cart opearation takes about 8-10s

### Describe the bug
Deployment is on Cloud Run and and Cloud Build,
Database we are using Google Cloud Postgres

### System information
Database: Google Cloud Postgres
Memory : 1 Gib
CPU : 1

### Expected behavior
 Quicker responses from Cart Operations 

![image](https://github.com/medusajs/medusa/assets/86911386/97c42681-20b9-4302-af84-57c29ca130a4)

**Comment by LainLic** [comment]
Loading takes forever at the moment no matter if working with the cart on the frontend or changing settings in admin. I remember having a good experience last time I used medusa so I think it's not normal. On reddit two more people have problems with speed. Thought it could be in dev process only but if many people struggle it will probably be the same after build right?

**Comment by rakshit-Launchpad** [comment]
facing the same issue in my GCP deployment. also the cart complete API is talking much longer than this(like 20-25 sec)
