### ISSUE TITLE
Docs(Code Issue): Medusa AI Assistant showing & mixing old/deleted docs

### ISSUE THREAD

**Issue by OmarMHawash** [medusajs/medusa#7265]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Steps to reproduce:
1. Ask for `useToast medusa ui`
2. Click on **useToast documentation** reference source link

**Image showing mix of old & new doc references:**

![Screen Shot 2024-05-07 at 5 10 37 PM](https://github.com/medusajs/medusa/assets/81506354/8aff0fa7-d723-452f-997f-d97964141435)

### How can this issue be resolved?

1.
2.
3.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for reporting this! WIll issue an update to its index.

Closing this issue as it'll be resolved off github
