### ISSUE TITLE
Typo: Landing Page

### ISSUE THREAD

**Issue by bhardwajakshit** [medusajs/medusa#7279]
### Describe the bug

There's a minor typo on the [landing page](https://medusajs.com/#:~:text=Join%20our%20a%20community). 

### Steps to reproduce the behavior

1. Visit [Medusa Landing Page](https://medusajs.com/#:~:text=Join%20our%20a%20community)

### Expected behavior

- Should be corrected to **_Join our community of more..._** from **_Join our a community of more..._** 
### Screenshots
<img width="1440" alt="Screenshot 2024-05-09 at 4 53 01 AM" src="https://github.com/medusajs/medusa/assets/66516548/3ffce522-8122-4d57-bcce-356b1e6861ee">

### Additional context

Reporting this issue here as I'm uncertain if the landing page repository is public, it seems to be private.

**Comment by shahednasser** [comment]
Thanks for reporting this! WIll forward it to the relevant team.
