### ISSUE TITLE
Cart discount applied subscriber

### ISSUE THREAD

**Issue by BorisKamp** [medusajs/medusa#7294]
Hi!

Using medusa `1.20.6` im refactoring my custom subscriber files to match the [new](https://docs.medusajs.com/development/events/create-subscriber) way. My current subscribers use the [old deprecated way](https://docs.medusajs.com/development/events/create-subscriber-deprecated) 

I have one subscriber which listened to the `cart-discount.applied` event but I cannot find the subscriber for it in the new way of doing this. The cartService only has [these events](https://docs.medusajs.com/development/events/events-list#cart-events).

How can I do this?

**edit: added old subscriber code:**

```javascript
import { addProductToDeal } from './../custom/pipedriveApi'

class CartDiscountNotifierSubscriber {
  protected readonly cartService
  config = {
    relations: ['discounts', 'discounts.rule', 'region'],
  }

  constructor({ eventBusService, cartService }) {
    eventBusService.subscribe('cart-discount.applied', this.cartDiscountApplied)

    this.cartService = cartService
  }

  // We apply the discount to the deal in Pipedrive
  cartDiscountApplied = async (data) => {
    // We wait for 5 seconds so we know for sure that if we fetch the cart, the discount is applied.
    setTimeout(() => {
      this.cartService
        .retrieveWithTotals(data.cart_id, this.config)
        .then(async (cart) => {
          if (
            cart.context.pipedrive_deal_id &&
            cart.discount_total &&
            cart.discounts?.length > 0
          ) {
            await addProductToDeal(
              cart.context.pipedrive_deal_id,
              process.env.PIPEDRIVE_DISCOUNT_PRODUCT_ID,
              -cart.discount_total / 100,
              1,
              cart.region?.tax_rate,
              cart.discounts?.[0].rule?.description
            )
          }
        })
    }, 5000)
  }
}

export default CartDiscountNotifierSubscriber

```

**Comment by adevinwild** [comment]
I tried to look for the `cart-discount.applied` in the old codebase, but it has never existed, maybe it was a custom event or I missed something ?
What you could do to achieve the same behavior would be to extend the `CartService.applyDiscounts` function and use the `EventBusService`  to emit our custom event.


First we extend the CartService :
```ts
// src/services/cart.ts (A new file to create)


import { Cart, CartService as MedusaCartService } from '@medusajs/medusa' // Here we are using an alias `MedusaCartService`
import { Lifetime } from "awilix"

class CartService extends MedusaCartService {
    static LIFE_TIME = Lifetime.SCOPED
    static readonly Events = {
        ...MedusaCartService.Events,
        DISCOUNT_APPLIED: "cart-discount.applied"
    }

    constructor() {
        // @ts-ignore
        super(...arguments)
    }


    async applyDiscounts(cart: Cart, discountCodes: string[]): Promise<void> {
        await super.applyDiscounts(cart, discountCodes)

        this.eventBus_.emit(CartService.Events.DISCOUNT_APPLIED, cart) // Or anything you need in 2nd parameter, here we sending the `cart` object to the Subscriber
    }
}

export default CartService
```

Then we can create a new Subscriber : 
```ts
// src/subscribers/cart-discount.ts

import {
    type SubscriberConfig,
    type SubscriberArgs,
} from "@medusajs/medusa"
import CartService from "../services/cart"

export default async function cartDiscountHandler({
    data, eventName, container, pluginOptions,
}: SubscriberArgs<Record<string, any>>) {
    const cart = data

    // do something with the cart...
}

export const config: SubscriberConfig = {
    event: CartService.Events.DISCOUNT_APPLIED,
    context: {
        subscriberId: "cart-discount-handler",
    },
}
```


You should receive the event when trying to add a Discount to your cart, here the log in the terminal : 
![image](https://github.com/medusajs/medusa/assets/68734155/306ecf67-6924-4c91-9fbd-4b308b4305a3)

**Comment by BorisKamp** [comment]
Same for the `draft_order.deleted` event, it is not in the docs anymore....

**Comment by adevinwild** [comment]
> Same for the `draft_order.deleted` event, it is not in the docs anymore....

What was your Medusa version?

**Comment by BorisKamp** [comment]
@adevinwild Thank you for your reply.
I was too quick to post here, it seemed I had custom emits placed in my code for both `cart-discount.applied` and `draft_order.deleted`, so you're right you could not find them... Sorry about that.

Your approach is interesting, I have this code now:
```javascript
// src/services/carts.ts

import {
  Cart,
  EventBusService,
  CartService as MedusaCartService,
} from '@medusajs/medusa' // Here we are using an alias `MedusaCartService`

class CartService extends MedusaCartService {
  static readonly Events = {
    ...MedusaCartService.Events,
    DISCOUNT_APPLIED: 'cart-discount.applied',
  }

  constructor() {
    // @ts-ignore
    super(...arguments)
  }

  /**
   * Updates the cart's discounts.
   * If discount besides free shipping is already applied, this
   * will be overwritten
   * Throws if discount regions does not include the cart region
   * @param cart - the cart to update
   * @param discountCode - the discount code
   */

  async applyDiscount(cart: Cart, discountCode: string): Promise<void> {
    console.log('1234')
    const discount = await this.applyDiscounts(cart, [discountCode])
    this.eventBus_.emit(CartService.Events.DISCOUNT_APPLIED, cart) // Or any object you need in 2nd parameter

    console.log('Discount applied', discount)

    return discount
  }
}

export default CartService
```

However, it does not work, it is not printing `1234` when I apply a discount. What I did for now is add a middleware to `/store/carts/:cartId` and in there check if `if (req.body?.discounts?.length > 0) { do stuff }`

This works.

But I would like to figure out your way as well (to learn!).

Another question, By extending `applyDiscount`, in the `src/services/carts.ts` file, we are just adding logic to the base `applyDiscount` method right, instead of replacing it? So if Medusa updates `applyDiscount` I do not get problems?

**Comment by adevinwild** [comment]
> @adevinwild Thank you for your reply. I was too quick to post here, it seemed I had custom emits placed in my code for both `cart-discount.applied` and `draft_order.deleted`, so you're right you could not find them... Sorry about that.
> 
> Your approach is interesting, I have this code now:
> 
> ```js
> // src/services/carts.ts
> 
> import {
>   Cart,
>   EventBusService,
>   CartService as MedusaCartService,
> } from '@medusajs/medusa' // Here we are using an alias `MedusaCartService`
> 
> class CartService extends MedusaCartService {
>   static readonly Events = {
>     ...MedusaCartService.Events,
>     DISCOUNT_APPLIED: 'cart-discount.applied',
>   }
> 
>   constructor() {
>     // @ts-ignore
>     super(...arguments)
>   }
> 
>   /**
>    * Updates the cart's discounts.
>    * If discount besides free shipping is already applied, this
>    * will be overwritten
>    * Throws if discount regions does not include the cart region
>    * @param cart - the cart to update
>    * @param discountCode - the discount code
>    */
> 
>   async applyDiscount(cart: Cart, discountCode: string): Promise<void> {
>     console.log('1234')
>     const discount = await this.applyDiscounts(cart, [discountCode])
>     this.eventBus_.emit(CartService.Events.DISCOUNT_APPLIED, cart) // Or any object you need in 2nd parameter
> 
>     console.log('Discount applied', discount)
> 
>     return discount
>   }
> }
> 
> export default CartService
> ```
> 
> However, it does not work, it is not printing `1234` when I apply a discount. What I did for now is add a middleware to `/store/carts/:cartId` and in there check if `if (req.body?.discounts?.length > 0) { do stuff }`
> 
> This works.
> 
> But I would like to figure out your way as well (to learn!).
> 
> Another question, By extending `applyDiscount`, in the `src/services/carts.ts` file, we are just adding logic to the base `applyDiscount` method right, instead of replacing it? So if Medusa updates `applyDiscount` I do not get problems?

hey @BorisKamp 
Sorry just updated my code snippet !

In this updated code snippet you don't have to worry about Medusa next updates (Apart from version 2.x, I don't want to get ahead of myself, but I think some things will change since the whole codebase get some big updates), here, we are just overriding the function but we do not change anything inside it's original behavior, so don't worry about it.

By the way, if you want to know how I did to find which function to override, I just followed the path from the storefront to the backend, when you add a discount to the Cart, it updates the cart using the `CartService.update` function, referenced [here](https://github.com/medusajs/medusa/blob/v1.20.6/packages/medusa/src/services/cart.ts#L1198).

Then at line [#1280](https://github.com/medusajs/medusa/blob/v1.20.6/packages/medusa/src/services/cart.ts#L1280), we can see that the `CartService.applyDiscounts` is used, so this is the one we wants to override :)

Now you can implement on your own the same concept to your DraftOrder custom event

**Comment by BorisKamp** [comment]
Hey @adevinwild 
Clear, thank for all the explanation!

this still does not work for me tho, when I add a discount, I only get these events:
<img width="441" alt="Screenshot 2024-05-13 at 10 24 16" src="https://github.com/medusajs/medusa/assets/8350740/59d22e81-76a4-46b5-9514-c4424e7b7b19">

My `carts.ts` is exactly as you described.

**Comment by adevinwild** [comment]
> Hey @adevinwild Clear, thank for all the explanation!
> 
> this still does not work for me tho, when I add a discount, I only get these events: <img alt="Screenshot 2024-05-13 at 10 24 16" width="441" src="https://private-user-images.githubusercontent.com/8350740/329978166-59d22e81-76a4-46b5-9514-c4424e7b7b19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODk3MjgsIm5iZiI6MTcxNTU4OTQyOCwicGF0aCI6Ii84MzUwNzQwLzMyOTk3ODE2Ni01OWQyMmU4MS03NmE0LTQ2YjUtOTUxNC1jNDQyNGU3YjdiMTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTNUMDgzNzA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGE4YjMzNDA2ZjAxZWNhZTRhYTc1ZWJjMjhhOTk3NTk2YmNhMDA0NTc0ZTBjZThhYjRkYmYzZDg3M2JmNWNlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fLxCYCX61dvejFTA-b8f3eNQPnd9mCIAkySFhgukx7E">
> 
> My `carts.ts` is exactly as you described.

Weird I tried on my computer and had no issues, how do you apply the discount to a Cart ? I used the Next.js Starter to test it and it just updates the Cart by adding to `cart.discounts` a specific discount.

**Comment by BorisKamp** [comment]
> > Hey @adevinwild Clear, thank for all the explanation!
> > this still does not work for me tho, when I add a discount, I only get these events: <img alt="Screenshot 2024-05-13 at 10 24 16" width="441" src="https://private-user-images.githubusercontent.com/8350740/329978166-59d22e81-76a4-46b5-9514-c4424e7b7b19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODk3MjgsIm5iZiI6MTcxNTU4OTQyOCwicGF0aCI6Ii84MzUwNzQwLzMyOTk3ODE2Ni01OWQyMmU4MS03NmE0LTQ2YjUtOTUxNC1jNDQyNGU3YjdiMTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTNUMDgzNzA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGE4YjMzNDA2ZjAxZWNhZTRhYTc1ZWJjMjhhOTk3NTk2YmNhMDA0NTc0ZTBjZThhYjRkYmYzZDg3M2JmNWNlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fLxCYCX61dvejFTA-b8f3eNQPnd9mCIAkySFhgukx7E">
> > My `carts.ts` is exactly as you described.
> 
> Weird I tried on my computer and had no issues, how do you apply the discount to a Cart ? I used the Next.js Starter to test it and it just updates the Cart by adding to `cart.discounts` a specific discount.

I call [Update cart](https://docs.medusajs.com/api/store#carts_postcartscart) with `discounts` in the body. Which the the only way to add a discount to a cart imo?

**Comment by adevinwild** [comment]
> > > Hey @adevinwild Clear, thank for all the explanation!
> > > this still does not work for me tho, when I add a discount, I only get these events: <img alt="Screenshot 2024-05-13 at 10 24 16" width="441" src="https://private-user-images.githubusercontent.com/8350740/329978166-59d22e81-76a4-46b5-9514-c4424e7b7b19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODk3MjgsIm5iZiI6MTcxNTU4OTQyOCwicGF0aCI6Ii84MzUwNzQwLzMyOTk3ODE2Ni01OWQyMmU4MS03NmE0LTQ2YjUtOTUxNC1jNDQyNGU3YjdiMTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTNUMDgzNzA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGE4YjMzNDA2ZjAxZWNhZTRhYTc1ZWJjMjhhOTk3NTk2YmNhMDA0NTc0ZTBjZThhYjRkYmYzZDg3M2JmNWNlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fLxCYCX61dvejFTA-b8f3eNQPnd9mCIAkySFhgukx7E">
> > > My `carts.ts` is exactly as you described.
> > 
> > 
> > Weird I tried on my computer and had no issues, how do you apply the discount to a Cart ? I used the Next.js Starter to test it and it just updates the Cart by adding to `cart.discounts` a specific discount.
> 
> I call [Update cart](https://docs.medusajs.com/api/store#carts_postcartscart) with `discounts` in the body. Which the the only way to add a discount to a cart imo?

yes you're right, we are doing the same thing, maybe we are missing something here...
Can you share a repro of your repo so I can check?

**Comment by BorisKamp** [comment]
@adevinwild I can invite you to the repo as it's private. What email address can I use?

**Comment by BorisKamp** [comment]
Im having some other wierd behavior as well, this is my `middlewares.ts` file:
```javascript
// import { raw } from 'body-parser'
import {
  MedusaNextFunction,
  MedusaRequest,
  MedusaResponse,
  type MiddlewaresConfig,
} from '@medusajs/medusa'
// import { addDiscountToPipedriveDeal } from '../custom/middleware/add-discount-to-pipedrive-deal'
// import { removeDiscountFromPipedriveDeal } from '../custom/middleware/remove-discount-from-pipedrive-deal'
// import { addProductToPipedriveDeal } from '../custom/middleware/add-product-to-pipedrive-deal'
// import { updateProductOnPipedriveDeal } from '../custom/middleware/update-product-on-pipedrive-deal'
// import { removeProductFromPipedriveDeal } from '../custom/middleware/remove-product-from-pipedrive-deal'
// import { setCustomerMiddleware } from '../custom/middleware/set-customer-middleware'

const updateProductOnPipedriveDeal = (
  req: MedusaRequest,
  res: MedusaResponse,
  next: MedusaNextFunction
) => {
  console.dir(req.body)
  // do something
  next()
}

export const config: MiddlewaresConfig = {
  routes: [
    // {
    //   matcher: '/routes/store/hooks-test',
    //   middlewares: [raw({ type: 'application/json' })],
    //   bodyParser: false,
    // },

    // {
    //   matcher: '/store/*',
    //   middlewares: [setCustomerMiddleware],
    // },

    // // Carts middleware
    // {
    //   matcher: '/store/carts/:cartId',
    //   middlewares: [addDiscountToPipedriveDeal],
    //   method: ['POST'],
    // },

    // {
    //   matcher: '/store/carts/:cartId/discounts/:discountCode',
    //   middlewares: [removeDiscountFromPipedriveDeal],
    //   method: ['DELETE'],
    // },

    // // Draft orders
    // {
    //   matcher: '/admin/draft-orders/:id/line-items',
    //   middlewares: [addProductToPipedriveDeal],
    //   method: ['POST'],
    // },

    {
      matcher: '/admin/draft-orders/:id/line-items/:lineItemId',
      middlewares: [updateProductOnPipedriveDeal],
      method: ['POST'],
    },

    // {
    //   matcher: '/admin/draft-orders/:id/line-items/:lineItemId',
    //   middlewares: [removeProductFromPipedriveDeal],
    //   method: ['DELETE'],
    // },
  ],
}
```
 and on line 20 I print the body, however, it is always `undefined` although I definitely send a body......

Im so confused here. I commented out all the other code in the file to make sure that does cause it.

**Comment by adevinwild** [comment]
Sent you a message on Discord @BorisKamp

**Comment by adevinwild** [comment]
**Main issue is fixed, it's because the filename was `cart.ts` instead of `carts.ts`.**


For the other issue about middlewares, I had the same issue and here is the solution if you want to access the `req.body` inside a middleware : 

```ts

import {
  urlencoded,
  json
} from "body-parser"

const updateProductOnPipedriveDeal = (
  req: MedusaRequest,
  res: MedusaResponse,
  next: MedusaNextFunction
) => {
  console.dir(req.body)
  // do something
  next()
}


export const config: MiddlewaresConfig = {
  routes: [{
    matcher: '/admin/draft-orders/:id/line-items/:lineItemId',
    middlewares: [urlencoded({ extended: true }), json(), updateProductOnPipedriveDeal],
    method: ['POST'],
  },
  ]
}

```

> Edit: Finally I was just missing the `json()`

**Comment by adevinwild** [comment]
I think we can close this issue 🙌🏼

**Comment by BorisKamp** [comment]
Thank you @adevinwild !

@shahednasser / core team, please update the middleware docs to include this part about the body parsing.

**Comment by shahednasser** [comment]
Just to check: you had to manually add the `json` middleware to access the body in the middleware or in the route? It should work fine in the route right?

If it's in the middleware, we can add a troubleshooting around it, but this is a specific use case so i don't think adding it in the main docs makes sense

**Comment by adevinwild** [comment]
> Just to check: you had to manually add the `json` middleware to access the body in the middleware or in the route? It should work fine in the route right?
> 
> If it's in the middleware, we can add a troubleshooting around it, but this is a specific use case so i don't think adding it in the main docs makes sense

For routes, no problem, but when you try to access the body in middleware, it's impossible to get a value.
So whenever you want to access `req.body` in a **custom middleware** you just need to add `urlencoded` and `json` from the `body-parser` package.

[Docs talks about this a bit](https://docs.medusajs.com/development/api-routes/create#parse-request-body-parameters), but no mention of accessing the body inside a middleware, and maybe you're right, it's a specific use case

**Comment by shahednasser** [comment]
Thanks for letting me know. For now I'll close this issue and ensure to add this as a troubleshooting guide
