### ISSUE TITLE
not getting connected with the medusa port.

### ISSUE THREAD

**Issue by GAURANGSURTE** [medusajs/medusa#7298]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I'm trying to connect to the medusa store that I've created but cannot able to access it, actually I don't have any about how to reconnect to the store front and that's why I'm here to solve my problem 
![Screenshot 2024-05-11 003850](https://github.com/medusajs/medusa/assets/88529949/c99cba15-cc9a-429e-8f57-98502eab02a7)

### How can this issue be resolved?

1. you can give me the command to start it 
2. instructions to solve the issue 
3.guide
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by adevinwild** [comment]
What about using `npx medusa develop` instead ?

**Comment by shahednasser** [comment]
Why are you running `medusa develop` in the storefront? That should only be used in the Medusa backend.

If you're using the Next.js storefront, you can run it with `npm run dev` or `yarn dev`.

**Comment by GAURANGSURTE** [comment]
can you tell me about how to start the medusa backend

**Comment by shahednasser** [comment]
To start the medusa backend, go to its directory and run `npm run dev` or `yarn dev`.

Will close this issue, feel free to re-open it if you face any other problems.
