### ISSUE TITLE
"Environment" instead of "Networking" ty[p

### ISSUE THREAD

**Issue by PropWeights** [medusajs/medusa#7300]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

On the https://docs.medusajs.com/deployments/server/deploying-on-railway page under the "Add Domain Name" section, under 2. it currently says:
2. Click on the Settings tab and scroll down to the **Environment** section.
But it should say:
2. Click on the Settings tab and scroll down to the **Networking** section.

Thanks.

### How can this issue be resolved?

Fix the typo from "Environment" to "Networking".

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Hi, not sure if this was referring to an old version of railway but new projects have an Environment section, not Networking.

Will close this issue. Feel free to re-open it if necessary,
