### ISSUE TITLE
API Ref(admin): Issue with downloading full reference

### ISSUE THREAD

**Issue by mbohlini** [medusajs/medusa#7316]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Broken link for Download Full Reference.
https://docs.medusajs.com/api/download/store
When i press the link i just get a 404. Same issue for
https://docs.medusajs.com/api/download/admin

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for reporting this issue! I've opened a PR to fix it

**Comment by shahednasser** [comment]
Issue fixed in PR #7318
