### ISSUE TITLE
JwtStrategy requires a secret or key

### ISSUE THREAD

**Issue by smartdev09** [medusajs/medusa#7320]
### Describe the bug

I get `JwtStrategy requires a secret or key` when running `npx create-medusa-app@latest`

![Uploading jwt stratyegy.png…]()

### System information

Medusa version (including plugins):
Node.js version: 18.17
Database: Postgres 
Operating system: Ubuntu
Browser (if relevant): Not relevant

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by shahednasser** [comment]
Can you try again? issue should be fixed now

**Comment by shahednasser** [comment]
Can you try again now? Issue should be fixed

**Comment by DgitalNarrative** [comment]
I was also having the same issue since yesterday afternoon. Tested 1h ago and kept getting that same error.
Tested just now and the issue seems to be fixed.
Thank you @shahednasser for the quick response to this.

**Comment by shahednasser** [comment]
Yea sorry about that, pushed a small update yesterday that messed it up 😅

Closing this issue now

**Comment by smartdev09** [comment]
The error is gone, thanks @shahednasser. 

But the installation is stuck on `Finish preparation...`
