### ISSUE TITLE
Repo's findAndCount only returns one result

### ISSUE THREAD

**Issue by BorisKamp** [medusajs/medusa#7343]
Hi!

Using Medusa `1.20.6` I have this custom route:
```javascript
// src/api/admin/variants/company/[company]/route.ts
import {
  ProductVariant,
  type MedusaRequest,
  type MedusaResponse,
} from '@medusajs/medusa'
import { EntityManager, Raw } from 'typeorm'

export const GET = async (req: MedusaRequest, res: MedusaResponse) => {
  const manager: EntityManager = req.scope.resolve('manager')
  const productVariantRepo = manager.getRepository(ProductVariant)

  const [variants, count] = await productVariantRepo.findAndCount({
    where: {
      bb_company_slugs: Raw(() => '"bb_company_slugs"::TEXT ILIKE \'%"bb"%\''),
    },
    skip: 0,
    take: 10,
  })

  return res.json({
    variants,
    count,
  })
}
```

To query product variants by a custom `jsonb` field I added called `bb_company_slugs`.

Here's a screenshot of the data in the table
<img width="1108" alt="Screenshot 2024-05-15 at 17 03 56" src="https://github.com/medusajs/medusa/assets/8350740/284e4674-1f62-4e6c-b2f2-0a8101c37f5d">

As you can see there are three records with values for that field.

Now if I call `{{medusa-host}}/admin/variants/company/bbs?limit=10` I only get back one result, I've tried so many different raw queries but I cannot seem to get more then one result. 

The query is copied from Postico on my Macbook, where it works and return two results:
<img width="1116" alt="Screenshot 2024-05-15 at 17 06 02" src="https://github.com/medusajs/medusa/assets/8350740/16ca3b62-5f9f-4e45-ac64-8359daf5ed11">

Is this a bug?

**Comment by olivermrbl** [comment]
Can I get you to add [database logging](https://docs.medusajs.com/development/backend/configurations#database_logging) and paste the query that Typeorm fires here?

**Comment by BorisKamp** [comment]
> Can I get you to add [database logging](https://docs.medusajs.com/development/backend/configurations#database_logging) and paste the query that Typeorm fires here?

Ah perfect, I was looking for something like that but could not find it!

It logs this:
```
query: SELECT "ProductVariant"."id" AS "ProductVariant_id", "ProductVariant"."created_at" AS "ProductVariant_created_at", "ProductVariant"."updated_at" AS "ProductVariant_updated_at", "ProductVariant"."deleted_at" AS "ProductVariant_deleted_at", "ProductVariant"."title" AS "ProductVariant_title", "ProductVariant"."product_id" AS "ProductVariant_product_id", "ProductVariant"."sku" AS "ProductVariant_sku", "ProductVariant"."barcode" AS "ProductVariant_barcode", "ProductVariant"."ean" AS "ProductVariant_ean", "ProductVariant"."upc" AS "ProductVariant_upc", "ProductVariant"."variant_rank" AS "ProductVariant_variant_rank", "ProductVariant"."inventory_quantity" AS "ProductVariant_inventory_quantity", "ProductVariant"."allow_backorder" AS "ProductVariant_allow_backorder", "ProductVariant"."manage_inventory" AS "ProductVariant_manage_inventory", "ProductVariant"."hs_code" AS "ProductVariant_hs_code", "ProductVariant"."origin_country" AS "ProductVariant_origin_country", "ProductVariant"."mid_code" AS "ProductVariant_mid_code", "ProductVariant"."material" AS "ProductVariant_material", "ProductVariant"."weight" AS "ProductVariant_weight", "ProductVariant"."length" AS "ProductVariant_length", "ProductVariant"."height" AS "ProductVariant_height", "ProductVariant"."width" AS "ProductVariant_width", "ProductVariant"."metadata" AS "ProductVariant_metadata", "ProductVariant"."bb_company_slugs" AS "ProductVariant_bb_company_slugs" FROM "public"."product_variant" "ProductVariant" WHERE ( (("bb_company_slugs"::TEXT ILIKE '%"bb"%')) ) AND ( "ProductVariant"."deleted_at" IS NULL ) LIMIT 10
query: SELECT COUNT(1) AS "cnt" FROM "public"."product_variant" "ProductVariant" WHERE ( (("bb_company_slugs"::TEXT ILIKE '%"bb"%')) ) AND ( "ProductVariant"."deleted_at" IS NULL )
```

So two `SELECT FROM WHERE` queries are ran, the first one seems correct, but the second one indeed has the `COUNT(1)` in it. No idea where that comes from, you do?

**Comment by olivermrbl** [comment]
Typeorm always runs the count query separately from the "main" query – if you run `find` instead of `findAndCount` it won't be there. 

What happens if you c/p the first query and fire it directly against your DB?

**Comment by BorisKamp** [comment]
Ah okay @olivermrbl . Can you elaborate on this `What happens if you c/p the first query and fire it directly against your DB?`, I have no clue what you mean by `c/p`?

**EDIT: c/p is copy paste off course, let me try, silly me.**

By the way, is there any way I can get this new column to be implemented in the existing `{{medusa-host}}/admin/variants` endpoint and make the param `bb_company_slugs=bb` work as Im doing in this custom endpoint? I know how to do that with text and number fields, but not with `jsonb` fields.

**Comment by BorisKamp** [comment]
> What happens if you c/p the first query and fire it directly against your DB?
I get back the same single response I get back in Postman.... thats weird to me! 
<img width="1114" alt="Screenshot 2024-05-15 at 19 57 21" src="https://github.com/medusajs/medusa/assets/8350740/60fecfc2-0494-4108-aad8-31e2de927822">

**Comment by olivermrbl** [comment]
What if you remove the double qoutes `""` from the ILIKE -> `%bb%`

**Comment by BorisKamp** [comment]
> What if you remove the double qoutes `""` from the ILIKE -> `%bb%`

Pff Comparing the two queries (the one TypeORM makes and the one from Postico on my mac) I found out that TypeORM adds a `AND` clause to exclude deleted variants. Which makes sense! But I've overlooked this compared to what I saw in Postico and some rows returned there we're deleted variants....

That's what happens when I'm programming for too long straight without rest )-:

Thanks for the help!

**Comment by olivermrbl** [comment]
Glad you figured it out!

**Comment by BorisKamp** [comment]
> Glad you figured it out!

Do you have a hint for this?:
>By the way, is there any way I can get this new column to be implemented in the existing {{medusa-host}}/admin/variants endpoint and make the param bb_company_slugs=bb work as Im doing in this custom endpoint? I know how to do that with text and number fields, but not with jsonb fields.

**Comment by olivermrbl** [comment]
Hmm, I haven't had to do this before, so I can't offer much help without digging into it. Perhaps @shahednasser has ideas from building examples?

**Comment by shahednasser** [comment]
Hi @BorisKamp , I believe the way to do this would be:

1. [Extend the repository](https://docs.medusajs.com/development/entities/extend-repository) to modify how the find/findAndCount methods work and handle your custom field differently.
2. [Extend the validator](https://docs.medusajs.com/development/api-routes/extend-validator) of the `/admin/variants` API route to allow passing your custom field as a query parameter.

I haven't actually tried this out but I believe that should get your use case working 😄

**Comment by BorisKamp** [comment]
> Hi @BorisKamp , I believe the way to do this would be:
> 
> 1. [Extend the repository](https://docs.medusajs.com/development/entities/extend-repository) to modify how the find/findAndCount methods work and handle your custom field differently.
> 2. [Extend the validator](https://docs.medusajs.com/development/api-routes/extend-validator) of the `/admin/variants` API route to allow passing your custom field as a query parameter.
> 
> I haven't actually tried this out but I believe that should get your use case working 😄

Thank you for your reply. However, I do not see how this would work. Im talking about extending functionality so that the core GET variants endpoint accepts a params like so: `bb_company_slugs_include=bb`. And looking at my column data in the first post, only return the rows that contain `"bb"`.

**Comment by shahednasser** [comment]
The second step ensures that the endpoint accepts the parameter, and the first step defines how filtering the parameter happens (the core uses the repository under the hood).

If you check the service [here](https://github.com/medusajs/medusa/blob/cbb2f3c855e8c07416b4d7ff829c3003a82f4a2f/packages/medusa/src/services/product-variant.ts#L951), it uses the `findAndCount` method of the repository to retrieve the records. The service is used by the endpoint.

Alternatively, you can extend the service and override the `listAndCount` method to handle the filtering logic you want, but looking at the filtering logic in the endpoint above, you probably need to implement it in the repository.
