### ISSUE TITLE
Column deleted_at does not exist on database when fetching with product module

### ISSUE THREAD

**Issue by samhenderson511** [medusajs/medusa#7355]
### Describe the bug

I updated the Medusa backend a few days ago and just today the frontend has started throwing errors from the product module: 
```
Error: select "p0"."id", "p0"."handle", "p0"."name", "p0"."parent_category_id" from "public"."product_category" as "p0" where "p0"."deleted_at" is null and "p0"."handle" like '%/MENSWEAR%' and "p0"."is_active" = true limit 1000 - column p0.deleted_at does not exist
```
The same thing happens when fetching both products and product categories.

### System information

Medusa version (including plugins):
```
    "@medusajs/medusa": "^1.20.6",
    "@medusajs/medusa-js": "^6.1.8",
    "@medusajs/pricing": "^0.1.12",
    "@medusajs/product": "^0.3.12",
```
Node.js version: 20.13.1
Database: Postgres
Operating system: MacOS
Browser (if relevant): Arc

### Steps to reproduce the behavior

1. Fetch something with product module
2. deleted_at column doesn't exist in database

### Expected behavior

I should receive an array of categories from this code:
``` jsx
const productService = await initializeProductModule()
const categories = await productService.listCategories(
{ handle: { $like: `%${categoryHandle}%` } as any, is_active: true },
{
take: 1000,
select: ["id", "handle", "name", "parent_category_id"],
}
```

**Comment by sradevski** [comment]
@samhenderson511 please make sure the migrations have been run again, as that's likely the culprit. If that doesn't work, you can try and add the columns manually in your DB
