### ISSUE TITLE
Error 400 when create new cart

### ISSUE THREAD

**Issue by poiuyt183** [medusajs/medusa#7361]
![image](https://github.com/medusajs/medusa/assets/81480245/76fe02bb-c99f-4897-ae92-f38238e89891)

I can't create new cart, though I followed the instruction of ![How to Add Cart Functionality] (https://docs.medusajs.com/modules/carts-and-checkout/storefront/implement-cart)
Please, help me!

**Comment by sradevski** [comment]
Hi @hoshikira18 please include more information, what is the exact error, stack traces, and so on. I will close the ticket as it doesn't seem to be a bug, please reach out on Discord if you need help with implementation.
