### ISSUE TITLE
Create Medusa app with nextjs storefront fails with invalid github url error

### ISSUE THREAD

**Issue by aadityadeshmukh** [medusajs/medusa#7363]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The create medusa app command fails when we select the nextjs storefront option. The error is as follows:
npx create-medusa-app@latest --db-url "xxxx"
Need to install the following packages:
create-medusa-app@1.2.8
Ok to proceed? (y) y
╔════════════════════════════════════════════════════════════════════════╗
║                                                                        ║
║   Medusa collects anonymous usage analytics                            ║
║   to help improve Medusa for all users.                                ║
║                                                                        ║
║   If you'd like to opt-out, you can use `medusa telemetry --disable`   ║
║                                                                        ║
║                                                                        ║
╚════════════════════════════════════════════════════════════════════════╝
? What's the name of your project? markone
? Enter an email for your admin dashboard user enigma@flash.co
? Would you like to create the Next.js storefront? You can also create it later Yes
🚀 Starting project setup, this may take a few minutes.
√ Created project directory
/ Installing Next.js Storefront...

┌────────────────────────────────────────────────── 💡 Medusa Tips ───────────────────────────────────────────────────┐
│                                                                                                                     │
│   An entity represents a table in the database. You can create a table by creating a custom entity and migration.   │
│                                                                                                                     │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
An error occurred while installing Next.js storefront: Error: Command failed: npx create-next-app -e https://github.com/medusajs/nextjs-starter-medusa markone-storefront
Found invalid GitHub URL: "https://github.com/medusajs/nextjs-starter-medusa". Please fix the URL and try again.

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Can you try running the nextjs command with the `@latest` tag to test it out:

```
npx create-next-app@latest -e https://github.com/medusajs/nextjs-starter-medusa markone-storefront
```

If that fixes it then we probably need to add it into the `create-medusa-app` command.

**Comment by shahednasser** [comment]
This issue has been addressed, but haven't been released yet. will close it for now.
