### ISSUE TITLE
Need to create custom module in admin panel

### ISSUE THREAD

**Issue by muthukumar199r** [medusajs/medusa#7414]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Need to create custom module in admin panel

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Hello, this issue lacks details so will close it for now. Feel free to re-open it with more details.
