### ISSUE TITLE
UI Docs Issue in the title & description of Alert component

### ISSUE THREAD

**Issue by Kingkon963** [medusajs/medusa#7432]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The title and description of the [Alert](https://docs.medusajs.com/ui/components/alert) component are currently referencing the Avatar component.

### How can this issue be resolved?

1. Updating the [alert.mdx](https://github.com/medusajs/medusa/blob/e3beaf5a2971a1125d7ee0cbc24e7d6589ff255b/www/apps/ui/src/content/docs/components/alert.mdx?plain=1#L2C1-L3C75) file

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for reporting this! please feel free to open a PR to fix it

**Comment by Kingkon963** [comment]
I've opened a [PR](https://github.com/medusajs/medusa/pull/7435) for this.

Please let me know if I can be of any further help.

Although this PR is brief, it is particularly special to me because it's my first contribution to an OSS project. 😊
