### ISSUE TITLE
Docs(Code Issue): Code Issue in /development/workflows

### ISSUE THREAD

**Issue by chiuwah** [medusajs/medusa#7449]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In the example code the MedusaRequest property `validatedQuery` is giving undefined here. As I could not find any documentation on `validatedQuery`, I assume it should be just `query`?

```javascript
import type {
  MedusaRequest,
  MedusaResponse,
} from "@medusajs/medusa"
import myWorkflow from "../../../workflows/hello-world"

export async function GET(
  req: MedusaRequest,
  res: MedusaResponse
) {
  const { result } = await myWorkflow(req.scope).run({
    input: {
      name: req.validatedQuery.name as string, // gives undefined
    },
  })

  res.send(result)
}
```

### How can this issue be resolved?

Change `req.validatedQuery.name` to `req.query.name`

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch! It should be `req.query.name`. Feel free to open a pull request to fix it.
