### ISSUE TITLE
Duplicate Identifier 'id' Error in Generated SDK

### ISSUE THREAD

**Issue by monikagorkhiya** [medusajs/medusa#7466]
### Describe the bug

When generating the SDK for the combined.oas.json file, an error occurs when running the application. The error message indicates a **Duplicate identifier 'id'** in two generated files:

- `src/test-cl1/services/AdminPriceListsService.ts`
- `src/test-cl1/services/AdminProductsService.ts`

#Steps to reproduce the behavior

## 1. Generate the SDK using the following command:

```
npm install openapi-typescript-codegen --save-dev
```
```

npx openapi --input ./build/oas/combined.oas.json --output ./src/test-cl1 --client fetch --name storeCl --useOptions
```
## 2. Run the application.

```
npm run dev
```

## 3. Encounter the following error
```
Duplicate identifier 'id'

```

### System information

Medusa version (including plugins):
      Medusa CLI version: 1.3.22 
      Medusa version: 1.20.6
Node.js version: 20.13.1
Database: postgres:14
Operating system: Linux

### Expected behavior

The SDK should be generated without any duplicate identifier errors, and the application should run successfully.

### Actual Behavior
The generated SDK contains duplicate identifiers in the following files, causing the application to fail:

- `src/test-cl1/services/AdminPriceListsService.ts`
![image](https://github.com/medusajs/medusa/assets/97655102/686ebb18-ad47-4c40-9f1b-f75177d045fa)

- `src/test-cl1/services/AdminProductsService.ts`
![image](https://github.com/medusajs/medusa/assets/97655102/c39bc234-f3a7-4a0c-a3df-459bf9a42eb7)

**Comment by SalahAdDin** [comment]
@monikagorkhiya Did you check whether it is solved or not?
