### ISSUE TITLE
bug: product export only exports first product in database

### ISSUE THREAD

**Issue by matmar10** [medusajs/medusa#7545]
### Describe the bug

When downloading products using the Export feature, only the first product is downloaded

### System information

Medusa version (including plugins): `"@medusajs/medusa": "^1.20.6",` | `"@medusajs/file-local": "^1.0.3",`
Node.js version: `10.12.2`
Database: Postgres 16
Operating system: Mac, Linux
Browser (if relevant): N/A

### Steps to reproduce the behavior

Prerequisite:
- Ensure directory structure exists (work around for Issue #7542)
- Ensure you have at least two published products in your store

1. Log In
2. Go to Products in admin
3. Click "Export Products"
4. Click notifications in top right
5. Wait for export to complete
6. Click download
11. Open file as raw text
12. Observe file contents, only one product is present

### Expected behavior

All products should be exported

### Additional context

Relates to  #6282 #7506 & #7542

**Comment by matmar10** [comment]
Still an issue.

**Comment by keyur-niq** [comment]
Is there any fix for it? I have to keep connecting to my prod db using local server to export and import.

**Comment by shahkeyur** [comment]
Is there any fix for it? I have to keep connecting to my prod db using local sever and disable the R2 file management to make it work.
