### ISSUE TITLE
Documentation: Medusa Subscription Stripe Plugin 404

### ISSUE THREAD

**Issue by DanielHirunrusme** [medusajs/medusa#7555]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

On this page: https://docs.medusajs.com/recipes/subscriptions

The link to Medusa's official Stripe Plugin for subscriptions is a 404 Github repo:
https://github.com/medusajs/medusa/tree/develop/packages/medusa-payment-stripe

Also here is a plugin someone created:
https://npm.io/package/medusa-stripe-subscription

I've found another related thread:
https://github.com/medusajs/medusa/discussions/1232

Starting this thread that is focused on this broken link in the documentation. 

### How can this issue be resolved?

1. Update link in documentation
2. Make official plugin public

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for reporting this! It's because the plugin has been moved to the `v1.x` branch of this repository. I'll open a PR to fix this.

**Comment by DanielHirunrusme** [comment]
Sure thing! Thank you. As a possible addition to the documentation here, are there any official examples/recipes for creating a subscription product? It would be super helpful to see how to create this using Medusa

**Comment by shahednasser** [comment]
Unfortunately we don't have any specific examples for that as it depends on your use case.
