### ISSUE TITLE
Unable to install medusa js from local path for local backen development

### ISSUE THREAD

**Issue by oakbani** [medusajs/medusa#7565]
Here is the error that I see when I try to run my local instance. 

> > medusa-starter-default@0.0.1 start
> cross-env npm run build && medusa start

> medusa-starter-default@0.0.1 build
> cross-env npm run clean && npm run build:server && npm run build:admin

> medusa-starter-default@0.0.1 clean
> cross-env ./node_modules/.bin/rimraf dist

> medusa-starter-default@0.0.1 build:server
> cross-env npm run clean && tsc -p tsconfig.server.json

> medusa-starter-default@0.0.1 clean
> cross-env ./node_modules/.bin/rimraf dist

src/api/admin/onboarding/route.ts:22:8 - error TS2339: Property 'withTransaction' does not exist on type 'OnboardingService'.

22       .withTransaction(transactionManager)
          ~~~~~~~~~~~~~~~

src/models/onboarding.ts:1:10 - error TS2305: Module '"@medusajs/medusa"' has no exported member 'BaseEntity'.

1 import { BaseEntity } from "@medusajs/medusa";
           ~~~~~~~~~~

src/repositories/onboarding.ts:1:28 - error TS2307: Cannot find module '@medusajs/medusa/dist/loaders/database' or its corresponding type declarations.

1 import { dataSource } from "@medusajs/medusa/dist/loaders/database";
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/services/onboarding.ts:1:10 - error TS2305: Module '"@medusajs/medusa"' has no exported member 'TransactionBaseService'.

1 import { TransactionBaseService } from "@medusajs/medusa";
           ~~~~~~~~~~~~~~~~~~~~~~

src/services/onboarding.ts:22:33 - error TS2339: Property 'activeManager_' does not exist on type 'OnboardingService'.

22     const onboardingRepo = this.activeManager_.withRepository(
                                   ~~~~~~~~~~~~~~

src/services/onboarding.ts:34:23 - error TS2339: Property 'atomicPhase_' does not exist on type 'OnboardingService'.

34     return await this.atomicPhase_(
                         ~~~~~~~~~~~~


Found 6 errors in 4 files.

Errors  Files
     1  src/api/admin/onboarding/route.ts:22
     1  src/models/onboarding.ts:1
     1  src/repositories/onboarding.ts:1
     3  src/services/onboarding.ts:1

**Comment by albertomenen** [comment]
Im experiencing the same problem and dont know how to solve it

**Comment by sradevski** [comment]
Can you please try again with the latest version, this shouldn't be an issue. Thanks!
