### ISSUE TITLE
[ADMIN] - sync url filter params

### ISSUE THREAD

**Issue by raukaute** [medusajs/medusa#7568]
## Bug report

Set filters are not synced upon refresh. 

### Describe the bug

When I set filters, e.g. on order list page, they are synced to the url as query params. However, when I refresh the browser, all filters are unset. Works only for pagination params.

### System information

Medusa version (including plugins): 1.18.1, admin: 7.1.8

### Steps to reproduce the behavior

See above.

### Expected behavior

Url query params should set filter when page loads.

**Comment by SalahAdDin** [comment]
@raukaute was it fixed?
