### ISSUE TITLE
Can't Edit or Create Prices

### ISSUE THREAD

**Issue by ckizer** [medusajs/medusa#7570]
![CleanShot 2024-05-31 at 12 38 59@2x](https://github.com/medusajs/medusa/assets/191738/3c9601de-5d83-463f-8344-bc4fa3303aa7)

Even trying the view options, I cannot enter any prices. Here's a video of the entire process:
https://share.cleanshot.com/tqJTzy9w

**Comment by kasperkristensen** [comment]
Hey @ckizer 

Looks like your product does not have any variants. Prices are stored on Variants in Medusa, and not directly on the product. So in order to create prices or in this case price list prices, you first need to create at least one variant for the product.

**Comment by kasperkristensen** [comment]
Closing this, as it seems to be due to missing variants. Feel free to re-open if that is not the case 😄
