### ISSUE TITLE
Unable to run storefront in production because of build errors 

### ISSUE THREAD

**Issue by AwaaX** [medusajs/medusa#7571]
### Preliminary Checks

- [ ] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I get type error "Type error: Unused '@ts-expect-error' directive." when trying to run build so i can't use storefront in production mode

### How can this issue be resolved?

No idea

### Are you interested in working on this issue? Sorry I'm not a developer I am a e-commerce company holder testing medusa

- [ ] I would like to fix this issue

**Comment by sradevski** [comment]
@AwaaX I can build the project without issues. Can you please provide more information to reproduce the issue from a clean clone? What command did you run? Are you running `main`? What is your node/yarn version?

What are you trying to run, the [starter](https://github.com/medusajs/nextjs-starter-medusa) project?

**Comment by matmar10** [comment]
@sradevski  I am also facing this issue with a completely clean (out of the box) install. 

I have created a clean install that replicates the issue here: [matmar10/medusa-storefront](https://github.com/matmar10/medusa-storefront)

## Steps to reproduce:

This is using Node `v20.12.2`

1. `npx create-next-app -e https://github.com/medusajs/nextjs-starter-medusa my-medusa-storefront`
2. `cd my-medusa-storefront`
3. `npm run build`

## Expected behavior:

1. Project builds okay out of the box -or-
2. Removing the `@ts-expect-error` allows to build

## Actual behavior

```Bash
./src/modules/products/components/product-tabs/accordion.tsx:57:8
Type error: Unused '@ts-expect-error' directive.

  55 |       )}
  56 |     >
> 57 |       {/* @ts-expect-error */}
     |        ^
  58 |       <AccordionPrimitive.Header className="px-1">
  59 |         <div className="flex flex-col">
  60 |           <div className="flex w-full items-center justify-between">
```

![Screenshot 2024-06-12 at 2 53 11 PM](https://github.com/medusajs/medusa/assets/19975/e9b3fdee-e9ab-4c73-a7d6-1ce6008a5dd5)

## Work-Around / Fix

You can resolve the issue by leaving the first `@ts-expect-error` and removing the remaining ones:

```diff
diff --git a/src/modules/products/components/product-tabs/accordion.tsx b/src/modules/products/components/product-tabs/accordion.tsx
index db8855a..03d837a 100644
--- a/src/modules/products/components/product-tabs/accordion.tsx
+++ b/src/modules/products/components/product-tabs/accordion.tsx
@@ -54,14 +54,12 @@ const Item: React.FC<AccordionItemProps> = ({
         className
       )}
     >
-      {/* @ts-expect-error */}
       <AccordionPrimitive.Header className="px-1">
         <div className="flex flex-col">
           <div className="flex w-full items-center justify-between">
             <div className="flex items-center gap-4">
               <Text className="text-ui-fg-subtle text-sm">{title}</Text>
             </div>
-            {/* @ts-expect-error */}
             <AccordionPrimitive.Trigger>
               {customTrigger || <MorphingTrigger />}
             </AccordionPrimitive.Trigger>
@@ -73,7 +71,6 @@ const Item: React.FC<AccordionItemProps> = ({
           )}
         </div>
       </AccordionPrimitive.Header>
-      {/* @ts-expect-error */}
       <AccordionPrimitive.Content
         forceMount={forceMountContent}
         className={clx(
```

**Comment by andresrivero** [comment]
I had this error as well with npm, I tried the fix above but got a different error - tried adding @medusajs/types but no luck.

I deleted my .node-modules and then used yarn, yarn dev, and yarn build - it ran successfully and built the next app

**Comment by santiblanko** [comment]
same here with node 20

**Comment by AwaaX** [comment]
> @AwaaX I can build the project without issues. Can you please provide more information to reproduce the issue from a clean clone? What command did you run? Are you running `main`? What is your node/yarn version?
> 
> What are you trying to run, the [starter](https://github.com/medusajs/nextjs-starter-medusa) project?

I do `npx create-next-app -e https://github.com/medusajs/nextjs-starter-medusa my-medusa-storefront`
then `npm run build`

```
node -v
v20.15.1

```
```
npm -v
10.7.0
```

> @sradevski I am also facing this issue with a completely clean (out of the box) install.
> 
> I have created a clean install that replicates the issue here: [matmar10/medusa-storefront](https://github.com/matmar10/medusa-storefront)
> ## Steps to reproduce:
> 
> This is using Node `v20.12.2`
> 
>     1. `npx create-next-app -e https://github.com/medusajs/nextjs-starter-medusa my-medusa-storefront`
> 
>     2. `cd my-medusa-storefront`
> 
>     3. `npm run build`
> 
> 
> ## Expected behavior:
> 
>     1. Project builds okay out of the box -or-
> 
>     2. Removing the `@ts-expect-error` allows to build
> 
> 
> ## Actual behavior
> 
> ```shell
> ./src/modules/products/components/product-tabs/accordion.tsx:57:8
> Type error: Unused '@ts-expect-error' directive.
> 
>   55 |       )}
>   56 |     >
> > 57 |       {/* @ts-expect-error */}
>      |        ^
>   58 |       <AccordionPrimitive.Header className="px-1">
>   59 |         <div className="flex flex-col">
>   60 |           <div className="flex w-full items-center justify-between">
> ```
> 
> ![Screenshot 2024-06-12 at 2 53 11 PM](https://private-user-images.githubusercontent.com/19975/338872722-e9b3fdee-e9ab-4c73-a7d6-1ce6008a5dd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NTA5NDcsIm5iZiI6MTcyMTc1MDY0NywicGF0aCI6Ii8xOTk3NS8zMzg4NzI3MjItZTliM2ZkZWUtZTlhYi00YzczLWE3ZDYtMWNlNjAwOGE1ZGQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDE2MDQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0NmFkNzNiYTgyYWNmNTk1NjA3MjI2MDZkNTIxNGFjMzg2YmM2ZGFhNTdiMmJlYzNlZjQ3ZDljYzRlYmNmNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gkng3nL970Hre_MUPD0CDUKgnABPvfVUgzKK5n_OVxU)
> ## Work-Around / Fix
> 
> You can resolve the issue by leaving the first `@ts-expect-error` and removing the remaining ones:
> 
> ```diff
> diff --git a/src/modules/products/components/product-tabs/accordion.tsx b/src/modules/products/components/product-tabs/accordion.tsx
> index db8855a..03d837a 100644
> --- a/src/modules/products/components/product-tabs/accordion.tsx
> +++ b/src/modules/products/components/product-tabs/accordion.tsx
> @@ -54,14 +54,12 @@ const Item: React.FC<AccordionItemProps> = ({
>          className
>        )}
>      >
> -      {/* @ts-expect-error */}
>        <AccordionPrimitive.Header className="px-1">
>          <div className="flex flex-col">
>            <div className="flex w-full items-center justify-between">
>              <div className="flex items-center gap-4">
>                <Text className="text-ui-fg-subtle text-sm">{title}</Text>
>              </div>
> -            {/* @ts-expect-error */}
>              <AccordionPrimitive.Trigger>
>                {customTrigger || <MorphingTrigger />}
>              </AccordionPrimitive.Trigger>
> @@ -73,7 +71,6 @@ const Item: React.FC<AccordionItemProps> = ({
>            )}
>          </div>
>        </AccordionPrimitive.Header>
> -      {/* @ts-expect-error */}
>        <AccordionPrimitive.Content
>          forceMount={forceMountContent}
>          className={clx(
> ```

Thanks, you should edit : Keep the two firsts: one line 30 , one line 48 **

after it work

**Comment by AwaaX** [comment]
> @sradevski I am also facing this issue with a completely clean (out of the box) install.
> 
> I have created a clean install that replicates the issue here: [matmar10/medusa-storefront](https://github.com/matmar10/medusa-storefront)
> ## Steps to reproduce:
> 
> This is using Node `v20.12.2`
> 
>     1. `npx create-next-app -e https://github.com/medusajs/nextjs-starter-medusa my-medusa-storefront`
> 
>     2. `cd my-medusa-storefront`
> 
>     3. `npm run build`
> 
> 
> ## Expected behavior:
> 
>     1. Project builds okay out of the box -or-
> 
>     2. Removing the `@ts-expect-error` allows to build
> 
> 
> ## Actual behavior
> 
> ```shell
> ./src/modules/products/components/product-tabs/accordion.tsx:57:8
> Type error: Unused '@ts-expect-error' directive.
> 
>   55 |       )}
>   56 |     >
> > 57 |       {/* @ts-expect-error */}
>      |        ^
>   58 |       <AccordionPrimitive.Header className="px-1">
>   59 |         <div className="flex flex-col">
>   60 |           <div className="flex w-full items-center justify-between">
> ```
> 
> ![Screenshot 2024-06-12 at 2 53 11 PM](https://private-user-images.githubusercontent.com/19975/338872722-e9b3fdee-e9ab-4c73-a7d6-1ce6008a5dd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NTA5NDcsIm5iZiI6MTcyMTc1MDY0NywicGF0aCI6Ii8xOTk3NS8zMzg4NzI3MjItZTliM2ZkZWUtZTlhYi00YzczLWE3ZDYtMWNlNjAwOGE1ZGQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDE2MDQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0NmFkNzNiYTgyYWNmNTk1NjA3MjI2MDZkNTIxNGFjMzg2YmM2ZGFhNTdiMmJlYzNlZjQ3ZDljYzRlYmNmNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gkng3nL970Hre_MUPD0CDUKgnABPvfVUgzKK5n_OVxU)
> ## Work-Around / Fix
> 
> You can resolve the issue by leaving the first `@ts-expect-error` and removing the remaining ones:
> 
> ```diff
> diff --git a/src/modules/products/components/product-tabs/accordion.tsx b/src/modules/products/components/product-tabs/accordion.tsx
> index db8855a..03d837a 100644
> --- a/src/modules/products/components/product-tabs/accordion.tsx
> +++ b/src/modules/products/components/product-tabs/accordion.tsx
> @@ -54,14 +54,12 @@ const Item: React.FC<AccordionItemProps> = ({
>          className
>        )}
>      >
> -      {/* @ts-expect-error */}
>        <AccordionPrimitive.Header className="px-1">
>          <div className="flex flex-col">
>            <div className="flex w-full items-center justify-between">
>              <div className="flex items-center gap-4">
>                <Text className="text-ui-fg-subtle text-sm">{title}</Text>
>              </div>
> -            {/* @ts-expect-error */}
>              <AccordionPrimitive.Trigger>
>                {customTrigger || <MorphingTrigger />}
>              </AccordionPrimitive.Trigger>
> @@ -73,7 +71,6 @@ const Item: React.FC<AccordionItemProps> = ({
>            )}
>          </div>
>        </AccordionPrimitive.Header>
> -      {/* @ts-expect-error */}
>        <AccordionPrimitive.Content
>          forceMount={forceMountContent}
>          className={clx(
> ```

Thanks, you should edit : Keep the two firsts: one line 30 , one line 48 **

after it work

**Comment by zaheerahmad33** [comment]
same here with node 18.20.4
