### ISSUE TITLE
API Reference Docs: Customer response appears incomplete

### ISSUE THREAD

**Issue by jaredhill4** [medusajs/medusa#764]
There are various places where the API reference documentation seems to be incomplete.

For example, when looking at the example response in the screenshot below, it appears to be missing fields from the `Customer` model, particularly:

- `billing_address`
- `shipping_addresses`

<img width="1792" alt="Screen Shot 2021-11-09 at 3 02 05 PM" src="https://user-images.githubusercontent.com/7476478/141005243-03f276fc-09ea-44bc-a1cb-4b5eb5c39b9b.png">

This is the case with many of the example responses related to `Customer`.

**Comment by srindom** [comment]
Hi Jared! 

Thanks for flagging this - we are working on making all the small response examples in the reference docs more true to how they actually work. The first step has been to do it for all GET endpoints, but we plan to do it for every endpoint in Medusa. Until that is done there might be a couple of inconsistencies between the response example and what actually gets sent back.

**Comment by tiendq** [comment]
> Hi Jared!
> 
> Thanks for flagging this - we are working on making all the small response examples in the reference docs more true to how they actually work. The first step has been to do it for all GET endpoints, but we plan to do it for every endpoint in Medusa. Until that is done there might be a couple of inconsistencies between the response example and what actually gets sent back.

Hi,

Regarding shipping address, I don't see how to create a new address, "Add a Shipping address" here needs an `id`, while `id` should be auto generated, isn't it?

**Comment by olivermrbl** [comment]
Hey @tiendq. I see, that our API reference is a bit outdated. Will make sure to it up-to-speed as soon as possible. 

We recently updated our API layer (converted it to Typescript), and you should be able to add a shipping address with [this endpoint](https://github.com/medusajs/medusa/blob/master/packages/medusa/src/api/routes/store/customers/create-address.ts). Alternatively, addresses can only be [added directly to a cart](https://github.com/medusajs/medusa/blob/master/packages/medusa/src/api/routes/store/carts/update-cart.ts).

Let me know if this was what you were looking for :)

**Comment by tiendq** [comment]
> Hey @tiendq. I see, that our API reference is a bit outdated. Will make sure to it up-to-speed as soon as possible.
> 
> We recently updated our API layer (converted it to Typescript), and you should be able to add a shipping address with [this endpoint](https://github.com/medusajs/medusa/blob/master/packages/medusa/src/api/routes/store/customers/create-address.ts). Alternatively, addresses can only be [added directly to a cart](https://github.com/medusajs/medusa/blob/master/packages/medusa/src/api/routes/store/carts/update-cart.ts).
> 
> Let me know if this was what you were looking for :)

Thanks for your information but unfortunately it isn't what I'm looking for, it looks like Medusa has no function for migration from other stores (while I think it should). If it only allows me to add a shipping address directly with a cart by `me` requests so how can I add a bulk of existing customers from other databases which need requests start with `/admin`?

**Comment by jaredhill4** [comment]
@olivermrbl and @tiendq,

We had the same issue with not being able to add/update/delete a shipping address for a customer by id, since there is currently only a client endpoint, and not an admin endpoint.

I'm currently in the process of setting up three custom `/admin` endpoints that mirror the client endpoint, but allow you to pass the `customer_id` as a URL parameter. This will allow use to manage a user's shipping addresses via the admin.

My code for this is almost an exact copy of the methods used for the client endpoint, except it gets the `customer_id` from the `req.params.id`.

Here is a copy of that code:

```
import {
  defaultStoreCustomersFields,
  defaultStoreCustomersRelations
} from '@medusajs/medusa/dist/api/routes/store/customers';
import { validator } from '@medusajs/medusa/dist/utils/validator';
import { Type } from 'class-transformer';
import { IsString, IsObject, IsOptional, IsNotEmpty, ValidateNested } from 'class-validator';

export const addCustomerAddress = async (req, res) => {
  const { id } = req.params;

  const validated = await validator(StorePostCustomersCustomerAddressesReq, req.body);

  const customerService = req.scope.resolve('customerService');

  let customer = await customerService.addAddress(id, validated.address);
  customer = await customerService.retrieve(id, {
    relations: defaultStoreCustomersRelations,
    select: defaultStoreCustomersFields
  });

  res.status(200).json({ customer });
};

export const updateCustomerAddress = async (req, res) => {
  const { id, address_id } = req.params;

  const validated = await validator(StorePostCustomersCustomerAddressesAddressReq, req.body);

  const customerService = req.scope.resolve('customerService');

  let customer = await customerService.updateAddress(id, address_id, validated);

  customer = await customerService.retrieve(id, {
    relations: defaultStoreCustomersRelations,
    select: defaultStoreCustomersFields
  });

  res.json({ customer });
};

export const deleteCustomerAddress = async (req, res) => {
  const { id, address_id } = req.params;

  const customerService = req.scope.resolve('customerService');

  await customerService.removeAddress(id, address_id);

  const customer = await customerService.retrieve(id, {
    relations: defaultStoreCustomersRelations,
    select: defaultStoreCustomersFields
  });

  res.json({ customer });
};

class StorePostCustomersCustomerAddressesReq {
  @ValidateNested()
  @Type(() => AddressCreatePayload)
  @IsNotEmpty()
  address;
}

class AddressCreatePayload {
  @IsString()
  first_name;

  @IsString()
  last_name;

  @IsString()
  @IsOptional()
  phone;

  @IsObject()
  @IsOptional()
  metadata = {};

  @IsString()
  @IsOptional()
  company;

  @IsString()
  address_1;

  @IsString()
  @IsOptional()
  address_2;

  @IsString()
  city;

  @IsString()
  country_code;

  @IsString()
  province;

  @IsString()
  postal_code;
}
```

**Comment by jaredhill4** [comment]
@olivermrbl perhaps we should consider adding `/admin` endpoints like this to manage the customer shipping addresses to the `medusa` core?

**Comment by tiendq** [comment]
@jaredhill4 

Thank you, I believe that if anyone want to use Medusa seriously - I mean in a real store - will need to do many customizations like yours. It's still immature, both features and documentation. I was quite surprised to not be able to print an order/invoice etc., who can manage a real store without printing capability? :)
