### ISSUE TITLE
Paypal not updating correct price 

### ISSUE THREAD

**Issue by khalilxg** [medusajs/medusa#7641]
stack: medusajs latest: + medusajs nextjs + medusajs postgres

scenario:

user not loged in or even loged in same scenario
purchase a product with 5$
he continue to checkout, fill-in the form, selects paypal, click on paypal, not continue to payement he exit,
go back to purchase more products with 300$ 
back to purchase and payement
paypal popup shows that he'll only pay 5$ continue to payement, validate, ok,
the order page successfully apear showing that the total is 305$

/// at user paypal account he only get -5$
/// at admin dashboard the user pay 305$
/// at database table payment the user payed 305$
/// at database table payment_session amout is 305$

conclusion: user not getting to pay latest total update

**Comment by khalilxg** [comment]
heeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeelp

**Comment by twietobiii** [comment]
Sounds like the same problem as this [Issue](https://github.com/medusajs/medusa/issues/7097)

**Comment by khalilxg** [comment]
any update on this bug ?????,,,,,,,,,,,,,,,,
