### ISSUE TITLE
Fetch failed upon server restart 

### ISSUE THREAD

**Issue by northrn** [medusajs/medusa#7656]
Medusa version (including plugins): 1.03
Node.js version: 20.13.1

I am receiving this error when attempting to start my development server on a new Medusa project. I have not touched the code at all. The server starts successfully but as soon as the page tries to load in my browser, I receive the error seen below:

<img width="906" alt="Screenshot 2024-06-08 at 7 35 34 PM" src="https://github.com/medusajs/medusa/assets/44729398/67e1fed9-43d8-4830-94fe-0b7215210f0a">

Not sure what is causing this or how to address it considering this is code that came with the project. I first installed this project about 2.5 weeks ago. The backend dashboard was working fine.

**Comment by 0mykull** [comment]
Try running admin dashboard server then storefront server at the same time, it worked for me.

**Comment by sradevski** [comment]
Likely the backend isn't reachable when the storefront starts up, as the other comment suggests. Closing
