### ISSUE TITLE
 i have enabled product categories in medusa when i tried to create ,update and delete categories operations it is giving me the cors issue when i tried in postman it works fine . if these api's are getting cors issue then i can get cors issue for other apis also it won't be like that.can you please guide me 

### ISSUE THREAD

**Issue by underlineit-dev-5** [medusajs/medusa#7669]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

My apis are working fine in postman but didn't worked in UI its urgent for me please fix
![Screenshot (542)](https://github.com/medusajs/medusa/assets/104749172/e04aa2fb-2b48-4318-9c43-9a3a7df6183e)

### How can this issue be resolved?

1.enable product categories
2.create product category, then you will see the issue
3
...

### Are you interested in working on this issue?

- [x] I would like to fix this issue

**Comment by sradevski** [comment]
Please have a look at https://docs.medusajs.com/troubleshooting/cors-issues, it works in Postman since postman doesn't care about CORS.
