### ISSUE TITLE
Error parsing output of "yarn workspaces info" command in medusa-dev

### ISSUE THREAD

**Issue by MEClouds** [medusajs/medusa#7683]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

**Issue Title:**
Error parsing output of "yarn workspaces info" command in medusa-dev

**Description:**
When attempting to run `medusa-dev` after setting up my Medusa project according to the instructions, I encountered an error related to parsing the output of the `yarn workspaces info` command. This issue prevents me from proceeding with the development environment setup.

**Steps to Reproduce:**
1. Fork the Medusa repository.
2. Install dependencies using `yarn install`.
3. Build the project using `yarn build`.
4. Set the location of the Medusa repository.
5. Run `medusa-dev` command.

**Expected Behavior:**
The `medusa-dev` command should run successfully and set up the development environment without any errors.

**Actual Behavior:**
The following error occurs:

```
Failed to parse "sanitized" output of "yarn workspaces info" command.

Sanitized string: "{"location":".","name":"root"}
{"location":"integration-tests/api","name":"integration-tests-api"}
{"location":"integration-tests/http","name":"integration-tests-http"}
{"location":"integration-tests/modules","name":"integration-tests-modules"}
....
```

**Environment:**
- Operating System: windows 11
- Node.js Version: 20
- Yarn Version: 3.2.1
- Medusa-dev-cli Version: 0.0.32

**Additional Information:**
- I have verified that my Yarn version (3.2.1) is compatible with Medusa.
- Double-checked workspace configuration in `package.json` file and found no syntax errors.
- All project dependencies, including Medusa and related packages, are up-to-date.
- Environment variables are correctly set up.
- Debugging output did not provide additional insights into the root cause of the issue.

**Screenshot(s):**
![image](https://github.com/medusajs/medusa/assets/84941140/1b47ca23-fa32-4f43-a20d-46b60a93a225)

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by cherrynik** [comment]
Referring to the [docs](https://docs.medusajs.com/development/fundamentals/local-development#medusas-dev-cli-tool):

Switch yarn to v1:
```sh
yarn set version classic
```

(Re-)install packages by running:
```sh
yarn install
```

Run:
```sh
medusa-dev
```

_It might seem as terminal gets stuck at `glob 9`, it's not. Simply click `Enter`, installation will proceed._

Done.
