### ISSUE TITLE
Cart Items not showing in production

### ISSUE THREAD

**Issue by aftabhussain6** [medusajs/medusa#7689]
### Environment

- **Medusa version:** 1.20.7
- **Node.js version:** v20.12.2
- **EC2 instance type:** linux

### Description

I am experiencing an issue with my storefront build on an EC2 instance. When I add products to the cart, they are added successfully, but the cart does not display any items when viewed. This issue does not occur when I build and run the storefront locally.

### Steps to Reproduce

1. **Add products to the cart:**
   - Navigate to a product page
   - Click on "Add to Cart"
   - Confirm that the product is added successfully (e.g., a success message or cart icon updates)

2. **View the cart:**
   - Navigate to the cart page
   - Observe that the cart is empty

### Expected Behavior

The cart should display the products that were added.

### Actual Behavior

The cart does not display any products even though they were added successfully.

### Additional Context

- This issue only occurs on the EC2 deployment. When running the build locally, the cart functions correctly.
- I have ensured that the backend is properly connected and accessible from the EC2 instance.
- There are no errors or warnings in the browser console or server logs related to the cart functionality.

**Comment by humbleEwan** [comment]
This only happened to me if I had 0 in stock for that item. If that's not the case I would check out the DB and see what's in the cart (or what is not, or is there a cart at all) and work from there
