### ISSUE TITLE
CollectionsResource does not return products

### ISSUE THREAD

**Issue by qimolin** [medusajs/medusa#7735]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In the documentation [JavaScript client](https://docs.medusajs.com/references/js-client/CollectionsResource) & [Medusa React](https://docs.medusajs.com/references/medusa-react/hooks/store/product_collections), it looks like products get returned when using the collections endpoint. This is however not the case as I saw in #4264 and #4647.

### How can this issue be resolved?

1. Remove products from collections response in both clients
2. Update corresponding documentation

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for reporting this @qimolin , will open a PR to fix this
