### ISSUE TITLE
B2B and next 14

### ISSUE THREAD

**Issue by hrohwer** [medusajs/medusa#7737]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

 hi guys this recipe no longer seems to work, I'm wondering if it has something to do with the next 14 update?

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Hi @hrohwer can you provide more details on the issue?

**Comment by hrohwer** [comment]
Sure, if I follow the following recipe it no longer works.

https://docs.medusajs.com/recipes/b2b

My assumption is that it is due to the upgrade to next 14 separating server and client side components? But I am still learning.

The idea is to show VAT incl for B2C and vat excl B2B

**Comment by shahednasser** [comment]
The recipe has code snippets for the Medusa backend, not Next.js

**Comment by hrohwer** [comment]
ok, however it implements the frontend usage of a B2B meta flag which can not be accessed? 
excuse my ignorance however ....In short for some reason the recipe does not work if I follow it to the point.

**Comment by shahednasser** [comment]
Do you mean the code black in the example of [this section](https://docs.medusajs.com/recipes/b2b#create-an-api-route-to-check-customers)? If not please point me to the exact place that's not working

**Comment by hrohwer** [comment]
this part https://medusajs.com/blog/medusa-b2b-part-2/

**Comment by shahednasser** [comment]
Unfortunately, we don't keep blog posts updated. You can follow the steps to get a general idea of the changes you need to make in the storefront, but there's no plan on making updates at the moment.

Will close this issue.
