### ISSUE TITLE
Install nextjs-started-medusa

### ISSUE THREAD

**Issue by Staxar** [medusajs/medusa#7750]
### Describe the bug

Hey!
Facing with problem today with medusa js installation

### System information

Medusa version (including plugins):
Node.js version: v20.11.1
Database: postgres
Operating system: w10
Terminal: powershell

### Steps to reproduce the behavior

PS D:\Projects\ecommerce> npx create-medusa-app@latest --db-url "my-db-url" --seed --with-nextjs-starter
? What's the name of your project? my-medusa-store
? Enter an email for your admin dashboard user admin@medusa-test.com
🚀 Starting project setup, this may take a few minutes.
✔ Created project directory
⠹ Installing Next.js Storefront...

   ┌────────────────────────────────────────────────── 💡 Medusa Tips ──────────────────────────────────────────────────┐
   │                                                                                                                    │
   │   Medusa provides multi-currency and region support, with full control over prices for each currency and region.   │
   │                                                                                                                    │
   └────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
An error occurred while installing Next.js storefront: Error: Command failed: npx create-next-app -e https://github.com/medusajs/nextjs-starter-medusa my-medusa-store-storefront
Found invalid GitHub URL: "https://github.com/medusajs/nextjs-starter-medusa". Please fix the URL and try again.

On bash is working

**Comment by shahednasser** [comment]
Thanks fo reporting this! Seems like the installation isn't using the latest `create-next-app` command. Will open a PR to fix it

**Comment by navadeep-munjam** [comment]
npx create-next-app@latest -e https://github.com/medusajs/nextjs-starter-medusa my-medusa-store-storefront
Use this

**Comment by shahednasser** [comment]
This issue should be fixed, will close it. Feel free to re-open it if necessary
