### ISSUE TITLE
Admin REST API only allows for integer pricing value

### ISSUE THREAD

**Issue by NiekSulter** [medusajs/medusa#7754]
### Describe the bug

When using the Admin REST API to create or update a product variant, setting the price is only allowed as an integer. Updating the price manually through the Admin UI I'm able to set the price as a float.

This also occurs for the Price Lists 

### System information

Medusa version (including plugins): 1.20.6
Node.js version: 20.11.1
Database: Postgres 16
Operating system:
Browser (if relevant):

### Steps to reproduce the behavior

1. HTTP test client
2. Create a product using `<ADMIN_URL>/admin/products`
3. See error

### Expected behavior

Product is created with the correct price of 10.99

### Code snippets

- Request body:
```
{
    "title": "My Test Product",
    "variants": [
        {
            "title": "default",
            "prices": [
                {
                    "amount": 10.99,
                    "currency_code": "eur"
                }
            ]
        }
    ]
}
```

- Response:
`{
    "type": "invalid_data",
    "message": "amount must be an integer number"
}`

**Comment by colinpieper** [comment]
This is intentional to avoid floating-point errors. €10.99 should be set as `"amount": 1099`. Multiply the amount by 100 and round to whole numbers.

**Comment by kasperkristensen** [comment]
Hey @NiekSulter,

@colinpieper is correct that in V1 the API expects the price value in a "cents" format. So for currencies that have to decimals like USD or EUR, a price of $10.95 should be sent to the API as `{ amount: 1095 }`. On your storefront you need to convert this back to human-readable value, so to display a USD price in your storefront your would do `price / 100`.
