### ISSUE TITLE
Docs(Code Issue): Code Issue in /development/plugins/create

### ISSUE THREAD

**Issue by NicolasGorga** [medusajs/medusa#7755]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In the package.json snippet found after: `This is the configuration that will be used when transpiling your admin code.

Finally, update the build scripts in your project and add a new prepare command:` I think the "build:server" script is wrong.

### How can this issue be resolved?

1. Replace "build:server": "cross-env npm run clean && tsc -p tsconfig.json" for "build:server": "cross-env npm run clean && tsc -p tsconfig.server.json"

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch! Feel free to open a PR to fix it.
