### ISSUE TITLE
Product variant set price

### ISSUE THREAD

**Issue by BorisKamp** [medusajs/medusa#7780]
Hi! Using Medusa `1.20.6`, Im creating a new product variant trough the admin interface (`{{host}}/app/a/products/prod_01H1PXK75VHYQ9KHGBXZFW4PE2`)) but Im unable to set a price for the variant. If I remember correctly, back in the days you could set the price trough the admin UI. Now you only seem to be able to do this by calling the update product variant endpoint `/admin/products/{id}/variants/{variant/id}` and sending a `prices` array?

Am I missing something here?

**Comment by kasperkristensen** [comment]
Hey @BorisKamp,

In the current admin, you can't set prices while creating a product, you do it afterwards. Once the product is created, you then hit "Edit prices" on the "Variants" card.

<img width="885" alt="image" src="https://github.com/medusajs/medusa/assets/45367945/2e985aed-b6f1-4a14-8297-28fb0686dcb7">
