### ISSUE TITLE
API Ref(store): Issue in Request Password Reset

### ISSUE THREAD

**Issue by ank-2222** [medusajs/medusa#7802]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

![image](https://github.com/medusajs/medusa/assets/76547947/00d39a56-233e-42a8-be5c-a2802177a942)

- Error tag should be replaced with success tag
- Order of "Request password reset" and "Reset password" is exchanged which can be seen from documentation description of "request password reset"

### How can this issue be resolved?

1. Need to change tag 
2. Need to change the order 

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
No need to change the order of API routes (as they're displayed in alphabetical order), but nice catch on the error tag!

To fix the tag, we need to change the condition [here](https://github.com/medusajs/medusa/blob/16669ce53d2c32bf1aeec90df7550e8b8bff71ec/www/apps/api-reference/components/Tags/Operation/DescriptionSection/Responses/index.tsx#L25) to instead check that the status code begins with `20`. Can you open a PR with this fix?

**Comment by ank-2222** [comment]
Yes sure, I will create a PR for this.

**Comment by ank-2222** [comment]
[pull Request for this Fix](https://github.com/medusajs/medusa/pull/7813)

**Comment by ank-2222** [comment]
@shahednasser [New Pr](https://github.com/medusajs/medusa/pull/7817) on v1.x
