### ISSUE TITLE
Error build admin ui

### ISSUE THREAD

**Issue by magereact** [medusajs/medusa#7825]
Hi Guys,

I'm using Node version 18 on MacOS Monterey 12.7.5.
I simply used the command `npx create-medusa-app@latest --db-url my-postgressql-url`.
It runs the commands and connects to the db success, but when the admin build process gets some errors.
Can you help me?
![image](https://github.com/medusajs/medusa/assets/68157281/ebed167d-6688-4ea8-ad0c-36ff421ec869)
![image](https://github.com/medusajs/medusa/assets/68157281/340739cd-a86d-4759-bed1-5734ecd81041)
![image](https://github.com/medusajs/medusa/assets/68157281/1e2f00dd-093f-44b9-a310-3dafa2c2856b)
![image](https://github.com/medusajs/medusa/assets/68157281/bc293e43-9c9b-4ecc-92b9-e45a91f359b3)

Thanks

**Comment by sradevski** [comment]
Can you please try with node 20 and a fresh installation? This doesn't seem like it should cause issues, and I cannot reproduce it.
