### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by fakecode0** [medusajs/medusa#7830]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In https://medusajs.com/blog/announcing-multi-language-support/ display a URL https://docs.medusajs.com/contribution/admin-translations, but the URL display Page Not Found

### How can this issue be resolved?

1.Delete the blog or give a page to teach how to add a new language in MedusaJs Admin

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for reporting this! We've removed the link from the blog post now.
