### ISSUE TITLE
Not Found Product Collection Events

### ISSUE THREAD

**Issue by fakecode0** [medusajs/medusa#7841]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

How to get Product Collection Events descriptions?

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Hello, you can find all product collection events here: https://docs.medusajs.com/development/events/events-list#payment-collection-events

will close this issue for now, feel free to re-open for any other help needed.
