### ISSUE TITLE
Docs(Code Issue): Code Issue in /modules/carts-and-checkout/backend/add-payment-provider

### ISSUE THREAD

**Issue by WCarlW** [medusajs/medusa#7865]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The names of import packages are different from the names used in the code below. 

### How can this issue be resolved?

1. Change `PaymentContext` to `PaymentProcessorContext`
2. Change `PaymentSessionResponse` to `PaymentProcessorSessionResponse`
3.
...

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch! Feel free to open a PR against the `v1.x` branch with a fix
