### ISSUE TITLE
Issue with migration generation 

### ISSUE THREAD

**Issue by as-as2018** [medusajs/medusa#7868]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I was setup new medusa and i want to create marketplace for that i was extended entities like store, user, product, order and also create migration manually but i'm facing issue migration error when run migration order of the migration is conflicting and it also time taking to create manually migration file. to generate migration i it should be automatically generated no matter it is extended or not.

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by humbleEwan** [comment]
It is bugged. You cannot extend OR (which is more annoying) make connections to any Medusa Entity. What you can do as a workaround is to manually make the connection table and have a field of the other Entity id, but do not actually connect them. Then from any service you can manually get the other entity by ID. Hope this helps.

**Comment by shahednasser** [comment]
Hi @as-as2018 can you share the migration error you're facing? Also if you can share the steps you're following to create the migration that would be great
