### ISSUE TITLE
Generating Access Token

### ISSUE THREAD

**Issue by arimtiaz** [medusajs/medusa#7876]
How can I generate access token? 
![image](https://github.com/medusajs/medusa/assets/83642378/9be20c16-57d8-4771-ba5a-caad3a6ee871)

**Comment by humbleEwan** [comment]
Based on my experience with medusa, the admin panel does not use tokens. I'm guessing session something else, it was easier to just log in trough the browser, setup a panel and run tests from there, rather to figure out how it works.

**Comment by arimtiaz** [comment]
@humbleEwan Nah I am not trying to het admin panel token. What i Did is extended medusa to adapt multi vendor functionality now I have to test it for that I need access token to send post and get methods

**Comment by humbleEwan** [comment]
Then open the panel, go to settings, and select API key management option. Other than that I do not see any other way

**Comment by arimtiaz** [comment]
That one doesnt work but there is this doc that they have but i couldn't understand it. Do you mind giving it a look.

https://docs.medusajs.com/api/admin#authentication

**Comment by humbleEwan** [comment]
![image](https://github.com/medusajs/medusa/assets/55978753/1f465045-6f0a-46f3-b7f2-a213a5e3f150)
It works fine.

**Comment by arimtiaz** [comment]
Did you have to add anything on the postman authentication?

**Comment by humbleEwan** [comment]
After I have the token I use it as a Bearer token

**Comment by arimtiaz** [comment]
From where did you get the bearer token?

**Comment by arimtiaz** [comment]
So when you first sent the post request to the auth/token you didnt need any tokens?

**Comment by humbleEwan** [comment]
To get this JWT no. I only sent my email and password in the body. This is an authentication endpoint

**Comment by sradevski** [comment]
Hey all, you can use both session and JWT-based authentication with both Medusa v1 and v2. We are planning to use JWTs for authentication by default in v2 (but both methods are supported for now). 

The auth flow in v2 looks like this:
1. Call `/auth/user/emailpass` to login/signup - This will return a JWT token on success
2. If you want to use sessions and pass auth as cookies, call `/auth/session` with the JWT token, which will initiate a session

Moreover, v2 will also support creating API keys that you can use for programatically calling the API.

For any additional discussions, please use Discord instead. thanks!

**Comment by Multichoiceagency** [comment]
Hey all, you can use both session and JWT-based authentication with both Medusa v1 and v2. We are planning to use JWTs for authentication by default in v2 (but both methods are supported for now).

The auth flow in v2 looks like this:

Call /auth/user/emailpass to login/signup - This will return a JWT token on success
If you want to use sessions and pass auth as cookies, call /auth/session with the JWT token, which will initiate a session
Moreover, v2 will also support creating API keys that you can use for programatically calling the API.

For any additional discussions, please use Discord instead. thanks!

this one works with v2
