### ISSUE TITLE
API Ref(admin): Issue in Create a Location Level

### ISSUE THREAD

**Issue by NitishGameChanges** [medusajs/medusa#7887]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Create a Location Level
- It should be Create an Inventory Level

Apis path should also have inventory level not location level. 

Same issue with 
Update a Location Level
- It should be Update an Inventory Level

Same issue with 
Delete a Location Level
- It should be Delete an Inventory Level

Apis path should also have inventory level not location level. 

### How can this issue be resolved?

Create a Location Level
- It should be Create an Inventory Level

Apis path should also have inventory level not location level. 

Same issue with 
Update a Location Level
- It should be Update an Inventory Level

Same issue with 
Delete a Location Level
- It should be Delete an Inventory Level

Apis path should also have inventory level not location level. 

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch! will open a PR to fix them
