### ISSUE TITLE
Product variant inventory_quantity is not decremented when creating a order from draft order, but returns does increment it 

### ISSUE THREAD

**Issue by ederwii** [medusajs/medusa#7899]
### Describe the bug

When creating a order from a draft order, the product variant `inventory_quantity` is not decremented by the order line items, but if a return process is completed, the `inventory_quantity` increases.

### System information

Medusa version (including plugins): 1.20.7
Node.js version: 20.14.0

### Steps to reproduce the behavior

# Prerequisites: 
* Have at least 2 different products 
* Each product should have at least 1 variant
* Each variant should have inventory_quantity = 10
* Each variant should have manage_inventory = true

1. Start a new draft order
2. Add 1 product variant to the cart, quantity = 3
3. Create the draft order
4. In the draft order detail, first thing to notice, the Shipment information says 1 product but the JSON is empty. 
5. Mark it as paid (this will create a order for this draft order)
6. go to the order detail
7. Create a fulfillment for the item
8. Mark fulfillment shipped
9. Note: At this point I would expect to see the product variant quantity to be decreased, but no, still 10 in existence
10. Start a return process 
11. Select the product, quantity = 3
12. Mark receive return
13. Go to products

### Expected behavior

The product variant inventory_quantity should be modified when the order was fulfilled or shipped, but this never happened.
After the return process was completed, I ended up having a wrong inventory_quantity (I ended up having 13 instead of the original 3. Maybe medusa will start to duplicate real life items? cool feature, looking forward)

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

This is on a brand new medusa instance, no special configuration. My intention is to consume this via API, I'm creating a POS system upon Medusa but, while working on this, I'm seeing this issue. 

I hope I provided the enough information for this.

**Comment by octalpixel** [comment]
@olivermrbl just wanted bump this up, this issue present in 1.20.9 as well. Also activating the stock location and inventory module makes the inventory_quantity undefined as well (tried this on a new setup)

**Comment by octalpixel** [comment]
@ederwii did you figure your way around this ?

**Comment by ederwii** [comment]
@octalpixel not yet. My temporary fix is to programmatically decrement the variant quantity if it's needed.
