### ISSUE TITLE
Error starting server QueryFailedError: relation "public.country" does not exist

### ISSUE THREAD

**Issue by ashu1230** [medusajs/medusa#7914]
### System information
Medusa version: 0.0.1:
Node.js version: v18.17.0
Database: PostgreSQL
Operating system: windows
Browser (if relevant): chrome

PS D:\my-project-name> medusa develop
Successfully compiled 0 files with Babel (20ms).
11:01:05 am [@medusajs/admin] Started development server on http://localhost:7001/
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:7001/, http://[::1]:7001/
<i> [webpack-dev-server] Content not from webpack is served from 'D:\WeFrameTech\my-medusa-neuz\public' directory
<i> [webpack-dev-server] 404s will fallback to '/'
<i> [webpack-dev-middleware] wait until bundle finished: /
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
error:   An error occurred while connecting to Redis:
 Error: Connection is closed.
✔ Models initialized – 311ms
✔ Plugin models initialized – 612ms
✔ Strategies initialized – 602ms
⠋ Initializing database
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
⠹ Initializing database
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
⠴ Initializing database
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
✔ Database initialized – 955ms
✔ Repositories initialized – 492ms
✔ Services initialized – 1729ms
⠋ Initializing modules
⠙ Initializing modules
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
⠴ Initializing modules
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
✔ Modules initialized – 1455ms
✔ Express intialized – 39ms
⠋ Initializing plugins
⠹ Initializing plugins
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
✔ Plugins intialized – 9162ms
✔ Subscribers initialized – 231ms
✔ API initialized – 1313ms
⠋ Initializing defaults
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
⠸ Initializing defaults
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
⠼ Initializing defaults
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
⠴ Initializing defaults
error:   Error starting server
QueryFailedError: relation "public.country" does not exist
    at PostgresQueryRunner.query (D:\WeFrameTech\my-medusa-neuz\node_modules\typeorm\driver\postgres\PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SelectQueryBuilder.loadRawResults (D:\WeFrameTech\my-medusa-neuz\node_modules\typeorm\query-builder\SelectQueryBuilder.js:2192:25)        
    at async SelectQueryBuilder.executeCountQuery (D:\WeFrameTech\my-medusa-neuz\node_modules\typeorm\query-builder\SelectQueryBuilder.js:1712:25)     
    at async SelectQueryBuilder.getCount (D:\WeFrameTech\my-medusa-neuz\node_modules\typeorm\query-builder\SelectQueryBuilder.js:770:29) {
  query: 'SELECT COUNT(1) AS "cnt" FROM "public"."country" "Country"',
  parameters: [],
  driverError: error: relation "public.country" does not exist
      at D:\WeFrameTech\my-medusa-neuz\node_modules\pg\lib\client.js:526:17
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async PostgresQueryRunner.query (D:\WeFrameTech\my-medusa-neuz\node_modules\typeorm\driver\postgres\PostgresQueryRunner.js:184:25)
      at async SelectQueryBuilder.loadRawResults (D:\WeFrameTech\my-medusa-neuz\node_modules\typeorm\query-builder\SelectQueryBuilder.js:2192:25)      
      at async SelectQueryBuilder.executeCountQuery (D:\WeFrameTech\my-medusa-neuz\node_modules\typeorm\query-builder\SelectQueryBuilder.js:1712:25)   
      at async SelectQueryBuilder.getCount (D:\WeFrameTech\my-medusa-neuz\node_modules\typeorm\query-builder\SelectQueryBuilder.js:770:29) {
    length: 113,
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: undefined,
    position: '31',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '1431',
    routine: 'parserOpenTable'
  },
  length: 113,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '31',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1431',
  routine: 'parserOpenTable'
}
assets by path *.js 36 MiB 23 assets
assets by path public/ 2.75 MiB
  asset public/locales/tm/translation.json 193 KiB [emitted] [from: node_modules/@medusajs/admin-ui/ui/public/locales/tm/translation.json] [copied]    
  + 21 assets
assets by path *.ttf 1.24 MiB
  asset 442f6a4cc2f03aaf41f6.ttf 398 KiB [emitted] [immutable] [from: .cache/admin/src/fonts/Inter-SemiBold.ttf] (auxiliary name: main)
  + 4 assets
assets by path *.css 307 KiB
  asset main.css 231 KiB [emitted] (name: main)
  + 2 assets
assets by path images/*.svg 2.33 KiB
  asset images/icon-plus-gray.svg 1.46 KiB [emitted] [from: node_modules/react-nestable/dist/styles/icon-plus-gray.svg] (auxiliary id hint: vendors)   
  asset images/icon-minus-gray.svg 884 bytes [emitted] [from: node_modules/react-nestable/dist/styles/icon-minus-gray.svg] (auxiliary id hint: vendors)
asset index.html 437 bytes [emitted]
Entrypoint main 9.62 MiB (1.24 MiB) = runtime~main.bundle.js 117 KiB main.css 231 KiB main.bundle.js 9.28 MiB 5 auxiliary assets
orphan modules 1.37 MiB (javascript) 1.24 MiB (asset) 15.3 KiB (runtime) [orphan] 656 modules
runtime modules 84.5 KiB 49 modules
modules by path ./node_modules/ 9.79 MiB (javascript) 26.8 KiB (css/mini-extract)
  javascript modules 9.78 MiB 2235 modules
  css modules 26.8 KiB
    css ./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js!./node_modules/react-nestable/dist/styles/index.css 1.76 KiB [built] [code generated]
    css ./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js!./node_modules/react-datepicker/dist/react-datepicker.css 25.1 KiB [built] [code generated]
  ./node_modules/axios/package.json 1.92 KiB [built] [code generated]
modules by path ./.cache/admin/src/ 8.4 MiB (javascript) 157 KiB (css/mini-extract) 775 modules
./util.inspect (ignored) 15 bytes [built] [code generated]
webpack 5.92.1 compiled successfully in 120255 ms
<i> [webpack-dev-middleware] wait until bundle finished: /_cache_admin_src_extensions__main-entry_ts.chunk.js
<i> [webpack-dev-middleware] wait until bundle finished: /public/locales/en/translation.json
assets by status 4.29 MiB [cached] 33 assets
assets by status 36 MiB [emitted]
  assets by chunk 16.7 MiB (id hint: vendors)
    asset vendors-node_modules_medusajs_ui_dist_cjs_index_js-node_modules_iso8601-duration_lib_index_js-398b7d.chunk.js 14.8 MiB [emitted] [minimized] (id hint: vendors)
    asset vendors-node_modules_emoji-picker-react_dist_emoji-picker-react_esm_js-node_modules_react-col-28f01f.chunk.js 1.41 MiB [emitted] [minimized] (id hint: vendors)
    asset tsub-middleware.chunk.js 357 KiB [emitted] [minimized] (name: tsub-middleware) (id hint: vendors)
 hint: vendors)
  assets by info 3.05 KiB [immutable]
    asset main.31c144f395c38dd18694.hot-update.js 2.41 KiB [emitted] [immutable] [hmr] [minimized] (name: main)
    asset runtime~main.31c144f395c38dd18694.hot-update.js 613 bytes [emitted] [immutable] [hmr] [minimized] (name: runtime~main)
    asset runtime_main.31c144f395c38dd18694.hot-update.json 43 bytes [emitted] [immutable] [hmr]
  + 18 assets
Entrypoint main 9.62 MiB (1.24 MiB) = runtime~main.bundle.js 117 KiB runtime~main.31c144f395c38dd18694.hot-update.js 613 bytes main.css 231 KiB main.bundle.js 9.28 MiB main.31c144f395c38dd18694.hot-update.js 2.41 KiB 5 auxiliary assets
cached modules 19.3 MiB (javascript) 184 KiB (css/mini-extract) 1.24 MiB (asset) 15.3 KiB (runtime) [cached] 3663 modules
runtime modules 38.6 KiB 21 modules
orphan modules 216 KiB [orphan] 1 module
./.cache/admin/src/assets/styles/global.css 716 bytes [built] [code generated]
webpack 5.92.1 compiled successfully in 36342 ms

**Comment by sradevski** [comment]
Closing as the ticket lacks important information to be able to debug if it is a bug or a configuration issue.
