### ISSUE TITLE
Error instaling Nextjs storefront

### ISSUE THREAD

**Issue by glomon** [medusajs/medusa#7946]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

This is the error i got:

 Starting project setup, this may take a few minutes.
✔ Created project directory
⠦ Installing Next.js Storefront...

An error occurred while installing Next.js storefront: Error: Command failed: npx create-next-app -e https://github.com/medusajs/nextjs-starter-medusa bogo-storefront-storefront
Found invalid GitHub URL: "https://github.com/medusajs/nextjs-starter-medusa". Please fix the URL and try again.

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for reporting this @glomon . We've fixed this in the PR #7806, but still haven't released a new version.

I suggest you clear the npm cache and try again. That way, the latest `create-next-app` is used.

**Comment by glomon** [comment]
i cleared the cache and still got the same error, can you give me some hints?

thnx in advance
