### ISSUE TITLE
Docs(Code Issue): wrong path of file

### ISSUE THREAD

**Issue by sebelapetr** [medusajs/medusa#7991]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

<img width="631" alt="Screenshot 2024-07-06 at 10 48 09" src="https://github.com/medusajs/medusa/assets/71403204/ad923d8f-f3ca-4ab2-84ef-6c43caa2ecb2">
Path in code example is src/modules/hello.index.ts, but it has to bz src/modules/hello/index.ts

https://docs.medusajs.com/v2/basics/modules-and-services

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch! WIll open a PR to fix it
