### ISSUE TITLE
Notification service not firing, keep getting "Processing XXX which has 0 subscriber"

### ISSUE THREAD

**Issue by parotech123** [medusajs/medusa#7995]
### Describe the bug

After extending the notificazion service as per guide https://docs.medusajs.com/development/notification/create-notification-provider#overview, every event is not firing and in the log console i get

``Processing XXX which has 0 subscriber```

### System information

Medusa version (including plugins): 1.20.4, no pluginns
Node.js version: 20.4.0
Database: postgres
Operating system: ubuntu 22
Browser (if relevant):

### Steps to reproduce the behavior

1. start an empty project and install medusa
2. extends the notification service as per docs provided and create dedicated loader
3. Install bus local
4. try to fire any events from the front end
5. event is logged and processed correctly, but the notification system does not fire

### Expected behavior

Notification system extended should fire 

### Screenshots

![image](https://github.com/medusajs/medusa/assets/49280466/edb11a79-3b22-4949-bbbd-51a317b340ba)

![image](https://github.com/medusajs/medusa/assets/49280466/6fdace3a-491e-482d-9e28-4f8ccdca1f11)

**Comment by SalahAdDin** [comment]
@parotech123 can you check if it was fixed? which medusa version are you using?
