### ISSUE TITLE
Issue Creating Custom Admin Page/Route with Medusa v2

### ISSUE THREAD

**Issue by usmanjaved02** [medusajs/medusa#7997]
### Describe the bug

I'm trying to create a custom page/route using the v2 documentation (https://docs.medusajs.com/v2/advanced-development/admin/ui-routes), but I keep getting errors saying that certain files don't exist.

### System information

Medusa version (including plugins): v2
Node.js version: 21.7.3
Database: postgres
Operating system:  Windows
Browser (if relevant): Google Chrome

### Screenshots
![WhatsApp Image 2024-07-07 at 1 29 03 AM](https://github.com/medusajs/medusa/assets/86144979/bb35efe2-ca88-4fd1-827e-4198fb6d52f9)

![WhatsApp Image 2024-07-07 at 1 30 08 AM](https://github.com/medusajs/medusa/assets/86144979/5582ea9b-7085-42c6-a6dd-44d10dddc075)

**Comment by kasperkristensen** [comment]
Hi @usmanjaved02, could I get you to try again with the latest version of the preview release?

**Comment by usmanjaved02** [comment]
Hey @kasperkristensen The issue of custom page is resolved many thanks But I am unable to create the route on sidebar using following code

Documentation Link: https://docs.medusajs.com/v2/advanced-development/admin/ui-routes

import { defineRouteConfig } from "@medusajs/admin-shared"
import { ChatBubbleLeftRight } from "@medusajs/icons"
import { Container } from "@medusajs/ui"

const CustomPage = () => {
  return <Container>This is my custom route</Container>
}

export const config = defineRouteConfig({
  label: "Custom Route",
  icon: ChatBubbleLeftRight,
})

export default CustomPage

**Comment by SalahAdDin** [comment]
@usmanjaved02 any update on it?

**Comment by SalahAdDin** [comment]
@usmanjaved02 Did you check it?

**Comment by usmanjaved02** [comment]
@SalahAdDin yes its working fine now

**Comment by SalahAdDin** [comment]
@usmanjaved02 you can close this issue then, thanks!
