### ISSUE TITLE
Medusa 2.0 Admin/Storefront: No Images show up at all when creating products.

### ISSUE THREAD

**Issue by kenidotproton** [medusajs/medusa#8000]
### Describe the bug

When creating a new product in the backend the thumbnail/images won't show up at all despite setting up the local files and it uploading to the folder.

### System information

Medusa version (including plugins): 2.0
Node.js version: v20.14.0
Database: postgres
Operating system: Mac OS Sonoma
Browser (if relevant): Arc

### Steps to reproduce the behavior

1. Add a new product.
2. Upload image to said product
3. Save it as a draft or continue with the steps for creating the product
4. Publish the product

### Expected behavior

Images is supposed to show up in the admin/storefront however they don't

### Screenshots

If applicable, add screenshots to help explain your problem

<img width="853" alt="Screenshot 2024-07-06 at 11 46 42 PM" src="https://github.com/medusajs/medusa/assets/152208750/333e3ca3-1add-472b-bbd3-d790ee8c58e1">

**Comment by adrien2p** [comment]
Hey @kenidotproton , thanks for the report, we will tackle this one in the coming days 👍
