### ISSUE TITLE
Email  not received whenever I clicked "Forget Password"

### ISSUE THREAD

**Issue by ghost** [medusajs/medusa#8008]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Whenever i try to log in to medusa login admin its showing that "These credentials do not match our records." even I entered the correct username and password . Whenever I click send rest instructions. I don't receive any email.

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
@GowriChandanaGadi thanks for reporting this issue, it seems like there are multiple issues here, but can I first get you to confirm what Medusa version you're using?

**Comment by ghost** [comment]
Fixed!


I cleared every database and again install the backend then it's working

**Comment by shahednasser** [comment]
Good to hear! Will close this issue then.

**Comment by ghost** [comment]
Thanks a lot.
