### ISSUE TITLE
Medusa 2.0 Database Issue

### ISSUE THREAD

**Issue by hans642** [medusajs/medusa#8027]
### Describe the bug

When i migration database from Medusa 1.20.7 to 2.0, the medusa service show the error:

> error:   Could not resolve module: PaymentModuleService. Error: Loaders for module PaymentModuleService failed: column "is_enabled" of relation "payment_provider" does not exist

table payment_provider 
2.0 database DDL
```
CREATE TABLE public.payment_provider (
	id text NOT NULL,
	is_enabled bool DEFAULT true NOT NULL,
	CONSTRAINT payment_provider_pkey PRIMARY KEY (id)
);
```
1.20.7 database DDL
```
CREATE TABLE public.payment_provider (
	id varchar NOT NULL,
	is_installed bool DEFAULT true NOT NULL,
	CONSTRAINT "PK_ea94f42b6c88e9191c3649d7522" PRIMARY KEY (id)
);
```

### System information

Medusa 2.0 
Node.js version: v22.4.1
Database: progress
Operating system: mac
Browser (if relevant): chrome

how can i migration database?

**Comment by sradevski** [comment]
Hey @hans-minesec we still don't have a migration plan from v1 to v2 ready, that is something that will come in the upcoming couple of months. In the meantime, we only support starting with new v2 projects, but not migrating from v1 to v2.

See https://github.com/medusajs/medusa/discussions/7955 for more details
