### ISSUE TITLE
No Draft Order in v2.0

### ISSUE THREAD

**Issue by huhongbo** [medusajs/medusa#8028]
### System information

Medusa version (including plugins): 2.0 preview 
Node.js version:v20.15.0
Database: postgres 15
Operating system: debian 12.6
Browser (if relevant): 

### Steps to reproduce the behavior

1. Go to 'http://localhost:9000/app/orders'

### Expected behavior

There should be Drafts oder under the Order menu

**Comment by riqwan** [comment]
Hey @huhongbo, draft orders are currently under development. It'll take some more time before we can add it to the preview release 🤞🏻

**Comment by turacma** [comment]
Any update on this? AFAICT Draft orders are still not supported in the v2 preview.
