### ISSUE TITLE
Order completion fails for certain orders

### ISSUE THREAD

**Issue by Klorrd** [medusajs/medusa#8077]
### Describe the bug
We are running a customized Medusa multi-vendor marketplace. Sometimes, when completing orders, an error is thrown, causing the order completion to fail. However, the payment is still captured by Stripe. All other Medusa-related functionalities work fine; the issue is only with order completion. 
If we restart the Fargate container, the issue get resolved, and orders can be completed without any problems. However, the issue reoccurs after a few days.

### System information

Medusa version (including plugins): ^1.11.4, (plugins: medusa-fulfillment-manual, medusa-payment-manual, medusajs/file-local, medusajs/admin, medusa-file-s3, medusa-payment-stripe, medusa-plugin-sendgrid, medusa-plugin-algolia)
Node.js version: Node 18
Database: Postgres 
Operating system: Linux (dockerized and running in AWS Fargate instance)
Browser (if relevant): N/A

### Expected behavior

Order completion without any issue.

### Screenshots

Cloud watch error logs during the cart completion
![Screenshot from 2024-07-11 08-58-16](https://github.com/medusajs/medusa/assets/117348746/ce14928f-21b1-49c0-a991-656bae8eaff6)

**Comment by sradevski** [comment]
@Klorrd can you also reproduce this issue locally? I don't know how much we can do about it without additional debugging information, as it seems it only happens sometimes on Fargate. It could be due to a connection to the DB being destroyed prematurely, or a similar issue with the lifecycle of a serverless function. 

You can also try upgrading to the latest version of 1.x and see if that maybe helps.

**Comment by Klorrd** [comment]
Thank you for the response. 
Unfortunately we couldn't reproduce the issue in local setup therefore no additional debugging information. 
Could this issue be related to running Medusa servers on Fargate containers? Will moving the servers to EBS have any affect?

**Comment by sradevski** [comment]
@Klorrd I think without some additional information, it's very difficult to say what and why is happening here. Can you just try upgrading first to the latest `v1.x` version and let us know if the issue still persists?

**Comment by Klorrd** [comment]
We have heavily customized Medusa features. Since we have an active production marketplace, I'm worried that updating will cause issues. Will update the thread if we have any additional information.

**Comment by sradevski** [comment]
Great, thanks! I'll close the ticket for now as we cannot really action it, but if you have more details we can either reopen it or create a new one.
