### ISSUE TITLE
Lack of RTL Support in Medusa Admin UI

### ISSUE THREAD

**Issue by MEClouds** [medusajs/medusa#8086]
#### Description
The Medusa Admin UI currently does not support right-to-left (RTL) languages, such as Arabic, when switching from left-to-right (LTR) languages. This results in an incorrect layout and alignment of UI elements, making the interface difficult to use for RTL language speakers.

#### Steps to Reproduce
1. Switch the language in the Medusa Admin settings to an RTL language (e.g., Arabic).
2. Observe that the layout and alignment do not adjust to the RTL format.

#### Expected Behavior
The UI should automatically adjust to the RTL layout when an RTL language is selected, ensuring that all elements are properly aligned and displayed.

#### Suggested Solution
To address this issue, the following steps are recommended:
1. **Use `rtl-detect`**: This library can be used to detect if a language is RTL. It can be integrated into the language switching logic to determine if the direction should be changed.
   - [rtl-detect on npm](https://www.npmjs.com/package/rtl-detect#require-rtl-detect-lib)
  
2. **Integrate `DirectionProvider` from Radix UI**: The `DirectionProvider` utility can be used to easily switch between LTR and RTL layouts. This will ensure that the entire UI adjusts its direction based on the selected language.
   - [DirectionProvider Documentation](https://www.radix-ui.com/primitives/docs/utilities/direction-provider)

Implementing these changes will enhance the usability of the Medusa Admin UI for users of RTL languages.

**Comment by ramiborni** [comment]
Indeed, RTL must be included in V2.0

**Comment by SalahAdDin** [comment]
@ramiborni I agree but it is not an easy thing to do.
