### ISSUE TITLE
EISDIR: illegal operation on a directory

### ISSUE THREAD

**Issue by Petr-Hl** [medusajs/medusa#8101]
### System information

Default configuration after fresh install by npx create-medusa-app@preview

Medusa CLI version: 1.3.22
Medusa version: 1.20.6-preview-20240712060553
Node.js version: v22.4.0
Database: 
Operating system: Windows 11 23H2
Browser (if relevant):

### Steps to reproduce the behavior

1. yarn build
4. See error:
```
yarn run v1.22.22
$ medusa build
Error: EISDIR: illegal operation on a directory, open 'H:\Medusa\dist\admin\widgets\product-widget.js'
    at async open (node:internal/fs/promises:639:25)
    at async writeFile (node:internal/fs/promises:1216:14)
    at async writeToOut (H:\Medusa\node_modules\@medusajs\medusa\src\commands\build.ts:70:3)        
    at async medusaTransform (H:\Medusa\node_modules\@medusajs\medusa\src\commands\build.ts:105:5)  
    at async Promise.all (index 3)
    at async default_1 (H:\Medusa\node_modules\@medusajs\medusa\src\commands\build.ts:137:3) {      
  errno: -4068,
  code: 'EISDIR',
  syscall: 'open',
  path: 'H:\\Medusa\\dist\\admin\\widgets\\product-widget.js'
}

```
### Screenshots
![image](https://github.com/user-attachments/assets/50df9eb6-a33b-43da-b6f8-fc52047f7606)

**Comment by sradevski** [comment]
Hey @Petr-Hl , can you please try again with the latest version? I believe https://github.com/medusajs/medusa/pull/8023 should have fixed it.

**Comment by Petr-Hl** [comment]
Hey @sradevski , for sure I tried more times that. On the first one project - deleted node_modules, dist and yarn.lock. Now I tried create new one project by` npx create-medusa-app@preview `command. All work good but the same issue.
`medusa -v` shows me this after the fresh install:
`Medusa version: 1.20.6-preview-20240711150439 `

next after reinstall dependences I have this:
`Medusa version: 1.20.6-preview-20240713030436`

```
C:\Tmp\test-medusa2>yarn build
yarn run v1.22.22
$ medusa build
Error: EISDIR: illegal operation on a directory, open 'C:\Tmp\test-medusa2\dist\admin\routes\custom\page.js'
    at async open (node:internal/fs/promises:639:25)
    at async writeFile (node:internal/fs/promises:1216:14)
    at async writeToOut (C:\Tmp\test-medusa2\node_modules\@medusajs\medusa\src\commands\build.ts:70:3)
    at async medusaTransform (C:\Tmp\test-medusa2\node_modules\@medusajs\medusa\src\commands\build.ts:105:5)
    at async Promise.all (index 1)
    at async default_1 (C:\Tmp\test-medusa2\node_modules\@medusajs\medusa\src\commands\build.ts:137:3) {
  errno: -4068,
  code: 'EISDIR',
  syscall: 'open',
  path: 'C:\\Tmp\\test-medusa2\\dist\\admin\\routes\\custom\\page.js'
}
Done in 2.65s.
```
C:\Tmp\test-medusa2\src\admin\routes\custom\page.tsx -->
```
import { Container } from "@medusajs/ui";

const CustomPage = () => {
  return <Container>This is my custom route</Container>;
};

export default CustomPage;

```

but both has the same issue...
With Medusa v1.20 I had never problem.

**Comment by imash96** [comment]
Getting this below error

[Error: EISDIR: illegal operation on a directory, open 'F:\Projects\website\backend\dist\api\admin\custom\route.js'] {
  errno: -4068,
  code: 'EISDIR',
  syscall: 'open',
  path: 'F:\\Projects\\website\\backend\\dist\\api\\admin\\custom\\route.js'
}

**Comment by carlos-r-l-rodrigues** [comment]
@Petr-Hl @imash96 it should be fixed in the next preview release (in about 3 hours)
Please let me know if you have any issue.

Thanks

**Comment by Petr-Hl** [comment]
Hi @carlos-r-l-rodrigues , YES! **Now it's OK**, 

thank you very much for close this issue!
