### ISSUE TITLE
Not Able to create Variants inside the Product after the Product has been created

### ISSUE THREAD

**Issue by Marwan-Dalaty** [medusajs/medusa#8119]
Variant inventory is managed separately from variant creation + updating, so we should remove `inventory_quantity` from the request to the BE as well as the input field in the create variant form. 

---

## Bug report

There are 2 ways to add variants for a product:

1. Through the wizard from the Production section, you press on create Product and inside the " Details " step of the wizard, you can add the options + the variants. --> through this way the variants would be created under the Product and it will work.
2. Create first the Product without adding the options + variants and after that once the Product has been created, if you try to go and add variants after you add the options, it doesn't work and the variants won't be created and in the console it will give the reason of the error that there is no valid value for the inventory number. Please take a look at the screenshots I've attached as a reference.

### System information

Medusa version 2.01-preview
Node.js version:
Database: PSQL v16
Operating system: Ubunut 20.04
Browser : chrome

### Steps to reproduce the behavior

1. Go to the product
2. Click on Create variant
3. write the details of the variant and after that try to save it and check the error in the developer console

### Expected behavior

the new variant should be saved under the product

### Screenshots

![Screenshot from 2024-07-14 02-15-04](https://uploads.linear.app/6afc998d-0125-4bd5-a791-94d2bbd42b7c/6a0b733d-e662-4197-824b-038b8bfd7bf5/d19f8445-e1b5-495a-b947-a14b8e0f6b63?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzZhZmM5OThkLTAxMjUtNGJkNS1hNzkxLTk0ZDJiYmQ0MmI3Yy82YTBiNzMzZC1lNjYyLTQxOTctODI0Yi0wMzhiOGJmZDdiZjUvZDE5Zjg0NDUtZTFiNS00OTVhLWI5NDctYTE0YjhlMGY2YjYzIiwiaWF0IjoxNzIwOTU3OTgyLCJleHAiOjMzMjkxNTE3OTgyfQ.SL7-Q0IDZWIMbf5ik2C1BOv7lkzpB6OnvQwaJSo6rE4)

After that if you try to save the new variant, it will give the error only in the developer console and no message will appear on the UI

![Screenshot from 2024-07-14 02-13-42](https://uploads.linear.app/6afc998d-0125-4bd5-a791-94d2bbd42b7c/7adae2b9-d479-49d4-9152-137e1b81b231/c91ed3f4-4cc5-4f06-9404-1abd9b924878?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzZhZmM5OThkLTAxMjUtNGJkNS1hNzkxLTk0ZDJiYmQ0MmI3Yy83YWRhZTJiOS1kNDc5LTQ5ZDQtOTE1Mi0xMzdlMWI4MWIyMzEvYzkxZWQzZjQtNGNjNS00ZjA2LTk0MDQtMWFiZDliOTI0ODc4IiwiaWF0IjoxNzIwOTU3OTgyLCJleHAiOjMzMjkxNTE3OTgyfQ.wkFqg0eDoJRfAm4wOzEKB_qppHJG3VrTr2lxgxwQSCc)

**Comment by olivermrbl** [comment]
Nice catch, this is indeed a bug. We'll fix this right away. You can expect it to be part of next week's release :)
