### ISSUE TITLE
Injection zones are not suggested 

### ISSUE THREAD

**Issue by bunsyy** [medusajs/medusa#8123]
### Describe the bug

When I define the zone of my custom widget, I don't get the suggestion of the available zones.

### System information

Medusa version (including plugins): 1.20.6-preview-20240712030459
Node.js version: v20.15.0
Database: PostgreSQL
Operating system: mac Sonoma
Browser (if relevant):

### Steps to reproduce the behavior

1. create a custom widget in `./src/admin/widgets/`
2. export config with `defineWidgetConfig`
3. define the zone for that widget

### Expected behavior

```js
export const config = defineWidgetConfig({
  zone: "" // <- I expect typescript to suggest all the available injection zones
});
```
### Screenshots

<img width="647" alt="Screenshot 2024-07-14 at 8 38 37 in the morning" src="https://github.com/user-attachments/assets/ad05c4c4-d9a3-4816-ba9e-c115b9419fd2">
<img width="647" alt="Screenshot 2024-07-14 at 8 27 15 in the morning" src="https://github.com/user-attachments/assets/ac6736da-44f2-400e-bb41-054d471ca100">

### Code snippets

N/A

### Additional context

For now, I have to dive deep into index `node_modules/@medusajs/admin-shared/dist/index.d.ts` to see the list of `INJECTION_ZONES`.

**Comment by Petr-Hl** [comment]
Hi @bunsyy , try change it like this:

`// Set the widget injection zone
export const config: WidgetConfig = {
  zone: "product.details.after",
};
`

**Comment by surajgjadhav** [comment]
Hi @srindom,
can I take this up ?

**Comment by srindom** [comment]
@surajgjadhav sure thanks! @kasperkristensen might already have looked into this though so let's just check with him if it makes sense?
