### ISSUE TITLE
Localization issue in admin dashboard UI

### ISSUE THREAD

**Issue by yehiatarek63** [medusajs/medusa#8124]
### Bug Description

Some words are not localized meaning that they are always in english regardless of the language that I select.

### Steps to reproduce the behavior

1. Go to settings an switch to another language besides english
2. The settings page along with other elements in the admin dashboard UI are still in english

### Expected behavior

All text in the admin dashboard should be translated to the required language.

### Screenshots

![image](https://github.com/user-attachments/assets/d241d5f2-823d-4c64-8d6d-bf9dcd576977)
![image](https://github.com/user-attachments/assets/613f0768-a3de-407b-a413-66a686b7f300)

**Comment by srindom** [comment]
Hi @yehiatarek63 - in v1 we don't have translation keys for settings titles and descriptions and we won't be able to find time to work on this. However, everything is translatable in v2.

I will close this for now, if someone is willing to work on adding translation keys for settings in v1 we'd be happy to accept a PR.

**Comment by yehiatarek63** [comment]
@srindom Thanks, I just wanted to ask, has multi-language been implemented yet in v2? I installed it and took a look but only English is available as of now and will there be RTL support for RTL languages?

**Comment by srindom** [comment]
The admin application is ready for internationalization, but we only have an English file so far (https://github.com/medusajs/medusa/blob/develop/packages/admin-next/dashboard/public/locales/en-US/translation.json). New translations files will have to be added for other locales.

We haven't built RTL support into the new dashboard. I don't know much about the requirements for this. Is it simply a question of using `dir="rtl"` on the HTML tag and ensuring the styles take direction into account or is there more to it?

**Comment by yehiatarek63** [comment]
1. I can contribute to the arabic translation and make a PR
2. To support RTL, we need to change dir="rtl".
3. RTL version of the CSS is required
4. RTL layout affects Arabic, Hebrew, Aramaic, Persian, Urdu and Kurdish
5. Make sure that any SVGs like arrows are rotated in the RTL version

**Comment by srindom** [comment]
We would be happy to accept an Arabic translation 🙏 I'd request that you wait a couple of weeks though since there's still plenty of active development on admin for v2. I will make a reminder to ping you when we are ready.

Regarding RTL, I don't think we will be able to prioritize this effort anytime soon. I believe we do get some help out of the box from Tailwind, however, it will be a big task to get it done across the admin application https://tailwindcss.com/blog/tailwindcss-v3#rtl-and-ltr-modifiers. If anyone feels inclined to PR it we would be happy to help make it land.

**Comment by MEClouds** [comment]
Hi there,

I am already working on adding RTL support and fixing some issues. I will make pull requests after finishing it. Right now, I am working on:

- Adding RTL support
- Fixing the UI to work correctly in RTL
- Adding the missing translations

After I finish these tasks, I will make the pull requests.

- [x] RTL Support (done)
- [x] Fixing UI in RTL (done)
- [ ] Adding missing translations(in progress)

![image](https://github.com/user-attachments/assets/87f18d4e-cc9c-4317-898a-61497b43bc21)

@srindom 
#8245

**Comment by alsherif-khalaf** [comment]
> Hi there,
> 
> I am already working on adding RTL support and fixing some issues. I will make pull requests after finishing it. Right now, I am working on:
> 
> * Adding RTL support
> * Fixing the UI to work correctly in RTL
> * Adding the missing translations
> 
> After I finish these tasks, I will make the pull requests.
> 
> * [x]  RTL Support (done)
> * [x]  Fixing UI in RTL (done)
> * [ ]  Adding missing translations(in progress)
> 
> ![image](https://private-user-images.githubusercontent.com/84941140/349572108-87f18d4e-cc9c-4317-898a-61497b43bc21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwNjgzMTksIm5iZiI6MTczNjA2ODAxOSwicGF0aCI6Ii84NDk0MTE0MC8zNDk1NzIxMDgtODdmMThkNGUtY2M5Yy00MzE3LTg5OGEtNjE0OTdiNDNiYzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA1VDA5MDY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkNTRlMmNiODhiNzI5ZjRhYzc3ODUyZTk5OWNlNWYxNDNlYmZhNjg2NjJiOThhNDg5MWM1Nzc5ODkzODA2ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5cxU84l3eq6pRHZEB6dbJjnZhsKpyptf0w8AUYu0RJY)
> 
> @srindom #8245

How can I add Arabic translation to V2 ?

**Comment by SalahAdDin** [comment]
@alsherif-khalaf Follow [this PR](https://github.com/medusajs/medusa/pull/10034).

Seems to be super easy.

**Comment by blueholding** [comment]
how to use Arabic in medusajs?

**Comment by Ahmedabuseta** [comment]
> how to use Arabic in medusajs?

just scroll down with kyboard after click the select input

**Comment by SalahAdDin** [comment]
@srindom why isn't this planned?
