### ISSUE TITLE
Pull current remote links using useRemoteQueryStep.

### ISSUE THREAD

**Issue by Arrowkuu** [medusajs/medusa#8134]
### Describe the bug

I wanted to pull currentLinks using 'useRemoteQueryStep' and there is no such option. More informations in screenshots.

### System information

Medusa version (including plugins): v2
Node.js version: -
Database: -
Operating system: -
Browser (if relevant): -

### Steps to reproduce the behavior

-

### Expected behavior

-

### Screenshots

<img src="https://i.imgur.com/cRvyMRU.png" />
<img src="https://i.imgur.com/Wax63Pw.png" />

### Code snippets

-

### Additional context

-

**Comment by sradevski** [comment]
@Arrowkuu can you please check what the name of the database table is for this relationship, and ensure the link has been defined? It sounds like either the link is not created, or you are using the incorrect name to fetch the data.

**Comment by adrien2p** [comment]
@sradevski I ve asked to open this issue to be linked with the pr 👍

**Comment by adrien2p** [comment]
@Arrowkuu this should probably be available in a next preview, I will close this in the meantime and feel free to let us know if something goes wrong 👍
