### ISSUE TITLE
medusa migrations command does not accept "generate" argument

### ISSUE THREAD

**Issue by intrinsic-blockchain** [medusajs/medusa#8136]
## Bug report
The CLI command _**npx medusa migrations generate <module_name>**_ does not work.

### Describe the bug
To generate migrations we after we create models or links we would need to run the command  _**npx medusa migrations generate <module_name>**_ but it throws the error **_Argument: action, Given: "generate", Choices: "run", "revert", "show"_**

### System information

Medusa version (including plugins): "preview"
Node.js version: 20.5.1
Database: postgreSQL 16
Operating system: Windows 11

### Steps to reproduce the behavior
References: 
https://docs.medusajs.com/v2/resources/recipes/marketplace/examples/vendors#step-3-generate-and-run-migrations
https://docs.medusajs.com/v2/basics/data-models#generate-a-migration

1. Create a new module with models folder and define new models
2. Run the CLI command _**npx medusa migrations generate <module_name>**_
4. See error in console

### Expected behavior

The command should execute and migrations should be created in the migrations folder inside the module.

### Screenshots
![image](https://github.com/user-attachments/assets/483a9eb5-8744-4b5d-9d9d-dca912116e23)
![image](https://github.com/user-attachments/assets/e7a11786-5c4a-43fa-94fb-a97a7943e883)
![image](https://github.com/user-attachments/assets/a7f508ca-ef87-45b5-957d-6c01653ab26e)

**Comment by thetutlage** [comment]
The `generate` action was released during the weekend. So, if you have created the app earlier, then it is most likely that you are getting this error.

Can you please run `yarn list @medusajs/medusa` and share the exact version installed in your project?

Also, running `yarn upgrade` might fix the problem for you.

**Comment by intrinsic-blockchain** [comment]
@thetutlage thanks for the direction. Looks like you were right, I had the version @medusajs/medusa@1.20.6-preview-20240709150457 and on running the update command I see @medusajs/medusa@1.20.6-preview-20240716060610. The command now works for me. Thank you!
