### ISSUE TITLE
Configuration of Backend URL in Local File Service

### ISSUE THREAD

**Issue by akoenig** [medusajs/medusa#8173]
More a generic question instead of an actual issue 🙂  – How can I configure [this](https://github.com/medusajs/medusa/blob/8ef4483afb25ab63a9abeb242a1ae9c6f94a88ad/packages/modules/providers/file-local/src/services/local-file.ts#L14-L15) value in my `medusa-config.js` (Medusa 2)?

**Comment by carlos-r-l-rodrigues** [comment]
in your medusa-config:
```typescript
[Modules.FILE]: {
  resolve: "@medusajs/file",
  options: {
    providers: [
      {
        resolve: "@medusajs/file-local-next",
        id: "local",
        options: {
          // These options are passed to the providers
          backend_url: "...",
        },
      },
    ],
  },
},
```

https://docs.medusajs.com/v2/resources/architectural-modules/file/local

**Comment by akoenig** [comment]
Ah, sorry, missed this one in the docs. Thanks a lot, @carlos-r-l-rodrigues
