### ISSUE TITLE
Flickering when show prompt 

### ISSUE THREAD

**Issue by Dominic-Preap** [medusajs/medusa#8193]
## Bug report
Flickering when show prompt with `@medusajs/ui`

https://github.com/user-attachments/assets/1ca308cb-4af6-4ef0-8551-18e45e31a4f6

### Describe the bug

When doing custom widget on product detail page, we use `Prompt` to confirm update item but when display it shows not correctly like in the docs page.

### System information

Medusa version (including plugins): `@medusajs/medusa1.20.8`, `medusajs/ui@3.0.1`
Node.js version: 20
Database: Postgres
Operating system: Windows
Browser (if relevant): Chrome

### Steps to reproduce the behavior

1. Create new widget for product page, (code is below).
2. Click on open button to see. (Video demo above)

### Expected behavior

It should work like in the [doc page](https://docs.medusajs.com/ui/components/prompt).

### Screenshots

Video demo above

### Code snippets

```tsx
import type { WidgetConfig } from '@medusajs/admin';
import { Product } from '@medusajs/medusa';
import { Container, Prompt } from '@medusajs/ui';

const ProductWidget: React.FC<{ product: Product }> = ({ product }) => {
  return (
    <Container>
      <div className="flex flex-row">
        <PromptDemo />
      </div>
    </Container>
  );
};

export const config: WidgetConfig = {
  zone: 'product.details.after'
};

export default ProductWidget;

export function PromptDemo() {
  return (
    <Prompt>
      <Prompt.Trigger asChild>
        <button>Open</button>
      </Prompt.Trigger>
      <Prompt.Content>
        <Prompt.Header>
          <Prompt.Title>Delete something</Prompt.Title>
          <Prompt.Description>Are you sure? This cannot be undone.</Prompt.Description>
        </Prompt.Header>
        <Prompt.Footer>
          <Prompt.Cancel>Cancel</Prompt.Cancel>
          <Prompt.Action>Delete</Prompt.Action>
        </Prompt.Footer>
      </Prompt.Content>
    </Prompt>
  );
}
```

### Additional context

N/A

**Comment by duc-hoang-161** [comment]
You should try it on a clean browser. Those extensions might cause issues

**Comment by srindom** [comment]
This happens because of conflicting Tailwind styles in the `@medusajs/ui` and `@meduasjs/admin-ui` packages. 

A fix should be relatively simple, however, we are not going to prioritize this right now. If anyone wants to open a PR for it feel free to. We'd be happy to help it land 👍
