### ISSUE TITLE
Timestamp "created_at" can't be removed by using  Fields Operator

### ISSUE THREAD

**Issue by Deroswent** [medusajs/medusa#8203]
When you make an Admin API request to get [List Products](https://docs.medusajs.com/v2/api/admin#products_getproducts), and try to remove unnecessary fields using [Fields Operator](https://docs.medusajs.com/v2/api/admin#select-fields-and-relations) - the field containing the timestamp “created_at” is not removed. This field is always contained in the response.   

Medusa version (including plugins): 2.01-preview   
Node.js version: v20.15.0      
Database: PostgreSQL 16     
Operating system: Windows 11 Pro      

### Steps to reproduce the behavior   

1.  Sent GET request (add to request your authorization method) to  `http://localhost:9000/admin/products?fields=-created_at`   and get an answer to it.

### Expected behavior

Expected that the “created_at” field will be missing from the received data (because the “-” sign is used before the “created_at” field in the query.). But it is still contained in the response.  It is always contained in the response, no matter which filter options are applied

![2024-07-20_21-07](https://github.com/user-attachments/assets/623a2957-1f51-4003-a406-cc2c57e19d19)

### Additional context

Interesting behavior: the field changes its position in the response if you try to delete it.   

Sent GET request (add to request your authorization method) to http://localhost:9000/admin/products   

Answer (notice the location of “created_at”.):     
```
{
  "products": [
    {
      "id": "prod_01J2QCSWJP36CK8Q5RBG7FSS9C",
      "title": "Medusa T-Shirt",
      "subtitle": null,
      "status": "published",
      "external_id": null,
      "description": "Reimagine the feeling of a classic T-shirt. With our cotton T-shirts, everyday essentials no longer have to be ordinary.",
      "handle": "t-shirt",
      "is_giftcard": false,
      "discountable": true,
      "thumbnail": "https://medusa-public-images.s3.eu-west-1.amazonaws.com/tee-black-front.png",
      "collection_id": null,
      "type_id": null,
      "weight": "400",
      "length": null,
      "height": null,
      "width": null,
      "hs_code": null,
      "origin_country": null,
      "mid_code": null,
      "material": null,
      "created_at": "2024-07-14T01:13:05.365Z",
      "updated_at": "2024-07-14T01:13:05.365Z",
      "deleted_at": null,
      "metadata": null,
      "type": null,
      "collection": null,
      "options": [
        {
........................................................................

```

And now try to use Fields Operator:  sent GET request (add to request your authorization method) to  `http://localhost:9000/admin/products?fields=-created_at`     

Answer (the position of “created_at” in the response has changed, now it is displayed after “metadata”)

```
{
  "products": [
    {
      "id": "prod_01J2QCSWJP36CK8Q5RBG7FSS9C",
      "title": "Medusa T-Shirt",
      "subtitle": null,
      "status": "published",
      "external_id": null,
      "description": "Reimagine the feeling of a classic T-shirt. With our cotton T-shirts, everyday essentials no longer have to be ordinary.",
      "handle": "t-shirt",
      "is_giftcard": false,
      "discountable": true,
      "thumbnail": "https://medusa-public-images.s3.eu-west-1.amazonaws.com/tee-black-front.png",
      "collection_id": null,
      "type_id": null,
      "weight": "400",
      "length": null,
      "height": null,
      "width": null,
      "hs_code": null,
      "origin_country": null,
      "mid_code": null,
      "material": null,
      "updated_at": "2024-07-14T01:13:05.365Z",
      "deleted_at": null,
      "metadata": null,
      "created_at": "2024-07-14T01:13:05.365Z",
      "type": null,
      "collection": null,
      "options": [
........................................................
```

**Comment by sradevski** [comment]
Hey @Deroswent thanks for the report, we'll have a look into it.

**Comment by adrien2p** [comment]
Hey https://github.com/medusajs/medusa/pull/8213 here is a pr to handle it
