### ISSUE TITLE
Access to XMLHttpRequest at 'http://localhost:9000/admin/users' from origin 'http://localhost:7001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by stelasido** [medusajs/medusa#8209]
When I use standard `localhost` in medusa-config and env as is by default, I can't access REMOTE_URL:7001,, - ERR_CONNECTION_REFUSED, when I use 0.0.0.0, I can, but the above error. I am using a standard ec2 instance, no problems with other apps, ping localhost resolves:

      develop: {
        open: true,
        host: "0.0.0.0",
        logLevel: "error",
        port: 7001,
      }, 
the cors error, but it loads /login . Even, set STORE_CORS=/http://.+/ in my-medusa-store/.env and the same cors error.
The error is when I run it on dev `npm run dev`.

**Comment by sradevski** [comment]
Hey @stelasido please refer to https://docs.medusajs.com/troubleshooting/cors-issues, I believe this is not a bug but simply a misconfiguration. If you are still having issues, please head to our discord channel to get help from the community.
