### ISSUE TITLE
Just a double space

### ISSUE THREAD

**Issue by azharul-islam** [medusajs/medusa#8210]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In https://medusajs.com/recap/, New commerce features in 2.0., there's double space in "high-converting  commerce applications". 

### How can this issue be resolved?

1. Just fix the double space
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for reporting this @ashish-patwal , I'll pass this along to the related team. As this issue isn't related to this repo, I'll close it.
