### ISSUE TITLE
remoteLink.create throws error even though the link exists

### ISSUE THREAD

**Issue by lokeswaran-aj** [medusajs/medusa#8217]
### Describe the bug
I followed the v2 documentation to learn about links, when I tried to create link, i was getting the following error:
`error:   Module to type product and my_custom by keys product_id and my_custom_id was not found. Ensure the link exists, keys are correct, and link is passed in the correct order to method 'remoteLink.create'. `

### System information

Medusa version (including plugins):
Node.js version: v20.11.1
Database: postgres
Operating system: macos
Browser (if relevant):

### Steps to reproduce the behavior

1. Define link between any 2 [module](https://docs.medusajs.com/v2/advanced-development/modules/module-links)
2. Now use the remoteLink.create() method as shown in the [docs](https://docs.medusajs.com/v2/advanced-development/modules/remote-link#create-link)

### Expected behavior
The data should be stored in the mapping table

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by adrien2p** [comment]
When creating a link in an order, it mean that the link must also follow that order, so a link custom <> product should be created as { custom..., product }

cc @shahednasser the doc does not reflect that, cc @carlos-r-l-rodrigues can you confirm I am right I believe we did that but I remember a discussion to allow both direction during creation

**Comment by srindom** [comment]
@lokeswaran-aj - can you verify that the order was the problem? 

We have updated docs to clarify this. If the problem still occurs feel free to reopen.
