### ISSUE TITLE
ERR_CONNECTION_REFUSED, after npx create-medusa-app@latest on REMOTE_IP:7001

### ISSUE THREAD

**Issue by stelasido** [medusajs/medusa#8218]
There is a bug, when I am using the default settings `npx create-medusa-app@latest`, which starts the dev, I can't access the store in REMOTE_IP:7001, -> `ERR_CONNECTION_REFUSED`
 I need to change `localhost` with `0.0.0.0` and I can access it, but then, I see a CORS problem. This is with every EC2 instance, that Ive tried - Ubuntu and Amazon Linux 2023. The CORS problem is for host `localhost` and there is no sence, because on the client, `localhost` resolves to the client, but not to remote.
In my local machine with Windows, it works fine - it opens `http://localhost:7001/invite?token=...`, but in remote, after ``npx create-medusa-app@latest` -> REMOTE_IP:7001, -> `ERR_CONNECTION_REFUSED`

- The settings are, what they are by default, when you run `npx create-medusa-app@latest`
- NodeJS v18.20.3

**Comment by stelasido** [comment]
To open the login REMOTE_IP:7001, I need to add exactly that, all other envs, doesn't matter: 
![image](https://github.com/user-attachments/assets/4a628201-c1ed-47c0-9325-6cd6e6de1894)
Then I see that:
![image](https://github.com/user-attachments/assets/452617a6-94b7-44c3-983e-dedeacecd676)

As you can see, it requests to localhost:9000 from origin REMOTE_IP:7001, there is no logic for that

**Comment by stelasido** [comment]
U can simply test, by creating an EC2 instance for less than an hour, allow 7001, 7000, 8000, 9000 ports and use `npx create-medusa-app@latest`

**Comment by kasperkristensen** [comment]
@stelasido you need to set the `backend` param in the admin plugin options, the default value is `http://localhost:9000`, which is wrong in your case. 

```
options: {
  autoRebuild: true,
  backend: <here>,
  develop: {
    open: true,
    port: "0.0.0.0"
  }
}
```

**Comment by stelasido** [comment]
> @stelasido you need to set the `backend` param in the admin plugin options, the default value is `http://localhost:9000`, which is wrong in your case.
> 
> ```
> options: {
>   autoRebuild: true,
>   backend: <here>,
>   develop: {
>     open: true,
>     port: "0.0.0.0"
>   }
> }
> ```

Still the same. Also, when I run it, it uses the private IP, but not the public/elastic IP 
![image](https://github.com/user-attachments/assets/9ed417a6-80c1-4f14-b6ac-a57d8654e4e9)
This is with 0.0.0.0: 
![image](https://github.com/user-attachments/assets/63835972-47ad-4147-aeb3-3b1ae3c31788)

This is without, any `develop.host`:
![Uploading image.png…]()

**Comment by kasperkristensen** [comment]
@stelasido 

What are you setting the `backend` prop to? And is the dashboard not making requests to that URL?

**Comment by stelasido** [comment]
@kasperkristensen without host: 0.0.0.0:
![image](https://github.com/user-attachments/assets/562cafa4-8464-4ac7-80a7-3d58900bce7b)

![image](https://github.com/user-attachments/assets/8d2ffd0d-beaa-497f-a10b-c3081dd91a0a)
`ERR_CONNECTION_REFUSED`
with `host: '0.0.0.0'`:
![image](https://github.com/user-attachments/assets/0606e062-3b35-4758-9460-7f795fee661b)
I can access login, but there is still problem. Now, not bloked request, but: 
![image](https://github.com/user-attachments/assets/aef3f21c-4b5b-4c0d-8a5e-4de3e34299d2)
This is after `npm build`, in case of some static cache.
Also REMOTE_URL:9000 works fine in all cases, I can access it via browser  `Cannot GET /` - which means the API works

**Comment by kasperkristensen** [comment]
@stelasido I see the issue now, and will open a PR to fix it. In the meantime, you can set the `serve` option in the admin plugin options to false:

```
options: {
  serve: false,
  // ...other options
}
```

And then the backend should be picked up correctly. Remember to also update your ADMIN_CORS to match the custom host you have set for the admin development server.

**Comment by olivermrbl** [comment]
@stelasido, can you give the following snapshot a try and let us know if the issue is resolved:
```
yarn add @medusajs/admin@7.1.16-snapshot-20240723085529
```

**Comment by olivermrbl** [comment]
@stelasido, any luck? We have a release later today and would like to include it if possible.

**Comment by stelasido** [comment]
hi, yes. Thx, will close the case.

**Comment by naveennavee** [comment]
@stelasido Im also facing same problem kindly help me.

Im running store-front and admin. I have edited both the .env. if I use curl command to hit the vm-ip:9000 im getting success message. but with login page im re-directing to localhost page.
this is medusa env's
`DATABASE_TYPE=postgres
DATABASE_URL=postgres://medusa:new@localhost/medusa-Buqf
MEDUSA_ADMIN_ONBOARDING_TYPE=nextjs
STORE_CORS=http://vm:8000,http://vm:7001,http://vm:9000
MEDUSA_ADMIN_ONBOARDING_NEXTJS_DIRECTORY=test-storefront
MEDUSA_BACKEND_URL=http://vm:9000
NEXT_PUBLIC_MEDUSA_BACKEND_URL=http://vm:9000
LOG_FILE=medusaa.log
ADMIN_CORS=http://vm:7001`

this is medusa-store .env's
`NEXT_PUBLIC_MEDUSA_BACKEND_URL=http://vm:9000`

Kindly help me
![medusa](https://github.com/user-attachments/assets/e989f3e2-7a77-4517-ac7f-c14edc63d0cc)
![ui](https://github.com/user-attachments/assets/e39e17d0-1583-4e45-b5dc-b8a887e1fd12)
