### ISSUE TITLE
calculated_amount and original_amount in variants.calculated_price doesn't have 2 decimal places

### ISSUE THREAD

**Issue by Arrowkuu** [medusajs/medusa#8220]
### Describe the bug

In `variants.calculated_price`, `calculated_amount` and `original_amount` doesn't have 2 decimal places.
### System information

Medusa version (including plugins): v2
Node.js version: 21
Database: Postgres
Operating system: -
Browser (if relevant): -

### Steps to reproduce the behavior

-

### Expected behavior

-

### Screenshots

<img src="https://i.imgur.com/8z927YG.png" />

### Code snippets

-

### Additional context

-

**Comment by sradevski** [comment]
Already fixed in the latest preview release, closing
