### ISSUE TITLE
Contentful migration doesn't provide a media field, only a thumbnail one.

### ISSUE THREAD

**Issue by ghost** [medusajs/medusa#8243]
### What Medusa version and documentation are you using?

v1

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

When installing the Contentful plugin, the product.ts and index.ts files do not handle the media connection/field to Contentful during the migration process. As a result, when you upload a product from the Medusa Backend, it does not upload to Contentful; only the variant for the new product is added. This issue occurs specifically when creating a product with media. If you only provide a thumbnail, there is no problem, as the files listed have their respective fields for the thumbnail.

For example a test product,
<img width="1313" alt="image" src="https://github.com/user-attachments/assets/233bcc9d-2f7d-4ad1-8790-77dfaf0245db">

And in Contentful,
<img width="1387" alt="image" src="https://github.com/user-attachments/assets/77bca457-59a5-4abd-8348-dc911fe8948b">

### How can this issue be resolved?

1. Add the section for medias in _product.ts_, what it don't know If it has to be a link with another entity or just added to the product fields.
For example:
```
product
    .createField("medias")
    .name("Medias")
    .type("Array")
    .items({
      type: "Link",
      linkType: "Entry",
      validations: [
        {
          linkContentType: ["productMedias"],
        },
      ],
    });
```
2. Fix _index.ts_ so when you do the migration is counted and added to Contentful, this step depends if the media is a link or not.
3. Check if it works using `npx medusa develop`
...

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by ghost** [comment]
What I need to know if the media field should be a link one or not, depending on that I can check the solution. Cheers.

**Comment by srindom** [comment]
I think an asset would be sufficient here - i.e., doesn't need to link to an additional entity. 

Happy to accept a PR with your fix 👍

**Comment by ghost** [comment]
Hi,

I tried a few things, like doing it without the link entity and with it. The problem is the object, and I cannot link both. I also tried doing it with Categories (all of this in V1 of Medusa), but when I tried to upload a product to Medusa, it doesn't update in Contentful. I don't know where to see the process or if I need to add something more, like in the medusa.config.js file.


EDIT: I also tried with medusa.config.js with custom fields and nothing happens.

**Comment by SalahAdDin** [comment]
@TomasH-medismart did you fix it?

**Comment by ghost** [comment]
No, I couldn’t. I tried using both an asset and an entity, but I believe the issue lies with the webhook that listens for uploads in Contentful. It seems that the webhook isn’t properly recognizing or handling media files, so they aren’t getting linked with the other values.”

**Comment by SalahAdDin** [comment]
Are you moving to another e-commerce?

**Comment by ghost** [comment]
No, but right now is not a priority for me. I would try again in the future. But I don't know how to modify the contenful plugin so it also checks for the media.

**Comment by SalahAdDin** [comment]
> No, but right now is not a priority for me. I would try again in the future. But I don't know how to modify the contenful plugin so it also checks for the media.

Did you try to follow the documentation about creating plugins?

**Comment by ghost** [comment]
I knew that I could download the existing plugin that medusa has on contentful and try fixing it there, but I didn't have the time to do it sadly. 😞

**Comment by SalahAdDin** [comment]
Is it a MedusaJS plugin?

**Comment by ghost** [comment]
Yes. In this link you have all the information: https://docs.medusajs.com/plugins/cms/contentful
 What I tried was changing the content model of the product so when it synchronized with Contentful also add the media. And then was two ways of doing it.
1.  Putting as an array of asset, being that the media field you can upload up to 3 images.
2. Creating an Asset object and making that the array.

You can check the types of Contentful here https://www.contentful.com/developers/docs/concepts/links/ and here: https://www.contentful.com/developers/docs/concepts/data-model/

**Comment by SalahAdDin** [comment]
@srindom, @TomasH-medismart need support to fix this issue.
