### ISSUE TITLE
Medusa v2 Docs: Issue in 1. Introduction - Medusa v2 Docs

### ISSUE THREAD

**Issue by exportsodas** [medusajs/medusa#8248]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The documentation here throws an infinite loop: https://docs.medusajs.com/v2/resources/events-reference

MESSAGE:
This Request has triggered an infinite loop.

Your connection is working correctly.

Vercel is working correctly.

508: INFINITE_LOOP Code: INFINITE_LOOP_DETECTED

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for reporting this! Opened PR #8255 to fix this.
