### ISSUE TITLE
Not able to update a document of a custom model by id 

### ISSUE THREAD

**Issue by akmaksumov** [medusajs/medusa#8253]
### Describe the bug

Calling `update[EntityName]s(id, data)` on a custom model throws a `NOT_FOUND` error , with message `[EntityName] with id "" not found`. The provided `id` is `"01J3GTNMN8YBSSW0RGK7Y145G4"`,  so somewhere down the line it gets lost and replaced with an empty string. Calling `update[EntityName]s({ id : id }, data)` **does not** throw an error, however it returns the original data unchanged.

### System information

Medusa version (including plugins): v2.0.1
Node.js version: v20.15.1
Database: PostgreSQL 16 
Operating system: macOS 14.5
Browser (if relevant): 

### Steps to reproduce the behavior

1. Define a new module, where the main service extends `MedusaService` 
2. Define new models and add them to the main service constructor 
3. Run migrations
4. Define a new `POST` API route at `admin/module-name/[id]` that updates the document with the given `[id]`. 
5. Call `update[EntityName]s(id, data)` inside that route's function 

### Expected behavior

A successful update of the document with provided `[id]`

#### Models : `./src/modules/cms/models/cms.ts`
```typescript
import { model } from "@medusajs/utils";

const Cms = model.define("cms", {
	id: model.id().primaryKey(),
	title: model.text(),
	is_enabled: model.boolean().default(false),
	metadata: model.json().nullable(),
	cms_provider: model.hasOne(() => CmsProvider).nullable(),
	cms_products: model.hasMany(() => CmsProduct),
});

const CmsProvider = model.define("cms_provider", {
	id: model.id().primaryKey(),
	title: model.text(),
	url: model.text().nullable(),
	metadata: model.json().nullable(),
	cms: model
		.belongsTo(() => Cms, {
			mappedBy: "cms_provider",
		})
		.nullable(),
});

const CmsProduct = model.define("cms_product", {
	id: model.id().primaryKey(),
	external_id: model.text().unique().searchable(),
	metadata: model.json().nullable(),
	cms: model.belongsTo(() => Cms, {
		mappedBy: "cms_products",
	}),
	cms_product_variants: model.hasMany(() => CmsProductVariant),
});

const CmsProductVariant = model.define("cms_product_variant", {
	id: model.id().primaryKey(),
	external_id: model.text().unique().searchable(),
	metadata: model.json().nullable(),
	cms_product: model.belongsTo(() => CmsProduct, {
		mappedBy: "cms_product_variants",
	}),
});

export { CmsProvider, CmsProduct, CmsProductVariant };
export default Cms;
```
#### Main Service: `./src/modules/cms/service.ts`
```typescript
import { Logger } from "@medusajs/medusa";
import { MedusaService, ContainerRegistrationKeys } from "@medusajs/utils";
import { CMSProductPayloadDTO } from "./typings";
import Cms, { CmsProvider, CmsProduct, CmsProductVariant } from "./models/cms";
import PayloadCMSProvider, {
	PayloadCMSProviderOptions,
	convertProductStatus,
} from "../../providers/cms";

type InjectedDependencies = {
	logger: Logger;
};
type CMSModuleOptions = {
	providers?: PayloadCMSProviderOptions[];
};

class CMSModuleService extends MedusaService({
	Cms,
	CmsProvider,
	CmsProduct,
	CmsProductVariant,
}) {
	private providers_: Map<string, PayloadCMSProvider>;
	protected logger_: Logger;
	constructor(
		{ logger }: InjectedDependencies,
		{ providers }: CMSModuleOptions
	) {
		super(...arguments);
		this.logger_ = logger;
		this.logger_.info(
			`Provided arguments: ${JSON.stringify(arguments, null, "\t")}`
		);
		this.providers_ = new Map();
		if (providers) {
			providers.forEach((provider) => {
				this.providers_.set(
					provider.id,
					new PayloadCMSProvider(provider)
				);
			});
		}
	}

	async listCmses(...args: any) { // NOTE: Does not correctly infer plural method names for names ending with "s"
		return await super.listCms(...arguments);
	}
	async listAndCountCmses() {
		return await super.listAndCountCms(...arguments);
	}
	async createCmses(...args: any) {
		return await super.createCms(...arguments);
	}
	async updateCmses(...args: any) {
		this.logger_.info(
			`Received a request for updateCmses: ${JSON.stringify(
				arguments,
				null,
				"\t"
			)}`
		);
		return await super.updateCms(...arguments);
	}
	async deleteCmses() {
		return await super.deleteCms(...arguments);
	}
	async softDeleteCmses() {
		return await super.softDeleteCms(...arguments);
	}
	async restoreCmses() {
		return await super.restoreCms(...arguments);
	}
}

export default CMSModuleService;
```
`./src/modules/cms/index.ts`
```typescript
import CMSModuleService from "./service";
import { Module } from "@medusajs/utils";

export const CMS_MODULE = "cmsModuleService";

export default Module(CMS_MODULE, {
	service: CMSModuleService,
});
```
`./medusa-config.js`
```typescript
import { loadEnv, defineConfig } from "@medusajs/utils";
import { CMS_MODULE } from "./src/modules/cms";
loadEnv(process.env.NODE_ENV, process.cwd());

module.exports = defineConfig({
	projectConfig: {
		databaseUrl: process.env.DATABASE_URL,
		http: {
			storeCors: process.env.STORE_CORS,
			adminCors: process.env.ADMIN_CORS,
			authCors: process.env.AUTH_CORS,
			jwtSecret: process.env.JWT_SECRET || "supersecret",
			cookieSecret: process.env.COOKIE_SECRET || "supersecret",
		},
	},
	modules: {
		[CMS_MODULE]: {
			resolve: "./modules/cms",
			options: {
				providers: [
					{
						id: "payload-cms-main",
						apiKey: process.env.PAYLOAD_CMS_API_KEY,
						cmsUrl: process.env.PAYLOAD_CMS_URL,
						authSlug: "integrations",
					},
				],
			},
			definition: {
				isQueryable: true,
			},
		},
	},
});
```

#### API - Route: `./src/api/admin/cms/[id]/route.ts`

```typescript
import { MedusaRequest, MedusaResponse } from "@medusajs/medusa";
import { MedusaError } from "@medusajs/utils";
import CMSModuleService from "../../../../modules/cms/service";

export async function GET(
	req: MedusaRequest,
	res: MedusaResponse
): Promise<void> {
	const cmsModuleService =
		req.scope.resolve<CMSModuleService>("cmsModuleService");

	const cms = await cmsModuleService.retrieveCms(
		req.params.id,
		req.retrieveConfig
	);
	res.status(200).json({ cms });
}

/**
 * Update data by its ID
 */
export async function POST(
	req: MedusaRequest,
	res: MedusaResponse
): Promise<void> {
	const logger = req.scope.resolve("logger");
	const cmsModuleService =
		req.scope.resolve<CMSModuleService>("cmsModuleService");
	logger.info(`Received a request for POST on /admin/cms/${req.params.id}`);

	// * * * * * * * * * * * * * * * * *
	// No Error, but data is not updated
	const cms = await cmsModuleService.updateCmses(
		{ id: req.params.id },
		req.body
	);
	// * * * * * * * * * * * * * * * * *
	// Throws `NOT_FOUND` Error
	const cms_ = await cmsModuleService.updateCmses(req.params.id, req.body);
	res.status(200).json(cms);
}
```

#### Document before operation:

```json
{
  "cms": {
    "id": "01J3GTNMN8YBSSW0RGK7Y145G4",
    "title": "test-cms",
    "is_enabled": false,
    "metadata": null,
    "cms_provider": null,
    "created_at": "2024-07-23T22:16:27.049Z",
    "updated_at": "2024-07-23T22:16:27.049Z",
    "deleted_at": null
  }
}
```

#### Request body:

```json
{
  "title":"test-cms-2"
}
```

#### logged input parameters to `update` method followed by error and stack-trace:

![Screenshot 2024-07-23 at 9 38 28 PM](https://github.com/user-attachments/assets/97413ac7-10a1-4749-8907-c29cd752d8b1)
![Screenshot 2024-07-23 at 9 39 31 PM](https://github.com/user-attachments/assets/51b26e2d-5de0-4851-8ca4-a9edef4dd97d)
#### Here we wrap `id` as `{ id : req.params.id }`, no error but the document was not updated:
![Screenshot 2024-07-23 at 9 41 43 PM](https://github.com/user-attachments/assets/076bedae-577c-46de-94bc-aefc56552947)

#### Document after the operation (Response) that does not throw error, same as original:

```json
{
  "id": "01J3GTNMN8YBSSW0RGK7Y145G4",
  "title": "test-cms",
  "is_enabled": false,
  "metadata": null,
  "cms_provider": null,
  "created_at": "2024-07-23T22:16:27.049Z",
  "updated_at": "2024-07-23T22:16:27.049Z",
  "deleted_at": null
}
```

**Comment by adrien2p** [comment]
hey @akmaksumov , the api for the update is the following one (not yet very well typed though sorry for that)
```ts
updateCms({ id, ...body })

// or

updateCms([{ id, ...body }])

// or

updateCms({ selector: { id }, data: body })

// or

updateCms([{ selector: { id }, data: body }])
```

could you give that a spin please.

the issue with your actual usage is the following:
- first one, you are passing an object that only contains the id, therefore nothing to update
- in the second one, you are passing just the value of the id, so we grab the primary key of the model, assign data[primaryKey] which does not exists in the input and therefore endup with an empty id and throw an error

**Comment by shahednasser** [comment]
To add to @adrien2p 's answer, you can find examples of using each of the generated methods in [this documentation](https://docs.medusajs.com/v2/advanced-development/modules/service-factory#generated-methods).

**Comment by akmaksumov** [comment]
> hey @akmaksumov , the api for the update is the following one (not yet very well typed though sorry for that)
> 
> ```ts
> updateCms({ id, ...body })
> 
> // or
> 
> updateCms([{ id, ...body }])
> 
> // or
> 
> updateCms({ selector: { id }, data: body })
> 
> // or
> 
> updateCms([{ selector: { id }, data: body }])
> ```
> 
> could you give that a spin please.
> 
> the issue with your actual usage is the following:
> 
> * first one, you are passing an object that only contains the id, therefore nothing to update
> * in the second one, you are passing just the value of the id, so we grab the primary key of the model, assign data[primaryKey] which does not exists in the input and therefore endup with an empty id and throw an error

Great! All of these work and fix this issue, thank you!

**Comment by akmaksumov** [comment]
> To add to @adrien2p 's answer, you can find examples of using each of the generated methods in [this documentation](https://docs.medusajs.com/v2/advanced-development/modules/service-factory#generated-methods).

Thank you! I will refer to these from this point on. I initially was referring to [built in modules](https://docs.medusajs.com/v2/resources/references/sales_channel/ISalesChannelModuleService/methods/sales_channel.ISalesChannelModuleService.updateSalesChannels) as they also provide type hints for parameters, however I did not notice that the api is different for custom modules, is it intentional? or will they eventually converge into one implementation?

**Comment by adrien2p** [comment]
Wonderful, yes currently the base class provides you with some implementations that the core modules might override (argument shapes as well before normalizing and calling the base one) but the idea long term is to get all of them normalized
