### ISSUE TITLE
medusa-admin build --deployment command is giving an errors

### ISSUE THREAD

**Issue by vholik** [medusajs/medusa#8264]
## Bug report
When running medusa-admin build --deployments I get error

### Describe the bug

When running medusa-admin build --deployments I get this error

$ medusa-admin build --deployment
⠧ Building Admin UI
node_modules/@radix-ui/react-portal/dist/index.mjs (1:0) Module level directives cause errors when bundled, "use client" in "node_modules/@radix-ui/react-portal/dist/index.mjs" was ignored.
node_modules/@radix-ui/react-dialog/dist/index.mjs (1:0) Module level directives cause errors when bundled, "use client" in "node_modules/@radix-ui/react-dialog/dist/index.mjs" 
⠇ Building Admin UI
node_modules/@radix-ui/react-dismissable-layer/dist/index.mjs (1:0) Module level directives cause errors when bundled, "use client" in "node_modules/@radix-ui/react-dismissable-layer/dist/index.mjs" was ignored.
node_modules/@radix-ui/react-focus-scope/dist/index.mjs (1:0) Module level directives cause errors when bundled, "use client" in "node_modules/@radix-ui/react-focus-scope/dist/index.mjs" was ignored.
node_modules/@radix-ui/react-presence/dist/index.mjs (1:0) Module level directives cause errors when bundled, "use client" in "node_modules/@radix-ui/react-presence/dist/index.mjs" was ignored.
node_modules/@radix-ui/react-focus-guards/dist/index.mjs (1:0) Module level directives cause errors when bundled, "use client" in "node_modules/@radix-ui/react-focus-guards/dist
⠋ Building Admin UI
node_modules/@radix-ui/react-tooltip/dist/index.mjs (1:0) Module level directives cause errors when bundled, "use client" in "node_modules/@radix-ui/react-tooltip/dist/index.mjs
⠹ Building Admin UI
node_modules/@radix-ui/react-popper/dist/index.mjs (1:0) Module level directives cause errors when bundled, "use client" in "node_modules/@radix-ui/react-popper/dist/index.mjs" 
⠦ Building Admin UI
node_modules/@radix-ui/react-dropdown-menu/dist/index.mjs (1:0) Module level directives cause errors when bundled, "use client" in "node_modules/@radix-ui/react-dropdown-menu/dist/index.mjs" was ignored.
node_modules/@radix-ui/react-collapsible/dist/index.mjs (1:0) Module level directives cause errors when bundled, "use client" in "node_modules/@radix-ui/react-collapsible/dist/i
⠧ Building Admin UI
node_modules/@radix-ui/react-accordion/dist/index.mjs (1:0) Module level directives cause errors when bundled, "use client" in "node_modules/@radix-ui/react-accordion/dist/index.mjs" was ignored.
node_modules/@radix-ui/react-menu/dist/index.mjs (1:0) Module level directives cause errors when bundled, "use client" in "node_modules/@radix-ui/react-menu/dist/index.mjs" was 
⠇ Building Admin UI
[vite]: Rollup failed to resolve import "iso8601-duration" from "/Users/myhome/Desktop/my-project/node_modules/@medusajs/admin-ui/ui/src/components/templates/discount-table/use-promotion-columns.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error Command failed with exit code 

### System information

Medusa version (including plugins): all is set preview
Node.js version: 1.20 (i tried on different machines with the different nodejs versions it doesnt matter)
Database:
Operating system:
Browser (if relevant):

### Steps to reproduce the behavior

Try to build admin with the newest medusa admin panel

### Expected behavior

Admin builds

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by vholik** [comment]
I'm closing this issue due to medusa-admin is not supported in Medusa 2.0 and admin panel can be accessed via backend_url/app

**Comment by mehdinourollah** [comment]
> I'm closing this issue due to medusa-admin is not supported in Medusa 2.0 and admin panel can be accessed via backend_url/app

PLEASE write this somewhere ... It took me 2 hours to find that the admin panel is now served on localhost:9000/app and not on localhost:7000 as before 😭

**Comment by helderjnpinto** [comment]
@mehdinourollah me too ... the documentation is not explicit to this
