### ISSUE TITLE
[Deprecation] Custom state pseudo classes changing in Next.js Storefront

### ISSUE THREAD

**Issue by jason-kkcc** [medusajs/medusa#8294]
When visiting https://next.medusajs.com/us, the following deprecation warnings appear in the Chrome console:
text
[Deprecation] Custom state pseudo classes are changing from ":--webkit-search-cancel-button" to ":state(webkit-search-cancel-button)" soon. See more here: https://github.com/w3c/csswg-drafts/issues/4805

This error also occurs in my custom-developed and deployed [handcrafted gifts platform ](https://www.heartvoicegifts.com)based on the Medusa Next.js storefront. I have been unable to locate the source of this error or determine its origin.
Could you please investigate this issue and provide guidance on how to resolve or mitigate these deprecation warnings in the Next.js storefront? Any information on the potential impact of these changes and recommended steps for updating would be greatly appreciated.
Thank you for your attention to this matter.

**Comment by kasperkristensen** [comment]
Hi @jason-kkcc

The warning comes from our UI library, where we use `:--webkit-search-cancel-button` selector to style on of our components. But as the warnings mentions, the change will occur **soon**, but hasn't yet, so nothing we can do about atm. Once the change has taken effect, we will also update our styles to match the change.

**Comment by nenadrakovic** [comment]
Any update on this? :)
