### ISSUE TITLE
Can't change order status

### ISSUE THREAD

**Issue by kevin25** [medusajs/medusa#8309]
When I provide the tracking number on the manual fulfillment, the order is still processing. Is that medusa feature or bug? How can I put it to the completed order status?

The ideal logic is like Shopify

Fulfill => provide tracking number => change to fulfilled status => When delivered => change status to completed.

Processing => fulfilled => completed

### System information

Medusa version (including plugins):
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by olivermrbl** [comment]
You can create a subscriber that updates the order status whenever you deem appropriate. 

In your specific use case, it would be on `order.fulfillment_created`. It would look something along the lines of:
```
export default async function updateOrder({  data, eventName, container, }) {
  const orderService = container.resolve("orderService")

  const { id } = data

  await orderService.update(id, { ... })
}

export const config: SubscriberConfig = {
  event: "order.fulfillment_created",
}
```
