### ISSUE TITLE
Updating variant pricing deletes fields

### ISSUE THREAD

**Issue by HarleySalas** [medusajs/medusa#8376]
### Describe the bug

When going to a variant and editing it's prices for different currencies/countries and pressing save, it will (randomly?) delete fields that were not touched, or "dirty" as some would call it.

### System information

Medusa version (including plugins): 
@medusajs/medusa: `1.20.6-preview-20240729150459`
@medusajs/pricing: `0.1.13-preview-20240729150459`
@medusajs/product: `0.3.13-preview-20240729150459`

Node.js version: `22.2.0`

Database: `postgres 16.3`
Operating system: `Linux Mint 21.3 Cinnamon`
Browser (if relevant): `Version 126.0.6478.114 (Official Build) (64-bit)`

### Steps to reproduce the behavior

1. Go to a product variant's edit page.
2. In the `Price` card on the right side, click the icon with 3 dots and press `Edit` to edit prices.
3. Observe the existing fields, make some edits, save and reopen the modal.
4. Check for data inconsistencies.

### Expected behavior

When updating a value in the pricing table, you would expect nothing to be deleted, especially if you did not touch it.

### Screenshots
https://github.com/user-attachments/assets/de634f45-364e-46d1-9b18-3f470ac20b67

**Comment by sradevski** [comment]
Hey @HarleySalas thanks for the detailed ticket, we'll have a look 👍
