### ISSUE TITLE
Can't create a store with Medusa v2

### ISSUE THREAD

**Issue by superzaky** [medusajs/medusa#8381]
### Describe the bug

This is the command I tried to execute:

`npx create-medusa-app@preview`

And this is the error that I get:
[![enter image description here][1]][1] 

I have already tried to clean my cache with the following command:

`npm cache clean --force`

However, that didn't work unfortunately. Can someone perhaps help me? Thanks in advance.

  [1]: https://i.sstatic.net/yrbbGT90.png

### System information

Medusa version (including plugins): Medusa v2
Node.js version: 22.5.1
Database: PostgreSQL
Operating system: Windows
Browser (if relevant):

### Steps to reproduce the behavior
I have already mentioned this, see above description

### Expected behavior
That a medusa store is created

**Comment by adrien2p** [comment]
@superzaky are you sure you are under node 22 when this command is being run? This error usually means that optional chaining is not available in your environment.

Could you check that and let us know please 😊

**Comment by superzaky** [comment]
Turns out I had two different Node.js versions on my computer, after deleting the older one, everything worked fine.
