### ISSUE TITLE
Can't get storefront running in medusa.js v2.0 and Next.js 14.2.4 is out of date.

### ISSUE THREAD

**Issue by superzaky** [medusajs/medusa#8395]
I am getting an error when I try to run the storefront. This is the error that I get:

![image](https://github.com/user-attachments/assets/61b3a5c1-a3f8-4a48-9fec-228f98a91df6)

Notice that the above screenshot clearly states that: 

Next.js (14.2.4) out of date

### System information

Medusa version (including plugins): Medusa v2
Node.js version: 22.5.1
Database: PostgreSQL
Operating system: Windows
Browser (if relevant):

### Steps to reproduce the behavior
Start making a medusa.js v2 store and start the back end. After that, start the storefront by typing the following command:
`yarn dev`

### Expected behavior

That I can see the storefront in the browser.

### Code 
In case you want to see my code, then you can find it on the following link:
https://github.com/superzaky/webshop_Zaky

**Comment by 420coupe** [comment]
Try starting the storefront with npm run dev

**Comment by superzaky** [comment]
I fixed it by reinstalling node_modules
