### ISSUE TITLE
Can't run a seed in medusa.js V2

### ISSUE THREAD

**Issue by superzaky** [medusajs/medusa#8399]
### Describe the bug
I am getting the following error, see screenshot :
![image](https://github.com/user-attachments/assets/813ce506-462d-4235-b35c-46470acd8a0a)

I typed in Powershell the following command:
`npm run seed`

Which then executes this command for me as stated in package.json:
`"seed": "medusa exec ./src/scripts/seed.ts"`

However, seeding does not work as seen in the aforementioned screenshot unfortunately. Could someone perhaps help me? Thanks in advance.

### System information
Medusa version (including plugins): Medusa v2
Node.js version: 22.5.1
Database: PostgreSQL
Operating system: Windows

### Code
In case you want to see my code, then you can find it on the following link:
https://github.com/superzaky/webshop_Zaky

**Comment by olivermrbl** [comment]
@superzaky, can you please ensure migrations have been run:
```
npx medusa migrations run
```

**Comment by superzaky** [comment]
> @superzaky, can you please ensure migrations have been run:
> 
> ```
> npx medusa migrations run
> ```

@olivermrbl I already ran the migrations, but I still keep getting the same error..

**Comment by olivermrbl** [comment]
Can you also try to sync your module links? It seems to be a missing link between region and payment providers.
```
npx medusa links sync
```

**Comment by superzaky** [comment]
> Can you also try to sync your module links? It seems to be a missing link between region and payment providers.
> 
> ```
> npx medusa links sync
> ```

I did what you just said, and now I get a different error:
![image](https://github.com/user-attachments/assets/f2acc69f-7c49-403b-b825-f2579cd42b7d)

My review service : 

```
import { MedusaService } from "@medusajs/utils"
import review from "./models/review";

class ReviewService extends MedusaService({
  review
}) {

}

export default ReviewService
```

**Comment by olivermrbl** [comment]
Did you check what the error message suggests might be the problem? That is, an issue with the use of id on your review model.

**Comment by superzaky** [comment]
> Did you check what the error message suggests might be the problem? That is, an issue with the use of id on your review model.

Thanks got it working now, so it seems no issue at all then :)
