### ISSUE TITLE
Event Bus : Processing undefined which has 0 subscribers (V2.0)

### ISSUE THREAD

**Issue by Attachai77** [medusajs/medusa#8403]
### Describe the bug

I was having issue using `@medusajs/event-bus-redis` in V2.0.  I am not sure my medusa-config is correct or not, I added it same as v1.

- I've got this following logs when run project.  I'm not sure what I did wrong for `redisUrl not found. A fake redis instance will be used.
`
<img width="575" alt="Screenshot 2567-08-02 at 12 35 01" src="https://github.com/user-attachments/assets/3b30029d-c5a3-463b-9162-6cd72a84c773">

- Also when I tried to trigger event by updating product , I got this logs `info:    Processing undefined which has 0 subscribers`  It seems like can not detect the event. 
<img width="467" alt="Screenshot 2567-08-02 at 12 36 38" src="https://github.com/user-attachments/assets/315f8459-2341-41a7-b856-bc0301561279">

### System information

Medusa version (including plugins): Medusa v2 preview.  (@medusajs/event-bus-redis: "preview")
Node.js version:  v20.12.2
Database: postgres
Operating system: Mac OS
Browser (if relevant): Chrome

### Steps to reproduce the behavior

1. Create Medusa v2 via this command `npx create-medusa-app@preview`
2. Set up Redis for event-bus
3. Install `@medusajs/event-bus-redis`
4. Update event-bus config in medusa-config.js following here
```
module.exports = defineConfig({
  projectConfig: {
    databaseUrl: process.env.DATABASE_URL,
    http: {
      storeCors: process.env.STORE_CORS,
      adminCors: process.env.ADMIN_CORS,
      authCors: process.env.AUTH_CORS,
      jwtSecret: process.env.JWT_SECRET || "supersecret",
      cookieSecret: process.env.COOKIE_SECRET || "supersecret",
    },
  },
  modules: {
    [Modules.EVENT_BUS]: {
      resolve: '@medusajs/event-bus-redis',
      options: {
        redisUrl: process.env.REDIS_URL || 'redis://localhost:6379'
      },
    },
  },
  ```
5. Go to Admin dashboard and to update a product
6. See `Processing undefined which has 0 subscribers`

### Expected behavior
When I avoid using   `@medusajs/event-bus-redis` so it works.  I understand that it switch to use `event-bus-local`.
<img width="514" alt="Screenshot 2567-08-02 at 13 09 31" src="https://github.com/user-attachments/assets/ffc8adb9-c740-40fc-8442-e0ba026f1b5d">

**Comment by olivermrbl** [comment]
@Attachai77, thanks for highlighting this. We'll investigate and resolve it asap.
