### ISSUE TITLE
`isLocalMedusaProject` failing in docker-compose setup. Can't run migrations

### ISSUE THREAD

**Issue by drewdecarme** [medusajs/medusa#841]
Hey there,

I'm in the process of creating a Medusa commerce store using docker and I'm running into a little trouble with the CLI execution in docker. More specifically, the CLI seems to be failing on the `isLocalMedusaProject` check.

https://github.com/medusajs/medusa/blob/1de0b28f386bfab62cf4a352acd3e40aec6e5b92/packages/medusa-cli/src/create-cli.js#L305

I'm using Yarn Berry or yarn v3 with plug and play. Postgres and Redis are being created fine and the Medusa CLI itself is being called fine, however, it cannot find the command to migrate the DB and it keeps printing out the migration CLI help instructions.

```
backend_1   | ╔════════════════════════════════════════════════════════════════════════╗
backend_1   | ║                                                                        ║
backend_1   | ║   Medusa collects anonymous usage analytics                            ║
backend_1   | ║   to help improve Medusa for all users.                                ║
backend_1   | ║                                                                        ║
backend_1   | ║   If you'd like to opt-out, you can use `medusa telemetry --disable`   ║
backend_1   | ║                                                                        ║
backend_1   | ║                                                                        ║
backend_1   | ╚════════════════════════════════════════════════════════════════════════╝
backend_1   | medusa migrations [action]
backend_1   | 
backend_1   | Migrate the database to the most recent version.
backend_1   | 
backend_1   | Options:
backend_1   |   --verbose                Turn on verbose output  [boolean] [default: false]
backend_1   |   --no-color, --no-colors  Turn off the color in output  [boolean] [default: false]
backend_1   |   --json                   Turn on the JSON logger  [boolean] [default: false]
backend_1   |   --action  [required] [choices: "run", "show"]
backend_1   |   -h, --help               Show help  [boolean]
backend_1   |   -v, --version            Show version number  [boolean]
backend_1   | TypeError: cmd is not a function
backend_1   |     at /app/.yarn/cache/@medusajs-medusa-cli-npm-1.1.23-ba7728ccd1-2b7f1ca793.zip/node_modules/@medusajs/medusa-cli/dist/create-cli.js:205:14
backend_1   |     at /app/.yarn/cache/@medusajs-medusa-cli-npm-1.1.23-ba7728ccd1-2b7f1ca793.zip/node_modules/@medusajs/medusa-cli/dist/create-cli.js:108:24
```

I've traced it to this line in the medusa CLI: https://github.com/medusajs/medusa/blob/1de0b28f386bfab62cf4a352acd3e40aec6e5b92/packages/medusa-cli/src/create-cli.js#L46

```js
function resolveLocalCommand(command) {
    if (!isLocalProject) {
      cli.showHelp()
    }

    try {
      const cmdPath = resolveCwd.silent(
        `@medusajs/medusa/dist/commands/${command}`
      )
      return require(cmdPath).default
    } catch (err) {
      cli.showHelp()
    }
  }
```

Here's the repo: https://github.com/drewdecarme/the-montessori-woodshop

Clone the repo and run `docker-compose build` and `docker-compose up`. Any help or guidance on how to allow my migrations to run would be great.

**Comment by Manoj0Marmat** [comment]
@drewdecarme need .env file to perform docker-compose commands 
unavailable in the repo provided.

**Comment by pKorsholm** [comment]
The issue is that you have not run `npm install` which is required since you dont have any packages installed in your backend docker container

You can include an `npm install` statement in your `entrypoint.sh` in your backend and it should be working then 😄

**Comment by drewdecarme** [comment]
@Manoj0Marmat I added a `.env-sample` to the repo. It uses the standard environment variables that Medusa suggests so there are no real secrets exposed. Copy over the file to the `.env` file `cp .env-sample .env` and then try running it again.

@pKorsholm So I'm using Yarn Berry, with PlugNPlay modules so the module resolution is a little different. In Yarn Berry or Yarn Modern of V3 or whatever they're calling it these days, all modules that are used are zipped up under the `.yarn/` directory, which I'm copying over in my `Dockerfile` file.

When running `yarn install` in the Dockerfile, yarn removes all of the cached dependencies that aren't being used which leans out the docker container when using workspaces. I tried `yarn install` in the `entrypoint.sh` to no avail.

**I guess my next question is... why checks in the CLI?** Also, there may be an opportunity to enhance some error handling, especially in the `isLocalMedusaProject` function where the catch block doesn't emit any useable or next steps errors.

**Comment by drewdecarme** [comment]
I guess the more I look at it now, has to do with how the `resolve-cwd` package is resolving that dynamically referenced command in the CLI. According to their documentation...

```
resolveCwd.silent(moduleId)
Returns undefined instead of throwing when the module can't be found.
```

If the package comes back as undefined then that function, `resolveLocalCommand` should most likely throw an error instead of returning undefined.

**Comment by drewdecarme** [comment]
Sorry for the spamming here, but I was able to successfully run the migrations when I switched back over to npm. Here's a copy of my `entrypoint.sh`. I commented out the yarn specific code and added in regular standard ol npm commands.

```
#!/bin/sh

cd /app

echo "Yarn Version:"
yarn --version

echo "Installing dependencies..."
# yarn install
npm install --no-package-lock --only production

echo "Running migrations..."
# yarn workspace @woodshop/backend migrate
npm run migrate -w @woodshop/backend
```

So my guess in the comment above about the dynamic package resolution being an issue in the `resolveLocalCommand` is most likely right. I think that if the modules we're required / imported at the beginning of the file rather than added dynamically in that function, this wouldn't be an issue anymore and I'd be able to continue using the newer version of yarn and its Zero Install feature.

Would any maintainers be open to a PR for this? Or at least confirming that what I'm sniffing is right?

**Comment by pKorsholm** [comment]
Dont worry about spamming 😄  wrgt. your proposition as to why this issue occurs it sounds right that with no direct dependencies to `medusajs` it removes the dependency, since the error occurs when it is not found. 

We would love to take a look at it, but none of us has experience with yarn berry and workspace, so we cant promise anything regarding how long it will take to fix 😅

**Comment by Manoj0Marmat** [comment]
@pKorsholm hello sir can you guide me 🥺 I wanna contribute 🥺 want to learn more. I'll do your work 🥺

**Comment by pKorsholm** [comment]
Hi @Manoj0Marmat 

We have a [discord community](https://discord.com/invite/xpCwq3Kfn8) where a lot of stuff is going on 😄  I would advise you to join there and drop a message in the introductions channel and we can give you an introduction to medusa and get you started 😄

**Comment by Manoj0Marmat** [comment]
@pKorsholm thank you 😍
