### ISSUE TITLE
Overlap UI issue in admin when scheduling gift cards

### ISSUE THREAD

**Issue by blanklob** [medusajs/medusa#8421]
### Describe the bug

When trying to create a new gift card, there is a mini UI overalapping issue prevent date selection in the UI. 

### System information

Medusa version (including plugins): medusa v1.20.8, medusa/admin v7.1.15 and 
Node.js version: v20
Database: postgres neon
Operating system: Macintosh; Intel Mac OS X 10_15_7

### Screenshots

If applicable, add screenshots to help explain your problem

<img width="1018" alt="Capture d’écran 2024-08-02 à 20 25 16" src="https://github.com/user-attachments/assets/fcc41add-4f42-4dfd-97cd-fd97c2e6eaff">

**Comment by olivermrbl** [comment]
@blanklob, thanks for reporting this. We will attend to this asap. 

Feel free to send a PR for it, if you are up for it :)

**Comment by MEClouds** [comment]
Actually, I fixed it in #8245

**Comment by MEClouds** [comment]
Actually, I fixed it in #8245 

![Screenshot_20240813_172031_GitHub.jpg](https://github.com/user-attachments/assets/5c140c11-45cc-4e31-bafc-542f02b7e4de)
