### ISSUE TITLE
Strategies not loaded in worker mode in v1

### ISSUE THREAD

**Issue by SGFGOV** [medusajs/medusa#8427]
### Describe the bug

The batch processing strategy wasn't loaded in the worker mode.  It reported unable to find .. "strategy name"  

warn:    An error occurred while processing batch.created: Error: Unable to find a BatchJob strategy with the type batch-strategy-name

### System information

Medusa version (including plugins):1.20.7
Node.js version: 18+
Database: Postgres 13
Operating system: Linux
Browser (if relevant): NA

### Steps to reproduce the behavior

Create a batch process using the server
The worker will not find it. 

### Expected behavior

The worker had to execute the batch process

**Comment by olivermrbl** [comment]
I am not sure this is an issue with the `worker_mode`. Strategies are loaded regardless of what mode the server is running in. 

Can you provide a repro?

**Comment by SGFGOV** [comment]
Sure.. you just need to start a batch process via the worker. Rather it won't start.  Inserted it throws an error like the one above

**Comment by olivermrbl** [comment]
Unfortunately, I can't help you with the information provided. Closing until further has been shared.
