### ISSUE TITLE
Custom state pseudo classes have been changed from ":--webkit-search-cancel-button" to ":state(webkit-search-cancel-button)". See more here: <URL>

### ISSUE THREAD

**Issue by sheraz4196** [medusajs/medusa#8438]
I have created a medusa app. And having those bugs regarding webkit and pseudo classes.

Custom state pseudo classes have been changed from ":--webkit-search-cancel-button" to ":state(webkit-search-cancel-button)". See more here: <URL>

I have checked an issue, but there reply was that, they will update it soon, and medusa can'r do anything unless they update it.

But now it is updated there and error is clearly saying has been changed.

So medusa, please fix it asap. Thanks.!!

**Comment by olivermrbl** [comment]
Can you provide reproducible steps please? :)

Closing until further details have been provided.
