### ISSUE TITLE
Can't skip to next line for Product Description

### ISSUE THREAD

**Issue by HarleySalas** [medusajs/medusa#8459]
### Describe the bug

Upon creating a product and adding a description, while typing in the product `Description` field, pressing `enter`, or `shift+enter` will cause you to go from the `Details` tab to the next form step, `Organize`, rather than skipping to the next line.

### System information

Medusa version (including plugins): `preview-20240803120600`
Node.js version: `22.2.0`
Database: `Postgres 16.3`
Operating system: `Linux Mint 21.3 Cinnamon`
Browser (if relevant): `Chrome Version 126.0.6478.114 (Official Build) (64-bit)`

### Steps to reproduce the behavior

1. Create a product
2. Type some words in the description field
3. Press `shift+enter`

### Expected behavior

Pressing enter or shift+enter should cause you to go to the next line, not proceed to the next step in the form.

### Screenshots

![image](https://github.com/user-attachments/assets/474a5a38-eee2-46be-8285-d5e3dd94d745)

**Comment by olivermrbl** [comment]
Thanks for reporting this. 

We will revisit the UX around form submission in the near future. The change of the behavior will be:
- CMD + Enter -> Submit form
- Enter -> New line in certain fields, like the description area
