### ISSUE TITLE
Notification service was not triggering

### ISSUE THREAD

**Issue by BorisKamp** [medusajs/medusa#8464]
Hey! using medusa `1.20.9` I released to production yesterday evening. Today I heard from my client that some stuff was not working. After some research I found out that no events were emitted (or picked up), normally I see stuff like this in the logs on production:

`{"level":"info","message":"Processing draft_order.created which has 1 subscribers","timestamp":"2024-08-06 09:18:17"}`
But this was **not the case now**.

I changed a line of code, redeployed and it was working again, my subscribers worked again.

Does this sound familiar? It's pretty concerning and I would like to figure out what went wrong here.

**Comment by olivermrbl** [comment]
> I changed a line of code, redeployed and it was working again, my subscribers worked again.

Do you mean you reverted to version 1.20.8 and everything worked as expected? Or what line of code did you change?

**Comment by olivermrbl** [comment]
Closing this until further information has been shared.

**Comment by BorisKamp** [comment]
> > I changed a line of code, redeployed and it was working again, my subscribers worked again.
> 
> Do you mean you reverted to version 1.20.8 and everything worked as expected? Or what line of code did you change?

Sorry for my late reply @olivermrbl . I just added a `console.log` statement in my code so I could commit and deploy again. After that it worked again.
