### ISSUE TITLE
create-medusa-app should not make assumptions about database name

### ISSUE THREAD

**Issue by techtegritycs** [medusajs/medusa#8494]
## Bug report
`npx create-medusa-app` will ask for a **Postgres username** and a **Postgres password** , it never asks for a postgres database. it assumes the username is the database and requires there to be a database table that has the same name as the database user. this should not be required, and or assumed. either ask for the database or dont require the database name to match the username, espcially since none of that matters anyway, because the `npx create-medusa-app` creates its own database with the name medusa-xxxx

**Comment by shahednasser** [comment]
Thank you for reporting this issue @techtegritycs , will look into it soon!
