### ISSUE TITLE
Upload files in production using @medusajs/file-s3@preview doesn't work (MinIO)

### ISSUE THREAD

**Issue by chasie** [medusajs/medusa#8498]
### Describe the bug

Doesn't work uploading media @medusajs/file-s3@preview on local MinIO bucket

### System information

Medusa version (including plugins):
Node.js version: v20.16.0
Database: PostgreSQL 16
Operating system: Ubuntu 22.04.4 LTS
Browser (if relevant):

### Steps to reproduce the behavior

1. [Install MinIO](https://min.io/docs/minio/linux/index.html).
2. Change port to 9001 using the [console address](https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#minio.server.-console-address) and [address](https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#minio.server.-address) CLI options.
3. Create [MinIO access and secret access key](https://min.io/docs/minio/linux/administration/console/security-and-access.html#id1).
4. Create a [MinIO bucket](https://min.io/docs/minio/linux/administration/console/managing-objects.html#creating-buckets) with public access policy:
5. Go to the bucket's dashboard.
Under the Summary section, click on the pencil icon next to Access Policy.
In the pop-up, choose Custom from the dropdown.
In the editor, enter the following:
6. MinIO server setuped
7. Create Product without Media
8. Go to product created in step 7
9. In product go to 'Media' section
10. Click 'Add Media' 
11. Upload Image
12. Click 'Save'
### Expected behavior

Upload and saved Media to product

### Screenshots
<img width="1493" alt="Снимок экрана 2024-08-08 в 11 33 21" src="https://github.com/user-attachments/assets/28383813-b173-4a26-9477-98de3e0693b4">
<img width="1493" alt="Снимок экрана 2024-08-08 в 11 35 13" src="https://github.com/user-attachments/assets/87112755-6345-427d-919f-5ff95fc1e7ec">
<img width="1493" alt="Снимок экрана 2024-08-08 в 11 35 25" src="https://github.com/user-attachments/assets/313cfd52-ff46-409a-a456-3bc7fbba89ff">

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

Error:
```
error:   getaddrinfo ENOTFOUND ecommerce.minio-server.domain.com
Error: getaddrinfo ENOTFOUND ecommerce.minio-server.domain.com
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'ecommerce.minio-server.domain.com',
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
error:   getaddrinfo ENOTFOUND ecommerce.minio-server.domain.ru
{
  message: 'getaddrinfo ENOTFOUND ecommerce.minio-server.domain.com',
  name: 'Error',
  stack: 'Error: getaddrinfo ENOTFOUND ecommerce.minio-server.domain.com\n' +
    '    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)\n' +
    '    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)',
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'ecommerce.minio-server.domain.com',
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```
My '.env' file:
```
MEDUSA_ADMIN_ONBOARDING_TYPE=nextjs
STORE_CORS=https://opt-test.domain.com,https://docs.medusajs.com
ADMIN_CORS=https://hub-test.domain.com,https://docs.medusajs.com
AUTH_CORS=https://hub-test.domain.com,https://opt-test.shermadini-house.com,https://docs.medusajs.com
MEDUSA_ADMIN_ONBOARDING_NEXTJS_DIRECTORY=test-prod-create-storefront
REDIS_URL=<REDACTED>
JWT_SECRET=<REDACTED>
COOKIE_SECRET=<REDACTED>
DATABASE_URL=<REDACTED>
POSTGRES_URL=<REDACTED>
PORT=9012
MEDUSA_BACKEND_URL=https://hub-test.domain.com
S3_FILE_URL=https://minio-server.domain.com:9001/ecommerce
S3_ACCESS_KEY_ID=<REDACTED>
S3_SECRET_ACCESS_KEY=<REDACTED>
S3_REGION=us-east-1
S3_BUCKET=ecommerce
S3_ENDPOINT=https://minio-server.domain.com:9001/
```
My 'medusa-config.js':
```
import { loadEnv, defineConfig, Modules } from '@medusajs/utils'
import commonjs from 'vite-plugin-commonjs'

loadEnv(process.env.NODE_ENV, process.cwd())

module.exports = defineConfig({
  projectConfig: {
    redisUrl: process.env.REDIS_URL,
    databaseUrl: process.env.DATABASE_URL,
    http: {
      storeCors: process.env.STORE_CORS,
      adminCors: process.env.ADMIN_CORS,
      authCors: process.env.AUTH_CORS,
      jwtSecret: process.env.JWT_SECRET || "supersecret",
      cookieSecret: process.env.COOKIE_SECRET || "supersecret",
    }
  },
  admin: {
    backendUrl: process.env.MEDUSA_BACKEND_URL,
    vite: () => ({
      plugins: [
        commonjs({
          filter: (id) => /node_modules\/react-nestable/.test(id),
        }),
      ],
    }),
  },
  modules: {
    [Modules.CACHE]: {
      resolve: "@medusajs/cache-redis",
      options: {
        redisUrl: process.env.REDIS_URL,
      },
    },
    [Modules.EVENT_BUS]: {
      resolve: "@medusajs/event-bus-redis",
      options: {
        redisUrl: process.env.REDIS_URL,
      },
    },
    [Modules.WORKFLOW_ENGINE]: {
      resolve: "@medusajs/workflow-engine-redis",
      options: {
        redis: {
          url: process.env.REDIS_URL,
        },
      },
    },
    [Modules.FILE]: {
      resolve: "@medusajs/file",
      options: {
        providers: [
          {
            resolve: "@medusajs/file-s3",
            id: "s3",
            options: {
              file_url: process.env.S3_FILE_URL,
              access_key_id: process.env.S3_ACCESS_KEY_ID,
              secret_access_key: process.env.S3_SECRET_ACCESS_KEY,
              region: process.env.S3_REGION,
              bucket: process.env.S3_BUCKET,
              endpoint: process.env.S3_ENDPOINT,
              // other options...
            },
          },
        ],
      },
    },
  }
})
```
Add any other context about the problem here

**Comment by HarleySalas** [comment]
If this is a self-hosted minio, you'll need to set a region on it and ensure that region matches, I believe. I could be wrong about that part; maybe `us-east-1` works as default?

However, what I'm certain that you *are missing* is `forcePathStyle`. Here is my config, which has worked for Minio, as well as a couple other S3 compatible options:
```
if (process.env.S3_ACCESS_KEY) {
  modules[Modules.FILE] = {
    resolve: "@medusajs/file",
    options: {
      providers: [
        {
          resolve: "@medusajs/file-s3",
          id: "s3",
          options: {
            file_url: process.env.S3_URL,
            access_key_id: process.env.S3_ACCESS_KEY,
            secret_access_key: process.env.S3_SECRET_KEY,
            region: process.env.S3_REGION,
            bucket: process.env.S3_BUCKET,
            endpoint: process.env.S3_ENDPOINT,
            additional_client_config: {
              forcePathStyle: true,
            },
          },
        },
      ],
    },
  };
}
```
I believe you may need that `id: "s3"` as well. Start with the `forcePathStyle`, then try changing your region and if it still isn't working, try adding the `id`.

**Comment by chasie** [comment]
@HarleySalas  Thank you so much, you have saved me quite a lot of time :)
I added `forcePathStyle ` and it solved my problem
