### ISSUE TITLE
Porting Omnipay

### ISSUE THREAD

**Issue by WinterSilence** [medusajs/medusa#850]
[Omnipay](https://omnipay.thephpleague.com) supports over 200 payment gateways. If you porting [Omnipay API](https://github.com/thephpleague/omnipay-common) to JS, then you can fast port any gateway package.

**Comment by olivermrbl** [comment]
Thanks for showing interesting! Feature requests have been moved to GitHub Discussions, so will close this one. Please open a new discussion if you are still interested in an Omnipay plugin :)
