### ISSUE TITLE
Error with Restock Notifications Plugin

### ISSUE THREAD

**Issue by abdulbasit-appsensus** [medusajs/medusa#8503]
### What Medusa version and documentation are you using?

v1

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I have followed this documentation: https://docs.medusajs.com/plugins/other/restock-notifications.

- Installed the library plugin
- add the specified code in medusa.config plugins
- run migrations

But when i start my server, im having an error that : 
```
error:   Error starting server
AwilixResolutionError: Could not resolve 'restockNotificationModel'.
```
![image](https://github.com/user-attachments/assets/5ac06e6d-b569-4b5e-bbe6-a99b87753d84)

**Comment by olivermrbl** [comment]
@abdulbasit-appsensus, a new version is out. Please give it a spin when time allows for it.
