### ISSUE TITLE
Medusa migrations run missing tables

### ISSUE THREAD

**Issue by bytevault** [medusajs/medusa#8531]
### Describe the bug

Medusa migrations run does not create all necessary tables for seeding

### System information

Medusa version (including plugins): 2.0.4-preview
Node.js version: 20.16
Database: Postgres 16.2
Operating system: MacOS

### Steps to reproduce the behavior

1. npx create-medusa-app@preview
2. table count - 124
3. delete database
4. npx medusa migrations run
5. table count - 107
6. See below for differences

```
[
  'link_module_migrations',
  'cart_payment_collection',
  'cart_promotion',
  'publishable_api_key_sales_channel',
  'location_fulfillment_provider',
  'product_variant_price_set',
  'location_fulfillment_set',
  'order_cart',
  'order_fulfillment',
  'order_payment_collection',
  'product_variant_inventory_item',
  'product_sales_channel',
  'return_fulfillment',
  'shipping_option_price_set',
  'order_promotion',
  'sales_channel_stock_location',
  'region_payment_provider'
]

```

### Expected behavior

Migrations should create all necessary tables

### Discussion
If this is the expected behaviour of migrations, then what extra steps are required to construct the database? What is **create-medusa-app** doing differently than **medusa migrations run** that resulted the difference?

**Comment by thetutlage** [comment]
Can you please run `medusa links sync` command and see if the tables count is same as new medusa app?

**Comment by bytevault** [comment]
This worked, for reference [Module Links](https://docs.medusajs.com/v2/advanced-development/modules/module-links#2-sync-links)
