### ISSUE TITLE
min_quantity and max_quantity not set when trying to update variant prices

### ISSUE THREAD

**Issue by BeyondOT** [medusajs/medusa#8536]
### Describe the bug

The min_quanity and max_quantity are always null even when request clearly has them.

### System information

Medusa version (including plugins): 1.20.9
Node.js version: v20.16.0
Database: Postgresql
Operating system: Windows 11
Browser (if relevant):

### Steps to reproduce the behavior

1. Use the useAdminUpdateVariant hook provided by medusa-react.
```typescript 
const updateVariant = useAdminUpdateVariant(product.id);
```
2. try to update the variant
```typescript

const data: ProductVariantPricesUpdateReq[] = [
      {
        amount: 6500,
        min_quantity: 1,
        max_quantity: 20,
        currency_code: "mad",
      },
    ];

    updateVariant.mutate(
      { variant_id: variant.id, prices: data, metadata: { is_b2b: is_b2b } },
      {
        onSuccess: ({ product }) => {
          notify.success("Success", "Product updated");
        },
        onError: ({ message }) => {
          notify.error("Failed", message);
        },
      }
    );
```

### Expected behavior

For the price that was updated to have the min_quantity and max_quantity set 1 and 20.

### Current behavior

The amount changes correctly but the min_quantity and max_quantity are null.

### Screenshots

![image](https://github.com/user-attachments/assets/8a491775-ce8e-4c86-b1bc-559699b50f4d)

### Additional info

I also tried to create a custom api route and post to that and use the productVariantService instead but the issue remains the same, neither productVariantService.upsertCurrencyPrices() nor productVariantService.updateVariantPrices work as expected.

**Comment by neehhaa06** [comment]
Hello @BeyondOT :)

```
Ensure `min_quantity` and `max_quantity` are correctly included in the request payload and debug the Medusa backend to confirm these values are received and processed. Check the database schema to ensure these fields can be updated. If needed, patch the Medusa code and test to confirm the fix.
```

**Comment by BeyondOT** [comment]
Hello @neehhaa06 , thank you for your reply. 

As I mentioned in the issue above I have already ensured that the payload contains min_quantity and max_quantity. I also ensured that the backend does recieve these values. 
I also tried to go through the service reponsible for the update directly, by creating a custom api route and using the productVariantService but still the results are exactly the same.
I haven't tried changing the core code itself to see if I can fix it because I don't really know how I can access that code in my dev environment.

**Comment by neehhaa06** [comment]
Hello @BeyondOT :)

Have you gone through these steps?

```
Clone the Repository: git clone https://github.com/medusajs/medusa.git

Install and Start: Use npm install and then npm run develop

Make Core Modifications: Update the necessary files within the repository

Link to Your Project: Execute npm link in the Medusa folder, followed by npm link medusa in your project directory

Test and Commit: Test your changes and then choose to either revert or commit them
```
