### ISSUE TITLE
Unable to override default emailpass auth provider module

### ISSUE THREAD

**Issue by bytevault** [medusajs/medusa#8542]
Medusa Version: 2.0.4-preview

Right now I'm facing the issue of migrating users from other platforms (firebase, cognito) to mine without asking them to reset password. Because others use different hash functions. I would like to override this using my own emailpass provider. 

I can't figure out a workaround for this. Adding my own emailpass provider to the auth configs won't work, because it would always resolve to the first provider with id 'emailpass', which is hard coded to be the first in array.

And I can see that in [auth provider loader](https://github.com/medusajs/medusa/blob/73cc66905aaa01bcb47fe5c988c29ae179ec4ed4/packages/modules/auth/src/loaders/providers.ts), comment on line 36 says:
```ts
// Note: For now we want to inject some providers out of the box
const providerConfig = [
    {
      resolve: EmailPassProvider,
      id: "emailpass",
    },
    ...(options?.providers ?? []),
  ]
```

When will this be removed? I think it could be put in the config file by default instead of in the auth module?

I also created a discussion thread, not sure if this is a bug or feature request. Response in either would be great. 
#8541

**Comment by sradevski** [comment]
Hey @ByteVault thanks for the report! I think this is a perfectly valid use-case, and the only reason we hard-coded the email pass provider is just to make it a bit easier for people to get started with Medusa. However, now that we have a default config in place, maybe we can remove the default provider and allow you to fully configure the providers, similar to other modules.

We'll keep you updated 👍
