### ISSUE TITLE
Medusa Book link Broken

### ISSUE THREAD

**Issue by tkejr** [medusajs/medusa#8543]
### What Medusa version and documentation are you using?

v1

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

When I try to access [Medusa Book](https://medusa-docs-v2-git-docs-v2-medusajs.vercel.app/) from https://docs.medu
![Screenshot 2024-08-09 at 7 19 57 PM](https://github.com/user-attachments/assets/ab4a414a-8952-4101-b2cd-5130777c30de)
sajs.com/v2/resources. It shows 

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch! Will fix it 👍🏻
