### ISSUE TITLE
remove redis it's no longer open source it's a waste of time 

### ISSUE THREAD

**Issue by sanba-anass** [medusajs/medusa#8544]
### System information

Medusa version (including plugins):
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by sradevski** [comment]
Thanks for the ticket. Feel free to not use Redis, you can easily implement modules that don't use Redis.
