### ISSUE TITLE
@medusajs/framework is not releasing according to other @medusajs packages

### ISSUE THREAD

**Issue by HarleySalas** [medusajs/medusa#8546]
### Describe the bug

[@medusajs/framework](https://www.npmjs.com/package/@medusajs/framework?activeTab=versions) is not publishing new versions in parallel with the other `preview` packages.

### System information
This error happened while installing the dependencies of @medusajs/medusa@1.20.6-preview-20240811120630
Medusa version (including plugins): `preview-20240811120630`
Node.js version: `22.2.0`

### Steps to reproduce the behavior

1. use `create-medusa-app`
2. remove `node_modules`
3. attempt to reinstall packages

### Expected behavior

Preview versions should match and be in sync with the rest of the `preview` releases.

### Screenshots
At the time of publishing, you can see that after `0.0.2-preview-20240811060700`, it skips 2 releases and the subsequent 2 releases attempt to use a `@medusajs/framework` version that does not exist:
![image](https://github.com/user-attachments/assets/217b44db-1442-4c26-adfb-8ade8caade5a)

![image](https://github.com/user-attachments/assets/89b38f79-6d17-411f-b4b6-4b740a435d58)

**Comment by JoeJoeyMa** [comment]
`npm i @medusajs/framework@0.0.2-preview-20240811060700`
Manual installation first

**Comment by srindom** [comment]
Does this happen with other package managers too? We currently don't directly support compatibility with pnpm

**Comment by HarleySalas** [comment]
> Does this happen with other package managers too? We currently don't directly support compatibility with pnpm

Its working with yarn. I'll just do the manual installation as suggested by Joe. I'm too stubborn with my hatred for yarn
