### ISSUE TITLE
Can't use Medusa in service workers or Cloudflare Workers due to Axios limitations

### ISSUE THREAD

**Issue by drewdecarme** [medusajs/medusa#857]
## Issue

I was interested in deploying my application in a serverless environment, more specifically Cloudflare Workers. At the moment, Axios is the HTTP library used for interacting with the Medusa API via the client that's explored from this package.

Service Workers can only operate using `fetch` and don't support `XMLHttpRequest`. In addition, the stable method for deploying Cloudflare Workers is via `service-worker`. So, unfortunately, Axios cannot be used in in PWA service workers or Cloudflare Workers.

Here's a the main issue: https://github.com/axios/axios/issues/1219

The primary maintainer of Axios [just said in October that they're going to be moving to a V1](https://github.com/axios/axios/issues/4209) which would support a `fetch based adapter in order to use it in different deployment contexts such as Cloudflare Workers. However, if you scroll down to his comment [here](https://github.com/axios/axios/issues/4209#issuecomment-949583996),

> Version 1 will very easily be a year long project, we can still add features, make fixes etc as long as we don't break anything in terms of BC.

So converting Axios is a long way out in order to use Medusa in its current state in environments that only support the `fetch` API. This is kind of a super blocker for using one of the more popular methods of deploying serverless applications.

## Potential Solutions
1. Update the instance of Axios you're using to the fork of Axios that Contentful uses, which has a patch already added to it to use fetch. Read more on the fork here: https://github.com/contentful/contentful.js/pull/396
2. Update the Medusa App to use plain old fetch instead of using Axios. This would probably require some breaking changes as that the types and a few of the interfaces would have to change surrounding errors, replies, and responses.
3. Update the client options so that fetch can be used instead of Axios without re-writing the entire module

Thoughts?

**Comment by srindom** [comment]
@drewdecarme - We are moving feature requests to GitHub Discussions to keep better track of the most requested features (using the upvote mechanism) and streamline GitHub Issues around bugs. Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!
