### ISSUE TITLE
Migration run doesn't work on docker even with sslmode=disable

### ISSUE THREAD

**Issue by FinaritrAndrianiaina** [medusajs/medusa#8570]
### Describe the bug

When I run medusa migrations run, I get 

`failed with error the server does not support ssl connections`

### System information

Medusa version (including plugins): v2.0.3-preview
Node.js version: v20
Database:
Operating system:

### Additional context

Already added sslmode=disable on the connection string

**Comment by FinaritrAndrianiaina** [comment]
So I see where is the error coming from. It should be ssl_mode=disable not sslmode=disable. I don't know if it's on purpose but I looked at this postgres documentation is sslmode [libpq-ssl]( https://www.postgresql.org/docs/current/libpq-ssl.html).

**Comment by uvlek** [comment]
With ssl_mode=disable still error

**Comment by Bogd1y** [comment]
Life saver, thanks
