### ISSUE TITLE
Storefront API: get customer payment methods is broken.

### ISSUE THREAD

**Issue by dwene** [medusajs/medusa#858]
Issue is this line:
`  const store = await storeService.retrieve(["payment_providers"])`

https://github.com/medusajs/medusa/blob/master/packages/medusa/src/api/routes/store/customers/get-payment-methods.ts#L45

Looks like `payment_providers` is not on the store model.

I was able to fix it in my custom API using `await paymentProviders.list()`

**Comment by olivermrbl** [comment]
Hi there. We highly appreciate you filing an issue and showing an interest in improving Medusa.

I apologize for the delayed response.

Moving forward, we aim to do better. But we would like to start fresh. Therefore, we are considering all older issues as stale and closing them, even though they might still be relevant.

Please don’t hesitate to re-open the issue (or create a new one) if you still need a resolution or an answer.

Thanks ❤️
