### ISSUE TITLE
Enhancement: Ability to use admin middleware in custom APIs

### ISSUE THREAD

**Issue by dwene** [medusajs/medusa#859]
It appears that right now all custom APIs are insecure by default. It would be nice if I could reuse the same middleware that the admin api uses in my custom api.

**Comment by srindom** [comment]
@dwene - We are moving feature requests to GitHub Discussions to keep better track of the most requested features (using the upvote mechanism) and streamline GitHub Issues around bugs. Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!
