### ISSUE TITLE
unused shipping_address query parameter in GET store/orders/

### ISSUE THREAD

**Issue by zakariaelas** [medusajs/medusa#860]
Hey guys, thanks for this amazing open source project!

It looks like the `shipping_address` [query param](https://github.com/medusajs/medusa/blob/master/packages/medusa/src/api/routes/store/orders/lookup-order.ts#L73-L77) is not really used in our express controller. Even the oas comments don't include it. Not sure what the initial thinking was here, perhaps should be removed for now because it pops up as an option when using the medusa-js client.

**Comment by kasperkristensen** [comment]
Yo Zak, thank you and also thank you for all of your contributions! 😁

We are aware that it is unused, but since it is used by one our customers, it would be a breaking change for them to remove it at this point.
