### ISSUE TITLE
Medusa v2 Docs: Issue in 1. Introduction - Medusa v2 Docs - Search docs Not Working

### ISSUE THREAD

**Issue by sidd-kulk** [medusajs/medusa#8621]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Tried searching for documentation for all areas in the V2 docs (https://docs.medusajs.com/v2) but it seems not to be working.  

### How can this issue be resolved?

1. Access https://docs.medusajs.com/v2
2. Try Ctrl/Cmd K and search for "Arch"
3. Does not return any results.

Actual: Should return search results.  

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch! Will look into it 👍🏻

**Comment by shahednasser** [comment]
Issue has been fixed, there was a problem with the Algolia crawler. Closing this!

**Comment by sidd-kulk** [comment]
Thanks!
