### ISSUE TITLE
promotions in Medusa v2

### ISSUE THREAD

**Issue by Snorlax-Chan** [medusajs/medusa#8632]
## Bug report
"I want to report a bug regarding promotions in Medusa v2. In the 'What items will the promotion be applied to?' section, it seems that the logic for 'in' and 'not in' filters is reversed. For example, when I want to apply a discount to a specific product like a T-shirt, I have to select 'not in' + the specified product. Shouldn't it actually be 'in' + the specified product?"
### System information

Medusa version (including plugins):
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by Snorlax-Chan** [comment]
"Additionally, the promotion does not work even when the product equals the specified product. This bug also affects product categories and product collections."

**Comment by riqwan** [comment]
Hey @Snorlax-Chan,

Thanks for reporting this! I've opened a PR to address this, should be available to use soon.
