### ISSUE TITLE
I can't deploy the medusa v2 to Railway even followed all the steps from their V2 Docs

### ISSUE THREAD

**Issue by BJR-developer** [medusajs/medusa#8644]
So there are no errors in build time, just in Deploy Logs, starting time got that's error (See in below).
I think the issues possible from here >> in **medusa-config.js**  
so in that file they use >>> `import { loadEnv, defineConfig, Modules } from "@medusajs/utils";`
` const { loadEnv, defineConfig, Modules } = require("@medusajs/utils");`

so if I use "import" way then Railway gives another error called I can't use that way , I should use type:"module" in package.json . bla bla bla many issues. then I try commonjs for import that file. now working! but looks like database are not connected! is ENV not running or working?
what kind of issues possible?

```
> medusa-starter-default@0.0.1 predeploy

> medusa migrations run && medusa links sync

[medusa-config] ⚠️ redis_url not found. A fake redis instance will be used.

[medusa-config] ⚠️ redis_url not found. A fake redis instance will be used.

Error: Failed to establish a connection to PostgreSQL. Please ensure the following is true and try again:

      - You have a PostgreSQL database running

      - You have passed the correct credentials in medusa-config.js

      - You have formatted the database connection string correctly. See below:

      "postgres://[username]:[password]@[host]:[post]/[db_name]" - If there is no password, you can omit it from the connection string

          at handlePostgresDatabaseError (/app/node_modules/@medusajs/medusa/node_modules/@medusajs/utils/dist/common/handle-postgres-database-error.js:17:15)

```

**Comment by BJR-developer** [comment]
**UPDATED:**
When I did not add any kind of Modules like S3, Stripe, etc in modules object. then it's working fine, it's deploying in the Railway...if modules object added, I got error :
```
/app/medusa-config.js:1
import { loadEnv, defineConfig, Modules } from "@medusajs/utils";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1350:18)
    at Module._compile (node:internal/modules/cjs/loader:1379:20)
    at Module._extensions..js (node:internal/modules/cjs/loader:1518:10)
    at Module.load (node:internal/modules/cjs/loader:1249:32)
    at Module._load (node:internal/modules/cjs/loader:1065:12)
    at Module.require (node:internal/modules/cjs/loader:1271:19)
    at require (node:internal/modules/helpers:123:16)
    at getConfigFile (/app/node_modules/medusa-core-utils/dist/get-config-file.js:17:24)
    at /app/node_modules/@medusajs/medusa/dist/loaders/config.js:36:52
    at /app/node_modules/@medusajs/medusa/dist/loaders/index.js:324:57

```

**Comment by BJR-developer** [comment]
Finally Error Solve. Suppose you need to install stripe or sendgrid or etc plugin . for Example I was trying to integrate the S3 Bucket as a Storage. and their npm package they said to install that **@medusajs/file-s3**
you can notice your **package.json** dependency looks like this:
 `"@medusajs/file-s3": "preview-123-blabla"` _Change that to_ >>  `"@medusajs/file-s3": "preview"`

So conclusion is You need to use version always preview. maybe this is need until they V2 completed. 

Thank you @shahednasser to making medusa as a powerful ecommerce cms & framework...

![image](https://github.com/user-attachments/assets/261ef85b-a0cd-434a-98eb-3f701ec08291)

**Comment by herawais** [comment]
railway is a nightmare
