### ISSUE TITLE
'"medusa-react"' has no exported member named 'useAdminCreateStockLocation'

### ISSUE THREAD

**Issue by EspiraMarvin** [medusajs/medusa#8645]
### Cannot start medusajs admin

I can't start the Medusajs admin, it outputs the error below
```js
'"medusa-react"' has no exported member named 'useAdminCreateStockLocation'. Did you mean 'useAdminCreateCollection'?
```
It stems from the medusa-react package

### System information

Medusa version (including plugins):
Node.js version: 20
Database: postgres
Operating system: linux
Browser (if relevant): firefox

### Steps to reproduce the behavior

1. Cloned the [medusa admin repo](https://github.com/medusajs/admin#-quickstart)
2.  Installed deps with yarn
3. Start server - yarn start
4. See error below
![image](https://github.com/user-attachments/assets/5b412759-f918-49fd-a81c-08efda3a6c1b)

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by kasperkristensen** [comment]
Hi @EspiraMarvin, the old admin repository was archived almost a year ago, and we are no longer maintaining it. We instead ship the admin dashboard as plugin for your Medusa server. See the docs for information on how to setup the plugin here - https://docs.medusajs.com/admin/quickstart.

**Comment by EspiraMarvin** [comment]
> Hi @EspiraMarvin, the old admin repository was archived almost a year ago, and we are no longer maintaining it. We instead ship the admin dashboard as plugin for your Medusa server. See the docs for information on how to setup the plugin here - https://docs.medusajs.com/admin/quickstart.

This was helpful, thanks
