### ISSUE TITLE
Medusa Learning Resources: Issue in Medusa Learning Resources

### ISSUE THREAD

**Issue by BJR-developer** [medusajs/medusa#8646]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Please mention that if something dependency like  **@medusajs/file-s3** packages you want to integrate then you need to install that package version in preview (ex: yarn add @medusajs/file-s3@preview).. so make sure packages.json file have >>>  `"@medusajs/file-s3": "preview"` ...otherwise deployment will be fail in Railway.

### How can this issue be resolved?

1.npm install @medusajs/file-s3@preview
2.
3.
...

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for reporting this! Will add a note about it in the documentation.
