### ISSUE TITLE
When will Paypal payment method be supported？

### ISSUE THREAD

**Issue by yumcc-com** [medusajs/medusa#8650]
### Describe the bug

When will Paypal payment method be supported？
![image](https://github.com/user-attachments/assets/bf2c378e-5860-4426-aca0-215f74dbc448)

### System information

Medusa version (including plugins): 2.0
Node.js version: v20.0.0
Database: 
Operating system:
Browser (if relevant):

**Comment by olivermrbl** [comment]
We don't have plans of building an official PayPal plugin any time soon, so you should not expect it for the official release at the end of the year. 

However, you are more than welcome to create your own module and share it as a package with our community. You can probably reuse a lot of the code from:
- The [Stripe 2.0 provider implementation](https://github.com/medusajs/medusa/tree/develop/packages/modules/providers/payment-stripe)
- The [PayPal 1.0 provider implementation](https://github.com/medusajs/medusa/tree/v1.x/packages/medusa-payment-paypal)

Note, we will likely not accept a PR to the core repository, but please feel free to ping me here, and we can help promote your package.
