### ISSUE TITLE
medusajs/medusa-js all response types seem incorrect.

### ISSUE THREAD

**Issue by dwene** [medusajs/medusa#866]
We're using typescript with the medusa-js client.

It appears that all the storefront api responses are mistyped.

Ex: `await client.products.list();` has response type `AxiosResponse<StoreProductsListRes>`

`AxiosResponse` has this structure
```
export interface AxiosResponse<T = any>  {
  data: T;
  status: number;
  statusText: string;
  headers: any;
  config: AxiosRequestConfig;
  request?: any;
}
```

So in order to compile typescript you have to overwrite all the types using `any`

```
const response = await client.products.list();
const products = response.data.products; // throws runtime error because response.data is undefined.
const products = (response as any).products as Product[] // works
```

**Comment by zakariaelas** [comment]
hello @dwene! Thanks a lot for taking the time to report this! 

We're aware of the type mismatch and a PR solving this has already been merged to the `develop` branch. Here are the new [types](https://github.com/medusajs/medusa/blob/develop/packages/medusa-js/src/typings.ts) returned by pretty much all our client methods. 

So once we make a new release (@olivermrbl will be able to tell you when), you'll be able to do:
```javascript
const { products, response } = await client.products.list();
// products will be of type Product[]
// response will be of type Omit<AxiosResponse, "data">

// you can also do
const { products, offset, limit, count } = await client.products.list()
```

Sorry for the inconvenience and thanks again :pray: !

**Comment by dwene** [comment]
Awesome, thanks @zakariaelas!

**Comment by olivermrbl** [comment]
Thanks for pitching in @zakariaelas!

We aim to do a new release Monday next week. :)

**Comment by octalpixel** [comment]
> Thanks for pitching in @zakariaelas!
> 
> We aim to do a new release Monday next week. :)

Next week Monday is tomorrow or the week after?

**Comment by zakariaelas** [comment]
Hey @octalpixel ! Tomorrow 👍
