### ISSUE TITLE
cannot configure db during backend creation

### ISSUE THREAD

**Issue by anipik358** [medusajs/medusa#8684]
exact same problem is occuring as was reported in 
"cannot configure db during backend creation #4272"
No solution is appropriate in the thread

**Comment by sradevski** [comment]
@anipik358 please provide more information on your setup, the steps you did, medusa version, and so on. We can't do anything with the information you included in the issue.

**Comment by anipik358** [comment]
@sradevski 
Thanks for your reply. I have added details.

Describe the bug
When trying to create the medusa backend, I cannot get past the DB creation step. Selecting continue just shows the same output. I can select 'change credentials' and enter data into the fields but it will just spit out "Could not verify DB credentials - please try again"

System information
Medusa CLI version: 1.3.23
Node.js version: v20.16.0
Database: postgreSQL
Operating system: Linux MX
Browser (if relevant): 

Steps to reproduce the behavior
run 'medusa new my-medusa-store' 
Click on 'continue' or 'change credentials'
See error
![Postgres db credential errorScreenshot_2024-08-21_13-08-10](https://github.com/user-attachments/assets/6e337f76-ce81-427e-bdcf-16c5f7eaf402)
![Postgres db credential error 2 Screenshot_2024-08-21_13-08-10](https://github.com/user-attachments/assets/1ededff2-6f30-4307-af96-a0be1781bbaf)

It seems that the credentials can't be saved, I tried hard coding them also but that didn't help. 
Postgres was not running, which should be expected as credentials were not added.
I was able to get the 7001 browser to load but cannot log in.

**Comment by anipik358** [comment]
It seems the DB created with no users, so it had to be manually removed and a new one created manually with a user so users could be added.
