### ISSUE TITLE
Medusa Service factory returns incorrect type for models that end with 's' letter

### ISSUE THREAD

**Issue by vholik** [medusajs/medusa#8704]
### Describe the bug

I have created productAttributes module with the model `product-attributes`. The type of the `productAttributesModuleService` contains methods like `createProductAttributess` (notice 2 's' in the end) but once you try to use these methods you would get this error :
```
error:   service.createProductDetailss is not a function
```

so you should change it to `service.createProductDetails` in order to make it work but the typescript shows you an error that function does not exist in that service

### System information

Medusa version (including plugins):
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by olivermrbl** [comment]
Nice catch – one we hadn't stumbled upon ourselves yet. Will be fixed and part of a release in the near term.
