### ISSUE TITLE
Medusa Learning Resources: Issue in Relations between Payment Module and Other Modules

### ISSUE THREAD

**Issue by lexvz14** [medusajs/medusa#8707]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Link in navigation points to https://docs.medusajs.com/v2/resources/commerce-modules/payment/relation-to-other-modules. The correct link is https://docs.medusajs.com/v2/resources/commerce-modules/payment/relations-to-other-modules

### How can this issue be resolved?

Update link in documentation

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch! Will open a PR to fix it
