### ISSUE TITLE
Fix optional fields on product create

### ISSUE THREAD

**Issue by adrien2p** [medusajs/medusa#871]
Some fields, such as images, tags, variants etc..., in product creation are optional. But the usage behind make them required since undefined values are unexpected at the moment.
PR: #861

**Comment by OthmanAmoudi** [comment]
that happens with me too I tried to add a product and it fails.

steps to reproduce the bug:
1 - login as a member (/admin/auth)
2- POST request to yourstore.com/admin/products

request body:
```
{
   "title":"my product",
  "subtitle": null,
  "description": "test-product-description",
  "handle": "test-product",
  "is_giftcard": false
}
```
request response: 
```
{
	"message": "Cannot read property 'map' of undefined"
}
```

**Comment by webface** [comment]
Same issue adding custom data to an overridden product entity and service. The admin/products route validators don't allow additional fields.
body:
```
{
    "title":"File Product",
    "files":[{"url":"123456"}]
}
```

**Comment by adrien2p** [comment]
> Same issue adding custom data to an overridden product entity and service. The admin/products route validators don't allow additional fields.
> 
> body:
> 
> ```
> 
> {
> 
>     "title":"File Product",
> 
>     "files":[{"url":"123456"}]
> 
> }
> 
> ```

This is not related
