### ISSUE TITLE
Medusa v2 Docs: Issue in 4.2.2. Service Factory - Medusa v2 Docs

### ISSUE THREAD

**Issue by bansal-ashish-dev** [medusajs/medusa#8750]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Found a typo here 

listMyCustoms
### listAndCount 
retrieveMyCustom
createMyCustoms
updateMyCustoms
deleteMyCustoms
softDeleteMyCustoms
restoreMyCusto

### How can this issue be resolved?

should be listAndCountMyCustoms

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for pointing this out! However, this was intentional as there wasn't a lot of space for a full method title. We'll look into another way of resolving this if it makes sense.
