### ISSUE TITLE
npm install package version not found

### ISSUE THREAD

**Issue by boguc** [medusajs/medusa#8754]
I wanted to install packages for copy of project

Medusa version 2:
Node.js version: v22.6.0
Database: postgress
Operating system: ubuntu 22

npm install
npm error code ETARGET
npm error notarget No matching version found for @medusajs/framework@0.0.2-preview-20240824180502.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.

**Comment by 420coupe** [comment]
yarn install  with yarn -v 3.2.1
