### ISSUE TITLE
Migration failes with exit code 0

### ISSUE THREAD

**Issue by McTom234** [medusajs/medusa#8812]
### Describe the bug

When running a migration and the migration fails, the command exits with code 0. This is unsuitable for production environment pipelines.

### System information

Medusa version (including plugins): 1.20.9
Node.js version: 20
Database: postgres
Operating system: linux-ubuntu

### Expected behavior

Exit with code 1.

**Comment by olivermrbl** [comment]
Thanks for the report. However, since this is not a critical bug for Medusa v1.*, we won't be changing the current behavior.

**Comment by McTom234** [comment]
Okay @olivermrbl

Do you have another fix for that?

**Comment by olivermrbl** [comment]
What do you want to achieve?

**Comment by McTom234** [comment]
> When running a migration and the migration fails, the command exits with code 0. This is unsuitable for production environment pipelines.

The pipeline (basically a bash script) should fail with an exit code.
