### ISSUE TITLE
Duplicate customers

### ISSUE THREAD

**Issue by BorisKamp** [medusajs/medusa#8815]
Hi!

Using Medusa `1.20.9`, when I create a draft order, I sent both `email` and `customer_id` along in the body.

Due to a UI glitch I need to fix in my frontend the `customer_id` sometimes is `null` or `undefined`. The `email` is set tho, always, to an e-mail address of an existing customer. What I find unexpected is that in this case a new customer is created by Medusa with `has_account` set to `false`. Why is not checked if a customer exists with that e-mail address, and if so use that customer, else create a new one?

**Comment by olivermrbl** [comment]
That would leak data about a customer to anyone who has the email.

**Comment by BorisKamp** [comment]
> That would leak data about a customer to anyone who has the email.

I understand that from a public perspective, but in my case I use an admin endpoint which requires a API token. In that case it does not matter if the info leaks right? Since it's behing closed doors.
