### ISSUE TITLE
Server running in worker mode doesn't have health 

### ISSUE THREAD

**Issue by m0sth8** [medusajs/medusa#8825]
### Describe the bug

When medusa server is running in `workerMode: "worker"` it runs http server but doesn't setup `health` entrypoint. 
We use this entrypoint in kubernetes readiness check. 

[health route](https://github.com/medusajs/medusa/blob/v2.0.6-preview/packages/framework/framework/src/http/express-loader.ts#L69) is skipped in `worker` mode in [loadEntrypoints](https://github.com/medusajs/medusa/blob/ac18b5d35feae54cc89fa0ee614878054fe996d8/packages/medusa/src/loaders/index.ts#L81) method. 

Related PR:
#6790 

### System information

Medusa version (including plugins): v2.0.6-preview
Node.js version: 20
Database: postgres@15
Operating system: alpine linux amd64
Browser (if relevant):

### Steps to reproduce the behavior

1. Run medusa in `workerMode: "worker"`
2. Open http://localhost:9010/health/ in browser

### Expected behavior

Expected http status 200 OK response, actual response is 404 not found.

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by olivermrbl** [comment]
This is expected behavior, as worker processes do not load application entry points, including the HTTP layer. You will need to perform your readiness check differently for the worker processes. I am not very familiar with Kubernetes and their readiness probes, so I am not sure what is possible, but perhaps you can instead write a script that opens a (very) short-lived socket connection to the worker process to evaluate its health.

**Comment by m0sth8** [comment]
> This is expected behavior, as worker processes do not load application entry points, including the HTTP layer. You will need to perform your readiness check differently for the worker processes. I am not very familiar with Kubernetes and their readiness probes, so I am not sure what is possible, but perhaps you can instead write a script that opens a (very) short-lived socket connection to the worker process to evaluate its health.

It's just the whole purpose of the merged PR #6790 was to enable http server to serve health endpoint. 
So worker runs http server now but it's useless =)

**Comment by m0sth8** [comment]
fixed in #10737
