### ISSUE TITLE
bug: Promotions - Buy X get Y

### ISSUE THREAD

**Issue by 420coupe** [medusajs/medusa#8829]
### Describe the bug

The current methodology for Buy X get Y, is that it discounts according the rule set you've placed. 
For example: Buy 10 get 20

With the current structure if 10 of product X are purchased, it would reduce the price of (20  * product Y). However if you only add 10 items to the cart it will reduce the cost to a negative number. 

Shouldn't this logic actually add additional qty to cart?

I've been looking into the code for a little bit regarding this and my thought is this should be redesigned to actually add additional items to the cart. 

After looking into it, here's what i think would be required, please let me know if I'm missing a piece that's tied. 

#### new first-class vars for 
- ``addItemAdjustment`` - quantity would need to be added here
- ``cart - bonus_item_id:`` - thought for this is to be able to loop through cart. ie if i buy 100 should the buy 10 get 20 apply 10 times or once?
- ``cart`` - bonus_item_qty 
- ``order`` - bonus_item_qty

#### modify 
- ``lineItemAdjustmentsToCreate`` - to include logic for adding quantity
- ``BuyXgetY template`` - to include quantity 

#### migrations
- ``cart_line_item_adjustments`` add column (bonus_item_qty)
- ``cart_line_item_adjustments`` add column (bonus_item_id)
- ``order_item`` add column (bonus_item_qty)
- ``order_item`` add column (bonus_item_raw_qty) ? is this needed?

### System information

Medusa version (including plugins): ``@medusajs/medusa@npm:1.20.6-preview-20240827210442 [a5fee] (via npm:preview [a5fee])``
Node.js version: ``v21.7.1``
Database: ``Supabase (postgres)``
Operating system: ``Ubuntu 22.04.4 LTS``
Browser (if relevant):

### Steps to reproduce the behavior

1. Install and configure medusa backend
2. Create a new promotion - buyXgetY
3. Automatic, everyone can use the code, max 10000000
4. unlock condition - min qty 10 and product X
5. qty of items promotion will apply - 20 and product X again
6. go to storefront and add 10 of item X
7. see bug 

### Expected behavior

The buyXgetY promotion should add items to the cart and keep track of how many 'bonus' items were added. Discount functionality should work the exact same way it currently does. Adding items to cart would solve the potential possibility for negative numbers. 

### Screenshots

![image](https://github.com/user-attachments/assets/1b6f44a0-33b5-4611-94dc-22cb90b94af4)

### Additional context

I'd like some feedback from the core team around discussion of how the current buyXgetY is implemented and if how i proposed above would be the ideal or correct implementation. If so i'll go ahead and tackle updating this piece. 

additionally current configuration is not tracking the number of times the promotion has been used, or atleast not updating it

```json
{
  "id": "promo_01J61AWQCF6E5Y9D0MK6APVJXS",
  "code": "Buy10Get20",
  "is_automatic": true,
  "type": "buyget",
  "created_at": "2024-08-24T04:39:11.012Z",
  "updated_at": "2024-08-24T04:39:11.415Z",
  "deleted_at": null,
  "campaign_id": "procamp_01J61AWQCSVF0BM15TZ6E9F9ED",
  "application_method": {
    "id": "proappmet_01J61AWQCNKZH6NB28DRDWGM30",
    "raw_value": {
      "value": "100",
      "precision": 20
    },
    "apply_to_quantity": 20,
    "buy_rules_min_quantity": 10,
    "type": "percentage",
    "target_type": "items",
    "allocation": "across",
    "target_rules": [
      {
        "id": "prorul_01J61AWQSGEE69J24YBNCAFATV",
        "description": null,
        "attribute": "items.product.id",
        "operator": "eq",
        "created_at": "2024-08-24T04:39:11.416Z",
        "updated_at": "2024-08-24T04:39:11.416Z",
        "deleted_at": null,
        "values": [
          {
            "value": "prod_01J5WAY0AEQ6S6FS5Z3WG8214A"
          }
        ]
      }
    ],
    "buy_rules": [
      {
        "id": "prorul_01J61AWQSK17Z0NQJR3195S80K",
        "description": null,
        "attribute": "items.product.id",
        "operator": "eq",
        "created_at": "2024-08-24T04:39:11.418Z",
        "updated_at": "2024-08-24T04:39:11.418Z",
        "deleted_at": null,
        "values": [
          {
            "value": "prod_01J5WAY0AEQ6S6FS5Z3WG8214A"
          }
        ]
      }
    ],
    "created_at": "2024-08-24T04:39:11.008Z",
    "updated_at": "2024-08-24T05:08:23.985Z",
    "currency_code": null,
    "max_quantity": 0,
    "deleted_at": null,
    "value": 100
  },
  "rules": [],
  "campaign": {
    "id": "procamp_01J61AWQCSVF0BM15TZ6E9F9ED",
    "name": "Test 1",
    "description": "DerfTuned Digital Art - 001",
    "campaign_identifier": "DTDA-001",
    "starts_at": "2024-08-23T13:00:00.000Z",
    "ends_at": "2024-08-31T13:00:00.000Z",
    "created_at": "2024-08-24T04:39:11.006Z",
    "updated_at": "2024-08-24T04:41:06.715Z",
    "budget": {
      "id": "probudg_01J61AWQCXXMYV6QA6A4Q2WYAA",
      "type": "usage",
      "raw_limit": {
        "value": "10000000",
        "precision": 20
      },
      "raw_used": {
        "value": "0",
        "precision": 20
      },
      "created_at": "2024-08-24T04:39:11.014Z",
      "updated_at": "2024-08-24T04:41:06.715Z",
      "currency_code": null,
      "deleted_at": null,
      "limit": 10000000,
      "used": 0
    },
    "deleted_at": null
  }
}
```

**Comment by 420coupe** [comment]
Any feed back on this, or should i tackle to correctly add the additional bonuses while also discounting them ?

**Comment by riqwan** [comment]
Hey @420coupe, apologies for the delay. Thanks for surfacing this, this uncovers some important bugs that needs addressing!

Let me have a think through this, workshop and get back to you as soon as possible.

**Comment by riqwan** [comment]
Just did some investigation on this. Aside from the core issue you're addressing, this has uncovered 4 bugs:

1. when its BuyX getX (not BuyX getY), we don't differentiate between what needs to be in the cart vs where we apply the adjustments
2. discounts seems to be going over the subtotal
3. taxes seems to be going in the negatives
4. Usage doesn't seem to be accounted for

I'll create tickets for these for us to tackle in the coming week. If you'd like to address one of these yourself, let me know and we can work together on it.

**Comment by riqwan** [comment]
Regarding the core issue you're addressing here - should the workflows add an item to the cart when a BuyGet promotion is applied?

I like your suggestion, but I think this concern should be moved to the client. The cart workflows will not have enough information to know which specific variant of a product needs to be applied. With your solution, we can only do this when the promotion has a specific variant to apply, which will reduce the flexibility of the feature. 

An example, if you buy 2 tshirts, you get 1 sweater free. A sweater can have 4 variants - S, M, L & XL. The customer would have to choose which variant they'd like to add to the cart. 

We can instead add some logic in the frontend, where we hit an endpoint upon applying a buyget promotion to see if an action is necessary to be performed on the cart - the action being adding the specific variant to the cart when the promotion buy rules match. If the user already has the free item in the cart, user does nothing and the promotions apply. If its necessary to add an item to the cart, we open a popup where the customer can choose and then run the promotion application logic.

**Comment by riqwan** [comment]
Last thing, we should also potentially add some control logic to promotions that you referred to - i.e. how many times can a promotion be applied on a cart?

**Comment by 420coupe** [comment]
> Regarding the core issue you're addressing here - should the workflows add an item to the cart when a BuyGet promotion is applied?
> 
> I like your suggestion, but I think this concern should be moved to the client. The cart workflows will not have enough information to know which specific variant of a product needs to be applied. With your solution, we can only do this when the promotion has a specific variant to apply, which will reduce the flexibility of the feature.
> 
> An example, if you buy 2 tshirts, you get 1 sweater free. A sweater can have 4 variants - S, M, L & XL. The customer would have to choose which variant they'd like to add to the cart.
> 
> We can instead add some logic in the frontend, where we hit an endpoint upon applying a buyget promotion to see if an action is necessary to be performed on the cart - the action being adding the specific variant to the cart when the promotion buy rules match. If the user already has the free item in the cart, user does nothing and the promotions apply. If its necessary to add an item to the cart, we open a popup where the customer can choose and then run the promotion application logic.

I think workflow might be the right place to do it so you can additional handle multiple buyget promotions for the same product in this location to avoid what i mention below with the stackable promos and looping through cart item quantity. However my thought on where it gets added, is it actually gets added to the adjustment. Then total item quantity = line_item.qty + line_item_adjustment.qty. This way they can be tracked separately and number of ``get``  items can be queried if needed. Ie this would be useful for tax purposes as the get products can be considered a marketing expense. (just thinking much further down the line for additional tax/accounting integrations). 

Ah you're right, I didn't even think of the variant options. Yes, this should def be pushed to the client side and allow them to choose if multiple variants available, otherwise just apply if only 1 variant. 

Regarding number of times a promotion can be applied to a cart -  definitely think this should be an option when setting the promotion. My question regarding this is how would it work if you have multiple buyget promotions for the same product X, should they be stackable? This is also probably another good option to include for promotions. Though it does get tricky on looping through to make sure you don't over apply any bonuses. 

I'd be more than happy to be included in solving this so i can better learn the core code base and continue contributing to improving it.

**Comment by riqwan** [comment]
> Ie this would be useful for tax purposes as the get products can be considered a marketing expense. (just thinking much further down the line for additional tax/accounting integrations).

Currently the promotions are stackable by default. We will in the future add more controls here on whether a promo can be combined with other promos or promos of the same type.

The adjustments will contain a promotion link, this can be used to decided for when doing tax/accounting. 

> My question regarding this is how would it work if you have multiple buyget promotions for the same product X, should they be stackable? 

If you have 2 promotions applied to a cart:

1. buy X get Y
2. buy X get 50% on Y

In this case, we apply only 1. 

In this case:

1. buy X get 20% on Y
2. buy X get 25% on Y

In this case, we apply 1 & 2.

We apply the most valuable promotion first and then apply other promotions if there is a pending value to apply a promotion on.

**Comment by 420coupe** [comment]
So how would you handle tiered Buy X get X, 

ex. 
Buy 10 (product x) get 20 (product x)
Buy 50 (product x) get 100 (product x)
Buy 100 (product x) get 1000 (product x)

If customer bought 160 product x, should their bonus be 1120 + the original 160 for a total of 1280?

**Comment by riqwan** [comment]
If you've got 1280 items in the cart already, then you should get a bonus of 1120. i.e. you only pay for 160.

Its a good test to add to our test-suite.

**Comment by 420coupe** [comment]
> If you've got 1280 items in the cart already, then you should get a bonus of 1120. i.e. you only pay for 160.
> 
> Its a good test to add to our test-suite.

in my experience having the end user add the complete amount to get the bonus happens less than 1%, general customer is very very dumb. Caused a lot of headaches in previous as you had to go in and manually edit everyone's order.

**Comment by riqwan** [comment]
@420coupe we can fix that issue with a frontend hook that add them to cart

**Comment by riqwan** [comment]
We're tracking the frontend hook as a separate task internally as it requires some design and will be worked on at a later point. Feel free to reopen this if you come across more irregularities. Thanks for the help in surfacing this @420coupe and testing this! 🎉
