### ISSUE TITLE
Product Tag not saving when edit product.

### ISSUE THREAD

**Issue by juansoler** [medusajs/medusa#8886]
### System information

Medusa version (including plugins): 2.0.7 preview
Node.js version: 20.15
Database: postgres
Operating system: Ubuntu Server 22.04
Browser (if relevant): 

### Steps to reproduce the behavior

1. Go to Product Edit
2. Click on Edit Organization
3. No appear Product Tags created already.

### Expected behavior

You cannot set product tags to a product because it doesn't appear in the combobox when you're editing the product.

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by olivermrbl** [comment]
Nice catch, fixed in #8887
