### ISSUE TITLE
Error starting server with scheduled jobs due to a new change in bullmq

### ISSUE THREAD

**Issue by AndrewGold** [medusajs/medusa#8888]
### Describe the bug

In bullmq's [latest release](https://github.com/taskforcesh/bullmq/releases/tag/v5.12.12), and error is thrown when a queue is created with a colon in the name. The JobSchedulerService creates a queue with name "scheduled-jobs:queue".

### System information

Medusa version (including plugins): 1.20.6
Node.js version: 18
Database: postgres
Operating system: macOS
Browser (if relevant):

### Steps to reproduce the behavior

1. Create a scheduled job
2. Run the server

**Comment by dtduong30** [comment]
I have encountered the same issue. Here are the logs related to the bug for reference:

![Screen Shot 2024-08-30 at 5 36 43 PM](https://github.com/user-attachments/assets/bef386a2-69ca-4050-ae76-e5f90f0d8810)

**Comment by dtduong30** [comment]
It seems that the issue might be related to the version of bullMQ. To address this, I've used resolutions and overrides in my package.json to ensure specific versions are used:

```
"resolutions": {
  "@medusajs/medusa/bullmq": "5.7.1"
},
"overrides": {
  "@medusajs/medusa/bullmq": "5.7.1"
}
```

This configuration locks in the specified versions and should help resolve the issue. Please inform me of any updates or if additional changes are required.

**Comment by adevinwild** [comment]
> "resolutions": {
>   "@medusajs/medusa/bullmq": "5.7.1"
> },
> "overrides": {
>   "@medusajs/medusa/bullmq": "5.7.1"
> }

Thanks for this! 🫶
We should create a PR to fix the `scheduled-jobs:queue` name

**Comment by adevinwild** [comment]
Hey @srindom , I think we can close this one 🙌
