### ISSUE TITLE
Medusa v2 Docs: Issue in 3.11. Workflows - Medusa v2 Docs

### ISSUE THREAD

**Issue by atistrcsn** [medusajs/medusa#8904]
### What Medusa version and documentation are you using?

None

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

There is a mistake in the example naming on the following page:
https://docs.medusajs.com/v2/advanced-development/api-routes/parameters#path-parameters 

### How can this issue be resolved?

Replace the "/message/{id}" path name with the corresponding name, as: "/hello-world/{id}"

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch! Please open a PR to fix it
