### ISSUE TITLE
Add a note about trailing backslashes

### ISSUE THREAD

**Issue by renanboni** [medusajs/medusa#8920]
## Bug report
**Vendors** API always returns _Unauthorized_

### Describe the bug
I'm trying to follow the [Marketplace recipe](https://docs.medusajs.com/v2/resources/recipes/marketplace/examples/vendors), however, I came across an issue when creating the vendor (this last release cleared some confusion around it but it still doesn't work unless I'm doing something wrong).

1. Register the vendor (create its **emailpass** auth identity)
Calling the following endpoint:

**http://localhost:9000/auth/vendor/emailpass/register**
```
{
    "email": "test-medusa-js@gmail.com",
    "password": "medusajs"
}
```
Returns a jwtToken, which translates to:
```
{
  "actor_id": "",
  "actor_type": "vendor",
  "auth_identity_id": "authid_01J6MB5779FA6PD5CY0RXNRENH",
  "app_metadata": {},
  "iat": 1725112163,
  "exp": 1725198563
}
```
So far so good, as the actor_id should not be empty when the vendor entity is created, which leads me to the second step.

2. Create the vendor entity
Since now we have the token, we should be able to create the vendor entity by hitting the following endpoint:
**http://localhost:9000/vendors/**
```
Bearer token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY3Rvcl9pZCI6IiIsImFjdG9yX3R5cGUiOiJ2ZW5kb3IiLCJhdXRoX2lkZW50aXR5X2lkIjoiYXV0aGlkXzAxSjZNQjU3NzlGQTZQRDVDWTBSWE5SRU5IIiwiYXBwX21ldGFkYXRhIjp7fSwiaWF0IjoxNzI1MTEyNDQ0LCJleHAiOjE3MjUxOTg4NDR9.E0sKeD75u76qQun0Dkcdqd4o9RmQ1EoO_3ukUMVC26I
(Same as returned from the endpoint from the 1st step).
{
    "name": "MedusaJS Test Store",
    "handle": "medusa-js-test-store",
    "admin": {
        "email": "test-medusa-js@gmail.com",
        "first_name": "Medusa JS",
        "last_name": "test"
    }
}
```

This is the response:
**401**
```
{
    "message": "Unauthorized"
}

```

This is my middleware:

```
export default defineMiddlewares({
    routes: [
        {
            matcher: "/vendors",
            method: "POST",
            middlewares: [
                authenticate("vendor", ["session", "bearer"], {
                    allowUnregistered: true,
                }),
            ],
        },
        {
            matcher: "/vendors/*",
            middlewares: [
                authenticate("vendor", ["session", "bearer"]),
            ],
        },
    ],
})
```

And I might be wrong but **allowUnregistered** means that the **actor_id** can be empty.

### System information

Medusa version (including plugins): v2.0.7-preview

### Expected behavior

A vendor should be created after its auth identity has been created.

**Comment by shahednasser** [comment]
Hi @renanboni thank you for submitting this issue! I'll look into it

**Comment by shahednasser** [comment]
@renanboni I wasn't able to reproduce your issue. Can you share the exact `curl` requests your making? Also, please make sure you have the latest Medusa preview version by removing `yarn.lock` and `node_modules`, then re-installing the dependencies

**Comment by renanboni** [comment]
Hi @shahednasser thanks for your help, here are the requests I've made.

PS: I'm sure I'm using the latest version, I did what you mentioned and I was asked to add the **"@medusajs/auth-emailpass": "preview"** module, which was required only in the 2.0.7 preview version.

**1. http://localhost:9000/auth/vendor/emailpass/register**

```
curl --location 'http://localhost:9000/auth/vendor/emailpass/register' \
--header 'Content-Type: application/json' \
--header 'Cookie: connect.sid=s%3AchHMG6cSqo9s8W80DVBmNQcsn1ismXrM.fbDe7vkPz2E3ilutZ39nbDTYw4ozAh8SElsQuwyLLGM' \
--data-raw '{
    "email": "test-medusa@gmail.com",
    "password": "test"
}'
```

<< Response
```
{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY3Rvcl9pZCI6IiIsImFjdG9yX3R5cGUiOiJ2ZW5kb3IiLCJhdXRoX2lkZW50aXR5X2lkIjoiYXV0aGlkXzAxSjZSWU5KWjVWSkpZQzZOVEZaSEFQOVhDIiwiYXBwX21ldGFkYXRhIjp7fSwiaWF0IjoxNzI1MjY2ODQwLCJleHAiOjE3MjUzNTMyNDB9.tXzvYQg2Z-lK54LPzdaeViWLloOuUqp0Yjv8Xled05s"
}
```

**2. http://localhost:9000/vendors/**

```
curl --location 'http://localhost:9000/vendors/' \
--header 'Content-Type: application/json' \
--header 'Authorization: ••••••' \
--header 'Cookie: connect.sid=s%3AchHMG6cSqo9s8W80DVBmNQcsn1ismXrM.fbDe7vkPz2E3ilutZ39nbDTYw4ozAh8SElsQuwyLLGM' \
--data-raw '{
    "name": "MedusaJS Test Store 2",
    "handle": "medusa-js-test-store-2",
    "admin": {
        "email": "test-medusa@gmail.com",
        "first_name": "Medusa JS Store",
        "last_name": "test"
    }
}'
```

<< Response
```
{
    "message": "Unauthorized"
}
```

**Comment by shahednasser** [comment]
Thanks for the details @renanboni . Seems like the issue originates from using an ending backslash in `http://localhost:9000/vendors/`. Can you remove it and try again? So send a request to `http://localhost:9000/vendors`.

Will make sure to add a note about this in the docs to avoid confusion in the future.

**Comment by renanboni** [comment]
@shahednasser oooh! I can't believe I banged my head against the wall for hours over the weekend because of this hahaha, thanks a lot! - yes, updating the docs will help a lot as I've seen 4 other people with the same problem!

Thanks and have a nice week ahead!

**Comment by shahednasser** [comment]
Sorry for the confusion and thank you for reporting this! That way we can mitigate more people getting hung up on this problem 😅

Will keep this issue open to update the docs
