### ISSUE TITLE
Custom endpoint does not work and only works after saving a file that restarting the server.

### ISSUE THREAD

**Issue by balramxyadav** [medusajs/medusa#8922]
### Describe the bug

I've read a lot about similar issues, including on Discord, but nothing seems to work for me. This happens on the express route, and when I tried it with the default API routes, the issue occurs there as well. However, after I save a file, everything starts to work. Can someone help me with this?

### System information

Medusa version (including plugins): 1.20.8, medusa-plugin-wishlist
Node.js version: v20.10.0
Database: Postgres
Operating system: Mac

### Steps to reproduce the behavior

I tried to access the custom route /store/custom. It returns a 404 on the first run, but after saving the file, it starts to work and returns OK.

### Expected behavior

Custom routes to work well.

Also, many of the plugins I use don't seem to work. The wishlist plugin returns a 404, and the same happens with the rating plugin.

**Comment by balramxyadav** [comment]
Hi @adevinwild - I saw you had a similar issue. did you get a fix?

**Comment by srindom** [comment]
Hi @balramxyadav, if the file isn't saved Medusa can't find and build it so this is expected behavior.
