### ISSUE TITLE
Update Heroku CLI commands

### ISSUE THREAD

**Issue by akilesh-io** [medusajs/medusa#8925]
### What Medusa version and documentation are you using?

None

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

This command no longer works, we need to provide other valid plans **mini** is deprecated and need to provide app name:
```heroku addons:create heroku-postgresql:mini```

### How can this issue be resolved?

Use the updated CLI commands
1. `heroku addons:create heroku-postgresql --app [your app name]`

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for reporting this! Will update the docs
