### ISSUE TITLE
Metadata on product_category does not exist

### ISSUE THREAD

**Issue by lexvz14** [medusajs/medusa#8926]
## Bug report

Metadata column does not exist on the product_category table in the database. As a result, fetching categories fails.

### System information

Medusa version (including plugins): 2.0.6
Node.js version: 20+
Database: PostgreSQL
Operating system: MacOS
Browser (if relevant): N/A

### Steps to reproduce the behavior

A:
1. Make a POST request to `/admin/product-categories` with `metadata` present in the request body.
2. Note error

B:
1. Make a GET request to `/admin/product-categories` 
2. Note error

### Expected behavior
Should be able to create category with metadata AND fetch categories.

### Code snippets

Error for GET request:
```
{
    "code": "unknown_error",
    "type": "unknown_error",
    "message": "An unknown error occurred."
}
```

Error for POST request:
```
{
    "type": "invalid_data",
    "message": "column \"metadata\" of relation \"product_category\" does not exist"
}
```

Error in console of medusa backend:
```
error:   select "p0"."id", "p0"."name", "p0"."description", "p0"."handle", "p0"."is_active", "p0"."is_internal", "p0"."rank", "p0"."parent_category_id", "p0"."created_at", "p0"."updated_at", "p0"."metadata" from "public"."product_category" as "p0" where "p0"."deleted_at" is null limit 50 - column p0.metadata does not exist
InvalidFieldNameException: select "p0"."id", "p0"."name", "p0"."description", "p0"."handle", "p0"."is_active", "p0"."is_internal", "p0"."rank", "p0"."parent_category_id", "p0"."created_at", "p0"."updated_at", "p0"."metadata" from "public"."product_category" as "p0" where "p0"."deleted_at" is null limit 50 - column p0.metadata does not exist
```

**Comment by olivermrbl** [comment]
@lexvz14, it looks like you might be missing a migration. Product category metadata was added last week. 

Can I get you to try to run:
```
npx medusa db:migrate
```

**Comment by lexvz14** [comment]
Did the trick, my bad. Thank you!
