### ISSUE TITLE
[Orders Module] Translations fix

### ISSUE THREAD

**Issue by raphaelbernhart** [medusajs/medusa#8992]
### Describe the bug

As described in [here](https://docs.medusajs.com/user-guide/tips/languages) this issue is for changing of some german translations.

- "Verarbeitung" => "In Verarbeitung" ([image](https://github.com/user-attachments/assets/9a6c7819-49fd-4525-a47f-e1061069ac5c))
- "Summary" => "Zusammenfassung" - not translated ([image](https://github.com/user-attachments/assets/ec5d2fd1-fa45-4f13-94ee-ac78e8c412b3))
- "Zahlung einfangen" => "Zahlung eintragen" - "einfangen" means catch. ([image](https://github.com/user-attachments/assets/98dd98d0-4c4f-49bb-8b1b-e032647ea598))
- "Vertragserfüllung" => "Auftragserfüllung" - "Vertrag" means "contract", IMO "Auftragserfüllung" would be the better wording ([image](https://github.com/user-attachments/assets/33f2170a-d124-4da0-a26b-004bb15fa8c0))
- "Rohbestellung" => "Rohdaten" ([image](https://github.com/user-attachments/assets/dfb4acbf-c0dc-4f7e-9d12-4a5ac5c098dd))

**Comment by srindom** [comment]
Thanks for highlighting these opportunities to improve the translations. We would be happy to accept a PR with the new translation strings but will close for now as we won't be prioritizing this ourselves.

**Comment by raphaelbernhart** [comment]
> Thanks for highlighting these opportunities to improve the translations. We would be happy to accept a PR with the new translation strings but will close for now as we won't be prioritizing this ourselves.

I am also open to contributing but I am not sure where to ^^

On the website its stated that I should open an issue and on github I could not find any translations. Can you give me a hint which code to change?
