### ISSUE TITLE
Products.search fails when sales channels are turned on via public api key

### ISSUE THREAD

**Issue by SGFGOV** [medusajs/medusa#9025]
The middleware validateProductSalesChannelAssociation is called on all /products/:id irrespective of method,
s Aa result when a post request is sent to /products/search it triggers  the isProductInSalesChannels method,
which in turn triggers retrieve_

productService.retrieve_ throws an exception if the id=="search"
and then the middleware fails

possible solutions
1. use the middleware only on get requests
or 
2. modify productService.retrieve_ and productService.isProductInSalesChannels to return unknown if the id is search

Which would be the better approach ?

Medusa version: 1.20.9
node version: 18.17.1

**Comment by srindom** [comment]
You are right this is a bug, would you be up for opening a fix?

**Comment by SGFGOV** [comment]
Sure..plz tell me which branch to start from

**Comment by SGFGOV** [comment]
> Sure..plz tell me which branch to start from.. also which approach you prefer
