### ISSUE TITLE
Medusa Learning Resources: Issue in Inventory Concepts - Medusa Learning Resources

### ISSUE THREAD

**Issue by sensei-woo** [medusajs/medusa#9070]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The link first link on this page leads to a page not found link

[InventoryItem data model](https://docs.medusajs.com/v2/resources/references/inventory/models/InventoryItem)

### How can this issue be resolved?

1. simple update to the correct page or create the correct page
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch! Will open a PR to fix this
