### ISSUE TITLE
/auth/token/refresh returns error

### ISSUE THREAD

**Issue by m0sth8** [medusajs/medusa#9071]
### Describe the bug

When I use /auth/token/refresh method it returns 

```
{type: "unauthorized", message: "Could not find a auth provider with id: refresh"}
```

### System information

Medusa version: 1.20.6-preview-20240829151422
@medusajs/auth: 0.0.4-preview-20240829151422
@medusajs/auth-google: 0.0.2-preview-20240909180554
Node.js version: 20
Database: postgres
Operating system: linux

### Steps to reproduce the behavior

I used an example for google https://docs.medusajs.com/v2/resources/storefront-development/customers/third-party-login with some fixes.

```
  if (shouldCreateCustomer) {
    await createCustomer(token)

    token = await refreshToken(token)
  }
```
This code sends request to `/auth/token/refresh` with the next result:
```
{type: "unauthorized", message: "Could not find a auth provider with id: refresh"}
```

### Expected behavior

A new token.

**Comment by sradevski** [comment]
Hey @m0sth8 can you please upgrade to the latest preview version? The issue is that the middleware is missing, it should work on the latest version.

**Comment by ashish-ranjan-gloify** [comment]
not working in latest also , its only working when the token is not expired, if the token is expired it won't work, if its that way then what's the purpose of refresh token?
