### ISSUE TITLE
TypeError: cmd is not a function

### ISSUE THREAD

**Issue by stevebanik** [medusajs/medusa#908]
This error appears during 'medusa develop'

```
TypeError: cmd is not a function
    at /usr/lib/node_modules/@medusajs/medusa-cli/dist/create-cli.js:260:7
    at /usr/lib/node_modules/@medusajs/medusa-cli/dist/create-cli.js:108:24
    at Object.handler (/usr/lib/node_modules/@medusajs/medusa-cli/dist/create-cli.js:54:24)
    at Object.runCommand (/usr/lib/node_modules/@medusajs/medusa-cli/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/usr/lib/node_modules/@medusajs/medusa-cli/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.parse (/usr/lib/node_modules/@medusajs/medusa-cli/node_modules/yargs/build/lib/yargs.js:584:29)
    at module.exports (/usr/lib/node_modules/@medusajs/medusa-cli/dist/create-cli.js:392:6)
    at Object.<anonymous> (/usr/lib/node_modules/@medusajs/medusa-cli/dist/index.js:70:27)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
```

-bash-4.2# uname -a
Linux ip-10-0-82-92.us-west-2.compute.internal 4.14.248-189.473.amzn2.x86_64 #1 SMP Mon Sep 27 05:52:26 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by adrien2p** [comment]
Hi @stevebanik where did you run your command and where is you medusa-config file located ?

**Comment by onedawa** [comment]
IMO `cmd is not a function` is an unhelpful error

**Comment by stevebanik** [comment]
Hi @adrien2p I ran it in /root and I'm unable to find medusa-config:

```
-bash-4.2# find / -name medusa-config
-bash-4.2# 
```

**Comment by adrien2p** [comment]
Hi, you have to scaffold the project, then you move into the root of the project, and there you'll have everything

**Comment by fishboro** [comment]
Hey @adrien2p - I am actually receiving the same error as @stevebanik

I followed the [tutorial ](https://docs.medusajs.com/tutorial/set-up-your-development-environment)for setting up my dev environment in your documentation.

After running 'medusa new medusa-test --seed':

```
~/medusa-test$ medusa develop
medusa develop

Start development server. Watches file and rebuilds when something changes

Options:
  --verbose                Turn on verbose output                                                 [boolean] [default: false]
  --no-color, --no-colors  Turn off the color in output                                           [boolean] [default: false]
  --json                   Turn on the JSON logger                                                [boolean] [default: false]
  -H, --host               Set host. Defaults to localhost                                   [string] [default: "localhost"]
  -p, --port               Set port. Defaults to 9000                                             [string] [default: "9000"]
  -h, --help               Show help                                                                               [boolean]
  -v, --version            Show version number                                                                     [boolean]
TypeError: cmd is not a function
    at /usr/lib/node_modules/@medusajs/medusa-cli/dist/create-cli.js:260:7
    at /usr/lib/node_modules/@medusajs/medusa-cli/dist/create-cli.js:108:24
    at Object.handler (/usr/lib/node_modules/@medusajs/medusa-cli/dist/create-cli.js:54:24)
    at Object.runCommand (/usr/lib/node_modules/@medusajs/medusa-cli/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/usr/lib/node_modules/@medusajs/medusa-cli/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.parse (/usr/lib/node_modules/@medusajs/medusa-cli/node_modules/yargs/build/lib/yargs.js:584:29)
    at module.exports (/usr/lib/node_modules/@medusajs/medusa-cli/dist/create-cli.js:392:6)
    at Object.<anonymous> (/usr/lib/node_modules/@medusajs/medusa-cli/dist/index.js:70:27)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
```

### Files in medusa-test:
Dockerfile  README.md  data  develop.sh  docker-compose.yml  medusa-config.js  package.json  src

### Host info:
Linux gsopi01 5.4.0-1047-raspi #52-Ubuntu SMP PREEMPT Wed Nov 24 08:16:38 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

### Dependencies installed and versions:
    Node.js = v17.3.0
    Git = 2.25.1
    Postgresql = 14.1-2.pgdg20.04+1
    Redis = 6.2.6
    Medusa CLI = 1.1.25

**Comment by Smileek** [comment]
Hi @fishboro 

As @adrien2p mentioned:
> you have to scaffold the project

More specifically, the setup instruction lacks one line: `cd my-medusa-store` after `medusa new my-medusa-store --seed`

**Comment by olivermrbl** [comment]
Hi @fishboro ! Did you manage to resolve your issue? 😊

**Comment by srindom** [comment]
I'll close for now - let us know if you need more help @fishboro :)

**Comment by walkrr** [comment]
I am getting the same issue, after running cd my-medusa-store that error is still coming up. Running ubuntu 20.04.3 and the latest version of nodejs.

**Comment by danish17** [comment]
@walkrr, check your Node version. If you are using an older version of Node, trying updating to the LTS or the latest version.

**Comment by walkrr** [comment]
That worked, I had to use a module called n to get it to use the latest node instead of stable. Thanks

**Comment by spatial763** [comment]
@stevebanik I got same issue can you please help me

**Comment by adrien2p** [comment]
@spatial763 did you try the previous suggestions?

**Comment by spatial763** [comment]
> @spatial763 did you try the previous suggestions?

Yes I tried pervious suggestions and follow the instructions carefully but still get the error

**Comment by DebashisCodes** [comment]
@adrien2p I am getting the same too when I ran medusa develop.

Current **node** version is: **16.16.0**
The current **npm** version is: **8.11.0**


![Screenshot 2022-08-02 at 10 49 01 PM](https://user-images.githubusercontent.com/3373927/182436002-196365ad-287e-4478-a8fb-21e0773d6d9c.png)
![Screenshot 2022-08-02 at 10 50 50 PM](https://user-images.githubusercontent.com/3373927/182436027-6bb432da-879c-4970-95d7-ad2d485d97e5.png)

**Comment by WizzDex** [comment]
Getting the same error on "medusa user", works fine on "medusa" alone.
![image](https://user-images.githubusercontent.com/50861043/184508348-70a66c09-5c97-4aaf-84bd-6013215975cc.png)

**Comment by Hemann55** [comment]
In my case, there are no errors when medusa commands are executed in the exact same folder where medusa-config file is located. (Which is in my-medusa-store/backend folder in my case) Anywhere else only "medusa" or "medusa --version" will work but commands like "medusa user" will not work.

**Comment by NolimitL** [comment]
Hi! @adrien2p I tried you advice but it doesn't work for me. I still have the same error.

```
medusa-server  | medusa migrations [action]
medusa-server  | 
medusa-server  | Manage migrations from the core and your own project
medusa-server  | 
medusa-server  | Options:
medusa-server  |   --verbose                Turn on verbose output  [boolean] [default: false]
medusa-server  |   --no-color, --no-colors  Turn off the color in output  [boolean] [default: false]
medusa-server  |   --json                   Turn on the JSON logger  [boolean] [default: false]
medusa-server  |   --action  [required] [choices: "run", "revert", "show"]
medusa-server  |   -h, --help               Show help  [boolean]
medusa-server  |   -v, --version            Show version number  [boolean]
medusa-server  | TypeError: cmd is not a function
```
Could you please explain what can be the cause of this?

**Comment by spanwair** [comment]
DIFFERENT SOLUTION FOR THOSE ASKING FOR HELP WITH `medusa user ...`

for those who is getting error while running `medusa user ...`, just change your terminal folder to ./my-medusa-store and than run same script. Problem is that `medusa` script tryng to run some packages locally from deps and in medusa-admin/node_modules are missing those deps. Happy codding

**Comment by anle1991** [comment]
got the same error on node 19.1.0

**Comment by anle1991** [comment]
ok resolved it by creating the User in the Store Server folder

**Comment by jonjahr** [comment]
FWIW I ran into this error too when setting up MinIO.  TLDR I think it's a conflict with yarn v3+.  I fixed the error by undoing the `yarn add` and re-installing with `npm`.  

Steps to reproduce:  (MacOS and node v16)

* Fresh install with `medusa new ...`
* Run `yarn add medusa-file-minio` (with yarn v3.2.3)
* Per [guide](https://docs.medusajs.com/add-plugins/minio), add MinIO stuff to `.env` and `medusa-config.js`.
* Run `medusa develop`
* The error appears: "TypeError: cmd is not a function..."

To fix the error:
* Run `yarn remove medusa-file-minio`
* Manually delete all the files yarn added
* Run `npm install medusa-file-minio`
* Run `medusa develop`
* The server starts up. No error.

**Comment by vasilemidrigan** [comment]
Works! Thanks!

**Comment by mgomez-tubs** [comment]
in my case i forgot to copy the .yarnrc file and yarn was going for a pnp install which caused it to not find the needed files under node_modules. might or might not related to this but i still leave it here for reference

**Comment by dev-ileaf** [comment]
Got the same error in the railway while deploying.

When I initiated a redeployment on the railway, the build was successful, but the server did not start, and the application did not respond. When I rolled back the process, it worked fine. This issue also occurs when pushing changes.

I noticed on the deployment log that the "TypeError: cmd command was not found"

![image](https://github.com/medusajs/medusa/assets/166790996/7ff9b32f-6732-4be1-bb01-b660705215ba)

**Comment by facundocapua** [comment]
I'm having the same issue as @dev-ileaf please advice

**Comment by vavilondev** [comment]
the same issue as guys above

**Comment by facundocapua** [comment]
Thanks to @dev-ileaf
I have changed my `railway.toml` to this:
```
[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs", "yarn"]

[build.nixpacksPlan.phases.install]
cmds=["yarn install"]
```

According to the documentation is the preferred way: https://docs.medusajs.com/deployments/server/deploying-on-railway#add-railway-configuration-file

**Comment by pepijn-vanvlaanderen** [comment]
We build on Railway with a Dockerfile and ran on a fresh install into this issue as well. For us the solution was to put an (empty) uploads folder in the repo. Somehow medusa start swallows the real error and spits out `TypeError: cmd is not a function`, while running a custom start command we saw the real error of the missing uploads directory.

**Comment by piotr-wieruszewski** [comment]
> We build on Railway with a Dockerfile and ran on a fresh install into this issue as well. For us the solution was to put an (empty) uploads folder in the repo. Somehow medusa start swallows the real error and spits out `TypeError: cmd is not a function`, while running a custom start command we saw the real error of the missing uploads directory.

Thanks for the pointer! That was an issue on our end too when deploying to GCP from GitHub and the `uploads` folder was empty so it was skipped.

**Comment by lorisdileo** [comment]
I encountered the same issue after updating my entire package.json file. The solution was to downgrade glob from version 11 or 10 to 9.3.5.

**Comment by yusufyilmazf** [comment]
somehow my npx or node was trying to run the medusa command via @medusajs/medusa-cli/cli.js(sth like that) but I think that this is previous version or sth. 

I fix my problem by changing my package.json as 
˙˙˙
"scripts": {
    "build": "node node_modules/@medusajs/cli/cli.js build",
    "seed": "node node_modules/@medusajs/cli/cli.js exec ./src/scripts/seed.ts",
    "start": "node node_modules/@medusajs/cli/cli.js start",
    "dev": "node node_modules/@medusajs/cli/cli.js develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
˙˙˙
