### ISSUE TITLE
Where to generate admin ACCESS_TOKEN [Question]

### ISSUE THREAD

**Issue by onedawa** [medusajs/medusa#909]
Hi,
The admin api end points require an access token. For example, 
[Get Session Docs](https://docs.medusajs.com/api/admin/auth/get-session)
```
curl -X GET https://medusa-url.com/admin/auth   --header "Authorization: Bearer <ACCESS TOKEN>"
 ```
 How is this ACCESS_TOKEN obtained?

**Comment by jbesraa** [comment]
^^
any answers?

**Comment by olivermrbl** [comment]
> ^^ any answers?

You can generate a UUID or similar and add directly on your user in the database in column `api_token`. Let me know if you need help.
