### ISSUE TITLE
pass inputs to steps documentation not up to date with preview

### ISSUE THREAD

**Issue by Slepzs** [medusajs/medusa#9110]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

After new changes to @medusajs/workflows-sdk. There has to be added more to the introduction example to have it working without type issues. 

https://docs.medusajs.com/development/workflows#pass-inputs-to-steps

issue: 
1. typescript: Expected 3 type arguments, but got 2
2. Argument of type '(input: WorkflowData<WorkflowInput>) => WorkflowData<{ message: string; }>' is not assignable to parameter of type '(input: WorkflowData<WorkflowInput>) => void | WorkflowResponse<WorkflowOutput, any[]

```
const myWorkflow = createWorkflow<WorkflowInput, WorkflowOutput, any[]>(
  "hello-world",
  function(input) {
    const str1 = step1();
    const str2 = step2(input);

    const result = transform(
      {
        str1,
        str2,
      },
      (input) => ({
        message: `${input.str1}\n${input.str2}`,
      }),
    );

    return new WorkflowResponse(result);
  },
);
```

### How can this issue be resolved?

1. add any[] as third agurment to createWorkflow type
3. return result as new WorkflowResponse
4. import workflowResponse
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Hi @Slepzs , the link you shared the Medusa v1 documentation. Instead, you should be using the Medusa v2 documentation here:

https://docs.medusajs.com/v2/basics/workflows

Closing this issue, feel free to follow up with additional comments

**Comment by Slepzs** [comment]
Ah my bad, and thanks!
