### ISSUE TITLE
[website] Hover status bug

### ISSUE THREAD

**Issue by eduayme** [medusajs/medusa#9111]
### What Medusa version and documentation are you using?

None

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

On your public website page [https://medusajs.com/framework/](https://medusajs.com/framework) there are the `Read docs` and `View code` links with undesired hover behaviours. On mouse hover the background changes. Based on other pages, I think this should not be the case. I attach a screenshot next with the hover state. I was not sure where to send this bug so I send it here in Docs, hope it helps :)

<img width="1440" alt="Screenshot 2024-09-11 at 22 26 17" src="https://github.com/user-attachments/assets/4a27f9d0-c99a-4f09-aa05-24ca1d00f620">

### How can this issue be resolved?

1. Removing the `hover:bg-*` class should solve the problem.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by Amaanghazi22** [comment]
If the bug still exists, I would like to fix this.

**Comment by srindom** [comment]
Thanks for reporting - we will take a look at it :)

Will close here since this is unrelated to the codebase.
