### ISSUE TITLE
Sales Channel indexing with Meilisearch

### ISSUE THREAD

**Issue by WFL-Niek** [medusajs/medusa#9124]
I'm using the Meilisearch plugin to index & search my products. Since the /store/products/search endpoint doesn't allow for passing sales_channel_ids, I would like to make use of the Meilisearch filters. However, Meilisearch isn't indexing the sales_channels field on the products. 

My current plugin config:

```
{
    resolve: `medusa-plugin-meilisearch`,
    options: {
        config: {
            host: process.env.MEILISEARCH_HOST,
            apiKey: process.env.MEILISEARCH_API_KEY,
        },
        settings: {
            products: {
                indexSettings: {
                    searchableAttributes: ["title", "description", "variant_sku", "metadata", "handle", "sales_channels"],
                    displayedAttributes: ["id", "title", "description", "variant_sku", "thumbnail", "metadata", "handle", "variants", "sales_channels"],
                },
                primaryKey: "id",
            },
        },
    },
}
```

**Comment by olivermrbl** [comment]
@WFL-Niek, we won't be improving any V1 plugins now that V2 is coming out very soon, so I'll be closing this issue. 

However, you might be able to achieve what you are looking for by passing a custom data transformer in the MeiliSearch plugin configuration. See the documentation [here](https://docs.medusajs.com/plugins/search/meilisearch#index-settings).
