### ISSUE TITLE
Unexpected page render error if I delete the product image on the product details page

### ISSUE THREAD

**Issue by kee0624** [medusajs/medusa#9135]
### System information

Medusa version (including plugins):
Node.js version: 20.11.1
Database: postgres
Operating system: mac os
Browser (if relevant):

### Steps to reproduce the behavior

1. Create one new product
2. Upload only one product image
3. Once the product is published, go to the product details you just created and remove the product image through the overlay
4. You get the Unexpected page render error after that

### Expected behavior

The page should not break if I delete the product image

### Screenshots

![Screenshot 2024-09-15 at 6 12 48 PM](https://github.com/user-attachments/assets/4c2111d0-5732-4e07-8e50-2ee37b96a641)

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by olivermrbl** [comment]
@kee0624, I am unable to reproduce this issue. Can you share more detailed steps? Also, what file provider are you using?

**Comment by SummerFans** [comment]
@kee0624 could you provide a screenshot of the error message from the console

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and the issue is not actionable.

**Comment by appinteractive** [comment]
I encountered the same issue and wrote a patch for it.

https://gist.github.com/appinteractive/22e812f2d430c46b35b8cff80677613c

related to https://github.com/medusajs/medusa/issues/12250
