### ISSUE TITLE
Price lists expired but still affect the special price in storefront

### ISSUE THREAD

**Issue by peerapatzimpligital** [medusajs/medusa#9176]
### Describe the bug
When the price list expires, it still affects the special price in the storefront.

### System information

Medusa version (including plugins):
Node.js version:v20.16.0
Database:postgres
Operating system:Mac os
Browser (if relevant):

### Steps to reproduce the behavior

1. Create a price list and set start and end dates.
2. If the current time is within the period, it shows as active in the backend, and the special price is calculated in the frontend.
3. If the current time is later than the end date, it shows as expired in the backend, but the special price is still calculated in the frontend.

### Expected behavior

If the current time is later than the end date, it shows as expired in the backend, and the special price is not displayed in the frontend.

### Screenshots

<img width="1634" alt="Screenshot 2567-09-18 at 16 10 44" src="https://github.com/user-attachments/assets/054aee74-baa5-4306-9a7d-e28a4bbdad7a">

<img width="1636" alt="Screenshot 2567-09-18 at 16 11 22" src="https://github.com/user-attachments/assets/4440b3b0-6bf1-4f7a-b198-e17f83a3f112">

<img width="1616" alt="Screenshot 2567-09-18 at 16 11 53" src="https://github.com/user-attachments/assets/354a83e5-ed1a-4d3c-b2a3-e66f187ba28d">

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by 420coupe** [comment]
hard refresh the storefront. nextjs caches in .next. If still there try deleting .next and relaunch store-front.

**Comment by peerapatzimpligital** [comment]
@420coupe I tried all of your suggestions, but the special price still shows on storefront

**Comment by olivermrbl** [comment]
@peerapatzimpligital, thanks for reporting this. We'll look into it asap :)

**Comment by peerapatzimpligital** [comment]
Why is this issue closed? Is it already fixed?
