### ISSUE TITLE
Medusa Learning Resources: Issue in Medusa Learning Resources

### ISSUE THREAD

**Issue by aikrom** [medusajs/medusa#9186]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

There are many problems in the examples. Incorrect import directories, directories of example files. For example, [here](https://docs.medusajs.com/v2/resources/recipes/marketplace/examples/restaurant-delivery#create-api-route-1). 

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Hi @aikrom thanks for opening this PR! Can you clarify where the issues exactly are?
