### ISSUE TITLE
Price Lists > Create > Customer availability: Table missing customers count

### ISSUE THREAD

**Issue by Kushal-starr** [medusajs/medusa#9210]
There is some issue while creating a price list for particular customer_groups.

I created the customer_group with customer. Now creating the price_list for that particular customer_group, so when I'm toggling to Customer availability” field and selecting the customer_group its giving me 0 customer under that customer_group, which is getting effected in my storefront, enabling that price list for all the customers.

PFA below
![Screenshot 2024-09-20 at 5 04 23 PM](https://github.com/user-attachments/assets/12ef3ae9-6b8d-4961-9b5f-c6e75df4a20e)

FYI: @olivermrbl

**Comment by olivermrbl** [comment]
@Kushal-starr, thanks for the report.

Please, provide more specific reproducible steps in a bullet list format, and I'll attend to it.

**Comment by Kushal-starr** [comment]
Below are the steps for replicating the same issue: (from Medusa Store)

- Create a customer_group.
- Create/add customer to this customer_group.
- Create a price_list
- And while creating, at the last toggle to "**Customer availability**” field and selecting the customer_group which you have just created. It will show "-" under customer, even if the customer is added to my customer_group.

(It must show the number of customers available to my customer_group. Also, I think its not getting updated, because if I create the price_list assuming that its getting updated on backend side and not visible on UI part, but this assumption came wrong. As I logged in with the id which is not added to that customer group it was showing the effective prices for that customer also).

Pls feel free to comment if any other issues persists/you are not able to replicate this.

**Comment by olivermrbl** [comment]
Followed the steps above, and I am still unable to reproduce. 

Can you share a screen recording?

**Comment by Kushal-starr** [comment]
@olivermrbl  PFA below,
[Recording-20240923_101845.webm](https://github.com/user-attachments/assets/47b463f0-02c3-4841-b51e-7cc1f1533754)

**Comment by olivermrbl** [comment]
Got it, I see it now. We'll get this fixed this week :)
