### ISSUE TITLE
Error while completing the checkout process

### ISSUE THREAD

**Issue by Kushal-starr** [medusajs/medusa#9212]
As there is new concept of publishable API key in the storefront side. So I created a new saleschannel and linked that with a new publishable API that I created. Also, linked the products with that saleschannel. 

Now my products linked with that saleschannel is now shown on my storefront I'm able to add them in cart and able to proceed with the checkout process. I enter the address and When I proceed for the "Continue to delivery" it give me an error saying:
**"Error setting up the request: Unable to assign cart to disabled Sales Channel: Default Sales Channel"**

How I will be linking the cart to the saleschannel that I have created. Is there something I need to configure for cart also??

PFA below, 
![Screenshot 2024-09-20 at 6 25 13 PM](https://github.com/user-attachments/assets/7b276af8-8090-44bc-9631-14b4b215d6e9)

FYI: @olivermrbl

**Comment by olivermrbl** [comment]
This should happen automatically. Can I get you to clear the browser cache and try again? You might have had an old cart in local storage.

And just be sure, you need to:
- Create Publishable API Key
- Associate Sales Channel with Publishable Key
- Associate Location with Sales Channel
- Associate Products with Sales Channel
- Add Publishable API Key as a header to all `/store*` requests by setting environment variable `NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=<pub key>`

**Comment by Kushal-starr** [comment]
@olivermrbl  Already done and proceeded with the mentioned steps.

Also, tried replicating the sam eon other browser too.
<img width="1426" alt="Screenshot 2024-09-20 at 9 47 58 PM" src="https://github.com/user-attachments/assets/9ba68cee-48e6-421f-ab76-0f00fb20f1f1">

Also, already linked the location with my sales channel.

**Comment by 420coupe** [comment]
I had a similar issue with new build, i just went into db manually and deleted the Default Sales Channel created by medusa in the db and cleared up the issue.

**Comment by Kushal-starr** [comment]
Hi @olivermrbl , any updates on this?? :)

**Comment by thetutlage** [comment]
@Kushal-starr Did you have any luck trying the solution shared by @420coupe ?

**Comment by sradevski** [comment]
Closing as there isn't any response.
