### ISSUE TITLE
Docs(Code Issue): Missing imports and formatting inconsistency

### ISSUE THREAD

**Issue by amaster507** [medusajs/medusa#9224]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

URL: https://docs.medusajs.com/v2/customization/extend-models/extend-create-product#2-link-brand-to-product-using-workflow-hook

missing the imports:

```ts
import { Modules, ContainerRegistrationKeys } from "@medusajs/utils"
```

And line `19` `const remoteLink = ...` is indented inconsistently

### How can this issue be resolved?

1. Add missing import line in example
2. Remove extra indentation from line 19 (~20 after the import statement is added)

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by amaster507** [comment]
Also,

> In the Medusa application's logs, you'll find the message `Linked brand to products`, indicating that the workflow hook handler ran and linked the brand to the products.

This log did not happen for me. I believe to get this log, you will need to add a console log in the scripts you wrote, or maybe increase logging level, but default logging level does not log this line in v2

**Comment by shahednasser** [comment]
Nice catch! Will open a PR to fix those, seems like the code snippet is missing a logging statement as well.
