### ISSUE TITLE
Docs(Code Issue): typo of example URL

### ISSUE THREAD

**Issue by amaster507** [medusajs/medusa#9225]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Url: https://docs.medusajs.com/v2/customization/extend-models/query-linked-records#test-it-out

`http://localhost:9000/admin/product/prod_123/brand` should be `http://localhost:9000/admin/products/prod_123/brand` Notice `product` vs `products`

Might be good to add note to replace `prod_123` with your actual product id that was returned from the previous steps.

### How can this issue be resolved?

1. Fix typo
2. Possibly add note to replace `prod_123` with actual product id.

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch! ~please open a PR to fix it~ Ended up fixing it as part of PR #9236
