### ISSUE TITLE
Docs(Code Issue): TypeScript Error

### ISSUE THREAD

**Issue by amaster507** [medusajs/medusa#9226]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

URL: https://docs.medusajs.com/v2/customization/integrate-systems/service#1-create-service

`moduleDef.options` is not strongly typed, so the line:

```ts
this.options_ = moduleDef.options
```

produces ts error:

> Property 'apiKey' is missing in type 'Record<string, unknown>' but required in type 'BrandClientOptions'. `ts(2741)`
client.ts(5, 5): 'apiKey' is declared here.

### How can this issue be resolved?

1. add the code ` as BrandClientOptions`

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by amaster507** [comment]
Also the line:

```ts
async createBrand(brand: Record<string, string>)
```

later is the culprit for a type error because the value type of `string` is too strict for `brand` which has properties that are `Date` values.

To fix this, change the line to allow either `string | Date` values like:

```ts
async createBrand(brand: Record<string, string | Date>)
```

**Comment by shahednasser** [comment]
Thanks for reporting this! wIll look into it
