### ISSUE TITLE
Docs(Code Issue): TypeScript Error Property 'id' is missing in type 'Record<string, string>' but required in type 'SyncBrandToSystemInput'

### ISSUE THREAD

**Issue by amaster507** [medusajs/medusa#9227]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Url: https://docs.medusajs.com/v2/customization/integrate-systems/handle-event#3-handle-brandcreated-event

Line:

```
}: SubscriberArgs<Record<string, string>>) {
```

is the culprit of a ts error on line:
```
input: data,
```
Error:
> Property 'id' is missing in type 'Record<string, string>' but required in type 'SyncBrandToSystemInput'. `ts(2741)`
index.ts(5, 5): 'id' is declared here.
type.d.ts(12, 5): The expected type comes from property 'input' which is declared here on type 'FlowRunOptions<SyncBrandToSystemInput>'

### How can this issue be resolved?

1. Change `Record<string, string>` to instead use `SyncBrandToSystemInput`
2. Add `SyncBrandToSystemInput` to import statement from `"../workflows/sync-brand-to-system"`

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for reporting this! Will look into it
