### ISSUE TITLE
Typo in website menu item.

### ISSUE THREAD

**Issue by cristian-home** [medusajs/medusa#9233]
### What Medusa version and documentation are you using?

None

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

![imagen](https://github.com/user-attachments/assets/63d25980-2ba4-4658-9de6-1d7214494a74)
There is a typo in the menu `Product > Module > Other > Authentication` where it says “User authentication and **authorisation**” and it should say “User authentication and **authorization**”.

### How can this issue be resolved?

1. Just correcting the Typo is enough.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for reporting this! I relayed it to the associated team. Will close this as it'll be handled in a separate repo.
