### ISSUE TITLE
Custom Attributes in medusa 2.0

### ISSUE THREAD

**Issue by Kushal-starr** [medusajs/medusa#9235]
Can anyone help/guide me 'how to enable the custom-attributes in the medusa 2.0'

As of now, I follow the steps that were there in the documentation. But unable to see the widget in my medusa 2.0 Admin UI.

Below are some screenshots for the steps I followed:
1. Install 'medusa-custom-attributes' (used it with --force as it was giving some dependency issue)
2. Added 'MEDUSA_FF_PRODUCT_CATEGORIES=true'  in .env 
3. Added 
{
    resolve: `medusa-custom-attributes`,
    options: {
      enableUI: true,
      projectConfig: {
        store_cors: process.env.STORE_CORS,
        admin_cors: process.env.ADMIN_CORS,
      },
    },
  },
  in the medusa-config.js
4. Run the migrations

@olivermrbl  Could you pls assist with this providing any documentation on this or any direction for this. Thanks in advance!!!

**Comment by olivermrbl** [comment]
@Kushal-starr, what guide have you been following? 

This is a plugin for V1 and won't be ported to V2 any time soon.

**Comment by SalahAdDin** [comment]
@Kushal-starr you could try to port it to Medusa 2, or ask/implement this feature for it

**Comment by Kushal-starr** [comment]
@SalahAdDin I tried to doing so in medusa 2.0 but its not compatible, giving me some of the packages dependency’s. Even after re/install the packages. Tried deleting the package-lock.json and re/installing it again, still the issue was persisting.

**Comment by SalahAdDin** [comment]
> @SalahAdDin I tried to doing so in medusa 2.0 but its not compatible, giving me some of the packages dependency’s. Even after re/install the packages. Tried deleting the package-lock.json and re/installing it again, still the issue was persisting.

I guess the way to do that is to create a new plugin and transplant all the existing code from this repo.

**Comment by Kushal-starr** [comment]
ohh is it so...will look into that. Also it will be good if we will some direction on this from you too @olivermrbl.

**Comment by SalahAdDin** [comment]
@Kushal-starr isn't there any way to add extra attributes to the products?
