### ISSUE TITLE
InventoryService takes only first 15 items

### ISSUE THREAD

**Issue by noubase** [medusajs/medusa#9247]
## Bug report

InventoryService takes only first 15 items

### Describe the bug

If you query the InventoryService and expect more than 15 records, you will only receive the first 15.
This behavior causes an issue in the `ensureInventoryLevels` method within the `InventoryModuleService`, as it incorrectly calculates the `missing` array.

### System information

Medusa version (including plugins): 2.0.9-preview
Node.js version: v20.15.1
Database: PostgreSQL 16.3
Operating system: MacOS Version 14.6.1
Browser (if relevant):

### Steps to reproduce the behavior

```
const sku = variants.map(v => v.sku); // 53 elements
const inventoryItems = await inventoryService.listInventoryItems({
  sku
}, {take: sku.length});

const inventoryItemsWithoutTake = await inventoryService.listInventoryItems({
  sku
});
```

### Expected behavior

The `inventoryItems` array has a length of 53, and `inventoryItemsWithoutTake` should have the same length. However, it currently contains only the first 15 elements.

**Comment by noubase** [comment]
`packages/modules/inventory-next/src/services/inventory-module.ts`

lines 120 ... 128

```
const inventoryLevels = await this.listInventoryLevels(
      {
        $or: [
          { id: idData.filter(({ id }) => !!id).map((e) => e.id) },
          ...itemLocationData,
        ],
      },
      {},
      context
    )
```    
In this case, `itemLocationData` contains 53 elements, but `inventoryLevels` still only includes the first 15.

**Comment by noubase** [comment]
![image](https://github.com/user-attachments/assets/e2086111-fd5c-417f-a3b0-40f389f49bd1)

`packages/core/utils/src/modules-sdk/build-query.ts`

As I understand it, this line is causing the issue. 
While I can control how many items I want to retrieve in my code, the `ensureInventoryLevels` method will still block me regardless.

**Comment by adrien2p** [comment]
@noubase thanks for reporting it, I ve open a pr that fixes this hidden constraint and many other issues. You don't have to do anything on your side and when it will be released you should be good 👍
