### ISSUE TITLE
storefront nextjs installation

### ISSUE THREAD

**Issue by 11thmoonlight** [medusajs/medusa#9260]
### What Medusa version and documentation are you using?

None

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

An error occurred while installing Next.js storefront: Error: Command failed: npx create-next-app@latest -e https://github.com/medusajs/nextjs-starter-medusa hinode-storefront
Found invalid GitHub URL: "https://github.com/medusajs/nextjs-starter-medusa". Please fix the URL and try again.
i encounter this message whenever i try to intstall next js storefront

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for reporting this issue but I wasn't able to reproduce it. Can you provide more details on your system? i.e. what node version, OS, etc... also if you can ensure that you're actually using the latest `create-next-app` version that would be great.

**Comment by sradevski** [comment]
Closing as there hasn't been any response
