### ISSUE TITLE
Docs(v2): Missing example for using Medusa's core flows

### ISSUE THREAD

**Issue by itsjab** [medusajs/medusa#9263]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

From the docs, it is difficult to gauge how to use Medusa's core flows, such as `createProductVariantsWorkflow`. Yet, these workflows are extremely powerful when used in an API route or subscriber.

### How can this issue be resolved?

The issue can be resolved by adding a few examples of using a core flow in an API route or subscriber.

I've been recently working on an API route, in which I've used the `createProductVariantsWorkflow` core flow. Would be simple enough to add this as an example.

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for opening this issue! Yes we're aware of this and we have it planned after finishing up other priorities. Hoping we can have them available some time soon for you to use 👍🏻
