### ISSUE TITLE
Docs(v2): Medusa Development Resources - Medusa Admin - Vercel: Incorrect install command

### ISSUE THREAD

**Issue by JohnGemstone** [medusajs/medusa#9264]
### What Medusa version and documentation are you using?

v2

### Issue Summary

https://docs.medusajs.com/v2/resources/deployment/admin/vercel#3-create-vercel-project

Hey theres a typo on step 3.4.3 for vercel's output settings where it says:

```
Set the Install Command field to the following:

- npm run build
- yarn build
- pnpm run build
```

build should be install

Cheers!

**Comment by SalahAdDin** [comment]
@JohnGemstone could you open a PR to solve it?
