### ISSUE TITLE
Webpack Dev Middleware Waiting for Bundle Completion

### ISSUE THREAD

**Issue by anand-m-s** [medusajs/medusa#9319]
I'm experiencing an issue where the Webpack Dev Middleware is stuck at "wait until bundle finished" for the path /app when trying to run the Medusa backend. This is impacting my ability to access the admin dashboard.
![Screenshot_20240926_144108](https://github.com/user-attachments/assets/d5e89ce9-0a7c-4040-9d42-a231ce14f368)

when i go to this url 
http://64.227.137.191:9000/app

showing like this : Admin is running in development mode. See the terminal for the URL.

**Comment by sradevski** [comment]
Hey Anand, I'm afraid we can't do much about it without some reproduction steps, especially since our focus is on 2.0 now. I suggest you move to 2.0 where we use Vite, which is less resource-intensive and works better overall.
