### ISSUE TITLE
ModuleIntegrationTestRunner Doesn't Support Module Dependencies

### ISSUE THREAD

**Issue by AlexAntonides** [medusajs/medusa#9320]
### Describe the bug
The `moduleIntegrationTestRunner` method in `medusa-test-utils` doesn't allow you to include the dependencies of a module, making it hard to add tests to custom modules that require dependencies (e.g. `Modules.EVENT_BUS`).

### System information
**Medusa version (including plugins)**: preview / v2.0.10
**Node.js version**: 20
**Database**: Postgres 16.4
**Operating system**: macOs 15.0

### Steps to reproduce the behaviour
1. Create a module with a dependency (e.g. `Modules.EVENT_BUS`)
    ```ts
    export default class YourModuleService extends MedusaService<...> {
           constructor({
                [Modules.EVENT_BUS]: eventBusModuleService,
           }: InjectedDependencies) { ... }
    }
    ```
2. Add it to the `medusa-config.js`,
    ```js
    modules: {
          [YOUR_MODULE]: {
                 resolve: "[YOUR_PATH]",
                 dependencies: [Modules.EVENT_BUS],
          }
    }
    ```
3. Verify it loads successfully on local. 
4. In a test file, use the `moduleIntegrationTestRunner` to register your module,
  ```ts
  import { moduleIntegrationTestRunner } from "medusa-test-utils"
 
  moduleIntegrationTestRunner<Service>({
       moduleName: YOUR_MODULE,
       resolve: "YOUR_PATH",
       testSuite: ...
  })
  ```
5. The test fails, because the service is unable to load the dependency. However, there is no way to add this dependency.  

### Expected behavior
I expect the moduleIntegrationTestRunner to have an option to include the dependencies, for example,
```ts
  import { moduleIntegrationTestRunner } from "medusa-test-utils"
 
  moduleIntegrationTestRunner<Service>({
       moduleName: YOUR_MODULE,
       resolve: "YOUR_PATH",
       dependencies: [Modules.EVENT_BUS],
       testSuite: ...
  })
```
I tried this locally by modifying the code, and then my service is able to load correcvtly.

### Additional context
The solution could be very simple, 
- Add `dependencies = []` [as one of the parameters](https://github.com/medusajs/medusa/blob/v2.0.10/packages/core/medusa-test-utils/src/module-test-runner.ts#L68).
- Add `dependencies` to `modulesConfig_` [under resolve](https://github.com/medusajs/medusa/blob/v2.0.10/packages/core/medusa-test-utils/src/module-test-runner.ts#L114).

**Comment by adrien2p** [comment]
Thank you for reporting that, here we go https://github.com/medusajs/medusa/pull/9330
you can now specify the module dependencies for the tests and in the injectedDependencies you can provide their values

**Comment by AlexAntonides** [comment]
Thank you for your quick support!
