### ISSUE TITLE
Medusa can't use tsconfig.json path aliases

### ISSUE THREAD

**Issue by bwmirek** [medusajs/medusa#9351]
After updating my `tsconfig.json` to use path aliases, the app won't run. It stars to throwing errors: `Error in loading config: Cannot find module '@app/modules/whatever'`.

## Code Snippets
```typescript
// tsconfig.json
// ...
"baseUrl": ".",
"paths": {
  "@app/*": ["src/*"],
},
// ...
```

**Comment by yuning-zhang** [comment]
Probably not Medusa related. Path aliases only informs the typescript compiler. Node (ts-node) in this case can't find the modules in node_modules. Consider using something like `https://www.npmjs.com/package/tsconfig-paths`. It worked for me. 

1. Install package
2. Add `"require": ["tsconfig-paths/register"]` under `ts-option` in tsconfig.json

**Comment by bwmirek** [comment]
Thanks @yuning-zhang for this workaround, yet I still think this should be supported out of the box in such package like Medusa.

**Comment by thetutlage** [comment]
Hello @bwmirek 👋

Thanks for opening the issue. Yes, this is something we should support out of the box. So let's us add it to our backlog

**Comment by JohnGemstone** [comment]
Some info here:
https://docs.medusajs.com/learn/conventions/ts-aliases

Following the instructions, it still doesn't work when running a dev server

**Comment by jungsikjeong** [comment]
> Some info here: https://docs.medusajs.com/learn/conventions/ts-aliases
> 
> Following the instructions, it still doesn't work when running a dev server

정말 감사합니다. 덕분에 에러를 해결했습니다.

**Comment by SalahAdDin** [comment]
MedusaJS is using vite, why is it not possible to use path aliases?
