### ISSUE TITLE
Missing Item Thumbnail in GET Carts API

### ISSUE THREAD

**Issue by abdul-tycheros** [medusajs/medusa#9353]
thumbnail missing from response.

**Comment by Dev-Abdullah-H** [comment]
To retrieve the thumbnail when fetching cart details, you need to include items.thumbnail as a field parameter in your request. For example:
```
http://localhost:9000/store/carts/cart_01J8SYXEZEECXEAXQ7GX747FK7?fields=+items.thumbnail
```

**Comment by abdul-tycheros** [comment]
Got it! Adding items.thumbnail worked perfectly. Thanks! @sradevski
