### ISSUE TITLE
Medusa v2 Docs: Issue in 8. Deployment Overview - Medusa v2 Docs

### ISSUE THREAD

**Issue by tthias** [medusajs/medusa#9356]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In the following sentence, "Heroku" is misspelled:
The Medusa server must be deployed to a hosting provider supporting Node.js server deployments, such as Railway, DigitalOcean, AWS, **<ins>Heruko</ins>**, etc…

### How can this issue be resolved?

1. Turning "Heruko" into "Heroku"

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch! WIll open a PR to fix it
