### ISSUE TITLE
Docs(Code Issue): Storefront not configured correctly

### ISSUE THREAD

**Issue by jkuzmanovik** [medusajs/medusa#9363]
### What Medusa version and documentation are you using?

None

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

When i create medusajs backend and storefront with npx create-medusa-app@preview and when i run both servers i get this error:

src/middleware.ts (33:15) @ notFound

  31 |
  32 |     if (!regions?.length) {
> 33 |       notFound()
     |               ^
  34 |     }
  35 |
  36 |     // Create a map of country codes to regions.

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by sradevski** [comment]
Hi there, it seems you haven't created a region in admin, so the storefront will fail (as it expects one). Also, make sure you have a publishable key set.
