### ISSUE TITLE
API Ref(store): Issue in Get Shipping Options typo: `/store/shipping-options/{cart/id}`

### ISSUE THREAD

**Issue by afifurrohman-id** [medusajs/medusa#9374]
### What Medusa version and documentation are you using?

v1

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

`/store/shipping-options/{cart/id}`

![{D6F3346E-56AF-4D76-974D-06E18CD39F05}](https://github.com/user-attachments/assets/c8ea19b6-921c-4164-9798-e3fb6cc1ac29)

it should `/store/shipping-options/{cart_id}`

### How can this issue be resolved?

change to /store/shipping-options/{cart_id}

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for opening this issue! Will fix it

**Comment by shahednasser** [comment]
Closing this issue as it's been fixed.
