### ISSUE TITLE
The price list settings for start and end dates to mark as expired/active do not work on the storefront.

### ISSUE THREAD

**Issue by peerapatzimpligital** [medusajs/medusa#9376]
## Bug report
When creating a price list and changing the start and end date settings, it doesn't seem to work on the storefront.

### System information

Medusa version (including plugins): Medusajs V2 @preview
Node.js version: v20.16.0
Database:Postgres
Operating system: macOS 15.0 (24A335)
Browser (if relevant): Chrome

### Steps to reproduce the behavior

1. Go to the price list page and add a price list rule.
2. Select a start date and end date within the current time period. It will show the label "Active."
3. Check that the storefront product price is calculated (shows the special price).
4. Edit the start date and end date to fall outside the current time period. It will show the label "Expired."
5. Check that the storefront product price is calculated (shows the original price).
6. Edit the start date and end date again to set them within the current time period.
7. Check that the storefront product price is not recalculated (shows the original price).

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

https://github.com/user-attachments/assets/bb2df0e4-1426-483a-8329-9589efa22bc0

**Comment by fPolic** [comment]
Thanks for the report @peerapatzimpligital. We have a [PR](https://github.com/medusajs/medusa/pull/9276) open that will fix the issue.

**Comment by Attachai77** [comment]
I stuck same issue, in my case I added a price list and set start date for next week, and then i set it in time currently  but the price list not working.
