### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by james-kaguru** [medusajs/medusa#9388]
### What Medusa version and documentation are you using?

v1

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I have 2 documentation issues
1. How to specify the port that the medusa backend can run is not shown. I have seend that it can be set by setting PORT in the .env however this cannot be found in the documentation
2. Documentation on seeding. I cant seem to find documentation on the seeding guidlines for medusa...I can only see the instructions for seeding. I believe the documentation could be improved by showing us the conventions that medusa uses to seed

### How can this issue be resolved?

1. Documenting the PORT for the env
2. Documenting the seeding guidlines and how we could also use it for seeding our own custom entities

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thank you for reporting this issue. We have a document on environment variables [here](https://docs.medusajs.com/learn/fundamentals/environment-variables). As for seeding conventions, we don't have any other than what is mentioned in the instructions guide you're referring to.

Will close this issue. Feel free to re-open if you have more questions.
