### ISSUE TITLE
Docs(Code Issue): Missing info about timeout

### ISSUE THREAD

**Issue by bwmirek** [medusajs/medusa#9409]
### What Medusa version and documentation are you using?

None

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Docs doesn't give an example of increasing timeout for tests. This matter because setting up database counts towards default total time limit for jest.

### How can this issue be resolved?

Just add this somewhere into example:
```typescript
jest.setTimeout(60 * 1000)
```

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for reporting this! WIll add a note about this in the docs.
