### ISSUE TITLE
Unable to Create Delivery Address Without Login During Checkout

### ISSUE THREAD

**Issue by abdul-tycheros** [medusajs/medusa#9420]
I am attempting to complete my cart checkout without logging in, but I receive an "Unauthorized" message from the **/store/customers/me/addresses** API. I have included the x-publishable-api-key in the request, but I did not provide an API token since I am not logged in. How can I resolve this issue?

**Comment by nehaaprasad** [comment]
Hello @abdul-tycheros :)

`
I think, 
When attempting to create a delivery address without logging in, the "Unauthorized" problem can be resolved by first making sure the API permits guest users to create addresses and then using the appropriate endpoint for that purpose. Ensure your request includes all relevant parameters and headers; if a token is needed, see if there’s a guest token accessible. Please Try your request using Postman or Curl, and if the problem still arises, seek more help from the API docs or support.
`

**Comment by abdul-tycheros** [comment]
Dear @naaa760 
I appreciate you taking the time to share this information!

**Comment by sradevski** [comment]
Hi there, the `/me` endpoint is for logged in users. You should simply set the shipping details on the cart without creating an address.
