### ISSUE TITLE
Removal of https://medusajs.com/plugins/medusa-plugin-smtp/ from the website.

### ISSUE THREAD

**Issue by gohlance** [medusajs/medusa#9424]
### What Medusa version and documentation are you using?

None

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The following repo is not maintained and it have a lack of proper documentation. This waste dev time on trying to get it to work.

### How can this issue be resolved?

1. Removal of the notification plugin from the official website
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by olivermrbl** [comment]
Our plugins page show all community contributions and does not account for whether or not it is maintained.
