### ISSUE TITLE
Error reading product list in storefront 

### ISSUE THREAD

**Issue by earmellin** [medusajs/medusa#9432]
### Describe the bug

Clean install of RC1, opening the storefront the product list returns an unknown error.

In backend's log you can see the error details:

error: A non-negative integer must be provided to offset.

generated by the fact that you are calling the list of products with offset=-100

GET /store/products?limit=100&**offset=-100**&region_id=reg_01J96WVAHTDCS7G9P70JSFZQN1&fields=%2Avariants.calculated_price&order=created_at

and offset cannot be a negative number

### System information

Medusa version (including plugins): 2.0-rc1
Node.js version: v20.16.0
Database: Postgres 14
Operating system: macOS 14.6.1
Browser (if relevant): Chrome

### Steps to reproduce the behavior

1. Go to Storefront fresh installed
2. Click on Store
3. See error

### Expected behavior

View the list of products

**Comment by olivermrbl** [comment]
@earmellin, thanks for reporting this. We'll fix it asap. Seems to be an issue with a malformed URL
