### ISSUE TITLE
All View Source links point to 404 page in the Plugins page

### ISSUE THREAD

**Issue by barrerajuanjose** [medusajs/medusa#9470]
### What Medusa version and documentation are you using?

v1

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Github links in the plugins page point to 404 pages. These are the step to reproduce the issue
1. Open https://medusajs.com/
2. Using the menu, go to Resources -> Plugins. This step opens the url https://medusajs.com/plugins/
3. Select a plugin (all of them have the same issue), for example this -> https://medusajs.com/plugins/medusa-plugin-meilisearch/
4. Click on the View Source link on the left column, that links will open a Github 404 page -> https://github.com/medusajs/medusa/tree/develop/packages/medusa-plugin-meilisearch

Taking a look at the repo, it looks like the plugins are in different branches instead of in the develop branch. I think that the current url should be in the branch `feat/medusa-plugin-admin`
https://github.com/medusajs/medusa/tree/feat/medusa-plugin-admin/packages/medusa-plugin-meilisearch

### How can this issue be resolved?

I am starting learning about this project, then I do know where the code of page lives or how the page gets the information to render. But I am open to help.

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by SalahAdDin** [comment]
@barrerajuanjose did it work?

**Comment by barrerajuanjose** [comment]
> @barrerajuanjose did it work?

@SalahAdDin I did not change. The broken links still are there.

**Comment by SalahAdDin** [comment]
@barrerajuanjose needs to reopen this issue then.

Are you still working with Medusa?
