### ISSUE TITLE
Medusa Development Resources: Issue in Commerce Modules - Medusa Development Resources

### ISSUE THREAD

**Issue by fryshaun** [medusajs/medusa#9485]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

some data model links in documentation are 404, presumably referring to old url structures

### How can this issue be resolved?

1. Update 'Item's Product Details' [LineItem data model](https://docs.medusajs.com/v2/resources/references/order/models/LineItem) to [OrderLineItem data model](https://docs.medusajs.com/v2/resources/references/order/models/OrderLineItem)
2. ShippingMethod data Model link and Transaction data model link also 404.
...

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for opening this issue! WIll look into it
