### ISSUE TITLE
Medusa AI Assistant issue

### ISSUE THREAD

**Issue by akshayambulgekar** [medusajs/medusa#9490]
### What Medusa version and documentation are you using?

None

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

When Medusa AI Assistant responds with code, the code block width isn't proper. There's a black shadow in between, and the scrollbar isn't displaying correctly. These issues are related to the UI of an application.i attached the related images of issue
![Screenshot 2024-10-07 170025](https://github.com/user-attachments/assets/faaf68d7-e0b8-4f5c-be54-a70dc859539b)
![Screenshot 2024-10-07 170040](https://github.com/user-attachments/assets/4c8c31e9-ae0e-4fe0-b971-cae79bbf3e07)
![Screenshot 2024-10-07 170047](https://github.com/user-attachments/assets/fcd83ffb-bb4b-4f16-9f03-63de412d7305)

### How can this issue be resolved?

1.Just have to change the width of respective block according to response 
2.
3.
...

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for reporting this! WIll look into it

**Comment by shahednasser** [comment]
Issue has been fixed. Closing.
