### ISSUE TITLE
memory allocation of 8388608 bytes failed on medusa admin startup

### ISSUE THREAD

**Issue by Jaikar1** [medusajs/medusa#9503]
### Describe the bug

Once the project creation is completed, when it is starting, fails on admin start up, logs shows a last message saying `memory allocation of n bytes failed`.

### System information

Medusa version (including plugins):
Node.js version: v18.15.0
Database: postgres (PostgreSQL) 14.5 (Debian 14.5-1.pgdg110+1) 
Operating system: Windows 11
Browser (if relevant): Chrome 129.0.6668.90 (Build oficial) (64 bits)

### Steps to reproduce the behavior

1. Execute `npx create-medusa-app@latest` and wait for it to complete
2. Once the whole project is build it prompt to Chrome and error appears

### Expected behavior

I am expecting localhost:7001 to show the admin login page but instead i get and error and immediatly the server goes down.

### Screenshots

While the project is starting it prompts to `http://localhost:7001` and takes sometime loading, like 20 seconds, after that it shows this:
![image](https://github.com/user-attachments/assets/293bc7a1-2373-465b-8f35-929c8c11e5f7)

Then in the logs it shows this
![image](https://github.com/user-attachments/assets/5d3665e5-f1c4-4232-ba90-f6922f88d15d)

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

- It happens exactly the same once the project is build and i execute `medusa develop` or `medusa start` and `medusa-admin start` 
- The memory bytes could change on every initialization.
- I tried setting `NODE_OPTIONS="--max-old-space-size=8192"` but there was no effect.

**Comment by sradevski** [comment]
Unless you have a reproduction of the issue, or you can pinpoint why it's happening, I'm afraid we can't do much about it. I would suggest to maybe start using 2.0 as it has somewhat lower memory requirements
