### ISSUE TITLE
Category path overflow

### ISSUE THREAD

**Issue by ChristofferOakDigital** [medusajs/medusa#9509]
### Describe the bug

It's a very minor issue, just noticed that long paths in Categories overflows the container and creates sidescroll on the site.

### System information

Medusa version (including plugins):
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

![Screenshot 2024-10-09 at 12 26 11](https://github.com/user-attachments/assets/59ec5bab-c4d8-47da-81f8-a989ee59b065)

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by olivermrbl** [comment]
Thanks @ChristofferOakDigital, we'll get this fixed asap.

**Comment by akshaywakhare** [comment]
Hi, is this open for contribution? I'd like to work on this
