### ISSUE TITLE
Graph query ignores the pagination config

### ISSUE THREAD

**Issue by renanboni** [medusajs/medusa#9516]
## Bug report
The graph ignores the **take** property from the **pagination** object and always returns everything.

### System information

Medusa version (including plugins): Medusa 2.0 RC 2

### Expected behavior

Only the amount of records passed in should be returned

### Code snippets

```
export const GET = async (
    req: AuthenticatedMedusaRequest,
    res: MedusaResponse
) => {
    const query = req.scope.resolve(ContainerRegistrationKeys.REMOTE_QUERY)
    const vendorId = await getVendorId(req, req.scope)

    const {data: [vendor]} = await query.graph({
        entity: "vendor",
        fields: req.remoteQueryConfig.fields,
        filters: {
            id: vendorId,
        },
        pagination: {
            skip: req.remoteQueryConfig.pagination.skip,
            take: req.remoteQueryConfig.pagination.take,
        }
    })

    res.json({
        "collections": vendor.product_collections,
    })
}
```

```
export const defaultStoreCollectionFields = [
    "product_collections.id",
    "product_collections.title",
    "product_collections.handle",
    "product_collections.created_at",
    "product_collections.updated_at",
]

export const retrieveTransformQueryConfig = {
    defaults: defaultStoreCollectionFields,
    isList: false,
}

export const listTransformQueryConfig = {
    ...retrieveTransformQueryConfig,
    defaultLimit: 10,
    isList: true,
}
```

It doesn't matter what we pass in in the **take** property, everything is going to be returned from the database.

I have the following link between Vendor and ProductCollection:

```
export default defineLink(
    MarketplaceModule.linkable.vendor,
    {
        linkable: ProductModule.linkable.productCollection,
        isList: true,
    }
)

```

Which means each store can have its collections, and I'm trying to fetch the collections from the vendor using that query.

### Additional context

Add any other context about the problem here

**Comment by carlos-r-l-rodrigues** [comment]
Hi @renanboni,
At the moment, the query tool can just paginate/limit the rows of the main entity, all the relations will be aggregated and return all the data.

In your case you can query starting from your Link, and expand the product_collections relation.

something like this:

```typescript
import vendorLink from "../links/vendor-product-collection"; // path to your link definition

await query.graph({
  entity: vendorLink.entryPoint,
  fields: req.remoteQueryConfig.fields,
  filters: {
    vendor_id: vendorId,
  },
  pagination: {
    skip: req.remoteQueryConfig.pagination.skip,
    take: req.remoteQueryConfig.pagination.take,
  },
});
```

This will paginate correctly, and `product_collections` will be expanded with the correct data.
Now you'll have to map the result and return only the `product_collections` data.

**Comment by renanboni** [comment]
hi @carlos-r-l-rodrigues, thanks, it works now.

One more question, when you say **_"...and expand the product_collections relation"_** do you mean I should run another query to get the collections (now that I have their IDs) or I can still get the relations using the same query?

Thanks!

**Comment by carlos-r-l-rodrigues** [comment]
Hey @renanboni,
you can use the same query.
by expanding the relation I just meant that you have to ask for the relation `product_collection.*`.
Because the link entity will only contain the `vendor_id` and the `product_collection_id` in it. if you want the actual entity you have to expand like: `product_collection.*` / `vendor.*` 

I guess if you just change your `defaultStoreCollectionFields` to `product_collection.` instead of plural, it will work

**Comment by renanboni** [comment]
it worked like a charm! the singular/plural always gets me :D

**Comment by renanboni** [comment]
solved! thanks @carlos-r-l-rodrigues

**Comment by renanboni** [comment]
I am sorry to reopen this again. It might be related - I saw in the docs that it is not possible to filter the entities from the other modules, for example this isn't possible:

```
const {data} = await query.graph({
        entity: vendorProductsLink.entryPoint,
        fields: ["product.*"],
        filters: {
            vendor_id: vendorId,
            collection_id: "some_id"
        },
    })
```

I can't filter the products by category_id in one go right? is there a plan to implement that in the future? because otherwise I will have to pull all the products from the database whenever I need to filter them by any of their attributes.

thanks again!

**Comment by carlos-r-l-rodrigues** [comment]
The `query.graph` can only filter the main entrypoint and aggregations, but you can't perform a cross module filter or sort.
That cross-module filtering and sorting will come as a new module "Index" and you will be able to filter and sort nested modules, like sorting products by price for example.

However all that doesn't exclude the need of a dedicated search engine for more complex cases, or full text search, if your store needs that.

Your example, of filtering a product by a category would need the Index module at least, because product_categories is a N:N relation and if you want to exclude products that don't belong to that category, the regular left join when requesting a relation won't do it.

**Comment by carlos-r-l-rodrigues** [comment]
for now, you have to query things separated to simulate this behavior, or have a custom search module, ingesting all the data and performing custom queries.

**Comment by renanboni** [comment]
Thanks a lot for all the explanations. Do you have any idea when this index module will be released?

**Comment by carlos-r-l-rodrigues** [comment]
It is already merged in develop, however it isn't possible to customize it yet.
We'll work on it after v2 release, end of October.

**Comment by srindom** [comment]
Will close this for now as the pagination issue was solved. As Carlos mentions there are plans for an Index module for cross module filtering. If you have inputs on behavior of that module that you'd like to see you are encouraged to open a Discussion.
