### ISSUE TITLE
GPay button doesn't process payment

### ISSUE THREAD

**Issue by jakubox** [medusajs/medusa#9540]
## Bug report
GPay button doesn' process payment
### Describe the bug
Ehn using the Gpay button on the payment page and not the credit card payment doesn't finish even though when using the credit card option and subsequently using the gpay button inplementation from Tatrabanka everything works and get's returned correctly 

### System information

Medusa version (including plugins): production
Node.js version:  
Database:
Operating system: Android 14 Update 1
Browser (if relevant): Chrome 129.0.6668.100

### Steps to reproduce the behavior

1. Go to '...' payment page
2. Click on '....' GPay button
3. Scroll down to '....' n/a

### Expected behavior

I expect the payment to go through

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Staff in restaurant doesn't believe in bugs and considers system to by fail proof. So that is a good thing for you. ;)

**Comment by olivermrbl** [comment]
This issue does not contain enough information for us to help. Please fill out the full template and reopen the issue.
