### ISSUE TITLE
Cannot remove many to many association using the `update` method

### ISSUE THREAD

**Issue by yuning-zhang** [medusajs/medusa#9547]
### Describe the bug

Service Factory `update` method cannot remove many to many association. Using the example in the doc [manage many-to-many relationship](https://docs.medusajs.com/v2/advanced-development/data-models/manage-relationships), see the following code to completely remove associations.

```
const product = await helloModuleService.updateProducts({
  id: "123",
  orders: [],
})
```

By passing an empty array, this should remove all orders from the product. Instead, it doesn't change anything. As long as there's one element in the array, updating association seems to work. But with an empty array, associations are not updated as one would expect.

### System information

Medusa version (including plugins): rc-02
Node.js version: v20
Database: Supabase
Operating system: MacOS 14
Browser (if relevant):

### Steps to reproduce the behavior

1. Create a many to many relationship such as [orders <-> products](https://docs.medusajs.com/v2/advanced-development/data-models/relationships#many-to-many-relationship)
2. Create an association
```
const product = await helloModuleService.updateProducts({
  id: "123",
  orders: ["321"],
})
```
3. Attempt to remove association by passing an empty orders array
```
const product = await helloModuleService.updateProducts({
  id: "123",
  orders: [],
})
```
4. Fetch orders and see that order id "321" is still associated with product "123"

### Expected behavior

Passing an empty array to remove any many to many association

**Comment by sradevski** [comment]
Hi @yuning-zhang this has been fixed, please upgrade to the latest Medusa version
