### ISSUE TITLE
Medusa Development Resources: Issue in Deploy Medusa Application to Railway - Medusa Development Resources

### ISSUE THREAD

**Issue by tanshu** [medusajs/medusa#9548]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The dependencies in the package.json are not named:
  "@medusajs/medusa/cache-redis": "rc",
  "@medusajs/medusa/event-bus-redis": "rc",
They are should named
  "@medusajs/cache-redis": "rc",
  "@medusajs/event-bus-redis": "rc",

### How can this issue be resolved?

1. Update the docs to show the right dependencies.
2.
3.
...

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch! WIll open a PR to fix it.
