### ISSUE TITLE
NavBar dropdown not extended upto 100% width

### ISSUE THREAD

**Issue by 0xsapphir3** [medusajs/medusa#955]
Due to the less width of the screen, the navbar has a dropdown to show more options. Now, the width of the dropdown is not up to the right side. Instead, it leaves out some of the space on the right side. 

Here is the screenshot:

**Comment by olivermrbl** [comment]
The attached screenshot is not working, so not entirely sure what you are referring to :)

**Comment by AsianCat54x** [comment]
Ah I get it didn't get uploaded properly. Here is the picture:

![Screenshot from 2022-01-05 18-55-56](https://user-images.githubusercontent.com/82395440/148225005-c11014e7-7543-4cba-bfd6-897b132db56f.png)
 
Don't you think that the navbar should be extended to 100% (till the end of the screen)?

**Comment by olivermrbl** [comment]
Our website is implemented in Webflow and this issue has been resolved. Thanks for reporting it :)
