### ISSUE TITLE
Middleware is not registering on custom API routes

### ISSUE THREAD

**Issue by zaidrashid** [medusajs/medusa#9556]
### Describe the bug

Creating a middleware on a custom API route does not seem to work or register. I was following the steps explained here [(creating basic API routes)](https://docs.medusajs.com/v2/basics/api-routes) and [here (adding middleware)](https://docs.medusajs.com/v2/advanced-development/api-routes/middlewares)

### System information

Medusa version (including plugins): v2 rc:3
Node.js version: v20.17.0
Database: Postgresql 
Operating system: Windows 11
Browser (if relevant): not relevant, tested using CURL or any API call is sufficient.

### Steps to reproduce the behavior

Example Repository -> [here](https://github.com/zaidrashid/medusa-playground)

1. Set up a new Medusa V2 service, by running `npx create-medusa-app@rc`
2. Set up a new custom API route. Such as below at `src/api/hello-world/route.ts`:
    ```js
    import type {
      MedusaRequest,
      MedusaResponse,
    } from "@medusajs/framework/http"
    
    export const GET = (
      req: MedusaRequest,
      res: MedusaResponse
    ) => {
      console.log("This is from the route");
      res.json({
        message: "[GET] Hello world!",
      })
    }
    ```
3. Set up a middleware at `src/api/middleware.ts`:
    ```js
    import { defineMiddlewares } from "@medusajs/medusa";
    import type {
      MedusaNextFunction,
      MedusaRequest,
      MedusaResponse,
    } from "@medusajs/framework/http";
    
    export default defineMiddlewares({
      routes: [
        {
          method: "GET", // having the method here declared or not, produce the same issue
          matcher: "/hello-world",
          middlewares: [
            (req: MedusaRequest, res: MedusaResponse, next: MedusaNextFunction) => {
              console.log("Received a request!");
              next();
            },
          ],
        },
      ],
    });
    ```
4. Run `npm run dev`
5. Call the API route by executing `curl http://localhost:9000/hello-world` or calling it via POSTMAN
6. Observe the terminal for console.log messages. 

### Expected behavior

Expect that there will be 2 console.log messages:
```bash
console.log("Received a request!");
console.log("This is from the route");
```
But only one from `route.ts`
```bash
console.log("This is from the route");
```

### Screenshots

![image](https://github.com/user-attachments/assets/1b2c3f1f-7d5d-47c9-9086-9498bb999c51)

### Code snippets

See steps to reproduce above

### Additional context

I am trying to set an [authentication method](https://docs.medusajs.com/v2/advanced-development/api-routes/protected-routes) in my custom API route but I found that it doesn't implement any. When I remove everything and just try to check the middleware, then only I found this issue.

**Comment by olivermrbl** [comment]
I followed the steps you outlined here and this is what I am seeing:
```
✔ Server is ready on port: 9000 – 25ms
Received a request!
This is from the route
::1 - - [14/Oct/2024:10:41:55 +0000] "GET /hello-world HTTP/1.1" 200
::1 - - [14/Oct/2024:10:41:55 +0000] "GET /favicon.ico HTTP/1.1" 404
```

Can you please provide a repository with a reproduction, and I'll try to see if there is an issue?

**Comment by zaidrashid** [comment]
Hi @olivermrbl , thanks for checking this. Sure thing, I  just pushed the repo [here](https://github.com/zaidrashid/medusa-playground). 

I skipped the configuration of `.env` file, but its just missing the configuration to the DB. The DB is clean and does not have any additional data added to it, on any tables. 

Also a little bit more on my current environment, which I forgot to add in the early post. 

1. I use `npm` instead of `yarn`. 
2. My PostgreSQL is running on a docker container. I use the `postgress:latest` image
3. I ran this on windows 11, but WSL2 running Ubuntu 22.04.3 LTS

**Comment by zaidrashid** [comment]
I am so sorry! I just realized that I should name the file `middlewares.ts` instead of `middleware.ts`. That fixes the issue. I'm closing this issue, and will update the repo incase somebody stumble upon it. 

But thanks for looking into it.
