### ISSUE TITLE
Error Starting Server Due to mappedBy reference in module models

### ISSUE THREAD

**Issue by vholik** [medusajs/medusa#9569]
## Bug report

```bash
Error starting server
Error: Loaders for module VehicleModuleService failed: VehicleYear.models has unknown 'mappedBy' reference: VehicleModel.vehicle_year
```

### Describe the bug

I encountered an error when starting the server, related to the relationships between my models in one `vehicle` module. The error specifically points to an unknown mappedBy reference between VehicleYear and VehicleModel.

**brand.ts**
```typescript
import { model } from "@medusajs/framework/utils";
import { VehicleYear } from "./year";

export const Brand = model.define("brand", {
  id: model
    .id({
      prefix: "bra",
    })
    .primaryKey(),
  name: model.text(),
  logo: model.text().nullable(),
  years: model.hasMany(() => VehicleYear),
});
```

**year.ts**
```typescript
import { model } from "@medusajs/framework/utils";
import { Brand } from "./brand";
import { VehicleModel } from "./model";

export const VehicleYear = model.define("vehicle_year", {
  id: model
    .id({
      prefix: "year",
    })
    .primaryKey(),
  year: model.number(),
  brand: model.belongsTo(() => Brand, {
    mappedBy: "years",
  }),
  models: model.hasMany(() => VehicleModel),
});
```

**model.ts**
```typescript
import { model } from "@medusajs/framework/utils";
import { VehicleYear } from "./year";
import { VehicleVariant } from "./variant";

export const VehicleModel = model.define("vehicle_model", {
  id: model
    .id({
      prefix: "model",
    })
    .primaryKey(),
  name: model.text(),
  years: model.belongsTo(() => VehicleYear, {
    mappedBy: "models",
  }),
});
```

I suspect the error might be due to having both `model.belongsTo` and `model.hasMany` in the same models (`VehicleYear` and `VehicleModel`).

### System information

Medusa version (including plugins):
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by thetutlage** [comment]
Hello @vholik 

Sorry for the late reply. Actually, the error you get is because the DML is not able to discover the inverse of the relationship using the default naming convention. 

So there are two ways to fix it. 

- First, we either stick to be conventional naming. In that case, the property name on the `VehicleModel` should be `vehicle_year` and not `year`.
  ```diff
  - years: model.belongsTo(() => VehicleYear, {
  + vehicle_year: model.belongsTo(() => VehicleYear, {
    mappedBy: "models",
  }),
  ```

- Or we define a custom `mappedBy` property when defining the relationship on the `VehicleYear` model.
  ```diff
  models: model.hasMany(() => VehicleModel, {
  +  mappedBy: "years"
  }),
  ```
