### ISSUE TITLE
@medusajs/medusa-react hasn't been published

### ISSUE THREAD

**Issue by solomonbroadbent** [medusajs/medusa#957]
likely i'm making a dumb mistake here but it seems the `@medusajs/medusa-react` package hasn't been published to npm.

following the docs here:
https://github.com/medusajs/medusa/tree/master/packages/medusa-react#installation

not found on npm as shown here:
https://www.npmjs.com/search?q=%40medusajs%2Fmedusa-react

`npm install --save @medusajs/medusa-react react-query` error:
<img width="851" alt="Screenshot 2021-12-24 at 08 17 08" src="https://user-images.githubusercontent.com/15527744/147283393-fc7c7db8-0d40-439d-a5dc-2dfe68c19c4a.png">

**Comment by srindom** [comment]
This is what you are looking for: https://www.npmjs.com/package/medusa-react

:)
