### ISSUE TITLE
Admin: Return Reasons / List View Layout Issue for the Description Field

### ISSUE THREAD

**Issue by shaun-xenon** [medusajs/medusa#9572]
### Describe the bug

After adding "Return Reasons" via the admin, the list view for this page does not correctly display the description field. The text is present but there is an issue with the layout.

### System information

Medusa version (including plugins): 2.0.0-rc.4 with no plugins
Node.js version: 21.2.0
Database: PostgreSQL 16.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit
Operating system: Kubuntu 24.04
Browser (if relevant): Firefox 131.0.2 (64-bit)

### Steps to reproduce the behavior

1. Go to 'Settings/Return Reasons'
2. Click on 'Create'
3. Add field data to 'Value', 'Label' and 'Descriptions' fields (nb, the Descriptions field should actually be singular)'
4. Click on 'Save'
5. See error

### Expected behavior

The value, label and description for the newly created "return reason" should be listed.

### Screenshots

![Medusa-Admin_v2 0 0-rc 4_(Return-Reasons-List-View)](https://github.com/user-attachments/assets/d71f8ada-c65b-4726-b70c-cfc68a9c8e1c)

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

This issue appears to be limited to Firefox for me as it works as intended using Brave and Google Chrome.

**Comment by shaun-xenon** [comment]
The list view for this page is probably in need of table headers and the addition of the 'Label' column, to be consistent with the other pages of the admin. Currently, only the 'Value' and 'Description' is displayed, and there are no headers.

![Medusa-Admin_v2 0 0-rc 4_(Return-Reasons-List-View)-2](https://github.com/user-attachments/assets/36cffa30-c2c8-4527-921a-6e96c6a6be51)

**Comment by olivermrbl** [comment]
Can you describe what is different between Firefox and Chrome? It is not obvious from the issue description. The Return Reasons table is intentionally different from others and in line with our designs. 

However, you are correct that "Descriptions" should be "Description". I'll open an issue internally for this.

**Comment by shaun-xenon** [comment]
The component that renders the label and description seems to have it's height set to a very low value, causing only 1 or 2 pixels of the top of the text to be visible.

Here is a screenshot taken with Firefox on the top and Chrome on the bottom screen that hopefully clarifies the issue.

![Medusa-Admin_v2 0 0-rc 4_(Return-Reasons-List-View)-3](https://github.com/user-attachments/assets/1115ab64-8842-4b29-aced-2aee82e2aaec)

**Comment by olivermrbl** [comment]
Thanks we'll look into it!
