### ISSUE TITLE
ts: Argument of type 'ReadonlyURLSearchParams' is not assignable to parameter of type 'string |

### ISSUE THREAD

**Issue by volkan0x** [medusajs/medusa#9578]
### Describe the bug

I get this error on `src/modules/checkout/components/payment/index.tsx` file at `createQueryString` const.

> ts: Argument of type 'ReadonlyURLSearchParams' is not assignable to parameter of type 'string | URLSearchParams | string[][] | Record<string, string> | undefined'.
>   Type 'ReadonlyURLSearchParams' is not assignable to type 'URLSearchParams'.
>     The types returned by '[Symbol.iterator]()' are incompatible between these types.
>       Type 'IterableIterator<[string, string]>' is missing the following properties from type 'URLSearchParamsIterator<[string, string]>': map, filter, take, drop, and 9 more.

### System information

Medusa version (including plugins):
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Steps to reproduce the behavior

1. Go to 'https://github.com/volfcan/medusa-frontend'
2. Clone the repository
3. See error

### Expected behavior

No errors

### Screenshots

<img width="1680" alt="Screenshot 2024-10-15 at 10 17 31" src="https://github.com/user-attachments/assets/e68ad85f-fff4-466b-872a-994d4ca44873">

### Code snippets

```typescript
  const createQueryString = useCallback(
    (name: string, value: string) => {
      const params = new URLSearchParams(searchParams)
      params.set(name, value)

      return params.toString()
    },
    [searchParams]
  )
````

**Comment by Sankalpcreat** [comment]
const params = new URLSearchParams(Array.from(searchParams.entries())); should be added in that 
<img width="922" alt="Screenshot 2024-10-16 at 3 01 11 PM" src="https://github.com/user-attachments/assets/7fbcb84b-07fa-4b08-8886-a3c8935d22c9">

1. compatibility with URLSearchParams
2. It converts the ReadonlyURLSearchParams into a format that can be directly used to create a new instance of URLSearchParams

This approach is perfectly valid and should fix the type error while allowing you to modify the query string as needed.

**Comment by SalahAdDin** [comment]
@volfcan can you check it?
