### ISSUE TITLE
Medusa V2 candidate-4

### ISSUE THREAD

**Issue by jkuzmanovik** [medusajs/medusa#9583]
I am trying to deploy completly new Medusajs v2 candidate 4 backend to railway. Here is the meduss-config, also i am using:
    "@medusajs/cache-redis": "rc",
    "@medusajs/event-bus-redis": "rc",
    "@medusajs/workflow-engine-redis": "rc",
    
  ,
import { loadEnv, defineConfig } from '@medusajs/framework/utils'

loadEnv(process.env.NODE_ENV || 'development', process.cwd())

module.exports = defineConfig({
  projectConfig: {
    databaseUrl: process.env.DATABASE_URL,
    http: {
      storeCors: process.env.STORE_CORS!,
      adminCors: process.env.ADMIN_CORS!,
      authCors: process.env.AUTH_CORS!,
      jwtSecret: process.env.JWT_SECRET || "supersecret",
      cookieSecret: process.env.COOKIE_SECRET || "supersecret",
    },
    //Worker mode 
    workerMode: process.env.MEDUSA_WORKER_MODE as "shared" | "worker" | "server",
    //Reddis-url
    redisUrl: process.env.REDIS_URL,
  },
  admin: {
    disable: process.env.DISABLE_MEDUSA_ADMIN === "true",
    backendUrl: process.env.MEDUSA_BACKEND_URL,
  },
  //Modules
  modules: [
    {
      resolve: "@medusajs/cache-redis",
      options: {
        redisUrl: process.env.REDIS_URL,
      },
    },
    {
      resolve: "@medusajs/event-bus-redis",
      options: {
        redisUrl: process.env.REDIS_URL,
      },
    },
    {
      resolve: "@medusajs/workflow-engine-redis",
      options: {
        redis: {
          url: process.env.REDIS_URL,
        },
      },
    },
  ]
})

But everytime i get this error:

Error: Module @medusajs/cache-redis doesn't have a serviceName. Please provide a 'key' for the module or check the service joiner config.
    at /app/node_modules/@medusajs/utils/src/common/define-config.ts:278:15
    at Array.reduce (<anonymous>)
    at resolveModules (/app/node_modules/@medusajs/utils/src/common/define-config.ts:234:35)
    at defineConfig (/app/node_modules/@medusajs/utils/src/common/define-config.ts:106:19)
    at Object.<anonymous> (/app/medusa-config.ts:5:30)
    at Module._compile (node:internal/modules/cjs/loader:1460:14)
    at Module.m._compile (/app/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1544:10)
    at Object.require.extensions.<computed> [as .ts] (/app/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1275:32)

**Comment by renequez** [comment]
I've solved it like this:
```ts
modules: [
      {
         resolve: '@medusajs/cache-redis',
         key: ModuleRegistrationName.CACHE,
         options: {
            redisUrl: process.env.REDIS_URL,
         },
      },
      {
         resolve: '@medusajs/event-bus-redis',
         key: ModuleRegistrationName.EVENT_BUS,
         options: {
            redisUrl: process.env.REDIS_URL,
         },
      },
      {
         resolve: '@medusajs/workflow-engine-redis',
         key: ModuleRegistrationName.WORKFLOW_ENGINE,
         options: {
            redis: {
               url: process.env.REDIS_URL,
            },
         },
      },
   ],
```
Basically adding the key property for each module. `ModuleRegistrationName` is imported from `@medusajs/framework/utils`.

This is missing from the docs, but seems to be required.

**Comment by adrien2p** [comment]
This [pr](https://github.com/medusajs/medusa/pull/9589) sould fix this issue, in the meantime, @renequez solution works 💪 

ps: if you could format the code next time it would be nice :)

**Comment by Attachai77** [comment]
I have some question. what is difference between `Modules` and  `ModuleRegistrationName`  from '@medusajs/framework/utils' , Could I use either ?

**Comment by olivermrbl** [comment]
@adrien2p, can we close this issue? 🙏

**Comment by adrien2p** [comment]
Yes we can 👌 
@Attachai77 the registration name will be removed if not already the case. It is a legacy constant
