### ISSUE TITLE
Pivot tablet deleted after update to RC4

### ISSUE THREAD

**Issue by renanboni** [medusajs/medusa#9597]
## Bug report
I was on Medusa RC2 when I decided to update it to RC4 today -  when I ran the **npx medusa db:sync-links** command it said my table had been deleted.

![Screenshot 2024-10-15 at 20 24 30](https://github.com/user-attachments/assets/a107d35e-2153-4d23-99d2-58f2f9b8a96c)

then when I went to pgAdmin (before pressing enter to delete it) to see the tables I noticed it had two:
public.api_key_api_key_marketplacemodule_vendor
public.apikey_api_key_marketplacemodule_vendor

the module seems to have been renamed, but I'd like to confirm.

### System information

Medusa version (including plugins): update from RC2 to RC4
Node.js version:
Database:
Operating system:
Browser (if relevant):

**Comment by olivermrbl** [comment]
Yes, this is correct. We had a minor regression in the RC2 around link tables naming.

**Comment by renanboni** [comment]
thanks @olivermrbl closing :)
