### ISSUE TITLE
Shipping Options Service Missing, canCalculate is never called.

### ISSUE THREAD

**Issue by amaster507** [medusajs/medusa#9598]
### Describe the bug

The `shipping-options` service seems to be missing

### System information

Medusa version (including plugins):
Node.js version: 20
Database: postgres
Operating system: linux host with docker containers running node/postgres/redis/etc.
Browser (if relevant): Chrome/NA

### Steps to reproduce the behavior

1. Implement a class extending the `AbstractFulfillmentProviderService` with the `canCalculate` and other methods.
2. Update `medusa-config.js` to use the custom fulfillment provider service.
3. Update the admin to use the custom fulfillment provider service and create shipping options using a calculated price. 

### Expected behavior

The custom fulfullment `canCalculate` should be called when listing shipping options for a calculated options.

### Screenshots

See Discussion linked below

### Code snippets

https://github.com/medusajs/medusa/discussions/9495

### Additional context

From looking at the 1.x repo, the `canCalculate` method is called withing the `packages > medusa > src > services > shipping-options.ts` And this gets called from `validatePriceType_` which gets called from `validateAndMutatePrice`, etc. None of these seem to exist anymore in the v2 repo. Obviously there was a refactor, and I believe these were not added back in after the refactor.

**Comment by olivermrbl** [comment]
You are right, we haven't added backend support for calculated prices on shipping options yet. This is something we will look into in the coming days or right after the official release :)

**Comment by amaster507** [comment]
assuming this will be post 2.0 release? Is there any indication in the docs what other features like this may not yet be fully developed. The 2.0 docs lead me to believe that a fulfillment service would be functional if I developed it correctly and added it to the configuration. Just want to know what else is lacking in the official 2.0 release.

**Comment by ikok07** [comment]
> You are right, we haven't added backend support for calculated prices on shipping options yet. This is something we will look into in the coming days or right after the official release :)

I want to use Medusa for my next project but I really need this feature. Will it be available in the next couple of days?

**Comment by victormamede** [comment]
I also noticed that the medusa sdk throws an error if there's no price for a shipping option, even if that price is calculated.

**Comment by Reomar** [comment]
Is this bug fixed ?!

**Comment by amaster507** [comment]
Not that I am aware of. I've postponed trying to get it to work until some official word about the status of plugin modules like this and their future. If they plan on supporting the existing APIs or if there is some other model that should be followed instead.

**Comment by amaster507** [comment]
@olivermrbl any updates? It's been a few days since 2.0 release...

**Comment by amaster507** [comment]
is this addressed at all with the latest releast https://github.com/medusajs/medusa/tree/v2.1.0? I would like official feedback before I wast time on trying to see if this works now or not. Maybe with the commit #10432 ??

**Comment by amaster507** [comment]
@olivermrbl was this resolved in the 2.1.1 release??

> ### Shipping option rules
>
> We've introduced support for pricing rules on shipping options. Initially, the feature allows you to define prices based on the cart item total. For example, you could have a free shipping option that is only available when the item total is above 100 EUR.
> Every time the cart is updated, e.g. with new items, we refresh the shipping methods to ensure the correct price is applied at all times.
> You'll find the new setting in the admin dashboard under "Settings > Locations & Shipping > View details > Edit prices (on shipping option)".

**Comment by olivermrbl** [comment]
@amaster507, this is part of the next release, likely shipping later this week. My apologies for not following up.

**Comment by Saman67** [comment]
@olivermrbl - Can you give us update about this issue? Thanks

**Comment by Reomar** [comment]
I think it's fixed in v2.1.3, is that right?

**Comment by shahednasser** [comment]
Hey guys, this issue is fixed in the latest release. Will close this issue now.

**Comment by blbergo** [comment]
I'm having a similar problem to this in v2.1.3, where `validateOption` appears to not be called when creating a calculated shipping option from the UI. For context, I'm building a custom shipping integration with Shippo, and they require creating a service zone before requesting live rates at checkout, and so it would make sense to create this zone once the option is created by an admin user.

**Comment by blbergo** [comment]
I am now having the same issue with `validateFulfilmentData` - for anyone looking for a workaround, try overriding the default API routes for `/shipping-option/your-desired-route` to intercept requests

**Comment by shahednasser** [comment]
Hey @bibergo I would advise you to update to the latest version, and if it's still not working then please open a new issue with all your setup's details so that we can provide better support.

**Comment by JayeshGorasia** [comment]
Having Issue with return shipping_options for return order calculatePrice not getting called when selecting return shipping option on return order in admin panel due to which its returning falling error
Cannot read properties of null (reading 'calculated_amount')
{
  message: "Cannot read properties of null (reading 'calculated_amount')",
  name: 'TypeError',
  stack: "TypeError: Cannot read properties of null (reading 'calculated_amount')\n" +
    '    at Function.<anonymous> (/home/jayeshgorasia/office-dev/shopper2/node_modules/@medusajs/core-flows/src/order/utils/prepare-shipping-method.ts:14:35)\n' +
    '    at Proxy.returnFn (/home/jayeshgorasia/office-dev/shopper2/node_modules/@medusajs/workflows-sdk/src/utils/composer/transform.ts:192:30)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async resolveProperty (/home/jayeshgorasia/office-dev/shopper2/node_modules/@medusajs/workflows-sdk/src/utils/composer/helpers/resolve-value.ts:17:11)\n' +
    '    at async resolveValue (/home/jayeshgorasia/office-dev/shopper2/node_modules/@medusajs/workflows-sdk/src/utils/composer/helpers/resolve-value.ts:78:7)\n' +
    '    at async Promise.allSettled (index 0)\n' +
    '    at async promiseAll (/home/jayeshgorasia/office-dev/shopper2/node_modules/@medusajs/utils/src/common/promise-all.ts:27:18)\n' +
    '    at async unwrapInput (/home/jayeshgorasia/office-dev/shopper2/node_modules/@medusajs/workflows-sdk/src/utils/composer/helpers/resolve-value.ts:50:14)\n' +
    '    at async unwrapInput (/home/jayeshgorasia/office-dev/shopper2/node_modules/@medusajs/workflows-sdk/src/utils/composer/helpers/resolve-value.ts:65:26)\n' +
    '    at async resolveValue (/home/jayeshgorasia/office-dev/shopper2/node_modules/@medusajs/workflows-sdk/src/utils/composer/helpers/resolve-value.ts:79:7)\n' +
    '⮑ sat /home/jayeshgorasia/office-dev/shopper2/node_modules/@medusajs/core-flows/dist/order/workflows/return/create-return-shipping-method.js: [create-return-shipping-method -> create-order-shipping-methods (invoke)]'
}

**Comment by shahednasser** [comment]
@JayeshGorasia please open a new issue explaining your problem
