### ISSUE TITLE
Want to deploy on google cloud run

### ISSUE THREAD

**Issue by QasimRiaz** [medusajs/medusa#9609]
### What Medusa version and documentation are you using?

None

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Its working on the windows locally. i want to run on the google cloude run its deploy but issues with multipul ports any artical fix this issue or guide me ?

### How can this issue be resolved?

1
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by olivermrbl** [comment]
Appreciate the interest in the project. Unfortunately, we don't (and likely won't) have a guide for this any time soon. Please seek help in our Discord community or elsewhere :)

**Comment by xeonnux** [comment]
Hi I am currently working on deploying my app using github actions to cloudrun and currently got my backend working but still need to deploy and connect my frontend. Will post here a documentation of how I did so once I have completed.

**Comment by irab** [comment]
> Hi I am currently working on deploying my app using github actions to cloudrun and currently got my backend working but still need to deploy and connect my frontend. Will post here a documentation of how I did so once I have completed.

Hi @xeonnux , how did it go with the Cloud Run deployment?
