### ISSUE TITLE
Product variants are not editable (v2)

### ISSUE THREAD

**Issue by renequez** [medusajs/medusa#9620]
### Describe the bug

Product variants are not editable, whatever field I'd try to edit I'm getting the error `Variant (M) with provided options already exists.`

### System information

Medusa version (including plugins): rc 6, fresh install, no plugins
Node.js version: 20.17.0
Database: PostgreSQL 16.4
Operating system: Windows 11
Browser (if relevant): Edge

### Steps to reproduce the behavior

1. Start a new Medusa project with `npx create-medusa-app@rc`.
2. Go to one of the seeded products, e.g. Medusa Sweatpants (or create a new product)
3. Edit any field for any of the variants.
4. Press `Save`.

### Expected behavior

I should be able to edit product variants.

### Screenshots

![image](https://github.com/user-attachments/assets/18c53e42-137f-4468-892d-ac4a03c7b831)

**Comment by olivermrbl** [comment]
Thanks for the report, we'll get to this asap
