### ISSUE TITLE
Medusa Development Resources: Issue in Integrations - Medusa Development Resources

### ISSUE THREAD

**Issue by Jotadebeese** [medusajs/medusa#9627]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In the [integrations](https://docs.medusajs.com/v2/resources/integrations) section of the Medusa documentation, the examples for **Payments** and **Files** are inverted. Specifically, **Stripe** is currently listed under Files while **AWS S3** is under Payments, which seems incorrect.

- Stripe should be listed under Payments.
- AWS S3 (and compatible APIs) should be under Files.

Please see the attached screenshot for reference:

![image](https://github.com/user-attachments/assets/49683532-2fc4-4a84-8476-1c9678655690)

### How can this issue be resolved?

1. Stripe should be listed under Payments.
2. AWS S3 (and compatible APIs) should be under Files.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for reporting this! Someone already opened a PR to fix it #9627
