### ISSUE TITLE
Docs (Code Issue): Missing Query Parameter in Example of Workflow

### ISSUE THREAD

**Issue by VrajPatelK** [medusajs/medusa#9628]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In the [documentation](https://docs.medusajs.com/v2/basics/workflows#4-test-workflow), the example provided for making a request to the workflow endpoint is missing the `name` query parameter.

### Actual example:
```
curl http://localhost:9000/workflow
```

### Expected example:
```
curl http://localhost:9000/workflow?name=john
```

This is causing an issue when using the workflow in code, as demonstrated below.

## Code Example:

- Workflow : `src/workflows/hello-world.ts`

```bash
import {
  createStep,
  createWorkflow, StepResponse, WorkflowResponse
} from "@medusajs/framework/workflows-sdk"

// step-1
const step1 = createStep("step-1", async () => {
  return new StepResponse(`Hello from step one!`)
})

// step-2
type WorkflowInput = {
  name: string
}

const step2 = createStep("step-2", async ({ name }: WorkflowInput) => {
  return new StepResponse(`Hello ${name} from step two!`)
})

// workflow
const myWorkflow = createWorkflow(
  "hello-world",
  function (input: WorkflowInput) {
    const str1 = step1()
    // to pass input
    const str2 = step2(input)

    return new WorkflowResponse({
      message: str1,
    })
  }
)

export default myWorkflow


```

- API Route : `src/api/workflow/route.ts`

```bash
import type {
  MedusaRequest,
  MedusaResponse,
} from "@medusajs/framework/http"
import myWorkflow from "../../workflows/hello-world"

export async function GET(
  req: MedusaRequest,
  res: MedusaResponse
) {
  const { transaction, result, errors } = await myWorkflow(req.scope)
    .run({
      input: {
        name: req.query.name as string,
      },
    })

  res.json({
    transaction,
    result,
    errors,
  })
}
```

When running this code with `curl http://localhost:9000/workflow`. I encountered the following issue:

- Console output for a `transaction`: 

```bash
{
  "transaction": {
    # ... other fields
    "context": {
      "payload": {},
      "invoke": {
        "step-1": {
          "__type": "Symbol(WorkflowWorkflowData)",
          "output": {
            "__type": "Symbol(WorkflowStepResponse)",
            "output": "Hello from step one!",
            "compensateInput": "Hello from step one!"
          }
        },
        "step-2": {
          "__type": "Symbol(WorkflowWorkflowData)",
          "output": {
            "__type": "Symbol(WorkflowStepResponse)",
            "output": "Hello undefined from step two!", # undefined
            "compensateInput": "Hello undefined from step two!"  # undefined
          }
        }
      },
      "compensate": {}
    },
   # ... other fields
  },
  "result": {
    "message": "Hello from step one!"
  },
  "errors": []
}

```

The issue arises because the `name` parameter is not passed in the request. Updating the curl command in the [documentation](https://docs.medusajs.com/v2/basics/workflows#4-test-workflow) to include the correct query parameter would resolve this issue.

#### Steps to Reproduce:

1. Implement the code as shown above.
2. Run the curl command `curl http://localhost:9000/workflow` (as per the docs).
3. The output will be `Hello undefined from step two!`

#### Resolution Suggestion: 

Update the [documentation](https://docs.medusajs.com/v2/basics/workflows#4-test-workflow) to include the query parameter in the curl command:

```
curl http://localhost:9000/workflow?name=john
```

### Are you interested in working on this issue?

- [x] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch! Feel free to open a PR with the fix. You can click on "Edit this page" at the end of the page, make the change, and open the PR.

**Comment by VrajPatelK** [comment]
Hey! @shahednasser I have raised the [PR#9640](https://github.com/medusajs/medusa/pull/9640) for this[#9628] issue.
But, I am facing this authentication error for deployment on a Vercel. Can you ensure it, once ?

**Comment by VrajPatelK** [comment]
should I re run the jobs ?
