### ISSUE TITLE
Docs(Code Issue): Missing Product Options in Admin API Product Creation with Additional Data Example

### ISSUE THREAD

**Issue by VrajPatelK** [medusajs/medusa#9632]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In the Medusa [documentation](https://docs.medusajs.com/v2/customization/extend-models/extend-create-product#test-it-out), the current `curl` example for creating a product via the Admin API is missing the `options` field, which is required for the product. This results in an error when attempting to create a product.

### Current Example:

```bash
curl -X POST 'http://localhost:9000/admin/products' \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer {token}' \
--data '{
    "title": "Product 1",
    "additional_data": {
        "brand_id": "01J7AX9ES4X113HKY6C681KDZ2J"
    }
}'
```

### Expected Example:

```bash
curl -X POST 'http://localhost:9000/admin/products' \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer {your_token}' \
-d '{
  "title": "Product 1",
  "options": [
    {
      "title": "Default option",
      "values": ["Default option value"]
    }
  ],
  "additional_data": {
    "brand_id": "01J7AX9ES4X113HKY6C681KDZ2J"
  }
}'

```

This missing field leads to the following error:

### Code Example:

```bash
{
  "type": "invalid_data",
  "message": "Product options are not provided for: [Product 1]."
}

```

### Steps to Reproduce:

1. Run the provided curl command:

```bash
curl -X POST 'http://localhost:9000/admin/products' \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer {token}' \
--data '{
    "title": "Product 1",
    "additional_data": {
        "brand_id": "01J7AX9ES4X113HKY6C681KDZ2J"
    }
}'

```
2. Observe the error message indicating that product options are missing.

### Resolution Suggestion:

Update the [documentation](https://docs.medusajs.com/v2/customization/extend-models/extend-create-product#test-it-out) with the correct `curl` example, including the `options` field:

```bash
curl -X POST 'http://localhost:9000/admin/products' \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer {your_token}' \
-d '{
  "title": "Product 1",
  "options": [
    {
      "title": "Default option",
      "values": ["Default option value"]
    }
  ],
  "additional_data": {
    "brand_id": "01J7AX9ES4X113HKY6C681KDZ2J"
  }
}'

```

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for submitting this issue @VrajPatelK ! This is due to a new update that requires an option to be passed.

Will open a PR to fix it
