### ISSUE TITLE
create-medusa-app: Found invalid GitHub URL error

### ISSUE THREAD

**Issue by bitcoinvsalts** [medusajs/medusa#9659]
## Bug report

Trying to run this command:

```
npx create-medusa-app@latest
```

### Describe the bug

Error logs:

```
✔ Created project directory
⠧ Installing Next.js Storefront...

   ┌─────────────────────────────────────────── 💡 Medusa Tips ────────────────────────────────────────────┐
   │                                                                                                       │
   │   Medusa's store endpoint paths are prefixed by /store. The admin endpoints are prefixed by /admin.   │
   │                                                                                                       │
   └───────────────────────────────────────────────────────────────────────────────────────────────────────┘
An error occurred while installing Next.js storefront: Error: Command failed: npx create-next-app@latest -e https://github.com/medusajs/nextjs-starter-medusa my-medusa-stor-storefront
Found invalid GitHub URL: "https://github.com/medusajs/nextjs-starter-medusa". Please fix the URL and try again.
```

### System information

Medusa version (including plugins):
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by shahednasser** [comment]
Hi @bitcoinvsalts , can you provide more details on your OS and node version? I can't reproduce the issue on my side.

Also, can you try running `npx create-next-app@latest -e https://github.com/medusajs/nextjs-starter-medusa my-medusa-stor-storefront` separately and see if the error occurs?

**Comment by bitcoinvsalts** [comment]
Hi @shahednasser 
Sorry, it was due to my local env. I am closing it.
