### ISSUE TITLE
404 on all Admin pages when navigated to directly.

### ISSUE THREAD

**Issue by joekendal** [medusajs/medusa#9660]
### Describe the bug

When you deploy the admin to Vercel following the guide, it is only possible to enter the / path in the URL and then navigate to another section by clicking the navbar element. If you try to reload a URL such as /orders or /products you will get a 404.

The implementation is only allowing dynamic URL updates which is not what is conformant with web standards.

### System information

Medusa version (including plugins): 2.0.0-rc6
Node.js version: 20
Database: Postgres
Operating system: Linux
Browser (if relevant):

### Steps to reproduce the behavior

1. Follow the Admin deployment guide for Vercel
2. Visit the domain URL. 
3. When it has loaded /orders, or if you have clicked on products, just hit reload
4. Get a 404

### Expected behavior

The path should be navigable directly from the URL rather than a dynamic update from the root each time.

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by kasperkristensen** [comment]
Hi @joekendal, did you include a `rewrites` in your vercel.json? It's described here: https://docs.medusajs.com/deployments/admin/deploying-on-vercel#step-3-add-vercel-configurations

**Comment by joekendal** [comment]
@kasperkristensen yes, and this error was only introduced when upgrading from v2 rc #2 -> v2 rc #3

So it was working previously on medusa without any problems. I've set the build command to `yarn build --admin-only`
 output directory to `.medusa/admin` in vercel
 
 Are the v2 rewrites correct?

**Comment by joekendal** [comment]
This seems to be caused by a monorepo setup. Closing

**Comment by JohnGemstone** [comment]
Had this same issue, my mistake was putting `vercel.json` into the root of the monorepo rather than the root of `./apps/backend`. Just in case others face the same issue.
Cheers
