### ISSUE TITLE
Examples in documentation now lead to error 404

### ISSUE THREAD

**Issue by chrislicodes** [medusajs/medusa#9670]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

When navigating to https://docs.medusajs.com/v2/learn/more-resources/examples we are now met with a Error 404.

### How can this issue be resolved?

Navigate to https://docs.medusajs.com/v2/learn/more-resources/examples

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Hi @chrislicodes , we changed this examples section to instead be https://docs.medusajs.com/v2/resources/examples for more examples. We added a redirect but must have been missed between some of the latest changes.

Will close this issue now, feel free to reopen if necessary.
