### ISSUE TITLE
Admin: Add new currency with Tax Inclusive Pricing enabled doesn't automatically update status in list view

### ISSUE THREAD

**Issue by shaun-xenon** [medusajs/medusa#9673]
### Describe the bug

After adding a new currency with the **Tax Inclusive Pricing** switch enabled, the change isn't immediately visible in the list view after saving. You need to refresh the page to see that it's enabled, and navigating away and back won't update it either.

As a side note, consider changing the values of _True_ and _False_ in the admin to _Yes_ and _No_.

### System information

Medusa version (including plugins): 2.0.0-rc.7 without plugins
Node.js version: 21.2.0
Database: PostgreSQL 16.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit
Operating system: Kubuntu 24.04
Browser (if relevant): Google Chrome 130.0.6723.58 (Official Build) (64-bit); Firefox 131.0.3 (64-bit)

### Steps to reproduce the behavior

1. Go to 'Settings > Store > Currencies'
2. Click on 'Add'
3. Select any currency to add
4. Enable 'Tax inclusive pricing'
5. Click on 'Save'
6. See that 'Tax inclusive pricing' is 'False' for the newly added currency
7. Refresh page
8. See that it now shows 'True'

### Expected behavior

Upon hitting the 'Save' button, the list view should immediately show that the currency added has **Tax Inclusive Pricing** enabled.

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by olivermrbl** [comment]
@ShaunXenonKhan, we'll get this sorted out asap :)
