### ISSUE TITLE
Admin: Grammar/spelling issue on new account registration flow

### ISSUE THREAD

**Issue by shaun-xenon** [medusajs/medusa#9674]
### Describe the bug

I noticed two grammatical errors affecting the Medusa Admin's professionalism during the account creation flow.

1) "Create you account below" should be "Create your account below"
2) "Your account has is registered" should be "Your account has been registered" or "Your account is now registered"

### System information

Medusa version (including plugins): 2.0.0-rc.7 without plugins (the issue was noticed in the preview and regrettably, I didn't raise the issue sooner)
Node.js version: n/a
Database: n/a
Operating system: n/a
Browser (if relevant): n/a

### Steps to reproduce the behavior

1. Invite a new user to create an admin account
2. Follow link to account creation form
3. See error

### Source files

The source file is "packages/admin/dashboard/src/i18n/translations/en.json"

Here are the keys:

Issue 1: "invite.hint"
Issue 2: "invite.successTitle"

**Comment by ShaunXenonKhan** [comment]
I don't know the files these strings are located in, so hopefully some screenshots will help.

![Medusa-Admin_v2 0 0-rc 7_(Welcome-1)](https://github.com/user-attachments/assets/2fb9e64e-67f7-409d-b2b7-8a628ba32986)

![Medusa-Admin_v2 0 0-rc 7_(Welcome-2)](https://github.com/user-attachments/assets/00f0c8ea-1aa6-4e29-a997-da643835cad0)

**Comment by olivermrbl** [comment]
@ShaunXenonKhan, thanks for the report. Please feel free to send a PR :)
