### ISSUE TITLE
Loaders for module Payment failed: Trying to register a payment provider without a provider identifier.

### ISSUE THREAD

**Issue by homosape** [medusajs/medusa#9678]
## Bug report
Hi, I can't build backend after adding custom payment provider.

### Describe the bug
I've created Medusa v2 project from scratch and the only thing I did was adding custom payment provider according documentation. After I did that `yarn dev` was started throwing an error.

### System information

Medusa version (including plugins):
```
  "dependencies": {
    "@medusajs/admin-sdk": "rc",
    "@medusajs/framework": "rc",
    "@medusajs/medusa": "rc",
    "@medusajs/medusa-cli": "rc",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
```
Node.js version: v20.12.1
Database: Supabase
Operating system: macOS
Browser (if relevant):

### Steps to reproduce the behavior

1. Create new Medusa project with `npx create-medusa-app@rc`
2. Skip creating storefront
3. Add custom payment provider to modules
4. Add all methods according [documentation](https://docs.medusajs.com/v2/resources/references/payment/provider)
5. Run `yarn dev`

### Expected behavior

App should start and I should be able to see new payment provider in Admin panel.

### Screenshots
<img width="1081" alt="Screenshot 2024-10-19 at 17 30 48" src="https://github.com/user-attachments/assets/26143fa4-0656-4875-8531-b04a0ee906ff">

<img width="296" alt="Screenshot 2024-10-19 at 17 35 58" src="https://github.com/user-attachments/assets/4c98b74d-ea95-410b-9365-bcc557e8d976">

<img width="666" alt="Screenshot 2024-10-19 at 17 36 37" src="https://github.com/user-attachments/assets/6addab1b-0ed6-4b21-a467-b35110290390">

### Code snippets
`medusajs.config.ts`
```
import { loadEnv, defineConfig } from "@medusajs/framework/utils";

loadEnv(process.env.NODE_ENV || "development", process.cwd());

module.exports = defineConfig({
  modules: [
    {
      resolve: "@medusajs/medusa/payment",
      options: {
        providers: [
          {
            resolve: "./src/modules/bog",
            id: "bog-payment",
          },
        ],
      },
    },
  ],
  projectConfig: {
    databaseUrl: process.env.DATABASE_URL,
    http: {
      storeCors: process.env.STORE_CORS!,
      adminCors: process.env.ADMIN_CORS!,
      authCors: process.env.AUTH_CORS!,
      jwtSecret: process.env.JWT_SECRET || "supersecret",
      cookieSecret: process.env.COOKIE_SECRET || "supersecret",
    },
  },
});

**Comment by olivermrbl** [comment]
@homosape, any chance you can create a repository with a reproduction? Would happily take a look

**Comment by olivermrbl** [comment]
@homosape, I just tried to follow the steps outlined in the documentation linked above, and I could not reproduce the issue.

**Comment by homosape** [comment]
@olivermrbl original repo is in bitbucket and it's private but here is the exact copy of it in github https://github.com/homosape/medusa-v2-starter

Changes that I've made are in develop branch

**Comment by olivermrbl** [comment]
It seems your lock-file isn't up to date. I would have created a PR with the changes, but I don't have access.

The steps are:
- Delete lock file
- Remove dependencies `@medusajs/medusa-cli` and `medusa-test-utils` from `package.json`
- Install dependencies `@medusajs/cli@rc` and `@medusajs/test-utils@rc`

Separately, I noticed an error in our docs. You should not use `Modules.PAYMENT` when you create the provider export in `bog/index.ts`. You should use a name specific to your provider, e.g. "bog_payment".

**Comment by homosape** [comment]
@olivermrbl  thanks!
