### ISSUE TITLE
Bug: Logged in user gets passed back to all storefronts

### ISSUE THREAD

**Issue by 420coupe** [medusajs/medusa#9679]
### Describe the bug

When a user logs in to the storefront, the logged in customer credentials get sent to all incoming request regardless of original request. 

ie if i log in on my cell phone with user test@gmail.com
My desktop which was not logged in, can refresh and will now be logged into test@gmail.com

### System information

Medusa version (including plugins):``@medusajs/medusa@2.0.0-rc-20241018141633"``
Node.js version: `v21.7.1`
Database: `Supabase(postgres)`
Operating system: `Ubuntu 22.4.04 LTS`
Browser (if relevant):

### Steps to reproduce the behavior

1. Stand up medusajs v2 latest rc and nextjs store front
2. Open browser a and create an account and log in
3. Open incognito browser b and click account -> you will be signed into account above.

### Expected behavior

The user credentials should only be sent back to the originating ip that requested it, not all incoming requests.

**Comment by olivermrbl** [comment]
Thanks for highlighting, this is solved in #9704 and part of the next preview release + official release.
