### ISSUE TITLE
allow_backorder and manage_inventory Fields Not Persisted During Product Variant Updates in Update Products Workflow

### ISSUE THREAD

**Issue by erickirt** [medusajs/medusa#9680]
### I'm experiencing an issue where the `allow_backorder` and `manage_inventory` fields are not correctly persisted when updating product variants using the update products workflow in MedusaJS.

**Steps to Reproduce**:

1. Use the `update-products` workflow to update one or more product variants, including the `allow_backorder` and `manage_inventory` fields in the variant data.
2. After the workflow completes, check the updated product variants in the database or via the API.
3. Observe that the `allow_backorder` and `manage_inventory` fields have not been updated and retain their previous values.

**Expected Behavior**:

- The `allow_backorder` and `manage_inventory` fields should be correctly updated and persisted in the database when provided in the update payload for product variants.

**Actual Behavior**:

- The `allow_backorder` and `manage_inventory` fields are not updated in the database, and their values remain unchanged after the update workflow is executed.

**Analysis and Possible Cause**:

After reviewing the MedusaJS codebase, it appears that these fields are not being correctly handled and persisted during the update products workflow. Specifically:

1. **Workflow Input Preparation**:
   - **File**: `packages/core/core-flows/src/product/workflows/update-products.ts`
   - **Function**: `prepareUpdateProductInput`
   - **Issue**: The function does not manipulate or exclude `allow_backorder` and `manage_inventory`, but it's unclear if these fields are being passed through correctly to the update step.

2. **Update Products Step**:
   - **File**: `packages/core/core-flows/src/product/workflows/steps/update-products.ts`
   - **Function**: `updateProductsStep`
   - **Issue**: The step delegates the update to the `IProductModuleService`, but there is no explicit handling to ensure that `allow_backorder` and `manage_inventory` are persisted.

3. **Service Layer**:
   - **File**: `packages/modules/product/src/services/product-module-service.ts`
   - **Class**: `ProductModuleService`
   - **Method**: `updateVariants_`
   - **Issue**: The method does not seem to process the `allow_backorder` and `manage_inventory` fields when updating product variants.

**Relevant Code Snippets**:

- **Validators Definition**:
  - **File**: `packages/medusa/src/api/admin/products/validators.ts`
  - The fields are defined and accepted in the `UpdateProductVariant` schema:

    ```typescript
    export const UpdateProductVariant = z.object({
      // ... other fields ...
      allow_backorder: booleanString().optional(),
      manage_inventory: booleanString().optional(),
      // ... other fields ...
    });
    ```

- **Update Workflow Lacks Explicit Handling**:
  - In `update-products.ts` and `product-module-service.ts`, there's no explicit code to map and persist these fields during the update process.

**Possible Solution**:

- **Modify the Update Workflow**:
  - Ensure that the `updateProductVariantsStep` in `update-product-variants.ts` includes logic to handle the `allow_backorder` and `manage_inventory` fields.
  - Update the `updateVariants_` method in `product-module-service.ts` to process and persist these fields when updating product variants.

**Additional Information**:

- **Affected Files**:
  - `packages/core/core-flows/src/product/workflows/update-products.ts`
  - `packages/core/core-flows/src/product/workflows/steps/update-products.ts`
  - `packages/modules/product/src/services/product-module-service.ts`
  - `packages/medusa/src/api/admin/products/validators.ts`

- **MedusaJS Version**: rc-5

**Request**:

Could you please investigate this issue and provide a fix to ensure that `allow_backorder` and `manage_inventory` are correctly persisted when updating product variants using the update products workflow?

**Thank you** for your attention to this matter!

**Comment by olivermrbl** [comment]
@erickirt, I am unable to reproduce your issue. Can you please review [this test](https://github.com/medusajs/medusa/compare/chore/test-variant-update?expand=1) and let me know if I am missing something?

**Comment by erickirt** [comment]
Nevermind, I found the issue was in setting the manage inventory to false while keeping allow back orders true was overriding the manage_inventory:false and creating the variants anyway.
