### ISSUE TITLE
Docs(Code Issue): Medusa object not constructable (JS SDK)

### ISSUE THREAD

**Issue by Ketlark** [medusajs/medusa#9698]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I want to use medusa JS SDK to perform call on backend server, but when i use the default sample code from documentation, the medusa object is not constructable:

![image](https://github.com/user-attachments/assets/5e4cacbc-672b-42d7-9770-18a9893e5eef)

### How can this issue be resolved?

Issue can be solved by calling `new Medusa.default`

### Are you interested in working on this issue?

- [x] I would like to fix this issue

**Comment by shahednasser** [comment]
Hello, can you clarify which code snippet you used from the docs? And which page are you referring to?

**Comment by Ketlark** [comment]
Of course, it's this part : https://docs.medusajs.com/v2/resources/js-sdk#setup-js-sdk. I get rid of error but can't still used the SDK normally, even after tried multiple class import from it

**Comment by shahednasser** [comment]
Can you share your code block? Also, what type of project are you using it in?

**Comment by Ketlark** [comment]
```
import env from '#start/env'
import Medusa from '@medusajs/js-sdk'

export default class MedusaService {
  private static instance: Medusa.Admin
  private static MEDUSA_API_KEY = env.get('MEDUSA_API_KEY')

  static getInstance() {
    if (!MedusaService.instance) {
      MedusaService.instance = new Medusa.default({
        baseUrl: 'https://erp.mullo.fr',
        apiKey: this.MEDUSA_API_KEY,
      }).admin
    }
    return MedusaService.instance
  }
}

```

A sample nodeJS backend project that use Medusa backend API

**Comment by thetutlage** [comment]
Can you please share the tsconfig of your project?

**Comment by Ketlark** [comment]
@thetutlage here is it 

```
{
  "extends": "@adonisjs/tsconfig/tsconfig.app.json",
  "compilerOptions": {
    "jsx": "react",
    "rootDir": "./",
    "outDir": "./build",
  },
}
```
with base : 
```

{
  "compilerOptions": {
    "target": "ESNext",
    "module": "NodeNext",
    "lib": ["ESNext"],
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "isolatedModules": true,
    "removeComments": true,
    "esModuleInterop": true,
    "strictNullChecks": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "strictPropertyInitialization": true,
    "experimentalDecorators": true,
    "noImplicitAny": true,
    "strictBindCallApply": true,
    "strictFunctionTypes": true,
    "noImplicitThis": true,
    "skipLibCheck": true
  },
  "ts-node": {
    "swc": true
  }
}
```

**Comment by thetutlage** [comment]
Hello @Ketlark 

I looked into the issue and it seems like our JS SDK is not compatible with the ESM implementation of Node.js and therefore it is not working at runtime and have type errors as well.

I will be working on it in the coming days and will let you know.

**Comment by Ketlark** [comment]
@thetutlage any news or blocking steps ? maybe i can help to fix it

**Comment by thetutlage** [comment]
Hello @Ketlark 

Sorry for the late reply. We will discussing on fixing this issue this Monday internally and will keep you posted about it.

**Comment by Ketlark** [comment]
@thetutlage Is that long to fix ? I think it's not a minor bug considering usage of the lib outside of medusa, it's literraly unusable atm

**Comment by CosmicNIO** [comment]
@thetutlage Any update on this?

**Comment by xzymxeqgmc** [comment]
any follow up on this?
