### ISSUE TITLE
Medusa v2 Documentation: Issue in 3.3. Modules - Test the Module

### ISSUE THREAD

**Issue by mk0y** [medusajs/medusa#9700]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In the [Test the Module](https://docs.medusajs.com/v2/learn/basics/modules#test-the-module) section GET request is being used to create new entity. GET should list entities or get a single entity.

### How can this issue be resolved?

1. Instead of GET, it should be a POST request definition.

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch! Feel free to open a PR to fix it.

**Comment by sradevski** [comment]
This seems to have been fixed, closing
