### ISSUE TITLE
Custom Admin UI Route is being added to the extensions

### ISSUE THREAD

**Issue by Rohit-Bera** [medusajs/medusa#9706]
## Bug report

As we have already seen in medusa v1 that , we had medusa-admin to customize side-bar ui routes ,  based on requirements.

Medusa Admin : https://github.com/medusajs/admin .
but this repo has been archived.

and in Medusa V2 when i am trying to add custom side bar ui route , it is being added into the extensions.
As per Medusa V1 user , when we add any plugin or extra functionality , it is being added into the extensions.

### System information

Medusa version (including plugins):  v2
Node.js version: v20.13.1
Database: postgresql
Browser (if relevant): chrome

### Steps to reproduce the behavior
please refer this documentation : https://docs.medusajs.com/v2/learn/customization/customize-admin/route

### Expected behavior
the custom Admin UI route should be added in the side-bar after any option `orders` , `products` , etc like it used to work in medusa v1. 

### Screenshots
<img width="1792" alt="Screenshot 2024-10-22 at 11 17 30 AM" src="https://github.com/user-attachments/assets/346c24f6-9123-4fcd-b9b5-784ca1bf4e07">

### Additional context
Also it would be more helpfull , if you add more ui options like `Routedrawer` , `SingleColumnPage` , `TwoColumnPage` etc.
so it would be easier to create same ui as medusa v2 which it is currently providing.

**Comment by thetutlage** [comment]
Hello @Rohit-Bera 👋

This is working as intended as per the design choice we had made with V2. All custom routes now shows up under the `Extensions` group.
