### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by JamieSlome** [medusajs/medusa#971]
Hey there!

I belong to an open source security research community, and a member (@razorboygrim) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by olivermrbl** [comment]
Hi @JamieSlome! 

Many thanks for reaching out and keeping us up to speed. We've just added the `SECURITY.md` file.

Looking forward to hearing from you @razorboygrim :)

**Comment by JamieSlome** [comment]
Hello @olivermrbl - great! 👍 We appreciate the swiftness!

You should receive a couple of e-mails shortly with more information, otherwise, you can view the reports directly here in the meantime:

https://huntr.dev/bounties/1aee5e83-70e0-4fbd-8255-6cbc6966f184/
https://huntr.dev/bounties/76890349-523d-4f04-9d57-8f42311be4bc/
https://huntr.dev/bounties/21d958d9-d428-4952-bea6-68bfb4476897/
https://huntr.dev/bounties/42d91ab8-865d-41ee-9614-926409cefe1c/

They are only visible to maintainers with repository write access 🤝

**Comment by JamieSlome** [comment]
Hi @olivermrbl - did you get a chance to take a look at the reports?
