### ISSUE TITLE
`createOrdersWorkflow` only works with one item

### ISSUE THREAD

**Issue by Alexnortung** [medusajs/medusa#9733]
### Describe the bug

It doesn't really make sense that this workflow's name is create order**s**, when it only works with a single item.

### Steps to reproduce the behavior

1. run the workflow `createOrdersWorkflow` with an array of items
2. I get an erro that the region was not found.

### Expected behavior

I expected the function to work with multiple items and not just one.

**Comment by sradevski** [comment]
This was renamed to be singular, closing now: https://github.com/medusajs/medusa/pull/10134
