### ISSUE TITLE
Http Cart type payment_collection field is not a list

### ISSUE THREAD

**Issue by vethan** [medusajs/medusa#9738]
### Describe the bug

Line 76 medusa/packages/core/types/src/http/cart/common.ts reads:
 `payment_collection?: BasePaymentCollection`

However a list of payment collections is passed when requests are made from the backend.  Should either the medusa backend should send single objects, or this type should be `BasePaymentCollection[]`

### System information

Medusa version (including plugins): 2.0.0
Node.js version: N/A
Database:N/A
Operating system:N/A
Browser (if relevant):

### Steps to reproduce the behavior

1. Create a cart with a payment collection with medusa SDK
2. Try to access cart.payment_collection.payment_sessions
3. It will be undefined
4. Access cart.payment_collection[0].payment_sessions
5. It will be defined but type checking will report an error

### Expected behavior

Either cart.payment_collection.payment_sessions should contain payment sessions, or the type should be a list

### Screenshots

If applicable, add screenshots to help explain your problem
N/A
### Code snippets

If applicable, add code samples to help explain your problem
N/A
### Additional context

Add any other context about the problem here
N/A

**Comment by vethan** [comment]
I'm just dumb and wrote bad code

**Comment by vethan** [comment]
Turns out not entirely my fault.  Seems that sometimes cart.payment_collection is an object, and other times it is an array.  It has seems to become an array if you hit a "Could not delete all payment sessions" error, at which point it will stay an array.  Not sure how to reproduce as yet, but will keep trying to investigate

**Comment by vethan** [comment]
Seems to be the case if you create two payment collections in quick succession (So still bad code that you shouldn't write)

**Comment by olivermrbl** [comment]
>  if you create two payment collections in quick succession

@vethan, do you mean you send two requests using the JS-SDK method `store.cart.initiatePaymentSessions`?

**Comment by vethan** [comment]
I was calling ` medusaSdk.store.payment.initiatePaymentSession` in two consecutive re-renders, which caused a 'Could not delete all payment sessions' error.

**Comment by Hurrell** [comment]
I've also experienced frustration hunting down a bug caused by this. Don't have any opinion as to whether the return or the type should be updated, just that they match :)
