### ISSUE TITLE
isValidHandle should be case insenstive

### ISSUE THREAD

**Issue by lopper** [medusajs/medusa#9740]
### Describe the bug

 isValidHandle should support both upper and lower case letters. Both upper and lower case values are valid url handles.

### System information

Medusa version (including plugins):
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by SalahAdDin** [comment]
@lopper  was it fixed?

**Comment by lopper** [comment]
No it was not fixed

**Comment by SalahAdDin** [comment]
@lopper  I guess this issue lacks of the proper information, please fill it in properly.
