### ISSUE TITLE
Bug report: Discrepancy between Toast implementation and documentation example

### ISSUE THREAD

**Issue by VrajPatelK** [medusajs/medusa#9741]
### Describe the bug

1. **Discrepancy in Toast appearance:** When I implemented the provided `Toast` component, the appearance differed from what was shown in the [documentation](https://docs.medusajs.com/ui/components/toast#examples). The actual `Toast` (<a href="#image-1"> shown in image-1</a>) does not match the design of the one in the [documentation](https://docs.medusajs.com/ui/components/toast#examples) (<a href="#image-2"> shown in image-2</a>).
2. **Close button not working as expected:** In the [documentation](https://docs.medusajs.com/ui/components/toast#examples) example (<a href="#image-2"> shown in image-2</a>), when clicking the **"Close"** button, the toast does not close even though `dismissable` is set to `true`.

### System information
- **Medusa version (including plugins):** `v2`
    - `"@medusajs/ui-preset": "preview"`
    - `"@medusajs/ui": "preview"` 
- **Node.js version:** `v20.13.1`
- **Database:** `postgresql^15.1`
- **Operating system:** `macOS`
- **Browser (if relevant):** `chrome`

### Steps to reproduce the behavior

1. Go to the `Toast` component in the [documentation](https://docs.medusajs.com/ui/components/toast#examples).
2. Implement the `Toast` component using the provided code.
3. Compare the appearance of the `Toast` with what is shown in the [documentation](https://docs.medusajs.com/ui/components/toast#examples).
4. Click the "Close" button and observe that the toast does not dismiss.
5. Notice both the appearance discrepancy and the non-functional **"Close"** button.

### Expected behavior

1. The implemented `Toast` component should match the design and behavior shown in the [documentation](https://docs.medusajs.com/ui/components/toast#examples) (<a href="#image-2"> shown in image-2</a>).
2. The **"Close"** button should function as expected, dismissing the toast when `dismissable` is set to `true`(<a href="#image-2"> shown in image-2</a>).

### Screenshots

<a name="image-1"/>

#### Image1 (While Implementation)

![actual-image](https://github.com/user-attachments/assets/5e974bd8-2a63-4f96-bd18-879b938595d7)

<a name="image-2"/>

#### Image:2 ([Inside Docs](https://docs.medusajs.com/ui/components/toast#examples))

![expected-image](https://github.com/user-attachments/assets/ada9a676-cb36-49ef-b2ce-9a4fb2c55c7e)

### Code snippets

```bash
import { Button, Toaster, toast } from "@medusajs/ui"

export function DismissableToaster() {
  return (
    <>
      <Toaster />
      <Button
        onClick={() =>
          toast.info("Info", {
            description: "The quick brown fox jumps over the lazy dog.",
            dismissable: true,
          })
        }
      >
        Show
      </Button>
    </>
  )
}

```

**Comment by kasperkristensen** [comment]
Hi @VrajPatelK, I think that either you were viewing the V1 docs or seeing a cached version of the page as we were updating the UI docs to reflect the release of V2 yesterday. At least on my end https://docs.medusajs.com/ui/components/toast is showing the correct component.

Hitting the "x" button on a Toaster in V2 also works as expected, so closing this issue. If you are facing any issues with the V2 version of the toaster then feel free to re-open the issue.
