### ISSUE TITLE
Docs(Code Issue): Update Alert Documentation

### ISSUE THREAD

**Issue by VrajPatelK** [medusajs/medusa#9742]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In the Medusa UI [documentation](https://docs.medusajs.com/ui/components/alert#examples), the `AlertDemo` component does not display variants such as `warning` or `success` in the current code snippet. This should be enhanced to demonstrate the usage of different alert variants.

For, [warning](https://docs.medusajs.com/ui/components/alert#warning-alert) & [success](https://docs.medusajs.com/ui/components/alert#success-alert)

### Current Code Example (Actual):

```bash
import { Alert } from "@medusajs/ui"

export function AlertDemo() {
  return <Alert>You are viewing Medusa docs.</Alert>
}
```

### Expected Code Example:
- For a `warning`
```bash
import { Alert } from "@medusajs/ui"

export function AlertDemo() {
  return <Alert variant="warning">You are viewing Medusa docs.</Alert>
}
```

- For a `success`
```bash
import { Alert } from "@medusajs/ui"

export function AlertDemo() {
  return <Alert variant="success">You are viewing Medusa docs.</Alert>
}
```

### How can this issue be resolved?

1. Update the `AlertDemo` component in the [documentation](https://docs.medusajs.com/ui/components/alert#examples) to include variant examples for `warning` and `success`.
2. Ensure that the new examples show the flexibility of the `Alert` component, enhancing the demonstration of its variants.

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for opening this issue! Will look into it
