### ISSUE TITLE
Bug in invites

### ISSUE THREAD

**Issue by Tech-dev-coder** [medusajs/medusa#9743]
### What Medusa version and documentation are you using?

None

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

![Screenshot from 2024-10-24 12-47-32](https://github.com/user-attachments/assets/8f1550d7-18bc-494c-bee9-bb1c7901ad6b)
![Screenshot from 2024-10-24 12-47-43](https://github.com/user-attachments/assets/2273dc60-41d7-4cb8-a746-6562bf9bfea2)
![Screenshot from 2024-10-24 12-48-15](https://github.com/user-attachments/assets/82438bc7-5472-4575-b33b-7c4061a7dd06)
![Screenshot from 2024-10-24 12-53-32](https://github.com/user-attachments/assets/74e49297-f1f8-409b-a518-993f4c9845c2)

If i try again it showing server error 

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by thetutlage** [comment]
@Tech-dev-coder Did you try the invite link in the same browser session as the one you are logged-in? 

Because, I just gave the invite link a try in a different browser and that works fine

**Comment by olivermrbl** [comment]
@Tech-dev-coder, based on your reaction, I assume the suggested fix worked, so closing this for now.
