### ISSUE TITLE
Customer Section Links (Shipping Address, Billing Address, Transfer Ownership, Email) Redirect to 404 Page

### ISSUE THREAD

**Issue by mustafaugurlu973** [medusajs/medusa#9751]
### Describe the bug
When clicking on the "Shipping Address," "Billing Address," "Transfer Ownership," or "Email" links in the Customer section on the order details page, I am being redirected to a 404 error page. These links should navigate to the corresponding pages for editing or viewing customer details but are currently leading to a non-existent page.

### System information
- **Medusa version (including plugins)** Medusa V2 
- **Project started with:** `npx create-medusa-app@latest`

### Steps to reproduce the behavior
1. Go to the order details page.
2. In the "Customer" section, click on the three-dot menu.
3. Select either "Shipping Address," "Billing Address," "Transfer Ownership," or "Email."
4. You will be redirected to a 404 error page.

### Expected behavior
Clicking on the "Shipping Address," "Billing Address," "Transfer Ownership," or "Email" links should take the user to the relevant customer information page for editing or viewing the details.

### Screenshots
<img width="1389" alt="Ekran Resmi 2024-10-24 11 45 28" src="https://github.com/user-attachments/assets/beb0a8f5-1d50-4dc3-b96e-d54e053e7c7f">

**Comment by olivermrbl** [comment]
@mustafaugurlu973, thanks for the report. You are right, we are missing something here. We'll attend to it asap!

**Comment by rudik99** [comment]
Also happens on the other functions on the order page  - @olivermrbl do you want me to raise a seperate issue for them or you happy to consolidate on the 1?

<img width="996" alt="Screenshot 2024-10-31 at 09 13 13" src="https://github.com/user-attachments/assets/e07ad9ff-2911-449f-8259-a508c0acd183">
<img width="964" alt="Screenshot 2024-10-31 at 09 13 31" src="https://github.com/user-attachments/assets/fdc9f692-fdfb-425a-9345-4b3fb4eaf236">
<img width="981" alt="Screenshot 2024-10-31 at 09 13 38" src="https://github.com/user-attachments/assets/e6e59875-ad03-4adf-89a6-1074ce9b5444">
<img width="1408" alt="Screenshot 2024-10-31 at 09 13 16" src="https://github.com/user-attachments/assets/b0489461-d8f7-4634-94d6-41759a1e020f">

**Comment by SalahAdDin** [comment]
@olivermrbl  is there any news on this?

**Comment by olivermrbl** [comment]
These features were added in a recent release. Please update to the latest version of Medusa and try again.
