### ISSUE TITLE
Workflow Transaction ID Not Displayed, Clicking the Link Throws an Error

### ISSUE THREAD

**Issue by mustafaugurlu973** [medusajs/medusa#9754]
### Title
Workflow Transaction ID Not Displayed, Clicking the Link Throws an Error

### Describe the bug
On the **Workflows** page, the **Transaction ID** is not displayed. Additionally, when clicking on any of the workflow entries, an error occurs, and the page fails to load with an "An unexpected error occurred" message. 

The browser console shows the following error:
`TypeError: Cannot read properties of undefined (reading 'compensateInput')`

### System information
- **Medusa version:** Medusa V2
- **Project started with:** `npx create-medusa-app@latest`
- **Browser:** Chrome v130.0.6723.70

### Steps to reproduce the behavior
1. Go to the **Workflows** page in the settings.
2. Observe that the **Transaction ID** is missing for all entries.
3. Click on any of the workflow entries.
4. You will see an error page with the message "An unexpected error occurred."

### Expected behavior
- The **Transaction ID** should be displayed for each workflow entry.
- Clicking on any workflow entry should lead to a detailed view of that specific workflow without throwing an error.

### Screenshots

1. **Workflows page without Transaction ID displayed:**
<img width="1369" alt="Ekran Resmi 2024-10-24 11 57 55" src="https://github.com/user-attachments/assets/0d8a3589-2c5c-4585-af02-251d5632d31d">

2. **Error page after clicking a workflow entry:**
<img width="1282" alt="Ekran Resmi 2024-10-24 12 13 55" src="https://github.com/user-attachments/assets/21cefab5-23c6-43c0-a3a7-8c6c07ee9dd7">

**Comment by olivermrbl** [comment]
@adrien2p, is this something you could look into?

**Comment by adrien2p** [comment]
Hi @mustafaugurlu973 thank you very much for reporting this issue. This [PR](https://github.com/medusajs/medusa/pull/9757) should fix it 💪

**Comment by olivermrbl** [comment]
Issue solved in #9757 and part of next release.
