### ISSUE TITLE
Custom Date Picker Not Working in Filter Section Across All Pages

### ISSUE THREAD

**Issue by mustafaugurlu973** [medusajs/medusa#9758]
### Describe the bug
When selecting "Custom" in the date picker within the **Filter** section, the date picker does not open. This issue persists for all date fields across all pages where the Filter section is present, preventing custom date selection.

### System information
- **Medusa version:** Medusa V2
- **Project started with:** `npx create-medusa-app@latest`
- **Browser:** Chrome v130.0.6723.70

### Steps to reproduce the behavior
1. Navigate to any page with the **Filter** section.
2. Click on any date filter option.
3. Select "Custom" as the date range.
4. The date picker does not appear, and custom dates cannot be selected.

### Expected behavior
The date picker should open when "Custom" is selected, allowing the user to choose specific dates.

### Screenshots / Video
I have attached a screen recording showing the issue in action:

https://github.com/user-attachments/assets/27ef6d7c-97e4-49d6-a3ad-42665b59238a

### Additional context
This issue affects all pages where the Filter section is present and applies to all date fields.

**Comment by olivermrbl** [comment]
@mustafaugurlu973, thanks will be fixed today and part of the next release!

**Comment by JasonEastar** [comment]
> [@mustafaugurlu973](https://github.com/mustafaugurlu973), thanks will be fixed today and part of the next release!

**I see this issue is still not resolved in version: 2.8.6**

**Comment by jayuparmar** [comment]
Hi! 👋
I'm trying to build a custom date filter in my React project using Medusa UI, and I want the input/output to use the mm/dd/yyyy format.

Is there an example or recommended approach for customizing the date picker / filter format in Medusa UI?
Specifically, I’d like to:

Display dates as mm/dd/yyyy

Parse user input in this format

Integrate it into a Medusa UI filter component (e.g., for orders or custom list filters)

If anyone has guidance or sample code for customizing date formats in Medusa UI, I’d really appreciate it. Thanks!****

**Comment by jayseepossible** [comment]
Hi! 👋
Issue: Date range filter excludes start and end dates

When I select a date range in the date picker (for example, 01-12-25 to 09-12-25), the filter only returns records that fall strictly between these dates.

Records that occur on the start date or end date (for example, 01-12-25 or 09-12-25) are not included in the results.

Expected behavior:
The filter should include data from both the first and last selected dates.
