### ISSUE TITLE
Console Errors When Adding a Customer to a Customer Group 

### ISSUE THREAD

**Issue by mustafaugurlu973** [medusajs/medusa#9760]
### Describe the bug
When attempting to add a customer to a customer group, the "Add" button opens the modal, but errors appear in the browser console regardless of whether customer groups exist or not. The groups may or may not be listed, but the following warnings and errors are shown in the console when the modal opens.

### System information
- **Medusa version:** Medusa V2
- **Project started with:** `npx create-medusa-app@latest`
- **Browser:** Chrome v130.0.6723.70

### Steps to reproduce the behavior
1. Navigate to the **Customers** page.
2. Select a customer and click the **Add** button under the **Customer Groups** section.
3. The modal opens, and regardless of whether customer groups exist or not, errors are shown in the console.

### Screenshots

1. **Before opening the modal:**
<img width="2058" alt="Ekran Resmi 2024-10-24 13 54 23" src="https://github.com/user-attachments/assets/087c1d70-8b60-477c-ac8f-8df463f3dc3b">
   
2. **Errors displayed after opening the modal:**
<img width="2056" alt="Ekran Resmi 2024-10-24 13 54 41" src="https://github.com/user-attachments/assets/db9f7af3-23f6-4c10-85df-69765f90a57c">

**Comment by olivermrbl** [comment]
@mustafaugurlu973, thanks for highlighting. 

This is not a breaking issue, so we will treat this with low priority. Feel free to send a PR, if you are up for fixing it :)
