### ISSUE TITLE
Create Auth Provider Module - Location redirect url not working after successful validateCallback response.

### ISSUE THREAD

**Issue by jgatto1** [medusajs/medusa#9774]
### Describe the bug

I'm creating a custom auth module following [this](https://docs.medusajs.com/resources/references/auth/provider) docs. I'm able to get the authentication token, but for some reason I'm not redirected to the `location` url I provided in the `validateCallback` method:

```
async validateCallback(
    req: AuthenticationInput,
    authIdentityService: AuthIdentityProviderService
  ): Promise<AuthenticationResponse> {
    if (req.query && req.query.error) {
      return {
        success: false,
        error: `${req.query.error_description}, read more at: ${req.query.error_uri}`,
      }
    }

    const code = req.query?.code ?? req.body?.code
    if (!code) {
      return { success: false, error: "No code provided" }
    }

    const tokenUrl = `${this.config_.endpoint}/oidc/token`

    try {

      const apiResponse = await fetch(tokenUrl, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: `code=${code}&redirect_uri=${encodeURIComponent(this.config_.callbackUrl)}&client_id=${this.config_.clientId}&client_secret=${this.config_.clientSecret}&grant_type=authorization_code`,
      });

      var response = await apiResponse.json();

      const { authIdentity, success } = await this.verify_(
        response.id_token as string,
        authIdentityService
      )

      // TODO:  This is not working, not redirecting 
      const returnBody: AuthenticationResponse = {
        success,
        authIdentity,
        location: this.config_.successRedirectUrl,
        // successRedirectUrl: this.config_.successRedirectUrl,
      }
      return returnBody;
    } catch (error) {
      return { success: false, error: error.message }
    }
  }
```
The `AuthenticationResponse` says for location:
```
    /**
     * The URL to redirect to for further authentication action
     * with a third-party provider. This takes precedence before
     * the `success` field.
     *
     * So, after checking that authentication is successful,
     * you should check whether this field is defined and, if so, redirect to the
     * specified location.
     */
    location?: string;
```
But then I go to `medusa/packages/medusa/src/api/auth/[actor_type]/[auth_provider]/callback/route.ts` and there is no usage of the `location` value. In a `preview` release of Medusa v2 there was an if condition that redirected to that url if exists. So I'm not sure how to proceed, if you removed the redirection and the `location` of `AuthenticationResponse` is outdated and you need to remove it.

### System information

Medusa version (including plugins): 2.0.0
Node.js version: v20.17.0
Database: 13.16-1.pgdg120+1
Operating system: MacOS 14.0 (23A344)
Browser (if relevant):

### Expected behavior

It should redirect to the specified `location` value, or it should not support `location`.

### Related

I've also found same behavior for the `authenticate` method. In `develop` it doesn't redirect to the `location` returned value from the auth module class. Maybe is not a bug, just the new flow, if so the `location` description is confusing.

**Comment by olivermrbl** [comment]
Hey @jgatto1, we updated our authentication flow to rely on a client-side redirect rather than a server-side one. 

You can read more about it [here](https://docs.medusajs.com/resources/commerce-modules/auth/authentication-route).

**Comment by sradevski** [comment]
Closing this issue since the auth flows and approaches are already documented
