### ISSUE TITLE
Add Turkish Language Support for MedusaJS

### ISSUE THREAD

**Issue by bekiryazgann** [medusajs/medusa#9776]
Hi MedusaJS Team,

I hope you're doing well. I have created a Turkish language support file for MedusaJS, and I would love to contribute it to the project. The file includes translations for various user-facing texts and system messages, ensuring a better experience for Turkish-speaking users.

Please let me know the best way to submit this contribution or if any adjustments are needed before integrating it.

Thank you for your hard work on MedusaJS, and I look forward to contributing!

**Comment by sradevski** [comment]
There has been a community contribution to add Turkish already, so I'll close this ticket. Feel free to review the translations and modify as necessary: https://github.com/medusajs/medusa/pull/10109
