### ISSUE TITLE
Edit Customer metadata via Store API - zodValidator error

### ISSUE THREAD

**Issue by docloulou** [medusajs/medusa#9779]
### Describe the bug

I'm trying to store some additional data (age, company informations, etc.) in the metadata via an API call, but it doesn't seem to be working because of Zod validation. It's not working for registering or updating a customer.

### System information

Medusa version (including plugins): 2.0.0 

### Expected behavior

be able to edit customer metadata via Store API

### Screenshots

![image](https://github.com/user-attachments/assets/c4bd2789-f035-4e13-ad94-eb08533997b5)
![image](https://github.com/user-attachments/assets/4da7110b-0c0d-4e31-b6bf-4dcc7c8d0b2c)

**Comment by kasperkristensen** [comment]
Fixed in #9780
