### ISSUE TITLE
Product updated doesn't fire the event product.updated

### ISSUE THREAD

**Issue by juansoler** [medusajs/medusa#9783]
### Describe the bug

I'm creating subscriber using the events product-variant.created, product.deleted and so on. 

But, if I try to update the product (just name or description) it doesn't fire the event 'product.updated'.  

If you edit the variant or the option their own events are fired properly. 

### System information

Medusa version (including plugins): 2.0
Node.js version: 20
Database: postgres
Operating system: ubuntu server 22.04
Browser (if relevant): chrome

### Steps to reproduce the behavior

1. Go to 'Products'
2. Click on 'edit'
3. Change name or description, etc. (not option or variant values).
4. The product is updated correctly but it doesn't fire the event 'product.update'.

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

```

import { SubscriberArgs, type SubscriberConfig } from "@medusajs/framework"
import { IProductModuleService } from "@medusajs/framework/types"
import { Modules } from "@medusajs/framework/utils"
import { MeiliSearch, Settings } from "meilisearch"
import {
    ContainerRegistrationKeys,
  } from "@medusajs/framework/utils"

export default async function productUpdateHandler({
  event: { data },
  container,
}: SubscriberArgs<{ id: string }>) {


      // const client: MeiliSearch = new MeiliSearch()

  const client = new MeiliSearch({
   ********
  })

//   client.createIndex('medicamentos', { primaryKey: 'id' })


try {
    console.log(data);


    
    // const query = container.resolve(ContainerRegistrationKeys.QUERY)
    
    const productModuleService: IProductModuleService =
    container.resolve(Modules.PRODUCT)

  const productId = data.id

  const productVariant = await productModuleService.retrieveProductVariant(
    productId
  )

  const product = await productModuleService.retrieveProduct(
    productVariant.product_id,
    {
        relations: ["options", "categories", "tags"],
      }
    
  )

  

  client.index('medicamentos').addDocuments([{
    id: product.id,
    title: product.title,
    thumbnail: product.thumbnail ||  "",
    description: product.description || "",
    creado: product.createdAt,
    handle: product.handle
}])

  console.log(product);
  

  console.log(`The product ${product.title} was updated`)

} catch (error) {
    console.log(error);
    
}

  
}

export const config: SubscriberConfig = {
  event: `product.updated`,

}
```

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by Attachai77** [comment]
try using this
```
import { ProductEvents } from '@medusajs/framework/utils';

export const config: SubscriberConfig = {
	event: ProductEvents.PRODUCT_UPDATED,
};
```

**Comment by juansoler** [comment]
Yes, it works. Thank you.

**Comment by sradevski** [comment]
Closing as it seems the original issue is resolved.

However, I would urge everyone to prefer using the `*WorkflowEvents` instead as those are more reliable (since creating a product involved multiple steps, it's not just creating the product itself in the DB).

**Comment by Attachai77** [comment]
> WorkflowEvents

Hi @sradevski  I tried using this, bus not work , can you please tell me my wrong?
```
import { ProductWorkflowEvents } from '@medusajs/framework/utils';

export const config: SubscriberConfig = {
	event: ProductWorkflowEvents.UPDATED,
};
```

**Comment by SalahAdDin** [comment]
> > WorkflowEvents
> 
> Hi @sradevski I tried using this, bus not work , can you please tell me my wrong?
> 
> ```
> import { ProductWorkflowEvents } from '@medusajs/framework/utils';
> 
> export const config: SubscriberConfig = {
> 	event: ProductWorkflowEvents.UPDATED,
> };
> ```

I helped to @juansoler
