### ISSUE TITLE
API Ref(admin): Issue in Create Fulfillment

### ISSUE THREAD

**Issue by Chhidori** [medusajs/medusa#9786]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

the API reference doesn't include details about path parameter or required fields for the request body

### How can this issue be resolved?

by adding the relevant details

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Hi @Chhidori can you share the link you're viewing? Because [this one](https://docs.medusajs.com/api/admin#fulfillments_postfulfillments) has all the details.

**Comment by Chhidori** [comment]
Hi @shahednasser,

Thanks for the reply! I was actually looking at the same documentation you mentioned. In version 1, the path parameter is there, but I couldn’t find it in version 2.

Is there no path parameter in this version, or am I missing something? Just want to make sure I’m asking the right question here.

Thanks for the help!

**Comment by shahednasser** [comment]
This API route is for creating a fulfillment in general, but i'm guessing you're looking for the one to create a fulfillment for an order, which is here: https://docs.medusajs.com/api/admin#orders_postordersidfulfillments

This one accepts the order ID as a path parameter.

If this is what you're looking for please feel free to close the issue.

**Comment by Chhidori** [comment]
Thank you for pointing me to the correct route!
