### ISSUE TITLE
v1 documentaton links are invalid

### ISSUE THREAD

**Issue by han0417** [medusajs/medusa#9787]
### What Medusa version and documentation are you using?

None

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I just want to check about Discount feature in medusa v1 doc

but links are invalid

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Hello, can you please explain your issue more? What link are you trying to access?

**Comment by pshemek** [comment]
Hello, I found this issue as well, mostly when searching solutions in Google. Multiple indexed pages are not found, i.e. https://docs.medusajs.com/development/modules/overview
I am aware it's due to v2 migration but it's not a good experience and impression.

**Comment by han0417** [comment]
> Hello, can you please explain your issue more? What link are you trying to access?

https://docs.medusajs.com/user-guide/discounts

I trying to access this link, but shows page not found

![截圖 2024-10-25 下午5 02 10](https://github.com/user-attachments/assets/c5e0f797-0d80-45ce-ab60-a5cac813875d)

I use medusajs v1 for development, but now can't view v1 docs 🥲

**Comment by oreldx** [comment]
For those looking for the v1 documentation, you can still access it by adding `/v1` to the main documentation URL. Simply visit [https://docs.medusajs.com/v1](https://docs.medusajs.com/v1).

Personally, I find it surprising that the toggle between v1 and v2 wasn’t retained in the new v2 documentation. Even though the v2 placeholder is still present, a toggle switch—defaulted to v2—could offer a more user-friendly experience for those needing to reference both versions.

**Comment by shahednasser** [comment]
Hey everyone, thank you for all the reports! As @oreldx mentioned, the v1 docs are not at https://docs.medusajs.com/v1 . Will look into Google's search index to avoid this problem occurring in the future. Sorry for the inconvenience!

Will close this issue as it's resolved separately from this repo. If you have any other remarks though please feel free to comment / re-open the issue.
