### ISSUE TITLE
Reservation order number not showing in the inventory page

### ISSUE THREAD

**Issue by erickirt** [medusajs/medusa#9797]
In the medusajs admin dashboard the inventory page has a section called reservations which lists reservations, the order number of a reservation isn't showing. 

Pictures:
reservation on the Inventory page:
<img width="823" alt="Screenshot 2024-10-25 at 10 44 57 AM" src="https://github.com/user-attachments/assets/9b20e26d-6833-4d21-859b-239a724a5f29">

Reservation on the reservation page:
<img width="1518" alt="Screenshot 2024-10-25 at 10 54 00 AM" src="https://github.com/user-attachments/assets/1d2f5e8c-a9c1-48a0-b4a6-456dd3b197da">

**Comment by SalahAdDin** [comment]
@erickirt  was it fixed?

**Comment by erickirt** [comment]
They changed the table to not show the order line item id at all now.

**Comment by SalahAdDin** [comment]
> They changed the table to not show the order line item id at all now.

Is it that bad?

**Comment by erickirt** [comment]
Doesn't matter, medusa is a technical product for technical people and you can still get a reservation by a order line item, i guess they really want it decoupled as opposed to feature based, but I am a fan of the new architecture
