### ISSUE TITLE
The link to upgrade guide is broken

### ISSUE THREAD

**Issue by sgazzola80** [medusajs/medusa#9802]
### What Medusa version and documentation are you using?

None

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I was looking at the guide to upgrade medusa 2.0.0 to 2.0.1 using the link

https://docs.medusajs.com/upgrade-guides

but it's broken

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Hello, thank you for opening this issue! With 2.0 we're posting all version updates in our [release notes](https://github.com/medusajs/medusa/releases). Please feel free to refer to it for upgrade guides.
