### ISSUE TITLE
Docs(Code Issue): "validateAndTransformBody" has wrong import

### ISSUE THREAD

**Issue by millansingh** [medusajs/medusa#9810]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The docs are showing importing `validateAndTransformBody` from `"@medusajs/framework/utils"`. This is incorrect. The correct import is from `"@medusajs/framework"`.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch! PR #9820 should resolve this.
