### ISSUE TITLE
StockLocationModule has no linkable property.

### ISSUE THREAD

**Issue by nykkos144** [medusajs/medusa#9812]
### Describe the bug

`import StockLocationModule from '@medusajs/medusa/stock-location';`

`StockLocationModule.linkable` is missing. Thus making linking impossible.

### System information

Medusa version (including plugins): v2
Node.js version: v20.14.0
Database: postgres - local
Operating system: macOS
Browser (if relevant): 

### Steps to reproduce the behavior

1. Import StockLocationModule
2. Try to link to another module

### Expected behavior

For StockLocationModule to have linkable property

**Comment by itariv** [comment]
Hi @olivermrbl ! is it gonna be changed anytime soon?
