### ISSUE TITLE
No Local Development Documentation

### ISSUE THREAD

**Issue by Ratnadeep2k** [medusajs/medusa#9816]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

When I try to access the contribution guidelines and click on the local setup guide, an error message appears.

### How can this issue be resolved?

1. documentation needs to be updated or fixed.
### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
~Nice catch! Will open a PR to fix this.~ Sorry, I couldn't find the problematic guide, can you post a link of where you found the exact issue?

**Comment by Ratnadeep2k** [comment]
> ~Nice catch! Will open a PR to fix this.~ Sorry, I couldn't find the problematic guide, can you post a link of where you found the exact issue?

do you find any local setup guide there ?

**Comment by Ratnadeep2k** [comment]
> ~Nice catch! Will open a PR to fix this.~ Sorry, I couldn't find the problematic guide, can you post a link of where you found the exact issue?
https://docs.medusajs.com/usage/local-development 

README -> contribution guide -> local development documentation

**Comment by shahednasser** [comment]
Oh ok so it's in this repo not in the docs, will look into fixing it

**Comment by Ratnadeep2k** [comment]
> Oh ok so it's in this repo not in the docs, will look into fixing it

Can you send me the link I will try to fix this issue ! or step to fix this !

**Comment by shahednasser** [comment]
Actually we need to look further into this as the process for contributing may have changed. Will check internally and see how we can resolve it.

**Comment by Ratnadeep2k** [comment]
> Actually we need to look further into this as the process for contributing may have changed. Will check internally and see how we can resolve it.

Ok sure , Thank you
