### ISSUE TITLE
Price list not applied to customer group

### ISSUE THREAD

**Issue by docloulou** [medusajs/medusa#9819]
### Describe the bug

The price list works if no customer group is specified, but when it is attached to a specific group, the users in that group are not affected by the price list. (with Bearer token sent with /store/products)

### System information

Medusa version (including plugins) : 2.0.1

### Expected behavior

I expected that attaching a price list to a specific customer group would apply the price list automatically to all users within that group, adjusting prices accordingly.

**Comment by docloulou** [comment]
maybe found the issue : 

in [/store/carts API](https://github.com/medusajs/medusa/blob/7c629f494f7d733d893c78f25a1493f41c8e4e98/packages/medusa/src/api/store/carts/route.ts)
how customer_id is retrieved :
```
   const workflowInput = {
    ...req.validatedBody,
    customer_id: req.auth_context?.actor_id,
  }
```

in [/store/products API pricecontext middleware ](https://github.com/medusajs/medusa/blob/7c629f494f7d733d893c78f25a1493f41c8e4e98/packages/medusa/src/api/utils/middlewares/products/set-pricing-context.ts)
how customer_id is retrieved :

```
     const customerGroups = await refetchEntities(
        "customer_group",
        { customer_id: req.user?.customer_id },
        req.scope,
        ["id"]
      )
```
  
the two ways :

1. customer_id: req.**auth_context**?.actor_id
2.  customer_id: req.**user**?.customer_id


both refers to
```
 import {
  AuthenticatedMedusaRequest,
  refetchEntities,
  refetchEntity,
} from "@medusajs/framework/http"
```


==> [AuthenticatedMedusaRequest Type](https://github.com/medusajs/medusa/blob/7c629f494f7d733d893c78f25a1493f41c8e4e98/packages/core/framework/src/http/types.ts)
```

export interface AuthContext {
  actor_id: string
  actor_type: string
  auth_identity_id: string
  app_metadata: Record<string, unknown>
}

export interface AuthenticatedMedusaRequest<Body = never>
  extends MedusaRequest<Body> {
  auth_context: AuthContext
  publishable_key_context?: PublishableKeyContext
}
```

So, `req.user` do not exist ?

**Comment by sradevski** [comment]
This should have been fixed by https://github.com/medusajs/medusa/pull/10197
