### ISSUE TITLE
Page not found after clicking a link at https://medusajs.com/blog/foraged/

### ISSUE THREAD

**Issue by sinewavess** [medusajs/medusa#9823]
### What Medusa version and documentation are you using?

None

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

i opened https://medusajs.com/blog/foraged/, and i clicked on this: 
![image](https://github.com/user-attachments/assets/09c23d53-4ec3-4449-8fad-9dd0dc56f8dd)
it brought me to a 404 page tho
https://docs.medusajs.com/recipes/marketplace

### How can this issue be resolved?

1. Remove the link from the blog post

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch! Will relay this to the associated team. As this is not resolved in this repo, will close this issue.
