### ISSUE TITLE
Promotion module mismatching types

### ISSUE THREAD

**Issue by renanboni** [medusajs/medusa#9824]
The _createPromotions_ from **IPromotionModuleService** module takes in a **CreatePromotionDTO** while the _retrievePromotion_ function returns a **PromotionDTO**.

So, if I have something like this Typescript will complain:

```
export type DeletePromotionWorkflowInput = {
    promotionId: string
}

const deletePromotionStep = createStep(
    "delete-promotion-step",
    async (input: Readonly<DeletePromotionWorkflowInput>, {container}) => {
        const promotionService: IPromotionModuleService = container
            .resolve(ModuleRegistrationName.PROMOTION)

        const promotion = await promotionService.retrievePromotion(input.promotionId)

        await promotionService.deletePromotions([promotion.id])

        return new StepResponse(
            undefined,
            promotion
        )
    },
    async (promotion, {container}) => {
        const promotionService: IPromotionModuleService = container
            .resolve(ModuleRegistrationName.PROMOTION)

        // TODO: createPromotions should accept PromotionDTO?
        // @ts-ignore
        await promotionService.createPromotions(promotion)
    }
)

export default deletePromotionStep
```

**Comment by renanboni** [comment]
ok, should I use the respective workflows instead? They seem to return the expected object

**Comment by olivermrbl** [comment]
@renanboni, I recommend you use the pre-built [step](https://github.com/medusajs/medusa/blob/develop/packages/core/core-flows/src/promotion/steps/delete-promotions.ts) or [workflow](https://github.com/medusajs/medusa/blob/develop/packages/core/core-flows/src/promotion/workflows/delete-promotions.ts).

In the meantime, we'll fix the type issue!
