### ISSUE TITLE
Draft orders still not available in admin dashboard in 2.0.1

### ISSUE THREAD

**Issue by andrewshadura** [medusajs/medusa#9826]
The issue #8028 already reported that draft orders were missing from the development version in July. That issue was closed but the draft orders still don’t show up in the admin dashboard as of the recent release, and there is still no UI to create them.

This issue is to track the progress on the implementation of support for draft orders in the admin UI.

**Comment by olivermrbl** [comment]
@andrewshadura, appreciate the report, but our Issues board is only for bug reports. We will be tackling draft orders within the next three months. You can follow the progress in our GitHub Releases.

**Comment by andrewshadura** [comment]
Well, it is a bug, isn’t it? GitHub Releases do not allow tracking progress of issues, they are, well, for releases.
Closing a valid issue *twice* doesn’t seem like a good approach to me. Especially not as "completed".

**Comment by olivermrbl** [comment]
@andrewshadura, draft orders is an upcoming improvement, not a bug. We are well-aware of this shortcoming and it is on the roadmap. That said, the fact that we currently show draft orders in the orders overview could be deemed a bug, I'll forward this to the team, so we can make a decision on this.

I closed this issue because you wanted to use it for tracking progress on the implementation of draft orders, which our issues board is not intended for.

I hope you understand the rationale.

**Comment by andrewshadura** [comment]
They do *not* show in the orders overview, that was a typo.
Regarding the workflows, on the contrary, most projects I’ve seen or participated in use issues for work in progress or planned items. As in, when someone actually starts working on a feature, the issue gets assigned to that person, when it’s done, it gets closed. I can’t remember the last time I saw a project that didn’t do that, in fact, apart from this one. In other words, this approach is very unconventional.
And no, I don’t understand what the rationale is, to be honest. How am I supposed to learn this issue is or isn’t being worked on, if not by seeing the status of an issue change to *in progress* or it being mentioned in a pull request? Release notes have a lot of other things in them, so it’s easy to miss something, and also having a dedicated issue would allow me and others to be notified when something regarding this specific issue changes in the project, without requiring us to dig through lists of unrelated notes.
