### ISSUE TITLE
Medusa v2 Documentation: Issue in Medusa v2 Documentation

### ISSUE THREAD

**Issue by kooliahmd** [medusajs/medusa#9827]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Many links are pointing to 404 pages, ex: 
In https://medusajs.com/plugins/medusa-plugin-meilisearch/ there is a link [MeiliSearch Plugin Documentation](https://docs.medusajs.com/plugins/search/meilisearch) pointing nowhere. 

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for reporting this! This issue is mainly because we moved the v1 docs to `https://docs.medusajs.com/v1`. I've opened a PR to set up common redirects to the v1 docs, but will also contact the necessary team to update the plugins library.
