### ISSUE TITLE
Medusa Development Resources: Issue in File Module Providers - Medusa Development Resources

### ISSUE THREAD

**Issue by justinelut** [medusajs/medusa#9833]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

module.exports = defineConfig({
  // ...
  modules: [
    {
      resolve: "@medusajs/framework/file",
      options: {
        providers: [
          {
            resolve: "./src/modules/my-file",
            id: "my-file",
            options: {
              // provider options...
            },
          },
        ],
      },
    },
  ]
In teh docs, the resolve : "@medusajs/framework/file" is confusing to first timers developing file uploading modules.

### How can this issue be resolved?

1. Change the "@medusajs/framework/file" to "@medusajs/medusa/file"
2.
3.
...

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch! PR #9833 resolves the issue.
