### ISSUE TITLE
Mixed up MEDUSA_WORKER_MODE value in docs

### ISSUE THREAD

**Issue by yannickschuchmann** [medusajs/medusa#9835]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

[In this guide](https://github.com/medusajs/medusa/blob/c8d79c4ad4ae019b99c09fbff74120d130c1c1cb/www/apps/resources/app/deployment/medusa-application/railway/page.mdx?plain=1#L222) the value for `MEDUSA_WORKER_MODE` should be `server` instead of `worker` I guess.

### How can this issue be resolved?

Putting the correct value.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch! Will open a PR to fix it

**Comment by shaun-xenon** [comment]
Also, in Section 7 of the same doc,  `DISABLE_MEDUSA_ADMIN` should be true (in the terminal view)
