### ISSUE TITLE
Stripe Plugin Not Found

### ISSUE THREAD

**Issue by TGiacinto** [medusajs/medusa#9837]
Describe the bug
Error: Unable to find the plugin "medusa-payment-stripe".

Hello everyone, I’m having an issue with the medusa-payment-stripe plugin.

I followed the guide, installed the package, and added the following to medusa-config.ts:

```
module.exports = defineConfig({
    projectConfig: {
        databaseUrl: process.env.DATABASE_URL,
        http: {
            storeCors: process.env.STORE_CORS!,
            adminCors: process.env.ADMIN_CORS!,
            authCors: process.env.AUTH_CORS!,
            jwtSecret: process.env.JWT_SECRET || "supersecret",
            cookieSecret: process.env.COOKIE_SECRET || "supersecret",
        }
    },
    plugins: [
        {
            resolve: "medusa-payment-stripe",
            options: {
                api_key: process.env.STRIPE_API_KEY
            }
        }
    ]
});
```

However, when I try to start the server, I get the following error:

<img width="875" alt="image" src="https://github.com/user-attachments/assets/48c6886d-e4c3-464d-96ca-ae18e6a95093">

System information
**Medusa version (including plugins):**
- Medusa CLI version: 1.3.23
- Medusa version: 2.0.1

**Stripe Plugin:** 
"medusa-payment-stripe": "6.0.7",

**Node**
Node.js version: v20.18.0

Database: postgresSQL
Operating system: MacOs Sequoia 15.0.1

**Node Modules**

![image](https://github.com/user-attachments/assets/b9821f2f-5405-4c6f-b4d8-a74c8c6a444e)

I’ve also tried invalidating Yarn’s cache, but I’m still encountering the same problem.

**Comment by olivermrbl** [comment]
@TGiacinto, in Medusa v2.0, payment integrations are built as module providers and should be installed in the payment module configuration.

You can find the setup guide [here](https://docs.medusajs.com/resources/commerce-modules/payment/payment-provider/stripe).
