### ISSUE TITLE
Could not resolve module: Payment

### ISSUE THREAD

**Issue by olawale-o** [medusajs/medusa#9838]
### Describe the bug

Unable to get started with medusa

### System information

Medusa version (including plugins):
Node.js version: v20.17.0
Database: postgresSQL
Operating system: MacOS BigSur
Browser (if relevant):

### Steps to reproduce the behavior

1 sudo yarn dev

![Screen Shot 2024-10-28 at 13 04 56](https://github.com/user-attachments/assets/0bb09ddf-9ddc-403c-ba41-4b415154589d)
![Screen Shot 2024-10-28 at 13 05 05](https://github.com/user-attachments/assets/40e8ebfb-621a-4f30-9f0e-0d25bbf8a864)

**Comment by carlos-r-l-rodrigues** [comment]
If you check the messages, all your modules aren't able to connect to postgres. Check your connection string and postgres server.

I'm closing this as it doesn't seem to be a bug.
