### ISSUE TITLE
Can't inject ICustomerModuleService inside custom auth provider 

### ISSUE THREAD

**Issue by Shriz07** [medusajs/medusa#9853]
### Describe the bug

Following the guide about dependency injection via constructor https://docs.medusajs.com/learn/advanced-development/modules/container I can't inject ICustomerModuleService inside my auth service. I got error "Could not find a auth provider with id: keycloak" whenever I try to reach any endpoints releated to that auth provider. No errors in console while building app. Without service injection everything works fine.

### System information

Medusa version (including plugins): 2.0.0
Node.js version: 2.10.0
Database: Postgres 16.3
Operating system: Ubuntu 20.04
Browser (if relevant):

### Code snippets

```import { AbstractAuthModuleProvider } from "@medusajs/framework/utils"
import { Logger } from "@medusajs/framework/types"
import { ICustomerModuleService } from "@medusajs/types"
import { Modules } from "@medusajs/framework/utils"

type InjectedDependencies = {
  logger: Logger,
  customerModuleService: ICustomerModuleService
}

type Options = {
  apiKey: string
}

class KeycloakAuthProviderService extends AbstractAuthModuleProvider {
  static identifier = "keycloak"
  protected logger_: Logger
  protected options_: Options
  protected customerModuleService_: ICustomerModuleService

  constructor(
    { logger, customerModuleService }: InjectedDependencies,
    options: Options
  ) {
    super(...arguments)
    this.logger_ = logger
    this.options_ = options
    this.customerModuleService_ = customerModuleService
  }

  // Other methods...
}

export default KeycloakAuthProviderService```

**Comment by olivermrbl** [comment]
You cannot inject services from outside a module's domain. Modules are isolated from each other and cross-module operations should be performed in workflows.

You can read more about module isolation [here](https://docs.medusajs.com/learn/advanced-development/modules/isolation).
