### ISSUE TITLE
Add languages available in v2

### ISSUE THREAD

**Issue by claudiojin** [medusajs/medusa#9855]
Hello, for now there is only English for the admin panel, can i add the translation in Italian? If yes, how?

**Comment by giuda-ballerino** [comment]
I'd like to know this as well.

**Comment by shahednasser** [comment]
Hello, we now have a guide on how to translate the admin:

https://docs.medusajs.com/resources/contribution-guidelines/admin-translations

Closing this issue.

**Comment by maulobo** [comment]
I want to translate the admin panel to spanish. Is that possible? in V2

**Comment by shahednasser** [comment]
The Medusa Admin dashboard is already translated to spanish, learn how to change the language in this user guide: https://docs.medusajs.com/user-guide/settings/profile#edit-profile-details
