### ISSUE TITLE
Upgrade Link it's broken on README file

### ISSUE THREAD

**Issue by volpejoaquin** [medusajs/medusa#9858]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Hello team! I'm trying to access to `Follow the [Upgrade Guides](https://docs.medusajs.com/upgrade-guides/) to keep your Medusa project up-to-date.` on the README file but when I got redirected to https://docs.medusajs.com/upgrade-guides/ I'm seeing a `Page Not Found` message.

Can someone point to me the correct docs for upgrade the project please ? 🙏 

Thank you in advance

### Are you interested in working on this issue?

- [x] I would like to fix this issue

**Comment by shahednasser** [comment]
Thanks for pointing this out! I've opened a PR to fix this issue.
