### ISSUE TITLE
--host flag does not work

### ISSUE THREAD

**Issue by mofax** [medusajs/medusa#9865]
## Bug report

When running `medusa start --host 0.0.0.0` the server should run on `0.0.0.0` so that it can be accessed externally.

Instead "localhost" is still used.

### System information

Medusa version (including plugins): `2.0.1`
Node.js version: `v22.3.0`
Operating system: `MacOS 15.0`

### Expected behavior

The server should run on the provided host

### Screenshots

![CleanShot 2024-10-29 at 21 20 35@2x](https://github.com/user-attachments/assets/ebe897e2-000a-4ae2-a5e4-6a958660cd1a)

**Comment by thetutlage** [comment]
Both the `host` flag and the `HOST` environment variables are not taken into account.

**Comment by thetutlage** [comment]
Fixed by https://github.com/medusajs/medusa/pull/9912
