### ISSUE TITLE
Vercel Admin Deployment

### ISSUE THREAD

**Issue by volpejoaquin** [medusajs/medusa#9869]
## Bug report
I'm having some issues trying to run an admin version of medusajs v2 on vercel site. I can't make it work and I don't know what it's happening.

### Describe the bug

I have the following `Build & Development Settings`:

<img width="958" alt="Screenshot 2024-10-29 at 9 50 50 PM" src="https://github.com/user-attachments/assets/7ab3e9ba-9985-4183-bc6f-27c30b55af90">

The building step it's working but I'm getting 404 when I try to enter to the site under `/app` path 👇 

<img width="1125" alt="Screenshot 2024-10-29 at 9 51 23 PM" src="https://github.com/user-attachments/assets/6839e1f2-0aaf-4ed0-9d13-b67d8b93b633">

<img width="1265" alt="Screenshot 2024-10-29 at 9 51 58 PM" src="https://github.com/user-attachments/assets/c4f9c174-88a1-4134-b441-9c63754b910e">

My scripts are 👇 

<img width="612" alt="Screenshot 2024-10-29 at 9 53 29 PM" src="https://github.com/user-attachments/assets/e27a69c7-54ef-418d-bba4-8aa928d7bb8b">

btw, I want to run the project on port `80` on vercel ⚠️ 

I would love to have some help on this error because I spent many hours and couldn't figure it out 😢 

### Importat Note

I added this file but it's not working (I saw something related to [this on v1](https://github.com/medusajs/medusa/blob/ccec9b875014bd0cf3beeea6df091df16cd44603/www/apps/resources/app/deployment/admin/vercel/page.mdx#L2)) 👇 

<img width="664" alt="Screenshot 2024-10-29 at 9 56 29 PM" src="https://github.com/user-attachments/assets/4f14f721-3293-4716-974a-807981d94eec">

I guess that this can be related to the port configuration or to something related to `rewrites

### System information

Medusa version (including plugins): `latest` (`2.0.1`)
Node.js version: 20
Database: postgress
Operating system: Mac OS
Browser (if relevant): Firefox (it's not relevant)

**Comment by docloulou** [comment]
please attach the build and deployment log from vercel

this is my config, and its works : 
![image](https://github.com/user-attachments/assets/0c24fc0a-9b51-4bf2-8099-e58ddb45c670)
![image](https://github.com/user-attachments/assets/4d7debae-5677-4ea1-89c6-40bca03cd71c)
![image](https://github.com/user-attachments/assets/dad238b8-7674-4203-becd-49490ab39739)
![image](https://github.com/user-attachments/assets/47bf1b69-c104-44c4-9494-315537db40e2)

**Comment by shahednasser** [comment]
Hi @volpejoaquin , we have a documentation on how to deploy the admin on vercel [here](https://docs.medusajs.com/resources/deployment/admin/vercel).

Please follow its steps, and if you face any problems, feel free to reopen this issue.

**Comment by volpejoaquin** [comment]
@docloulou @shahednasser is there any way to also deploy the medusa server into vercel ? I don't want to use different tools for each part (server, admin, store)

**Comment by shahednasser** [comment]
You can learn how to deploy the server and admin in this guide:

https://docs.medusajs.com/resources/deployment/medusa-application/railway

The storefront has to be deployed separately. Learn how to do it in this guide: 

https://docs.medusajs.com/resources/deployment/storefront/vercel

**Comment by docloulou** [comment]
> @docloulou @shahednasser is there any way to also deploy the medusa server into vercel ? I don't want to use different tools for each part (server, admin, store)

 Medusa application is not built for serverless platform (like vercel, netlify...) you can host Medusa application and admin on the same VM/dedicated server or separate application from admin (admin on vercel and application on real server)

If you are not familiar with server management you should wait for Medusa cloud

**Comment by asif7897** [comment]
**Do anyone find solution ?**

**Comment by asif7897** [comment]
**Has anyone found a solution?**

**Comment by volpejoaquin** [comment]
@asif7897 no, I'm using https://railway.app/

**Comment by amaben2020** [comment]
> Hi [@volpejoaquin](https://github.com/volpejoaquin) , we have a documentation on how to deploy the admin on vercel [here](https://docs.medusajs.com/resources/deployment/admin/vercel).
> 
> Please follow its steps, and if you face any problems, feel free to reopen this issue.

Doesnt work even after following the steps

<img width="1321" alt="Image" src="https://github.com/user-attachments/assets/4bfc1dbb-6e46-45d5-b4e0-ced9c01dac3f" />

**Comment by Reomar** [comment]
> please attach the build and deployment log from vercel
> 
> this is my config, and its works : ![image](https://github.com/user-attachments/assets/0c24fc0a-9b51-4bf2-8099-e58ddb45c670) ![image](https://github.com/user-attachments/assets/4d7debae-5677-4ea1-89c6-40bca03cd71c) ![image](https://github.com/user-attachments/assets/dad238b8-7674-4203-becd-49490ab39739) ![image](https://github.com/user-attachments/assets/47bf1b69-c104-44c4-9494-315537db40e2)

Thanks @docloulou  this works, but the moment I refresh the page it brings that 404 again

Edited: 

Solved by adding this line to `vercel.json` inside the root directory

```js

{
  "rewrites": [{ "source": "/(.*)", "destination": "/index.html" }]
}

**Comment by rodrigobarona** [comment]
@Reomar thank you so much for sharing the experience and the configuration. How is running Vercel after a week of testing? Because the Medusa documentations recommend running a platform like railway and not on Vercel, it is frontend oriented

**Comment by ecbakas** [comment]
Hey, i'am trying to deploy on vercel when i follow those steps im ending up with this blank screen you can check; https://pratika.ertugrulcan.com.tr/

**Comment by ecbakas** [comment]
> Hey, i'am trying to deploy on vercel when i follow those steps im ending up with this blank screen you can check from here; https://pratika.ertugrulcan.com.tr/
> 
> im open any advice & help. thank you 

its working now. i think it was cache issue.

**Comment by ecbakas** [comment]
![Image](https://github.com/user-attachments/assets/6785e507-fb07-41f5-b550-ef8a51b9985f)
![Image](https://github.com/user-attachments/assets/406bbe2d-e5f0-4b83-b0c8-004e50e64d0c)

I'am stuck here on deploy admin to vercel. Any help?

Deployment on : https://pratika.ertugrulcan.com.tr
