### ISSUE TITLE
Cannot start Medusa after the first launch

### ISSUE THREAD

**Issue by howardRaul1** [medusajs/medusa#9873]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

**System information**
Medusa version: 2.0.1.
Node.js version: v20.18.0
Database: Postgres 17
Operating system: Windows 10

**Steps to Reproduce**
Following the Quick Start Guide, I ran "npx create-medusa-app@latest" to launch Medusa for the first time, and it worked fine.

However, after I restarted my computer and tried to launch Medusa a second time, I believe that I cannot re-use the above command anymore, because I am not "creating" a new Medusa instance.

Instead, to start Medusa, I followed the documentation at "https://docs.medusajs.com/learn/first-customizations" to run "npm run dev".  Then, I got the following errors:

C:\Users\xxx\xxx\medusa> npm run dev
npm error Missing script: "dev"
npm error
npm error To see a list of scripts, run:
npm error   npm run

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by webgodo** [comment]
1. Make sure you're running the `npm run dev` command in the correct working directory. If you created the project (using `npx create-medusa-app@latest`) in the home folder (`~`), navigate to that folder with `cd`, and open the directory that was created. The folder name will be the name you provided in response to the `npx` prompt, "What's the name of your project?"

2. If the previous step didn’t work, please paste the content of the `package.json` file.
