### ISSUE TITLE
Notification Provider is not working

### ISSUE THREAD

**Issue by imumesh18** [medusajs/medusa#9874]
### Describe the bug

I have a custom notification provider for sending whatsapp messages but the notification provider says it’s not found. I have followed the v1 docs for creating custom notification provider i have added the identifier and i have added the loaders as well but still no luck if someone can help will be really appreciated.

I Keep on getting this error.

info:    Could not find a notification provider with id: whatsapp.
warn:    An error occured while whatsapp was processing a notification for order.placed: Could not find a notification provider with id: whatsapp.

### System information

Medusa CLI version: 1.3.23
Medusa version: 1.20.9
Node.js version: v22
Database: postgresql
Operating system: macos
Browser (if relevant):

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

Here is the code
// src/services/whatsapp.ts

import { Lifetime } from 'awilix';
import { AbstractNotificationService, type ReturnedData } from '@medusajs/medusa';
import WhatsappProvider from '../providers/whatsapp';
import type { EntityManager } from 'typeorm';
import { type CountryCode, parsePhoneNumber } from 'libphonenumber-js';
import { SUPPORTED_LANGUAGES_CODE } from '../types/whatsapp/languageCodes';
import OrderService from './order';

export default class WhatsappService extends AbstractNotificationService {
	static identifier = 'whatsapp';
	static LIFE_TIME = Lifetime.SINGLETON;
	private client: WhatsappProvider;
	protected manager_: EntityManager;
	protected transactionManager_: EntityManager;
	protected orderService: OrderService;

	constructor(container, options) {
		super(container);
		this.client = new WhatsappProvider({
		});
		this.manager_ = container.resolve('manager');
		this.transactionManager_ = container.resolve('transactionManager');
		this.orderService = container.resolve('orderService');
	}

	async sendNotification(event: string, data: unknown, attachmentGenerator: unknown): Promise<ReturnedData> {
		console.log('Sending WhatsApp message:', event, data);
		if (event === OrderService.Events.PLACED) {
			return await this.manager_.transaction(async (manager) => {
				const order = await this.orderService
					.withTransaction(manager)
					.retrieveWithTotals((data as { id: string }).id, {
						relations: [
							'items',
							'items.variant',
							'items.variant.product',
							'items.variant.product.store',
							'shipping_methods',
							'shipping_address',
							'gift_cards',
							'discounts',
							'payments',
							'store',
						],
					});

				// bussiness logic to send to whatsapp.
		}

		// Return a default value if the event is not 'order.placed'
		return {
			to: '',
			status: 'ignored',
			data: data as Record<string, unknown>,
		};
	}

	async resendNotification(
		notification: unknown,
		config: unknown,
		attachmentGenerator: unknown
	): Promise<ReturnedData> {
		const { event, data } = notification as { event: string; data: unknown };
		return this.sendNotification(event, data, attachmentGenerator);
	}
}

// src/loaders/notification.ts
import type { MedusaContainer, NotificationService } from '@medusajs/medusa';
import OrderService from '../services/order';

export default async (container: MedusaContainer): Promise<void> => {
	const notificationService = container.resolve<NotificationService>('notificationService');
	notificationService.subscribe(OrderService.Events.PLACED, 'whatsapp');
};

### Additional context

Add any other context about the problem here

**Comment by sradevski** [comment]
There are multiple notification providers in v1 that work as expected, so you've likely missed some steps from https://docs.medusajs.com/v1/development/notification/create-notification-provider. You can also refer to the existing providers on how you might need to set things up.
