### ISSUE TITLE
It is not possible to create a new user within the application or via the CLI command.

### ISSUE THREAD

**Issue by JuanseSosa** [medusajs/medusa#9875]
### Describe the bug

When an invitation link is created and then accessed to enter the details for the new account, the system detects an error. If I try to use the same email again, I receive a message that the email is already in use.

### System information

Medusa version (including plugins): 2.0.1
Node.js version: 20
Database: postgres 16
Operating system: IOS 

### Steps to reproduce the behavior

1. Go to User Administration.
2. Send User Invitation.
3. Open the invitation link.
4. Enter the information.
5. See error.

### Screenshots

![image](https://github.com/user-attachments/assets/8a985639-00c2-40a0-97c6-e17cbb8a1155)
![image (1)](https://github.com/user-attachments/assets/5afc4dc0-47b7-4f9c-99b0-688295f832c7)
![Captura de pantalla 2024-10-30 a la(s) 3 09 56 p  m](https://github.com/user-attachments/assets/a5626a66-b94e-4073-bdd2-4a2a1fa939d8)

**Comment by olivermrbl** [comment]
What error are you seeing the first time to attempt to accept the invite?

**Comment by JuanseSosa** [comment]
The error I see when trying to accept the invitation for the first time is the following,: 
<img width="1119" alt="Captura de pantalla 2024-10-31 a la(s) 5 32 49 p  m  (2)" src="https://github.com/user-attachments/assets/08097b5c-7d11-40ae-8ecd-5511e643b703">

And then this error:
The error occurs when the guest's email has already been used previously to send an invitation that was later canceled. Here's a test: https://www.loom.com/share/d458ed4dc9c84aaa849c57617c09beac?sid=4d2fe58a-8d98-4049-a6bd-fea68cc909f7

**Comment by JuanseSosa** [comment]
@olivermrbl Is there any update on this?

**Comment by sradevski** [comment]
We cannot reproduce this on our side. Please try upgrading to the latest version and let us know if the issue still persists.
