### ISSUE TITLE
Medusa v2 Documentation: Issue in 3.3. Modules - Medusa v2 Documentation

### ISSUE THREAD

**Issue by kooliahmd** [medusajs/medusa#9876]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Following the doc on how to create a module, I'm getting this TS error:
```
 error TS2307: Cannot find module '@medusajs/framework/utils' or its corresponding type declarations.
```

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by mhumayunsaeed** [comment]
Been facing the same issue. Used the following commands in the terminal:

`yarn add awilix@^8.0.1`
`yarn add @mikro-orm/core@5.9.7 @mikro-orm/knex@5.9.7 @mikro-orm/migrations@5.9.7 @mikro-orm/postgresql@5.9.7`
`yarn add @medusajs/cli`

This did fix the issue for me but then I had another error and I am stuck on it. It is the following error:

![image](https://github.com/user-attachments/assets/4f390162-27c7-411b-9b3f-e3d5e3fb8a44)

**Comment by br-busolo** [comment]
I have been running V1 just fine until yesterday. Both my local and production build are down and it is chaotic:
<img width="1117" alt="Screenshot 2024-10-31 at 13 39 11" src="https://github.com/user-attachments/assets/d5116fd2-a47d-4f90-9310-5f9e171c3997">

**Comment by mhumayunsaeed** [comment]
> I have been running V1 just fine until yesterday. Both my local and production build are down and it is chaotic: <img alt="Screenshot 2024-10-31 at 13 39 11" width="1117" src="https://private-user-images.githubusercontent.com/125957179/381917808-d5116fd2-a47d-4f90-9310-5f9e171c3997.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0Mzk2NTgsIm5iZiI6MTczMDQzOTM1OCwicGF0aCI6Ii8xMjU5NTcxNzkvMzgxOTE3ODA4LWQ1MTE2ZmQyLWE0N2QtNGY5MC05MzEwLTVmOWUxNzFjMzk5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQwNTM1NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzdlMTJlOTg5NWRmZDM2MDBmZjVmZTUxNTJhYjdiMmQ0NjA4YjcyNmQxZTFkZjJkMmMxNzE1MTdmNjA4ZDg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PEA2UUvkPTZP0Bsrg1AQrKkubD4TnOJFrjc7bkg47bg">



Have you been able to try the possible solution I mentioned? There were some more additions, but try this first and let me know.

Also, add the '@medusajs/framework' by using the following command: `yarn add '@medusajs/framework@latest`

**Comment by br-busolo** [comment]
Still running into a host of issues. Unfortunately moving to V2 is not an option because core plugins we use are not implemented. Any luck @Humayun-glitch

**Comment by mhumayunsaeed** [comment]
> Still running into a host of issues. Unfortunately moving to V2 is not an option because core plugins we use are not implemented. Any luck @Humayun-glitch

No, mate! I gave up on it and started giving other projects my priority. I kept on running different issues even after solving the ` error TS2307: Cannot find module '@medusajs/framework/utils'`

**Comment by br-busolo** [comment]
Thanks mate. This is a live project for me with traffic that is now not working. All paths even a new installation is failing. Very bad experience. Will share anything I learn.

**Comment by mhumayunsaeed** [comment]
> Thanks mate. This is a live project for me with traffic that is now not working. All paths even a new installation is failing. Very bad experience. Will share anything I learn.

Sure, same here. I was assigned to run this locally and this is an ongoing project. Idk, whether it is a core Medusa issue for me or is because some previous developer has fucked it up. The API is unable to run, other things such as the admin panel were able to run locally.

**Comment by sradevski** [comment]
Hey all, can you please try upgrading to the latest version (or creating a new medusa project)? There should be no issues that we are aware of, but please report if there are!

**Comment by mhumayunsaeed** [comment]
@sradevski I tried upgrading to the latest version but it conflicts with the other dependencies. Anyway, I upgraded to the latest version and then ran the "yarn seed" command. I get the error that I have to use the medusa seed command. Now, I am stuck there. Any guides on how to proceed from there? I have to run an already built marketplace locally.
