### ISSUE TITLE
Can not install meilisearch plugin in v2.0.1

### ISSUE THREAD

**Issue by kooliahmd** [medusajs/medusa#9879]
On `v2.0.1` It is not possible to install meilisearch with :
```
npm install medusa-plugin-meilisearch
```

I get: 
```
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: medusa-starter-default@0.0.1
npm error Found: @medusajs/medusa@2.0.1
npm error node_modules/@medusajs/medusa
npm error   peerOptional @medusajs/medusa@"^2.0.0" from @medusajs/test-utils@2.0.1
npm error   node_modules/@medusajs/test-utils
npm error     dev @medusajs/test-utils@"latest" from the root project
npm error   @medusajs/medusa@"latest" from the root project
npm error
npm error Could not resolve dependency:
npm error medusa-plugin-meilisearch@"*" from the root project
npm error
npm error Conflicting peer dependency: @medusajs/medusa@1.20.10
npm error node_modules/@medusajs/medusa
npm error   peer @medusajs/medusa@"^1.12.0" from medusa-plugin-meilisearch@2.0.11
npm error   node_modules/medusa-plugin-meilisearch
npm error     medusa-plugin-meilisearch@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
```

When I try with 
```
 npm install medusa-plugin-meilisearch --legacy-peer-deps
 ```
 
The install passes, However medusa backend server fails to start:
 ```
Error: Unable to find the plugin "medusa-plugin-meilisearch".
    at resolvePlugin (/Users/kooliahmed/projects/buyup/buyup/node_modules/@medusajs/medusa/src/loaders/helpers/resolve-plugins.ts:97:11)
    at /Users/kooliahmed/projects/buyup/buyup/node_modules/@medusajs/medusa/src/loaders/helpers/resolve-plugins.ts:137:21
    at Array.map (<anonymous>)
 ```

**Comment by olivermrbl** [comment]
The Meilisearch plugin has not been migrated to v2, and v1 plugins are not compatible with v2 you can't use it in its current state.  

We don't have any plans of migrating the Meilisearch plugin ourselves any time soon, but you are more than welcome to take on this task when we release our updated plugin documentation soon.

**Comment by IgorKhomenko** [comment]
@olivermrbl is there any example of plugin which is already compatible with V2? Would be really helpful

**Comment by chillpilllike** [comment]
So currently we can not use any form of search on storefront?

**Comment by kooliahmd** [comment]
> So currently we can not use any form of search on storefront?

Medusa 2.0 is still at its early stage, And most of the ecosystem around it is just not yet ready. Seems that the maintainers will rely on contributors to fill the gap. I would be happy to help however there is no guidance on how to upgrade a v1 plugin to v2. Also, should the `medusa-plugin-meilisearch` v2 live inside medusa mono-repo or create a new repo inside medusa orga, or the contributor have to fully take its ownership?

**Comment by rokmohar** [comment]
I had the same issue and I've created a plugin that works for me with Medusa 2.0.1

https://github.com/rokmohar/medusa-plugin-meilisearch

**Comment by okechukwu0127** [comment]
> https://github.com/rokmohar/medusa-plugin-meilisearch

Tried installing yours on v2.0.4 and i got the same blocker that @kooliahmd  complained about
Your documentation shows that `medusa-plugin-meilisearch` would be installed not `@rokmohar/medusa-plugin-meilisearch` wondering if that was on purpose.

Also when i introduce the plugin resolve as `@rokmohar/medusa-plugin-meilisearch`, the app would not start and brakes as well

```plugins: [
    // other plugins
    {
      resolve: '@rokmohar/medusa-plugin-meilisearch',
```
      

Kindly assist

**Comment by rokmohar** [comment]
Hello @okechukwu0127 

I've updated the README, please make sure to use the correct command for install:
`npm install --save @rokmohar/medusa-plugin-meilisearch`

And put your MeiliSearch configuration under `modules` key and not `plugins` in `medusa-config.ts`

Let me know how it works.

**Comment by okechukwu0127** [comment]
@rokmohar 

Thanks for your clarification on the package name to install

at  src/subscribers/product-upsert.ts

```
const meiliSearchService: MeiliSearchService = container.resolve(
    "@rokmohar/medusa-plugin-meilisearch"
  );
```

I get the error 
'MeiliSearchService' refers to a value, but is being used as a type here. Did you mean 'typeof MeiliSearchService'?ts(2749)

<img width="968" alt="image" src="https://github.com/user-attachments/assets/b44b9f2c-5b91-48f3-a383-a8cf4a63d2c8">

When i change the code to

```
const meiliSearchService: typeof MeiliSearchService = container.resolve(
    "@rokmohar/medusa-plugin-meilisearch"
  );
```

I now get the error 
```
Property 'addDocuments' does not exist on type 'ModuleExports'.ts(2339)

```


<img width="809" alt="image" src="https://github.com/user-attachments/assets/a5710d05-f4f4-4c80-9b34-c1cccbfbc1c5">



same issue is applicable to src/subscribers/product-delete.ts


<img width="983" alt="image" src="https://github.com/user-attachments/assets/62b4f7c3-cd22-41ad-91b2-4cc6943f1662">




Kindly let me know what the issue is as I am still stock

**Comment by rokmohar** [comment]
Hey @okechukwu0127 

It seems you have a wrong import, it looks like you forgot the opening and closing bracket, it should be:
`import { MeiliSearchService } from '@rokmohar/medusa-plugin-meilisearch'`

This is what I have and works for me:
![image](https://github.com/user-attachments/assets/57a8b91c-9db4-4294-813d-603e96036e2d)

I see that I wrote it wrong in the README, I will update it.

Hope this works for you

**Comment by UKFox** [comment]
Works for me, thank you @rokmohar 👍

**Comment by SalahAdDin** [comment]
What about typesense?

**Comment by UKFox** [comment]
Just for info, if you have the error : 

```
error:   Could not resolve module: @rokmohar/medusa-plugin-meilisearch. Error: Loaders for module @rokmohar/medusa-plugin-meilisearch failed: Unexpected token '<', "<html>
<h"... is not valid JSON

error:   Error starting server
error:   Loaders for module @rokmohar/medusa-plugin-meilisearch failed: Unexpected token '<', "<html>
<h"... is not valid JSON
Error: Loaders for module @rokmohar/medusa-plugin-meilisearch failed: Unexpected token '<', "<html>
<h"... is not valid JSON
    at runLoaders [...]
    [...]
```

It just mean that your meilisearch instance is not accessible, in my case it was behind a proxy and i guess this was the result of a 502 or 404 html error page when trying to fetch the json file

Hope this helps anyone who might face this problem

**Comment by UKFox** [comment]
Also @rokmohar i think you might add the id to `displayedAttributes` for the plugin settings in the doc as the ids are used for the result search page SearchResultsTemplate : **\src\app\[countryCode]\(main)\results\[query]\page.tsx**
```
const ids = hits
    .map((h) => h.objectID || h.id)
    .filter((id): id is string => {
      return typeof id === "string"
    })

  return (
    <SearchResultsTemplate
      query={query}
      ids={ids}
      sortBy={sortBy}
      page={page}
      countryCode={params.countryCode}
    />
  )
```

**Comment by SalahAdDin** [comment]
> I had the same issue and I've created a plugin that works for me with Medusa 2.0.1
> 
> https://github.com/rokmohar/medusa-plugin-meilisearch

Thanks, you are the mvp.
