### ISSUE TITLE
Unable to find the plugin "medusa-payment-razorpay", when updating medusa to v2.

### ISSUE THREAD

**Issue by sushant049** [medusajs/medusa#9881]
error:   Error starting server Error: Unable to find the plugin "medusa-payment-razorpay", when updating medusa to v2.

**Comment by imumesh18** [comment]
The Razorpay plugin has not been migrated to v2, and v1 plugins are not compatible with v2 you can't use it in its current state. Probably you can reach out to the developer of the plugin to get it resolved.

**Comment by WASIF738871** [comment]
@olivermrbl I am on v2 what to do next for payment as Razorpay plugin is not compatible with v2.

**Comment by OmkarHalpatrao** [comment]
> [@olivermrbl](https://github.com/olivermrbl) I am on v2 what to do next for payment as Razorpay plugin is not compatible with v2.

did you find any way for razorpay payment

**Comment by WASIF738871** [comment]
yes @olivermrbl I got this link https://medusajs.com/plugins/@sgftechpayment-razorpay/. Use this It should work fine .

**Comment by OmkarHalpatrao** [comment]
> yes [@olivermrbl](https://github.com/olivermrbl) I got this link https://medusajs.com/plugins/@sgftechpayment-razorpay/. Use this It should work fine .

thankyou rightnow i was refering this only and i had one doubt do we need to create any module because it is not mentioned in docs and there are resolving the razorpay in modules in medusa.config.ts

**Comment by WASIF738871** [comment]
> > yes [@olivermrbl](https://github.com/olivermrbl) I got this link https://medusajs.com/plugins/@sgftechpayment-razorpay/. Use this It should work fine .
> 
> thankyou rightnow i was refering this only and i had one doubt do we need to create any module because it is not mentioned in docs and there are resolving the razorpay in modules in medusa.config.ts

yes you need to create razorpay button in client side and you will be good to go. It all mentioned in docs how to add in backend and client side

**Comment by OmkarHalpatrao** [comment]
does this  https://medusajs.com/plugins/@sgftechpayment-razorpay/.    plugin supports v2
after creating button i got error on this line 
import { cancelOrder, placeOrder, waitForPaymentCompletion } from "@lib/data/cart"
it says cancelOrder is not thier in /lib/data/cart

**Comment by WASIF738871** [comment]
> does this https://medusajs.com/plugins/@sgftechpayment-razorpay/. plugin supports v2 after creating button i got error on this line import { cancelOrder, placeOrder, waitForPaymentCompletion } from "@lib/data/cart" it says cancelOrder is not thier in /lib/data/cart

Comment cancelOrder function

**Comment by asrudii** [comment]
> yes [@olivermrbl](https://github.com/olivermrbl) I got this link https://medusajs.com/plugins/@sgftechpayment-razorpay/. Use this It should work fine .

Hi @WASIF738871 , when I try select payment razor, there is error "Error setting up the request: cart not ready"

**Comment by medhansh17** [comment]
Has anyone set up razorpay payment for react-native apps , getting cart not ready error

**Comment by hritikjsl** [comment]
"Error setting up the request: cart not ready"
I am getting the same error. if resolve please update
