### ISSUE TITLE
Missing store entity in remote query entry points

### ISSUE THREAD

**Issue by tot-kristian** [medusajs/medusa#9883]
### Describe the bug
I tried linking an entity with the store:
`export default defineLink(
  {
    linkable: MarketplaceModule.linkable.vendor,
    isList: false,
  },
  StoreModule.linkable.store,
);`

Now when I try to use it (after running links:sync) like this:
` const query = req.scope.resolve(ContainerRegistrationKeys.QUERY);

  const { data: vendors } = await query.graph({
    entity: "vendor",
    fields: ["id", "store.*"],
    filters: {
      id: vendor.id,
    },
  });`
  
 I see a TS issue where "store.*" is not a known property of vendor. I checked and it indeed does not exist. Only the **store_link** exists. I checked even further and the Store type is completely missing from the configuration.
 

### System information

Medusa version (including plugins):2.0.1
Node.js version:20.17.0
Database:postgres
Operating system:
Browser (if relevant):

### Steps to reproduce the behavior

1. Define any link with the Store module's store entity
2. Try to query the store through your linked entity using remote query
3. See error

### Expected behavior

I would expect to see the store entity defined and I should also be able to choose the store's properties I need there.

**Comment by olivermrbl** [comment]
@tot-kristian, can you please provide a minimum reproduction in a repository and we will take a look at it?

**Comment by tot-kristian** [comment]
@olivermrbl Sure, here you go:
https://github.com/tot-kristian/medusa-store-bug
Sorry for the delay.

2 endpoints are exposed, 
POST /bug-reproduction
`body: { productId: string; storeId: string}`
- Just so you can see that I can indeed link the product and the store  together without any issues

GET /bug-reproduction
- it should just return every product with the store entity attached to it.
- I used a workflow here and inside the step you can already see the issue: `get-products-with-store-step.ts`

Additionally you can also check the `.medusa/types/remote-query-entry-points.d.ts` which is the source of the issue I believe.


Let me know if I can provide any additional information.

**Comment by tot-kristian** [comment]
@olivermrbl Could it be that the graphql schema for the store is just missing? 
I don't see a schema file/folder there. If that is the case, I would be more than happy to create it.
