### ISSUE TITLE
Order retrieve missing value: variant_option_values

### ISSUE THREAD

**Issue by GabrielDA7** [medusajs/medusa#9893]
the sdk method store.order.retrieve({}) doesn't retrieve variant_option_values, it's always null despite the fact that my item has variant options

Medusa version: 2.0.1

variant_options_values must be filled in with the variant's options

**Comment by adrien2p** [comment]
Hi @GabrielDA7 ,

would you mind sharing how you are using the retrieve method please? maybe if you could have a reproduction repository it could help. So far, I am unable to reproduce
<img width="751" alt="Screenshot 2024-11-06 at 15 59 27" src="https://github.com/user-attachments/assets/0f979f89-716d-4ae7-bfe0-b95c9f6de4a3">
