### ISSUE TITLE
Password reset token not generating properly

### ISSUE THREAD

**Issue by Chethank1407** [medusajs/medusa#9894]
I tried posting my mail ID (which is a customer data in medusa db) to fetch password reset token. It returned with status 204 No content.

![image](https://github.com/user-attachments/assets/79fd0dbd-5acd-4c33-bc76-58e70eee4bb4)

Any other method is available to fetch the reset token?

**Comment by olivermrbl** [comment]
@Chethank1407, I presume this is an endpoint you've created yourself, as this is not part of our core?

Please add more information about what actions are performed in the endpoint, as we currently have no way of debugging this issue.

**Comment by olivermrbl** [comment]
@Chethank1407 Please fill out a new issue template with the required information. Closing until then.
