### ISSUE TITLE
Error: An error occurred while processing payment. Webhook_received: TypeError: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by ok1054689** [medusajs/medusa#9896]
### Describe the bug

 packages/medusa/src/subscribers/payment-webhook.ts 

 if (
    (input.payload.rawData as unknown as SerializedBuffer).type === "Buffer"
  ) 

error: An error occurred while processing payment.webhook_received: TypeError: Error: An error occurred while processing payment. Webhook_received: TypeError: Cannot read properties of undefined (reading 'type')
 
### System information

Medusa version (including plugins):
Node.js version: 20
Database: 
Operating system: 2.0
Browser (if relevant):

**Comment by sradevski** [comment]
@ok1054689 please provide more information on where the call to the webhook comes from, and your general setup, otherwise we can't do much about the issue you are facing.
