### ISSUE TITLE
Too many Redis sessions

### ISSUE THREAD

**Issue by renequez** [medusajs/medusa#9897]
### Describe the bug

Using the redis cache module creates a session in redis for **_each_** request made from the storefront.

### System information

Medusa version (including plugins): 2.0.1
Node.js version: 20.17.0
Database: PostgreSQL 16.4
Operating system: Windows 11
Browser (if relevant): Edge

### Steps to reproduce the behavior

1. Create a new medusa project, with the storefront starter.
2. Have a redis db running on your machine.

```ts
import { loadEnv, defineConfig } from '@medusajs/framework/utils'

loadEnv(process.env.NODE_ENV || 'development', process.cwd())

module.exports = defineConfig({
  projectConfig: {
    databaseUrl: process.env.DATABASE_URL,
    redisUrl: process.env.REDIS_URL, // <---
    http: {
      storeCors: process.env.STORE_CORS!,
      adminCors: process.env.ADMIN_CORS!,
      authCors: process.env.AUTH_CORS!,
      jwtSecret: process.env.JWT_SECRET || "supersecret",
      cookieSecret: process.env.COOKIE_SECRET || "supersecret",
    }
  },
  modules: [
    {
      resolve: '@medusajs/medusa/cache-redis',
      options: {
         redisUrl: process.env.REDIS_URL,
      },
   },
  ]
})
```

3. Go to the storefront and navigate around, add products to the cart, refresh pages etc., basically act like a normal user on a shop.
4. Check your redis `sess` key, you'll notice there are tons of sessions created.

### Expected behavior

I don't think there should be sessions created for each and every request. Is this maybe happening without adding redisUrl to the config as well? I've got no idea how to check what express-session does when in-memory, but in any case, it doesn't sound right.

**Comment by olivermrbl** [comment]
This is not related to the cache module. The express session is part of a core loader (`@medusajs/medusa`) and runs on every app start. 

By default, we save uninitialized sessions with `express-session`. You can configure most options in your `medusa-config.js`.

https://github.com/medusajs/medusa/blob/7b51204ef396cecdc85ec7a18270c123d29a24cd/packages/core/framework/src/http/express-loader.ts#L34-L47

For example:
```
module.exports = defineConfig({
  projectConfig: {
    ...
    http: { ... },
    sessionOptions: { saveUninitialized: false }
  },
  ...
})
```

It might be that destroying unused sessions is a better approach, I'll discuss this with the team. But this should solve your "issue" for the time being.
