### ISSUE TITLE
failed to get medusa version Error: Cannot find module

### ISSUE THREAD

**Issue by imash96** [medusajs/medusa#9903]
### Describe the bug

When I start the server by setting **MEDUSA_TELEMETRY_VERBOSE** to true and then start dev server lot of error come and server fail to start

> D:\Project\backend>npm run dev
> 
> medusa-starter-default@0.0.1 dev
> medusa develop
> 
> info:    Watching filesystem to reload dev server on file change
> failed to get medusa version Error: Cannot find module 'D:\Project\backend\node_modules\@medusajs\medusa\dist\modules\package.json.js'
>     at createEsmNotFoundErr (node:internal/modules/cjs/loader:1286:15)
>     at finalizeEsmResolution (node:internal/modules/cjs/loader:1274:15)
>     at resolveExports (node:internal/modules/cjs/loader:640:14)
>     at Function._findPath (node:internal/modules/cjs/loader:748:31)
>     at Function.<anonymous> (node:internal/modules/cjs/loader:1235:27)
>     at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue (D:\Project\backend\node_modules\@cspotcode\source-map-support\source-map-support.js:811:30)
>     at Function.Module._resolveFilename (D:\Project\backend\node_modules\tsconfig-paths\src\register.ts:115:36)
>     at Function.resolve (node:internal/modules/helpers:151:19)
>     at Telemeter.getMedusaVersion (D:\Project\backend\node_modules\@medusajs\telemetry\dist\telemeter.js:80:41)
>     at Telemeter.enqueue_ (D:\Project\backend\node_modules\@medusajs\telemetry\dist\telemeter.js:123:34) {
>   code: 'MODULE_NOT_FOUND',
>   path: 'D:\\Project\\backend\\node_modules\\@medusajs\\medusa\\package.json'
> }
> failed to get medusa version Error: Cannot find module '@medusajs/medusa-cli'
> Require stack:
> - D:\Project\backend\node_modules\@medusajs\telemetry\dist\telemeter.js
> - D:\Project\backend\node_modules\@medusajs\telemetry\dist\index.js
> - D:\Project\backend\node_modules\@medusajs\cli\dist\create-cli.js
> - D:\Project\backend\node_modules\@medusajs\cli\dist\index.js
> - D:\Project\backend\node_modules\@medusajs\cli\cli.js
>     at Function.<anonymous> (node:internal/modules/cjs/loader:1249:15)
>     at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue (D:\Project\backend\node_modules\@cspotcode\source-map-support\source-map-support.js:811:30)
>     at Function.Module._resolveFilename (D:\Project\backend\node_modules\tsconfig-paths\src\register.ts:115:36)
>     at Function.resolve (node:internal/modules/helpers:151:19)
>     at Telemeter.getCliVersion (D:\Project\backend\node_modules\@medusajs\telemetry\dist\telemeter.js:94:18)
>     at Telemeter.enqueue_ (D:\Project\backend\node_modules\@medusajs\telemetry\dist\telemeter.js:124:31)
>     at Telemeter.track (D:\Project\backend\node_modules\@medusajs\telemetry\dist\telemeter.js:113:21)
>     at track (D:\Project\backend\node_modules\@medusajs\telemetry\dist\index.js:17:15)
>     at internalStart (D:\Project\backend\node_modules\@medusajs\medusa\src\commands\start.ts:97:10)
>     at start (D:\Project\backend\node_modules\@medusajs\medusa\src\commands\start.ts:221:11) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     'D:\\Project\\backend\\node_modules\\@medusajs\\telemetry\\dist\\telemeter.js',
>     'D:\\Project\\backend\\node_modules\\@medusajs\\telemetry\\dist\\index.js',
>     'D:\\Project\\backend\\node_modules\\@medusajs\\cli\\dist\\create-cli.js',
>     'D:\\Project\\backend\\node_modules\\@medusajs\\cli\\dist\\index.js',
>     'D:\\Project\\backend\\node_modules\\@medusajs\\cli\\cli.js'
>   ]
> }
> info:    Skipping instrumentation registration. No register function found.
> redisUrl not found. A fake redis instance will be used.
> warn:    Local Event Bus installed. This is not recommended for production.
> warn:    No default locking provider explicit defined. Using "in-memory" as default.
> Flushing queue...
> info:    No job to load from D:\Project\backend\node_modules\@medusajs\medusa\dist\jobs. skipped.
> info:    Generated modules types
> ✔ Server is ready on port: 9000 – 11ms
> info:    Admin URL → http://localhost:9000/app
> failed to get medusa version Error: Cannot find module 'D:\Project\backend\node_modules\@medusajs\medusa\dist\modules\package.json.js'
>     at createEsmNotFoundErr (node:internal/modules/cjs/loader:1286:15)
>     at finalizeEsmResolution (node:internal/modules/cjs/loader:1274:15)
>     at resolveExports (node:internal/modules/cjs/loader:640:14)
>     at Function._findPath (node:internal/modules/cjs/loader:748:31)
>     at Function.<anonymous> (node:internal/modules/cjs/loader:1235:27)
>     at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue (D:\Project\backend\node_modules\@cspotcode\source-map-support\source-map-support.js:811:30)
>     at Function.Module._resolveFilename (D:\Project\backend\node_modules\tsconfig-paths\src\register.ts:115:36)
>     at Function.resolve (node:internal/modules/helpers:151:19)
>     at Telemeter.getMedusaVersion (D:\Project\backend\node_modules\@medusajs\telemetry\dist\telemeter.js:80:41)
>     at Telemeter.enqueue_ (D:\Project\backend\node_modules\@medusajs\telemetry\dist\telemeter.js:123:34) {
>   code: 'MODULE_NOT_FOUND',
>   path: 'D:\\Project\\backend\\node_modules\\@medusajs\\medusa\\package.json'
> }
> failed to get medusa version Error: Cannot find module '@medusajs/medusa-cli'
> Require stack:
> - D:\Project\backend\node_modules\@medusajs\telemetry\dist\telemeter.js
> - D:\Project\backend\node_modules\@medusajs\telemetry\dist\index.js
> - D:\Project\backend\node_modules\@medusajs\cli\dist\create-cli.js
> - D:\Project\backend\node_modules\@medusajs\cli\dist\index.js
> - D:\Project\backend\node_modules\@medusajs\cli\cli.js
>     at Function.<anonymous> (node:internal/modules/cjs/loader:1249:15)
>     at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue (D:\Project\backend\node_modules\@cspotcode\source-map-support\source-map-support.js:811:30)
>     at Function.Module._resolveFilename (D:\Project\backend\node_modules\tsconfig-paths\src\register.ts:115:36)
>     at Function.resolve (node:internal/modules/helpers:151:19)
>     at Telemeter.getCliVersion (D:\Project\backend\node_modules\@medusajs\telemetry\dist\telemeter.js:94:18)
>     at Telemeter.enqueue_ (D:\Project\backend\node_modules\@medusajs\telemetry\dist\telemeter.js:124:31)
>     at Telemeter.track (D:\Project\backend\node_modules\@medusajs\telemetry\dist\telemeter.js:113:21)
>     at track (D:\Project\backend\node_modules\@medusajs\telemetry\dist\index.js:17:15)
>     at Server.<anonymous> (D:\Project\backend\node_modules\@medusajs\medusa\src\commands\start.ts:142:16)
>     at Server.emit (node:events:530:35) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     'D:\\Project\\backend\\node_modules\\@medusajs\\telemetry\\dist\\telemeter.js',
>     'D:\\Project\\backend\\node_modules\\@medusajs\\telemetry\\dist\\index.js',
>     'D:\\Project\\backend\\node_modules\\@medusajs\\cli\\dist\\create-cli.js',
>     'D:\\Project\\backend\\node_modules\\@medusajs\\cli\\dist\\index.js',
>     'D:\\Project\\backend\\node_modules\\@medusajs\\cli\\cli.js'
>   ]
> }
> 

### System information

Medusa version (including plugins): 2.0.1
Node.js version: 22.x
Database: Postgres
Operating system: Win11

### Steps to reproduce the behavior

1. Install medusa
2. set MEDUSA_TELEMETRY_VERBOSE to true
3. Start server

### Expected behavior

No error should have logged to console

**Comment by adrien2p** [comment]
Thank you for reporting it, I ve pushed a fix for that [here](https://github.com/medusajs/medusa/pull/9939)
