### ISSUE TITLE
GET http://shop.mydomain.com:42161/app/ net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by princessfrombabylon99** [medusajs/medusa#9905]
I installed Medusa on AWS, 
Node 20
Postgres
I used this command npx create-medusa-app@latest, till then everything worked fine.
Then I tried to login to admin panel, I tried to enter the email , also tried to create a new admin user.
Same as last year , it started throwing errors.
![image](https://github.com/user-attachments/assets/8e73d099-94af-467c-833f-0437896db072)
![image](https://github.com/user-attachments/assets/fd9c3868-cd5d-47cb-ba3f-dbfb67535d60)

I tried to assisgn a domain and SSL also , still faced same problem.

**Comment by princessfrombabylon99** [comment]
Below is the Nginx configuration , has it got anything to do with this?
```
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
  
   worker_connections 1024;
}

http {
   # Basic Settings
   sendfile on;
   tcp_nopush on;
   types_hash_max_size 2048;
   server_tokens off;

   include /etc/nginx/mime.types;
   default_type application/octet-stream;

   # SSL Settings
   ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
   ssl_prefer_server_ciphers on;

   # Logging Settings
   access_log /var/log/nginx/access.log;
   error_log /var/log/nginx/error.log;

   # Gzip Settings
   gzip off;

   server {

      listen [::]:443 ssl;
      listen 443 ssl;

      server_name shop.prodURL;
    ssl_certificate /etc/letsencrypt/live/shop.prodURL/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/shop.prodURL/privkey.pem; # managed by Certbot

      include /etc/letsencrypt/options-ssl-nginx.conf;
      ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

      location / {
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header Host $host;
         proxy_pass http://127.0.0.1:9000;
         proxy_http_version 1.1;
         proxy_cache_bypass $http_upgrade;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection "upgrade";
      }
   
}
}

```

**Comment by sradevski** [comment]
@princessfrombabylon99 I understand it's frustrating when things don't work. However, just saying we need to do something about it doesn't help, as it's not even clear where the issue is.

What would instead be useful is for you to provide more information on your setup, hosting, and a reproduction of the issue so we can find if it is an issue with Medusa or your hosting setup.

**Comment by princessfrombabylon99** [comment]
@sradevski I need help with getting started .Especially , deploying MedusaJS and setting up reverse proxy. Could you please help ?

**Comment by SalahAdDin** [comment]
> @sradevski I need help with getting started .Especially , deploying MedusaJS and setting up reverse proxy. Could you please help ?

Did you check the documentation?

**Comment by princessfrombabylon99** [comment]
@SalahAdDin Team Medusa  already helped me.  Hence closed this thread.
