### ISSUE TITLE
Tax inclusive pricing for shipping options not respecting region's settings

### ISSUE THREAD

**Issue by renequez** [medusajs/medusa#9906]
### Describe the bug

When I enable tax inclusive pricing for a region and set a shipping option's price for that region, the shipping option’s `is_tax_inclusive` value will be `false`, which causes it to be calculated incorrectly in the cart.

Currently, the workaround is to set the currency as tax inclusive as well, which changes `is_tax_inclusive` to `true`. However, I’m not sure this is the correct setup.

### System information

Medusa version (including plugins): 2.0.1
Node.js version: 20.17.0
Database: PostgreSQL 16.4
Operating system: Windows 11
Browser (if relevant): Edge

### Steps to reproduce the behavior

1. Create a region with tax inclusive pricing enabled.
2. Create a shipping option for the manual provider.
3. Update the shipping option's price for the created region.
4. Call `medusaClient.store.fulfillment.listCartOptions` via medusa js sdk.
5. You'll see `"is_tax_inclusive": false` in the response.

### Expected behavior

I would expect for the shipping option pricing to respect a region's settings.

**Comment by olivermrbl** [comment]
@renequez, thanks for the report. #9929 should solve the issue.
