### ISSUE TITLE
Remove "Promo Code" not working with body promo_codes.

### ISSUE THREAD

**Issue by abdul-tycheros** [medusajs/medusa#9911]
Here is my code for a DELETE method with a request body.

Note: It works correctly in Postman (screenshot attached).

const response = await apiClient.request({
    method: "DELETE",
    url: `/store/carts/${cartId}/promotions?fields=+items.thumbnail`,
    data: {
        promo_codes: [promoCode],
    },
});

<img width="877" alt="Screenshot 2024-11-04 at 9 28 55 am" src="https://github.com/user-attachments/assets/7fa2dc03-bef3-4a0d-9436-814c7db9bddc">

**Comment by olivermrbl** [comment]
@abdul-tycheros, this report does not follow our guidelines for issues. Please provide the information in the template and we will attend to it.

**Comment by abdul-tycheros** [comment]
@olivermrbl  ERROR  [Cart API] Error removing promo code: Request failed with status code 400 . Unable to remove the applied promo code using the API with Axios in React.

```
export const removePromoCode = async (promoCode: string) => {
  try {
    let cartId = (await getCache(CACHE_KEY))?.id;
    if (!cartId) throw new Error("No cart found");

    const response = await apiClient.request({
      method: "DELETE",
      url: `/store/carts/${cartId}/promotions?fields=+items.thumbnail`,
      data: {
        promo_codes: [promoCode],
      },
    });

    const cart = response.data.cart;
    if (cart.items && cart.items.length > 0) {
      await setCache(CACHE_KEY, cart);
      return cart;
    } else {
      return await getCache(CACHE_KEY);
    }
  } catch (error) {
    const errorMessage = (error as Error).message || "Unknown error occurred";
    console.error(`[Cart API] Error removing promo code: ${errorMessage}`);
    throw error;
  }
};
```

**Comment by olivermrbl** [comment]
@abdul-tycheros, what does the error message say?

**Comment by abdul-tycheros** [comment]
@olivermrbl  ERROR [Cart API] Error removing promo code: Request failed with status code 400.

medusa v2.0

Actually, the issue is with using the DELETE method while passing a body in Axios with React. This request works fine in Postman. Could you try this API on your end without the SDK?

**Comment by abdul-tycheros** [comment]
@olivermrbl Issue resolved with same code above code. Successfully removed used promo code.
