### ISSUE TITLE
Cannot Implement Custom Tax Provider

### ISSUE THREAD

**Issue by ricardolopesdev** [medusajs/medusa#9918]
### Describe the bug

I'am trying to implement a Custom Tax Provider and i follow the documentation.
https://docs.medusajs.com/resources/commerce-modules/tax/module-options

and gives the follow error:
*TypeError: moduleProviderServices is not iterable at loadInternalModule*
### System information

Medusa version (including plugins):2.0.1
Node.js version:20.18.0
Database:Postegre
Operating system:Ubuntu 22.04
Browser (if relevant):

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets
_medusa-config.ts_
```
import { Modules } from "@medusajs/framework/utils"
 module.exports = defineConfig({
  modules: [
    {
      resolve: "@medusajs/tax",
      options: {
        providers: [
          {
            resolve: "./path/to/my-provider",
            id: "my-provider",
            options: {},
          },
        ],
      },
    },
  ]
})
```

_my-tax.ts_ located in ".src/servives"

```
 import {ITaxProvider, TaxTypes} from "@medusajs/framework/types"

 export default class MyTaxProvider implements ITaxProvider {
   static identifier = "my-tax";
   getIdentifier(): string {
    return "my-tax";
    }
async getTaxLines(
    itemLines: TaxTypes.ItemTaxCalculationLine[],
    shippingLines: TaxTypes.ShippingTaxCalculationLine[],
    _: TaxTypes.TaxCalculationContext
  ): Promise<(TaxTypes.ItemTaxLineDTO | TaxTypes.ShippingTaxLineDTO)[]> {
let taxLines: (TaxTypes.ItemTaxLineDTO | TaxTypes.ShippingTaxLineDTO)[] =
      itemLines.flatMap((l) => {
        return l.rates.map((r) => ({
          rate_id: r.id,
          rate: r.rate || 0,
          name: r.name,
          code: r.code,
          line_item_id: l.line_item.id,
          provider_id: this.getIdentifier()
        }))
})
 taxLines = taxLines.concat(
      shippingLines.flatMap((l) => {
        return l.rates.map((r) => ({
          rate_id: r.id,
          rate: r.rate || 0,
          name: r.name,
          code: r.code,
          shipping_line_id: l.shipping_line.id,
          provider_id: this.getIdentifier()
        }))
      })
    )
    return taxLines
  }
}

```

### Additional context

Add any other context about the problem here

**Comment by olivermrbl** [comment]
Does your provider contain a `ModuleProvider` export similar to the existing providers, e.g. [the Stripe payment provider](https://github.com/medusajs/medusa/blob/develop/packages/modules/providers/payment-stripe/src/index.ts)? For reference, here's the general [guide on building a payment provider](https://docs.medusajs.com/resources/references/payment/provider).

If you could please provide a reproduction in a repository, we'd be happy to take a deeper look.

**Comment by ricardolopesdev** [comment]
Please Check this repo https://github.com/ricardolopesit/my-medusa-store/tree/master/src/services/my-tax
check services folder in src

**Comment by olivermrbl** [comment]
@ricardolopesit, the application starts without errors on my side.

Any specific steps I should take to reproduce?

**Comment by ricardolopesdev** [comment]
Yes it's true, please try use the provider. To perform some verification/calculation and check if enter some info in provided. This is the issue I have. Not enter in provider when it is to verify/calculate items taxes

**Comment by ricardolopesdev** [comment]
@olivermrbl I analyzed your code, and in tax-module-service.ts i found one block that seems it's related with the tax provider.
https://github.com/medusajs/medusa/blob/develop/packages/modules/tax/src/services/tax-module-service.ts#L721

**Comment by ricardolopesdev** [comment]
@olivermrbl I managed to solve this bug, but I think it will be the correct way, it's need add the id of provider to table __tax_provider__  
![image](https://github.com/user-attachments/assets/6ef5a63f-f872-433b-8dae-22fb4c7e033a)
and after that add the same id in table __tax_region__ 
![image](https://github.com/user-attachments/assets/3618bd0c-7d5a-4f0c-a863-123fb08914a2)

I edit and managed the tables manualy.
