### ISSUE TITLE
Google Authorization, in case sensitive.

### ISSUE THREAD

**Issue by Furman1331** [medusajs/medusa#9925]
### Describe the bug

While checking google authorization logic, I found TODO comment, which is a clear mistake.

Google OAuth documentation has a Important point which says
![image](https://github.com/user-attachments/assets/73df53e3-a81d-4ce2-b748-328ec5f7b84b)

In medusa it works like the entity_id is email.
![Zrzut ekranu 2024-11-4 o 23 32 39](https://github.com/user-attachments/assets/62f740e4-6da1-4ff0-a296-7bf9052ba30c)

Google documentation: https://developers.google.com/identity/gsi/web/guides/verify-google-id-token
You will found it on rock bottom.

**Comment by sradevski** [comment]
Hey there, thanks for opening a ticket! We'll look into resolving that TODO as soon as possible.
