### ISSUE TITLE
The installation immediately reported an error saying that medusa is not an internal or external command. Where in the document does it say that @medusajs/medusa-cli needs to be installed?

### ISSUE THREAD

**Issue by aboutjquery** [medusajs/medusa#9926]
### What Medusa version and documentation are you using?

None

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The installation immediately reported an error saying that medusa is not an internal or external command. Where in the document does it say that @medusajs/medusa-cli needs to be installed?

To be honest, the documentation is very confusing and very unfriendly, I hope the documentation can explain these basics more clearly.

getting start just one sentence npx create-medusa-app@latest

"
Get started[#](https://docs.medusajs.com/learn#get-started)

Prerequisites
3
[Node.js v20+↗](https://nodejs.org/en/download)
[Git CLI tool↗](https://git-scm.com/downloads)
[PostgreSQL↗](https://www.postgresql.org/download/)
Create your first Medusa store by running the following command:

Terminal
npx create-medusa-app@latest
"

No, its pop error after installed, "medusa is not an internal or external command"

Where is it mentioned that you need to install cli? It is very unfriendly to newbies, thank you.

### How can this issue be resolved?

1. easier to start
2.don't waste time

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by princessfrombabylon99** [comment]
+1
I am experiencing the same issues and need some assistance with CORS and .env configuration.  I am unable to log into the admin panel. I had intended to use Medusa in a production environment, but there appears to be limited documentation available regarding configuration. I reached out to the Medusa team about a year ago, but they pay such a deaf ear.

**Comment by aboutjquery** [comment]
> +1 I am experiencing the same issues and need some assistance with CORS and .env configuration. I am unable to log into the admin panel. I had intended to use Medusa in a production environment, but there appears to be limited documentation available regarding configuration. I reached out to the Medusa team about a year ago, but they pay such a deaf ear.

I wasted an afternoon, and after solving the cli, some errors that were not documented kept appearing, at least I couldn't find them when getting started.

First, there is not much information online, and the ones that are available are v1.

Second, when you click on the content searched on Google, it is always page not found. Why not do some redirection??? It’s super confusing.

For example https://docs.medusajs.com/development/backend/install

Later, someone on reddit also mentioned that it was difficult to get started with documentation.

I'm giving up for now, I'll study other things first

I hope the official can improve the documentation

**Comment by princessfrombabylon99** [comment]
**I also gave up and installed Magento2.**

![image](https://github.com/user-attachments/assets/57a93d63-09fe-4655-bb4c-c75c15677d23)

**Comment by SalahAdDin** [comment]
> **I also gave up and installed Magento2.**
> 
> ![image](https://private-user-images.githubusercontent.com/185712311/383254279-57a93d63-09fe-4655-bb4c-c75c15677d23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4Mzk2ODksIm5iZiI6MTczMDgzOTM4OSwicGF0aCI6Ii8xODU3MTIzMTEvMzgzMjU0Mjc5LTU3YTkzZDYzLTA5ZmUtNDY1NS1iYjRjLWM3NWMxNTY3N2QyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQyMDQzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDM4YjgyNGEyNDFjOWUzY2VjZGY5NjRjMjQzYTQ3NDQwYWFkYjk5ZjNkM2I4YWQwZDUzNTk2NDU3ZDk5MDBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mrkMQgYgkn-t3Qt8gljSCFXT729iqegcXfrakJ7paAU)

Saleor or Vendure Commerce

**Comment by sradevski** [comment]
Hey all, we'll look into this and see how we can improve the getting started. I'll close this for now as a duplicate.

duplicate #9927

**Comment by sradevski** [comment]
I'll reopen to look into the create-medusa-app issue separately, as that might be a different issue

**Comment by shahednasser** [comment]
Hey @aboutjquery thank you for opening this issue. Can you provide more details on the command you ran, the progress of the command, and the exact error you got?

**Comment by princessfrombabylon99** [comment]
@shahednasser I get screen , tried creating another user , still I get same message
![image](https://github.com/user-attachments/assets/1d006688-6c98-4938-80b1-58c5c9773be3)

I used `npx create-medusa-app@latest`
Node 20
Postgres 16
Ubuntu 24.04

Could you please help so that I too could get the ball rollling. I am really giving up on this.

**Comment by shahednasser** [comment]
Hi @princessfrombabylon99 , seems like your issue is different, can you create a new issue to avoid overlap? I'll be happy to help you there! Also, when creating the new issue, if you can share the logs when you ran `npx create-medusa-app@latest` and the steps after would be great!

**Comment by princessfrombabylon99** [comment]
> Hi @princessfrombabylon99 , seems like your issue is different, can you create a new issue to avoid overlap? I'll be happy to help you there! Also, when creating the new issue, if you can share the logs when you ran `npx create-medusa-app@latest` and the steps after would be great!

Okay, Let me create a different thread. I will tag you.

**Comment by shahednasser** [comment]
Closing this issue as it should be resolved in the latest Medusa version. Feel free to re-open if you keep facing it.
