### ISSUE TITLE
Where is the documentation that explains how to get started???.env? cli? etc...

### ISSUE THREAD

**Issue by aboutjquery** [medusajs/medusa#9927]
### What Medusa version and documentation are you using?

None

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I have tried many different things, and this is the most difficult project I have ever encountered to start. The official documentation states that starting is as simple as "npx create-medusa-app@latest"

What next? It’s Customizations. Should we point out how to configure env? Should we explain this at the beginning? If it is not configured, how to start? How to Customize?

You always need to add an explanation about .env.template, right? Even if the document is available now but I can't find it, I think the official should put the information that needs to be used at the beginning into an earlier chapter.

### How can this issue be resolved?

1. More reasonable documentation

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by sradevski** [comment]
Hey there, thanks for opening a ticket!

Can you please try to provide more concrete information on what and how you'd like to see? We can take that and improve on our current documentation. Just saying the documentation is bad doesn't give a very constructive feedback and doesn't really help us improve the docs.

Thanks!
