### ISSUE TITLE
column "unit_price" of relation "order_item" does not exist

### ISSUE THREAD

**Issue by lokeswaran-a** [medusajs/medusa#9931]
### Describe the bug

The last time I upgraded Medusa was when preview version 8 was published. Today, I'm trying to upgrade to the latest **preview** version (not to RC or actual 2.0.0). I'm not able to create an order from the cart.

Here is the code for the step that I created; it is failing at the `await orderService.createOrders(createOrder)` line

```typescript
const createOrderForCart = createStep(
  'create-order-for-cart',
  async (input: WorkflowData<CartToOrder>, { container }) => {
    const cartService = container.resolve<ICartModuleService>(Modules.CART)
    const orderService = container.resolve<IOrderModuleService>(Modules.ORDER)
    const cart = await cartService.retrieveCart(input.id, {
      relations: ['shipping_address', 'billing_address', 'items'], filters: {
        metadata: {
          is_active: true,
        },
      },
    })
    delete cart.shipping_address['id']
    delete cart.billing_address['id']

    const allItems = cart.items.map((item) => {
      return {
        title: item.title,
        quantity: item.quantity,
        unit_price: item.unit_price,
      }
    })

    const createOrder = {
      customer_id: input.customer_id,
      items: allItems,
      status: 'pending',
      currency_code: 'INR',
      region_id: cart.region_id,
      shipping_address: cart.shipping_address,
      billing_address: cart.billing_address,
      metadata: cart.metadata,
    } as CreateOrderDTO

    const orders = await orderService.createOrders(createOrder)

    const order = orders[0]

    const link = createRemoteLinkStep([
      {
        [Modules.ORDER]: {
          order_id: order.id,
        },
        [Modules.CART]: {
          cart_id: input.id,
        },
      }])
    const result = transform({ link, input }, () => ({ orderId: link[0].order.order_id, cartId: input.id }))
    return new StepResponse({ result, cart, order })
  },
)
```

I tried the same with the [createOrdersStep](https://docs.medusajs.com/resources/references/medusa-workflows/steps/createOrdersStep) workflow from Medusa. But I m facing the same issue. Can someone confirm if it is a bug from our end or medusa end?

### System information

Medusa version (including plugins): latest preview
Node.js version: 20
Database: postgres:16
Operating system: macos
Browser (if relevant):

### Steps to reproduce the behavior

Use the `orderService.createOrders` method or `createOrdersStep` step

### Expected behavior

An order should be created from the cart

### Error trace stack

```bash
{
  message: 'column "unit_price" of relation "order_item" does not exist',
  name: 'Error',
  stack: 'Error: column "unit_price" of relation "order_item" does not exist\n' +
    '    at dbErrorMapper (/Users/lokeswaranaruljothy/Documents/tw/web-redington-backoffice/node_modules/@medusajs/utils/src/dal/mikro-orm/db-error-mapper.ts:60:11)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async MikroOrmBaseRepository.transaction (/Users/lokeswaranaruljothy/Documents/tw/web-redington-backoffice/node_modules/@medusajs/utils/src/dal/mikro-orm/mikro-orm-repository.ts:72:12)\n' +
    '    at async OrderModuleService.descriptor.value (/Users/lokeswaranaruljothy/Documents/tw/web-redington-backoffice/node_modules/@medusajs/utils/src/modules-sdk/decorators/inject-transaction-manager.ts:32:14)\n' +
    '    at async OrderModuleService.createOrders (/Users/lokeswaranaruljothy/Documents/tw/web-redington-backoffice/node_modules/@medusajs/order/src/services/order-module-service.ts:605:20)\n' +
    '    at async Proxy.<anonymous> (/Users/lokeswaranaruljothy/Documents/tw/web-redington-backoffice/node_modules/@medusajs/orchestration/src/workflow/local-workflow.ts:129:20)\n' +
    '    at async Object.<anonymous> (/Users/lokeswaranaruljothy/Documents/tw/web-redington-backoffice/src/workflows/create-order-from-cart.ts:54:20)\n' +
    '    at async Object.invoke (/Users/lokeswaranaruljothy/Documents/tw/web-redington-backoffice/node_modules/@medusajs/workflows-sdk/src/utils/composer/helpers/create-step-handler.ts:72:52)\n' +
    '    at async DistributedTransaction.handler (/Users/lokeswaranaruljothy/Documents/tw/web-redington-backoffice/node_modules/@medusajs/orchestration/src/workflow/workflow-manager.ts:214:16)\n' +
    '    at async stepHandler (/Users/lokeswaranaruljothy/Documents/tw/web-redington-backoffice/node_modules/@medusajs/orchestration/src/transaction/transaction-orchestrator.ts:806:20)\n' +
    '⮑ sat /Users/lokeswaranaruljothy/Documents/tw/web-redington-backoffice/src/workflows/create-order-from-cart.ts: [create-order-for-cart-step-id -> create-order-for-cart (invoke)]',
  __isMedusaError: true,
  type: 'invalid_data',
  code: undefined,
  date: 2024-11-05T07:52:16.673Z
}
```

**Comment by olivermrbl** [comment]
@lokeswaran-a, have you run migrations? The `unit_price` column was added to the `order_item` table recently. 

```
npx medusa db:migrate
```

**Comment by lokeswaran-a** [comment]
Yes, you are right! When I create a new database and run the migrations, it creates the order_item table with unit_price. But in our case, we already have this table, so I think the latest is not getting applied. What can I do?

Edit: ~~These 3 migrations from the order module have not been run in our database even after the version upgrade: Migration20240913092514, Migration20240930122627, and Migration20241014142943.~~ These migrations are running in our higher environment. So, we are good!

One more issue:
Previous we were using orderMoudleService.deleteOrderItems, but now that method is not exported from Medusa. Any particular reason for that? There are other methods as well like createOrderSummaries, updateOrderSummaries and cartModuleService.createLineItems

**Comment by olivermrbl** [comment]
@lokeswaran-a, great!

In a previous release, some order module methods were renamed, e.g. `deleteOrderItems` to `deleteOrderLineItems`. You can find all available methods in the API reference [here](https://docs.medusajs.com/resources/references/order).

**Comment by lokeswaran-a** [comment]
Oh, I thought that `deleteOrderLineItems` will only delete in the `order_line_item` table. But what about the `createOrderSummaries`?

**Comment by carlos-r-l-rodrigues** [comment]
hi @lokeswaran-a,
Not related to the issue, but I noticed that your step definition is calling `createRemoteLinkStep` and there is also a `transform` in there.
Steps should only execute a single operation, and their compensation function should revert that.
`createRemoteLinkStep` should be called as another step in your workflow, and inside a step you shouldn't be using any `transform`, these are meant to be used on the `createWorkflow` where you are composing its execution flow.
