### ISSUE TITLE
Docs(Code Issue): Wrong environment templates for the Railway deployment

### ISSUE THREAD

**Issue by 0ctave** [medusajs/medusa#9937]
### What Medusa version and documentation are you using?

None

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

The documentation indicates in the Railway deployment section seem to give the wrong environment file templates.

It seem to be the case for the server and worker templates :

> COOKIE_SECRET=supersecret # TODO GENERATE SECURE SECRET
> JWT_SECRET=supersecret  # TODO GENERATE SECURE SECRET
> STORE_CORS= # STOREFRONT URL
> ADMIN_CORS= # ADMIN URL
> AUTH_CORS= # STOREFRONT AND ADMIN URLS, SEPARATED BY COMMAS
> DISABLE_MEDUSA_ADMIN=true 
> MEDUSA_WORKER_MODE=worker    # This should be set to server as this is a server node
> PORT=9000
> DATABASE_URL=${{Postgres.DATABASE_PUBLIC_URL}}
> REDIS_URL=${{Redis.REDIS_PUBLIC_URL}}

> COOKIE_SECRET=supersecret # TODO GENERATE SECURE SECRET
> JWT_SECRET=supersecret  # TODO GENERATE SECURE SECRET
> DISABLE_MEDUSA_ADMIN=false  # This should be set to true as this is a worker node
> MEDUSA_WORKER_MODE=worker
> PORT=9000
> DATABASE_URL=${{Postgres.DATABASE_PUBLIC_URL}}
> REDIS_URL=${{Redis.REDIS_PUBLIC_URL}}

### How can this issue be resolved?

A small modification of the documentation should fix the imprecision

1. Replace _worker_ with _server_ in the server node configuration MEDUSA_WORKER_MODE
2. Replace _false_ with _true_ in the worker node configuration DISABLE_MEDUSA_ADMIN

### Are you interested in working on this issue?

- [x] I would like to fix this issue

**Comment by sradevski** [comment]
Hey, thanks for opening an issue! Would you be interested in opening a PR to get this fixed?

**Comment by 0ctave** [comment]
Sure, I'll open a PR to remake part of the page when I have some time

**Comment by shahednasser** [comment]
Thanks for opening this issue! We actually have PR #9842 to fix this, just need to merge it
