### ISSUE TITLE
[Bug]: Service factory update method does not remove the link when empty list is passed

### ISSUE THREAD

**Issue by lokeswaran-a** [medusajs/medusa#9943]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "dev": "medusa develop",
    "build": "medusa build",
    "start": "medusa start",
    "seed": "medusa exec ./src/scripts/user-seed.ts && medusa exec ./src/scripts/seed.ts",
    "migrate": "medusa db:migrate",
    "migrate:gen": "npx medusa db:generate",
    "test": "jest --testPathPattern=spec\\.ts$",
    "test:watch": "jest --watch --testPathPattern=spec\\.ts$",
    "test:coverage:local": "jest --coverage --testPathPattern=spec\\.ts$",
    "test:coverage": "jest --coverage",
    "lint": "yarn eslint",
    "lint:fix": "yarn eslint --fix",
    "prepare": "husky",
    "test:env": "cross-env NODE_ENV=test yarn run dev",
    "test:integration": "jest integration-tests"
  },
  "dependencies": {
    "@aws-sdk/client-s3": "^3.658.1",
    "@aws-sdk/client-ses": "^3.637.0",
    "@aws-sdk/credential-provider-web-identity": "^3.621.0",
    "@aws-sdk/s3-request-presigner": "^3.675.0",
    "@medusajs/admin-sdk": "preview",
    "@medusajs/api-key": "preview",
    "@medusajs/auth": "preview",
    "@medusajs/auth-emailpass": "preview",
    "@medusajs/cache-inmemory": "preview",
    "@medusajs/cart": "preview",
    "@medusajs/cli": "preview",
    "@medusajs/currency": "preview",
    "@medusajs/customer": "preview",
    "@medusajs/event-bus-local": "preview",
    "@medusajs/event-bus-redis": "preview",
    "@medusajs/file": "preview",
    "@medusajs/file-local-next": "preview",
    "@medusajs/framework": "^2.0.1",
    "@medusajs/fulfillment": "preview",
    "@medusajs/fulfillment-manual": "preview",
    "@medusajs/inventory-next": "preview",
    "@medusajs/medusa": "preview",
    "@medusajs/notification": "preview",
    "@medusajs/notification-local": "preview",
    "@medusajs/order": "preview",
    "@medusajs/payment": "preview",
    "@medusajs/pricing": "preview",
    "@medusajs/product": "preview",
    "@medusajs/promotion": "preview",
    "@medusajs/region": "preview",
    "@medusajs/sales-channel": "preview",
    "@medusajs/stock-location-next": "preview",
    "@medusajs/store": "preview",
    "@medusajs/tax": "preview",
    "@medusajs/user": "preview",
    "@medusajs/workflow-engine-inmemory": "preview",
    "@types/express-serve-static-core": "^5.0.0",
    "@types/multer": "^1.4.12",
    "csv-parser": "^3.0.0",
    "express": "^4.17.2",
    "get-port": "^7.1.0",
    "http-status-codes": "^2.3.0",
    "json-2-csv": "^5.5.6",
    "multer": "^1.4.5-lts.1",
    "newrelic": "latest",
    "typeorm": "^0.3.20",
    "uuid": "^10.0.0"
  },
  "devDependencies": {
    "@babel/preset-env": "^7.24.8",
    "@eslint/js": "^9.6.0",
    "@mikro-orm/cli": "5.9.7",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "@stdlib/number-float64-base-normalize": "0.0.8",
    "@stylistic/eslint-plugin": "^2.3.0",
    "@swc/core": "1.5.7",
    "@types/express": "^4.17.13",
    "@types/jest": "^29.5.12",
    "@types/mime": "1.3.5",
    "@types/node": "^17.0.8",
    "@types/react": "^18.3.2",
    "@types/uuid": "^10.0.0",
    "cross-env": "^7.0.3",
    "eslint": "^9.6.0",
    "eslint-plugin-react": "^7.34.3",
    "globals": "^15.8.0",
    "husky": "^9.0.11",
    "jest": "^29.7.0",
    "jest-sonar": "^0.2.16",
    "medusa-test-utils": "^1.1.45",
    "supertest": "^7.0.0",
    "ts-jest": "^29.2.3",
    "ts-node": "^10.9.2",
    "typescript": "5.5.4",
    "typescript-eslint": "^7.16.0"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v20.0.0

### Database and its version

postgresql 16

### Operating system name and version

Macos

### What happended?

Here is my code:
```typescript
const updatedRole = await roleModuleService.updateRoles({
  id,
  permissions:[],
})
```
I have created 2 tables with many-to-many relationships: `roles` and `permissions`. When I update the roles with some permission IDs, it updates the _joint table_ by adding or removing the relationship. But when I pass an empty list ([]) for permission, no changes have been made to the joint table, i.e., the old relationships still exist.

btw, this was already raised via Slack, but since last week the Slack support has been removed. So, I dont know the latest update on this issue

### Expected behavior

Permissions linked to that role id should have been deleted

### Actual behavior

Permissions linked to that role ID still exist

### Link to reproduction repo

https://github.com/lokeswaran-a/medusa-update-method-bug

**Comment by sradevski** [comment]
Hey @lokeswaran-a I believe this should fix your issue: https://github.com/medusajs/medusa/pull/9917.

Please let me know if it doesn't and we'll look into it, closing the ticket until then

**Comment by lokeswaran-a** [comment]
In which version of Medusa is this fix published? We are sticking with the `preview` version in the `package.json` for now. So, will this fix be applied by removing` yarn.lock` and installing again in our service?

**Comment by sradevski** [comment]
@lokeswaran-a You can upgrade to 2.0.2 (will be released today), or to the latest preview. Updating your package.json and lockfile should do the trick

**Comment by lokeswaran-a** [comment]
@sradevski One doubt: I upgraded the medusa packages a few days ago, and I see the version as `@medusajs/admin-bundler@2.0.1-preview-xxxxxxxxxxxx`. Does this mean it has new features that are introduced in the RC to 2.0.1? How does preview work?

**Comment by sradevski** [comment]
@lokeswaran-a since we officially released 2.0, we suggest using the 2.x versions now, not the previews. The previews work as follows: If the latest release is 2.0.2, all previews released after it will be eg. 2.0.3-preview-xxxx.

**Comment by lokeswaran-a** [comment]
@sradevski Yes, we are going live soon. So, we have planned to upgrade medusa after that

So, this bugfix and any other bugfix will be published in the preview releases as well, right?

**Comment by sradevski** [comment]
@lokeswaran-a yes it will, previews happen every 3 hours, just keep in mind that some of those might have a bug as they are not "official" per-se.

**Comment by lokeswaran-a** [comment]
Thanks,

Actually, the reason for now using the **official** version is that we don't have the bandwidth to fix the breaking changes introduced in the RC and official releases. But if the version in `yarn.lock` is already `@medusajs/admin-bundler@2.0.1-preview-xxxxxxxxxxxx` that means it has the breaking changes published in the RC and official version and we have handled the breaking changes, right?

**Comment by sradevski** [comment]
@lokeswaran-a yes, if all your packages are on that version

**Comment by siddharktw** [comment]
Adding to this discussion .
IN the above versions, I am seeing that a lot of medusa events like product.updated, cart.created etc. are not being generated.  Any idea?
