### ISSUE TITLE
[Bug]: Admin is hard-coded to use http://localhost:9000/

### ISSUE THREAD

**Issue by mofax** [medusajs/medusa#9945]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start --host 0.0.0.0",
    "dev": "medusa develop",
    "docker:build": "docker build -t coolcatch-bo .",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "2.0.2-preview-20241106030353",
    "@medusajs/cli": "2.0.2-preview-20241106030353",
    "@medusajs/framework": "2.0.2-preview-20241106030353",
    "@medusajs/medusa": "2.0.2-preview-20241106030353",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v22.3.0

### Database and its version

Postgres 17

### Operating system name and version

macOS 15.1

### Browser name

Chrome 130

### What happended?

I have medusa deployed here https://coolbackoffice.fly.dev/app

When trying to authenticate, the request goes to `http://localhost:9000/auth/user/emailpass` instead of `https://coolbackoffice.fly.dev/auth/user/emailpass`

### Expected behavior

The fetch call should use the relative path, that is, `/auth/user/emailpass` this would allow it to work on any domain since the browser can build out the full url.

### Actual behavior

request goes to `http://localhost:9000/auth/user/emailpass` probably because the path is hardcoded somewhere.

"somewhere" appears to be here: https://github.com/medusajs/medusa/blob/674c86eaa066aa2a9f296f464052d21acaf209f9/packages/admin/dashboard/src/lib/client/client.ts#L3

### Link to reproduction repo

github.com/mofax/coolcatch

**Comment by mofax** [comment]
[UPDATE]

Adding

```dotenv
VITE_MEDUSA_BACKEND_URL=https://coolbackoffice.fly.dev
```

does not appear to work either.

**Comment by sradevski** [comment]
Hey @mofax , we are getting this resolved as we speak:
1. First PR: https://github.com/medusajs/medusa/pull/9942
2. Don't default to localhost in admin: https://github.com/medusajs/medusa/pull/9947

In the meantime, you can set
```
{
  admin: {
   backendUrl: "https://yourdomain.com"
   }
}
```

in your medusa config for it to work, or you can just wait for the next release.

I'll close the ticket as it's something that will be resolved soon

**Comment by mofax** [comment]
thanks @sradevski will test when am back at my keyboard.
