### ISSUE TITLE
API Ref(store): Issue in Set Authentication Session

### ISSUE THREAD

**Issue by NaveenKumarRaja** [medusajs/medusa#9946]
### What Medusa version and documentation are you using?

None

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I'm trying to get authenticated customer info. But I got unauthorized error in response.
curl -X POST '{backend_url}/auth/session' \
-H 'Authorization: Bearer {jwt_token}'

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by sradevski** [comment]
Please provide more information on how you got the JWT token, what you did to debug this and so on. We cannot do anything with just the information you provided here.

Here's a [test for generating session cookies](https://github.com/medusajs/medusa/blob/30edc8fa40ff5ed6ecc8c55f555f9d975df497f5/integration-tests/http/__tests__/auth/admin/auth.spec.ts#L23), if there is an issue please reproduce it through a test and let us know.

Closing the issue until we have more info and we can confirm it being an issue
