### ISSUE TITLE
Using cloudlfare images for image storage

### ISSUE THREAD

**Issue by Conor-Burns** [medusajs/medusa#995]
Would like to try implementing https://www.cloudflare.com/products/cloudflare-images/ as a file package

Thoughts?

**Comment by olivermrbl** [comment]
That would be cool!

A good place to get started is by looking at one of our current file plugins (e.g. [DigitalOcean](https://github.com/medusajs/medusa/blob/master/packages/medusa-file-spaces/src/services/digital-ocean.js)).

Let me know if you need any help!

To test it against a locally running Medusa server the following steps, should make it happen:
- Navigate to your plugin package, `medusa-file-cloudflare` (or similar), run `yarn link`
- Build the plugin
- Navigate to your Medusa server and run `yarn link medusa-file-cloudflare`
- Add the plugin with its options to `medusa-config.js`
e.g. 
```
{
    resolve: `medusa-file-cloudflare`,
    options: {
    ....
    },
  },
```
- Upload image in admin

**Comment by Conor-Burns** [comment]
Ah well
