### ISSUE TITLE
[Bug]: Resolution of relationships in remote query types

### ISSUE THREAD

**Issue by noubase** [medusajs/medusa#9952]
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@dnd-kit/modifiers": "^7.0.0",
    "@medusajs/admin-sdk": "2.0.2-snapshot-20241105102007",
    "@medusajs/cli": "2.0.2-snapshot-20241105102007",
    "@medusajs/framework": "2.0.2-snapshot-20241105102007",
    "@medusajs/medusa": "2.0.2-snapshot-20241105102007",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "axios-retry": "^4.5.0",
    "contentful-management": "11.35.1",
    "contentful-rich-text-html-parser": "^1.5.13",
    "lodash": "^4.17.21",
    "pg": "^8.13.1",
    "react-icons": "^5.3.0",
    "xmlrpc": "^1.3.2"
  },
  "devDependencies": {
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/lodash": "^4.17.12",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "medusa-test-utils": "rc",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v20.18.0

### Database and its version

postgres (PostgreSQL) 16.3

### Operating system name and version

Mac OS

### What happended?

There is no `product` field on `OrderLineItem`, but I can resolve it with `query.graph`

![image](https://github.com/user-attachments/assets/c33ca33d-8d21-4b97-b4fc-ee79d9a8157e)

### Expected behavior

There should be a field `product: Product`

### Actual behavior

No field for `Product`

### Link to reproduction repo

There is no need in isolated repo for this issue

**Comment by adrien2p** [comment]
@noubase Thank you for the report, Indeed it is an issue on our side on the way we are resolving the read only link definition internally. We are working on it 💪

**Comment by noubase** [comment]
v2.0.4

It’s fixed, but only up to two levels of relationships.
<img width="882" alt="image" src="https://github.com/user-attachments/assets/dd22f287-0124-43a3-880e-ab47e7570b25">

**Comment by adrien2p** [comment]
> v2.0.4
> 
> 
> 
> It’s fixed, but only up to two levels of relationships.
> 
> <img width="882" alt="image" src="https://github.com/user-attachments/assets/dd22f287-0124-43a3-880e-ab47e7570b25">
> 
> 

We can indeed increase the level of resolution but the main idea was to prevent typescript to fail when reaching a too high level of depth. Cause ts is limited in how deep it can go. Though we can probably increase the limit to a higher level.
Wdyt @carlos-r-l-rodrigues i remember we discussed exactly that ahah
