### ISSUE TITLE
[Bug]: Medusajs admin crash on large product

### ISSUE THREAD

**Issue by erickirt** [medusajs/medusa#9954]
### Package.json file

```JSON
{
  "name": "medusa-next2",
  "version": "1.0.3",
  "private": true,
  "author": "Kasper Fabricius Kristensen <kasper@medusajs.com> & Victor Gerbrands <victor@medusajs.com> (https://www.medusajs.com)",
  "description": "Next.js Starter to be used with Medusa server",
  "keywords": [
    "medusa-storefront"
  ],
  "scripts": {
    "dev": "next dev -p 8000",
    "build": "next build",
    "start": "next start -p 8000",
    "lint": "next lint",
    "analyze": "ANALYZE=true next build",
    "test-e2e": "playwright test e2e"
  },
  "resolutions": {
    "webpack": "^5",
    "@types/react": "17.0.40"
  },
  "dependencies": {
    "@headlessui/react": "^1.6.1",
    "@hookform/error-message": "^2.0.0",
    "@medusajs/icons": "^2.0.1",
    "@medusajs/js-sdk": "latest",
    "@medusajs/ui": "rc",
    "@meilisearch/instant-meilisearch": "^0.7.1",
    "@paypal/paypal-js": "^5.0.6",
    "@paypal/react-paypal-js": "^7.8.1",
    "@stripe/react-stripe-js": "^1.7.2",
    "@stripe/stripe-js": "^1.29.0",
    "algoliasearch": "^4.20.0",
    "axios": "^1.6.7",
    "lodash": "^4.17.21",
    "next": "^14.0.0",
    "pg": "^8.11.3",
    "qs": "^6.12.1",
    "react": "^18.2.0",
    "react-country-flag": "^3.0.2",
    "react-dom": "^18.2.0",
    "react-instantsearch-hooks-web": "^6.29.0",
    "react-intersection-observer": "^9.3.4",
    "server-only": "^0.0.1",
    "tailwindcss-radix": "^2.8.0",
    "webpack": "^5"
  },
  "devDependencies": {
    "@babel/core": "^7.17.5",
    "@medusajs/types": "rc",
    "@medusajs/ui-preset": "rc",
    "@playwright/test": "^1.41.1",
    "@types/lodash": "^4.14.195",
    "@types/node": "17.0.21",
    "@types/pg": "^8.11.0",
    "@types/react": "^18.2.42",
    "@types/react-dom": "^18.2.18",
    "@types/react-instantsearch-dom": "^6.12.3",
    "ansi-colors": "^4.1.3",
    "autoprefixer": "^10.4.2",
    "babel-loader": "^8.2.3",
    "eslint": "8.10.0",
    "eslint-config-next": "^13.4.5",
    "postcss": "^8.4.8",
    "prettier": "^2.8.8",
    "tailwindcss": "^3.0.23",
    "typescript": "^5.3.2"
  }
}
```

### Node.js version

22.9

### Database and its version

Postgre 17

### Operating system name and version

Mac os(latest)

### Browser name

Chrome and safari

### What happended?

Admin crashes with large product

Create a product with about 1000 variants and the admin throws this error:
<--- Last few GCs --->

[56962:0x138008000]   173331 ms: Mark-Compact 4036.4 (4143.1) -> 4034.8 (4142.9) MB, pooled: 0 MB, 801.00 / 0.00 ms  (average mu = 0.064, current mu = 0.008) allocation failure; scavenge might not succeed
[56962:0x138008000]   174186 ms: Mark-Compact 4036.2 (4143.6) -> 4035.4 (4143.6) MB, pooled: 0 MB, 852.79 / 0.00 ms  (average mu = 0.033, current mu = 0.003) allocation failure; scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 0x10462e57c node::OOMErrorHandler(char const*, v8::OOMDetails const&) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
 2: 0x10480b768 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
 3: 0x1049e1480 v8::internal::Heap::stack() [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
 4: 0x1049f5614 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags)::$_7::operator()() const [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
 5: 0x1049f4ecc void heap::base::Stack::SetMarkerAndCallbackImpl<v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags)::$_7>(heap::base::Stack*, void*, void const*) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
 6: 0x105127044 PushAllRegistersAndIterateStack [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
 7: 0x1049df844 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
 8: 0x1049d4dd4 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
 9: 0x1049d5600 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
10: 0x1049aa760 v8::internal::FactoryBase<v8::internal::Factory>::NewRawTwoByteString(int, v8::internal::AllocationType) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
11: 0x1049b9e50 v8::internal::Factory::NewStringFromUtf8(v8::base::Vector<unsigned char const>, unibrow::Utf8Variant, v8::internal::AllocationType) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
12: 0x104827c14 v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::NewStringType, int) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
13: 0x1047216dc node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding, v8::Local<v8::Value>*) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
14: 0x104605ce8 void node::Buffer::(anonymous namespace)::StringSlice<(node::encoding)1>(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
15: 0x1051930f4 Builtins_CallApiCallbackOptimizedNoProfiling [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
16: 0x10c338a98 
17: 0x10b9cbe1c 
18: 0x10b7d7408 
19: 0x10c1245c8 
20: 0x10bf753bc 
21: 0x10c63299c 
22: 0x10c33b56c 
23: 0x10c3b46d4 
24: 0x10c3a6440 
25: 0x10c4a0884 
26: 0x10c18ea04 
27: 0x10518ec0c Builtins_JSEntryTrampoline [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
28: 0x10518e8f4 Builtins_JSEntry [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
29: 0x10493abd4 v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
30: 0x10493a14c v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
31: 0x1048218a4 v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
32: 0x10454dce0 node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context, v8::Local<v8::Value>) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
33: 0x104564b8c node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
34: 0x10471a3c8 node::StreamBase::CallJSOnreadMethod(long, v8::Local<v8::ArrayBuffer>, unsigned long, node::StreamBase::StreamBaseJSChecks) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
35: 0x10471badc node::EmitToJSStreamListener::OnStreamRead(long, uv_buf_t const&) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
36: 0x10471fd44 node::LibuvStreamWrap::OnUvRead(long, uv_buf_t const*) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
37: 0x1047204a8 node::LibuvStreamWrap::ReadStart()::$_1::__invoke(uv_stream_s*, long, uv_buf_t const*) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
38: 0x10517a97c uv__stream_io [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
39: 0x105182390 uv__io_poll [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
40: 0x105170390 uv_run [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
41: 0x10454e46c node::SpinEventLoopInternal(node::Environment*) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
42: 0x10467310c node::NodeMainInstance::Run(node::ExitCode*, node::Environment*) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
43: 0x104672ea4 node::NodeMainInstance::Run() [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
44: 0x1045f40b0 node::Start(int, char**) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
45: 0x18d93c274 start [/usr/lib/dyld]

### Expected behavior

Normal admin product editing

### Actual behavior

<--- Last few GCs --->

[56962:0x138008000]   173331 ms: Mark-Compact 4036.4 (4143.1) -> 4034.8 (4142.9) MB, pooled: 0 MB, 801.00 / 0.00 ms  (average mu = 0.064, current mu = 0.008) allocation failure; scavenge might not succeed
[56962:0x138008000]   174186 ms: Mark-Compact 4036.2 (4143.6) -> 4035.4 (4143.6) MB, pooled: 0 MB, 852.79 / 0.00 ms  (average mu = 0.033, current mu = 0.003) allocation failure; scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 0x10462e57c node::OOMErrorHandler(char const*, v8::OOMDetails const&) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
 2: 0x10480b768 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
 3: 0x1049e1480 v8::internal::Heap::stack() [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
 4: 0x1049f5614 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags)::$_7::operator()() const [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
 5: 0x1049f4ecc void heap::base::Stack::SetMarkerAndCallbackImpl<v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags)::$_7>(heap::base::Stack*, void*, void const*) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
 6: 0x105127044 PushAllRegistersAndIterateStack [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
 7: 0x1049df844 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
 8: 0x1049d4dd4 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
 9: 0x1049d5600 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
10: 0x1049aa760 v8::internal::FactoryBase<v8::internal::Factory>::NewRawTwoByteString(int, v8::internal::AllocationType) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
11: 0x1049b9e50 v8::internal::Factory::NewStringFromUtf8(v8::base::Vector<unsigned char const>, unibrow::Utf8Variant, v8::internal::AllocationType) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
12: 0x104827c14 v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::NewStringType, int) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
13: 0x1047216dc node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding, v8::Local<v8::Value>*) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
14: 0x104605ce8 void node::Buffer::(anonymous namespace)::StringSlice<(node::encoding)1>(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
15: 0x1051930f4 Builtins_CallApiCallbackOptimizedNoProfiling [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
16: 0x10c338a98 
17: 0x10b9cbe1c 
18: 0x10b7d7408 
19: 0x10c1245c8 
20: 0x10bf753bc 
21: 0x10c63299c 
22: 0x10c33b56c 
23: 0x10c3b46d4 
24: 0x10c3a6440 
25: 0x10c4a0884 
26: 0x10c18ea04 
27: 0x10518ec0c Builtins_JSEntryTrampoline [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
28: 0x10518e8f4 Builtins_JSEntry [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
29: 0x10493abd4 v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
30: 0x10493a14c v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
31: 0x1048218a4 v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
32: 0x10454dce0 node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context, v8::Local<v8::Value>) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
33: 0x104564b8c node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
34: 0x10471a3c8 node::StreamBase::CallJSOnreadMethod(long, v8::Local<v8::ArrayBuffer>, unsigned long, node::StreamBase::StreamBaseJSChecks) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
35: 0x10471badc node::EmitToJSStreamListener::OnStreamRead(long, uv_buf_t const&) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
36: 0x10471fd44 node::LibuvStreamWrap::OnUvRead(long, uv_buf_t const*) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
37: 0x1047204a8 node::LibuvStreamWrap::ReadStart()::$_1::__invoke(uv_stream_s*, long, uv_buf_t const*) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
38: 0x10517a97c uv__stream_io [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
39: 0x105182390 uv__io_poll [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
40: 0x105170390 uv_run [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
41: 0x10454e46c node::SpinEventLoopInternal(node::Environment*) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
42: 0x10467310c node::NodeMainInstance::Run(node::ExitCode*, node::Environment*) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
43: 0x104672ea4 node::NodeMainInstance::Run() [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
44: 0x1045f40b0 node::Start(int, char**) [/Users/hooligan/.nvm/versions/node/v22.9.0/bin/node]
45: 0x18d93c274 start [/usr/lib/dyld]

### Link to reproduction repo

this is a product size issue, so i think a large product may make more sense

**Comment by kasperkristensen** [comment]
Hi @erickirt

You mention that the admin crashes but you have added the package.json from the Next starter project to your issue, so just wanted to hear if this issue occurs in the admin dashboard or in the Next.js storefront?

**Comment by erickirt** [comment]
I apologize for my mistake. Here is the package.json for the medusajs:
```json
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "dev:debug": "node --inspect $(which npx) medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/icons": "latest",
    "@medusajs/js-sdk": "latest",
    "@medusajs/medusa": "latest",
    "@medusajs/types": "latest",
    "@medusajs/ui": "^3.0.1",
    "@medusajs/workflow-engine-redis": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "@ninja/bd": "workspace:*",
    "@opentelemetry/exporter-zipkin": "^1.26.0",
    "@opentelemetry/instrumentation-pg": "^0.44.0",
    "@opentelemetry/resources": "^1.26.0",
    "@opentelemetry/sdk-node": "^0.53.0",
    "@opentelemetry/sdk-trace-node": "^1.26.0",
    "@tanstack/react-query": "^5.59.15",
    "@tanstack/react-table": "^8.20.5",
    "@uiw/react-json-view": "2.0.0-alpha.27",
    "awilix": "^8.0.1",
    "axios": "^1.7.7",
    "pg": "^8.13.0",
    "react-i18next": "^15.1.0",
    "react-router-dom": "^6.27.0"
  },
  "devDependencies": {
    "@faker-js/faker": "^9.0.3",
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.14",
    "@types/node": "^20.16.13",
    "@types/react": "^18.3.11",
    "@types/react-dom": "^18.3.1",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.3",
    "vite": "^5.4.9"
  },
  "engines": {
    "node": ">=20"
  }
}
```

**Comment by souvrard** [comment]
Hy,

Same error for me, with 150 products in a csv file....

**Comment by erickirt** [comment]
For me the error occurs due to the size of the individual product, not many products.

**Comment by erickirt** [comment]
To be more clear, it is any large products, not one large upload. I have products that have 1000 variants.

**Comment by jkuzmanovik** [comment]
I have the same problem. I have custom module that extends the product module, and i have created workflow that creates the items. I can insert 10000 new item's without any problem. But when i try to create products like 100. Using the createProductsWorkflow. It just don't work. If i try in smaller batches it works, but again for 100 (whic its not that big) it gets stuck

**Comment by erickirt** [comment]
I want to clarify once again the my problem is not with medusa backend but with the medusa admin react. The backend works fine

**Comment by carlos-r-l-rodrigues** [comment]
Hi @erickirt, thanks for pointing it out.
We'll work on the admin to avoid overfetching product data and make it smooth even when there are many variants.

**Comment by carlos-r-l-rodrigues** [comment]
@jkuzmanovik, this is a bit unrelated and not really a bug.
The workflow to create a product is quite complex, and it creates many other related things in different modules like product, pricing, inventory, all the links, etc. At the moment it is expected that you need to process smaller batches.

**Comment by thetutlage** [comment]
@jkuzmanovik It will be great if you can create a separate issue for it. We will keep this one focused on the original (identified) issue.
