### ISSUE TITLE
babel not found!

### ISSUE THREAD

**Issue by 416d72** [medusajs/medusa#997]
Hi, I've tried deploying to heroku following the steps specified [here](https://docs.medusajs.com/how-to/deploying-on-heroku) but when I visit the app URL, I get `503` error.

After checking logs, I found this:
```js
/bin/sh: 1: /app/node_modules/.bin/babel: not found
Error: Command failed: /app/node_modules/.bin/babel src -d dist
at checkExecSyncError (child_process.js:790:11)
at execSync (child_process.js:863:15)
at /app/node_modules/@medusajs/medusa/dist/commands/develop.js:82:42
at step (/app/node_modules/@medusajs/medusa/dist/commands/develop.js:33:23)
at Object.next (/app/node_modules/@medusajs/medusa/dist/commands/develop.js:14:53)
at /app/node_modules/@medusajs/medusa/dist/commands/develop.js:8:71
at new Promise (<anonymous>)
at __awaiter (/app/node_modules/@medusajs/medusa/dist/commands/develop.js:4:12)
at default_1 (/app/node_modules/@medusajs/medusa/dist/commands/develop.js:74:12)
at /app/node_modules/@medusajs/medusa-cli/dist/create-cli.js:260:7 {
  status: 127,
  signal: null,
  output: [ null, null, null ],
  pid: 29,
  stdout: null,
  stderr: null
}
Process exited with status 0
State changed from starting to crashed
```

**Comment by olivermrbl** [comment]
Hi there @416d72! 

I just tried to out the flow in the guide, and couldn't reproduce the issues you are facing.

Can I get you to try once again from the start? The steps regarding the Node.js Heroku build pack and the extra couple of scripts for `package.json` is especially important.

Alternatively, if you have a repo, I could try it out using that?

Let me know! 😊

**Comment by 416d72** [comment]
I deleted the app, remade it again and the issue is gone now.
Surely I missed something in the first try!
