### ISSUE TITLE
Medusa v2 Documentation: Issue in 5.8.5. Workflow Hooks - Medusa v2 Documentation

### ISSUE THREAD

**Issue by martinerko** [medusajs/medusa#9971]
### What Medusa version and documentation are you using?

None

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Typos in the code snippets

### How can this issue be resolved?

1. fixing the code snippet

Replace 
```ts
import { createProductsWorkflow } from "@medusajs/medusa/core-flows"

createProductsWorkflow.productCreated(
  async ({ productId }, { container }) => {
    // TODO perform an action

    return new StepResponse(undefined, { ids })
  },
  async ({ ids }, { container }) => {
    // undo the performed action
  }
)
```

with

```ts
import { createProductsWorkflow } from "@medusajs/medusa/core-flows"

createProductsWorkflow.hooks.productCreated(
  async ({ products }, { container }) => {
    // TODO perform an action

    return new StepResponse(undefined, { ids })
  },
  async ({ ids }, { container }) => {
    // undo the performed action
  }
)
```

...

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
Nice catch! Will open a PR to fix it.
