### ISSUE TITLE
[Bug]: It's not possible anymore to list product and filter by metadata

### ISSUE THREAD

**Issue by Ketlark** [medusajs/medusa#9975]
### Package.json file

```JSON
{
  "name": "mullo-backend",
  "version": "1.0.0",
  "private": true,
  "type": "module",
  "license": "UNLICENSED",
  "scripts": {
    "start": "node bin/server.js",
    "build": "node ace build",
    "dev": "node ace serve --hmr",
    "test": "node ace test",
    "lint": "eslint .",
    "format": "prettier --write .",
    "typecheck": "tsc --noEmit",
    "email": "email dev --dir=app/modules/notifications/infrastructure/templates"
  },
  "imports": {
    "#controllers/*": "./app/controllers/*.js",
    "#exceptions/*": "./app/exceptions/*.js",
    "#models/*": "./app/models/*.js",
    "#mails/*": "./app/mails/*.js",
    "#services/*": "./app/services/*.js",
    "#listeners/*": "./app/listeners/*.js",
    "#events/*": "./app/events/*.js",
    "#middleware/*": "./app/middleware/*.js",
    "#validators/*": "./app/validators/*.js",
    "#providers/*": "./providers/*.js",
    "#policies/*": "./app/policies/*.js",
    "#abilities/*": "./app/abilities/*.js",
    "#database/*": "./database/*.js",
    "#start/*": "./start/*.js",
    "#tests/*": "./tests/*.js",
    "#config/*": "./config/*.js",
    "#addresses/*": "./app/modules/addresses/*.js",
    "#users/*": "./app/modules/users/*.js",
    "#organizations/*": "./app/modules/organizations/*.js",
    "#products/*": "./app/modules/products/*.js",
    "#webhooks/*": "./app/modules/webhooks/*.js",
    "#crm/*": "./app/modules/crm/*.js",
    "#orders/*": "./app/modules/orders/*.js"
  },
  "devDependencies": {
    "@adonisjs/assembler": "^7.5.2",
    "@adonisjs/eslint-config": "^1.3.0",
    "@adonisjs/prettier-config": "^1.3.0",
    "@adonisjs/tsconfig": "^1.3.0",
    "@japa/api-client": "^2.0.3",
    "@japa/assert": "^3.0.0",
    "@japa/plugin-adonisjs": "^3.0.1",
    "@japa/runner": "^3.1.4",
    "@react-email/components": "^0.0.22",
    "@swc/core": "^1.5.3",
    "@types/luxon": "^3.4.2",
    "@types/node": "^20.12.10",
    "@types/react": "^18.3.3",
    "eslint": "^8.57.0",
    "hot-hook": "^0.2.5",
    "pino-pretty": "^11.0.0",
    "prettier": "^3.2.5",
    "react": "^18.3.1",
    "react-email": "^2.1.6",
    "ts-node": "^10.9.2",
    "typescript": "5.6.3"
  },
  "dependencies": {
    "@adonisjs/auth": "^9.2.1",
    "@adonisjs/core": "^6.12.1",
    "@adonisjs/cors": "^2.2.1",
    "@adonisjs/lucid": "^20.6.0",
    "@clerk/backend": "1.13.8",
    "@vinejs/vine": "2.1.0",
    "got": "^14.4.2",
    "luxon": "^3.4.4",
    "neverthrow": "^6.2.1",
    "pg": "^8.12.0",
    "reflect-metadata": "^0.2.2",
    "resend": "^3.5.0",
    "ulid": "^2.3.0"
  },
  "hotHook": {
    "boundaries": [
      "./app/controllers/**/*.ts",
      "./app/middleware/*.ts"
    ]
  },
  "eslintConfig": {
    "extends": "@adonisjs/eslint-config/app"
  },
  "prettier": "@adonisjs/prettier-config"
}
```

### Node.js version

v20

### Database and its version

Postgres 14

### Operating system name and version

Debian

### What happended?

It's not possible anymore to list product and filter by metadata like we could in V1, documentation doesn't have the same params than before in V1

### Expected behavior

we should have the possibility to sort by metadata

### Actual behavior

Sorting by metadata is not possible

### Link to reproduction repo

https://github.com/mullo-dev/backend

**Comment by thetutlage** [comment]
Hello @Ketlark 

Can you please share which API are you using to filter products? Sharing a code example will be great

**Comment by thetutlage** [comment]
I'll close the issue for now. But don't hesitate to reopen it once you share more info. Always happy to help

**Comment by aerskine-resonance** [comment]
i am trying to filter the /store/products https://docs.medusajs.com/api/store#products_getproducts endpoint by metadata (or by a linked module) and am having trouble figuring that out and I think this is the same issue as originally mentioned. 

@thetutlage do you have any guidance? i'm having trouble figuring out from the docs how this is recommended to be done

**Comment by SanjayDevTech** [comment]
@thetutlage Can you confirm will this work?

**Comment by SanjayDevTech** [comment]
@aerskine-resonance can you reopen this issue

**Comment by NicolasGorga** [comment]
Hello @thetutlage I think i am having an issue related to this, how can we pass a new property to the query params to validate of a core route? For example, i created an attributes module and i would like to call /store/products?attributes=ids

I haven't found anywhere in the docs nor in the code any indication of how to do this, which makes me think it is not possible. Is this the case? If so, is there any hacky workaround, as i think this is very much needed? Otherwise any link to a core entity is unusable in terms of filtering for core GET endpoints.

Something similar to additionalDataValidator for core POST routes
