### ISSUE TITLE
[Bug]: Quickstart guid link is pointing for Not Found page

### ISSUE THREAD

**Issue by ambigos1** [medusajs/medusa#9978]
### Package.json file

```JSON
Hi.
The Quickstart guide is linking to a non existing page:
https://docs.medusajs.com/create-medusa-app
```

### Node.js version

20

### Database and its version

16.5

### Operating system name and version

windows

### Browser name

chrome

### What happended?

Hi.
The Quickstart guide is linking to a non existing page:
https://docs.medusajs.com/create-medusa-app

### Expected behavior

get to v2 quickstart guid page

### Actual behavior

page not fount

### Link to reproduction repo

goto: https://docs.medusajs.com/create-medusa-app

**Comment by thetutlage** [comment]
Hello 👋 

Can you please share where on the website you found this link? A screenshot will be helpful

**Comment by ambigos1** [comment]
page: https://github.com/medusajs/medusa
![image](https://github.com/user-attachments/assets/d77af2b9-4fc6-4e4d-8180-e96879ab8e58)

@thetutlage

**Comment by thetutlage** [comment]
Ohh thanks. Its with the Github README

**Comment by thetutlage** [comment]
Duplicate of https://github.com/medusajs/medusa/issues/9858

**Comment by thetutlage** [comment]
Fixed in https://github.com/medusajs/medusa/pull/9860

**Comment by ambigos1** [comment]
@thetutlage 
Hi
more links with not-found errors
at: https://docs.medusajs.com/learn/customization/extend-models/query-linked-records
Prerequisites links do not exists

[Brand Module↗](https://docs.medusajs.com/customization/custom-features/module)
[Defined link between the Brand and Product data models.↗](https://docs.medusajs.com/customization/extend-models/define-link)

![image](https://github.com/user-attachments/assets/4796c9e5-08af-4997-8834-4354fc740f04)

**Comment by shahednasser** [comment]
Nice catch @ambigos1 ! Will open a PR to fix those

**Comment by ambigos1** [comment]
no problem.
I used a nice tool that catches broken links.
and I found on Medusa domain 190 broken links
https://brokenlinkcheck.com/broken-links.php

another tool i found: https://www.drlinkcheck.com/

![image](https://github.com/user-attachments/assets/f1b36264-9343-4d77-8772-4f3e425ffed6)

**Comment by ambigos1** [comment]
and you can use the following tool to catch all broken links under the docs subdomain
found 89 more broken links
https://www.drlinkcheck.com/

**Comment by shahednasser** [comment]
Thanks for sharing! A lot of those are actually because of a big change in paths we had recently, mainly where we moved all v1 docs to https://docs.medusajs.com/v1, so it's not possible to fix all of these.
