### ISSUE TITLE
Where I can find or infer relations names for every already created entity on medusa backend?

### ISSUE THREAD

**Issue by DiegoRam** [medusajs/medusa#9981]
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

It's too hard to infer what are all relation for a entity.
IE: Orders
I was able to infer `items` and `shipping_addres` but what about payment method? I've tried `payment_collections` but it gives an error like: Order entity does not have payment_collections which is not true

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

**Comment by thetutlage** [comment]
Hello @DiegoRam 

Can you please provide a bit more information of what exactly you are trying to achieve? What code you have written to infer the `items` and `shipping_address`?

**Comment by DiegoRam** [comment]
HI @thetutlage , sure thing.

`let order = await orderService.retrieveOrder(data.id, {
        relations: ["items", "shipping_address", "payment_collections"],
        select: ["total", "discount_total", "shipping_total", "status", "customer_id"]
      })`

Please notice that I'm looking for payment method 
and error thrown tells me that Order entity does not have a property "payment_collections"

**Comment by thetutlage** [comment]
Hello 👋

You should be using the query engine to fetch relationships that are defined via links. This is because, modules cannot reach out to other modules directly. In your case, the `order` module has no direct relationship with the `payment_collection`, the relationship is formed via a link.

Here's an example of how to use the query engine.

```ts
const query = req.scope.resolve('query')
const orders = await query.graph({
  entity: 'order',
  fields: ['payment_collections.*']
})
```

**Comment by DiegoRam** [comment]
Hey @thetutlage It's worked thanks.
