### ISSUE TITLE
[Bug]: Broken validation / Unexpected behavior in order fulfillment workflows

### ISSUE THREAD

**Issue by turacma** [medusajs/medusa#9982]
### Package.json file

```JSON
{
  "name": "ship",
  "version": "0.0.1",
  "description": "SHIP for Eight Sleep",
  "author": "Eight Sleep",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "2.0.2",
    "@medusajs/api-key": "2.0.2",
    "@medusajs/auth": "2.0.2",
    "@medusajs/auth-emailpass": "2.0.2",
    "@medusajs/cache-inmemory": "2.0.2",
    "@medusajs/cart": "2.0.2",
    "@medusajs/cli": "2.0.2",
    "@medusajs/currency": "2.0.2",
    "@medusajs/customer": "2.0.2",
    "@medusajs/event-bus-local": "2.0.2",
    "@medusajs/event-bus-redis": "2.0.2",
    "@medusajs/framework": "2.0.2",
    "@medusajs/file": "2.0.2",
    "@medusajs/file-local": "2.0.2",
    "@medusajs/fulfillment": "2.0.2",
    "@medusajs/fulfillment-manual": "2.0.2",
    "@medusajs/inventory": "2.0.2",
    "@medusajs/js-sdk": "^2.0.2",
    "@medusajs/medusa": "2.0.2",
    "@medusajs/notification": "2.0.2",
    "@medusajs/notification-local": "2.0.2",
    "@medusajs/order": "2.0.2",
    "@medusajs/payment": "2.0.2",
    "@medusajs/pricing": "2.0.2",
    "@medusajs/product": "2.0.2",
    "@medusajs/promotion": "2.0.2",
    "@medusajs/region": "2.0.2",
    "@medusajs/sales-channel": "2.0.2",
    "@medusajs/stock-location": "2.0.2",
    "@medusajs/store": "2.0.2",
    "@medusajs/tax": "2.0.2",
    "@medusajs/types": "2.0.2",
    "@medusajs/user": "2.0.2",
    "@medusajs/workflow-engine-inmemory": "2.0.2",
    "express": "^4.21.1",
    "stripe": "^17.3.1"
  },
  "devDependencies": {
    "@mikro-orm/cli": "5.9.7",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "@stdlib/number-float64-base-normalize": "0.2.3",
    "@swc/core": "1.9.1",
    "@swc/jest": "^0.2.37",
    "@types/express": "^5.0.0",
    "@types/jest": "^29.5.14",
    "@types/node": "^22.9.0",
    "@types/react": "^18.3.12",
    "jest": "^29.7.0",
    "@medusajs/test-utils": "2.0.2",
    "prop-types": "^15.8.1",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.3"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v20.15.0

### Database and its version

Aurora Postgres

### Operating system name and version

Mac OS X 15.0.1 (24A348)

### What happended?

It is possible to create an order with an empty `shipping_methods` array:

```
const order = (await createOrdersWorkflow(req.scope).run({
        input: {
          status: "draft",
          email: email,
          region_id: region_id,
          promo_codes: [],
          currency_code: currency,
          shipping_methods: [],
          items: items,
        }
      })).result;
```

You can then create a fulfillment for that order:

```
const fulfillmnet = (await createOrderFulfillmentWorkflow(container).run({
            input: {
                location_id: location.id,
                order_id: order.id,
                items: fulfilledItems,
            }
        })).result;
```

The location does not have any association with a fulfillment provider or service zone

The fulfillment will be created with a fulfillment provider even though nothing in the order or fulfillment is associated with that provider.

### Expected behavior

1. Probably shouldn't allow orders to be created without shipping methods
2. If it doesn't fail at order creation time, it should definitely fail at fulfillment time as no provider should be able to be determined.

### Actual behavior

1. Order is created
2. Fulfillment is created (as long as there is at least one shipping option in the DB)

### Link to reproduction repo

See above for minimal code, requires particular state in DB

**Comment by turacma** [comment]
FWIW, this seems to be the source of the second issue:

https://github.com/medusajs/medusa/blob/af9eec73df6c8a30fe71de8b8c3a3444962df1ca/packages/core/core-flows/src/order/workflows/create-fulfillment.ts#L283

If `shippingOptionId` is undefined, the remote query does essentially a "select *" on shipping options and returns the first match.

Probably should throw there if it's undefined

May also want to consider throwing here:

https://github.com/medusajs/medusa/blob/af9eec73df6c8a30fe71de8b8c3a3444962df1ca/packages/core/core-flows/src/common/steps/use-remote-query.ts#L166

When list is `false` and there's more than one result.

**Comment by turacma** [comment]
It would also be useful if `createOrderFulfillmentWorkflow` could allow `providerId` to be supplied as an override option, similar to how the location can be overridden or inferred. Without this, you wouldn't be able to create fulfillment with different providers as `createOrderFulfillmentWorkflow` only takes the first on the order.

**Comment by olivermrbl** [comment]
@turacma, thanks for the report.

> 1. Probably shouldn't allow orders to be created without shipping methods

It should be possible to create orders without shipping methods. For example, imagine selling digital products that don't require physical shipping. These products would be "delivered" as a license key (or similar) sent to the customer's email inbox. 

That said, I realize we currently lack a validation check in the checkout flow. If some items require shipping, customers can still complete their cart without selecting a shipping method. I've created an internal issue, and we'll address this in the near future.

Regarding your other comments:

> If shippingOptionId is undefined, the remote query does essentially a "select *" on shipping options and returns the first match. Probably should throw there if it's undefined

Related to my comment above, you should be able to create a fulfillment without a shipping option. We shouldn't throw if this is not provided, but we should indeed fix the issue with picking the first found shipping option, as it would otherwise lead to unintended results.

> It would also be useful if createOrderFulfillmentWorkflow could allow providerId to be supplied as an override option, similar to how the location can be overridden or inferred. Without this, you wouldn't be able to create fulfillment with different providers as createOrderFulfillmentWorkflow only takes the first on the order.

Good catch, this should definitely be possible. We should allow you to specify specific shipping option as part of creating the fulfillment. We will tackle this in the near future.

**Comment by turacma** [comment]
@olivermrbl Did the update for selecting the shipping option / provider as part of the fulfillment ever get actioned?

**Comment by olivermrbl** [comment]
> @olivermrbl Did the update for selecting the shipping option / provider as part of the fulfillment ever get actioned?

@turacma, not yet. This is on the roadmap, and I hope we can tackle within this month or the next.

**Comment by fPolic** [comment]
Hey @turacma, we will publish a release today that contains a few changes relevant to the discussion above.
Now, an (override) shipping option can be passed when creating a fulfillment. Also, validation is improved so a cart requires a shipping method if there are items that require shipping.
